[AC-2508][AC-2511] member access report view and export logic
bitwarden/clients pull request #10011
Opened 2024-07-08 10:58 UTC by aj-rosado

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/AC-2508
https://bitwarden.atlassian.net/browse/AC-2511

## 📔 Objective

- **Report-utils.ts:** Added generic report functionalities that were necessary to build this report and can be reused in future reports.
- **Member-access-report.service.ts** Added specific service for member access report that will get the data and transform it into the desired type
- Added models and views that will support the data for the reports. Same model will be used for export and view.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-07-08 14:45 UTC, audreyality requested changes
⚠️ - requested change

Everything else is curiosity and/or optional.

2024-07-08 14:45 UTC, audreyality commented on apps/web/src/app/tools/reports/report-utils.ts
> +export function aggregateProperty<T, K extends keyof T, V>(array: T[], property: K): V[] {
⛏️ This function doesn't aggregate; it collects. (Aggregates are typicall reduced values.)
🤔 The presence of `unknown` leads me to believe that the type of this method are incorrect. It should be possible for `array[i][property]` to be typechecked by the function definition. If that proves to difficult, then consider restructuring the function so that it can be typechecked.

2024-07-08 14:45 UTC, audreyality commented on apps/web/src/app/tools/reports/report-utils.ts
> +  });
🎨 Avoid `forEach` unless you have a really good reason to use it. 

* `for(...of)` handles enumeration using a generator, which for an array maps to the same operator.
* When transforming arrays, functions like `map`, `reduce`, `flat` and so forth can be used for array computation with less code (and usually better performance).


```javascript
// here's your forEach loop using array's collection functions
const aggregated: V[] = array.map(i => i[property]).filter(Array.isArray).flat();
```

2024-07-08 14:45 UTC, audreyality commented on apps/web/src/app/tools/reports/report-utils.ts
> +}
🎨 Seems like this is unnecessarily complex. Consider limiting it to CSV only, and invoking the `fileDownloadService` at the CSV callsite. That way, if you want to (say) write it to disk you can still reuse the export logic.

```javascript
fileDownloadService.download({
  fileName: filename,
  blobData: toCsv(data, headers),
  blobOptions: { type: "text/plain" },
});

// `fileSaveService` is hypothetical
fileSaveService.save({
  path: path,
  blobData: toCsv(data, headers)
});
```

2024-07-08 14:45 UTC, audreyality commented on apps/web/src/app/tools/reports/report-utils.ts
👍🏻 Loving the documentation and unit tests

2024-07-08 14:45 UTC, audreyality commented on bitwarden_license/bit-web/src/app/tools/reports/member-access-report/member-access-report.component.ts
> +import { ExportHelper } from "../../../../../../../libs/tools/export/vault-export/vault-export-core/src/services/export-helper";
❓ Should this header use `@bitwarden/...`? If not, why?

2024-07-08 14:45 UTC, audreyality commented on bitwarden_license/bit-web/src/app/tools/reports/member-access-report/member-access-report.component.ts
> +    this.dataSource.data = this.reportService.generateMemberAccessReportView();
🤔 Seems like this method should have arguments.

2024-07-08 14:45 UTC, audreyality commented on bitwarden_license/bit-web/src/app/tools/reports/member-access-report/services/member-access-report.service.ts
> +  }
⚠️ Seems like there needs to be some indirection here. Consider injecting a dependency that provides the data, then mock that dependency to return the data in `memberAccessReportsMock`. That way, your test can specify the mocked data and you won't need to rewrite it once the actual data can be sourced.

2024-07-08 14:45 UTC, audreyality commented on bitwarden_license/bit-web/src/app/tools/reports/member-access-report/view/member-access-export.view.ts
> +export const userReportItemHeaders: { [key in keyof MemberAccessExportItem]: string } = {
💭 Keep in mind that `{ [key in keyof MemberAccessExportItem]: string }` might be a good thing to generalize when writing a future report. 😄

2024-07-09 18:03 UTC, aj-rosado commented on apps/web/src/app/tools/reports/report-utils.ts
> +export function aggregateProperty<T, K extends keyof T, V>(array: T[], property: K): V[] {
Could not find a proper way to typecheck this as we are using complex types as objects. 
Could properly check for primitive types but for objects could only check if it was an object and that would not provided enough utility

Probably allowing the user to pass as parameter a comparator to be used when validating the data would work, I'm open to suggestions

2024-07-09 18:04 UTC, aj-rosado commented on bitwarden_license/bit-web/src/app/tools/reports/member-access-report/member-access-report.component.ts
> +    this.dataSource.data = this.reportService.generateMemberAccessReportView();
It doesn't need to decrypt anything so doesn't need the `OrganizationId`, might need it in the future for the API call or are you referring to something else?

2024-07-09 18:08 UTC, audreyality commented on bitwarden_license/bit-web/src/app/tools/reports/member-access-report/member-access-report.component.ts
> +    this.dataSource.data = this.reportService.generateMemberAccessReportView();
it just seems odd that you'd set the organization id but not use it.

2024-07-09 18:16 UTC, audreyality commented on apps/web/src/app/tools/reports/report-utils.ts
> +export function aggregateProperty<T, K extends keyof T, V>(array: T[], property: K): V[] {
I think a validator might do to much for something that's a utility. I think the real issue I'm seeing is that I'm thinking of composability in terms of operators ("the functions I pass in to map/reduce/etc"). You're thinking of it in terms of processing steps ("first gather the data from this column, now add it all together").

2024-07-09 18:19 UTC, audreyality approved these changes

2024-07-09 18:23 UTC, audreyality commented on bitwarden_license/bit-web/src/app/tools/reports/member-access-report/services/member-access-report.service.ts
> +  }
I'm not much a fan of "spyOn" mocks. They're brittle to refactoring. But that reservation isn't enough to block the review.

2024-07-11 10:38 UTC, aj-rosado commented on bitwarden_license/bit-web/src/app/tools/reports/member-access-report/services/member-access-report.service.ts
> +  }
Never thought about that regarding the spyOn and it makes sense. In this case we can easily avoid that issue so I just created a new api service to have the call, like we have on other places.

2024-07-11 14:13 UTC, audreyality approved these changes

2024-07-11 16:11 UTC, merged