[PM-9422] generator engine
bitwarden/clients pull request #10032
Opened 2024-07-09 14:03 UTC by audreyality

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-9422

## 📔 Objective

* Factor generation algorithms into engines. This is to allow services to use these algorithms without the policy or saved settings required for the password generator screens.
* Add unit tests for generation algorithms.

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-07-10 19:10 UTC, djsmith85 requested changes
@audreyality Really nice job with this.

Some comments here and there, but mostly questions, ask for renames, removal of magic strings/numbers

2024-07-10 19:10 UTC, djsmith85 commented on libs/tools/generator/core/src/strategies/eff-username-generator-strategy.ts
> +    const digits = options.wordIncludeNumber ?? DefaultEffUsernameOptions.wordIncludeNumber ? 4 : 0;
❓ Is 4 the default number of digits being appended?
🎨  Please move the definition of this magic number elsewhere.

2024-07-10 19:10 UTC, djsmith85 commented on libs/tools/generator/core/src/engine/email-calculator.ts
> +  concatenate(username: string, domain: string) {
❓  It says that a username is passed in, but in the current usages we pass in the website-name?

2024-07-10 19:26 UTC, audreyality commented on libs/tools/generator/core/src/engine/types.ts
> +  all: number;
I think this is a documentation problem. It's the number of characters selecting from all groups. Length can then be calculated by just adding the numbers together. This is desirable because it avoids dependencies among the fields, and makes every one of them work in a self-similar way.

```
// Total length computation is straightforward
const length = Object.values(request).filter(v => v > 0).reduce(sum, 0);

// And it means that you don't run into this pickle:
const whichOneIsWrong = {
  length: 5,
  uppercase: 5,
  number: 1,
};
```

2024-07-10 19:44 UTC, audreyality commented on libs/tools/generator/core/src/engine/email-randomizer.ts
> +  async randomAsciiSubaddress(email: string, options?: { length?: number }) {
Only those whose argument lists get too long. All of the types you see originally started as primitives like `randomAsciiSubaddress`.

2024-07-10 19:54 UTC, audreyality commented on libs/tools/generator/core/src/strategies/passphrase-generator-strategy.ts
> +      words: requestWords >= 3 ? requestWords : DefaultPassphraseGenerationOptions.numWords,
> Is 3 our min number of words or where does this restriction come from?

It's here because it existed in the prior version (line 37). I didn't question it; just implemented it.

> Checking and switching to defaults is currently an untested branch within the unit-tests

It's unlikely to matter. The strategies are largely legacy code. They'll be replaced with configurations and providers in the final design.

2024-07-10 19:56 UTC, audreyality commented on libs/tools/generator/core/src/strategies/eff-username-generator-strategy.ts
> +    const digits = options.wordIncludeNumber ?? DefaultEffUsernameOptions.wordIncludeNumber ? 4 : 0;
Yes. This is another case of a magic number in the original logic that I kept around for compatibility purposes.

2024-07-10 20:00 UTC, audreyality commented on libs/tools/generator/core/src/engine/email-calculator.ts
> +  concatenate(username: string, domain: string) {
This is referring to the parts of an email: `username+subaddress@domain`.

The docs also mention this:
> the username part of the email address

The idea here is to communicate that this can work with any data. The password generator happens to pass in the website name, but another part of the application could pass in something else entirely. Perhaps there's a way to state this more clearly.

2024-07-11 18:48 UTC, audreyality commented on libs/tools/generator/core/src/strategies/password-generator-strategy.ts
> +    function process(
Addressed in 9e400de7d2.

2024-07-11 19:00 UTC, audreyality commented on libs/tools/generator/core/src/strategies/passphrase-generator-strategy.ts
> +      words: requestWords >= 3 ? requestWords : DefaultPassphraseGenerationOptions.numWords,
Addressed in 3356668265a2e.

2024-07-11 19:08 UTC, audreyality commented on libs/tools/generator/core/src/engine/types.ts
> +  length?: number;
addressed in 9e400de7d2d

2024-07-11 19:09 UTC, audreyality commented on libs/tools/generator/core/src/engine/username-randomizer.ts
> +  async randomWords(options?: WordsRequest) {
Addressed in f235240cad4.

2024-07-11 19:13 UTC, audreyality commented on libs/tools/generator/core/src/engine/email-randomizer.ts
> +    const length = options?.length ?? 1;
Addressed in 9e400de7d2.

2024-07-18 15:17 UTC, djsmith85 requested changes

2024-07-18 15:17 UTC, djsmith85 commented on libs/tools/generator/core/src/data/username-digits.ts
> +  disabled: 6,
❓ Shouldn't this be zero? This is a change of behaviour over the previous -
https://github.com/bitwarden/clients/pull/10032/commits/b88e6a3b354c909277302207f26e980004d189ac#diff-f7e01db40beee98b0439cb0199cf7ddc01418e756c7101f27ad71d536363b47aL38-R41

I think that is also the reason for the failing tests.

2024-07-18 15:28 UTC, audreyality commented on libs/tools/generator/core/src/engine/username-randomizer.ts
> +    const length = request?.numberOfWords ?? 1;
Addressed in d75b90daef93566.

2024-07-18 15:28 UTC, audreyality commented on libs/tools/generator/core/src/engine/email-randomizer.ts
> +    const length = options?.numberOfWords ?? 1;
Addressed in d75b90daef93566.

2024-07-18 15:30 UTC, audreyality commented on libs/tools/generator/core/src/data/username-digits.ts
> +  disabled: 6,
The tests were failing because the `numberOfWords` rename wasn't applied to the unit tests. (Why are we even using typescript if a basic refactor like rename misses these things... 🙄)

Fixing the zero is addressed in 73bf6a3.
Broken tests addressed in d75b90daef9.

2024-07-18 15:37 UTC, djsmith85 approved these changes
Awesome work on this! Thank you!

2024-07-19 20:34 UTC, merged