[CL-285] Add default loading state to popup-page
bitwarden/clients pull request #10040
Opened 2024-07-09 20:23 UTC by vleague2

## 🎟️ Tracking

[CL-285](https://bitwarden.atlassian.net/browse/CL-285)

## 📔 Objective

This PR adds an accessible loading state to the `popup-page`. It also reduces some boilerplate code in the stories file.

## 📸 Screenshots

Click on the "Storybook Publish" action and view the Browser > Popup Layout "Loading" story.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-07-09 21:34 UTC, willmartian requested changes

2024-07-09 21:34 UTC, willmartian commented on apps/browser/src/platform/popup/layout/popup-page.component.html
> +  </span>
What is the expected screen reader functionality when interacting with this component?

2024-07-09 21:34 UTC, willmartian commented on apps/browser/src/platform/popup/layout/popup-page.component.ts
> +  constructor(protected i18nService: I18nService) {}
We should default to using the newer `inject` function vs constructor injection

2024-07-09 21:34 UTC, willmartian commented on apps/browser/src/platform/popup/layout/popup-page.component.ts
> +    this.loadingText = this.loadingText ?? this.i18nService.t("loading");
I believe we can just make this the default value when declaring the property.

2024-07-09 21:34 UTC, willmartian commented on apps/browser/src/platform/popup/layout/popup-page.component.html
> +  [ngClass]="loading ? 'tw-bg-black/30' : 'tw-bg-background-alt'"
There was a miscommunication regarding the desired end behavior here. We can just use `tw-bg-background-alt`

2024-07-12 14:43 UTC, vleague2 commented on apps/browser/src/platform/popup/layout/popup-page.component.html
> +  </span>
After much discussion, we have decided to go with a simple aria-label on the spinner for now, and defer further accessibility implementation to another ticket.

2024-07-12 14:47 UTC, willmartian commented on apps/browser/src/platform/popup/layout/popup-page.component.ts
> +  @Input() loadingText?: string = this.i18nService.t("loading");
Do you think adding the ability to customize this now is still necessary if we are revisiting in the future?

2024-07-12 14:51 UTC, vleague2 commented on apps/browser/src/platform/popup/layout/popup-page.component.ts
> +  @Input() loadingText?: string = this.i18nService.t("loading");
Maybe not necessary, but if we don't end up returning to this accessibility work in the near future, I think it'd be nice to have the ability to customize it for design in the meantime.

2024-07-12 14:54 UTC, willmartian approved these changes
LGTM :shipit:

2024-07-12 14:54 UTC, willmartian commented on apps/browser/src/_locales/en/messages.json
> +    "message": "Loading"
Surprised we didn't already have this...

2024-07-12 18:32 UTC, vleague2 commented on apps/browser/src/_locales/en/messages.json
> +    "message": "Loading"
I saw it in the web app but not in browser :(

2024-07-12 20:09 UTC, danielleflinn approved these changes

2024-07-15 16:57 UTC, willmartian approved these changes

2024-07-15 18:29 UTC, merged