[AC-2520] Remove Unassigned Items Banner
bitwarden/clients pull request #10042
Opened 2024-07-09 20:50 UTC by vincentsalucci

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/AC-2520

## 📔 Objective

> Remove all `Unassigned Items Banner` code

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-07-09 20:57 UTC, shane-melton approved these changes
Vault change looks good!

2024-07-09 21:13 UTC, willmartian approved these changes

2024-07-10 01:02 UTC, eliykat requested changes
Looks good, just gotta make sure we clean up our data on the way out 🧹

2024-07-10 01:02 UTC, eliykat commented on libs/common/src/platform/state/state-definitions.ts
> -
We need a data migration to remove this data at the same time as removing the StateDefinition.

See [this Slack conversation](https://bitwarden.slack.com/archives/C02LPDKPML6/p1712719872504199) for previous discussion on how to do this.

So you'll need to write a `Migrator` subclass in `libs/common/src/state-migrations/migrations` which gets that accounts object and removes this key from it.

2024-07-11 15:00 UTC, vincentsalucci commented on libs/common/src/platform/state/state-definitions.ts
> -
Thanks for the reminder. I've reverted this change and will create a follow-up PR with the state-definition removal/migration.

2024-07-11 15:02 UTC, vincentsalucci commented
@eliykat @willmartian @shane-melton : Reverted a change that is not relevant to your prior reviews 👍

2024-07-11 15:52 UTC, shane-melton approved these changes

2024-07-11 19:10 UTC, willmartian approved these changes

2024-07-11 20:23 UTC, eliykat approved these changes

2024-07-12 16:06 UTC, merged