[PM-8803] Edit Custom Fields
bitwarden/clients pull request #10054
Opened 2024-07-10 16:35 UTC by nick-livefront

Stacked on top of @shane-melton's https://github.com/bitwarden/clients/pull/9928

## 🎟️ Tracking

[PM-8803](https://bitwarden.atlassian.net/browse/PM-8803)

## 📔 Objective

Adding the ability to add custom fields to a cipher.

#### High level changes/features:
- Added Custom Fields component that includes both the display of current custom fields and "add field" button
  - This possibly could be pulled into multiple components so the same component doesn't have to be used in both places within the "Additional Options" section.
  -  The "work in progress" ciphers is needed to populate the initial values
- A custom field can be edited inline to update the value and within the dialog for the label.
- Generic integration with `CipherFormContainer`

#### Accessibility related changes

- When a new custom field is added, the input is focused.
  - The announcement of the field here was a little tricky, the only way I could get consistent results is when the input is focused after the announcement.
- The up/down arrows will move an item up or down respectively. 
  - I opted to not pull this into a directive for now mostly because the code imprint was so small.

#### Tailwind

- I noticed some of my tailwind styles weren't being applied, I had to edit the tailwind config to pull in our components from the vault folder. We must have been using already included styles up until now 🫨 

## 📸 Screenshots

|Adding Values|Screen Reader - moving values|
|-|-|
|<video src="https://github.com/bitwarden/clients/assets/125900171/1579b074-7d42-4a7c-9a56-3e4de9f338b0" />|<video src="https://github.com/bitwarden/clients/assets/125900171/63679cef-16f4-42b2-bf1c-2810d17380e4" />|

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-07-10 17:51 UTC, shane-melton reviewed
This is looking great! I'm still reviewing, but wanted to get this comment out there to get your thoughts early on. Let me know what you think!

2024-07-10 17:51 UTC, shane-melton commented on libs/vault/src/cipher-form/components/additional-options/additional-options-section.component.ts
> +  @Input({ required: true }) updatedCipherView: CipherView | null = null;
💭 I'm hesitant to start passing around the `updatedCipherView` to the child form components. I feel it starts to break the contract provided by `CipherFormContainer` and introduces multiple sources of truth (the form groups and now this view) for the current state of the form component for the children and will become tricky to keep straight.

What if we made the `CustomFieldComponent` expose a `hasFields()` getter that we could use to show/hide the "+ Add Field" button here? It could also expose an `addField()` method that the button would trigger and would open the dialog within the `CustomFieldComponent`. 

I believe this would let us get around the need for the  `updatedCipherView` and the `ngDoCheck` stuff below. What do you think?

2024-07-10 18:08 UTC, nick-livefront commented on libs/vault/src/cipher-form/components/additional-options/additional-options-section.component.ts
> +  @Input({ required: true }) updatedCipherView: CipherView | null = null;
I'm glad you had some ideas! I think I got stuck on the single train of thought I was on and kept rolling with it. 

I like the idea to expose the logic directly from `CustomFieldComponent`. I'll ponder the implementation but in the meantime keep going with the review and I can field that as it comes in

2024-07-10 19:13 UTC, shane-melton requested changes
Looks really good, and nice job on getting the drag/drop and arrow key functionality working! I added a few more questions and minor suggestions/nits. 

There is also one weird issue with regards to interacting with ciphers that have their password fields hidden that we'll need to address.

2024-07-10 19:13 UTC, shane-melton commented on libs/vault/src/cipher-form/components/custom-fields/custom-fields.component.html
> +          <button
⚠️ If we're editing an existing cipher and it does not have `viewPassword` flag set to `true` then we need to hide this password toggle button and disable the input for existing hidden custom fields. However, if the user is **editing** a cipher that has `viewPassword == false` then we need to allow the toggle for newly added hidden fields so they can see what they're adding. (this comes from the `Edit, except passwords` collection permission)

Admittedly this is a weird scenario because, upon saving the field, the user will then lose visibility into the custom hidden field they just added 🙃. But, from what I can tell, this is how the [current custom fields behave](https://github.com/bitwarden/clients/blob/3f0f5af26a6b98941ec6af269afefe1a3699bfee/apps/web/src/app/vault/individual-vault/add-edit-custom-fields.component.html#L82).

2024-07-10 19:13 UTC, shane-melton commented on libs/vault/src/cipher-form/components/custom-fields/custom-fields.component.ts
> +  async handleKeyDown(event: KeyboardEvent, label: string, index: number) {
👍 Nice job on getting this working!

2024-07-10 19:23 UTC, shane-melton commented on libs/vault/src/cipher-form/components/custom-fields/custom-fields.component.html
> +          <button
Also, just an fyi, I have found that hiding the password toggle button is non-trivial with the `bitPasswordInputToggle` directive and have a potential fix for that in my work on [PM-8524](https://github.com/bitwarden/clients/blob/3f0f5af26a6b98941ec6af269afefe1a3699bfee/apps/web/src/app/vault/individual-vault/add-edit-custom-fields.component.html#L82)

2024-07-11 18:27 UTC, nick-livefront commented on libs/vault/src/cipher-form/components/custom-fields/add-edit-custom-field-dialog/add-edit-custom-field-dialog.component.html
> +          *ngFor="let type of fieldTypeOptions"
There is a bug in that implementation, the items passed via input are overwrote by the `bit-option` implementation ([code](https://github.com/bitwarden/clients/blob/f46221654c5aabd8f0b31c07a1cf30fbfbfba397/libs/components/src/select/select.component.ts#L53)), because there are no options found. 

Thankfully, there are no implementations in the codebase that would hit this. 

Is there a correct place to create a bug for that? The CL JIRA?

2024-07-11 19:04 UTC, nick-livefront commented on libs/vault/src/cipher-form/components/custom-fields/custom-fields.component.html
> +  <button
I wanted to re-use the same button in two different places in the template. 

One as "standalone" or outside of the `bit-section`, and the other inside the `bit-section`, so this was just a way to not write the same button twice.

2024-07-11 21:18 UTC, nick-livefront commented on libs/vault/src/cipher-form/components/custom-fields/add-edit-custom-field-dialog/add-edit-custom-field-dialog.component.html
> +      {{ "addField" | i18n }}
I like it! [468899a](https://github.com/bitwarden/clients/pull/10054/commits/468899a272cf094ef8894979ec46bfca9df0df88)

2024-07-11 21:19 UTC, nick-livefront commented on libs/vault/src/cipher-form/components/custom-fields/add-edit-custom-field-dialog/add-edit-custom-field-dialog.component.ts
> +    label: [""],
Yup! I double checked with Danielle as well. [f55d29f](https://github.com/bitwarden/clients/pull/10054/commits/f55d29fc9bdf37b590397bd8fed564156455735b)

2024-07-11 21:20 UTC, nick-livefront commented on libs/vault/src/cipher-form/components/custom-fields/add-edit-custom-field-dialog/add-edit-custom-field-dialog.component.html
I did add the wrapping `form` because it feels like a good pattern and hooks right into the disabled state of the submit buttons.

I didn't added submit action, I didn't see a technical gain there because a "submission" isn't occurring. If I missed another benefit, let me know.

2024-07-11 21:21 UTC, nick-livefront commented on libs/vault/src/cipher-form/components/custom-fields/custom-fields.component.html
> +  <button
Unneeded after trimming the component down to only the custom fields section in [3cc46bb](https://github.com/bitwarden/clients/pull/10054/commits/3cc46bb786e9d2dd0db343678bf15018661bc5bb)

2024-07-11 21:22 UTC, nick-livefront commented on libs/vault/src/cipher-form/components/custom-fields/custom-fields.component.html
> +          <button
Thank you, TIL! I believe I should have that handled here to match: [926ff63](https://github.com/bitwarden/clients/pull/10054/commits/926ff639e3423979674de46a63576189cbd3b1e6)

2024-07-11 21:22 UTC, nick-livefront commented on libs/vault/src/cipher-form/components/additional-options/additional-options-section.component.ts
> +  @Input({ required: true }) updatedCipherView: CipherView | null = null;
After a couple trials and understanding your suggestion, I think I made it to the destination!

[3cc46bb](https://github.com/bitwarden/clients/pull/10054/commits/3cc46bb786e9d2dd0db343678bf15018661bc5bb)

2024-07-12 15:25 UTC, shane-melton commented on libs/vault/src/cipher-form/components/custom-fields/add-edit-custom-field-dialog/add-edit-custom-field-dialog.component.html
> +          *ngFor="let type of fieldTypeOptions"
Ah, good catch! Yep, the CL JIRA is the place to log such a thing.

2024-07-12 15:33 UTC, shane-melton commented on libs/vault/src/cipher-form/components/custom-fields/add-edit-custom-field-dialog/add-edit-custom-field-dialog.component.html
I believe one possible benefit of using the submit action is that it allows the user to use the Enter key to submit the form versus needing to click the button. 

It would also allow us to simplify the template by having a single submit button that has a label that changes based on the variant (similar to the dialog title) and then submission handler would decide between `updateLabel()` and `addField()`.

2024-07-15 18:25 UTC, shane-melton requested changes
Looking good! Just a few CL suggestions I missed on the first pass.

2024-07-15 18:25 UTC, shane-melton commented on libs/vault/src/cipher-form/components/custom-fields/custom-fields.component.html
> +        type="button"
🎨 We should be able to use the `bitLink linkType="primary"` directive instead of specifying the styles explicitly and `bitTypography`.

2024-07-15 18:25 UTC, shane-melton commented on libs/vault/src/cipher-form/components/custom-fields/custom-fields.component.ts
> +  newField: boolean;
⛏️ Would you mind adding some documentation clarifying why we have this `newField` property? I had to do a couple double takes when investigating its purpose in the original custom fields component and think it would help others in the future.

2024-07-16 20:41 UTC, nick-livefront commented on libs/vault/src/cipher-form/components/custom-fields/add-edit-custom-field-dialog/add-edit-custom-field-dialog.component.html
> +          *ngFor="let type of fieldTypeOptions"
Added! [CL-348](https://bitwarden.atlassian.net/browse/CL-348)

cc: @willmartian

2024-07-16 21:06 UTC, nick-livefront commented on libs/vault/src/cipher-form/components/additional-options/additional-options-section.component.html
> +    <button
[a1d4b61](https://github.com/bitwarden/clients/pull/10054/commits/a1d4b61914af0de3d2ac438a567cdf3c78bd81ed)

2024-07-16 21:06 UTC, nick-livefront commented on libs/vault/src/cipher-form/components/custom-fields/custom-fields.component.html
> +        type="button"
Nice catch! [a1d4b61](https://github.com/bitwarden/clients/pull/10054/commits/a1d4b61914af0de3d2ac438a567cdf3c78bd81ed)

2024-07-16 21:07 UTC, nick-livefront commented on libs/vault/src/cipher-form/components/custom-fields/custom-fields.component.ts
> +  newField: boolean;
Good call, it took me a bit to see that field on the view. [c187f3a](https://github.com/bitwarden/clients/pull/10054/commits/c187f3a7cc30dff9747f8777a3348ae84da868d2) let me know what you think about how this is worded. I tried to basically put what you had here: https://github.com/bitwarden/clients/pull/10054#discussion_r1672810101

2024-07-16 21:07 UTC, nick-livefront commented on libs/vault/src/cipher-form/components/custom-fields/add-edit-custom-field-dialog/add-edit-custom-field-dialog.component.html
Sold! I agree [09e7736](https://github.com/bitwarden/clients/pull/10054/commits/09e77366ba0d36ee013b7fedcc6f0502436ec622)

2024-07-16 21:16 UTC, shane-melton commented on libs/vault/src/cipher-form/components/custom-fields/custom-fields.component.ts
> +  newField: boolean;
Looks good to me, thank you!

2024-07-16 21:18 UTC, shane-melton approved these changes
Changes look good! Nice work!

2024-07-17 14:11 UTC, merged