Tools/pm 9613/port forwarders to integrations
bitwarden/clients pull request #10075
Opened 2024-07-11 16:47 UTC by audreyality

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-9613

## 📔 Objective

* Introduce "forwarder" integration logic
* Isolate forwarder remote procedure calls
* Consolidate forwarder implementations into static configurations

## 🦖 System Evolution

A lot of work went into "boiling out" the logic specific to a given integrator, but at present that logic is fully disconnected from its consumers. There are better ways to represent it, I'm sure, but iterating it further blocks higher priority work. So, for now, it's a little makeshift byt

Some ideas:

* A lot of this data should be made available through an integration service instead of global variables.
* I think the RPC calls might be better structured as templates, and that the result handlers should be simplified--HTTP status could be automatically handled, for example. There's almost no variation and all handlers can signal an error easily.
* Fixed data might be provided through server-side configuration or a flat file.
* Authentication could be made into data.

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-07-11 16:59 UTC, audreyality commented
📝 I'll work on the missing tests, and I've noticed a few places missing JSDoc as well.

2024-07-11 17:01 UTC, audreyality commented on libs/tools/generator/core/src/integration/addy-io.ts
📝 Here's an example of one of the integrator files. It's well-organized, but it looks messy because it's all object literals.

2024-07-11 17:10 UTC, audreyality commented on libs/tools/generator/core/src/strategies/forwarder-generator-strategy.ts
📖 Getting the strategy to typecheck with all of the different integration settings was challenging.

2024-07-23 18:35 UTC, djsmith85 requested changes
@audreyality Amazing work on making this configurable and hard to get wrong when using the forwarders. This is unfortunately only a partial review, but I wanted to give you some feedback before logging off for today. Mostly smaller things I noticed here and there.

❓  This is not directly relevant to these changes, but something I was wondering about while reviewing and testing: Handling of errors within the RestClient.
- You already noted that the error-message within the RestClient should move be replace by more generic ones. 
Thinking about this being more flexible with a generic RPC/rest-client and the forwarders seemingly similar but due differ in there error handling and parsing. Maybe there should be a way to pass in a function on how to check/respond to specific errors?

During my testing, I found that the `RestClient.tryGetErrorMessage()` would work in most situations but ForwardEmail as an example, fills `response.error` and `message `, thus leaving the actionable/informational part (`Invalid Api token`) from returning and just telling the user `Unauthorized` or `An error occurred`.

Some of the forwarders and potential future integrations will provide good error information and might be represented in different ways (`response.error`, `.message`, `.result`, `.status`, etc.).

2024-07-23 19:09 UTC, audreyality commented
> This is not directly relevant to these changes, but something I was wondering about while reviewing and testing: Handling of errors within the RestClient.
> ... Thinking about this being more flexible with a generic RPC/rest-client and the forwarders seemingly similar but due differ in there error handling and parsing. Maybe there should be a way to pass in a function on how to check/respond to specific errors?

1. Keep in mind that this is not a generic rest client. It's a rest client specific to integrations. My primary goal here is to avoid giving them much latitude, specifically by making integrator-specific logic as declarative as possible.
2. The value extraction in the JSON logic can output an error in the "cause" part of the tuple it returns. This is then packaged within a more generic error message that the rest client throws. At present, [only the fastmail integration uses this feature](https://github.com/bitwarden/clients/blob/cdc459bff70057519f5aff600acf2cc647780eab/libs/tools/generator/core/src/integration/fastmail.ts#L78-L98).
3. `RestClient` in particular eschews integration-specific error handling. It delegates that to the [RPC definition](https://github.com/bitwarden/clients/blob/cdc459bff70057519f5aff600acf2cc647780eab/libs/tools/generator/core/src/engine/rpc/get-account-id.ts#L17-L23). I expect that to require some refinement as systems make vendored RPC calls.

2024-07-24 21:07 UTC, djsmith85 requested changes

2024-07-24 21:07 UTC, djsmith85 commented on libs/tools/generator/core/src/engine/settings.ts
> +   *  is `jd`, then the generated email address will be `jd@mydomain.io`
⛏️  Should be `domain.io` instead of `mydomain.io`
```suggestion
   *  is `jd`, then the generated email address will be `jd@domain.io`
```

2024-07-25 15:50 UTC, audreyality commented on libs/tools/generator/core/src/integration/addy-io.ts
> +const createForwardingEmail = Object.freeze({
Addressed in 62c0e04ab3. This header is now output by all "create forwarding address" RPCs.

2024-07-25 15:50 UTC, audreyality commented on libs/tools/generator/core/src/types/forwarder-options.ts
> +  baseUrl?: string;
This is stray code from an old implementation path. Removed in 7ab7694c57.

2024-07-25 15:52 UTC, audreyality commented on libs/common/src/tools/integration/integration-context.ts
> +    return result as any;
This code was necessary before I performed the cast on line 30. Removed in 28c73887a.

2024-07-25 15:52 UTC, audreyality commented on libs/common/src/tools/integration/integration-context.ts
> +    if (token === "") {
Addressed by a45304715d7.

2024-07-25 15:52 UTC, audreyality commented on libs/common/src/tools/integration/integration-context.ts
> +  authenticationToken(
Addressed by 543ea3b19f54fd.

2024-07-25 15:54 UTC, audreyality commented on libs/tools/generator/core/src/engine/settings.ts
> +   *  is `jd`, then the generated email address will be `jd@mydomain.io`
Addressed in c8bfa95f41662.

2024-07-25 15:55 UTC, audreyality commented
> yes please add the snippet to tryGetErrorMessageto retain user-actionable error messages for ForwardEmail.

Addressed in 1c0634f52f.

2024-07-25 16:06 UTC, audreyality commented on libs/common/src/tools/integration/integration-context.ts
> +  baseUrl(): string {
Addressed by 543ea3b19f54fd.

2024-07-25 16:33 UTC, djsmith85 submitted a review, later dismissed

2024-07-26 21:10 UTC, audreyality commented on libs/common/src/tools/integration/rpc/rest-client.ts
📝 Adding the "X-Requested-With": "XMLHttpRequest" header doesn't seem to have affected the output of the endpoint. It's returning strings instead, so I've extended `fetchJson` to handle them.

2024-07-29 10:17 UTC, djsmith85 requested changes

2024-07-29 10:17 UTC, djsmith85 commented on apps/browser/src/_locales/en/messages.json
> +  "forwarderInvalidToken": {
⚠️ :information_source: Fixing the typo for the i18n keys will delete all existing translations. I'm fine with the changes, just wanted you to be aware of it

2024-07-29 10:17 UTC, djsmith85 commented on libs/common/src/tools/integration/rpc/rest-client.ts
> +    const parsable = body.startsWith("{") || body.startsWith(`'`) || body.startsWith(`"`);
⚠️  This might throw if an empty body gets passed in.

2024-07-29 10:17 UTC, djsmith85 commented on libs/common/src/tools/integration/rpc/rest-client.ts
> +    if (!body.length || body.includes("<")) {
:warning:  This might throw if an empty body gets passed in.

2024-07-29 13:58 UTC, audreyality commented on libs/common/src/tools/integration/rpc/rest-client.ts
> +    if (!body.length || body.includes("<")) {
This method is private and `tryGetErrorMessage` ensures that `body` will never be `null`.

2024-07-29 13:58 UTC, audreyality commented on libs/common/src/tools/integration/rpc/rest-client.ts
> +    const parsable = body.startsWith("{") || body.startsWith(`'`) || body.startsWith(`"`);
This method is private and `tryGetErrorMessage` ensures that `body` will never be `null`.

2024-07-29 14:01 UTC, audreyality commented on apps/browser/src/_locales/en/messages.json
> +  "forwarderInvalidToken": {
I don't believe there are any other translations yet. I did a global find-replace for this and only the English files were hit. Unless I've missed something (totally reasonable), the translations should be fine.

It does bring up the question of whether I should rename the keys used by the RestClient to remove "forwarder", though. Would you prefer that in this PR or a followup?

2024-07-29 14:02 UTC, djsmith85 commented on libs/common/src/tools/integration/rpc/rest-client.ts
> +    const parsable = body.startsWith("{") || body.startsWith(`'`) || body.startsWith(`"`);
I must have skipped over the existence of the null-coalescing operator

2024-07-29 14:06 UTC, djsmith85 approved these changes

2024-07-29 14:06 UTC, djsmith85 commented on apps/browser/src/_locales/en/messages.json
> +  "forwarderInvalidToken": {
Likely didn't find them because they are hidden within vscode, to not pollute the search-results: https://github.com/bitwarden/clients/blob/main/.vscode/settings.json

If you have good reason the rename the keys and delete all the existing translations, then please do it within this PR. As 2nd rename would delete the translations again.

2024-07-29 14:18 UTC, audreyality commented on apps/browser/src/_locales/en/messages.json
> +  "forwarderInvalidToken": {
TIL. I'll adjust all the things.

2024-07-29 14:20 UTC, audreyality commented on apps/browser/src/_locales/en/messages.json
> +  "forwarderInvalidToken": {
TIL.

> If you have good reason the rename the keys and delete all the existing translations, then please do it within this PR. As 2nd rename would delete the translations again.

I'll actually back out this PR, I think, and keep the spelling errors for now. Reason being, there's a *lot* of translation files to edit.

2024-07-29 14:27 UTC, djsmith85 commented on apps/browser/src/_locales/en/messages.json
> +  "forwarderInvalidToken": {
Okay. You wouldn't need to edit all the translation files. The Crowdin Sync takes care of it. Almost all devs only need to pay attention to the en/messages.json.

2024-07-29 14:28 UTC, djsmith85 approved these changes

2024-07-30 09:40 UTC, djsmith85 approved these changes

2024-07-30 12:40 UTC, merged