Make biometrics ipc more type-safe by adding enums and command classes
bitwarden/clients pull request #10119
Opened 2024-07-15 12:26 UTC by quexten

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-9798

## 📔 Objective

Improve type-safetey of biometrics IPC by using shared enums instead of magic strings, and by introducing classes for the message / response types.

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-07-15 12:27 UTC, quexten commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/bitwarden/clients/10119?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#10119** <a href="https://app.graphite.dev/github/pr/bitwarden/clients/10119?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#10052** <a href="https://app.graphite.dev/github/pr/bitwarden/clients/10052?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#9979** <a href="https://app.graphite.dev/github/pr/bitwarden/clients/9979?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#9977** <a href="https://app.graphite.dev/github/pr/bitwarden/clients/9977?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#9976** <a href="https://app.graphite.dev/github/pr/bitwarden/clients/9976?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#9945** <a href="https://app.graphite.dev/github/pr/bitwarden/clients/9945?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#9944** <a href="https://app.graphite.dev/github/pr/bitwarden/clients/9944?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#9943** <a href="https://app.graphite.dev/github/pr/bitwarden/clients/9943?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @quexten and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-22 16:34 UTC, jprusik requested changes
nice improvement to typing; let's avoid enums (see prior art elsewhere where we've moved away from this: e.g. `apps/browser/src/autofill/enums`)

Everything else LGTM 👍

2024-07-22 16:34 UTC, jprusik commented on libs/auth/src/common/models/domain/native-messages.ts
> +}
avoid using enums in Typescript:
https://dev.to/ivanzm123/dont-use-enums-in-typescript-they-are-very-dangerous-57bh

2024-07-23 17:05 UTC, quexten commented on libs/auth/src/common/models/domain/native-messages.ts
> +}
Thank you, this was a great read. TBH the solution feels somewhat hacky, when this is syntactically much nicer to just represent with an enum. Sad that this is needed, but I'll update the PR to it.

2024-07-24 20:11 UTC, jprusik approved these changes

2024-07-24 20:11 UTC, jprusik commented
erp - missed that it was in draft, apologies!

2024-07-25 09:36 UTC, quexten commented
It's mostly under code-review since I need to re-consider the order to merge this PR-stack in since I had to pull out the browser-provided userkey changes for now.

2024-09-16 14:44 UTC, quexten commented
Will be addressed in a larger biometrics refactor; closing.

2024-09-16 14:44 UTC, closed without merging