[CL-305] Allow margin to be disabled for elements at the bottom of a page
bitwarden/clients pull request #10132
Opened 2024-07-16 13:49 UTC by vleague2

## 🎟️ Tracking

[CL-305](https://bitwarden.atlassian.net/browse/CL-305)

## 📔 Objective

This PR adds the ability to manually disable a `bit-section`'s bottom margin, primarily for use on sections that are the last element on the page and should not have extra bottom margin. This is a pattern used on other components with built-in margin.

This PR implements the `disableMargin` input on the extension vault page, which is where the extra margin issue was reported. It also adds a `section` to the `popup-layout` stories to provide a more realistic story for the extension layout.

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-07-16 20:07 UTC, shane-melton requested changes

2024-07-16 20:07 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/vault-list-items-container/vault-list-items-container.component.html
> +<bit-section *ngIf="ciphers?.length > 0 || description" disableMargin>
⚠️ This container is used a few times in the `vault-v2` component, one for each list section, with some needing the bottom margin to separate the section lists (at least, as far as I'm aware). 

If so, we will likely want to make this an input to the list container to pass through and then set the attribute on the last `<vault-list-items-container>` in the `vault-v2` template.

2024-07-16 20:14 UTC, vleague2 commented on apps/browser/src/vault/popup/components/vault-v2/vault-list-items-container/vault-list-items-container.component.html
> +<bit-section *ngIf="ciphers?.length > 0 || description" disableMargin>
Oh man good catch 🤦‍♀️

2024-07-17 20:26 UTC, shane-melton submitted a review, later dismissed
Looks great, thank you!

2024-07-17 21:03 UTC, willmartian approved these changes
One non-blocking suggestion:

2024-07-17 21:03 UTC, willmartian commented on libs/components/src/section/section.component.ts
> +    <section [ngClass]="sectionClass">
Thoughts on leaving the Tailwind classes in the template? Imo it is easier to parse. 
```
[ngClass]="{
  'tw-mb-6 md:tw-mb-12': !disableMargin
}"
```

2024-07-18 13:28 UTC, vleague2 commented on libs/components/src/section/section.component.ts
> +    <section [ngClass]="sectionClass">
Agreed, idk what I was thinking 😂

2024-07-18 14:26 UTC, willmartian commented on libs/components/src/section/section.component.ts
> +    <section [ngClass]="sectionClass">
Same, all the time

2024-07-18 14:27 UTC, willmartian approved these changes
:shipit:

2024-07-24 14:01 UTC, shane-melton approved these changes

2024-07-24 15:52 UTC, willmartian approved these changes

2024-07-24 15:53 UTC, shane-melton approved these changes

2024-07-24 16:08 UTC, merged