[PM-1900] Run Process Reload on Firefox
bitwarden/clients pull request #10149
Opened 2024-07-17 17:31 UTC by justindbaur

## 🎟️ Tracking

## 📔 Objective

Switch Firefox from running `window.location.reload(true)` to `chrome.runtime.processReload()`. Also to help avoid the sidebar from automatically re-opening when the process reload happens we are not going to open it automatically on install (since process reload emulates a reinstall). The sidebar is still open-able through the shortcut.

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-07-18 15:25 UTC, djsmith85 submitted a review, later dismissed
Changes are looking good, as they are quite similar to https://github.com/bitwarden/clients/pull/3683 😉 

Could please check if
- apps/browser/src/popup/app.component.ts: Removed a message handler for "reloadProcess" which never got called.
from https://github.com/bitwarden/clients/pull/3683 still applies and also remove it here.

2024-07-18 19:18 UTC, justindbaur commented
@djsmith85 Oh my word, I totally dropped the ball on the PR? Would you rather revive that?

I did some looking and the `"reloadProcess"` message is sent from SystemService but I don't think it would be necessary anymore. So I am happy to remove it as well. I did test the `open_at_install` & `chrome.runtime.reload` behavior in Opera and couldn't notice any adverse effects. I didn't consider safari though, I figured it didn't call it because the API wasn't supported, since as far as I knew they didn't have a sidebar. I will do some testing on it though and make those changes here.

2024-07-18 19:50 UTC, djsmith85 commented
> @djsmith85 Oh my word, I totally dropped the ball on the PR? Would you rather revive that?
> 
> I did some looking and the `"reloadProcess"` message is sent from SystemService but I don't think it would be necessary anymore. So I am happy to remove it as well. I did test the `open_at_install` & `chrome.runtime.reload` behavior in Opera and couldn't notice any adverse effects. I didn't consider safari though, I figured it didn't call it because the API wasn't supported, since as far as I knew they didn't have a sidebar. I will do some testing on it though and make those changes here.

No worries, at lot has happened since. Several changes to the process reload (clean up, refactor, biometrics) and more importantly MV3. Hence all the merge conflicts. I'm happy with keeping this open and close mine. Looking forward to hear about your findings when testing this and let me know if you wanna chat about anything.

2024-07-19 13:38 UTC, coroiu commented on apps/browser/src/manifest.v3.json
> +    "open_at_install": false
omg thank you this annoys me so much!

2024-07-19 13:38 UTC, coroiu approved these changes

2024-07-19 14:28 UTC, coroiu reviewed
failing tests

2024-07-22 10:43 UTC, djsmith85 requested changes
Changes are looking great, just one minor documentation change

2024-07-22 10:43 UTC, djsmith85 commented on apps/browser/src/platform/browser/browser-api.ts
>     * to reload or by calling the extension's runtime to reload.
⚠️ Documentation needs to be updated

2024-07-22 15:03 UTC, djsmith85 commented on apps/browser/src/platform/browser/browser-api.ts
> +   * Handles reloading the extension using underlying functionalify exposed by the browser API.
```suggestion
   * Handles reloading the extension using the underlying functionality exposed by the browser API.
```

2024-07-22 18:15 UTC, djsmith85 submitted a review, later dismissed

2024-07-24 06:41 UTC, coroiu submitted a review, later dismissed

2024-08-14 16:17 UTC, djsmith85 approved these changes

2024-08-19 08:25 UTC, coroiu submitted a review, later dismissed

2024-08-28 14:45 UTC, djsmith85 approved these changes

2024-08-28 19:00 UTC, merged