[CL-273] Update styles for checkbox and form control
bitwarden/clients pull request #10146
Opened 2024-07-17 16:03 UTC by vleague2

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-07-23 14:56 UTC, willmartian reviewed
Should the error/hint and label be aligned? cc @danielleflinn 

<img width="1728" alt="Screenshot 2024-07-23 at 10 54 36 AM" src="https://github.com/user-attachments/assets/846e69a0-3dbd-4726-abd5-6c3e808cbe6f">

2024-07-23 15:03 UTC, willmartian requested changes
Since some of these css choices are to support standalone checkboxes and how they display in tables, could you add a story of a checkbox in a table row?

2024-07-23 15:57 UTC, danielleflinn requested changes
@willmartian yes the error should be aligned to the label just like the hint is. Also It looks like the error text is a bit large. Lets use the same font-size as the field hint/error here. 

+ 1 to Will's comment on the story for a checkbox in a table row. I also noticed while reviewing, the standalone stories don't have focus indicators. Can we add those so they display around the single checkbox?

2024-07-30 14:03 UTC, willmartian commented on libs/components/src/form-control/label.directive.ts
> +    return this.parentFormControl ? classes : classes.concat(["tw-truncate"]);
Applying classes based on the presence of a parent can be accomplished with pure CSS/Tailwind:

`[&:not(bit-form-control_*)]:tw-truncate`

2024-07-30 15:18 UTC, willmartian approved these changes
Suggestion above is optional ^

2024-07-30 16:09 UTC, merged