[PM-9809] attachments v2 refactor
bitwarden/clients pull request #10142
Opened 2024-07-17 13:39 UTC by Jingo88

## 🎟️ Tracking

[PM-9809 Attachments Styling](https://bitwarden.atlassian.net/browse/PM-9809)

## 📔 Objective

* Renamed `attachments-v2` to `attachments-v2-view` because we have another `attachments-v2` that is part of the edit
* Refactored `attachments-v2-view` to utilize the same code as `attachments-v2`
* Moved MP reprompt code into `DownloadAttachmentsComponent`
* Removed excess code in `attachments-v2-view`
* Moved `cipher-attachments` out of browser popup and into the libs cipher-form

## 📸 Screen Recording

https://github.com/user-attachments/assets/3656cf9c-e127-4a20-90f9-df72d585b803

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-07-17 17:05 UTC, nick-livefront reviewed
@Jingo88 These changes make sense to me! 👏

2024-07-17 17:05 UTC, nick-livefront commented on libs/vault/src/components/download-attachment/download-attachment.component.ts
> +  // When this component is in the view we will want to check for the master password reprompt
What does "in the view" refer to here?

2024-07-17 17:05 UTC, nick-livefront commented on libs/vault/src/components/download-attachment/download-attachment.component.ts
> +  // When this component is in the view we will want to check for the master password reprompt
`When in "view" mode, we will want to check for the master password reprompt`?

2024-07-17 17:10 UTC, Jingo88 commented on libs/vault/src/components/download-attachment/download-attachment.component.ts
> +  // When this component is in the view we will want to check for the master password reprompt
ah yeah, let me re-write that

2024-07-18 22:25 UTC, shane-melton requested changes
Looks solid! Just noticed a few import path concerns we should take a closer look at.

2024-07-18 22:25 UTC, shane-melton commented on libs/vault/src/cipher-form/components/attachments/cipher-attachments.component.spec.ts
> +import { DownloadAttachmentComponent } from "@bitwarden/vault";
⚠️ I don't believe we can import from `@bitwarden/vault` from within `/libs/vault` as it can cause build errors. It should likely be a relative path.

2024-07-18 22:25 UTC, shane-melton commented on libs/vault/src/components/download-attachment/download-attachment.component.spec.ts
> +import { PasswordRepromptService } from "@bitwarden/vault";
⚠️ Same concern here with importing from `@bitwarden/vault` in `/libs/vault`.

2024-07-18 22:25 UTC, shane-melton commented on libs/vault/src/components/download-attachment/download-attachment.component.ts
> +import { PasswordRepromptService } from "@bitwarden/vault";
⚠️ One last one

2024-07-18 22:25 UTC, shane-melton commented on libs/vault/src/index.ts
> +export { CipherAttachmentsComponent } from "./cipher-form/components/attachments/cipher-attachments.component";
⛏️ Can we add this to the exports of `./cipher-view/index.ts` so we don't have to re-grab this path and export it explicitly as we already re-export `* from "./cipher-view";` above.

2024-07-23 17:20 UTC, shane-melton approved these changes

2024-07-23 17:27 UTC, merged