[AC-2709] Upgrade from 2 person/free org
bitwarden/clients pull request #10141
Opened 2024-07-17 12:58 UTC by cyprain-okeke

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/AC-2709
## 📔 Objective

Annual option will have three plan options

Monthly option will have two plan options, with the Families plan grayed out

Include discount badge for annual plan

Payment method will be required

## 📸 Screenshots

https://github.com/user-attachments/assets/318cc8fb-3ff7-4721-b015-8df7fd4133ec

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-07-17 16:33 UTC, amorask-bitwarden requested changes
Just one blocker regarding the form title for the upgrade so far. While I tried to look through the `change-plan-dialog.component`, the .ts file is over 800 lines. It seems like we're repeating a lot of stuff from the `organization-plans.component` if I'm not mistaken. Is there any opportunity to consolidate some of this?

2024-07-17 16:33 UTC, amorask-bitwarden commented on apps/web/src/app/billing/shared/tax-info.component.ts
> +    this.route.params.subscribe(async (params) => {
❓ Did you happen to check if this has any unintended consequences for other uses of this component? Seems strange that it would be so specific to begin with.

2024-07-17 16:33 UTC, amorask-bitwarden commented on apps/web/src/app/billing/organizations/change-plan-dialog.component.ts
> +        this.platformUtilsService.showToast(
I think this invocation is being deprecated. Can you replace it with the `ToastService`?

2024-07-19 16:03 UTC, amorask-bitwarden requested changes
Found a few issues related to the required Figma designs.

2024-07-19 16:03 UTC, amorask-bitwarden commented on apps/web/src/app/billing/organizations/change-plan-dialog.component.ts
> +  seatPriceMonthly(selectedPlan: PlanResponse) {
This method appears to be unused.

2024-07-19 16:03 UTC, amorask-bitwarden commented on apps/web/src/app/billing/organizations/change-plan-dialog.component.ts
> +  get paymentDesc() {
This method appears to be unused.

2024-07-19 16:03 UTC, amorask-bitwarden commented on apps/web/src/app/billing/organizations/change-plan-dialog.component.ts
> +  selfHostedForm = this.formBuilder.group({
This appears to be unused.

2024-07-19 16:03 UTC, amorask-bitwarden commented on apps/web/src/app/billing/organizations/change-plan-dialog.component.html
> +            *ngFor="let selectableProduct of selectableProducts; let i = index"
Not sure exactly where this is happening, but the Figma designs say when upgrading from Free and selecting Monthly, Families should be greyed out, not removed entirely:
![image](https://github.com/user-attachments/assets/7edbad4b-f770-496d-9cab-dfe9694b8fb9)

2024-07-23 08:41 UTC, cyprain-okeke commented on apps/web/src/app/billing/organizations/change-plan-dialog.component.ts
> +  get paymentDesc() {
removed

2024-07-23 08:41 UTC, cyprain-okeke commented on apps/web/src/app/billing/organizations/change-plan-dialog.component.ts
> +  seatPriceMonthly(selectedPlan: PlanResponse) {
removed

2024-07-23 08:41 UTC, cyprain-okeke commented on apps/web/src/app/billing/organizations/change-plan-dialog.component.ts
> +  selfHostedForm = this.formBuilder.group({
removed

2024-07-23 08:46 UTC, cyprain-okeke commented on apps/web/src/app/billing/organizations/change-plan-dialog.component.html
> +            *ngFor="let selectableProduct of selectableProducts; let i = index"
The grey out might to work because we filter by isAnnual and family plan is not monthly and will be removed from the list. I will discuss with design team to update the figma

2024-07-23 08:46 UTC, cyprain-okeke commented on apps/web/src/app/billing/organizations/change-plan-dialog.component.ts
> +export const openChangePlanDialog = (
thanks, this is done

2024-07-23 08:46 UTC, cyprain-okeke commented on apps/web/src/app/billing/organizations/change-plan-dialog.component.html
> +                {{ "selected" | i18n }}
this is done

2024-07-25 17:38 UTC, addisonbeck commented on apps/web/src/app/admin-console/organizations/members/members.component.ts
> +      productType !== ProductTierType.Families
⛏️ We have this same conditional in several places. Let's add an exported function next to `ProductTierType` called `isSelfUpgradable`. Or something else if you've got another idea - I'd just like to encapsulate this condition somehow.

2024-07-25 18:18 UTC, cyprain-okeke commented on apps/web/src/app/admin-console/organizations/members/members.component.ts
> +      productType !== ProductTierType.Families
changes has been made

2024-07-25 20:33 UTC, addisonbeck approved these changes

2024-07-29 15:28 UTC, amorask-bitwarden commented on apps/web/src/app/billing/organizations/change-plan-dialog.component.ts
> +export const openChangePlanDialog = (
@cyprain-okeke Trying to click invite member now results in a console error:
`Uncaught (in promise): Error: Unsupported product type: 0`

2024-07-29 15:31 UTC, amorask-bitwarden commented on apps/web/src/app/billing/organizations/change-plan-dialog.component.html
> +                {{ "selected" | i18n }}
I'm still seeing this as selectable after pulling down and running the changes?
![image](https://github.com/user-attachments/assets/52823dcd-5f8a-4ec5-bb35-1c81e084aad5)

2024-07-29 15:35 UTC, amorask-bitwarden requested changes
I'm still seeing a couple issues in the following comment sections:
- https://github.com/bitwarden/clients/pull/10141#discussion_r1684578018
- https://github.com/bitwarden/clients/pull/10141#discussion_r1695440794

Everything else looks good though.

2024-07-29 17:12 UTC, closed without merging