[PM-8386] - Add section header to import page
bitwarden/clients pull request #10153
Opened 2024-07-17 19:55 UTC by jaasen-livefront

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-8386

## 📔 Objective

This PR updates the import page to group the inputs into sections with a corresponding header.

** **NOTE** ** Adjustments to the background color was required for all clients in order to allow for a contrast between the card and background.

## 📸 Screenshots

## Desktop

|Light|Dark|
---|---
|![desktop-light](https://github.com/user-attachments/assets/f3eb0a3b-5a09-4752-991a-d52039a4f880)|![desktop-dark](https://github.com/user-attachments/assets/7d656377-bc5d-4da2-92e0-ab820c5f3fd1)|

## Web
|Light|Dark|
---|---
|![web-light](https://github.com/user-attachments/assets/009b2a4f-7a81-4e47-8b5a-4521064cce9a)|![web-dark](https://github.com/user-attachments/assets/4251cf54-a115-4c30-978b-fed4b25e6465)|

## Browser
|Light|Dark|
---|---
|![Screenshot 2024-07-17 at 12 49 24 PM](https://github.com/user-attachments/assets/17c4d0e4-1508-4dca-a405-f445d20d9217)|![Screenshot 2024-07-17 at 12 49 02 PM](https://github.com/user-attachments/assets/a2e954c7-1021-47ae-a604-39db4a0697bf)|

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-07-17 20:25 UTC, djsmith85 commented on apps/browser/src/_locales/en/messages.json
>    "importDestination": {
Any change of message content without changing the key won't be reflected in existing translations. Please change the key and replace it's usages. This needs to be done for all clients.
```suggestion
  "destination": {
```

2024-07-17 21:13 UTC, willmartian requested changes
This PR changes the bg color of `bit-layout` and `bit-dialog` from `tw-bg-background` to `tw-bg-background-alt`. This will affect _all_ pages and dialogs, and is not behind feature flag.

Is that desired, @danielleflinn ?

2024-07-18 00:03 UTC, danielleflinn commented
> This PR changes the bg color of` bit-layout` and `bit-dialog` from` tw-bg-background` to `tw-bg-background-alt`. This will affect all pages and dialogs, and is not behind feature flag.

No we should not do this everywhere. I think the background color changes need to be implemented as variants of these components for now since there are many layouts/dialogs in the web app that have not been designed to display on the darker background. 

Perhaps for now, we remove just the background colors from this work and add a follow on task to come back once we have a better plan to support this? @willmartian @djsmith85 does that work for you? Or should we put this task on hold?

2024-07-23 16:17 UTC, jaasen-livefront commented
@danielleflinn @willmartian Sounds good. I'll revert the changes to the background.

2024-07-23 17:54 UTC, djsmith85 approved these changes

2024-07-23 20:30 UTC, jaasen-livefront commented
@danielleflinn @willmartian Ready for re-review

2024-07-24 03:50 UTC, willmartian commented
> @willmartian please advise on what should be changed in the Dialog UI

I have [a PR](https://github.com/bitwarden/clients/pull/10237) open to add a background input to the dialog component. Y'all can either go ahead and add `background="alt"` to the relevant dialogs, or wait for that to be merged and pull it in.

2024-07-24 14:27 UTC, danielleflinn approved these changes

2024-07-24 14:27 UTC, merged