[PM-8794] Update "auto-fill" to "autofill"
bitwarden/clients pull request #10156
Opened 2024-07-17 20:35 UTC by alec-livefront

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-8794

## 📔 Objective

Updates references of "auto-fill", "auto-filled" and "Auto-filled" with "autofill", "autofilled" and "Autofilled" throughout the codebase.

> [!NOTE]
> I've added an [update to the contributing docs](https://github.com/bitwarden/contributing-docs/pull/385) with the same language changes.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-07-17 21:30 UTC, shane-melton requested changes

2024-07-17 21:30 UTC, shane-melton commented on apps/browser/src/_locales/en/messages.json
⚠️ Unfortunately, we cannot modify existing translation keys as they won't be picked up in Crowdin for other languages to update. We need to create new versions of the keys (e.g. "autoFill" -> "autoFillNoHypen") and then update their usage in the application.

@djsmith85 Do you by chance know if we have any naming convention or strategy for changing the key back at some point in the future so that we don't have to keep the long translation key around forever? Or possibly other ideas to make this less painful?

2024-07-19 20:30 UTC, alec-livefront commented on apps/browser/src/autofill/deprecated/overlay/pages/button/__snapshots__/autofill-overlay-button.deprecated.spec.ts.snap
> -  aria-label="toggleBitwardenVaultOverlay"
This seems odd to me that this was removed after running `npm jest -u`. I would have expected this to update to `toggleBitwardenVaultOverlayNoAutofillHyphen`?

2024-07-19 20:31 UTC, alec-livefront commented on apps/browser/src/autofill/deprecated/overlay/pages/button/__snapshots__/autofill-overlay-button.deprecated.spec.ts.snap
> -  aria-label="toggleBitwardenVaultOverlay"
Same concern as https://github.com/bitwarden/clients/pull/10156/files#r1684944878.

2024-07-23 13:34 UTC, djsmith85 commented on apps/browser/src/_locales/en/messages.json
@shane-melton: No naming strategy and changing the keys back is also not an option as it would nuke the existing translations again.

There is an option within the Crowdin upload settings:
https://github.com/bitwarden/clients/blob/477294379b2dc051d31ee1f8855f3ceec8d04c81/apps/browser/crowdin.yml#L8
that currently only removes the approval on update. This was specifically set back in the day (2018) to prevent deleting translation for a small typo or missing comma fix.

https://developer.crowdin.com/configuration-file/?q=config#changed-strings-update

Removing that option, will always delete the translations when a source string changes.

If there is a desire to change the current behaviour, we should discuss this in a larger group internally.

2024-07-23 19:25 UTC, shane-melton commented on apps/browser/src/_locales/en/messages.json
Good to know @djsmith85! I did not know about that setting/feature, thank you for the context!

I talked with @danielleflinn more about this and she is okay with updating these strings in place and preserving their translations (while still invalidating them as described in the Crowdin docs) as it is only a minor punctuation change. I don't see any reason to change the Crowdin upload settings at this time and this lets us get around needing to change every source key.

@alec-livefront My apologies for the back and forth on this, but we should be able to go back to what you had originally and simply update the English messages to remove the hyphen and leave the key alone.

2024-07-29 23:09 UTC, shane-melton approved these changes
Changes look good! Thanks again for all the work on this and and apologies for the lost effort with changing all the keys initially.

2024-07-29 23:09 UTC, shane-melton commented on apps/browser/src/platform/popup/layout/popup-layout.stories.ts
> -
🎨 (non-blocking): If we remove this change we can avoid tagging the platform team.

2024-07-30 13:50 UTC, alec-livefront commented on apps/browser/src/platform/popup/layout/popup-layout.stories.ts
> -
Must of been my IDE 🤷 

[1f52205](https://github.com/bitwarden/clients/pull/10156/commits/1f52205a4648e5b8a2d58fd7fd0678da4de2ef1d)

2024-07-30 14:34 UTC, shane-melton submitted a review, later dismissed

2024-07-30 16:15 UTC, djsmith85 submitted a review, later dismissed

2024-07-31 14:21 UTC, jprusik approved these changes

2024-07-31 14:22 UTC, jprusik commented
There are some entries in the desktop and web message catalog too, but that can be addressed in other/followup work.

2024-08-01 16:05 UTC, jprusik approved these changes

2024-08-01 17:39 UTC, merged