[SM-1302] Initial config page
bitwarden/clients pull request #10196
Opened 2024-07-19 22:17 UTC by differsthecat

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/SM-1302

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-07-23 08:49 UTC, mzieniukbw requested changes
Copying from project list component can be simplified.
The copy component likely have a race condition and the services that pull the data should be part of RXJS pipe.

2024-07-23 08:49 UTC, mzieniukbw commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/config/config.component.ts
> +  selector: "sm-config",
```suggestion
  selector: "sm-service-account-config",
```

2024-07-23 08:49 UTC, mzieniukbw commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/config/config.component.ts
> +    const allProjects = await this.projectService.getProjects(this.organizationId);
my gut is teling me that the `organizationId` is populated async, so there might be a race condition here.
Can all of this be part of the rxjs ?

2024-07-23 08:49 UTC, mzieniukbw commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/projects-list.component.html
> +                (click)="copiedProjectUUIdEvent.emit(project.id)"
this component should have full ownership of the copying to clipboard. The event seems to be like an unnecessary complexity and could be simplied by calling the `copyProjectUuid`.
This would also require small changes to `copyProjectUuid` itself to be non-static and use the `I18nService` and `PlatformUtilsService` from the constructor

2024-07-23 08:49 UTC, mzieniukbw commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/projects-list.component.ts
> +  static copyProjectUuid(
Making it explicit on intention is better, by adding `clipboard` to name
```suggestion
  static copyProjectUuidToClipboard(
```

2024-07-23 08:49 UTC, mzieniukbw commented on apps/web/src/locales/en/messages.json
> +  "machineAccountProjects": {
```suggestion
  "projectsAccessedByMachineAccount": {
```

2024-07-23 13:59 UTC, differsthecat commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/config/config.component.ts
> +  selector: "sm-config",
I went back and forth on the naming, this is better and I will make that change!

2024-07-23 14:02 UTC, differsthecat commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/projects-list.component.html
> +                (click)="copiedProjectUUIdEvent.emit(project.id)"
I had the same thoughts but erred on leaving things how they were because it seemed intentional.

2024-07-23 14:54 UTC, mzieniukbw commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/projects-list.component.html
> +                (click)="copiedProjectUUIdEvent.emit(project.id)"
I understand that you might want to configure the behaviour of the edit, delete, new project events, but for this one it's self contained. Also the fact that we just delegate back to ProjectList component implementation, we might as well drop the events idea for this one.

2024-07-24 15:45 UTC, differsthecat commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/projects-list.component.html
> +                (click)="copiedProjectUUIdEvent.emit(project.id)"
Agreed, I'll work on fixing this 🙂

2024-07-24 17:47 UTC, differsthecat commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/config/config.component.ts
> +    const allProjects = await this.projectService.getProjects(this.organizationId);
Fixed in [this commit](https://github.com/bitwarden/clients/pull/10196/commits/a05dd4c678da0d2683d4d73e29725710670fec92)!

2024-07-25 22:19 UTC, Thomas-Avery requested changes
Awesome! Looking forward to this one.

2024-07-25 22:19 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/config/config.component.ts
> +  };
:thinking: 

The copy code in the copy functions are synchronous.

Should the async be removed? 

 ```suggestion
  copyIdentityUrl = () => {
    this.platformUtilsService.copyToClipboard(this.identityUrl);
    this.toastService.showToast({
      variant: "success",
      title: null,
      message: this.i18nService.t("valueCopied", this.i18nService.t("identityUrl")),
    });
  };
```

2024-07-29 11:31 UTC, mzieniukbw commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/config/config.component.ts
> +      .subscribe();
Just to add, the `this.loading = false;` should probably be part of subscribe too ?

2024-07-29 11:31 UTC, mzieniukbw commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/config/config.component.ts
> +  copyIdentityUrl = async () => {
why not a regular function / method ? 
```suggestion
  copyIdentityUrl() {
```

2024-07-29 11:31 UTC, mzieniukbw commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/projects-list.component.ts
> +      this.i18nService.t("valueCopied", this.i18nService.t("uuid")),
shoudln't this be `projectId` from locale's ?
(Also needs to be added to messages.json)

2024-07-29 18:31 UTC, differsthecat commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/config/config.component.ts
> +      .subscribe();
Updated, and moved `this.loading` to the subscribe 🙂

2024-07-29 18:33 UTC, differsthecat commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/config/config.component.html
> +        <input bitInput type="text" [(ngModel)]="identityUrl" [disabled]="true" />
I did stick with a template-driven form here because it is read-only and simpler. There is no need for a reactive form because these inputs are not updated for the user. I can change it to reactive if we feel that is better to do for consistency!

2024-07-29 18:37 UTC, differsthecat commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-account.component.html
> +    <bit-tab-link [route]="['config']">Config</bit-tab-link>
Whoops, missed this one. Fixed! https://github.com/bitwarden/clients/pull/10196/commits/c5500f04c478cc3ba42b4686bc5635309777d2d0

2024-07-29 18:41 UTC, differsthecat commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/config/config.component.ts
> +  };
Yes, I copied these from another page and missed those :cone-of-shame:
Fixed: https://github.com/bitwarden/clients/pull/10196/commits/b952c928d7945a4c457d2b5b9a1fdcce545e1643

2024-07-29 18:41 UTC, differsthecat commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/config/config.component.ts
> +  copyIdentityUrl = async () => {
Fixed! https://github.com/bitwarden/clients/pull/10196/commits/b952c928d7945a4c457d2b5b9a1fdcce545e1643

2024-07-29 18:45 UTC, differsthecat commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/projects-list.component.ts
> +      this.i18nService.t("valueCopied", this.i18nService.t("uuid")),
I used the key that other places we copy Id's use, but I don't mind being more explicit; fixed: https://github.com/bitwarden/clients/pull/10196/commits/c144d80271a50b0d22b2d1b28aa6b373af54b091

2024-07-29 19:40 UTC, Thomas-Avery submitted a review, later dismissed
LGTM

2024-07-30 09:39 UTC, mzieniukbw requested changes
One typo, few promise simplifications

2024-07-30 09:39 UTC, mzieniukbw commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/config/config.component.ts
> +class serviceAccountConfig {
Uppercase letter
```suggestion
class ServiceAccountConfig {
```

2024-07-30 09:39 UTC, mzieniukbw commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/config/config.component.ts
>        .then((policies) => {
We already do await, so there is no point in doing "then"
```
var policies =  await this.accessPolicyService.getServiceAccountGrantedPolicies(organizationId, serviceAccountId);

const ids = policies.grantedProjectPolicies.map(
          (policy) => policy.accessPolicy.grantedProjectId,
);

smConfig.projects = allProjects.filter((project) =>
          ids.some((projectId) => projectId === project.id),
);
```

---

Also i think it's better to keep the `const smConfig` immutable, so it's better to create a `const projects` variable when getting the projects and at the very end just return
```
return {
     organizationId: organizationId,
      serviceAccountId: serviceAccountId,
      identityUrl: environment.getIdentityUrl(),
      apiUrl: environment.getApiUrl(),
      projects: projects,
} as ServiceAccountConfig;
```

2024-07-30 14:05 UTC, differsthecat commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/config/config.component.ts
>        .then((policies) => {
Great catches! 
fixed here: https://github.com/bitwarden/clients/pull/10196/commits/21e333c8d96cab9348286e8151439d619d5f2dce

2024-07-30 14:58 UTC, mzieniukbw commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/config/config.component.ts
> +    projects = allProjects.filter((project) => ids.some((projectId) => projectId === project.id));
How about initialising the `projects` variable here instead of above ?
```suggestion
    const projects = allProjects.filter((project) => ids.some((projectId) => projectId === project.id));
```

2024-07-30 15:31 UTC, mzieniukbw submitted a review, later dismissed

2024-07-30 20:49 UTC, mzieniukbw submitted a review, later dismissed

2024-09-17 10:56 UTC, mzieniukbw requested changes
Small simplification request

2024-09-17 10:56 UTC, mzieniukbw commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/config/config.component.ts
> +    }
With this change, the `const projects` is now identical to `policies.grantedProjectPolicies` - so it makes sense to change it to be build from `policies.grantedProjectPolicies` and not from `allProjects`. That way you don't need to filter the list and the only thing that needs to be mapped is `linkable`, which can only be true, if the `projectId` is in `allProjects`.
```suggestion
    const projects = policies.grantedProjectPolicies.map((policy) => {
        return {
            id: policy.accessPolicy.grantedProjectId,
            name: policy.accessPolicy.grantedProjectName,
            organizationId: organizationId,
            linkable: allProjects.some((project) => project.id === policy.accessPolicy.grantedProjectId),
          } as ProjectListView;
    });
```

2024-09-20 08:16 UTC, mzieniukbw submitted a review, later dismissed

2024-09-20 16:24 UTC, mzieniukbw approved these changes

2024-09-20 16:41 UTC, tangowithfoxtrot approved these changes
LGTM 🚀

2024-09-20 16:54 UTC, merged