[PM-9969] Papercut - Update component library storybook docs
bitwarden/clients pull request #10191
Opened 2024-07-19 17:59 UTC by jprusik

## 🎟️ Tracking

PM-9969

## 📔 Objective

Add component import examples, clean up some html/formatting nits

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-07-19 18:01 UTC, jprusik commented on libs/components/src/badge/badge.stories.ts
> +      <br /><br />
I used the prettier-preferred format for these tags

2024-08-07 14:48 UTC, willmartian requested changes
Thanks for this! A few suggestions:

2024-08-07 14:48 UTC, willmartian commented on libs/components/src/dialog/dialog/dialog.mdx
> +```
```suggestion
```ts
import { DialogModule, DialogService } from "@bitwarden/components";
```
```

2024-08-07 14:48 UTC, willmartian commented on libs/components/src/badge/badge.mdx
> +import { CardComponent } from "@bitwarden/components";
```suggestion
import { BadgeModule } from "@bitwarden/components";
```

2024-08-07 14:48 UTC, willmartian commented on libs/components/src/dialog/simple-dialog/simple-dialog.mdx
> +import { DialogService } from "@bitwarden/components";
Module is necessary if you are authoring a dialog; service is necessary if you are triggering one

```suggestion
import { DialogModule, DialogService } from "@bitwarden/components";
```

2024-08-07 14:49 UTC, willmartian commented on libs/components/src/dialog/dialog/dialog.mdx
> +import { DialogService } from "@bitwarden/components";
```suggestion
import { DialogModule, DialogService } from "@bitwarden/components";
```

2024-08-07 14:52 UTC, jprusik commented on libs/components/src/badge/badge.mdx
> +import { CardComponent } from "@bitwarden/components";
Ah, bad copy-paste; thanks

2024-08-07 14:52 UTC, willmartian approved these changes
:shipit: Thanks!

2024-08-07 14:53 UTC, jprusik commented on libs/components/src/dialog/simple-dialog/simple-dialog.mdx
> +import { DialogService } from "@bitwarden/components";
💡

2024-08-07 15:13 UTC, merged