[PM-10079 add keyboard shortcut to autofill identity and credit cards
bitwarden/clients pull request #10254
Opened 2024-07-24 20:44 UTC by cagonzalezcs

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-07-25 17:54 UTC, jprusik commented on apps/browser/src/_locales/en/messages.json
> +  },
I think we're wholesale moving to "autofill" over "auto-fill" now, but double-check with @danielleflinn

2024-07-25 18:04 UTC, danielleflinn commented on apps/browser/src/_locales/en/messages.json
> +  },
Correct! We should be using "Autofill"

2024-07-25 18:04 UTC, jprusik commented on libs/common/src/vault/services/cipher.service.ts
> +      .filter((cipher) => cipher.deletedDate == null && type.includes(cipher.type));
Does it make sense to do the filter first, then the sort, just to cut down on potential iterations?

2024-07-25 18:05 UTC, cagonzalezcs commented on apps/browser/src/_locales/en/messages.json
> +  },
I believe that's the case... for these two translations, I used the pre-existing translation used by the login cipher keyboard shortcut

2024-07-25 18:09 UTC, jprusik commented on apps/browser/src/_locales/en/messages.json
> +  },
I think we can update them now if it's easy, but not a blocker either way.

2024-07-25 18:18 UTC, jprusik approved these changes
a couple non-blocking nits, but LGTM

2024-07-25 18:29 UTC, jprusik commented
BIT run:
https://github.com/bitwarden/browser-interactions-testing/actions/runs/10099119859

2024-07-25 18:31 UTC, danielleflinn commented on apps/browser/src/_locales/en/messages.json
> +  },
Agreed that we can update them now. We can also treat these as a "punctuation" update so we don't lose existing CrowdIn translations. For updating their "auto-fill" strings, Vault just "updated the source strings without changing the keys."

2024-07-25 18:44 UTC, cagonzalezcs commented on libs/common/src/vault/services/cipher.service.ts
> +      .filter((cipher) => cipher.deletedDate == null && type.includes(cipher.type));
Good call

2024-07-25 18:44 UTC, cagonzalezcs commented on apps/browser/src/autofill/background/notification.background.ts
> +    if (["autofill_login", "autofill_card", "autofill_identity"].includes(retryCommand)) {
Good call, I've set up an enum for this.

I'm holding off for now on updating all references to these... but will do that in a follow up PR.

2024-07-25 18:44 UTC, cagonzalezcs commented on apps/browser/src/_locales/en/messages.json
> +  },
It has been updated

2024-07-29 18:43 UTC, shane-melton requested changes
Just one small nit for Vault owned changes. Otherwise, looks good!

2024-07-29 18:43 UTC, shane-melton commented on libs/common/src/vault/services/cipher.service.ts
> +  async getAllDecryptedCiphersOfType(type: CipherType[]): Promise<CipherView[]> {
⛏️ We can mark this as private as it is only used internally.

2024-07-30 17:56 UTC, cagonzalezcs commented on libs/common/src/vault/services/cipher.service.ts
> +  async getAllDecryptedCiphersOfType(type: CipherType[]): Promise<CipherView[]> {
Good call, I've changed the method to be `private`.

I think the reason I originally set it as `public` was because I think I can use the method in the `OverlayBackground` class... but I'll make that change when/if I need to use this method in that context.

2024-07-30 17:57 UTC, shane-melton approved these changes
Vault changes look good!

2024-07-31 11:18 UTC, dani-garcia approved these changes
Excited about this! Platform changes are good

2024-07-31 14:05 UTC, jprusik approved these changes

2024-07-31 17:52 UTC, merged