[PM-7306] Onboarding users to new UI
bitwarden/clients pull request #10267
Opened 2024-07-25 13:57 UTC by gbubemismith

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-07-25 16:26 UTC, danielleflinn submitted a review, later dismissed

2024-07-29 19:11 UTC, shane-melton requested changes

2024-07-29 19:11 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/vault-ui-onboarding/vault-ui-onboarding.component.ts
> +        <a bitButton href="#" buttonType="primary" bitDialogClose (click)="navigateToLink()">
❓ Do we need the `href` attribute here?

2024-07-29 19:11 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/vault-ui-onboarding/vault-ui-onboarding.component.ts
> +        <a bitButton href="#" buttonType="primary" bitDialogClose (click)="navigateToLink()">
❓ Also, do we want the dialog to close when they click to navigate? I see we have it opening in a new window, should we keep the dialog open? I believe this only concerns the Popout as the popup will likely close automatically once the new window is opened. cc: @danielleflinn

2024-07-29 19:50 UTC, danielleflinn commented on apps/browser/src/vault/popup/components/vault-v2/vault-ui-onboarding/vault-ui-onboarding.component.ts
> +        <a bitButton href="#" buttonType="primary" bitDialogClose (click)="navigateToLink()">
@shane-melton I think we are ok with closing the dialog when the user selects the "Learn more" link. The main thing we want to do here is inform the user that the new UI is expected, and by clicking the navigation link I expect the user will be informed enough that they don't need to / or expect to see the dialog again.

2024-07-29 19:51 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/vault-ui-onboarding/vault-ui-onboarding.component.ts
> +        <a bitButton href="#" buttonType="primary" bitDialogClose (click)="navigateToLink()">
Sounds good to me!

2024-07-29 19:52 UTC, gbubemismith commented on apps/browser/src/vault/popup/components/vault-v2/vault-ui-onboarding/vault-ui-onboarding.component.ts
> +        <a bitButton href="#" buttonType="primary" bitDialogClose (click)="navigateToLink()">
The href can be removed

2024-07-29 19:52 UTC, gbubemismith commented on apps/browser/src/vault/popup/components/vault-v2/vault-ui-onboarding/vault-ui-onboarding.component.ts
> +        <a bitButton href="#" buttonType="primary" bitDialogClose (click)="navigateToLink()">
I don't think you can get the onboarding dialog to show in the popout, cause clicking outside the dialog in the extension closes the dialog and sets the state

2024-07-29 19:52 UTC, gbubemismith commented on apps/browser/src/vault/popup/components/vault-v2/vault-ui-onboarding/vault-ui-onboarding.component.ts
> +      <path fill="#fff" d="M0 0h86v74H0z"/>
I think the hex might be okay in this case cause It doesn't do much, but I am OK to change to tailwind classes to keep it consistent

2024-07-29 20:09 UTC, shane-melton approved these changes

2024-07-29 22:15 UTC, danielleflinn approved these changes

2024-07-30 13:31 UTC, nick-livefront approved these changes

2024-07-30 13:31 UTC, nick-livefront commented on apps/browser/src/vault/popup/services/vault-ui-onboarding.service.ts
> +  // TODO: Update this date to the release date of the new Browser UI
❓ Is there a ticket associated with this TODO? I just don't want it to get forgotten about

2024-07-30 15:35 UTC, gbubemismith commented on apps/browser/src/vault/popup/services/vault-ui-onboarding.service.ts
> +  // TODO: Update this date to the release date of the new Browser UI
Yeah we have a ticket tracking this

2024-07-30 15:44 UTC, justindbaur approved these changes

2024-07-30 15:45 UTC, merged