Release arm64 binaries for macOS
bitwarden/clients pull request #10273
Opened 2024-07-25 22:36 UTC by jomifepe

## 🎟️ Tracking

https://github.com/orgs/bitwarden/discussions/10219

Other related discussions:
- https://github.com/orgs/bitwarden/discussions/8221
- https://community.bitwarden.com/t/arm-support-for-cli/42362
- https://community.bitwarden.com/t/release-macos-arm64-version-of-cli/63985/2

## 📔 Objective

It has been years since arm64 became the standard for macs, and this PR aims to tweak the build ci workflow to release those. It releases two new binaries: `bw-macos-arm64-*.zip` and `bw-oss-macos-arm64-*.zip `. Here is a successful run of this new build script: https://github.com/jomifepe/clients/actions/runs/10050097941.

## 📸 Screenshots

![Screenshot 2024-07-25 at 23 26 08](https://github.com/user-attachments/assets/b1b56995-15b7-49c7-b2b5-f12676b4a82c)
![Screenshot 2024-07-25 at 23 32 36](https://github.com/user-attachments/assets/69495356-7819-4803-b42f-a55b8b10f2e6)
![Screenshot 2024-07-25 at 23 33 15](https://github.com/user-attachments/assets/8d02208c-ac10-4293-a1f1-2b6cf8bd0c12)

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-08-27 09:33 UTC, jomifepe commented
I hope this doesn't get ignored like the previous attempts.

I know the CLI is low priority, but is there any other reason why this would not be desirable?

2024-12-26 22:23 UTC, jomifepe commented
@djsmith85 Any chance this will move forward?

2025-02-20 19:35 UTC, vgrassia requested changes
Hi @jomifepe, 

Thank you for your contribution. I only found one thing that needs to change:

- The `Build & Package Unix` step (Line 108) should include `target_suffix`.
```
npm run dist:${{ matrix.license_type.build_prefix }}:${{ env.SHORT_RUNNER_OS }}${{ matrix.os.target_suffix }} --quiet
```

2025-02-21 00:17 UTC, vgrassia approved these changes

2025-02-24 08:39 UTC, coroiu approved these changes
Thank you for you contribution!

2025-02-24 15:24 UTC, merged