[PM-6125] Handle kp.alg is string
bitwarden/clients pull request #10285
Opened 2024-07-26 11:33 UTC by coroiu

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-6125

## 📔 Objective

Converts `kp.alg` to numbers. This PR is based on https://github.com/bitwarden/clients/pull/7832 but moves the fix to outside the `Fido2Client` so that we can keep that service strictly spec-compliant.

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-07-29 16:36 UTC, shane-melton requested changes

2024-07-29 16:36 UTC, shane-melton commented on apps/browser/src/vault/fido2/webauthn-utils.ts
> +        .filter((params) => isNaN(params.alg)),
⚠️ I believe we want `.filter((params) => !isNaN(params.alg)),` to exclude any NaN values

2024-07-30 18:50 UTC, shane-melton submitted a review, later dismissed

2024-08-12 15:40 UTC, jprusik approved these changes

2024-08-12 17:23 UTC, shane-melton approved these changes

2024-08-19 08:17 UTC, merged