[BEEEP] [PM-10117] Migrate the 404 page
bitwarden/clients pull request #10286
Opened 2024-07-26 12:11 UTC by Hinton

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-10117

## 📔 Objective

Migrate the index.html to use tailwind instead of bootstrap styling.

## 📸 Screenshots

https://github.com/user-attachments/assets/9fd3974b-64ce-4f13-99a8-9c1396906a31

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-08-12 15:50 UTC, Hinton commented on apps/web/src/index.html
> +    <title page-title>Bitwarden Web vault</title>
To keep it consistent to other places. The Angular apps uses lowercase.

2024-08-12 15:51 UTC, Hinton commented on apps/web/src/scss/tailwind.css
> +  img.new-logo-themed {
Because `logo-themed` is already taken. 😢

2024-08-12 15:52 UTC, Hinton commented on apps/web/src/404.html
> +    <img class="new-logo-themed tw-m-8" alt="Bitwarden" />
We could do that, but I would need to move. the classes to a div to maintain the design.

2024-08-12 18:57 UTC, rr-bw requested changes
This looks great on web, but will break the logo on Desktop and I believe Browser when the email verification FF is turned on. Here is a screenshot on the `/signup` page on Desktop, which you get to by clicking "Create account" on the login page.

<img width="865" alt="Screenshot 2024-08-12 at 11 51 47 AM" src="https://github.com/user-attachments/assets/6dafa0cf-d436-4f5a-a9ed-3908220938c3">

2024-08-13 16:55 UTC, Hinton commented on libs/auth/src/angular/anon-layout/anon-layout.component.html
> +  <bit-icon *ngIf="!hideLogo" [icon]="logo" class="tw-w-[128px] [&>*]:tw-align-top"></bit-icon>
This was needed to ensure consistency between the loading page and angular.

2024-08-13 16:55 UTC, Hinton commented
@rr-bw I rolledback the changes to annon-layout.

2024-08-15 23:07 UTC, rr-bw approved these changes

2024-08-20 19:04 UTC, vleague2 approved these changes
Reminder to approve UI tests!

2024-08-26 16:15 UTC, merged