[BEEEP] [PoC] SSH Agent for Bitwarden Desktop
bitwarden/clients pull request #10293
Opened 2024-07-26 16:52 UTC by quexten

## 🎟️ Tracking

-
## 📔 Objective

> [!WARNING]  
> DO NOT MERGE This is a proof-of-concept PR for discussion. It still needs quite some work, to work properly and securely and also ssh-keys as an additional item type to be ready.

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-07-30 13:06 UTC, Hinton commented on apps/desktop/desktop_native/Cargo.lock
This is not a review, just an observation.

We add a significant amount of new dependencies here. The russh crates seems to be fairly dependency heavy and we should evaluate that we actually need everything they offer. Some things I noticed is they seem to support most key types which while good is probably not really required.

I previously glanced at the https://github.com/sekey project as a potential base for this feature.

2024-07-30 13:21 UTC, quexten commented on apps/desktop/desktop_native/Cargo.lock
Fair point. We can probably slim this down a bit (this is just a PoC). Not sure where the trade-off is with us having to pull in additional dependencies, or having to maintain them ourselves. Looks like sekey f.e is not maintained.

2024-07-30 13:46 UTC, quexten commented on apps/desktop/desktop_native/Cargo.lock
After looking into this, about half of the cargo lock changes were caused by completely unnecessary deps left over from development (now removed). futures and async traits can also probably be dropped with a few tweaks.

2024-07-30 14:38 UTC, Hinton commented on apps/desktop/desktop_native/Cargo.lock
Nice, that's a significant improvement. I wonder if the russh team are open to feature flagging various crypto types.

2024-07-30 16:32 UTC, quexten commented on apps/desktop/desktop_native/Cargo.lock
Not exactly sure from the product side, but if we want to allow import of ssh keys (not just generating from within bitwarden), we probably need many of the crypto / encoding deps to support decoding / decrypting the different (optionally password protected) ssh formats anyways :/

I did check again, and openssl is completely optional for both using the keys and generating / parsing them. So at least there is no blocker from adding it to sdk/a wasm module for web / browser.

Crypto implementations seem to mostly be from: https://github.com/RustCrypto

2024-08-22 13:53 UTC, quexten commented on apps/desktop/desktop_native/Cargo.lock
Removed `russh-keys` and configured the feature flags for `ssh-key` to exclude ecdsa / other unneeded things.

2024-08-27 11:36 UTC, dani-garcia reviewed
Not a full review as I haven't familiarised myself completely with the SSH agent protocol and I haven't had time to test this, but some initial comments around the Rust code.

Looks like a great start to me!

2024-08-27 11:36 UTC, dani-garcia commented on apps/desktop/desktop_native/core/src/ssh_agent/mod.rs
> +        self.send_tx.send(ssh_key.cipher_uuid.clone()).await.unwrap();
Nit: I don't think this clone is needed here, we're taking the key by value:
```suggestion
        self.send_tx.send(ssh_key.cipher_uuid).await.unwrap();
```

2024-08-27 11:36 UTC, dani-garcia commented on apps/desktop/desktop_native/core/src/ssh_agent/mod.rs
> +    std::fs::remove_file(sockname).unwrap_or_default();
I presume unwrap_or_default is used here to ignore the error if the file doesn't exist?
I think it would be clearer like this:
```suggestion
    let _ = std::fs::remove_file(sockname);
```

2024-08-27 11:36 UTC, dani-garcia commented on apps/desktop/desktop_native/core/src/ssh_agent/namedpipelistenerstream.rs
> +        }
Suggestion: I think you can replace this by just mapping the value

```suggestion
        this.rx.poll_recv(cx).map(|v| v.map(Ok))
```

2024-08-27 11:36 UTC, dani-garcia commented on apps/desktop/desktop_native/core/src/ssh_agent/ssh_agent.rs
> +    fn confirm(&self, _pk: Key) -> impl std::future::Future<Output = bool> + std::marker::Send {
Tiny nit: Send should be in the rust prelude and so it doesn't need to be fully qualified.
```suggestion
    fn confirm(&self, _pk: Key) -> impl std::future::Future<Output = bool> + Send {
```

2024-08-27 11:36 UTC, dani-garcia commented on apps/desktop/desktop_native/napi/src/lib.rs
> +                if let Err(e) = promise_result {
This if let should probably be replaced by a match, that way you don't have to manually unwrap it in the else block.

Same with the other if let in line 190

2024-08-27 11:36 UTC, dani-garcia commented on apps/desktop/desktop_native/core/src/ssh_agent/mod.rs
> +static KEYSTORE: std::sync::LazyLock<ssh_agent::KeyStore> =
I don't like the idea of having global mutable state very much, what do you think of creating a struct to contain this that gets initialized from TS?

Something like this:

```rust
struct SshAgent {
    // We move the keystore into this struct
    keystore: Keystore
}

// And all the previously freestanding functions are a part of the struct now
impl SshAgent {
    // This needs to return the instance now
    pub async fn start_server(...) -> Result<Self> {}

    pub fn set_keys(...) -> Result<()> {}
    pub fn lock() -> Result<()> {}
}
```

Then we can have the NAPI serve function return the instance and have the TS code hold a reference to it in the service.

For example, this is similar to what I'm doing with the IPC server:
NAPI lib: 
https://github.com/bitwarden/clients/blob/e511630d4a984d1f151f4b173a225decccb0aed1/apps/desktop/desktop_native/napi/src/lib.rs#L234-L274

Server being stored in a TS service: https://github.com/bitwarden/clients/blob/e511630d4a984d1f151f4b173a225decccb0aed1/apps/desktop/src/main/native-messaging.main.ts#L80

2024-08-27 11:36 UTC, dani-garcia commented on apps/desktop/desktop_native/core/src/ssh_agent/mod.rs
> +pub async fn set_keys(new_keys: Vec<(String, String, String)>) -> Result<(), anyhow::Error> {
This and `lock` don't seem to be awaiting anything so they probably don't need to be async

2024-08-27 11:36 UTC, dani-garcia commented on apps/desktop/desktop_native/core/src/ssh_agent/mod.rs
> +    }
This can be simplified by doing this instead, which would save us a few clones:
```rust
        keystore.iter_mut().for_each(|(_public_key, key)| {
            key.private_key = None;
        });
```

The `ssh_key::private::PrivateKey` internally implement Zeroize on Drop for their `KeypairData`, so that should ensure they are cleared from memory.

2024-08-27 11:45 UTC, quexten commented on apps/desktop/desktop_native/core/src/ssh_agent/mod.rs
> +static KEYSTORE: std::sync::LazyLock<ssh_agent::KeyStore> =
Yeah, that sounds good. I do wonder whether Drop would need to do cleanup to clean the sockets (on both windows named pipes and unix streams).

2024-08-28 13:28 UTC, quexten commented on apps/desktop/desktop_native/core/src/ssh_agent/mod.rs
> +static KEYSTORE: std::sync::LazyLock<ssh_agent::KeyStore> =
Drop/CancelleationToken are not implemented yet, but removed the global state and holding the state in the typescript service now.

2024-08-30 15:04 UTC, audreyality requested changes

2024-08-30 15:04 UTC, audreyality commented on apps/desktop/desktop_native/core/src/ssh_agent/msg.rs
⚠️ This code does not have a CLA, and bitwarden may not want to accept the license terms from the source. As of Google v Oracle, we shouldn't be copying symbols.

2024-08-30 15:04 UTC, audreyality commented on apps/desktop/src/app/tools/sshkey-generator.component.html
❌ Please remove the generator code. I don't want to take on code that I'll have to rewrite to use the credential generator services. Let's meet up to talk about how to rework this logic to flow through the new system, and merge it in a separate PR.

2024-08-30 15:11 UTC, quexten commented on apps/desktop/desktop_native/core/src/ssh_agent/msg.rs
Thoughts about just switching this to the naming from https://datatracker.ietf.org/doc/draft-miller-ssh-agent/ 
(and removing the constants we don't use, i.e reduce to:

```
SSH_AGENTC_REQUEST_IDENTITIES                  11
SSH_AGENTC_SIGN_REQUEST                        13
```

?

2024-08-30 15:23 UTC, audreyality commented on apps/desktop/desktop_native/core/src/ssh_agent/msg.rs
@patrick-bitwarden - I think this is a place where you'll need to step in. I know the issues that can arise with licenses, but copyright licensing is Legit Legal Stuff. Here's the relevant license for IETF docs: https://trustee.ietf.org/documents/trust-legal-provisions/

There are also questions as to whether the Apache-2.0 code I pointed out above can be used.

@quexten - As far as the file is concerned, assuming we can use the tables, you should include all of the relevant values. The compiler should be able to tree-shake the unused ones, and completeness will keep the code from churning if we later expand our usage.

2024-08-30 15:25 UTC, quexten commented on apps/desktop/desktop_native/core/src/ssh_agent/russh_encoding/mod.rs
The idea here was to not have to include the whole russh crate. Is forking russh into a separate repo, reducing it to the 1 file (which is in accordance with the apache license) and importing that a better option?

2024-08-30 15:27 UTC, audreyality commented on apps/desktop/desktop_native/core/src/ssh_agent/russh_encoding/mod.rs
This is a legal question, not a technical one. :(

2024-09-02 10:41 UTC, quexten commented
> I haven't gotten around to reviewing this @quexten. @dani-garcia is re-writing the IPC in #9894 which is getting closer to being merged and is also being used in the passkey PoC. As I understand it we will be using IPC logic here as part of NamedPipeServerStream. Should we be streamlining this to use the same IPC logic for ssh agent?

I asked @dani-garcia the same question, however I don't think it's possible since we are not doing IPC with another bitwarden process, but instead providing the SSH_AUTH_SOCK / on windows the named pipe that external programs (ssh/git/rsync/etc.) consume? (@dani-garcia feel free to correct me here if I'm missing something)

2024-09-02 10:59 UTC, dani-garcia commented
> > I haven't gotten around to reviewing this @quexten. @dani-garcia is re-writing the IPC in #9894 which is getting closer to being merged and is also being used in the passkey PoC. As I understand it we will be using IPC logic here as part of NamedPipeServerStream. Should we be streamlining this to use the same IPC logic for ssh agent?
> 
> I asked @dani-garcia the same question, however I don't think it's possible since we are not doing IPC with another bitwarden process, but instead providing the SSH_AUTH_SOCK / on windows the named pipe that external programs (ssh/git/rsync/etc.) consume? (@dani-garcia feel free to correct me here if I'm missing something)

Yeah, with the SSH agent we're fairly constrained on what we can do by the protocol, so I don't know if there's much logic to reuse there with what we're doing for IPC between Bitwarden owned processes. I think the next step for us in this field could involve improving on the Rust IPC module and moving the message authentication and encryption into it so the code can be reused between passkeys and browser integration, and that won't be something useful for this use case.

We're currently using the `interprocess` crate to abstract over the UNIX socket / Windows named pipe separation though, so we might also be able to use that here, but that's honestly only a very small part of the code.

2024-09-03 16:33 UTC, quexten commented on apps/desktop/desktop_native/core/src/ssh_agent/msg.rs
All of the licensing issues will be resolved by importing the `bitwarden-russh` crate instead, which will have whatever modifications we need (https://github.com/bitwarden/bitwarden-russh/pull/1).

2024-09-03 17:18 UTC, audreyality commented on apps/desktop/desktop_native/core/src/ssh_agent/msg.rs
Has this been confirmed? Don't just rely on what we discussed offline.

2024-09-03 17:23 UTC, quexten commented on apps/desktop/desktop_native/core/src/ssh_agent/msg.rs
I should have made that clearer, but yes, this has been discussed by @patrick-bitwarden , @Hinton and @trmartin4.

2024-09-04 09:05 UTC, quexten commented on apps/desktop/src/app/tools/sshkey-generator.component.html
The generator component has been removed. The current behaviour is to generate an ed25519 key when creating a new ssh key cipher (without any component/modal).

2024-09-04 12:40 UTC, audreyality approved these changes

2024-09-10 12:32 UTC, coroiu reviewed
Haven't gone through the entire PR yet, but submitting what I have so far before I disappear into meetings for the rest of the day :)

2024-09-10 12:32 UTC, coroiu commented on apps/desktop/src/platform/preload.ts
> +    await ipcRenderer.invoke("sshagent.signrequestresponse", { id: id, accepted: accepted });
suggestion: simplify 
```suggestion
    await ipcRenderer.invoke("sshagent.signrequestresponse", { id, accepted });
```

2024-09-10 12:32 UTC, coroiu commented on apps/desktop/src/platform/preload.ts
> +    return await ipcRenderer.invoke("sshagent.generatekey", { keyAlgorithm: keyAlgorithm });
suggestion: simplify
```suggestion
    return await ipcRenderer.invoke("sshagent.generatekey", { keyAlgorithm });
```

2024-09-11 13:22 UTC, quexten commented on apps/desktop/src/vault/app/vault/add-edit.component.html
> +<ng-template #sshGenerator></ng-template>
Left over from when this PR added generator, but this was removed and will be re-added in a followup PR based on tools new generator infrastructure. 

Removing this.

2024-09-11 13:31 UTC, quexten commented on apps/desktop/src/platform/services/renderer-ssh-agent.service.ts
> +      const noteCiphers = ciphers.filter(
Yeah, left over from the first BEEEP PoC.

2024-09-11 13:33 UTC, quexten commented on apps/desktop/src/platform/preload.ts
> +    });
> question: are we sending the key back into rust to decode and extract the private key?

Yes, the module in rust verifies it's a valid openssh formatted private key, and generates the corresponding public key and fingerprint. Later on we might also support parsing pkcs#8 formatted, and encrypted private keys. These would be decrypted in rust, and saved as openssh formatted keys on the cipher in order to just have one format.

2024-09-11 15:12 UTC, quexten commented on apps/desktop/src/platform/services/renderer-ssh-agent.service.ts
> +      }
Hmm, it would be neat if `decryptCiphers(ciphers: Cipher[], userId: UserId)` was public in cipherservice, so we don't ever have to "getAllDecrypted", but instead just decrypt the ssh ciphers (which we can filter while encrypted).

2024-09-11 15:38 UTC, quexten commented on apps/desktop/src/platform/services/renderer-ssh-agent.service.ts
> +        (async () => {
Just me not knowing RxJS enough. Replaced with pipe + switchmap.

2024-09-11 15:38 UTC, quexten commented on apps/desktop/src/platform/services/renderer-ssh-agent.service.ts
> +          }
Implemented this

2024-09-11 16:23 UTC, quexten commented on apps/desktop/src/vault/app/vault/add-edit.component.ts
> +import { sshagent } from "desktop_native/napi";
So instead, should we duplicate the "importresult" and import status enum and map them in main?

2024-09-12 08:55 UTC, coroiu reviewed
Just a few more comments

@quexten a thought I had was that we will probably want to document this in a similar way to https://contributing.bitwarden.com/architecture/deep-dives/passkeys/implementations/provider/browser-extension

2024-09-12 08:55 UTC, coroiu commented on apps/browser/src/_locales/en/messages.json
> +    "message": "Ssh key"
issue?: This I'm not so sure about. We don't capitalize acronyms in the code but when it comes to user facing strings we might still want to do that

2024-09-12 08:55 UTC, coroiu commented on apps/desktop/desktop_native/core/src/ssh_agent/mod.rs
> +            println!("[Ssh Agent Native Module] Starting Ssh Agent server on {:?}", ssh_path);
nit: did you do a find-all/replace-all? 😂 I'm guessing `BITWARDEN_SSH_AUTH_SOCK` shouldn't be changed `BITWARDEN_Ssh_AUTH_SOCK`

2024-09-12 08:55 UTC, coroiu commented on apps/desktop/desktop_native/napi/src/lib.rs
>      }
suggestion: Using `///` will let the IDE pick these up properly
```suggestion
    pub enum SshKeyImportStatus {
        /// ssh key was parsed correctly and will be returned in the result
        Success,
        /// ssh key was parsed correctly but is encrypted and requires a password
        PasswordRequired,
        /// ssh key was parsed correctly, and a password was provided when calling the import, but it was incorrect
        WrongPassword,
        /// ssh key could not be parsed, either due to an incorrect / unsupported format (pkcs#8) or key type (ecdsa), or because the input is not an ssh key
        ParsingError,
    }
```

2024-09-12 08:55 UTC, coroiu commented on apps/desktop/src/platform/services/renderer-ssh-agent.service.ts
> +export class RendererSshAgentService implements OnDestroy {
nit(non-blocking): we don't usually prefix web services with `renderer` since these are by far the most common services we have and then everything would be named `renderer`

2024-09-12 08:55 UTC, coroiu commented on apps/desktop/src/platform/services/renderer-ssh-agent.service.ts
> +        switchMap(async (message: any) => {
question: Do we support multiple requests being active at the same time?

**Why am I asking this?**
When the parent observable emits, `switchMap` will try to cancel the previous request (by unsubscribing to the internal observable) and start a new one for the new emit instead. Since we are using a promise as the `switchMap` callback, cancelling is not supported since there is no observable to unsubscribe from. The resulting behavior is that both callbacks/requests will be active at the same time. 

IF we don't support this then we need to either:

  1. Switch to `concatMap` which makes sure that the previous request has finished before starting a new one
  2. Rewrite the `switchMap` promise callback into an observable callback and make sure that we are creating a proper observable pipeline by not using `firstValueFrom` and refactoring the timeout to be rxjs-based. It's also possible to implement abort and clean-up logic using `AbortController`, but I wouldn't recommend it.

(2) is probably what we want, since (1) will cause the subsequent requests to have to wait for timeouts. I'd love to help out if choose this path and feel that you might need some guidance with rxjs, just send me a ping on slack and we can do some pair programming!

2024-09-12 08:55 UTC, coroiu commented on apps/desktop/src/platform/services/renderer-ssh-agent.service.ts
> +          }
issue: sorry, I forgot about the path that was clearing keys!

```suggestion
    combineLatest([
      timer(0, this.SSH_REFRESH_INTERVAL),
      this.desktopSettingsService.sshAgentEnabled$,
    ])
      .pipe(
        concatMap(async ([_, sshAgentEnabled]) => {
          if (!sshAgentEnabled) {
            await ipc.platform.sshagent.setKeys([]);
            return;
          }

          const ciphers = await this.cipherService.getAllDecrypted();
          if (ciphers == null) {
            await ipc.platform.sshAgent.lock();
            return;
          }
```

2024-09-12 08:55 UTC, coroiu commented on apps/desktop/src/platform/services/renderer-ssh-agent.service.ts
> +  }
Oh you moved it down here! Hmm, both are probably ok, up to you!

2024-09-12 08:55 UTC, coroiu commented on apps/desktop/src/platform/services/renderer-ssh-agent.service.ts
>            });
suggestion: since you added `takeUntil(this.destroy$)` further down, don't forget to add it here too

2024-09-12 08:59 UTC, coroiu commented on apps/desktop/src/vault/app/vault/add-edit.component.ts
> +import { sshagent } from "desktop_native/napi";
I'm honestly not sure, @Hinton do you know if importing the `napi` module into angular code like this might cause issues in the future? Or are we good as long as we don't try to require the native bindings? E.g 
```
nativeBinding = require('@bitwarden/desktop-napi-android-arm64')
```

2024-09-12 09:10 UTC, quexten commented on apps/desktop/desktop_native/core/src/ssh_agent/mod.rs
> +            println!("[Ssh Agent Native Module] Starting Ssh Agent server on {:?}", ssh_path);
Oh no.... I'll go back through them. Apologies.

2024-09-12 09:38 UTC, quexten commented on apps/desktop/src/platform/services/renderer-ssh-agent.service.ts
>            });
I'm a bit confused, this map is not RxJS but just regular typescript?

2024-09-12 10:02 UTC, coroiu commented on apps/desktop/desktop_native/napi/src/lib.rs
> +    }
suggestion: should we try to return any underlying errors so that the TS client can handle it?

2024-09-12 10:04 UTC, coroiu commented on apps/desktop/desktop_native/napi/src/lib.rs
> +        };
suggestion: consider moving this logic into `core` so that we keep `napi` focused on just the mapping logic. I think that will also make any potential transition to the SDK easier

2024-09-12 10:06 UTC, coroiu commented on apps/desktop/desktop_native/napi/src/lib.rs
> +        };
suggestion: same here, move to `core`

2024-09-12 10:07 UTC, coroiu commented on apps/desktop/desktop_native/napi/Cargo.toml
> +ssh-key = { version = "0.6.6", default-features = false, features = ["encryption", "ed25519", "rsa", "getrandom"] }
question/suggestion: do we need to depend on these crates in the `napi` crate? Can we move these to `core`?

2024-09-12 10:17 UTC, coroiu commented on apps/desktop/desktop_native/core/src/ssh_agent/mod.rs
> +                    .await;
question: why are we ignoring the result here? What about errors?

2024-09-12 10:26 UTC, coroiu commented on apps/desktop/desktop_native/core/src/ssh_agent/mod.rs
> +use bitwarden_russh::encoding;
issue: according to my compiler on macOS `msg` and `encoding` are unusued

2024-09-12 10:27 UTC, coroiu commented on apps/desktop/desktop_native/core/src/ssh_agent/mod.rs
issue: according to my compiler on windows we have few unused imports

```
3 | use anyhow::Error;
  |     ^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `async_stream::stream`
 --> core\src\ssh_agent\mod.rs:5:5
  |
5 | use async_stream::stream;
  |     ^^^^^^^^^^^^^^^^^^^^

warning: unused import: `Stream`
 --> core\src\ssh_agent\mod.rs:7:23
  |
7 | use futures::stream::{Stream, StreamExt};
  |                       ^^^^^^

warning: unused import: `bitwarden_russh::msg`
  --> core\src\ssh_agent\mod.rs:15:5
   |
15 | use bitwarden_russh::msg;
   |     ^^^^^^^^^^^^^^^^^^^^

warning: unused import: `bitwarden_russh::encoding`
  --> core\src\ssh_agent\mod.rs:17:5
   |
17 | use bitwarden_russh::encoding;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `StreamExt`
 --> core\src\ssh_agent\mod.rs:7:31
  |
7 | use futures::stream::{Stream, StreamExt};```

2024-09-12 10:34 UTC, coroiu commented on apps/desktop/desktop_native/core/src/ssh_agent/mod.rs
I haven't run the compiler on linux, but please do a quick check there too!

2024-09-12 10:55 UTC, quexten commented
> Just a few more comments
> 
> @quexten a thought I had was that we will probably want to document this in a similar way to https://contributing.bitwarden.com/architecture/deep-dives/passkeys/implementations/provider/browser-extension

Contributing docs draft (still needs work): https://github.com/bitwarden/contributing-docs/pull/426

2024-09-12 11:36 UTC, quexten commented
> @quexten have you run the rust files through a formatter? When I modify the files on my device I get a whole lot of reformatting. It's odd that the CI doesn't react to it, but could you please run prettier on everything?

@coroiu Might be my IDE (Zed) messing with things. I'll take a look.

2024-09-12 12:10 UTC, quexten commented on apps/desktop/desktop_native/core/src/ssh_agent/mod.rs
> +                    my_home().unwrap().ok_or(Error::msg("Could not determine home directory")).unwrap()
Hmm, what should be the fallback behavior if we can't find a home directory? (That should really never occur). Serve on `/tmp/.bitwarden-ssh-agent.sock`?

2024-09-12 12:12 UTC, coroiu commented on apps/desktop/desktop_native/core/src/ssh_agent/mod.rs
> +                    my_home().unwrap().ok_or(Error::msg("Could not determine home directory")).unwrap()
Just return the error and let electron log it? Unwrapping will panic and crash the application? Or are we in a separate thread here so we might only crash the thread?

2024-09-12 12:23 UTC, quexten commented on apps/desktop/desktop_native/core/src/ssh_agent/mod.rs
> +                    my_home().unwrap().ok_or(Error::msg("Could not determine home directory")).unwrap()
Updating to:
```rust
            let ssh_path = match std::env::var("BITWARDEN_SSH_AUTH_SOCK") {
                Ok(path) => path,
                Err(_) => {
                    println!("[SSH Agent Native Module] BITWARDEN_SSH_AUTH_SOCK not set, using default path");

                    let ssh_agent_directory = match my_home() {
                        Ok(Some(home)) => home,
                        Ok(None) => PathBuf::from("/tmp/"),
                        Err(_) => PathBuf::from("/tmp/"),
                    };
                    ssh_agent_directory
                        .join(".bitwarden-ssh-agent.sock")
                        .to_str()
                        .expect("Path should be valid")
                        .to_string()
                }
            };

```

2024-09-12 12:26 UTC, coroiu commented on apps/desktop/desktop_native/core/src/ssh_agent/mod.rs
> +                    my_home().unwrap().ok_or(Error::msg("Could not determine home directory")).unwrap()
Sounds good! Btw, you might be able to simplify 

```rs
                    let ssh_agent_directory = match my_home() {
                        Ok(Some(home)) => home,
                        Ok(None) => PathBuf::from("/tmp/"),
                        Err(_) => PathBuf::from("/tmp/"),
                    };
```

to

```rs
                    let ssh_agent_directory = match my_home() {
                        Ok(Some(home)) => home,
                        _ => PathBuf::from("/tmp/"),
                    };
```

2024-09-12 12:33 UTC, coroiu commented on apps/desktop/desktop_native/core/src/ssh_agent/mod.rs
> +                    my_home().unwrap().ok_or(Error::msg("Could not determine home directory")).unwrap()
@quexten you can also write it as 

```
                    let ssh_agent_directory = my_home()
                        .ok()
                        .flatten()
                        .unwrap_or_else(|| PathBuf::from("/tmp/"));
```

2024-09-12 12:35 UTC, coroiu commented on apps/desktop/desktop_native/core/src/ssh_agent/mod.rs
> +                    my_home().unwrap().ok_or(Error::msg("Could not determine home directory")).unwrap()
@quexten also, when converting `&str` to `String` it's preferred to use `.to_owned()`

2024-09-12 13:14 UTC, quexten commented on apps/desktop/desktop_native/core/src/ssh_agent/mod.rs
> +                    .await;
I'm wondering what the best way to handle the error in this case is. We are starting the agent on a new thread/task for a reason. Maybe somehow keep track of a status mutably on the agent state, then if the above code fails set the status to "error", and have typescript either have a callback for this or poll the status, and perform cleanup?

2024-09-12 13:15 UTC, quexten commented on apps/desktop/desktop_native/napi/Cargo.toml
> +ssh-key = { version = "0.6.6", default-features = false, features = ["encryption", "ed25519", "rsa", "getrandom"] }
I hadn't changed it since I thought we're moving this to SDK asap anyways, but might aswell move it to core now. That way we can already add tests.

2024-09-12 13:53 UTC, coroiu commented on apps/desktop/desktop_native/core/src/ssh_agent/mod.rs
> +                    .await;
Hmm, well, we do have a communication channel that goes across the threads. If we really wanted to I guess we could use that to return any errors or other status messages! If we want to keep it simple we could just log the errors instead, either way I think it would help us a lot to have some method of gaining insight into what is going wrong, in case we ever have to debug in the future.

Do the `print` commands work alright from separate threads btw?

2024-09-12 13:56 UTC, quexten commented on apps/desktop/desktop_native/napi/src/lib.rs
> +        };
Moved to core and cleaned generator/importer up a bit.

2024-09-12 13:56 UTC, coroiu commented on apps/desktop/desktop_native/napi/Cargo.toml
> +ssh-key = { version = "0.6.6", default-features = false, features = ["encryption", "ed25519", "rsa", "getrandom"] }
Yeah, the ownership discussion is still ongoing so I'm not sure when "asap" might actually be, better not to assume anything! :)

2024-09-13 10:09 UTC, quexten commented on apps/desktop/desktop_native/core/src/ssh_agent/mod.rs
> +                    .await;
Printing from threads seems not to have been a problem so far, though I have not checked to make sure Rust guarantees this.

2024-09-13 13:31 UTC, quexten commented on apps/desktop/src/platform/services/renderer-ssh-agent.service.ts
> +        switchMap(async (message: any) => {
This is what I came up with but I did not commit it yet:

```ts
this.messageListener
      .messages$(new CommandDefinition("sshagent.signrequest"))
      .pipe(
        concatMap(async () => {
          ipc.platform.focusWindow();
          if (await firstValueFrom(this.authService.activeAccountStatus$) !== AuthenticationStatus.Unlocked) {
            this.toastService.showToast({
              variant: "info",
              title: null,
              message: this.i18nService.t("sshAgentUnlockRequired"),
            });
          }
        }),
        switchMap(async (message: any) => {
          const cipherId = message.cipherId;
          const messageId = message.messageId;

          const ret = race([
            of({cipherId, messageId, timeout: false} as SshRequest).pipe(
              delay(this.SSH_REQUEST_UNLOCK_POLLING_INTERVAL)
            ),
            this.authService.activeAccountStatus$.pipe(
              filter((status) => status === AuthenticationStatus.Unlocked),
              map(() => {
                return {
                  cipherId,
                  messageId,
                  timeout: true
                } as SshRequest;
              })
            )
          ])
          return await firstValueFrom(ret);
        }),
        concatMap(async (request: SshRequest) => {
          if (request.timeout) {
            this.toastService.showToast({
              variant: "error",
              title: null,
              message: this.i18nService.t("sshAgentUnlockTimeout"),
            });
          } else {
            const decryptedCiphers = await this.cipherService.getAllDecrypted();
            const cipher = decryptedCiphers.find((cipher) => cipher.id == request.cipherId);

            const dialogRef = ApproveSshRequestComponent.open(
              this.dialogService,
              cipher.name,
              this.i18nService.t("unknownApplication"),
            );

            const result = await firstValueFrom(dialogRef.closed);
            await ipc.platform.sshAgent.signRequestResponse(request.messageId, result);
            ipc.platform.hideWindow();
          }
        }),
        takeUntil(this.destroy$)
      )
      .subscribe();
```

is this roughly what you had in mind?

2024-09-13 13:39 UTC, quexten commented on apps/desktop/src/platform/services/renderer-ssh-agent.service.ts
> +  }
Combined them back again.

2024-09-14 14:28 UTC, quexten commented on apps/desktop/src/platform/services/renderer-ssh-agent.service.ts
> +        switchMap(async (message: any) => {
Added.

2024-09-18 12:24 UTC, coroiu commented on apps/desktop/src/platform/services/renderer-ssh-agent.service.ts
> +        switchMap(async (message: any) => {
@quexten sorry for the delay, going through this PR again today :)

2024-09-19 11:13 UTC, coroiu commented on apps/desktop/src/platform/services/ssh-agent.service.ts
> +        concatMap(async (message: any) => {
question: Something seems to be off with how the lifetime of these requests are handled. I tried changing this `concatMap` to a `switchMap` which in theory should cause new requests to cancel previous ones. But that doesn't seem to be what happens. Instead `messageListener.messages$` doesn't seem to emit any new events at all. The odd thing is that the requests do seem to be cached/queued somewhere. I recorded a small video do demonstrate what I mean

https://github.com/user-attachments/assets/7914e32a-625a-444e-a70e-451aa67e309c

2024-09-19 11:13 UTC, coroiu commented on apps/desktop/src/platform/services/ssh-agent.service.ts
> +          } else {
issue: this timeout clause doesn't actually complete the request which leaves it limbo, causing the existing and new requests to hang.

I fixed this in my suggestion PR.

2024-09-19 11:18 UTC, coroiu commented on apps/desktop/src/platform/services/ssh-agent.service.ts
> +            await ipc.platform.sshAgent.signRequestResponse(request.requestId, result);
issue: this result can't be piped directly into `signRequestResponse` because that function expects a boolean, but if you close the dialog with the "x" button you will instead get `undefined` which seems to crash inside the NAPI -> Rust layer.

I fixed this in my suggestion PR.

2024-09-24 12:55 UTC, quexten commented on apps/desktop/src/platform/services/ssh-agent.service.ts
> +            ipc.platform.hideWindow();
Changed the behavior to not `hideWindow` for now, and to focus on:
- Vault is locked
- Authorization required
we can get back to this once we have a few of the post MVP items implemented.

2024-09-24 12:59 UTC, coroiu commented on apps/desktop/src/platform/services/ssh-agent.service.ts
> +        concatMap(async (message: any) => {
Probably yeah

2024-09-24 13:03 UTC, quexten commented on apps/desktop/src/app/services/init.service.ts
> +    private sshAgentService: SshAgentService,
Added in 7440913

2024-09-26 07:19 UTC, coroiu approved these changes

2024-09-26 07:19 UTC, coroiu commented on apps/desktop/src/platform/services/ssh-agent.service.ts
> +        switchMap(([message, status]) => {
@quexten you mentioned something about wanting to keep the `concatMap` behavior?

2024-09-26 07:19 UTC, coroiu commented on apps/desktop/src/platform/services/ssh-agent.service.ts
> +        // Please not that any error here will have cause the whole stream to
remove?

2024-09-26 18:04 UTC, quexten commented on apps/desktop/src/platform/services/ssh-agent.service.ts
> +        switchMap(([message, status]) => {
Current behavior seems fine since the dialogs are in a concat map. I'm mainly concerned that multiple dialogs show (which they do not). The timeouts also work in parallel, so current behavior seems good.

2024-09-26 18:05 UTC, merged

2025-01-28 17:43 UTC, daltonpearson commented
Any chance that we'll get the option to disable the authorize dialog? I understand that it's a security measure but considering you already have to be logged in I think the auth/deny popup adds a bit too much friction for the hassle.