[PM-10155] Automatic Login After Autofill
bitwarden/clients pull request #10297
Opened 2024-07-26 21:14 UTC by cagonzalezcs

WIP

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-08-07 13:37 UTC, justindbaur requested changes

2024-08-07 13:37 UTC, justindbaur commented on apps/browser/src/platform/browser/browser-api.ts
> -    if (!tabId) {
I think I'd rather this throw if given a negative number and the calling code should do the validation to not call this when they don't have a valid tab id.

2024-08-07 16:31 UTC, cagonzalezcs commented on apps/browser/src/platform/browser/browser-api.ts
> -    if (!tabId) {
@justindbaur 

Hmm... this is a far reaching method. Adding a thrown error, and ensuring that is handled correctly within all callers of the method will expand the scope of this refactor in a significant manner. 

Would it be better to add a follow up ticket to address this, given that we are only correctly the validation here to ensure that `tabId = 0` values are called? (Zero can be a valid tab id number)

2024-08-07 16:37 UTC, justindbaur commented on apps/browser/src/platform/browser/browser-api.ts
> -    if (!tabId) {
What's the current outcome of a negative tab number getting into this method that prompted this change?

2024-08-07 17:01 UTC, cagonzalezcs commented on apps/browser/src/platform/browser/browser-api.ts
> -    if (!tabId) {
If I remember correctly, I was getting a thrown error when the negative value was being passed to `chrome.tabs.get`. 

Pages like the `chrome-extension://` page are rendered with a tab id of -1, which was the core issue.

2024-08-07 17:07 UTC, justindbaur commented on apps/browser/src/platform/browser/browser-api.ts
> -    if (!tabId) {
So then I think I'd rather let that error be the one that keeps being thrown. There is seemingly something new in this PR that is calling this with a -1 and that is the place that handling the negative number would be better in my opinion.

2024-08-07 17:48 UTC, cagonzalezcs commented on apps/browser/src/platform/browser/browser-api.ts
> -    if (!tabId) {
Sounds good, I've removed this change to `BrowserApi` and added the checks within the file that i was using this method.

2024-08-07 17:51 UTC, justindbaur commented on apps/browser/src/platform/browser/browser-api.ts
> -    if (!tabId) {
Awesome, thank you so much!

2024-08-07 17:52 UTC, justindbaur approved these changes

2024-08-08 21:17 UTC, jprusik commented on apps/browser/src/autofill/content/auto-submit-login.ts
> +  function submitElementFoundAndClicked(
per offline conversation; we might try simulating user interactions (e.g. focusing and firing an "Enter" keyup event on the last relevant input) before an expensive search for the submit button.

2024-08-08 21:27 UTC, jprusik commented on apps/browser/src/autofill/content/auto-submit-login.ts
> +    setAutoSubmitLoginTimeout(400);
per offline conversation as a followup consideration: we might consider a hardcoded limit to how many times (and/or time interval limit) we retry actions like these in case of unanticipated scenarios (e.g. the multitude of multi-step form scenarios/patterns) that leave methods in open recursion

2024-08-08 21:28 UTC, jprusik approved these changes
Pair-reviewed; we identified some areas of potential follow-up, but as an MVP, it LGTM

2024-08-08 21:30 UTC, merged