[PM-2192] Improve userkey verification on biometric unlock
bitwarden/clients pull request #10326
Opened 2024-07-30 12:50 UTC by quexten

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-2192
https://github.com/bitwarden/clients/issues/5407

## 📔 Objective

Improve userkey validation for biometric unlock & add separate error message for debugging.

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-07-30 14:28 UTC, justindbaur requested changes
Couple minor changes.

2024-07-30 14:28 UTC, justindbaur commented on apps/browser/src/background/nativeMessaging.background.ts
> +                await this.cryptoService.setUserKey(userKey);
You can now pass `activeUserId` into this method. Ideally we will be making that parameter non-optional soon. Which @trmartin4 is actually doing in #9675.

2024-07-30 14:28 UTC, justindbaur commented on apps/browser/src/background/nativeMessaging.background.ts
> +                await this.cryptoService.clearKeys();
Here as well.

2024-07-31 09:47 UTC, quexten commented on apps/browser/src/background/nativeMessaging.background.ts
> +                await this.cryptoService.clearKeys();
Fixed both, thank you!

2024-07-31 11:25 UTC, justindbaur approved these changes

2024-08-02 13:38 UTC, quexten commented
Resolved a merge conflict.

2024-08-06 19:35 UTC, justindbaur approved these changes

2024-08-06 19:35 UTC, merged