[PM-9605] Extension AnonLayout wrapper component
bitwarden/clients pull request #10338
Opened 2024-07-31 03:48 UTC by rr-bw

- **setup extension component**
- **setup extension service**

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-08-02 21:44 UTC, JaredSnider-Bitwarden requested changes
Nice work on this! One small defect and one question!

2024-08-05 15:15 UTC, rr-bw commented on libs/components/src/styles.scss
> +}
@willmartian I was having some trouble with how `<app-current-account>` renders in storybook. By default the button adds padding and a border.

![Screenshot 2024-08-05 at 8 09 29 AM](https://github.com/user-attachments/assets/874cd7bd-33c0-448c-ba10-8c5e60ece394)

But in client implementations `<app-current-account>` does not have that border/padding. So I added some scss to `libs/components/src/styles.scss` to adjust the current account button in storybook to remove that default border/padding. Is this ok?

![Screenshot 2024-08-05 at 8 10 01 AM](https://github.com/user-attachments/assets/ea091ceb-a0f0-422e-9f09-d9e44cbab363)

2024-08-06 21:18 UTC, willmartian commented on libs/components/src/styles.scss
> +}
I _assume_ this issue is happening because of global CSS differing from where the component is typically used (browser) to where it is currently being rendered (Storybook, which includes all of the global CSS from web). 

We would likely see this issue if the component was used in the web client somewhere. 

Solutions in decreasing order of magnitude: (skip to 4 if you don't want to read my train of thought)

1. remove all global css from the clients and define them at the component level (in progress)
2. create a client toggle option in the Storybook UI that loads global css from each client (would be cool, but out of scope here)
3. ~add style overrides to `app-current-account` that makes it portable between clients~
4. Keep your patch in, and make a note on [CL-154](https://bitwarden.atlassian.net/browse/CL-154) to remove the patch later (do this one, it accomplishes the same as 3. but is less blocking for you)

2024-08-06 22:32 UTC, JaredSnider-Bitwarden approved these changes

2024-08-06 22:35 UTC, rr-bw commented on libs/components/src/styles.scss
> +}
Thanks @willmartian. We will do 4. I've added a [note to CL-154](https://bitwarden.atlassian.net/browse/CL-154).

2024-08-06 22:58 UTC, willmartian approved these changes

2024-08-06 23:02 UTC, merged