[PM-10045] - SendCreated page
bitwarden/clients pull request #10331
Opened 2024-07-30 17:59 UTC by jaasen-livefront

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-10045

## 📔 Objective

This PR adds the send created page as part of the browser refresh. It is shown as a result of a successfully created send which does currently exist so QA testing will not be possible. To enable this page on local development you may replace the `SendV2Component` with the `SendCreatedComponent` in `app-routing.module.ts`.

## 📸 Screenshots

![Screenshot 2024-07-30 at 10 35 45 AM](https://github.com/user-attachments/assets/93705479-32fe-40e6-8134-46b3409d7217)

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-07-31 12:09 UTC, djsmith85 requested changes
@Jordan Aasen Nice work. 
We still need to think of a way to pass the saved Send or SendId over to this page. The link and the number of days it's available are going to depend on the settings of the Send

2024-07-31 12:09 UTC, djsmith85 commented on apps/browser/src/_locales/en/messages.json
> +    "message": "The Send will be available to anyone with the link for the next [7] days.",
The number of days will be dynamic based on the settings (expiration/deletion date) of the Send

2024-07-31 12:09 UTC, djsmith85 commented on libs/angular/src/jslib.module.ts
> +    IconModule,
This module should be removed and can be added to the imports of the standalone send.created.component

2024-07-31 23:44 UTC, jaasen-livefront commented
@djsmith85 Ready for re-review!

2024-08-08 16:54 UTC, danielleflinn requested changes
@jaasen-livefront can you remove the brackets around the "7"? 

This punctuation was in Figma just to communicate that this value should dynamically change based on the deletion date the user selects

2024-08-13 18:36 UTC, jordan-aasen commented
@danielleflinn Nice catch! Looks like I posted an older screenshot. I've updated it with one that no longer contains the brackets.

2024-08-14 10:02 UTC, djsmith85 approved these changes

2024-08-15 14:58 UTC, danielleflinn approved these changes

2024-08-15 14:59 UTC, merged