Vault/pm 8655/update web app new item button
bitwarden/clients pull request #10354
Opened 2024-07-31 20:15 UTC by alec-livefront

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-8655?atlOrigin=eyJpIjoiYTljMTE3NWI0Njg3NDc4ZDk2MjBiOTVmNTFhNGU3Y2YiLCJwIjoiaiJ9

## 📔 Objective

Updates the web vault "new" button and related functionality:

- Updates the top "new" button style (rounded corners, thicker plus icon)
- Updates the dropdown menu for the top "new" button to show individual cipher types and adds divider between types and containers (folder, collection)
- Updates the onboarding "new item" link to "new login" (and directs user to dialog with "login" cipher selected)
- Updates the "no items new item" button styles (rounded corners, thicker plus icon)

## 📸 Screenshots

![Screenshot 2024-07-31 at 2 26 55 PM](https://github.com/user-attachments/assets/030b35ff-565e-4a21-b635-e4b0af433879)

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-07-31 21:22 UTC, shane-melton requested changes
Looks good, nice work! Just two small nits regarding button rounding that will eventually be taken care of by the design team's style feature branch once merged.

2024-07-31 21:22 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault.component.html
> +        [ngClass]="{ 'tw-rounded-full': extensionRefreshEnabled$ | async }"
⛏️  We don't need to round the button ourselves, it'll be taken care of with the design teams style feature branch once merged.

2024-07-31 21:22 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault-header/vault-header.component.html
> +            class="tw-rounded-full"
⛏️ We don't need to round the button ourselves, it'll be taken care of with the design teams style feature branch once merged and apply to all `bitButton`s automatically.

2024-07-31 21:22 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault.component.html
> +        <i class="bwi bwi-plus-f bwi-fw" aria-hidden="true"></i>
❓ @danielleflinn It's pretty minor but do we want this change from `bwi-plus` to `bwi-plus-f` to be behind the feature flag too? (this is for the empty vault New Item button)

2024-07-31 22:19 UTC, danielleflinn commented on apps/web/src/app/vault/individual-vault/vault.component.html
> +        <i class="bwi bwi-plus-f bwi-fw" aria-hidden="true"></i>
No preference from me; whatever is easier for you all

2024-07-31 22:32 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault.component.html
> +        <i class="bwi bwi-plus-f bwi-fw" aria-hidden="true"></i>
Keeping it as is works for me, thanks!

2024-08-02 14:06 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/vault-header/vault-header.component.html
> +            class="tw-rounded-full"
👍 [f9a2eef](https://github.com/bitwarden/clients/pull/10354/commits/f9a2eef924cc394eb12386536967a2ac5d1edb98)

2024-08-02 14:06 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/vault.component.html
> +        [ngClass]="{ 'tw-rounded-full': extensionRefreshEnabled$ | async }"
👍 [c816269](https://github.com/bitwarden/clients/pull/10354/commits/c816269f2eee7209b2a670462ec23a711bd7dd33)

2024-08-08 14:45 UTC, shane-melton approved these changes

2024-08-09 04:45 UTC, merged