Vault/pm 9665/implement view item view
bitwarden/clients pull request #10416
Opened 2024-08-06 14:42 UTC by alec-livefront

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-9665?atlOrigin=eyJpIjoiOGUzNDYwOWQxOGMxNDlkZjkyZDI4Mzk1YjNkNjJhMzYiLCJwIjoiaiJ9

## 📔 Objective

Add a new "view cipher" dialog to the web vault. When clicking on a link in the vault list it should launch a "View {type}" modal.

## 📸 Screenshots

https://github.com/user-attachments/assets/4a5491b9-c302-4b94-ad24-fdf389501bd6

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-08-06 14:45 UTC, alec-livefront commented on apps/web/src/app/shared/loose-components.module.ts
> +    CipherViewComponent,
Curious about the note "If you are building new functionality, please create or extend a feature module instead." - could someone point me towards a pattern of creating/extending a feature module?

2024-08-06 15:56 UTC, shane-melton commented on apps/web/src/app/shared/loose-components.module.ts
> +    CipherViewComponent,
We have a Web `VaultModule` for the Individual Vault [here](https://github.com/bitwarden/clients/blob/main/apps/web/src/app/vault/individual-vault/vault.module.ts) that we can extend by adding the new View dialog there. We'll also likely want to do add it to the Org `Vault Module` as well located [here](https://github.com/bitwarden/clients/blob/main/apps/web/src/app/vault/org-vault/vault.module.ts).

2024-08-06 16:12 UTC, shane-melton requested changes
I understand its still in draft and a WIP, but I wanted to make sure I pointed out some of these concerns to catch any potential issues early. If you have any follow up questions or would like to discuss further please let me know, happy to help!

2024-08-06 16:12 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/view.component.ts
> +export class ViewComponent extends BaseAddEditComponent implements OnInit, OnDestroy {
⚠️ This component should not need to extend the `BaseAddEditComponent` as nearly all of the functionality it needs is in the shared `<app-cipher-view>` component. This view dialog component should be fairly simple and only have the actions to open the `add-edit` dialog or delete the cipher. 

A good existing example of something similar is the recently added [assign collections dialog](https://github.com/bitwarden/clients/blob/main/apps/web/src/app/vault/components/assign-collections/assign-collections-web.component.ts) that is using our current best practices and components.

2024-08-06 16:12 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/view.component.ts
> +  templateUrl: "view.component.html",
🎨 We should make this `standalone: true` if possible.

2024-08-06 16:12 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/view.component.html
⚠️ We don't want to use the bootstrap `modal-dialog` classes any more and should instead use the `<bit-dialog>` component. Docs can be found [here](https://components.bitwarden.com/?path=/docs/component-library-dialogs-dialog--docs). And an in code example [here](https://github.com/bitwarden/clients/blob/main/apps/web/src/app/vault/components/assign-collections/assign-collections-web.component.html).

2024-08-06 16:12 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/view.component.html
> +      ngNativeValidate
🎨 We likely won't need this form any longer and can instead use a standard button for navigation and the [Async Actions directives](https://components.bitwarden.com/?path=/docs/component-library-async-actions-overview--docs) for the delete action.

2024-08-06 16:12 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/vault.component.html
> +<ng-template #cipherView></ng-template>
🎨 Using the `<bit-dialog>` and `DialogService` will remove the need to have this `ng-template`.

2024-08-06 16:12 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +  @ViewChild("cipherView", { read: ViewContainerRef, static: true })
🎨 Similarly, this isn't necessary with the `DialogService`.

2024-08-06 16:12 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +    const [modal, childComponent] = await this.modalService.openViewRef(
⚠️ We should use the [`DialogService`](https://components.bitwarden.com/?path=/docs/component-library-dialogs-service--docs) over the deprecated `modalService`.

2024-08-06 16:12 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +    const [modal, childComponent] = await this.modalService.openViewRef(
⚠️ We should use the [`DialogService`](https://components.bitwarden.com/?path=/docs/component-library-dialogs-service--docs) over the deprecated `modalService`.

2024-08-09 15:56 UTC, nick-livefront requested changes
A couple small nits and one change that has to do with testing

2024-08-09 15:56 UTC, nick-livefront commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +        } else {
⛏️ Should this be kept as an `else if`? `action` is only a string so anything could be passed. Maybe a small difference but it is a change in functionality.

2024-08-09 15:56 UTC, nick-livefront commented on apps/web/src/app/vault/individual-vault/view.component.html
> +        class="btn-outline-danger"
`buttonType="danger"` should be able to handle all styling of a deletion here rather than adding a class

```suggestion
        buttonType="danger"
```

2024-08-09 15:56 UTC, nick-livefront commented on apps/web/src/app/vault/individual-vault/view.component.html
> +        <i class="bwi bwi-trash bwi-lg bwi-fw" aria-hidden="true"></i>
⛏️ There isn't text within this button, an aria-label is needed. The `appA11yTitle` directive can assign both an aria-label and title to the button.
Note: `deleteCipher`  doesn't exist in the translations, it would need to be added. 
```html
[appA11yTitle]="'deleteCipher' | i18n"
```

2024-08-09 15:56 UTC, nick-livefront commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +    const cipherView = new CipherView(cipher);
❌ The `app-cipher-view` isn't populating because of the conversion to `CipherView` here. This should be a decryption. 

I'm kind of surprised all of the Types are happy here. @shane-melton any advice on how to avoid this kind of "gotcha"?

```ts
const cipherView = await cipher.decrypt(await this.cipherService.getKeyForCipherKeyDecryption(cipher))
```

2024-08-09 15:56 UTC, nick-livefront commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +    const cipherTypeString = ViewComponent.getCipherViewTypeString(cipherView, this.i18nService);
:pick: The level of abstraction between components is blurred here. `getCipherViewTypeString` exists on the dialog component and is used to pass a value back into the dialog component. The `cipherTypeString` param can be removed in favor of the dialog component determine the type in the `ngOnInit` lifecycle.

2024-08-09 15:56 UTC, nick-livefront commented on apps/web/src/app/vault/individual-vault/view.component.spec.ts
> +    TestBed.inject(BillingAccountProfileStateService);
❌ `TestBed.inject` is unnecessary for the the services where you don't need to grab an instance of that service. The providers array above is providing that instance for you.

For `organizationService` and `router` I find it more natural to pass values to the `useValue` property in the provider array. I find it to be a little less setup, but not a a necessary change. For example:

`organizationService = TestBed.inject(OrganizationService);` could be replaced by altering the `OrganizationService` in the provider array to: `{ provide: OrganizationService, useValue: { get: jest.fn().mockResolvedValue(mockOrganization) } }`

2024-08-09 15:56 UTC, nick-livefront commented on apps/web/src/app/vault/individual-vault/view.component.spec.ts
> +    jest.useFakeTimers();
⛏️ `jest.useFakeTimers()` isn't needed, I don't believe?

If it's not, the `afterEach` can be removed as well

2024-08-09 15:56 UTC, nick-livefront commented on apps/web/src/app/vault/individual-vault/view.component.ts
> +  async delete(): Promise<boolean> {
This is an old pattern that I find myself following as well. Or copying and pasting on accident 🙃 

The `boolean` return isn't used for anything and can be removed

```suggestion
  async delete(): Promise<void> {
```

2024-08-09 15:56 UTC, nick-livefront commented on apps/web/src/app/vault/individual-vault/view.component.ts
> +export function openViewCipherDialog(
❓ Any reason you didn't make this a static instance on the class? That appears to be a more common pattern: [BrowserSyncVerificationDialogComponent](https://github.com/bitwarden/clients/blob/0dcb338c64d1c552ca1a1464ff6c3ee1dab71c3b/apps/desktop/src/app/components/browser-sync-verification-dialog.component.ts#L19), [BulkRemoveDialogComponent](https://github.com/bitwarden/clients/blob/0dcb338c64d1c552ca1a1464ff6c3ee1dab71c3b/bitwarden_license/bit-web/src/app/admin-console/providers/manage/dialogs/bulk-remove-dialog.component.ts#L46)

2024-08-09 15:56 UTC, nick-livefront commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +    const cipherView = new CipherView(cipher);
Fixed in: [0dcb338](https://github.com/bitwarden/clients/pull/10416/commits/0dcb338c64d1c552ca1a1464ff6c3ee1dab71c3b)

2024-08-09 16:22 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/view.component.spec.ts
> +    TestBed.inject(BillingAccountProfileStateService);
I've removed the unnecessary TestBed.inject calls. However, when I try to rework `organizationService` as you suggest I get 
```
   Cannot use spyOn on a primitive value; undefined given

     78 |   describe("ngOnInit", () => {
     79 |     it("initializes the component with cipher and organization", async () => {
   > 80 |       jest.spyOn(organizationService, "get").mockResolvedValue(mockOrganization);
        |            ^
     81 |
     82 |       await component.ngOnInit();
     83 |
```

2024-08-09 18:23 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/view.component.ts
> +export function openViewCipherDialog(
I've seen it both ways. But if we feel it's more common to have it as a static method I can do that!

2024-08-09 19:13 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +        } else {
8e971150c53f15b2eca82f1743b4111c3caab72d

2024-08-09 20:13 UTC, nick-livefront commented on apps/web/src/app/vault/individual-vault/view.component.spec.ts
> +    TestBed.inject(BillingAccountProfileStateService);
Using `{ provide: OrganizationService, useValue: { get: jest.fn().mockResolvedValue(mockOrganization) } }` replaces the provider with your own instance of it. So in this case when the test runs within your class `organizationService` is `{ get: jest.fn... )}` and that's it.

`jest.SpyOn` is no longer needed because you already passed a mock function in place of it.

Your final test would be:
```ts
it("initializes the component with cipher and organization", async () => {
  await component.ngOnInit();

  expect(component.cipher).toEqual(mockCipher);
  expect(component.cipherTypeString).toEqual("login");
  expect(component.organization).toEqual(mockOrganization);
});
```

2024-08-09 20:14 UTC, nick-livefront commented on apps/web/src/app/vault/individual-vault/view.component.ts
> +export function openViewCipherDialog(
👍 I'm cool with either

2024-08-09 21:14 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +    const cipherTypeString = ViewComponent.getCipherViewTypeString(cipherView, this.i18nService);
That makes too much sense 😂 fixed: [251875a](https://github.com/bitwarden/clients/pull/10416/commits/251875a53543b9cda9793f395a62fb5a817f6345)

2024-08-09 21:53 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/view.component.spec.ts
> +    TestBed.inject(BillingAccountProfileStateService);
[5394167](https://github.com/bitwarden/clients/pull/10416/commits/5394167119a240b1feea7a7c2b89677e022fb0bd)

2024-08-12 20:37 UTC, nick-livefront reviewed
All of my comments have been resolved 🥳 

Just one translation to fix

2024-08-12 20:37 UTC, nick-livefront commented on apps/web/src/app/vault/individual-vault/view.component.html
> +        <i class="bwi bwi-trash bwi-lg bwi-fw" aria-hidden="true"></i>
@alec-livefront `deleteCipher` should be added to the `messages.json` for translation

2024-08-14 15:51 UTC, nick-livefront approved these changes

2024-08-14 16:36 UTC, shane-melton requested changes
Great work on this! Exciting to see the new component working in the Web vault!

I only noticed a few small issues we'll want to address before merging. Otherwise, just a couple other nits/suggestions!

2024-08-14 16:36 UTC, shane-melton commented on apps/web/src/locales/en/messages.json
> +    "message": "Delete cipher"
⚠️ We try to avoid using the word "cipher" for any UI elements displayed to the user as not everyone is familiar with the term. I think we can get away with simply "Delete", but if not, we should use "Delete item" instead.

2024-08-14 16:36 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/view.component.html
> +        bitFormButton
⛏️ This isn't technically a form button anymore since we've removed the form.

2024-08-14 16:36 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/view.component.ts
> +      this.deletePromise = this.deleteCipher();
⛏️ We don't seem to be using this promise anywhere else and can just await the call directly. (In the past its usually used to prevent duplicate submissions/clicks)

Alternatively, to follow our current best practices, we should make this delete method an arrow-function assigned to a `delete` property so that it can be used with the `[bitAction]` directive on the button instead of the `(click)` event handler. This handles duplicate submission prevention and showing a loading icon on the button while the action is being performed. ([docs here](https://components.bitwarden.com/?path=/docs/component-library-async-actions-standalone-documentation--docs))

2024-08-14 16:36 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/view.component.ts
> +        return this.i18nService.t("viewItemType", "login");
⚠️ We need to translate these item types as well.
```suggestion
        return this.i18nService.t("viewItemType", this.i18nService.t("login"));
```

2024-08-14 16:36 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/view.component.html
> +      bitFormButton
⛏️ Same here, not a form button anymore.

2024-08-14 16:36 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/view.component.spec.ts
> +      const cleanupSpy = jest.spyOn(component, "ngOnDestroy");
❓ I think this is just testing that Angular is calling `ngOnDestroy` and not any of our own functionality within? If so,  we can probably drop this test.

2024-08-14 16:36 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/view.component.spec.ts
> +      const deleteSpy = jest.spyOn(component, "delete").mockImplementation(() => Promise.resolve());
⛏️ (non-blocking): It would be nice to also test that `dialogRef.close()` was called for this and the `edit()` test above since that is "public" behavior expected of the dialog.

2024-08-14 16:36 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/view.component.spec.ts
👍 Thanks for adding tests!

2024-08-15 19:33 UTC, alec-livefront commented on apps/web/src/locales/en/messages.json
> +    "message": "Delete cipher"
[507f0c5](https://github.com/bitwarden/clients/pull/10416/commits/507f0c5e518d13122fdc0a835c2dabb6bd12c7ea)

2024-08-15 19:33 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/view.component.html
> +        bitFormButton
[506ae58](https://github.com/bitwarden/clients/pull/10416/commits/506ae589c2b2529bbed45318daa053b9c81f7592)

2024-08-15 19:41 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/view.component.ts
> +      this.deletePromise = this.deleteCipher();
I decided to remove the delete cipher functionality from the cipher view, relying on the existing `deleteCipher` function in `vault.component.ts`. I did have to modify `deleteCipher` a bit so that we can skip the confirmation dialog, as that should show before the main dialog is closed. Let me know if you have any thoughts on this new approach.

[50bf8fa](https://github.com/bitwarden/clients/pull/10416/commits/50bf8fad615443f6c33494ee12cf473f41204aa1)

2024-08-15 19:41 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/view.component.ts
> +        return this.i18nService.t("viewItemType", "login");
👍 [b8a1816](https://github.com/bitwarden/clients/pull/10416/commits/b8a18162b1bc32d811ca16b774c608744eecad48)

2024-08-15 19:41 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/view.component.html
> +      bitFormButton
👍 [506ae58](https://github.com/bitwarden/clients/pull/10416/commits/506ae589c2b2529bbed45318daa053b9c81f7592)

2024-08-15 19:42 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/view.component.spec.ts
> +      const cleanupSpy = jest.spyOn(component, "ngOnDestroy");
Good call - removed: [7919dc1](https://github.com/bitwarden/clients/pull/10416/commits/7919dc1c28fbe6326b29576bfa09d56a63895d4b)

2024-08-15 19:42 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/view.component.spec.ts
> +      const deleteSpy = jest.spyOn(component, "delete").mockImplementation(() => Promise.resolve());
[453de16](https://github.com/bitwarden/clients/pull/10416/commits/453de160d094d75d0e23a975937114db9e063d18)

2024-08-15 19:45 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/view.component.ts
> +        return this.i18nService.t("viewItemType", "login");
One question that came up while doing this: Should the title for a note be "View secure note" or "View note"? The "secure note" version is next to all the other type translations, so I went with that initially. Not sure if there's a standard for this.

2024-08-15 20:02 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/view.component.ts
> +        return this.i18nService.t("viewItemType", "login");
We're using "View note" in the browser extension so I think we may want do the same here but I'll let @danielleflinn confirm.

2024-08-15 20:04 UTC, danielleflinn commented on apps/web/src/app/vault/individual-vault/view.component.ts
> +        return this.i18nService.t("viewItemType", "login");
Yes please update to "View note"

2024-08-15 20:04 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/view.component.ts
> +      this.deletePromise = this.deleteCipher();
Hmm, I think this may change a few other behaviors unintentionally. It looks like we're going to re-prompt the master password by using the existing function. Also, the existing function in `vault.component.ts` doesn't make the call to the `messagingService.send()` that was being made by the original edit dialog.

2024-08-15 20:23 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/view.component.ts
> +      this.deletePromise = this.deleteCipher();
Ah, I was thinking we'd want to re-prompt here but the user already has to do that to view 👍 I've reverted this back to having the delete functionality in the `view.component.ts` [43a59d0](https://github.com/bitwarden/clients/pull/10416/commits/43a59d01749bfbd3fcf5e9e6879bedac08fc35db)

2024-08-15 20:24 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/view.component.ts
> +        return this.i18nService.t("viewItemType", "login");
[2f1c70c](https://github.com/bitwarden/clients/pull/10416/commits/2f1c70c4c32d62477adfdd2614d35fcb5f7e7cb9)

2024-08-19 15:51 UTC, shane-melton requested changes
One last thing we need to tweak since https://github.com/bitwarden/clients/pull/10422 was merged and removed the FC V1 flag from `main` and we do not want to add it back here with the dialog.

2024-08-19 15:51 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/view.component.ts
> +  flexibleCollectionsV1Enabled = false;
⚠️ This flag (flexibleCollectionsV1) was recently removed in https://github.com/bitwarden/clients/pull/10422 and should be removed here as well.

2024-08-19 21:32 UTC, merged