[PM-10682] user state subject
bitwarden/clients pull request #10426
Opened 2024-08-06 21:49 UTC by audreyality

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-10682

## 📔 Objective

The user state subject adapts state providers to an rxjs subject.

The subject will be used by the generator UI to load and store the active user’s global generator settings.

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-08-06 22:02 UTC, audreyality commented on libs/common/src/tools/dependencies.ts
📝 Not all of the types in this file are used by the user-state subject, but they *are* all used by the service code in downstream PRs.

2024-08-07 11:55 UTC, djsmith85 requested changes
Nice work, which we already discussed last week. Just some documentation updates needed before we can merge

2024-08-07 11:55 UTC, djsmith85 commented on libs/common/src/tools/dependencies.ts
> + */
⚠️  Documentation needs to be updated after re-name of the dependency

2024-08-07 11:55 UTC, djsmith85 commented on libs/common/src/tools/dependencies.ts
> +};
❓ Should we name it WhenTrue, if it only emits when true?

2024-08-07 13:05 UTC, audreyality commented on libs/common/src/tools/dependencies.ts
> +};
I don't believe that's necessary. It's common for other conditionals (`if`, `while`, rxjs `filter`, etc) that we don't call out they only execute when their value is true.

2024-08-07 13:07 UTC, audreyality commented on libs/common/src/tools/dependencies.ts
> + */
Addressed in 2e5f7d8df1d97ab202.

2024-08-07 13:14 UTC, audreyality commented
❗ Please don't review this until I've addressed the remaining unit tests. :)

2024-08-07 15:03 UTC, djsmith85 approved these changes

2024-08-07 15:06 UTC, merged