[PM-10294] Remove FC v1 from Clients
bitwarden/clients pull request #10422
Opened 2024-08-06 19:50 UTC by vincentsalucci

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-10294

## 📔 Objective

> Remove FC v1 references from the clients codebase

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-08-08 02:39 UTC, eliykat requested changes
Love this

![Screenshot 2024-08-08 at 11 41 48 AM](https://github.com/user-attachments/assets/113d4d9b-8fc1-49bf-a10d-4ab7dea35268)

2024-08-08 02:39 UTC, eliykat commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +    // V1 limits admins to only adding items to collections they have access to.
⛏️  still some "V1" references in comments in this file.

2024-08-08 18:36 UTC, shane-melton requested changes
Looks good! Just one tiny nit for an unused `ConfigService`

2024-08-08 18:36 UTC, shane-melton commented on apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.ts
⛏️ We don't need `ConfigService` anymore in this component 🎉

2024-08-08 19:00 UTC, shane-melton submitted a review, later dismissed
Vault changes look good! Thanks for removing all that code, very happy to see it go!

2024-08-08 22:19 UTC, eliykat approved these changes

2024-08-09 18:17 UTC, vincentsalucci commented
@shane-melton @eliykat Had to resolve one conflict 😞

2024-08-09 18:17 UTC, shane-melton approved these changes

2024-08-11 22:23 UTC, eliykat approved these changes

2024-08-12 17:37 UTC, shane-melton approved these changes

2024-08-12 20:10 UTC, eliykat approved these changes

2024-08-12 20:10 UTC, eliykat submitted a review, later dismissed
Please also remove the enum definition.

2024-08-12 20:12 UTC, vincentsalucci commented
> Please also remove the enum definition.

Have a follow-up PR ready with this change. Aligns with our Task creation/timing with the server enum.

2024-08-12 20:25 UTC, vincentsalucci commented
@bitwarden/dept-design Adding the group to the PR per process: no net-new changes have been made to the UI, rather a checkbox is now visible due to the removal of the Flexible Collections V1 feature flag.

2024-08-12 20:43 UTC, sukhleenb approved these changes

2024-08-13 15:45 UTC, merged