[PM-10731] Move vault icons
bitwarden/clients pull request #10453
Opened 2024-08-08 19:28 UTC by nick-livefront

## 🎟️ Tracking

[PM-10731](https://bitwarden.atlassian.net/browse/PM-10731)

## 📔 Objective

Stemming from https://github.com/bitwarden/clients/pull/10423#issuecomment-2276325509, this moves all icons only used within the vault to within `libs/vault` and can be imported like so:

```ts
import { VaultIcons } from "@bitwarden/vault";
``` 

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-08-08 19:38 UTC, shane-melton approved these changes
Thank you!

2024-08-08 19:39 UTC, shane-melton requested changes
Thanks for grabbing this! 

~Looks like storybook is failing though, perhaps we missed some stories using the old paths?~

Actually, Tools is using the `NoResults` icon for their send-v2 component. I guess we should leave that in the CL.

2024-08-08 19:43 UTC, nick-livefront commented
@shane-melton I thought `NoResults` was only used in the vault. I was mistaken. I moved that one back to the component library

2024-08-08 19:44 UTC, shane-melton approved these changes

2024-08-09 23:02 UTC, willmartian approved these changes
LGTM, ty!

2024-08-12 13:38 UTC, merged