[BEEEP] New export format: Zip with attachments
bitwarden/clients pull request #10465
Opened 2024-08-09 10:57 UTC by quexten

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-08-09 11:38 UTC, quexten commented
Also, do we know how much users / orgs actually store in attachments? I would suspect for large file storage they would use a different service, so we might just enable org attachment export too.

2024-08-09 11:45 UTC, djsmith85 commented
> @djsmith85 Since zips are intransparent blobs (unlike json), is there any good way to add tests for this? Maybe unzip the created blob again using the same library, and compare the files?

Yes, that would be a good approach. I wouldn't go as far comparing the files (content) as just checking that it contains a data.json and the expected filenames for attachments.

If we are sticking with JSZip for now that would just be JSZip.loadAsync() and then iterating/searching for the files. 

One of the reasons I chose JSZip at the time was support for JS and Node execution (cli), but I'm totally fine with using another library, especially if it's offering better support for streams.

2024-08-09 14:16 UTC, quexten commented
Added tests for data.json being present, and for one attachment being present. Sadly I had to mock request, fetch on the global object. I think in the mid-term, creating something like an "AttachmentDownloadService" might make sense since we have fetch calls just spread throughout the code atm.

2024-08-12 12:32 UTC, audreyality commented
> @djsmith85 Since zips are intransparent blobs (unlike json), is there any good way to add tests for this? Maybe unzip the created blob again using the same library, and compare the files?

You might also check how the library performs it's tests.
https://github.com/Stuk/jszip/blob/main/test/asserts/file.js

Teasing apart what those helpers do might be a bit much, though.

2025-02-06 15:50 UTC, croci commented
Please merge this! The zip export would be extremely useful!

2025-03-03 14:57 UTC, audreyality requested changes

2025-03-03 14:57 UTC, audreyality commented on apps/cli/src/tools/export.command.ts
> +          ? ((await this.exportService.getExport(format, password)) as string)
⚠️ This needs to test whether the output is actually a string. Alternatively, consider splitting `getExport` into a unique method per return type.

2025-03-03 14:57 UTC, audreyality commented on libs/tools/export/vault-export/vault-export-core/src/services/individual-vault-export.service.ts
>      }
🤔 Seems like the `Blob` return was introduced by `this.getDecryptedExportZip()`. Since the other two methods return strings, it seems reasonable to expect `getDecryptedExportZip` to be called from its own code-path.

💭 Alternatively, `getEncryptedExport` and `getDecryptedExport()` could have their result be converted to returning `Blob`, which would eliminate the string-typed return from `getExport()`.

2025-03-03 14:57 UTC, audreyality commented on libs/tools/export/vault-export/vault-export-ui/src/components/export.component.ts
> +  }
🎨 Since the data's content type is required for proper interpretation of the result, consider returning it with the exported data.

```typescript
// in vault-export.service.abstraction, introduce abstraction
type ExportedVault = {
  type: "application/zip",
  data: Blob,
  name: string // should the file name be attached here as well?
} | {
  type: "text/plain",
  data: string,
  name: string // should the file name be attached here as well?
};

// update `getExport` prototype w/ abstraction
getExport: (format: ExportFormat, password: string) => Promise<ExportedVault>;
```

In the above code, `ExportedVault.type` is a property enabling type selectivity on `ExportedVault.data` using [discriminated union](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#discriminated-unions) logic.

2025-03-03 14:59 UTC, audreyality commented
> Yes, that would be a good approach. I wouldn't go as far comparing the files (content) as just checking that it contains a data.json and the expected filenames for attachments.

🎨 You could, however, check to see that the attachment files are listed in the `data.json`.

2025-03-13 11:22 UTC, djsmith85 reviewed
Huge thanks to @quexten for working on this. I apologize for the long review time, as this has been stuck between other priorities. We've discussed this internally a couple of times and decided that @bitwarden/team-tools-dev will take ownership and carry this PR. Thanks @audreyality for doing an initial review.

I'm adding some notes and code comments on the PR for transparency, while working through the review/development and testing. I'll be working on resolving them here.

Some other things to note:
- ~~There is currently no error-handling (with the download part)~~ 41a1fe7
- There is no visual indication/error popup to the user in case something fails (only console logs)
- There is no progress indication other than the loading spinner after clicking "Export vault". Not an issue prior as the export files tend to be small, now they will be larger and thus taking longer
- The export once triggered cannot be cancelled

Some of the things mentioned above, are true even now without these changes, but with longer running processes and more potential failure points, we should aim to include them, to provide better feedback to the user.

2025-03-13 11:22 UTC, djsmith85 commented on libs/tools/export/vault-export/vault-export-core/src/services/individual-vault-export.service.ts
> +    for (const cipher of await this.cipherService.getAllDecrypted(activeUserId)) {
⚠️ The list of ciphers retrieved here is not properly filtered. It doesn't skip ciphers with an organizationId assigned to it. Adding that to the if below, would solve this temporarily.

🌱 A larger change, but a better way would be: Consider breaking up the retrieval and filtering done within getDecryptedExport() and only then passing in the list of

2025-03-13 11:22 UTC, djsmith85 commented on libs/tools/export/vault-export/vault-export-core/src/services/individual-vault-export.service.ts
> +        const response = await fetch(new Request(attachment.url, { cache: "no-store" }));
🤔 Something I need to clarify further internally, but the url used here within a development environment, does not point to the place to download an attachment. This might. be a bug within our dev setup and it has gone unnoticed as all other call sites use the CipherController (`apiService.getAttachmentData()`) which returns an `AttachmentResponse` with the correct download location within the url-property.

2025-03-14 12:53 UTC, djsmith85 commented on libs/tools/export/vault-export/vault-export-ui/src/components/export.component.ts
> +  }
Awesome idea and I created https://github.com/bitwarden/clients/pull/13842 which is stacked on top off this PR, to make it easier to review.

2025-03-14 12:57 UTC, djsmith85 commented on libs/tools/export/vault-export/vault-export-core/src/services/individual-vault-export.service.ts
>      }
I don't disagree, although I think will be kept as is for now. https://github.com/bitwarden/clients/pull/13842 definitely improves the weirdness between string | Blob returns.

The way it is currently implemented is by introducing a new format (`zip`). In the future I imagine supporting attachments for any format (`csv`, `json`, `encrypted_json`) and including them would be an option to the user (`includeAttachments: boolean`).

2025-03-24 13:39 UTC, audreyality reviewed
There's a few changes you'll need to make to your test cases. Also a few places where you should be following a lint instead of disabling it.

2025-03-24 13:39 UTC, audreyality commented on libs/tools/export/vault-export/vault-export-core/src/services/individual-vault-export.service.spec.ts
> +      }).rejects.toThrow("Error downloading attachment");
```suggestion
      await expect(async () => {
        await exportService.getExport("zip");
      }).rejects.toThrow("Error downloading attachment");
```

2025-03-24 13:39 UTC, audreyality commented on libs/tools/export/vault-export/vault-export-core/src/services/individual-vault-export.service.spec.ts
> +      }).rejects.toThrow("Error decrypting attachment");
```suggestion
      await expect(async () => {
        await exportService.getExport("zip");
      }).rejects.toThrow("Error decrypting attachment");
```

2025-03-24 13:39 UTC, audreyality commented on libs/tools/export/vault-export/vault-export-core/src/services/individual-vault-export.service.spec.ts
🎨 Consider using whitespace to separate your tests according to arrange/act/assert. If you need more than these 3 groups (for example, you need to assert a precondition), then introduce it with a comment.

2025-03-24 13:39 UTC, audreyality commented on libs/tools/export/vault-export/vault-export-core/src/services/individual-vault-export.service.spec.ts
> +      expect(apiService.getAttachmentData).not.toHaveBeenCalled();
⚠️ This does not assert that the ciphers have been filtered out. It asserts that specific methods shouldn't be called. Either assert the result of the export or update the test case label.

2025-03-24 13:39 UTC, audreyality commented on libs/tools/export/vault-export/vault-export-core/src/services/individual-vault-export.service.spec.ts
> +    it("throws error if attachment can't be downloaded (status !== 200)", async () => {
🎨 Consider testing several status values and asserting this test case affirmatively.

```
it.each([[400], [401], [404], [500]])(
  "throws error if the http request fails (status === %n)",
  async (status) => { /* test case */ }
);
```

2025-03-24 13:39 UTC, audreyality commented on libs/tools/export/vault-export/vault-export-core/src/services/individual-vault-export.service.ts
> +    }
⚠️ You should either use `e` or delete it. You should also assert its type as `unknown`.

🎨 Consider logging `e` using the `SemanticLogger` or `LogService`.

2025-03-24 13:39 UTC, audreyality commented on libs/tools/export/vault-export/vault-export-ui/src/components/export.component.ts
> +        }
⛏️ Consider restructuring these `if` statements to reduce nesting.

2025-03-24 17:16 UTC, djsmith85 commented on libs/tools/export/vault-export/vault-export-core/src/services/individual-vault-export.service.ts
> +    }
Addressed with 1c9dd461438d96256e19fc5a9b9e7f89d6465a7c

2025-03-24 17:17 UTC, djsmith85 commented on libs/tools/export/vault-export/vault-export-core/src/services/individual-vault-export.service.spec.ts
> +    it("throws error if attachment can't be downloaded (status !== 200)", async () => {
Addressed with e5659743154047aa5d6e95e311f44a4b4e823d84

2025-03-24 17:17 UTC, djsmith85 commented on libs/tools/export/vault-export/vault-export-core/src/services/individual-vault-export.service.spec.ts
Addressed with 3ac6dd0b2fad93507f6abe70f54ff1adbb262613

2025-03-24 17:18 UTC, djsmith85 commented on libs/tools/export/vault-export/vault-export-core/src/services/individual-vault-export.service.spec.ts
> +      }).rejects.toThrow("Error decrypting attachment");
Addressed with 4b4c7779c66fdcf329e4d2c8271c059f8a5660dd

2025-03-24 17:19 UTC, djsmith85 commented on libs/tools/export/vault-export/vault-export-core/src/services/individual-vault-export.service.spec.ts
> +      }).rejects.toThrow("Error downloading attachment");
Now part of e5659743154047aa5d6e95e311f44a4b4e823d84

2025-03-24 17:20 UTC, audreyality approved these changes, later dismissed

2025-03-24 18:34 UTC, audreyality approved these changes

2025-03-25 12:30 UTC, merged