[PM-10607] Require userId for getKeyForCipherKeyDecryption
bitwarden/clients pull request #10509
Opened 2024-08-14 12:23 UTC by gbubemismith

## 🎟️ Tracking
[PM-10607](https://bitwarden.atlassian.net/browse/PM-10607)

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-08-14 16:15 UTC, JaredSnider-Bitwarden submitted a review, later dismissed
Auth changes look good!

2024-08-14 16:15 UTC, JaredSnider-Bitwarden commented on libs/common/src/platform/services/fido2/fido2-authenticator.service.spec.ts
Non blocking informational:  In case you didn't know, there is a nice helper function called `mockAccountServiceWith(...)` which makes it easy to mock `AccountService` context without having to stand up your own active account observable.

2024-08-14 16:50 UTC, r-tome approved these changes
AC changes look good!

2024-08-14 17:01 UTC, cagonzalezcs approved these changes

2024-08-14 17:01 UTC, justindbaur approved these changes

2024-08-14 17:50 UTC, shane-melton requested changes

2024-08-14 17:50 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/add-edit.component.ts
> +  protected async encryptCipher(userId: UserId) {
⚠️ This was made `async` so I believe we'll need to `await` the `super` and `cipherService.encrypt` calls OR remove the `async` keyword. Otherwise, we won't properly await the the calls.

2024-08-14 17:50 UTC, shane-melton commented on libs/angular/src/vault/components/add-edit.component.ts
> +  protected async encryptCipher(userId: UserId) {
⚠️ Same here, we made it `async` so we need to await the inner call or remove `async`.

2024-08-14 18:50 UTC, cagonzalezcs approved these changes

2024-08-14 18:52 UTC, JaredSnider-Bitwarden approved these changes

2024-08-14 18:53 UTC, justindbaur approved these changes

2024-08-14 19:15 UTC, shane-melton submitted a review, later dismissed

2024-08-14 23:00 UTC, eliykat submitted a review, later dismissed

2024-08-15 08:13 UTC, r-tome approved these changes

2024-08-15 13:00 UTC, r-tome submitted a review, later dismissed

2024-08-15 13:01 UTC, cagonzalezcs approved these changes

2024-08-15 14:14 UTC, JaredSnider-Bitwarden approved these changes

2024-08-15 14:32 UTC, shane-melton approved these changes

2024-08-15 14:56 UTC, MGibson1 commented on libs/common/src/platform/services/fido2/fido2-authenticator.service.ts
> +          await this.cipherService.getKeyForCipherKeyDecryption(encrypted, activeUserId),
Doesn't this just kick the can down the road to these services? Ultimately the source of which user did the interaction is the component that triggered the action.

2024-08-15 16:55 UTC, gbubemismith commented on libs/common/src/platform/services/fido2/fido2-authenticator.service.ts
> +          await this.cipherService.getKeyForCipherKeyDecryption(encrypted, activeUserId),
Yeah, I agree, but then these changes happened because the new version of `getUserKeyWithLegacySupport` requires the userId to be passed down (I think Auth team used a similar pattern recently). The bug we're addressing hasn't been successfully replicated by QA, and from the reported issue, we see it happens when the user switches accounts.

2024-08-15 16:58 UTC, MGibson1 commented on libs/common/src/platform/services/fido2/fido2-authenticator.service.ts
> +          await this.cipherService.getKeyForCipherKeyDecryption(encrypted, activeUserId),
I believe you're saying that user switch doesn't occur during passkey usage, right?

2024-08-15 17:03 UTC, gbubemismith commented on libs/common/src/platform/services/fido2/fido2-authenticator.service.ts
> +          await this.cipherService.getKeyForCipherKeyDecryption(encrypted, activeUserId),
Yeah user switch doesn't occur during passkeys

2024-08-15 17:34 UTC, MGibson1 commented on libs/common/src/platform/services/fido2/fido2-authenticator.service.ts
> +          await this.cipherService.getKeyForCipherKeyDecryption(encrypted, activeUserId),
Fair enough, but we need to push this up to components

2024-08-15 17:34 UTC, MGibson1 approved these changes

2024-08-15 19:06 UTC, ttalty approved these changes

2024-08-15 19:43 UTC, justindbaur approved these changes

2024-08-15 20:04 UTC, eliykat approved these changes

2024-08-16 16:55 UTC, r-tome approved these changes

2024-08-19 18:09 UTC, cagonzalezcs approved these changes

2024-08-19 18:11 UTC, justindbaur approved these changes

2024-08-19 18:13 UTC, shane-melton submitted a review, later dismissed

2024-08-19 18:14 UTC, vincentsalucci submitted a review, later dismissed

2024-08-19 18:15 UTC, JaredSnider-Bitwarden submitted a review, later dismissed

2024-08-19 18:25 UTC, audreyality approved these changes
📝 Just reviewed the tools code since this is an urgent PR. Looks like everything is in order.

2024-08-20 09:53 UTC, r-tome approved these changes

2024-08-20 14:46 UTC, JaredSnider-Bitwarden submitted a review, later dismissed

2024-08-20 14:47 UTC, r-tome submitted a review, later dismissed

2024-08-20 14:48 UTC, cagonzalezcs submitted a review, later dismissed

2024-08-20 14:51 UTC, justindbaur approved these changes

2024-08-20 14:52 UTC, audreyality approved these changes

2024-08-20 15:33 UTC, audreyality approved these changes

2024-08-20 15:33 UTC, JaredSnider-Bitwarden approved these changes

2024-08-20 15:36 UTC, justindbaur approved these changes

2024-08-20 15:56 UTC, shane-melton approved these changes

2024-08-20 15:57 UTC, cagonzalezcs approved these changes

2024-08-20 16:00 UTC, vincentsalucci approved these changes

2024-08-20 16:00 UTC, merged