[PM-8228] - Create new Premium Component
bitwarden/clients pull request #10514
Opened 2024-08-14 17:04 UTC by jaasen-livefront

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-8228

## 📔 Objective

This PR creates a new premium component as part of the extension refresh epic.

## 📸 Screenshots

![Screenshot 2024-08-14 at 9 58 05 AM](https://github.com/user-attachments/assets/def4f035-5502-426d-9a86-2ac4c09df5f9)

![Screenshot 2024-08-14 at 9 58 15 AM](https://github.com/user-attachments/assets/d1ece589-7d81-4dff-a878-59448d87ea39)

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-08-14 17:31 UTC, shane-melton reviewed
Just a couple questions around the i18n keys/messages added.

2024-08-14 17:31 UTC, shane-melton commented on libs/angular/src/vault/components/premium.component.ts
> +      content: { key: "ppremiumPurchaseAlert" },
❓ Is this supposed to be be `premiumPurchaseAlertV2`?  I don't see that key being used anywhere though it was added to `messages.json`. 

Also, if it is supposed to be the `V2` key, should it be behind the feature flag?

2024-08-14 17:31 UTC, shane-melton commented on apps/browser/src/_locales/en/messages.json
> +  "ppremiumPurchaseAlert": {
❓ Is the double "pp" intentional to get around duplicate keys? Or is there a typo? I see it in a few other keys, and I'm not sure what the desired end state is.

2024-08-14 17:48 UTC, jaasen-livefront commented on libs/angular/src/vault/components/premium.component.ts
> +      content: { key: "ppremiumPurchaseAlert" },
@shane-melton Great question! I'm not sure if updates to the copy are meant to be behind a feature flag. I had originally added `premiumPurchaseAlertV2` but decided to instead rename the existing key to `ppremiumPurchaseAlert` which I've seen done. Looks like I missed this particular key. Is there someone we can reach out to who has knowledge on how to handle these cases?

2024-08-14 17:52 UTC, shane-melton commented on libs/angular/src/vault/components/premium.component.ts
> +      content: { key: "ppremiumPurchaseAlert" },
@danielleflinn Do you have any thoughts on this or know who we should reach out to?

2024-08-14 18:24 UTC, jaasen-livefront commented on libs/angular/src/vault/components/premium.component.ts
> +      content: { key: "ppremiumPurchaseAlert" },
@shane-melton @danielleflinn After chatting with @djsmith85 he's informed me that all copy changes for V2 also need to be hidden behind a feature flag. I've updated the code to reflect this.

2024-08-14 18:25 UTC, jaasen-livefront commented on apps/browser/src/_locales/en/messages.json
> +  "ppremiumPurchaseAlert": {
@shane-melton Updated to use `premiumPurchaseAlertV2`

2024-08-14 19:18 UTC, shane-melton approved these changes

2024-08-14 19:18 UTC, shane-melton commented on apps/browser/src/_locales/en/messages.json
> +  "ppremiumPurchaseAlert": {
Thanks!

2024-08-14 20:31 UTC, djsmith85 requested changes

2024-08-14 20:31 UTC, djsmith85 commented on apps/browser/src/_locales/en/messages.json
> -    "message": "1 GB encrypted storage for file attachments."
This and other deleted ones cannot be removed as they are still used within the premium.component.html.

If the message doesn't change as in `ppremiumSignUpStorage` and `premiumSignUpStorage`, then it might be best to just re-use it. I'm usually the one preaching to replace the existing keys, but in this case the only difference seems to be the removed period at the end.

Context: With the feature flag we are currently keeping both UIs and only once the extension refresh is in production we can start removing the component and any unused keys in the messages.json

2024-08-14 20:31 UTC, djsmith85 commented on apps/web/src/locales/en/messages.json
> +  },
These don't need to be added yet, as the premium-v2.component is specific to browser. The web has it's own component which is not based on the libs/premium.component.

2024-08-14 20:31 UTC, djsmith85 commented on apps/browser/src/billing/popup/settings/premium-v2.component.html
> +    </bit-section>
🌱 @bitwarden/team-billing-dev  Thought for future improvement: Moving this markup into a separate premium-base.component and then this could also be re-used on the desktop, which currently has a specialised markup although it only needs to wrapped with a dialog vs. a popup-page

2024-08-14 20:31 UTC, djsmith85 commented on libs/angular/src/vault/components/premium.component.ts
>      protected stateService: StateService,
⛏️  The stateService is never used and can be removed.

2024-08-15 13:30 UTC, amorask-bitwarden approved these changes

2024-08-15 14:33 UTC, shane-melton approved these changes

2024-08-15 17:31 UTC, merged