[PM- 9666] Implement edit item view individual vault
bitwarden/clients pull request #10553
Opened 2024-08-17 20:10 UTC by alec-livefront

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-9666?atlOrigin=eyJpIjoiNTc4YzRhYmI0Mzg5NDNlNWE4MDNiMjJjYTlkMjI4ODAiLCJwIjoiaiJ9

## 📔 Objective

Adds a new edit item view component to be shown when the extension refresh feature flag is enabled. The new edit item view incorporates the [Cipher Form UI](https://components.bitwarden.com/?path=/docs/vault-cipher-form--docs) to display the cipher information. The new item edit view also:

1. Adds an "attachments" button (when available) which open the new attachments interface in a dialog.
2. For logins, opens the password generator in a new dialog when a user generates a password.

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-08-21 16:01 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +      const dialogRef = this.dialogService.open<
⛏️ We make this a static method or helper function in the `AttachmentsV2Component` to match the pattern we have for other dialogs.

2024-08-21 16:03 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +        madeAttachmentChanges = true;
⛏️ This is only used by the old modalService below for tracking if changes were made. We don't need to update it with the new dialog since we get a `result.action` back.

2024-08-21 16:13 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +    if (this.extensionRefreshEnabled) {
🎨 I'm thinking it may be beneficial to create an entirely separate `addCipherV2` method that we call here if the `extensionRefresh` flag is enabled. 

Since we now have the ability to pass in `DialogParams` instead of having to get a reference to the component, we don't need to all the complicated chaining of `addCipher -> editCipher -> editCipherId`. We can simply have `addCipherV2` call the `openAddEditCipherDialog()` helper with the necessary params and refresh / navigate after success.

⚠️ Speaking of passing params, we are currently missing the pre-selection of active filters in the extensionRefresh path. We need to pass in the available `organizationId`, `collectionId`, and `folderId` to the `initialValues` of the cipherForm config (likely via the DialogParams). If you have questions about this let me know!

2024-08-21 16:18 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +    if (this.extensionRefreshEnabled) {
🎨 Similar suggestion here, I think it would be beneficial to have a separate `editCipherIdV2` method we can call to that we call immediately at the top of `editCipherId` if the flag is enabled. It will make it easier to remove the old code once we remove the feature flag and should ideally make it easier to follow.

For instance, we're returning the `dialogRef.componentInstance` but that should never be used/necessary if the flag is enabled.

2024-08-21 16:23 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/password-generator.component.ts
⚠️ This dialog also needs to support username generation and should be nearly identical to the [`VaultGeneratorDialog` in Browser](https://github.com/bitwarden/clients/blob/041cd87e7e7f414c9155f1d8c95804aa841f454d/apps/browser/src/vault/popup/components/vault-v2/vault-generator-dialog/vault-generator-dialog.component.ts#L53), except that it should use `bit-dialog` instead of the `popup-page`.

We'll likely want to rename this to something like `WebVaultGeneratorDialog` as well to better distinguish the two.

2024-08-21 16:29 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
> +  async onPasswordGenerationEvent(formGroup: FormGroup) {
⚠️ This shouldn't be necessary after switching to the `CipherFormGenerationService`.

2024-08-21 16:31 UTC, shane-melton commented on libs/angular/src/utils/add-edit-query-params.ts
⛏️ Can we move this to the `/libs/vault/src/cipher-form` and perhaps rename it to `cipher-form-query-params.ts` to keep everything together?

2024-08-21 16:33 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +    const component = (await this.editCipher(cipher, null, true)) as
🎨 Similar to the other `v2` suggestions, we can check the flag here and if true use the `editCipherIdV2()` method instead to avoid the weirdness of needing to return the component instance when unnecessary.

2024-08-21 16:34 UTC, shane-melton commented on libs/vault/src/cipher-form/components/attachments/cipher-attachments.component.ts
👍 Thanks for adding the `onRemoveSuccess` event!

2024-08-21 16:34 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
> +    { provide: CipherFormGenerationService, useClass: DefaultCipherFormGenerationService },
ℹ️ Here is where you can override the `CipherFormGenerationService` with a Web variant.

2024-08-21 16:36 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
> +        takeUntil(this.destroy$),
⛏️ We should use `takeUntilDestroyed()` and call this method from the constructor.

2024-08-21 16:38 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
> +    if (cipher.edit) {
⚠️ `cipher.edit` represents that the cipher is editable not that we're in edit mode. We need to check `this.config.mode` instead.

2024-08-21 16:39 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
> +    this.onSavedCipher.emit(this.cipher);
❓ I don't think we need this `onSavedCipher` event since we're in a dialog and are returning the result/action above. Is it being used somewhere else?

2024-08-21 16:40 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
> +    await this.router.navigate([], {
⚠️ We can't close the dialog and then navigate away. We don't know if that's what the user of the dialog always wants. If so, navigation should be the responsibility of anyone that opens the dialog.

2024-08-21 16:42 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
> +  async edit(): Promise<void> {
⚠️ I don't think this is used anywhere and can be removed? There is no edit button since we're already in the edit dialog.

2024-08-21 16:43 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
> +    this.dialogRef.close();
⛏️  We should close the Dialog with a `Canceled` action so the consumer of the dialog can respond appropriately.

⚠️ We should not navigate and let the consumer decide what to do.

2024-08-21 16:46 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
> +    this.attachmentDialogRef.close({ action: AttachmentDialogResult.Closed });
❓ I don't believe this dialog ref is ever updated anywhere? I see it being imported in the constructor, but that will likely be `null` the first time and then never set again.

Should we be setting its value in the `openAttachmentsDialog()` above?

2024-08-21 16:48 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
> +          const cipherId = (getCipherIdFromParams(params) || this.cipher?.id) as CipherId;
⚠️ `params` is not a `Params` object anymore (but instead our custom `QueryParams` object) and will have lost any reference to the old `cipherId` query param. We need to put that logic to check for the old `cipherId` param in the `QueryParams` constructor instead.

2024-08-21 16:48 UTC, shane-melton commented on libs/angular/src/utils/add-edit-query-params.ts
> +export class QueryParams {
❓ 💭 Perhaps we should rename this to `CipherFormQueryParams` as well to make it less generic.

2024-08-21 16:49 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
> +  onDeletedCipher = new EventEmitter<CipherView>();
🎨 We should be able to remove these `EventEmitters`.

2024-08-21 16:51 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
> +  cipher: CipherView;
🎨 A lot of these properties are unused or not relevant to this dialog anymore. (Perhaps left over from copy/paste from the other AddEditComponent). We should go through and remove the unused properties.

2024-08-21 16:53 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
> +    this.route.queryParams
💭 🎨 Thinking about this some more, we shouldn't even been watching the route params in this dialog. The parent page component should be doing that and passing in the values as `DialogParams` instead of route query params.

2024-08-26 13:28 UTC, alec-livefront commented on libs/vault/src/cipher-form/components/login-details-section/login-details-section.component.ts
> +      this.passwordGenerationEvent.emit(this.loginDetailsForm);
👍 I've added a `WebCIpherFormGenerationService` at `apps/web/src/app/vault/services/web-cipher-form-generation.service.ts` in this commit: [4ea35ce](https://github.com/bitwarden/clients/pull/10553/commits/4ea35cedd962cebf8ae84c5b6ade7b3c6d6113b2)

2024-08-26 13:40 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +      const dialogRef = this.dialogService.open<
👍 [55ed985](https://github.com/bitwarden/clients/pull/10553/commits/55ed9854496fa2e72713f616b58c1de1529c6ae5)

2024-08-26 13:47 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +    if (this.extensionRefreshEnabled) {
Good call. I struggled with this a big though because the template file calls `addCipher`, and I wasn't sure if we want to add conditional logic to the template file. I ended up just short circuiting the existing `addCipher`, directing the flow to `addCipherV2` if the extension refresh flag is enabled. Let me know what you think / if you have a better suggestion! [8f7ee9e](https://github.com/bitwarden/clients/pull/10553/commits/8f7ee9ea7ff73229534047754df62daf698daf81)

2024-08-26 13:48 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
> +          const cipherId = (getCipherIdFromParams(params) || this.cipher?.id) as CipherId;
I don't think this one is relevant anymore since we're now passing data via DialogParams.

2024-08-26 13:49 UTC, alec-livefront commented on libs/angular/src/utils/add-edit-query-params.ts
> +export class QueryParams {
I ended up scrapping this move since we pass the data via DialogParams now.

2024-08-26 15:43 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +    if (this.extensionRefreshEnabled) {
👍 c4892a1a79ef12ff0665e87b22d6a62ef121191b

2024-08-26 15:45 UTC, alec-livefront commented on libs/angular/src/utils/add-edit-query-params.ts
I scrapped the changes to `QueryParams` since we are passing data via DialogParams now.

2024-08-26 15:47 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
> +        takeUntil(this.destroy$),
A little confused on this one. I ended up calling `this.setHeader` in the `ngOnInit`. Maybe that satisfies your request in conjunction with the other changes?

2024-08-26 15:49 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
> +    this.onSavedCipher.emit(this.cipher);
👍 removed

2024-08-26 15:49 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
> +  async edit(): Promise<void> {
👍 removed

2024-08-26 15:51 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
> +    this.attachmentDialogRef.close({ action: AttachmentDialogResult.Closed });
👍 removed

2024-09-05 21:52 UTC, shane-melton requested changes
Getting very close! Just a few more things we need to clean up before we're ready to go.

2024-09-05 21:52 UTC, shane-melton commented on libs/vault/src/cipher-form/components/web-generator-dialog/web-generator-dialog.component.ts
> +   * Opens the vault generator dialog in a full screen dialog.
⛏️ This comment doesn't apply to the Web dialog (its only full screen on Browser)

2024-09-05 21:52 UTC, shane-melton commented on libs/vault/src/cipher-form/components/login-details-section/login-details-section.component.ts
> +  extensionRefreshEnabled: boolean = false;
⛏️ We should be able to remove this property entirely now

2024-09-05 21:52 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
>  export interface AddEditCipherDialogParams {
⚠️ All of these dialog params are already specified in the `cipherFormConfig` object and will likely lead to confusion. We should be able to use only the `cipherFormConfig` property and remove the others to have a single source of truth.

2024-09-05 21:52 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
> +  cipher: CipherView;
🎨 Looks like we can clean up a few more of these properties that are unused/redundant with the config param.
- `cipher` - Not used in the template and only used in `ngOnInit` to set `this.organization` (also unused)
- `cipherId` - Can be replaced with `this.config.originalCipher?.id`
- `organization` - Unused
- `cipherType` - Can be replaced with `this.config.cipherType`
- `cloneMode` - Can be replaced with `this.config.mode === "clone"`
- `destroy$` - We're using `takeUntilDestroyed()` so this subject is no longer necessary

2024-09-05 21:52 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
> +    private organizationService: OrganizationService,
⛏️ We don't need the `organizationService`.

2024-09-05 21:52 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +      const dialogRef = AttachmentsV2Component.open(this.dialogService, {
💭 We have a `viewOnly` mode for the original modal attachments dialog. We probably need to investigate if that is still necessary in our shared component as well. Not something we need to address right now, but wanted to make note of it.

2024-09-05 21:52 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +        cipher: null,
🎨 Related to my suggestion about the dialog params, we should be able to just pass in the `config` object here (setting any other necessary properties on it instead) and remove the others (`cipher`, `cipherType`, etc.)

2024-09-05 21:52 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +      | AddEditComponentV2;
⛏️ We're no longer returning the `AddEditComponentV2` and can remove this.

2024-09-05 21:52 UTC, shane-melton commented on libs/vault/src/cipher-form/components/login-details-section/login-details-section.component.ts
> +    private configService: ConfigService,
⛏️ We can remove the configService too since we no longer need the feature flag value.

2024-09-05 21:52 UTC, shane-melton commented on libs/vault/src/cipher-form/components/web-generator-dialog/web-generator-dialog.component.ts
> +const slideIn = trigger("slideIn", [
⛏️ We don't use this `slideIn` animation for the Web dialog and it can be removed.

2024-09-05 21:52 UTC, shane-melton commented on libs/vault/src/cipher-form/services/web-cipher-form-generation.service.ts
👍 Looks great!

2024-09-05 21:52 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +    if (this.extensionRefreshEnabled) {
Short circuiting in the method is what I was thinking too and I think it looks much better this way! Thanks!

2024-09-09 16:02 UTC, alec-livefront commented on libs/vault/src/cipher-form/components/web-generator-dialog/web-generator-dialog.component.ts
> +   * Opens the vault generator dialog in a full screen dialog.
939d3f454a42a0d56ea85567ea444bbe4143840e

2024-09-09 21:03 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +      | AddEditComponentV2;
[ba47af1](https://github.com/bitwarden/clients/pull/10553/commits/ba47af11c85be11aaa43dd985c070c66b4f64e4c)

2024-09-09 21:08 UTC, alec-livefront commented on libs/vault/src/cipher-form/components/login-details-section/login-details-section.component.ts
> +    private configService: ConfigService,
[39215b4](https://github.com/bitwarden/clients/pull/10553/commits/39215b470bc5be0ea47e689b22e799e4ff1c72da)

2024-09-09 23:01 UTC, alec-livefront commented on libs/vault/src/cipher-form/components/web-generator-dialog/web-generator-dialog.component.ts
> +const slideIn = trigger("slideIn", [
[3bd6b8d](https://github.com/bitwarden/clients/pull/10553/commits/3bd6b8d43e1adc195ba43d18fff8458ac199aa4b)

2024-09-10 03:06 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +      const dialogRef = AttachmentsV2Component.open(this.dialogService, {
Yeah that seems like something we'll want to clean up after extension refresh is permanent?

2024-09-10 03:07 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
> +  cipher: CipherView;
[d81a9b7](https://github.com/bitwarden/clients/pull/10553/commits/d81a9b7955715663189743d5ab8b5616b25d5bef)

2024-09-10 03:09 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
>  export interface AddEditCipherDialogParams {
I think I was expecting we'd need this to handle query parameters but that doesn't seem to be the case 👍

2024-09-10 23:35 UTC, shane-melton requested changes

2024-09-10 23:35 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
> +    @Inject(DIALOG_DATA) public params: { cipherFormConfig: CipherFormConfig; cloneMode?: boolean },
⛏️ We still shouldn't need the extra `cloneMode` property, `cipherFormConfig.mode === "clone"` should be enough.

2024-09-10 23:35 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
> +  config: DialogConfig,
⛏️ We still want the generic typing here in order to convey the configuration options available. We can likely just use the `CipherFormConfig` type.

2024-09-10 23:35 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +        cipher: null,
⛏️ We can clean these unused params now and just pass the `config`.

2024-09-10 23:35 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +        cipher: cipherView,
⛏️ Similar here, we don't need `cipher` or `cloneMode` now that we're just using the `config` type.

2024-09-10 23:35 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
> +  protected destroy$ = new Subject<void>();
⛏️ `destroy$` is unused and can be removed along with the `OnDestroy` hook down below.

2024-09-10 23:35 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
> +  cloneMode: boolean = false;
⛏️ `cloneMode` can be replaced with `this.config.mode === "clone"`

2024-09-11 15:51 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
> +    @Inject(DIALOG_DATA) public params: { cipherFormConfig: CipherFormConfig; cloneMode?: boolean },
Sorry, I think I missed this in your previous review. I was able to completely remove mentions of `cloneMode ` from this component. 👍 [832b4b1](https://github.com/bitwarden/clients/pull/10553/commits/832b4b1fcacadcc30b14f65eeb4097b615519295)

2024-09-11 15:51 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
> +  config: DialogConfig,
[b0088e7](https://github.com/bitwarden/clients/pull/10553/commits/b0088e7356036632e62e5edfdff6a37d5f5f46f7)

2024-09-11 15:51 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +        cipher: null,
Taken care of in this commit: [832b4b1](https://github.com/bitwarden/clients/pull/10553/commits/832b4b1fcacadcc30b14f65eeb4097b615519295)

2024-09-11 15:52 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +        cipher: cipherView,
Taken care of in this commit: [832b4b1](https://github.com/bitwarden/clients/pull/10553/commits/832b4b1fcacadcc30b14f65eeb4097b615519295)

2024-09-11 15:53 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
> +  cloneMode: boolean = false;
It doesn't seem `cloneMode` actually does anything in this component? I've removed it but let me know if I've missed something.

2024-09-11 15:56 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
> +  protected destroy$ = new Subject<void>();
[845e539](https://github.com/bitwarden/clients/pull/10553/commits/845e53960723fa88c26416845fb271f9980eedff)

2024-09-11 17:11 UTC, cturnbull-bitwarden submitted a review, later dismissed

2024-09-11 20:55 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
> +    @Inject(DIALOG_DATA) public params: { cipherFormConfig: CipherFormConfig; cloneMode?: boolean },
No problem! Glad we were able to completely remove it!

2024-09-11 20:56 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
> +  cloneMode: boolean = false;
Agreed, I don't think its needed in this V2 version.

2024-09-11 21:09 UTC, shane-melton requested changes
Just a few more things I noticed after playing around with this locally

2024-09-11 21:09 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +    return openAddEditCipherDialog(this.dialogService, {
⚠️ We need to await a result from the dialogRef instead of returning here. That way we can  `refresh()` the vault like we do down below in `editCipherV2()`. Otherwise, the vault becomes stale with the outdated cipher.

2024-09-11 21:09 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +    return openAddEditCipherDialog(this.dialogService, {
❓ @danielleflinn After successfully creating a new item in the Web vault, should the user be returned to the Vault or should the View dialog open for the newly created cipher?

2024-09-11 21:09 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/add-edit-v2.component.ts
> +  Deleted = "deleted",
⛏️ We don't need the `Deleted` result type because its not actually possible to delete a cipher from this dialog now.

2024-09-11 22:42 UTC, danielleflinn commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +    return openAddEditCipherDialog(this.dialogService, {
@shane-melton Ideally it would show the View Item dialog if possible (this keeps things consistent with the new Extension and with what Desktop does).

I'd also expect after saving from the Edit item view that the dialog would update to the View item view. 

Let me know if this introduces a bunch of technical complexity

2024-09-12 20:00 UTC, alec-livefront commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +    return openAddEditCipherDialog(this.dialogService, {
I've updated the component to open the View dialog on edit/add 👍

2024-09-17 19:52 UTC, shane-melton reviewed
This looks good to go! But, it does look like we have some merge conflicts 😢

2024-09-18 16:33 UTC, alec-livefront commented
> This looks good to go! But, it does look like we have some merge conflicts 😢

@shane-melton Should be up to date now!

2024-09-18 17:25 UTC, shane-melton approved these changes
Looks good! Thanks for all the work on this!

2024-09-18 17:48 UTC, merged