[PM-10974] Edit/Add Cipher - back handling
bitwarden/clients pull request #10620
Opened 2024-08-19 18:17 UTC by nick-livefront

## 🎟️ Tracking

[PM-10974](https://bitwarden.atlassian.net/browse/PM-10974)

## 📔 Objective

Route the user properly back through history when creating or editing a cipher.
- The hurdle here was _how_ the user got to the add/edit component. 
- In the case where they were already viewing the cipher, navigating them to the `view-cipher` route would result in the user needing to double click on the back button before getting back to the vault.

## 📸 Screenshots

| New Cipher | Edit Cipher | Clone Cipher|
|-|-|-|
|<video src="https://github.com/user-attachments/assets/20236bb8-7312-4965-a322-f2ec06bb8225" />|<video src="https://github.com/user-attachments/assets/325e0ea5-9221-4601-b3fd-95f8b6b95d63" />|<video src="https://github.com/user-attachments/assets/c9f9abae-ecda-420d-938d-d48f1b128243" />|

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-08-19 20:53 UTC, shane-melton requested changes
One tiny nit with the comment language, otherwise looks good!

2024-08-19 20:53 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.ts
> +    // In this case, we want to go back to the view-cipher page while also removing it from the
⛏️ I think instead of "In this case..." we want to say "In case of creating a new cipher..."

2024-08-20 14:45 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.ts
> +    // In this case, we want to go back to the view-cipher page while also removing it from the
👍 [c2538ef](https://github.com/bitwarden/clients/pull/10620/commits/c2538ef8890740aabbaa3e82f03e94acd78aeb08)

2024-08-20 21:23 UTC, shane-melton approved these changes

2024-08-21 00:12 UTC, merged