[PM-4473] use anon layout for send access component
bitwarden/clients pull request #10699
Opened 2024-08-23 16:28 UTC by jaasen-livefront

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-4473

## 📔 Objective

This PR uses the anon layout for the send access component. Some refactoring of the component was required in order to satisfy the design specs and the anon layout requirements.

## 📸 Screenshots

|Before|After|
---|---
|![Screenshot 2024-08-23 at 9 28 27 AM](https://github.com/user-attachments/assets/62466653-03f9-4eaa-91bd-7c98ba24aa6b)|![Screenshot 2024-08-23 at 9 27 13 AM](https://github.com/user-attachments/assets/7c88acd2-762d-4e34-8b84-7bcadf18800e)|

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-08-26 23:28 UTC, JaredSnider-Bitwarden submitted a review, later dismissed
`AnonLayout` configuration and `AnonLayoutWrapperDataService` looks good!

2024-08-27 12:18 UTC, djsmith85 requested changes

2024-08-27 12:18 UTC, djsmith85 commented on apps/web/src/app/oss-routing.module.ts
> +          pageSubtitle: "sendAccessCreatorIdentifier",
We should not set the subTitle here. 

If a Send is password-protected the creator cannot be shown correctly, as the Send needs to be decrypted first.

I suggest we only set `sendAccessCreatorIdentifier` via the `layoutWrapperDataService` once it becomes available.

2024-08-27 16:36 UTC, jaasen-livefront commented on apps/web/src/app/oss-routing.module.ts
> +          pageSubtitle: "sendAccessCreatorIdentifier",
@djsmith85 Agreed! Done. ;)

2024-08-27 17:16 UTC, djsmith85 approved these changes

2024-08-27 17:18 UTC, merged