[PM-11350] Use shared expiration year normalization util function
bitwarden/clients pull request #10735
Opened 2024-08-26 21:07 UTC by jprusik

## 🎟️ Tracking

PM-11350

## 📔 Objective

We don’t currently enforce a normalized format for stored, user-entered values of expiry year (e.g. credit cards). Because of this, values like “00” are ambiguous, and invalid values like “0302", "awdawdawd", “40000”, and “4.5” are accepted.

![Screenshot 2024-08-26 at 1 02 41 PM](https://github.com/user-attachments/assets/36721416-8427-4950-b01f-3e7ff7ed870a)

These changes aim to normalize user submitted values to a YYYY format (given the context of expiration) so that downstream logic doesn’t have ensure proper handling these cases and to more authoritatively establish the full date to be stored.

Note, format normalization during new/edit cipher views happens upon submit (not on field value change).

## 📸 Screenshots

https://github.com/user-attachments/assets/d20dbb4d-4d9d-4aac-9a5c-44bfd406b6f5

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-08-26 21:11 UTC, jprusik commented on libs/common/src/vault/utils.ts
> +  // is more likely to be a mistake than an intentional value for the far past or far future.
Because we have and maintain the context of usage intent (expiry year), we do not need to support _all_ valid year formats (e.g. "334", "203054", "-3653", "0"), since they aren't relevant

2024-08-27 18:42 UTC, jprusik commented on libs/common/src/vault/utils.ts
> +    const currentCentury = `${new Date().getFullYear()}`.slice(0, 2);
We could get more clever with this re: calculation around the turn of a century, but we have a few years before we practically have to worry about that.

2024-08-28 12:41 UTC, Jingo88 submitted a review, later dismissed

2024-08-28 15:01 UTC, djsmith85 requested changes

2024-08-28 15:01 UTC, djsmith85 commented on libs/common/src/vault/utils.ts
> +export function normalizeExpiryYearFormat(yearInput: string | number): Year | null {
:art: Please add unit tests to check for all the different edge cases.

2024-08-28 17:58 UTC, cagonzalezcs commented on libs/common/src/vault/utils.ts
> +export function normalizeExpiryYearFormat(yearInput: string | number): Year | null {
+1

2024-08-28 18:46 UTC, jprusik commented on libs/common/src/vault/utils.ts
> +export function normalizeExpiryYearFormat(yearInput: string | number): Year | null {
Ah, they were updated at the callsite, but I can copy them down here too 👍

2024-08-28 19:11 UTC, jprusik commented on libs/common/src/vault/utils.ts
> +export function normalizeExpiryYearFormat(yearInput: string | number): Year | null {
Ah, good call - I actually found another uncovered edge; commit incoming

2024-08-28 20:57 UTC, jprusik commented on libs/common/src/vault/utils.ts
> +export function normalizeExpiryYearFormat(yearInput: string | number): Year | null {
036f16d90c017f27644897650b9a3d66584f1d35

2024-08-29 08:15 UTC, djsmith85 approved these changes

2024-08-29 13:43 UTC, cagonzalezcs approved these changes

2024-08-29 13:54 UTC, Jingo88 approved these changes

2024-09-03 19:12 UTC, merged