[PM-8125] Move Trash to the Vault settings page
bitwarden/clients pull request #10736
Opened 2024-08-27 00:54 UTC by gbubemismith

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-08-28 19:50 UTC, danielleflinn requested changes
One design bug I caught; otherwise looks good. Thanks!

2024-08-28 19:50 UTC, danielleflinn commented on apps/browser/src/vault/popup/settings/trash-list-items-container/trash-list-items-container.component.html
> +    <h2 class="tw-font-bold" bitTypography="h5">
This should be `bitTypography="h6"` and I think the `tw-font-bold` class is not needed. The font-weight should be applied from the bitTypography element already.

The styling of the section header should look the same as the section header on the cipher Edit/View pages.

2024-08-29 00:15 UTC, danielleflinn approved these changes

2024-08-29 00:17 UTC, danielleflinn commented on apps/browser/src/vault/popup/settings/trash-list-items-container/trash-list-items-container.component.html
> +    <h2 class="tw-font-bold" bitTypography="h5">
@gbubemismith can you update the PR screen recording or drop a screenshot here of the update? 

I'm OOO the next few days so I went ahead and approved this though so you aren't blocked while I'm out

2024-08-29 15:35 UTC, gbubemismith commented on apps/browser/src/vault/popup/settings/trash-list-items-container/trash-list-items-container.component.html
> +    <h2 class="tw-font-bold" bitTypography="h5">
@danielleflinn, the PR has been updated with the latest screen recording. Thank you.

2024-08-30 19:37 UTC, Jingo88 approved these changes

2024-08-30 19:46 UTC, merged