[SM-10995]-Removing feature flag
bitwarden/clients pull request #10784
Opened 2024-08-29 02:29 UTC by cd-bitwarden

## 🎟️ Tracking

[
](https://bitwarden.atlassian.net/browse/PM-10995)
## 📔 Objective

Remove feature flag vault-bulk-management-action
## 📸 Screenshots

None 

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-04 20:33 UTC, shane-melton requested changes
This looks good! Just have a few minor suggestions/nits.

2024-09-04 20:33 UTC, shane-melton commented on apps/web/src/app/vault/components/vault-items/vault-cipher-row.component.ts
> -  protected moveToOrganization() {
🎨 We should also be able to remove these event types from the `VaultItemEvent` type since they're no longer accessible. (e.g. `moveToOrganization` and `viewCipherCollections` in [this file](https://github.com/bitwarden/clients/blob/main/apps/web/src/app/vault/components/vault-items/vault-item-event.ts))

2024-09-04 20:33 UTC, shane-melton commented on apps/web/src/app/vault/components/vault-items/vault-items.component.ts
> +    return this.showDelete();
🎨 Since this is just wrapping `showDelete()` we can probably consolidate them to help prevent any confusion.

2024-09-04 20:33 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/bulk-action-dialogs/bulk-move-dialog/bulk-move-dialog.component.ts
⛏️ The `configService` is no longer used by this component and can be removed.

2024-09-04 20:33 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault.component.ts
⛏️ The configService is no longer used by this component and can be removed.

2024-09-11 20:22 UTC, cd-bitwarden commented on apps/web/src/app/vault/individual-vault/vault.component.ts
I think we do need it on this file, please verify and let me know if I'm wrong 😆

2024-09-17 14:39 UTC, cd-bitwarden commented
closing this PR as I had to open this PR again after changing the branch name :) 

https://github.com/bitwarden/clients/pull/11000

2024-09-17 14:39 UTC, closed without merging