[PM-11462] [Defect] Getting mp reprompt on edit
bitwarden/clients pull request #10836
Opened 2024-08-31 04:00 UTC by alec-livefront

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-11462?atlOrigin=eyJpIjoiYmJiMDhjNzQyNjk0NGEyY2ExYzNlYTMwMjI3YjFjNmMiLCJwIjoiaiJ9

## 📔 Objective

- Prevent MP re-prompt when an item is edited from the view dialog
- Maintains MP re-prompt when an item is edited directly from URL (`action="edit"` in URL when page is loaded)

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-09 19:42 UTC, shane-melton requested changes
I think we could simplify this a bit to make things easier to understand, especially when we have to come back in an remove the `extension-refresh` feature flag . Let me know what you think!

2024-09-09 19:42 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +    if (!extensionRefreshEnabled) {
🎨 Instead of having to check this feature flag multiple times and track the reason for the negation, could we instead pass in an argument to skip the password re-prompt (e.g. `skipReprompt: boolean = false`). Then, the `viewCipherById` callback can pass in `true` while the `queryParams` subscription above can remain unchanged (default to always re-prompting). What do you think?

2024-09-09 19:42 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +    if (!this.extensionRefreshEnabled) {
🎨 Same here, if we add a `skipReprompt` argument that defaults to `false` we should be able to leave everything else alone except the `viewCipherById()` `edit` action where we would pass in `true` (since we know they already passed the re-prompt)

2024-09-09 19:42 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +  protected cipherEditedFromViewDialog: boolean;
❓ Why do we need this in the org vault and not the individual vault?

2024-09-11 14:48 UTC, alec-livefront commented
@shane-melton I've reworked this based on your suggestion of adding a `skipMPReprompt` argument.

I noticed an issue that was present in the original work as well: if you were to close the `re-prompt dialog` the `edit dialog` would still open. I believe this is because the `editCipher` is called an additional time when the URL changes. I was able to avoid this by setting a `passwordRePromptCancelled` flag, but I'm not sure if that's the appropriate approach. Let me know what you think.

2024-09-11 16:20 UTC, alec-livefront commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +  protected cipherEditedFromViewDialog: boolean;
I was able to eliminate this in the rewrite.

2024-09-20 17:57 UTC, alec-livefront commented
Will be handled by the changes in PM-12389

2024-09-20 17:57 UTC, closed without merging