[PM-8111] Browser Refresh: LoginComponent
bitwarden/clients pull request #10856
Opened 2024-09-02 15:51 UTC by rr-bw

- **setup new LoginComponent files in libs/auth**
- **update pageTitle**
- **handle loading email settings**
- **setup web-login.service.ts**
- **implement web onInit**
- **fill out webOnInit**
- **refactor getOrgPolicies call**
- **update import**
- **add validateEmail logic**
- **handle registerRoute**
- **add showPasswordless flag**
- **handle captcha**
- **handle startAuthRequestLogin()**
- **add handleMigrateEncryptionKey to default and web service**

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-10-03 18:17 UTC, danielleflinn commented
@alec-livefront can you double check that the SVGs for the vault are using the `art` tailwind color variables? The hand illustration looks correct.

The "Get master password" hint link in the browser screenshot looks off. Is there some browser specific css that is overriding the Design System `bit-link` styles?

2024-10-04 02:56 UTC, alec-livefront commented
> @alec-livefront can you double check that the SVGs for the vault are using the `art` tailwind color variables? The hand illustration looks correct.
> 
> The "Get master password" hint link in the browser screenshot looks off. Is there some browser specific css that is overriding the Design System `bit-link` styles?

Ah yes, I see that now. I applied the same styles I had to apply for the "Create account" link. Does this look better?

![Screenshot 2024-10-03 at 9 52 59 PM](https://github.com/user-attachments/assets/bf611112-c119-4b1e-92ba-6db90e73ee06)

2024-10-07 21:50 UTC, rr-bw commented
@alec-livefront I'm still reviewing this, but for now I did notice that clicking "Login with master password" on Web does not automatically navigate to the vault.


https://github.com/user-attachments/assets/d3287938-eb68-44b4-8bde-aa64419278fa

2024-10-08 17:29 UTC, danielleflinn commented
@alec-livefront I was just chatting with @JaredSnider-Bitwarden about an open design question we had for where we could put a "back" action for the web and desktop implementation. We are aligned with adding a 2nd secondary styled button below "Log in with Device". I've updated [Figma to show this change](https://www.figma.com/design/3nTnAyNBMyBKOgvE5ATS5R/Auth-pages-refresh?node-id=12-2404&t=shLP6EEavTy3Gqcv-4). Could you add this to the PR?

2024-10-08 18:02 UTC, rr-bw reviewed
Thanks for your work on this. Some comments below.

2024-10-08 22:26 UTC, rr-bw commented on libs/auth/src/angular/login/login.component.html
> +      (click)="saveEmailSettings()"
Duplication: I noticed we are running `saveEmailSettings()` within the `goToHint()` method on the mousedown event and also on the click event.

2024-10-09 18:47 UTC, rr-bw commented on libs/auth/src/angular/login/login.component.ts
> +    this.loginEmailService.setLoginEmail(this.formGroup.value.email);
I missed this earlier. We should `await` this promise.

2024-10-10 14:46 UTC, alec-livefront commented on libs/auth/src/angular/login/login.component.ts
> +    this.loginEmailService.setLoginEmail(this.formGroup.value.email);
👍 [6d980bf](https://github.com/bitwarden/clients/pull/10856/commits/6d980bfadde687bc2a1377776e7f3f2079850746)

2024-10-10 14:47 UTC, alec-livefront commented on libs/auth/src/angular/login/default-login-component.service.ts
> +    const webVaultUrl = env.getWebVaultUrl();
I think Jared  mentioned we shouldn't hard code any URLs, and that there shouldn't be a scenario where `url` is `null`. Is that accurate @JaredSnider-Bitwarden?

2024-10-10 14:48 UTC, alec-livefront commented on libs/auth/src/angular/login/login.component.html
> +      (click)="saveEmailSettings()"
I've simplified this, removing `saveEmailSettings` and moving `gotToHint` to `(click)`: [6e337e1](https://github.com/bitwarden/clients/pull/10856/commits/6e337e1e7d6fbe403800981be25b0fc61721554e)

2024-10-10 14:49 UTC, alec-livefront commented on libs/auth/src/angular/login/login.component.html
> +        (keyup.enter)="clientType === ClientType.Desktop ? continue() : null"
Good call! [57044a6](https://github.com/bitwarden/clients/pull/10856/commits/57044a685593f666019adc571002b522f31f2077)

2024-10-10 14:59 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/login/default-login-component.service.ts
> +    const webVaultUrl = env.getWebVaultUrl();
Yes, I just finished a decent refactor of the `WebEnvironmentService` + unit tests for it. In either the US QA or US EU environments, the `webVault` url will always exist. We don't want this service to have a randomly hardcoded URL that doesn't work for local or QA environments. The URL should always be provided by the env service.

2024-10-10 15:02 UTC, alec-livefront commented on libs/auth/src/angular/login/default-login-component.service.ts
> +    return this.clientType == ClientType.Web;
[3868dcb](https://github.com/bitwarden/clients/pull/10856/commits/3868dcbc601861ae2fbeeffa0802fec2e7bad506)

2024-10-10 15:05 UTC, alec-livefront commented on libs/auth/src/angular/login/login.component.ts
> +      await this.goAfterLogIn(authResult.userId);
[47ce605](https://github.com/bitwarden/clients/pull/10856/commits/47ce605e77dbb8ea04681d3a9f4917d1010de997)

2024-10-10 15:07 UTC, alec-livefront commented on libs/auth/src/angular/login/login.component.html
> +      <ng-container *ngIf="isLoginWithPasskeySupported()">
👍 [8975b60](https://github.com/bitwarden/clients/pull/10856/commits/8975b60e1edfe509e9ea35b75c163162b9aff256)

2024-10-10 15:29 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/login/login.component.html
> +      <ng-container *ngIf="isLoginWithPasskeySupported()">
@rr-bw and @alec-livefront , login with passkey is [only supported on web](https://bitwarden.com/help/login-with-passkeys/). We should trust but verify any Figma designs against the current implementation (i.e., we should look at the existing v1 component to see what is supported). 

We also should not be putting any comments about which client supports the feature into the new login component if that is delegated to the service. It's the service's job to tell the component and any comments like that can get out of sync easily w/ the service implementation.

2024-10-10 16:02 UTC, alec-livefront commented
> @alec-livefront I was just chatting with @JaredSnider-Bitwarden about an open design question we had for where we could put a "back" action for the web and desktop implementation. We are aligned with adding a 2nd secondary styled button below "Log in with Device". I've updated [Figma to show this change](https://www.figma.com/design/3nTnAyNBMyBKOgvE5ATS5R/Auth-pages-refresh?node-id=12-2404&t=shLP6EEavTy3Gqcv-4). Could you add this to the PR?

👍 Added a back button: [ea68572](https://github.com/bitwarden/clients/pull/10856/commits/ea685728ca0fb23bd0c89fbe81bafa43a49c2b45)

@danielleflinn a question for you on something I noticed: In dark mode on the desktop client do we need to swap the vault logo with a specific dark version? It doesn't seem to have very much contrast for parts (sorry, for the photo - I can't seem to take screenshots of electron apps for some reason right now)

![IMG_2449](https://github.com/user-attachments/assets/4a9c501c-58bc-4061-a095-266b9a06c6b4)

2024-10-10 16:31 UTC, danielleflinn commented
@alec-livefront we style all SVGs in the app using tailwind color variables so that a single SVG can be used and styling can be applied based on the theme. You should be able to open the SVG and replace any hardcoded hex codes with `tw-fill-art-accent`/`tw-stroke-art-accent` for any teal / light blue accents you see in Figma and `tw-fill-art-primary`/`tw-stroke-art-primary`  for the dark blue.

2024-10-10 21:07 UTC, alec-livefront commented on libs/auth/src/angular/login/login.component.html
> +      <ng-container *ngIf="isLoginWithPasskeySupported()">
👍 3936ccd979d6da064c2cc04d3b2c540d6fcad570

2024-10-16 03:12 UTC, alec-livefront commented
@JaredSnider-Bitwarden this should be ready for another look. Based on our discussion Thursday:

- Combined `validateEmail` and `continue` methods into just `continue`
- Remove the `showToast` call from the `continue` method as we'll be showing login errors via inline errors via [PM-3301](https://github.com/bitwarden/clients/pull/11443)
- Change goAfterLogin so that if we evaluate master password for all clients (moved logic to `evaluatePassword` and borrowed logic from lock component)
- Added test for `DefaultLoginCcomponentService`
- Removed updating policies
- Removed `webOnInit` as it doesn't seem checking the query parameters was relevant anymore

2024-10-17 18:31 UTC, JaredSnider-Bitwarden requested changes
Thank you for your continued improvements! This is looking better and better!
I did see several more changes that we need to make unfortunately with this incomplete pass.

2024-10-17 18:31 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/login/login.component.ts
> +    }
❓ : Can we add a TODO that we will be replacing toast validation with inline validation per our previous discussion? 

In [your comment](https://github.com/bitwarden/clients/pull/10856#issuecomment-2415636834), you called out that this was removed, but I'm ok keeping it until we actually deprecate it in the follow up work.

2024-10-17 18:31 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/login/login-component.service.ts
> +  setPreviousUrl: (route: UrlTree) => void | null;
⚠️ : this method is no longer used with the removal of the `webOnInit` and should be removed.

2024-10-17 18:31 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/login/login.component.ts
> +  protected async evaluatePassword(): Promise<void> {
👍 nice work on this change. I tested it locally as well on all clients, and it works flawlessly!

2024-10-17 20:57 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/icons/vault.icon.ts
> +  <svg width="120" height="100" viewBox="0 0 120 100" fill="none" xmlns="http://www.w3.org/2000/svg">
⚠️ : In order for this to scale appropriately using the viewbox, the width & height must be removed.

2024-10-17 21:03 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/icons/wave.icon.ts
> +  <svg xmlns="http://www.w3.org/2000/svg" width="100" height="98" fill="none">
⚠️ : I believe this icon is missing viewBox="0 0 120 100" to support scaling + the hardcoded width and height need to be removed.

2024-10-17 21:13 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/icons/wave.icon.ts
> +  <svg xmlns="http://www.w3.org/2000/svg" width="100" height="98" fill="none">
Actually, we might need to get it natively re-exported with viewbox. Please coordinate with @danielleflinn to get a new copy.

2024-10-17 21:17 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/icons/wave.icon.ts
> +  <svg xmlns="http://www.w3.org/2000/svg" width="100" height="98" fill="none">
Actually, 
![hand](https://github.com/user-attachments/assets/d1209fb6-e249-47d7-98f9-fd80118b063e)

2024-10-17 21:41 UTC, danielleflinn commented on libs/auth/src/angular/icons/wave.icon.ts
> +  <svg xmlns="http://www.w3.org/2000/svg" width="100" height="98" fill="none">
Here is a new copy 
![hand](https://github.com/user-attachments/assets/f68cc540-949e-4056-ac1e-e2e174a3de43)

2024-10-18 20:00 UTC, alec-livefront commented on libs/auth/src/angular/login/login.component.ts
> +  validatedEmail = false;
> `ExtensionLoginComponentService`

@JaredSnider-Bitwarden I've been tinkering w/ this for a minute and am a little confused with the request (not the purpose, but the implementation). I don't see how I can use `ExtensionLoginComponentService` directly in the login component either since it is in the extension context too?

2024-10-18 20:03 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/login/login.component.ts
> +  validatedEmail = false;
In the `LoginComponent`, you already have the `LoginComponentService` injected to use. When the extension is built, we provide the `ExtensionLoginComponentService` as the implementation for the `LoginComponentService` abstraction. Does that make sense?

2024-10-18 20:03 UTC, alec-livefront commented on libs/auth/src/angular/login/login.component.html
> +          [queryParams]="{ email: formGroup.value.email }"
[79e177a](https://github.com/bitwarden/clients/pull/10856/commits/79e177ac24d0afd39ebf5b5d827c9eae4d9a5dfc)

2024-10-18 20:04 UTC, alec-livefront commented on apps/browser/src/popup/app-routing.module.ts
> +                test: "test",
[b5cdf4d](https://github.com/bitwarden/clients/pull/10856/commits/b5cdf4d6f7638899b5232e2ef21be633852a8c38)

2024-10-18 20:05 UTC, alec-livefront commented on libs/auth/src/angular/login/login.component.ts
> +  }
[a49c445](https://github.com/bitwarden/clients/pull/10856/commits/a49c4458d3588b35308361e3a6744d830a18a5af) & [40dd0dd](https://github.com/bitwarden/clients/pull/10856/commits/40dd0dd1d214db378fa7525c5b615622de0870a6)

2024-10-18 20:05 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/login/login.component.ts
> +  validatedEmail = false;
Oh, my recommendation doesn't appear as clear to me from when I wrote it. 

You have to add a new top level method to the `LoginComponentService` abstraction for showing the back button. Then, make it a no-op in the default implementation.  Then, in the `ExtensionLoginComponentService`, you will be able to inject the `ExtensionAnonLayoutWrapperDataService ` and use it. Does that make sense?

2024-10-21 15:04 UTC, alec-livefront commented on libs/auth/src/angular/login/login.component.ts
> +  validatedEmail = false;
@JaredSnider-Bitwarden I'm still having trouble with this. I've implemented what I think we've talked about here [628acf0](https://github.com/bitwarden/clients/pull/10856/commits/628acf0c16bb4067be637c2bb9df39d14d2d61b0). This doesn't seem to work however, and I can't quite figure out why.

2024-10-21 18:17 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/login/login.component.ts
> +  validatedEmail = false;
Demoed fix + pushed up fix: https://github.com/bitwarden/clients/pull/10856/commits/16b0d338e84c5f93801e79e56dc978481c94e197

2024-10-21 19:25 UTC, alec-livefront commented on libs/auth/src/angular/login/login.component.ts
> +    await this.getLoginWithDevice(this.loggedEmail);
[808d31c](https://github.com/bitwarden/clients/pull/10856/commits/808d31c790ca9dd43476cad1c18e058363a367ba)

2024-10-21 19:26 UTC, alec-livefront commented on libs/auth/src/angular/icons/vault.icon.ts
> +  <svg width="120" height="100" viewBox="0 0 120 100" fill="none" xmlns="http://www.w3.org/2000/svg">
[3af2178](https://github.com/bitwarden/clients/pull/10856/commits/3af2178ad29d8fd9e9b5ade898790d8dc5023e1e)

2024-10-21 19:27 UTC, alec-livefront commented on libs/auth/src/angular/icons/wave.icon.ts
> +  <svg xmlns="http://www.w3.org/2000/svg" width="100" height="98" fill="none">
👍

2024-10-21 21:06 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/login/login-component.service.ts
> +  setPreviousUrl: (route: UrlTree) => void | null;
@alec-livefront , the method was correctly removed from the abstraction but left in the implementations. I cleaned that up here: https://github.com/bitwarden/clients/pull/10856/commits/814f19315224a8a17b4f0dbedbafb1e165823100

2024-10-21 23:31 UTC, JaredSnider-Bitwarden requested changes
Thank you for tackling another round of feedback. We are really close. I've tackled a few smaller items, but I wanted to leave these requests here for now:

2024-10-21 23:31 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/login/default-login-component.service.ts
> +    return false;
⚠️ : we need a `DesktopLoginComponentService` which has `isLoginViaAuthRequestSupported` hardcoded to return true. Per our [docs](https://bitwarden.com/help/log-in-with-device/), we are supposed to support login with device on web, extension, and desktop.

2024-10-21 23:32 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/anon-layout/anon-layout.component.ts
> +      this.icon = VaultIcon;
No work is required to address these comments beyond reading and understanding the changes.

2024-10-21 23:37 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/login/login.component.ts
⚠️ : Can you investigate why the extension loads and immediately shows an input required error? It might be a focus issue. 

https://github.com/user-attachments/assets/c89c416c-0132-4bba-879d-37cbe5a75af6

2024-10-22 16:28 UTC, alec-livefront commented on libs/auth/src/angular/login/login.component.ts
I've removed a call to `validateEmail` that was being called when the client was Browser. [021f9af](https://github.com/bitwarden/clients/pull/10856/commits/021f9afbf6387eedeadcb6ff5ec947fcb555bfe6)

I think this is a hold over from when we were checking the "showPasswordless" flag - which I don't believe we need anymore because we are are validating the email before showing the "Log in with device" button

2024-10-22 16:29 UTC, alec-livefront commented on libs/auth/src/angular/login/default-login-component.service.ts
> +    return false;
[e3ad14a](https://github.com/bitwarden/clients/pull/10856/commits/e3ad14a393709aa505c26a196e3940c57fa891cf)

2024-10-24 00:53 UTC, JaredSnider-Bitwarden requested changes
We are incredibly close on this PR. A question and a single set of tests to enhance:

2024-10-24 00:53 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/register-form/register-form.component.spec.ts
I don't think this test suite should be included in these changes unless I'm missing something.

2024-10-24 00:53 UTC, JaredSnider-Bitwarden commented on libs/angular/src/auth/functions/unauth-ui-refresh-redirect.spec.ts
🏅 : thank you for testing this!

2024-10-24 00:53 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/login/default-login-component.service.spec.ts
> +    it("launches SSO browser window with correct URL", async () => {
❓ : can we improve this `launchSsoBrowserWindow` test suite by 
1. Adding a test for each client supported
2. Dynamically building the URL based on the test data for comparison at the end vs hardcoding.

2024-10-24 14:22 UTC, alec-livefront commented on libs/auth/src/angular/login/default-login-component.service.spec.ts
> +    it("launches SSO browser window with correct URL", async () => {
872fd969f7a3eb439dfab17006379c6d54bd5289

2024-10-24 16:54 UTC, JaredSnider-Bitwarden submitted a review, later dismissed

2024-10-24 17:03 UTC, justindbaur reviewed
Couple minor things.

2024-10-24 17:03 UTC, justindbaur commented on apps/web/src/app/core/core.module.ts
> +      CryptoFunctionServiceAbstraction,
```suggestion
      CryptoFunctionService,
```

2024-10-24 17:29 UTC, alec-livefront commented on apps/browser/src/popup/services/services.module.ts
> +  }),
82175800f7c709952362ee54a3318a7d205164e4

2024-10-24 17:29 UTC, alec-livefront commented on apps/browser/src/popup/services/services.module.ts
> +} from "@bitwarden/common/platform/abstractions/platform-utils.service";
82175800f7c709952362ee54a3318a7d205164e4

2024-10-24 17:29 UTC, alec-livefront commented on apps/browser/src/popup/services/services.module.ts
> +} from "@bitwarden/common/platform/abstractions/crypto-function.service";
82175800f7c709952362ee54a3318a7d205164e4

2024-10-24 17:45 UTC, alec-livefront commented on apps/web/src/app/core/core.module.ts
> +import { CryptoFunctionService as CryptoFunctionServiceAbstraction } from "@bitwarden/common/platform/abstractions/crypto-function.service";
017c57b5ed1770fa54e39825082c350b380be1f6

2024-10-24 17:45 UTC, alec-livefront commented on apps/web/src/app/core/core.module.ts
> +      CryptoFunctionServiceAbstraction,
017c57b5ed1770fa54e39825082c350b380be1f6

2024-10-24 18:21 UTC, JaredSnider-Bitwarden approved these changes

2024-10-24 19:53 UTC, justindbaur approved these changes

2024-10-24 19:53 UTC, merged