[PM-11395] [Defect] View Login - TOTP premium badge does nothing when clicked
bitwarden/clients pull request #10857
Opened 2024-09-02 17:09 UTC by alec-livefront

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-11395?atlOrigin=eyJpIjoiMmE4ZGVhZWVlYzM1NDQ5Zjg2NTk4OTgzY2Q3ZjM4NTAiLCJwIjoiaiJ9

## 📔 Objective

Clicking on the "Premium" badge was not triggering any functionality in web vault. It seems like we needed to inject the `MessagingService` and trigger it like we do in the original Add/Edit component.

## 📸 Screenshots

<img width="1129" alt="Screenshot 2024-09-02 at 12 08 43 PM" src="https://github.com/user-attachments/assets/6c35427c-f787-40bd-b1b3-e27f5054c971">

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-09 14:16 UTC, gbubemismith submitted a review, later dismissed

2024-09-09 18:26 UTC, shane-melton requested changes

2024-09-09 18:26 UTC, shane-melton commented on libs/vault/src/cipher-view/login-credentials/login-credentials-view.component.ts
> +    this.messagingService.send("upgradeOrganization", {
⚠️ This only works for organization ciphers, we need to send the `premiumRequired` message instead when a cipher does not belong to an organization.

2024-09-09 18:26 UTC, shane-melton commented on libs/vault/src/cipher-view/login-credentials/login-credentials-view.component.ts
> +    /**
⚠️ If we're sending a message using the message service for the web client, then we likely don't want to also navigate. We need a means to do different actions depending on the client we're in. We achieve this behavior for other aspects by creating a common service that has unique implementations registered for each client. We can create a `PremiumUpgradeService` interface that can send messages for Web and navigate for Browser.

2024-09-12 14:58 UTC, alec-livefront commented
@shane-melton I took a stab at adding a `PremiumUpgradeService` but am a little confused on how to use this service in the browser extension client. I figured I'd ping you with the latest to make sure I'm on the right path here.

2024-09-12 18:27 UTC, shane-melton requested changes
This is definitely on the right track and what I had in mind! I left a few comments/suggestion on how we might simplify things a bit.

To use in the Browser we'd need to provide the `BrowserPremiumUpgradeService` in the `ViewV2Component` in the Browser project as that is what shows `CipherView` component.

Also, we should probably put these services under Vault's ownership for now, and we can work/discuss with Billing in the future to see if its something they want to take ownership.

2024-09-12 18:27 UTC, shane-melton commented on apps/browser/src/platform/services/browser-premium-upgrade.service.ts
> +    const router = inject(Router);
⚠️ I don't believe we can `inject()` in a method and we'll need to move this to a property on the service class itself. e.g. `private router = inject(Router);`

2024-09-12 18:27 UTC, shane-melton commented on apps/web/src/app/billing/services/web-individual-premium-upgrade.service.ts
> +export class WebIndividualPremiumUpgradeService implements PremiumUpgradeService {
🎨 Instead of having separate services for both Individual and Organizations, we could have a single `Web` service and the `getPremium()` method could accept an optional `organizationId`. Then if the id is present we would send the `upgradeOrganization` message, otherwise use the `premiumRequired` message.

2024-09-12 18:27 UTC, shane-melton commented on apps/web/src/app/billing/services/web-organization-premium-upgrade.service.ts
🎨 See my other comment about merging this with the other `Web` implementation.

2024-09-12 18:27 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/view.component.ts
> +      useFactory: (injector: Injector, component: ViewComponent) => {
🎨 If we combine the `Web` services, we should be able to simplify this.

2024-09-12 18:27 UTC, shane-melton commented on libs/common/src/billing/abstractions/organizations/premium-upgrade.service.abstraction.ts
> +  abstract getPremium(): Promise<void>;
🎨 Since we're creating something new here, I think it would be better to rename this to something like `promptForPremium()` to be more clear that we're not doing any upgrading in the service, but just prompting them to upgrade. 

Similarly, we might want to do something similar with the service name -- perhaps `PremiumUpgradePromptService`?

2024-09-12 18:27 UTC, shane-melton commented on libs/vault/src/cipher-view/login-credentials/login-credentials-view.component.ts
> +    await this.premiumUpgradeService.getPremium();
👍 Perfect!

2024-09-12 20:03 UTC, alec-livefront commented on apps/web/src/app/billing/services/web-individual-premium-upgrade.service.ts
> +export class WebIndividualPremiumUpgradeService implements PremiumUpgradeService {
Oh that will simplify it quite a bit! good idea

2024-09-13 14:56 UTC, alec-livefront commented on libs/common/src/billing/abstractions/organizations/premium-upgrade.service.abstraction.ts
> +  abstract getPremium(): Promise<void>;
Sounds good - I've updated the names 👍

2024-09-13 18:03 UTC, alec-livefront commented
@shane-melton I think I have this working in both web vault and browser. One piece of behavior I haven't been able to figure out how to fix is in the web vault, when you get navigated to the `settings/subscription/premium` page the view dialog remains open. I tried adding a `this.dialogService.closeAll()` to `web vault/src/app/app.component.ts` but that didn't seem to do it. Adding something like that to the service seems to close the view dialog before the navigation.

2024-09-17 19:40 UTC, shane-melton commented
@alec-livefront I think we'll need to re-implement the premium simple dialog in order to get the result back to know if we should close our dialog. Here's an example of the Web service that seems to be working as expected for me. What do you think?
```ts
import { DialogRef } from "@angular/cdk/dialog";
import { Injectable } from "@angular/core";
import { Router } from "@angular/router";

import { OrganizationId } from "@bitwarden/common/types/guid";
import { PremiumUpgradePromptService } from "@bitwarden/common/vault/abstractions/premium-upgrade-prompt.service";
import { DialogService } from "@bitwarden/components";

import {
  ViewCipherDialogCloseResult,
  ViewCipherDialogResult,
} from "../individual-vault/view.component";

/**
 * This service is used to prompt the user to upgrade to premium.
 */
@Injectable()
export class WebVaultPremiumUpgradePromptService implements PremiumUpgradePromptService {
  constructor(
    private dialogService: DialogService,
    private router: Router,
    private dialog: DialogRef<ViewCipherDialogCloseResult>,
  ) {}

  async promptForPremium(organizationId?: OrganizationId) {
    let upgradeConfirmed;
    if (organizationId) {
      upgradeConfirmed = await this.dialogService.openSimpleDialog({
        title: { key: "upgradeOrganization" },
        content: { key: "upgradeOrganizationDesc" },
        acceptButtonText: { key: "upgradeOrganization" },
        type: "info",
      });
      if (upgradeConfirmed) {
        await this.router.navigate(["organizations", organizationId, "billing", "subscription"]);
      }
    } else {
      upgradeConfirmed = await this.dialogService.openSimpleDialog({
        title: { key: "premiumRequired" },
        content: { key: "premiumRequiredDesc" },
        acceptButtonText: { key: "upgrade" },
        type: "success",
      });
      if (upgradeConfirmed) {
        await this.router.navigate(["settings/subscription/premium"]);
      }
    }

    if (upgradeConfirmed) {
      this.dialog.close({ action: ViewCipherDialogResult.premiumUpgrade });
    }
  }
}
```

2024-09-18 19:18 UTC, alec-livefront commented
> @alec-livefront I think we'll need to re-implement the premium simple dialog in order to get the result back to know if we should close our dialog. Here's an example of the Web service that seems to be working as expected for me. What do you think?
> 
> ```ts
> import { DialogRef } from "@angular/cdk/dialog";
> import { Injectable } from "@angular/core";
> import { Router } from "@angular/router";
> 
> import { OrganizationId } from "@bitwarden/common/types/guid";
> import { PremiumUpgradePromptService } from "@bitwarden/common/vault/abstractions/premium-upgrade-prompt.service";
> import { DialogService } from "@bitwarden/components";
> 
> import {
>   ViewCipherDialogCloseResult,
>   ViewCipherDialogResult,
> } from "../individual-vault/view.component";
> 
> /**
>  * This service is used to prompt the user to upgrade to premium.
>  */
> @Injectable()
> export class WebVaultPremiumUpgradePromptService implements PremiumUpgradePromptService {
>   constructor(
>     private dialogService: DialogService,
>     private router: Router,
>     private dialog: DialogRef<ViewCipherDialogCloseResult>,
>   ) {}
> 
>   async promptForPremium(organizationId?: OrganizationId) {
>     let upgradeConfirmed;
>     if (organizationId) {
>       upgradeConfirmed = await this.dialogService.openSimpleDialog({
>         title: { key: "upgradeOrganization" },
>         content: { key: "upgradeOrganizationDesc" },
>         acceptButtonText: { key: "upgradeOrganization" },
>         type: "info",
>       });
>       if (upgradeConfirmed) {
>         await this.router.navigate(["organizations", organizationId, "billing", "subscription"]);
>       }
>     } else {
>       upgradeConfirmed = await this.dialogService.openSimpleDialog({
>         title: { key: "premiumRequired" },
>         content: { key: "premiumRequiredDesc" },
>         acceptButtonText: { key: "upgrade" },
>         type: "success",
>       });
>       if (upgradeConfirmed) {
>         await this.router.navigate(["settings/subscription/premium"]);
>       }
>     }
> 
>     if (upgradeConfirmed) {
>       this.dialog.close({ action: ViewCipherDialogResult.premiumUpgrade });
>     }
>   }
> }
> ```



> @alec-livefront I think we'll need to re-implement the premium simple dialog in order to get the result back to know if we should close our dialog. Here's an example of the Web service that seems to be working as expected for me. What do you think?
> 
> ```ts
> import { DialogRef } from "@angular/cdk/dialog";
> import { Injectable } from "@angular/core";
> import { Router } from "@angular/router";
> 
> import { OrganizationId } from "@bitwarden/common/types/guid";
> import { PremiumUpgradePromptService } from "@bitwarden/common/vault/abstractions/premium-upgrade-prompt.service";
> import { DialogService } from "@bitwarden/components";
> 
> import {
>   ViewCipherDialogCloseResult,
>   ViewCipherDialogResult,
> } from "../individual-vault/view.component";
> 
> /**
>  * This service is used to prompt the user to upgrade to premium.
>  */
> @Injectable()
> export class WebVaultPremiumUpgradePromptService implements PremiumUpgradePromptService {
>   constructor(
>     private dialogService: DialogService,
>     private router: Router,
>     private dialog: DialogRef<ViewCipherDialogCloseResult>,
>   ) {}
> 
>   async promptForPremium(organizationId?: OrganizationId) {
>     let upgradeConfirmed;
>     if (organizationId) {
>       upgradeConfirmed = await this.dialogService.openSimpleDialog({
>         title: { key: "upgradeOrganization" },
>         content: { key: "upgradeOrganizationDesc" },
>         acceptButtonText: { key: "upgradeOrganization" },
>         type: "info",
>       });
>       if (upgradeConfirmed) {
>         await this.router.navigate(["organizations", organizationId, "billing", "subscription"]);
>       }
>     } else {
>       upgradeConfirmed = await this.dialogService.openSimpleDialog({
>         title: { key: "premiumRequired" },
>         content: { key: "premiumRequiredDesc" },
>         acceptButtonText: { key: "upgrade" },
>         type: "success",
>       });
>       if (upgradeConfirmed) {
>         await this.router.navigate(["settings/subscription/premium"]);
>       }
>     }
> 
>     if (upgradeConfirmed) {
>       this.dialog.close({ action: ViewCipherDialogResult.premiumUpgrade });
>     }
>   }
> }
> ```

@shane-melton this worked!

2024-09-18 21:00 UTC, merged