[Pm 9823] Extract biometric messaging service
bitwarden/clients pull request #10862
Opened 2024-09-03 12:57 UTC by quexten

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-23 14:53 UTC, mzieniukbw requested changes

2024-09-23 14:53 UTC, mzieniukbw commented on apps/desktop/src/services/ddg-message-handler.service.ts
> +export class DDGMessageHandlerService {
I hate acronyms, can we change it ?
```suggestion
export class DuckDuckGoMessageHandlerService {
```
and file rename `duck-duck-go-message-handler.service.ts`

2024-09-23 14:55 UTC, quexten commented on apps/desktop/src/services/ddg-message-handler.service.ts
> +export class DDGMessageHandlerService {
Looks good from my side, but this will be owned by @bitwarden/team-autofill-dev , so leaving this comment open for them to chime in.

2024-09-23 16:26 UTC, jprusik commented on apps/desktop/src/services/ddg-message-handler.service.ts
> +export class DDGMessageHandlerService {
I think the presumption around the more generic naming of `NativeMessageHandlerService` was to indicate that it should own any other native integrations that might exist in the future, but I have no issue with using more explicit naming until that case emerges.

> I hate acronyms, can we change it ?

+1  - I also prefer verbosity in naming to concise ambiguity

cc @differsthecat

2024-09-27 07:37 UTC, quexten commented on apps/desktop/src/services/ddg-message-handler.service.ts
> +export class DDGMessageHandlerService {
Noting ddg testing for QA. I hope this change makes it so we don't have to account for it in the future since the services are entirely split and shouldn't affect each other anymore.

2024-09-28 08:55 UTC, mzieniukbw approved these changes

2024-10-02 08:53 UTC, quexten commented
Fixed merge conflicts and updated codeownership.

2024-10-02 09:22 UTC, mzieniukbw commented on apps/desktop/src/services/biometric-native-messaging.service.ts
> +export class BiometricMessageHandlerService {
🤔 Shouldn't the file name follow the same name pattern: include the `handler` ? Especially considering the DuckDuckGo contains the `handler` in file name ?

2024-10-02 10:01 UTC, mzieniukbw commented on apps/desktop/src/services/biometric-native-messaging.service.ts
> +export class BiometricMessageHandlerService {
Just noticed, the file name also includes `native`, where class does not.

2024-10-02 11:22 UTC, quexten commented on apps/desktop/src/services/biometric-native-messaging.service.ts
> +export class BiometricMessageHandlerService {
Fixed, nice catch!

2024-10-02 12:02 UTC, mzieniukbw submitted a review, later dismissed
LGTM from KM perspective.

2024-10-24 16:48 UTC, jprusik approved these changes

2024-11-05 14:14 UTC, jprusik submitted a review, later dismissed

2024-11-07 15:55 UTC, jprusik approved these changes

2024-11-23 01:41 UTC, merged