[PM-8161] Payment optional trial MVP
bitwarden/clients pull request #10872
Opened 2024-09-03 20:19 UTC by cyprain-okeke

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-8163
https://bitwarden.atlassian.net/browse/PM-8164
https://bitwarden.atlassian.net/browse/PM-8165
https://bitwarden.atlassian.net/browse/PM-8445

## 📔 Objective

We will test whether removing the payment requirement from our trial is a net positive for our business. We will do this in a minimum viable way to minimize our engineering investment in an uncertain outcome. 

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-05 15:34 UTC, mzieniukbw requested changes
There is room for improvement from Secrets Manager side of things, which could apply to different areas too (since there is a lot of repeating logic).

Questions:
1. On the last video, which showcases a scenario of when the trial ended and a payment is successfully, subscribing the org to a plan - the icon on the organization suggests the organization is still disabled, while it just got re-enabled. Are we missing some state data refresh on a subscription added / org enabled ?(Observables chained). Or maybe you are supposed to logout and login to see the changes ?
2. Can customer start SM trial during the 7 day PM trial ?
3. Is self-hosted affected ? I.E. Trial ends, no payment made, but customer is already on self-hosted, does the license expire on the same time ?

2024-09-05 15:34 UTC, mzieniukbw commented on bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.html
> +  *ngIf="!loading && !defaultPaymentSource?.paymentSource && isOwner"
Is it possible to have payment source but not have a subscription (payment added, subscription failed) ?
It might be more reliable to just check if the subscription is trialing instead.

2024-09-09 20:52 UTC, gbubemismith commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +  handleClose() {}
❌ This method is empty

2024-09-09 20:52 UTC, gbubemismith commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +    this.refreshing = true;
❌ I think this is redundant as we already handle this in the subscription

2024-09-09 20:52 UTC, gbubemismith commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +  protected defaultPaymentSource: BillingPaymentResponse;
I think we can consolidate `defaultPaymentSource`, `isOwner` and `isTrailing` into a single property `showPaymentIssueBanner` that determines whether to show the banner, and then we don't have to set them individually in the `identifyOrganizationsWithUpcomingPaymentIssues` method

2024-09-09 20:52 UTC, gbubemismith commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +  protected isTrailing: boolean;
:pick: typo `isTrialing`

2024-09-09 20:58 UTC, gbubemismith requested changes
I left some comments and a question

2024-09-17 20:21 UTC, cyprain-okeke commented on bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.html
> +        : ("freeTrialEndPromptForLessThanADayNoOrgName" | i18n)
We are working base on design.

2024-09-18 11:21 UTC, cyprain-okeke commented on apps/web/src/app/auth/trial-initiation/secrets-manager/secrets-manager-trial-free-stepper.component.ts
> +          this.plan = PlanType.EnterpriseAnnually;
I think we want to default to Annual. We have about 2x as many annual plans as monthly. And this is also a decision from the product team

2024-09-18 11:22 UTC, cyprain-okeke commented on apps/web/src/app/vault/individual-vault/vault-filter/components/vault-filter.component.ts
> +      const sub = await this.organizationApiService.getSubscription(orgNode.node.id);
Yes, if the request for payment becomes successful then we enable the organization.

2024-09-19 14:34 UTC, cyprain-okeke commented on apps/web/src/app/vault/individual-vault/vault.component.ts
It is not all business logic that the vaultBanner component can cater to. Besides, the bit-banner is a reusable component that is used in multiple places without it being associated with the VaultBannersComponent.

The payment business logic, which is intended to generate as much bit-banners in this component as is needed, is unique, and is not a reusable function that could be placed in a service for reuse in another component.

2024-09-19 14:35 UTC, cyprain-okeke commented on apps/web/src/app/vault/individual-vault/vault.component.html
> +<ng-container *ngFor="let banner of bannersToDisplay; index as i">
It is not all business logic that the vaultBanner component can cater to. Besides, the bit-banner is a reusable component that is used in multiple places without it being associated with the VaultBannersComponent.

The payment business logic, which is intended to generate as much bit-banners in this component as is needed, is unique, and is not a reusable function that could be placed in a service for reuse in another component.

2024-09-19 16:21 UTC, gbubemismith commented on apps/web/src/app/vault/individual-vault/vault.component.html
> +<ng-container *ngFor="let banner of bannersToDisplay; index as i">
What I mean is this code can be moved to the `VaultBannersComponent`; we have other banners in that component as well, so you can use a similar approach

2024-09-23 13:51 UTC, mzieniukbw requested changes
The SM free trial is still broken and prone to race conditions on org change. Have a look at my suggestions.

2024-09-23 13:51 UTC, mzieniukbw commented on apps/web/src/app/auth/trial-initiation/secrets-manager/secrets-manager-trial-free-stepper.component.ts
> +      .subscribe((v) => (this.isTrialPaymentEnabled = v));
Since I do not see this variable being used anywhere, except for the components's `.html.ts`, we should make it observable instead. See guidance: https://contributing.bitwarden.com/contributing/code-style/angular#avoid-subscriptions

2024-09-23 13:51 UTC, mzieniukbw commented on apps/web/src/app/core/trialFlowService.service.ts
> +  private trialRemainingDays: number = 0;
we don't need this field, you can inline it into the method

2024-09-23 13:51 UTC, mzieniukbw commented on bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.ts
> +            await this.locateOrganizationsWithIncomingPaymentIssues();
This is still a race condition on `this.organizationId`, coming from separate observable and what's worse, every time we subscribe here (org change), we create completely new Observable chain (see content of this method), technically then all of the executes multiple times. Not sure if there is any ordering guarantee, so it's safe to say it's going to be random when you start switching between orgs.
I think we should never create new observables from within the observable pipe or subscription to avoid this problem.

2024-09-23 13:51 UTC, mzieniukbw commented on bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.ts
> +        }),
This should be part of subscribe instead

2024-09-23 13:51 UTC, mzieniukbw commented on bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.ts
>    }
The [computed](https://v16.angular.io/api/core/computed) is in `Developer preview`. It was released in v17+, but why not just use angular natively supported computed getter ?
```suggestion
  get freeTrialMessage() {
      if (this.trialRemainingDays >= 2) {
        return this.i18nService.t("freeTrialEndPrompt", this.trialRemainingDays);
      } else if (this.trialRemainingDays == 1) {
        return this.i18nService.t("freeTrialEndPromptForOneDayNoOrgName");
      } else {
        return this.i18nService.t("freeTrialEndingSoonWithoutOrgName");
      }
  }
```

2024-09-25 10:02 UTC, mzieniukbw reviewed
Looking good for SM changes, i have few cleanup comments though, have a look.

2024-09-26 14:29 UTC, mzieniukbw requested changes
Few changes for SM

2024-09-26 14:29 UTC, mzieniukbw commented on bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.ts
> +          this.locateOrganizationsWithIncomingPaymentIssues(sub, billing);
The `async` in subscribe is not recommended and would normally result in linter issue, but since you use `next` in `subscribe` (a nasty hack), a linter does not detect it.
The way around is is to move out those two promises out of subscription into separate Observable.
You only need `organizationId` for those and technically we should avoid subscribing (recommendation from our contributing docs), so i would move everything that have to do with free trial to an Observable, like so:
1. Separate to `Observable<Organization>`, since we need `isOwner` from organization for trialing:
```
    const org$ = orgId$.pipe(
      switchMap((orgId) => this.organizationService.get(orgId)),
    );

    org$.pipe(takeUntil(this.destroy$)).subscribe((org) => {
      this.organizationId = org.id;
      this.organization = org;
      this.organizationName = org.name;
      this.userIsAdmin = org.isAdmin;
      this.loading = true;
      this.organizationEnabled = org.enabled;
    });
```
2. Create separate freeTrial type and Observable:
```
type FreeTrial = {
  trialing: boolean;
  remainingDays: number;
  message: string;
};

protected freeTrial$: Observable<FreeTrial>;

    this.freeTrial$ = org$.pipe(
      switchMap((org) =>
        combineLatest([
          of(org),
          this.organizationApiService.getSubscription(org.id),
          this.organizationApiService.getBilling(org.id),
        ])
      ),
      map(([org, sub, billing]) => {
        return this.locateOrganizationsWithIncomingPaymentIssues(org, sub, billing);
      }),
      takeUntil(this.destroy$)
    );
```
3. Change the `this.locateOrganizationsWithIncomingPaymentIssues` to add `org: Organization` as argument. Also don't reference any of `this.`, just return the `FreeTrial` type.
Change the `get freeTrialMessage()`, since message is now part of `FreeTrial` type.
4. From `.html`:
```
*ngIf="!loading && freeTrial$ | async as freeTrial"
>
  {{ freeTrial.message }}
```

2024-09-29 02:19 UTC, gbubemismith commented on apps/web/src/app/vault/individual-vault/vault-filter/components/vault-filter.component.ts
> +      if (sub && sub?.subscription?.status === "unpaid") {
No need for sub here

```suggestion
      if (sub?.subscription?.status === "unpaid") {
```

2024-09-29 02:19 UTC, gbubemismith commented on apps/web/src/app/vault/individual-vault/vault-filter/components/vault-filter.component.ts
> +    if (!orgNode?.node?.enabled) {
❓ is there a reason you added the optional chain to node?

2024-09-29 02:19 UTC, gbubemismith commented on apps/web/src/app/vault/individual-vault/vault-filter/components/vault-filter.component.ts
> +    if (orgNode?.node?.id === "AllVaults") {
❓ is there a reason you added the optional chain to node?

2024-09-29 02:19 UTC, gbubemismith commented on apps/web/src/app/vault/individual-vault/vault-filter/components/vault-filter.component.ts
> +    this.vaultFilterService.setOrganizationFilter(orgNode?.node);
❓ is there a reason you added the optional chain to orgNode?

2024-09-29 02:19 UTC, gbubemismith commented on apps/web/src/app/vault/individual-vault/vault-banners/vault-banners.component.html
> +    organization?.trialRemainingDays >= 2
I think [the same](https://github.com/bitwarden/clients/pull/10872/files#r1750805932) can be done here

2024-09-29 02:19 UTC, gbubemismith commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +  orgId: any;
❌ this should be a string

2024-10-01 13:48 UTC, mzieniukbw requested changes
Few more SM related changes.

2024-10-01 13:48 UTC, mzieniukbw commented on bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.ts
> +      remainingDays: this.trialRemainingDays,
Let's remove this side effect, there should be no `this.` reference in this method, since is part of Observable
```suggestion
    const defaultPaymentSource = billing;
    let trialRemainingDays = 0;
    if (trialEndDate) {
      const today = new Date();
      const trialEnd = new Date(trialEndDate);
      const timeDifference = trialEnd.getTime() - today.getTime();
     trialRemainingDays = Math.ceil(timeDifference / (1000 * 60 * 60 * 24));
    }
    return {
      trialing: isTrialing,
      remainingDays: trialRemainingDays,
```

2024-10-01 13:48 UTC, mzieniukbw commented on bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.ts
> +      message: this.freeTrialMessage,
You need to convert the getter `get freeTrialMessage() {` into normal function, since the computation of the message is done here and we should not rely on any of `this.` references, to reduce the amount of side effects.
```suggestion
      message: this.getFreeTrialMessage(trialRemainingDays),
```

and then the `trialRemainingDays` method itself:
```
  getFreeTrialMessage(trialRemainingDays: number) {
    if (trialRemainingDays >= 2) {
    ...
```

2024-10-01 13:48 UTC, mzieniukbw commented on apps/web/src/app/core/trial-flow.service.ts
> +    org: OrganizationSubscriptionResponse,
```suggestion
    orgSubscriptionResponse: OrganizationSubscriptionResponse,
```

2024-10-01 13:48 UTC, mzieniukbw commented on apps/web/src/app/core/trial-flow.service.ts
> +        : Math.ceil(timeDifference / (1000 * 60 * 60 * 24)),
The `timeDifference` is always 0.
```suggestion
    return {
      isOwner,
      isTrialing,
      trialRemainingDays: trialEndDate ? this.calculateTrialRemainingDays(trialEndDate) : 0,
```

2024-10-01 13:48 UTC, mzieniukbw commented on bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.html
> +    {{ freeTrial?.message }}
```suggestion
    {{ freeTrial.message }}
```

2024-10-01 13:48 UTC, mzieniukbw commented on bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.ts
> +  protected isTrialing: boolean;
We don't need those anymore, since it's all part of `freeTrial$` now.

2024-10-01 13:48 UTC, mzieniukbw commented on bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.ts
> +  protected freeTrial$!: Observable<FreeTrial>;
```suggestion
  protected freeTrial$: Observable<FreeTrial>;
```

2024-10-01 13:48 UTC, mzieniukbw commented on bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.ts
> +  private locateOrganizationsWithIncomingPaymentIssues(
🎨  This method is almost identical to the `TrialFlowService`.  Can't we just have one ?

2024-10-01 13:48 UTC, mzieniukbw commented on bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.ts
> +    sub: OrganizationSubscriptionResponse,
How about `organizationSubscriptionResponse` or `subscriptionResponse` or `subscription`
```suggestion
    organizationSubscription: OrganizationSubscriptionResponse,
```

2024-10-01 13:48 UTC, mzieniukbw commented on bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.ts
> +    const isTrialing = sub?.subscription?.status == "trialing";
Can `organization` be undefined/null ?
Same of `OrganizationSubscriptionResponse` and `BillingResponse`

2024-10-01 14:51 UTC, amorask-bitwarden requested changes
Couple questions and some feedback on the billing side.

2024-10-01 14:51 UTC, amorask-bitwarden commented on apps/web/src/app/billing/shared/payment-method.component.ts
> +export class PaymentMethodComponent implements OnInit, OnDestroy {
❌ Any changes made here will have to be made in the [organization-payment-method.component](https://github.com/bitwarden/clients/blob/main/apps/web/src/app/billing/organizations/payment-method/organization-payment-method.component.ts) as well, as that's the one that will be used after the Stripe Sources deprecation.

2024-10-01 14:51 UTC, amorask-bitwarden commented on apps/web/src/app/billing/shared/payment-method.component.ts
> +      const organizationPromise = await this.organizationService.get(this.organizationId);
❌ You don't need to await this if you're passing it to `await Promise.all`.

2024-10-01 14:51 UTC, amorask-bitwarden commented on apps/web/src/app/billing/shared/payment-method.component.ts
> +      this.determineOrgsWithUpcomingPaymentIssues();
❓ This path is the one that gets invoked when we're on the User Payment Method page. Do we need to invoke this org-specific function here?

2024-10-01 14:51 UTC, amorask-bitwarden commented on apps/web/src/app/billing/shared/payment-method.component.ts
> +      window.setTimeout(async () => {
⛏️ Can you leave a comment as to what's going on here? It's a bit difficult to reason through. Particularly just the timeout and the replacement of the state.

2024-10-01 14:51 UTC, amorask-bitwarden commented on apps/web/src/app/billing/shared/payment-method.component.ts
> +  async navigateToPaymentMethod() {
❌  This method is unused.

2024-10-02 09:28 UTC, mzieniukbw requested changes

2024-10-02 09:28 UTC, mzieniukbw commented on apps/web/src/app/core/trial-flow.service.ts
> +import { FreeTrial } from "@bitwarden/common/billing/types/free-trial";
this class is part of core, but we return typo from billing, this is wrong. Let's move the `FreeTrial` to core.

2024-10-02 09:28 UTC, mzieniukbw commented on bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.ts
> +  private freeTrialData: FreeTrial;
We don't need this.

2024-10-02 09:28 UTC, mzieniukbw commented on bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.ts
> +        return this.freeTrialData;
```suggestion
        return this.trialFlowService.checkForOrgsWithUpcomingPaymentIssues(
          org,
          sub,
          billing?.paymentSource,
        );
```

2024-10-02 11:37 UTC, mzieniukbw requested changes

2024-10-02 11:37 UTC, mzieniukbw commented on apps/web/src/app/auth/trial-initiation/secrets-manager/secrets-manager-trial-paid-stepper.component.ts
> +  trialFlowOrgs: string[] = [
Since this is immutable, could be `static` or `const` outside of class

2024-10-02 11:37 UTC, mzieniukbw commented on apps/web/src/app/auth/trial-initiation/secrets-manager/secrets-manager-trial-paid-stepper.component.ts
> +    router: Router,
`protected` or `private` ?

2024-10-02 11:37 UTC, mzieniukbw commented on apps/web/src/app/auth/trial-initiation/secrets-manager/secrets-manager-trial-paid-stepper.component.ts
> +  async ngOnInit(): Promise<void> {
New line
```suggestion
  }

  async ngOnInit(): Promise<void> {
```

2024-10-02 12:57 UTC, mzieniukbw submitted a review, later dismissed
LGTM for SM changes. 
Please make sure to update QA notes for SM and include regression testing during QA.

2024-10-02 15:48 UTC, amorask-bitwarden submitted a review, later dismissed

2024-10-03 13:54 UTC, vleague2 commented on apps/web/src/app/layouts/org-switcher/org-switcher.component.ts
> +    if (sub?.subscription?.status === "unpaid") {
^ I think this got lost in the reviews haha, just this one question from me!

2024-10-03 15:56 UTC, gbubemismith requested changes
These are just some little things I noticed

2024-10-03 17:46 UTC, gbubemismith submitted a review, later dismissed
Vault changes look good

2024-10-04 10:44 UTC, addisonbeck approved these changes

2024-10-04 10:53 UTC, mzieniukbw approved these changes

2024-10-04 13:29 UTC, vleague2 approved these changes

2024-10-04 14:03 UTC, amorask-bitwarden approved these changes

2024-10-04 14:11 UTC, JaredSnider-Bitwarden approved these changes
Auth changes look good! Nice work and thank you for recording the scenarios!

2024-10-17 11:46 UTC, mzieniukbw approved these changes

2024-10-17 18:07 UTC, addisonbeck approved these changes

2024-10-17 18:20 UTC, mzieniukbw submitted a review, later dismissed

2024-10-17 21:06 UTC, JaredSnider-Bitwarden approved these changes

2024-10-22 15:55 UTC, JaredSnider-Bitwarden approved these changes

2024-10-22 17:09 UTC, amorask-bitwarden submitted a review, later dismissed

2024-10-22 20:59 UTC, mzieniukbw submitted a review, later dismissed

2024-10-23 10:09 UTC, addisonbeck submitted a review, later dismissed

2024-10-23 13:30 UTC, vleague2 submitted a review, later dismissed

2024-10-23 19:12 UTC, gbubemismith commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +                if (length == 1) {
We can leave `organizationsPaymentStatus$` as previously and create an observable to handle the dialog. 

example
```
  private readonly unpaidSubscriptionDialog$ = this.organizationService.organizations$.pipe(
    filter((organizations) => organizations.length === 1),
    switchMap(([organization]) =>
      from(this.organizationApiService.getSubscription(organization.id)).pipe(
        switchMap((subscription) =>
          from(this.trialFlowService.handleUnpaidSubscriptionDialog(organization, subscription)),
        ),
      ),
    ),
  );
  
  ngOnInit() {
  this.unpaidSubscriptionDialog$
        .pipe(takeUntil(this.destroy$))
        .subscribe()
  }
```

2024-10-23 19:24 UTC, gbubemismith commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +              .subscribe(),
❌ Same anti-pattern exists here; we should handle the dialog separately

2024-10-23 19:26 UTC, gbubemismith commented on apps/web/src/app/core/trial-flow.service.ts
🤔 Shouldn't this service be in the billing folder?

2024-10-23 19:42 UTC, gbubemismith commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +      takeUntil(this.destroy$),
This can be removed as we subscribe in the template

2024-10-23 20:43 UTC, gbubemismith submitted a review, later dismissed

2024-10-23 20:50 UTC, JaredSnider-Bitwarden submitted a review, later dismissed

2024-10-23 20:56 UTC, addisonbeck approved these changes

2024-10-24 06:34 UTC, mzieniukbw approved these changes

2024-10-24 09:14 UTC, jonashendrickx submitted a review, later dismissed

2024-10-24 13:22 UTC, amorask-bitwarden submitted a review, later dismissed

2024-10-24 13:32 UTC, vleague2 submitted a review, later dismissed

2024-10-29 13:29 UTC, mzieniukbw approved these changes

2024-10-29 13:39 UTC, gbubemismith requested changes

2024-10-29 13:39 UTC, gbubemismith commented on apps/web/src/locales/en/messages.json
> +  "verified-domain-single-org-warning" : {
We use camel case for keys

2024-10-29 13:39 UTC, gbubemismith commented on apps/web/src/locales/en/messages.json
> +  "verified-domain-single-org-warning" : {
```suggestion
  "verifiedDomainSingleOrgWarning" : {
```

2024-10-29 13:39 UTC, gbubemismith commented on apps/web/src/locales/en/messages.json
> +  "single-org-revoked-user-warning": {
Same issue here

2024-10-29 13:55 UTC, gbubemismith approved these changes

2024-10-29 17:33 UTC, gbubemismith approved these changes

2024-10-29 18:04 UTC, vleague2 approved these changes

2024-10-29 19:19 UTC, amorask-bitwarden submitted a review, later dismissed

2024-10-29 19:23 UTC, mzieniukbw submitted a review, later dismissed

2024-10-29 20:10 UTC, addisonbeck approved these changes

2024-10-31 10:00 UTC, jonashendrickx submitted a review, later dismissed

2024-10-31 13:35 UTC, vleague2 commented on apps/web/src/app/layouts/org-switcher/org-switcher.component.ts
> +    private router: Router,
Just noticed we have a couple added arguments here that don't seem to be used, do we still need these now that the logic for handling the subscription is in the trial service?

2024-10-31 14:03 UTC, vleague2 submitted a review, later dismissed

2024-10-31 14:05 UTC, gbubemismith submitted a review, later dismissed

2024-10-31 16:14 UTC, mzieniukbw approved these changes

2024-10-31 19:20 UTC, gbubemismith submitted a review, later dismissed

2024-11-01 08:04 UTC, mzieniukbw reviewed
You have come CI failures due to locale changes.

2024-11-01 08:04 UTC, mzieniukbw commented on apps/web/src/locales/en/messages.json
> +    "message": "add a payment method.",
https://github.com/bitwarden/clients/actions/runs/11619973441/job/32360776968?pr=10872
You should not change locale messages content, once it's merged to main. Mainly because Crowdin, the 3rdparty tool we use for translations, does not detect and re-translate already translated content. Which means for other languages that added dot `.` will never be there.
To fix this, just just add new `addAPaymentMethod2` with the dot and leave the old one as it was.

2024-11-01 17:04 UTC, amorask-bitwarden submitted a review, later dismissed

2024-11-01 17:06 UTC, gbubemismith approved these changes

2024-11-01 19:54 UTC, JaredSnider-Bitwarden submitted a review, later dismissed

2024-11-01 20:27 UTC, addisonbeck submitted a review, later dismissed

2024-11-03 07:46 UTC, mzieniukbw requested changes

2024-11-03 07:46 UTC, mzieniukbw commented on apps/web/src/locales/en/messages.json
> +      "organization": {
This is incorrect format
```suggestion
    "placeholders": {
      "organization": {
```

2024-11-04 10:24 UTC, mzieniukbw requested changes

2024-11-04 10:24 UTC, mzieniukbw commented on apps/web/src/locales/en/messages.json
> +   },
formatting is off

2024-11-04 10:43 UTC, mzieniukbw submitted a review, later dismissed

2024-11-04 14:21 UTC, vleague2 submitted a review, later dismissed

2024-11-04 15:29 UTC, gbubemismith approved these changes

2024-11-04 15:31 UTC, JaredSnider-Bitwarden approved these changes

2024-11-04 16:25 UTC, JaredSnider-Bitwarden approved these changes

2024-11-04 16:35 UTC, mzieniukbw submitted a review, later dismissed

2024-11-04 19:07 UTC, addisonbeck submitted a review, later dismissed

2024-11-04 21:51 UTC, gbubemismith submitted a review, later dismissed

2024-11-05 14:54 UTC, vleague2 submitted a review, later dismissed

2024-11-11 15:30 UTC, JaredSnider-Bitwarden approved these changes

2024-11-11 15:31 UTC, amorask-bitwarden approved these changes

2024-11-11 15:35 UTC, mzieniukbw approved these changes

2024-11-11 15:43 UTC, addisonbeck approved these changes

2024-11-11 15:55 UTC, willmartian approved these changes

2024-11-11 16:04 UTC, shane-melton approved these changes

2024-11-11 16:05 UTC, merged