[PM-11200] Move delete item permission to Can Manage
bitwarden/clients pull request #10890
Opened 2024-09-04 18:57 UTC by gbubemismith

## 🎟️ Tracking
[PM-11200](https://bitwarden.atlassian.net/browse/PM-11200)

## 📔 Objective
Currently, users with Can Edit permissions can delete items within the collection. This should be updated so that only users with the Can Manage permission can delete items within a collection.

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-04 21:05 UTC, shane-melton requested changes
This looks good for the Individual Vault, but I suspect we're going to run into an issue with the AC/org vault that we'll want to address in the share vault items component.

Also, just an fyi, this is likely going to conflict with https://github.com/bitwarden/clients/pull/10784

2024-09-05 18:37 UTC, gbubemismith commented
> This looks good for the Individual Vault, but I suspect we're going to run into an issue with the AC/org vault that we'll want to address in the shared vault items component.
> 
> Also, just an fyi, this is likely going to conflict with #10784

Thanks for pointing this out.I didn't even think of AC

2024-09-09 21:38 UTC, gbubemismith commented on apps/web/src/app/vault/components/vault-items/vault-items.component.ts
> +      if (organization?.allowAdminAccessToAllCollectionItems) {
Thanks that makes sense

2024-09-09 21:52 UTC, shane-melton requested changes

2024-09-09 21:52 UTC, shane-melton commented on apps/web/src/app/vault/components/vault-items/vault-items.component.ts
> +        (organization.isAdmin || organization.permissions.editAnyCollection)
⚠️ `editAnyCollection` is not restricted by `allowAdminAccessToAllCollectionItems`. We should pull that condition to its own `if` statement or separate `||` condition.

2024-09-10 18:15 UTC, merged