[PM-11667] Remove all code related to the outdated custom permissions 'Edit/Delete Assigned Collections'
bitwarden/clients pull request #10904
Opened 2024-09-05 15:10 UTC by r-tome

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-11667

## 📔 Objective

Remove all code related to the outdated custom permissions 'Edit/Delete Assigned Collections'.

[Server PR](https://github.com/bitwarden/server/pull/4736).

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-06 04:33 UTC, eliykat requested changes

2024-09-06 04:33 UTC, eliykat commented on libs/common/src/state-migrations/migrations/40-move-organization-state-to-state-provider.ts
Data models in migrations should not be changed, because they represent the data model at that point in time. That's why we duplicate the definition here, so that the code can change without breaking old migrations.

2024-09-06 14:24 UTC, coroiu commented
Platform is no longer a code owner here, removing :) Enjoy and hope you have a good day, sir!

2024-09-06 17:07 UTC, ike-kottlowski approved these changes
I'll approve, but I think we need to address

2024-09-09 01:28 UTC, eliykat approved these changes

2024-09-17 13:22 UTC, merged