Auth/PM-10684 - Fix CLI asking for MP even if session key provided as command option
bitwarden/clients pull request #10917
Opened 2024-09-05 23:03 UTC by JaredSnider-Bitwarden

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-10684

## 📔 Objective

## 📸 Screenshots

https://github.com/user-attachments/assets/3b0b9742-16ee-49d9-92b1-17dbe5399366

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-05 23:55 UTC, justindbaur requested changes
One tiny style change, other than that looks perfect.

2024-09-05 23:55 UTC, justindbaur commented on apps/cli/src/base-program.ts
> +    hasUserKey =
I think after you refactored this we don't need to actually `let` this anymore.

```suggestion
    // If the process.env does not have a BW_SESSION key, then we will never be able to retrieve
    // the auto user key from secure storage. This is because the auto user key is encrypted with
    // the session key.
    const hasUserKey =
```

2024-09-06 02:29 UTC, JaredSnider-Bitwarden commented on apps/cli/src/base-program.ts
> +    hasUserKey =
Thank you for catching that! It's cleaned up!

2024-09-06 10:08 UTC, justindbaur approved these changes

2024-09-09 14:03 UTC, merged