[PM-11631] - hide free Bitwarden Families button if user is not eligible
bitwarden/clients pull request #10971
Opened 2024-09-10 00:04 UTC by jaasen-livefront

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-11631

## 📔 Objective

This PR hides the "Free Bitwarden Families" button if none of their orgs have family sponsorship available.

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-10 10:01 UTC, djsmith85 requested changes

2024-09-10 10:01 UTC, djsmith85 commented on apps/browser/src/tools/popup/settings/about-page/more-from-bitwarden-page-v2.component.ts
> +    this.organizationService.organizations$
⚠️  I know I pointed you to the code to be potentially used, but looking if we could replace the `BehaviourSubject` with an `Observable` I discovered, that the orgService has `canManageSponsorships$`. This seems to take care of the check for us.

In addition to switching over to `canManageSponsorships$` could you please add documentation to the observable on the orgService abstraction.

2024-09-10 18:40 UTC, djsmith85 submitted a review, later dismissed

2024-09-11 04:00 UTC, eliykat requested changes
1 nit around the jsdoc wording, otherwise lgtm!

2024-09-11 04:00 UTC, eliykat commented on libs/common/src/admin-console/abstractions/organization/organization.service.abstraction.ts
> +   * Determined by the user's organization's ability to manage sponsorships
I suggest the following wording - mostly to clarify that the current user is issuing/managing the sponsorship, not receiving it. The second line is unnecessary.

> Emits `true` if the user can create or manage a Free Bitwarden Families sponsorship.

2024-09-12 16:34 UTC, djsmith85 approved these changes

2024-09-13 01:58 UTC, eliykat approved these changes

2024-09-13 01:58 UTC, merged