Pm 11438
bitwarden/clients pull request #10982
Opened 2024-09-10 22:48 UTC by jaasen-livefront

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-11438

## 📔 Objective

This PR fixes the padding on the input button for the new organization license field.

## 📸 Screenshots

|Before|After|
---|---
|
![Screenshot 2024-09-10 at 3 44 34 PM](https://github.com/user-attachments/assets/5db8beff-1101-49aa-be0c-937fc3d919ec)|![Screenshot 2024-09-10 at 3 44 04 PM](https://github.com/user-attachments/assets/0d808606-dfd4-4ca0-8667-412b49d8360f)|

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-11 13:01 UTC, amorask-bitwarden requested changes
Can you also make this change on the [premium-v2.component](https://github.com/bitwarden/clients/blob/main/apps/browser/src/billing/popup/settings/premium-v2.component.html)?

2024-09-12 16:49 UTC, jaasen-livefront commented
> Can you also make this change on the [premium-v2.component](https://github.com/bitwarden/clients/blob/main/apps/browser/src/billing/popup/settings/premium-v2.component.html)?

@amorask-bitwarden Are you able to point out exactly where the extra padding should go. This is the page this component renders:

![Screenshot 2024-09-12 at 9 48 19 AM](https://github.com/user-attachments/assets/e1ebd41d-fbd4-4227-a57a-315bbee774f9)

2024-09-12 16:51 UTC, amorask-bitwarden commented
> > Can you also make this change on the [premium-v2.component](https://github.com/bitwarden/clients/blob/main/apps/browser/src/billing/popup/settings/premium-v2.component.html)?
> 
> @amorask-bitwarden Are you able to point out exactly where the extra padding should go. This is the page the [premium-v2.component.html](https://github.com/bitwarden/clients/blob/main/apps/browser/src/billing/popup/settings/premium-v2.component.html) component renders:
> 
> ![Screenshot 2024-09-12 at 9 48 19 AM](https://private-user-images.githubusercontent.com/166539328/366981806-e1ebd41d-fbd4-4227-a57a-315bbee774f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNjAxMDUsIm5iZiI6MTcyNjE1OTgwNSwicGF0aCI6Ii8xNjY1MzkzMjgvMzY2OTgxODA2LWUxZWJkNDFkLWZiZDQtNDIyNy1hNTdhLTMxNWJiZWU3NzRmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQxNjUwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZGM1YTljMjhjMzlmZjkxZTcwZGRiYTM1ZmJjOWRiYmQxMjM0MjZhMzk3MWE2NTQ4M2Y2YWIyZmRmODI4YmE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U1m1nG6E5zrZ6ohQbUqylrly4k1OHcWvdbxC07a06_4)

@jaasen-livefront Weird, looks fine there. Just figured it would have the same issue cuz they have almost identical HTML templates. Apologies and thanks for checking!

2024-09-12 16:51 UTC, amorask-bitwarden approved these changes

2024-09-12 16:52 UTC, merged