[PM-10914] add option to delete all folders if migration fails
bitwarden/clients pull request #10983
Opened 2024-09-11 01:33 UTC by jlf0dev

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-10914
## 📔 Objective

Many legacy migrations have failed due to un-decryptable folders. This allows the user the option to delete all their folders and attempt the migration again.
## 📸 Screenshots

https://github.com/user-attachments/assets/7aef1474-cc4b-4d3e-a01e-84d7915e873d

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-11 20:12 UTC, ike-kottlowski submitted a review, later dismissed

2024-09-11 20:15 UTC, shane-melton requested changes

2024-09-11 20:15 UTC, shane-melton commented on libs/common/src/vault/services/folder/folder-api.service.ts
> +    await this.folderService.clearCache();
⚠️ We'll want to use `folderService.clear()` to ensure we also clear the `encryptedFoldersState`

2024-09-11 20:27 UTC, shane-melton approved these changes
Folder service changes look good to go!

2024-09-11 21:15 UTC, quexten reviewed
LGTM But I would suggest updating the messaging since we are deleting all folders.

2024-09-11 21:15 UTC, quexten commented on apps/web/src/locales/en/messages.json
> +    "message": "When updating your encryption key, some folders could not be decrypted. To continue with the update, these folders must be deleted. No vault items will be deleted if you proceed."
:art: This messaging suggests only some folders will be deleted. However we delete all folders. I believe that we need to update this messaging to reflect that?
```suggestion
    "message": "When updating your encryption key, your folders could not be decrypted. To continue with the update, all folders must be deleted. No vault items will be deleted if you proceed."
```

2024-09-12 10:20 UTC, mzieniukbw requested changes
We have all of the information on the items that we are unable to decrypt in client. There is no need to go to server and guesstimate what went wrong.

2024-09-12 10:20 UTC, mzieniukbw commented on apps/web/src/app/auth/migrate-encryption/migrate-legacy-encryption.component.ts
> +          await this.submit();
what if we attempted to delete the folders, we failed, we loop on `submit` and it fails again. Maybe then throw some user friendly error ?
Also technically it could be a problem of any other thing like `Sends`, `EmergencyAccesses`, `ResetPasswordKeys` or `WebauthnKeys` not rotating, what then ?

2024-09-12 10:20 UTC, mzieniukbw commented on apps/web/src/app/auth/migrate-encryption/migrate-legacy-encryption.component.ts
> +      if (e.message === "All existing folders must be included in the rotation.") {
⚠️ This is wrong place to do this logic. This error occurs on server when the expected number of existing items (before rotation) does not match the items after rotation (part of the request to rotate).
Which clearly comes from THIS code.

Why don't we do this on the client ?
These are situations where the might be an error thrown or number of items might be wrong on client side that comes to my mind:
1. Sync error. We could easily do this by separating `await this.syncService.fullSync(false, true);` in try - catch. We could show to the user that there have been some issue with sync and whether he/she want to try again.
2. We have the items from the server api, but we are unable to decrypt the items with existing key - since we hold the decryption keys, we can easily check in `await this.keyRotationService.rotateUserKeyAndEncryptedData(masterPassword, activeUser);` what fails, throw appropriate error, catch it and then action on it from that. Or better, split the `rotateUserKeyAndEncryptedData` into one that returns an error as part of return with the items and type that it failed to decrypt.

2024-09-12 12:52 UTC, jlf0dev commented on apps/web/src/app/auth/migrate-encryption/migrate-legacy-encryption.component.ts
> +          await this.submit();
We're only going to focus on folders for now since its consistently been the only error stopping migration. We also have evidence of somewhere around 10 users that deleting the folders fixes the migration.

I'm curious what you mean about it failing again, do you mean if it throws the same folder error? or a different error? If it throws a different error we'll display that just like did with folders. Its useful to have these error show up show so CS can easily identify these cases.

2024-09-12 13:42 UTC, mzieniukbw commented on apps/web/src/app/auth/migrate-encryption/migrate-legacy-encryption.component.ts
> +      if (e.message === "All existing folders must be included in the rotation.") {
@jlf0dev I am ok with this being a separate improvements done later in time too, since this might be large piece of work.

2024-09-12 13:54 UTC, mzieniukbw commented on apps/web/src/app/auth/migrate-encryption/migrate-legacy-encryption.component.ts
> +          await this.submit();
I meant different error, since it is not 100% confirmed the problem is only with folders. I am worrying that deleting folders will not fix this issue and users would have to raise CS anyway.

2024-09-12 13:56 UTC, mzieniukbw approved these changes

2024-09-12 14:45 UTC, jlf0dev commented on apps/web/src/app/auth/migrate-encryption/migrate-legacy-encryption.component.ts
> +          await this.submit();
We've been able to confirm for 5 users so far that the problem is only with folders. I can see your point though and as we discussed hopefully we can add more error handling in the future!

2024-09-12 16:07 UTC, shane-melton approved these changes

2024-09-12 17:41 UTC, ike-kottlowski approved these changes

2024-09-12 17:47 UTC, merged