[PM-12004] Fix ~60 compile warnings in webpack for web
bitwarden/clients pull request #11004
Opened 2024-09-12 09:54 UTC by Hinton

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-12004

## 📔 Objective

Decrease webpack warnings when building web. This adjust our `tsconfig` files to remove many unused files and only include the necessary.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-12 18:07 UTC, MGibson1 requested changes
These includes exist because they prevent import and matcher failures. I think we can specify a separate `tsconfig.spec.json` to use with jest, but simply removing causes error in spec files.

Take a look at [trial-initiation.component.spec.ts](https://github.com/bitwarden/clients/blob/e29025df28767dd420033b0c994613fb35b55529/apps/web/src/app/auth/trial-initiation/trial-initiation.component.spec.ts) in your branch, for example.

2024-09-13 09:53 UTC, Hinton commented
@MGibson1 That's annoying. Seems the only approach is to define a specific tsconfig for building ...

2024-09-16 14:55 UTC, MGibson1 commented
yep, seems to be the only way

2024-09-16 16:11 UTC, MGibson1 approved these changes

2024-09-19 13:00 UTC, merged