[PM-11899] - send text details component
bitwarden/clients pull request #11002
Opened 2024-09-11 22:16 UTC by jaasen-livefront

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-11899

## 📔 Objective

This PR adds the send text details component. This is one of three PRs for the new create send UI as part of the extension refresh.

## 📸 Screenshots

|New|Edit|
---|---
|![Screenshot 2024-09-11 at 3 04 35 PM](https://github.com/user-attachments/assets/27ab9c83-9172-47cd-83dd-1b77bea86f58)|![Screenshot 2024-09-11 at 3 04 07 PM](https://github.com/user-attachments/assets/637e5cd6-daef-4de8-927f-7ac8f30b0bea)|

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-17 18:58 UTC, djsmith85 requested changes
Only a partial review

As discussed I'm uncertain about the changes to the send and sendApi services, which we should likely revert and focus this PR on the UI changes. If it breaks saving Sends on the feature-flagged part, we should fix it in a separate PR.

2024-09-17 20:48 UTC, jaasen-livefront commented
> Only a partial review
> 
> As discussed I'm uncertain about the changes to the send and sendApi services, which we should likely revert and focus this PR on the UI changes. If it breaks saving Sends on the feature-flagged part, we should fix it in a separate PR.

Sounds good. The type changes were only a narrowing of types so reverting back to `any` won't cause any type issues.

2024-09-18 11:50 UTC, djsmith85 requested changes

2024-09-18 11:50 UTC, djsmith85 commented on apps/browser/src/_locales/en/messages.json
> +  },
⚠️ Message key is not used anywhere and is duplicated by `hideTextByDefault` which is used.

2024-09-18 11:50 UTC, djsmith85 commented on apps/browser/src/_locales/en/messages.json
> +  },
⚠️ These message keys are not used anywhere. Need to be removed. Likely will be introduced with the send-options component

2024-09-18 11:50 UTC, djsmith85 commented on libs/tools/send/send-ui/src/send-form/components/send-details/send-text-details.component.html
> +    <bit-hint>{{ "sendTextDesc" | i18n }}</bit-hint>
⚠️ The hint is not included within the latest design.

2024-09-18 11:58 UTC, djsmith85 commented on libs/tools/send/send-ui/src/send-form/components/send-details/send-text-details.component.html
> +    <bit-hint>{{ "sendTextDesc" | i18n }}</bit-hint>
Addressed with 6c7ad7ccdc0de93910bec288ad3b977da00bc000

2024-09-18 11:58 UTC, djsmith85 commented on apps/browser/src/_locales/en/messages.json
> +  },
Addressed with efffcc6cfb41b7cce7f5a59c12d6137cd465318a

2024-09-18 12:04 UTC, djsmith85 approved these changes
@jaasen-livefront  Addressed some minor issues myself and this is now ready to merge.

2024-09-18 12:04 UTC, merged