[Sm-10995] feature flag removal
bitwarden/clients pull request #11000
Opened 2024-09-11 21:35 UTC by cd-bitwarden

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-12 00:11 UTC, gbubemismith requested changes
I left some tiny nits; other than that, this looks good

2024-09-12 00:11 UTC, gbubemismith commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> -          await this.editCipherCollections(event.item);
⛏️ I think we can remove the `editCipherCollections` function

2024-09-12 00:37 UTC, cd-bitwarden commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> -          await this.editCipherCollections(event.item);
You're right 👍

2024-09-12 19:23 UTC, gbubemismith approved these changes

2024-09-17 15:31 UTC, shane-melton submitted a review, later dismissed

2024-09-19 14:11 UTC, gbubemismith requested changes
I noticed this while trying to align my PR with yours

2024-09-19 14:11 UTC, gbubemismith commented on apps/web/src/app/vault/components/vault-items/vault-items.component.html
> +              *ngIf="showDelete || showBulkTrashOptions"
:warning: I missed this. `showDelete` won't execute as it's not a getter

2024-09-25 15:51 UTC, shane-melton requested changes

2024-09-25 15:51 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> -    private configService: ConfigService,
⚠️ The `configService` can no longer be removed as its being used to get the `extension-refresh` flag below.

2024-09-25 15:52 UTC, cd-bitwarden commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> -    private configService: ConfigService,
Thank you for noticing this Shane!

2024-09-25 16:14 UTC, gbubemismith commented on apps/web/src/app/vault/org-vault/vault.component.ts
> -          await this.editCipherCollections(event.item);
🤔 I think we should leave `viewCipherCollections` for now, as AC doesn't use `assign to collections` yet

2024-10-02 16:50 UTC, shane-melton approved these changes

2024-10-02 16:55 UTC, gbubemismith approved these changes

2024-10-02 16:55 UTC, merged