[PM-11418] generator policy constraints
bitwarden/clients pull request #11014
Opened 2024-09-12 19:54 UTC by audreyality

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-11418

## 📔 Objective

Use constraints to enforce policy for the password generator.

Constraints were introduced to communicate model validation and spinner configuration to the user interface. This PR uses the same constraints to enforce model invariants by injecting them into the `UserStateSubject`. 

# 🦕 Evolution

The evaluator system remains for compatibility purposes, and may be moved to `@bitwarden/generator-legacy` module (or eliminated entirely) in a future PR.

## 📸 Screenshots

TBD

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-12 19:59 UTC, audreyality commented on libs/common/src/tools/types.ts
📝 The core types needed to understand the data flow are in this file.

2024-09-12 20:03 UTC, audreyality commented on libs/tools/generator/core/src/policies/password-generator-options-evaluator.spec.ts
📝 The code introduces a new requirement for the legacy code: it no longer supports partial values. In practice, this shouldn't be an issue as both the legacy and new services fill in missing members.

That said, because this does affect existing code, it will require a regression test on the password and passphrase generators.

2024-09-12 20:11 UTC, audreyality commented on libs/tools/generator/core/src/types/password-generation-options.ts
📝 `PasswordGenerationOptions` was an incredibly flexible type which introduced a lot of boilerplate to constraint processing. Making its properties required reduced the boilerplate significantly, and opened an opportunity to cut out `minLength`, which the new system models as a constraint.

2024-09-16 16:03 UTC, audreyality commented on apps/web/src/locales/en/messages.json
> +    "description": "Help text displayed when a policy limits the password generator's options."
Perhaps "Guidance" is a better word? It's a message displayed to let the user know that their inputs are limited because someone in their org said so.

2024-09-20 12:17 UTC, djsmith85 requested changes
Awesome work on this 🚀 

We can continue discussions offline regarding naming options vs settings and some other details, but for the sake of moving this along and unblocking the UI refresh work this is looking great.

Just some nits and then this is good to go.

2024-09-20 19:03 UTC, audreyality commented on libs/tools/generator/core/src/rx.ts
>   */
Addressed by c287e1775d

2024-09-23 09:07 UTC, djsmith85 approved these changes

2024-09-23 09:07 UTC, merged