[PM-12066] Add sorting to weak password report
bitwarden/clients pull request #11027
Opened 2024-09-13 12:09 UTC by djsmith85

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-12066

## 📔 Objective

### Code changes
- **Simplify the filter(toggle group) to filter by organizationId instead of a orgFilterStatus property which is not present on the CipherView** - https://github.com/bitwarden/clients/commit/14664ce88b38b8e3bffea2394bdd23374d117ef3
- **Add sorting to weak password report table** - https://github.com/bitwarden/clients/commit/0ce397034bf4302d52354dabe39f679a68c13f26
  - Create new type to represent a row within the report
  - Add types and remove usage of any
  - Include the score/badge within the data passed to the datasource/table instead of looking it up via the `passwordStrengthMap`
  - Remove unneeded passwordStrengthCache
  -  Enable sorting via bitSortable
  - Set default sort to order by weakness
- **Show headers and sort also within AC version of weak-password report but hide the Owner column-** https://github.com/bitwarden/clients/commit/7e0ae8be55eb96441bc41530ee50bee265d8e0b1

## 📸 Screenshots

### Password Manager
#### Before
![image](https://github.com/user-attachments/assets/425395bd-8522-46b2-a51f-e44c901dd157)

#### After
![image](https://github.com/user-attachments/assets/882bc4de-fc23-4c17-9d7c-2ebffc6620e5)
![image](https://github.com/user-attachments/assets/2f27690c-1a8f-424e-adcd-a391b25fadcb)

### Admin Console
#### Before
![image](https://github.com/user-attachments/assets/bd75b71c-eca9-45f0-b72c-e3d84d0d1547)

#### After
![image](https://github.com/user-attachments/assets/ff302747-ef3f-4224-8b57-eea6bf566d15)

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-16 12:54 UTC, audreyality requested changes
Overall these changes look good.

👍🏻 Introducing types makes the code easier to follow.
⛏️ There's a lot of magic numbers in the code. It'd be nice to see those pulled out into constants.
🌱 The reports seem to have a lot of business logic embedded in the components. Consider whether this logic should be extracted into a service. If any should, write a ticket proposing an API for the service.

2024-09-16 12:54 UTC, audreyality commented on apps/web/src/app/tools/reports/pages/weak-passwords-report.component.ts
> +type ReportScore = [string, BadgeVariant];
⚠️ This type is exposed to the view, which makes the badge bindings harder to understand. It should be an object, not an array.

2024-09-16 12:54 UTC, audreyality commented on apps/web/src/app/tools/reports/pages/cipher-report.component.ts
> +      this.dataSource.filter = (c: CipherView) => c.organizationId === status;
⚠️ This seems wrong, because the organization is not a status. I assume that `status` can contain an organizationId? If so, consider structuring the logic to make that more clear.

Example:
```
let filter = null;
if(typeof status === 'number' && status === 1) {
   filter = (c:CipherView) => c.organizationId == null;
} else if(typeof status === 'string') {
   const orgId = status as OrganizationId;
   filter = (c: CipherView) => c.organizationId === orgId;
}
this.dataSource.filter = filter;
```

2024-09-25 10:42 UTC, djsmith85 commented on apps/web/src/app/tools/reports/pages/cipher-report.component.ts
> +      this.dataSource.filter = (c: CipherView) => c.organizationId === status;
Addressed with 002b95ae252f931cb6eb54a081c830d0c4c7cb1a

2024-09-25 10:43 UTC, djsmith85 commented on apps/web/src/app/tools/reports/pages/weak-passwords-report.component.ts
> +type ReportScore = [string, BadgeVariant];
Addressed with a440e60e4b7bb0e8a248c5b0954701f7b4fa79db

2024-09-26 23:38 UTC, merged