initial commit for individual plans
bitwarden/clients pull request #11083
Opened 2024-09-16 15:31 UTC by jonashendrickx

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-11901

## 📔 Objective

Deduplicate the code where self-hosting licenses are being uploaded for organizations. Some additional work was done for individual licenses.

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-17 13:15 UTC, amorask-bitwarden requested changes
Great first pass! Please fix up the comments marked with ❌ and let me know what you think about the ⛏️ s.

2024-09-17 13:15 UTC, amorask-bitwarden commented on apps/web/src/app/billing/shared/self-hosting-license-uploader/abstract-self-hosting-license-uploader.component.ts
> +export abstract class AbstractSelfHostingLicenseUploaderComponent {
⛏️ I'll let you ultimately decide this because it's only a matter of style, but a more functional approach would be to combine all 3 of the license uploading components and then pass in what you need as inputs. 

For example:
```typescript
export class SelfHostLicenseUploaderComponent {
    @Input({ required: true }) private description: string;
    @Input({ required: true }) private hintFileName: string;
    @Input({ required: true }) private onSubmit: File => Promise<void>;
}
```
The `onSubmit` input can be passed in from the parent to tell the license uploader what specifically we want to do with the `File` if the existing validation passes. 

```typescript
submit = async () => {
  this.form.markAllAsTouched();

  if (this.form.invalid) {
    return this.toastService.showToast({
      variant: "error",
      title: this.i18nService.t("errorOccurred"),
      message: this.i18nService.t("selectFile"),
    });
  }

  const emailVerified = await this.tokenService.getEmailVerified();
  if (!emailVerified) {
    return this.toastService.showToast({
      variant: "error",
      title: this.i18nService.t("errorOccurred"),
      message: this.i18nService.t("verifyEmailFirst"),
    });
  }

  await this.onSubmit(this.form.value.file);

  // You can either include the necessary post-processing in the `onSubmit` or emit an event to handle it in the parent.
}
```
Example of this approach in the [manage-tax-information.component](https://github.com/bitwarden/clients/blob/f6702cd2d74c32dda2d60bc6df0e46b563978867/libs/angular/src/billing/components/manage-tax-information/manage-tax-information.component.ts).

2024-09-17 13:15 UTC, amorask-bitwarden commented on libs/common/src/enums/feature-flag.enum.ts
> +  [FeatureFlag.PM11901_RefactorSelfHostingLicenseUploader]: TRUE,
❌ We always want these set to `FALSE` by default.

2024-09-17 13:15 UTC, amorask-bitwarden commented on apps/web/src/app/billing/organizations/organization-plans.component.ts
> +      this.useSelfHostingLicenseUploaderFeature = await this.configService.getFeatureFlag(
✅ Good call to only grab the flag if we're on a self-hosted instance.

2024-09-17 13:15 UTC, amorask-bitwarden commented on apps/web/src/app/billing/individual/premium/premium-v2.component.ts
> +  postFinalizeUpgrade = async () => {
❓ What was the purpose of splitting `finalizeUpgrade` into two methods?

2024-09-17 13:15 UTC, amorask-bitwarden commented on apps/web/src/app/billing/individual/premium/premium-v2.component.ts
> +  async ngOnInit(): Promise<void> {
❌ `ngOnInit` is not necessary here. You can grab an Observable of the feature flag using:
```typescript
// Properties
protected useLicenseUploaderComponent$: Observable<boolean>;

// Constructor
this.useLicenseUploaderComponent$ = this.configService.getFeatureFlag$(FeatureFlag.PM11901_RefactorSelfHostingLicenseUploader);
```
Once you have an observable, in your HTML you can subscribe to it using then `async` pipe:
```html
<individual-self-hosting-license-uploader
    *ngIf="useLicenseUploaderComponent | async"
    (onLicenseFileUploaded)="(onLicenseFileSelectedChanged)"
  />
```

2024-09-17 22:38 UTC, jonashendrickx commented on apps/web/src/app/billing/individual/premium/premium-v2.component.ts
> +  postFinalizeUpgrade = async () => {
The bit that remains in the finalizeUpgrade was already executed by the license uploader component. Because I figured it might always be required to run. And then it executes the remainder here in the `postFinalization` method.

2024-09-19 12:38 UTC, jonashendrickx commented on apps/web/src/app/billing/shared/self-hosting-license-uploader/abstract-self-hosting-license-uploader.component.ts
> +    this.submit = this.submit.bind(this);
I couldn't get it to work without it.

2024-09-19 12:41 UTC, jonashendrickx commented on apps/web/src/app/billing/shared/self-hosting-license-uploader/license-uploaded-event.ts
> +export class LicenseUploadedEvent {
I personally like the verbosity, so if the code needs to be extended it would be easier, but I will remove it.

2024-09-19 12:43 UTC, jonashendrickx commented on apps/web/src/app/billing/shared/self-hosting-license-uploader/license-uploader-form-model.ts
> +export interface LicenseUploaderFormModel {
@amorask-bitwarden Don't we want type safety for certain things?

2024-09-20 19:10 UTC, cturnbull-bitwarden reviewed
Overall looks good. Up to you on the remaining nitpicks, though it does look like you have a conflict at `apps\web\src\app\billing\organizations\organization-plans.component.html`

2024-09-24 14:41 UTC, amorask-bitwarden requested changes
Just one change on the premium component template, otherwise looks good.

2024-09-24 14:41 UTC, amorask-bitwarden commented on apps/web/src/app/billing/individual/premium/premium-v2.component.html
> +    (onLicenseFileUploaded)="(onLicenseFileSelectedChanged)"
❌  I think this is supposed to be:
`(onLicenseFileUploaded)="onLicenseFileSelectedChange()"`

![image](https://github.com/user-attachments/assets/7eb785a7-e6d4-499c-b5c9-37286c5c78b1)

2024-09-24 14:41 UTC, amorask-bitwarden commented on apps/web/src/app/billing/organizations/organization-plans.component.ts
> +  protected useLicenseUploaderComponent$: Observable<boolean>;
💡 Not necessary to change, but if you want to in the future, you can initiate this from the declaration:
```typescript
protected useLicenseUploaderComponent$ = this.configService.getFeatureFlag$(
  FeatureFlag.PM11901_RefactorSelfHostingLicenseUploader,
);
```

2024-09-24 14:41 UTC, amorask-bitwarden commented on apps/web/src/app/billing/shared/self-hosting-license-uploader/license-uploader-form-model.ts
> +export interface LicenseUploaderFormModel {
@jonashendrickx It will be typed by the `formGroup`, but not necessary to change.

2024-09-25 08:12 UTC, jonashendrickx commented on apps/web/src/app/billing/individual/premium/premium-v2.component.html
> +    (onLicenseFileUploaded)="(onLicenseFileSelectedChanged)"
@amorask-bitwarden The warning is gone once I added the brackets.

2024-09-25 12:56 UTC, amorask-bitwarden approved these changes

2024-09-26 09:23 UTC, merged