[AC-2627] Empty Collection New Item Btn Permissions
bitwarden/clients pull request #11089
Opened 2024-09-16 20:27 UTC by Jingo88

## 🎟️ Tracking

[AC-2627](https://bitwarden.atlassian.net/browse/AC-2627)

## 📔 Objective

Only show new item btn in empty collection for can edit perm

## 📸 Screen Recording

https://github.com/user-attachments/assets/3c316e2b-0419-447a-9684-4cf8419d386b

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

[AC-2627]: https://bitwarden.atlassian.net/browse/AC-2627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-09-16 21:29 UTC, shane-melton requested changes

2024-09-16 21:29 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/vault.component.html
> +            selectedCollection?.node?.canEdit(organization)
⚠️  I believe we want `canEditItems()` instead of `canEdit()`. `canEdit()` is more restrictive in that it requires the user to have `manage` permissions, but we want to check if they have `!readonly`.

2024-09-17 16:31 UTC, Jingo88 commented on apps/web/src/app/vault/org-vault/vault.component.html
> +            selectedCollection?.node?.canEdit(organization)
ah nice. thanks!

2024-09-17 16:40 UTC, shane-melton approved these changes
Looks good!

2024-09-17 18:28 UTC, merged