[PM-11927] - File Send popout dialog
bitwarden/clients pull request #11138
Opened 2024-09-18 21:56 UTC by jaasen-livefront

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-11927

## 📔 Objective

This PR adds a dialog which appears when the user attempts to create a file send while in a context that requires a popout window.

## 📸 Screenshots

![Screenshot 2024-09-18 at 2 53 36 PM](https://github.com/user-attachments/assets/bfab4078-651c-4052-ac10-c6fdebe28334)

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-19 09:00 UTC, djsmith85 reviewed
@jaasen-livefront I know the design mentions showing this popup after selecting file on the new button on browsers that don't support this. I think we should still navigate to the edit page and show the popup then. 

I think this should be an (optional) part of the SendFileDetailsComponent as the pop-out logic is only needed within that context and if we create another way to create a Send we'd need to re-implement it. I mention optional as we are planning to re-use the add/edit pages on the clients, but the FilePopoutDialog is only needed within the browser extension. If making it optional/injectable is more work, then just moving it to the SendFileDetailsComponent is fine with me.

2024-09-19 19:14 UTC, djsmith85 requested changes
As discussed offline: The `filePopoutUtilsService` should only be responsible to tell you that a message will need to be shown, but it should not be responsible for showing it.

2024-09-19 19:14 UTC, djsmith85 commented on libs/tools/send/send-ui/src/new-send-dropdown/new-send-dropdown.component.html
> +  <a type="button" bitMenuItem (click)="handleNewFileClick()">
⚠️ This can be reverted as it's doing the same thing as introduced within the new method.

2024-09-24 08:40 UTC, djsmith85 requested changes
@jaasen-livefront  No changes since my last review

2024-09-24 20:50 UTC, jaasen-livefront commented
@djsmith85 Whoops! Forgot to push my commit. 🤦 Should be gtg now.

2024-09-25 12:00 UTC, djsmith85 requested changes
@jaasen-livefront Just some minor clean-ups from the refactor.

Could you please test this within Firefox or another browser where this popup would be shown. I've had some weird issues. Browser slowing down, not navigating to the add-edit and then showing the popup multiple times 🤷

2024-09-25 12:00 UTC, djsmith85 commented on apps/browser/src/tools/popup/send-v2/send-v2.component.ts
> +  shouldShowFilePopoutMessage = false;
⚠️ All changes can be reverted as no longer neeed

2024-09-25 12:00 UTC, djsmith85 commented on libs/tools/send/send-ui/src/send-form/components/send-form.component.ts
> +
⚠️ Can be removed as it isn't used anywhere

2024-09-25 12:00 UTC, djsmith85 commented on apps/browser/src/tools/popup/send-v2/send-v2.component.spec.ts
> +import { FilePopoutUtilsService } from "../services/file-popout-utils.service";
⚠️ No longer part of the SendV2Component ctor. Please remove

2024-09-25 19:16 UTC, jaasen-livefront commented
@djsmith85 Fixed the issue you mentioned. The component was calling itself in the dialog which caused an infinite loop. 🤦 . I added a container component which handles this as well as added the config to check if the mode isn't "add" to prevent the dialog from coming up in an edit context.

2024-09-25 19:29 UTC, djsmith85 requested changes

2024-09-25 19:29 UTC, djsmith85 commented on apps/browser/src/tools/popup/send-v2/send-file-popout-dialog/send-file-popout-dialog-container.component.ts
> +  imports: [JslibModule, CommonModule, DialogModule, ButtonModule, TypographyModule],
The Dialog-, Button- and TypographyModule shouldn't be needed here, as there's no markup to render

2024-09-25 19:35 UTC, merged