[PM-11926]  - send created redirect
bitwarden/clients pull request #11140
Opened 2024-09-18 22:19 UTC by jaasen-livefront

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-11926

## 📔 Objective

This PR adds a redirect to the send created page after successfully creating a send as part of the extension refresh.

## 📸 Screenshots

## Note: the icon in the send-created page isn't rendering properly because of the new tw `art` prefix classes that will be added along with the extension refresh.

https://github.com/user-attachments/assets/c6a45805-343a-4642-ab49-df9707457cdb

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-24 18:45 UTC, djsmith85 requested changes

2024-09-24 18:45 UTC, djsmith85 commented on apps/browser/src/tools/popup/send-v2/send-created/send-created.component.html
> +      [backAction]="close.bind(this)"
⛏️ This can just be close
```suggestion
      [backAction]="close"
```

2024-09-24 18:45 UTC, djsmith85 commented on libs/common/src/tools/send/services/send-api.service.ts
> +  async save(sendData: [Send, EncArrayBuffer]): Promise<SendData> {
⚠️ Please also update the `send-api.service.abstraction`

2024-09-24 20:41 UTC, jaasen-livefront commented on apps/browser/src/tools/popup/send-v2/send-created/send-created.component.html
> +      [backAction]="close.bind(this)"
@djsmith85 Binding to the current context is required here, otherwise the popup header component will attempt to call `this.close` which doesn't exist in `PopupHeaderComponent`. There's a similar implementation [here](https://github.com/bitwarden/clients/blob/4b6c7bf0df1012aea1c820d6de28898fc64c17b2/apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.html#L5).

2024-10-01 19:48 UTC, djsmith85 approved these changes
I've updated the model being used to bubble up after calling save.

I have split the save and navigation part and use events to differ between create and update. The navigation (back or to the send-created-page) has been moved out of the shared component into the client-specific send-add-edit.component. The idea being that we later implement this component on web and desktop. The only thing I haven't found a great solution for is the back-navigation of the send-created page. This will need to be refactored at a later point. 

Either find a way to wire up a send-create-close event and use the send-add-edit.component to take care of the navigation
or
The send-created page is slimmed down to it's body and the send-add-edit.component.html includes it under a conditional. That would mean though that it would also need to change the header and take care of the new buttons shown in the footer 🤷 

Merging this, to continue testing, but will need more work to make it a fully shareable component across all clients.

2024-10-01 19:58 UTC, merged