[PM-11503] Organization Automatic Sync verbiage is misleading
bitwarden/clients pull request #11151
Opened 2024-09-19 14:21 UTC by jonashendrickx

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-19 18:58 UTC, djsmith85 requested changes

2024-09-19 18:58 UTC, djsmith85 commented on apps/web/src/locales/en/messages.json
> +  },
⚠️  This has no changes to the removed `billingSyncDesc `

2024-09-19 18:58 UTC, djsmith85 commented on apps/web/src/app/billing/organizations/organization-subscription-selfhost.component.html
> +            {{ "manualBillingTokenUploadDesc" | i18n }}
⚠️ `manualBillingTokenUploadDesc` is not defined in the `en/messages.json`

2024-09-19 18:58 UTC, djsmith85 commented on apps/web/src/app/billing/organizations/organization-subscription-selfhost.component.html
> +            {{ "automaticBillingSyncDesc" | i18n }}
⚠️ `automaticBillingSyncDesc ` is not defined in the `en/messages.json`

2024-09-20 11:10 UTC, djsmith85 commented on apps/web/src/app/billing/organizations/organization-subscription-selfhost.component.html
> +            {{ "automaticBillingSyncDesc" | i18n }}
⚠️  Still an issue. As the message belonging to `automaticBillingSyncDesc` has no changes over `billingSyncDesc`, maybe just revert this line and also the changes in `en/messages.json` where `billingSyncDesc` is removed.

2024-09-20 11:11 UTC, djsmith85 commented on apps/web/src/locales/en/messages.json
> +  },
⚠️ Also still an issue

2024-09-20 14:38 UTC, cturnbull-bitwarden submitted a review, later dismissed

2024-09-23 09:18 UTC, djsmith85 requested changes

2024-09-23 09:18 UTC, djsmith85 commented on apps/web/src/locales/en/messages.json
> +  },
This message key is defined, but not used anywhere. 

❓  Is it possible that `billingSyncDesc`was supposed to be replaced with `billingTokenSyncDesc`, but you then introduced `automaticBillingSyncDesc`as the final replacement? If my assumption is correct, then please remove `billingTokenSyncDesc`from `en/messages.json`

2024-09-23 10:41 UTC, djsmith85 submitted a review, later dismissed

2024-09-23 13:08 UTC, cturnbull-bitwarden approved these changes

2024-09-23 16:08 UTC, djsmith85 approved these changes

2024-09-24 13:23 UTC, amorask-bitwarden approved these changes

2024-10-02 09:23 UTC, merged