[PM-12359] Fix typography of change shortcut section text
bitwarden/clients pull request #11163
Opened 2024-09-19 20:53 UTC by jprusik

## 🎟️ Tracking

PM-12359

## 📔 Objective

> In the autofill settings page, the “Autofill shortcut” section shows “Manage shortcuts” text as larger, this makes the hierarchy of the page a bit funky. 

This PR fixes that

## 📸 Screenshots

| Before | After |
| --- | --- ||
| ![section-before](https://github.com/user-attachments/assets/cd985016-0164-49bc-b39a-11e6ef1d0390) | ![section-after](https://github.com/user-attachments/assets/70417510-afd0-490e-a934-9c1eebd806c5) |

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-19 21:40 UTC, danielleflinn requested changes

2024-09-19 21:40 UTC, danielleflinn commented on apps/browser/src/autofill/popup/settings/autofill.component.html
> +      <bit-card bitTypography="body2">
@jprusik I'm not seeing a visual difference in your screenshots; it seems like this change was made in the "Autofill on page load" section. Is this change supposed to be on line 110?

2024-09-20 16:49 UTC, jprusik commented on apps/browser/src/autofill/popup/settings/autofill.component.html
> +      <bit-card bitTypography="body2">
fixed in 9e11aea9c80026e42d6523f5a0bff2d505b5320d

2024-09-20 16:50 UTC, danielleflinn approved these changes
Looks great! Thank you

2024-09-20 16:52 UTC, cagonzalezcs approved these changes

2024-09-20 16:59 UTC, merged