[PM-12505] - add delete send button to footer
bitwarden/clients pull request #11187
Opened 2024-09-20 23:45 UTC by jaasen-livefront

## 🎟️ Tracking
https://bitwarden.atlassian.net/browse/PM-12505

## 📔 Objective

This PR adds the delete button to the footer of the edit send page.

## 📸 Screenshots

https://github.com/user-attachments/assets/6d1e657e-7816-4564-b5d5-58311b2c92dc

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-23 17:23 UTC, djsmith85 requested changes
As a quick win (approaching deadline), we can include the delete within the send-add-edit.component. 

Thinking forward though about re-using the `send-form.component` on other clients, it should take care of the deletion (via `SendFormConfigService`) and prompt like it already does for the submit action.

I envision a `onSendDeleted`-event which would then take care of the navigation and success toast, which are client-specific. On browser I'd navigate back (this.location.back) but on web I'd close a dialog and on desktop I might remove/hide the tools-send-form 🤷

2024-09-23 17:23 UTC, djsmith85 commented on apps/browser/src/tools/popup/send-v2/add-edit/send-add-edit.component.ts
> +      content: { key: "deleteSendConfirmation" },
The message needs to be changed according to the design into:
"Are you sure you want to _permanently_ delete this Send?"

While this is being changed, it should also be used within the `send-list-items-container.component`

2024-09-23 17:23 UTC, djsmith85 commented on apps/browser/src/tools/popup/send-v2/add-edit/send-add-edit.component.html
> +      class="tw-border-0 tw-ml-auto bwi-lg"
The classes shouldn't be need

2024-09-23 17:23 UTC, djsmith85 commented on apps/browser/src/tools/popup/send-v2/add-edit/send-add-edit.component.html
> +      (click)="deleteSend()"
Please use `bitAction` instead. Example for the delete button can be found on the [vault's view2 component](https://github.com/bitwarden/clients/blob/bcddf575a1935e2c29189f0707587afaf82f5f84/apps/browser/src/vault/popup/components/vault-v2/view-v2/view-v2.component.html#L29)

2024-09-23 17:34 UTC, jaasen-livefront commented on apps/browser/src/tools/popup/send-v2/add-edit/send-add-edit.component.html
> +      class="tw-border-0 tw-ml-auto bwi-lg"
@djsmith85 Without the classes the icon gets a border, doesn't align right, and is too small.

2024-09-23 17:39 UTC, djsmith85 commented on apps/browser/src/tools/popup/send-v2/add-edit/send-add-edit.component.html
> +      class="tw-border-0 tw-ml-auto bwi-lg"
@danielleflinn

2024-09-23 17:43 UTC, djsmith85 approved these changes
Approving for the changes I requested, leaving it to @danielleflinn to comment/approve on the usage of the classes.

2024-09-23 17:45 UTC, djsmith85 requested changes

2024-09-23 17:51 UTC, danielleflinn commented on apps/browser/src/tools/popup/send-v2/add-edit/send-add-edit.component.html
> +      class="tw-border-0 tw-ml-auto bwi-lg"
This component should use https://components.bitwarden.com/?path=/story/component-library-icon-button--danger, in the current styles it has a border which will be removed in the Design System feature branch.

2024-09-23 18:18 UTC, jaasen-livefront commented on apps/browser/src/tools/popup/send-v2/add-edit/send-add-edit.component.html
> +      class="tw-border-0 tw-ml-auto bwi-lg"
Ok I'll remove the `tw-border-0` class. According to @danielleflinn's feedback everything else should remain unless I'm missing something.

2024-09-23 19:35 UTC, danielleflinn approved these changes

2024-09-24 07:26 UTC, djsmith85 approved these changes

2024-09-24 07:26 UTC, merged