[PM-12504] - hide create send button and send tab when sends are disabled
bitwarden/clients pull request #11186
Opened 2024-09-20 22:56 UTC by jaasen-livefront

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-12504

## 📔 Objective

This PR implements the requirements to the send list page and nav for when sends are disabled:

1. remove the create send button
2. display callout
3. remove sends from tab if user has no sends

## 📸 Screenshots

|With existing send|Without existing send|
---|---
|![Screenshot 2024-09-20 at 3 51 59 PM](https://github.com/user-attachments/assets/a36e1738-ebd2-458e-82b3-9fef504b6c5a)|![Screenshot 2024-09-20 at 3 35 02 PM](https://github.com/user-attachments/assets/3df34540-b071-49b9-be0f-f936107add01)|

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-23 14:05 UTC, audreyality requested changes
❌ Need to fix the failing unit tests.

The other feedback is discussion and questions. It doesn't block the merge.

2024-09-23 18:20 UTC, jaasen-livefront commented on apps/browser/src/platform/popup/layout/popup-tab-navigation.component.ts
> +    ])
@audreyality Great feedback thanks!

2024-09-23 18:21 UTC, jaasen-livefront commented on apps/browser/src/platform/popup/layout/popup-tab-navigation.component.ts
> +    private sendItemsService: SendItemsService,
@audreyality @djsmith85  I updated it to instead use the `SendService` which is a more direct path.

2024-09-23 19:14 UTC, audreyality commented on apps/browser/src/platform/popup/layout/popup-tab-navigation.component.ts
> +    private sendItemsService: SendItemsService,
Sorry, I wasn't clear. I'm wondering whether policy should be enforced by the service, as opposed to by the component.

2024-09-24 13:54 UTC, audreyality requested changes

2024-09-24 20:33 UTC, audreyality approved these changes

2024-09-24 20:36 UTC, audreyality commented on apps/browser/src/platform/popup/layout/popup-tab-navigation.component.ts
> +    private sendItemsService: SendItemsService,
🌱 Discussed this question with Daniel offline. We want to move towards smart services and low-logic components. There's quite a few options on how to accomplish that, and we'll do so in a future tech breakdown. :)

2024-09-25 13:18 UTC, vleague2 requested changes

2024-09-25 13:18 UTC, vleague2 commented on apps/browser/src/platform/popup/layout/popup-tab-navigation.component.ts
> +    private sendService: SendService,
I know I just approved but then I thought to check Storybook -- there is a story for the popup layout components, which are now throwing console errors because these services are not mocked in the story. Could you update that?

2024-09-25 16:35 UTC, audreyality approved these changes

2024-09-25 16:42 UTC, jaasen-livefront commented on apps/browser/src/platform/popup/layout/popup-tab-navigation.component.ts
> +    private sendService: SendService,
@vleague2 Nice catch!

2024-09-25 17:38 UTC, vleague2 approved these changes

2024-09-25 17:40 UTC, merged