[PM-5611] username generator settings
bitwarden/clients pull request #11201
Opened 2024-09-23 15:36 UTC by audreyality

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-5611

## 📔 Objective

Add components for generating usernames and email addresses.

Note: omits forwarders; these will be added in a later PR.

## 🐞 Known issues

- [ ] Username generator not reachable on UI (only options blocks)
- [ ] Net-new functionality is not yet unit tested
- [ ] Public and protected members are not fully documented
- [ ] GeneratorType -> CredentialType rename affects files outside of modern UI scope

## 🦕 System Evolution

This PR introduces "generator preferences" that track the user's last selections in the UI. These distinguish between the different contexts in which the generator can be used using "generator categories". The primary difference between the preferences and navigation settings is that preferences distinguish between usernames and email addresses, whereas the navigation settings are tightly bound to the generator's navigation context.

This PR also introduces the idea of algorithms. These were always present, and the name exists largely to distinguish them from the legacy logic, which uses "types" and "subtypes" instead. The purpose of this logic is enabling data-driven (and, in particular, policy-driven) capabilities at the service level. 

These features will be backported to the password component to enable the password/passphrase options to be filtered according to the user's active policy. They will also be used to surface forthcoming integrations including SSH credential generation and forwarder support. Last but not least, they allow the policy subsystem to target arbitrary credential types--specifically usernames and email addresses.

## 📸 Screenshots

TBD

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-23 15:58 UTC, audreyality commented
> ![Logo](https://camo.githubusercontent.com/b91f4d9f898c088eaec6e978363a73a243fd9fdc575892ad49036b910fb9d528/68747470733a2f2f63646e2e6173742e636865636b6d6172782e6e65742f696e746567726174696f6e732f6c6f676f2f436865636b6d6172782e706e67) **Checkmarx One – Scan Summary & Details** – [682a2c5f-ef0a-41fb-a63a-dffc07decaf6](https://ast.checkmarx.net/projects/41bd746e-d417-4eda-afeb-01a59d162661/scans?id=682a2c5f-ef0a-41fb-a63a-dffc07decaf6&branch=tools%2FPM-5611%2Fusername-generator-settings)
> ### New Issues
> Severity 	Issue 	Source File / Package 	Checkmarx Insight
> ![MEDIUM](https://camo.githubusercontent.com/1aff14a175a437056d0282b90c228a18633d1363177a8223b360f316f92050e2/68747470733a2f2f63646e2e6173742e636865636b6d6172782e6e65742f696e746567726174696f6e732f73657665726974792f4d656469756d2e706e67) 	[Client_Privacy_Violation](https://ast.checkmarx.net/results/41bd746e-d417-4eda-afeb-01a59d162661/682a2c5f-ef0a-41fb-a63a-dffc07decaf6/sast/description/359/2526234764757185080) 	/libs/tools/generator/components/src/username-generator.component.html: [3](https://github.com/bitwarden/clients/blob/tools/PM-5611/username-generator-settings//libs/tools/generator/components/src/username-generator.component.html#L3) 	[Attack Vector](https://ast.checkmarx.net/results/682a2c5f-ef0a-41fb-a63a-dffc07decaf6/41bd746e-d417-4eda-afeb-01a59d162661/sast?result-id=dcMAOyN2a1j3Yz68cXyLaWC6DSo%3D&redirect=true)

@withinfocus - Do you know if it's possible to add an exception/allowance to checkmarx so it knows `bit-color-password` isn't sending credentials to an external source?

2024-09-23 16:02 UTC, withinfocus commented
That would be going in and marking the findings as not exploitable / proposed not exploitable. Somewhat manual but once it's done it should stay closed unless a significant refactor happens.

2024-09-25 18:42 UTC, djsmith85 requested changes

2024-09-25 18:42 UTC, djsmith85 commented on libs/tools/generator/core/src/engine/username-randomizer.spec.ts
> +    it("processes password generation options", async () => {
⚠️ Please update the description of all added tests here (username-randomizer vs password)

2024-09-25 18:42 UTC, djsmith85 commented on libs/tools/generator/core/src/engine/username-randomizer.spec.ts
> +      const password = new UsernameRandomizer(randomizer);
⚠️ Please rename the variables used. SUT is an instance of UsernameRandomizer not a password.

2024-09-25 18:42 UTC, djsmith85 commented on libs/tools/generator/components/src/subaddress-settings.component.ts
> +/** Options group for passphrases */
⚠️ ⛏️  Wrong description for subaddress-settings.component

2024-09-25 18:42 UTC, djsmith85 commented on libs/tools/generator/components/src/catchall-settings.component.ts
> +/** Options group for passphrases */
⚠️ ⛏️  Wrong description for catchall-settings.component

2024-09-25 18:42 UTC, djsmith85 commented on libs/tools/generator/components/src/catchall-settings.component.ts
> +  userId: UserId | null;
⚠️ Docs needs to be updated

2024-09-25 18:42 UTC, djsmith85 commented on libs/tools/generator/components/src/subaddress-settings.component.ts
> +  userId: UserId | null;
⚠️ Docs needs to be updated

2024-09-25 18:42 UTC, djsmith85 commented on libs/tools/generator/components/src/username-generator.component.html
> +      {{ "generatePassword" | i18n }}
@danielleflinn This isn't mentioned within the design. To improve accessibility we should probably state what the user would be specifically generating when clicking the button (catchall, subaddress, username(forwarder). This change would also apply to the new password-generator.component

2024-09-25 18:42 UTC, djsmith85 commented on libs/tools/generator/components/src/username-generator.component.html
> +      {{ "copyPassword" | i18n }}
If we decide to adjust the text as stated above, then this should also be updated

2024-09-25 18:42 UTC, djsmith85 commented on libs/tools/generator/components/src/username-generator.component.ts
> +/** Options group for passwords */
⚠️ ⛏️  Wrong description for username-generator.component

2024-09-25 18:42 UTC, djsmith85 commented on libs/tools/generator/components/src/username-generator.component.ts
> +   */
⚠️ Docs needs to be updated

2024-09-25 18:42 UTC, djsmith85 commented on libs/tools/generator/components/src/username-settings.component.ts
> +/** Options group for passphrases */
⚠️ ⛏️ Wrong description for username-settings.component

2024-09-25 18:42 UTC, djsmith85 commented on libs/tools/generator/components/src/username-settings.component.ts
> +   */
⚠️ Docs needs to be updated

2024-09-25 19:18 UTC, audreyality commented on libs/tools/generator/core/src/engine/email-randomizer.spec.ts
> +      const password = new EmailRandomizer(randomizer);
Addressed by [c34c1c1](https://github.com/bitwarden/clients/pull/11201/commits/c34c1c12f043f224128cebb7da707569da5d78f2)

2024-09-25 19:18 UTC, audreyality commented on libs/tools/generator/core/src/engine/username-randomizer.spec.ts
> +    it("processes password generation options", async () => {
Addressed by [c34c1c1](https://github.com/bitwarden/clients/pull/11201/commits/c34c1c12f043f224128cebb7da707569da5d78f2)

2024-09-25 19:18 UTC, audreyality commented on libs/tools/generator/core/src/engine/username-randomizer.spec.ts
> +      const password = new UsernameRandomizer(randomizer);
Addressed by [c34c1c1](https://github.com/bitwarden/clients/pull/11201/commits/c34c1c12f043f224128cebb7da707569da5d78f2)

2024-09-25 19:18 UTC, audreyality commented on libs/tools/generator/components/src/subaddress-settings.component.ts
> +/** Options group for passphrases */
Addressed by [c34c1c1](https://github.com/bitwarden/clients/pull/11201/commits/c34c1c12f043f224128cebb7da707569da5d78f2)

2024-09-25 19:18 UTC, audreyality commented on libs/tools/generator/components/src/catchall-settings.component.ts
> +/** Options group for passphrases */
Addressed by [c34c1c1](https://github.com/bitwarden/clients/pull/11201/commits/c34c1c12f043f224128cebb7da707569da5d78f2)

2024-09-25 19:18 UTC, audreyality commented on libs/tools/generator/components/src/catchall-settings.component.ts
> +  userId: UserId | null;
Addressed by [c34c1c1](https://github.com/bitwarden/clients/pull/11201/commits/c34c1c12f043f224128cebb7da707569da5d78f2)

2024-09-25 19:18 UTC, audreyality commented on libs/tools/generator/components/src/subaddress-settings.component.ts
> +  userId: UserId | null;
Addressed by [c34c1c1](https://github.com/bitwarden/clients/pull/11201/commits/c34c1c12f043f224128cebb7da707569da5d78f2)

2024-09-25 19:19 UTC, audreyality commented on libs/tools/generator/components/src/username-generator.component.ts
> +/** Options group for passwords */
Addressed by [c34c1c1](https://github.com/bitwarden/clients/pull/11201/commits/c34c1c12f043f224128cebb7da707569da5d78f2)

2024-09-25 19:19 UTC, audreyality commented on libs/tools/generator/components/src/username-generator.component.ts
> +   */
Addressed by [c34c1c1](https://github.com/bitwarden/clients/pull/11201/commits/c34c1c12f043f224128cebb7da707569da5d78f2)

2024-09-25 19:19 UTC, audreyality commented on libs/tools/generator/components/src/username-settings.component.ts
> +/** Options group for passphrases */
Addressed by [c34c1c1](https://github.com/bitwarden/clients/pull/11201/commits/c34c1c12f043f224128cebb7da707569da5d78f2)

2024-09-25 19:19 UTC, audreyality commented on libs/tools/generator/components/src/username-settings.component.ts
> +   */
Addressed by [c34c1c1](https://github.com/bitwarden/clients/pull/11201/commits/c34c1c12f043f224128cebb7da707569da5d78f2)

2024-09-25 19:21 UTC, audreyality commented
⚠️ Known issue - typechecking on unit tests broke.

2024-09-25 19:25 UTC, audreyality commented on libs/tools/generator/components/src/username-generator.component.ts
> +  protected credentialTypes$ = new BehaviorSubject<Option<CredentialAlgorithm>[]>([]);
[I do](https://github.com/bitwarden/clients/blob/22108dc0b9075db49238198616e369babab94973/libs/tools/generator/components/src/username-generator.component.ts#L87-L88).

[As does the hint text](https://github.com/bitwarden/clients/blob/2c9b3a508162e4f32d93b9a68d0531e05b63ed36/libs/tools/generator/components/src/username-generator.component.ts#L95).

2024-09-25 19:30 UTC, audreyality commented on libs/tools/generator/components/src/username-generator.component.html
> +      {{ "generatePassword" | i18n }}
We probably don't want to be too specific, because getting the grammar right for every kind of generator will caues headaches. I recommend we either tie it to the credential categories (at present: password, username, email), or make it fully generic and just label it "generate credential" or similar.

2024-09-27 09:19 UTC, djsmith85 approved these changes
This is looking awesome! 

Definitely helped having time to review while in draft and discussing offline.

2024-09-27 13:02 UTC, merged