[PM-11199] added permission labels to ciphers in AC
bitwarden/clients pull request #11210
Opened 2024-09-23 22:36 UTC by Jingo88

## 🎟️ Tracking

[PM-11199](https://bitwarden.atlassian.net/browse/PM-11199)

## 📔 Objective

- Adding Permission Labels to Ciphers in AC.
- If a cipher belongs to multiple collections make sure the label shows the highest lvl permission

## 📸 Screenshots

<img width="1712" alt="PM-11199" src="https://github.com/user-attachments/assets/e210cbcd-a4ec-48a0-ba23-a6a19063bb15">

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-24 19:37 UTC, shane-melton requested changes
I think there may be potential to simplify this a bit, let me know what you think!

2024-09-24 19:37 UTC, shane-melton commented on apps/web/src/app/vault/components/vault-items/vault-cipher-row.component.ts
> +  protected get permissionText() {
🎨 The `cipher` view already has enough information to render the correct permission. You shouldn't need to check/iterate through the collections. Something like this should be enough:

```ts
get permissionKey() {
    if (this.cipher.edit) {
      return this.cipher.viewPassword ? "canEdit" : "canEditExceptPass";
    } else {
      return this.cipher.viewPassword ? "canView" : "canViewExceptPass";
    }
  }
```

2024-09-24 19:37 UTC, shane-melton commented on apps/web/src/app/vault/components/vault-items/vault-cipher-row.component.ts
> +  protected get permissionText() {
ℹ️  I also see that we do **not** automatically set the `cipher.edit` flag to true when a user has the `canEditAllCiphers` permission. We would need to either do this manually when we [fetch the ciphers here](https://github.com/bitwarden/clients/blob/3646214a0f8ea069fd01a982a0fdd86035c38646/apps/web/src/app/vault/org-vault/vault.component.ts#L337) or modify the server to adjust the response when the user has that level of access.

Something, like this could work in the org vault `allCiphers$` definition:
```ts
if (organization.canEditAllCiphers) {
  ciphers = await this.cipherService.getAllFromApiForOrganization(organization.id);
  ciphers?.forEach((c) => (c.edit = true));
} else {
  // Otherwise, only fetch ciphers they have access to (includes unassigned for admins).
  ciphers = await this.cipherService.getManyFromApiForOrganization(organization.id);
}
```

2024-09-30 19:47 UTC, shane-melton approved these changes

2024-10-02 14:26 UTC, gbubemismith submitted a review, later dismissed

2024-10-15 15:32 UTC, shane-melton approved these changes

2024-10-16 11:11 UTC, gbubemismith approved these changes

2024-10-22 14:07 UTC, merged