[CL-459] Fix chip behavior when opening menu while item is selected
bitwarden/clients pull request #11227
Opened 2024-09-24 20:05 UTC by vleague2

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-25 15:20 UTC, danielleflinn requested changes
✅ Root menu displays after opening / closing / reselecting chip without selecting anything
✅ Menu that contains the selected item displays when reopened after selecting an item with no children
✅ Menu that contains "view items" displays when reopened after selecting 
⛔️ Open menu after selecting an item, navigate to a sub-menu then close without changing selection. Re-open, observe the last menu that was viewed (sub-menu) is shown. Ideally when re-opening, the menu that contains the selected item would open.

2024-09-25 18:38 UTC, danielleflinn approved these changes
✅ Menu opens correctly if an item is selected and you navigate to a sub-menu and close it, then reopen. 

There is some incorrect behavior still appearing in the stories where we show a pre-selected chip. Not sure if that is something we can/should fix. 

https://github.com/user-attachments/assets/caf0e652-bd1c-4ae3-904c-8f8b1a7831b4

2024-09-25 20:00 UTC, merissaacosta approved these changes

2024-09-26 15:25 UTC, danielleflinn approved these changes

2024-09-26 15:52 UTC, merged