Split `LimitCollectionCreationDeletion` in two
bitwarden/clients pull request #11223
Opened 2024-09-24 16:49 UTC by addisonbeck

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-10-03 04:28 UTC, eliykat requested changes

2024-10-03 04:28 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/settings/account.component.ts
> +  protected collectionManagementFormGroup_VNext = this.formBuilder.group({
I can see the `vNext` formgroup is used in the TS code, but it doesn't appear to be referenced in the template.

2024-10-03 04:28 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/settings/account.component.ts
> +      .subscribe((x) => (this.limitCollectionCreationDeletionSplitFeatureFlagIsEnabled = x));
I recommend against subscribing, then you can just do a 1-liner: `this.limitCollectionCreationDeletionSplitFeatureFlagIsEnabled = this.configService.getFeatureFlag$(FeatureFlag.LimitCollectionCreationDeletionSplit);`.

Although I admit using `await firstValueFrom` is a bit awkward, that may come down to personal preference.

2024-10-07 18:49 UTC, addisonbeck commented on apps/web/src/app/admin-console/organizations/settings/account.component.ts
> +  protected collectionManagementFormGroup_VNext = this.formBuilder.group({
Thanks for the catch. Addressed!

__Commit:__ [Reference feature toggle in template](https://github.com/bitwarden/clients/pull/11223/commits/c712b074bc34cec7e52b5e64313b7f93ffb7f27b)

2024-10-07 18:51 UTC, addisonbeck commented on apps/web/src/app/admin-console/organizations/settings/account.component.ts
> +      .subscribe((x) => (this.limitCollectionCreationDeletionSplitFeatureFlagIsEnabled = x));
I do tend to use observables over promises as a principle. If you feel strongly about this let me know, but I don't think this matters too much for such ephemeral code. Both are definitely readable and people are used to observable data flows in the project.

2024-10-08 06:40 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/settings/account.component.ts
> +      .subscribe((x) => (this.limitCollectionCreationDeletionSplitFeatureFlagIsEnabled = x));
Not at all, I agree completely about it being ephemeral code.

2024-10-08 06:41 UTC, eliykat approved these changes

2024-10-16 14:35 UTC, JaredSnider-Bitwarden approved these changes
Auth change looks good

2024-10-17 03:33 UTC, eliykat approved these changes

2024-10-17 10:34 UTC, merged