Km/pm 10408/ssh generator with modern generator infrastructure
bitwarden/clients pull request #11232
Opened 2024-09-25 10:47 UTC by quexten

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-10-01 16:16 UTC, audreyality requested changes
The ⚠️ and ⛏️ comments are requested changes. The rest is me being thorough. That said, this PR is really good! There's just heavy development atm, and so you're catching the flak of extending a semi-stable system.

2024-10-01 16:16 UTC, audreyality commented on libs/tools/generator/core/src/data/policies.ts
⛏️ This file is provided to maintain compatibility with `@bitwarden/generator-legacy`. These changes can be reverted since you haven't extended that assembly.

2024-10-01 16:16 UTC, audreyality commented on libs/tools/generator/core/src/engine/abstractions.ts
🎨 The engine is, at present, an internal type. There's no need to abstract it behind an interface. Unless I missed something?

2024-10-01 16:16 UTC, audreyality commented on libs/tools/generator/core/src/engine/sshkey-generator.ts
> +    _request: SshKeyRequest,
⚠️ The request type should not vary. It's fixed across all generator implementations.

🌱 Generator algorithm awareness, for example, extends this to communicate category and algorithm. It's likely that forwarder support will extend it to communicate the selected integration. And so forth.

2024-10-01 16:16 UTC, audreyality commented on libs/tools/generator/core/src/strategies/sshkey-generator-strategy.ts
⚠️ Strategies are provided for backwards compatibility withlegacy services. The new system uses configurations for the same purpose. This can be deleted.

2024-10-01 16:16 UTC, audreyality commented on libs/tools/generator/core/src/strategies/storage.ts
> +    clearOn: [],
```suggestion
    clearOn: ["logout"],
```

2024-10-01 16:16 UTC, audreyality commented on libs/tools/generator/core/src/types/sshkey-generation-options.ts
> +  keyAlgorithm?: "rsa" | "ed25519";
⛏️ This should be extracted into the algorithm and category metadata.

2024-10-01 16:16 UTC, audreyality commented on libs/tools/generator/core/src/types/sshkey-generation-options.ts
❓ Is there a reason why these values may not be specified? Consider removing the `?` from them and fully defining their initial value instead.

2024-10-02 14:16 UTC, quexten commented on libs/tools/generator/core/src/data/default-sshkey-generation-options.ts
> +  bits: null,
E25519 has no concept of a configurable keylength/bits - it is always 32 bytes. So the setting does not make sense for this algorithm.

Would we add the default for RSA here, even though the default key type is ed25519?

2024-10-02 14:24 UTC, audreyality commented on libs/tools/generator/core/src/types/sshkey-generation-options.ts
> +  bits?: number;
```suggestion
  /** The key size of a variable-length `keyAlgorithm` in bits. 
   *  `null` when the selected key has a fixed width.
   */
  bits: number | null;
```

2024-10-02 14:26 UTC, audreyality commented on libs/tools/generator/core/src/data/default-sshkey-generation-options.ts
> +  bits: null,
Nope! I added a suggestion for how to document the type to explain this.

An alternative is to specify the key length for ed25519, even though it can't change.

2024-10-03 08:52 UTC, quexten commented on libs/tools/generator/core/src/engine/abstractions.ts
This was left from trying some approaches in the codebase. Cleaning this up.

2024-10-03 09:05 UTC, quexten commented on apps/desktop/src/app/tools/sshkey-generator.component.ts
> +  privateKey: string;
What is this referring to? The component is used in desktop/../add-edit.component.ts. 
Seems to be imported the wrong way though.

2024-10-03 09:10 UTC, quexten commented on libs/tools/generator/core/src/abstractions/sshkey-native-generator.abstraction.ts
> +export abstract class SshKeyNativeGeneratorAbstraction {
Might make sense to have the implementation be "DesktopNativeSshKeyNativeGenerator", and later add "SdkSshKeyNativeGenerator" to indicate where the generation is actually happening.

2024-10-03 13:36 UTC, audreyality commented on apps/desktop/src/app/tools/sshkey-generator.component.ts
> +  privateKey: string;
The `privateKey` property.

2024-10-03 13:38 UTC, audreyality commented on libs/tools/generator/core/src/abstractions/sshkey-native-generator.abstraction.ts
> +export abstract class SshKeyNativeGeneratorAbstraction {
👍🏻 I like that. 😄

2024-10-21 11:51 UTC, quexten commented on apps/desktop/src/app/tools/sshkey-generator.component.ts
> +  privateKey: string;
It is/was being used to cache the emitted credentials until the user hits save in the dialog. I feel like there is a better way though as the current approach would allow null values to be saved when the first generation takes longer than the user takes to save.

2024-10-21 12:03 UTC, quexten commented on libs/tools/generator/core/src/types/sshkey-generation-options.ts
> +  keyAlgorithm?: "rsa" | "ed25519";
Generation options no longer include the key algorithm.

2024-10-21 12:13 UTC, quexten commented on libs/tools/generator/core/src/engine/sshkey-generator.ts
> +    _request: SshKeyRequest,
Extended generate to include an algorithm parameter. Thoughts on somehow encoding the settings type for each credential algorithm on the type layer? If I were to introduce a separate type for rsa/ed25519 generationoptions, the type could at the moment not be enforced. I'd imagine there are other cases where the settings differ significantly between the algorithms?

2024-10-21 12:32 UTC, quexten commented on libs/tools/generator/components/src/sshkey-generator.component.ts
> +  readonly onGenerated = new EventEmitter<string>();
Emits GeneratedCredential now!

2024-10-21 13:37 UTC, quexten commented on apps/desktop/src/app/tools/sshkey-generator.component.ts
> +  @Output() generated = new EventEmitter<string>();
Implemented this!

2024-10-21 13:40 UTC, quexten commented on libs/tools/generator/components/src/sshkey-settings.component.ts
> +    [Controls.keyAlgorithm]: [Generators.SshKey.settings.initial.keyAlgorithm],
Seems to be fixed

2024-10-21 13:51 UTC, audreyality commented on apps/desktop/src/app/tools/sshkey-generator.component.ts
> +  privateKey: string;
A `BehaviorSubject` would hold onto the value for you and you could hook up a `pipe` that watches it so that you know when you can save.

```
// in .component.ts
private privateKey = new BehaviorSubject<...>(null);
protected canSaveKey$ = this.privateKey.pipe(map((k) => !k));

// in .component.html
<button [disabled]="canSaveKey$ | async">Save</button>
```

2024-10-21 14:02 UTC, audreyality commented on libs/tools/generator/core/src/engine/sshkey-generator.ts
> +    _request: SshKeyRequest,
> Extended generate to include an algorithm parameter. 

⛏️ You need to extend the `GenerationRequest` with an `algorithm` field. You shouldn't extend the generator. (That's why your PR is huge now.) The method only gets two parameters: One contains the request data surfaced by the generator system, the other contains settings data surfaced by your extension.

> Thoughts on somehow encoding the settings type for each credential algorithm on the type layer?

How is this different from the `Settings` type parameter? There are places where we need to erase it, but since we're always returning to a type-checked configuration that's internally consistent, the dynamism should still be type-safe.

2024-10-21 14:29 UTC, quexten commented on apps/desktop/src/app/tools/sshkey-generator.component.ts
> +  privateKey: string;
Nice, implemented this.

2024-10-21 15:06 UTC, audreyality commented on apps/desktop/src/app/tools/sshkey-generator.component.html
> +        <button type="button" data-dismiss="modal" (click)="onCancel()">Cancel</button>
⛏️ This should be localized.

2024-10-21 15:06 UTC, audreyality commented on apps/desktop/src/app/tools/sshkey-generator.component.html
> +        <button type="button" [disabled]="canSaveKey$ | async" class="primary" (click)="onSave()">
⛏️ This button requires an accessibility label.

2024-10-22 10:49 UTC, quexten commented on apps/desktop/src/app/tools/sshkey-generator.component.html
> +        <button type="button" data-dismiss="modal" (click)="onCancel()">Cancel</button>
Fixed.

2024-10-22 10:50 UTC, quexten commented on apps/desktop/src/app/tools/sshkey-generator.component.html
> +        <button type="button" [disabled]="canSaveKey$ | async" class="primary" (click)="onSave()">
Also fixed (I think)?

2024-10-22 10:52 UTC, quexten commented on libs/tools/generator/core/src/engine/sshkey-generator.ts
> +    _request: SshKeyRequest,
> ⛏️ You need to extend the GenerationRequest with an algorithm field. You shouldn't extend the generator. (That's why your PR is huge now.) The method only gets two parameters: One contains the request data surfaced by the generator system, the other contains settings data surfaced by your extension.

Okay, implemented this.

2024-10-22 10:58 UTC, quexten commented on libs/tools/generator/core/src/types/sshkey-generation-options.ts
At this point GitHub does not seem to show what this is referring to. Do you know if this point is still relevant or if it was fixed along the way?

2024-10-22 13:29 UTC, audreyality commented on apps/desktop/src/app/tools/sshkey-generator.component.html
🤔 It just occurred to me that you've split the component's template out from its impl. I think the template should reside with the impl in `@bitwarden/components`.

2024-10-22 13:29 UTC, audreyality commented on apps/desktop/src/app/tools/sshkey-generator.component.html
> +        <button type="button" [disabled]="canSaveKey$ | async" class="primary" (click)="onSave()">
There's guidance at [components.bitwarden.com](https://components.bitwarden.com/?path=/docs/component-library-icon-button--docs#accessibility)

2024-10-22 13:32 UTC, audreyality commented on libs/tools/generator/core/src/types/sshkey-generation-options.ts
This comment is attached to the whole file. I'm talking about the member(s) of the [`SsshKeyGenerationOptions` class](https://github.com/bitwarden/clients/blob/km/pm-10408/ssh-generator-with-modern-generator-infrastructure/libs/tools/generator/core/src/types/sshkey-generation-options.ts).

Seems that you've addressed it!

2024-10-22 13:45 UTC, audreyality commented on libs/tools/generator/core/src/data/generators.ts
> +  id: "rsa",
❓ Are there other kinds of RSA keys that we'd like to generate? (I'm mainly wondering whether this should have an ID that includes ssh in it as a means to distinguish it from other uses of RSA.)

2024-10-22 13:47 UTC, audreyality commented on libs/tools/generator/core/src/engine/sshkey-generator.ts
> +        request.algorithm as "rsa" | "ed25519",
🎨 You can use your `SshKeyAlgorithm` type here instead of the anonymous type.

2024-10-22 13:51 UTC, audreyality commented on libs/tools/generator/core/src/services/credential-generator.service.ts
> +    const algorithm$ = dependencies?.algorithm$ ?? new BehaviorSubject<CredentialAlgorithm>(null);
📝 Just a note that this is sufficient for now, but it'll be changing before the end of the year. `generate$` should actually load the configuration and wire it in. 

This is very much out of scope of the PR. Just didn't want you to be surprised if you revisit it after I get the change in place.

2024-10-22 13:59 UTC, audreyality commented on libs/tools/generator/core/src/abstractions/sshkey-native-generator.abstraction.ts
> +export abstract class SshKeyNativeGenerator {
💭 I'm not sure that this type is necessary. It only has two implementations--one that trampolines to the platform code and one that's a no-op. Why can't these be implemented in the engine directly?

2024-10-22 14:00 UTC, audreyality commented on libs/tools/generator/core/src/strategies/storage.ts
> +export const ED25519_SSHKEY_SETTINGS = new UserKeyDefinition<SshKeyGenerationOptions>(
⛏️ This should be loading and saving `Record<string, never>` correct? It doesn't have any settings.

2024-10-22 14:01 UTC, audreyality commented on libs/tools/generator/core/src/types/sshkey-generation-options.ts
> +export type SshKeyGenerationOptions = {
⛏️ This should probably be `RsaSshKeyGenerationOptions`

2024-10-23 09:34 UTC, quexten commented on apps/desktop/src/app/tools/sshkey-generator.component.html
> +        <button type="button" [disabled]="canSaveKey$ | async" class="primary" (click)="onSave()">
Changed to `applyA11yTitle`, thanks for the link!

2024-10-23 09:41 UTC, quexten commented on apps/desktop/src/app/tools/sshkey-generator.component.html
Hmm, is this just a naming issue? This component should actually be `sshkey-generator-dialog.component.html`. The typescript file for it is already in the same path.  This one is just the dialog. I'm not sure whether other platforms would re-use the dialog (in contrast to the generator component)? `libs/tools/generator/../` contains another - shared - `sshkey-generator.component.{html,ts}`, which is the actual generator component.

2024-10-23 09:43 UTC, quexten commented on libs/tools/generator/core/src/data/generators.ts
> +  id: "rsa",
Yeah, that makes sense. Just to clarify, id's are "globally" unique, not per category unique, right?

2024-10-23 09:48 UTC, quexten commented on libs/tools/generator/core/src/abstractions/sshkey-native-generator.abstraction.ts
> +export abstract class SshKeyNativeGenerator {
Is it possible to have engine implementations live in e.g. `apps/desktop/**/`? The electron implementation needs access to `ipc` which is not possible in the shared modules.

2024-10-23 10:06 UTC, quexten commented on libs/tools/generator/core/src/engine/sshkey-generator.ts
> +        request.algorithm as "rsa" | "ed25519",
Done in d89d1a0d9

2024-10-23 10:08 UTC, quexten commented on libs/tools/generator/core/src/strategies/storage.ts
> +export const ED25519_SSHKEY_SETTINGS = new UserKeyDefinition<SshKeyGenerationOptions>(
Instead of directly using `Record<string, never>`, I've now rename the previous `SshKeyGenerationOptions` to RsaSshKeyGenerationOptions` and added `export type Ed25519KeyGenrationOptions = Record<string, never>;`

2024-10-23 10:08 UTC, quexten commented on libs/tools/generator/core/src/types/sshkey-generation-options.ts
> +export type SshKeyGenerationOptions = {
Added in ad89d1a

2024-10-28 13:46 UTC, audreyality commented on apps/desktop/src/app/tools/sshkey-generator.component.html
> +        <button type="button" [disabled]="canSaveKey$ | async" class="primary" (click)="onSave()">
There's now new support for this logic in `main`. You'll need to [specify the i18n keys](https://github.com/bitwarden/clients/blob/main/libs/tools/generator/core/src/types/credential-generator-configuration.ts#L73-L83) in your configuration. Then you can read the localized values using [the related properties in `AlgorithmInfo`](https://github.com/bitwarden/clients/blob/main/libs/tools/generator/core/src/types/credential-generator-configuration.ts#L31-L44).

2024-10-28 13:47 UTC, audreyality commented on apps/desktop/src/app/tools/sshkey-generator.component.html
🤦🏻‍♀️ You're totally right. This feedback is incorrect.

2024-10-28 13:49 UTC, audreyality commented on libs/tools/generator/core/src/data/generators.ts
> +  id: "rsa",
They're unique within the bounds of the generator logic. They're not unique across the full application.

2024-10-28 13:53 UTC, audreyality commented on libs/tools/generator/core/src/engine/sshkey-generator.ts
> +        request.algorithm as "rsa" | "ed25519",
📝 Looks like you need to push this up?

2024-10-28 14:05 UTC, audreyality commented on libs/tools/generator/core/src/abstractions/sshkey-native-generator.abstraction.ts
> +export abstract class SshKeyNativeGenerator {
I see what you're going for here. This is a platform interface that the generator just happens to use.

This interface belongs in [`@bitwarden/common/platform/abstractions`](https://github.com/bitwarden/clients/tree/main/libs/common/src/platform/abstractions). It's no-op implementation belongs to `@bitwarden/common` as well. The reason being that IPC is presently owned by platform; it's not presently included in the generator's scope.

2024-10-28 14:09 UTC, audreyality reviewed
👍🏻 This is looking pretty good! 

I've added a few comments to explain changes needed due to the recently merged forwarder logic and component bugfixes. Please let me know if you need help resolving the merge!

2025-01-14 14:31 UTC, closed without merging