[PM-10426] Admin Console - Edit Modal
bitwarden/clients pull request #11249
Opened 2024-09-25 19:37 UTC by nick-livefront

## 🎟️ Tracking

## 📔 Objective

- Add the Extension Refresh styling to the Admin Console Vault
  - With how the data is updated with the `refresh$` observable and keeping state in the query parameters, I was seeing multiple instances of the view modal open after an edit takes place. This is going to solved by @shane-melton's work in combining the view/add/edit modal into a single modal. 
    - Because of this, I removed all "view" modal logic and matched the current experience in admin console of only having an edit option.
- Added a config option and relevant UI to hide the folder selection in the Add/Edit modal. Folders aren't applicable to admin console.

### Observable Oddity

As you can see in my video below when creating a new cipher, there is a duration of time when the cipher isn't created but the query params are updated causing the "unknown cipher" toast to display. 

For this reason, I'm keeping this as a draft PR but can be reviewed or used for @shane-melton's work. 

## 📸 Screenshots

|Edit then Add|
|-|
|<video src="https://github.com/user-attachments/assets/a83d199b-f54b-46f5-bbe5-4e74f5a705e6" />|

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-10-03 18:11 UTC, danielleflinn submitted a review, later dismissed
Screen recordings look good as I expect the generator dialogs will be updated later when the generator PR is merged. 

> Should I add functionality to refresh the vault when a cipher is saved and the user is navigated to the view dialog?

Hmm, I think it would make sense to refresh the Vault on Save of a new item, if it isn't too complex. But I will differ to Shane on the final call, ideally the behavior would be consistent with what we have in the end user PM view.

2024-10-03 19:44 UTC, shane-melton requested changes
Nice work on this! I think its coming together nicely! I just see a few permission issues we'll need to resolve.

As for refreshing the Vault after a cipher is saved, but before closing the dialog;  we can find a way to do that, but I had left it to only refresh on dialog close in the PM. Watching for the dialog result was the most straightforward way to know if a save event occured.

If we want to refresh on every save, we'll need to include some type of event emitter in our `dialogRef` so that the caller can listen to both the close and save observables.

2024-10-03 19:44 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/services/admin-console-cipher-form-config.service.ts
> +  );
⚠️ This should match the `editableCollections$` observable from the org vault to be sure the acting user has access to assign items to the selected collections. Something like this perhaps:

```
    private editableCollections$ = organization$.pipe(
      switchMap(async (org) => {
        const collections = await this.collectionAdminService.getAll(org.id)
        // Users that can edit all ciphers can implicitly add to / edit within any collection
        if (org.canEditAllCiphers) {
          return collections;
        }
        // The user is only allowed to add/edit items to assigned collections that are not readonly
        return collections.filter((c) => c.assigned && !c.readOnly);
      }),
    );
```

2024-10-03 19:44 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/services/admin-console-cipher-form-config.service.ts
> +    const cipherData = new CipherData(cipherResponse);
❓ We may need to set `cipherReponse.edit = true` here like we did in the org vault add-edit component. I can't recall if the admin endpoint sets this to `true` for us.

2024-10-03 19:44 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +    cloneCipher: boolean,
⛏️ Can we move the JSdocs above the method so they're not between the args?

2024-10-03 19:44 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +    const cipher = await this.cipherService.get(id);
⚠️ This will fail for Unassigned ciphers as they're not available in the `cipherService`. We were passing in the entire `cipherView` to this method previously to avoid needing to repeat the logic performed in building the `allCiphers$` observable. 

I think we should still pass the view object in here directly, and if it doesn't exist we should return early as it is not possible to open the dialog in View mode without a cipher.

2024-10-03 19:44 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +      formConfig,
⚠️ We should set the `disableForm` dialog parameter here as it was a direct replacement for `disableEdit` for the original View dialog. It should be set based on the if the cipher can be modified. 

e.g. `disableForm: !cipher.edit && !this.organization.canEditAllCiphers`

2024-10-03 19:44 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +      cipher?.edit ? "edit" : "partial-edit",
🎨 `partial-edit` is used to edit Folders and Favorite status, both of which should be hidden in the AC, so we should just leave this as "edit". The `disableForm` dialog parameter mentioned in my other comment will disable the cipher form entirely.

2024-10-03 19:44 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +        filter(() => this.vaultItemDialogRef == undefined || !this.extensionRefreshEnabled),
👍 Thanks for copying this over to the org vault!

2024-10-03 19:44 UTC, shane-melton commented on libs/vault/src/cipher-form/components/item-details/item-details-section.component.html
🎨 We should also hide the "Favorite ⭐" icon when in the AC as it is also not applicable there. Maybe we can repurpose/rename this option to hide both of those fields? Maybe something like `hideIndividualFields`?

2024-10-04 16:09 UTC, nick-livefront commented on apps/web/src/app/vault/org-vault/services/admin-console-cipher-form-config.service.ts
> +  );
Good catch! [e4b3f28](https://github.com/bitwarden/clients/pull/11249/commits/e4b3f28165789a1c119af39d7b2bd6ef8145bfa0)

2024-10-04 16:10 UTC, nick-livefront commented on apps/web/src/app/vault/org-vault/services/admin-console-cipher-form-config.service.ts
> +    const cipherData = new CipherData(cipherResponse);
Tracing back the original vault code, it was introduced here https://github.com/bitwarden/clients/pull/4025, so I'd agree probably needed! [09d7fe2](https://github.com/bitwarden/clients/pull/11249/commits/09d7fe2c750d41a8d160c61779a3999c3051b632)

2024-10-04 16:11 UTC, nick-livefront commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +    cloneCipher: boolean,
[1edc24e](https://github.com/bitwarden/clients/pull/11249/commits/1edc24e7b549bf60f20e650f6902db363567a7f3)

2024-10-04 16:14 UTC, nick-livefront commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +      formConfig,
[85a53f4](https://github.com/bitwarden/clients/pull/11249/commits/85a53f4e5986cf0abe80e34924589c7a869ab48b)

2024-10-04 16:14 UTC, nick-livefront commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +      cipher?.edit ? "edit" : "partial-edit",
[03b8a29](https://github.com/bitwarden/clients/pull/11249/commits/03b8a29a11dde00dd6658f453dbdcf28579ae670)

2024-10-04 16:15 UTC, nick-livefront commented on libs/vault/src/cipher-form/components/item-details/item-details-section.component.html
I ended up with `hideIndividualVaultFields`, does that clash with any other naming conventions I'm not aware of?

[787c962](https://github.com/bitwarden/clients/pull/11249/commits/787c962e95ad52b4ce1028853b4e3b556f76a9db)

2024-10-04 17:01 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +    const cipher = await this.cipherService.get(id);
Ah, good catch, it will also fail there as well and we should make the same change there. 

For clarity, "fail" means it will simply skip the re-prompt and continue to the edit dialog. The edit dialog opened successfully because it has custom logic internally to retrieve the cipher from the admin API if its not available in the cipherService. That's also why this has likely gone un-noticed, you have would specifically need to have MP re-prompt enabled for an unassigned item that is opened in the AC.

(btw, you can create unassigned items by deleting the last collection an item is assigned to)

2024-10-04 17:01 UTC, shane-melton commented on libs/vault/src/cipher-form/components/item-details/item-details-section.component.html
I don't see any problem with that name, thanks!

2024-10-04 17:16 UTC, shane-melton requested changes
Just two more small nits/suggestions and the change to pass `CipherView` to `editCipher()` and then I think this is good to go! Nice work!

2024-10-04 17:16 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/services/admin-console-cipher-form-config.service.ts
> +      allowPersonalOwnership,
🎨 I just noticed the Owner dropdown is enabled in the demo, so we should probably set `allowPersonalOwnership` to false here so they can't create personal items while in the AC.

2024-10-04 17:16 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +      cipher?.type,
⛏️ We have mixed use of `?` on `cipher` on these two lines. We should probably just return early at the top of the method if `cipher == null` as there's nothing to view at that point and something has likely gone wrong.

2024-10-04 18:16 UTC, nick-livefront commented on apps/web/src/app/vault/org-vault/services/admin-console-cipher-form-config.service.ts
> +      allowPersonalOwnership,
Makes sense! [f04fef5](https://github.com/bitwarden/clients/pull/11249/commits/f04fef59f40ee986be2b6ea794d29ec0875b74c7)

2024-10-04 18:21 UTC, shane-melton approved these changes
I think this looks good to go! 

We should likely do a quick test/pass without the feature flag enabled to ensure we're not breaking anything with the changes related to passing in the full cipher objects. (or simply wait until after the next `rc` cut next week)

2024-10-07 15:59 UTC, merged