[PM-12425] Remove FF: AC-2828_provider-portal-members-page
bitwarden/clients pull request #11241
Opened 2024-09-25 14:37 UTC by amorask-bitwarden

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-12425

## 📔 Objective

Removes the enabled `AC-2828_provider-portal-members-page` feature flag and updates the `bulk-confirm.component` and `bulk-remove.component` in Admin Console to extend the `base-bulk-confirm.component` and `base-bulk-remove.component` respectively.

## 📸 Screenshots

Bulk invite users in Admin Console (unchanged):

https://github.com/user-attachments/assets/834da705-d9b4-4d9d-a5c3-4d06b9330d1d

Bulk confirm users in Admin Console:

https://github.com/user-attachments/assets/fdc6e19e-9e38-48f1-9d3c-a6a64fd5a802

Bulk remove users in Admin Console:

https://github.com/user-attachments/assets/4fc1cb90-67f1-48b5-8100-d575fae94f5a

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-26 05:29 UTC, eliykat requested changes
Partial review only, I'll finish it tomorrow, but here's some feedback in the meantime.

2024-09-26 05:29 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/providers/providers-routing.module.ts
> +                path: "members",
You also need to update the side nav to read "Members" instead of "People" and navigate to the updated route. It's currently broken.

2024-09-26 15:27 UTC, amorask-bitwarden commented on bitwarden_license/bit-web/src/app/admin-console/providers/providers-routing.module.ts
> +                path: "members",
Thanks for catching that. Resolved in https://github.com/bitwarden/clients/pull/11241/commits/9a649f23d386653302a2473fe169f1f7ae85709c.

https://github.com/user-attachments/assets/119b7cc9-ee62-45c8-85de-58644e0c93d2

2024-10-01 04:41 UTC, eliykat submitted a review, later dismissed
Thanks @amorask-bitwarden ! Please make sure to send this via QA so they can do a quick regression on the bulk confirm and bulk remove.

2024-10-21 17:43 UTC, amorask-bitwarden commented
@eliykat This came out of QA with some merge conflicts, mind if I get another look when you have a sec?

2024-10-22 10:25 UTC, eliykat approved these changes

2024-10-22 12:46 UTC, merged