[PM-12345] Add type settings for inline autofill menu
bitwarden/clients pull request #11260
Opened 2024-09-26 19:54 UTC by jprusik

## 🎟️ Tracking

PM-12345

## 📔 Objective

Provide users a way to turn off the inline autofill menu for specific cipher types

## 📸 Screenshots

| Before | After |
| --- | --- |
| ![before](https://github.com/user-attachments/assets/bd878113-7b62-417d-8d5c-4761d05d20c8) | ![after](https://github.com/user-attachments/assets/becb2fd2-ebf4-472e-a057-88bbb6e26003) |
| ![refresh-before](https://github.com/user-attachments/assets/7245ceca-ca7c-4941-833c-ce50f4fd7b1c) | ![refresh-after](https://github.com/user-attachments/assets/e72087f5-040c-4f66-a434-f701cf804c7f) |

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-27 15:29 UTC, danielleflinn approved these changes

2024-09-27 16:23 UTC, cagonzalezcs requested changes

2024-09-27 16:23 UTC, cagonzalezcs commented on apps/browser/src/autofill/services/autofill-overlay-content.service.ts
> +    }
❗ - We have a bit of an issue with how these settings are being referenced/stored.

If we cache these values, and a user changes the setting for showing inline menu cards/identities within their extension, we still retain the presentation of identities/cards on all fields until they refresh the page.

As a result of how we handle binding event listeners on each field, I think we're kind of forced to do a rebuild of the content script logic for each opened tab when the settings change. We do this for changes that happen to the inline menu visibility setting... and likely we need to do the same for these other settings. 

Look at the implementation of `AutofillService.handleInlineMenuVisibilityChange` to see what we're doing when that setting is modified. Something similar needs to exist for the two now settings... either that, or we need to incorporate some extended logic to unset the listeners of identity or card fields separately (and reset the `showAccountCreation` element for login fields)

2024-10-02 20:25 UTC, jprusik commented
Ah missed test updates; feel free to hold off on re-review for the moment

2024-10-02 20:46 UTC, jprusik commented on apps/browser/src/autofill/services/autofill-overlay-content.service.ts
> +    }
addressed in 646319105fb2e434aa29d455003d201e94577459

2024-10-03 09:42 UTC, cagonzalezcs commented on apps/browser/src/autofill/services/autofill.service.ts
> +    );
⚠️ - This effectively is undone/ignored by the following `this.reloadAutofillScripts` call. 

Since we're triggering a reload of the content scripts after this, we are in effect trigger a re-init of the entirety of the autofill content script behavior. Updating the setting with a message is a throwaway action as a result of that re-init. 

The reason why I originally set up the `updateAutofillInlineMenuVisibility` message was to avoid doing this expensive re-load of the scripts. In the current implementation, the inline menu visibility setting is referenced when the menu is opened... the update to that reference should only occur when we need to identify if we want to open the whole menu or just the button on focus.

If the setting is going from and disabled to enabled state (or vice versa), we are forced to trigger a re-injection of the scripts since we load different scripts depending on the visibility setting... otherwise we can just update that content script ref. 

Now that said, I think the right call here is to remove the `updateAutofillInlineMenuVisibility` message when changing the identity or credit card inline menu settings and just trigger a reload of the script in either regard. The reason we'd want to do that is to ensure we reset the listeners present on all fields. We could implement the reset ourselves in a more optimal manner... but given that these settings aren't likely to be changed often, I think it's fine for us to reload the scripts entirely.

2024-10-03 09:42 UTC, cagonzalezcs commented on apps/browser/src/autofill/services/autofill.service.ts
> +    );
```suggestion
```

Suggestion, remove this entirely

2024-10-03 09:42 UTC, cagonzalezcs commented on apps/browser/src/autofill/services/autofill.service.ts
> +      }
```suggestion
    const inlineMenuPreviouslyDisabled = previousSetting === AutofillOverlayVisibility.Off;
    const inlineMenuCurrentlyDisabled = currentSetting === AutofillOverlayVisibility.Off;
    if (!inlineMenuPreviouslyDisabled && !inlineMenuCurrentlyDisabled) {
      const tabs = await BrowserApi.tabsQuery({});
      tabs.forEach((tab) =>
        BrowserApi.tabSendMessageData(tab, "updateAutofillInlineMenuVisibility", {
          inlineMenuVisibility: currentSetting,
        }),
      );
      return;
```

Suggestion - revert this logic, only triggering an update when the actual inline menu visibility is modified.

2024-10-03 09:42 UTC, cagonzalezcs commented on apps/browser/src/autofill/services/autofill.service.ts
> +    cipherType?: CipherType,
```suggestion
```

Suggestion - Remove this, it likely isn't necessary

2024-10-03 09:42 UTC, cagonzalezcs commented on apps/browser/src/autofill/services/autofill.service.ts
> +          CipherType.Identity,
```suggestion
```

Suggestion - Remove this

2024-10-03 09:42 UTC, cagonzalezcs commented on apps/browser/src/autofill/services/autofill.service.ts
> +          CipherType.Card,
```suggestion
```

Suggestion - Remove this

2024-10-03 09:42 UTC, cagonzalezcs commented on apps/browser/src/autofill/services/autofill-overlay-content.service.ts
> +      }
```suggestion
    if (!isNaN(data?.inlineMenuVisibility)) {
      this.inlineMenuVisibility = data.inlineMenuVisibility;
```

Suggestion - Revert this, in effect the script reload that is happening when the inline menu cards and inline menu identities setting is changed will handle the expected change to happen on the content script side.

2024-10-03 09:42 UTC, cagonzalezcs commented on apps/browser/src/autofill/content/abstractions/autofill-init.ts
> +    newSettingValue?: InlineMenuVisibilitySetting | boolean;
```suggestion
    inlineMenuVisibility?: InlineMenuVisibilitySetting;
```

Suggestion - Revert this

2024-10-03 15:53 UTC, jprusik commented on apps/browser/src/autofill/content/abstractions/autofill-init.ts
> +    newSettingValue?: InlineMenuVisibilitySetting | boolean;
4a355b2f085c0e2db21a4286a45218b192239fab

2024-10-03 15:53 UTC, jprusik commented on apps/browser/src/autofill/services/autofill-overlay-content.service.ts
> +      }
4a355b2f085c0e2db21a4286a45218b192239fab

2024-10-03 15:53 UTC, jprusik commented on apps/browser/src/autofill/services/autofill.service.ts
> +          CipherType.Card,
4a355b2f085c0e2db21a4286a45218b192239fab

2024-10-03 15:53 UTC, jprusik commented on apps/browser/src/autofill/services/autofill.service.ts
> +          CipherType.Identity,
4a355b2f085c0e2db21a4286a45218b192239fab

2024-10-03 15:53 UTC, jprusik commented on apps/browser/src/autofill/services/autofill.service.ts
> +    cipherType?: CipherType,
4a355b2f085c0e2db21a4286a45218b192239fab

2024-10-03 15:53 UTC, jprusik commented on apps/browser/src/autofill/services/autofill.service.ts
> +      }
4a355b2f085c0e2db21a4286a45218b192239fab

2024-10-03 15:53 UTC, jprusik commented on apps/browser/src/autofill/services/autofill.service.ts
> +    );
4a355b2f085c0e2db21a4286a45218b192239fab

2024-10-03 15:55 UTC, jprusik commented
BIT run:
https://github.com/bitwarden/browser-interactions-testing/actions/runs/11165365651

2024-10-03 16:24 UTC, cagonzalezcs commented on apps/browser/src/autofill/services/autofill.service.ts
> +      typeof oldSettingValue === "boolean" || typeof oldSettingValue === "boolean";
```suggestion
      typeof oldSettingValue === "boolean" || typeof newSettingValue === "boolean";
```
Typo?

2024-10-03 17:17 UTC, jprusik commented on apps/browser/src/autofill/services/autofill.service.ts
> +      typeof oldSettingValue === "boolean" || typeof oldSettingValue === "boolean";
yes - thanks!

fixed ea58f9e65651843e91ec0522b764b463b037a41b

2024-10-03 17:19 UTC, cagonzalezcs approved these changes

2024-10-11 21:28 UTC, cagonzalezcs approved these changes

2024-10-15 15:07 UTC, merged