Vault/pm 12334
bitwarden/clients pull request #11289
Opened 2024-09-27 13:07 UTC by gbubemismith

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-10-02 16:39 UTC, shane-melton requested changes
Nice work on tackling this! I noticed a few permission issues we'll want to address and had a few other suggestions.

Also, I think we'll need to apply some of this logic to the new browser refresh view like the `view-v2` component which is still only checking `cipher.edit`. I don't know if we need to consider "activeCollections" in the extension refresh though, that may be a question for design/product.

2024-10-02 16:39 UTC, shane-melton commented on libs/common/src/vault/services/cipher-authorization.service.ts
> +          organization?.permissions.editAnyCollection ||
🎨 The `organization` class has a helper/getter named `canEditAllCiphers` that can be used instead for this conditional.

⚠️ `organization.isAdmin` should be avoided when dealing with modifying ciphers as its inherits `true` for provider users who should no longer have edit access to ciphers.

2024-10-02 16:39 UTC, shane-melton commented on libs/common/src/vault/services/cipher-authorization.service.ts
> +                .filter((c) => cipher.collectionIds.includes(c.id))
🎨 We shouldn't need to filter again. The call to `decryptedCollectionViews$(cipher.collectionIds)` is already only returning collections the cipher is assigned to.

2024-10-02 16:39 UTC, shane-melton commented on libs/common/src/vault/services/cipher-authorization.service.ts
> +                if (activeCollection) {
❓ If the active collection is somehow `null` here should we return `false`? My interpretation of the `activeCollectionId` is when passed in I want to check if the user can delete a cipher by only considering the permission of the collection id passed in. In which case, if the cipher is not assigned to that collection, we should return `false`.

2024-10-02 16:39 UTC, shane-melton commented on libs/common/src/vault/services/cipher-authorization.service.ts
👍 It's great to see an implementation of this service! Thanks for getting it off the ground for us!

2024-10-02 16:39 UTC, shane-melton commented on libs/common/src/vault/services/cipher-authorization.service.spec.ts
👍 Love to see tests!!

2024-10-02 16:39 UTC, shane-melton commented on libs/common/src/vault/services/cipher-authorization.service.spec.ts
> +  it("should return true if cipher has no organizationId", (done) => {
🎨 It may be helpful to wrap these all in a `describe("canDeleteCiphers$")` block to better indicate we're testing the `canDeleteCiphers$` observable. I know we only have that one public method at the moment, but I imagine we'll have more in the future.

2024-10-02 16:39 UTC, shane-melton commented on apps/web/src/app/vault/components/vault-items/vault-items.component.ts
> +      cipher.collectionIds.length === 0
⚠️ Unassigned ciphers (`cipher.collectionIds.length === 0`) can only be managed by Admin/Owners. We need to separate this check to when we have an `organization` and can check `canEditUnassignedCiphers`.

2024-10-02 16:39 UTC, shane-melton commented on apps/cli/src/vault/delete.command.ts
> +      this.cipherAuthorizationService.canDeleteCipher$(cipherView),
❓ Do we actually need the `cipherView` to check if we can delete the cipher? I don't think we need any decrypted properties to check its permissions and accepting an encrypted `Cipher` should be okay I think. But maybe, I'm missing something?

2024-10-02 16:39 UTC, shane-melton commented on libs/angular/src/vault/components/add-edit.component.ts
> +  @Input() canDeleteCipher: boolean = false;
⛏️ I think this `canDeleteCipher` input is a unused and can be removed.

2024-10-03 20:17 UTC, gbubemismith commented on apps/cli/src/vault/delete.command.ts
> +      this.cipherAuthorizationService.canDeleteCipher$(cipherView),
We accept cipherView on `canDeleteCipher$ because it is used mainly on the view and edit components that already have cipherView as a field. I think it makes sense to refactor `canDeleteCipher$` to accept organizationId and collectionIds since that's what we need

2024-10-07 08:57 UTC, gbubemismith commented on libs/common/src/vault/services/cipher-authorization.service.ts
> +export abstract class CipherAuthorizationServiceAbstraction {
Fixed here f204d6a3e7eb4f732323f842e4e0adedb8f6c079

2024-10-07 08:58 UTC, gbubemismith commented on libs/common/src/vault/services/cipher-authorization.service.ts
> +          organization?.permissions.editAnyCollection ||
Fixed here f204d6a3e7eb4f732323f842e4e0adedb8f6c079

2024-10-07 08:58 UTC, gbubemismith commented on libs/common/src/vault/services/cipher-authorization.service.ts
> +                .filter((c) => cipher.collectionIds.includes(c.id))
Fixed here f204d6a3e7eb4f732323f842e4e0adedb8f6c079

2024-10-07 08:59 UTC, gbubemismith commented on libs/common/src/vault/services/cipher-authorization.service.spec.ts
> +  it("should return true if cipher has no organizationId", (done) => {
Fixed here 931ccf9be720a6765100e102665b118c61ccc2ee

2024-10-07 09:05 UTC, gbubemismith commented on apps/web/src/app/vault/components/vault-items/vault-items.component.ts
> +      cipher.collectionIds.length === 0
Fixed here aa5bf50c3a6e1af13c099c7385cefda1bdd988e5

2024-10-07 09:06 UTC, gbubemismith commented on apps/cli/src/vault/delete.command.ts
> +      this.cipherAuthorizationService.canDeleteCipher$(cipherView),
Fixed here bdce8ca0557b623db20f98519f7b3d818e00739a

2024-10-07 15:23 UTC, ike-kottlowski approved these changes

2024-10-07 23:06 UTC, shane-melton requested changes
This is looking really good! Just saw one typo and then I had some two thoughts on how we could improve the API for the cipher authorization service. Let me know what you think!

2024-10-07 23:06 UTC, shane-melton commented on libs/common/src/vault/services/cipher-authorization.service.ts
> +}
🎨 💭 Thinking about this API some more and how we might simplify it a bit.

1. I think there is still value in the simplicity of passing in a Cipher-like object instead of `orgId` and `collectionIds` separately. By having them separate we're forcing the user to deconstruct the object in every calling location and trusting that they're passing the correct organization and collectionIds.

   I know we separated them to allow us to use both encrypted and decrypted cipher objects. But, we could achieve the same by introducing a `type CipherLike = Cipher | CipherView;` This would allow users of the service to pass in both encrypted `Cipher` and decrypted `CipherView` objects.

2. `activeCollectionId` is very use case specific and requires users of the service to know what "active" means in order to discern what its used for. Something like `collectionsToConsider`, `targetCollections`, or `allowedCollections` could be a more generic alternative that also better informs the purpose of argument. 

   As for making it an array, I don't really mind either way. But it would allow us to do something like for the implementation:

```ts
const collections = targetCollections 
? allCollections.filter(c => targetCollections.contains(c.id)) 
: allCollections;

return allCollections.some(c => c.manage);
```

What do you think of those two ideas/thoughts?

2024-10-08 07:56 UTC, gbubemismith commented on libs/common/src/vault/services/cipher-authorization.service.ts
> +}
👍🏼 Nice I like this approach

2024-10-08 19:33 UTC, ike-kottlowski submitted a review, later dismissed

2024-10-08 20:05 UTC, shane-melton requested changes

2024-10-08 20:05 UTC, shane-melton commented on libs/vault/src/cipher-form/abstractions/cipher-form-config.service.ts
> +  activeCollectionId?: CollectionId;
🎨 I missed this on the first pass, but can we move this to the `VaultItemDialogParams` instead of the cipher form config and config service? The cipher form doesn't use it anywhere, and its only applicable to the `VaultItemDialogComponent`.

2024-10-08 21:11 UTC, shane-melton commented on libs/common/src/vault/services/cipher-authorization.service.ts
> +          return of(organization?.canEditUnmanagedCollections === true);
@gbubemismith We still need to update this

2024-10-08 21:15 UTC, gbubemismith commented on libs/common/src/vault/services/cipher-authorization.service.ts
> +          return of(organization?.canEditUnmanagedCollections === true);
@shane-melton, this was addressed here b5f970d1e5c52e3f460b67cbcd14446e9307cb1e

2024-10-08 21:16 UTC, shane-melton commented on libs/common/src/vault/services/cipher-authorization.service.ts
> +          return of(organization?.canEditUnmanagedCollections === true);
🤦 Thanks, ended up clicking an outdated link.

2024-10-08 21:17 UTC, shane-melton submitted a review, later dismissed
Looks good, nice work!

2024-10-08 21:27 UTC, ike-kottlowski approved these changes

2024-10-14 16:40 UTC, shane-melton approved these changes

2024-10-14 17:40 UTC, shane-melton approved these changes

2024-10-14 17:58 UTC, ike-kottlowski approved these changes

2024-10-16 15:49 UTC, shane-melton approved these changes

2024-10-16 18:45 UTC, ike-kottlowski approved these changes

2024-10-22 13:15 UTC, merged