[PM-12721] - add copy button to send options password field
bitwarden/clients pull request #11295
Opened 2024-09-27 17:30 UTC by jaasen-livefront

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-12721

## 📔 Objective

This PR adds a copy button to the send options password field

## 📸 Screenshots

![Screenshot 2024-09-27 at 10 29 38 AM](https://github.com/user-attachments/assets/950085d5-e5d9-44a4-a98f-cfd94eadc637)

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-27 17:38 UTC, djsmith85 requested changes

2024-09-27 17:38 UTC, djsmith85 commented on libs/tools/send/send-ui/src/send-form/components/options/send-options.component.html
> +        [appA11yTitle]="'copyValue' | i18n"
⚠️ Should be specific to copying a password

2024-09-27 17:58 UTC, djsmith85 requested changes

2024-09-27 17:58 UTC, djsmith85 commented on libs/tools/send/send-ui/src/send-form/components/options/send-options.component.html
> +        [appA11yTitle]="'passwordCopied' | i18n"
This would only be used once a password has been copied. There should be a "copy password" within en/messages.json

2024-09-27 18:12 UTC, jaasen-livefront commented on libs/tools/send/send-ui/src/send-form/components/options/send-options.component.html
> +        [appA11yTitle]="'passwordCopied' | i18n"
🤦 

Fixed now.

2024-09-30 11:56 UTC, djsmith85 approved these changes

2024-09-30 11:56 UTC, merged