[PM-12774] - don't display filters when no sends are available
bitwarden/clients pull request #11298
Opened 2024-09-27 19:29 UTC by jaasen-livefront

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-12774

## 📔 Objective

This PR fixes an issue where the send filters were displayed when active sends were present.

## 📸 Screenshots

![Screenshot 2024-09-27 at 12 24 55 PM](https://github.com/user-attachments/assets/19b81b36-5d2d-4ec5-beb2-13be987f87d8)

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-30 19:43 UTC, djsmith85 requested changes

2024-09-30 19:43 UTC, djsmith85 commented on apps/browser/src/tools/popup/send-v2/send-v2.component.html
> +  <div slot="above-scroll-area" class="tw-p-4" *ngIf="!sendsDisabled && (sends$ | async).length">
The `above-scroll-area` should always be shown and hiding it with !sendDisabled would also remove the callout.

How about removing this change and instead replace the `*ngIf="!sendsDisabled"` on line 13 with `*ngIf="listState !== sendState.Empty"` 

The search and filters would always be hidden when no items are there. If a user had existing Sends before the DisableSend-policy got enabled, then I'd expect them to also be able to search and filter on existing Sends.

2024-09-30 21:56 UTC, jaasen-livefront commented on apps/browser/src/tools/popup/send-v2/send-v2.component.html
> +  <div slot="above-scroll-area" class="tw-p-4" *ngIf="!sendsDisabled && (sends$ | async).length">
@djsmith85 That makes sense. The reason I moved the logic up to the above-scroll-area was to avoid rendering it to avoid the extra top padding which slightly misaligns the empty state content. I'll instead use a conditional class.

2024-10-01 10:02 UTC, djsmith85 requested changes

2024-10-01 10:02 UTC, djsmith85 commented on apps/browser/src/tools/popup/send-v2/send-v2.component.html
> +  <div slot="above-scroll-area" [ngClass]="{ 'tw-p-4': (sends$ | async)?.length }">
Testing with the solution below and my other suggestion I haven't experienced any issues with added padding or mis-rendering.

```suggestion
  <div slot="above-scroll-area" class="tw-p-4">
```

2024-10-01 10:02 UTC, djsmith85 commented on apps/browser/src/tools/popup/send-v2/send-v2.component.html
> +    <ng-container *ngIf="!sendsDisabled && (sends$ | async)?.length">
As mentioned before I'd expect as a user with Sends created before the policy is enabled to be able to filter and sort their existing Sends, even if they can only view and delete them.

If you remove the `!sendsDisabled` you'll notice that relying on `sends$` doesn't work well, as it is also used to show filtered results. This then completely removes the search and filter capabilities. That why I suggest:
```suggestion
    <ng-container *ngIf="listState !== sendState.Empty">
```

2024-10-01 18:46 UTC, djsmith85 approved these changes

2024-10-01 18:46 UTC, merged