Add Web Push Support
bitwarden/clients pull request #11346
Opened 2024-10-01 18:44 UTC by justindbaur

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-10-16 23:04 UTC, MGibson1 requested changes

2024-10-16 23:04 UTC, MGibson1 commented on libs/common/src/platform/notifications/internal/signalr-connection.service.ts
> +      const sheduleReconnect = (): Subscription => {
```suggestion
      const scheduleReconnect = (): Subscription => {
```

please check cspell for others I may have missed

2024-10-16 23:04 UTC, MGibson1 commented on libs/common/src/platform/notifications/internal/signalr-connection.service.ts
> +              reconnectSubscription = sheduleReconnect();
```suggestion
              reconnectSubscription = scheduleReconnect();
```

2024-10-16 23:04 UTC, MGibson1 commented on libs/common/src/platform/notifications/internal/signalr-connection.service.ts
> +        reconnectSubscription = sheduleReconnect();
```suggestion
        reconnectSubscription = scheduleReconnect();
```

2024-10-16 23:04 UTC, MGibson1 commented on libs/common/src/platform/notifications/internal/signalr-connection.service.ts
> +        reconnectSubscription = sheduleReconnect();
```suggestion
        reconnectSubscription = scheduleReconnect();
```

2024-10-17 13:48 UTC, justindbaur commented on libs/common/src/platform/notifications/internal/default-notifications.service.ts
> +            }
_Mostly_, to do any sort of `reconnect` or `updateConnection` you do have to be authed and unlocked. But technically the very first connect does NOT enforce that. So if your application called `init` while you were locked you can connect. I'm happy to change it because receiving logout events is very useful but I do believe there are some preliminary changes to make the access token be stored encrypted by the user key which would make it unattainable unless you are unlocked.

https://github.com/bitwarden/clients/blob/073ee4739b0844c9558be7dc45f202bb3bd0a850/libs/common/src/services/notifications.service.ts#L223-L251

2024-10-22 17:34 UTC, justindbaur commented on libs/common/src/platform/notifications/notifications.service.ts
> +  abstract disconnectFromInactivity(): void;
I do too, I wanted to yank them out alongside the `updateConnection` method but didn't want to expand the scope that much. 

I envision there would probably be a `ActivityService` with `activity$` and that could be part of the chain instead of it tracking it's own `BehaviorSubject`. Then as you say, we could move it into just the SignalR code so that web push would be allowed to stay connected when there isn't activity.

2024-10-23 19:44 UTC, justindbaur commented on libs/common/src/platform/notifications/internal/worker-webpush-connection.service.ts
> +          return of(subscription);
I went with 3 for now, I can simplify it a whole lot by just doing all of it in a single `defer`, it does make it much simpler. Regarding 1 though, I think this will already reuse the same subscription. I intentionally left out any eager `unsubscribe` and non-active user notifications are filtered out in notifications service.

2024-10-24 13:41 UTC, justindbaur commented on libs/common/src/platform/notifications/internal/worker-webpush-connection.service.ts
> +        }
Very good call, we now capture all the information we might need from the `supportStatus$` method and it becomes encapsulated in the returned service.

2024-10-24 17:28 UTC, justindbaur commented on libs/common/spec/matrix.ts
I added some more documentation to the method but here is a snippet from it:

```ts
interface MyService {
  event$(userId: UserId) => Observable<UserEvent>
}

// Test
const myService = mock<MyService>();
const eventGetter = Matrix.autoMockMethod(myService.event$, (userId) => BehaviorSubject<UserEvent>());

eventGetter("userOne").next(new UserEvent());
eventGetter("userTwo").next(new UserEvent());
```

This replaces a more manual way of doing things like:

```ts
const myService = mock<MyService>();
const userOneSubject = new BehaviorSubject<UserEvent>();
const userTwoSubject = new BehaviorSubject<UserEvent>();
myService.event$.mockImplementation((userId) => {
   if (userId === "userOne") {
     return userOneSubject;
   } else if (userId === "userTwo") {
     return userTwoSubject;
   }
   return new BehaviorSubject<UserEvent>();
});

userOneSubject.next(new UserEvent());
userTwoSubject.next(new UserEvent());
```

Basically so I can easily emit values for different users easily in tests.

2024-10-29 22:37 UTC, MGibson1 commented on libs/common/spec/matrix.ts
I see, the problem it's solving is that the pattern we're using of parametrized observables is pretty wordy to set up.

2024-10-29 22:49 UTC, MGibson1 commented on libs/common/spec/matrix.ts
> + */
```suggestion
/**
 * A Matrix is an arbitrarily deep and broad map of constant values to a given cached value. It is intended to manage cached values for a set of method arguments.
 */
```

2024-10-29 23:15 UTC, MGibson1 submitted a review, later dismissed

2024-10-29 23:15 UTC, MGibson1 commented on libs/common/src/platform/notifications/internal/worker-webpush-connection.service.ts
> +    // Do connection
Looks like the same FIXME is required, though. There is no guarantee that the server config retrieved is the same as that given requested for the given userId.

For now, this _probably_ isn't a bug since we _should_ only look for the support status of active accounts, but that is definitely a bug-in-waiting.

2024-10-29 23:15 UTC, MGibson1 commented on libs/common/src/platform/notifications/internal/worker-webpush-connection.service.ts
> +    // Do connection
oops, just saw you did add a fixme there in a later commit. Seems like the best we can do for now 👍

2024-10-29 23:15 UTC, MGibson1 commented on libs/common/src/platform/notifications/internal/worker-webpush-connection.service.ts
> +          return of(subscription);
Not sure where I was coming from with 1, I'm pretty sure I tried to create multiple subscriptions and you can't. Worth double checking, but you're probably right we need to update existing subscriptions, which means rethinking our tags.

2024-10-30 15:34 UTC, JaredSnider-Bitwarden commented on libs/common/src/platform/notifications/internal/default-notifications.service.ts
> +            }
@MGibson1 , the idea to encrypt the access token with the user key was born out of a mistaken assumption about when the access token was cleared in web in prod. We are proceeding with the web process reload ticket https://github.com/bitwarden/clients/pull/11781 without worrying about encrypting the access token at this time.

2024-10-30 18:41 UTC, justindbaur commented on libs/common/src/platform/notifications/internal/index.ts
It _was_ working: https://github.com/bitwarden/clients/blob/18f7d64a6d34e940445ffb37f70759a20548e434/.eslintrc.json#L331-L346

I should just be able to add `**/platform/notifications/**` but it's not working now and I don't want to add it now in case it spontaneously starts working again.

2024-10-31 13:08 UTC, coroiu reviewed
I assume Matt already went through the web push technology-specific parts so I just looked at the more general integration code and added some suggestions :)

2024-10-31 13:08 UTC, coroiu commented on libs/common/src/platform/notifications/internal/default-notifications.service.ts
> +      });
question: this is gonna shut down the notifications completely, is that ok? Or do we want to retry later? Maybe we retry somewhere else?

2024-11-20 21:14 UTC, justindbaur commented on libs/common/src/platform/notifications/internal/default-notifications.service.ts
> +      });
I'm alright with this, all the known possible errors (the ones in SignalR) are already managed more locally. If there are other, unknown, problems I would rather it actually fail, hopefully prompting a bug report that we can look at and fix the issue.

2024-11-20 21:24 UTC, justindbaur commented on libs/common/src/platform/notifications/internal/default-notifications.service.ts
> +        if (notificationsUrl === "http://-") {
Yep! 37e2eff7244de17f8b8bb8ebdbaa2c13ea36554a

2024-11-20 21:26 UTC, justindbaur commented on libs/common/src/platform/notifications/internal/default-notifications.service.spec.ts
> +  });
I made these tests:
- `does not re-connect when the user transitions from locked to unlocked doesn't reconnect`
- `connects when a user transitions from logged out to [Unlocked|Locked]`

We specifically don't want it to reconnect when they simply go from locked to unlocked since both statuses should have access to the access token.

2024-11-20 21:27 UTC, justindbaur commented on libs/common/src/platform/notifications/internal/default-notifications.service.spec.ts
> +    // falling back to using SignalR
Added these in some form or fashion in: ac47da4ee0119413fa75107e55e21665ab9df51b

Let me know how I did!

2024-11-21 10:38 UTC, coroiu commented on libs/common/src/platform/notifications/internal/default-notifications.service.ts
> +  }
> For example, webPushConnectionService.supportStatus$ bases itself on config and that could cause more calls to /config than our application actually needs.

Ideally we should have protections in place for this at the source (which I think we do), I don't think its fair to be putting that kind of burden on the subscriber. We have a very intricate webs of observables and can't expect every subscriber to keep track of exactly how each observable works and what consequences it causes. I think we have to keep readability in mind.

Also, keep in mind that "only subscribing when necessary" i.e. not using `combineLatest` will generate a lot of unsubscription/re-subscription events, potentially thwarting any caching mechanisms that might exist in the upstream observables.

That said, I don't think "if I don't need it, I shouldn't subscribe to it" is a bad principle, and I think the way you split it up into multiple functions really improved readability!

But you did get me curious about whether I could modify my original suggestion to avoid unnecessary subscriptions so I decided to play around with it a little bit. Not sure if it's better, but this is what I came up with

```ts
  private connectUser$(userId: UserId) {
    return this.environmentService.environment$.pipe(
      switchMap((environment) => {
        const notificationsUrl = environment.getNotificationsUrl();
        if (notificationsUrl === DISABLED_NOTIFICATIONS_URL) {
          return EMPTY;
        }
        return of(notificationsUrl);
      }),
      withLatestFrom(this.authService.authStatusFor$(userId)),
      switchMap(([notificationsUrl, authStatus]) => {
        if (
          authStatus !== AuthenticationStatus.Locked &&
          authStatus !== AuthenticationStatus.Unlocked
        ) {
          return EMPTY;
        }
        return of(notificationsUrl);
      }),
      withLatestFrom(this.activitySubject),
      switchMap(([notificationsUrl, activityStatus]) => {
        if (activityStatus === "inactive") {
          return EMPTY;
        }
        return of(notificationsUrl);
      }),
      withLatestFrom(this.webPushConnectionService.supportStatus$(userId)),
      switchMap(([notificationsUrl, webPushSupport]) => {
        if (webPushSupport.type === "supported") {
          return webPushSupport.service.notifications$.pipe(map((n) => [n, userId] as const));
        }
        return this.signalRConnectionService.connect$(userId, notificationsUrl).pipe(
          filter((n) => n.type === "ReceiveMessage"),
          map((n) => [n.message, userId] as const),
        );
      }),
    );
  }
```

2024-11-21 12:43 UTC, coroiu commented on libs/common/src/platform/notifications/internal/default-notifications.service.spec.ts
> +    // falling back to using SignalR
Looking good!

2024-11-21 12:45 UTC, coroiu submitted a review, later dismissed
Everything addressed 👍

2024-11-21 12:45 UTC, coroiu commented on libs/common/src/platform/notifications/internal/default-notifications.service.spec.ts
> +  it("does not re-connect when the user transitions from locked to unlocked doesn't reconnect", async () => {
typo?
```suggestion
  it("does not re-connect when the user transitions from locked to unlocked", async () => {
```

2024-11-21 18:14 UTC, justindbaur commented on libs/common/src/platform/notifications/internal/default-notifications.service.spec.ts
> +  it("does not re-connect when the user transitions from locked to unlocked doesn't reconnect", async () => {
Yes, fixed as part of 98076cfc97b48057145d2f27522f631369c9fcdc when I added more cases for this test.

2024-11-21 18:16 UTC, justindbaur commented on libs/common/src/platform/notifications/internal/default-notifications.service.ts
> +  }
I noticed that I think most of the ugliness comes from retrieving the `notificationsUrl` pretty early on and then having to keep it around until it is finally needed as part of the SignalR connection. I ended up making a method to just take it as a parameter and then it's just captured there once. The rest of the observable can be kept pretty darn flat. I think it's the best version yet.

2024-11-22 07:27 UTC, coroiu approved these changes

2024-11-22 07:27 UTC, coroiu commented on libs/common/src/platform/notifications/internal/default-notifications.service.spec.ts
> +    subscription.unsubscribe();
thought: If we get issues with people making changes to this file and forgets these unsubscribes we could look into cleaning in `afterEach` or `beforeEach`

2024-11-22 07:27 UTC, coroiu commented on libs/common/src/platform/notifications/internal/default-notifications.service.ts
> +  }
Oh yeah good point, looks a little like a combination of your separate function solution combined with my previous suggestion but cleaner without `withLatestFrom`, nice 👍

2024-12-02 23:05 UTC, JaredSnider-Bitwarden reviewed
A few tiny questions (per discussion, I'm not actually a required reviewer):

2025-01-24 08:31 UTC, coroiu approved these changes
GitHub is showing me the entire merge from main as a change from my latest review so I ended up reviewing each commit by itself. Gave me a lol when I found the small adventure you had with `webNavigation`:D 

Sorry for the delay in reviewing this, approved with just a question!

2025-01-24 08:31 UTC, coroiu commented on libs/common/src/platform/notifications/internal/worker-webpush-connection.service.ts
> +          }
question: couldn't we fix this by changing how `getOrCreateSubscription$` works?

2025-01-29 13:39 UTC, justindbaur commented on libs/common/src/platform/notifications/internal/worker-webpush-connection.service.ts
> +          }
I'm happy with the rarity of when we would get `null` here. We should only get it from a `pushsubscriptionchange` event that has a `null` `newSubscription` property. Which according to the docs the only example of when that would happen is when the user removes the permission (which isn't possible in browser). That would lead to an error and us falling back to SignalR which I think is the right move here.

2025-01-29 13:49 UTC, merged