[PM-1992] in ac add current collection actions in menu
bitwarden/clients pull request #11364
Opened 2024-10-02 17:31 UTC by cd-bitwarden

## 🎟️ Tracking

[
](https://bitwarden.atlassian.net/browse/PM-1992)
## 📔 Objective

Removing code thats not longer needed in admin console for collections modal, and deprecating the component for collections that we no longer want to use.

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-10-02 18:09 UTC, shane-melton requested changes
I think we can actually completely remove both the `CollectionsComponents` in the Web  project since they're no longer in use anywhere in the Web code base. 

For refernce:
`apps/web/src/app/vault/individual-vault/collections.component.ts`
`apps/web/src/app/vault/org-vault/collections.component.ts`

2024-10-02 18:09 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/collections.component.ts
🎨 Since this isn't used anywhere at this point, we can actually just delete it entirely! Apologies for misleading you with `@deprecated`, I thought it may have still been in use.

2024-10-02 19:48 UTC, shane-melton submitted a review, later dismissed
🎉 Looks great!

2024-10-07 06:55 UTC, coroiu approved these changes

2024-10-24 18:13 UTC, shane-melton approved these changes

2024-10-25 17:43 UTC, justindbaur approved these changes

2024-10-25 18:19 UTC, merged