[PM-11162] Assign To Collections Permission Update
bitwarden/clients pull request #11367
Opened 2024-10-02 18:52 UTC by Jingo88

## 🎟️ Tracking

[PM-11162](https://bitwarden.atlassian.net/browse/PM-11162)

## 📔 Objective

Only users with `Can Edit` permissions will be allowed to `Assign To Collections`. If the user has `Can Edit Except Password` they should not see `Assign To Collections` in the menu of the item row. 

## 📸 Screen Recording

https://github.com/user-attachments/assets/48a30f9d-6d1b-43ff-afa4-9e03b820b60d

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-10-02 20:03 UTC, shane-melton requested changes
The change to `vault-items` looks good!

However, we need to make a similar change to the `item-details-section.component` for the new CipherForm. It also allows users to modify a cipher's collections without the "Assign To Collections" dialog so we need to adjust that component to disable the collections control when `!cipher.viewPassword`

2024-10-07 22:11 UTC, shane-melton requested changes

2024-10-07 22:11 UTC, shane-melton commented on libs/vault/src/cipher-form/components/item-details/item-details-section.component.ts
> +      this.showCollectionsControl = true;
⚠️ We only want to disable the collection control when they don't have access to assign to other collections. Disabling allows the user to still see what its assigned to, otherwise there is no way to view that information.

2024-10-07 22:11 UTC, shane-melton commented on libs/vault/src/cipher-form/components/item-details/item-details-section.component.ts
🎨 I think we can put a check in the `initFromExistingCipher` method after the call to `updateCollectionOptions()` to check if `originalCipher.edit && originalCipher.viewPassword`. If that is `false` then we should call `this.itemDetailsForm.controls.collectionIds.disable()` which will prevent the user from changing the value.

Then we wouldn't need to modify the `updateCollectionOptions()` method.

2024-10-07 22:11 UTC, shane-melton commented on apps/web/src/app/vault/components/vault-items/vault-items.component.ts
> +    return (
💭  I noticed this returned value is used by the `vault-cipher-row.component` to show the attachments button. I don't think we want to disable that with when `viewPassword == false` so we may need to introduce a new option specifically for assigning collections (e.g. `canAssignCollections`)

2024-10-16 04:55 UTC, eliykat requested changes

2024-10-16 04:55 UTC, eliykat commented on libs/angular/src/admin-console/components/collections.component.ts
> +    this.organizationService.get$(cipher.organizationId).subscribe((org) => {
This observable is not unsubscribed.

2024-10-16 04:55 UTC, eliykat commented on libs/angular/src/admin-console/components/collections.component.ts
> +      this.canAssignCollections = true;
I don't follow this - if the cipher isn't in an organization, you can't assign it to a collection.

2024-10-16 04:55 UTC, eliykat commented on libs/angular/src/admin-console/components/collections.component.ts
@shane-melton this is the file that tagged me for a review, but I think this would fall under Vault ownership under the team boundaries we discussed. Do you agree? If so I can just rubber stamp this review once Vault have approved, but if you could then move it into Vault ownership that would be really helpful.

Also, I was trying to figure out how this is used. I found it in `desktop`, but there's also a subclass in `web` which appears unused: https://github.com/bitwarden/clients/blob/main/apps/web/src/app/vault/individual-vault/collections.component.ts#L1.

2024-10-16 04:55 UTC, eliykat commented on libs/angular/src/admin-console/components/collections.component.ts
> +      this.canAssignCollections = org.canEditAllCiphers || (cipher.edit && cipher.viewPassword);
`org.canEditAllCiphers` checks admin permissions. Do we allow admin permissions from the individual vault on desktop? I thought we only allowed that from Admin Console, regardless of client.

2024-10-16 04:56 UTC, eliykat commented on libs/angular/src/admin-console/components/collections.component.ts
> +      this.canAssignCollections = org.canEditAllCiphers || (cipher.edit && cipher.viewPassword);
Also, `cipherView.canAssignToCollection => cipher.edit && cipher.viewPassword` might be a useful abstraction, but I'll leave that up to Vault.

2024-10-18 20:51 UTC, shane-melton commented on libs/angular/src/admin-console/components/collections.component.ts
Agreed, this should be under our ownership now as it deals with assigning an item to a collection. We can get it moved over after this PR.

And yes, its been replaced with the new `AssignCollections` component in Web/Browser and is already under our ownership there. We just need to keep this one around for a bit longer until we can update Desktop as well.

2024-10-22 14:59 UTC, shane-melton submitted a review, later dismissed
Looks good to go! There do seem to be a couple merge conflicts though

2024-10-22 23:36 UTC, shane-melton submitted a review, later dismissed

2024-10-23 01:15 UTC, eliykat submitted a review, later dismissed
This no longer impacts AC Team owned code and my main concern about the not-unsubscribed observable has been addressed.

2024-10-29 00:00 UTC, eliykat submitted a review, later dismissed

2024-10-31 23:52 UTC, eliykat submitted a review, later dismissed

2024-11-05 17:51 UTC, shane-melton commented on libs/vault/src/components/assign-collections.component.ts
> +        this.toastService.showToast({
🎨 We should try and detect the lack of edit permission before making the request. If the API fails for some other reason (say its down or slow to respond) the user will get a confusing message about not having edit permissions when they may actually have. 

Ultimately, I think we want to avoid putting logic in place that depends on getting an error response from our API.

2024-11-05 17:54 UTC, shane-melton commented on apps/cli/src/commands/edit.command.ts
> +      if (e.message === "Resource not found.") {
🎨 Similarly, I would think we should prevent them from sending the request by checking for ViewPassword instead of relying on an error response from the server.

2024-11-06 18:18 UTC, Jingo88 commented on libs/vault/src/components/assign-collections.component.ts
> +        this.toastService.showToast({
Yeah that's fair. I just removed this. With the new code the user will not be able to view any `Assign` options if they do not have `manage` or `edit` access

2024-11-06 18:18 UTC, Jingo88 commented on apps/cli/src/commands/edit.command.ts
> +      if (e.message === "Resource not found.") {
Moved `viewPassword` logic check above. This works now because of our changes in the associated server PR

2024-11-06 18:24 UTC, shane-melton submitted a review, later dismissed

2024-11-07 00:38 UTC, eliykat reviewed
This no longer affects any AC Team owned files, no approval needed from me 👍

2024-11-11 17:47 UTC, shane-melton commented on libs/admin-console/src/common/collections/models/collection.view.ts
> +  canEditItems(org: Organization, excludeHidePassword = true): boolean {
🎨 I feel like we may have a mismatch of double negatives here that's making this a bit confusing. How do you feel about renaming the arg to something like `editPasswords = true` and tweaking the extra conditional to be 
```ts
(this.assigned && !this.readOnly && (!editPasswords || !this.hidePassword))
```

Also, we're changing the default behavior of this method by defaulting it to `true` so we need to make sure any existing calling locations are prepared for that change. (fortunately I think its only 1 spot in the org vault template `vault.component.html`.

2024-11-11 22:00 UTC, shane-melton commented on libs/admin-console/src/common/collections/models/collection.view.ts
>    // Applying excludeHidePassword false will remove collections with Can Edit Except Password Permissions
⛏️ Comment is outdated

2024-11-12 15:24 UTC, shane-melton approved these changes

2024-12-04 17:31 UTC, shane-melton submitted a review, later dismissed
Latest changes look good! (Only one minor non-blocking nit)

2024-12-04 17:31 UTC, shane-melton commented on libs/vault/src/cipher-form/components/cipher-form.component.ts
> +    private organizationService: OrganizationService,
⛏️ (non-blocking): I think this is unused now and can be removed.

2024-12-10 19:47 UTC, shane-melton approved these changes

2025-01-07 19:36 UTC, Jingo88 commented
After speaking with product and design we have decided to move away from hiding `Can Edit Except Passwords` collections from the dropdown. 

If an item belongs to only a `Can Edit Except Passwords` collection, the user will not see the `Assign to Collections` action in the item row menu, and the collections dropdown will be disabled

If an item belongs to multiple collections with a higher permission (e.g. item is in `Can Edit Except Password` and `Can Manage`) the user will see the `Assign to Collections` action, and the collections dropdown in the edit modal will show all available collections

Will provide updated description and screen recordings.

2025-01-08 22:15 UTC, cd-bitwarden submitted a review, later dismissed
These changes look good to me 👍

2025-01-09 00:01 UTC, shane-melton approved these changes

2025-01-15 08:08 UTC, eliykat reviewed
A few questions/suggestions but they are non-blocking as I am no longer a codeowner in this review.

2025-01-15 08:08 UTC, eliykat commented on apps/web/src/app/vault/components/vault-items/vault-items.component.ts
> +    }
Suggestion: this could be moved to inside the `cipher.canAssignToCollections` getter.

2025-01-15 08:08 UTC, eliykat commented on libs/vault/src/cipher-form/components/item-details/item-details-section.component.ts
> +      !(this.originalCipherView?.edit && this.originalCipherView?.viewPassword)
Shouldn't this be using the `canAssignToCollections` getter?

2025-01-15 18:16 UTC, Jingo88 commented on apps/web/src/app/vault/components/vault-items/vault-cipher-row.component.ts
> +    return this.organization.canEditAllCiphers || (this.cipher.edit && this.cipher.viewPassword);
Good call. The checkbox will still show in PM but not for AC. If a user uses the checkbox for bulk updates the actions allowed will be based by the lowest permissions. (e.g. if a user selects a `Edit except PW`, and a `Manage`) only `Add to folders` will show

2025-01-15 19:00 UTC, cd-bitwarden submitted a review, later dismissed
Looks good

2025-01-16 05:04 UTC, eliykat commented on apps/web/src/app/vault/components/vault-items/vault-cipher-row.component.ts
> +    return this.organization.canEditAllCiphers || (this.cipher.edit && this.cipher.viewPassword);
I was mixing up bulk actions and the per-row menu. Looking at it again I agree this should be fine.

2025-01-16 05:04 UTC, eliykat approved these changes

2025-01-17 15:41 UTC, cd-bitwarden submitted a review, later dismissed
You're most recent changes look good 👍

2025-01-27 04:13 UTC, eliykat approved these changes

2025-01-27 18:42 UTC, cd-bitwarden approved these changes
LGTM!

2025-02-04 20:25 UTC, cd-bitwarden approved these changes
lgtm

2025-02-04 20:44 UTC, merged