[CL-425] - add tools card component
bitwarden/clients pull request #11375
Opened 2024-10-03 00:28 UTC by jaasen-livefront

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/CL-425

## 📔 Objective

This PR adds a new card-like component to be used initially for the new reports initiative but will likely see re-use elsewhere.

## 📸 Screenshots

![Screenshot 2024-10-02 at 5 25 42 PM](https://github.com/user-attachments/assets/84ebb803-3396-4fc0-9924-e6175fc23433)

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-10-03 13:43 UTC, vleague2 reviewed
Looking great so far!! Just a couple random things as I was looking through

2024-10-03 13:43 UTC, vleague2 commented on libs/tools/card/src/card.component.html
> +    <small>{{ subText }}</small>
I'd recommend checking with design to see which typography variant this should be, rather than using `small`

2024-10-03 13:43 UTC, vleague2 commented on libs/tools/card/src/card.component.ts
> +      "tw-box-border tw-block tw-text-main tw-border-solid tw-border-1 tw-border-secondary-300 tw-border tw-rounded-lg tw-p-6",
Oddly enough, when I check storybook, I'm not seeing the rounded borders applied. Maybe double-check that these are all working as expected?

2024-10-03 13:43 UTC, vleague2 commented on libs/tools/card/src/card.component.ts
> +      "tw-box-border tw-block tw-text-main tw-border-solid tw-border-1 tw-border-secondary-300 tw-border tw-rounded-lg tw-p-6",
I also went to check the figma file for typography variants and noticed that the card background color looks different than the screenshot that we have on the ticket. I'd also check with design to see if there have been any updates to the design for this component since we took that screenshot (because idk if what I'm looking at is the most updated).

2024-10-09 18:24 UTC, jaasen-livefront commented on libs/tools/card/src/card.component.ts
> +      "tw-box-border tw-block tw-text-main tw-border-solid tw-border-1 tw-border-secondary-300 tw-border tw-rounded-lg tw-p-6",
@vleague2 Should be fixed now.

2024-10-09 18:24 UTC, jaasen-livefront commented on libs/tools/card/src/card.component.html
> +    <small>{{ subText }}</small>
@vleague2 Unfortunately we don't have designs for this that I'm aware of. We're currently just going on the screenshot in the ticket.

2024-10-09 18:33 UTC, djsmith85 requested changes

2024-10-09 18:33 UTC, djsmith85 commented on libs/tools/card/src/card.component.ts
> +  @Input() maxValue: number;
⚠️  Please add documentation to any public facing methods/properties

2024-10-09 20:58 UTC, jaasen-livefront commented on .vscode/settings.json
> +  "angular.enable-strict-mode-prompt": false
@djsmith85 Ack! VScode keeps changing my settings!

2024-10-10 08:19 UTC, djsmith85 submitted a review, later dismissed

2024-10-11 20:17 UTC, vleague2 commented on libs/tools/card/src/card.component.html
> +    <small>{{ subText }}</small>
I added the figma file to the ticket so you have it for reference. I am unable to inspect this particular text to see the font sizes, so I'd recommend asking the designer to specify.

2024-10-11 20:23 UTC, jaasen-livefront commented on libs/tools/card/src/card.component.html
> +    <small>{{ subText }}</small>
@vleague2 Ah thank you! I've updated the component to match the design.

2024-10-11 20:32 UTC, vleague2 approved these changes
A couple non-blocking comments that can be addressed as the component is iterated on!

2024-10-11 20:32 UTC, vleague2 commented on libs/tools/card/src/card.component.ts
> +      "tw-box-border tw-bg-background tw-block tw-text-main tw-border-solid tw-border tw-border-secondary-300 tw-border [&:not(bit-layout_*)]:tw-rounded-lg tw-p-6",
You probably don't need the `not(bit-layout)` part of the selector and can just use `tw-rounded-lg` instead. That is part of the current card due to its use in the browser extension, but this card will not be used there

2024-10-11 20:32 UTC, vleague2 commented on libs/tools/card/src/card.stories.ts
> +  title: "Toools/Card",
```suggestion
  title: "Tools/Card",
```

2024-10-11 20:32 UTC, vleague2 commented on libs/tools/card/src/card.component.ts
> +export class CardComponent {
I'd consider making this a bit more specific since its inputs are geared towards this particular use case (which makes sense). Like `ReportCardComponent` or something. (And remove the description of it being "generic" from the `tools/card/README.md`, etc)

2024-10-11 21:00 UTC, djsmith85 approved these changes

2024-10-11 21:00 UTC, merged