[PM-13170] Enable use of new generators on web
bitwarden/clients pull request #11405
Opened 2024-10-04 10:20 UTC by djsmith85

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-13170

## 📔 Objective

Create a web-specific hosting component for the new credential-generator. Temporarily, this is going to use the new password-generator component, but will be replaced once https://github.com/bitwarden/clients/pull/11398 has merged.

The swap is guarded by a feature flag, so this can be merged without affecting current production.

## 📸 Screenshots

### Before
![image](https://github.com/user-attachments/assets/26c8eda8-6c70-42f7-92f5-d30aad12138d)

### After (temporary)
![image](https://github.com/user-attachments/assets/bd587219-afc1-4c6a-baca-0d42c4272305)

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-10-04 13:15 UTC, audreyality reviewed
👍🏻  Lookin' good! Just a nit.

2024-10-04 13:15 UTC, audreyality commented on apps/web/src/app/tools/credential-generator/credential-generator.component.html
> +  <!-- Will get replaced with <tools-credential-generator /> once https://github.com/bitwarden/clients/pull/11398 has been merged -->
⛏️ I've been calling out things to address in later commits using `FIXME: xyz`. That way it's easy to find tech debt with `grep`.

2024-10-04 13:18 UTC, djsmith85 commented on apps/web/src/app/tools/credential-generator/credential-generator.component.html
> +  <!-- Will get replaced with <tools-credential-generator /> once https://github.com/bitwarden/clients/pull/11398 has been merged -->
Addressed with ff18d01

2024-10-04 13:22 UTC, audreyality approved these changes

2024-10-08 18:43 UTC, audreyality approved these changes

2024-10-10 08:36 UTC, coroiu requested changes

2024-10-10 08:36 UTC, coroiu commented on apps/web/src/app/shared/loose-components.module.ts
> +    CredentialGeneratorComponent,
issue: we should avoid adding new components to this module

2024-10-10 08:44 UTC, djsmith85 commented on apps/web/src/app/shared/loose-components.module.ts
> +    CredentialGeneratorComponent,
@coroiu You are absolutely right and as it's a standalone component, I didn't need to import here anyway 🙈 

Addressed with 605d017

2024-10-10 08:44 UTC, coroiu approved these changes
Platform approval no longer needed - approving to get rid of "requested changes status"

2024-10-10 08:45 UTC, coroiu commented on apps/web/src/app/shared/loose-components.module.ts
> +    CredentialGeneratorComponent,
Hehe it was the only platform dependency too :D Approved!

2024-10-10 13:42 UTC, audreyality approved these changes

2024-10-10 13:42 UTC, merged