[PM-11201] Add the ability to sort by Name, Group, and Permission within the collection and item tables
bitwarden/clients pull request #11453
Opened 2024-10-07 22:44 UTC by gbubemismith

## 🎟️ Tracking
[PM-11201](https://bitwarden.atlassian.net/browse/PM-11201)

## 📔 Objective
Add the ability to sort by Name, Group, and Permission within the collection and item tables. 

In order to reduce the view of sporadic checkboxes, the default sort order should be by:

* Collections and Items
* Highest permission
     - Can manage
     - Can edit
     - Can edit, except passwords
     - Can view
     - Can view, except passwords
     - No access
* Alphabetical order of collections and items

## 📸 Screenshots

https://github.com/user-attachments/assets/17b6570e-5c7b-4a17-b09f-68985c3ad9b0

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

[PM-11201]: https://bitwarden.atlassian.net/browse/PM-11201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-10-07 22:47 UTC, gbubemismith commented on apps/web/src/app/vault/components/vault-items/vault-items.component.ts
> +      items = items.sort(this.defaultSort);
ℹ️ This caused the regression issues previously. After testing, I forgot to revert to applying the default sort and instead passed the group sort

2024-10-08 19:44 UTC, Jingo88 approved these changes

2024-10-08 20:08 UTC, Jingo88 submitted a review, later dismissed

2024-10-23 14:21 UTC, gbubemismith commented on libs/components/src/table/sortable.component.ts
> +  @Input()
ℹ️ @bitwarden/team-design-system the `fnFactory` was created because we needed collections to always appear before ciphers and then sort each group in ascending/descending order. Before `fnFactory`, we couldn't properly handle direction changes while maintaining collections at the top

2024-10-24 15:15 UTC, vleague2 commented on libs/components/src/table/sortable.component.ts
> +  @Input()
I'm not super familiar with our table component, but I see we already do have a `fn` input for a sort function. I guess there wasn't a way to extend/modify that to achieve what you wanted?

2024-10-24 17:09 UTC, Jingo88 submitted a review, later dismissed

2024-10-24 17:58 UTC, gbubemismith commented on libs/components/src/table/sortable.component.ts
> +  @Input()
Yeah, we already have an `fn` input that returns a `type SortFn = (a: any, b: any) => number`; modifying the `fn` input would mean changing the signature of the `SortFn` by adding a third parameter, and this would mean touching more aspects of the code, `fnFactory` seems less invasive and lets us create a `SortFn` with the direction passed in from the component

2024-10-28 14:00 UTC, Jingo88 submitted a review, later dismissed

2024-10-28 14:54 UTC, willmartian commented on libs/components/src/table/sortable.component.ts
> +  @Input()
Hi.

I prefer changing the existing `fn` input to have a third, optional parameter:

`type SortFn = (a: any, b: any, direction?: SortDirection) => number;`

1. This doesn't break any existing functionality
2. Having two different inputs for sorting is more mental overhead

---

Could you also update the "Sorting" section of `table.mdx` to document this change?

2024-10-28 14:55 UTC, willmartian requested changes
Changes requested here: https://github.com/bitwarden/clients/pull/11453#discussion_r1819219741

2024-10-29 16:45 UTC, willmartian requested changes

2024-10-29 16:45 UTC, willmartian commented on libs/components/src/table/table-data-source.ts
> +          : sort.fn(a, b) * directionModifier;
Why is this ternary necessary? Can't we always call `sort.fn(a, b, sort.direction) * directionModifier`?

2024-10-29 17:00 UTC, gbubemismith commented on libs/components/src/table/table-data-source.ts
> +          : sort.fn(a, b) * directionModifier;
Yeah this works

2024-10-29 17:33 UTC, willmartian submitted a review, later dismissed
DS changes look good, thanks! Don't forget to review/approve Chromatic diffs before merging.

2024-10-30 18:21 UTC, Jingo88 submitted a review, later dismissed

2024-10-31 14:07 UTC, willmartian submitted a review, later dismissed

2024-11-05 15:31 UTC, Jingo88 approved these changes

2024-11-05 17:49 UTC, willmartian commented on libs/components/src/table/sortable.component.ts
> +      const direction = this.isActive && this.direction === "asc" ? "desc" : defaultDirection;
1. Why pass the value as a param vs refer to it directly? 
2. The casting isn't safe, since the value can be a boolean. 

What do you think about rewriting to something like:

```ts
const defaultDirection = this._default === "desc" ? "desc" : "asc";
const direction = this.isActive && this.direction === "asc" ? "desc" : defaultDirection;
```

2024-11-06 16:17 UTC, willmartian commented on libs/components/src/table/sortable.component.ts
> +      const direction = this.isActive && this.direction === "asc" ? "desc" : defaultDirection;
Looks good, thanks!

2024-11-06 16:18 UTC, willmartian approved these changes
LGTM 👍

2024-11-06 19:15 UTC, Jingo88 approved these changes

2024-11-07 15:10 UTC, merged