Import from LogMeOnce not working  2.0
bitwarden/clients pull request #11452
Opened 2024-10-07 22:34 UTC by dlfi

Fixes #11406

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-10-10 08:11 UTC, djsmith85 reviewed
@dlfi Thank you for your contribution. 

The changes look pretty straightforward, but I was wondering, if you'd be up to adding some unit-tests to verify old and new behaviour. 

Examples can be found under the `libs/importer/spec`-folder. There are a couple of csv-file-importers that have tests which you can use as guidance.

2024-10-12 14:55 UTC, dlfi commented
Thank you for approval for workflows @djsmith85  and I would be happy to do tests! Already thought about it. I will try as soon as possible. Should it be in this pull request or do I need to make a new issue for tests?

2024-10-12 17:39 UTC, djsmith85 commented
@dlfi Tests should be added with this PR, then we can verify everything in one place before passing it on to QA.

2024-10-31 18:54 UTC, dlfi commented
Hi @djsmith85 I just added the tests to PR. I hope I did it right, I was inspired by the tests you linked me to. Sorry it took so long.

2024-11-05 20:20 UTC, djsmith85 requested changes
Nice work on adding the test cases @dlfi. Just some minor changes and then this ready to get passed on to QA.

Thanks again for your contribution!

2024-11-05 20:38 UTC, dlfi commented on libs/importer/spec/logmeonce-csv-importer.spec.ts
> +import { data as logmeonceData } from "./test-data/logmeonce-csv/logmeonce.test.validData.csv";
For sure! Thank you for the comment I just changed it.

2024-11-05 21:13 UTC, djsmith85 submitted a review, later dismissed
Thanks for the quick changes. Approving and moving this to QA for testing.

Once they give their okay, this can get merged and will be included in a future release.

2024-11-05 21:22 UTC, djsmith85 approved these changes

2026-08-13 08:31 UTC, djsmith85 commented
Apologies @dlfi I had reviewed and passed this on to QA, but they ran into some issues with other item types not being mapped correctly. I should have commented on them here, but I was aiming to carry this myself. I did have some local changes that were close but never fully completed the work. Since then I've moved into a different team, and the issue has been resolved by https://github.com/bitwarden/clients/pull/21473/

I apologize for your contribution not getting the proper attention and attribution.

Thank you very much for your contribution, and I hope this experience hasn't put you off from contributing to open source projects.

Closing this now.

Kind regards,
Daniel

2026-08-13 08:31 UTC, closed without merging