Delete @types/gulp & @types/minimatch on posinstall
bitwarden/clients pull request #11509
Opened 2024-10-11 15:34 UTC by Hinton

## 🎟️ Tracking

## 📔 Objective

Seems to work more reliably than the overrides. The root issue should be fixed when https://github.com/electron/asar/pull/332 is merged.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-10-17 17:17 UTC, MGibson1 requested changes
Could you update commit comment to mention when these hacks should be removed? Please do this through a rebase so that github will use the sole commit as the squash commit message

2024-10-17 18:44 UTC, Hinton commented
@MGibson1 I always manually write my merge commits, so a squash won't be needed. At this point I don't see this happening in the near future due to the electron maintainers perspective on the issue.

2024-10-17 18:45 UTC, Hinton commented
The auto merge has the following message. "This can be reverted once https://github.com/electron/asar/issues/330 is resolved."

2024-10-22 17:58 UTC, MGibson1 approved these changes

2024-10-22 17:58 UTC, merged