[PM-9723] Refresh: LoginViaAuthRequestComponent
bitwarden/clients pull request #11545
Opened 2024-10-14 19:04 UTC by rr-bw

- **Rename legacy components to V1**
- **setup new component**
- **migrate constructor() and ngOnInit()**
- **migrate verifyAndHandleApprovedAuthReq(), loginViaAuthRequestStrategy(), and buildAuthRequestLoginCredentials()**
- **migrate startAuthRequestLogin() and buildAuthRequest()**
- **migrate handleExistingAdminAuthRequest() and handleExistingAdminAuthReqDeletedOrDenied()**
- **migrate handleApprovedAdminAuthRequest() and handleSuccessfulLoginNavigation()**
- **migrate handlePostLoginNavigation()**
- **migrate web template**

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-11-05 22:49 UTC, JaredSnider-Bitwarden requested changes
Excellent work. No major issues - just a few comments below:

2024-11-05 22:49 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/login-via-auth-request/login-via-auth-request.component.ts
> +  async ngOnInit(): Promise<void> {
💡 : This is looking better, but can we refactor this further to (1) extract individual actions like validating email into functions and (2) reduce the 3 separate conditions which set / check state. If we can have two main branches for the two types of auth requests, I think that would be a large improvement.

2024-11-07 01:02 UTC, rr-bw commented on libs/common/src/services/api.service.ts
>    // TODO: PM-3519: Create and move to AuthRequest Api service
- https://github.com/bitwarden/clients/pull/11545/commits/9de7a01cb321bb95207065a21335ddd05962fa5d
- Added info to the [Jira Ticket](https://bitwarden.atlassian.net/browse/PM-9724) for that cleanup

2024-11-07 01:02 UTC, rr-bw commented on libs/auth/src/angular/icons/devices.icon.ts
> +  <svg xmlns="http://www.w3.org/2000/svg" width="120" height="100" fill="none">
- https://github.com/bitwarden/clients/pull/11545/commits/b21edf17b859bb441ee0dbc15500d4cc7805076e

2024-11-07 01:03 UTC, rr-bw commented on libs/auth/src/angular/login-via-auth-request/login-via-auth-request.component.ts
> +  async ngOnInit(): Promise<void> {
- https://github.com/bitwarden/clients/pull/11545/commits/dd610e30776578ed3bf1239006c4a95c027a3560

2024-11-15 22:58 UTC, rr-bw commented on libs/auth/src/angular/login-via-auth-request/login-via-auth-request.component.ts
> +     *             > decrypts userKey > establishes trust (if required) > proceeds to vault
@JaredSnider-Bitwarden 

Am I correct in understanding that "Flow 1" here is not actually a flow? That is, when dealing with an Admin Auth Request, we are always receiving an encrypted UserKey, not a MasterKey, meaning Flow 1 is not truly a flow?

If I am correct, then I would re-write this section as one flow in total, making no mention of having a MasterKey in memory or not. Which would look like:

```
***********************************
     Admin Auth Request Flows
***********************************

Flow 1: Authed SSO TD user requests admin approval.

    SSO TD user authenticates via SSO > navigates to /login-initiated > clicks "Request admin approval"
      > navigates to /admin-approval-requested which creates an AdminAuthRequest
        > receives approval from device with authRequestPublicKey(userKey) > decrypts userKey
          > establishes trust (if required) > proceeds to vault
```

2024-11-15 23:10 UTC, rr-bw commented on libs/auth/src/angular/login-via-auth-request/login-via-auth-request.component.ts
> +      }
@JaredSnider-Bitwarden 

Instead of checking the `State` to determine the codepath, [as we did in the legacy component](https://github.com/bitwarden/clients/blob/main/libs/angular/src/auth/components/login-via-auth-request.component.ts#L316-L332), I'm using the AuthStatus as this allows me to consolidate two things:
1. Getting the auth request from the server _**using the correct authenticated/unauthenticated endpoint**_.
    - Note that this now means Standard Flows 3-4, which are both authed, will now grab the auth request from `getAuthRequest()` (authed endpoint) instead of from `getAuthResponse()` (unauthed endpoint). Those flows were previously using the unauthed endpoint because even though they are authed flows, the case `State.StandardAuthRequest` sent them to the unauthed endpoint.
3. Handling the actual flow with a method name that distinguishes authenticated vs unauthenticated flows.

2024-11-18 15:53 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/login-via-auth-request/login-via-auth-request.component.ts
> +     *             > decrypts userKey > establishes trust (if required) > proceeds to vault
Yes, great catch. Admin auth requests always send the encrypted user key (per the logic in the `organization-auth-request.service.ts`).

2024-11-18 15:54 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/login-via-auth-request/login-via-auth-request.component.ts
> +      }
Excellent differentiation. Thank you so much for cleaning all this logic up. 🏅

2024-11-18 15:59 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/login-via-auth-request/login-via-auth-request.component.ts
> +     *             > decrypts userKey > establishes trust (if required) > proceeds to vault
If you want to add a further clarifier, as TDE users are required to be enrolled in admin password reset (which gives the admin's access to the user's user key), that is how the admins are able to send over the auth request public key encrypted user key to the user to allow them to unlock.

2024-11-18 23:23 UTC, rr-bw commented on libs/auth/src/angular/login-via-auth-request/login-via-auth-request.component.ts
> +     *             > decrypts userKey > establishes trust (if required) > proceeds to vault
Sure, update here - https://github.com/bitwarden/clients/pull/11545/commits/c76b5c477fc1a8a9de12cba786614b3ad66e343f

Also updated the PR description.

2024-11-19 19:06 UTC, JaredSnider-Bitwarden approved these changes
Excellent work on this. Thank you very much for all the rounds of testing and thorough documentation. This is so much cleaner.

2024-11-19 22:53 UTC, merged