[PM-13402] Adding the service to get member cipher details
bitwarden/clients pull request #11544
Opened 2024-10-14 18:45 UTC by ttalty

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-13402

## 📔 Objective

Report service infrastructure to access the new member cipher details information from the api. 
Depends on https://github.com/bitwarden/server/pull/4876
## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-10-17 13:29 UTC, audreyality requested changes
👍🏻 Very focused PR. It was dirt simple to review.

The only requested change is adding unit tests. Everything else is gravy.

2024-10-17 13:29 UTC, audreyality commented on bitwarden_license/bit-web/src/app/tools/reports/member-access-report/response/member-cipher-details.response.ts
⚠️ This should be unit tested.

❓ @djsmith85 - Do we want to put the report infrastructure in a bitwarden_license library instead of directly in the webapp?

2024-10-17 13:29 UTC, audreyality commented on bitwarden_license/bit-web/src/app/tools/reports/member-access-report/services/member-cipher-details-api.service.ts
> +    const responses = response.map((o: any) => new MemberCipherDetailsResponse(o));
🎨 Wrapping the RPC in a service would give greater control over how the report is constructed to the backend. This can be important, in particular, for compatibility and scaling purposes.

2024-10-17 13:34 UTC, djsmith85 commented on bitwarden_license/bit-web/src/app/tools/reports/member-access-report/response/member-cipher-details.response.ts
As per a recent discussion with product, this should be placed under BW license

2024-10-18 15:26 UTC, ttalty commented on bitwarden_license/bit-web/src/app/tools/reports/member-access-report/services/member-cipher-details-api.service.ts
> +    const responses = response.map((o: any) => new MemberCipherDetailsResponse(o));
This will definitely be wrapped into a service. Was keeping this file straightforward. As in the only logic here will be the api calls. Just mapped like similar response objects. I am working on the service that will consume this data.

2024-10-18 15:34 UTC, audreyality commented on bitwarden_license/bit-web/src/app/tools/reports/member-access-report/services/member-cipher-details-api.service.ts
> +    const responses = response.map((o: any) => new MemberCipherDetailsResponse(o));
🤦🏻‍♀️ I saw the `Injectable` and thought this was angular component. Didn't realize it's already in a service.

2024-10-18 15:38 UTC, audreyality commented on bitwarden_license/bit-web/src/app/tools/reports/member-access-report/response/member-cipher-details.response.ts
Talked about this offline -- my question is about whether we want to split it into a library so that we can share it with the bitwarden-licensed CLI and/or a bitwarden-licensed desktop app.

♻️ The answer is that those are good things to do, but there wasn't a decision made one way or the other. @ttalty - Either put this in the existing common library, create a tools-specific library, or file a JIRA w/ this feedback to track that we'll decide how to address this feedback later.

2024-10-18 19:20 UTC, ttalty commented on bitwarden_license/bit-web/src/app/tools/reports/member-access-report/services/member-cipher-details-api.service.ts
> +    const responses = response.map((o: any) => new MemberCipherDetailsResponse(o));
Moved to bitwarden license and into a new tools\reports\access-intelligence folder

2024-10-18 19:20 UTC, ttalty commented on bitwarden_license/bit-web/src/app/tools/reports/member-access-report/response/member-cipher-details.response.ts
Moved to bitwarden license and into a new tools\reports\access-intelligence folder

2024-10-18 19:22 UTC, audreyality approved these changes

2024-10-18 19:23 UTC, audreyality approved these changes

2024-10-21 16:07 UTC, merged