[PM-13651] migrate verify recover delete provider component
bitwarden/clients pull request #11586
Opened 2024-10-16 18:35 UTC by BTreston

## 🎟️ Tracking

[PM-13651](https://bitwarden.atlassian.net/browse/PM-13651)

## 📔 Objective

This PR refactors the VerifyRecoverDeleteProvider component to use the component library and removes bootstrap classes from the templates. It also removes the VerifyRecoverDeleteProvider and the Providers components out of the loose-components.module and into their own domain specific module.

## 📸 Screenshots

Before: 
<img width="413" alt="Screenshot 2024-10-16 at 11 45 42 AM" src="https://github.com/user-attachments/assets/e91e1642-a604-4e19-be3e-6613212a1a7f">

After:
![Screenshot 2024-10-16 at 12 47 04 PM](https://github.com/user-attachments/assets/57c5aa9f-d377-4c25-ad58-27c227d94615)
(note, the container is slightly wider. This is to avoid using arbitrary values.)

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-10-17 01:53 UTC, eliykat requested changes

2024-10-17 01:53 UTC, eliykat commented on apps/web/src/app/admin-console/providers/verify-recover-delete-provider.component.html
It looks like this was originally put in the wrong place - provider functionality is under the Bitwarden License (a proprietary source-available license rather than OSS) and is therefore located in `bitwarden_license/bit-web/src/app/admin-console/providers`. Please move it there and add it to that module and routing module.

2024-10-17 01:53 UTC, eliykat commented on apps/web/src/app/admin-console/providers/verify-recover-delete-provider.component.ts
> +    private formBuilder: UntypedFormBuilder,
We do use `UntypedFormBuilder` in some places, but only as a transitional measure after Angular added strongly typed forms. All new uses should be the regular (typed) `FormBuilder`.

2024-10-17 01:53 UTC, eliykat commented on apps/web/src/app/admin-console/providers/verify-recover-delete-provider.component.ts
> +    private formBuilder: UntypedFormBuilder,
That said - it doesn't look like you actually have any form components here, other than the button. Buttons with `bitSubmit` functionality can be used standalone outside of forms: see https://components.bitwarden.com/?path=/docs/component-library-async-actions-standalone-documentation--docs

2024-10-17 01:53 UTC, eliykat commented on apps/web/src/app/admin-console/providers/verify-recover-delete-provider.component.html
This page can leverage the `AnonLayoutComponent`, see documentation here: https://components.bitwarden.com/?path=/docs/auth-anon-layout--docs

That should remove most of this markup. See `verify-recover-delete.component` as an example.

2024-10-17 01:53 UTC, eliykat commented on apps/web/src/app/shared/loose-components.module.ts
Thank you for taking the initiative to continue to clean up this module. 👏 It's definitely a solid front-end tech debt task.

2024-10-17 16:28 UTC, BTreston commented on apps/web/src/app/shared/loose-components.module.ts
Thank you for the feedback, super helpful!

2024-10-18 04:52 UTC, eliykat requested changes

2024-10-18 04:52 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/providers/verify-recover-delete-provider.component.ts
> +  submit = async () => {
You can delete the `try/catch` and error logging in this callback. `bitAction` handles that for you.

2024-10-22 10:19 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/providers/verify-recover-delete-provider.component.ts
> +    await this.formPromise;
Apologies for not spotting this earlier. `this.formPromise` is no longer required, it was only used in the `appApiAction` directive which has now been removed. You can await the promise directly and remove the `formPromise` class property.

2024-10-22 10:21 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/providers/verify-recover-delete-provider.component.ts
>      private logService: LogService,
`logService` is also now unused.

2024-10-25 00:19 UTC, eliykat approved these changes

2024-10-28 00:14 UTC, eliykat approved these changes

2024-10-28 15:58 UTC, merged