Auth/pm 8115/desktop extension UI refresh self hosted
bitwarden/clients pull request #11597
Opened 2024-10-17 02:29 UTC by alec-livefront

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-8115?atlOrigin=eyJpIjoiZjYxZDhiNjg1OWQwNDFlZGI3NWQyYmVkYTZlMGVhNGYiLCJwIjoiaiJ9

## 📔 Objective

Uses the new `RegistrationSelfHostedEnvConfigDialogComponent` as the dialog when selecting "self-hosted" from the server configuration on the login page. Also adjusts the leading text for the select based on whether the `UnauthenticatedExtensionUIRefresh` is enabled.

## 📸 Screenshots

<img width="1302" alt="Screenshot 2024-10-16 at 9 28 46 PM" src="https://github.com/user-attachments/assets/1dc0d6e9-37f6-4d38-9867-37253ac8c787">
![Screenshot 2024-10-16 at 9 28 34 PM](https://github.com/user-attachments/assets/2ec2d8a3-4c08-42b9-8b2e-3bd69f3cef38)
![Screenshot 2024-10-16 at 9 28 24 PM](https://github.com/user-attachments/assets/5bc8e125-3aab-413b-b3c0-d52b14cc2334)

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-10-18 14:52 UTC, JaredSnider-Bitwarden commented on apps/browser/src/auth/popup/home.component.ts
I apologize that the task was not clear enough on this, but we do not need to modify the existing login components - only the new login component's env selector.

2024-10-21 16:02 UTC, alec-livefront commented on apps/browser/src/auth/popup/home.component.ts
@JaredSnider-Bitwarden does this mean this needs to branch off of 8111?

2024-10-21 16:23 UTC, JaredSnider-Bitwarden commented on apps/browser/src/auth/popup/home.component.ts
No, upon reviewing the changesets, this can be done separately.

2024-10-25 19:22 UTC, JaredSnider-Bitwarden requested changes
I tested this really quickly, but the self hosted option doesn't open on desktop or browser after merging main? 

https://github.com/user-attachments/assets/31a1648a-47dc-4afc-b98f-b60f33618463

2024-10-28 19:23 UTC, alec-livefront commented
@JaredSnider-Bitwarden I believe I've implemented everything we talked about this morning:

- Moving / renaming the `SelfHostedEnvConfigDialogComponent`
- Removing the EnvironmentSelectorService
- Removing the instance of "loggingInOn" from browser messages

2024-10-28 19:46 UTC, JaredSnider-Bitwarden requested changes
Nice work! This is incredibly close! Just a few notes below:

2024-10-28 19:46 UTC, JaredSnider-Bitwarden commented on libs/angular/src/auth/components/environment-selector.component.ts
> +        await SelfHostedEnvConfigDialogComponent.open(this.dialogService);
This is looking a lot better! We should add a success toast if the return result is successful of:
```TypeScript
  this.toastService.showToast({
        variant: "success",
        title: null,
        message: this.i18nService.t("environmentSaved"),
      });
```
Taken from the `RegistrationEnvSelectorComponent`.  "environmentSaved" already exists on each client as well.

2024-10-28 19:46 UTC, JaredSnider-Bitwarden commented on libs/angular/src/auth/components/environment-selector.component.ts
> +import { SelfHostedEnvConfigDialogComponent } from "../../../../auth/src/angular/self-hosted-env-config-dialog/self-hosted-env-config-dialog.component";
⚠️ , anytime you see an import like this from our auth directory, it should be a red flag to indicate that we are missing an `index.ts` export somewhere. Anything coming out of our libs/auth should be either imported from `from "@bitwarden/auth/angular"` or `from "@bitwarden/auth/common"`

2024-10-28 19:46 UTC, JaredSnider-Bitwarden commented on libs/angular/src/auth/components/environment-selector.component.ts
> +import { SelfHostedEnvConfigDialogComponent } from "../../../../auth/src/angular/self-hosted-env-config-dialog/self-hosted-env-config-dialog.component";
Here's the way to resolve this: https://github.com/bitwarden/clients/pull/11597/commits/a8cc5df806bc7d4fa8081d735f24306066084015

2024-10-28 20:03 UTC, alec-livefront commented on libs/angular/src/auth/components/environment-selector.component.ts
> +        await SelfHostedEnvConfigDialogComponent.open(this.dialogService);
[7cc875f](https://github.com/bitwarden/clients/pull/11597/commits/7cc875ff336dbd98bbbf35549f204b7c2afd1770)

2024-10-28 20:28 UTC, JaredSnider-Bitwarden approved these changes
LGTM!

2024-10-28 21:12 UTC, merged