[PM-12989] Create process for qa to build client with particular sdk version
bitwarden/clients pull request #11601
Opened 2024-10-17 11:55 UTC by coroiu

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-10-17 12:48 UTC, michalchecinski requested changes

2024-10-17 12:48 UTC, michalchecinski commented on .github/workflows/build-desktop.yml
> +          branch: ${{ inputs.sdk_branch }}
Since the input is not required we should have a fallback option if the value is not supplied. I'd suggest creating a new step to detect if the `${{ inputs.sdk_branch }}` input is empty. It can look like that:

```
      - name: SDK branch output
        id: sdk-branch-output
        run: |
          if [[ "${{ inputs.sdk_branch }}" == "" ]]; then
            echo "Latest Released Version: main"
            echo "sdk_branch=main" >> $GITHUB_OUTPUT
          else
            echo "SDK branch: ${{ inputs.sdk_branch }}"
            echo "sdk_branch=${{ inputs.sdk_branch }}" >> $GITHUB_OUTPUT
          fi
 ```
 
 Then in the line 83 you can reference it like that:
 ```
 ${{ steps.sdk-branch-output.outputs.sdk_branch }}
 ```

2024-10-17 12:53 UTC, michalchecinski commented on .github/workflows/build-desktop.yml
> +          branch: ${{ inputs.sdk_branch }}
If that's the case, we don't need the solution I suggested. ☺️

2024-10-17 12:54 UTC, michalchecinski submitted a review, later dismissed

2024-10-22 07:25 UTC, coroiu commented
Closing and moving to https://github.com/bitwarden/sdk-internal/pull/5

2024-10-22 11:31 UTC, coroiu commented
Woops, accidentally close the client PR

2024-10-24 12:57 UTC, audreyality reviewed
⚠️ Looks like there's a build failure because the SDK function isn't yet available in the SDK artifact the build is presently using.

👍🏻 Tools changes LGTM otherwise!

2024-10-24 13:00 UTC, coroiu commented
@audreyality Yeah we're having some CI issues due to a repo split that hasn't fully settled. The changes are merged but we're unable to build https://github.com/bitwarden/sdk-internal/actions/runs/11495900424/job/31996431116

Fortunately this PR introduces the ability to bypass NPM so manual build targeting main should work as expected. But yeah, we can't merge before this is resolved, just wanted to start getting code reviews in :)

2024-10-29 13:46 UTC, audreyality commented on apps/browser/src/tools/popup/settings/about-dialog/about-dialog.component.ts
> +    catchError(() => "Unsupported"),
It seems wrong to me that this method uses exceptions to communicate an expected state. Is there a chance the service could include metadata for when the SDK is unsupported? An example:

```typescript
type SdkVersion = { version: string } | false;
// or
type SdkVersion = { version: string } | null;
// or
type SdkVersion = { version: string } | "unsupported";
//or
type SdkVersion = { supported: true, version: string } | { supported: false };
``

2024-10-29 13:52 UTC, coroiu commented on apps/browser/src/tools/popup/settings/about-dialog/about-dialog.component.html
> +    <p class="user-select">SDK: {{ sdkVersion$ | async }}</p>
I don't think we translate `SDK`, see e.g. "Electron", "Rendered"

https://github.com/bitwarden/clients/blob/c8862174d57ceeb0c0535bc1cee5ab9012374c8f/apps/desktop/src/main/menu/menu.about.ts#L57-L65

2024-10-29 14:01 UTC, audreyality commented on apps/browser/src/tools/popup/settings/about-dialog/about-dialog.component.html
> +    <p class="user-select">SDK: {{ sdkVersion$ | async }}</p>
That looks like code we haven't transitioned yet. Of the 4 labels, only 1 (Node) is a brand name. The others are just words. That said, this isn't my call. I was nitting a code smell. 

@danielleflinn - Should we be localizing the SDK label? Should I add a ticket to localize the snippet @coroiu just posted?

2024-10-29 14:03 UTC, coroiu commented on apps/browser/src/tools/popup/settings/about-dialog/about-dialog.component.html
> +    <p class="user-select">SDK: {{ sdkVersion$ | async }}</p>
For some context, I don't really expect users to be looking at this, in anything they might copy and paste it when contacting CS. This is just a way to confirm that QA is testing with the correct version

2024-10-29 14:05 UTC, coroiu commented on apps/browser/src/tools/popup/settings/about-dialog/about-dialog.component.ts
> +    catchError(() => "Unsupported"),
I mean, soon you won't be able to run the clients without WASM support so you'll never be able to reach this dialog anyways. But you have a point, maybe "Unavailable" is a better term, since we have no way of knowing why we weren't able to call it

2024-10-29 14:17 UTC, audreyality commented on apps/browser/src/tools/popup/settings/about-dialog/about-dialog.component.ts
> +    catchError(() => "Unsupported"),
> soon you won't be able to run the clients without WASM support so you'll never be able to reach this dialog anyways

Either way, the error handling for SDK metadata should be encapsulated by the service. Maybe you need to put in a small JS shim for methods like `version` so that a failure-t-load-SDK error doesn't leak through the interface used to inspect the SDK's meta-state.

2024-10-29 14:58 UTC, coroiu commented on apps/browser/src/tools/popup/settings/about-dialog/about-dialog.component.ts
> +    catchError(() => "Unsupported"),
Moved the error handling out of this component!

2024-10-29 15:06 UTC, audreyality approved these changes
👍🏻 Looking good! 
🌱 Thank you for moving the error handling into the service layer!

There's a nit, but it's cool if we circle back. I don't think it's worth blocking this PR over. :)

2024-10-30 13:53 UTC, justindbaur requested changes
It can be for the future but I love the idea of having `VersionService` available with the exact same interface for all the clients and then deprecating the method from `PlatformUtilsService`. I want to slim down what is offered from `PlatformUtilsService`.

2024-10-30 13:53 UTC, justindbaur commented on apps/web/src/app/platform/version.service.ts
> +      };
I think we should ask product if we could add version info somewhere in the web app. The app version is available from the login screen but I'd love to add it somewhere when you're signed in as well. Then we can avoid attaching things to window.

This can be a future improvement though.

2024-10-30 13:53 UTC, justindbaur commented on apps/web/src/app/platform/version.service.ts
> +  init() {
I prefer a more specific name for methods like this.

```suggestion
  applyVersionToWindow() {
```

2024-10-30 14:42 UTC, coroiu commented on .github/workflows/build-browser.yml
> +        if: ${{ inputs.sdk_branch != '' || inputs.sdk_commit != '' }}
Woooops, I added it as a temporary debug tool, must've missed this!

2024-10-30 14:43 UTC, coroiu commented on apps/web/src/app/platform/version.service.ts
> +      };
I just thought `main (7e7a10a)` wouldn't look so pretty on the login page 🤷

2024-10-30 15:40 UTC, coroiu commented on apps/web/src/app/platform/version.service.ts
> +      };
I could also just print the version on startup, if that would be better? That way we'd avoid attaching stuff to `window`

2024-11-04 13:16 UTC, coroiu commented on apps/web/src/app/platform/version.service.ts
> +      };
👍 for future reference, thread here: https://bitwarden.slack.com/archives/C0321H9M0KS/p1730726130705639

2024-11-04 14:16 UTC, justindbaur approved these changes

2024-11-05 12:57 UTC, justindbaur approved these changes

2024-11-07 14:05 UTC, audreyality commented on package.json
❓ Is the angular upgrade intentional?

2024-11-07 14:05 UTC, audreyality approved these changes

2024-11-08 07:22 UTC, coroiu commented on package.json
Look like github included a merge commit into you comparison, the angular update was brought in from main so no worries :)

2024-11-15 14:46 UTC, audreyality approved these changes

2024-11-19 12:59 UTC, justindbaur approved these changes

2024-11-19 12:59 UTC, merged