Tools/pm 13454/get hostname for login uri
bitwarden/clients pull request #11646
Opened 2024-10-21 20:28 UTC by voommen-livefront

## 🎟️ Tracking

[
](https://bitwarden.atlassian.net/browse/PM-13454)

## 📔 Objective

This PR substitutes the URL to just the host name - making it easier to group them together.

## 📸 Screenshots

Before:
![image](https://github.com/user-attachments/assets/8494725b-eb0b-4ec6-8025-5eede55698ee)

After:
![image](https://github.com/user-attachments/assets/767ac628-aa86-47e9-b495-fa085fa7c639)

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-10-24 13:37 UTC, ttalty commented on apps/web/src/app/tools/access-intelligence/password-health-members-uri.component.ts
⚠️ Add the members count column that is already mapped in the service. The elements can be copied from the password health members component.

2024-10-24 18:39 UTC, voommen-livefront commented on apps/web/src/app/tools/access-intelligence/password-health-members-uri.component.ts
done.

2024-10-25 15:28 UTC, ttalty requested changes

2024-10-25 15:28 UTC, ttalty commented on bitwarden_license/bit-common/src/tools/reports/access-intelligence/services/password-health.service.ts
>  }
❌ This should not be excluding duplicate uris here. It will miss data.

For example: Using the mock data. There is a `google.com` uri that is associated with 3 members. 

![image](https://github.com/user-attachments/assets/1875f21f-d69d-480e-838d-5792a5d11fbb)

Using the item that shows `example.com` and is associated with 6 members. If the mock data was updated: `src\tools\reports\access-intelligence\services\ciphers.mock.ts` and for the `example.com` cipher (id:`cbea34a8-bde4-46ad-9d19-b05001228cd3`)  add `http://google.com` as a uri to that collection. 

The report only displays one google.com uri and it is the first one that has 3 members. The google.com with 6 members does not display. 

Updating the uri for the example.com cipher to any uri not used will display the additional item. 

Refactor to ignore the check to see if the uri exists.

2024-10-30 18:11 UTC, ttalty approved these changes

2024-10-30 18:11 UTC, merged