[PM-13839][PM-13840] Admin Console Collections
bitwarden/clients pull request #11649
Opened 2024-10-21 20:58 UTC by nick-livefront

## 🎟️ Tracking

[PM-13839](https://bitwarden.atlassian.net/browse/PM-13839)
[PM-13840](https://bitwarden.atlassian.net/browse/PM-13840)

Associated Server PR (coming soon...)

## 📔 Objective

- When viewing in Admin Console
  - all collections an item belongs to should be shown, even if I don't have access to the collection
- When editing in Admin Console
  - Only collections I have edit+ access to that an item belongs to  (assuming "owners and admins can manage all collections and items" is off)
  - When "owners and admins can manage all collections" is on, then all collections can be edited

## 📸 Screenshots

|Update Cipher with Admin/owner can Edit on, then Show when admin/owner is off|
|-|
|<video src="https://github.com/user-attachments/assets/80fc4728-2c49-4fd3-a2ce-74d5f6d397fd" />

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-10-22 19:45 UTC, nick-livefront commented on libs/vault/src/cipher-form/services/default-cipher-form.service.ts
This change from saving the collections before any other edits was made in part of [PM-13887](https://bitwarden.atlassian.net/browse/PM-13887). I was seeing errors with saving edits before assigning to the collection.

2024-10-25 03:06 UTC, shane-melton requested changes
One small edge case we need to check and then this looks good!

2024-10-25 03:06 UTC, shane-melton commented on libs/vault/src/cipher-form/services/default-cipher-form.service.ts
> +      savedCipher = await this.cipherService.updateWithServer(encryptedCipher, config.admin);
⚠️ There's a really specific edge case where the user may un-assign themselves from a cipher by removing the last editable collection from the cipher. If this happens, the call to `cipherService.updateWithServer` will fail due to a lack of permissions after first updating the collections. You'd only run into this if the access all items as admin setting was off and you removed a the last editable collection.

I believe to avoid this, we can still save the collections first. But, when the original cipher is unassigned, we need to update the call to `updateWithServer` to have a check for an unassigned original cipher. 

e.g.
```ts
updateWithServer(encryptedCipher, config.admin || originalCollectionIds.size === 0)
```

This will use the admin endpoint for both of the scenarios that require it.

2024-10-26 19:51 UTC, nick-livefront commented on libs/vault/src/cipher-form/services/default-cipher-form.service.ts
> +      savedCipher = await this.cipherService.updateWithServer(encryptedCipher, config.admin);
As always, great catch 🤯 [e6c5032](https://github.com/bitwarden/clients/pull/11649/commits/e6c50327e2c54cc508498804cac95f5858e0847c)

2024-10-29 00:14 UTC, shane-melton commented on libs/vault/src/cipher-form/services/default-cipher-form.service.ts
> +      savedCipher = await this.cipherService.updateWithServer(encryptedCipher, config.admin);
Agh, I misspoke in my comment above, sorry. We should still update the **cipher first**.

That way if a user makes a change to the cipher AND unassigns themselves, the change to cipher is still persisted. Otherwise, the user is going to unassign themselves and then fail to update the cipher because they no longer have access.

If the cipher is originally unassigned, we can update the cipher first by making the change described above and also updating the call to use the `saveCollectionsWithServerAdmin()` method to account for the unassigned permissions.

2024-10-29 00:16 UTC, shane-melton commented on libs/vault/src/cipher-form/services/default-cipher-form.service.ts
> +      savedCipher = await this.cipherService.updateWithServer(encryptedCipher, config.admin);
(We should eventually just encapsulate this “admin / not admin” logic internally within the `CipherService` to avoid this headache repeatedly. But, I don’t think we need to do that here and now, as there will likely be other consequences we’ll have to consider that our outside of scope.)

2024-10-29 20:21 UTC, nick-livefront commented on libs/vault/src/cipher-form/services/default-cipher-form.service.ts
> +      savedCipher = await this.cipherService.updateWithServer(encryptedCipher, config.admin);
I think I finally wrapped my head around all of the permutations that can happen here 😅 And I was able to get those situations rolling locally so I feel better about that too.
 
 [e70380e](https://github.com/bitwarden/clients/pull/11649/commits/e70380e24d9b024f072fb75fde17441ace41e483) & [679ceb2](https://github.com/bitwarden/clients/pull/11649/commits/679ceb2ee09a4b82a13729595eb7b1da6dbc4154)

2024-10-29 20:24 UTC, nick-livefront commented on libs/vault/src/cipher-form/components/item-details/item-details-section.component.ts
> +          (this.partialEdit || !c.readOnly || this.config.admin)
@shane-melton The logic behind `canEditItems` and `!c.readOnly || this.config.admin` overlaps. Do you think it's better to be explicit here with referencing the config? Or should I update the logic to

`c.organizationId === orgId && c.canEditItems(organization) && this.partialEdit`

2024-10-30 18:52 UTC, shane-melton commented on libs/vault/src/cipher-form/components/item-details/item-details-section.component.ts
> +          (this.partialEdit || !c.readOnly || this.config.admin)
I think its okay to be explicit and reference the config.

With that said, I do think we want to re-arrange these conditions so that `partialEdit` still supersedes the edit-ability of a collection because the control is disabled.

```ts
c.organizationId === orgId && (this.partialEdit || c.canEditItems(organization) || this.config.admin)
```

2024-10-30 19:23 UTC, nick-livefront commented on libs/vault/src/cipher-form/components/item-details/item-details-section.component.ts
> +          (this.partialEdit || !c.readOnly || this.config.admin)
👍 [fea33b1](https://github.com/bitwarden/clients/pull/11649/commits/fea33b1ee53194e8e800b94d7d024d95598acd41)

2024-10-31 18:48 UTC, shane-melton approved these changes
Changes look good to me! Really nice work on this!

2024-10-31 18:49 UTC, shane-melton requested changes
Oops, looks like we have some failing tests

2024-11-01 00:29 UTC, nick-livefront commented on libs/vault/src/cipher-form/components/item-details/item-details-section.component.ts
> +      this.showCollectionsControl = true;
@shane-melton Calling this change out. The "should enable/show collection control when an organization is selected" unit test caught the case where `orgId` is falsy but then truthy. I don't _believe_ that this would happen in the UI but through the logic it's possible so I added the enable/show logic here.

2024-11-01 15:48 UTC, shane-melton commented on libs/vault/src/cipher-form/components/item-details/item-details-section.component.ts
> +      this.showCollectionsControl = true;
That should be fine and I agree, I don't think it should come up in use, but better safe than sorry!

2024-11-01 15:48 UTC, shane-melton submitted a review, later dismissed

2024-11-04 19:12 UTC, nick-livefront commented on apps/web/src/app/vault/components/vault-item-dialog/vault-item-dialog.component.ts
> +    this.formConfig.originalCipher = cipher;
This logic stems from defect: [PM-14449](https://bitwarden.atlassian.net/browse/PM-14449).

When a cipher was edited within the Admin console and the user doesn't have "direct" access, the `cipherService` will return null. In this case the `getCipherAdmin` should be used to refetch the cipher

2024-11-04 20:04 UTC, nick-livefront commented on apps/web/src/app/vault/components/vault-item-dialog/vault-item-dialog.component.ts
> +    this.formConfig.originalCipher = cipher;
https://github.com/user-attachments/assets/2428b711-aa81-4551-8580-eaaa2a3362d0

2024-11-04 20:34 UTC, shane-melton approved these changes

2024-11-07 16:22 UTC, merged