Switch to rustcrypto argon2 on desktop
bitwarden/clients pull request #11753
Opened 2024-10-28 17:20 UTC by quexten

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-14185

## 📔 Objective

Cross-compiling and building desktop in some environments (arm cross compile; flatpak build from source) is made difficult by the native CPP dependency. This PR switches the desktop argon2 implementation to use rustcrypto's argon2 crate (same as the SDK) via desktop_native. Note: The crate currently implements parallelism sequentially, so this change does have a performance impact. In a quick measurement, for the default settings (with parallelism = 4), unlock was 33% as fast as the npm module. However, given that other clients use the same rust implementation via the sdk, this seems like a reasonable trade-off.

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-10-28 21:23 UTC, mzieniukbw requested changes

2024-10-28 21:23 UTC, mzieniukbw commented on apps/desktop/desktop_native/core/Cargo.toml
> +argon2 = "0.5.3"
enable feature `zeroize` to make it safer

2024-10-28 21:23 UTC, mzieniukbw commented on apps/desktop/desktop_native/core/src/crypto/crypto.rs
> +        std::hint::black_box([0u8; 4096]);
❓ I don't know why we use, the docs literally says there is no guarantee it works and it's not recommended in any cryptographic or security usage.
This library can use `zeroize` with enabled feature, does it solve this problem ?

2024-10-29 11:10 UTC, quexten commented on apps/desktop/desktop_native/core/Cargo.toml
> +argon2 = "0.5.3"
Enabled

2024-10-29 13:17 UTC, mzieniukbw submitted a review, later dismissed

2024-10-29 14:27 UTC, dani-garcia reviewed
Changes LGTM, but we should also remove these lines in the electron builder config:

https://github.com/bitwarden/clients/blob/e39ab59fa8bd280cc4c3b8acab36cb63cb5e4324/apps/desktop/electron-builder.json#L23-L26

2024-10-29 14:30 UTC, dani-garcia commented on apps/desktop/desktop_native/core/src/crypto/crypto.rs
> +            e.to_string()
Tiny nit, this can be simplified slightly like this, which uses the error Display impl:
```suggestion
            "Argon2 parameters are invalid: {e}"
```

2024-10-29 18:45 UTC, quexten commented on apps/desktop/desktop_native/core/src/crypto/crypto.rs
> +            e.to_string()
Updated, nice!

2024-10-29 19:22 UTC, mzieniukbw submitted a review, later dismissed

2024-10-30 10:43 UTC, quexten commented
Sorry about that, fixed now.

2024-10-30 13:37 UTC, dani-garcia submitted a review, later dismissed

2024-10-30 16:48 UTC, mzieniukbw approved these changes

2024-10-31 19:36 UTC, Thomas-Avery requested changes
Looking good, a few minor things to check out.

2024-10-31 19:36 UTC, Thomas-Avery commented on apps/desktop/desktop_native/napi/src/lib.rs
> +}
```suggestion
}

```
:pick: missing new line at EOF.

2024-10-31 19:36 UTC, Thomas-Avery commented on apps/desktop/desktop_native/core/src/crypto/crypto.rs
> +    let _ = argon.hash_password_into(secret, &salt, &mut hash);
```suggestion
argon.hash_password_into(secret, &salt, &mut hash)?;
```

With `let _ =` won't the error case of the `Result<()>` be suppressed here? 

I would recommend using the `?` operator or explicitly handling the error result.

2024-10-31 19:36 UTC, Thomas-Avery commented on apps/desktop/desktop_native/core/src/crypto/crypto.rs
> +pub fn argon2(
Should we have some unit tests for this function?

2024-10-31 19:36 UTC, Thomas-Avery commented on apps/desktop/src/platform/main/main-crypto-function.service.ts
> +          salt: Uint8Array;
I see this is related to ipc?
Do we need to be worried about backwards compatibility with these type changes?

2024-11-01 10:32 UTC, quexten commented on apps/desktop/src/platform/main/main-crypto-function.service.ts
> +          salt: Uint8Array;
Argon2 itself works on uint8 arrays, so things are getting converted at some point. So far, the node-argon implementation is converting to buffer using https://nodejs.org/api/buffer.html#static-method-bufferfromstring-encoding which defaults to encoding in utf-8. This PR also encodes to utf-8 in renderer-crypto-function-service. So from that persective, they should be the same.

The IPC here is *not* between two different bitwarden applications, but between bitwarden-desktop's main and renderer process (both part of desktop). So these are never out of sync version wise.

2024-11-01 10:48 UTC, quexten commented on apps/desktop/desktop_native/core/src/crypto/crypto.rs
> +pub fn argon2(
Added a test, testing the happy path. Not sure about errors, I don't think we are testing these for any other argon implementations, or handling them, since they should be prevented by the settings validation when changing to argon2.

2024-11-01 10:49 UTC, quexten commented on apps/desktop/desktop_native/core/src/crypto/crypto.rs
> +    let _ = argon.hash_password_into(secret, &salt, &mut hash);
Passing through with ? + map err now

2024-11-01 15:36 UTC, Thomas-Avery approved these changes
LGTM

2024-11-01 15:38 UTC, Thomas-Avery commented on apps/desktop/desktop_native/core/src/crypto/crypto.rs
> +pub fn argon2(
Happy path sounds good for now. In the future, if we run into any error cases happening, we should add them.

2024-11-04 10:31 UTC, dani-garcia approved these changes

2024-11-12 13:58 UTC, dani-garcia submitted a review, later dismissed

2024-11-12 16:44 UTC, dani-garcia commented
Just noticed one webpack config that still references the old argon2, we probably want to remove it as well:

https://github.com/bitwarden/clients/blob/5592d640a8f6e714b10a8402ca18296fba995462/apps/desktop/webpack.main.js#L85

2024-11-13 16:56 UTC, mzieniukbw submitted a review, later dismissed

2024-11-14 16:33 UTC, dani-garcia commented on apps/desktop/desktop_native/Cargo.lock
> +
There are some cargo build errors in CI, I think because this `syn` package appears to be duplicated? Same thing with the `zvariant` below. If you check the packages immediately after them, it's just other semver compatible versions. I think this is what was causing the weird issue that made me downgrade zbus in the other PR.

You should be able to delete both the syn and package entries from this cargo.lock, as it seems it got malformed during a merge. You can also restore the cargo.lock from main and then run cargo build to regenerate it.

2024-12-04 10:14 UTC, coroiu commented
@quexten I'm having issues with an electron update due to argon2 (https://github.com/bitwarden/clients/pull/11580) which I think we should be able to bypass completely using this PR. Do you think that we could get this merged soon?

2024-12-04 10:23 UTC, quexten commented
Let's test this on main instead, given we have a long window until next rc cut. Enabling automerge.

2024-12-04 10:31 UTC, mzieniukbw approved these changes

2024-12-04 11:52 UTC, dani-garcia approved these changes

2024-12-04 11:54 UTC, merged