[PM-11698] - fix header in billing sync dialog
bitwarden/clients pull request #11777
Opened 2024-10-29 18:02 UTC by jaasen-livefront

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-11698

## 📔 Objective

This PR fixes the header size in the billing sync dialogs.

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-10-29 18:56 UTC, danielleflinn requested changes

2024-10-29 18:56 UTC, danielleflinn commented on apps/web/src/app/billing/organizations/billing-sync-api-key.component.html
> +    <span bitDialogTitle>
I don't think changing this to a `<span>` is the proper solution as this is a new view's title it should remain an `<h1>` so a screen reader can navigate the new view by heading.

Looking at Storybook it looks like we are missing some of the `bittypography="h3"` styling that is usually applied to the `bitDialogTitle` 

@vleague2 would you mind weighing in on why the Component Library is not applying the proper heading styles here?

2024-10-29 18:56 UTC, danielleflinn commented on apps/web/src/app/billing/organizations/billing-sync-key.component.html
> +    <span bitDialogTitle>
same as previous comment

2024-10-29 20:18 UTC, danielleflinn commented on apps/web/src/app/billing/organizations/billing-sync-api-key.component.html
> +    <span bitDialogTitle>
@jaasen-livefront Which dialogs were you referencing?  The ones I found had `<h1><span></span></h1> `

2024-10-29 20:20 UTC, vleague2 commented on apps/web/src/app/billing/organizations/billing-sync-api-key.component.html
> +    <span bitDialogTitle>
@danielleflinn @jaasen-livefront It looks like the `bitDialogTitle` is just a selector used by the dialog component that doesn't apply any styles. The `bitDialogTitle` gets wrapped by an `h1` applying `h3` styles inside the dialog component itself, so I think this change is correct. What story are you looking at where the styling is missing?

2024-10-29 20:22 UTC, danielleflinn commented on apps/web/src/app/billing/organizations/billing-sync-api-key.component.html
> +    <span bitDialogTitle>
Ok so the rendered dialog will include the h1 in the browser inspector? That's all I care about but its hard to tell if that is happening here

2024-10-29 20:24 UTC, danielleflinn approved these changes
Ignore previous comments if this renders with an `<h1>` element and proper styling

2024-10-29 20:35 UTC, jaasen-livefront commented
> Ignore previous comments if this renders with an `<h1>` element and proper styling

@danielleflinn Indeed! The `span` is wrapped within an `h1` tag.

2024-10-30 13:26 UTC, vleague2 approved these changes

2024-10-31 09:45 UTC, jonashendrickx approved these changes

2024-10-31 16:34 UTC, merged