BEEEP Adjacent - AccountService misc improvements - (1) prefer null o…
bitwarden/clients pull request #11779
Opened 2024-10-29 19:12 UTC by JaredSnider-Bitwarden

…ver undefined and (2) add new Account type

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-10-29 20:47 UTC, mzieniukbw requested changes

2024-10-29 20:47 UTC, mzieniukbw commented on libs/auth/src/angular/lock/lock.component.ts
>      this.activeAccount = activeAccount;
🎨 how about updating `this.activeAccount` to be of type `Account | null` ?

2024-10-29 20:47 UTC, mzieniukbw commented on libs/common/src/auth/services/account.service.ts
>    if (account?.id == null) {
🎨 
```suggestion
  if (account === null) {
```

2024-10-29 20:47 UTC, mzieniukbw commented on libs/common/src/auth/services/account.service.ts
> +  (account) => account?.id ?? null,
🎨 
```suggestion
  (account) => account !== null ? account.id : null,
```

2024-10-29 20:49 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/lock/lock.component.ts
>      this.activeAccount = activeAccount;
Great catch! Resolved!

2024-10-29 20:55 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/account.service.ts
>    if (account?.id == null) {
@mzieniukbw , making that change will prevent errors from being thrown if the account id is null which is the previous and intended behavior.  I could modify the function to have 2 separate checks if we want strict equality + separate errors:
```TypeScript
export const getUserId = map<Account | null, UserId>((account) => {
  if (account === null) {
    throw new Error("Null account");
  }

  if (account.id === null) {
    throw new Error("Null account id");
  }

  return account.id;
});
```

2024-10-29 20:59 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/account.service.ts
> +  (account) => account?.id ?? null,
@mzieniukbw , the second suggestion introduces a potential error scenario at runtime that the existing approach does not: 
if the account is `undefined`, the ternary will evaluate to true, and an error of `Cannot read property 'id' of undefined` will be thrown. I feel like the first option is a bit safer, no?

2024-10-29 21:00 UTC, mzieniukbw commented on libs/common/src/auth/services/account.service.ts
>    if (account?.id == null) {
I don't think `account.id === null` is possible, since the type have changed. The `id` field no longer holds undefined, it's non-nullable.
See your change: https://github.com/bitwarden/clients/pull/11779/files#diff-2a1c9ca9ce353732848f3482f82776ffd664d143d552f5c8b8fde133496d5814R15

2024-10-29 21:13 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/account.service.ts
> +  (account) => account?.id ?? null,
I agree with you regarding strict mode. It would be so much better. For now, can we keep the more defensive style?

2024-10-29 21:14 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/account.service.ts
>    if (account?.id == null) {
Oh, right. Thank you for pointing that out. I've updated it to simply catch `null` or `undefined` account scenarios - but not worry about explicitly checking for `account.id`.

2024-10-29 21:14 UTC, mzieniukbw commented on libs/common/src/auth/services/account.service.ts
> +  (account) => account?.id ?? null,
Sure. To be more specific it's this setting https://www.typescriptlang.org/tsconfig/#strictNullChecks (enabled in strict mode). 🤔 It made me wonder, maybe we should gradually enable it file by file for better types correctness.

2024-10-29 21:16 UTC, mzieniukbw approved these changes
LGTM ❤️

2024-10-30 17:20 UTC, rr-bw approved these changes

2024-10-30 21:53 UTC, justindbaur approved these changes

2024-10-30 21:54 UTC, merged