Auth/PM-12077 - Initial work on web process reload - more testing required.
bitwarden/clients pull request #11781
Opened 2024-10-29 19:48 UTC by JaredSnider-Bitwarden

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-11-19 10:35 UTC, quexten requested changes
Nice job!

2024-11-19 10:35 UTC, quexten commented on apps/web/src/app/app.component.ts
>    private async logOut(logoutReason: LogoutReason, redirect = true) {
It seems the logoutReason parameter is now unused.

Question: Just to confirm, this is intentional?

If so, we can remove it.

2024-11-19 16:00 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/app.component.ts
>    private async logOut(logoutReason: LogoutReason, redirect = true) {
Addressed! Thank you for catching it!

2024-11-20 08:38 UTC, coroiu approved these changes
Simple PR with big benefits, nice work!

2024-11-20 08:38 UTC, coroiu commented on apps/web/src/app/app.component.ts
> +  loading = false;
suggestion (non-blocking): 
```suggestion
  protected loading = false;
```

2024-11-20 08:38 UTC, coroiu commented on apps/web/src/app/app.component.ts
> +    // will prevent any toasts from being displayed long enough to be read
thought: maybe we could put the reason in the URL or in some temporary local storage and show it on startup instead, if we really wanted to show the toast

2024-11-20 08:38 UTC, coroiu commented on apps/web/src/app/app.component.ts
> +      await this.processReloadService.startProcessReload(this.authService);
question: I know this isn't a new addition in this PR, but I'm curious if you know why we send in the service as a parameter here instead of relying on DI?

2024-11-20 09:43 UTC, quexten approved these changes
Also LGTM. Nice work!

2024-11-20 15:41 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/app.component.ts
> +    // will prevent any toasts from being displayed long enough to be read
Yes, @justindbaur and I have spoken about a toast queue service where we could store this data pre-process reload and read messages off the queue on app bootstrap, but that implementation is outside the scope of this PR.

2024-11-20 15:41 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/app.component.ts
> +      await this.processReloadService.startProcessReload(this.authService);
I believe that is v1 and @quexten intends to refactor that further in the future iirc?

2024-11-20 15:42 UTC, coroiu commented on apps/web/src/app/app.component.ts
> +    // will prevent any toasts from being displayed long enough to be read
> but that implementation is outside the scope of this PR.

Oh yeah, just a thought, but sounds like you've already considered it 👍

2024-11-20 17:28 UTC, Patrick-Pimentel-Bitwarden commented
Reviewed code and documentation for why this change was needed. No notes.

2024-11-20 17:28 UTC, Patrick-Pimentel-Bitwarden approved these changes

2024-11-20 17:39 UTC, quexten commented on apps/web/src/app/app.component.ts
> +      await this.processReloadService.startProcessReload(this.authService);
Left over from before process reload was pulled out into it's own service. The idea was not to change any logic. https://github.com/bitwarden/clients/pull/10853/files#diff-7d45a576eb605c6fe6b5ef93fc64c8f9b3824fc0acade93ff526b4215ef74ccbL42-L67

2024-11-20 18:54 UTC, merged