[pm-14025] Remove usage of ActiveUserState from organization.service
bitwarden/clients pull request #11799
Opened 2024-10-30 19:43 UTC by BTreston

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-14025

## 📔 Objective

WIP

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-11-11 17:08 UTC, BTreston commented on libs/common/src/admin-console/abstractions/organization/vnext-organization.service.abstraction.ts
Just to be clear on this one:

- rename the class definitions in organization.service.ts to include the "default" prefix
- rename organization.service.ts to default-organization.service.ts
- rename new vnext-[filename] files to default-vnext[filename]

This would include updating the import statements across some 150 files. Just want to double check before making that wide a change. The other requested changes have been committed to this branch.

2024-11-12 05:41 UTC, eliykat commented on libs/common/src/admin-console/abstractions/organization/deafult-vnext.organization.service.abstraction.ts
This should be called `vnext-organization.service.ts`.

2024-11-12 05:41 UTC, eliykat commented on libs/common/src/admin-console/services/organization/vnext-organization.service.ts
This should be called `default-vnext-organization.service.ts`.

2024-11-12 05:41 UTC, eliykat commented on libs/common/src/admin-console/services/organization/vnext-organization.service.spec.ts
This should be called `default-vnext-organization.service.spec.ts`.

2024-11-12 05:41 UTC, eliykat commented on libs/common/src/admin-console/abstractions/organization/vnext-organization.service.abstraction.ts
I've commented on each file below to clarify exact naming.

No need to rename the current organization service given that we're about to replace it anyway. But I figure that you're going to have to update all the calling locations when you sub in the vnext implementation, so that's a good time to update the name as well.

2024-11-12 06:00 UTC, eliykat requested changes

2024-11-15 07:20 UTC, eliykat requested changes
Just this and then we should be good to go.

The next stage of this is to update all callers to use the new interface and implementation. That will affect a _lot_ of calling locations, so you may want to consider whether to update 1 client at a time (1 client per PR) rather than all at once.

2024-11-18 03:41 UTC, eliykat approved these changes

2024-11-18 17:26 UTC, merged