[CL-499] compact mode
bitwarden/clients pull request #11796
Opened 2024-10-30 18:34 UTC by willmartian

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/CL-499

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-10-30 18:35 UTC, willmartian commented on libs/components/src/item/item.component.html
>  >
I removed this div and moved the styles to the host element, so that I could utilize CSS `:first` and `:last`.

2024-10-31 13:42 UTC, vleague2 commented on libs/components/src/stories/compact-mode.mdx
> +Bitwarden has a global compact mode setting for users who prefer a more information-dense UI.
Do we want to note that it is only present in the extension for now? In case people read this and think that it applies to all clients

2024-10-31 13:42 UTC, vleague2 commented on libs/components/src/shared/bit-settings.service.ts
> +export class BitSettingsService {
Is this intended to mean settings like user settings, or settings like DS settings?

2024-10-31 13:54 UTC, vleague2 commented
Not that this is caused by your PR, but I noticed that the item action content doesn't seem to be vertically centered. It looks more noticeable in compact mode to me
![Screenshot 2024-10-31 at 9 53 06 AM](https://github.com/user-attachments/assets/fcf6ec6f-1e6d-4dca-a034-a185d98472b3)

2024-11-04 18:31 UTC, willmartian commented
> Not that this is caused by your PR, but I noticed that the item action content doesn't seem to be vertically centered. It looks more noticeable in compact mode to me ![Screenshot 2024-10-31 at 9 53 06 AM](https://private-user-images.githubusercontent.com/32983157/381971899-fcf6ec6f-1e6d-4dca-a034-a185d98472b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NDUzNDUsIm5iZiI6MTczMDc0NTA0NSwicGF0aCI6Ii8zMjk4MzE1Ny8zODE5NzE4OTktZmNmNmVjNmYtMWU2ZC00ZGNhLWEwMzQtYTE4NWQ5ODQ3MmIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDE4MzA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiYjI0NGZjNTBlYzgyMDczOTJlNWE5MDI2ODExMTEyMzUwNTEwMTJlNjQ3ODI5NDNkYTEyNmU4Y2NjZjIwMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._Pv9I7vbXrtE4SA3wvhYnNuO3hrUrFzVDEu11-rkzq4)

Should be fixed with [9f05381](https://github.com/bitwarden/clients/pull/11796/commits/9f053816814ad424f3e91d7c75e2d80ef2edf309)

2024-11-06 20:17 UTC, willmartian commented on libs/components/src/stories/compact-mode.mdx
> +Bitwarden has a global compact mode setting for users who prefer a more information-dense UI.
Fixed here [4a1e27d](https://github.com/bitwarden/clients/pull/11796/commits/4a1e27d7f3b5cba175ab04088f1c70bc1a7ac078)

2024-11-06 20:17 UTC, willmartian commented on libs/components/src/item/item.stories.ts
> +<div class="tw-bit-compact tw-max-h-">
Fixed here [4a1e27d](https://github.com/bitwarden/clients/pull/11796/commits/4a1e27d7f3b5cba175ab04088f1c70bc1a7ac078)

2024-11-06 20:18 UTC, willmartian commented on libs/components/src/shared/bit-settings.service.ts
> +export class BitSettingsService {
Global DS settings, does this make that more clear? [67c37dd](https://github.com/bitwarden/clients/pull/11796/commits/67c37dd0182b97fdbff8d917ca31761547ece136)

Devs can hook this to user settings as appropriate elsewhere.

2024-11-06 20:48 UTC, danielleflinn requested changes
✅ Verified spacing and border-radius on bit-list and bit-list groups is expected
✅ Verified spacing is reduced for header and footer elements show as expected
✅ Verified footer elements are now aligned-center
✅ Known limitation of compact mode: when macOS has only show scrollbar "when scrolling" the scrollbar may overlap slightly with the bit-item content. This is acceptable as we are unable to adjust this with how the styling is currently handled. 
⛔️ Unable to verify is navigation footer has reduced padding as shown [here in figma](https://www.figma.com/design/IqMYFyT2WVyyDaV3PeyVDi/Compact-mode?node-id=127-16986&t=7bp55q2FXRXLxLQu-4)

2024-11-06 20:56 UTC, vleague2 commented
I just remembered that we have some hardcoded heights in px for virtual scrolling. We'll probably need compact mode versions of that, right? Otherwise it won't work in virtual scroll?

2024-11-06 20:58 UTC, willmartian commented
> @vleague2  I just remembered that we have some hardcoded heights in px for virtual scrolling. We'll probably need compact mode versions of that, right? Otherwise it won't work in virtual scroll?

Yes. Great call out. I need to think about the best way to handle that.

2024-11-12 19:51 UTC, nick-livefront commented on libs/components/src/stories/compact-mode.mdx
> +To get/set compact mode in TypeScript, the `BitSettingsService` exposes a `compactMode` signal.
Just looking at this to integrate it with the extension, I believe this should be `DesignSystemService`

```suggestion
To get/set compact mode in TypeScript, the `DesignSystemService` exposes a `compactMode` signal.
```

2024-11-12 22:30 UTC, willmartian commented on libs/components/src/stories/compact-mode.mdx
> +To get/set compact mode in TypeScript, the `BitSettingsService` exposes a `compactMode` signal.
Thanks! [84e18b1](https://github.com/bitwarden/clients/pull/11796/commits/84e18b1922114cfb2cdc9937d49dd7df7a0463bb)

2024-11-13 20:39 UTC, danielleflinn submitted a review, later dismissed
✅ bit-item-group doesn't have the extra 6px of space at the end of the list in either modes that was previously observed
✅ bit-item spacing updated + no spacing exists between list items and last item retains the bottom border
✅ bit-item has a min-height that matches button height for instances that only have 1 line of text
✅ bit-items instances in the extension previously observed to have a missing top border radius now show the proper radius
✅ extension layout now handles search slot padding allowing it to be updated in compact mode. Verified padding is expected in compact mode on Vault and Send pages
✅ Verified no unexpected bottom padding on Vault virtual scroll container when searching or filtering
✅ Compact mode setting appears on Appearance page and includes a beta badge. Setting persists when user closes the extension
❓ Main navigation padding still matches the default padding. Ideally we would drop this top padding by about 4px to more closely match the height of the footer with buttons (view/edit pages). That said, I missed this in my last list of feedback so I'm ok with us moving this to followup work so we can move the feature to QA

2024-11-14 02:04 UTC, willmartian commented
>❓ Main navigation padding still matches the default padding. Ideally we would drop this top padding by about 4px to more closely match the height of the footer with buttons (view/edit pages). That said, I missed this in my last list of feedback so I'm ok with us moving this to followup work so we can move the feature to QA

Oops, added here: [1296019](https://github.com/bitwarden/clients/pull/11796/commits/1296019667ac4090acfb28f1047a151bfc81b057)

https://github.com/user-attachments/assets/e27dc1b0-03dc-466a-b052-706920282d4e

2024-11-14 17:13 UTC, shane-melton submitted a review, later dismissed
Vault changes look good!

2024-11-14 19:16 UTC, merissaacosta commented on apps/browser/src/platform/popup/layout/popup-compact-mode.service.ts
> +        : document.body.classList.remove("tw-bit-compact");
do we have to worry about the remove function failing if `tw-bit-compact` doesnt exist? i forget if that fails silently or not

2024-11-14 19:26 UTC, merissaacosta commented on apps/browser/src/vault/popup/components/vault-v2/vault-list-items-container/vault-list-items-container.component.ts
> +    map((enabled) => (enabled ? 53 : 59)),
Suggestion: do we want to put these number values in a variable?

2024-11-14 19:34 UTC, merissaacosta approved these changes

2024-11-14 21:54 UTC, willmartian commented on apps/browser/src/vault/popup/components/vault-v2/vault-list-items-container/vault-list-items-container.component.html
> +      [itemSize]="itemHeight$ | async"
Yep! That is how we bind an observable or promise to a template. My change [here](https://github.com/bitwarden/clients/pull/11796/files#diff-ce62244148a0f0356e4e4452fcf207980c85581c4eb00710e16d733ef1d48e2aR68) makes this necessary.

2024-11-14 21:56 UTC, willmartian commented on apps/browser/src/platform/popup/layout/popup-compact-mode.service.ts
> +        : document.body.classList.remove("tw-bit-compact");
It doesn't error: 

> If the string is not in the list, no error is thrown, and nothing happens. 
https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/remove

2024-11-14 21:59 UTC, willmartian commented on apps/browser/src/vault/popup/components/vault-v2/vault-list-items-container/vault-list-items-container.component.ts
> +    map((enabled) => (enabled ? 53 : 59)),
Personal opinion: Since the comment above already explains the values, and they are only used in a single place, I don't think a descriptive name adds much.

2024-11-14 22:02 UTC, willmartian commented on apps/browser/src/vault/popup/components/vault-v2/vault-list-items-container/vault-list-items-container.component.html
> +      [itemSize]="itemHeight$ | async"
Angular docs: https://v17.angular.io/guide/observables-in-angular#async-pipe

2024-11-15 21:09 UTC, willmartian commented
Sorry, I borked the commit history with a bad rebase after merging the feature branch.

2024-11-15 23:09 UTC, danielleflinn approved these changes
✅ Verified page header and footer spacing in default mode was updated to match requirements
✅ Verified compact mode card, form-field, and sections, now have decreased padding

2024-11-18 14:25 UTC, djsmith85 approved these changes
Approving for tools

2024-11-18 15:29 UTC, vleague2 reviewed
Thoughts/q's but looking really good!

2024-11-18 15:29 UTC, vleague2 commented on apps/browser/src/vault/popup/settings/appearance-v2.component.ts
> +    enableCompactMode: false,
❓ So does this setting's value remain in memory like the theme setting if the user has already set it in the past?

2024-11-18 16:12 UTC, willmartian commented on apps/browser/src/platform/popup/layout/popup-header.component.html
> +        class="-tw-ml-1"
💭 Yes, valid point. I brought that up with @danielleflinn, but I believe her preference is to use the default icon button size (which I don't disagree with), so this is a workaround to make it look optically aligned to the left. Just a tradeoff for not using filled button styles. 

The other approach here would be to do something like `when header first child is button, use less left padding`. But that feels over-abstracted if we are only ever using a single button here.

2024-11-18 16:17 UTC, willmartian commented on apps/browser/src/vault/popup/settings/appearance-v2.component.ts
> +    enableCompactMode: false,
Yes. This initial `false` value is basically fake. 
1.) it is immediately overwritten by whatever is saved in state when the component first loads [here.](https://github.com/bitwarden/clients/pull/11796/files#diff-3228cd6f057f502717e15062abf5a8622263a22fd7a92ef277920e5e8dbfc78fR83) The form isn't shown until after all of these promises resolve. 
2.) form changes are saved in state [here](https://github.com/bitwarden/clients/pull/11796/files#diff-3228cd6f057f502717e15062abf5a8622263a22fd7a92ef277920e5e8dbfc78fR120-R123)

2024-11-18 16:24 UTC, vleague2 commented on apps/browser/src/platform/popup/layout/popup-header.component.html
> +        class="-tw-ml-1"
Agreed! Ty for context!

2024-11-18 16:25 UTC, vleague2 submitted a review, later dismissed

2024-11-18 20:07 UTC, vleague2 approved these changes

2024-11-18 20:15 UTC, djsmith85 approved these changes

2024-11-18 20:51 UTC, gbubemismith approved these changes

2024-11-18 21:35 UTC, merged