[PM-13818] Allow user to edit self-hosted url during registration
bitwarden/clients pull request #11790
Opened 2024-10-30 14:13 UTC by alec-livefront

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-13818?atlOrigin=eyJpIjoiZmQ2Njc1OTg0NTg5NGI1NDkxMjdhZmQ0NThiOGJmZjciLCJwIjoiaiJ9

## 📔 Objective

Re-launch the `self-hosted-env-config-dialog` after a user has previously selected the self hosted option from the "Creating account on" select. This allows a user to go back and edit values after the dialog has closed.

## 📸 Screenshots

![Screenshot 2024-10-30 at 9 12 54 AM](https://github.com/user-attachments/assets/92f81b61-a0ff-4a04-bfcb-ef801251b5f7)
![Screenshot 2024-10-30 at 9 13 04 AM](https://github.com/user-attachments/assets/77f1f3c4-8b41-4399-8d81-3c2194f17a8d)

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-10-30 15:30 UTC, willmartian commented on libs/auth/src/angular/registration/registration-env-selector/registration-env-selector.component.ts
> +  }
Converting the `open` promise to an observable requires a lot of ceremony that isn't buying us anything, since we are effectively converting it back to a promise with `take(1)` and `subscribe()` in `onSelectClosed`.

What do you think of this alternative? 


```ts
type RegionSelection = RegionConfig | Region.SelfHosted | null;

protected async onSelectClosed(value: RegionSelection) {
    if (value === Region.SelfHosted) {
      const result = await SelfHostedEnvConfigDialogComponent.open(this.dialogService)
      return this.handleSelfHostedEnvConfigDialogResult(result, prevSelectedRegion);
    }
}

```

2024-10-30 15:32 UTC, willmartian commented on libs/components/src/select/select.component.ts
> +  protected lastSelectedValue: T;
How does this differ from `selectedValue`?

2024-10-30 15:32 UTC, willmartian commented on libs/components/src/select/select.component.ts
> +    }
I feel like we should always emit, since the event is called "closed" and the select is indeed closing.

2024-10-30 21:28 UTC, alec-livefront commented on libs/auth/src/angular/registration/registration-env-selector/registration-env-selector.component.ts
> +  }
[6d92fcb](https://github.com/bitwarden/clients/pull/11790/commits/6d92fcb26576cbcbc12d08fd3a411045fd038d17)

2024-10-30 21:28 UTC, alec-livefront commented on libs/components/src/select/select.component.ts
> +    }
[13704a9](https://github.com/bitwarden/clients/pull/11790/commits/13704a9bcc297659964e64f91209010bb1ffaa1f)

2024-11-05 18:19 UTC, willmartian commented on libs/components/src/select/select.component.ts
> +  protected lastSelectedValue: T;
I worry about keeping track of the value in two different places introducing errors. I don't know how the timing of `ng-select`'s close event interacts with an asynchronous update to the form's value. 

Could we just update this to not emit any value? The current value can simply be accessed by the consumer's form group. 

```ts
handleClose() {
   console.log(this.selectedRegion.value);
}
```

2024-11-05 18:19 UTC, willmartian requested changes
See https://github.com/bitwarden/clients/pull/11790#discussion_r1829815428

2024-11-05 21:42 UTC, alec-livefront commented on libs/components/src/select/select.component.ts
> +  protected lastSelectedValue: T;
@willmartian do you mean like this?

```
  protected onClose() {
    this.closed.emit();
  }
```

That works! I've added that and removed `userSelectedValue`: [820210e](https://github.com/bitwarden/clients/pull/11790/commits/820210efbf7057bc949041e98e223ad1324ce926)

2024-11-06 15:22 UTC, willmartian requested changes

2024-11-06 15:22 UTC, willmartian commented on libs/components/src/select/select.component.ts
> +  @Output() closed = new EventEmitter<T>();
```suggestion
  @Output() closed = new EventEmitter();
```

2024-11-06 15:22 UTC, willmartian commented on libs/auth/src/angular/registration/registration-env-selector/registration-env-selector.component.ts
> +  }
This needs to be refactored to no longer expect a parameter, correct? Since `close` no longer emits a value.

2024-11-06 18:28 UTC, alec-livefront commented on libs/auth/src/angular/registration/registration-env-selector/registration-env-selector.component.ts
> +  }
Whoops yes - here's the fix: 2533716659f631699ee4cfae79d93ef580315dc8

2024-11-06 18:50 UTC, willmartian approved these changes
DS changes look good, thanks!

2024-11-06 19:12 UTC, JaredSnider-Bitwarden approved these changes

2024-11-06 19:17 UTC, merged