Auth/pm 5237/hide create account when registration disabled
bitwarden/clients pull request #11811
Opened 2024-10-31 18:16 UTC by alec-livefront

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-5237?atlOrigin=eyJpIjoiYzc4ODNlZjM5Y2RiNDY5Njg5YmU5MjM3YjgwYjZjYTkiLCJwIjoiaiJ9

## 📔 Objective

Shows or hides the "create account" link based on the GlobalSettings configuration.

## 📸 Screenshots

![Screenshot 2024-10-31 at 1 16 25 PM](https://github.com/user-attachments/assets/75d50023-821e-4344-a6b9-cb7ced02b795)
![Screenshot 2024-10-31 at 1 16 12 PM](https://github.com/user-attachments/assets/ae4a64f8-be25-40a1-89e1-255fce8fe420)

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-10-31 18:22 UTC, alec-livefront commented
@JaredSnider-Bitwarden would you mind taking a look at this and letting me know if I'm on the right track? One piece I haven't been able to work out is "The create account section should react to environment changes if a user changes from an env where open registration is enabled to one where it is disabled" - it seems I have to refresh the page to get it to pick up the latest config.

2024-11-01 20:50 UTC, JaredSnider-Bitwarden requested changes
Per our call, some notes below!

2024-11-01 20:50 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/login/login-v1.component.html
Let's not update any v1 components.

2024-11-01 20:50 UTC, JaredSnider-Bitwarden commented on libs/common/src/platform/services/server-settings.service.ts
💡 : can we add the Default prefix to the service to match our docs, please?

2024-11-01 20:50 UTC, JaredSnider-Bitwarden commented on libs/common/src/platform/models/domain/server-settings.ts
> +
Let's deprecate the interface and just work directly with the `ServerSettings` class

2024-11-01 20:50 UTC, JaredSnider-Bitwarden commented on libs/common/src/platform/services/server-settings.service.ts
> +    return this.configService.serverSettings$.pipe(map((settings: ServerSettings) => settings));
Let's clean up this map as it isn't necessary, please

2024-11-04 03:20 UTC, alec-livefront commented on apps/web/src/app/auth/login/login-v1.component.html
[3493673](https://github.com/bitwarden/clients/pull/11811/commits/34936733971eaa6f11fa58e02bc4d3cd636eedb8)

2024-11-04 03:35 UTC, alec-livefront commented on libs/common/src/platform/services/server-settings.service.ts
> +    return this.configService.serverSettings$.pipe(map((settings: ServerSettings) => settings));
[3d1dcf3](https://github.com/bitwarden/clients/pull/11811/commits/3d1dcf3c431b0af9652d46d239ec0a7e867b6bac)

2024-11-04 03:35 UTC, alec-livefront commented on libs/common/src/platform/services/server-settings.service.ts
[d63753e](https://github.com/bitwarden/clients/pull/11811/commits/d63753e55f62be9d5f6f91832da9796080227b13)

2024-11-04 03:36 UTC, alec-livefront commented on libs/common/src/platform/models/domain/server-settings.ts
> +
[a08fd41](https://github.com/bitwarden/clients/pull/11811/commits/a08fd41b51c2b25b50ee5e0080a7cad55a5e7d7b)

2024-11-05 22:53 UTC, JaredSnider-Bitwarden requested changes
One tiny clean up item and this is done! Excellent work!

2024-11-05 22:53 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/login/login-v1.component.html
> -    <hr />
This <hr /> seems to have been removed in error?

2024-11-05 22:53 UTC, JaredSnider-Bitwarden commented on libs/common/src/platform/services/default-server-settings.service.spec.ts
Nice test suite!

2024-11-06 04:13 UTC, alec-livefront commented on apps/web/src/app/auth/login/login-v1.component.html
> -    <hr />
[4434520](https://github.com/bitwarden/clients/pull/11811/commits/4434520e8de6d635d07171c02ce8cc6322d812fe)

2024-11-06 15:15 UTC, JaredSnider-Bitwarden approved these changes

2024-11-06 21:21 UTC, JaredSnider-Bitwarden approved these changes

2024-11-06 22:57 UTC, addisonbeck approved these changes

2024-11-06 22:57 UTC, merged