[PM-10326] Hide 'remove' option for organization managed members
bitwarden/clients pull request #11874
Opened 2024-11-06 11:28 UTC by r-tome

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-10326

## 📔 Objective

Hide the ‘remove’ option on the members list and on the individual member dialog for managed members

## 📸 Screenshots

<img width="765" alt="image" src="https://github.com/user-attachments/assets/6ab349d9-63ce-4f07-b663-bd3cea09ef8d">

<img width="649" alt="image" src="https://github.com/user-attachments/assets/7fa0c4c9-2f2b-4f1a-aba9-c77bc9c91144">

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-11-07 14:38 UTC, BTreston commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.html
> +          *ngIf="editMode && params.managedByOrganization === false"
❓ Would this prevent you from removing the user form an org they are a member of where they are not a managed user?

2024-11-07 15:05 UTC, r-tome commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.html
> +          *ngIf="editMode && params.managedByOrganization === false"
No, it only prevents removing a user who _is_ a managed user, as they have the **Delete** action instead. An alternative condition could be `*ngIf="editMode && params.managedByOrganization !== true`

2024-11-07 16:27 UTC, BTreston submitted a review, later dismissed

2024-11-08 14:59 UTC, BTreston requested changes
Looks good, just some ⛏️ s to keep the logic clean

2024-11-08 14:59 UTC, BTreston commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.html
> +              params.managedByOrganization === false)
`accountDeprovisioningEnabled$ | async` and `manangedByOrganization' here will be booleans, I don't think we need the === check. We should be able to just use their values for these conditions:

```suggestion
            editMode &&
           (!(accountDeprovisioningEnabled$ | async) || !params.managedByOrganization)
```

2024-11-08 14:59 UTC, BTreston commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.html
> +            params.managedByOrganization === true
Same comment as above for these

2024-11-08 14:59 UTC, BTreston commented on apps/web/src/app/admin-console/organizations/members/members.component.html
> +                >
This file too

2024-11-08 15:13 UTC, r-tome commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.html
> +              params.managedByOrganization === false)
Makes sense, I've made that change across all conditions

2024-11-08 15:16 UTC, BTreston approved these changes

2024-11-11 10:51 UTC, merged