Move kdf to km ownership
bitwarden/clients pull request #11877
Opened 2024-11-06 14:07 UTC by quexten

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-11-07 12:05 UTC, mzieniukbw requested changes

2024-11-07 12:05 UTC, mzieniukbw commented on libs/key-management/src/models/kdf-config.ts
> +import { KdfType } from "../../../common/src/platform/enums/kdf-type.enum";
❓  Shouldn't we own `KdfType` too ?

2024-11-07 12:05 UTC, mzieniukbw commented on libs/common/src/auth/services/key-connector.service.ts
>  import { KeyService } from "../../../../key-management/src/abstractions/key.service";
Use `@bitwarden/key-management`

2024-11-07 12:05 UTC, mzieniukbw commented on libs/common/src/auth/services/user-verification/user-verification.service.spec.ts
>  import { KeyService } from "../../../../../key-management/src/abstractions/key.service";
Use `@bitwarden/key-management`

2024-11-07 12:05 UTC, mzieniukbw commented on libs/common/src/auth/services/user-verification/user-verification.service.ts
>  import { KeyService } from "../../../../../key-management/src/abstractions/key.service";
Use `@bitwarden/key-management`

2024-11-07 12:05 UTC, mzieniukbw commented on libs/common/src/tools/send/services/send.service.ts
>  import { KeyService } from "../../../../../key-management/src/abstractions/key.service";
Use `@bitwarden/key-management`

2024-11-07 12:05 UTC, mzieniukbw commented on libs/common/tsconfig.json
> +    "../key-management/src/kdf-config.service.ts"
❓ Can't we just do this ? `"../key-management/src/index.ts"`

2024-11-07 16:40 UTC, jrmccannon approved these changes
Changes to admin console code are good.

2024-11-08 11:51 UTC, djsmith85 reviewed
Tools changes look good, besides the one thing @mzieniukbw already commented on

2024-11-08 12:53 UTC, mzieniukbw commented on apps/desktop/src/app/services/services.module.ts
> +  KdfConfigService as KdfConfigServiceAbstraction,
❓ Shouldn't this be instead:
```
DefaultKdfConfigService,
KdfConfigService
```

2024-11-08 13:25 UTC, mzieniukbw approved these changes

2024-11-08 13:39 UTC, djsmith85 approved these changes
Approving for tools

2024-11-11 17:13 UTC, Jingo88 approved these changes

2024-11-12 14:52 UTC, JaredSnider-Bitwarden approved these changes

2024-11-14 19:38 UTC, jrmccannon approved these changes

2024-11-21 12:45 UTC, merged