[PM-12049] Remove usage of ActiveUserState from folder service
bitwarden/clients pull request #11880
Opened 2024-11-06 15:52 UTC by gbubemismith

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-11-08 17:49 UTC, gbubemismith commented on libs/common/src/vault/services/key-state/folder.state.ts
> +    const decryptFolderPromises = folders.map((f) => f.decryptWithKey(userKey, encryptService));
ℹ️  @bitwarden/team-platform-dev changed folder decryption to use `decryptWithKey` instead of the `decrypt` method.

2024-11-08 17:51 UTC, gbubemismith commented on libs/common/src/vault/services/folder/folder.service.ts
> +      takeWhile((userId) => userId != null),
ℹ️ @bitwarden/team-platform-dev added `takeWhile` operator to stop folder state observations when userId becomes invalid (during logout)

2024-11-08 17:54 UTC, gbubemismith commented on libs/common/src/vault/services/folder/folder.service.ts
> +      takeWhile((userId) => userId != null),
ℹ️ @bitwarden/team-platform-dev added `takeWhile` operator to stop folder state observations when userId becomes invalid (during logout)

2024-11-12 19:00 UTC, gbubemismith commented on libs/importer/src/components/import.component.ts
> +      .folderViews$(this.activeUserId$)
We use `takeWhile` which immediately completes the stream when userId is null/undefined.

2024-11-12 19:01 UTC, audreyality commented on libs/importer/src/components/import.component.ts
> +      .folderViews$(this.activeUserId$)
Thanks! 😄

2024-11-12 19:02 UTC, audreyality approved these changes

2024-11-15 00:23 UTC, shane-melton reviewed
Nice work on this so far! 

I mostly just left a couple thoughts/comments on my concern with mixing `Observable<UserId>` and `UserId` arguments to the `FolderService`. They're not hard change requests, but I think it something we should consider / discuss further.

Also, I do think we'll need to introduce the same `UserId` requirement to the `FolderApiService` to ensure we are always using the same userId throughout a submission.

2024-11-15 00:23 UTC, shane-melton commented on libs/common/src/vault/services/folder/folder.service.ts
> +  folderViews$(userId$: Observable<UserId>): Observable<FolderView[]> {
💭 I'm hesitant to update this interface to accept an `Observable<UserId>`. There is a chance users of the service could be combining the results of `folderViews$` with other service observables. For example:

```ts
combineLatest([
  folderService.folderViews$(accountService.activeUserId$), 
  cipherService.cipherViews$(accountService.activeUserId$)
])
```

If this happens and `activeUserId$` emits, it could lead to `folderView$()` emitting before `cipherViews$()` (because folders are typically fewer/smaller so faster to decrypt than ciphers). If that happens then the `combineLatest` will emit with `[newUserIdFolderViews, oldUserIdCipherViews]` and the consumer could be inadvertently mixing user data.

By requiring a specific `userId` we help protect consumers / encourage them to ensure they have an unchanging userId for all of their services.

Open to other's thoughts on this. There was a related conversation in Slack [here](https://bitwarden.slack.com/archives/C02LPDKPML6/p1731419911601229?thread_ts=1731376762.928409&cid=C02LPDKPML6) and a good [StackBlitz example](https://stackblitz.com/edit/xhfr9b?devToolsHeight=33&file=index.ts) of the potential issue from Justin.

2024-11-15 00:23 UTC, shane-melton commented on libs/common/src/vault/services/folder/folder.service.ts
> +  async get(id: string, userId$: Observable<UserId>): Promise<Folder> {
💭 🎨  We're immediately taking the `firstValueFrom` this `userId$` observable (via `this.folders$()`). Imo it would be more clear to simply accept an unchanging `UserId`.

2024-11-15 00:23 UTC, shane-melton commented on libs/common/src/vault/services/folder/folder.service.ts
> +  async upsert(folderData: FolderData | FolderData[], userId: UserId): Promise<void> {
💭 This makes sense to me. It implies that the user of the service knows they're updating a specific user's folder and not just the latest from the `activeUserId$` stream. But, now it seems kind of odd that we have some methods taking `UserId` and others taking `Observable<UserId>`. It makes me more inclined to be consistent and use `UserId` everywhere. What do you think?

2024-11-15 00:23 UTC, shane-melton commented on apps/browser/src/vault/popup/settings/folders-v2.component.ts
> +    this.folders$ = this.folderService.folderViews$(this.activeUserId$).pipe(
💭 I'm not sure what we gain by making the `folderViews$` reactive to / depend on the `activeUserId$`. 

If the `acitveUserId$` changes, we're almost certainly navigating away to another page (lock/logout) and the view will be destroyed very soon after. To avoid needing to await a `firstValueFrom(this.activeUserId$)` we could `pipe`/`switchMap` to the `folderService.folderViews(activeUserId)` instead.

2024-11-19 18:41 UTC, gbubemismith commented
> Nice work on this so far!
> 
> I mostly just left a couple thoughts/comments on my concern with mixing `Observable<UserId>` and `UserId` arguments to the `FolderService`. They're not hard change requests, but I think it something we should consider / discuss further.
> 
> Also, I do think we'll need to introduce the same `UserId` requirement to the `FolderApiService` to ensure we are always using the same userId throughout a submission.

Yeah I agree with simplifying it to a single user id. The simpler userId approach makes things more predictable 👍🏼

2024-11-19 18:46 UTC, gbubemismith commented on libs/importer/src/components/import.component.ts
> +    this.folders$ = this.activeUserId$.pipe(
@audreyality does `folder$` need to react to user changes in this component? or we could simplify to:


```ts
const activeUserId = await firstValurFrom(this.activeUserId$);
this.folders$ = this.folderService.folderViews(userId)
  .pipe(map(folders => folders.filter(f => f.id != null)));

```

2024-11-19 18:59 UTC, audreyality commented on libs/importer/src/components/import.component.ts
> +    this.folders$ = this.activeUserId$.pipe(
There's no guarantee that a component will be destroyed when the user changes; that's just how it works right now. I'd like to keep the complexity since observables are more resilient to change than promises.

2024-11-19 20:56 UTC, audreyality approved these changes

2024-11-19 22:02 UTC, addisonbeck approved these changes
LGTM, but a review from @justindbaur would be smart

2024-11-22 20:45 UTC, Thomas-Avery submitted a review, later dismissed
KM changes look good.

2024-11-26 17:20 UTC, justindbaur requested changes
Looks good, just one recommendation for the changes in sync service.

2024-11-26 17:20 UTC, justindbaur commented on libs/common/src/platform/sync/core-sync.service.ts
I think it would be better to change these methods to take a `userId: UserId` parameter which can be given the value `payloadUserId` from inside `NotificationsService`. Although it's true that the notification always comes from the active user today we may change it in the future where background locked users can receive push notifications.

2024-11-26 20:08 UTC, justindbaur approved these changes

2024-11-26 21:12 UTC, Thomas-Avery approved these changes

2024-11-26 21:51 UTC, shane-melton approved these changes
Changes look great! Really nice work on this!

2024-11-27 14:30 UTC, audreyality approved these changes

2024-11-27 18:16 UTC, addisonbeck submitted a review, later dismissed

2024-12-02 16:25 UTC, jprusik approved these changes
Approved for Autofill concerns

2024-12-20 16:23 UTC, audreyality approved these changes
📝 No changes to tools files since my last review!

2024-12-20 17:13 UTC, rr-bw submitted a review, later dismissed

2024-12-23 19:53 UTC, justindbaur requested changes

2024-12-23 19:53 UTC, justindbaur commented on libs/common/src/platform/state/state-definitions.ts
> +export const FOLDER_MEMORY = new StateDefinition("decryptedFolders", "memory");
Folders aren't countable and a user could have many of them, for that reason we should use the memory implementation with infinite space on browser. 

```suggestion
export const FOLDER_MEMORY = new StateDefinition("decryptedFolders", "memory", {
  browser: "memory-large-object",
});
```

2024-12-23 19:55 UTC, jprusik submitted a review, later dismissed

2024-12-23 20:55 UTC, shane-melton reviewed
Looks good! But we do need to make [Justin's suggested change](https://github.com/bitwarden/clients/pull/11880/files/134a6ca2036618b8a7c4b9baa560698343882efe..2a921e3a3ecafdbf082ebea3607bf66f7cd38498#r1896078754).

2024-12-23 23:50 UTC, shane-melton approved these changes

2024-12-24 14:03 UTC, audreyality reviewed
Please wait to tag me in until you've addressed all required changes. 😄

2024-12-24 16:33 UTC, audreyality approved these changes

2024-12-24 18:54 UTC, shane-melton approved these changes

2024-12-26 14:28 UTC, justindbaur approved these changes

2024-12-26 23:17 UTC, rr-bw approved these changes

2024-12-27 15:19 UTC, addisonbeck approved these changes

2025-01-02 16:40 UTC, jprusik approved these changes

2025-01-02 16:41 UTC, Thomas-Avery approved these changes

2025-01-02 22:16 UTC, merged

2025-01-30 19:20 UTC, cd-bitwarden commented on apps/cli/src/commands/get.command.ts
> +      let folders = await this.folderService.getAllDecryptedFromState(activeUserId);
check this, were we getting all folders before for all users?