Ac/pm 12273 integration page
bitwarden/clients pull request #11883
Opened 2024-11-06 18:55 UTC by BTreston

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-12273

## 📔 Objective

This PR adds a new Integrations page in Admin console and refactors the Integration Card and Integration Grid components from living in Secrets Manager to living the in Shared Components.

## 📸 Screenshots

Uploading Screen Recording 2024-11-06 at 1.49.56 PM.mov…

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-11-13 03:14 UTC, eliykat requested changes
Great work!

I'm surprised we don't have any Storybook stories for the integration grid and card. Can you please add these? There are lots of examples (files ending in `.stories.ts`), or check out the Storybook [documentation](https://storybook.js.org/docs/get-started/whats-a-story). That way it will show up at https://components.bitwarden.com (or `npm run storybook` locally).

Also, some of the logos look quite dark in dark mode (from your video). Can you please discuss with design and see if we can fix that somehow?

2024-11-13 03:14 UTC, eliykat commented on apps/web/src/app/shared/components/integrations/integration-grid/integration-grid.component.html
> +    attr.aria-label="open the {{ integration.name }} implementation guide in a new tab"
I'm not sure these are universally applicable. Looking at the Secrets Manager integration page, many of the links are links to Github repos, not implementation guides. Can you check with design what they want the wording to be for SM?

Assuming it does need to be different for different use cases, we need to figure out how to make it more generic. My first thought is that you could use some `@Input` properties to provide a callback, which takes an `Integration` object and returns the fully i18n'd title / tooltip.

That also avoids adding the `i18nService` and pipe as a dependency to these components, which isn't a huge deal, but it does keep them simpler and easier to test.

2024-11-13 03:14 UTC, eliykat commented on apps/web/src/app/shared/components/integrations/integration-grid/integration-grid.component.html
> +    attr.aria-label="open the {{ integration.name }} implementation guide in a new tab"
Also, aria attributes should also be i18n'd.

2024-11-13 03:14 UTC, eliykat commented on apps/web/src/app/shared/components/integrations/integration-card/integration-card.component.spec.ts
Please add tests to cover new tooltip / aria behavior.

2024-11-13 03:14 UTC, eliykat commented on apps/web/src/app/shared/index.ts
> +export * from "./components/integrations/integrations.module";
Ideally you should have barrel files at each level, e.g. this would `export * from "./components"`, then components would `export * from "./integrations"`.

2024-11-13 03:14 UTC, eliykat commented on apps/web/src/app/shared/components/integrations/models.ts
> +  linkText?: string;
Does the component template require any changes to account for `linkText` potentially being undefined? It looks like we'd be left with an empty anchor tag at the moment.

2024-11-13 17:00 UTC, BTreston commented on apps/web/src/app/shared/components/integrations/integration-card/integration-card.component.html
Confirmed, The new design will also remove the hyper link form the secrets manager integration page. Adding updated video demo.

2024-11-13 17:10 UTC, BTreston commented on apps/web/src/app/shared/components/integrations/models.ts
> +  linkText?: string;
The existing styling on the anchor tag in the integration-card.component.html ensures the link encompasses the entire area of the card. In a followup with PM, it was decided to remove the hyperlink to bring the display of SM and AC inline with one another. This property will be removed as it is no longer needed.

2024-11-14 16:36 UTC, justindbaur approved these changes

2024-11-15 04:45 UTC, eliykat requested changes

2024-11-15 04:45 UTC, eliykat commented on apps/web/src/locales/en/messages.json
> +    "description": "This represents the beggining of a sentence. The full sentence will be 'Configure single sign-on for Bitwarden using the implementation guide for your Identity Provider."
typo: beggining
Also below

2024-11-15 04:45 UTC, eliykat commented on bitwarden_license/bit-web/src/app/secrets-manager/integrations/integrations.component.ts
Please delete these i18n strings from `messages.json` if they're not used anywhere else.

2024-11-15 04:45 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/integrations/integrations.pipe.ts
I think this could be in `shared/components/integrations` for re-use.

2024-11-15 04:45 UTC, eliykat commented on apps/web/src/app/shared/components/integrations/integration-grid/integration-grid.component.spec.ts
> +          useValue: mock<I18nService>({ t: (key) => key }),
Optional: it would be nice to confirm that the integration name was also passed in. Maybe something like `(key, p1) => key + " " + p1` so that you can assert both.

2024-11-15 04:45 UTC, eliykat commented on apps/web/src/app/shared/index.ts
Please use this barrel file to export what you need, e.g. your standalone components. Then update the imports to use the barrel file (the folder level) instead of specific files.

2024-11-15 04:45 UTC, eliykat commented on bitwarden_license/bit-web/src/app/secrets-manager/integrations/integrations.component.spec.ts
> +import { IntegrationGridComponent } from "@bitwarden/web-vault/src/app/shared/components/integrations/integration-grid/integration-grid.component";
Note to self: this needs to be fixed. (I know you know.)

2024-11-15 04:45 UTC, eliykat commented on apps/web/src/app/shared/components/integrations/integration-card/integration-card.stories.ts
> +        },
The card name isn't displaying properly in storybook in dark mode:

![Screenshot 2024-11-15 at 2 30 59 PM](https://github.com/user-attachments/assets/0bbeb634-3be9-4efc-9e08-8d7e3e31970d)

Maybe it's due to this mock? It doesn't respect the storybook iframe theming. Looking at other components, I can see a hack here which _may_ be related: https://github.com/bitwarden/clients/blob/main/apps/browser/src/auth/popup/extension-anon-layout-wrapper/extension-anon-layout-wrapper.stories.ts#L60-L67. If not, please ask in `#code`. (not sure myself)

2024-11-15 04:45 UTC, eliykat commented on apps/web/src/app/shared/components/integrations/integration-card/integration-card.stories.ts
> +    linkURL: "",
Please use a test image and link. Maybe one of the Bitwarden logos in `web/src/images` (if that will work), and a link to our homepage. Just so we're not using someone else's image as a test image, but we can still have an accurate depiction of the component.

2024-11-15 04:45 UTC, eliykat commented on apps/web/src/app/shared/components/integrations/integration-card/integration-card.stories.ts
> +  title: "Web/Integration Card",
Please put these 2 stories in their own section: `Web/Integration Layout/`

2024-11-15 04:45 UTC, eliykat commented on apps/web/src/app/shared/components/integrations/integration-grid/integration-grid.stories.ts
Same comments as above re: theming and using proper images and links.

2024-11-15 10:28 UTC, Hinton commented on apps/web/src/images/integrations/authenticator-icon-solid.svg
Please minify each svg image. You can use https://svgomg.net/

2024-11-15 15:54 UTC, BTreston commented on apps/web/src/app/shared/components/integrations/integration-card/integration-card.stories.ts
> +        },
The text in the template was missing the `tw-text-main` style class.

2024-11-18 04:22 UTC, eliykat requested changes

2024-11-18 04:22 UTC, eliykat commented on apps/web/src/app/shared/components/integrations/integration-card/integration-card.stories.ts
> +      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Bitwarden_logo.svg/512px-Bitwarden_logo.svg.png",
We can't link to an external site here - it will make our UI tests flaky because they'll depend on this URL remaining up-to-date and available. Is there any reason we can't use any of our own images in the repo?

2024-11-18 04:22 UTC, eliykat commented on apps/web/src/locales/en/messages.json
> +    "description": "This represents the begining of a sentence, broken up to include links. The full sentence will be 'Configure single sign-on for Bitwarden using the implementation guide for your I
```suggestion
    "description": "This represents the beginning of a sentence, broken up to include links. The full sentence will be 'Configure single sign-on for Bitwarden using the implementation guide for your Identity Provider."
```

2024-11-18 04:22 UTC, eliykat commented on apps/web/src/locales/en/messages.json
> +    "description": "This represents the begining of a sentence, broken up to include links. The full sentence will be 'Configure SCIM (System for Cross-domain Identity Management) to automatically pr
```suggestion
    "description": "This represents the beginning of a sentence, broken up to include links. The full sentence will be 'Configure SCIM (System for Cross-domain Identity Management) to automatically provision users and groups to Bitwarden using the implementation guide for your Identity Provider"
```

2024-11-18 04:22 UTC, eliykat commented on apps/web/src/app/shared/index.ts
[This comment](https://github.com/bitwarden/clients/pull/11883#discussion_r1843171053) still needs to be addressed, please let me know if you want to discuss.

2024-11-19 00:32 UTC, eliykat submitted a review, later dismissed
Great work, I appreciate you taking the time to tighten up the implementation and write stories.

There is one last thing to do: review (and approve) the changes in Chromatic. See the process here: https://contributing.bitwarden.com/contributing/pull-requests/chromatic but let me know if you have any questions. It's important that you do this before you merge, otherwise `main` will have unapproved Chromatic changes and it'll leak into everyone's development branches. (You can still approve it from `main`, it's just more disruptive to other devs.)

Once Chromatic changes are approved, the Chromatic PR checks should have a green tick next to them.

I see that there is some visual change (in Chromatic) to the Kitchen Sink story, but it seems minor and I can't see that you've done anything to cause it. But to be safe, I recommend asking `#team-eng-design-system` about that one. (EDIT: or something for @bitwarden/team-design-system to check when they review)

2024-11-19 00:32 UTC, eliykat commented on .storybook/main.ts
> +  staticDirs: ["../apps/web/src/images"],
I had no idea you had to do this, so nice work figuring it out.

2024-11-19 14:34 UTC, willmartian submitted a review, later dismissed
DS changes looks good 👍 

Had a few non-blocking thoughts on other files:

2024-11-19 14:34 UTC, willmartian commented on apps/web/src/app/admin-console/organizations/integrations/integrations.component.html
> +        [integrations]="integrationsList | filterIntegrations: IntegrationType.SSO"
🎨  Why a custom pipe? Why not:

```ts
const integrationsList = [...];
const ssoList = integrationsList.filter(integration => integration.type === IntegrationType.SSO);
```

2024-11-19 14:34 UTC, willmartian commented on apps/web/src/app/admin-console/organizations/integrations/integrations.component.html
> +    <section class="tw-mb-9">
There is also a `bit-section` component in the DS if you want consistent spacing with other sections in the app. Not sure if this needs to be different or not. cc @bitwarden/dept-design

2024-11-19 14:34 UTC, willmartian commented on apps/web/src/app/admin-console/organizations/integrations/integrations.component.ts
> +        name: "AD FS",
⛏️ Why set this in the constructor vs directly in the property declaration?

2024-11-19 14:34 UTC, willmartian commented on apps/web/src/app/shared/components/integrations/integration-card/integration-card.stories.ts
Thanks for writing a story 👏

2024-11-19 14:51 UTC, BTreston commented on apps/web/src/app/admin-console/organizations/integrations/integrations.component.html
> +        [integrations]="integrationsList | filterIntegrations: IntegrationType.SSO"
These were originally getters doing a similar thing you described. This was changed over on [this recommendation](https://github.com/bitwarden/clients/pull/11883#discussion_r1839285142). Probably because the number of local variables seemed to be getting a bit long and there may be more added to the list in the future.

2024-11-19 14:52 UTC, BTreston commented on apps/web/src/app/admin-console/organizations/integrations/integrations.component.ts
> +        name: "AD FS",
This pattern was copied from the existing secrets manager component. I have no strong preference over initializing in the constructor vs on declaration.

2024-11-21 16:55 UTC, willmartian submitted a review, later dismissed
DS changes look good 👍

2024-11-22 00:41 UTC, eliykat approved these changes

2024-11-22 15:47 UTC, Hinton commented
Images are minified, no concerns from my side.

2024-11-25 03:53 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/layouts/organization-layout.component.ts
> +      withLatestFrom(
I think `combineLatest` is a better fit here. It will emit all new values when _any_ source observable emits, which is better for independent observables (e.g. an org and a feature flag state - you need both but they emit independently).

With your current use of `withLatestFrom`, if the feature flag updates during execution, it won't emit a new value until and unless the `organization$` observable emits a new value (which it might never do, so you never get an updated emission).

2024-11-25 03:53 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/layouts/organization-layout.component.ts
> +          org.productTierType === ProductTierType.Enterprise && featrueFlagEnabled,
Is this right? Some integrations listed are available for Free and Teams orgs (e.g. Directory Connector is available for Teams, SM integrations are available for all plan types to my knowledge). We might need more granular logic for each section within the integration page. Can you check with Priya?

If that does need further work, you might consider merging your initial work (given that it's behind a feature flag) and then making these further changes in a separate PR.

2024-11-25 03:54 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/layouts/organization-layout.component.ts
> +          org.productTierType === ProductTierType.Enterprise && featrueFlagEnabled,
Navigation permissions should also be enforced at the routing level, see `organizationPermissionsGuard`. (There are lots of example uses.)

2024-11-26 18:33 UTC, BTreston commented on apps/web/src/app/admin-console/organizations/layouts/organization-layout.component.ts
> +          org.productTierType === ProductTierType.Enterprise && featrueFlagEnabled,
@eliykat I've added the routing permissions and will merge this if its good to go. The org tier logic will come in a followup PR.

2024-11-27 02:23 UTC, eliykat submitted a review, later dismissed

2024-12-03 16:54 UTC, vleague2 reviewed
Is the grid story supposed to be overlapped like this?

![Screenshot 2024-12-03 at 11 50 53 AM](https://github.com/user-attachments/assets/df232383-e4c4-4051-9d4b-dacd62b8ab7a)

2024-12-03 18:05 UTC, vleague2 approved these changes

2024-12-04 01:30 UTC, eliykat approved these changes

2024-12-05 00:16 UTC, eliykat approved these changes

2024-12-05 15:09 UTC, justindbaur approved these changes

2024-12-05 15:09 UTC, merged