[PM-13346] Email notification impacts
bitwarden/clients pull request #11967
Opened 2024-11-12 12:03 UTC by cyprain-okeke

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-13346

## 📔 Objective

Send email once policy is turned on to all members who have a free Families plan through the organization. This will only be sent to members who have activated the sponsorship.

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-11-13 20:11 UTC, jonashendrickx approved these changes

2024-11-14 09:35 UTC, r-tome requested changes
It seems like there's some changes from https://github.com/bitwarden/clients/pull/11894 so change this PR to target that branch, please.

It would be great if you could add some screenshots.

2024-11-14 09:35 UTC, r-tome commented on apps/web/src/app/admin-console/organizations/sponsorships/accept-family-sponsorship.component.ts
>        // FIXME: Verify that this floating promise is intentional. If it is, add an explanatory comment and ensure there is proper error handling.
Its no longer a floating promise so these comments can be removed

2024-11-14 10:06 UTC, cyprain-okeke commented on apps/web/src/app/admin-console/organizations/sponsorships/accept-family-sponsorship.component.ts
>        // FIXME: Verify that this floating promise is intentional. If it is, add an explanatory comment and ensure there is proper error handling.
removed

2024-11-14 11:40 UTC, r-tome approved these changes
I think there's a couple more comments to remove. Other than that I think it looks good!

2024-11-14 11:40 UTC, r-tome commented on apps/web/src/app/admin-console/organizations/sponsorships/accept-family-sponsorship.component.ts
>      // eslint-disable-next-line @typescript-eslint/no-floating-promises
Are these still needed?

2024-11-14 11:40 UTC, r-tome commented on apps/web/src/app/admin-console/organizations/sponsorships/accept-family-sponsorship.component.ts
>        // eslint-disable-next-line @typescript-eslint/no-floating-promises
This should be deleted too, I think

2024-11-14 12:29 UTC, cyprain-okeke commented on apps/web/src/app/admin-console/organizations/sponsorships/accept-family-sponsorship.component.ts
>        // eslint-disable-next-line @typescript-eslint/no-floating-promises
removed

2024-11-14 12:29 UTC, cyprain-okeke commented on apps/web/src/app/admin-console/organizations/sponsorships/accept-family-sponsorship.component.ts
>      // eslint-disable-next-line @typescript-eslint/no-floating-promises
removed

2024-11-14 12:34 UTC, merged