[PM-14219] Add service for new device verification notice
bitwarden/clients pull request #11988
Opened 2024-11-13 20:02 UTC by Jingo88

## 🎟️ Tracking

[PM-14219](https://bitwarden.atlassian.net/browse/PM-14219)

## 📔 Objective

Added service for New Device Verification Notice. Components and Routeguards that will use this are being implement next. 

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-11-13 20:11 UTC, shane-melton requested changes

2024-11-13 20:11 UTC, shane-melton commented on libs/vault/src/services/new-device-verification-notice.service.ts
> +    this.noticeState = this.stateProvider.getActive(NEW_DEVICE_VERIFICATION_NOTICE_KEY);
⚠️ We're moving away from `ActiveUserState` and should require a `userId` for service methods/state. Something like 
```ts
noticeState$(userId: userId) {
  return this.stateProvider.getUser(userId, NEW_DEVICE_VERIFICATION_NOTICE_KEY).state$;
}
```

2024-11-13 20:11 UTC, shane-melton commented on libs/vault/src/services/new-device-verification-notice.service.ts
> +  last_dismissal: string;
❓ What type of values will `last_dismissal` hold? Is it a date?

2024-11-13 20:11 UTC, shane-melton commented on libs/vault/src/services/new-device-verification-notice.service.ts
> +export type NewDeviceVerificationNotice = {
🎨 We should add some documentation on what these values represent / how they're expected to be used.

2024-11-13 20:43 UTC, gbubemismith commented on libs/vault/src/services/new-device-verification-notice.service.ts
> +    this.noticeState = this.stateProvider.getActive(NEW_DEVICE_VERIFICATION_NOTICE_KEY);
You can reference [this](https://github.com/bitwarden/clients/pull/11543/files#diff-2e58715e812bd8e9d38a0a222f54a6b8df07c6483cb0fdb0e640eae8737b1a95R155)

2024-11-14 14:09 UTC, coroiu approved these changes
State definition looks ok

2024-11-14 22:51 UTC, shane-melton commented on libs/vault/src/services/new-device-verification-notice.service.ts
> +  noticeState$(userId$: Observable<UserId>): Observable<NewDeviceVerificationNotice> {
💭 I think we may want to just accept a single `UserId` instead of `Observable<UserId>`. For reference there is some recent discussion on this [here](https://bitwarden.slack.com/archives/C02LPDKPML6/p1731419911601229?thread_ts=1731376762.928409&cid=C02LPDKPML6).

But, from my understanding, by accepting an observable, there is a greater chance we run into the same issue we're trying to avoid by moving away from `ActiveUserState` (race conditions with different userIds during account switching or lock/logout). 

cc: @justindbaur In case you have any more insight here.

2024-11-15 17:17 UTC, shane-melton approved these changes

2024-11-18 16:56 UTC, gbubemismith approved these changes

2024-11-19 09:53 UTC, coroiu approved these changes
No changes to platform code, approving!

2024-11-19 15:04 UTC, merged