[CL-269] extension router transitions
bitwarden/clients pull request #11989
Opened 2024-11-14 04:35 UTC by willmartian

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/CL-269

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-11-14 04:37 UTC, willmartian commented on apps/browser/src/popup/app-routing.module.ts
Regexp find & replace for the win 😎

2024-11-19 00:15 UTC, willmartian commented
@vleague2 I still need to tweak the actual animation that is being displayed, but what do you think of this elevation abstraction?

2024-11-19 17:10 UTC, vleague2 reviewed
I like the approach!! Looks much simpler and consistent

2024-11-19 17:10 UTC, vleague2 commented on apps/browser/src/popup/app.component.ts
> -    } else if (outlet.activatedRouteData.state === "ciphers") {
Is all this cipher stuff covered in the new elevation flows?

2024-11-19 23:47 UTC, willmartian commented on apps/browser/src/popup/app.component.ts
> -    } else if (outlet.activatedRouteData.state === "ciphers") {
Yes. It isn't necessary anymore.

2024-11-19 23:52 UTC, willmartian commented on apps/browser/src/popup/app-routing.animations.ts
> -}
These bound functions confused me more than helped.

2024-11-20 16:34 UTC, vleague2 approved these changes
Love it

2024-11-26 22:10 UTC, danielleflinn requested changes
✅ Animations slide in from left, on top of previous page for majority of pages
✅ No animation when navigating between the View and Edit item pages 
✅ Account switcher slides in from top 
⛔️ When viewing an item in the Trash, the "Trash" view slides out to reveal the View item page; then slides back over the View item when the user selects "back". The View item page should slide in, on top of the "Trash" view, then slide out when the user navigates back.

2024-11-27 15:51 UTC, willmartian commented
> ⛔️ When viewing an item in the Trash, the "Trash" view slides out to reveal the View item page; then slides back over the View item when the user selects "back". The View item page should slide in, on top of the "Trash" view, then slide out when the user navigates back.

Fixed with [aee101c](https://github.com/bitwarden/clients/pull/11989/commits/aee101c051dc6bbc37a6f37e49e32c0fa0c77e60) @danielleflinn

2024-11-27 16:48 UTC, danielleflinn requested changes
@willmartian thanks for fixing the Trash view bug. I got some last minute feedback, for now we want to update the Account switcher transition to also be slide in from right to remain consistent with the other animations. Once we have that change we are good to go to merge. Thanks!

2024-11-27 19:15 UTC, vleague2 approved these changes

2024-11-27 20:32 UTC, danielleflinn approved these changes
This looks great! Thanks for all your efforts with this on @willmartian 🎉

2024-11-27 20:33 UTC, merged