[PM-4816] Create shared LoginApprovalComponent
bitwarden/clients pull request #11982
Opened 2024-11-13 14:02 UTC by alec-livefront

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-4816?atlOrigin=eyJpIjoiMzE0Yjg5YjFhYTViNGY0M2E4M2YyY2MyNjg3YTFhMWYiLCJwIjoiaiJ9

## 📔 Objective

Moves the `LoginApprovalComponent` to `libs/auth` and moves desktop-specific logic to a service.

## 📸 Screenshots

<img width="1141" alt="Screenshot 2024-11-13 at 8 01 27 AM" src="https://github.com/user-attachments/assets/6d754351-8341-4aad-9b30-bc32f7a22ec1">

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-11-14 16:54 UTC, JaredSnider-Bitwarden requested changes
Great start on this! Some feedback below:

2024-11-14 16:54 UTC, JaredSnider-Bitwarden commented on libs/auth/src/common/abstractions/login-approval.service.abstraction.ts
Can we rename this to be `LoginApprovalComponentServiceAbstraction`?

2024-11-14 16:54 UTC, JaredSnider-Bitwarden commented on apps/desktop/src/auth/login/desktop-login-approval.service.ts
> +    await ipc.auth.loginRequest(
This has lost the original `isVisible` logic. This should only fire if the desktop window is  not visible.

2024-11-14 16:54 UTC, JaredSnider-Bitwarden commented on apps/desktop/src/auth/login/desktop-login-approval.service.ts
> +  async onInit(loginApprovalComponent: LoginApprovalComponent): Promise<void> {
I think we can avoid passing the component as a parameter here. Can we rename this method to be something like: `showLoginRequestedAlertIfWindowNotVisible()` and keep it as a no-op in the default implementation?

2024-11-14 19:39 UTC, alec-livefront commented on libs/auth/src/common/abstractions/login-approval.service.abstraction.ts
[a06d401](https://github.com/bitwarden/clients/pull/11982/commits/a06d401b6c4071cdfe1fec2baf66f24829e5f53a)

Should we update the other classes to contain `Component` too?

2024-11-14 19:41 UTC, JaredSnider-Bitwarden commented on apps/desktop/src/auth/login/desktop-login-approval.service.ts
> +  async onInit(loginApprovalComponent: LoginApprovalComponent): Promise<void> {
Yes, passing an individual email vs the entire component context is a better solution.

2024-11-14 19:49 UTC, alec-livefront commented on apps/desktop/src/auth/login/desktop-login-approval.service.ts
> +    await ipc.auth.loginRequest(
89ab519fe15f85eb795509f39643bea83cc2c1f9

2024-11-14 19:50 UTC, JaredSnider-Bitwarden commented on libs/auth/src/common/abstractions/login-approval.service.abstraction.ts
Yes, please.

2024-11-14 21:06 UTC, alec-livefront commented on libs/auth/src/common/abstractions/login-approval.service.abstraction.ts
[f0ccf69](https://github.com/bitwarden/clients/pull/11982/commits/f0ccf696647d5346900c7b77714dd1d0b3889ac8)

2024-11-15 17:48 UTC, micahblut commented
@alec-livefront I notice this doesn't show the environment the request is coming from like the design does. It also looks like the spacing between "login attempt by" and "fingerprint phrase" is off. Finally, could you send me a screenshot with the updated styles?

2024-11-15 21:35 UTC, JaredSnider-Bitwarden approved these changes
LGTM! Nice testing work as well!

2024-11-15 21:45 UTC, alec-livefront commented
@micahblut the original screenshot didn't have the correct spacing - I've updated with a screen recording which should show the correct spacing now. Could you elaborate on the environment? I'm not sure I see that in the screenshot attached to the ticket/

2024-11-18 18:39 UTC, justindbaur approved these changes

2024-11-22 18:55 UTC, merged