[PM-14964] revert passphrase minimum
bitwarden/clients pull request #12019
Opened 2024-11-15 23:41 UTC by audreyality

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-14964

## 📔 Objective

Revert 0254550b07277be7f0d6fedcd862b462e80947a3 and explain recommended boundaries using hint text.

## 📸 Screenshots

No policy; value exceeds recommended value:

<img width="376" alt="image" src="https://github.com/user-attachments/assets/ad9f52e3-6119-42cf-a020-d537a7b3ff9f">

<img width="376" alt="image" src="https://github.com/user-attachments/assets/288e014c-4b82-4c2a-8313-d248fe20a170">

No policy; value less than or equal to recommended value:

<img width="376" alt="image" src="https://github.com/user-attachments/assets/c257140c-7cae-453b-a8b6-5b4aba30a836">

<img width="376" alt="image" src="https://github.com/user-attachments/assets/21e6edc6-f266-4ec2-9eff-6d67da7fe330">

With policy; value exceeds recommended value:

<img width="376" alt="image" src="https://github.com/user-attachments/assets/6a2a174a-ec6c-48d3-9629-b47c3da77609">

<img width="376" alt="image" src="https://github.com/user-attachments/assets/efeb745a-099d-49ae-bd69-011862ba22ce">

With policy' value less than or equal to recommended value:

<img width="376" alt="image" src="https://github.com/user-attachments/assets/b6f218da-f81c-410f-95f3-225802b356b3">

<img width="376" alt="image" src="https://github.com/user-attachments/assets/675d01f9-c676-4d28-82b4-55db681a8d67">

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-11-15 23:49 UTC, ginat commented
Minimum values should not be changed for password or passphrase generator below 5 characters and 3 words, respectively. Did that mean to happen?

2024-11-15 23:51 UTC, audreyality commented
No. I haven't updated my tests yet, so there's bugs. :/

2024-11-15 23:51 UTC, ginat commented
All good, thank you for getting the PR party started!

2024-11-18 14:38 UTC, audreyality commented
Hi @bwbug. This PR is a hotfix whose scope is limited to reverting the minimum to its prior value. We've gotten some internal feedback about the hint text; that'll be addressed before this ticket merges.

In the meantime, I'm going to mark your comment off-topic so that the PR can focus on code review feedback. Please continue contributing your feedback concerning more substantial revisions using the [community forums thread](https://community.bitwarden.com/t/avoid-arbitrary-length-restrictions-in-generator/75764).

2024-11-18 17:37 UTC, vincentsalucci submitted a review, later dismissed
Changes to AC owned file `password-generator.component` look good 👍

2024-11-18 19:17 UTC, djsmith85 requested changes
Only one thing regarding the hint and the spacing. The rest is looking great!

2024-11-18 19:34 UTC, djsmith85 commented on apps/browser/src/_locales/en/messages.json
> +    "message": " Use $RECOMMENDED$ characters or more to generate a strong password.",
Discussed this offline and is addressed with [9828f29](https://github.com/bitwarden/clients/pull/12019/commits/9828f296d4fe3b6502e3bbeaeaaafd372cdb70bc)

2024-11-18 19:34 UTC, djsmith85 approved these changes

2024-11-18 19:43 UTC, vincentsalucci approved these changes

2024-11-18 19:43 UTC, merged