[CL-508] extension width setting
bitwarden/clients pull request #12040
Opened 2024-11-18 16:29 UTC by willmartian

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-11-18 19:11 UTC, willmartian commented
Whoops, let me fix those broken tests.

2024-11-18 20:12 UTC, vleague2 reviewed
Do we want to have some stories of the popup layout at different widths?

2024-11-18 22:09 UTC, danielleflinn requested changes
Feedback from DS team call: 
- Lets update the field label to "Extension width"
- Lets update the behavior so when the extension is popped out the popout's width defaults to the same as the "Extension width" setting.

2024-11-18 23:09 UTC, willmartian commented
>     * Lets update the field label to "Extension width"

[e56bb8a](https://github.com/bitwarden/clients/pull/12040/commits/e56bb8a3bc9ab3ee4fb48d4b550af915f5523999)

>     * Lets update the behavior so when the extension is popped out the popout's width defaults to the same as the "Extension width" setting.

[ffd8820](https://github.com/bitwarden/clients/pull/12040/commits/ffd8820aa2a2a8aeded33612d5051659628af12c)

2024-11-19 01:18 UTC, danielleflinn submitted a review, later dismissed
✅ Verified label text is expected
 ✅ Verified extension width updated to expected value for each appearance setting option
 ✅ Verified popup and popout width matched based on setting

2024-11-19 16:59 UTC, vleague2 submitted a review, later dismissed

2024-11-20 16:10 UTC, gbubemismith submitted a review, later dismissed

2024-11-20 17:27 UTC, willmartian commented on apps/browser/src/platform/popup/layout/popup-width.service.ts
> +const POPUP_WIDTH_KEY_DEF = new KeyDefinition<PopupWidthOption>(THEMING_DISK, "popup-width", {
@justindbaur When is it appropriate to share state definitions? Width is semantically related to theming, and it feels like we aren't meant to create a new state definition for every little piece of state, right? (Otherwise, why have key definitions at all?)

2024-11-20 18:31 UTC, justindbaur commented on apps/browser/src/platform/popup/layout/popup-width.service.ts
> +const POPUP_WIDTH_KEY_DEF = new KeyDefinition<PopupWidthOption>(THEMING_DISK, "popup-width", {
If you have similar things you can share them but one of the important rules is you shouldn't share them between teams and most likely shouldn't share them to "far" away from each other. Because the problem you could run into is someone else makes a key with the same name within a state definition that someone else does. So I think since this would be in DS ownership it should use its own state definition.

2024-11-22 16:04 UTC, willmartian commented on apps/browser/src/platform/popup/layout/popup-width.service.ts
> +const POPUP_WIDTH_KEY_DEF = new KeyDefinition<PopupWidthOption>(THEMING_DISK, "popup-width", {
Boom: [0fc38b9](https://github.com/bitwarden/clients/pull/12040/commits/0fc38b9209c82f845c5a30b52e3f93b93045b1c2) (thanks)

2024-11-22 17:08 UTC, vleague2 commented on libs/common/src/platform/services/config/default-config.service.ts
> +      return of(true);
Is this an accidental override?

2024-11-22 21:07 UTC, willmartian commented on libs/common/src/platform/services/config/default-config.service.ts
> +      return of(true);
OOF, yes. I thought I stashed that.

2024-11-22 21:48 UTC, vleague2 approved these changes

2024-11-25 17:57 UTC, gbubemismith submitted a review, later dismissed

2024-11-25 18:03 UTC, justindbaur submitted a review, later dismissed
Just one optional comment but otherwise looks good.

2024-11-25 18:23 UTC, willmartian commented on libs/common/src/platform/state/state-definitions.ts
> +export const POPUP_WIDTH_DISK = new StateDefinition("popupWidth", "disk");
Yes, good point. [6f1f799](https://github.com/bitwarden/clients/pull/12040/commits/6f1f799b176cf923516c9daa999cb15346431f98)

2024-11-25 18:25 UTC, gbubemismith approved these changes

2024-11-25 18:29 UTC, justindbaur approved these changes

2024-11-25 19:43 UTC, merged