[PM-13347] Web app impacts
bitwarden/clients pull request #12056
Opened 2024-11-19 19:01 UTC by cyprain-okeke

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-13347

## 📔 Objective

When the Remove Bitwarden Families policy is on, the product will follow the following behaviors depending on the # of organizations the user is part of.

Individual vault impacts - [Scenario 1](https://www.figma.com/proto/XvSu6yBd1AkP01YLQIp8J2/Disable-Families-for-Enterprise-policy?page-id=1%3A12&node-id=5250-4466&node-type=frame&viewport=717%2C513%2C0.05&t=c3oK6XgitCYGfS1o-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=5250%3A4466&show-proto-sidebar=1)

Given the users email address is only associated with 1 enterprise organization, when the policy is turned on, then hide the Free Bitwarden Families page from the navigation

Individual vault impacts - [Scenario 2](https://www.figma.com/proto/XvSu6yBd1AkP01YLQIp8J2/Disable-Families-for-Enterprise-policy?page-id=1%3A12&node-id=5250-4513&node-type=frame&viewport=717%2C513%2C0.05&t=c3oK6XgitCYGfS1o-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=5250%3A4490&show-proto-sidebar=1)

Given the email address is associated with multiple enterprise organization, the policy is turned on, and my sponsorship is status is active, when the user attempts to interact with the three dot menu, then the only option is to remove the sponsorship 

Individual vault impacts - [Scenario 3](https://www.figma.com/proto/XvSu6yBd1AkP01YLQIp8J2/Disable-Families-for-Enterprise-policy?page-id=1%3A12&node-id=5250-4579&node-type=frame&viewport=717%2C513%2C0.05&t=c3oK6XgitCYGfS1o-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=5250%3A4556&show-proto-sidebar=1)

Given the email address is associated with multiple enterprise organization, the policy is turned on, and my sponsorship is status is sent, when the user attempts to interact with the three dot menu, then the only option is to remove the sponsorship and we hide the Resend email option

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-11-20 12:38 UTC, jonashendrickx reviewed
Might need a better pull request title. :-)

2024-11-21 02:43 UTC, eliykat requested changes

2024-11-21 02:43 UTC, eliykat commented on apps/web/src/app/billing/settings/sponsored-families.component.ts
> +      FeatureFlag.IdpAutoSubmitLogin,
Wrong feature flag?

2024-11-21 02:43 UTC, eliykat commented on apps/web/src/app/billing/settings/sponsored-families.component.ts
> +      );
This is quite difficult to understand what's going on here. It is a fairly complex set of operations though. I had to rewrite it myself to be able to provide any feedback here, so here's what I came up with:

```ts
      const getPolicyStatus$ = (org: Organization) =>
        from(
          this.PolicyApiService.getPolicyStatus(org.id, PolicyType.FreeFamiliesSponsorshipPolicy),
        ).pipe(map((policyEnabled) => ({ organization: org, isPolicyEnabled: policyEnabled })));

      this.availableSponsorshipOrgs$ = this.organizationService.organizations$.pipe(
        map((orgs) => orgs.filter((o) => o.familySponsorshipAvailable)),
        switchMap((orgs) => forkJoin(orgs.map((o) => getPolicyStatus$(o)))),
        map((orgsWithPolicies) =>
          orgsWithPolicies.filter(({ isPolicyEnabled }) => !isPolicyEnabled),
        ),
        map((orgsWithPolicies) => orgsWithPolicies.map(({ organization }) => organization)),
      );
```

It actually turned out fairly similar to yours. I'd say the main differences are:
1. filter out orgs without family sponsorships available before calling the api, just to save on api traffic
2. extract the nested api call to its own method to avoid unnecessary nesting. I think maintaining a flat structure to rxjs logic is really important for readability
3. use `forkJoin` instead of `combineLatest`. `forkJoin` will wait for all inner observables to complete, then emit an array of the results, kind of like `Promise.all`. This is a better fit for this case rather than `combineLatest` which emits ongoing updates.
4. destructuring callback arguments is a bit tidier and easier to read

2024-11-21 02:43 UTC, eliykat commented on apps/web/src/app/billing/settings/sponsoring-org-row.component.ts
> +      this.isFreeFamilyPolicyEnabled = await this.PolicyApiService.getPolicyStatus(
This is repeating an api call that is done in the parent component. Ideally the parent should pass this down to the child so that we're not repeating api traffic unnecessarily.

2024-11-21 02:43 UTC, eliykat commented on apps/web/src/app/layouts/user-layout.component.ts
> +              isFreeFamilyPolicyEnabled = freeFamilyPolicyEnabled;
This is 1x api call per organization and this is in a top-level component (the layout) that is loaded every single time the web vault is loaded. This is extremely inefficient and would smash our server, we can't do this.

2024-11-21 02:43 UTC, eliykat commented on apps/web/src/app/layouts/user-layout.component.ts
> +    );
We generally avoid checking the plan type directly. Would `canManageSponsorships` work here?

2024-11-21 02:43 UTC, eliykat commented on apps/web/src/app/layouts/user-layout.component.ts
> +    return firstValueFrom(result$);
This is all new code, if you want to use observables then you should use them all the way through your methods (e.g. return an observable, then pipe the result) rather than changing them back into promises.

2024-11-21 02:43 UTC, eliykat commented on libs/common/src/admin-console/services/policy/policy-api.service.ts
This might solve a lot of my feedback here: if the user is a member of an org, they will receive that org's policies in their sync data, and they're available from `PolicyService.getAll$`. No api requests required. Can we use that instead of adding this endpoint?

2024-11-22 01:03 UTC, eliykat requested changes

2024-11-22 01:03 UTC, eliykat commented on apps/web/src/app/layouts/user-layout.component.ts
> +      (org) => org.productTierType === ProductTierType.Enterprise,
Unresolved feedback from last review: https://github.com/bitwarden/clients/pull/12056#discussion_r1851236563

2024-11-22 01:03 UTC, eliykat commented on apps/web/src/app/layouts/user-layout.component.ts
I think there is too much F4E specific logic in this for a layout component. Can it be moved to a service?

2024-11-22 16:12 UTC, willmartian requested changes

2024-11-22 16:12 UTC, willmartian commented on apps/web/src/app/layouts/user-layout.component.html
> +      </ng-template>
This group of conditionals feels overly complex. Add the end of the day we are rendering the same item, so it should be possible to use only a single `ngIf` (ideally by moving the logic to the TS file):
        <bit-nav-item
          [text]="'sponsoredFamilies' | i18n"
          route="settings/sponsored-families"
          *ngIf="showSponsoredFamilies$ | async"
        ></bit-nav-item>

2024-11-25 04:12 UTC, eliykat approved these changes
The usage of `PolicyService` is looking good, and the api calls have been removed, which were my main concerns from an AC Team perspective. I've left some feedback below but I'll leave the rest to Billing Team 👍

2024-11-25 04:12 UTC, eliykat commented on apps/web/src/app/layouts/user-layout.component.ts
> +
Duplicate code. I think you should delete this one and keep the definition in the service.

2024-11-25 04:12 UTC, eliykat commented on apps/web/src/app/layouts/user-layout.component.ts
> +    this.showSubscription$ = forkJoin([
`forkJoin` only emits after the source observables complete. Make sure that these observables complete before using it here. (I'm not sure they do)

2024-11-25 04:12 UTC, eliykat commented on apps/web/src/app/layouts/user-layout.component.ts
> +        .pipe(takeUntil(this.destroy$));
You only need to use `takeUntil` if you're explicitly calling `subscribe()`. Here it looks like you're only using this in an `async` pipe in the template, which will handle the unsubscribe for you. (Which is good! But you probably don't need the `onDestroy` pattern.)

2024-11-25 08:04 UTC, cyprain-okeke commented on apps/web/src/app/layouts/user-layout.component.ts
> +    this.showSubscription$ = forkJoin([
This is an existing codebase, it is not the part of changes i added

2024-11-25 22:36 UTC, cyprain-okeke commented on apps/web/src/app/layouts/user-layout.component.ts
> +    this.showSubscription$ = forkJoin([
Oh  sorry about that, I have reverted the change. Thanks for pointing that out

2024-11-25 23:41 UTC, eliykat approved these changes
AC changes look good

2024-11-26 20:06 UTC, willmartian requested changes

2024-11-26 20:06 UTC, willmartian commented on apps/web/src/app/layouts/user-layout.component.ts
> +
This is still a lot of billing-specific logic for a shared layout component. I would move all of this logic into the service you created:

```ts
this.showFreeFamilies$ = this.freeFamiliesPolicyService.showFreeFamilies$;
```

```html
<bit-nav-item
   [text]="'sponsoredFamilies' | i18n"
   route="settings/sponsored-families"
   *ngIf="showFreeFamilies$ | async"
></bit-nav-item>
```

Even better is to move the logic and template into its own component:

```html
<billing-free-families-nav-item></billing-free-families-nav-item>
```

2024-11-27 18:55 UTC, willmartian requested changes
New component looks good! Last request from me is to move it into a folder owned by the Billing team.

2024-11-27 19:41 UTC, willmartian approved these changes
DS-owned files look good to me! Thanks for iterating @cyprain-okeke 👏

2024-11-27 20:28 UTC, eliykat approved these changes

2024-11-28 14:59 UTC, merged