[PM-14345] Enabling drag and drop for cipher fields
bitwarden/clients pull request #12067
Opened 2024-11-20 16:56 UTC by cd-bitwarden

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-14345

## 📔 Objective

Add back a feature that existed before the extension refresh, the ability to drag and drop cipher fields

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-11-27 00:25 UTC, shane-melton requested changes
I think we could reduce a lot of duplicate code by introducing a `appTextDrag` directive. I put an example implementation in a comment below, let me know what you think!

I also noticed some `id` attributes on the inputs within a `*ngFor` that we'll need to adjust.

2024-11-27 00:25 UTC, shane-melton commented on libs/vault/src/cipher-view/additional-options/additional-options.component.html
> +        for="notes"
⛏️ `bit-label` does not support the `for` attribute and can be removed. The same applies for the rest of the PR.

(the `bit-form-field` automatically grabs the `id` from the `bitInput` directive and attaches it to the `label` element)

2024-11-27 00:25 UTC, shane-melton commented on libs/vault/src/cipher-view/additional-options/additional-options.component.html
> +        class="draggable"
⛏️ We should use the `tw-cursor-move` instead of `draggable` everywhere.

2024-11-27 00:25 UTC, shane-melton commented on libs/vault/src/cipher-view/additional-options/additional-options.component.ts
> +  setTextDataOnDrag(event: DragEvent, data: string) {
🎨 Instead of re-defining this everywhere, we could create a re-usable utility directive instead. Something like 

```ts
@Directive({
  selector: "[appTextDrag]",
  standalone: true,
  host: {
    draggable: "true",
    class: "tw-cursor-move",
  },
})
class TextDragDirective {
  @Input({
    alias: "appTextDrag",
    required: true,
  })
  data = "";

  @HostListener("dragstart", ["$event"])
  onDragStart(event: DragEvent) {
    event.dataTransfer.setData("text", this.data);
  }
}
```

And we could use it like:

```html
<bit-label [appTextDrag]="notes">...</bit-label>
```

It also has the benefit of applying the `draggable="true"` and `class="tw-cursor-move"` for us automatically as well.

2024-11-27 00:25 UTC, shane-melton commented on libs/vault/src/cipher-view/custom-fields/custom-fields-v2.component.html
> +          id="textValue"
⚠️ We cannot set the `id="textValue"` here because we're in a `*ngFor` loop which will cause duplicates. We can just drop the attribute as the `id` is automatically set and incremented by the `bitInput` directive.

2024-11-27 00:25 UTC, shane-melton commented on libs/vault/src/cipher-view/custom-fields/custom-fields-v2.component.html
> +          id="passwordValue"
⚠️ Same here, we cannot set the `id` to a static value within a `*ngFor` loop.

2024-11-27 00:25 UTC, shane-melton commented on libs/vault/src/cipher-view/custom-fields/custom-fields-v2.component.html
> +          id="checkboxValue"
⚠️ Same here

2024-11-27 19:36 UTC, cd-bitwarden commented on libs/vault/src/cipher-view/additional-options/additional-options.component.html
> +        for="notes"
that's great, thank you for explaining! :)

2024-12-04 22:36 UTC, shane-melton reviewed
Looking good, I think the directive works really nicely! Just a few small nits and a question about custom fields.

2024-12-04 22:36 UTC, shane-melton commented on libs/vault/src/cipher-view/custom-fields/custom-fields-v2.component.html
>          <bit-label> {{ "cfTypeLinked" | i18n }}: {{ field.name }} </bit-label>
❓ Should we include this linked custom fields too?

2024-12-04 22:36 UTC, shane-melton commented on libs/vault/src/cipher-view/login-credentials/login-credentials-view.component.html
> +      <bit-label for="userName" [appTextDrag]="cipher.login.username">
⛏️ `for` isn't a valid attribute for `bit-label`

2024-12-04 22:36 UTC, shane-melton commented on libs/vault/src/cipher-view/login-credentials/login-credentials-view.component.html
> +      <bit-label for="password" [appTextDrag]="cipher.login.password">{{
⛏️ `for` isn't a valid attribute for `bit-label`

2024-12-04 22:36 UTC, shane-melton commented on libs/vault/src/cipher-view/login-credentials/login-credentials-view.component.html
> +      <bit-label for="fido" [appTextDrag]="fido2CredentialCreationDateValue"
⛏️ `for` isn't a valid attribute for `bit-label`

2024-12-04 22:36 UTC, shane-melton commented on libs/vault/src/cipher-view/login-credentials/login-credentials-view.component.html
> +      <bit-label for="totp" [appTextDrag]="totpCodeCopyObj?.totpCode"
⛏️ `for` isn't a valid attribute for `bit-label`

2024-12-04 22:36 UTC, shane-melton commented on libs/angular/src/directives/text-drag.directive.ts
> +class TextDragDirective {
⛏️ `export` should be on the same line as `class TextDragDirective`

2024-12-05 15:21 UTC, cd-bitwarden commented on libs/vault/src/cipher-view/login-credentials/login-credentials-view.component.html
> +      <bit-label for="userName" [appTextDrag]="cipher.login.username">
oh this is embarrassing 😆 I had a commit for this yesterday before I requested your re-review, I just didn't push sync 😓

2024-12-05 15:28 UTC, cd-bitwarden commented on libs/vault/src/cipher-view/custom-fields/custom-fields-v2.component.html
>          <bit-label> {{ "cfTypeLinked" | i18n }}: {{ field.name }} </bit-label>
@shane-melton thanks for looking thoroughly at this PR, I was told not to include linked 🤔 is it possible the Jira ticket was incorrect?

2024-12-05 15:48 UTC, shane-melton commented on libs/vault/src/cipher-view/custom-fields/custom-fields-v2.component.html
>          <bit-label> {{ "cfTypeLinked" | i18n }}: {{ field.name }} </bit-label>
Of course!

And oh, I missed that bullet in the ticket, I think we're good to exclude it then!

2024-12-05 15:57 UTC, shane-melton approved these changes
Looks great!

2024-12-10 17:55 UTC, merged