Auth/pm 8114/all clients UI refresh sso component
bitwarden/clients pull request #12061
Opened 2024-11-20 03:20 UTC by alec-livefront

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-8114?atlOrigin=eyJpIjoiNDhjZTM5Y2QwNWZiNGI3Nzk3ZmZhNzY3N2Y4NzRjOWQiLCJwIjoiaiJ9

## 📔 Objective

Update SSO Component with new logo and text. Consolidate logic into client-specific services.

## 📸 Screenshots

https://github.com/user-attachments/assets/82d55883-2d89-4eae-bf2a-0ba65bee707b

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-11-21 09:56 UTC, coroiu reviewed
Seems you have some build issues :)

2024-11-21 22:20 UTC, JaredSnider-Bitwarden requested changes
A solid start on this work! I've not reviewed everything in depth, but I've got a few pieces of feedback below:

2024-11-21 22:20 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/sso/sso-component.service.ts
> +  onSuccessfulLoginTde?(): Promise<void>;
One of the goals of this PR is to refactor all these callbacks away instead of just moving them into the new services. We need to isolate and consolidate behavior into the submit method like we did on the login component. We also need to await a `fullSync` after successful authentication but before navigation in all scenarios now.

2024-11-21 22:20 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/sso/sso-component.service.ts
> +  onSuccessfulLoginTde?(): Promise<void>;
If there is client specific behavior that needs to execute on some clients and not others then that logic should be moved into single responsibility methods the SSO component service implementations. Please let me know if that makes sense!

2024-11-21 22:20 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/oss-routing.module.ts
We have to also add these changes to the extension and desktop.

2024-11-21 22:20 UTC, JaredSnider-Bitwarden commented on apps/web/src/locales/en/messages.json
Once you implement the changes from `apps/web/src/app/oss-routing.module.ts` in the other client's `app-routing.module`'s, these will likely need to be moved to the other client's `messages.json` files if they don't exist there already.

2024-11-21 22:20 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/sso/sso-component.service.ts
> +}
We already have a `ClientType` enum and we can use that here if we exclude the CLI. Let's just do:

`type SsoClientType = ClientType.Web | ClientType.Browser | ClientType.Desktop;
`

2024-11-22 03:16 UTC, alec-livefront commented on libs/auth/src/angular/sso/sso-component.service.ts
> +}
bc217527c5abd8949702384994b52d3068e32c7b

2024-11-22 03:19 UTC, alec-livefront commented on apps/web/src/app/oss-routing.module.ts
Like this? 6e86f0cce8f53e6c8d338d48ae9ef3c1da92769d 

I'm a little confused about this, because the desktop and browser extension open the SSO in a web browser window.

2024-12-02 16:36 UTC, alec-livefront commented on apps/web/src/locales/en/messages.json
I think these messages only show up in the browser window that opens during the SSO flow?

2024-12-02 19:36 UTC, JaredSnider-Bitwarden commented on apps/web/src/locales/en/messages.json
Great point! Sorry about that!

2024-12-02 19:42 UTC, JaredSnider-Bitwarden commented on apps/web/src/locales/en/messages.json
Per discussion on call, title should be moved to browser & desktop and routing modules updated to use anon-layout for new SSO component on each client.

2024-12-02 20:00 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/oss-routing.module.ts
Yep, good catch, my bad!

2024-12-07 18:22 UTC, JaredSnider-Bitwarden requested changes
Excellent work on this. Every single flow looked great! I have a few additional requests for some enhancements, but I'm really happy with how this is shaping up!

2024-12-07 18:22 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/sso/sso-component.service.ts
> +  preventClearingKeys?(): Promise<void>;
🏅 : marking these as optional is a great approach, and I'm going to use that moving forward for clarity.

2024-12-07 18:22 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/sso/default-sso-component.service.ts
> +  closeWindow: () => undefined | Promise<void>;
❓ : Should both of these be optional as well since the abstraction marks them as optional? We would need to add `?() `to where we call them in the new `SsoComponent` as well.

2024-12-07 18:22 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/anon-layout/anon-layout.stories.ts
🏅 : really nice job enhancing this! Minor request for the future would be to move separate but required enhancement work like this into it's own PR. I'd be happy to make a Jira ticket for something like this so it can be tracked separately.

2024-12-07 18:22 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/anon-layout/anon-layout-wrapper.component.html
> +  [titleAreaMaxWidth]="titleAreaMaxWidth"
❓ : is this something we should add to the extension anon layout as well?

2024-12-07 18:22 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/sso/sso.component.ts
> +  }
🏅 : this init is so much cleaner and easier to follow than before. Thank you very much for this refactor!

2024-12-07 18:22 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/sso/sso.component.ts
> +      this.setRequiredSsoVariables(qParams);
:bulb: Can we add a tiny bit of documentation on what specific flow / part in the SSO process hits this condition?

2024-12-07 18:22 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/sso/sso.component.ts
> +      await this.handleCodeAndStateParams(qParams);
:bulb: Can we add a tiny bit of documentation on what specific flow / part in the SSO process hits this condition?

2024-12-07 18:22 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/sso/sso.component.ts
> +
⚠️ : we need to add an awaited `syncService.fullSync(true)` here before navigation.

2024-12-07 18:22 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/sso/sso.component.ts
> +
The other full sync's can be removed and replaced with just this one call.

2024-12-07 18:22 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/sso/sso-component.service.ts
> +   * Prevents clearing keys from memory.
💡 , can we add docs for why we do this on what client (the docs can be on the actual client specific service if you think that is clearer)?

2024-12-07 18:22 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/sso/sso.component.ts
> +    await this.navigateViaCallbackOrRoute(async () => {}, ["2fa"], {
⚠️ : for all the calls to `navigateViaCallbackOrRoute` that do not actually have a callback, we can simply just navigate?  Hmm... we probably can completely remove `navigateViaCallbackOrRoute` and in the one existing situation where we still have a callback:

```TypeScript
    await this.navigateViaCallbackOrRoute(this.ssoComponentService.closeWindow, [
      "login-initiated",
    ]);
```

We can change that to simply check if the close window method exists on the service and close the window or navigate to "login-initiated"

2024-12-10 15:46 UTC, alec-livefront commented on libs/auth/src/angular/anon-layout/anon-layout-wrapper.component.html
> +  [titleAreaMaxWidth]="titleAreaMaxWidth"
🤔 So in this instance the description text isn't shown in the extension or desktop. The user is just shown "loading" for a brief moment. I suppose we could add it for consistency but I don't think it is necessary, and maybe less code is better.

![Screenshot 2024-12-09 at 3 53 18 PM](https://github.com/user-attachments/assets/cede46ae-96aa-47f9-bd63-fe7ea4e4c1d3)

2024-12-10 16:15 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/anon-layout/anon-layout-wrapper.component.html
> +  [titleAreaMaxWidth]="titleAreaMaxWidth"
Sounds good! Thank you for double checking!

2024-12-10 21:53 UTC, alec-livefront commented on libs/auth/src/angular/sso/sso-component.service.ts
> +   * Sets the cookies for the SSO component service.
2b586a8c51c5dc42ce2821feaf14f9d42b238790

2024-12-10 21:54 UTC, alec-livefront commented on apps/browser/src/auth/popup/login/extension-sso-component.service.ts
> +    @Inject(WINDOW) private window: Window,
a3045f3d5aada47ba14ab755507ce84cd5d7cab7

2024-12-10 21:55 UTC, alec-livefront commented on apps/desktop/src/app/app-routing.module.ts
> +  }),
84e556c6202086a94273bb7cbdf5fb604f3826c5

2024-12-10 21:55 UTC, alec-livefront commented on apps/browser/src/popup/app-routing.module.ts
> +  ...unauthUiRefreshSwap(SsoComponentV1, SsoComponent, {
237d6b6562c8526406a30501b0895d4e4250d40b

2024-12-10 22:15 UTC, alec-livefront commented on apps/desktop/src/auth/login/desktop-sso-component.service.ts
8b258cc964e3f325df5501f15ecaefb95dd84215 & ac15f8f7cd5159f45bb9a3c2a3b5623496ab5aca

2024-12-10 22:17 UTC, alec-livefront commented on libs/auth/src/angular/sso/default-sso-component.service.ts
> +  closeWindow: () => undefined | Promise<void>;
Yes, I've marked them both optional in the abstract class. I'm not sure they actually need to be defined in the `DefaultSsoComponentService` at all (I'd imagine only functionality shared between 2 or more clients would be useful here).

2024-12-11 03:54 UTC, alec-livefront commented on libs/auth/src/angular/sso/sso-component.service.ts
> +   * Prevents clearing keys from memory.
I've renamed this to `reloadOpenWindowsWhenNotUnlocked` to better reflect what it's doing (532167dab4a3f41028658ed297ae208decabea81) - I'm confused why it is necessary.

2024-12-11 03:55 UTC, alec-livefront commented on libs/auth/src/angular/sso/sso.component.ts
> +
3915670b9b471c760613efb43a1c28f1bd0501a5

2024-12-11 03:55 UTC, alec-livefront commented on libs/auth/src/angular/sso/sso.component.ts
> +      await this.handleCodeAndStateParams(qParams);
71f76662b66f8658292a2cdf02cebee7fe806876

2024-12-11 03:55 UTC, alec-livefront commented on libs/auth/src/angular/sso/sso.component.ts
> +      this.setRequiredSsoVariables(qParams);
71f76662b66f8658292a2cdf02cebee7fe806876

2024-12-11 04:09 UTC, alec-livefront commented on libs/auth/src/angular/sso/sso.component.ts
> +    await this.navigateViaCallbackOrRoute(async () => {}, ["2fa"], {
2685d5f717cd0f435ff281c4cf64cbea0da6ea86

2024-12-11 20:46 UTC, alec-livefront commented on bitwarden_license/bit-web/src/app/admin-console/providers/clients/vnext-clients.component.ts
> +// FIXME: Update this file to be type safe and remove this and next line
@JaredSnider-Bitwarden IDK if I should actually touch these `vnext` files?

2024-12-11 20:49 UTC, JaredSnider-Bitwarden commented on bitwarden_license/bit-web/src/app/admin-console/providers/clients/vnext-clients.component.ts
> +// FIXME: Update this file to be type safe and remove this and next line
@alec-livefront , yeah, if those errors came from merging in main, they should be fixed by the team which merged them in.

2024-12-11 23:57 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/sso/sso.component.ts
> +
@alec-livefront , I'm sorry I wasn't clear with this feedback. We need to put the full sync after the requires 2FA check. The user has to be fully logged in in order to sync the proper data, and if 2FA is required, the user's login attempt will be rejected.

2024-12-11 23:59 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/sso/sso.component.ts
> +
I went ahead and fixed it: https://github.com/bitwarden/clients/pull/12061/commits/9bc5ae9438f3eb278c726b61d4697bd5ac39b452

2024-12-12 00:23 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/sso/sso-component.service.ts
> +   * Prevents clearing keys from memory.
I looked at the git history for it and I found this PR: https://github.com/bitwarden/clients/pull/2156

"src/popup/accounts/sso.component.ts - this onSuccessfulLogin callback runs after the user successfully authenticates with SSO. Currently, this refreshes all open tabs/windows belonging to the extension - I'm not sure why, but I assume it's so that it'll display the unlock page properly. With Key Connector, the user is already unlocked and all this does is dump the keys out of memory, locking the vault again. So: don't refresh if the vault is already unlocked."

I tested removing the call to `reloadOpenWindowsWhenNotUnlocked` and it works in both extension SSO scenarios I tested (TDE & MP encryption orgs) to land the user on the proper screen. I actually think that call could introduce bad behavior. The user should always be unlocked at that point in the process. Let's remove this call.

2024-12-12 00:26 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/sso/sso-component.service.ts
> +   * Prevents clearing keys from memory.
I've removed it here: https://github.com/bitwarden/clients/pull/12061/commits/dcb232064491bfb00a4907f970f78940c59a5260

2024-12-12 00:27 UTC, JaredSnider-Bitwarden approved these changes
Thank you for your excellent work on this!

2024-12-12 16:22 UTC, coroiu approved these changes

2024-12-12 16:28 UTC, merged