[PM-13455] Risk insights aggregation in a new service.
bitwarden/clients pull request #12071
Opened 2024-11-20 19:29 UTC by ttalty

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-13455

## 📔 Objective

Data aggregation service for the all applications health report for risk insights. 

The service contains three generate methods. 

1. `generateRawDataReport` Members, password health, and uris are associated at the cipher level. Returns the raw data containing the weak password, reused password, and exposed password. The trimmed uris and assigned members. Used for the first diagnostic tab for raw data just not displaying the members info/uris. Also used for the raw data + members diagnostic tab by displaying the member information and excluding the uris.
2. `generateRawDataUriReport` Calls the `generateRawDataReport` for the base data. Flattens out the base data. A record for each uri is created with it's parent cipher health information. 
3. `generateApplicationsReport` Calls the `generateRawDataUriReport` for the flattened base data. The uris need to be grouped together and the report data aggregated. Returns the uri, member information, total password count, at risk member information, and at risk member counts.

Important methods to note:

- `getTrimmedCipherUris` Uses `Utils.getHostname` to trim to the hostname. For each cipher we want to return only distinct trimmed uris. A cipher can have two uris: 'https://google.com' and 'google.com/login' assigned to the cipher. Both trimmed uris are 'google.com' when flattened this would duplicate the uri detail causing incorrect totals in the final report. Only return distinct trimmed uris for each cipher. 
- `getApplicationHealthReport` Where the final health report object is aggregated. The record is at risk if their is a weak password, exposed, or reused password. If there is an existing record in the array with the current items uri. The password count value is incremented. The members are updated to include any members not already in the existing item. If the new record is at risk. At risk members are updated with any new entries and the at risk password count is incremented. If there is not an existing record. The new application health report record is created instead of updated. This method uses the `getApplicationReportDetail` private method to create the object for update/create. 

ℹ️ This is a work in progress meant to start the review process. Future development will include test cases and implementation. 

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-12-03 17:08 UTC, audreyality requested changes
Requested changes are ⚠️ and ⛏️ . 
Points of discussion that block approval are 🤔 and ❓.
Everything else is commentary.

2024-12-03 17:08 UTC, audreyality commented on bitwarden_license/bit-common/src/tools/reports/risk-insights/services/risk-insights-report.service.ts
> +        : 0;
🎨 `Map.get` returns `undefined` when the key isn't found. This allows you to use nullish resolution instead of `has`!

```ts
const foo = new Map<string, number>();
const bar = foo.get("bar") ?? 0;
```

2024-12-04 16:19 UTC, ttalty commented on bitwarden_license/bit-common/src/tools/reports/risk-insights/services/risk-insights-report.service.ts
> +@Injectable()
Working on the importing of it with dependency injection. My question to Daniel was if we should use jslib for the bit license libs.

2024-12-04 16:31 UTC, audreyality commented on bitwarden_license/bit-common/src/tools/reports/risk-insights/services/risk-insights-report.service.ts
> +@Injectable()
Looks like the current approach is to create a module in `bit-web/src/tools/{...}` and then add it to [bit-web/src/app/app.module.ts](https://github.com/bitwarden/clients/blob/main/bitwarden_license/bit-web/src/app/app.module.ts).

You can see the admin team doing this with the `OrganizationsModule`.

2024-12-09 17:27 UTC, ttalty commented on bitwarden_license/bit-common/src/tools/reports/risk-insights/services/risk-insights-report.service.ts
Unit tests added

🌱 In the future these unit tests will evolve as the critical applications logic is added.

2024-12-09 17:28 UTC, ttalty commented on bitwarden_license/bit-common/src/tools/reports/risk-insights/services/risk-insights-report.service.ts
> +@Injectable()
📝 [This PR](https://github.com/bitwarden/clients/pull/12206) addresses the module being created.

2024-12-09 18:11 UTC, audreyality requested changes
The observable stuff should be cleaned up now if you can. I should have pointed it out before. It wasn't obvious what was going on until I saw the test cases. 😅 

Everything else is a nit or optional.

2024-12-09 18:11 UTC, audreyality commented on bitwarden_license/bit-common/src/tools/reports/risk-insights/services/risk-insights-report.service.spec.ts
> +    expect(testCase.reusedPasswordCount).toEqual(2);
🤔 I think these assertions can be cleaned up using 

```ts
expect(testCase).toMatchObject({
  cipherMembers: expect.toHaveLength(2),
  trimmedUris: expect.toHaveLength(3),
  weakPasswordDetail: expect.toBeTruthy(),
  exposedPasswordDetail: expect.toBeTruthy(),
  reusedPasswordCount: 2
})
```

📝 Fun fact: It also lets you test nested objects!

2024-12-09 19:50 UTC, audreyality requested changes
Just a few nits.

2024-12-09 19:50 UTC, audreyality commented on bitwarden_license/bit-common/src/tools/reports/risk-insights/services/risk-insights-report.service.ts
> +      // timeout(TIMEOUT_IN_MS),
⛏️ Either delete this code or set an appropriate timeout.

2024-12-09 19:50 UTC, audreyality commented on bitwarden_license/bit-common/src/tools/reports/risk-insights/services/risk-insights-report.service.ts
> +    // return this.getApplicationHealthReport(cipherHealthUriReport);
⛏️ This code should also be deleted.

2024-12-09 19:50 UTC, audreyality commented on bitwarden_license/bit-common/src/tools/reports/risk-insights/services/password-health.service.spec.ts
> +// TODO: Remove password-health report service after PR-15498 completion
⛏️ Use `FIXME` to identify tech debt

2024-12-10 18:48 UTC, audreyality requested changes
👍🏻 Thanks for resolving all of my feedback!

📝 There's new feedback based on the strict null checking ADR.

2024-12-10 18:48 UTC, audreyality commented on bitwarden_license/bit-common/src/tools/reports/risk-insights/models/password-health.ts
⚠️ You should prefer `undefined` to `null` per [ADR-14](https://contributing.bitwarden.com/architecture/adr/typescript-strict/#guidelines). In this case, you could implement it by marking the provided properties as optional (`?`).

🎨 The other option is to rework your PR so that it never partially defines an object. 😖

2024-12-12 14:55 UTC, audreyality approved these changes

2024-12-12 14:55 UTC, merged