[PM-15112] Fix missing i18n and block ssh key creation in web
bitwarden/clients pull request #12082
Opened 2024-11-21 10:56 UTC by quexten

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-15112

## 📔 Objective

Since web is still missing capabilities for generating keys, we detect if the add-edit component gets opened with the ssh-key cipher-type selected and force switch to login, so that we do not accidentally allow the user to create broken ssh key ciphers.

This wil be removed as soon as we can generate ssh keys via the sdk in web.

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-11-21 21:09 UTC, Jingo88 requested changes

2024-11-21 21:09 UTC, Jingo88 commented on apps/web/src/app/vault/individual-vault/add-edit.component.ts
> +    if (this.type == CipherType.SshKey && this.cipherId == null) {
Can we make this `===`

2024-11-22 14:12 UTC, quexten commented on apps/web/src/app/vault/individual-vault/add-edit.component.ts
> +    if (this.type == CipherType.SshKey && this.cipherId == null) {
Ok, but this needs to be `=== undefined` then.

2024-11-26 14:22 UTC, Jingo88 commented on apps/web/src/app/vault/individual-vault/add-edit.component.ts
> +    if (this.type == CipherType.SshKey && this.cipherId == null) {
oh apologies. I meant `===` for the `this.type` haha. The `this.cipherId == null` is fine.

2024-11-26 17:44 UTC, quexten commented on apps/web/src/app/vault/individual-vault/add-edit.component.ts
> +    if (this.type == CipherType.SshKey && this.cipherId == null) {
Ohh, whoops. Fixed now.

2024-11-26 22:00 UTC, merged