Auth/PM-8113 - 2FA Components UI Refresh
bitwarden/clients pull request #12087
Opened 2024-11-21 17:39 UTC by JaredSnider-Bitwarden

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2025-02-10 08:47 UTC, coroiu commented on apps/web/src/app/core/core.module.ts
> +  }),
question/suggestion: putting a provider in the root `CoreModule` like this will mean that it may (in certain case) remain in memory throughout the entire application lifetime. Do you think it would be possible to define this service as provider on the component instead? This isn't a service that needs to be available to the entire application, right?

2025-02-10 14:07 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/core/core.module.ts
> +  }),
Hmm... that is a really good point. Yeah, the component services are meant for managing all client specific logic but they aren't really intended to be used in any other scenarios on other components today.

2025-02-11 13:46 UTC, coroiu submitted a review, later dismissed

2025-02-13 01:46 UTC, JaredSnider-Bitwarden commented
@rr-bw , I've added TDE offboarding support to the flows. 

Here's my tests:
![Web](https://github.com/user-attachments/assets/345d5c1b-de66-460b-8f60-836d2d4c6c7e)](https://github.com/user-attachments/assets/1902fa81-b7c7-41ca-b54c-7d98f5bb1233)

![Extension](https://github.com/user-attachments/assets/345d5c1b-de66-460b-8f60-836d2d4c6c7e)](https://github.com/user-attachments/assets/e0506448-5cf3-4064-9e13-be4877332d65)

![Desktop](https://github.com/user-attachments/assets/345d5c1b-de66-460b-8f60-836d2d4c6c7e)](https://github.com/user-attachments/assets/f0eb7117-927c-4d66-a863-ca266b719faa)

2025-02-13 08:11 UTC, coroiu submitted a review, later dismissed
No platform changes, approving

2025-02-13 15:49 UTC, coroiu approved these changes

2025-02-15 04:41 UTC, rr-bw requested changes

2025-02-15 04:41 UTC, rr-bw commented on libs/auth/src/angular/two-factor-auth/two-factor-auth.component.html
> +    <div class="tw-flex tw-flex-col tw-space-y-3 tw-mb-3">
```suggestion
    <div class="tw-flex tw-flex-col tw-space-y-3">
```

AnonLayout already has padding built-in.

2025-02-15 04:41 UTC, rr-bw commented on libs/auth/src/angular/two-factor-auth/two-factor-auth.component.ts
> +  inSsoFlow = false;
Is `inSsoFlow` used anywhere? It's assigned in `ngOnInit()` but I don't think it's ever used.

2025-02-15 04:41 UTC, rr-bw commented on apps/browser/src/auth/services/extension-two-factor-auth-component.service.ts
> +      document.body.classList.add("linux-webauthn");
`.linux-webauthn` is an SCSS class. Do we want this in a Tailwind file?

2025-02-15 04:41 UTC, rr-bw commented on libs/auth/src/angular/two-factor-auth/two-factor-options.component.ts
>    @Output() onRecoverSelected = new EventEmitter();
I don't think the `onProviderSelected` and `onRecoverSelected` outputs are actually being used in the new flow. Also, I'd think you can remove the concept of "recover" entirely from this component (and the `TwoFactorOptionsDialogResult` enum) since the recovery code button is now being shown as an option directly on the 2FA screen. If I'm correct, address also the reference to `TwoFactorOptionsDialogResult` in `selectOtherTwoFactorMethod()` on `TwoFactorAuthComponent`.

2025-02-15 04:41 UTC, rr-bw commented on libs/auth/src/angular/two-factor-auth/two-factor-options.component.ts
>    providers: any[] = [];
Is there a reason for the 4 uses of `any` in this file?

2025-02-15 04:41 UTC, rr-bw commented on libs/auth/src/angular/two-factor-auth/two-factor-auth.component.ts
> +  async selectOtherTwofactorMethod() {
```suggestion
  async selectOtherTwoFactorMethod() {
```

2025-02-15 04:41 UTC, rr-bw commented on libs/auth/src/angular/two-factor-auth/two-factor-auth.component.html
> +        (click)="selectOtherTwofactorMethod()"
```suggestion
        (click)="selectOtherTwoFactorMethod()"
```

2025-02-18 20:17 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/two-factor-auth/two-factor-auth.component.html
> +    <div class="tw-flex tw-flex-col tw-space-y-3 tw-mb-3">
f43b33db6e12b5e5ac134fdfe8694eccaaeab269

2025-02-18 20:19 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/two-factor-auth/two-factor-auth.component.ts
> +  inSsoFlow = false;
Good catch:
35a14c8ca9a34ed962e7a1873c5580679f18e239

2025-02-18 20:28 UTC, JaredSnider-Bitwarden commented on apps/browser/src/auth/services/extension-two-factor-auth-component.service.ts
> +      document.body.classList.add("linux-webauthn");
Per discussion, to avoid increasing test surface, will keep this class here.

2025-02-18 20:40 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/two-factor-auth/two-factor-options.component.ts
>    @Output() onRecoverSelected = new EventEmitter();
Great catch. 
4f25d11b20f8f0b9fd45b0cb712bfeec269a27a8

Video of testing after changes: 
https://github.com/user-attachments/assets/ce40c74c-9db2-4433-be1b-57014d41ed40

2025-02-18 20:42 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/two-factor-auth/two-factor-options.component.ts
>    providers: any[] = [];
Nope, great catch. 
d1a0d97afbd88f01694a3f173474d69e8be26f89

2025-02-18 20:44 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/two-factor-auth/two-factor-auth.component.ts
> +  async selectOtherTwofactorMethod() {
ac3f7e806e124e99f3c0dc47c61b7b3aecb40f65

2025-02-19 09:02 UTC, rr-bw requested changes

2025-02-19 14:11 UTC, JaredSnider-Bitwarden commented on apps/browser/src/_locales/en/messages.json
> +    "desccription": "Select another two-step login method"
4376f0ee7364fab2a43e8fcbdc7395ebb4ece23f

2025-02-19 14:11 UTC, JaredSnider-Bitwarden commented on apps/desktop/src/locales/en/messages.json
> +    "desccription": "Select another two-step login method"
4376f0ee7364fab2a43e8fcbdc7395ebb4ece23f

2025-02-19 14:11 UTC, JaredSnider-Bitwarden commented on apps/web/src/locales/en/messages.json
> +    "desccription": "Select another two-step login method"
4376f0ee7364fab2a43e8fcbdc7395ebb4ece23f

2025-02-19 14:11 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/icons/two-factor-auth/two-factor-auth-security-key.icon.ts
> +        <path stroke="#2CDDE9" stroke-width=".784"
f3c87e60efaac59386aa38599f02f1422aa89337

2025-02-19 14:11 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/icons/two-factor-auth/two-factor-auth-security-key.icon.ts
> +        <path class="tw-fill-art-primary"" fill-rule="evenodd"
bdf38c263bfa350fd83dda70dc4c9b88e93a0b87

2025-02-19 14:13 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/two-factor-auth/child-components/two-factor-auth-duo/two-factor-auth-duo.component.html
No, I've removed it here: ac0b80f8e52c4efd3f62619f794213712757552c

2025-02-19 14:14 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/shared/loose-components.module.ts
> -    UpdatePasswordComponent,
No, I must have messed that up while merging! Great catch!
Re-added here: 213245b91f97e0fabfd13844b9f986b3d9d0ec60

2025-02-19 21:22 UTC, rr-bw requested changes

2025-02-19 21:22 UTC, rr-bw commented on apps/browser/src/auth/services/extension-two-factor-auth-duo-component.service.spec.ts
> +      browserMessagingApi.messageListener$.mockReturnValue(messsageStream$);
```suggestion
      const messageStream$ = new BehaviorSubject(message);
      browserMessagingApi.messageListener$.mockReturnValue(messageStream$);
```

2025-02-19 21:22 UTC, rr-bw commented on libs/common/src/auth/abstractions/two-factor.service.ts
Could use some JSDocs

2025-02-19 22:33 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/two-factor-auth/two-factor-auth.component.ts
> +      tokenValue = tokenFormValue;
Good catch. I ended up having to research a bit to ensure that none of our 2FA methods generated OTPs that have white space in them... but to be safe I'm just going to add the trim and not the replace like we had before.

2025-02-19 22:33 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/two-factor-auth/two-factor-auth.component.ts
> +      tokenValue = tokenFormValue;
7f873f121db1366fa193b27374e478965faeabbd

2025-02-19 23:26 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/abstractions/two-factor.service.ts
Good call! 
Typescript strict change: 8d78f575bc1e9dc07c5fc0f7a348e79ac47c46ce
JSDocs change: aa8e011cd522e1e62e7beed8a81b91faff850495

2025-02-20 01:30 UTC, rr-bw requested changes

2025-02-20 01:58 UTC, rr-bw requested changes

2025-02-20 01:58 UTC, rr-bw commented on apps/web/src/connectors/webauthn-fallback.html
> +              class="tw-stroke-art-primary"
```suggestion
              class="tw-fill-art-primary tw-stroke-art-primary"
```

With just the stroke it looks like this:
<img width="158" alt="Screenshot 2025-02-19 at 5 45 56 PM" src="https://github.com/user-attachments/assets/af48a50c-7436-40ce-b4fa-9dc296e506b6" />

With both it looks like this (which is same as Figma):

<img width="158" alt="Screenshot 2025-02-19 at 5 53 08 PM" src="https://github.com/user-attachments/assets/2f8186ed-38f3-4973-bf44-303a8ad50988" />

2025-02-20 01:58 UTC, rr-bw commented on libs/auth/src/angular/icons/two-factor-auth/two-factor-auth-webauthn.icon.ts
> +    <path class="tw-stroke-art-primary" fill-rule="evenodd" stroke-width=".355"
```suggestion
    <path class="tw-fill-art-primary tw-stroke-art-primary" fill-rule="evenodd" stroke-width=".355"
```

2025-02-20 02:13 UTC, JaredSnider-Bitwarden commented on apps/web/src/connectors/webauthn-fallback.html
> +              class="tw-stroke-art-primary"
oh, right. My bad. Tyvm for catching that!

2025-02-20 04:08 UTC, rr-bw approved these changes

2025-02-20 07:59 UTC, coroiu approved these changes
No platform changes, approving 👍

2025-02-24 14:59 UTC, merged