[CL-511] - add variant to links within banners
bitwarden/clients pull request #12090
Opened 2024-11-21 21:08 UTC by jaasen-livefront

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/CL-511

## 📔 Objective

This PR updates link `linkType` prop from `contrast` to `secondary` for all components whose banners include a link, fixing a poor color contrast.

## 📸 Screenshots

![Screenshot 2024-11-21 at 1 07 11 PM](https://github.com/user-attachments/assets/ae07a021-2a6c-4da7-89f6-4a54f60f62f7)

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-11-26 14:23 UTC, Jingo88 approved these changes

2024-11-26 19:42 UTC, amorask-bitwarden approved these changes

2024-11-27 16:01 UTC, mzieniukbw approved these changes
LGTM from SM side

2024-12-02 17:40 UTC, shane-melton requested changes
I think we just have a slight mixup of attribute names here that we need to fix.

2024-12-02 17:40 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault-banners/vault-banners.component.html
> +    variant="secondary"
⚠️ `variant` is not a supported input for `bitLink`. I think you want to update the `linkType` attribute to be `secondary` instead.

e.g. `linkType="secondary"`

2024-12-02 17:40 UTC, shane-melton commented on apps/web/src/app/billing/organizations/payment-method/organization-payment-method.component.html
> +    link="secondary"
⚠️ `link` is not a supported attribute of `bitLink`. I think you want to still use the `linkType="secondary"`

2024-12-02 17:50 UTC, shane-melton approved these changes

2024-12-02 19:07 UTC, mzieniukbw approved these changes

2024-12-04 17:23 UTC, amorask-bitwarden approved these changes

2024-12-06 15:09 UTC, Jingo88 approved these changes

2024-12-06 19:29 UTC, merged