PM-15070 Star critical apps
bitwarden/clients pull request #12109
Opened 2024-11-22 18:02 UTC by voommen-livefront

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-15070

## 📔 Objective

When a record is flagged - then show a "start" next to it rather than a checkbox

## 📸 Screenshots

<img width="916" alt="image" src="https://github.com/user-attachments/assets/aea65156-333d-4de2-a57e-e190ca0fd858">

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-12-04 16:12 UTC, audreyality reviewed
❌ It looks like this PR has conflicts with #12005 and #12039. Please tag me back in once that PR merges.

2025-01-06 20:13 UTC, ttalty reviewed
Just a quick change of moving around some of the logic.

2025-01-06 20:13 UTC, ttalty commented on bitwarden_license/bit-common/src/tools/reports/risk-insights/services/critical-apps-api.service.ts
⚠️Can we create two services? Keep this `critical-apps-api.service.ts` and only have the api calls similar to the `member-cipher-details-api.service.ts` where only the api calls go in. 

The code on line 110:

```
this.apiService.send(
          "GET",
          `/reports/password-health-report-applications/${orgId.toString()}`,
          null,
          true,
          true,
        ),
```
For this would be the only code for the api call. Then create another service called `critical-apps.service.ts` which would contain all the other business logic in this file. 

The reasoning is we are going to be having add/remove and potentially updates on the critical apps. Moving just the api calls into it's own service allows for easier testing, segmenting responsibility, and potentially reuse in the future.

2025-01-13 18:35 UTC, ttalty approved these changes
Looks good. I fixed the merge conflict.

2025-01-13 19:08 UTC, voommen-livefront commented
> ❌ It looks like this PR has conflicts with #12005 and #12039. Please tag me back in once that PR merges.

@audreyality - to make this easier, I closed #12005 and #12039 into a single PR. You had reviewed #12039 (https://github.com/bitwarden/clients/pull/12039) and approved it a while ago!

2025-01-14 20:04 UTC, audreyality requested changes
There are some critical issues in this code (marked with ❌). Please reach out if you need me to go into why.

2025-01-15 17:22 UTC, voommen-livefront commented on bitwarden_license/bit-common/src/tools/reports/risk-insights/services/critical-apps-api.service.ts
> +  SaveCriticalApps(
I have been looking at this code for a while and didn't spot the problem! Sorry about that. Changed the method names to `saveCriticalApps` and `getCriticalApps`.

2025-01-15 17:23 UTC, voommen-livefront commented on bitwarden_license/bit-web/src/app/tools/access-intelligence/all-applications.component.ts
> +} from "@bitwarden/bit-common/tools/reports/risk-insights/models/password-health";
I have removed the comment and it looks fine 🤞

2025-01-15 17:24 UTC, voommen-livefront commented on bitwarden_license/bit-web/src/app/tools/access-intelligence/all-applications.component.ts
>        });
This was a bit of a challenge for me. I consolidated the code into one `combineLatest` - you are right - it takes away duplicate code and makes it easier to understand.

2025-01-15 17:25 UTC, voommen-livefront commented on bitwarden_license/bit-web/src/app/tools/access-intelligence/all-applications.component.ts
> +              );
Agreed. I have moved the side-effects to the `subscribe` method

2025-01-15 17:33 UTC, audreyality commented on bitwarden_license/bit-common/src/tools/reports/risk-insights/services/critical-apps-api.service.spec.ts
Thank you!

2025-01-15 17:33 UTC, audreyality commented on bitwarden_license/bit-web/src/app/tools/access-intelligence/all-applications.component.ts
> +          this.organization = organization as Organization;
⛏️ Is the `as Organization` type assertion necessary? `organization`'s type should flow through the observable. If typescript refuses to flow the type, you might try adding `as const` on line 90. That tells the compiler that the return value has a fixed type, thereby avoiding the type assertion.

📝 As to why the type assertion isn't ideal--it forces the type to be `Organization`. If the type flows properly then this isn't necessary. If the type isn't flowing properly, however, then the compiler is likely casting from `any` or `unknown`, which always succeeds.

2025-01-15 18:07 UTC, voommen-livefront commented on bitwarden_license/bit-web/src/app/tools/access-intelligence/all-applications.component.ts
> +          this.organization = organization as Organization;
Audrey, you are correct. The type assertion wasn't needed. I have removed it and all the changes work just fine.

2025-01-15 18:09 UTC, audreyality approved these changes

2025-01-15 19:40 UTC, audreyality commented on bitwarden_license/bit-web/src/app/tools/access-intelligence/all-applications.component.ts
> +// @ts-strict-ignore
⛏️  Seems like you should either solve the type issues or disable the lint.

📝 The remainder of my feedback assumes you're solving the type issues.

2025-01-15 19:40 UTC, audreyality commented on bitwarden_license/bit-web/src/app/tools/access-intelligence/all-applications.component.ts
> +          const org = (organization ?? {}) as Organization;
🤔 It appears what's implemented subverts the type system. While on a technical level you've eliminated the null values by substituting an empty JS object, the type assertion is false. Your substitute object lacks any of the properties [required by `Organization`](https://github.com/bitwarden/clients/blob/99937e5831baa1ce9adbef4fd2403dcb5b7b777c/libs/common/src/admin-console/models/domain/organization.ts#L10). Either produce an object that meets the interface requirements or fully handle the case where the organization isn't defined.

There's a few ways I could see handling undefined organizations.

* Throw an exception and handle it using `subscribe({ error: (e) => ... })`. This would be appropriate if you expect the user to be able to fix the problem of a missing organization.
* Throw an exception and don't handle it; `subscribe` will re-throw the error. This would be appropriate if this issue should never occur.
* [Filter nullish organizations](https://rxjs.dev/api/operators/filter) out of the observable. This is useful if an organization may be temporarily unavailable.
*  Use the `skipWhile`/`takeWhile` to turn them into observable completion. This is useful if you want to disable the page when an organization is unavailable.

2025-01-15 19:40 UTC, audreyality commented on bitwarden_license/bit-web/src/app/tools/access-intelligence/all-applications.component.ts
> +      (this.activatedRoute.snapshot.paramMap.get("organizationId") as string) ?? "";
🤔 Is there ever a case where the page shouldn't be supplied an `organizationId`? If so, then you should conditionally run the logic that depends on `organizationId`. If not, then you should throw an error.

2025-01-15 19:48 UTC, voommen-livefront commented on bitwarden_license/bit-web/src/app/tools/access-intelligence/all-applications.component.ts
> +      (this.activatedRoute.snapshot.paramMap.get("organizationId") as string) ?? "";
In fact, it was this line that caused tests to fail. Turns out that `paramMap.get('..')` returns `string | undefined` - and that caused the tests to fail. This piece of code fixed it. This is the link to the failing tests
https://github.com/bitwarden/clients/actions/runs/12794336886/job/35669250167

2025-01-15 20:34 UTC, voommen-livefront commented on bitwarden_license/bit-web/src/app/tools/access-intelligence/all-applications.component.ts
> +      (this.activatedRoute.snapshot.paramMap.get("organizationId") as string) ?? "";
I have fixed this to remove the type.

2025-01-15 20:35 UTC, voommen-livefront commented on bitwarden_license/bit-web/src/app/tools/access-intelligence/all-applications.component.ts
> +          const org = (organization ?? {}) as Organization;
I used `skipUntil` as it seemed less code and easier to use. 
Much appreciate the guidance - I did try the first two - but it seemed like more code and so I landed on using `skipWhile` - the guidance proved extremely helpful. Thanks again.

2025-01-15 22:03 UTC, audreyality approved these changes

2025-01-16 14:45 UTC, ttalty approved these changes

2025-01-16 14:47 UTC, merged