[PM-15180] - update copy for free trial banner
bitwarden/clients pull request #12151
Opened 2024-11-25 18:54 UTC by jaasen-livefront

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-15180

## 📔 Objective

This PR updates the translation keys for the different trial banners to all have complete sentences to allow for proper translation.

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-11-25 19:16 UTC, djsmith85 requested changes
@jaasen-livefront If you are changing the context/meaning of a message, you'll need to delete the old key+message and any usages and create a new pair.

This is to ensure that any messages that were translated with the old meaning are deleted and the new text is present for the translations

2024-11-25 20:43 UTC, cyprain-okeke commented on apps/web/src/locales/en/messages.json
> -    "message": "$ORGANIZATION$, your free trial ends in $COUNT$ days. To maintain your subscription,",
The business requested that `To maintain your subscription,` be removed

2024-11-25 21:06 UTC, jaasen-livefront commented on apps/web/src/locales/en/messages.json
> -    "message": "$ORGANIZATION$, your free trial ends in $COUNT$ days. To maintain your subscription,",
@cyprain-okeke Given how different languages break up sentences in different ways and the fact this translation in particular was broken between 2 keys it was decided to make both keys complete sentences in order to allow for proper translation.

2024-11-25 21:41 UTC, cyprain-okeke commented on apps/web/src/locales/en/messages.json
> -    "message": "$ORGANIZATION$, your free trial ends in $COUNT$ days. To maintain your subscription,",
Please provide a video recording

2024-11-25 21:56 UTC, jaasen-livefront commented on apps/web/src/locales/en/messages.json
> -    "message": "$ORGANIZATION$, your free trial ends in $COUNT$ days. To maintain your subscription,",
@cyprain-okeke Sorry I'm not sure what you mean. What would you like the recording of?

2024-11-25 22:17 UTC, cyprain-okeke commented on apps/web/src/locales/en/messages.json
> -    "message": "$ORGANIZATION$, your free trial ends in $COUNT$ days. To maintain your subscription,",
run the application and test it, while testing record it and attached it to the pr.

2024-11-25 23:45 UTC, jaasen-livefront commented on apps/web/src/locales/en/messages.json
> -    "message": "$ORGANIZATION$, your free trial ends in $COUNT$ days. To maintain your subscription,",
@cyprain-okeke Screen recording attached

2024-11-27 16:07 UTC, mzieniukbw requested changes

2024-11-27 16:07 UTC, mzieniukbw commented on apps/web/src/locales/en/messages.json
>          "example": "You must set up 2FA on your user account before you can join this organization."
i just noticed, this example text is wrong.

2024-11-27 16:07 UTC, mzieniukbw commented on apps/web/src/app/billing/shared/payment-method.component.html
> +    {{ "routeToPaymentMethodTriggerV2" | i18n }}
Could not find this in `messages.json`

2024-11-27 16:07 UTC, mzieniukbw commented on apps/web/src/locales/en/messages.json
>        "count": {
the example text is wrong for the two placeholders.

2024-11-27 16:07 UTC, mzieniukbw commented on apps/web/src/locales/en/messages.json
> +    "message": "Click here add a payment method."
```suggestion
    "message": "Click here to add a payment method."
```

2024-12-03 17:42 UTC, jaasen-livefront commented
@mzieniukbw Thanks for your feedback. Ready for review again.

2024-12-04 10:32 UTC, mzieniukbw approved these changes

2024-12-04 13:10 UTC, djsmith85 approved these changes
Changes are looking good!

2024-12-04 18:24 UTC, shane-melton approved these changes

2024-12-04 18:30 UTC, jaasen-livefront commented
@gbubemismith @cyprain-okeke Would you guys mind taking a look?

2024-12-04 19:14 UTC, gbubemismith approved these changes
Looks good!

2024-12-09 10:15 UTC, jonashendrickx approved these changes

2024-12-09 11:08 UTC, cyprain-okeke approved these changes

2024-12-10 17:43 UTC, merged