Allow epheremal pin to survive process reload on desktop and add ephe…
bitwarden/clients pull request #12199
Opened 2024-12-01 23:02 UTC by quexten

…remal pin store for rust

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-12-05 19:46 UTC, rr-bw requested changes

2024-12-05 19:46 UTC, rr-bw commented on apps/desktop/src/auth/services/desktop-pin.service.ts
> +    const epheremalValue = await ipc.platform.ephemeralStore.getEphemeralValue(
I would find/replace "epheremal" with "ephemeral". I noticed some other instances in other files.

2024-12-05 19:46 UTC, rr-bw commented on apps/desktop/src/auth/services/desktop-pin.service.ts
Is it possible to add some testing for this service?

2024-12-09 12:14 UTC, quexten commented on apps/desktop/src/auth/services/desktop-pin.service.ts
> +    const epheremalValue = await ipc.platform.ephemeralStore.getEphemeralValue(
Heh, I always confuse these. Thanks for catching it.

2024-12-09 12:32 UTC, quexten commented on apps/desktop/src/auth/services/desktop-pin.service.ts
Added tests

2025-01-22 22:54 UTC, closed without merging