[PM-13659] implement auth timeout state for 2fa flows
bitwarden/clients pull request #12201
Opened 2024-12-02 02:19 UTC by alec-livefront

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-12-02 19:54 UTC, vleague2 requested changes

2024-12-02 19:54 UTC, vleague2 commented on libs/angular/src/auth/components/two-factor-auth/two-factor-auth-expired.component.ts
> +    <button bitButton block (click)="navigateToLogin()" buttonType="primary">
If this just loads a new route, it would be more semantically accurate to use an anchor element. `bitButton` works on an anchor.

2024-12-02 19:54 UTC, vleague2 commented on libs/components/src/tw-theme.css
> +  --color-art-primary600: 23 93 220;
We try to avoid adding new colors unless absolutely necessary, to keep the palette limited. In this particular case, you can use the existing `primary-600` color for this SVG (`tw-fill-primary-600`).

2024-12-03 18:24 UTC, alec-livefront commented on libs/angular/src/auth/components/two-factor-auth/two-factor-auth-expired.component.ts
> +    <button bitButton block (click)="navigateToLogin()" buttonType="primary">
[a8813ea](https://github.com/bitwarden/clients/pull/12201/commits/a8813ea265a50463dc9afc3cb2c373e721c6c03f)

2024-12-03 19:35 UTC, JaredSnider-Bitwarden approved these changes
Nice work on this!

2024-12-03 19:55 UTC, merged