[PM-15154] Domain verification copy update
bitwarden/clients pull request #12217
Opened 2024-12-03 12:41 UTC by r-tome

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-15154

## 📔 Objective

Updated the copy for domain verification to replace the word "verify" with "claim" throughout the application when the account deprovisioning feature flag is enabled.

## 📸 Screenshots

<img width="1266" alt="image" src="https://github.com/user-attachments/assets/7538846e-5dce-4c96-a9c3-c20941f2de97">
<img width="412" alt="image" src="https://github.com/user-attachments/assets/243aa123-4efd-4559-8614-dbcc828ed8bc">
<img width="555" alt="image" src="https://github.com/user-attachments/assets/0896ccdf-9930-4fd2-aa98-a34c9822cb74">
<img width="799" alt="image" src="https://github.com/user-attachments/assets/cfd4338d-9536-4dee-85ef-841c35bc1c1a">

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-12-06 14:40 UTC, BTreston requested changes
Looking good, just a few pieces of feedback

2024-12-06 14:40 UTC, BTreston commented on apps/web/src/app/admin-console/organizations/layouts/organization-layout.component.ts
> +  getDomainVerificationNavigationTextKey(): Observable<string> {
We should refactor this to be a variable instead of a function and then pass that variable into the i18n pipe in the template. In general you should avoid calling functions during data binding and interpolation in the template.

2024-12-06 14:40 UTC, BTreston commented on bitwarden_license/bit-web/src/app/admin-console/organizations/manage/domain-verification/domain-add-edit-dialog/domain-add-edit-dialog.component.ts
> +    this.accountDeprovisioningEnabled = await this.configService.getFeatureFlag(
We should remove the await here and change this variable to be an observable. You can then subscribe to it in the template with the async pipe and you can then do:
`await firstValueFrom(this.accountDeprovisioningEnabled$) ` 
below to convert to a promise and immediately resolve, which lets you use the value in a more imperative way.

2024-12-06 14:40 UTC, BTreston commented on bitwarden_license/bit-web/src/app/admin-console/organizations/manage/domain-verification/domain-add-edit-dialog/domain-add-edit-dialog.component.ts
The suggestion in this file also applies to the domain-verification component

2024-12-06 17:27 UTC, BTreston approved these changes

2024-12-06 19:46 UTC, justindbaur commented on apps/web/src/app/core/event.service.ts
@djsmith85 This should probably be owned by tools right?

2024-12-06 19:51 UTC, rr-bw approved these changes

2024-12-11 11:27 UTC, addisonbeck approved these changes

2024-12-11 14:47 UTC, merged