[PM-13755] Use active user count for seat validation
bitwarden/clients pull request #12228
Opened 2024-12-03 20:23 UTC by JimmyVo16

Use active user count for seat validation instead of total users. This ensures that revoked users do not occupy an organization's seat.

Note: this is in draft mode because I need to talk to the team about an edge with member access report. 

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-13755

## 📔 Objective

1. 

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-12-04 10:19 UTC, eliykat requested changes
I left a comment on the Jira ticket, also some early feedback below.

2024-12-04 10:19 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/members/members.component.ts
>          this.organization.productTierType === ProductTierType.Families)
This logic is representing "plans that don't let you add additional seats". This is repeated in the validator, in the `productHasAdditionalSeatsOption` variable. I suggest you extract it to a function that can be reused - maybe exported from the validator given that it's closely related to seat limit validation.

2024-12-04 10:19 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/members/members.component.ts
The first block of logic in `edit` has an incorrect calculation using the `confirmedUserCount` only. Can you please update it to use the same calculation as everywhere else.

2024-12-04 10:19 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts
As discussed in the Jira ticket - I suggest splitting the `MemberDialogParams` into a discriminated union of "params required for inviting" and "params required for editing".

2024-12-04 10:19 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts
> +  activeUserCount?: number;
When it comes to billing, our verbiage for this is "occupied seats", so I suggest `occupiedSeatCount` for consistency.

2024-12-04 10:19 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/members/members.component.ts
> +        activeUserCount: this.dataSource.activeUserCount,
I suggest adding an `occupiedSeatCount` getter that returns the `activeUserCount`, just so that you don't have to reference the dataSource every time, and so that it's using the billing verbiage.

2024-12-04 10:19 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/validators/org-seat-limit-reached.validator.ts
> +    return null;
Please add a unit test for this line per the Codecov annotation (check the Github diff).

2024-12-04 20:40 UTC, JimmyVo16 commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts
> +  activeUserCount?: number;
If there are docs on idioms/verbiages like this, then please send them my way 😄

2024-12-04 22:00 UTC, JimmyVo16 commented
I'll address the reseller flow and add more test coverage tomorrow.

2024-12-05 01:56 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts
> +export interface EditMemberDialogParams {
This is looking good! A few suggestions:
- review the existing params - not all of them are required for both flows. e.g. `organizationUserId` is not needed when inviting a new member. `this.editMode` would then be set based on `params.kind`.
- `numConfirmedMembers` may no longer be required once you remove the reseller toast
- if there are still a number of common params, you can move them to a third interface: `CommonDialogParams` and then union your other interfaces with it, e.g. `export type MemberDialogParams = (InviteMemberDialogParams | EditMemberDialogParams) & CommonDialogParams;`.

2024-12-05 17:35 UTC, JimmyVo16 commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts
> +export interface EditMemberDialogParams {
> review the existing params - not all of them are required for both flows. e.g. organizationUserId is not needed when inviting a new member.

It looks like we're using it here

![image](https://github.com/user-attachments/assets/ec1aa9f3-f734-4d56-a232-150c86bd6b86)

but this logic will ensure that's always null

<img width="500" alt="image" src="https://github.com/user-attachments/assets/f2130e21-becd-47d8-a12d-1f7b9f190831">

I guess `userView.id` is not a nullable field. 

Let me do some testing and confirm the current behavior. 

FYI: I'm still working through the other comments.

2024-12-05 17:42 UTC, JimmyVo16 commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts
> +export interface EditMemberDialogParams {
> numConfirmedMembers may no longer be required once you remove the reseller toast

Addressed

2024-12-05 18:06 UTC, JimmyVo16 commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/validators/org-seat-limit-reached.validator.ts
> +export function isFixedSeatPlan(productTierType: ProductTierType): boolean {
I'll add tests for `getUniqueNewEmailCount` and `isFixedSeatPlan`.

2024-12-05 18:06 UTC, JimmyVo16 commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts
> -      await this.userService.save(userView);
@eliykat 

The logic was difficult to follow due to the numerous inline conditionals and the coupling between the edit and invite flows. I decided to break this up into separate methods for better readability. All the tests still pass, but I’ll circle back to add tests for any gaps identified by Codecov.

I understand this might make reviewing more challenging, so if you prefer, I can break this into a separate MR.

2024-12-05 21:04 UTC, JimmyVo16 commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts
> -      await this.userService.save(userView);
@eliykat 

After reviewing the code further, I realized we could determine if it's an "invite user" action right from the [button click](https://github.com/bitwarden/clients/blob/main/apps/web/src/app/admin-console/common/base-members.component.ts#L118). What do you think about decoupling the invite user flow from the edit user flow at this point? At a glance, it looks like we could remove 5+ small conditionals, making the code much more straightforward.

I also noticed that passing in InviteMemberDialogParams is inaccurate here since this path is used for both Edit flow and Invite flow. By decoupling them, we can pass in the correct parameter.

With all these refactors, the scope is growing quite large, and I think it justifies creating another PR. Ideally, we should get the refactor in first, but I’d like to hear your thoughts on all of this or whether you think this is not the right path to take.

2024-12-05 21:11 UTC, JimmyVo16 commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts
> -      await this.userService.save(userView);
To clarify, we would have `MembersComponent` override the `invite` method. We won't be modifying the `BaseMembersComponent`.

2024-12-05 21:14 UTC, JimmyVo16 commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts
> +export interface EditMemberDialogParams {
Confirmed that `organizationUserId ` will be null for Invite flow. 

![image](https://github.com/user-attachments/assets/c6e8e3b0-e8d3-448f-bfab-7e4a7d69c442)

2024-12-05 21:28 UTC, JimmyVo16 commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts
> +export interface EditMemberDialogParams {
It looks like we have three cases:
1. Invite new user
2. Edit existing users with a fixed seat plan
3. Edit existing users with a dynamic seat plan

Cases 1 and 2 need the occupied seat count, while case 3 does not.
Cases 2 and 3 will have an organizationUserId since they involve existing users, whereas case 1 will not, as it involves a new user.

I'll create a specific type for each case.

2024-12-06 00:30 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts
> +export interface EditMemberDialogParams {
I think your analysis is right, my only feedback is to think about the API for opening the modal. The caller should know whether they want to invite or edit a user - that's the basic action being undertaken. Also, because "invite" and "edit" are different methods/flows, we're reducing conditional logic by separating them.

On the other hand, asking the caller to figure out what type of plan the organization is on and then alter their call based on that is probably (a) too much to expect the caller to figure out, and (b) can't be known before runtime, so is unlikely to simplify the code flow / number of conditionals.

2024-12-06 14:00 UTC, JimmyVo16 commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts
> +export interface EditMemberDialogParams {
> On the other hand, asking the caller to figure out what type of plan the organization is on and then alter their call based on that is probably (a) too much to expect the caller to figure out, and (b) can't be known before runtime, so is unlikely to simplify the code flow/number of conditionals. There might be diminishing returns in splitting the params at this level of granularity.

Agreed. I think I’ll refactor to separate the edit and invite flows first, then circle back to this. It might not be an issue or might become an easier problem once things are clearer lol.

2024-12-12 22:01 UTC, JimmyVo16 commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts
> +export interface EditMemberDialogParams {
The refactor solves the problem of the invite vs. edit flow; however, the report page is a separate issue since it only uses the edit flow. This specific problem is about validating seats based on the organization type.

I feel that changing the code for the report page to pass in the occupied seats when the validator doesn’t even need them might be an unnecessary effort and could potentially confuse future engineers.

I keep coming back to passing in a nullable value since it’s the simplest solution for now. If we want to explore a more robust approach, it might make sense to spin it off into a separate ticket, especially since this one has already taken up a lot of time.

That said, I don’t think this decision should block the current fix from going out. Let me know what you think. I'm open to other ideas.

2024-12-12 22:02 UTC, JimmyVo16 commented on bitwarden_license/bit-web/src/app/tools/reports/member-access-report/member-access-report.component.ts
> +        // This occupiedSeatCount is not needed for path.
I will update this based on our decision.

2024-12-12 22:07 UTC, JimmyVo16 commented
I will perform final testing after a decision is made on this [thread](https://github.com/bitwarden/clients/pull/12228#discussion_r1870506098).

2024-12-13 03:33 UTC, eliykat commented on apps/web/src/app/admin-console/common/people-table-data-source.ts
> +  }
The table data source doesn't need this info. Its only role is to manage the data source of the table, including sorting and filtering. The `activeUserCount` does reflect the occupied seat count, but that's not a concern of the data source object.

I suggest moving this getter `members.component.ts` where it's actually needed.

2024-12-13 03:33 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts
> +export interface EditMemberDialogParams {
My thinking was that separating add & invite flows (and params) solves this problem. The validator is only on the email input field, which is only needed for the invite flow.

So for example, `setFormValidators` could have an early return, which also acts as a type guard:

```ts
    if (this.isEditDialogParams(this.params)) {
      return;
    }
```

And then you can remove `occupiedSeatCount` from `EditMemberDialogParams`, because it's not needed, and then the reports page doesn't need to pass it in.

2024-12-13 04:02 UTC, eliykat requested changes
I think this worked out well! I know we've spent a bit of time on it, thanks for coming on the journey.

2024-12-13 04:02 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/validators/org-seat-limit-reached.validator.spec.ts
> +    const OccupiedSeatCount = 1;
⛏️  Style:
```suggestion
    const occupiedSeatCount = 1;
```

2024-12-13 16:00 UTC, audreyality reviewed
Some questions and concerns, but otherwise the tools code is looking pretty good!

2024-12-13 16:45 UTC, JimmyVo16 commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts
> +export interface EditMemberDialogParams {
Wow, you're right! The email input control isn't visible for the edit flow. I totally missed this (in hindsight, it's very obvious lol)

Yeah, this should make things a lot easier.

2024-12-13 16:58 UTC, JimmyVo16 commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/validators/org-seat-limit-reached.validator.ts
> +}
Yeah, that sounds good to me. 

Q: which one does `Teams = 2` fall under?

2024-12-13 21:01 UTC, JimmyVo16 commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/validators/org-seat-limit-reached.validator.ts
> +export function isFixedSeatPlan(productTierType: ProductTierType): boolean {
My knowledge of all the nuances of the plans is limited right now, so I’ll lean on Thomas for guidance here. @eliykat thoughts?

2024-12-13 21:04 UTC, JimmyVo16 commented on bitwarden_license/bit-web/src/app/tools/reports/member-access-report/member-access-report.component.ts
> +        // This occupiedSeatCount is not needed for path.
Sorry, I forgot to link to the original thread as I did with [one](https://github.com/bitwarden/clients/pull/12228#issuecomment-2540107399).

That said, we decided to remove this property for this path, and the latest code change reflects that.

2024-12-13 21:41 UTC, JimmyVo16 commented
I will do a regress test for both the member report page and the member page

2024-12-13 22:15 UTC, JimmyVo16 commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts
> +    return params.kind === "Edit";
We can't use `editMode` here since this method is used to determine the `editMode` value.

2024-12-13 22:35 UTC, JimmyVo16 commented
I will continue testing on Monday.

2024-12-13 22:53 UTC, JimmyVo16 commented
Final testing 

[Member page testing.webm](https://github.com/user-attachments/assets/746c606b-1daf-4db1-ac90-6704361a7062)
[Report page testing.webm](https://github.com/user-attachments/assets/7fde48f7-d717-4e80-a8f7-83a0ef605deb)


Seat calculation
When seats are available 

<img width="635" alt="image" src="https://github.com/user-attachments/assets/61c70174-6cdf-4d66-b4d9-d2fc45b0025c" />

When seats are `not` available 

<img width="637" alt="image" src="https://github.com/user-attachments/assets/715a39c5-3884-4887-87de-3ec8f07be0c6" />

2024-12-17 03:26 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts
> +    return params.kind === "Edit";
I meant that this method could replace `this.editMode` altogether. But I think we've worked this over enough, so it's not required.

2024-12-17 14:53 UTC, audreyality approved these changes
👍🏻 Tools code LGTM!

2024-12-17 21:24 UTC, BTreston approved these changes
non-blocking ⛏️ for potential followup PR. Otherwise looks good

2024-12-17 21:24 UTC, BTreston commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.html
> +            this.isEditDialogParams(this.params) &&
We should avoid function calls in the template during data binding. Also you don't need `this.` in the template either.

2024-12-18 15:12 UTC, JimmyVo16 commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.html
> +            this.isEditDialogParams(this.params) &&
Thank you! I'll keep that in mind for the future.

2024-12-18 15:39 UTC, merged