[PM-9111] Extension: persist add/edit form
bitwarden/clients pull request #12236
Opened 2024-12-04 02:39 UTC by nick-livefront

## 🎟️ Tracking

[PM-9111](https://bitwarden.atlassian.net/browse/PM-9111)
[Server PR](https://github.com/bitwarden/server/pull/5106)

## 📔 Objective

Use `ViewCacheService` to store the cipher that is being added/edited to repopulate the form when the extension loses focus and regains focus.
- This stores the `cipher` in the `signal` as it is updated in the form. 
  - The cache is discarded when a navigation occurs which keeps users from seeing stale values.
  - `CipherFormCacheService` is an in-between consuming components and the `ViewCacheService`
- The main logic occurs in `CipherFormComponent`:
  - The `updatedCipherView` is set to the cached cipher if it is available.
  - `getInitialCipherView` allows each of the child components to get the cached cipher to populate their own forms with either the cached cipher or the `updatedCipherView`. This is a change from using `originalCipherView`
  - Cloning also needed a flag to check so `- Clone` is only appended on the initial load of the cloned cipher.
- Both the `PM9111ExtensionPersistAddEditForm` and `PersistPopupView` feature flag should be enabled to use.

<details>

<summary>`PopupViewCacheService.formGroup`</summary>

- `PopupViewCacheService` has a `formGroup` method that will store/create a `formGroup` directly and update the value as the form updates. This didn't work for the cipher form as each child component registers their own individual form as they are initialized in `registerChildForm`. I wasn't able to successfully get this to work with the dynamic & nested form.

- Along the same lines, trying to store each child form in `PopupViewCacheService.formGroup` would require a cache entry for each individual form group alongside repopulating which strays from how the cipher form has a singular form.

- Initialization with `PopupViewCacheService.formGroup` didn't support `FormArray`s we definitely could overcome that with some logic change

</details>

## 📸 Screenshots

#### Adding Ciphers

|Login|Card|Identity|Note|
|-|-|-|-|
|<video src="https://github.com/user-attachments/assets/05a5c95d-c916-45f7-a431-61fdc60c0ce2" />|<video src="https://github.com/user-attachments/assets/ad52e19d-7935-4933-962d-5f42a62cd458" />|<video src="https://github.com/user-attachments/assets/a3ffa4e7-dc88-496d-ae5d-36b345604498" />|<video src="https://github.com/user-attachments/assets/61f16c50-2e68-4923-a35b-0977ca83d92c" />|

#### Other scenarios

|Editing a cipher|Cloning a cipher|
|-|-|
|<video src="https://github.com/user-attachments/assets/916004c0-62f1-431b-ad6f-2fc64f615042" />|<video src="https://github.com/user-attachments/assets/2c438a74-86f1-4d55-a0b1-0b2b068e0d28" />|

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-12-11 21:07 UTC, shane-melton requested changes
I think this approach worked out nicely, great work! I just noticed a few issues and had a few small suggestions.

2024-12-11 21:07 UTC, shane-melton commented on libs/vault/src/cipher-form/services/default-cipher-form-cache.service.ts
> +    this.cipherCache.set({ ...cipherView } as CipherView);
💭 I'm slightly worried this may not be a "deep" enough / separate clone.

For example the item details and auto fill option child forms update the form values during initialization that ends up making changes to the `updatedCipherView` which we're caching here which in turn may be affecting subsequent child forms during initialization.

I did see the item details section having an impact which I described in my other comment about pulling the `collectionIds` reference out. However, when I tried stepping through the auto fill options form with multiple URIs everything appeared to be working, which makes me suspicious that we may just be getting "lucky".

2024-12-11 21:07 UTC, shane-melton commented on libs/vault/src/cipher-form/services/default-cipher-form-cache.service.ts
💭 We should double check that this behaves as expected in the Web client that uses a `NoopViewCacheService`.

2024-12-12 20:55 UTC, nick-livefront commented on libs/vault/src/cipher-form/components/item-details/item-details-section.component.ts
> +      if (!initializedWithCachedCipher) {
Which two conditions? 🤔  Adding `"- Clone"` to the name and setting the `organizationId` are unrelated pieces of logic, combing them with the above check `mode === 'clone'` would tie them together. 

I could be misunderstanding your expected result.

2024-12-12 21:21 UTC, shane-melton commented on libs/vault/src/cipher-form/components/item-details/item-details-section.component.ts
> +      if (!initializedWithCachedCipher) {
Agh, I mis-read the diff and thought adding the `"- Clone"` was the only thing in the `{ }` here. Never mind!

2024-12-13 02:10 UTC, nick-livefront commented on libs/vault/src/cipher-form/services/default-cipher-form-cache.service.ts
> +    this.cipherCache.set({ ...cipherView } as CipherView);
I did some digging, Signals use `Object.is` by default, any new object would fail that equality check update the signal value. [Docs](https://angular.dev/guide/signals#signal-equality-functions).

I think your concern is legitimate and I can't really find an answer to it. If we have a deeply nested object and there is a comparison done against and updated value would it still hold the same reference. 

Do you think it's worth creating a deep clone for it? [structuredClone](https://developer.mozilla.org/en-US/docs/Web/API/Window/structuredClone) is available but the browser support may be too narrow for our liking.

2024-12-13 02:14 UTC, nick-livefront commented on libs/vault/src/cipher-form/services/default-cipher-form-cache.service.ts
> +  private popupViewCacheService: ViewCacheService = inject(ViewCacheService);
👍 [cb5d689](https://github.com/bitwarden/clients/pull/12236/commits/cb5d689cc19be94df11d146ecca23aee7456bd00)

2024-12-13 02:14 UTC, nick-livefront commented on libs/vault/src/cipher-form/services/default-cipher-form-cache.service.ts
> +const POPUP_CIPHER_CACHE_KEY = "popup-cipher-cache";
👍 [cb5d689](https://github.com/bitwarden/clients/pull/12236/commits/cb5d689cc19be94df11d146ecca23aee7456bd00)

2024-12-13 02:15 UTC, nick-livefront commented on libs/vault/src/cipher-form/components/item-details/item-details-section.component.ts
> +    const prefillCollections = prefillCipher.collectionIds?.length
Nice! Catch! This scenario totally slipped by me. 

Updated! [7ef3a7b](https://github.com/bitwarden/clients/pull/12236/commits/7ef3a7b00c484bd537f97b8884e1b62518e1775a)

2024-12-13 02:15 UTC, nick-livefront commented on libs/vault/src/cipher-form/components/item-details/item-details-section.component.ts
> +      collectionIds: prefillCipher.collectionIds,
Updated! [7ef3a7b](https://github.com/bitwarden/clients/pull/12236/commits/7ef3a7b00c484bd537f97b8884e1b62518e1775a)

2024-12-13 02:15 UTC, nick-livefront commented on libs/vault/src/cipher-form/components/cipher-form.component.ts
> +    return this.updatedCipherView;
This one is tripping me but I agree with you. I recall switching from `originalCipherView` to `updatedCipherView` during development but I can't for the life of me remember why.

1) I should write better commit messages
2) I'm betting it was necessary for one of my earlier solutions that didn't pan out. After testing  `originalCipherView` works just fine and makes more sense. We're rolling.

[77c0c19](https://github.com/bitwarden/clients/pull/12236/commits/77c0c19f40a7365e5337bf487bda905e1ec295dd)

2024-12-13 02:16 UTC, nick-livefront commented on libs/vault/src/cipher-form/services/default-cipher-form-cache.service.ts
> +    this.cipherCache.set({ ...cipherView } as CipherView);
For now, I added a comment about the default equality check but I'll update depending on which you think is a good path forward.

[5c0a399](https://github.com/bitwarden/clients/pull/12236/commits/5c0a399e5e47dd37ef5423c55642321bf168d7d8)

2024-12-13 02:16 UTC, nick-livefront commented on libs/vault/src/cipher-form/services/default-cipher-form-cache.service.ts
I haven't seen any preserved values or anything unexpected in the web 🚀

2025-01-09 00:31 UTC, shane-melton submitted a review, later dismissed
This is looking great!

I would also suggest we have QA run through this before we merge unless they or you think otherwise. My thinking is, while the bulk of the functionality is behind a feature flag, we are still making some adjustments to the initialization logic for the child form components.

Also apologies for the delay of this review!

2025-01-10 15:53 UTC, Jingo88 submitted a review, later dismissed

2025-01-14 21:13 UTC, nick-livefront commented
@Jingo88 The Autofill on page load setting was being overwrote because of the URIs were first being added to the form. When the URIs were adding the value of on the form was still `null` causing the existing cipher to then have a `null` value on   the next calls.

I added `emitEvent` false when adding existing URIs to stop this behavior. The `valueChanges` will be emitted when the next call to patch the existing autofill on load value. [af9dc2e](https://github.com/bitwarden/clients/pull/12236/commits/af9dc2e4bdf1fd5d5d3447de89807b319129e894)

2025-01-17 16:18 UTC, Jingo88 submitted a review, later dismissed

2025-01-17 16:27 UTC, Jingo88 approved these changes

2025-01-22 16:34 UTC, Jingo88 approved these changes

2025-01-22 16:43 UTC, nick-livefront commented
@justindbaur When you have time could you give this PR a look?

2025-01-22 16:49 UTC, justindbaur approved these changes

2025-01-22 16:49 UTC, merged