[PM-15545][Defect] Update trial initiation UI for new flow via trial/send-verification-email endpoint
bitwarden/clients pull request #12256
Opened 2024-12-05 13:16 UTC by cyprain-okeke

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-15545
## 📔 Objective

Since we are deprecating the old trial initiation path (we ca no longer access it), we need to apply this new implementation to the new path using the trial/send-verification-email endpoint.
## 📸 Screenshots

**When the trialPayment flag is turn off**
https://github.com/user-attachments/assets/dac94553-5e9e-4a09-97d7-d00187c54700

**When the trialPayment flag is turn on**

https://github.com/user-attachments/assets/c09c3d25-150f-4553-9b80-561b30eb6487

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-12-05 16:09 UTC, JaredSnider-Bitwarden requested changes
Nice work on this, but a few tweaks are needed to add clarity:

2024-12-05 16:09 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/trial-initiation/complete-trial-initiation/complete-trial-initiation.component.ts
> +  protected enableTrialPayment$ = this.configService.getFeatureFlag$(
⚠️ : I think we need to change this variable name (and the `isTrialPaymentEnabled` boolean)  to something more clear to match what the flag is. 

To me, `enableTrialPayment$` being enabled would mean that the user is required to enter payment for setting up a trial. However, according to the videos and the name of the feature flag, that is not correct. 

Can we mirror the name of the feature flag to get added clarity here? Ex: `trialPaymentOptional$`

2024-12-05 16:09 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/trial-initiation/complete-trial-initiation/complete-trial-initiation.component.ts
> +  async handleButtonClick(): Promise<void> {
💡 : can we rename this method to something less generic? It's specifically the button click for the org name entry section so maybe something like `orgNameEntrySubmit` ?

2024-12-05 16:09 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/trial-initiation/complete-trial-initiation/complete-trial-initiation.component.html
> +        {{ isTrialPaymentEnabled ? ("startTrial" | i18n) : ("next" | i18n) }}
❓ : this looks correct to me, but in the videos this never changed from start trial like I expected?

2024-12-05 16:10 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/trial-initiation/complete-trial-initiation/complete-trial-initiation.component.html
> +        {{ isTrialPaymentEnabled ? ("startTrial" | i18n) : ("next" | i18n) }}
Flag off: 
<img width="653" alt="image" src="https://github.com/user-attachments/assets/5797e7cb-3ef3-4e94-b469-948fbabcb217">


Flag on:
![image](https://github.com/user-attachments/assets/a26634d3-b553-4e18-9674-8f5573548e8e)

2024-12-05 18:05 UTC, cyprain-okeke commented on apps/web/src/app/auth/trial-initiation/complete-trial-initiation/complete-trial-initiation.component.html
> +        {{ isTrialPaymentEnabled ? ("startTrial" | i18n) : ("next" | i18n) }}
There are two videos, one for when the flag is on, it removes the billing section and change the next to start trial at organization information stage. And when the flag is off, the billing stage is return and and the button at the organization information stage is next

2024-12-05 18:11 UTC, cyprain-okeke commented on apps/web/src/app/auth/trial-initiation/complete-trial-initiation/complete-trial-initiation.component.ts
> +  protected enableTrialPayment$ = this.configService.getFeatureFlag$(
done

2024-12-05 18:11 UTC, cyprain-okeke commented on apps/web/src/app/auth/trial-initiation/complete-trial-initiation/complete-trial-initiation.component.ts
> +  async handleButtonClick(): Promise<void> {
done

2024-12-05 19:35 UTC, JaredSnider-Bitwarden requested changes

2024-12-05 19:35 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/trial-initiation/complete-trial-initiation/complete-trial-initiation.component.ts
> +    this.isTrialPaymentEnabled = await firstValueFrom(this.trialPaymentOptional$);
❓ : can we change this variable name as well to match `trialPaymentOptional$`?

2024-12-05 19:35 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/trial-initiation/complete-trial-initiation/complete-trial-initiation.component.html
> +        {{ isTrialPaymentEnabled ? ("startTrial" | i18n) : ("next" | i18n) }}
This ternary is not working as written as far as I can tell:
`{{ isTrialPaymentEnabled ? ("startTrial" | i18n) : ("next" | i18n) }}`

In both videos, the button says "Start Trial".  When the flag is off, it should show "next" as you said.

2024-12-05 19:57 UTC, cyprain-okeke commented on apps/web/src/app/auth/trial-initiation/complete-trial-initiation/complete-trial-initiation.component.html
> +        {{ isTrialPaymentEnabled ? ("startTrial" | i18n) : ("next" | i18n) }}
I think, the start Trial was cached by the browsers,  I have updated an updated video

2024-12-05 21:15 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/trial-initiation/complete-trial-initiation/complete-trial-initiation.component.ts
> +    this.trialPaymentOptional$
We should just use `await firstValueFrom` here so that we don't create n subscriptions if the user clicks the submit button rapidly.

2024-12-05 21:40 UTC, JaredSnider-Bitwarden approved these changes
Thank you for your patience with the reviews! Nice work!

2024-12-11 22:02 UTC, JaredSnider-Bitwarden submitted a review, later dismissed

2024-12-12 16:10 UTC, JaredSnider-Bitwarden approved these changes

2024-12-12 16:17 UTC, merged