[PM-12443] Remove paging logic from base clients component and subclassesk
bitwarden/clients pull request #12250
Opened 2024-12-04 20:46 UTC by BTreston

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-12443

## 📔 Objective

This PR adds the new implementations for the provider Clients and ManageClients components with virtual scrolling, sorting, and filtering. These new implementations are protected by a new feature flagged route and the BaseClients component inheritence is removed. All new components are now standalone components.

## 📸 Screenshots

Feature flag turned off:
![Screenshot 2024-12-04 at 3 42 47 PM](https://github.com/user-attachments/assets/2200402e-4e00-40f5-a435-b39fe659568a)
![Screenshot 2024-12-04 at 3 44 20 PM](https://github.com/user-attachments/assets/7e01519a-e1e6-4888-8867-428e0b528906)

Feature flag turned on:
![Screenshot 2024-12-04 at 3 45 27 PM](https://github.com/user-attachments/assets/1929e1b9-1288-4593-821f-412f2e2d61aa)
![Screenshot 2024-12-04 at 3 45 17 PM](https://github.com/user-attachments/assets/11af0ba2-191f-43fe-a479-9f058f280dd8)

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-12-06 02:30 UTC, eliykat requested changes
In your screenshots, the ManageComponent appears without the individual row menus when the flag is off, but the cog menus appear when the flag is on. Is this right? What has caused this change? Can you check with Sukhleen whether the cog is still the current design? It looks a bit out of place.

Also, please make sure that you've tested this yourself with lots of rows and scrolled around and make sure that it's displaying properly - just to make sure virtual scrolling is working as expected. (The easiest way is to add some temporary code to fill up your TableDataSource with test data.)

Overall looks great!

2024-12-06 02:30 UTC, eliykat commented on bitwarden_license/bit-web/src/app/billing/providers/clients/vnext-manage-clients.component.ts
> +          data.organizationName.toLowerCase().startsWith(searchText.toLowerCase());
I think `startsWith` is too restrictive, generally we use `indexOf` for a more permissive search. (e.g. see the default search implementation: https://github.com/bitwarden/clients/blob/main/libs/components/src/table/table-data-source.ts#L227)

2024-12-06 02:30 UTC, eliykat commented on bitwarden_license/bit-web/src/app/billing/providers/clients/vnext-manage-clients.component.ts
> +  protected destroy$ = new Subject<void>();
You should be able to use `takeUntilDestroyed()` instead of the old `this.destroy$` pattern. I think that requires that the code in `ngOnInit` is moved to the ctor, but none of it's async so that shouldn't be an issue.

2024-12-06 02:30 UTC, eliykat commented on bitwarden_license/bit-web/src/app/billing/providers/clients/vnext-manage-clients.component.ts
> +    this.clients.map((client) => (client.plan = client.plan.replace(" (Monthly)", "")));
Good call removing this from the template.

`map` returns a new array, it's clearer to use `forEach` when you're mutating the existing array:

```suggestion
    this.clients.forEach((client) => (client.plan = client.plan.replace(" (Monthly)", "")));
```

2024-12-06 02:30 UTC, eliykat commented on bitwarden_license/bit-web/src/app/billing/providers/clients/vnext-manage-clients.component.ts
> +  clients: ProviderOrganizationOrganizationDetailsResponse[];
`clients` doesn't need to be a class property. It looks like it can be local to the `load` method, and the template can reference `dataSource.data`.

2024-12-06 02:30 UTC, eliykat commented on bitwarden_license/bit-web/src/app/billing/providers/clients/vnext-manage-clients.component.ts
> +  ngOnInit(): void {
I think this is missing the search param logic from the current base class: https://github.com/bitwarden/clients/blob/main/bitwarden_license/bit-web/src/app/admin-console/providers/clients/base-clients.component.ts#L56-L60

2024-12-06 02:30 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/providers/clients/vnext-clients.component.ts
Same feedback applies here as the other component class.

2024-12-06 02:30 UTC, eliykat commented on bitwarden_license/bit-web/src/app/billing/providers/clients/vnext-manage-clients.component.html
> +  <bit-table-scroll [dataSource]="dataSource" [rowSize]="47" class="table table-hover table-list">
`rowSize` should be the height of each row in pixels. Please make sure you've used devtools to inspect the actual current height and that this is set accurately. (I only mention it because this is the same value as in the documentation example, if it really is 47px high then that's fine.)

2024-12-06 10:45 UTC, jonashendrickx submitted a review, later dismissed

2024-12-06 15:34 UTC, BTreston commented
> In your screenshots, the ManageComponent appears without the individual row menus when the flag is off, but the cog menus appear when the flag is on. Is this right? What has caused this change? Can you check with Sukhleen whether the cog is still the current design? It looks a bit out of place.
> 
> Also, please make sure that you've tested this yourself with lots of rows and scrolled around and make sure that it's displaying properly - just to make sure virtual scrolling is working as expected. (The easiest way is to add some temporary code to fill up your TableDataSource with test data.)
> 
> Overall looks great!

@eliykat  In the ManageComponent, the cog appears on row hover, so its still there. I'll confirm the expected behavior just to be sure. I did test the virtual scroll, I'll attach a video as well for completeness.

2024-12-06 17:14 UTC, BTreston commented on bitwarden_license/bit-web/src/app/billing/providers/clients/vnext-manage-clients.component.html
> +  <bit-table-scroll [dataSource]="dataSource" [rowSize]="47" class="table table-hover table-list">
old is 53.5px and new ends up being 53px. If we want I can add the half pixel to keep it the same, but I figured not having the half px is a bit cleaner.

2024-12-09 03:35 UTC, eliykat commented on bitwarden_license/bit-web/src/app/billing/providers/clients/vnext-manage-clients.component.html
> +  <bit-table-scroll [dataSource]="dataSource" [rowSize]="47" class="table table-hover table-list">
This `rowSize` doesn't affect the actual height of the row. It's used by virtual scroll to calculate how much is visible at a time and how large the scroll container needs to be. So it needs to accurately _represent_ the height of the row (otherwise we get visual defects).

> The <cdk-virtual-scroll-viewport> displays large lists of elements performantly by only rendering the items that fit on-screen. Loading hundreds of elements can be slow in any browser; virtual scrolling enables a performant way to simulate all items being rendered by making the height of the container element the same as the height of total number of elements to be rendered, and then only rendering the items in view. Virtual scrolling is different from strategies like infinite scroll where it renders a set amount of elements and then when you hit the end renders the rest.

[ref](https://material.angular.io/cdk/scrolling/overview#virtual-scrolling)

So the half px doesn't matter, provided that whatever it is, `rowSize` accurately reflects the actual height. If you want to lock it to 53px high then you can do that using Tailwind like normal.

(Sorry if this is over-explained, just making sure we're on the same page.)

2024-12-09 03:37 UTC, eliykat reviewed
Looks good pending
- design feedback on the cogs
- rowSize discussion above

@jonashendrickx could you please have a look at [my comment above](https://github.com/bitwarden/clients/pull/12250#discussion_r1872454786) and let me know what you think?

2024-12-09 15:08 UTC, BTreston commented
> Looks good pending
> 
>     * design feedback on the cogs
> 
>     * rowSize discussion above
> 
> 
> @jonashendrickx could you please have a look at [my comment above](https://github.com/bitwarden/clients/pull/12250#discussion_r1872454786) and let me know what you think?

The rowSize is changed to match the actual row height. Feedback from product says the cog is fine.

2024-12-09 23:47 UTC, eliykat approved these changes
LGTM, would be good to remove the duplicate route guard code in the components depending on Billing's feedback, but also not essential.

2024-12-10 17:56 UTC, jonashendrickx approved these changes

2024-12-11 14:53 UTC, merged