[PM-14366] Deprecated active user state from billing state service
bitwarden/clients pull request #12273
Opened 2024-12-06 16:20 UTC by cturnbull-bitwarden

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-14366

## 📔 Objective

This PR updates the `BillingAccountProfileStateService` to remove its dependency on `ActiveUserStateProvider` by requiring explicit user IDs when checking premium status. This change:

1. Modifies the service's public observables to accept a `userId` parameter instead of relying on the active user state
2. Removes the internal state tracking of the active user
3. Updates all consumers of the service to pass the active user's ID by combining with `AccountService.activeAccount$`, often via a `switchMap`, or otherwise, `firstValueFrom`

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-12-09 15:07 UTC, audreyality reviewed
Just a nit. There are also failing unit tests that need to be addressed.

2024-12-09 15:07 UTC, audreyality commented on apps/cli/src/tools/send/commands/create.command.ts
> +        ) {
```suggestion
        const hasPremium$ = this.accountService.activeAccount$.pipe(
          switchMap(({id}) => this.accountProfileService.hasPremiumFromAnySource(id)
          )
        );
        if (!(await firstValueFrom(hasPremium$)) {
```

2024-12-09 16:40 UTC, willmartian requested changes

2024-12-09 16:40 UTC, willmartian commented on apps/web/src/app/layouts/user-layout.component.ts
> +      ),
Could this instead be added to some relevant service? Such that this block could be updated to:

```ts
this.showSubscription$ = this.someService.showSubscriptionInNav$;  // etc
```

That way the internal logic is fully owned by the appropriate team, rather than existing in this shared component.

2024-12-11 16:56 UTC, gbubemismith requested changes
Just added a few suggestions and pointed out some failing tests. Thanks for working on this

2024-12-11 16:56 UTC, gbubemismith commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +            ),
I think this can be simplified, we have activeUserId initialized on L288

```suggestion
            this.billingAccountProfileStateService.hasPremiumFromAnySource$(this.activeUserId)
```

2024-12-11 16:56 UTC, gbubemismith commented on apps/web/src/app/vault/individual-vault/vault-banners/services/vault-banners.service.ts
⚠️ Tests are failing for this service. They need to be updated to handle the AccountService dependency

2024-12-11 16:56 UTC, gbubemismith commented on apps/web/src/app/vault/individual-vault/add-edit.component.ts
> +      ),
can we do this instead?

``` ts
const activeUserId = await firstValueFrom(
  this.accountService.activeAccount$.pipe(map(a => a.id))
);

this.canAccessPremium = await firstValueFrom(
  this.billingAccountProfileStateService.hasPremiumFromAnySource$(activeUserId)
);
```

2024-12-11 16:56 UTC, gbubemismith commented on apps/cli/src/vault/create.command.ts
> +    const account = await firstValueFrom(this.accountService.activeAccount$);
I think we can delete this and move the `activeUserId` declared on L155 out of the try scope

2024-12-11 16:56 UTC, gbubemismith commented on apps/browser/src/vault/popup/components/vault-v2/attachments/open-attachments/open-attachments.component.ts
⚠️ A test is failing for this component.

2024-12-17 18:40 UTC, jonashendrickx approved these changes

2024-12-17 19:50 UTC, cturnbull-bitwarden commented on libs/angular/src/vault/components/view.component.ts
> +    const activeAccount = await firstValueFrom(this.accountService.activeAccount$);
Done! Take a look at the latest updates

2024-12-17 19:51 UTC, cturnbull-bitwarden commented on apps/web/src/app/vault/individual-vault/vault-banners/services/vault-banners.service.ts
Resolved

2024-12-17 19:51 UTC, cturnbull-bitwarden commented on apps/web/src/app/vault/individual-vault/add-edit.component.ts
> +      ),
Definitely, pushed the update

2024-12-17 19:59 UTC, audreyality approved these changes
👍🏻 Tools code LGTM!

🤔 I wonder whether there's places that `of` will fail because it completes. Where `firstValueFrom` or `combineLatest` is used it shouldn't cause any issues since those keep the "singularity" of the last (only) emitted value. If there are places that expect the observable to change value instead of completing, then there could be a lot of non-responsive UI.

I guess what I'm saying is, please run the regression suite on this before merge, if we can, since this PR affects so much.

2024-12-17 20:04 UTC, willmartian commented on apps/web/src/app/layouts/user-layout.component.ts
> +  }
Much better, thank you! Any reason to not move the `AccountService` dependency inside the service as well? Such that we could do:

```ts
this.showSubscription$ =  this.billingAccountProfileStateService.activeAccountCanViewSubscription$;
```

or, the active account could be the default if no account ID is provided:

```ts
this.showSubscription$ =  this.billingAccountProfileStateService.canViewSubscription()$;
```

There might be reasons to not do this! Curious what you think @cturnbull-bitwarden

2024-12-17 20:08 UTC, JaredSnider-Bitwarden submitted a review, later dismissed
Auth changes look good.

2024-12-17 20:11 UTC, willmartian approved these changes

2024-12-17 20:22 UTC, cturnbull-bitwarden commented on apps/web/src/app/layouts/user-layout.component.ts
> +  }
It's a good question! I decided to keep `BillingAccountProfileStateService` independent of `AccountService` for a couple of reasons:

1. Simply speaking, I wanted to maintain a clear dependency direction and avoid introducing `AccountService` as a hard dependency
2. My thinking for `BillingAccountProfileStateService` was that it should have a single responsibility - managing the state of billing's premium flags using the `StateProvider` pattern

That said, after implementing this, I've still had to map `AccountService.activeAccount$` in a bunch places to avoid using `ActiveUserStateProvider`. I'm open to revisiting this design in a follow-up PR.

2024-12-17 20:47 UTC, BTreston approved these changes
Just some non-blocking ⛏️'s. Otherwise looks good!

2024-12-17 22:03 UTC, gbubemismith submitted a review, later dismissed
Changes look good. Thanks.

2024-12-18 10:47 UTC, dani-garcia approved these changes

2024-12-18 13:24 UTC, justindbaur commented on apps/web/src/app/core/guards/has-premium.guard.ts
> +      ),
No need to do this on this PR but I worry that some of the routes might navigate to a route protected with this right after logging in. Since active user state wouldn't emit until an account is set as active it would have delayed until that happened. I think we should give it a grace period to allow the account to come in and if it doesn't happen in a reasonable time throw an error because I think it would likely be a developer error. 

```suggestion
      filter((account) => account != null),
      timeout({
        first: 2000,
        with: () => {
          throw new Error("An active user is expected when checking if a user has premium.");
        },
      }),
      switchMap((account) =>
        billingAccountProfileStateService.hasPremiumFromAnySource$(account.id),
      ),
```

Please don't worry about doing this here though, you've got a lot of approvals and I can throw up a small PR doing it after you merge.

2024-12-18 14:34 UTC, jprusik commented on apps/browser/src/autofill/browser/main-context-menu-handler.ts
> +      );
oo, moving this out of the loop was a good idea; thanks 👍

2024-12-18 14:35 UTC, jprusik approved these changes
Approved for Autofill concerns

2024-12-18 18:53 UTC, willmartian commented on apps/web/src/app/layouts/user-layout.component.ts
> +  }
> avoid introducing AccountService as a hard dependency

🎨 

IMO, `AccountService` _is already_ a hard dependency of the service as written. Consumers can't use the methods unless they have an account ID (often, the active account ID). This is evident by the number of times we needed to import `AccountService` in the PR. My gut says: if we always need to import a peer dep, maybe that dep should be brought into the service. 

Larger questions at play here: when is it appropriate to push dependencies onto the consumer of a service? Should services that act on accounts provide convenience methods that target the active account, since it is most often interacted with? Gonna share in Slack to see if others have strong opinions.

2024-12-18 20:29 UTC, cturnbull-bitwarden commented on apps/browser/src/vault/popup/components/action-buttons.component.ts
> +        takeUntil(this.componentIsDestroyed$),
Thanks for the suggestion! I created a tech debt task [here](https://bitwarden.atlassian.net/browse/PM-16205) for us to handle this in a follow-up PR

2024-12-23 17:34 UTC, cturnbull-bitwarden commented
I just addressed a broken unit test from a change in `main`. I'll wait to re-request reviews until QA has finished testing!

2024-12-23 20:53 UTC, jprusik submitted a review, later dismissed

2025-01-06 14:43 UTC, gbubemismith submitted a review, later dismissed

2025-01-06 14:50 UTC, audreyality approved these changes

2025-01-06 14:58 UTC, jonashendrickx submitted a review, later dismissed

2025-01-06 15:44 UTC, gbubemismith submitted a review, later dismissed

2025-01-06 15:45 UTC, jonashendrickx approved these changes

2025-01-06 15:53 UTC, audreyality approved these changes

2025-01-06 16:57 UTC, addisonbeck submitted a review, later dismissed

2025-01-06 18:02 UTC, willmartian approved these changes

2025-01-06 19:06 UTC, BTreston submitted a review, later dismissed

2025-01-06 19:12 UTC, JaredSnider-Bitwarden approved these changes

2025-01-06 20:23 UTC, JaredSnider-Bitwarden approved these changes

2025-01-06 20:25 UTC, audreyality approved these changes

2025-01-06 20:33 UTC, gbubemismith approved these changes

2025-01-06 21:01 UTC, BTreston approved these changes

2025-01-06 22:48 UTC, willmartian approved these changes

2025-01-07 11:17 UTC, dani-garcia approved these changes

2025-01-07 14:22 UTC, jonashendrickx approved these changes

2025-01-07 15:25 UTC, merged