[CL-510] Create slot for banners in popup-page component
bitwarden/clients pull request #12279
Opened 2024-12-06 22:24 UTC by jprusik

## 🎟️ Tracking

CL-510

## 📔 Objective

The popup-page component should have a banner content projection slot for banners. This slot will have zero margin, unlike slot="above-scroll-area".

## 📸 Screenshots

![Screenshot 2024-12-06 at 5 23 25 PM](https://github.com/user-attachments/assets/020d0c37-9480-4b8a-a25b-d0089d8044ae)
![Screenshot 2024-12-06 at 5 23 06 PM](https://github.com/user-attachments/assets/163bbfb2-f9d9-4a1e-adf4-5410bedda744)

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-12-14 20:49 UTC, willmartian requested changes
Thanks for adding this! One thing:

2024-12-14 20:49 UTC, willmartian commented on apps/browser/src/platform/popup/layout/popup-page.component.html
> +  <div class="tw-transition-colors tw-duration-200 tw-border-0 tw-border-solid">
I do not believe the classes on this `div` are necessary. The `div` itself is probably also not necessary.

2024-12-16 17:43 UTC, danielleflinn submitted a review, later dismissed

2024-12-18 22:15 UTC, jprusik commented on apps/browser/src/platform/popup/layout/popup-page.component.html
> +  <div class="tw-transition-colors tw-duration-200 tw-border-0 tw-border-solid">
even better, thanks 🙌 

addressed in 4f0d1b09cbe38229d262211b2667f00529e05a33

2024-12-18 22:16 UTC, danielleflinn approved these changes

2024-12-19 21:47 UTC, willmartian approved these changes
Looks great, thanks!

2024-12-19 21:47 UTC, merged