[PM-13755] Decouple Invite and Edit User Flows
bitwarden/clients pull request #12277
Opened 2024-12-06 21:10 UTC by JimmyVo16

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-14826

## 📔 Objective

Refactor the code to separate the invite and edit user flows, improving readability by reducing conditional complexity and decoupling responsibilities.

For members.component.ts
1. Create an overload `invite` method and move all the invite user flow from `edit` method into it.

For member-dialog.component.ts
1. Refactor the submit method into smaller methods with more focused responsibilities: `handleEditUser`, `handleInviteUsers`, and `getUserView`.
2. Remove the toast in the `submit` method as form validation prevents this code from being executed. [Discussion](https://bitwarden.slack.com/archives/C030X6FR3RD/p1733331018548869?thread_ts=1733307883.524059&cid=C030X6FR3RD)

No new visible behavior was introduced.

## 📸 Screenshots

Tested by going through invite, edit, revoke, and remove

[Regression testing.webm](https://github.com/user-attachments/assets/ad3e7247-1c07-4e35-be57-b5abb13258af)

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-12-09 04:27 UTC, eliykat requested changes
All makes sense to me! Minor feedback only.

Also note your Jira ticket link is wrong.

2024-12-09 04:27 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/members/members.component.ts
> +  async invite(initialTab: MemberDialogTab = MemberDialogTab.Role) {
Please use early returns in this method rather than if/else if/else.

2024-12-09 04:27 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/members/members.component.ts
The order of methods in this class could also be improved. I think it's easier to read and understand when the layout of the code roughly reflects the call chain, and related methods are grouped together. e.g.

- invite
- handleSeatLimitForFixedTiers
- handleInviteDialog
- edit

etc

2024-12-09 04:27 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/members/members.component.ts
Please address the FIXMEs in this file as well. (Looking up the eslint rule/s should provide context but let me know if you have any questions.)

2024-12-09 20:05 UTC, JimmyVo16 commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts
> +  private async handleInviteUsers(userView: OrganizationUserAdminView, organization: Organization) {
Oh, I like this pattern as well, declaring variables/methods closer to their use. I noticed that all the private methods were at the top, so I assumed that was the pattern. Good to know that’s not the case. I’ll go ahead and make the change.

2024-12-09 20:14 UTC, JimmyVo16 commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts
> +  private async handleInviteUsers(userView: OrganizationUserAdminView, organization: Organization) {
Yup, that's correct! I added a comment in the object, but it might not be immediately obvious since it doesn’t have a clear name to reference lol

2024-12-11 02:02 UTC, eliykat requested changes

2024-12-11 02:02 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts
> +    this.setInputEmailCountValidator(organization, emails.length);
Validators should be attached when the form is first initialized, so that the user gets immediate feedback when filling it out. You should delete `setInputEmailCountValidator` and attach your validator in the existing `setFormValidators` method.

2024-12-11 19:08 UTC, JimmyVo16 commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/validators/org-seat-limit-reached.validator.spec.ts
> +    });
I thought it wouldn't matter since the variable is essentially a constant, but you're right there is a risk and it's wise to be defensive.

A question for the future: is there any preference between these two options?

option 1, basically what you have
```ts
let teamsStarterOrganization: Organization;
beforeEach(() => {
  teamsStarterOrganization = orgFactory(...);
});

it("...") // etc
```

Option 2
```ts
it("test 1", () => {
  // Arrange
  const organization = orgFactory({
    productTierType: ProductTierType.Enterprise,
    seats: 100,
  });
});

it("test 2", () => {
  // Arrange
  const organization = orgFactory({
    productTierType: ProductTierType.Enterprise,
    seats: 100,
  });
});
```

2024-12-11 19:26 UTC, JimmyVo16 commented
Testing 
[Code review testing 2.webm](https://github.com/user-attachments/assets/f71f0304-700c-42d2-9f5f-58f0a38d4627)

2024-12-11 19:45 UTC, JimmyVo16 commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/validators/org-seat-limit-reached.validator.ts
> +export function inputEmailLimitValidator(
Question: Does this mean that most of the time, validator files will contain only one validator?

2024-12-12 00:17 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/validators/org-seat-limit-reached.validator.spec.ts
> +    });
The variable assignment is a constant, but the value is mutable. It is defensive, but we err on the side of not letting unit tests affect each other.

I prefer option 1: moving common setup code into a `beforeEach`.

2024-12-12 00:20 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/validators/org-seat-limit-reached.validator.ts
> +export function inputEmailLimitValidator(
Yes I think that's a fair rule. But in general it's about having smaller, single-purpose files.

2024-12-12 00:42 UTC, eliykat reviewed
You also have some failures caused by strict typechecking: https://github.com/bitwarden/clients/actions/runs/12283466303/job/34277004841

It's a bit premature to start solving these, I suggest adding the magic comment to the top of the offending files:

```ts
// FIXME: Update this file to be type safe and remove this and next line
// @ts-strict-ignore
```

2024-12-12 00:42 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts
> +    emailsControl.setValidators(_inputEmailLimitValidator);
Check out the documentation for `setValidators`: https://v17.angular.io/api/forms/AbstractControl#setValidators

> Sets the synchronous validators that are active on this control. Calling this overwrites any existing synchronous validators.

What you're actually doing here is:
- setting the `required`, `commaSeparatedEmails` and `orgSeatLimitReachedValidator` validators;
- then overwriting those with the `required`, `commaSeparatedEmails` and `inputEmailValidator` validators.

So you're setting some twice, and losing `orgSeatLimitReachedValidator`.

You should call `setValidators` once with an array of all the validators you want to set.

Also, the underscore prefix (`_`) _may_ be used for private properties (it's not a strict pattern like it is in C#) but shouldn't be used for local variables.

2024-12-12 15:42 UTC, JimmyVo16 commented
> You also have some failures caused by strict typechecking: https://github.com/bitwarden/clients/actions/runs/12283466303/job/34277004841
> 
> It's a bit premature to start solving these, I suggest adding the magic comment to the top of the offending files:
> 
> ```ts
> // FIXME: Update this file to be type safe and remove this and next line
> // @ts-strict-ignore
> ```
I was looking at this yesterday. The only thing that I'm confused about is that this isn't my change. I guess the type check goes through the whole code repo or code paths?

Either way, I'm going to do what you suggested.

2024-12-12 16:46 UTC, JimmyVo16 commented
Testing Code review 3
[Testing 3.webm](https://github.com/user-attachments/assets/9a63b394-0072-4969-b076-01172f45cbe3)

2024-12-13 03:08 UTC, eliykat commented
> I was looking at this yesterday. The only thing that I'm confused about is that this isn't my change. I guess the type check goes through the whole code repo or code paths?

You're right - my bad. `main` was broken, so when you updated your branch you pulled in the failures. `main` is now fixed so it resolved itself when you last updated your branch. :)

This lgtm!

2024-12-13 03:09 UTC, eliykat submitted a review, later dismissed

2024-12-19 01:22 UTC, eliykat submitted a review, later dismissed

2025-01-13 16:04 UTC, ttalty submitted a review, later dismissed

2025-01-20 20:13 UTC, JimmyVo16 commented
I did some regression tests for the Free and the family tiers to make sure my changes and Brandon's changes are both working.


https://github.com/user-attachments/assets/944afd2b-3042-4418-8627-f71a6ececd61


https://github.com/user-attachments/assets/f64ff941-3ad5-4316-80e9-bfc825d9eb5f

2025-01-21 16:51 UTC, BTreston requested changes
One question and a few suggestions. Otherwise looks good

2025-01-21 16:51 UTC, BTreston commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.html
> +        *ngIf="!loading && this.isEditDialogParams(this.params) && params.name"
⛏️ we should avoid function calls in the template when possible, accessing this property directly rather than through the function would do that.

2025-01-21 18:04 UTC, JimmyVo16 commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts
> +  private noMasterPasswordConfirmationDialog(username: string) {
The refactor in this code separates `edit user flow` and `add user flow`. The name only exists in the `edit user flow` and not the `add user flow` because the user doesn't exist at this point. 

This turns `noMasterPasswordConfirmationDialog` into a pure function that just gets called when needed vs having to decide in the function of which flow it's in.

2025-01-21 18:22 UTC, JimmyVo16 commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.html
> +        *ngIf="!loading && this.isEditDialogParams(this.params) && params.name"
I'll push up a change for this

2025-01-21 18:24 UTC, JimmyVo16 commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts
> +  isEditDialogParams(
We're using this method to get type guard for `params`.

2025-01-22 16:07 UTC, BTreston approved these changes

2025-01-22 16:18 UTC, ttalty approved these changes

2025-01-22 20:27 UTC, eliykat commented
@BTreston has this covered so no need to get a review from me 👍

2025-01-23 19:24 UTC, merged