[PM-15635] Folders not working on desktop
bitwarden/clients pull request #12333
Opened 2024-12-10 17:41 UTC by gbubemismith

## 🎟️ Tracking
https://bitwarden.atlassian.net/browse/PM-15635

## 📔 Objective
On desktop, each user isn’t getting their own folders. Any edits to folders are happening to all users, and it’s showing the same folders on every user. Browser appears to be fine.

## 📸 Screenshots

https://github.com/user-attachments/assets/3078878a-19a5-4144-abab-bb1aa39ab812

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-12-10 17:58 UTC, shane-melton requested changes
Just one issue with some missing clears on the `replace` and `delete` methods

2024-12-10 17:58 UTC, shane-melton commented on libs/common/src/vault/services/folder/folder.service.ts
> +      switchMap(([userId, folderData]) => {
💭 While I don't think its causing an issue here, its seems like a bit of a code smell that we're overriding the same `userId` identifier for both the `folderView$()` and `switchMap()` scopes. 

Do we need to use the `combinedState$`? Could we just rely on the `encryptedFolderState(userId)` to always return data for the provided `userId`?

2024-12-10 17:58 UTC, shane-melton commented on libs/common/src/vault/services/folder/folder.service.ts
⚠️ The `replace` and `delete` methods in this file do not explicitly clear the `decryptedFolderState` which will lead to out of sync data between the decrypted `folderViews$` and the encrypted `folders$` observables.

2024-12-10 18:04 UTC, gbubemismith commented on libs/common/src/vault/services/folder/folder.service.ts
> +      switchMap(([userId, folderData]) => {
Yeah we don't need the combinedstates anymore

2024-12-11 22:00 UTC, shane-melton approved these changes

2024-12-11 22:09 UTC, gbubemismith commented on libs/common/src/vault/services/key-state/folder.state.ts
> +  "folder",
Yeah I think changing it would help

2024-12-13 11:37 UTC, addisonbeck approved these changes

2024-12-17 01:52 UTC, merged