[PM-12273] use organization properties for access permissions
bitwarden/clients pull request #12358
Opened 2024-12-11 20:33 UTC by BTreston

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-12273

## 📔 Objective

This PR adds access permissions to the integrations page and the tabs within the integration page.

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-12-11 23:48 UTC, eliykat commented
This is a rebase of #12260 so I've added @JimmyVo16 back to it as the other reviewer of that PR.

2024-12-12 01:40 UTC, eliykat requested changes

2024-12-12 01:40 UTC, eliykat commented on libs/common/src/admin-console/models/domain/organization.ts
> +    return this.isAdmin || this.userIsManagedByOrganization || this.canAccessEventLogs;
Following up on [this comment](https://github.com/bitwarden/clients/pull/12260#discussion_r1880382614):

>From Priya, roles allowed to access the page are:
Owners
Admins
Manage users
Manage groups
Access event logs

`userIsManagedByOrganization` is referring to "claimed" users (i.e. users whose email address domain has been verified by the organization), which is unrelated to what you're doing here. Manage users, manage groups, and access event logs are all custom permissions, which you can check on the `this.permissions` object.

Each custom permission also has a corresponding getter (e.g. `this.canAccessEventLogs`); that is also fine to use, although _within_ the organization class I personally prefer to be more exact about the roles/permissions required. (You'll see that the getters have nested logic to refer to all higher roles.)

2024-12-12 01:40 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/layouts/organization-layout.component.ts
> +          switchMap(() => this.organizationApiService.getPlanType(org.id)),
Could you make this logic use the `organization.productTierType` instead? I suggest this for a few reasons
1. it lets you refer to the general tier of the plan (e.g. Families) rather than specific years (which exist for grandfathering in pricing, e.g. Families2019). That may be what you're after here if you don't actually care about the plan year.
2. it's simpler
3. it avoids an extra api call just to load the basic layout component

2024-12-12 01:40 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/layouts/organization-layout.component.ts
> +          ),
This is duplicating the `organization.canAccessIntegrations` logic. Ideally the route guard logic and the "show navigation button" logic should be identical (in this case, referring to the same getter on the organization logic).

2024-12-12 16:59 UTC, JimmyVo16 commented on apps/web/src/app/admin-console/organizations/layouts/organization-layout.component.ts
> +        ).pipe(filter((enabled) => enabled && org.isAdmin && org.canAccessIntegrations)),
Non-blocking comment: It looks like we already checked for `isAdmin` in `canAccessIntegrations`. Do we need it here as well?

2024-12-12 17:06 UTC, JimmyVo16 requested changes
The code changes look good to me, but could you post a screenshot of the testing artifact?

2024-12-12 21:12 UTC, BTreston commented
> The code changes look good to me, but could you post a screenshot of the testing artifact?
![Screenshot 2024-12-12 at 4 04 14 PM](https://github.com/user-attachments/assets/d5c04665-10c3-48c8-8880-ae5854c60702)
![Screenshot 2024-12-12 at 4 03 51 PM](https://github.com/user-attachments/assets/bcf4f876-68c8-4277-92f2-6bf957cdcddf)

2024-12-13 04:11 UTC, eliykat requested changes
LGTM, just 1 minor change

2024-12-13 04:11 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/layouts/organization-layout.component.ts
> +        ).pipe(filter((enabled) => enabled && org.canAccessIntegrations)),
You can use `map` rather than `switchMap` if your callback does not return a promise or observable. e.g.

```ts
      map(([org, featureFlagEnabled]) =>
          (org.productTierType === ProductTierType.Enterprise ||    // no need to use of
            org.productTierType === ProductTierType.Teams) &&
            featureFlagEnabled &&
            org.canAccessIntegrations)),
```

However in this case, the `productTierType` affects whether the org can access the integrations page, so really it should be:

```ts
      map(([org, featureFlagEnabled]) =>
            featureFlagEnabled &&
            org.canAccessIntegrations)),
```

And the `org.canAccessIntegrations` getter should include the `ProductTierType` check.
Otherwise someone is liable to use the org getter without knowing to do the plan check as well.

2024-12-13 15:04 UTC, JimmyVo16 approved these changes

2024-12-15 22:33 UTC, eliykat approved these changes
Great work, thank you!

2024-12-15 22:33 UTC, merged