[PM-12985] - Updating reports to use new modal for view/edit cipher
bitwarden/clients pull request #12383
Opened 2024-12-12 20:37 UTC by cd-bitwarden

## 🎟️ Tracking

## 📔 Objective

Updating reports to use new modal for view/edit cipher
dialog

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-12-13 15:35 UTC, audreyality commented on apps/web/src/app/shared/loose-components.module.ts
🤔 This module seems rather loosely defined. There may be nothing wrong, but I'm wondering what alternatives there are?

2024-12-20 14:13 UTC, djsmith85 requested changes
@cd-bitwarden: Overall the changes are looking good. Just one thing about the missing reprompt and the tests are currently failing. Then this should be good to go

2024-12-20 14:13 UTC, djsmith85 commented on apps/web/src/app/tools/reports/pages/cipher-report.component.ts
> -    }
We should still include the check for the reprompt before showing the view-window

2024-12-31 22:11 UTC, JimmyVo16 submitted a review, later dismissed

2025-01-09 14:12 UTC, djsmith85 submitted a review, later dismissed

2025-01-10 15:49 UTC, Jingo88 submitted a review, later dismissed

2025-01-10 20:21 UTC, JimmyVo16 submitted a review, later dismissed

2025-01-14 15:03 UTC, djsmith85 approved these changes

2025-01-14 19:38 UTC, Jingo88 submitted a review, later dismissed

2025-01-14 19:42 UTC, JimmyVo16 submitted a review, later dismissed

2025-01-23 19:34 UTC, rr-bw approved these changes

2025-01-29 21:03 UTC, djsmith85 approved these changes

2025-01-29 21:25 UTC, Jingo88 approved these changes

2025-01-30 20:42 UTC, JimmyVo16 approved these changes

2025-02-14 16:17 UTC, Jingo88 submitted a review, later dismissed

2025-02-14 16:22 UTC, djsmith85 approved these changes

2025-02-21 13:32 UTC, djsmith85 approved these changes

2025-02-21 13:44 UTC, Jingo88 approved these changes

2025-02-21 13:45 UTC, merged