[CL-509] Avoid double scrollbar appearing when default zoom is >100%
bitwarden/clients pull request #12427
Opened 2024-12-16 15:24 UTC by vleague2

## 🎟️ Tracking

[CL-509](https://bitwarden.atlassian.net/browse/CL-509)

## 📔 Objective

When the default zoom is set to >100% in a chromium-based browser, the browser extension was displaying a 2nd scrollbar. This was due to the fact that we had set the extension to the max chrome extension height of 600px, but when zoomed in, less than 600px of height were available. This caused the content to need to scroll to reach its 600px height. 

We had some code already to adjust the max height of the extension depending on how many pixels were available, but it was not working. This PR updates the checks so that the code works and applies the correct body size class for the height available, and also adds a check for the extension being open in a chrome tab so that we can ensure it stretches to fill the content in a tab.

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-12-16 16:17 UTC, vleague2 commented on apps/browser/src/platform/popup/layout/popup-page.component.ts
> -    class: "tw-h-full tw-flex tw-flex-col tw-flex-1 tw-overflow-y-hidden",
ℹ️ I think this class was a leftover from previous implementations -- it would need to be in a flex parent, so I'm removing it since it's not doing anything.

2024-12-18 17:04 UTC, willmartian requested changes
Overall looks good! Few small things:

2024-12-18 17:04 UTC, willmartian commented on apps/browser/src/platform/popup/browser-popup-utils.ts
> +  }
❓ Is converting `tabId` as a boolean safe? Is `0` a valid `tabId`?

⛏️ 🎨  I think it is neater to handle early exit conditions first:

```ts
if(!tabId) { 
  return;
}

// ...
```

2024-12-18 17:04 UTC, willmartian commented on apps/browser/src/popup/scss/base.scss
>    }
Are these `!important` needed?

2024-12-18 22:09 UTC, vleague2 commented on apps/browser/src/popup/scss/base.scss
>    }
Good catch, no they are not!

2024-12-19 21:34 UTC, willmartian approved these changes
LGTM

2024-12-19 21:40 UTC, addisonbeck approved these changes

2024-12-27 20:42 UTC, merged