[PM-16102] Increase clickable area for bit-item actions
bitwarden/clients pull request #12450
Opened 2024-12-17 20:48 UTC by vleague2

## 🎟️ Tracking

[PM-16102](https://bitwarden.atlassian.net/browse/PM-16102)

## 📔 Objective

This PR increases the clickable area for each trailing `bit-item` action button so that the buttons are more accessible. To do so, we had to make a modification to the `bit-badge` (`:before` does not work when you have `overflow:hidden`, so we needed to move that property to an interior layer of badge), which necessitated changing it from a directive to a component. This should not affect any usages of the badge. 

## 📸 Screenshots

Before:

https://github.com/user-attachments/assets/a59e5f00-e3cf-46d2-97f7-5d896de51eb0

After:

https://github.com/user-attachments/assets/91f0868d-32c6-48a6-a261-8e39278c5ad5

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

[PM-16102]: https://bitwarden.atlassian.net/browse/PM-16102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-12-18 15:22 UTC, vleague2 commented on libs/components/src/item/item-action.component.ts
> +      "[&>button]:tw-relative [&>button:not([bit-item-content])]:before:tw-content-[''] [&>button]:before:tw-absolute [&>button]:before:tw-block [&>button]:before:tw-top-[-0.75rem] [&>button]:before:
ℹ️ The `not([bit-item-content])` is to prevent the `:before` area being added to the main item action, which also uses the `item-action` component.

2024-12-18 17:41 UTC, willmartian commented on libs/components/src/item/item-action.component.ts
> +      "[&>button]:tw-relative [&>button:not([bit-item-content])]:before:tw-content-[''] [&>button]:before:tw-absolute [&>button]:before:tw-block [&>button]:before:tw-top-[-0.75rem] [&>button]:before:
❓

In `bit-item-content`, we define the Y padding as `tw-py-2 bit-compact:tw-py-1.5`. The padding hooks into compact mode. My understanding is that the position properties here should be 1:1 with the padding, right? `p-1.5 === .375rem` and `p-2 === .5rem`

And if these values are meant to be coupled, would it be helpful to represent them as a shared CSS variable? `--bit-item-x-padding` etc? Then we could use the same variable in both places? Just wondering if we are worried about accidentally breaking this in the future if it is _meant_ to be lockstep, but not actually lockstep.

2024-12-18 17:49 UTC, vleague2 commented on libs/components/src/item/item-action.component.ts
> +      "[&>button]:tw-relative [&>button:not([bit-item-content])]:before:tw-content-[''] [&>button]:before:tw-absolute [&>button]:before:tw-block [&>button]:before:tw-top-[-0.75rem] [&>button]:before:
Hm yeah it probably should be. I think I was eyeballing whether or not it looked like the right height and never went back and updated it

2024-12-19 18:50 UTC, vleague2 commented on libs/components/src/item/item-action.component.ts
> +      "[&>button]:tw-relative [&>button:not([bit-item-content])]:before:tw-content-[''] [&>button]:before:tw-absolute [&>button]:before:tw-block [&>button]:before:tw-top-[-0.75rem] [&>button]:before:
For posterity, they don't match because the padding units have a different origin point than the positioning units, but they are updated to be more accurate and responsive to compact mode in this commit: [fc4c0eb](https://github.com/bitwarden/clients/pull/12450/commits/fc4c0eb9804f34ab73c2496ae30f28e809e9410a))

2024-12-19 22:06 UTC, danielleflinn approved these changes
✅ In storybook, verified bit-item actions click area now includes to top/bottom padding on the bit-item

2024-12-19 22:09 UTC, danielleflinn requested changes
Whoops–was a bit fast with that approval...it would be nice if we could make this focus ring not be cropped by the edge of the bit-item.  Is that possible? 
<img width="152" alt="Screenshot 2024-12-19 at 2 07 06 PM" src="https://github.com/user-attachments/assets/b04621d9-9964-438e-9ea8-cad0b2309655" />

2024-12-20 17:11 UTC, willmartian approved these changes
LGTM, ty

2024-12-20 17:51 UTC, danielleflinn approved these changes
Focus ring padding fixed! Thanks!

2024-12-20 18:27 UTC, vleague2 commented on libs/components/src/badge/badge.component.ts
> +export class BadgeComponent implements FocusableElement {
I'll do a quick check for any `bitBadge` instances doing that before I merge.

2024-12-20 19:03 UTC, merged