Auth/pm 1214/device management screen
bitwarden/clients pull request #12455
Opened 2024-12-17 22:27 UTC by alec-livefront

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-1214?atlOrigin=eyJpIjoiOGUyMGIwODJmODQwNDlkMjlhZmFhZDYxNmVjN2EyZGEiLCJwIjoiaiJ9

## 📔 Objective

Adds a device management tab under settings -> security. Allows a user to manage the devices of their account by approving them, logging them out or deleting them.

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-12-18 04:13 UTC, alec-livefront commented
I could use help on a few things I'm unsure of on this PR:

1. The ticket calls for virtual scroll on the table. However, when I try to implement `bit-table-scroll` I get `Unhandled error in angular TypeError: Cannot read properties of undefined (reading 'template')`. I looked at the `vnext-clients` component to see if I could spot what might be different here but came up empty.
2. I'm not sure how to implement the `removeDevice`, `approveDevice` or `logOutDevice` functions (or if it is currently possible with the backend). I tried to flush out `removeDevice` using the `devices/{id}/deactivate` endpoint but I don't believe it is working. I could use some direction on what to do here.
3. The Figma designs seem to show relative times for the last login (like "This week", "Last month". I'm wondering if there is existing logic to convert a date to a human readable time exists elsewhere in the app? I couldn't find anything. It shouldn't be hard to write but I wanted to be consistent. Another issue is I'm wondering how to get the last login date - it doesn't seem to be included in the device info from the backend.

2024-12-20 17:49 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/device-trust.service.implementation.ts
> +  }
⚠️ : I believe this new method better belongs on the `DevicesService` vs this service. This also allows you to undo the strict typing updates here so we don't have to re-test the device trust implementation for this change.

2024-12-20 19:47 UTC, JaredSnider-Bitwarden requested changes
This is looking great! I've got a few UI suggestions and some minor clean up items below:

2024-12-20 19:47 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/settings/security/device-management.component.html
💡 : upon watching the video, I think we should implement a loading state for the table which doesn't show the table until the data is loaded.

2024-12-20 19:47 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/settings/security/device-management.component.html
> +              {{ "remove" | i18n }}
❓ : the [figma](https://www.figma.com/design/girHiInJR1CRjLYvXQDIEl/Device-Management?node-id=136-65807&p=f&t=jTEpzNxkTRMPDW3k-0) calls for `Remove device` as the button text here. Did that change?

2024-12-20 19:47 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/settings/security/device-management.component.html
> +  </h2>
The [figma](https://www.figma.com/design/girHiInJR1CRjLYvXQDIEl/Device-Management?node-id=3411-81540&t=jTEpzNxkTRMPDW3k-0) calls for a loading icon here when async actions like remove device or log out are being taken

2024-12-20 19:47 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/settings/security/device-management.component.ts
> +    return metadata.platform ? `${category} - ${metadata.platform}` : category;
❓ : Nice job building out this metadata out. Do you think we should translate "Unknown" as a platform?

2024-12-20 19:47 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/settings/security/device-management.component.ts
> +      });
❓ : can we change this to be a call to `this.validationService.showError(error);` instead? As far as I know, that's the general recommendation for non-specific error handling.

2024-12-20 19:47 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/settings/security/security-routing.module.ts
> +      },
⚠️ : I believe this should be gated behind the feature flag guard for web app approvals, right?

2024-12-20 19:47 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/abstractions/devices/devices.service.abstraction.ts
🏅 Thank you for refactoring this to use abstract and actual methods instead of arrow functions.

2024-12-20 19:47 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/settings/security/device-management.component.ts
Excellent docs throughout. Thank you!

2024-12-20 19:47 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/device-trust.service.spec.ts
Same comment as here: https://github.com/bitwarden/clients/pull/12455/files#r1894224023

2024-12-20 19:47 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/devices-api.service.implementation.spec.ts
🏅 Thank you for adding this missing test suite!

2024-12-20 20:21 UTC, alec-livefront commented on apps/web/src/app/auth/settings/security/device-management.component.html
> +              {{ "remove" | i18n }}
d01ca4d5613c9c622608b195a9c57750fc611915

2024-12-20 23:33 UTC, alec-livefront commented on apps/web/src/app/auth/settings/security/device-management.component.html
I've added a loading state for when the table is loading, and added the spinner for when async actions are waiting to complete: 0932e1886c5fe84f04ad4d67662d5508b881dd2a

2024-12-20 23:33 UTC, alec-livefront commented on apps/web/src/app/auth/settings/security/device-management.component.html
> +  </h2>
0932e1886c5fe84f04ad4d67662d5508b881dd2a

2024-12-20 23:34 UTC, alec-livefront commented on apps/web/src/app/auth/settings/security/device-management.component.ts
> +    return metadata.platform ? `${category} - ${metadata.platform}` : category;
Can you elaborate on that? Are you talking about the `DeviceType.UnknownBrowser` having a `platform` of "Unknown"?

2024-12-20 23:41 UTC, alec-livefront commented on apps/web/src/app/auth/settings/security/device-management.component.ts
> +      });
39341019182c71afb5711ce1819f07d779569f48

2024-12-21 14:52 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/settings/security/device-management.component.ts
> +    return metadata.platform ? `${category} - ${metadata.platform}` : category;
Yes, I'm sorry that comment was not as clear as I meant for it to be. "Unknown" is the only non proper noun so we could translate it.

2024-12-23 17:35 UTC, alec-livefront commented on apps/web/src/app/auth/settings/security/device-management.component.ts
> +    return metadata.platform ? `${category} - ${metadata.platform}` : category;
Ah ok that makes sense! 4bb04596c27b1e588a321ffcc9e7a2ae55c3083c

2024-12-27 20:28 UTC, alec-livefront commented on apps/web/src/app/auth/settings/security/security-routing.module.ts
> +      },
[66e497c](https://github.com/bitwarden/clients/pull/12455/commits/66e497c230d799d8c1027cff28159389597cf234)

2024-12-27 22:35 UTC, rr-bw requested changes

2024-12-27 22:35 UTC, rr-bw commented on apps/web/src/app/auth/settings/security/device-management.component.html
> +<div class="tabbed-content">
Question: Why `tabbed-content`? Did you mean `tabbed-header`? And why not use Tailwind?

And a slight UI adjustment: The header for the Devices table isn't quite formatted according to Figma. There should be a bit more spacing between the heading and subheading/paragraph text. (It also doesn't look the same as the headers in the other tabs: Master Password, Two-step login).

**Figma**

<img width="488" alt="Screenshot 2024-12-27 at 2 26 06 PM" src="https://github.com/user-attachments/assets/38d48591-e9ae-4a0e-8dbd-fed4449b5714" />

**Current Implementation**

<img width="830" alt="Screenshot 2024-12-27 at 2 26 16 PM" src="https://github.com/user-attachments/assets/48200cad-a028-4a94-aa3a-b1b465f39208" />

2024-12-27 22:35 UTC, rr-bw commented on apps/web/src/app/auth/settings/security/device-management.component.html
> +    ></i>
Is there a corresponding link/popover text for this question mark icon?

2024-12-27 22:35 UTC, rr-bw commented on apps/web/src/app/auth/settings/security/device-management.component.html
> +        [bitSortable]="col.sortable ? col.name : null"
For me, the "Current Session" is the second item. It should be the first (according to Jira task).

<img width="912" alt="Screenshot 2024-12-27 at 2 32 06 PM" src="https://github.com/user-attachments/assets/e4dada6a-196e-4623-a306-ad80deea0823" />

2024-12-30 16:33 UTC, alec-livefront commented on apps/web/src/app/auth/settings/security/device-management.component.html
> +    ></i>
I have an open question re. that on the FIgma: https://www.figma.com/design/girHiInJR1CRjLYvXQDIEl?node-id=3411-81480#1076109108

2024-12-30 16:52 UTC, alec-livefront commented on apps/web/src/app/auth/settings/security/device-management.component.html
> +        [bitSortable]="col.sortable ? col.name : null"
[fa51b93](https://github.com/bitwarden/clients/pull/12455/commits/fa51b93a0f6208bd882d922afb4ac0d21a4d0706)

2024-12-30 16:52 UTC, alec-livefront commented on apps/web/src/app/auth/settings/security/device-management.component.html
> +<div class="tabbed-content">
[3bebfab](https://github.com/bitwarden/clients/pull/12455/commits/3bebfabc4056105c82cfb331f3a10641a3aaf859)

2024-12-30 20:19 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/settings/security/device-management.component.html
> +    ></i>
@alec-livefront , everything is looking solid here! Just waiting on this last item before approval!

2025-01-02 16:38 UTC, alec-livefront commented on apps/web/src/app/auth/settings/security/security-routing.module.ts
> +      },
@JaredSnider-Bitwarden Per this convo w/ Todd I think we're going to test this on the feature branch? https://bitwarden.atlassian.net/browse/PM-1214?focusedCommentId=80794 I've removed the feature flag here: [3ed12c6](https://github.com/bitwarden/clients/pull/12455/commits/3ed12c641c006c81f8566f7b70b5c94ef2cffcef)

2025-01-02 16:40 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/settings/security/security-routing.module.ts
> +      },
Ah, ok. I'm sorry for leading you in the wrong direction with this comment. I forgot that was decided.

2025-01-06 15:41 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/settings/security/device-management.component.html
> +    ></i>
Popover commit: [f017b27](https://github.com/bitwarden/clients/pull/12455/commits/f017b2796e9f7707c0b3b58718938749c4ac09e1)

2025-01-06 18:01 UTC, JaredSnider-Bitwarden approved these changes
Nice work!

2025-01-07 19:29 UTC, merged