[PM-14347][PM-14348] New Device Verification Logic
bitwarden/clients pull request #12451
Opened 2024-12-17 21:04 UTC by nick-livefront

## 🎟️ Tracking

[PM-14347](https://bitwarden.atlassian.net/browse/PM-14347)
[PM-14348](https://bitwarden.atlassian.net/browse/PM-14348)

## 📔 Objective
Stacked on top of @Jingo88's PR: #12360

Adds logic for new device verification pages, guards and state
- Adds check for scenarios when the new device verification is hidden
- Adds logic for temporary flag which will be shown every 7 days until the user enables 2 factor auth
- Adds logic for permanent flag which is blocking until the user enables two factor auth or selects they have reliable access. 
- Adds missing question mark to "access to email" copy

## 📸 Screenshots

|Temporary|Permanent|
|-|-|
|<video src="https://github.com/user-attachments/assets/b9f97abe-a5bc-4d79-b4e9-dd23bc1378f6" />|<video src="https://github.com/user-attachments/assets/5480049f-dd30-45f3-8da8-f6c09100f16f" />|

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-12-17 21:50 UTC, shane-melton requested changes
Looks really good! Just noticed one issue with regards to the active userId and caching the profile. 

Also, thanks for all the tests!! 🧪 🎉

2024-12-17 21:50 UTC, shane-melton commented on libs/angular/src/vault/services/vault-profile.service.ts
⚠️ We'll need to cache these values per `userId` as the active user could change between invocations. I know the `ApiService` does not support specifying a `userId` so we'll probably just need to cache the profile value passed on the `ProfileReponse.id` property. 

Then the `getProfileCreationDate` and `getProfileTwoFactorEnabled` methods should accept a `userId` parameter for looking up the cache and/or verifying it matches the `ProfileResponse.id` from the API.

2024-12-17 21:50 UTC, shane-melton commented on libs/angular/src/vault/services/vault-profile.service.ts
🎨 Can we add a TODO or comment that this should be a temporary service that should be replaced or moved to the `AccountService` after we can ensure a sync occurs during the login flow.

2024-12-18 19:15 UTC, nick-livefront commented on libs/angular/src/vault/services/vault-profile.service.ts
🤯 Great call and catch. That could be a poor experience waiting to happen.

[476c024](https://github.com/bitwarden/clients/pull/12451/commits/476c024b18297a6d36e2a76fba65d5e92e7283b8)

2024-12-18 19:15 UTC, nick-livefront commented on libs/angular/src/vault/services/vault-profile.service.ts
Added: [5f14221](https://github.com/bitwarden/clients/pull/12451/commits/5f142219dc404148cff8c8e5c2b6e3f2d9a584f6)

[PM-16202](https://bitwarden.atlassian.net/browse/PM-16202)

2024-12-18 19:41 UTC, shane-melton commented on libs/angular/src/vault/services/vault-profile.service.ts
Thanks!

2024-12-18 20:03 UTC, shane-melton submitted a review, later dismissed
Looks good! Nice work!

2024-12-19 15:26 UTC, nick-livefront commented
Rebased because #12360 was merged into `main`. I also tacked on a commit to short circuit the logic when both of the feature flags are not true: [a57b6b7](https://github.com/bitwarden/clients/pull/12451/commits/a57b6b79bad07123312267057d3e32c05b290a4b), that way it avoids any unneeded logic being executed.

2024-12-19 15:46 UTC, shane-melton approved these changes

2024-12-19 15:55 UTC, merged