[PM-15987] Improve email/master password entry back/forward navigation
bitwarden/clients pull request #12469
Opened 2024-12-18 22:17 UTC by alec-livefront

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-15987?atlOrigin=eyJpIjoiYjNhOWMzMjQ3ZmE3NDhkZjk5MjU0NzMzZGQ3YWU2MmUiLCJwIjoiaiJ9

## 📔 Objective

There were issues with the original solution for PM-15987 in Safari (clicking the back button from the master password entry screen did not reliably bring you back to the email entry screen). We were also disabling the browser's "forward" button after navigating back to the email entry screen from the master password entry screen.

This PR refactors the original work to provide a more consistent experience (tested in Safari, Firefox & Chrome). It also enables the browser's forward button after a user has navigated back to the email entry screen.

One notable change is the email validation now occurs on input rather than blur. I needed to make this change because if a user clicks the browser's forward button after immediately editing the email address `blur` isn't triggered (and the user could proceed to the MP entry with an invalid email). I also added a `continueClicked` function to differentiate a user clicking the continue button (requires us to push to the browser history) vs continuing via the browser's forward button.

## 📸 Screenshots

https://github.com/user-attachments/assets/9f46f038-a6af-4d5c-8a18-47414f63a7fc

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-12-19 14:27 UTC, Patrick-Pimentel-Bitwarden approved these changes
Appreciate the comments, looks good 👍

2024-12-19 14:52 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/login/login.component.html
Per our discussion, we need to improve the validity checking before allowing navigation login via SSO as it requires a valid email.  However, I'd incorrectly mentioned that we needed to check validity for login with passkey as that flow doesn't require email.

2024-12-19 15:00 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/login/login.component.html
Also, there is a `validateEmail` on the component that we can use before navigating to the SSO screen.

2024-12-19 21:36 UTC, JaredSnider-Bitwarden requested changes
Looking better!  Thank you for your work on this! A few more tweaks below:

2024-12-19 21:36 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/login/login.component.html
>          </button>
We can consolidate these buttons now, right?

2024-12-20 04:08 UTC, alec-livefront commented on libs/auth/src/angular/login/login.component.html
>          </button>
Good catch! bbe9a20caa7c69a551e3e7bd2d39044be341d6e8

2024-12-20 17:54 UTC, alec-livefront commented on libs/auth/src/angular/login/login-secondary-content.component.ts
The registration start component does - but the registration component didn't. I added it across the instances and removed intermediate passing of query variables.

2024-12-20 18:46 UTC, JaredSnider-Bitwarden requested changes
Nice work on the requested SSO changes + the type safety enhancements!

A few requests below, plus we can remove all changes to the old register components as those are being removed so we don't need to do any work to them.

2024-12-23 15:41 UTC, alec-livefront commented on libs/auth/src/angular/login/login-secondary-content.component.ts
9fea749eeb168f4a90278761fe3b922bba956e58

2024-12-23 16:50 UTC, alec-livefront commented on libs/auth/src/angular/login/login.component.ts
> +      await this.getKnownDevice(this.emailFormControl.value ?? "");
[f4b4532](https://github.com/bitwarden/clients/pull/12469/commits/f4b453256fdfa5fc0ff7594e07bc97eea4caedfd)

2024-12-23 16:51 UTC, alec-livefront commented on libs/auth/src/angular/login/login.component.ts
> +    this.loginEmailService.setRememberEmail(this.formGroup.value.rememberEmail ?? false);
[8a6a249](https://github.com/bitwarden/clients/pull/12469/commits/8a6a249ce34bab88d77f4f4ea2e0769dc9136c07)

2024-12-23 16:51 UTC, alec-livefront commented on libs/auth/src/angular/login/login.component.ts
> +      this.emailFormControl.value ?? "",
Like this? [8a6a249](https://github.com/bitwarden/clients/pull/12469/commits/8a6a249ce34bab88d77f4f4ea2e0769dc9136c07)

2024-12-27 08:13 UTC, rr-bw requested changes

2024-12-27 08:13 UTC, rr-bw commented on libs/auth/src/angular/login/login.component.ts
> +      email: new FormControl<string>("", [Validators.required, Validators.email]),
Question: out of curiosity, what's the reason for changing to an explicit `new FormControl`?

2024-12-27 08:13 UTC, rr-bw commented on libs/auth/src/angular/login/login.component.ts
> +      undefined, // captcha no longer used in new login / registration scenarios
Can this line (201) just be removed entirely? We do have a comment in `login-credentials.ts` which also indicates captcha is deprecated.

2024-12-27 08:13 UTC, rr-bw commented on libs/auth/src/angular/login/login.component.html
>          (keyup.enter)="continue()"
I think this will need to be `continueClicked()` as well. Maybe rename the function if you can think of something more fitting - "`continuePressed()`", for example, is a bit more generic and could cover the idea of both pressing enter to continue and clicking to continue.

2024-12-27 08:13 UTC, rr-bw commented on libs/auth/src/angular/login/login.component.ts
> +    if (!(await this.validateEmail())) {
Nit: For easier debugging, could set the result of the call to a variable, and pass that variable in.

```
const isEmailValid = await this.validateEmail();

if (!isEmailValid) {
  ...
}
```

2024-12-27 08:13 UTC, rr-bw commented on libs/auth/src/angular/login/login.component.ts
>      if (await this.validateEmail()) {
Nit: For easier debugging, could set the result of the call to a variable, and pass that variable in.

```
const isEmailValid = await this.validateEmail();

if (isEmailValid) {
  ...
}
```

2024-12-27 08:13 UTC, rr-bw commented on apps/browser/src/auth/popup/register.component.ts
According to Jared's comment, I think you can remove changes to this file and also `register-form.component.ts`

2024-12-30 17:22 UTC, alec-livefront commented on apps/browser/src/auth/popup/register.component.ts
[6f8648f](https://github.com/bitwarden/clients/pull/12469/commits/6f8648ff4a1b01ea903ddb42cce39f15fa9ec684)

2024-12-30 17:22 UTC, alec-livefront commented on libs/auth/src/angular/login/login.component.ts
>      if (await this.validateEmail()) {
[dd6b942](https://github.com/bitwarden/clients/pull/12469/commits/dd6b942817f79770304795e7c06aa28e1c5c6e9a)

2024-12-30 17:22 UTC, alec-livefront commented on libs/auth/src/angular/login/login.component.ts
> +    if (!(await this.validateEmail())) {
[249d613](https://github.com/bitwarden/clients/pull/12469/commits/249d613ac0a9325a5b8336800b27ef0ed80a0f70)

2024-12-30 17:23 UTC, alec-livefront commented on libs/auth/src/angular/login/login.component.html
>          (keyup.enter)="continue()"
[e724529](https://github.com/bitwarden/clients/pull/12469/commits/e7245291aa4598817321570fc403e7bc7b43abb7)

2024-12-30 17:23 UTC, alec-livefront commented on libs/auth/src/angular/login/login.component.ts
> +      undefined, // captcha no longer used in new login / registration scenarios
[5dbb7c1](https://github.com/bitwarden/clients/pull/12469/commits/5dbb7c1fc16d7573886ca95d31b6a61ae38126c7)

I wanted to preserve the comment but if it's already commented it can go!

2024-12-30 17:24 UTC, alec-livefront commented on libs/auth/src/angular/login/login.component.ts
> +      email: new FormControl<string>("", [Validators.required, Validators.email]),
I thought this was necessary to fix a strict typing error but I guess not: [834f5c9](https://github.com/bitwarden/clients/pull/12469/commits/834f5c97dfaaf680285857db1da4314cca792d1f)

2024-12-30 22:15 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/login/login.component.ts
> +      this.emailFormControl.value ?? "",
Yes, perfect!

2024-12-30 22:23 UTC, JaredSnider-Bitwarden requested changes
This is looking great! All my tests looked great. One tiny clean up item, and it's good to go.

2024-12-30 22:23 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/register-form/register-form.component.ts
This change can be removed?

2024-12-31 16:10 UTC, alec-livefront commented on apps/web/src/app/auth/register-form/register-form.component.ts
oops missed one! removed

2025-01-02 13:59 UTC, Patrick-Pimentel-Bitwarden commented on libs/auth/src/angular/login/login.component.ts
> +    const credentials = new PasswordLoginCredentials(email ?? "", masterPassword ?? "");
Should we be logging any kind of warning if we are passing in empty strings here?

2025-01-02 14:01 UTC, Patrick-Pimentel-Bitwarden reviewed
Looks good. One question.

2025-01-02 16:38 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/login/login.component.ts
> +    const credentials = new PasswordLoginCredentials(email ?? "", masterPassword ?? "");
Great catch. We should actually check that these values exist as part of the validation. We shouldn't ever try to login with known empty string credentials.

2025-01-02 16:59 UTC, alec-livefront commented on libs/auth/src/angular/login/login.component.ts
> +    const credentials = new PasswordLoginCredentials(email ?? "", masterPassword ?? "");
[420e3ec](https://github.com/bitwarden/clients/pull/12469/commits/420e3ece321c05223625f99608c09cc1c583afe1)

2025-01-02 23:21 UTC, JaredSnider-Bitwarden approved these changes

2025-01-06 19:01 UTC, rr-bw approved these changes

2025-01-06 19:01 UTC, merged