Move import to sdk and enable it in browser/web
bitwarden/clients pull request #12479
Opened 2024-12-19 15:01 UTC by quexten

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-12-27 14:21 UTC, audreyality requested changes
Requested changes marked with ⚠️.  
Review-blocking concerns that may not require changes marked with 🤔.
Everything else is commentary.

2024-12-27 14:21 UTC, audreyality commented on libs/angular/src/vault/components/add-edit.component.ts
> +            await this.importSshKeyFromClipboard(password);
⚠️ There's no guarantee that the user ever enters the correct password. Using recursion could exhaust the callstack, crashing the consuming code. Consider, instead, running this check in a loop and exiting if the number of failed attempts exceeds a threshold.

💭 This is the kind of code that rxjs is quite good at managing. The solution is likely non-trivial, however, as you'll need to materialize and dematerialize the stream to properly implement the retry logic. I gave it a try, but didn't feel comfortable providing the code for use in logic that isn't unit tested. 🫠

2024-12-27 14:21 UTC, audreyality commented on libs/vault/src/cipher-form/components/sshkey-section/sshkey-section.component.ts
> +  async importSshKeyFromClipboard(password: string = "") {
♻️ This function is replicated with minor alterations across several components. Consider extracting the decision making into one or more shared functions.

2025-01-06 12:25 UTC, quexten commented on libs/angular/src/vault/components/add-edit.component.ts
> +            await this.importSshKeyFromClipboard(password);
The desktop-only implementation had a similar bug where a user would be indefinitely prompted. I do think it's unlikely that a user would re-enter the password enough times to actually bear the risk of exhausting the callstack, but I agree it's more readable in a loop.

2025-01-06 12:26 UTC, quexten commented on libs/angular/src/vault/components/add-edit.component.ts
> +            });
Agreed, should be in a better state now.

2025-01-06 12:31 UTC, quexten commented on libs/angular/src/vault/components/add-edit.component.ts
> +    } catch (e) {
Agreed, and updated. Should be more readable now.

2025-01-06 13:25 UTC, quexten commented on libs/vault/src/cipher-form/components/sshkey-section/sshkey-section.component.ts
> +  async importSshKeyFromClipboard(password: string = "") {
To be honest, _after rewriting it_, it is so much shorter that moving this out to a service, just for the two consumers, seems like it would lead to less clarity of the code.

2025-01-06 15:19 UTC, audreyality commented on libs/common/src/models/export/ssh-key.export.ts
> +    const parsedKey = import_ssh_key(req.privateKey);
@djsmith85 - I think this is a place where we'll need your importer expertise.

2025-01-06 15:33 UTC, audreyality commented on libs/angular/src/vault/components/add-edit.component.ts
> +      break;
⛏️ Mixing 3 different control flow keywords here leads me to believe there's a better way to state this.

2025-01-06 15:33 UTC, audreyality commented on libs/angular/src/vault/components/add-edit.component.ts
> +          }
This doesn't need to be solved now--♻️ identifies tech debt. If you're interested in it, though, you might consider embedding an enum in the `Ok` block of the result.

```
enum SshImport {
  Imported(value),
  MissingPassword, // expected failure case
  InvalidPassword, // expected failure case
}

fn method(...) : Result<SshImport, Exception> {
  // ...
}
```

2025-01-06 15:43 UTC, quexten commented on libs/angular/src/vault/components/add-edit.component.ts
> +          }
Wasm-bindgen does not support enums with values at the moment (otherwise Result would also be trivial to represent), but only C-style enums: https://github.com/rustwasm/wasm-bindgen/issues/2407. So for passing to typescript, this would need to be converted to some struct, similar to what was done in the desktop-only implementation.

2025-01-09 14:08 UTC, djsmith85 commented on libs/common/src/models/export/ssh-key.export.ts
> +    const parsedKey = import_ssh_key(req.privateKey);
The current behaviour is that, if any error on any item occurs, the whole import is aborted. We might want to change that in the future, if we can provide a detailed import report, but for now it just aborts, to not cause partial imports without a notice to the user.

@quexten Please ensure during dev/testing that an invalid ssh key will throw and show which import-item is causing the issue. If you are also able to provide a detailed/informative error messages, users will appreciate it.

2025-01-09 14:39 UTC, audreyality commented on libs/angular/src/vault/components/add-edit.component.ts
> +          }
Or you could use [Tsify-next](https://github.com/siefkenj/tsify?tab=readme-ov-file#enum), which is already included as a dependency.

2025-01-15 13:09 UTC, quexten commented on libs/common/src/models/export/ssh-key.export.ts
> +    const parsedKey = import_ssh_key(req.privateKey);
Ok, the error message from the import is now directly exposed to the user. It could use clarification though, since it is unclear which item this is referring to, and the error message doesn't actually say that it is an *ssh key*. The latter part can be changed in the sdk, for the former part. Is that blocking for this PR?

2025-01-15 17:44 UTC, quexten commented on libs/angular/src/vault/components/add-edit.component.ts
> +      break;
Splitting the first attempt out seemed to help simplify this a bit. It's longer now but more readable.

2025-01-15 17:48 UTC, audreyality commented on libs/angular/src/vault/components/add-edit.component.ts
> +      break;
Yes! The new code is much more clear! Thank you! 😄

2025-01-15 17:48 UTC, audreyality submitted a review, later dismissed

2025-01-17 12:13 UTC, quexten commented on apps/browser/src/_locales/en/messages.json
> +  "sshKeyPasted": {
Fixed

2025-01-17 12:13 UTC, quexten commented on apps/web/src/locales/en/messages.json
> +  "sshKeyPasted": {
Fixed

2025-01-17 12:18 UTC, quexten commented on libs/vault/src/cipher-form/components/sshkey-section/sshkey-section.component.ts
> +    for (let attempt = 0; attempt <= ATTEMPTS; attempt++) {
Yeah, makes sense. Seems eslint forbids `while(true) though, and requires `for (;;) {` instead..

2025-01-17 12:38 UTC, quexten commented on libs/importer/src/importers/bitwarden/bitwarden-json-importer.ts
> +    }
Fixed.

2025-01-17 16:46 UTC, mzieniukbw commented on libs/vault/src/cipher-form/components/sshkey-section/sshkey-section.component.ts
> +    if (parsedKey == null) {
i don't think we can ever reach this. The conditions above either return or break the looping with valid (non null or undefined) `parsedKey`

2025-01-21 11:07 UTC, quexten commented on libs/vault/src/cipher-form/components/sshkey-section/sshkey-section.component.ts
> +    if (parsedKey == null) {
I agree, nice catch. Removed.

2025-01-21 13:22 UTC, mzieniukbw submitted a review, later dismissed

2025-01-21 19:27 UTC, addisonbeck approved these changes

2025-01-21 21:14 UTC, Patrick-Pimentel-Bitwarden commented
I suspect the auth team got added to this by a stale code ownership file as I'm not seeing which files falls under our domain nor is github showing that we are a code owner for this pr. Removing myself from the review, if you believe that is in error please add me back.

2025-01-21 21:21 UTC, mzieniukbw submitted a review, later dismissed

2025-01-22 16:40 UTC, addisonbeck approved these changes

2025-01-22 17:53 UTC, gbubemismith reviewed
I have left a few suggestions and one question on how the SDK client is used

2025-01-22 17:53 UTC, gbubemismith commented on libs/vault/src/cipher-form/components/sshkey-section/sshkey-section.component.ts
> +    return import_ssh_key(key, password);
❓ I noticed this code uses `await firstValueFrom(this.sdkService.client$);` without using the client value. Is there a reason we're not piping through the client like other SDK usages?

2025-01-22 17:53 UTC, gbubemismith commented on libs/vault/src/cipher-form/components/sshkey-section/sshkey-section.component.ts
> +    let parsedKey: SshKey = null;
⛏️ (non-blocking) small change for when we enable strict TS on this file
```suggestion
    let parsedKey: SshKey | null = null;
```

2025-01-22 17:53 UTC, gbubemismith commented on libs/angular/src/vault/components/add-edit.component.ts
> +
🎨 Looks like we are repeating complex logic in different components, is it possible to have this in a service so it can be reusable?

2025-01-22 17:57 UTC, gbubemismith commented on libs/vault/src/cipher-form/components/sshkey-section/sshkey-section.component.ts
> +    return import_ssh_key(key, password);
Oh thank you. I Just started working on the SDK 👍🏼

2025-01-22 18:22 UTC, quexten commented on libs/angular/src/vault/components/add-edit.component.ts
> +
Makes sense, will update this tomorrow.

2025-01-23 13:51 UTC, quexten commented on libs/angular/src/vault/components/add-edit.component.ts
> +
Moved to a service, and added tests covering the basic flows of the service.

2025-01-23 18:24 UTC, quexten commented on libs/vault/src/services/default-ssh-import-prompt.service.ts
> +export class DefaultSshImportPromptService {
Fixed!

2025-01-23 19:34 UTC, audreyality reviewed
👍🏻 The changes are looking good! I'm glad that the jest detection logic was removed from the importer. Just got one nit to pick.

2025-01-23 19:34 UTC, audreyality commented on libs/importer/src/importers/bitwarden/bitwarden-json-importer.ts
> +    await firstValueFrom(this.sdkService.client$);
⛏️ Seems like you went too far with this change. The comment should still be included, correct? If so, make sure you call out the tech debt with a FIXME.

```suggestion
    // initializes the SDK
    // FIXME: remove this once the SDK gets initialized automatically
    await firstValueFrom(this.sdkService.client$);
```

🤔 If this line is no longer needed for initialization, what does it do? Why isn't the value returned by `client$` used?

2025-01-24 11:02 UTC, quexten commented on libs/importer/src/importers/bitwarden/bitwarden-json-importer.ts
> +    await firstValueFrom(this.sdkService.client$);
> 🤔 If this line is no longer needed for initialization, what does it do? Why isn't the value returned by client$ used?

Yeah, I agree this comment makes sense. It is unfortunate that this needs to be done using such a confusing line of code at the moment.

2025-01-24 15:11 UTC, audreyality approved these changes

2025-01-24 17:47 UTC, gbubemismith submitted a review, later dismissed

2025-02-03 12:34 UTC, quexten commented
Brought up-to-date with main. Seems the macos build failures are unrelated and happening on all PRs.

2025-02-03 14:29 UTC, quexten commented
@Patrick-Pimentel-Bitwarden 

> I suspect the auth team got added to this by a stale code ownership file as I'm not seeing which files falls under our domain nor is github showing that we are a code owner for this pr. Removing myself from the review, if you believe that is in error please add me back.

Not sure what happened with the codeowners at this point, but after addressing feedback from other reviewers, auth is once again in the codeowers for this changes for `apps/web/src/app/auth/settings/emergency-access/view/emergency-add-edit-cipher.component.ts`, so I've added you back as reviewer.

2025-02-03 15:25 UTC, audreyality submitted a review, later dismissed

2025-02-03 15:50 UTC, mzieniukbw submitted a review, later dismissed

2025-02-03 15:50 UTC, mzieniukbw commented on libs/vault/src/services/default-ssh-import-prompt.service.ts
> +      } else {
🎨 could you add a test case coverage for this ?

2025-02-04 11:34 UTC, quexten commented on libs/vault/src/services/default-ssh-import-prompt.service.ts
> +      } else {
Is this not covered here? https://github.com/bitwarden/clients/blob/de0d9646d8e8d8e7d39e79954f494e1f74c111b5/libs/vault/src/services/ssh-import-prompt.service.spec.ts#L58-L70

2025-02-04 11:45 UTC, quexten commented on libs/vault/src/services/default-ssh-import-prompt.service.ts
> +          if (error.variant !== "WrongPassword") {
Added tests for the error cases

2025-02-04 16:19 UTC, audreyality approved these changes

2025-02-06 21:21 UTC, Patrick-Pimentel-Bitwarden approved these changes
👍  Auth changes look good as well as the rest of the pr.

2025-02-07 10:39 UTC, quexten commented
Resolved merge conflicts

2025-02-07 11:30 UTC, addisonbeck approved these changes

2025-02-07 16:16 UTC, audreyality submitted a review, later dismissed

2025-02-10 21:21 UTC, addisonbeck submitted a review, later dismissed

2025-02-10 21:25 UTC, gbubemismith approved these changes

2025-02-11 08:36 UTC, mzieniukbw submitted a review, later dismissed

2025-02-11 14:25 UTC, Patrick-Pimentel-Bitwarden submitted a review, later dismissed
👍 Great work!

2025-03-06 15:30 UTC, audreyality approved these changes

2025-03-06 15:36 UTC, gbubemismith approved these changes

2025-03-10 10:08 UTC, mzieniukbw approved these changes

2025-03-10 14:54 UTC, addisonbeck approved these changes

2025-03-10 16:51 UTC, coltonhurst approved these changes
Autofill removals look good!

2025-03-10 17:41 UTC, merged