Increase heap size for builds
bitwarden/clients pull request #12483
Opened 2024-12-19 17:19 UTC by quexten

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-12-19 17:22 UTC, justindbaur requested changes

2024-12-19 17:22 UTC, justindbaur commented on apps/cli/package.json
> +    "build:oss": "NODE_OPTIONS=\"--max-old-space-size=8192\" webpack",
I think we'll want to use `cross-env` for this like we do elsewhere. I don't think this would work as is on windows.

2024-12-19 19:53 UTC, quexten commented on apps/cli/package.json
> +    "build:oss": "NODE_OPTIONS=\"--max-old-space-size=8192\" webpack",
Added for desktop and cli

2024-12-19 21:08 UTC, justindbaur requested changes

2024-12-19 21:08 UTC, justindbaur commented on apps/web/package.json
> +    "build:bit": "NODE_OPTIONS=\"--max-old-space-size=8192\" webpack -c ../../bitwarden_license/bit-web/webpack.config.js",
I'm sorry, we want it for web as well. The CI might not _need_ it but we have developers who use windows. I should have been more clear that I meant it for all commands.

```suggestion
    "build:oss": "cross-env NODE_OPTIONS=\"--max-old-space-size=8192\" webpack",
    "build:bit": "cross-env NODE_OPTIONS=\"--max-old-space-size=8192\" webpack -c ../../bitwarden_license/bit-web/webpack.config.js",
```

2024-12-20 15:00 UTC, justindbaur approved these changes

2024-12-20 16:36 UTC, merged