[PM-12571][PM-13807] Add/Edit Folder Dialog
bitwarden/clients pull request #12487
Opened 2024-12-19 20:33 UTC by nick-livefront

## 🎟️ Tracking

[PM-12571](https://bitwarden.atlassian.net/browse/PM-12571)
[PM-13807](https://bitwarden.atlassian.net/browse/PM-13807)

## 📔 Objective

- Moves `AddEditFolderDialogComponent` to `@bitwarden/angular/vault/components` so it can be used by both the browser and web
  - Adds `AddEditFolderDialogResult` enum so the web vault can redirect when a folder is deleted. 
- Integrates the `AddEditFolderDialogComponent` to the web vault.
- Adds add/edit copy to the web messages file
- Fixes strict types on touched files
- Fixes missing hover border on delete icon button ([PM-13807](https://bitwarden.atlassian.net/browse/PM-13807))

## 📸 Screenshots

|Add/Edit/Delete folder on the web|
|-|
|<video src="https://github.com/user-attachments/assets/c904a0e9-a760-4b34-b28c-6302383dd74c" />|

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-12-19 20:44 UTC, shane-melton requested changes
Looks great! Just a few non-blocking suggestions/nits and one file move request.

2024-12-19 20:44 UTC, shane-melton commented on libs/angular/src/vault/components/add-edit-folder-dialog/add-edit-folder-dialog.component.ts
> +  Deleted = "deleted",
⛏️ (non-blocking): I think we might as well add a `Created` result here

2024-12-19 20:44 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +    const dialogRef = this.dialogService.open<AddEditFolderDialogResult, AddEditFolderDialogData>(
🎨 (non-blocking): Most of our dialog components have a `static open()` method that takes the dialog service and strongly typed parameters as arguments and it lets us avoid a lot of this generic boilerplate when trying to open the dialog. I think adding one here would be beneficial and make this dialogs behavior consistent with others.

2024-12-19 20:44 UTC, shane-melton commented on libs/angular/src/vault/components/add-edit-folder-dialog/add-edit-folder-dialog.component.html
🎨 Would you mind moving this to `/libs/vault/src/components` instead? Trying to consolidate our shared lib code into one spot and `/libs/vault` is where all (most?) of our recent browser refresh components live.

2024-12-20 16:05 UTC, nick-livefront commented on libs/angular/src/vault/components/add-edit-folder-dialog/add-edit-folder-dialog.component.ts
> +  Deleted = "deleted",
I originally didn't add it because it would go unused in all of the current scenarios. I tend to leave code out if it isn't used, but that isn't a soapbox I need to stand on here.

Added! [b20827e](https://github.com/bitwarden/clients/pull/12487/commits/b20827e52e3b0cdc966c49d83cabb4d54f0b0c96)

2024-12-20 16:05 UTC, nick-livefront commented on libs/angular/src/vault/components/add-edit-folder-dialog/add-edit-folder-dialog.component.html
Ah I was wondering what the difference was, I like the move! 

[54ae50e](https://github.com/bitwarden/clients/pull/12487/commits/54ae50e52f7e05aeadf0959871d669f8a7a7fadc)

2024-12-20 16:06 UTC, nick-livefront commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +    const dialogRef = this.dialogService.open<AddEditFolderDialogResult, AddEditFolderDialogData>(
I am all for consistency: [1b442f6](https://github.com/bitwarden/clients/pull/12487/commits/1b442f691c2aea986e371f17b71862f332f13346)

2025-01-09 00:06 UTC, shane-melton submitted a review, later dismissed
Looks good, nice work!

2025-01-09 00:08 UTC, shane-melton commented
I believe the failing tests should start working again after a merge with `main`. (we had some flaky date based tests that needed to be fixed for the new year)

2025-01-09 21:28 UTC, nick-livefront commented
Fixed conflicts from main, @shane-melton re-requesting review!

2025-01-09 21:29 UTC, shane-melton approved these changes

2025-01-10 19:03 UTC, nick-livefront commented
@shane-melton @gbubemismith Brad realized that the full folder name was not being populated in the web vault. This was caused by the folder name being broken down into parts to be shown in the nested format.

I added the `fullName` property to the `FolderFilter` type so the edit dialog can reference the full name rather than just the last part.

[706c388](https://github.com/bitwarden/clients/pull/12487/commits/706c3882ca6cf6585e8e2d0fcc86cc48ab3342b4), [b16fe41](https://github.com/bitwarden/clients/pull/12487/commits/b16fe41ffdc48677687815b097213002e4ccda84), [70bd316](https://github.com/bitwarden/clients/pull/12487/commits/70bd316ab8ddca18276a0d37f96643943e00ddac)

2025-01-14 19:19 UTC, gbubemismith approved these changes

2025-01-23 02:21 UTC, nick-livefront commented
@gbubemismith Kyra found a slight bug that when editing the folder, the full name was displayed in the filter menu. This was caused from editing the `folder` object directly which then altered the same object that the filter menu was looking at.

I used a shallow copy that is then passed to the edit dialog

|Before|After
|-|-|
|<video src="https://github.com/user-attachments/assets/6e376c50-c382-4e50-84f4-15e4f2069f9a" />|<video src="https://github.com/user-attachments/assets/f8bf2152-cf6d-4b4c-9472-304b7a90d5f0"/>|

2025-02-03 16:32 UTC, Jingo88 approved these changes

2025-02-04 21:13 UTC, merged