[PM-12606] Move Vault Timeout and Vault Timeout Settings to Key Management
bitwarden/clients pull request #12517
Opened 2024-12-20 20:47 UTC by jlf0dev

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-12606

## 📔 Objective

Move Vault Timeout and Vault Timeout Settings to Key Management. Tested web, extension, desktop, and CLI.
## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-12-20 21:13 UTC, vleague2 approved these changes
DS file looks good!

2024-12-20 21:23 UTC, quexten requested changes
(I did not comment on all instances) We have a few relative imports left over, unless I'm missing the reason for having them can we clean them up?

2024-12-20 21:23 UTC, quexten commented on libs/auth/src/angular/index.ts
> +export * from "../../../key-management/src/angular/vault-timeout-input/vault-timeout-input.component";
This should probably be removed. This is re-exporting key-management code in auth.

2024-12-20 21:23 UTC, quexten commented on libs/auth/src/common/services/login-strategies/login-strategy.service.ts
> +import { VaultTimeoutSettingsService } from "../../../../../key-management/src/vault-timeout/abstractions/vault-timeout-settings.service";
Should probably be something like:

```suggestion
import { VaultTimeoutSettingsService } from "@bitwarden/key-management"
```

2024-12-20 21:23 UTC, quexten commented on libs/common/src/auth/abstractions/token.service.ts
> +import { VaultTimeoutAction } from "../../../../key-management/src/vault-timeout/enums/vault-timeout-action.enum";
```suggestion
import { VaultTimeoutAction } from "@bitwarden/key-management"
```

2024-12-20 21:23 UTC, quexten commented on libs/common/src/auth/abstractions/token.service.ts
> +import { VaultTimeout } from "../../../../key-management/src/vault-timeout/types/vault-timeout.type";
```suggestion
import { VaultTimeout } from "@bitwarden/key-management"
```

2024-12-20 21:23 UTC, quexten commented on libs/common/src/auth/services/token.service.spec.ts
> +import {
`import { VaultTimeout, VaultTimeoutStringType } from "@bitwarden/key-management"`

2024-12-20 21:23 UTC, quexten commented on libs/common/src/auth/services/token.service.spec.ts
> +import { VaultTimeoutAction } from "../../../../key-management/src/vault-timeout/enums/vault-timeout-action.enum";
`import { VaultTimeoutAction } from "@bitwarden/key-management"`

2024-12-20 21:23 UTC, quexten commented on libs/common/src/auth/services/token.service.ts
> +import {
Import from `"@bitwarden/key-management"`

2024-12-20 21:23 UTC, quexten commented on libs/common/src/auth/services/user-verification/user-verification.service.spec.ts
> +import { VaultTimeoutSettingsService } from "../../../../../key-management/src/vault-timeout/abstractions/vault-timeout-settings.service";
Import from `"@bitwarden/key-management"`

2024-12-22 17:52 UTC, quexten approved these changes
Nice work, LGTM!

2024-12-22 17:54 UTC, quexten requested changes
Nice work on cleaning up the relative imports, looks like there is still some build errors, so revoking the mistaken approval.

2024-12-23 14:48 UTC, r-tome approved these changes

2024-12-23 21:34 UTC, jprusik submitted a review, later dismissed
approved for Autofill concerns

2024-12-24 01:05 UTC, quexten approved these changes

2025-01-15 14:27 UTC, jprusik approved these changes

2025-02-10 19:22 UTC, ike-kottlowski approved these changes

2025-02-13 23:03 UTC, closed without merging