Km/tmp ownership 2
bitwarden/clients pull request #12576
Opened 2024-12-25 09:09 UTC by quexten

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-12-26 13:48 UTC, JimmyVo16 approved these changes

2024-12-26 16:18 UTC, audreyality requested changes

2024-12-30 15:53 UTC, cturnbull-bitwarden approved these changes

2025-01-03 15:27 UTC, Patrick-Pimentel-Bitwarden commented on libs/admin-console/src/common/collections/models/collection.ts
> +import { EncString } from "../../../../../key-management/src/cryptography/domain/enc-string";
can we use `@bitwarden/key-management`? instead of the relative pathing?

2025-01-03 15:29 UTC, Patrick-Pimentel-Bitwarden commented on libs/auth/src/common/abstractions/pin.service.abstraction.ts
> +} from "../../../../key-management/src/cryptography/domain/enc-string";
Can we use `@bitwarden/key-management` instead of relative pathing?

2025-01-03 16:12 UTC, jprusik approved these changes
Approved for Autofill concerns

2025-01-03 18:46 UTC, Patrick-Pimentel-Bitwarden reviewed
`SymmetricCryptoKey`
`EncString`
`EncArrayBuffer`
`EncryptedString`
`EncryptionType`
seem to sometimes use relative imports. If you could please check them that would be appreciated.

2025-01-03 18:46 UTC, Patrick-Pimentel-Bitwarden commented on libs/key-management/spec/index.ts
> +  toEqualBuffer(expected: Uint8Array | ArrayBuffer): R;
Should this one have docs too?

2025-01-06 18:02 UTC, quexten commented on libs/key-management/spec/index.ts
> +  toEqualBuffer(expected: Uint8Array | ArrayBuffer): R;
Since this is moved from https://github.com/bitwarden/clients/blob/c349ea95c6a2608bee3296a60805a98e3d24348f/libs/common/spec/matchers/index.ts#L25 I had left this as-is for this PR, but I've updated it now to include docs for the function.

2025-01-06 18:03 UTC, quexten commented on libs/common/src/models/export/card.export.ts
> +import { EncString } from "../../../../key-management/src/cryptography/domain/enc-string";
I think I replaced all instances of this (at least if my IDE is to be believed).

2025-01-06 18:05 UTC, audreyality commented on libs/common/src/models/export/card.export.ts
> +import { EncString } from "../../../../key-management/src/cryptography/domain/enc-string";
👀 There's so many...

2025-01-06 18:07 UTC, audreyality approved these changes

2025-01-08 13:15 UTC, mzieniukbw commented on apps/desktop/src/key-management/preload.ts
> +import { KeySuffixOptions } from "../../../../libs/key-management/src/cryptography/enums/key-suffix-options.enum";
already fixed

2025-01-08 13:15 UTC, mzieniukbw commented on apps/desktop/src/key-management/preload.ts
> +// from starting up
this comment is no longer relevant

2025-01-08 13:16 UTC, mzieniukbw commented on libs/key-management/src/cryptography/abstractions/key.service.ts
> +import { OrganizationId, UserId } from "../../../../common/src/types/guid";
no longer relevant, already fixed

2025-01-08 13:16 UTC, mzieniukbw commented on libs/key-management/src/cryptography/abstractions/key.service.ts
> +} from "../../../../common/src/types/key";
no longer relevant, already fixed

2025-01-08 13:17 UTC, mzieniukbw commented on libs/key-management/src/cryptography/models/kdf-config.ts
> +import { RangeWithDefault } from "../../../../common/src/platform/misc/range-with-default";
no longer relevant, already fixed

2025-01-08 13:17 UTC, mzieniukbw commented on libs/key-management/src/cryptography/services/kdf-config.service.ts
> +} from "../../../../common/src/platform/state";
no longer relevant, already fixed

2025-01-08 13:18 UTC, mzieniukbw commented on libs/key-management/src/cryptography/services/key.service.spec.ts
> +import { FakeMasterPasswordService } from "../../../../common/src/auth/services/master-password/fake-master-password.service";
no longer relevant, already fixed

2025-01-08 13:18 UTC, mzieniukbw commented on libs/key-management/src/cryptography/services/key.service.spec.ts
> +import { PinServiceAbstraction } from "../../../../auth/src/common/abstractions";
no longer relevant, already fixed

2025-01-08 13:18 UTC, mzieniukbw commented on libs/key-management/src/cryptography/services/key.service.ts
> +import { PinServiceAbstraction } from "../../../../auth/src/common/abstractions";
no longer relevant, already fixed

2025-01-08 13:18 UTC, mzieniukbw commented on libs/key-management/src/cryptography/services/key.service.ts
> +import { OrganizationId, ProviderId, UserId } from "../../../../common/src/types/guid";
no longer relevant, already fixed

2025-01-08 13:39 UTC, quexten commented on apps/desktop/src/key-management/preload.ts
> +// from starting up
Removed in [8e4b843](https://github.com/bitwarden/clients/pull/12576/commits/8e4b843e934687f20f1c4ee3973bc30349ef4e29)

2025-01-08 13:39 UTC, quexten commented on libs/common/src/vault/abstractions/file-upload/cipher-file-upload.service.ts
> +import { SymmetricCryptoKey } from "@bitwarden/key-management";
Fixed in [8e4b843](https://github.com/bitwarden/clients/pull/12576/commits/8e4b843e934687f20f1c4ee3973bc30349ef4e29)

2025-01-08 13:39 UTC, quexten commented on libs/common/src/platform/services/file-upload/file-upload.service.ts
> +import { EncArrayBuffer } from "@bitwarden/key-management";
Fixed in [8e4b843](https://github.com/bitwarden/clients/pull/12576/commits/8e4b843e934687f20f1c4ee3973bc30349ef4e29)

2025-01-08 13:48 UTC, quexten commented on libs/common/src/vault/services/file-upload/cipher-file-upload.service.ts
> +import { SymmetricCryptoKey } from "@bitwarden/key-management";
Also removed in [8e4b843](https://github.com/bitwarden/clients/pull/12576/commits/8e4b843e934687f20f1c4ee3973bc30349ef4e29)

2025-01-08 13:48 UTC, quexten commented on libs/common/src/vault/models/domain/folder.spec.ts
> +    jest.mock("../../../../../key-management/src/cryptography/domain/enc-string");
Cleaned up in [99d9996](https://github.com/bitwarden/clients/pull/12576/commits/99d999625e7ba5e2ec10fcdfaa5c728d7656058c)

2025-01-08 13:48 UTC, quexten commented on libs/common/src/vault/models/view/attachment.view.spec.ts
> +jest.mock("../../../../../key-management/src/cryptography/domain/symmetric-crypto-key");
Cleaned up in [99d9996](https://github.com/bitwarden/clients/pull/12576/commits/99d999625e7ba5e2ec10fcdfaa5c728d7656058c)

2025-01-08 13:49 UTC, mzieniukbw submitted a review, later dismissed
LGTM!

2025-01-08 15:07 UTC, audreyality approved these changes

2025-01-08 15:51 UTC, JimmyVo16 approved these changes

2025-01-09 00:37 UTC, shane-melton approved these changes

2025-01-10 16:46 UTC, jprusik submitted a review, later dismissed
Approved for Autofill concerns

2025-01-14 17:52 UTC, Patrick-Pimentel-Bitwarden submitted a review, later dismissed
Great work, thank you 👍

2025-01-24 18:43 UTC, quexten commented
Note: At this point the PR had to be updated to move dependencies to `common/key-management/crypto` instead of the key-management package to avoid dependency cycles.

2025-01-24 20:02 UTC, JimmyVo16 approved these changes

2025-01-28 16:25 UTC, trmartin4 commented
@quexten due to the size of this PR, the Auth team has had issues with tooling to properly perform a review.  Could you please see if you could reasonably break this up into multiple PRs for review?  Perhaps a single service at a time?

2025-01-28 17:31 UTC, quexten commented
> @quexten due to the size of this PR, the Auth team has had issues with tooling to properly perform a review. Could you please see if you could reasonably break this up into multiple PRs for review? Perhaps a single service at a time?

I'll look into it. I believe in the first version of this PR it made sense to move all dependencies at once, since we were moving them to a separate package, leading to quite the mess of imports, but since it retargets the common library now, I think we can break it up.

2025-02-03 14:33 UTC, quexten commented
Replacing with this: https://github.com/bitwarden/clients/pull/13220

2025-02-03 14:33 UTC, closed without merging