[PM-15814]Alert owners of reseller-managed orgs to renewal events
bitwarden/clients pull request #12607
Opened 2024-12-27 21:22 UTC by cyprain-okeke

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-15814

## 📔 Objective

Organizations that are managed by a reseller have a higher probability of churning. This happens because of a breakdown in communication around renewal dates. 

the managed org does not have visibility into when their renewal date is, because their billing is managed by the reseller. Without knowing their renewal date, the managed org cannot issue a purchase order to their reseller.

the reseller does not respond to invoices from Bitwarden because they do not include a purchase order number matching one from a customer of theirs (the managed org). 

the first indication the managed org has that something has gone wrong is when the organization is suspended. This happens 30 days after the automatic invoice we send to the reseller is marked as unpaid, which is usually 45 days after it was issued (resellers get net-45 by default).

To help prevent this issue, we will show in-product messaging to owners of reseller-managed organizations, alerting them that their renewal date is upcoming, and to reach out to their reseller to insure uninterrupted service.

## 📸 Screenshots

<img width="1728" alt="Screenshot 2024-12-27 at 18 24 16" src="https://github.com/user-attachments/assets/84d02200-9e56-428e-b7d8-ff1cb596ccc2" />
<img width="1728" alt="Screenshot 2024-12-27 at 22 21 32" src="https://github.com/user-attachments/assets/a2ad0623-2fdb-43af-bbbc-9b59d0e1da8d" />

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-12-30 14:13 UTC, micahblut commented
@cyprain-okeke are the date formats localized? MM/DD/YYYY is not used in most places.

2024-12-30 15:49 UTC, cturnbull-bitwarden submitted a review, later dismissed

2024-12-31 15:45 UTC, Jingo88 requested changes
Looks good. just a small nit

2024-12-31 15:45 UTC, Jingo88 commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +    //this.resellerWarning1$.pipe(takeUntil(this.destroy$)).subscribe();
This looks like leftover commented out code, okay to remove?

2024-12-31 16:00 UTC, Jingo88 submitted a review, later dismissed

2024-12-31 16:02 UTC, gbubemismith requested changes
Just some small changes needed

2024-12-31 16:02 UTC, gbubemismith commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +    this.resellerWarning$ = combineLatest([organization$]).pipe(
I think we only need `combineLatest` when we have multiple independent streams. This can be simplified a bit

```suggestion
    this.resellerWarning$ = organization$.pipe(
    filter(org => org.isOwner),
    switchMap(org => this.billingApiService
      .getOrganizationBillingMetadata(org.id)
      .pipe(map(metadata => ({org, metadata})))
    ),
    map()
```

2024-12-31 16:49 UTC, gbubemismith submitted a review, later dismissed

2024-12-31 16:51 UTC, Jingo88 approved these changes

2024-12-31 16:53 UTC, cturnbull-bitwarden approved these changes

2024-12-31 16:55 UTC, gbubemismith approved these changes

2024-12-31 17:06 UTC, merged