[PM-15999] - use new generator components in desktop app
bitwarden/clients pull request #12639
Opened 2024-12-31 17:52 UTC by jaasen-livefront

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-15999

## 📔 Objective

This PR replaces the legacy credential generators with the new ones in the desktop app.

## 📸 Screenshots

https://github.com/user-attachments/assets/414f5f98-05d7-411b-8786-c8e38e66e8fe

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2025-01-02 14:33 UTC, audreyality requested changes
❌ This should not modify tools code. The host component should be within the vault code.

📝 The tools host component implements logic specific to the application-wide generator. We do not want the logic reused because these hosts have different user experience expectations. In particular, the application-wide generator includes top-level logic for selecting between a username or password. The vault has independent navigation for each of these.

2025-01-02 19:58 UTC, audreyality requested changes
You did not address my feedback.

2025-01-02 20:19 UTC, jaasen-livefront commented
@audreyality Thanks for your feedback. Should be gtg now. ;)

2025-01-02 20:27 UTC, audreyality approved these changes
👍🏻 Tools feedback addressed.

🤔 there's a deleted comment indicating that the revised logic should "use the cipher-form-generator component introduced with https://github.com/bitwarden/clients/pull/11350".

2025-01-02 20:52 UTC, jaasen-livefront commented
> 👍🏻 Tools feedback addressed.
> 
> 🤔 there's a deleted comment indicating that the revised logic should "use the cipher-form-generator component introduced with #11350".

Thanks for pointing that out. I've updated the component to instead use the `CipherFormGeneratorComponent` instead of calling the individual generators.

2025-01-02 20:56 UTC, audreyality reviewed
📝 I'm going to hold off on further reviews until this is signed off by @bitwarden/team-vault-dev

2025-01-03 15:37 UTC, gbubemismith reviewed
Looks good! Just added a suggestion and a question

2025-01-03 15:37 UTC, gbubemismith commented on apps/desktop/src/vault/app/vault/vault.component.ts
> +      this.dialogService.open(CredentialGeneratorComponent, {
🎨 (non-blocking): Our dialogue components usually have a static open method that takes the dialog service and params as an argument. I think we can do something similar to keep things consistent.

2025-01-03 15:37 UTC, gbubemismith commented on apps/desktop/src/vault/app/vault/vault.component.ts
> +    // TODO: Remove this when new generator feature is enabled
:question: is there a ticket tracking this?

2025-01-03 17:39 UTC, jordan-bite commented on apps/desktop/src/vault/app/vault/vault.component.ts
> +    // TODO: Remove this when new generator feature is enabled
@gbubemismith Totally agree, I don't like leaving TODOs without an accompanying ticket. I've found and referenced the ticket  number.

2025-01-03 17:39 UTC, jordan-bite commented on apps/desktop/src/vault/app/vault/vault.component.ts
> +      this.dialogService.open(CredentialGeneratorComponent, {
@gbubemismith Excellent point!I wasn't sure if it was better to leave the component as it to allow for reuse outside of a dialog context. I've updated it to follow the existing dialog component pattern.

2025-01-03 17:40 UTC, jaasen-livefront commented on apps/desktop/src/vault/app/vault/vault.component.ts
> +    // TODO: Remove this when new generator feature is enabled
@gbubemismith Totally agree, I don't like leaving TODOs without an accompanying ticket. I've found and referenced the ticket number.

2025-01-03 17:40 UTC, jaasen-livefront commented on apps/desktop/src/vault/app/vault/vault.component.ts
> +      this.dialogService.open(CredentialGeneratorComponent, {
@gbubemismith Totally agree, I don't like leaving TODOs without an accompanying ticket. I've found and referenced the ticket number.

2025-01-03 21:11 UTC, gbubemismith commented on apps/desktop/src/vault/app/vault/credential-generator-dialog.component.ts
> +export const openCredentialGeneratorDialog = (
we need this in the component 

```ts
static open(dialogService: DialogService, params: CredentialGeneratorParams) {}
```
and then you reference the static method in the vault component like so 

```ts
CredentialGeneratorDialogComponent.open()
```

2025-01-03 21:11 UTC, gbubemismith reviewed
Just one last change

2025-01-03 21:18 UTC, jaasen-livefront commented on apps/desktop/src/vault/app/vault/credential-generator-dialog.component.ts
> +export const openCredentialGeneratorDialog = (
@gbubemismith Gotcha! I was looking at a slightly different implementation. Should be gtg now.

2025-01-03 21:40 UTC, gbubemismith approved these changes

2025-01-06 15:05 UTC, audreyality approved these changes

2025-01-06 18:40 UTC, merged