[BEEEP] - Reorganize linting to improve feedback loop and reduce CI time.
bitwarden/clients pull request #2299
Opened 2022-01-28 19:12 UTC by mimartin12

## Type of change

- [ ] Bug fix
- [ ] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [X] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

This moves the linting up in the CI process so that we can close the feedback loop for linting errors. This reduces the time till an error is thrown by an average of 66%. 

## Code changes

- **.github/workflows/build.yml:** Restructured lint step, added dependencies to jobs to fail if lint fails, updated several popular actions to the newest version.

## Screenshots

## Testing requirements

Actions:
- Test a failure: https://github.com/bitwarden/browser/actions/runs/1763155944
- Succeeding run: https://github.com/bitwarden/browser/actions/runs/1763112622

## Before you submit

- [X] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2022-01-28 21:38 UTC, joseph-flinn requested changes

2022-01-28 21:38 UTC, joseph-flinn commented on .github/workflows/build.yml
> +
There's an extra newline here

2022-01-28 21:42 UTC, mimartin12 commented on .github/workflows/build.yml
> +
Micaiah uses _linter_, it was only slightly effective 🤣

2022-01-31 15:43 UTC, joseph-flinn approved these changes

2022-01-31 15:44 UTC, merged