[DEVOPS-810] Move Safari build to browser workflow
bitwarden/clients pull request #2683
Opened 2022-05-13 16:30 UTC by michalchecinski

## Type of change

- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [x] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

Move the Safari extension build task from the desktop build workflow to the browser build.

Use the build Safari extension artifact in the desktop build to prepare mac OS packages

## Code changes

## Screenshots

## Before you submit

- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2022-05-13 16:38 UTC, michalchecinski commented
Runs using changed workflow:
Browser: https://github.com/bitwarden/clients/actions/runs/2314180863
Desktop: https://github.com/bitwarden/clients/actions/runs/2320520008

2022-05-13 17:05 UTC, mimartin12 commented on .github/workflows/build-desktop.yml
> +          branch: DEVOPS-810_safari_build_browser # master
```suggestion
          branch: master
```

2022-05-13 17:26 UTC, joseph-flinn requested changes
We've decided to pin the commits for the actions we use for both reliability (if the upstream action breaks in a new release, we aren't affected) and to help avoid supply chain attacks.

2022-05-13 17:26 UTC, joseph-flinn commented on .github/workflows/build-desktop.yml
> +        uses: dawidd6/action-download-artifact@v2
```suggestion
        uses: dawidd6/action-download-artifact@b2abf1705491048a2d7074f7d90513044fd25d39  # v2.19.0
```

2022-05-13 17:26 UTC, joseph-flinn commented on .github/workflows/build-desktop.yml
> +        uses: dawidd6/action-download-artifact@v2
```suggestion
        uses: dawidd6/action-download-artifact@b2abf1705491048a2d7074f7d90513044fd25d39  # v2.19.0
```

2022-05-13 17:26 UTC, joseph-flinn commented on .github/workflows/build-desktop.yml
> +        uses: dawidd6/action-download-artifact@v2
```suggestion
        uses: dawidd6/action-download-artifact@b2abf1705491048a2d7074f7d90513044fd25d39  # v2.19.0
```

2022-05-13 17:26 UTC, joseph-flinn commented on .github/workflows/build-desktop.yml
> +        uses: dawidd6/action-download-artifact@v2
```suggestion
        uses: dawidd6/action-download-artifact@b2abf1705491048a2d7074f7d90513044fd25d39  # v2.19.0
```

2022-05-13 17:26 UTC, joseph-flinn commented on .github/workflows/build-desktop.yml
> +        uses: dawidd6/action-download-artifact@v2
```suggestion
        uses: dawidd6/action-download-artifact@b2abf1705491048a2d7074f7d90513044fd25d39  # v2.19.0
```

2022-05-13 17:26 UTC, joseph-flinn commented on .github/workflows/build-desktop.yml
> +        uses: dawidd6/action-download-artifact@v2
```suggestion
        uses: dawidd6/action-download-artifact@b2abf1705491048a2d7074f7d90513044fd25d39  # v2.19.0
```

2022-05-16 08:40 UTC, michalchecinski commented on .github/workflows/build-desktop.yml
> +        uses: dawidd6/action-download-artifact@v2
Done

2022-05-16 08:40 UTC, michalchecinski commented on .github/workflows/build-desktop.yml
> +        uses: dawidd6/action-download-artifact@v2
Done

2022-05-16 08:40 UTC, michalchecinski commented on .github/workflows/build-desktop.yml
> +        uses: dawidd6/action-download-artifact@v2
Done

2022-05-16 08:40 UTC, michalchecinski commented on .github/workflows/build-desktop.yml
> +        uses: dawidd6/action-download-artifact@v2
Done

2022-05-16 08:40 UTC, michalchecinski commented on .github/workflows/build-desktop.yml
> +        uses: dawidd6/action-download-artifact@v2
Done

2022-05-16 08:41 UTC, michalchecinski commented on .github/workflows/build-desktop.yml
> +        uses: dawidd6/action-download-artifact@v2
Done

2022-05-16 08:41 UTC, michalchecinski commented on .github/workflows/build-desktop.yml
> +          branch: DEVOPS-810_safari_build_browser # master
Done

2022-05-16 13:19 UTC, vgrassia requested changes

2022-05-16 13:19 UTC, vgrassia commented on .github/workflows/build-browser.yml
>        - name: Check if any job failed
In the step below you'll need to add an environment variable for the `build-safari` job status and add a check for failure in the `run` logic.

2022-05-16 13:19 UTC, vgrassia commented on .github/workflows/build-desktop.yml
> +          path: ${{ github.workspace }}/browser-build-artifacts
```suggestion
          path: ${{ github.workspace }}/browser-build-artifacts
```

2022-05-17 08:15 UTC, michalchecinski commented on .github/workflows/build-desktop.yml
> +          path: ${{ github.workspace }}/browser-build-artifacts
Done

2022-05-17 08:15 UTC, michalchecinski commented on .github/workflows/build-desktop.yml
> +          path: ${{ github.workspace }}/browser-build-artifacts
Done

2022-05-17 08:16 UTC, michalchecinski commented on .github/workflows/build-browser.yml
>        - name: Check if any job failed
Done :)

2022-05-17 12:00 UTC, vgrassia approved these changes

2022-05-18 14:31 UTC, merged