Clearing the search bar when switching accounts
bitwarden/clients pull request #2685
Opened 2022-05-13 18:40 UTC by CarleyDiaz-Bitwarden

## Type of change

- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

The search bar was not clearing in the header when users were switching between accounts.

## Code changes
apps/desktop/src/app/layout/search/search.component.ts
- Added broadcaster service and NgZone , search component now listens for the "clearSearchBarText" message, and then sets the search bar values to empty.

apps/desktop/src/app/layout/account-switcher.component.ts 
- sends a message now to search component to reset the search values to empty string.

## Before you submit

- [x] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2022-05-16 17:24 UTC, MGibson1 requested changes
What do you think about using observables instead? https://github.com/bitwarden/adr/pull/1

2022-05-16 17:24 UTC, MGibson1 commented on apps/desktop/src/app/layout/search/search.component.ts
> +          case "clearSearchBarText":
can't we just listen for switchAccount instead? I'd like to minimize messaging and certainly these one-of messages.

2022-05-16 21:37 UTC, CarleyDiaz-Bitwarden commented on apps/desktop/src/app/layout/search/search.component.ts
> +          case "clearSearchBarText":
Love that idea!

2022-05-18 16:05 UTC, CarleyDiaz-Bitwarden commented on apps/desktop/src/app/layout/search/search.component.ts
> +          case "clearSearchBarText":
I've updated it to use observables and listen to the activeAccount being changed :)

2022-05-23 17:52 UTC, Hinton approved these changes

2022-05-23 18:04 UTC, merged

2022-06-14 14:08 UTC, isleshocky77 commented
I haven't seen anyone else report it as a bug; however, while searching I found this PR that just went through. I'm guessing it's responsible for a bug that just popped up. When you enter a search keyword, and then open one of the items, it now clears the search term. This is extremely frustrating and didn't happen in the past.  

Imagine you search for "airline" and have multiple airline entries, and you click on the first to see a detail, click back, go to click on the second entry. It's no longer there as the search keyword has been cleared. This was not happening as of a couple of weeks ago.