Ps 575 pop out
bitwarden/clients pull request #2705
Opened 2022-05-19 19:01 UTC by CarleyDiaz-Bitwarden-zz

## Type of change

- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

When in the browser you can click on the expand button that opens the extension in a popup window an infinite amount of times, I added a check to see if it's already open, if so the expand button is hidden.

## Code changes

- pop-out.component.ts - added to the if statement so that being open in a popup window already sets the this.show variable to false, and hides the expand button.

## Before you submit

- [x] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2022-05-20 08:32 UTC, djsmith85 reviewed
I've attempted a fix, a long time ago, but got stuck on a CSS issue with the searchbar stuck to the left, please see https://github.com/bitwarden/clients/pull/1735

If you can fix that, that would be awesome. https://github.com/bitwarden/clients/pull/1693 might be related.

Closes #1690

2022-05-23 13:56 UTC, CarleyDiaz-Bitwarden commented
@djsmith85 Thank you for pointing those other related issues out, I was able to add some padding to the area and I am open to adjusting it again if necessary. 

<img width="443" alt="Screen Shot 2022-05-20 at 5 31 25 PM" src="https://user-images.githubusercontent.com/103955722/169835251-2def724b-7b4c-40ba-9b32-2f40b86c403f.png">
<img width="402" alt="Screen Shot 2022-05-20 at 5 31 19 PM" src="https://user-images.githubusercontent.com/103955722/169835255-d880ecd4-3bdc-4121-a782-52e89702fe6b.png">

2022-05-25 16:46 UTC, djsmith85 requested changes
Great work on this and thank you for picking this up.

This is looking good. Just one slight issue when displayed in the sidebar and being on the current tab page.

![image](https://user-images.githubusercontent.com/2670567/170316641-ef4f3dbd-779a-423e-a07c-9f3acad85e34.png)

Instead of manipulating `show` in the `current-tab.component.html`

`<app-pop-out [show]="!inSidebar"></app-pop-out>`

we could possibly not display it at all with an `ngIf` (slightly hacky)

`<app-pop-out *ngIf="!inSidebar"></app-pop-out>`

2022-05-30 18:57 UTC, djsmith85 approved these changes
Looking good !!

2022-06-01 15:40 UTC, merged