Feature/a11y hcaptcha cookie
bitwarden/clients pull request #2709
Opened 2022-05-20 14:39 UTC by jlf0dev

## Type of change

- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

hCaptcha allows users to load an accessibility cookie into their browser in order to bypass the captcha. This currently works for our web, browser, and mobile clients, but we haven't had a way to load cookies into desktop in the past.

This PR adds a component that allows users to paste in their accessibility cookie url from hCaptcha. This url is then opened in a new window and cookies are added to the process. When the user retries their hCaptcha, it is then able to see the accessibility cookie.

## Code changes

- **[jslib dependency](https://github.com/bitwarden/jslib/pull/811)**
- **apps/desktop/src/app/accounts/accessibility-cookie.component.\*:** Component for adding accessibility cookie. Opens a hCaptcha url provided by the user.
- **apps/desktop/src/app/accounts/login.component.html:** Add button for accessibility cookie
- **apps/desktop/src/app/accounts/register.component.html:** Add button for accessibility cookie
- **apps/desktop/src/app/accounts/two-factor.component.html:** Add button for accessibility cookie

## Screenshots

https://user-images.githubusercontent.com/24985544/169551441-985875df-f940-4a4f-a6b6-a30b0360ab80.mov

## Before you submit

- [x] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2022-05-26 06:30 UTC, eliykat requested changes
Nice solution, really good work on this @jlf0dev

2022-05-26 06:30 UTC, eliykat commented on apps/desktop/src/locales/en/messages.json
> +    "message": "Register as an accessibility user at"
You need to provide a complete example sentence in the description so that translators have the context. Otherwise it's an incomplete sentence and difficult to translate.

2022-05-26 06:30 UTC, eliykat commented on apps/desktop/src/app/accounts/accessibility-cookie.component.html
> +            [(ngModel)]="link"
Please use [reactive forms](https://angular.io/guide/reactive-forms) for all inputs

2022-05-26 06:30 UTC, eliykat commented on apps/desktop/src/app/accounts/accessibility-cookie.component.html
> +      <button type="button" routerLink="/login" class="btn block">{{ "done" | i18n }}</button>
"Done" seems like not our usual wording. Should it be "Close"?

2022-05-26 06:30 UTC, eliykat commented on apps/desktop/src/app/accounts/accessibility-cookie.component.ts
> +              this.listenForCookie = false;
If I have the cookie window open, and toggle back to the Bitwarden app before I'm done, it'll stop listening for the cookie, right? Maybe `onCookieSavedFailure` needs to reset the flag?

2022-05-26 06:30 UTC, eliykat commented on apps/desktop/src/app/accounts/accessibility-cookie.component.ts
> +              this.listenForCookie = false;
Thinking about this further, can we just listen for a window closed event? i.e. they save & exit the hcatpcha window, then we check for the cookie? Seems more intuitive to me than listening for focus.

2022-06-06 20:47 UTC, jlf0dev commented on apps/desktop/src/locales/en/messages.json
> +  "hCaptchaUrl": {
Added

2022-06-06 20:48 UTC, jlf0dev commented on apps/desktop/src/app/accounts/accessibility-cookie.component.html
> +            [(ngModel)]="link"
Updated to use reactive forms

2022-06-06 20:51 UTC, jlf0dev commented on apps/desktop/src/app/accounts/accessibility-cookie.component.html
> +      <button type="button" routerLink="/login" class="btn block">{{ "done" | i18n }}</button>
@danielleflinn had a previous suggestion to use "Done" since it corresponds with the forms intended user action better. It does deviate from what we normally use, but I also think it might a better UX choice in this situation. Let me know what you think.

2022-06-06 20:58 UTC, jlf0dev commented on apps/desktop/src/app/accounts/accessibility-cookie.component.ts
> +              this.listenForCookie = false;
Whenever we return focus back to the Bitwarden app, I close the secondary window and check for the cookie. This resets the entire process and we don't need `onCookieSavedFailure` to reset the flag. I think this is more appropriate than just listening for the window closed event for a couple reasons:
1. We can't get into a situation where they return to our app in the middle of the process and start opening multiple windows.
2. If we listen on window close and they never close the second window, we wouldn't check for the cookie when they return. 

Ideally I'd be listening for an event that fires when we have cookies added, but the cookie API provided by electron isn't quite good enough to work in this situation.

2022-06-06 20:58 UTC, jlf0dev commented on apps/desktop/src/locales/en/messages.json
> +    "message": "Register as an accessibility user at"
Done

2022-06-06 23:12 UTC, danielleflinn commented on apps/desktop/src/app/accounts/accessibility-cookie.component.html
> +      <button type="button" routerLink="/login" class="btn block">{{ "done" | i18n }}</button>
I thought about "close" but "close" seems to imply something like a modal is closing. Where this button just takes the user back.  Perhaps "Back" would be a better word to use here. What do you think @eliykat?

2022-06-07 13:01 UTC, MGibson1 commented on apps/desktop/src/app/accounts/login.component.html
> +            <button class="btn block" type="button" routerLink="/accessibility-cookie">
Is it possible to detect if an hcaptcha accessibility cookie is already set?

2022-06-07 13:02 UTC, MGibson1 commented on apps/desktop/src/app/accounts/login.component.html
> +            <button class="btn block" type="button" routerLink="/accessibility-cookie">
If we can, it's worth thinking about making captcha a component

2022-06-07 15:36 UTC, MGibson1 commented on apps/desktop/src/app/accounts/login.component.html
> +            <button class="btn block" type="button" routerLink="/accessibility-cookie">
ah I see, thanks

2022-06-09 04:54 UTC, eliykat commented on apps/desktop/src/app/accounts/accessibility-cookie.component.ts
> +              this.listenForCookie = false;
Those are all good reasons, I can see you've thought this through. I missed that we force the window to close in `checkForCookie()`, so I agree this should all work.

2022-06-09 04:59 UTC, eliykat commented on apps/desktop/src/app/accounts/accessibility-cookie.component.html
> +      <button type="button" routerLink="/login" class="btn block">{{ "done" | i18n }}</button>
That's a good point. "Back" might imply that changes aren't saved, so I agree with "Done". Thanks for clarifying!

2022-06-09 04:59 UTC, eliykat approved these changes

2022-06-09 12:14 UTC, merged