Add CLI dependencies to root package.json
bitwarden/clients pull request #2816
Opened 2022-06-02 21:06 UTC by Hinton

## Type of change

- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other

## Objective

Moves the CLI dependencies to the root package.json

## Before you submit

- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2022-06-02 22:08 UTC, Hinton commented on .github/workflows/build-cli.yml
> +        working-directory: ./
yes. All the dependencies are in the root package.json

2022-06-02 23:03 UTC, MGibson1 requested changes

2022-06-02 23:03 UTC, MGibson1 commented on .github/workflows/build-cli.yml
> +        working-directory: ./
I would guess this is what's causing the yaml lint failures, I think this needs to be wrapped in quotes
```suggestion
        working-directory: './'
```

2022-06-03 06:33 UTC, Hinton commented on .github/workflows/build-cli.yml
> +        working-directory: ./
The builds have been broken for awhile, and I don't think it,s just this file.

2022-06-03 13:41 UTC, joseph-flinn commented on .github/workflows/build-cli.yml
> +        working-directory: ./
The yaml linter is failing because of a "too many requests" from GitHub when we check the latest versions of the pinned actions. It is currently being worked on for a fix

2022-06-03 15:49 UTC, joseph-flinn approved these changes

2022-06-03 15:59 UTC, MGibson1 approved these changes

2022-06-03 18:11 UTC, merged