[PS-250] Prevent timeouts less than 1 minute
bitwarden/clients pull request #2836
Opened 2022-06-06 08:55 UTC by gbubemismith

## Type of change

- [X] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective
Web Vault should not allow the user to select a value less than 1 minute in the custom timeout inputs.

## Code changes
 - **src/app/settings/preferences.component.ts:** a check to know if minutes entered is valid happens in the `submit` method.
 - **src/app/settings/vault-timeout-input.component.html:** minimum timeout error message display 
 - **src/locales/en/messages.json:** error text message
 - **src/app/modules/vault/modules/individual-vault/individual-vault.component.ts:** removed unused reference

PR is related to https://github.com/bitwarden/jslib/pull/802

https://user-images.githubusercontent.com/13024008/170232966-482a757e-791f-48c2-9469-ff8c2032ce21.mov

## Before you submit

- [X] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2022-06-07 06:55 UTC, eliykat requested changes

2022-06-07 06:55 UTC, eliykat commented on apps/web/src/locales/en/messages.json
> -  "pageTitle": {
Something weird is going on with this file, the diff is `-1,5073 +1,5079`. Maybe caused by moving from web? I recommend you revert this file and reapply your changes manually.

2022-06-07 15:10 UTC, gbubemismith commented on apps/web/src/locales/en/messages.json
> -  "pageTitle": {
for some reason vscode keeps formatting it

2022-06-08 04:11 UTC, eliykat approved these changes

2022-06-08 04:41 UTC, merged