Multi root workspace tweaks
bitwarden/clients pull request #2858
Opened 2022-06-07 23:11 UTC by MGibson1

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other
```

## Objective

A few tweaks I find useful to #2846. These changes set up Jest as a recommended extension and change some settings so it will work out of the box. As we add tests to each folder, we should remove them from the disabled workspace settings. This PR also assumes we'll continue our pattern of creating `npm run test` scripts to point to jest.

2022-06-08 09:25 UTC, Hinton requested changes
Can we please use either tabs or spaces, not both 🙃?

2022-06-08 13:38 UTC, MGibson1 commented
> Can we please use either tabs or spaces, not both 🙃?

This change makes them spaces, which conforms to everywhere else in the repo. Unless you didn't mean the `clients.code-workspace` file?

2022-06-14 01:27 UTC, eliykat requested changes
Glad you found this useful!

2022-06-14 01:27 UTC, eliykat commented on bitwarden_license/bit-web/tsconfig.json
> +  "extends": "../../apps/web/tsconfig"
This tsconfig file has different paths for `compilerOptions.paths["src"]`, `files` and `includes`. It doesn't seem like these will resolve correctly if we just extend the web tsconfig.

2022-06-14 01:27 UTC, eliykat commented on apps/browser/.vscode/settings.json
> +{
Can these settings be moved to the `settings` object in `clients.code-workspace` instead of repeated in each workspace?

2022-06-14 01:27 UTC, eliykat commented on clients.code-workspace
> +    "desktop"
What about the other clients (browser and cli) - don't we only have jest tests in jslib at the moment?

2022-06-14 01:32 UTC, MGibson1 commented on apps/browser/.vscode/settings.json
> +{
No, `${workspaceFolder}` refers to the workspace root (i.e. `apps/web`, `libs` etc) since they have different depths, you can't apply the same value to all of them.

I actually suspect the webpack map fix is broken due to this, too, but I haven't taken to time to prove it, so I didn't change it here

2022-06-14 01:32 UTC, MGibson1 commented on clients.code-workspace
> +    "desktop"
No, we have tests for both browser and CLI. They're anemic, but the projects exist

2022-06-14 01:36 UTC, MGibson1 commented on bitwarden_license/bit-web/tsconfig.json
> +  "extends": "../../apps/web/tsconfig"
they're only compiled in the context of `apps/web` so the paths actually don't matter. That's why it's working now even though the `jslib` directory doesn't exist. This extension actually corrects the paths because they are evaluated relative to the extended `tsconfig`.

You can test this out for yourself. Go to any component in the `bitwarden_license` directory with some jslib dependency. You'll see the transpiler complaining about not finding the file. Then try it again in this branch. It should be fixed (it is for me, that's why I did it 😄 )

2022-06-14 01:51 UTC, eliykat commented on bitwarden_license/bit-web/tsconfig.json
> +  "extends": "../../apps/web/tsconfig"
good call!

2022-06-14 01:58 UTC, eliykat commented on apps/browser/.vscode/settings.json
> +{
I don't quite understand how vscode resolves these variables, but let's just roll with it, we can always change it later. This is the safer option in any case.

2022-06-14 01:59 UTC, eliykat approved these changes

2022-06-14 02:39 UTC, merged