[PS-589] Added Device Verification section setting for 2FA Email for new device
bitwarden/clients pull request #2868
Opened 2022-06-08 19:57 UTC by fedemkr

## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Add new section "Device Verification" inside Security -> Two Factor step to handle enable/disable of the feature
Added API calls for device verification settings. Depends on [Server](https://github.com/bitwarden/server/pull/2016)
MIgrated from Jslib: https://github.com/bitwarden/jslib/pull/818
Migrated from Web: https://github.com/bitwarden/web/pull/1708

## Code changes

- **api.service.ts:** Added API calls for device verification settings
- **two-factor-setup-component.html:** Added Device verification section with checkbox and explanation
- **two-factor-setup-component.ts:** Added logic for Device verification section. Also added confirmation dialog when enabling it to tell the user which email will be used to deliver the verification codes.

## Screenshots

<img width="938" alt="image" src="https://user-images.githubusercontent.com/15682323/170361220-9857ddb2-69b9-4198-ab2d-9b8760989a00.png">

## Before you submit

```
- [x] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [x] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-06-08 22:06 UTC, shane-melton commented on apps/web/src/app/settings/two-factor-setup.component.html
> +        <i class="bwi bwi-spinner bwi-spin" title="{{ 'loading' | i18n }}" aria-hidden="true"></i>
It looks like the spinner here is always going to be rendered, regardless of the form's status

2022-06-08 22:08 UTC, shane-melton commented on apps/web/src/app/settings/two-factor-setup.component.html
> +        class="btn btn-primary btn-submit"
I believe we can use the `bitButton` directive here

2022-06-13 18:00 UTC, jlf0dev requested changes

2022-06-13 18:08 UTC, fedemkr commented on apps/web/src/locales/en/messages.json
> +  "areYouSureYouWantToEnableDeviceVerificationTheVerificationCodeEmailsWillArriveAtX": {
@jlf0dev  IMO, when keys are the same as the value it's better to see exactly what the user is going to see without needing to go to `messages.json` to check for the value. If I just put `areYouSureEnableDeviceVerification` then someone reading the code may not see that it also has the information of where the verification code will arrive, and also why it takes a parameter for string interpolation.
I agree that having very long keys on some messages, like long descriptions should be avoided, but I didn't think this was the case.
Nonetheless, if it's still too long for you I can shorten it

2022-06-13 18:13 UTC, jlf0dev commented on apps/web/src/locales/en/messages.json
> +  "areYouSureYouWantToEnableDeviceVerificationTheVerificationCodeEmailsWillArriveAtX": {
That's fair, I'm a fan of readability

2022-06-13 18:13 UTC, jlf0dev approved these changes

2022-06-13 18:13 UTC, merged