Use NPM workspace
bitwarden/clients pull request #2874
Opened 2022-06-09 10:11 UTC by Hinton

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

This PR attemps to move our mono repo towards the more accepted standard way using *NPM Workspaces* for the different apps and libs. This allows us to use the different libraries using the npm package names. The libs package names has also been updated to be in the `@bitwarden` namespace.

Unfortunately since we don't compile TS individually for the differet libs we still need the tsconfig paths.

## Code changes

- **package.json:** Add npm workspaces.
- **tsconfig.json:** Update naming of dependencies.

## Before you submit

```
- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-06-09 10:59 UTC, coroiu commented on apps/browser/tsconfig.json
> +      "@bitwarden/angular/*": ["../../libs/angular/src/*"]
suggestion: add a root `tsconfig.json` with the common package and then extend it in these client configs to reduce duplicate config

2022-06-13 11:01 UTC, Hinton commented on apps/browser/tsconfig.json
> +      "@bitwarden/angular/*": ["../../libs/angular/src/*"]
I did that for the jslib libs. Unfortunately we can't do it for apps, since the paths are not merged.

2022-06-14 14:33 UTC, MGibson1 requested changes
Not so sure about the icomoon deletions, but if it works then I'm happy with it. Did you double check that our icons are loaded properly still?

2022-06-14 14:33 UTC, MGibson1 commented on apps/browser/tsconfig.json
> +      "@bitwarden/angular/*": ["../../libs/angular/src/*"]
Sorry to resurrect this, but I don't understand why we don't want to just make all the libs available to all the apps. It shouldn't include any extra code in builds if it's not referenced.

2022-06-14 14:54 UTC, Hinton commented on apps/cli/webpack.config.js
> +      allowlist: [/@bitwarden/],
Webpack believes `@bitwarden` is a dependency since it's found in the `node_modules` dir.

2022-06-14 14:55 UTC, Hinton commented on apps/web/.eslintrc.json
> -  "root": true,
Broke pre-commit for me.

2022-06-14 14:55 UTC, Hinton commented on apps/web/tsconfig.json
> +      "@bitwarden/components": ["../../libs/components/src"]
They are different. We only want the index.ts on components. For the other we actually need all the files (or until we have the barrel files)

2022-06-14 15:10 UTC, MGibson1 approved these changes

2022-06-14 15:10 UTC, merged