SM-48 - Disable/enable in user management
bitwarden/clients pull request #2893
Opened 2022-06-10 20:30 UTC by cscharf

## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

This adds the front-end user management functionality for Disabling and Enabling users within an organization. This is a pre-requisite to other work ongoing as well as a feature-add for user management where deleting/removing a user may not be desired and the action is 100% reversible. Edits can even be made to the user once disabled before re-enabling them.

## Code changes
Server PR: https://github.com/bitwarden/server/pull/2050
@fschillingeriv , when this does go live, it will impact user management UI/UX.

- **base.people.component.ts:** Changed the source of the `All` filter to show only _active_ (not disabled). Also added the necessary functions for performing disable/enable operations.
- **loose-components.module.ts:** I have no idea why this is necessary, but I'm assuming it is. I am not an angularologist.
- **bulk-disable.component.html|ts:** copy of the bulk remove component specifically for disabling users
- **bulk-enable.component.html|ts:** copy of the bulk remove component specifically for enabling users
- **people.component.html|ts:** Added new filter UI for disabled users and new gear menu options and disabled badge in user list
- **user-add-edit.component.html|ts:** Added new disabled badge indicator in title for modal, as well as new enable/disable buttons in the footer next to the remove button
- **en/messages.json:** New messages for disable/enable which couldn't be reused from orgs
- **api.service.ts:** New API endpoints for enable/disable and including bulk actions
- **organizationUserStatusType.ts:** New `Disabled = -1` org user status
- **providerUserStatusType.ts:** This one sucks and I'm not super happy about it, but there's a bit of shared code between Org users and Provider users, and this is great, but Provider users won't have a `Disabled` status (yet perhaps) so for now this a dummy placeholder to support compile-time TypeScript checks while maintaining shared code/logic between the 2. The server-side does not have a corresponding mapping of this enum value.

## Screenshots

### New Filter for Disabled Users
Note that outside of the `Disabled` filter view, these users are not displayed in the other filter views, including `All` in order to keep those uncluttered.
![image](https://user-images.githubusercontent.com/3904944/173143461-401e2bf9-bbb0-4b03-ad33-94004069c7c6.png)

### Inline Enable
In the gear icon next to a user in the list, there's a new option to `Enable` if the user is already `Disabled`.
![image](https://user-images.githubusercontent.com/3904944/173143817-1b3169cd-db59-4c57-a804-5bdfeba1c4ff.png)

### Inline Disable
In the gear icon next to a user in the list, when the user is active, there's a new option to `Disable` them.
![image](https://user-images.githubusercontent.com/3904944/173144027-f956212e-a79a-4432-979a-1874afff6ebc.png)

### Bulk Enable/Disable
There are also 2 new bulk actions for selected users in the active view to either `Enable` or `Disable` the user. This allows bulk operations against this new state.
![image](https://user-images.githubusercontent.com/3904944/173144302-0970b090-c8c9-47f4-a6b7-42a7fe2611c6.png)

### Edit Disabled User
Here we've opened a disabled user and the dialog shows the `Disabled` badge to draw attention, and in the lower right-hand corner there's a new button before the delete button for `Enable`.
![image](https://user-images.githubusercontent.com/3904944/173143051-a0041af1-d9e5-464f-bb32-1fc76784cfa0.png)

### Edit Active User
Here we've opened an active user (not disabled) and the dialog shows in the lower right-hand corner there's a new button before the delete button for `Disable`.
![image](https://user-images.githubusercontent.com/3904944/173143187-17334a1e-3920-4483-ab07-90fc20f6e0a5.png)

### Disable Active User
When disabling a user, a confirmation prompt is displayed.
![image](https://user-images.githubusercontent.com/3904944/173143267-b0834d6d-8ad9-4309-8e98-05ce20179daa.png)

## Before you submit

```
- [X] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [X] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-06-17 06:06 UTC, eliykat requested changes
A (non-critical) comment that didn't fit anywhere below: I could bulk-deactivate an already deactivated user, I think we're missing a check server side: https://github.com/bitwarden/server/blob/master/src/Core/Services/Implementations/OrganizationService.cs#L2218 (we check for an already-deactivated user individually but not in bulk)

2022-06-17 06:06 UTC, eliykat commented on apps/web/src/app/organizations/manage/user-add-edit.component.html
> +          </button>
The `appApiAction` stuff needs some changes:
* `[appApiAction]` is attached to the `<form>` element, not the button (and it's already there, so just delete it here)
* instead of referring to `activateBtn.loading`, refer to `form.loading`
* then you don't need the `#activateBtn` declaration

If you attach it to individual buttons, you get an Angular change detection error in the console (maybe because it's circular? idk, I just avoid it)

Same for the next button.

2022-06-17 14:35 UTC, cscharf commented
> A (non-critical) comment that didn't fit anywhere below: I could bulk-deactivate an already deactivated user, I think we're missing a check server side: https://github.com/bitwarden/server/blob/master/src/Core/Services/Implementations/OrganizationService.cs#L2218 (we check for an already-deactivated user individually but not in bulk)

Thanks @eliykat , I've resolved it with https://github.com/bitwarden/server/pull/2064

2022-06-17 14:38 UTC, cscharf commented on apps/web/src/app/common/base.people.component.ts
> +      this.removeUser(user);
Good call, thanks

2022-06-17 14:58 UTC, cscharf commented on apps/web/src/app/organizations/manage/user-add-edit.component.html
> +          </button>
Awesome, thanks Thomas, I've made those corrections/changes.

2022-06-17 15:07 UTC, cscharf commented on apps/web/src/app/organizations/manage/people.component.ts
> +    );
Gotcha, updating accordingly, thank you!

2022-06-20 01:16 UTC, eliykat approved these changes
Looking good!

2022-06-20 14:21 UTC, merged