[SM-44] Lazy loaded import and exporters
bitwarden/clients pull request #2918
Opened 2022-06-16 12:51 UTC by Hinton

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Migrate the importer and exports to be lazy loaded.

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

```
- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-06-22 04:39 UTC, eliykat requested changes
Had a quick look over with some comments, I'll have to review it closer and get my head around the ES2020 stuff. Have you eyeballed the Network tab to confirm that it is indeed lazy loading as intended?

2022-06-22 04:39 UTC, eliykat commented on apps/web/src/app/importers/importer.module.ts
> +export class ImportersModule {}
I suggest `ImportExportModule`, which better describes its functionality and distinguishes it from the `importers` in jslib.

2022-06-22 04:39 UTC, eliykat commented on apps/web/src/app/org-importers/org-export.component.ts
> +import { ExportComponent } from "../importers/export.component";
I think org features should stay in the `organisations` folder, pending further discussion on the ADR. Otherwise we have org features on the top level (in this PR), in the `organisations` folder (current practice), and nested at various depths in the `modules` folder (EUVR). This is adding another pattern on an ad-hoc basis.

2022-06-22 04:39 UTC, eliykat commented on apps/web/src/app/oss-routing.module.ts
> +            loadChildren: () => SecurityRoutingModule,
Why are we reversing all this existing lazy-loading? It's possible that we overuse it currently, but I'm not sure what the criteria is here.

2022-06-22 08:07 UTC, Hinton commented on apps/web/src/app/oss-routing.module.ts
> +            loadChildren: () => SecurityRoutingModule,
This PR enables lazy loading. All of the existing modules are not expected to be lazy loaded which will cause issues.

2022-06-22 12:52 UTC, Hinton commented
Yea, those are the additional bundles.
```
src_app_importers_export_component_ts-src_app_importers_import_component_ts-libs_common_src_s-f1b1f0.eeb1795dcaad48b31d5f.js (317.72 KB)
vendors-node_modules_jszip_dist_jszip_min_js.b04c555398ea9c7fb051.js (95.3 KB)
src_app_org-importers_org-importer_module_ts.65efbd1d2d546782bcca.js (62.31 KB)
src_app_importers_importer_module_ts.de307dd66b64e32ea6c2.js (2.84 KB)
```

2022-06-23 02:13 UTC, eliykat requested changes
I wanted to make sure I understood how webpack splits bundles for lazy loading, so I set up webpack-bundle-analyzer. In case you were interested:

1. left-hand side: bundle with common import/export code (mostly services, but also the base components)
2. right-bottom corner: bundle for individual code (doesn't contain much because most gets included in the common bundle)
3. right-top corner: bundle for the org code

![Screen Shot 2022-06-23 at 12 09 30 pm](https://user-images.githubusercontent.com/31796059/175192260-93501397-81f8-49e7-80f4-8ccd9722fd1e.png)

I'll submit a PR shortly with this tool set up.

Anyway, all looks good to me aside from the naming convention I've mentioned below.

2022-06-23 07:52 UTC, Hinton commented on apps/web/src/app/organizations/tools/import-export/org-export.component.ts
> +export class OrganizationExportComponent extends ExportComponent {
It's related to the PIQ task for avoiding duplicate class names. I don't believe it's good to have two components with identical names especially if they extend each other.

2022-06-28 20:22 UTC, eliykat approved these changes

2022-06-28 20:24 UTC, merged