Ps 55 encrypted export
bitwarden/clients pull request #2937
Opened 2022-06-20 21:38 UTC by cd-bitwarden

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

```
- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-06-21 05:31 UTC, eliykat requested changes
I've focused my review on the export flow, as this is what we've discussed, and I think my comments there will help you on the other changes as well.

I've left a lot of comments with more detail, but just to summarise the major points:
1. Move all `ExportComponent` logic to the base class and streamline it
2. Use reactive form controls, don't mix it with template-driven form logic
3. Use consistent i18n
4. Remove unneeded services etc

I'll also mention that we have our own Component Library with pre-styled form controls that we can use, but I think we should leave that until last - these changes will keep you busy, and refactoring that later won't be a big lift once all this is right.

2022-06-21 05:31 UTC, eliykat commented on apps/web/src/app/tools/export.component.ts
> +  viewUserApiKeyModalRef: ViewContainerRef;
This isn't required for `modalService.open`. If you see this around, it's because some older code uses `modalService.openViewRef`, which is no longer used. (but I didn't explain this when I gave you this example, so my bad)

2022-06-21 05:31 UTC, eliykat commented on libs/angular/src/components/user-secret-prompt.component.ts
> +export class UserSecretPromptComponent {
I'd call this `UserVerificationPromptComponent`, to keep it consistent with all the other `UserVerification` stuff.

2022-06-21 05:31 UTC, eliykat commented on libs/angular/src/components/user-secret-prompt.component.ts
> +  });
No need to have a `FormGroup` with a single control, you can just declare the control:

`secret = new FormControl()`

and then bind it in the template with `[formControl]="secret"`

2022-06-21 05:31 UTC, eliykat commented on libs/angular/src/components/user-secret-prompt.component.ts
> +      this.modalRef.close(false);
To make this as useful as possible, I think this component should show the error and let the user try again. (i.e. don't close the modal)

Only close & return false if the user exits out.

2022-06-21 05:31 UTC, eliykat commented on libs/angular/src/services/filePasswordPrompt.service.ts
> +import { Injectable } from "@angular/core";
I don't think you need services for the `FilePasswordPrompt` or the user verification prompt. This was a particular pattern used for the master password reprompt, because it's called from a lot of places and there is some other logic it needed to encapsulate.

Now, it's easy enough to just call `modalService.open(...)` directly in the component when you need a modal, so I suggest you do that instead of adding extra services. (Especially for `FilePasswordPrompt`, where it's only used in 1 location.)

2022-06-21 05:31 UTC, eliykat commented on apps/web/src/app/organizations/tools/export.component.ts
> +    this.modalTitle = modalConfig.data.modalTitle;
I don't think this is meant to be here

2022-06-21 05:33 UTC, eliykat commented on libs/angular/src/components/export.component.ts
> +    //fileEncryptionType 2 = file requires a user entered password, specific to the file
e.g.
```
export enum EncryptedExportType {
  AccountEncrypted = 0,
  FileEncrypted = 1
}
```

You can access it in the template by declaring it as a class member:

`encryptedExportType = EncryptedExportType`

2022-06-21 05:35 UTC, eliykat commented on libs/angular/src/components/user-secret-prompt.component.ts
> +export class UserSecretPromptComponent {
PS. I like how you let the user customize the text 👍 Maybe some default values would be useful, for the standard prompt text?

2022-06-21 05:36 UTC, eliykat commented
Also run linting: `npm run prettier && npm run lint:fix` to tidy your code as you go. (not a big deal until you're asking for a final review, but just in case you didn't know about it)

2022-06-21 13:53 UTC, cd-bitwarden commented on libs/angular/src/components/user-secret-prompt.component.ts
> +      this.modalRef.close(false);
Great point! 👍

2022-06-21 13:54 UTC, cd-bitwarden commented on apps/web/src/app/tools/export.component.html
> +  (ngSubmit)="promptUserForSecret(encryptionType)"
You're right! Can't believe I forgot that I don't need to pass the value 😆

2022-06-21 13:56 UTC, cd-bitwarden commented on libs/angular/src/components/export.component.ts
> +      const confirmPassword = this.confirmPassword;
I just thought it would be less wasteful than calling the confirmPassword() and password() function twice 🤔

2022-06-21 13:59 UTC, cd-bitwarden commented on apps/.vscode/launch.json
> +{
I'll be sure to leave this out in my real PR 😄 thanks!

2022-06-21 15:15 UTC, cd-bitwarden commented on libs/angular/src/components/export.component.ts
> +    //fileEncryptionType 2 = file requires a user entered password, specific to the file
Thanks! I was curious how enums worked in this project and was hoping someone would mention how to do it haha 👍

2022-06-21 17:17 UTC, cd-bitwarden commented on apps/web/src/app/tools/export.component.html
> +      <ng-container class="box-content condensed" *ngIf="formatControl === 'encrypted_json'">
nice! I didn't know ng-container behaved that way, good to know 👍

2022-06-21 18:33 UTC, cd-bitwarden commented on apps/web/src/app/tools/export.component.ts
> +    }
Good idea! Thanks

2022-06-21 22:03 UTC, cd-bitwarden commented on apps/web/src/app/tools/export.component.html
> +        [(ngModel)]="formatControl"
Cool, I updated this -- but I definitely need to find time to watch that knowledge sharing session you recommended!

2022-06-21 22:17 UTC, cd-bitwarden commented on apps/web/src/app/tools/export.component.html
> +        (change)="encryptionType = '0'"
Thanks, I'll bring this up to sukhleen

2022-06-21 22:25 UTC, cd-bitwarden commented on apps/web/src/app/tools/export.component.ts
> +import { Component, ViewChild, ViewContainerRef } from "@angular/core";
hmm not sure I completely understand the changes you are requesting 🤔

2022-06-22 03:15 UTC, eliykat commented on apps/web/src/app/tools/export.component.ts
> +import { Component, ViewChild, ViewContainerRef } from "@angular/core";
`clients/libs/angular/src/components` contains the base class for many Angular components, so that logic can be shared amongst the 3 Angular clients. In this case:

* `clients/libs/angular/src/components/export.component.ts` should contain all the common code that is required for the export functionality (such as what happens when you hit submit)
* each client's `ExportComponent` should sub-class this, add any client-specific code (minimal), and add the `@Component` decorator to tie it to a template (which is also different for each client)

So far, all clients support the same export options, so this PR should also add Password-Encrypted Export to desktop and browser to maintain that consistency. Therefore, all this code should go in the base class so that all Angular clients can use it. You can discuss this with product if you want to double check, or ask design if you need additional wireframes. But generally we want feature parity between clients.

We should also add it to mobile. That's out of scope here, but you could tackle that if you want some mobile experience, or coordinate with a mobile dev.

2022-07-21 21:08 UTC, cd-bitwarden commented
Closing this PR as it is outdated

2022-07-21 21:08 UTC, closed without merging