[CL-17] Tabs - Router
bitwarden/clients pull request #2952
Opened 2022-06-22 19:25 UTC by vincentsalucci

## Type of change
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective
> Implement tabs to be used in conjunction with `router-outlet`. 

## Code changes
- **components/src/index.ts:** Exported everything from the new `tabs` directory
- **dummy-components:** Created directory to hold all of the dummy components used for display purposes within the stories
- **src/tabs/index.ts**: Exported new tab module/group/item 
- **tab-group.component.html/ts**: Added layout for `tab-group` container and basic component class
- **tab-item.component.html**: Added layout that will switch to the correct element based on the `disabled` state. 
- **tab-item.component.ts**: This class mainly handles the application of base utility classes and active router link classes
- **tabs.module.ts**: Added module to import/export/declare necessary modules/components 
- **tabs.stories.ts**: Created default tabs + router story
- **tailwind.config.base.js**: Added the two other primary colors to be available for text coloring

## Screenshots
![0-tab-group-router-tabs](https://user-images.githubusercontent.com/26154748/175119782-0f8abc37-b1cf-4077-b036-e8db5da8f5f2.png)

## Before you submit
- [X] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2022-06-23 10:19 UTC, Hinton requested changes
Looks good overall, a few minor design comments.

The active effect looks a bit weird we should probably not show focus on active. @danielleflinn thoughts?

We seem to be changing text color on hover which doesn't match the figma. Although I'm not personally a fan of the underline either.

I also suspect we need to use z-index on focus since the outline doesn't appear on top currently.

2022-06-23 10:19 UTC, Hinton commented on libs/components/src/tabs/tabs.stories.ts
> +        ]),
We probably need  a default route for this to not look weird.

2022-06-23 10:22 UTC, Hinton commented on libs/components/src/tabs/dummy-components/dummy.component.html
> +</div>
I wonder if we could make this simpler by putting the styling before the router outlet in the stories, and just let the template be the title.

We could also move these into the stories file since they would only be

```
@Component({
  selector: "bit-tab-disabled-dummy",
  template: "Router - Disabled selected",
})
class DisabledDummyComponent {}
```

2022-06-23 10:33 UTC, Hinton commented on libs/components/src/tabs/tab-item.component.html
> +<ng-container [ngTemplateOutlet]="disabled ? btnRef : linkRef"></ng-container>
What do you think about using a switch here instead? Unfortunately I couldn't get rid of the last container. I also changed the disabled and aria-disabled to not be bindings to make it more obvious what's going on.

```suggestion
<ng-container [ngSwitch]="disabled">
  <a
    *ngSwitchCase="false"
    role="tab"
    [class]="baseClassList"
    [routerLink]="route"
    [routerLinkActive]="activeClassList"
    #rla="routerLinkActive"
    [attr.aria-selected]="rla.isActive"
  >
    <ng-content [ngTemplateOutlet]="content"></ng-content>
  </a>
  <button
    *ngSwitchCase="true"
    type="button"
    role="tab"
    [class]="baseClassList"
    disabled
    aria-disabled="true"
  >
    <ng-content [ngTemplateOutlet]="content"></ng-content>
  </button>
</ng-container>

<ng-template #content>
  <ng-content></ng-content>
</ng-template>

```

2022-06-23 14:37 UTC, danielleflinn commented on libs/components/src/tabs/tabs.stories.ts
> +      url: "https://www.figma.com/file/Zt3YSeb6E6lebAffrNLa0h/branch/f32LSg3jaegICkMu7rPARm/Web-Vault-Components-(Bootstrap)?node-id=1881%3A18454",
We should keep the focus state on the active tab; it would be odd behavior for a screen reader to only be able to focus that element if it wasn't active and allowing it to focus but hiding the focus indicator can be confusing for users using the visual indicator and keyboard navigation (where did the focus indicator disappear to?). 

That said, we could look at clearing the focus after a user clicks so that the active state is more visible. Material tabs seem to do this. 

Let's keep the color consistent between default and hover states. We also don't have the underline in the focus state on Figma; let's remove that.

2022-07-01 15:07 UTC, vincentsalucci commented on libs/components/src/tabs/dummy-components/dummy.component.html
> +</div>
Awesome suggestions. Thank you. Simplified and moving into stories file.

2022-07-01 15:14 UTC, vincentsalucci commented on libs/components/src/tabs/tabs.stories.ts
> +      url: "https://www.figma.com/file/Zt3YSeb6E6lebAffrNLa0h/branch/f32LSg3jaegICkMu7rPARm/Web-Vault-Components-(Bootstrap)?node-id=1881%3A18454",
Sorry everyone - the issues with the styles happened because I messed up the creation of this PR from the old repo to the new clients repo. Cleaning this up now!

2022-07-02 14:49 UTC, vincentsalucci commented on libs/components/src/tabs/tab-item.component.html
> +<ng-container [ngTemplateOutlet]="disabled ? btnRef : linkRef"></ng-container>
Fixed a typo in your suggestion (using `ng-content` inside of the switch items instead of `ng-container` and this is working as expected and is cleaner. Thanks for the suggestion!

2022-07-02 15:06 UTC, vincentsalucci commented
> I also suspect we need to use z-index on focus since the outline doesn't appear on top currently.

I wasn't able to get any z-index changes on the element to properly change how the ring was being displayed. No matter what was applied, the ring was behind the disabled button.

2022-07-02 15:10 UTC, vincentsalucci commented on libs/components/src/tabs/tabs.stories.ts
> +        ]),
I tried to get the active tab to be default selected by adding the changes we discussed, but wasn't successful. I've left the code in this most recent commit for review.

2022-07-02 21:21 UTC, Hinton commented on libs/components/src/tabs/tabs.stories.ts
> +        ]),
This seems to work for me.

```
        RouterModule.forRoot([
          { path: "active", component: ActiveDummyComponent },
          { path: "item-2", component: ItemTwoDummyComponent },
          { path: "item-3", component: ItemThreeDummyComponent },
          { path: "disabled", component: DisabledDummyComponent },
          { path: "", redirectTo: "active", pathMatch: "full" },
        ], { useHash: true}),
```

2022-07-05 09:22 UTC, Hinton commented
You can add `focus:tw-z-10` to the focus state and it should work.

2022-07-05 16:29 UTC, Hinton commented on libs/components/src/tabs/tab-item.component.ts
> +    ].join(" ");
You don't need to join these I believe. Just return the array directly.

2022-07-05 16:29 UTC, Hinton commented on libs/components/src/tabs/tab-item.component.ts
> +  route: string; // ['/route']
My personal preference are to keep these on the same line. If they only have a single decorator

```suggestion
  @Input() route: string; // ['/route']
```

2022-07-05 16:29 UTC, Hinton commented on libs/components/src/tabs/tab-item.component.ts
> +      "disabled:tw-border-t-transparent",
Do we need this? THe base style already has top border transparent.

2022-07-05 21:45 UTC, vincentsalucci commented on libs/components/src/tabs/tab-item.component.ts
> +    ].join(" ");
True. Thanks.

2022-07-05 21:45 UTC, vincentsalucci commented on libs/components/src/tabs/tab-item.component.ts
> +  route: string; // ['/route']
Alrighty.

2022-07-05 21:48 UTC, vincentsalucci commented on libs/components/src/tabs/tab-item.component.ts
> +      "disabled:tw-border-t-transparent",
It appears we don't. Good catch.

2022-07-05 21:52 UTC, danielleflinn submitted a review, later dismissed
Reviewed on Chromatic. Looks good!

2022-07-06 15:04 UTC, danielleflinn approved these changes

2022-07-13 16:04 UTC, vincentsalucci commented
Sorry @danielleflinn and @Hinton for the repeated dismissals! This PR should finally be good to go.

2022-07-13 16:12 UTC, danielleflinn submitted a review, later dismissed
Looks good in chromatic

2022-07-15 07:36 UTC, Hinton reviewed
Using `!` for all text colors since bootstrap tends to override it. There is one fairly annoying issue, the tabs jump when they become active due to `border-x`. We need to figure out a way to avoid that.

2022-07-15 15:11 UTC, vincentsalucci commented on libs/components/src/tabs/tab-group.component.html
> +>
Updated.

2022-07-15 15:15 UTC, vincentsalucci commented on libs/components/src/tabs/tab-item.component.ts
> +      "focus:tw-text-primary-700",
Updated.

2022-07-15 21:55 UTC, vincentsalucci commented on libs/components/src/tabs/tab-item.component.ts
> +      "tw-border-x",
Discussed with @Hinton - we will revisit this after this is merged.

2022-07-18 07:40 UTC, Hinton approved these changes
@danielleflinn I think the focus effect is slightly annoying. And I think `focus-visible` would be more appropriate here.

2022-07-18 14:17 UTC, merged

2022-07-18 20:03 UTC, danielleflinn commented
`Focus-visible` is fine with me