Ps55 6 22
bitwarden/clients pull request #2963
Opened 2022-06-23 16:44 UTC by cd-bitwarden

## Type of change

```
- [ ] Bug fix
- [ x ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

```
- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-06-23 16:54 UTC, cd-bitwarden commented on apps/browser/tsconfig.json
> -{
Oops probably shouldn't have deleted this.

2022-06-23 16:54 UTC, cd-bitwarden commented on apps/.vscode/launch.json
> +{
I wont include this file in my real PR

2022-07-15 04:42 UTC, eliykat requested changes
This is coming along nicely! Still some tidy up work to do for old/leftover code, and combining duplicate logic. Make sure to move all export component logic to the base class in `libs/angular`, because it's shared by all Angular apps (web, browser, desktop).

2022-07-15 04:42 UTC, eliykat commented on libs/angular/src/components/export.component.ts
> +  viewUserApiKeyModalRef: ViewContainerRef;
This old code still needs to be cleaned up

2022-07-15 04:42 UTC, eliykat commented on apps/web/src/app/tools/import-export/import.component.ts
> +  }
This is used for the master password reprompt feature specifically, you don't need it here.

2022-07-15 04:42 UTC, eliykat commented on apps/web/src/app/tools/import-export/import.component.ts
> +  }
looks like old code you need to clean up

2022-07-15 04:42 UTC, eliykat commented on apps/web/src/app/tools/import-export/import.component.ts
> +    const ref = await this.modalService.open(this.component, {
Inline `this.component`. There's no need to have it extracted as a class property.

2022-07-15 04:42 UTC, eliykat commented on apps/web/src/app/tools/import-export/import.component.ts
> +  }
This method seems unnecessary, just call `showPasswordPrompt` directly.

I'd also recommend calling it `showFilePasswordPrompt` to distinguish it from the user's MP.

2022-07-15 04:42 UTC, eliykat commented on apps/web/src/app/tools/import-export/import.component.ts
> +          } else {
Don't use empty `if` blocks, just do `if (!await this.promptFilePassword)` to handle the negative case.

2022-07-15 04:42 UTC, eliykat commented on libs/angular/src/components/file-password-prompt.component.ts
> +    );
I don't think import logic should be in this modal. The modal should get the file password only, and then return it to the `ImportComponent`, which handles it (i.e. by trying the import again).

2022-07-15 04:42 UTC, eliykat commented on apps/web/src/app/tools/import-export/export.component.ts
> +  modalTitle: string;
I don't think these are used anywhere.

2022-07-15 04:42 UTC, eliykat commented on libs/angular/src/services/userVerificationPrompt.service.ts
> +export class UserVerificationPromptService implements UserVerificationPromptServiceAbstraction {
I don't think you use this anywhere anymore, and a whole class for it seems like overkill. I think you can get rid of it.

2022-07-21 19:27 UTC, cd-bitwarden commented on libs/angular/src/components/file-password-prompt.component.ts
> +    );
I don't necessarily agree that we should take the suggested approach, do you have a strong opinion about changing this? If so we can schedule a quick chat so we can get on the same page 😄

2022-07-22 14:25 UTC, cd-bitwarden commented on apps/web/src/locales/en/messages.json
> +  "confirmVaultExportDesc" : {
Good suggestion 👍

2022-07-22 14:26 UTC, cd-bitwarden commented on apps/web/src/app/tools/import-export/export.component.ts
> +    }
✅

2022-07-22 14:27 UTC, cd-bitwarden commented on apps/web/src/app/tools/import-export/export.component.ts
> +    const modalTitle = "confirmVaultExport";
✅

2022-07-22 14:28 UTC, cd-bitwarden commented on apps/web/src/app/tools/import-export/import.component.ts
> +  }
Very true!

2022-07-22 14:30 UTC, cd-bitwarden commented on libs/angular/src/components/file-password-prompt.component.ts
> +    );
Spoke with Thomas through slack and decided we can leave this as is 😄

2022-07-22 14:32 UTC, cd-bitwarden commented on libs/angular/src/services/userVerificationPrompt.service.ts
> +export class UserVerificationPromptService implements UserVerificationPromptServiceAbstraction {
This whole file should be removed - let me know if you still see it, it's not on my branch anymore 🤔

2022-07-22 14:35 UTC, cd-bitwarden commented on apps/web/src/app/tools/import-export/export.component.ts
> +          this.i18nService.t("invalidMasterPassword")
It actually already did check on the UserVerificationPromptComponent, so I just needed to remove it here and it's good 😄

2022-07-22 22:41 UTC, cd-bitwarden commented on apps/web/src/app/tools/import-export/export.component.ts
> +      if (await ref.onClosedPromise()) {
Great suggestion!

2022-07-24 21:08 UTC, cd-bitwarden commented
> 

Should I just put notes above the code that needs to be moved, so that it can be moved by the person working on web/app/browser etc?

2022-07-26 10:22 UTC, eliykat requested changes
I've left detailed feedback so we can get this shaped up and merged. Good work so far!

A few comments that didn't fit anywhere else:

When running this locally, I got a number of errors in the console, e.g.
```
NG0303: Can't bind to 'ngIf' since it isn't a known property of 'div'.
ERROR TypeError: document.getElementById(...) is null
```

I recommend you test it and have a click around with devtools open so you can spot and debug any errors.

I also receive the `This file export will be password protected and require the file password to decrypt.` warning when exporting a **non-encrypted** file.

Last thing, the font size seems too small:

![Screen Shot 2022-07-26 at 8 20 37 pm](https://user-images.githubusercontent.com/31796059/180983743-40af1195-cf23-44da-ac9a-4326b980de15.png)

Hit me up on Slack or send me an invite if you want to discuss anything!

2022-07-26 10:22 UTC, eliykat commented on apps/web/src/locales/en/messages.json
> +    "message": "Leverages your Bitwarden account encryption not master password, to protect the export. This export can only be imported into the current account. Use this to create a backup that can
Typo (per the Figma)
```suggestion
    "message": "Leverages your Bitwarden account encryption, not master password, to protect the export. This export can only be imported into the current account. Use this to create a backup that cannot be used elsewhere."
```

2022-07-26 10:22 UTC, eliykat commented on apps/web/src/app/tools/import-export/export.component.html
> +                id="1"
Please use human-readable ids, e.g. `FileEncryptionType`

2022-07-26 10:22 UTC, eliykat commented on apps/web/src/app/tools/import-export/export.component.html
> +                [value]="0"
You can access the enum here by declaring it as a class property. e.g.

(in the class)
```ts
encryptedExportType = EncryptedExportType;
```

(in the template)
```ts
[value]="encryptedExportType.AccountEncrypted
```

That's much better because then it won't break if enum values change.

2022-07-26 10:22 UTC, eliykat commented on apps/web/src/app/tools/import-export/export.component.html
> +        <ng-container *ngIf="fileEncryptionType == 1">
Same here, better to use the enum rather than the enum value.

2022-07-26 10:22 UTC, eliykat commented on libs/angular/src/components/export.component.ts
> +    return (this.fileEncryptionType != 1 && this.password == undefined) || this.password == ""
Refer to the enum itself rather than the value, e.g. `EncryptedExportType.FileEncrypted`.

I'm also not sure about defaulting to a non-password protected export if the password is empty - that seems unsafe. I think we should just check the export format & file encryption type to make this decision.

2022-07-26 10:22 UTC, eliykat commented on libs/angular/src/components/export.component.ts
> +    }
This is repeating a lot of logic from the main `submit` method. The simplest suggestion I can think of is to extract this try/catch block into a `protected` method, like `doExport`. Then you can have your own submit logic in the child class and call `doExport` at the end, and you shouldn't need this method at all. I'm open to other suggestions though.

2022-07-27 15:18 UTC, cd-bitwarden commented on apps/web/src/app/components/user-verification-prompt.component.html
> +          <div [formGroup]="myGroup">
I was able to make this change :) I went the FormGroup route because I'm new at Angular -- and the console error I was getting recommended it haha

2022-07-27 17:48 UTC, cd-bitwarden commented on apps/web/src/app/modules/loose-components.module.ts
> +    FilePasswordPromptComponent,
oh, thank you for teaching me about this!

2022-07-27 23:34 UTC, cd-bitwarden commented on apps/web/src/app/tools/import-export/import.component.ts
> +    protected keyConnectorService: KeyConnectorService
Can't tell for sure, but I deduced you were talking about "KeyConnectorService" I removed it :)

2022-07-27 23:50 UTC, cd-bitwarden commented on libs/angular/src/components/export.component.ts
> +    confirmPassword: [""],
love that idea! Thank you 👍

2022-07-31 22:55 UTC, cd-bitwarden commented on apps/web/src/app/components/file-password-prompt.component.html
> +          <div>
fixed :)

2022-07-31 23:12 UTC, cd-bitwarden commented on apps/web/src/app/tools/import-export/export.component.html
> +                [value]="0"
Agreed, thanks!

2022-08-01 18:22 UTC, cd-bitwarden commented on libs/angular/src/components/file-password-prompt.component.ts
> +    fileContents: [""],
Thanks!

2022-08-01 18:25 UTC, cd-bitwarden commented on libs/angular/src/components/export.component.ts
> +    protected modalConfig: ModalConfig,
Removed them 👍

2022-08-01 18:27 UTC, cd-bitwarden commented on apps/web/src/app/components/file-password-prompt.component.html
> +      <div class="modal-footer">
Due to the design they chose I had to use modal-footer around the content to make it look correct, I'm new to styling these things, is there a better way?

2022-08-02 05:47 UTC, eliykat commented on libs/angular/src/components/export.component.ts
> +    protected modalConfig: ModalConfig,
`modalService` is still here

2022-08-02 05:52 UTC, eliykat commented on apps/web/src/app/components/file-password-prompt.component.html
> +<div class="modal fade" role="dialog" aria-modal="true" aria-labelledby="confirmVaultImport | i18n">
This expression needs to be evaluated - at the moment it's just a string. e.g.
```suggestion
<div class="modal fade" role="dialog" aria-modal="true" [attr.aria-labelledby]="confirmVaultImport | i18n">
```

Note that you need to prefix bound aria attributes with `attr.`, this is a weird Angular thing. [reference](https://angular.io/guide/accessibility#accessibility-attributes)

2022-08-02 05:52 UTC, eliykat commented on apps/web/src/app/components/file-password-prompt.component.html
> +          <div>
This looks much better now, thanks!

2022-08-02 07:34 UTC, eliykat commented on apps/web/src/app/components/file-password-prompt.component.html
> +      <div class="modal-footer">
Right, I didn't realise that it had styling attached that you wanted to reuse.

The reason I raised it is because HTML classes should be semantic, in other words, you should only use the `modal-footer` class (and styling) on the footer, you shouldn't reuse it for body content.

One way of dealing with this is to look at the styling you want from `modal-footer` and then replicate it in Tailwind. Then you don't have to worry about the scss as much, you can just use what you need, and you don't end up with this issue.

I ran out of time today to play with this, but I'm happy to experiment myself and push a change to show you what I mean.

2022-08-02 07:36 UTC, eliykat requested changes
Interim review as requested, I basically just went and ticked off the feedback you marked as resolved.

2022-08-03 21:07 UTC, cd-bitwarden commented on libs/angular/src/services/userVerificationPrompt.service.ts
> +export class UserVerificationPromptService implements UserVerificationPromptServiceAbstraction {
Removed it 👍

2022-08-03 21:48 UTC, cd-bitwarden commented on libs/angular/src/components/export.component.ts
> +    protected modalConfig: ModalConfig,
Could we potentially hop on a call tonight, when removing this I've had issues getting the code to work 😄

2022-08-03 21:50 UTC, cd-bitwarden commented on libs/angular/src/components/export.component.ts
> +    return (this.fileEncryptionType != 1 && this.password == undefined) || this.password == ""
So even though it's "non password protected" it's still protected by the account password 😄 so I don't think there are any issues defaulting to the original way (account password). Let me know what you think, I've gone ahead and updated it to use the enum

2022-08-03 22:31 UTC, cd-bitwarden commented on apps/web/src/app/components/file-password-prompt.component.html
> +              <input
added it back

2022-08-08 18:12 UTC, cd-bitwarden commented on libs/angular/src/components/export.component.ts
> +    }
Great idea!

2022-08-08 18:13 UTC, cd-bitwarden commented on apps/web/src/app/components/user-verification-prompt.component.html
> +          </app-user-verification>
I updated all the styling to be tailwinds 👍

2022-08-16 21:48 UTC, eliykat reviewed
A few quick notes for our review session:

* "Confirm format" needs to run validation on the password input fields (for password protected). At the moment there's no feedback.
* Pressing enter on the password input fields should submit the form, not toggle the password visibility. The FilePasswordPrompt component has the same issue

2022-08-16 21:48 UTC, eliykat commented on apps/web/src/app/components/file-password-prompt.component.html
> +        <div class="">
Remove empty class, or remove div altogether if it's not needed.

2022-08-16 21:48 UTC, eliykat commented on apps/web/src/app/core/core.module.ts
> +    },
These still need to be removed

2022-08-16 21:48 UTC, eliykat commented on apps/web/src/app/shared/loose-components.module.ts
> +    FilePasswordPromptComponent,
This is only used for import/export, so it can be declared in the `import-export.module.ts` instead.

2022-08-16 21:48 UTC, eliykat commented on libs/angular/src/components/export.component.ts
> +  async submitWithSecretAlreadyVerified() {
I'm still not following the submit logic very well, let's review this when we meet.

2022-08-16 21:48 UTC, eliykat commented on apps/web/src/app/tools/import-export/export.component.html
> +          <div class="tw-regular ml-3 pb-2 tw-text-xs">
This text still looks too small to me

2022-08-16 21:48 UTC, eliykat commented on apps/web/src/app/tools/import-export/export.component.html
> +              <label class="tw-semi-bold tw-ml-1 tw-text-xs"> {{ "accountBackup" | i18n }} </label>
This label needs to be associated with its form control, and we can probably get rid of some of these divs. Same for the other radio button.

2022-08-16 23:50 UTC, eliykat commented on apps/web/src/app/core/core.module.ts
> +    },
I'll look into this and push a fix, given we were hitting lots of errors when we tried to move it on the call.

2022-08-16 23:51 UTC, eliykat commented on apps/web/src/app/shared/loose-components.module.ts
> +    FilePasswordPromptComponent,
I'll also look into this one

2022-08-16 23:52 UTC, eliykat commented on libs/angular/src/components/export.component.ts
> +  async submitWithSecretAlreadyVerified() {
As discussed: let's move the logic of `submitWithSecretAlreadyVerified` into the top of the web `submit` method. Then delete `submitWithSecretAlreadyVerified` and call `doSubmit` directly from the web `submit` method.

2022-08-17 04:13 UTC, eliykat commented
@cd-bitwarden My last commit fixes the problem we were having when moving around `ImportService` and `FilePasswordPromptComponent` between modules. The issue is that `ImportService` and `FilePasswordPromptComponent` should both be scoped at the `ImportExportModule` level (feature module), but the `ModalService` which creates the dialog is scoped at the app level. So `ModalService` couldn't find `ImportService` to inject into `FilePasswordPromptComponent` when creating it. Which is an interesting problem.

There's probably a more elegant solution, but for now I've just passed in `ImportService` in the `ModalConfig.data`.

2022-08-17 04:34 UTC, eliykat requested changes
I think this is everything I said I'd get back to you on, back over to you!

2022-08-17 04:34 UTC, eliykat commented on apps/web/src/app/tools/import-export/export.component.ts
> +  async submit() {
Here's what you can do here to force form validation.

First, add validators in the code rather than in the HTML:
```ts
  exportForm = this.formBuilder.group({
    format: ["json"],
    secret: [""],
    filePassword: ["", Validators.required],
    confirmFilePassword: ["", Validators.required],
    fileEncryptionType: [],
  });
```

(remove the `required` attribute in the HTML)

Then mark all form components as "touched" to trigger validation:

```ts
this.exportForm.markAllAsTouched();
```

and you'll see the inline error messages pop up.

You should also bail out early if the form is invalid:

```ts
if (!this.exportForm.valid) {
return;
}
```

Because other clients don't use these fields we're now marking as required, you may have to move them down to the `web` import component. That is, re-declare `exportForm` with the extra fields in the web component, and remove the web-specific fields from the `libs/angular` base class.

Don't forget to quickly test one of the other clients to make sure we haven't broken anything.

2022-08-17 04:34 UTC, eliykat commented on apps/web/src/app/tools/import-export/export.component.ts
> +    if (!this.validFilePassword) {
Reminder to move this method to this class (from the base class), because it's only used by web. You could probably clean up the logic in it as well, now that we have the `Required` validators. i.e. you probably only need to check that the passwords are equal, not length etc.

2022-08-18 21:56 UTC, cd-bitwarden commented on apps/web/src/app/tools/import-export/export.component.html
> +              <label class="tw-semi-bold tw-ml-1 tw-text-xs"> {{ "accountBackup" | i18n }} </label>
Done :)

2022-08-18 21:59 UTC, cd-bitwarden commented on apps/web/src/app/tools/import-export/export.component.ts
> +    if (!this.validFilePassword) {
Done

2022-08-19 17:34 UTC, cd-bitwarden commented on apps/web/src/app/tools/import-export/export.component.html
> +          <div class="tw-regular ml-3 pb-2 tw-text-xs">
Coordinated with Sukhleen and ended up with a few visual changes

2022-08-19 18:46 UTC, cd-bitwarden commented on apps/web/src/app/tools/import-export/export.component.ts
> +  async submit() {
Thanks this worked! I disable them unless it was file encrypted export type.

2022-08-23 00:06 UTC, eliykat requested changes

2022-08-23 00:06 UTC, eliykat commented on apps/web/src/app/tools/import-export/file-password-prompt.component.html
> +          <button bitButton buttonType="primary" class="tw-mr-2" type="submit" appBlurClick>
This needs a spinner, large exports can take a while so we need to give feedback to the user. You can use the new `bit-submit-button` component from the CL.

2022-08-23 00:06 UTC, eliykat commented on libs/angular/src/components/export.component.ts
> +    this.exportForm.get("fileEncryptionType").setValue(EncryptedExportType.AccountEncrypted);
You can set a default value in the formControl declaration, e.g.
```
exportForm = this.formBuilder.group({
...
  fileEncryptionType: [EncryptedExportType.AccountEncrypted],
```

2022-08-23 00:06 UTC, eliykat commented on libs/angular/src/components/export.component.ts
> +    }
This call (and the getter itself) should be in the web child class, not here in the parent class.

2022-08-23 00:41 UTC, cd-bitwarden commented on apps/web/src/app/tools/import-export/export.component.html
> +              <label class="tw-semi-bold tw-text-md tw-ml-1 tw-mt-1 tw-mb-1">
👍

2022-08-23 00:43 UTC, cd-bitwarden commented on libs/angular/src/components/export.component.ts
> +    this.exportForm.get("fileEncryptionType").setValue(EncryptedExportType.AccountEncrypted);
ooh thanks!

2022-08-23 00:45 UTC, cd-bitwarden commented on libs/angular/src/components/export.component.ts
> +    }
okay makes sense

2022-08-23 00:45 UTC, cd-bitwarden commented on libs/angular/src/components/export.component.ts
> +      );
👍

2022-08-23 01:41 UTC, cd-bitwarden commented on apps/web/src/app/tools/import-export/file-password-prompt.component.html
> +          <button bitButton buttonType="primary" class="tw-mr-2" type="submit" appBlurClick>
good idea

2022-08-23 04:37 UTC, eliykat commented
@cd-bitwarden, I've fixed the error handling as follows:
* changed `FilePasswordPromptComponent` to just get the password and return it to `ImportComponent`
* `ImportComponent` has the password protected import logic

I also addressed some CodeScene feedback, mostly by just reducing nesting in some of the conditionals.

Please review and let me know what you think, and test it out to make sure the errors you were hitting are properly displayed.

One issue I ran out of time to solve is that if you select a non-encrypted export format -> click submit -> cancel out of the modal, then change to a File-Encrypted Export, the file password fields remain disabled. I think we need to enable/disable the fields based when the format and/or encryption type changes.

2022-08-26 04:40 UTC, eliykat requested changes

2022-08-26 04:40 UTC, eliykat commented on apps/web/src/app/components/user-verification-prompt.component.html
> +        class="tw-border-0 tw-border-t tw-border-solid tw-border-secondary-300 tw-bg-background-alt tw-bg-background-alt tw-p-3.5"
Duplicate `tw-bg-background-alt` classes

2022-08-26 04:40 UTC, eliykat commented on apps/web/src/app/tools/import-export/file-password-prompt.component.html
> +          class="tw-flex tw-w-full tw-flex-wrap tw-items-center tw-border-0 tw-border-t tw-border-solid tw-border-secondary-300 tw-bg-background-alt tw-bg-background-alt tw-pl-3.5 tw-pr-3.5 tw-pb-3.5
Duplicate `tw-bg-background-alt` classes

2022-08-26 04:49 UTC, eliykat approved these changes
Thank you for your work on this, please just make sure that file-encrypted import error (where you get double modals if the password is left blank) isn't still a problem before you merge (I couldn't reproduce it).

2022-08-29 14:11 UTC, merged