[EC-267] Unassigned collection has disappeared in web vault
bitwarden/clients pull request #3000
Opened 2022-06-29 12:52 UTC by coroiu

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Fix regression where filtering on "Unassigned" collections is no longer possible

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

![image](https://user-images.githubusercontent.com/2285588/176439890-a081f4db-b3ca-4838-a6f4-fcedacc8e342.png)

## Before you submit

```
- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-07-06 03:29 UTC, eliykat requested changes
Good work on this, and I love the tests.

2022-07-06 03:29 UTC, eliykat commented on libs/angular/src/modules/vault-filter/vault-filter.service.ts
> +        (c) => c.organizationId === organizationId || c.organizationId === null
Why is this change needed? Every collection should have an `organizationId`. The "Unassigned" collection does not exist in the `collectionService` cache and hasn't been added yet.

2022-07-06 03:29 UTC, eliykat commented on libs/angular/src/modules/vault-filter/models/vault-filter.model.spec.ts
> +    it("should return true when filter is set to favorites and cipher is favorite", () => {
There's a lot of repetition in the test names and it's difficult to identify related tests. I suggest nesting them again somehow, like:

```ts
describe("filterFunction", () => {
  describe("filters favorites", () => {
    it("when the cipher is a favorite", () => ...);
    it("when the cipher is not a favourite", () => ...);
  });
  describe("filters deleted items", () => {
    it("when the cipher is deleted", () => ...);
```

and so on.

I don't even think you need to state "returns true" etc, if it's otherwise clear what you're testing. Maybe you can think of better wording, but you get the idea.

2022-07-06 03:29 UTC, eliykat commented on libs/angular/src/modules/vault-filter/models/vault-filter.model.spec.ts
> +    it("should return false when filter is set to all and cipher is not favorite", () => {
This misdescribes the test, the filter is not set to all.

2022-07-06 03:29 UTC, eliykat commented on libs/angular/src/modules/vault-filter/models/vault-filter.model.spec.ts
> +      const filterFunction = createFilterFunction({ selectedCollectionId: "collectionId" });
You haven't set `selectedCollection`, shouldn't this test be failing?

2022-07-06 03:29 UTC, eliykat commented on libs/angular/src/modules/vault-filter/models/vault-filter.model.spec.ts
> +    it("should return true when filtering on my vault only and cipher does not have any organization", () => {
I think you should also test the inverse of this, i.e. my vault only + org item

2022-07-06 06:43 UTC, coroiu commented on libs/angular/src/modules/vault-filter/models/vault-filter.model.ts
> +  buildFilter(): VaultFilterFunction {
Yeah, the other clients were already refactored to use the `VaultFilter` model but the browser is very different and stores it's filters in query params instead of the `VaultFilter` class. I didn't want to do any more major changes in this PR which already contains more than the feature it's supposed to add. Also I didn't wanna risk breaking anything 😅 

Do you feel that the browser really should be refactored?

2022-07-06 06:51 UTC, coroiu commented on libs/angular/src/modules/vault-filter/models/vault-filter.model.spec.ts
> +    it("should return true when filter is set to favorites and cipher is favorite", () => {
Ah, thanks for pointing that out, grouping sounds like a great idea!

Regarding the test naming, I am using the `ShouldWhen` naming convention as stated in the [TDD Manifesto](https://tddmanifesto.com/a-clean-test/). Maybe one could rephrase the name, but I'd still like to keep the convention

> ShouldWhen
> 
> ShouldWhen template is an easy to read and widely used naming template. The name first reveals the expected behavior, then the precondition of the given test case.
> 
> Examples:
>
>    - ShouldHaveUserLoggedIn_whenUserLogsIn
>    - ShouldReturnCreditCardIsInvalidValidationError_whenTheOrderIsPurchasedWithInvalidCreditCardData
>    - ShouldIncreasebalanceWith100Euro_when100EuroDepositIsMadeToTheAccount

2022-07-06 07:37 UTC, coroiu commented on apps/web/src/app/modules/vault/modules/organization-vault/organization-vault.component.ts
> -        this.activeFilter.selectedFolderId != "none" &&
Nope that's exactly the thinking, `none` was not used in the web vault anymore and this is just a clean up 🙂

2022-07-06 07:48 UTC, coroiu commented on libs/angular/src/modules/vault-filter/vault-filter.service.ts
> +        (c) => c.organizationId === organizationId || c.organizationId === null
It's needed because of how the `Unassigned` collection works 

https://github.com/bitwarden/clients/pull/3000/files#diff-700e3d74ba9885c56bd3c0b248e825c105104e19b047b77078ee38085795e10cR74-R77
```typescript
    const noneCollection = new CollectionView();
    noneCollection.name = this.i18nService.t("unassigned");
    result.push(noneCollection);
```

2022-07-06 07:52 UTC, coroiu commented on libs/angular/src/modules/vault-filter/vault-filter.service.ts
> +        (c) => c.organizationId === organizationId || c.organizationId === null
But, hmmm, this change was initially made because I thought the `Unassigned` collection was supposed to be visible on the individual vault as well, where it wouldn't have a connection to any specific organization. However this function has since been moved to `async buildAdminCollections(organizationId: string)` where there is a connection to an organization.

I'll update this, good catch!

2022-07-06 09:23 UTC, coroiu commented on libs/angular/src/modules/vault-filter/models/vault-filter.model.spec.ts
> +    it("should return false when filter is set to all and cipher is not favorite", () => {
Restructured and reworded

2022-07-06 13:20 UTC, coroiu commented on libs/angular/src/modules/vault-filter/models/vault-filter.model.spec.ts
> +      const filterFunction = createFilterFunction({ selectedCollectionId: "collectionId" });
Nice catch, it doesn't fail because `selectedCollectionId` is ignored if `selectedCollection` is false

2022-07-07 00:35 UTC, eliykat commented on libs/angular/src/modules/vault-filter/models/vault-filter.model.ts
> +  buildFilter(): VaultFilterFunction {
Nope that's fine, I think you've done enough here without us also having to consider browser 🤯  Just wanted to make sure there was a reason!

2022-07-07 00:35 UTC, eliykat commented on libs/angular/src/modules/vault-filter/models/vault-filter.model.ts
> +    return (cipher) => {
Yep, I also checked the `this.deleted` change and came  to the same conclusion as you. All good!

2022-07-07 00:58 UTC, eliykat commented on libs/angular/src/modules/vault-filter/models/vault-filter.model.spec.ts
> +    it("should return true when filter is set to favorites and cipher is favorite", () => {
Ah, test naming, we could bikeshed on that all day 😁 

I am not particularly a fan of the ShouldWhen format, to me `ShouldReturnCreditCardIsInvalidValidationError_whenTheOrderIsPurchasedWithInvalidCreditCardData` is an example of a fairly unreadable test name.

I like a plain English approach, especially here (in Jest) where we get to use strings instead of function names. I also think that "includes/excludes" explains more than "should return true/false" - you can always check the assert statement if you want to know the expected return value, I think it's more useful that the test name describes the feature/functionality being tested.

All that said - we have no style guide here, so you can keep the current format. 

My only strong recommendation would be to add "given a" to the inner `describe` blocks. e.g. "given a generic cipher", "given a favorite cipher", "given a deleted cipher", etc... because you're describing the argument it's being given rather than, say, the system under test. I think it makes the context a lot clearer and it flows better (the describe + it blocks should form a rough sentence, like "filter function given a generic cipher should return true when filtering for favorites").

2022-07-07 01:25 UTC, eliykat reviewed
Looks good, the only outstanding item is just some further feedback on the test names. I've commented on the inline conversations above.

2022-07-07 07:13 UTC, coroiu commented on libs/angular/src/modules/vault-filter/models/vault-filter.model.spec.ts
> +    it("should return true when filter is set to favorites and cipher is favorite", () => {
> I am not particularly a fan of the ShouldWhen format, to me ShouldReturnCreditCardIsInvalidValidationError_whenTheOrderIsPurchasedWithInvalidCreditCardData is an example of a fairly unreadable test name.

I always assumed that the `camelCase_underscoreStyle` was just for an example for when you have to use the method name as the test name, meaning it would become `it('should return credit card is invalid validation error when the order is purchased with invalid credit card data')` when that is not a limitiation. But you have a very good point, bike shedding 😄

For me the _most important part is that the state under test is described in the name_. So `should throw error when email contains invalid characters` instead of `should throw error` which contains lots of assertions for all the error cases. Other than that I am pretty flexible about naming conventions 🙂 

Awesome suggestion, I really like `given a ...`! I'll add it straight away!

2022-07-07 08:00 UTC, coroiu commented on libs/angular/src/modules/vault-filter/models/vault-filter.model.ts
> +      }
Good points!
I'm changing to `null` in test to better reflect real values, but I'm leaving everything else as-is and resolving issue :)

2022-07-07 23:52 UTC, eliykat approved these changes

2022-07-08 08:18 UTC, merged