Refactor FolderService to use Observables
bitwarden/clients pull request #3022
Opened 2022-07-01 10:59 UTC by Hinton

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

```
- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-07-08 18:49 UTC, MGibson1 requested changes

2022-07-08 18:49 UTC, MGibson1 commented on libs/angular/src/modules/vault-filter/vault-filter.service.ts
> +  buildFolders(organizationId?: string): Observable<DynamicTreeNode<FolderView>> {
This method name doesn't really make sense anymore

2022-07-08 18:49 UTC, MGibson1 commented on libs/angular/src/modules/vault-filter/vault-filter.service.ts
> +      mergeMap((folders) => from(transformation(folders)))
This is a new method for me so I'm probably wrong, but isn't `mergeMap(... from([])` the same as just mapping the array (`map(folders => transformation(folders))`) ?

2022-07-08 18:49 UTC, MGibson1 commented on apps/browser/src/popup/vault/vault-filter.component.ts
> +    this.nestedFolders = allFolders.nestedList;
This is really not the right way to use this. It feels like this is pretty deep in the guts of the filters component structure. Are you thinking we need observables for each ciphers, collection, and folders before updating this behavior?

2022-07-08 18:49 UTC, MGibson1 commented on apps/web/src/app/vault/bulk-move.component.ts
> +    this.folderId = (await firstValueFrom(this.folders$))[0].id;
I'm struggling with the googling, but it really feels like there must be a better way to convert an observable array to a select node with a default value

2022-07-08 18:49 UTC, MGibson1 commented on libs/common/src/services/folder/folder.service.ts
> +        return;
Should update observables to `[]` if there's no active account

```suggestion
        await this.clear()
        return;
```

2022-07-08 18:49 UTC, MGibson1 commented on libs/common/src/services/state.service.ts
> -
Please update `Account` models by removing the possibility of storing unencrypted `FolderViews`

2022-07-09 13:15 UTC, Hinton commented on libs/angular/src/modules/vault-filter/vault-filter.service.ts
> +      mergeMap((folders) => from(transformation(folders)))
`mergeMap` flattens observables. Otherwise we would have an observable of an observable.

2022-07-09 16:11 UTC, Hinton commented on apps/browser/src/popup/vault/vault-filter.component.ts
> +    this.nestedFolders = allFolders.nestedList;
I know, but I didn't particularly want to update this in this iteration. The vault filter component essentially needs a major rewrite to behave reactively. Ciphers and collections should be observables as well, and once that's done we need to figure out how to handle the sub components inputs more appropiately, as it's all callback based.

2022-07-09 16:15 UTC, Hinton commented on apps/browser/src/popup/vault/vault-filter.component.ts
> +    this.nestedFolders = allFolders.nestedList;
https://rxjs.dev/api/index/function/combineLatest

2022-07-11 09:37 UTC, Hinton commented on libs/angular/src/modules/vault-filter/vault-filter.service.ts
> +  }
No me neither. But I do believe it's 1 step closer to where it's used with this move as it's only related to the visual presentation. I didn't want to focus on de-tangling the Tree structure in this PR.

2022-07-11 09:39 UTC, Hinton commented on apps/web/src/app/vault/bulk-move.component.ts
> +    this.folderId = (await firstValueFrom(this.folders$))[0].id;
```ts
(await firstValueFrom(this.folders$.pipe(folders => folders[0].id));
```

Not sure I like this much better ....

2022-07-11 09:53 UTC, Hinton commented on libs/common/src/services/state.service.ts
> -
I was a bit lazy here as I didn't want to write a data migration for this yet. I've added a new temporary data structure that only has `encrypted`. I suggest waiting until everything is migrated and we've figured out a better way of storing dynamic account data before doing this change.

2022-07-11 12:22 UTC, MGibson1 commented on libs/common/src/services/folder/folder.service.ts
> +    if (userId == (await this.stateService.getUserId())) {
ah I see, thank you.

2022-07-11 12:26 UTC, MGibson1 commented on apps/web/src/app/vault/bulk-move.component.ts
> +    this.folderId = (await firstValueFrom(this.folders$))[0].id;
No that's no better. I was hoping for some kind of select html node generation that understood observable arrays.

2022-07-11 12:27 UTC, MGibson1 commented on apps/web/src/app/vault/bulk-move.component.ts
> +    this.folderId = (await firstValueFrom(this.folders$))[0].id;
Now that I look at this again, though, this will throw for empty folder arrays. Do we always have a `No Folder` in there?

2022-07-11 12:27 UTC, MGibson1 commented on libs/common/src/services/state.service.ts
> -
I was hoping to avoid migrations as well, that's why I specifically asked about removing unencrypted FolderViews.

There should be no migrations necessary for memory-only state impacts.

2022-07-11 12:48 UTC, Hinton commented on apps/web/src/app/vault/bulk-move.component.ts
> +    this.folderId = (await firstValueFrom(this.folders$))[0].id;
We always have `No Folder`

2022-07-11 12:58 UTC, MGibson1 commented on libs/angular/src/modules/vault-filter/vault-filter.service.ts
> +  }
OK, let's make a tech debt item to restructure this service and implement the view trees better. I'm thinking jsut use the angular tree concept directly

2022-07-11 17:40 UTC, MGibson1 requested changes

2022-07-11 17:40 UTC, MGibson1 commented on libs/common/src/abstractions/folder/folder.service.abstraction.ts
> +  replace: (folders: { [id: string]: FolderData }) => Promise<void>;
🥇

2022-07-12 16:11 UTC, MGibson1 reviewed
:shipit:

2022-07-12 17:13 UTC, MGibson1 approved these changes
🚢 it

2022-07-12 18:25 UTC, merged