Ec 272 implement web workers
bitwarden/clients pull request #3043
Opened 2022-07-06 00:17 UTC by eliykat

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Add web workers - this is just a draft PR to track my progress in setting up the basic scaffolding, until #2970 and #3042 are merged.

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

```
- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-09-07 21:03 UTC, vincentsalucci commented
@MGibson1 @Hinton - Lots of big changes here. Would love ya'lls 👀 on this, if possible.

2022-09-07 22:41 UTC, MGibson1 commented
IDK... @eliykat specifically promised this PR would be small...

2022-09-07 23:29 UTC, eliykat commented
As small as I could make it 🤷 this PR is scoped to just the web worker feature itself and associated plumbing.

2022-09-08 09:09 UTC, djsmith85 requested changes
Awesome work on this @eliykat!! 

To keep track of what I have reviewed and what parts might need work or more reviewers, I have created the below. I will update this, once I continue my review of the unreviewed files or when issues have been addressed.

## Feature flags :heavy_check_mark:
### Definition of shared feature flag :heavy_check_mark:
- libs/common/src/misc/flags.ts

### Browser - Enabling :heavy_check_mark:
- apps/browser/config/development.json
- apps/browser/config/production.json

### Desktop - Disabled :heavy_check_mark:
- apps/desktop/config/development.json
- apps/desktop/config/production.json

### Web - Enabling :heavy_check_mark:
- apps/web/config/development.json
- apps/web/config/qa.json
- apps/web/config/cloud.json
- apps/web/config/selfhosted.json

### CLI - Undefined :heavy_check_mark:
Not included the in the following files, which if I remember correctly defaults a flag to false
- apps/cli/config/development.json
- apps/cli/config/production.json
Which is fine, as we are not planning on enabling this anytime.


## ServiceFactories :warning:
- apps/browser/src/background/service_factories/cipher-service.factory.ts :heavy_check_mark:
- apps/browser/src/background/service_factories/encrypt-worker-service.factory.ts :warning:

## EncryptWorkerService instantiation :warning:
### Browser :heavy_check_mark:
- apps/browser/src/background/main.background.ts
  - Instantiation of EncryptWorkerService and passed on to CipherService
  - Adding call to this.encryptWorkerService.clear()

- apps/browser/src/listeners/onCommandListener.ts
  - Instantiation of EncryptWorkerService and passed on to CipherService

### Web :heavy_check_mark:
- apps/web/src/app/app.component.ts
  - Instantiation of EncryptWorkerService and passed on to CipherService
  - Adding call to this.encryptWorkerService.clear()

### CLI :heavy_check_mark:
- apps/cli/src/bw.ts
  - Instantiation of EncryptWorkerService and passed on to CipherService
  - Adding call to this.encryptWorkerService.clear()

### Desktop :warning:
Registration of `EncryptWorkerService` via `AbstractEncryptWorkerService` is done via `jslib-service.module` **but**
- **apps\desktop\src\app\app.component.ts is missing `AbstractEncryptWorkerService` on the `ctor`**
- **`app.compontent.logout()` is missing a call to `this.encryptWorkerService.clear()`**

## PlatformUtils :warning:
- libs/common/src/abstractions/platformUtils.service.ts :heavy_check_mark:
- libs/node/src/cli/services/cliPlatformUtils.service.ts :warning:
- libs/electron/src/services/electronPlatformUtils.service.ts :heavy_check_mark:
- apps/browser/src/services/browserPlatformUtils.service.ts :heavy_check_mark:
- apps/web/src/app/core/web-platform-utils.service.ts :heavy_check_mark:

## Test/Specs :warning:
- libs/common/spec/utils.ts
- libs/common/spec/misc/utils.spec.ts :heavy_check_mark:
- libs/common/spec/models/domain/folder.spec.ts :heavy_check_mark:
- libs/common/spec/models/view/loginView.spec.ts :warning:
- libs/common/spec/models/view/cipherView.spec.ts :heavy_check_mark:
- libs/common/spec/models/view/attachmentView.spec.ts`:warning:
- libs/common/spec/services/cipher.service.spec.ts :heavy_check_mark:

## Misc
- libs/angular/src/services/injection-tokens.ts :heavy_check_mark:
  - Register new InjectionToken for ENCRYPT_WORKER_URL 
- libs/electron/src/window.main.ts :heavy_check_mark:
  - Enabling same environment for the worker as the window has

## Still in Review :eyes:
- libs/common/src/abstractions/encryptWorker.service.ts
- libs/common/src/services/cipher.service.ts
- libs/common/src/services/encryptWorker.service.ts
- libs/common/src/workers/encrypt.worker.spec.ts
- libs/common/src/workers/encrypt.worker.ts
- libs/common/src/workers/workerRequestResponse.spec.ts
- libs/common/src/workers/workerRequestResponse.ts

## Remaining/Unreviewed files
I'd love if @MGibson1 and/or @Hinton could have a look at these. Especially with the ES2020 and change of imports.

- apps/web/src/app/app.module.ts
- apps/web/src/app/core/index.ts
- bitwarden_license/bit-web/src/app/app.module.ts
- libs/angular/src/services/jslib-services.module.ts
- All tsconfig.json files

2022-09-08 09:10 UTC, Hinton reviewed
Some random things I found. I haven't reviewed this!

Do we know if setting ES2020 will result in any compatibility issues with browsers?

2022-09-08 09:10 UTC, Hinton commented on apps/web/tsconfig.json
> +    "types": ["jest"],
Why do we need to add jest types explicitly?

2022-09-08 09:10 UTC, Hinton commented on apps/web/src/app/core/index.ts
> +// export * from "./core.module";
Sounds like this got fixed, should we revert this now?

2022-09-08 21:36 UTC, eliykat commented on apps/browser/src/background/service_factories/encrypt-worker-service.factory.ts
> +type EncryptWorkerServiceFactoryOptions = FactoryOptions;
Yes, good call - first time working with this factory pattern.

2022-09-08 21:39 UTC, eliykat commented on apps/web/tsconfig.json
> +    "types": ["jest"],
I was having problems with jest types at one stage and this fixed it. I wasn't even writing tests in web though, so I'm not sure why I put it here. I'll try taking it out again.

2022-09-08 21:42 UTC, eliykat commented on apps/web/src/app/core/index.ts
> +// export * from "./core.module";
"Fixed" as in, "this workaround now works as intended". We still need the workaround :( I'll explain in my separate comment below, because the ES2020 here kinda sucks.

2022-09-08 22:16 UTC, eliykat commented
Here's some ES2020 related info for this PR.

## Browser Compatibility

> Do we know if setting ES2020 will result in any compatibility issues with browsers?

You already enabled ES2020 in `web` to make lazy-loading work. As `browser` is operating in the same browser with the same support, enabling it for `browser` as well seems safe. And Electron v19.* is locked to Chrome 106, which supports it.

However, I realised pretty late in this process that ES2020 is not all or nothing, <caniuse.com> has individual support charts for different features of it. Here's the [support chart for import.meta](https://caniuse.com/?search=import.meta) which we rely on here. It's been supported since 2018 for Chrome, Safari, Firefox and Opera, and since 2020 for Edge. It is actually very similar to the [support for dynamic imports](https://caniuse.com/es6-module-dynamic-import) which you enabled, and we haven't had any issues from it.

## Node Compatibility

### CLI

Node v16 [has stable support for ESM](https://nodejs.org/docs/latest-v16.x/api/esm.html#esm_modules_ecmascript_modules), but only [experimental support for import.meta](https://nodejs.org/docs/latest-v16.x/api/esm.html#importmetaresolvespecifier-parent).

Also, node doesn't really have web workers as such, it has [worker threads](https://nodejs.org/docs/latest-v16.x/api/worker_threads.html) which is like the node native version of the same concept.

At any rate, this feature has less benefit for CLI and it was never really the priority; it's not worth reimplementing a separate API here or messing with experimental support. We disable the feature at runtime via `platformUtilsService.supportsWebWorkers` and keep the `import.meta` statement out of the common code that CLI uses. (This is why it's provided via the constructor, to lift it up to client-specific code.) Remember that ES2020 is a different compile-time syntax, if Typescript hits ES2020 features during compilation without ESM support enabled, it'll throw an error.

### Jest

Jest is more of a challenge, because we're running tests for non-node clients in a node environment (using jsdom). That means that ES2020 code that compiles fine for the browser/Electron will not compile for tests, unless we enable experimental `import.meta` support in node, and experimental ES2020 support in Jest.

Without ES2020 support enabled, the `trial-initiation.component.spec.ts` test was failing to compile, because its various import statements would eventually find the `import.meta` statement. This is what commenting out `core.module.ts` from the barrel file is intended to avoid; importing anything from a barrel file imports _everything_ that the barrel file refers to. My bet - at this stage - is that test code should not need to import `core.module.ts`, because tests will always configure their own providers in TestBed. Keeping it out of the barrel file should hopefully keep it out of test code compilation.

The alternative is to enable `import.meta`/ES2020 support in Node and Jest, which I was able to do, I just thought the above was the more straightforward solution to try first. That said, this is only a test environment we're talking about, so using experimental features is not out of the question. (decorators are also experimental...)

Anyway, I hope that helps, in retrospect I would've raised this for discussion earlier but the node-related pain points came up pretty late in the process. Let me know what you think.

2022-09-12 18:36 UTC, MGibson1 requested changes
I've stopped reviewing when I got to cipherService and encryptWorkerService.

I don't think we can make cipherService carry the burden of determining whether it should use a web worker. That's someone else's responsibility.

IMO the right way to do this results in _no_ encryption/decryption in CipherService at all. It would just send off some encrypted data to an `EncryptService` that would then determine itself if it should send off to a web worker or do the work itself (preferably based on its own type, like `WebWorkerEncryptService` or just `EncryptService`).

We discussed this pretty early on, but I'm feeling it even more now -- this web worker can't be specific to Ciphers, it needs to just take in `EncString`s and decrypt them and send them back. It might be OK to accept objects implementing some `decryptable` interface or otherwise passing decryption information, but we can't have this intimacy between the CipherService and EncryptWorkerService/EncryptService.

2022-09-12 23:32 UTC, eliykat commented on apps/web/tsconfig.json
> +    "types": ["jest"],
Nothing, it's been removed ;)

2022-09-12 23:38 UTC, eliykat commented on apps/desktop/config/development.json
> +    "webWorkerDecryption": false
No, this is temporary until we find a solution for [EC-493](https://bitwarden.atlassian.net/browse/EC-493).

2022-09-12 23:55 UTC, eliykat commented on apps/browser/src/background/service_factories/encrypt-worker-service.factory.ts
> +    "vaultTimeoutService",
This is already fixed from Daniel's review - I can see the pattern here, it was just a copy + paste mistake that I missed. But I get your point that it would be nice to avoid it from the start; would it be any better if you just declared a [Symbol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) at the top of each factory file, then used that as the cache key in the exported factory function? Then that's guaranteed to be unique every time, but I _think_ you still get the human-readable string for debugging (disclaimer: I haven't tested).

2022-09-12 23:57 UTC, eliykat commented on libs/common/src/abstractions/encryptWorker.service.ts
> +export abstract class AbstractEncryptWorkerService {
I don't think so, last I heard it was a prefix, based on the [Use Explicit Class Names RFD](https://bitwarden.atlassian.net/wiki/spaces/PIQ/pages/177111115/Use+Explicit+class+names) and other recent class abstractions, e.g. `AbstractEncryptService`.

That type of decision might be better moved to a ADR though.

2022-09-20 02:25 UTC, eliykat commented
I'm closing this PR, I need to make some changes to how these services are structured (based on @MGibson1's excellent feedback) which will make a lot of the changeset described here redundant. I'll open a new PR when ready.

2022-09-20 02:25 UTC, closed without merging

2022-09-20 18:59 UTC, MGibson1 commented on apps/browser/src/background/service_factories/encrypt-worker-service.factory.ts
> +    "vaultTimeoutService",
I don't think that solves the issue, just moves the string change from here to the top of the file, right?