[EC-280] Update policies page content
bitwarden/clients pull request #3059
Opened 2022-07-07 11:43 UTC by r-tome

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [X] Other
```

## Objective

Update the content on the policies and single sign-on pages to make them more consistent, easier to understand, and to align better with the Bitwarden voice, tone, and style. 

## Code changes

- **apps/web/src/app/app.component.ts:** Moved master password reset policy up to 3rd row
- **apps/web/src/app/organizations/manage/policies.component.html:** Updated “Enabled” badge text to “On”
- **apps/web/src/app/organizations/policies/disable-send.component.html:** Updated “enabled” checkbox to “Turn on”
- **apps/web/src/app/organizations/policies/master-password.component.html:** Updated “enabled” checkbox to “Turn on”
- **apps/web/src/app/organizations/policies/master-password.component.ts:** Use the new master-password policy title text
- **apps/web/src/app/organizations/policies/password-generator.component.html:** Updated “enabled” checkbox to “Turn on”
- **apps/web/src/app/organizations/policies/require-sso.component.html:** Updated “enabled” checkbox to “Turn on”
- **apps/web/src/app/organizations/policies/reset-password.component.html:** Updated “enabled” checkbox to “Turn on”
- **apps/web/src/app/organizations/policies/send-options.component.html:** Updated “enabled” checkbox to “Turn on”
- **apps/web/src/app/organizations/policies/single-org.component.html:** Updated “enabled” checkbox to “Turn on”
- **apps/web/src/app/organizations/policies/two-factor-authentication.component.html:** Updated “enabled” checkbox to “Turn on”
- **apps/web/src/app/organizations/policies/two-factor-authentication.component.ts:** Use the new two-factor authentication policy title text
- **apps/web/src/locales/en/messages.json:** Updated existing policy titles; updated the introduction on the single sign on  page; added texts "Turn on" and "On"
- **bitwarden_license/bit-web/src/app/policies/disable-personal-vault-export.component.html:** Updated “enabled” checkbox to “Turn on”
- **bitwarden_license/bit-web/src/app/policies/maximum-vault-timeout.component.html:** Updated “enabled” checkbox to “Turn on”

## Screenshots

<img width="898" alt="image" src="https://user-images.githubusercontent.com/108268980/177765192-961d9fe2-6b47-4dd3-a23f-0c498238248c.png">
<img width="447" alt="image" src="https://user-images.githubusercontent.com/108268980/177765317-2d88d8e0-10e0-46c9-b828-d8cfaf73acf7.png">
<img width="447" alt="image" src="https://user-images.githubusercontent.com/108268980/177765385-c8eede54-e359-458e-a11e-e10ed9acee55.png">
<img width="919" alt="image" src="https://user-images.githubusercontent.com/108268980/177765444-52a2cf29-018f-45cd-9929-f79836320644.png">

## Before you submit

```
- [X] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-07-08 20:30 UTC, djsmith85 requested changes
@r-tome Awesome work on this 🚀 . Just one small thing that I had wrongly commented on during a previous conversation. Please add the separate policy title back in.

2022-07-08 20:30 UTC, djsmith85 commented on apps/web/src/locales/en/messages.json
> +    "message": "Require two-step login"
This needs to stay and a separate text (twoStepLoginPolicyTitle 🤷 ? ) needs to be created for the "Require two-step login" as that key is also used on for example the Settings page.

2022-07-11 08:53 UTC, r-tome commented on apps/web/src/locales/en/messages.json
> +    "message": "Require two-step login"
Nicely spotted, I've added the separate label twoStepLoginPolicyTitle.

2022-07-11 09:42 UTC, djsmith85 approved these changes

2022-07-11 10:24 UTC, merged