[PS-94] Ensure autofill always uses the same tab
bitwarden/clients pull request #3066
Opened 2022-07-07 20:53 UTC by shane-melton

## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Require specifying the tab that is to be autofilled in the autofill service.

## Code changes

- **apps/browser/src/services/autofill.service.ts:** Add a `tab` property to `options` to specify the tab to be autofilled.
- **_all others changes_:** Make use of the new `tab` property when calling `doAutoFill()` from the `autofillService`

## Before you submit
```
- [X] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-07-13 19:56 UTC, MGibson1 submitted a review, later dismissed
This looks great from my mile-high view. I'm happy once the new `any` is gone. I'll let @djsmith85 do a final review since he wanted to

2022-07-13 19:56 UTC, MGibson1 commented on apps/browser/src/background/runtime.background.ts
> +  private tabToAutoFill: any;
Please use the expected type here rather than `any`.

I know all the others are `any`, but we're trying to get away from them. 

In this instance, we're sending an interface so we're OK, but if it was an actual class there's a concern about loss of prototype during serialization, just specify the type as having keys of the expected type to ensure type compliance.

2022-07-15 16:29 UTC, djsmith85 requested changes

2022-07-15 16:29 UTC, djsmith85 commented on apps/browser/src/background/runtime.background.ts
> +  private tabToAutoFill: chrome.tabs.Tab;
I don't think this is needed, as it the value can be extracted from the  msg.tab and passed on onto the private method `autofillPage` once the typed parameter tabToAutoFill is included.

2022-07-18 20:38 UTC, shane-melton commented on apps/browser/src/background/runtime.background.ts
> +  private tabToAutoFill: chrome.tabs.Tab;
Yep, I replaced the class property with a typed parameter to the `autofillPage` method. 

I also looked into using the `tab` property in `pageDetails` like we discussed and **it is does contain** the same `tab` interface as `msg.tab`. However, I am still not completely confident in why the `pageDetails` is an array when filling a single tab, so I didn't refactor the autofill service at this time to avoid potentially breaking something unknown.

2022-07-21 14:58 UTC, djsmith85 approved these changes
@shane-melton Great work on this. This looking good and thank you for your patience with the review.

2022-07-21 17:56 UTC, merged