update electron
bitwarden/clients pull request #3071
Opened 2022-07-08 14:02 UTC by jlf0dev

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Update electron to `19.0.8`
Update electron-builder to `23.1.0`
Update electron-log to `4.4.8`
Update electron-store to `8.0.2`
Update electron-updater to `5.0.5`

There hasn't been any serious breaking changes in electron for these two versions:
https://www.electronjs.org/docs/latest/breaking-changes#planned-breaking-api-changes-190

## Before you submit

```
- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-07-08 14:18 UTC, Hinton commented
We need to be careful when bumping electron builder and updater, builder didn't properly support our certs for testflight before. And updater needs a QA round to ensure the updates behave properly.

2022-07-13 09:00 UTC, djsmith85 submitted a review, later dismissed
Changes look good, besides re-buiding `package-lock.json`.

For the electron-builder issue I have a created a follow-up task in our backlog.

2022-07-13 17:59 UTC, jlf0dev commented on package-lock.json
> +      "version": "2022.6.2",
I'm a little confused by this. We have the `2022.6.2` version in the cli project, so i'm assuming its copying it from there. Is there a reason it should stay as `1.22.1`?

2022-07-13 19:00 UTC, djsmith85 commented on package-lock.json
> +      "version": "2022.6.2",
No, the bump to that version is fine, but it should not be showing up in the diff, as you did not make that change.

2022-07-14 16:25 UTC, MGibson1 requested changes

2022-07-14 16:25 UTC, MGibson1 commented on package.json
> +    "electron-builder": "^22.11.10",
Please keep this at this exact version

2022-07-14 17:18 UTC, MGibson1 commented
@vgrassia can you please retest testflight with the latest changes?

2022-07-14 21:58 UTC, djsmith85 commented on package-lock.json
> +      "version": "2022.6.2",
Spoke about this earlier today and it seems that the cli version bump action only bumped the version in the `apps/cli/package.json` and `apps/cli/package-lock.json` and did not commit the change of the root `package.json` and `package-lock.json`.

Error in the build action: Not committing those changes properly. 
@jlf0dev just being the first dev to rebuild the package-lock.json and that's why the change shows up in the diff

2022-07-15 17:49 UTC, MGibson1 approved these changes

2022-07-15 17:56 UTC, merged