Adds Mir payment system
bitwarden/clients pull request #3079
Opened 2022-07-10 16:37 UTC by vitalybaev

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Mir is a Russian payment system that is quite popular. [More info](https://en.wikipedia.org/wiki/Mir_(payment_system))

There is a [request](https://community.bitwarden.com/t/add-new-type-of-card/11408) for this feature.

## Code changes

I've added `Mir` as a value of credit card brand as well as I've added both dark and light logos of the payment system.

Mir's cards are similar to Visa and Mastercard - 16 digits with 4 blocks, 4 digits each. All Mir cards starts with `2` so I've updated base importer code.

## Screenshots
<img width="398" alt="CleanShot 2022-07-10 at 19 23 34@2x" src="https://user-images.githubusercontent.com/724423/178153585-ef882533-5f37-4235-a193-cba4ab80a2a4.png">
<img width="503" alt="CleanShot 2022-07-10 at 19 23 16@2x" src="https://user-images.githubusercontent.com/724423/178153587-7bb9ea34-6af4-4347-b4a3-f09e85b7e2c7.png">

<img width="502" alt="CleanShot 2022-07-10 at 19 35 46@2x" src="https://user-images.githubusercontent.com/724423/178153622-8a2f9a65-288b-4234-87aa-fa934ff70dec.png">

## Before you submit

```
- [x] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-07-10 16:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitwarden/clients?pullRequest=3079) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bitwarden/clients?pullRequest=3079) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitwarden/clients?pullRequest=3079) it.</sub>

2022-07-13 10:55 UTC, djsmith85 requested changes
@vitalybaev Thank you for your contribution. Your changes are looking good so far. Just some minor additions.

@danielleflinn Could you please review the provided icons.

2022-07-13 10:55 UTC, djsmith85 commented on libs/common/src/importers/baseImporter.ts
> +    re = new RegExp("^2");
Kudos for adding the detection to the importters 🚀. Even though this is the last card check and does not overlap with the existing ones. The regex should be narrowed to `^220` as the number range is from `2200-2204` based on information I took from https://en.wikipedia.org/wiki/Payment_card_number. Please check if that is the case.

2022-07-13 10:55 UTC, djsmith85 commented on libs/angular/src/pipes/credit-card-number.pipe.ts
> +  Mir: [{ cardLength: 16, blocks: [4, 4, 4, 4] }],
Based on information taken from [here ](https://en.wikipedia.org/wiki/Payment_card_number) the card numbers length varies between 16-19. Maybe you can find how they usually get displayed when not shown in blocks of 4.

2022-07-13 14:20 UTC, vitalybaev commented on libs/common/src/importers/baseImporter.ts
> +    re = new RegExp("^2");
Oh, nice catch, IDK why I haven't checked Wikipedia for that. I've narrowed it to be exact `2200-2204`, because `2205` is taken by BORIKA.

2022-07-13 14:25 UTC, vitalybaev commented on libs/angular/src/pipes/credit-card-number.pipe.ts
> +  Mir: [{ cardLength: 16, blocks: [4, 4, 4, 4] }],
I did some investigation and can state, that Mir cards **could** have 16-19 digits, but the vast majority of them have 16 digits. I found only one case when bank issue cards with 19 digits:

<img width="288" alt="CleanShot 2022-07-13 at 17 10 35@2x" src="https://user-images.githubusercontent.com/724423/178757181-13c18972-1390-4ca3-afb2-1c3bd3a297a1.png">

Of course, I've updated the formatter, but since we don't actually know how exactly look cards with 17 and 18 digits, I've just put all additional numbers to the first block.

2022-07-13 16:12 UTC, vitalybaev commented on libs/common/src/importers/baseImporter.ts
> +    re = new RegExp("^2");
@danielleflinn yes, you are totally right, I've updated the screenshot for dark theme. It's not easy to find an appropriate English version of the Mir logo, I used this one:

https://connectum.eu/wp-content/uploads/2020/01/mir_logo_small_en.png

I made it white and resized to be visually the same in comparison to other logos.

2022-07-13 17:43 UTC, danielleflinn commented on libs/common/src/importers/baseImporter.ts
> +    re = new RegExp("^2");
@vitalybaev hmm; I wonder if we should just use the  `мир` Russian version of the logo rather than the English one? I'm not seeing the English Mir logo as an official option in the brand guidelines, and we should avoid miss-representing a trademarked brand. This would also solve for the localization question you had around the updating the logo.

2022-07-14 11:21 UTC, vitalybaev commented on libs/common/src/importers/baseImporter.ts
> +    re = new RegExp("^2");
@danielleflinn I thought about that, and _it seems_ that because of limited popularity in Russian-speaking countries, there are no examples of use English version of the logo.
But now I agree that we can leave logo in Russian because the vast majority of Mir users speak Russian.
So I've replaced logos as well as updated screenshots. For this purpose, I used an SVG logo from Wikipedia.

2022-07-14 11:29 UTC, vitalybaev commented
> @vitalybaev I think I'm reading your suggestion correctly; you'd like to update the "Mir" string for the "brand" drop down to `мир` if the user selects Russian as the account's language preference?
> 
> I think that is a great idea; we have several translators over in the [Bitwarden Crowdin](https://crowdin.com/project/bitwarden-web/ru) projects. If you'd like to suggest the update yourself, you can follow these Bitwarden Crowdin [contributor guidelines](https://bitwarden.com/blog/password-security-is-universal/).

@danielleflinn yes, you understood me correctly! It seems that 99% of Mir users (at least nowadays) speaks Russian, and therefore it's better to display them Russian `Мир` translation. But of course it's not good to show to the rest of the users Russian variant in select component. So, translation is the solution.

But I'm struggling with the process of creation of a new translation string. I see it as the following:
1. Manually create new string in `locales/en/messages.json`
2. Use this string normally through the `i18nService`
3. Then someone syncs Crowdin projects, after that translators will be able to translate this string to different languages.

Do I understand it correctly?

So that's why I decided to move this part to different PR 🙂

2022-07-15 15:42 UTC, djsmith85 approved these changes
Thank you for adding this. Code-wise this looks good and I'm approving your changes. 

Adding a hold label and requesting a review of the russian logos from @danielleflinn. 

Once she approves we can get this merged.

2022-07-18 14:52 UTC, danielleflinn commented
Russian logos look good!

2022-07-19 10:20 UTC, djsmith85 commented
@vitalybaev Thank you again for your contribution. This is ready to merge and will get passed on to QA. Your work will likely be included in the 2022.09 release.

@danielleflinn Thank you for your help in reviewing this.

2022-07-19 10:20 UTC, merged

2023-01-23 16:56 UTC, dkorzhevin commented
Can I ask for this change to be reversed?

You are a U.S. company, and you should not support an aggressor country and its sanctioned payment system.

I'm not talking about getting money, I'm talking about displaying the ability to add Mir cards. 

Also, no other password manager provides individual support for cards of this type.

I have been using your service for over 4 years, and I actively recommend its use in a professional environment, as I am a public person.

I ask you very much to meet and understand me and millions of other people who are now surviving in Ukraine, because of the Russian invasion.

2023-01-23 17:31 UTC, dbosompem commented
Hi @dkorzhevin thanks for checking in with this. The team has been discussing this internally as well with regards to similar concerns you've raised, and so we would most likely put a hold on this. Possibly a separate PR to handle that. Hope this helps.

2023-02-20 17:19 UTC, dkorzhevin commented
@dbosompem Dear bitwarden developers - how many months do you need to make the right decision? You're already have PR to remove ruSSian payment system:

https://github.com/bitwarden/clients/pull/4554

2023-02-20 17:23 UTC, dbosompem commented
@dkorzhevin I believe I replied on the other issue. We will review the PR and revert. Thanks!