[PS-683] Fix missed defaults and sentence cases
bitwarden/clients pull request #3095
Opened 2022-07-13 08:54 UTC by coroiu

## Type of change

- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other

## Objective

1. I missed some changes and some typos in the initial PR, this fixes those.
2. After discussions with @danielleflinn the "Ask for biometrics on launch" checkbox is now hidden if biometrics are disabled
3. I refactored biometric checkbox to use `ngModel`. Also added a note about a bug that's is affecting the checkbox (the bug is not introduced in this PR, it's been there since before). The bug affects `[checked]` as well as `[ngModel]`.

## Code changes

- **apps/browser/src/popup/settings/settings.component.html:** Hide auto prompt checkbox if biometrics disabled.
- **apps/browser/src/popup/settings/settings.component.ts :** Remove superfluous default. State service already contains default values.
- **apps/desktop/src/app/accounts/settings.component.html :** Hide auto prompt checkbox if biometrics disabled. Use `ngModel` for biometric checkbox.
- **apps/desktop/src/app/accounts/settings.component.ts :** Refactor `updateBiometric` to make it easier to read. Remove if-guard in `updateAutoPromptBiometrics` which is no longer needed because we hide the checkbox.
- **apps/desktop/src/locales/en/messages.json :** Fix typo and translation I missed updating.

## Screenshots

![image](https://user-images.githubusercontent.com/2285588/178692431-c49f6629-e82b-4a58-91c1-596ae920ebbd.png)
![image](https://user-images.githubusercontent.com/2285588/178692968-2c7426ef-d8eb-43d2-8e8b-95c94a574920.png)

## Before you submit

- [x] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2022-07-13 21:11 UTC, MGibson1 requested changes

2022-07-13 21:11 UTC, MGibson1 commented on apps/desktop/src/app/accounts/settings.component.ts
> +    // See: https://github.com/angular/angular/issues/13063
Can you describe what to change to get rid of this workaround once that issue is closed?

2022-07-13 21:11 UTC, MGibson1 commented on apps/desktop/src/app/accounts/settings.component.ts
>      }
Maybe merge these two ifs with an `||` ?

2022-07-14 07:51 UTC, coroiu commented on apps/desktop/src/app/accounts/settings.component.ts
> +    // See: https://github.com/angular/angular/issues/13063
Once the issue is closed it should resolve itself, I'll add a comment mentioning that!

2022-07-14 07:55 UTC, coroiu commented on apps/browser/src/popup/settings/settings.component.ts
> +    this.enableAutoBiometricsPrompt = !(await this.stateService.getDisableAutoBiometricsPrompt());
Yeah but `getDisableAutoBiometricsPrompt` already contains a null coalescing operator, so this operator should be unnecessary, right? See: https://github.com/bitwarden/clients/blob/PS-683-fix-defaults-and-sentence-cases/libs/common/src/services/state.service.ts#L865

2022-07-14 07:58 UTC, coroiu commented on apps/desktop/src/app/accounts/settings.component.ts
> -
I can re-add it, but will this case ever actually happen? This method is only called through the checkbox, and the checkbox is completely removed from the DOM if `this.biometric` is `false`

2022-07-19 12:07 UTC, MGibson1 commented on apps/browser/src/popup/settings/settings.component.ts
> +    this.enableAutoBiometricsPrompt = !(await this.stateService.getDisableAutoBiometricsPrompt());
ah, most things that come out of that class can be null. yeah, you don't need it

2022-07-19 12:08 UTC, MGibson1 commented on apps/desktop/src/app/accounts/settings.component.ts
> -
Removing an element from the dom doesn't remove it from the backing component. It'll maintain state even without a visualization.

2022-07-19 12:51 UTC, merged