[SG-388] Organization menu style improvements
bitwarden/clients pull request #3100
Opened 2022-07-13 18:57 UTC by BrandonM-Bitwarden

## Type of change
Bug fix for dark mode.

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

```
- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-07-13 18:59 UTC, BrandonM-Bitwarden commented on apps/web/src/scss/base.scss
> -button i.bwi {
I would prefer if this ccs relied on `.dropdown-item` but making a change like that would require significantly more testing and may have unexpected behaviour elsewhere.

2022-07-21 12:55 UTC, differsthecat commented on apps/web/src/scss/forms.scss
> -    background-color: themed("dropdownBackground");
I think the `dropdown-item` class is used in a lot of places and we probably shouldn't modify the css for it for this particular case.

2022-07-21 13:03 UTC, differsthecat requested changes
I'm a little wary about us modifying the css classes for things that are used in a lot of places like in `forms.scss`. This could be a good opportunity to use tailwind classes for the dropdown items here in the `organization-options` component :)

2022-07-25 15:26 UTC, differsthecat approved these changes
Nice work!

2022-07-25 15:26 UTC, merged