fix: remove unassigned from lists
bitwarden/clients pull request #3102
Opened 2022-07-14 10:03 UTC by coroiu

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

The `Unassigned` collection was mistakenly added to lists other than the filters menu. This removes it.

## Code changes

All changes are just to filter collections with `null` `id`

## Screenshots

## Before you submit

```
- [x] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-07-15 01:35 UTC, eliykat requested changes

2022-07-15 01:35 UTC, eliykat commented on libs/angular/src/components/add-edit.component.ts
> +    return allCollections.filter((c) => !c.readOnly && c.id != null);
This is coming from local synced data, which will never have the `Unassigned` collection (given that we only create it in `VaultFilterService.buildAdminCollections` for the purpose of showing it as a filter). So this check shouldn't be necessary here. (If it is then we have bigger problems)

2022-07-15 01:35 UTC, eliykat commented on libs/angular/src/components/collections.component.ts
> +      (c) => !c.readOnly && c.organizationId === this.cipher.organizationId && c.id != null
Same here

2022-07-18 07:02 UTC, coroiu commented on libs/angular/src/components/add-edit.component.ts
> +    return allCollections.filter((c) => !c.readOnly && c.id != null);
Removed!

2022-07-18 07:02 UTC, coroiu commented on libs/angular/src/components/collections.component.ts
> +      (c) => !c.readOnly && c.organizationId === this.cipher.organizationId && c.id != null
Removed!

2022-07-18 23:57 UTC, eliykat commented on apps/desktop/src/app/accounts/settings.component.html
> +              </div>
I think this is an accidental inclusion, please undo.

2022-07-18 23:58 UTC, eliykat requested changes

2022-07-18 23:58 UTC, eliykat commented on apps/desktop/src/app/accounts/settings.component.html
> +              </div>
I think this is an accidental inclusion, please undo.

2022-07-19 06:17 UTC, eliykat approved these changes

2022-07-19 06:29 UTC, merged