Folder fixes, including revamped auth logic
bitwarden/clients pull request #3118
Opened 2022-07-15 08:38 UTC by Hinton

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other
```

## Objective

Resolves two defects found with the folder refactor #3022.

## Code changes

- **libs/angular/src/modules/vault-filter/vault-filter.service.ts:** Fixed `getFolderNested` not working as it doesn't provide any folders to `getAllFoldersNested`. Solved by re-adding the null check.

## Screenshots

## Before you submit

```
- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-07-15 14:46 UTC, MGibson1 requested changes

2022-07-15 18:49 UTC, MGibson1 requested changes

2022-07-15 18:49 UTC, MGibson1 commented on libs/angular/src/modules/vault-filter/vault-filter.service.ts
>    protected async getAllFoldersNested(folders?: FolderView[]): Promise<TreeNode<FolderView>[]> {
You got rid of the null acceptance, but didn't  get rid of the `?` in the parameters

2022-07-15 18:49 UTC, MGibson1 commented on libs/common/src/services/state.service.ts
>        }
`activeAccountUnlocked` is already false in this branch, you need a new one

```suggestion
    this.activeAccount.subscribe(async (userId) => {
      if (userId == null && this.activeAccountUnlocked.getValue() == false) {
        return;
      } else if (userId == null) {
        this.activeAccountUnlocked.next(false);
      }
```

2022-07-18 07:48 UTC, Hinton commented on libs/common/src/services/state.service.ts
>        }
Ah correct. Although I would expect cryptoMasterKey to be null here.

2022-07-18 12:38 UTC, MGibson1 approved these changes

2022-07-18 12:39 UTC, merged