Cleanup `src` folder for web and move ts code  into `src/app` per angular convention
bitwarden/clients pull request #3127
Opened 2022-07-18 07:30 UTC by Hinton

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Moves all the "application" code into `src/app` per https://angular.io/guide/file-structure#application-source-files. Removes the `StateServiceAbstraction` since it's not needed, we just have a single implementation for state service.

## Before you submit

```
- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-07-22 18:19 UTC, MGibson1 approved these changes

2022-07-22 18:19 UTC, MGibson1 commented on package.json
> +    "lint": "eslint . || prettier --check .",
I don't understand why should be an OR instead of an AND. We want both to pass not either or.

2022-07-22 18:20 UTC, MGibson1 requested changes
Sorry, forgot about that npm script that needs reverting

2022-07-25 08:05 UTC, Hinton commented on package.json
> +    "lint": "eslint . || prettier --check .",
I was certain I read that `&&` for some reason didn't behave as expected, can't replicate the behavior again though so reverted.

2022-07-25 12:58 UTC, MGibson1 approved these changes

2022-07-25 13:13 UTC, merged