Add Autofill Shortcut to MV3 Extension
bitwarden/clients pull request #3131
Opened 2022-07-18 18:24 UTC by justindbaur

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Make `Cmd/Ctrl+Shift+L` shortcut work in MV3 chrome extension.

## Code changes

- **apps/browser/src/background.ts:** Add a fork for MV2 vs MV3
- **apps/browser/src/background/contextMenus.background.ts:** `@types/chrome` changed the type of `menuItemId` from `string` to `string | number`.
- **apps/browser/src/background/webRequest.background.ts:** Put the use of `webRequest` behind a manifest version check since MV3 won't be using it.
- **apps/browser/src/commands/ciphers/*.ts:** Commands splitting up cipher.service.ts so it can be constructed easier in service worker context
- **apps/browser/src/content/autofill.js:** Add new command handler that responds in the response callback.

## Screenshots

## Before you submit

```
- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-07-22 19:42 UTC, MGibson1 requested changes

2022-07-22 19:42 UTC, MGibson1 commented on apps/browser/src/listeners/onCommandListener.ts
> +  // TODO: Remove this before we encourage anyone to start using this
So what is your plan to remove this and the "don't love this" parts?

We need to work through our plan on getting this where we actually want it.

2022-07-22 19:42 UTC, MGibson1 commented on apps/browser/src/models/autofillField.ts
> +  [key: string]: any;
It'd be nice to not need this.

I know that's a lot more type definitions, but it seems like largely we can use the autofillConstants file to help out.

2022-07-22 20:24 UTC, justindbaur commented on apps/browser/src/background/contextMenus.background.ts
> +    if (typeof info.menuItemId !== "string") {
As far as I am away yes this is. BUT we are the controllers of the menuItemId so we can actually guarantee (as much as you can in JavaScript) that it will always be a `string`. So an argument could be made that we cast it as any and carry on as normal.

2022-07-26 18:04 UTC, justindbaur commented on apps/browser/webpack.config.js
> +
Switching to that breaks MV3 for me. It has the same problem that having the `commons2` chunk has. None of the message listeners get registered.

2022-07-26 18:06 UTC, justindbaur commented on libs/common/src/misc/utils.ts
> +  /* eslint-disable */
Yes I believe it's necessary as that is how you define variables in a namespace: https://www.typescriptlang.org/docs/handbook/declaration-files/by-example.html#global-variables

2022-07-26 18:15 UTC, justindbaur commented on libs/common/src/models/domain/symmetricCryptoKey.ts
> +import { Utils } from "@bitwarden/common/misc/utils";
This was done by accident, changed it back.

2022-07-26 18:16 UTC, justindbaur commented on libs/common/src/services/noop/noOpEvent.service.ts
> +export default class NoOpEventService implements EventService {
We can't do that but I can put a check in the constructor that throws when not in MV3.

2022-07-26 18:18 UTC, justindbaur commented on apps/browser/src/listeners/onCommandListener.ts
> +  // TODO: Remove this before we encourage anyone to start using this
I believe this is because of a circular dependency but this is also what it currently does just with a class variable instead of a local variable. It's just that I personally don't like the looks of it.

2022-07-26 19:10 UTC, justindbaur commented on apps/browser/src/models/autofillField.ts
> +  [key: string]: any;
This would require a lot of changes that I think would have to change the actual logic that I don't feel comfortable with. I think we should be able to use const assertions of a lot of the `autofillConstants` in the future but it would have to be a larger concerted effort than I'm comfortable doing in this PR.

2022-07-26 19:38 UTC, justindbaur commented on libs/common/src/models/view/cipherView.ts
> +  static initFromJson(jsonResult: CipherView): CipherView {
The initial CipherView does come in with a prototype from the decorator. Since that one does come in with a top level prototype I was assuming we were standardizing around that and that was my reasoning for this stuff. I will align with the work being done there though.

2022-08-09 15:06 UTC, MGibson1 requested changes

2022-08-09 15:06 UTC, MGibson1 commented on package.json
> -    "browser-hrtime": "^1.1.8",
Why are you removing this dep? This is needed in CLI

2022-08-09 15:29 UTC, justindbaur commented on package.json
> -    "browser-hrtime": "^1.1.8",
I can't actually find where this is used in CLI but either way CLI has it's own `package.json` with dependencies and `browser-hrtime` is still in there.

2022-08-09 22:57 UTC, MGibson1 approved these changes
We're going to have to get to that service split sooner rather than later to clean up `onCommandListener`

2022-08-09 22:57 UTC, MGibson1 commented on package.json
> -    "browser-hrtime": "^1.1.8",
I could _swear_ this pointed to `chalk` before...

nvm, this isn't needed there.

2022-08-10 01:30 UTC, merged