CL-7 Avatar
bitwarden/clients pull request #3153
Opened 2022-07-21 17:43 UTC by rr-bw

- CL-7 Begin Implementing Avatar
- add figma design to parameters

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

```
- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-07-22 14:36 UTC, Hinton commented on libs/components/src/avatar/avatar.stories.ts
> +      url: "https://www.figma.com/file/Zt3YSeb6E6lebAffrNLa0h/Tailwind-Component-Library?node-id=1717%3A15868",
This url doesn't seem to go to the avatar component.

```suggestion
      url: "https://www.figma.com/file/Zt3YSeb6E6lebAffrNLa0h/Tailwind-Component-Library?node-id=1881%3A16994",
```

2022-07-22 14:36 UTC, Hinton commented on libs/components/src/avatar/avatar.component.ts
> +  @Input() circle = false;
@danielleflinn can you confirm which inputs we want to expose?

Figma leads me to believe we want:

* Size: xl, normal, xs?
* Color: (Background color)

We currently have these settings from the existing avatar components which we need to either remove or keep.

* Circle: Always except for settings pages.
* fontWeight: always 300
* fontSize: 14 except settings which uses 35
* Size: 25 (users), 45 (organization page) or 75 (settings)
* charCount: always 2
* textColor: should be dynamic per figma
* dynamic: Seems to indicate if the avatar should update on change, I think we should remove this option.

2022-07-25 16:18 UTC, danielleflinn commented on libs/components/src/avatar/avatar.component.ts
> +  @Input() circle = false;
@Hinton we should be good with the following inputs:

- Size: large, default, small 
- Color: Background color
- Outline: if on a light background there should be the option to display with a 1px secondary-500 border so that our there is adequate contrast between the background and the clickable element. 
- dynamic: I think this is used on the Settings page to update the avatar if the Name field is updated. If deprecating this input will remove this functionality we should probably keep it; otherwise I'm fine with removing it. 

Based on your comment that we use 25, 45, and 75 width sizes currently, I've updated Figma's default and large size to match the existing sizes a bit better. @rr-bw the previous large size is not the default, and the new large size has a width of 72. 

The following do not need to be configurable per implementation:
- Shape/Circle: Always display as circle. There are plans to update the shape of the settings avatar in https://bitwarden.atlassian.net/browse/SG-58.
- fontWeight: always 300
- fontSize: should be set based on avatar size: Large=text-3xl, default=text-XL. small=text-xs
- charCount: always 2
- text-color: set dynamically to maintain a 4.5:1 contrast ratio. Ratio in Storybook shows only 2.45:1 currently. @differsthecat may have insight into how to adjust the existing contrast formula to increase accessibility.

2022-07-25 16:22 UTC, danielleflinn commented on libs/components/src/avatar/avatar.component.ts
> +    const enableGravatars = await this.stateService.getEnableGravitars();
@Hinton  There are plans to [deprecate Gravatars](https://bitwarden.atlassian.net/browse/SG-434) in the near future; do we want to remove this functionality from the CL component now?

2022-07-25 18:24 UTC, rr-bw commented on libs/components/src/avatar/avatar.component.ts
> +  @Input() circle = false;
Do we need to rethink the way we are implementing the avatar? Currently we are generating an SVG and styling it imperatively. For example, the `fontSize` input is being styled inline like so:
`textTag.style.fontSize = this.fontSize + "px"`.

To use a Tailwind class, I could change this to `textTag.classList.add('tw-text-sm')`, but this would only add the class to the SVG source during SVG generation, and not to our final DOM. In other words, the Tailwind class won't do anything here.

As an example, the Tailwind class in this case would get applied to the source found at `data:image/svg+xml;base64...`

![Screen Shot 2022-07-25 at 10 57 10 AM](https://user-images.githubusercontent.com/102181210/180846710-7b44506d-4003-4517-b186-a980df2d36f3.png)

…but this obviously doesn’t do anything for us since the final avatar component is rendered as: 

![Screen Shot 2022-07-25 at 10 59 19 AM](https://user-images.githubusercontent.com/102181210/180846743-e7cbf669-5105-49c7-a97e-1c4c600f6590.png)

There’s two potential solutions for this:

1. What I’ve currently done is kept the SVG `fontSize` at 20px and `svgSize` 48px every time during *SVG generation*. Then, I’ve enabled the outer *Avatar* component `img` to be resized using the `size` input, allowing for `large`, `default`, and `small`, which correlate to Tailwind classes, such as `tw-h-7 tw-w-7` for `small`, and so forth. The SVG (and font size) seems to scale decently well base on size. (You can preview this implementation on Storybook at the moment).

2. We could rework the Avatar component to be a styled `span` or `div` element instead of an `img` with a generated SVG `src`. This would allow for easier styling with Tailwind classes. (But maybe this path is not an option if we need this componenet to be an `img`.)

Does that all make sense? Let me know if you have any other suggestions.

2022-07-25 19:50 UTC, danielleflinn commented on libs/components/src/avatar/avatar.component.ts
> +  @Input() circle = false;
It's fine to not use tailwind classes for font-size and to keep the image component. I'll update Figma to reflect this.

2022-07-26 11:34 UTC, Hinton commented on libs/components/src/avatar/avatar.component.ts
> +  @Input() circle = false;
We should make `dynamic` the default and remove this option. I can't think of any reason we would not want it to auto update.

2022-07-26 11:47 UTC, Hinton requested changes
Lets take this opertunity to clean up the component and remove most of the legacy logic.

2022-07-26 11:47 UTC, Hinton commented on libs/components/src/avatar/avatar.component.ts
> +  }
We already have this in organization-name-badge. We should extract it to a common static class.

2022-07-26 11:47 UTC, Hinton commented on libs/components/src/avatar/avatar.component.ts
> +  private getCharText(character: string): HTMLElement {
I know this is copy and pasted, but I think the naming of this is a bit missleading. We're creating a html element so I think we should call it `createTextElement`.

2022-07-26 11:47 UTC, Hinton commented on libs/components/src/avatar/avatar.component.ts
> +    const enableGravatars = await this.stateService.getEnableGravitars();
Lets remove it.

2022-07-26 11:47 UTC, Hinton commented on libs/components/src/avatar/avatar.component.ts
> +  get avatarClass(): string {
Please return an array here instead, and rename the method to `classList` since it better matches the other components.

2022-07-26 11:47 UTC, Hinton commented on libs/components/src/avatar/avatar.component.ts
> +        className += "tw-h-[72px] tw-w-[72px]";
@danielleflinn do we explicitly want 72px or one of the tailwind sizes?

2022-07-26 11:47 UTC, Hinton commented on libs/components/src/avatar/avatar.component.ts
> +  @Input() dynamic = false;
Lets remove dynamic.

2022-07-26 11:47 UTC, Hinton commented on libs/components/src/avatar/avatar.component.ts
> +  @Input() data: string;
We should rename this from `data` to perhaps `text`. Data doesn't convey what we expect it to be.

2022-07-26 11:47 UTC, Hinton commented on libs/components/src/avatar/avatar.component.ts
> +      class="tw-rounded-full"
Once we have an array for `classList` we should probably move `tw-rounded-full` into that array as well to clean this up slightly.

2022-07-26 11:47 UTC, Hinton commented on libs/components/src/avatar/avatar.component.ts
> +      [src]="sanitizer.bypassSecurityTrustResourceUrl(src)"
Lets move the `sanitizer` logic into the typescript code. Using it directly in the template feels wrong.

2022-07-26 11:47 UTC, Hinton commented on libs/components/src/avatar/avatar.component.ts
> +  svgSize = 48;
These should be private. Or inlined where they are used.

2022-07-26 11:47 UTC, Hinton commented on libs/components/src/avatar/avatar.component.ts
> +      }
We don't plan on supporting a charcount other than 2 so lets remove part of this logic.

2022-07-26 11:47 UTC, Hinton commented on libs/components/src/avatar/avatar.component.ts
> +  }
We also use this in the organization name badge. Lets extract it to a common utils class. `ColorsUtils`?

2022-07-26 14:31 UTC, danielleflinn commented on libs/components/src/avatar/avatar.component.ts
> +        className += "tw-h-[72px] tw-w-[72px]";
Good catch; we can use a tailwind class. Let's go with w-16.

2022-07-28 07:46 UTC, Hinton commented on libs/components/src/avatar/avatar.component.ts
> +  @Input() email: string;
Email isn't used?

2022-07-28 10:42 UTC, Hinton commented
@danielleflinn have we had any thoughts on how to ensure avatars are unique when the text is identical? We could support two inputs one being the id, and the other being the text that is visible.

2022-07-28 14:37 UTC, danielleflinn commented
@Hinton I like the idea of an id to help randomize the color for users with 2 accounts including the same name. There is also work in the SG pod that will allow users to override the auto generated color of their avatar; see [SG-58](https://bitwarden.atlassian.net/browse/SG-58).

2022-07-28 21:20 UTC, rr-bw commented on libs/components/src/avatar/avatar.component.ts
> +  @Input() email: string;
It was used for gravatars, which we are removing, so I will remove `email`

2022-08-02 13:25 UTC, Hinton commented on libs/components/src/avatar/avatar.stories.ts
> +  `,
I don't believe we need the template here. It should only be needed if we use a directive or for some reason need some other logic for parameters.

2022-08-02 15:44 UTC, danielleflinn commented
> my only remaining question is asking if we want the avatar to not dynamically generate a matching color any longer.

After discussing the SG-58 with the SG pod, it seems like we do want to keep the dynamically generated color if no color variable is passed in. I've updated the inputs around the avatar to reflect this: 

- Color (optional): Background color. (if no color is passed in, generate default color using ID)
- Name: use to generate the 2 initials (pass in account’s Name or Email, depending on what is available)
- ID (optional):  if no color variable, always pass in the user ID to generate default color if it is available for that avatar instance. (if user ID is not available for an avatar instance, use the Name string to generate the default color)

Size and outlined inputs remain the same as previously defined.

2022-08-03 21:27 UTC, rr-bw commented on libs/components/src/avatar/avatar.component.ts
> +
@Hinton and @danielleflinn Let me know if this captures what you were thinking with the `id`. If the `color` input is set, the avatar will use that `color` for the background color. If not, it will use the `id` input to generate the background color. If neither `color` nor `id` are given, it will use the `text`.

2022-08-03 21:29 UTC, rr-bw commented on libs/components/src/avatar/avatar.component.ts
> +    if (this.color) {
@danielleflinn and @Hinton Let me know if this captures what you were thinking with the `id`. If the `color` input is set, the avatar will use that color for the background color. If not, it will use the `id` input to generate the background color. If neither `color` nor `id` are input, it will use the `text` input. Did I get that correct?

2022-08-03 21:31 UTC, rr-bw commented on libs/components/src/avatar/avatar.component.ts
> +      svg = this.createSvgElement(this.svgSize, this.color);
@danielleflinn and @Hinton Let me know if this captures what you were thinking with the `id`. If the `color` input is set, the avatar will use that color for the background color. If not, it will use the `id` input to generate the background color. If neither `color` nor `id` are input, it will use the `text` input. Did I get that correct?

2022-08-04 09:07 UTC, Hinton commented on libs/components/src/avatar/avatar.component.ts
> +      this.color = Utils.stringToColor(this.id.toString());
Do we actually want to set the color here? That would prevent it from autoupdating on changes to id, or name.

2022-08-19 16:39 UTC, vincentsalucci commented on libs/components/src/avatar/avatar.component.ts
> +    if (this.color) {
Personally, would prefer explicit `null/undefined` conditional checks instead of relying on truthy/falsy.

2022-08-19 16:39 UTC, vincentsalucci commented on libs/components/src/avatar/avatar.component.ts
> +    } else if (this.id) {
Same here!

2022-08-22 14:07 UTC, vincentsalucci submitted a review, later dismissed
This looks good to me! @Hinton @danielleflinn will have the final approvals 👍 
(@rr-bw this will need another merge from master, however)

2022-08-23 09:04 UTC, Hinton commented on libs/common/src/misc/utils.ts
> +  // Once we are allowing org colors to be changed and saved, change this out
This comment is out of date.

2022-08-23 09:05 UTC, Hinton reviewed
This looks good to me except for that outdated comment. Thanks for iterating on this @rr-bw.

2022-08-24 21:52 UTC, vincentsalucci approved these changes

2022-08-24 22:02 UTC, danielleflinn submitted a review, later dismissed

2022-08-25 08:11 UTC, Hinton approved these changes

2022-09-06 17:38 UTC, Hinton approved these changes

2022-09-06 18:02 UTC, merged