Enable beta channel desktop release
bitwarden/clients pull request #3161
Opened 2022-07-22 10:40 UTC by michalchecinski

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [x] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Add workflow to build and publish beta desktop releases to S3 bucket.

## Code changes

- **.github/workflows/release-desktop-beta.yml:** Test mobile release

## Screenshots

## Before you submit

```
- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-07-22 10:59 UTC, Hinton commented
@michalchecinski looks like you accidentally re-added the jslib submodules. Please delete those folders.

2022-07-22 13:59 UTC, joseph-flinn requested changes
Could you remove the `jslib` submodules? I don't think we use the git submodule pattern anymore.

2022-07-22 13:59 UTC, joseph-flinn commented on .github/workflows/release-desktop-beta.yml
> +          echo "::set-output name=branch-name::$branch_name"
Can we remove the mobile specific code here and exchange it for desktop?

2022-07-25 09:44 UTC, michalchecinski commented on .github/workflows/release-desktop-beta.yml
> +          echo "::set-output name=branch-name::$branch_name"
FIxed :)

2022-07-25 13:57 UTC, joseph-flinn reviewed
It looks like the linter is unhappy with the newest changes.

2022-07-29 22:35 UTC, merged