[PS-1123] Improve hostname and domain retrieval
bitwarden/clients pull request #3168
Opened 2022-07-24 11:27 UTC by djsmith85

## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
Finally got around finishing up https://github.com/bitwarden/jslib/pull/547

Improve the retrieval and validation of hostnames and domains, which affects url matching/auto-fill

The main change is replacing `tldjs` with [tldts](https://github.com/remusao/tldts)

Newly supported scenarios:

- IPv6
- subdomains with an underscore
- Fixes a scenario where IPv4 addresses would not be returned as they got prefixed with http:// (Regex failed)
- Fully up-to-date public-suffix list instead of relying on a regex  only including the most common tld's (`Utils.tldEndingRegex`)
- Support for parsing urls with umlauts
- Better detection if a url is a website and if it's launchable from the UI (Removed `Utils.tldEndingRegex`).

Asana task: https://app.asana.com/0/1153292148278596/1201431275009049/f

Could possibly improve or fix the following issues:

- #1191
- #1621
- #2304 
- #910 (Got closed due to inactivity but was still an issue),
- Closes #2107
- Closes #2108
- Closes #2811

## Code changes

### Improving hostname and domain detection/validation
- Uninstall `tldjs` and install `tldts` as replacement
  - **package.json:**, **apps/cli/package.json:**
  - **package-lock.json:** , **apps/cli/package-lock.json:** Re-built using `npm i`

- **libs/common/spec/misc/utils.spec.ts:** Added unit tests for `Utils.getDomain` and `Utils.getHostname`
- **libs/common/src/misc/utils.ts:**
  - Replaced `tldjs` with `tldts`
  - Removed `tldEndingRegex`
  - Added check for `about:` protocol
  - Removed no longer needed IP4 regex
  - getHostname no longer uses `Utils.getUrl` internally but relies on `tldts.getHostname`
  
- **libs/common/src/misc/tldjs.noop.ts:** Deleted tldjs.noop implementation
- **apps/desktop/tsconfig.json:** Removed usage of tldjs.noop
- **apps/web/tsconfig.json:** Removed usage of tldjs.noop

### isWebsite/launch detection
- **libs/common/spec/view/loginUriView.spec.ts:** Added unit tests for getters (`isWebsite`, `launchUri`, `canLaunch`) of `loginUriView`
- **libs/common/src/models/view/loginUriView.ts:** Replaced usage of `Utils.tldEndingRegex` with improved `Utils.getDomain`

## Before you submit

```
- [X] I have checked for **linting** errors (`npm run lint`) (required)
- [X] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-08-01 19:55 UTC, MGibson1 reviewed
Looks like a straight improvement. One question before approving, though

2022-08-01 19:55 UTC, MGibson1 commented on libs/common/src/misc/tldjs.noop.ts
> -export function getDomain(host: string): string | null {
Why is this no longer required?

2022-09-25 17:29 UTC, djsmith85 commented on libs/common/src/misc/tldjs.noop.ts
> -export function getDomain(host: string): string | null {
I can't say why this was initially introduced, but with this in place on web and desktop it would actually always return the hostname instead of the domain.

I just tested this with the 2fa reports on web and it actually produces more hits with my changes. As this now grabs the domain and checks it against the list from 2fa.directory. A hostname would not match with an entry.

2022-09-26 19:36 UTC, MGibson1 approved these changes
Looks good. I'm going to tag this with `needs-qa`, but it seems like an amorphous "please test autofill" to me, do you have any better qa notes than that?

2022-09-26 19:48 UTC, djsmith85 commented
@MGibson1 Thanks for the review, I'll add some more detailed notes for QA on the ticket.

2022-10-22 07:47 UTC, djsmith85 commented
Received approval from QA, just need a quick review of the 3 last merge commits pulling in master, before merging.

2022-10-24 15:32 UTC, justindbaur requested changes
Fantastic, love the tests. I would love to have a test defining the behavior of a file protocol (i.e `file:///C:/something/form.pdf`) going through `getDomain` and `getHostname` I'd imagine it would be null but mostly just want to define our expectation with something like that.

2022-10-24 15:32 UTC, justindbaur commented on libs/common/spec/misc/utils.spec.ts
> +    it("should support urls containing umlauts", () => {
TIL what that is called.

2022-10-24 17:19 UTC, djsmith85 commented
> Fantastic, love the tests. I would love to have a test defining the behavior of a file protocol (i.e `file:///C:/something/form.pdf`) going through `getDomain` and `getHostname` I'd imagine it would be null but mostly just want to define our expectation with something like that.

Good catch with the file-schema links. I had to add some exceptions to getHostname as they were returning `C` as host.

2022-10-24 17:24 UTC, justindbaur approved these changes

2022-10-24 17:26 UTC, merged