[EC-364] Expose key getters on CryptoService
bitwarden/clients pull request #3170
Opened 2022-07-25 04:48 UTC by eliykat

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

This is branched from https://github.com/bitwarden/clients/pull/3042 to avoid adding more changes to that PR. The diff should clear up once that's merged, or compare against that branch instead in the meantime.

To be able to use the new `encryptService` methods, a caller needs to be able to get their own key if required. This PR refactors `CryptoService` to allow this, which lets us mark the old encryption methods as officially deprecated.

## Code changes

There are 2 things we need to do here:

1. get the user's encryption key:
**libs/common/src/services/crypto.service.ts**
  - make `getKeyForEncryption` public, rename to `getKeyForUserEncryption`. Naming is hard, because this could be different to the user encryption key (`encKey`)! So I went with "user encryption" as the most general term
  - mark all old encryption and decryption methods as deprecated (with info on what to do instead)

2. resolve the legacy key if required:
* **libs/common/src/models/domain/symmetricCryptoKey.ts** - add `resolveLegacyKey`, which has been moved from `CryptoService`, and stateful parts removed. It's actually faster to create a new legacy key each time we need it, rather than saving to/from StateService.
* **libs/common/src/services/crypto.service.ts** - delete `resolveLegacyKey` private method
* **libs/common/src/services/encrypt.service.ts** - move calls to `resolveLegacyKey` to here (it depends on the `IEncrypted` being decrypted, so it does need to stay close to the decryption logic)
* **libs/common/src/services/state.service.ts** - remove `legacyEtmKey` getters and setters on `StateService` as they are no longer needed (same with the abstract class, `account` class, etc)
* **libs/common/src/services/stateMigration.service.ts** - delete `legacyEtmKey` from disk storage to clean up old data

## Screenshots

## Before you submit

```
- [x] I have checked for **linting** errors (`npm run lint`) (required)
- [x] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-08-02 17:48 UTC, MGibson1 requested changes

2022-08-02 17:48 UTC, MGibson1 commented on libs/common/src/models/domain/symmetricCryptoKey.ts
> +  resolveLegacyKey(encThing: IEncrypted): SymmetricCryptoKey {
This doesn't really have to do with the key itself, it's more a combination of the encrypted thing and the key. I think this belongs as a method on the `encryptService`, personally.

2022-08-03 05:21 UTC, eliykat commented on libs/common/src/models/domain/symmetricCryptoKey.ts
> +  resolveLegacyKey(encThing: IEncrypted): SymmetricCryptoKey {
Either seems fine to me. We have very skinny models and very bloated services, so I thought it was a nice opportunity - but I don't feel strongly about it. I've moved it to `encryptService`.

2022-08-03 14:56 UTC, MGibson1 approved these changes

2022-08-03 21:09 UTC, merged