[PS-1162] Preventing escape from closing popup when vault selector is open
bitwarden/clients pull request #3195
Opened 2022-07-28 10:14 UTC by aj-rosado

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Currently when the vault selector is open and Escape key is pressed. The whole browser extension popup is closed. It should close the selector on this case.

## Code changes

- **vault-select.component.ts:** Added listener to prevent escape from closing the extension popup

## Before you submit

```
- [x] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-07-31 09:03 UTC, patrickhlauke commented
Closes https://github.com/bitwarden/clients/issues/3078

2022-08-02 18:51 UTC, MGibson1 requested changes

2022-08-02 18:51 UTC, MGibson1 commented on apps/browser/src/popup/vault/vault-select.component.ts
> +  @HostListener("document:keydown", ["$event"])
I'd prefer to attach to a specific target here
```typescript
  @HostListener("document:keydown.escape", ["$event"])
```
should do, then you can remove the `event.key` logic.

2022-08-04 11:07 UTC, MGibson1 approved these changes

2022-08-05 14:24 UTC, merged