Run client test on build
bitwarden/clients pull request #3216
Opened 2022-08-01 13:59 UTC by michalchecinski

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Execute tests for every client project

## Code changes

Add workflow to run typescript tests on pull request.

- **.github/workflows/test.yml:** Run typescript tests on pull request

## Screenshots

## Before you submit

```
- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-08-01 14:41 UTC, mimartin12 commented on .github/workflows/test.yml
> +          # cache: 'npm'
What was your thoughts on commenting this out?

2022-08-02 07:56 UTC, michalchecinski commented on .github/workflows/test.yml
> +          # cache: 'npm'
Oh it was a leftover after testing :)

2022-08-11 21:29 UTC, eliykat requested changes
This PR will run all the tests in the repository, so you can remove the `npm run test` commands in `build-browser.yml` and `build-cli.yml`, otherwise we'll be doubling up. Thanks!

2022-08-23 00:26 UTC, eliykat reviewed
@michalchecinski Looks good to me in terms of what commands you're running, but I'd prefer @mimartin12 or another devops person to do the final review so they can review the GH actions side of things.

2022-08-23 00:27 UTC, eliykat commented
PS. also looks like the workflow linter is failing.

2022-08-23 22:58 UTC, mimartin12 approved these changes

2022-08-25 08:06 UTC, eliykat approved these changes

2022-08-25 08:06 UTC, merged