[PS-1093] Move Organization Api Calls
bitwarden/clients pull request #3243
Opened 2022-08-04 18:35 UTC by justindbaur

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Move organization api methods out of `ApiService` into their own `OrganizationApiService`. This is part one of two. Part two will convert `OrganizationService` to providing observables. 

## Code changes

- Move organization api calls to `organization-api.service.ts`
- Remove usage of `any` in changed files

## Screenshots

## Before you submit

```
- [x] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-08-15 23:09 UTC, MGibson1 requested changes

2022-08-16 15:45 UTC, justindbaur commented on apps/desktop/src/app/accounts/set-password.component.ts
> +
Yep, good call. Added it!

2022-08-16 15:46 UTC, justindbaur commented on apps/web/src/app/settings/adjust-payment.component.ts
> +  formPromise: Promise<void | unknown>;
No, both the calls it holds a promise to don't actually return anything. One was returning `any` but I changed it to being `void`.

2022-08-16 15:47 UTC, justindbaur commented on apps/web/src/app/settings/tax-info.component.ts
> +}
Kinda, it's based on a response model but doesn't need some of the properties and has a few of it's own that are calculated based on other properties. I made it a `Omit` and union type to make it smaller and smarter.

2022-08-16 15:48 UTC, justindbaur commented on apps/web/src/app/vault/vault-filter/organization-filter/organization-options.component.ts
> +  actionPromise: Promise<boolean | unknown>;
Yes it's reused 3 times, twice for boolean and once for void (was `any`). I switched this to being a `boolean | void`.

2022-08-24 16:25 UTC, MGibson1 approved these changes

2022-08-24 16:33 UTC, merged