Feature/mv3 browser observable memory caching
bitwarden/clients pull request #3245
Opened 2022-08-04 20:11 UTC by MGibson1

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Lays foundations for [Manifest V3 browser Memory Caching ADR](https://adr.bitwarden.com/decisions/0007-manifest-v3-browser-memory-caching).

In addition to easy session caching, this PR adds some useful functionalities:
* Feature Flags
* Development Flags
  * These are like feature flags, but always DISABLED when in production
* Dev flag protection decorator
  * Throws if a given dev flag is not active and the method is called.
* `CachedStorageService`
  * Extends `StorageService` with a `get_bypass_cache` to force update to cache from persistent source

### Session Behavior subject syncing
Synchronizes Behavior subjects across manifest v3 contexts (service worker, popout, popup, etc) through decorators on `BehaviorSubjects` and messaging.

This has been implemented for `FolderService`.

## Code changes

### Companion changes
These changes represent updates which support features, but are not directly related to any new functionality.

 - **.eslintignore**: Ignore config.js files for various apps
 - **base/development/production.json**: Config files for dev and feature flags for browser
 - **config.js**: configurator for browser webpack initialization. 
   - copied from the other apps, we should probably just centralize this somewhere
 - **folder.service.ts**: Makes behavior subject `protected` so that a subclass in the browser app can apply decorators to them.
   - Browser subclasses `FolderService` in order to encapsulate session syncing details within the browser extension application.
 - **browserApi.ts**: static method extracted from `browserMessagingService` to avoid unnecessary dependencies in decorators, which are difficult to resolve (see how `browserSession` decorator gains access to a `StateService`).
 - **StateService**: Add methods to directly interact with memory storage in Browser implementation of StateService.
 - **LocalBackedSessionStorageService**: 
   - Implemented `AbstractCachedStorageService` to allow for bypassing of cache on session sync
   - Added development flag to not encrypt local backing on session storage. This allows for easier debugging, but should **never** be turned on in production, thus the difference between Development flags and Feature flags.

### Dev Flag
 - **dev-flag.decorator.ts**: Decorator which wraps the method on which it is applied with a guard clause to throw if the method is used without the development flag being enabled. This is useful to ensure that unsafe development flag are not being used in production environments as development flag are always false in production.
 - **dev-flag.decorator.spec.ts**: Tests for `devFlag()`

### Browser Session, Session Sync, and Session Syncer
These three classes/decorators work in concert to listen to updates both over messaging and observing BehaviorSubjects to sync their observed Subjects over different contexts. This is how it works:
- sessionSync is applied to a `BehaviorSubject` to mark it as one to sync across a given browser session and provide construction metadata for serialized observables.
- browserSession must be applied to the containing class in order to initialize `SessionSyncer`s at class construction.
  - This is required to gain access to `StateService`, which is responsible for writing state to our session storage
    - It would be great to remove the `StateService` requirement, but until we can create a `LocalBackedStorageService` with no dependencies, we need to intercept _some_ kind of injection.
    - Note: this `StateService` is specifically the browser subclass version
  - It is also required to ensure that the class contained is initalized since decorators run at definition. The only way to observe the created `BehaviorSubjects` is to run at initialization.
- SessionSyncer 
  - Observes the given `BehaviorSubject`. On next, updates session data and sends out a sync message to other `SessionSyncer`s
  - On sync message from a different `SessionSyncer`, reads data from session storage pushes a next on it's `BehaviorSubject`

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

```
- [x] I have checked for **linting** errors (`npm run lint`) (required)
- [x] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

# Draft Reason
I want to incorporate the improvements made by @eliykat in #2970.

2022-08-11 03:59 UTC, eliykat requested changes
Review in progress, here's feedback on everything except for the `Browser Session, Session Sync, and Session Syncer` changes. (leaving the fun stuff until last 😉 )

2022-08-11 03:59 UTC, eliykat commented on apps/browser/src/services/state.service.spec.ts
> +      memoryStorageService = Object.create(LocalBackedSessionStorageService.prototype);
I'd suggest adding a comment here, it took me a moment to figure out why you were doing this. (i.e. we need the right prototype chain for the sut.) At first I just thought you were trying real hard to get typed jest mocks ;)

2022-08-11 03:59 UTC, eliykat commented on apps/browser/src/services/state.service.spec.ts
> +      expect(spy).toHaveBeenCalled();
`get_bypass_cache` will also be called if you _don't_ bypass the cache. Maybe also `expect` that `memoryStorageService.get` hasn't been called?

2022-08-11 03:59 UTC, eliykat commented on apps/browser/src/services/state.service.spec.ts
> +  describe("state methods", () => {
I assume this is all just lifted & shifted?

2022-08-11 03:59 UTC, eliykat commented on apps/browser/test.setup.ts
> -const get = jest.fn();
Nice tidy up here, but was there some reason that we wanted to have the same spies in local and session storage? 🤔 (Seems bad to conflate those to imo, but thought I'd double check with you)

2022-08-11 03:59 UTC, eliykat commented on libs/common/src/models/view/folderView.ts
> +    return Object.assign(new FolderView(), key_value_pair);
You need to instantiate the `Date` object, if present (and add test).

Also, not a big deal, but inconsistent naming on the parameter (`key_value_pair` vs. `obj` used everywhere else).

2022-08-11 03:59 UTC, eliykat commented on libs/common/src/models/domain/folder.ts
> +    return Object.assign(new Folder(), obj, { name: EncString.fromJSON(obj.name) });
Also need to instantiate the date here, and add a test.

2022-08-11 03:59 UTC, eliykat commented on libs/common/src/models/domain/encString.ts
> +    return this.encryptedString;
This is not a JSON object. I think we need to `return { encryptedString: this.encryptedstring }`, similar to `SymmetricCryptoKey`. Then `fromJSON` would also need to be updated.

2022-08-11 03:59 UTC, eliykat commented on libs/common/src/models/domain/encString.ts
> -      // data and header
Nice refactor of this constructor 😁

2022-08-11 03:59 UTC, eliykat commented on libs/common/src/models/domain/encString.ts
> +    this.hydrateByEncType(encType, encPieces);
Not a strongly held opinion, but I wonder whether this is too much indirection. This method is called `initFromEncryptedString`, I think it can hold the logic currently in `hydrateByEncType` as well without passing off to another, very similarly named method.

2022-08-11 04:22 UTC, eliykat requested changes
A few minor changes while I continue to get my head around the substance of the syncing logic. Will continue tomorrow.

2022-08-11 04:22 UTC, eliykat commented on apps/browser/src/decorators/session-sync-observable/session-sync.decorator.ts
> +  ctor?: new (args: any[]) => T;
I remember seeing that type-fest has a Constructor type you may be able to use here: https://github.com/sindresorhus/type-fest/blob/main/source/basic.d.ts#L9

2022-08-11 04:22 UTC, eliykat commented on apps/browser/src/decorators/session-sync-observable/session-sync.decorator.ts
> + * \@sessionSync({ arrayInitializer: Foo.fromJSON })
This jsdoc comment seems out of date, the `BuildOptions` above refer to `initializeAsArray` instead.

2022-08-11 04:22 UTC, eliykat commented on apps/browser/src/decorators/session-sync-observable/session-sync.decorator.ts
> + * and returns your BehaviorSubject data type. `initializeAsArray can optionally be used to indicate
Not sure if `data type` is the right way to describe a `fromJSON` return value. Maybe:

```suggestion
 * and returns your instantiated BehaviorSubject value. `initializeAsArray can optionally be used to indicate
```

2022-08-11 04:22 UTC, eliykat commented on apps/browser/src/decorators/session-sync-observable/session-sync.decorator.ts
> +    const p = prototype as SessionStorable;
Why not just type `prototype` as `SessionStorable` in the parameter list?

2022-08-11 04:22 UTC, eliykat commented on apps/browser/src/decorators/session-sync-observable/browser-session.decorator.ts
> +export function browserSession<TCtor extends { new (...args: any[]): any }>(constructor: TCtor) {
I think we can use the type-fest `Constructor` type here as well.

2022-08-11 04:30 UTC, eliykat commented
Please add the Jira ticket link/number to the PR.

2022-08-11 14:03 UTC, MGibson1 commented on apps/browser/src/flags.ts
> +function getFlags<T>(envFlags: string | T): T {
`devFlagEnabled` can't be, but I can see `getFlag` being in a utils class if we want. I don't see a huge need for that since it's fairly simple.

I think the root of what you're getting at is, do we want feature flags to be all-app-level. My vote would be no atm.

2022-08-11 14:08 UTC, MGibson1 commented on apps/browser/src/services/localBackedSessionStorage.service.ts
> +  async setDecryptedLocalSession(session: any): Promise<void> {
`session` is just the name of the map stored encrypted in local storage, but intended for use at the session level.

It should be a `Record<string, unknown>`, you're right

2022-08-11 14:14 UTC, MGibson1 commented on apps/browser/src/services/localBackedSessionStorage.service.ts
> +    const jsonSession = JSON.parse(JSON.stringify(session));
We do, I was having problems with lost keys when using Chrome's built-in local storage mechanisms (due to not serializing buffer arrays). It seems they likely do not call `toJSON` methods like `JSON.stringify` does.

Apart from that, I want to emulate the storage of this object in the dev environment as closely as possible, which is through a stringify/unstringify loop.

I store it as an object instead of a string only because it's way easier to debug while stored as a real key/value pair than a JSON string. Otherwise, the JSON parse would be on the retrieval side.

2022-08-11 14:19 UTC, MGibson1 commented on apps/browser/src/services/state.service.spec.ts
> +      expect(spy).toHaveBeenCalled();
No it won't, `mockResolvedValue` is syntactic sugar for `jest.fn().mockImplementation(() => Promise.resolve(value));` and `mockImplementation` blocks the calling of the real method.

2022-08-11 14:25 UTC, MGibson1 commented on libs/common/src/models/view/folderView.ts
> +    return Object.assign(new FolderView(), key_value_pair);
I'm not sure why I had snake_case on the brain in the PR 🐍 🧠

2022-08-11 14:58 UTC, MGibson1 commented on libs/common/src/models/domain/encString.ts
> +    return this.encryptedString;
currently, our model represents `EncString` as a simple string. I don't want to change that since it will have impacts on state and require a migration.

This way, on serialization sees an `EncString` exactly as if it were a string. Wrote some tests to show this.

2022-08-11 14:58 UTC, MGibson1 commented on libs/common/src/models/domain/encString.ts
> -      // data and header
gotta get those passing Codescene tests!

2022-08-11 16:18 UTC, MGibson1 commented on apps/browser/src/services/state.service.spec.ts
> +  describe("state methods", () => {
yup, just a tab over in a new `describe`

2022-08-11 16:29 UTC, MGibson1 commented on apps/browser/src/decorators/session-sync-observable/session-sync.decorator.ts
> +    const p = prototype as SessionStorable;
🧠

2022-08-11 18:17 UTC, MGibson1 commented on libs/common/src/models/domain/encString.ts
> +    this.hydrateByEncType(encType, encPieces);
Looks like codescene still passes -- agreed

2022-08-11 22:28 UTC, eliykat commented on apps/browser/src/decorators/session-sync-observable/session-sync.decorator.ts
> +    const p = prototype as SessionStorable;
True, we're kinda making it a `SessionStorable` aren't we? Fair enough

2022-08-12 04:57 UTC, eliykat requested changes
Review done, this is really complex logic and I think you did a great job breaking it down into logical chunks, as proven by the fact that I was able to understand it. 😅

2022-08-12 04:57 UTC, eliykat commented on apps/browser/src/decorators/session-sync-observable/session-syncer.spec.ts
> +  describe("successful initialize", () => {
I have some related feedback about this test file as a whole, I decided it was better to stick it all in 1 comment than litter it throughout.

In general I think this test file needs restructuring, it's a little difficult to navigate and I think we could describe the functionality a little better. e.g. `initialization` vs. `successful initialize` is not very clear.

You're also testing some internal methods, which doesn't really prove anything about the sut other than how it's structured internally. e.g. `should call updateSession` (This is the case whether or not you make them private as I suggested in another comment, but I do think making them private highlights this.)

I also think you could drop some tests where the happy path is implicitly tested by subsequent tests. (Such as the `behaviourSubject instanceof BehaviourSubject`).

My suggestion for a reworked test suite would be something like:

```
* initialization
  * should throw if behaviorSubject is not an instance of BehaviorSubject
  * should create if either ctor or initializer is provided
  * should throw if neither ctor nor initializer is provided
  * given manifest v2
    * should not start observing
    * should not start listening
    // manifest v3 happy path is tested as part of happy path tests below
* when a value is emitted
  * should update the session memory (assert stateService call)
  * should update sessionSyncers in other contexts (assert BrowserApi.sendMessage call)
* when an update message is received from another context
  * should ignore messages with the wrong command
  * should ignore a message from itself
  * should emit the value from the behaviourSubject   // test proper construction of the object here
```

2022-08-12 04:57 UTC, eliykat commented on libs/common/spec/models/domain/encString.spec.ts
> +    it("should serialize in an object exactly like a string", () => {
This is how `JSON.stringify` works - it's called recursively. We don't need to test this.

2022-08-12 04:59 UTC, eliykat commented on apps/browser/src/flags.ts
> +function getFlags<T>(envFlags: string | T): T {
I wasn't even thinking of top-level flags, which I agree is probably not something we want. I was just thinking of not repeating code, and giving feature flag capability to all other apps in the meantime.

Looking at it again though, it's < 20 LOC and it is somewhat tied to the definition of the flags, so let's not worry about it.

2022-08-12 05:07 UTC, eliykat commented on libs/common/src/models/domain/encString.ts
> +    return this.encryptedString;
Hmm. For some reason I thought that `toJSON` had to return a JSON _object_ in the sense of `{ key: value }`, but I see that's not the case. And as proven by your test. Okie dokie!

2022-08-12 12:59 UTC, MGibson1 commented on apps/browser/src/decorators/session-sync-observable/browser-session.decorator.spec.ts
> +    new TestClass(stateService);
I think smoke tests are fine if they're in the context of a greater suite around that logic. This test is better thought of as a compliment to the one above it, `it("should throw if StateService is not a constructor argument")`.

I did add in a `.toBeDefined()`. Maybe it makes the purpose of the test a little clearer, idk.

2022-08-12 13:25 UTC, MGibson1 commented on apps/browser/src/decorators/session-sync-observable/browser-session.decorator.spec.ts
> +    it("should create a session syncer", () => {
Realized I should move this concern into the `sessionSync` decorator, so this is gone, but done and tested over there now.

2022-08-12 13:29 UTC, MGibson1 commented on apps/browser/src/decorators/session-sync-observable/session-syncer.ts
> +    }
yeah, needs to be initialized. That's why we need two decorators, too. As far as I can tell, the property decorator doesn't give you the opportunity to execute code at initialize-time, which is what we need.

What really stink about this, is that you need to initialize all of your behavior subjects in the constructor (or with defaults). That's what we do, anyways, but it limits the utility

2022-08-12 13:42 UTC, MGibson1 commented on apps/browser/src/decorators/session-sync-observable/session-syncer.ts
> +    // This may be a memory leak.
This is there in an abundance of caution. We _want_ these to be around for the entirety of the context (service worker/popup/popout/tab/sidebar) lifetime. Destroying that context destroys the memory associated with it.

I don't want to address it now, because I see not way to address it. We have nothing we can hook into at destruction time to clean up, so we have to rely on the browser to clean up our processes memory.

The comment is just a hint for the future that this is a subscription to which we are not un-subscribing.

You may also be concerned about keeping subscription items in memory during account lock or account change. However, I think this is handled by the fact that we require the use of `BehaviorSubjects` and should be `null`ing out our subject on lock etc.

2022-08-12 13:48 UTC, MGibson1 commented on apps/browser/src/decorators/session-sync-observable/session-syncer.ts
> +      : (o: any) => Object.create(metaData.ctor.prototype, Object.getOwnPropertyDescriptors(o));
That's a good point.

It sounds like you know this, but we can't call the constructor directly because we don't know what arguments are required. We could limit constructors to no parameters and require initializers otherwise:

```typescript
export interface SyncedItemMetadata {
  key: string;
  ctor?: new () => any;
  initializer?: (key_value_pair: any) => any;
  initializeAsArray?: boolean;
}
```

```typescript
return metaData.initializer != null
  ? metaData.initializer
  : (o: any) => Object.assign(metaData.ctor(), Object.getOwnPropertyDescriptors(o));
```

2022-08-12 13:48 UTC, MGibson1 commented on apps/browser/src/decorators/session-sync-observable/session-syncer.ts
> +      : (o: any) => Object.create(metaData.ctor.prototype, Object.getOwnPropertyDescriptors(o));
Realistically, I think we'll always use initializers...

2022-08-12 14:29 UTC, MGibson1 commented on apps/browser/src/decorators/session-sync-observable/session-syncer.ts
> +    if (metaData.initializeAsArray) {
My thinking was not to make assumptions on the data based on its structure. We probably could determine if it's an array and use the initializer appropriately, but if something is expecting an array to create an object, we'd behave incorrectly.

2022-08-12 14:41 UTC, MGibson1 commented on apps/browser/src/decorators/session-sync-observable/session-syncer.ts
> +  observe() {
It's public for testing, but yes, ideally it would be private.

This entire class is not public, so I'm not terribly worried about exposing this.

2022-08-12 15:02 UTC, MGibson1 commented on apps/browser/src/decorators/session-sync-observable/session-syncer.ts
> +  observe() {
You're right about all these private things, but I want them to be public for testing. These set up pretty complicated listening logic that will make the tests harder to understand.

the reason I'm OK with this the entire class is private to this module, external users of these decorators don't have access to any of this porcelain.

2022-08-12 15:02 UTC, MGibson1 commented on apps/browser/src/decorators/session-sync-observable/session-syncer.ts
> +  listenForUpdates() {
See above private comment.

2022-08-12 15:02 UTC, MGibson1 commented on apps/browser/src/decorators/session-sync-observable/session-syncer.ts
> +  async updateFromMessage(message: any) {
See above private comment.

2022-08-12 15:02 UTC, MGibson1 commented on apps/browser/src/decorators/session-sync-observable/session-syncer.ts
> +  async updateSession(value: any) {
See above private comment.

2022-08-12 15:05 UTC, MGibson1 commented on apps/browser/src/decorators/session-sync-observable/session-syncer.ts
> +  static buildFromKeyValuePair(key_value_pair: any, metaData: SyncedItemMetadata) {
See above private comment.

The reason it's static is because it can be. It's an old habit from c#, where `static` offers a perf improvement in rare circumstances so it's in the coding standards to use where you can. If it bothers, I don't really care either way.

2022-08-12 15:14 UTC, MGibson1 commented on apps/browser/src/decorators/session-sync-observable/session-syncer.spec.ts
> +  describe("successful initialize", () => {
I suppose you're right. I didn't want to have to write mocking for message listening 😢, but fine. Now that someone else called it out, I need to do it.

2022-08-12 23:40 UTC, MGibson1 commented on apps/browser/src/decorators/session-sync-observable/session-syncer.spec.ts
> +  describe("successful initialize", () => {
I've tried all day. The best I can do is to try and capture our dangling promises and test the results. We can deal with the observable side OK, but emulating the messaging infrastructure is _not_ worth it in this case.

This goes back to something that it seems we disagree on. That is whether it is appropriate to test private methods. I firmly believe that it is. In my experience the only alternatives are to either
- increase the complexity of your tests, thus making them more fragile, difficult to read, and more concerned with implementation details
- shift private methods out of your class into a different class and make them public

There are times when neither are appropriate and it's better to just test the private method. Unfortunately I don't like TypeScripts support for private method testing -- you can do it, but you have to cast everything to an `any`. Ultimately what I decided works best here is to make public, single-concern methods and test them.

I think you're probably right with some of the happy path testing I did, but I don't think we should make everything private in this case -- this is already an internal class.

2022-08-15 04:47 UTC, eliykat commented on apps/browser/src/decorators/session-sync-observable/browser-session.decorator.spec.ts
> +    new TestClass(stateService);
Yes, that makes it clearer to me, so I'm happy with that solution. You might be right generally, I'm just used to seeing explicit assertions.

2022-08-15 04:58 UTC, eliykat commented on apps/browser/src/decorators/session-sync-observable/session-syncer.ts
> +      : (o: any) => Object.create(metaData.ctor.prototype, Object.getOwnPropertyDescriptors(o));
Both of those are good solutions. I personally prefer us to always require an initializer, because that means all classes are responsible for their own initialization using a standard method name such as `fromJSON`. (There's a bit more boilerplate, but such is OOP 🤷 )

The alternative is that we have some classes handle it themselves and others don't, which seems like a far more implicit pattern which is easier for other devs to miss.

2022-08-15 05:07 UTC, eliykat commented on apps/browser/src/decorators/session-sync-observable/session-syncer.ts
> +    if (metaData.initializeAsArray) {
That's fair - I assumed we'd always create an object from a key value pair, but you're right that that's not guaranteed to be the case.

2022-08-15 05:12 UTC, eliykat commented on apps/browser/src/decorators/session-sync-observable/browser-session.decorator.spec.ts
> +    it("should create a session syncer", () => {
Nice, that is a better place for it.

2022-08-15 05:35 UTC, eliykat commented on apps/browser/src/decorators/session-sync-observable/session-syncer.ts
> +    // This may be a memory leak.
Thank you for the detailed explanation, that adds some context for me (heh).

I agree that the browser should be clearing up memory in this situation, but I'd like to you to pass some notes to QA to make sure that this is the case. (e.g. eyeball memory usage over time, ensure no regressions re: clearing items from memory.) Honestly I'm not sure what we could do if it is a problem, but given that mv3 is totally new for us, I think it would be best to check our assumptions here.

2022-08-15 05:41 UTC, eliykat commented on apps/browser/src/decorators/session-sync-observable/session-syncer.ts
> +  static buildFromKeyValuePair(key_value_pair: any, metaData: SyncedItemMetadata) {
Static is fine, I was asking more out of curiosity than anything. I kinda like it because it makes it explicit that the method doesn't rely on the class state.

2022-08-15 05:59 UTC, eliykat commented on apps/browser/src/decorators/session-sync-observable/session-syncer.spec.ts
> +  describe("successful initialize", () => {
Thank you for spending more time on this. I don't think it's never appropriate to test private methods, but it does make me ask the question. I think your point about not wanting to mock the browser messaging infrastructure is a good one, so I agree that testing the callback method (`updateFromMessage`) in this case is a good workaround.

Re: the private methods, I don't like making methods public just to test them, but I also take your point about type safety - which is probably more important on a practical level.

I like how you've refactored and laid out the tests, so no need for us to spend more time here. 👍

2022-08-15 06:01 UTC, eliykat commented on apps/browser/src/decorators/session-sync-observable/session-syncer.ts
> +  observe() {
Hmm, interesting point that it's internal to this folder. Per my comment on the `session-syncer` tests, I can see why you did this now, so given it's an internal file I won't push the point.

2022-08-15 17:07 UTC, MGibson1 commented on apps/browser/test.setup.ts
> -const get = jest.fn();
no, that was one of the reasons I changed this. I think I just didn't think through potential usages when first writing this up.

2022-08-15 17:07 UTC, MGibson1 commented on apps/browser/src/decorators/session-sync-observable/session-syncer.ts
> +    // This may be a memory leak.
fair enough, I'll add to QA testing concerns and keep an eye on it myself, as well.

2022-08-15 21:47 UTC, eliykat commented on apps/browser/src/decorators/session-sync-observable/session-syncer.ts
> +      : (o: any) => Object.create(metaData.ctor.prototype, Object.getOwnPropertyDescriptors(o));
oops, didn't realise you'd aready done this 🙈

2022-08-15 21:49 UTC, eliykat approved these changes
Good work and thanks for a productive review process 🥳

2022-08-16 12:05 UTC, merged