feat-web: add hidden char count toggle
bitwarden/clients pull request #3262
Opened 2022-08-08 22:45 UTC by mkanavakatini

## Type of change
```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Add toggle hidden character count to web vault
https://community.bitwarden.com/t/re-toggle-hidden-character-count/42641

## Code changes

- **apps\web\src\app\vault\add-edit.component.html:** toggle count button, password count display form field
- **apps/web/src/scss/pages.scss:** styles for password count form field as per [figma design](https://www.figma.com/file/6fvTDa3zfvgWdizLQ7nSTP/Numbered-Password)
- **apps/web/src/scss/variables.scss:** new color variables for updated styling
- **libs/angular/src/components/add-edit.component.ts:** toggle count functionality

## Screenshots
![image](https://user-images.githubusercontent.com/13248401/183526588-e683d95f-035b-4409-9843-6c57e33201ab.png)
![image](https://user-images.githubusercontent.com/13248401/183526559-e4e6cbba-aa40-4c8f-a9ea-a6d2bf1f1159.png)

## Before you submit

```
- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-08-08 23:01 UTC, mkanavakatini commented on apps/web/src/scss/variables.scss
> +    pwCountTextMuted: #777777,
Followed the figma design for these colors but wasn't sure about the theming.

2022-08-12 05:22 UTC, eliykat commented
Great, thank you! I'll review next week. If you happen to get to the desktop app in the meantime, feel free to add it to this PR and we can merge it all in together. But I know you're doing this in your spare time, so we can also just merge this and do desktop separately.

2022-08-16 20:48 UTC, djsmith85 commented
@mkanavakatini Thank you very much for your work on this. 

I have merged master, and added the needed changes for the desktop client.

2022-08-30 07:36 UTC, eliykat requested changes
Thanks for this! Some feedback below, please let me know if you need any help with the changes and I can help out. (or @djsmith85 if he's keen 😉)

2022-08-30 07:36 UTC, eliykat commented on apps/web/src/app/vault/add-edit.component.html
> +                    appA11yTitle="{{ 'toggleCharacterCount' | i18n }}"
This string also needs to be added to `locales/en/messages.json`. Although I think you could probably use the same string for both.

2022-08-30 07:36 UTC, eliykat commented on apps/web/src/scss/pages.scss
> +.password-wrapper {
Our web client is a bit different, we're transitioning to [Tailwind](https://tailwindcss.com/) for our styling. I'd like to avoid adding new CSS if possible. Do you mind trying to re-write these additional styles using Tailwind?

Notes:
* you have to use the `tw-` prefix for Tailwind classes in our codebase
* the Tailwind theme colours are intentionally restricted, I'll double check what colours we should be using
* see also our contributing docs: https://contributing.bitwarden.com/code-style/tailwind/

2022-08-30 07:36 UTC, eliykat commented on apps/desktop/src/app/vault/view.component.html
> +                attr.aria-label="{{ 'toggleCharacterCount' | i18n }} {{ 'password' | i18n }}"
`attr.aria-label` isn't required, as `appA11yTitle` is a wrapper for this.

2022-08-31 06:28 UTC, eliykat commented on apps/web/src/scss/pages.scss
> +.password-wrapper {
Update: here are the Tailwind theme colours to be used for the character count display:
* Numbers=primary-500 
* letters=text-main 
* background=secondary=100 
* Symbols=danger-500
*  Character count=text-main

2022-08-31 06:33 UTC, eliykat submitted a review, later dismissed

2022-08-31 06:33 UTC, eliykat commented on apps/desktop/src/scss/misc.scss
> +    color: themed("mutedColor") !important;
Design has requested that this is changed to use `#212529` (light theme) and `#FFFFFF` (dark theme) to meet accessibility standards. You may have to check whether we have any suitable scss variable, or if not, add it to `variables.scss` (which is fine in desktop, it doesn't have Tailwind).

I'd also really appreciate it if you could make the same change in browser.

2022-11-02 02:43 UTC, eliykat commented on apps/web/src/scss/pages.scss
> +.password-wrapper {
Not possible given that the pipe is shared between clients, I've just updated the colours in the SCSS. I have suggested that we make a component library component for the color password pipe though.

2022-11-02 02:46 UTC, eliykat commented
I've addressed my own feedback above, I just need to do a final self-review and test, then I'll request a review from the team.

2022-11-02 03:10 UTC, eliykat commented on apps/desktop/src/scss/variables.scss
> +    // --color-danger-500
I may have gone overboard on the SCSS changes in browser and desktop. I don't think they need to use the full TW theme, the only change required here was the `pwCountText` so it's not using a muted colour.

2022-11-09 02:00 UTC, eliykat commented on apps/web/src/app/vault/add-edit.component.html
> +              <div [innerHTML]="cipher.login.password | colorPasswordCount"></div>
Note to self: use the new CL component in #4018 once merged

2022-11-10 00:48 UTC, eliykat commented on apps/desktop/src/scss/variables.scss
> +    // --color-danger-500
I think this is fine, there is marginal difference between the colours, and it made it easier to translate into other theme variants as well. Leaving this as is.

2022-11-18 02:43 UTC, eliykat commented
@djsmith85 Can you please give this a final review? It's probably easiest to review the whole thing from scratch, but for what it's worth, the main changes are:

* updated the "count text" color in desktop & browser per design feedback. I also fixed the alternating background color in desktop. Otherwise your desktop work is unchanged I believe.
* used the CL `ColorPasswordComponent` in web - this was added in a separate PR, so we're just wiring it up here and removing unused styles
* now that the pipe is no longer shared between components, remove it from `jslib-module` and import it directly in those clients that need it
* added i18n strings that were missing
* used `bitLink` for the Hide button in web
* fixed some of the show/hide logic in web to match Figma

Desktop:
<img width="573" alt="Screen Shot 2022-11-18 at 12 14 48 pm" src="https://user-images.githubusercontent.com/31796059/202604760-a9324538-4a32-41b2-b221-38f9ca2c3ed3.png">
<img width="573" alt="Screen Shot 2022-11-18 at 12 14 37 pm" src="https://user-images.githubusercontent.com/31796059/202604774-270c0c01-a3d1-47f1-b5ca-f70590ef4d20.png">
<img width="573" alt="Screen Shot 2022-11-18 at 12 14 22 pm" src="https://user-images.githubusercontent.com/31796059/202604782-16827ccb-f073-46d9-9a9a-010ca2eee0db.png">

Web:
<img width="809" alt="Screen Shot 2022-11-18 at 12 28 49 pm" src="https://user-images.githubusercontent.com/31796059/202604818-eb2c2c42-298e-4144-a9ab-8102171883cd.png">

2022-11-23 04:02 UTC, eliykat commented
@djsmith85 The issue in dark mode is now fixed. The problem is that web isn't using the Tailwind theme all the way through. In light mode, the add-edit modal uses the normal background colour, but in dark mode it uses the "alt-2" background colour, which is also what use to alternate the password count.

Fixed by expressly setting the background of the password count component in this location:

![Screen Shot 2022-11-23 at 1 45 34 pm](https://user-images.githubusercontent.com/31796059/203467057-44f4ab90-3870-4aa1-83bd-06a38bf09475.png)

Light mode is unaffected:

![Screen Shot 2022-11-23 at 1 58 33 pm](https://user-images.githubusercontent.com/31796059/203467083-780c7649-8bc0-486a-b423-4872acc04a03.png)

2022-11-23 04:03 UTC, eliykat commented
CI is running on this branch: https://github.com/bitwarden/clients/tree/feat/char-count-web-ci

2022-11-23 12:40 UTC, djsmith85 requested changes
Changes are looking good, just some things I noticed during testing.

The desktop is missing the `colorPasswordCount` functionality on hidden custom fields(`view-custom-fields.component.html`)
This is also the case on web, but not sure if we want to solve it the same way as the regular password field (blue button above the input)

Not quite part of this, but I also noticed that we use the `colorPasswordPipe` on the password-history when called from the password-generator but not if we open the history on a cipher (`password-generator-history.component.html` vs. `password-history.component.html`)

2022-11-24 04:27 UTC, eliykat commented
I've added the character count to hidden custom fields on desktop:

https://user-images.githubusercontent.com/31796059/203694087-267437c2-c533-440e-a544-85d3526b27ca.mov

I'll ask design what they want to do about web - I think this is the only thing outstanding.

I've also used the color password display for item password history on all clients. It seems like an oversight and an easy fix while we're here.

Web:
![Screen Shot 2022-11-24 at 2 08 45 pm](https://user-images.githubusercontent.com/31796059/203694143-88e00d0a-5f7b-492f-a874-de0489702256.png)

Browser:
![Screen Shot 2022-11-24 at 2 11 25 pm](https://user-images.githubusercontent.com/31796059/203694159-a2d70add-bbbb-4b9c-b3b0-4ba2cc06fae2.png)

Desktop:
![Screen Shot 2022-11-24 at 2 15 14 pm](https://user-images.githubusercontent.com/31796059/203694179-35e8f89c-4498-4898-b983-13196de71ce4.png)

2022-11-28 14:48 UTC, djsmith85 approved these changes
I'm approving this since code and functionality are looking great. Thank you @mkanavakatini and @eliykat for working on this.

Requesting a review from @bitwarden/dept-design regarding the [open question](https://github.com/bitwarden/clients/pull/3262#pullrequestreview-1191574510) about the `colorPasswordCount` on custom hidden fields in the web-vault.

2022-11-28 15:32 UTC, danielleflinn submitted a review, later dismissed
Let's leave the counter toggle for web hidden fields off for now. If we see additional requests for it we can revisit.

2022-11-28 20:56 UTC, eliykat commented
Note: ci is passing on this branch: https://github.com/bitwarden/clients/tree/feat/char-count-web-ci after merging in the latest `master`.

2022-12-20 12:29 UTC, djsmith85 approved these changes
Received approval from QA and last commits merging master are looking good.

I'm going to add one last commit before merging, as I noticed that the label for `toggleCharacterCount` was missing for desktop, which prevents the tooltip on the button from showing.

2022-12-20 12:31 UTC, djsmith85 approved these changes

2022-12-20 12:31 UTC, merged