[CL-44] Update button disabled state
bitwarden/clients pull request #3282
Opened 2022-08-11 15:45 UTC by vincentsalucci

## Type of change
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective
> Update the `button` component's disabled states. 

## Code changes
- **button.directive.ts**: Removed base disabled styling. Added `buttonType` specific disabled states. **NOTE** ran into a strange issue with the primary border/background reporting the same color/opaque values but the attributes rendered clearly didn't match. I had to apply a custom opacity value to get the closely aligned. This could very well be user error, so I'm looking for some guidance on the issue
- **tailwind.config.base.js**: Extended the `opacity` core plugin to handle custom value

## Screenshots
![Screen Shot 2022-08-08 at 4 20 59 PM](https://user-images.githubusercontent.com/26154748/183516866-dbe9a9c1-41ca-407d-9682-cdc0e98d87b0.png)

## Before you submit
- [X] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2022-08-11 16:36 UTC, danielleflinn approved these changes

2022-09-08 00:59 UTC, eliykat reviewed
Looks pretty straightforward, just 1 question below.

2022-09-08 00:59 UTC, eliykat commented on libs/components/tailwind.config.base.js
> +      },
If this is only needed in 1 place for 1 style in 1 component, should it just be an arbitrary value rather than added to our config? e.g. `disabled:tw-border-primary-500/[0.02]`. And we can lift it up to the config if we need it in multiple places. (Or please correct me if that's already the case.)

I might be wrong on this, my understanding is just that we should avoid modifying the config for single use cases (but we should also avoid arbitrary values, so I'm not sure which is the lesser evil).

2022-09-08 14:53 UTC, vincentsalucci commented on libs/components/tailwind.config.base.js
> +      },
Great questions! Truthfully, I don't mind either approach. Putting it in the config would make it clearer that its an expected value for matching borders -> backgrounds using opacity. Even though `.02` isn't perfect its the closest I could get without feeling like it was too far off using the preset values.

2022-09-12 16:59 UTC, danielleflinn submitted a review, later dismissed

2022-09-12 18:42 UTC, Hinton requested changes

2022-09-12 18:42 UTC, Hinton commented on libs/components/src/button/button.directive.ts
> +    "disabled:tw-border-primary-500/2", // Bg + Border needed further opacity
I figured out what's going on. It's the background. We need to set so the background doesn't extend into the border, which can be done using `background-clip`.  We want `background-clip: padding`.

https://tailwindcss.com/docs/background-clip
https://developer.mozilla.org/en-US/docs/Web/CSS/background-clip

2022-09-12 20:00 UTC, vincentsalucci commented on libs/components/src/button/button.directive.ts
> +    "disabled:tw-border-primary-500/2", // Bg + Border needed further opacity
Thanks @Hinton - updated with the latest info.

2022-09-12 20:01 UTC, vincentsalucci commented on libs/components/tailwind.config.base.js
> +      },
Based on Oscar's findings, I've been able to remove the custom opacity value. 👍

2022-09-12 20:15 UTC, danielleflinn approved these changes

2022-09-13 10:02 UTC, Hinton approved these changes

2022-09-13 14:20 UTC, merged