added duckduckgo's email forwarding service 🦆
bitwarden/clients pull request #3306
Opened 2022-08-14 15:30 UTC by Dattito

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

DuckDuckGo has an awesome email forwarding service like SimpleLogin is. It also removes tracker from the emails and it is possible to answer directly like it would be a normal email. I trust DuckDuckGo more than any other service, and I find it the easiest one to use.

I want to thank them and contribute to bitwarden by helping implementing their forwarding service into the bitwarden clients.

## Code changes

Their were only a few files to be changed as the foundation of the email forwarding service was made by the other forwarding services.

- **file.ext:** Description of what was changed and why
- **generator.component.ts** Added DuckDuckGo as an option for the email forwarding services (I called it "Private Duck Address" like they did, change it if you have a better name :))
- **generator.component.html** Added the api-key field for DuckDuckGo
- **usernameGeneration.service.ts** Added the logic for calling the api to get a new email

## Before you submit

```
- [X] I have checked for **linting** errors (`npm run lint`) (required)
- [X] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-08-14 15:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitwarden/clients?pullRequest=3306) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bitwarden/clients?pullRequest=3306) before we can accept your contribution.<br/><hr/>**Dattito** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitwarden/clients?pullRequest=3306) it.</sub>

2022-08-14 15:35 UTC, Dattito commented
No idea why CodeScene complains, it definitly couldn't do anything worse as I organized the new function parallel to the functions from firefox, simplelogin etc.

2022-08-16 17:29 UTC, kspearrin requested changes
Looks good. One comment.

2022-08-16 17:29 UTC, kspearrin commented on libs/common/src/services/usernameGeneration.service.ts
> +      throw "Unknown DuckDuckGo error occurred.";
I think you can remove this since it would throw the same exception below.

2022-08-16 17:30 UTC, kspearrin commented on libs/angular/src/components/generator.component.ts
> +      { name: "Private Duck Address", value: "duckduckgo" },
Is this what the service is called or should we just call it DuckDuckGo?

2022-08-17 14:41 UTC, kspearrin commented on libs/angular/src/components/generator.component.ts
> +      { name: "Private Duck Address", value: "duckduckgo" },
After speaking with the DDG team internally, it makes more sense for this to just be labeled as DuckDuckGo. There is already context for this option as being an email forwarding service, so that should be clear.

2022-08-19 13:44 UTC, kspearrin approved these changes

2022-08-19 13:45 UTC, merged