Desktop: Change box-headers from `<div>` to semantic headings
bitwarden/clients pull request #3313
Opened 2022-08-15 22:50 UTC by patrickhlauke

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Essentially, a late port to desktop of aspects from https://github.com/bitwarden/clients/pull/2234 (which I hadn't realised at the time also affected the desktop app).

Currently, the desktop app has text that acts as a heading, but is not marked up/exposed to assistive technologies as an actual heading. This PR marks these up more appropriately as `<h2>` headings.

## Code changes

- all the various **apps\desktop\src\...component.html** files: change `<div class="box-header"> ... </div>` to `<h2 class="box-header"> ... </h2>`
- **apps\desktop\src\scss\base.scss**: tweak styles for `h1`-`h6`. set an explicit `font-size` and `font-weight` (to suppress the otherwise giant text), and remove the unnecessary theming part - these headings naturally inherit the theming from their parent container already.

## Screenshots

## Before you submit

```
- [x] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-08-16 21:41 UTC, djsmith85 requested changes
@patrickhlauke Thank you for tackling this and following up on your previous work on browser.

The changes are looking good but I found a couple more instances on your branch with a search for `<div class="box-header"`

![image](https://user-images.githubusercontent.com/2670567/184990009-93d1ab56-6ded-42a4-b906-a59b79ddb9f2.png)

Could you please check those and I'll have another look once you've updated the PR.

2022-08-17 00:52 UTC, patrickhlauke commented
@djsmith85 well spotted, those slipped me by. done

2022-08-17 09:37 UTC, djsmith85 requested changes
This is looking good, just some minor things.

2022-08-17 09:37 UTC, djsmith85 commented on apps/desktop/src/app/accounts/settings.component.html
> +          <h2 class="box-header">
This should probably be an `h1` and as with the other modals we could use `aria-labelledby=` on the root `div` to announce "App settings for 'currentUserEmail'" instead of just settings

2022-08-17 09:37 UTC, djsmith85 commented on apps/desktop/src/app/accounts/delete-account.component.html
> +          <h2 class="box-header">{{ "deleteAccount" | i18n }}</h2>
Slightly out of scope: This dialog does not use `aria-labelledby=` to announce it's heading. I suggest using `deleteAccount`

2022-08-17 09:37 UTC, djsmith85 commented on apps/desktop/src/app/accounts/environment.component.html
> +          <h2 class="box-header">
Slightly out of scope: This dialog does not use `aria-labelledby=` to announce it's heading. I suggest using `settings` or possibly introducing a new `environmentSettings` key

2022-08-17 09:37 UTC, djsmith85 commented on apps/desktop/src/app/components/password-reprompt.component.html
> +          <h2 class="box-header">{{ "passwordConfirmation" | i18n }}</h2>
Should also be a `h1` as it's the title of the newly opened modal (aria-labelledby)

2022-08-17 11:13 UTC, patrickhlauke commented
@djsmith85 yup i think a separate PR to harmonise/normalise *all* modal headings to consistently use `<h1>` and to take the same `aria-labelledby` approach makes sense. watch this space ... ;)

2022-08-17 11:17 UTC, patrickhlauke commented on apps/desktop/src/app/components/password-reprompt.component.html
> +          <h2 class="box-header">{{ "passwordConfirmation" | i18n }}</h2>
ah, now i remember...I started off last night also looking at changing all instances to `<h1>`, but got myself in a find/replace mess because it was also picking up things in the web client in my change by accident, so bailed out of that. as said, probably best to make a separate specific PR that does this across the board for all clients (didn't want to in the end overtstuff this one)

2022-08-17 20:32 UTC, patrickhlauke commented on apps/desktop/src/app/accounts/settings.component.html
> +          <h2 class="box-header">
Simpler initially to just use that heading's content as the target of the `aria-labelledby` (otherwise, we'd need to go back using `aria-label` if that text isn't present anywhere)

2022-08-17 20:33 UTC, patrickhlauke commented on apps/desktop/src/app/accounts/environment.component.html
> +          <h2 class="box-header">
Simpler initially to just use that heading's content as the target of the `aria-labelledby` (otherwise, we'd need to go back using `aria-label` if that text isn't present anywhere)

2022-08-17 20:40 UTC, patrickhlauke commented
@djsmith85 addressed changes above

2022-08-17 20:41 UTC, patrickhlauke commented on apps/desktop/src/app/components/password-reprompt.component.html
> +          <h2 class="box-header">{{ "passwordConfirmation" | i18n }}</h2>
as it was only a handful just for desktop, made the change from `<h2>` to `<h1>` for the modals here

2022-08-18 09:27 UTC, djsmith85 commented on apps/desktop/src/app/accounts/environment.component.html
> +          <h1 class="box-header" id="selfHosteEnvironmentTitle">
Ideally we should have a title here that reflects what this dialog is about (Environment settings) and then `selfHosteEnvironmentTitle` would become an h2 again.

@danielleflinn What do you think?

2022-08-18 09:28 UTC, djsmith85 approved these changes
@patrickhlauke Thank you, changes are looking good.

2022-08-18 09:28 UTC, merged

2022-08-18 09:30 UTC, patrickhlauke commented on apps/desktop/src/app/accounts/environment.component.html
> +          <h1 class="box-header" id="selfHosteEnvironmentTitle">
I think it does - assuming the custom environment bits later on are like a subset of setting up a self hosted environment?