[EC-451] Org Admin Refresh Permissions Refactor
bitwarden/clients pull request #3320
Opened 2022-08-16 21:54 UTC by shane-melton

## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

#3252 refactored the organization routing permissions which were also modified as part of the org admin refresh. This PR properly brings those changes into `feature/org-admin-refresh` branch in order to account for the new tabs.

## Code changes

- **apps/web/src/app/organizations/billing/organization-billing-routing.module.ts:** Use the new `canAccessBillingTab` callback and remove redundant guards for child routes
- **apps/web/src/app/organizations/layouts/organization-layout.component.ts:** Use the new `canAccess<Tab>` callbacks
- **apps/web/src/app/organizations/navigation-permissions.ts:** Add new `canAccess<Tab>` callbacks for the new tabs added as part of the org admin refresh. And remove unused callbacks.
- **apps/web/src/app/organizations/reporting/organization-reporting-routing.module.ts:** Use the new `canAccessReportingTab` callback and remove redundant guards for child routes

## Before you submit

```
- [X] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-08-19 04:20 UTC, eliykat requested changes
Thanks for bringing this across to the feature branch! A few comments below.

2022-08-19 04:20 UTC, eliykat commented on apps/web/src/app/organizations/navigation-permissions.ts
> +    canAccessManageTab(org)
It looks like the Manage tab has been removed as part of the refresh, if so then you can delete this function. (There is a reference to it in the `bit-web` `organization-routing.module.ts`, but that seems safe to remove given that all child routes are guarded and that'll be changed as part of this refresh anyway.)

2022-08-19 04:20 UTC, eliykat commented on apps/web/src/app/organizations/navigation-permissions.ts
> +export function canAccessMembersTab(org: Organization): boolean {
You need to update the route to use this new function (in the OSS `organization-routing.module.ts`)

2022-08-19 04:20 UTC, eliykat commented on apps/web/src/app/organizations/navigation-permissions.ts
> +export function canAccessGroupsTab(org: Organization): boolean {
You need to update the route to use this new function (in the OSS `organization-routing.module.ts`)

2022-08-22 14:55 UTC, shane-melton commented on apps/web/src/app/organizations/navigation-permissions.ts
> +    canAccessManageTab(org)
Yep it should be removed, but I had left it due to the left over reference in `bit-web`. But you make a good point that it's already guarded and will be changed as part of #3251 anyways.

2022-08-22 16:42 UTC, shane-melton commented on apps/web/src/app/organizations/navigation-permissions.ts
> +export function canAccessMembersTab(org: Organization): boolean {
Yep, good catch!

2022-08-22 23:21 UTC, eliykat approved these changes

2022-08-23 17:45 UTC, merged