Lift up feature flags to libs/common
bitwarden/clients pull request #3324
Opened 2022-08-17 06:36 UTC by eliykat

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other
```

## Objective

I need feature flags in `libs/common` to enable/disable features on a shared service.

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

```
- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-08-19 19:24 UTC, vincentsalucci commented
I've reviewed this but haven't been very involved in the feature flag development/maintenance. Would feel most comfortable with another set of eyes to review as well.

2022-08-24 16:22 UTC, MGibson1 requested changes

2022-08-24 16:22 UTC, MGibson1 commented on libs/common/src/misc/flags.ts
> +// required to avoid linting errors when there are no feature flags
Idea:
This would be a big ask, but I'd like this file to be private to utils and imported only when overriding barrel files.

This would mean you'd have to add an `index.ts` file to `utils`, and update all `utils` references to the folder rather than direct to the exporting folder.

That way, the only way to access these base flag implementations from the app-specific versions.

2022-08-24 16:22 UTC, MGibson1 commented on apps/web/src/utils/flags.ts
> +// required to avoid linting errors when there are no feature flags
This is needed only for `DevFlags`. Prefer eslint-disable-next-line to disabling a rule in a file.

2022-08-24 16:22 UTC, MGibson1 commented on libs/common/src/misc/flags.spec.ts
> +});
Please add truthy dev flag test.

2022-08-25 07:36 UTC, eliykat commented on apps/web/src/utils/flags.ts
> +// required to avoid linting errors when there are no feature flags
I want to keep this on both `Flags` and `DevFlags`, as flags are regularly added and removed and I don't want to have to add the rule back in each time.

Changed it to `disable-next-line` though.

2022-08-25 07:41 UTC, eliykat commented on libs/common/src/misc/flags.spec.ts
> +});
Like this? https://github.com/bitwarden/clients/blob/refactor/flags/libs/common/src/misc/flags.spec.ts#L43

2022-08-25 07:46 UTC, eliykat commented on libs/common/src/misc/flags.ts
> +// required to avoid linting errors when there are no feature flags
To clarify - do you mean adding `libs/common/misc/index.ts` (the `misc` folder, not `utils`), updating all references to import from that barrel file, and then have each `flags.ts` ignore the barrel file when importing the base functions and shared flags?

2022-08-25 20:07 UTC, MGibson1 commented on libs/common/src/misc/flags.ts
> +// required to avoid linting errors when there are no feature flags
ty, I did mean `misc`.

The idea is to export everything public from `misc/index.ts`, not export these flag files, that way you should get linter errors when using the wrong `flagEnabled` (the one in libs) and not the right now (the one is the app you're working in).

Of course, now that I write that a little more explicitly, it would also mean you can't use flags in libs at all. I'm OK with that, but I believe you wanted to do this specifically so you could.

2022-08-25 20:08 UTC, MGibson1 commented on libs/common/src/misc/flags.spec.ts
> +});
nope, more like

```typescript
    it("returns true if truthy", () => {
      process.env.DEV_FLAGS = JSON.stringify({
        devHack: {key: 3},
      });

      expect(devFlagEnabled<any>("devHack")).toBe(true);
    });
```

2022-08-25 20:12 UTC, MGibson1 requested changes
responded to comments

2022-08-25 20:19 UTC, eliykat commented on libs/common/src/misc/flags.ts
> +// required to avoid linting errors when there are no feature flags
I understand - but you're right that I wanted to use `libs/common/misc/flags.ts` directly within `libs`, so I don't think we can make it private in the way you're describing.

I've updated the jsdoc comment to provide some guidance, but I think that's all we can do.

2022-08-25 20:21 UTC, eliykat commented on libs/common/src/misc/flags.spec.ts
> +});
Oh nice one - done (ty for the code snippet ;) )

2022-08-25 20:40 UTC, MGibson1 approved these changes

2022-08-26 03:00 UTC, eliykat commented
Desktop builds are failing due to an earlier PR. Given that it's unrelated to this PR, I'm merging this and will submit a separate PR to fix.

2022-08-26 03:00 UTC, merged