[PS-1282] Enable Arabic language support for desktop, browser, web
bitwarden/clients pull request #3333
Opened 2022-08-18 16:13 UTC by djsmith85

## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Thanks to our amazing community over at [Crowdin](https://crowdin.com/project/bitwarden-web) we can now add the Arabic language to our clients.

If you also want to get involved with more supported languages or improving our existing translations, please have a look at our [Contributing Guidelines](https://contributing.bitwarden.com/contributing/#localization-l10n)

Tagging @dwbit for visibility

## Code changes

- **libs/common/src/services/i18n.service.ts:** Register Arabic language with native name, which will be shown in the language dropdown if available in the client.

- Register with browser
  - **apps/browser/src/services/i18n.service.ts:** Add `ar` as supported language
  - **apps/browser/src/popup/app.module.ts:** Register Angular language module

- Register with desktop
  - **apps/desktop/src/services/i18n.service.ts:** Add `ar` as supported language
  - **apps/desktop/src/app/app.module.ts:** Register Angular language module

- Register with web
  - **apps/web/src/app/core/i18n.service.ts:** Add `ar` as supported language
  - **apps/web/src/app/shared/locales.ts:** Register Angular language module

## Before you submit

```
- [X] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-08-24 16:05 UTC, MGibson1 requested changes

2022-08-24 16:05 UTC, MGibson1 commented on apps/browser/src/popup/app.module.ts
> +registerLocaleData(localeAr, "ar");
Why are we missing "af" from this project?

2022-08-25 09:12 UTC, djsmith85 commented on apps/browser/src/popup/app.module.ts
> +registerLocaleData(localeAr, "ar");
We currently do not have support for Afrikaans in our [Crowdin-browser-project](https://crowdin.com/project/bitwarden-browser)

2022-08-29 17:28 UTC, MGibson1 approved these changes

2022-09-05 19:18 UTC, merged