Add folder to item view
bitwarden/clients pull request #3347
Opened 2022-08-20 22:38 UTC by patrickhlauke

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Currently, the item view does not give any indication if the item is in a folder or not. This PR adds a discreet "Folder: ..." listing at the bottom of the item, above the creation/update time.

## Code changes

- **apps\browser\src\popup\vault\view.component.html**: add "Folder:..." text at the end of the item view

## Screenshots

![A test item in the popup's item view, showing the new 'Folder: ...' text above the 'Updated: ...'](https://user-images.githubusercontent.com/895831/185768318-79297191-dbda-4c89-ad57-cea0ee96165d.png)

## Before you submit

```
- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-08-20 22:40 UTC, patrickhlauke commented
@djsmith85 my angular skills/understanding of how the codebase is organised here fail me ... I can grab the folder id, but not sure how to now grab the actual text/name of the folder. something involving `folders$`, but not quite sure how to grab/populate that. any chance you could point me in the right direction, or maybe get somebody to collab with me on this?

2022-08-28 23:48 UTC, patrickhlauke commented
also pinging @Hinton just in case he knows :)

2022-08-29 08:31 UTC, Hinton commented
@patrickhlauke you should be able to grab the folder from the id using something like
```ts
const folder (await firstValueFrom(this.folderService.folderView$)).find(f => f.id == <id>);
```

2022-08-29 10:25 UTC, patrickhlauke commented
@hinton sadly, my lack of angular knowledge now means i have zero idea where to slot that in...possibly bitten off more than i can chew here.

2022-08-29 12:13 UTC, Hinton commented
Hmm, one solution would be to add a `folder` field to `libs/angular/src/components/view.component.ts` called `folder`, and fetching it in `load` after `cipher.decrypt`.

```
this.folder (await firstValueFrom(this.folderService.folderView$)).find(f => f.id == <id>);
```

That would also allow you to use it in the other clients. The folderService would need to be added as a constructor argument.

2022-09-08 16:24 UTC, patrickhlauke commented
incidentally, while this is not ready yet (not found the time to actually work out how to do this last bit of getting the actual folder name), wondering if @danielleflinn thinks this stands a chance to make it into the product as well (as it's adjacent to something like https://github.com/bitwarden/clients/pull/3181)?

2022-09-08 19:16 UTC, sukhleenb commented
Hey Patrick! We do think including the folder name will be valuable data to display on this page. Since we’re looking into adding the Created date (# [3181](https://github.com/bitwarden/clients/pull/3181)), we’re leaning towards displaying the folder name in a slightly different pattern.  

Let me know if you’d like to change your PR to reflect the changes shown in the screenshot (folder name form field UI beneath the website field). If the item does not exist in a folder, we just wouldn't show that field. 

![Screen Shot 2022-09-08 at 12 13 46 PM](https://user-images.githubusercontent.com/95638650/189206926-5e763bed-311f-4f19-a6c6-e057fe4bbc96.png)

2022-09-08 19:51 UTC, patrickhlauke commented
> Created date (# https://github.com/bitwarden/clients/pull/3181), we’re leaning towards displaying the folder name in a slightly different pattern.

>
> Let me know if you’d like to change your PR to reflect the changes shown in the screenshot (folder name form field UI beneath the website field).

yup, looks good. was initially aiming at the most minimal UI change, but if you're happy with the more obvious one shown in that screenshot, I'll go for something like it (once I worked out the missing bit of how to get the actual human-readable folder name)

2022-09-09 23:15 UTC, patrickhlauke commented
with thanks to @Hinton for putting me on the right track (though it still needed a lot of trial and error on my part), this is now ready for review :)

2022-09-09 23:51 UTC, patrickhlauke commented
if https://github.com/bitwarden/clients/pull/3321 gets merged first, this will also need to have the drag-n-drop bit added

2022-09-13 20:11 UTC, patrickhlauke commented
> if #3321 gets merged first, this will also need to have the drag-n-drop bit added

done

2022-09-13 22:58 UTC, patrickhlauke commented
Updated to use `<label>` / `<input type="text" readonly>` (in anticipation of https://github.com/bitwarden/clients/pull/3485)

2022-09-25 11:03 UTC, djsmith85 requested changes
@patrickhlauke Thank you for your contribution. Just some minor things I've noticed.

2022-09-25 11:03 UTC, djsmith85 commented on libs/angular/src/components/view.component.ts
> +
We should add a if-condition to only fetch the folderName when the folderId is present/filled.

2022-09-25 12:46 UTC, patrickhlauke commented
Thanks @djsmith85 ... I'll have a look at all the above comments in a moment :+1:

2022-09-25 23:26 UTC, patrickhlauke commented on libs/angular/src/components/view.component.ts
> +
Done

2022-09-25 23:26 UTC, patrickhlauke commented on apps/browser/src/popup/vault/view.component.html
> +          for="folder"
Oops. fixed

2022-09-25 23:26 UTC, patrickhlauke commented on apps/browser/src/popup/vault/view.component.html
> +        <input id="FolderId" type="text" name="folderId" [value]="folder.name" readonly />
Done

2022-09-25 23:34 UTC, djsmith85 requested changes

2022-09-25 23:34 UTC, djsmith85 commented on apps/browser/src/popup/vault/view.component.html
> +        <input id="folderName" type="text" name="folderId" [value]="folder.name" readonly />
@patrickhlauke Thanks for updating the PR. I think we should still change the name-attribute. The element id is looking good.

2022-09-25 23:46 UTC, patrickhlauke commented on apps/browser/src/popup/vault/view.component.html
> +        <input id="folderName" type="text" name="folderId" [value]="folder.name" readonly />
Done

2022-09-26 00:06 UTC, djsmith85 approved these changes
@patrickhlauke This is looking good. Thanks again for you contributions.

I'll pass this on to QA and once they've given their approval I'll get this merged into master.

2022-10-19 23:11 UTC, djsmith85 commented
@patrickhlauke I've received approval from QA and this is ready to get merged. Thank you for your work on this.

2022-10-19 23:12 UTC, djsmith85 approved these changes

2022-10-19 23:12 UTC, merged