[SM-63] Display dates based off Figma
bitwarden/clients pull request #3358
Opened 2022-08-22 21:09 UTC by Thomas-Avery

## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

The purpose of this PR is to fix displaying dates in the secrets list overview.
The dates were not being displayed as requested in the Figma examples.

This is dependent on the server side change in https://github.com/bitwarden/server/pull/2206

## Code changes

bitwarden_license/bit-web/src/app/sm/secrets/secrets-list.component.html
Sending the date to the angular date pipe for formatting and localization.

## Screenshots

![image](https://user-images.githubusercontent.com/43214426/186019190-b67dfaa5-09e6-4b34-a8cc-c08e0a92e230.png)

## Before you submit

```
- [X] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-08-22 21:39 UTC, Hinton requested changes

2022-08-22 21:39 UTC, Hinton commented on bitwarden_license/bit-web/src/app/sm/secrets/secrets-list.component.html
> +      <td bitCell>{{ secret.revisionDate | date: "MM/dd/yyyy hh:mm a" }}</td>
Please do not use a hardcoded format. We use `medium` in a couple of places and that seems to be roughly equivalent.

2022-08-22 21:51 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/sm/secrets/secrets-list.component.html
> +      <td bitCell>{{ secret.revisionDate | date: "MM/dd/yyyy hh:mm a" }}</td>
resolved in https://github.com/bitwarden/clients/pull/3358/commits/ad940430d06f332e3901ec1e31b7398acad2b001

2022-08-22 21:56 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/sm/secrets/secrets-list.component.html
> +      <td bitCell>{{ secret.revisionDate | date: "MM/dd/yyyy hh:mm a" }}</td>
Short looks to be the most similar. 

`6/15/15, 9:03 AM`

vs the requested 
`06/15/2015 9:03 AM`

2022-08-23 08:25 UTC, Hinton commented on bitwarden_license/bit-web/src/app/sm/secrets/secrets-list.component.html
> +      <td bitCell>{{ secret.revisionDate | date: "MM/dd/yyyy hh:mm a" }}</td>
Checking with design if the intention was to use short, it's not used in any other places.

2022-08-24 14:08 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/sm/secrets/secrets-list.component.html
> +      <td bitCell>{{ secret.revisionDate | date: "MM/dd/yyyy hh:mm a" }}</td>
Resolved in https://github.com/bitwarden/clients/pull/3358/commits/17896fd664d7c455ccb8f78f610a983fe7bc602a

2022-08-26 16:16 UTC, Hinton approved these changes

2022-08-29 15:13 UTC, merged