[CL-27] [EC-455] Ng-Select Integration
bitwarden/clients pull request #3383
Opened 2022-08-25 20:09 UTC by vincentsalucci

## Type of change
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective
> Integrate/wrap the `ng-select` library as a `Component Library` component for use between projects.

## Code changes
- **libs/components/src/index.ts**: Added `./multi-select` component to barrel file
- **libs/components/src/multi-select/index.ts**: Exported necessary parts of the `multi-select` functionality
- **libs/components/src/multi-select/models/selectItemView.ts**: Created `SelectItemView` to be used for handling necessary data within the `ng-select` component. As of right now, this only supports the data types used within the `Manage Organization` flows.
- **libs/components/src/multi-select/multi-select.component.html**: Created component layout. Passed in all necessary variables and created custom templates to match mocks.
- **libs/components/src/multi-select/multi-select.component.ts**: Created corresponding component class. Handles multi-select scenarios and defaults to our implementation. Was very explicit with comments as this class works with the `ng-select` library and its API. We diverged a bit from standard use with how we collect the final selections. 
- **libs/components/src/multi-select/multi-select.module.ts**: Created module for use of the `MultiSelectComponent`
- **libs/components/src/multi-select/multi-select.stories.ts**: Created stories depicting the usage for our current manage organization use cases: `Groups` `Members` `Collections` `Members and Groups`
- **libs/components/src/multi-select/scss/bw.theme.scss**: Created customized `bitwarden` theme. I've left verbose comments about the selections. Other than base colors, I did not change much else and built the corresponding layouts with the default stylings.
- **libs/components/src/styles.scss**: Added import for the new theme and update existing references as according to [this](https://webpack.js.org/loaders/sass-loader/#resolving-import-at-rules)
- **package.json**: Installed the latest version of `ng-select`

## Screenshots
![0-multi-select-dual](https://user-images.githubusercontent.com/26154748/186753883-efa33a88-3090-4963-99ce-83da9e7b5a3e.png)

## Design Departures
- The only real difference between the mocks and this implementation is the nested collection. I've opted to using the `ng-select: groupBy` API instead of trying to craft our own. Below is a screenshot of the visual implementation:

![1-multi-select-groupBy](https://user-images.githubusercontent.com/26154748/186756406-a4b25413-c58d-4de5-a044-9678081c4ab0.png)

## Remaining Issues/Quirks
- @Hinton: when using `ngModel` to bind our returned list of selected items, we're also required to supply a `name` field (per angular). Right now I just have a hardcoded string to suppress the error. What's the best approach here?
- @Hinton: I ran a quick test using the `UserGroupsComponent` and ran into an interesting problem: hitting enter in the dialog would end up triggering the `submit` action of the dialog (which would also close the dialog) while also closing the list and enacting our `onItemsConfirmed` emitter. Is this a setting for dialogs? Or might we need to reconsider our flow for selecting items within the `ng-select` component?
- @danielleflinn: Using the `groupBy` API results in the collection list being "out of order" when compared to the mocks. It appears the listing will put un-grouped items first and then do the grouped items. Is this a deal breaker? Another question is in regards to the screenreader TTS when we confirm selected items: I'm unsure of how we control that and am looking for some guidance there.
- The final note is that this component has been specifically coded to work with the `multipleSelection` option `enabled`. If we have plans for introducing/using this with `single` selection, we'll need to make some changes to the existing code.

## Before you submit
- [X] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2022-08-26 16:13 UTC, Hinton commented on libs/components/src/multi-select/scss/bw.theme.scss
> +@mixin rtl {
Should we add a note that this is copied from ...

2022-08-30 21:12 UTC, vincentsalucci commented on libs/components/src/multi-select/scss/bw.theme.scss
> +@mixin rtl {
The `default.theme.scss` file (origination of this custom theme class) within the `@ng-select` library imports `mixins` but I wasn't able to successfully import it without breaking all the styles. Do you know of a better approach than just manually brining in the `mixin` from the specified file?

2022-09-01 16:49 UTC, Hinton commented on libs/components/src/multi-select/scss/bw.theme.scss
> +@mixin rtl {
I was more thinking of adding a note to this file that it's copied from `https://github.com/ng-select/ng-select/blob/master/src/ng-select/themes/default.theme.scss`

2022-09-01 16:53 UTC, vincentsalucci commented on libs/components/src/multi-select/scss/bw.theme.scss
> +@mixin rtl {
Oh - sorry for misunderstanding. Yes, I can do that for sure.

2022-10-04 12:11 UTC, coroiu commented
`Retrieving options` text color does not match figma

![image](https://user-images.githubusercontent.com/2285588/193815990-18756af2-9669-4278-9dc5-4821b54b0175.png)

![image](https://user-images.githubusercontent.com/2285588/193816038-56c61d01-c2b6-46e6-9bc2-19afc8fc68cd.png)

2022-10-04 12:18 UTC, coroiu commented
Icons does quite match figma. Different color and size, and the centering seems a bit off

![image](https://user-images.githubusercontent.com/2285588/193816999-43dc2104-718e-4c50-8eab-30c71136ea4b.png)

![image](https://user-images.githubusercontent.com/2285588/193817224-383f3936-ca4a-43d5-b69b-d342f5683264.png)

2022-10-04 12:20 UTC, coroiu reviewed
Behavior feels good, comments (code and design) are mostly smaller nitpicks. I worked on this myself so I'm not sure if should be the one that approves it

2022-10-04 15:52 UTC, danielleflinn requested changes
Can we change the hover style on the clear icon from the danger color to text-main? 

I'm ok with the style changes that are inconsistent with Figma mentioned above (text coloring for retrieving options and the icon difference from Figma–I think we already discussed we are limited with that icon); would be nice if we could fix the alignment of the clear icon with the drop down like @coroiu pointed out.

I don't see a story in Storybook for if the field can be displayed with hint text. Can you confirm hint text can be displayed with the field?

2022-10-04 18:50 UTC, vincentsalucci commented on libs/components/src/input/input.directive.ts
> +  }
Absolutely. Updated.

2022-10-04 18:51 UTC, vincentsalucci commented on libs/components/src/form-field/form-field.component.ts
> +  @ContentChild(NgControl) ngControl: NgControl;
Removed.

2022-10-04 19:19 UTC, vincentsalucci commented on libs/components/src/multi-select/multi-select.component.ts
> +  protected notifyOnTouched?: () => void;
Correct! Updated.

2022-10-04 19:39 UTC, vincentsalucci commented on libs/components/src/multi-select/multi-select.component.ts
> +  clearSearchOnAdd = true;
Before the final designs, I made all of these options `Inputs` in order for customization. But once we standardized our usage, I remove the `Input` option but left them in the code. Locking these down in `html` should be fine for now. 👍

2022-10-04 20:27 UTC, vincentsalucci commented on libs/components/src/multi-select/multi-select.component.ts
> +  clearSearchOnAdd = true;
Updated.

2022-10-05 15:54 UTC, vincentsalucci commented on libs/components/src/multi-select/multi-select.component.html
> +  [clearSearchOnAdd]="clearSearchOnAdd"
Originally I didn't use it but it has since been moved to a nice `shared.module` and I've replaced a couple of references you mentioned to clean up the component a little bit. 👍

2022-10-05 19:44 UTC, vincentsalucci commented
> Can we change the hover style on the clear icon from the danger color to text-main?
> 
> I'm ok with the style changes that are inconsistent with Figma mentioned above (text coloring for retrieving options and the icon difference from Figma–I think we already discussed we are limited with that icon); would be nice if we could fix the alignment of the clear icon with the drop down like @coroiu pointed out.
> 
> I don't see a story in Storybook for if the field can be displayed with hint text. Can you confirm hint text can be displayed with the field?

* Adjusted the clear hover color to `text-main`
* Correct, both the clear all icon and the dropdown arrow can not be customized.
* I've added hints to all of the multi-select stories 👍

2022-10-05 20:25 UTC, vincentsalucci commented on libs/components/src/form-field/multi-select.stories.ts
> +const formObj = fb.group({
Neeeeeeat! Updated to use this approach. Thank you :D

2022-10-05 21:07 UTC, vincentsalucci commented on libs/components/src/form-field/form-field.module.ts
> +  imports: [SharedModule],
Hmmmm. So originally this was removed due to a cyclic dependency that was occurring during the transition to the `BitFormFieldControl`. But after throwing the `InputModule/Directive` back in and also including `MultiSelectModule/Component`, I'm not seeing any issues and I believe this will alleviate the issue mentioned above 👍

2022-10-05 21:26 UTC, vincentsalucci commented on libs/components/src/multi-select/multi-select.component.ts
> +    this.placeholder = this.placeholder ?? this.i18nService.t("multiSelectPlaceholder");
Absolutely. Thanks for the reminder - added!

2022-10-05 21:26 UTC, vincentsalucci commented on libs/components/src/multi-select/multi-select.component.ts
> +    const key = Object.keys(this.ngControl.errors)[0];
Safety first!

2022-10-05 21:45 UTC, shane-melton commented on libs/components/src/multi-select/multi-select.component.ts
> +    const key = Object.keys(this.ngControl.errors)[0];
There's just one last one  here:
```suggestion
    const key = Object.keys(this.ngControl?.errors)[0];
```

2022-10-05 22:18 UTC, shane-melton commented on libs/components/src/form-field/form-field.module.ts
> +  imports: [SharedModule],
That should work, only thing that slightly bothers me still (and I could be wrong about this) is that we're explicitly re-exporting the _**individual**_ directive/components in the `FormFieldModule` instead of re-exporting the `InputModule` and `MultiSelectModules` themselves. Exporting the modules themselves lets each module handle/control what is publicly exported and doesn't require updating the exports in both places should a new component/directive be added. 

Currently, if a new directive were to be added to the `InputModule` we'd have to export it there and again in `FormFieldModule`.

2022-10-05 22:32 UTC, danielleflinn commented
Testing the keyboard navigation with this again; it looks like there isn't a way for the user to get to the 'clear' icon. Is there an option to make that keyboard accessible?

2022-10-06 07:06 UTC, coroiu commented on libs/components/src/form-field/form-field.module.ts
> +  imports: [SharedModule],
Also do we actually need to re-export at all? If we want to export for convenience then maybe we should create a common module for it eg. `BitFormsModule` instead of using `FormFieldModule` for this

2022-10-06 07:10 UTC, coroiu commented on libs/components/src/multi-select/multi-select.component.html
> +  clearAllText="{{ 'multiSelectClearAll' | i18n }}"
**suggestion(non-blocking):** this is the same as `[notFoundText]="'multiSelectNotFound' | i18n". Feel free to ignore this comment :D

2022-10-06 16:40 UTC, vincentsalucci commented on libs/components/src/multi-select/multi-select.component.html
> +  clearAllText="{{ 'multiSelectClearAll' | i18n }}"
Ahhh. Thanks for the info! I just used the pattern found most often when piping strings.

:themoreyouknow:

2022-10-06 16:44 UTC, vincentsalucci commented on libs/components/src/form-field/form-field.module.ts
> +  imports: [SharedModule],
I don't have a great answer here except I was preserving the pattern that @Hinton had initially put in place in which I'm assuming the `FormFieldModule` is the host for our form related elements and exporting the specific directive/component (respectively) within this module specifically would accomplish that.

2022-10-06 17:26 UTC, shane-melton commented on libs/components/src/form-field/form-field.module.ts
> +  imports: [SharedModule],
Both methods have the same end result, it just seemed slightly redundant to me. But, there very well may be a legitimate reason for why @Hinton did it that way originally with `FormFieldModule` that I'm just not familiar with. 

Either way, I don't believe this needs to necessarily hold up merging the PR as the original breaking issue of the missing `InputModule` has been fixed.

2022-10-06 17:31 UTC, shane-melton commented on libs/components/src/multi-select/multi-select.component.ts
> +    this.ngControl = !this.standalone ? this.injector.get(NgControl) : null ?? null;
I think we could get away without the `standalone` input property if we pass the `Optional` flag to the `injector.get()` method. That way it won't throw a bunch of console errors if the control isn't available.

```ts
this.injector.get(NgControl, null, InjectFlags.Optional);
```

However, I also see that `InjectFlags` seems to have been [prematurely deprecated from this issue.](https://github.com/angular/angular/issues/47164#issuecomment-1216412333)

2022-10-06 20:52 UTC, vincentsalucci commented on libs/components/src/multi-select/multi-select.component.ts
> +    this.ngControl = !this.standalone ? this.injector.get(NgControl) : null ?? null;
@shane-melton I reverted this change per our conversation and have injected `ngControl` and assigned the component context as the value accessor.  This also allowed me to remove the `Provider` as well. Thanks for the info!

2022-10-06 20:55 UTC, shane-melton commented on libs/components/src/multi-select/multi-select.component.ts
> +    this.ngControl = !this.standalone ? this.injector.get(NgControl) : null ?? null;
Great!

2022-10-07 17:31 UTC, shane-melton submitted a review, later dismissed
This looks good to me, nice work!

I do see there is still a bit of active discussion about accessibility, but I wanted to go ahead and approve for the dev group.

2022-10-10 07:08 UTC, coroiu commented on libs/components/src/form-field/form-field.module.ts
> +  imports: [SharedModule],
Fair point, we'll probably have multiple opportunities to revisit this in the future. Maybe send a DM to @Hinton directly to ask about it and then just do what you feel is best, that's my opinion! Either way I'll consider this issues solved from my side :)

2022-10-10 07:10 UTC, coroiu submitted a review, later dismissed

2022-10-10 22:13 UTC, vincentsalucci commented
@danielleflinn - The latest build will now announce both the label and hint/error as expected 👍 
@shane-melton @coroiu - Sorry for the dismissal, but I believe we're in a good state!

2022-10-10 22:20 UTC, danielleflinn submitted a review, later dismissed
Looks and sounds great with VoiceOver. Thank you @vincentsalucci for all your hard work on this!

2022-10-10 22:22 UTC, shane-melton submitted a review, later dismissed
LGTM!

2022-10-10 22:42 UTC, shane-melton approved these changes
Take two haha

2022-10-11 12:49 UTC, merged