[EC-499] Add encryptService to domain model decryption
bitwarden/clients pull request #3385
Opened 2022-08-25 23:38 UTC by eliykat

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

We recently pulled out encryption/decryption methods to `EncryptService`. This is because `CryptoService` depends on `StateService`, but we need to do decryption in contexts where the main application state is not available. (e.g. Web workers, Manifest v3 workers.)

We now need to make sure that this method is actually used when decrypting vault items.

The current call to `CryptoService` is nested deep in `EncString` - this is what's called when decrypting vault items. We need to shortcut this where a key is provided, so that we can use the new `EncryptService` methods in different contexts.

I'll say upfront - `ContainerService` is a bad pattern, having decryption logic in `EncString` is a bad pattern, and here we're extending this pattern further. I don't love it. But this is a big problem to solve, there's already a tech debt ticket for it [here](https://bitwarden.atlassian.net/browse/TDL-11), and I've already done a lot of refactoring in the course of this epic. I thought solving this particular tech debt problem was out of scope.

## Code changes

- **libs/common/src/services/container.service.ts** - add `EncryptService` here and add checks + throws in these getter methods (moved from `EncString`)
- **libs/common/src/misc/utils.ts** - add a getter method for `ContainerService` so that we can add the check + throw here if `ContainerService` isn't initialised (also moved from `EncString`)
- *libs/common/src/models/domain/encString.ts* - instead of calling `CryptoService.decryptToUtf8` (which gets the key and then calls `EncryptService`), we get the key ourselves and give it to `EncryptService`. It's exactly the same series of steps. But - it means that we only get the key if none is provided. This maintains backwards compatibility while allowing us to avoid `CryptoService` if we want.

Once you understand that, you'll see that I've repeated the same pattern for `attachment.ts`, which has similar logic, updated the `BitwardenContainer` constructor calls, and updated tests.

## Screenshots

## Before you submit

```
- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

2022-08-29 21:53 UTC, MGibson1 requested changes

2022-08-29 21:53 UTC, MGibson1 commented on libs/common/src/models/domain/attachment.ts
> +      // TODO: error?
This feels nuts. Can we not just see if the orgId is provided?

Do we always provide a string and just expect that if the org is not found it's a personal?

We at least know if a Cipher is an organization one, we should jsut use that to dictate the flow we take.

2022-08-29 21:53 UTC, MGibson1 commented on libs/common/src/models/domain/send.ts
>        model.key = await cryptoService.decryptToBytes(this.key, null);
Is `this.key` maybe null? if not, we should use encrypt service, here.

2022-08-29 21:53 UTC, MGibson1 commented on libs/common/src/services/container.service.ts
> +      throw new Error("ContainerService.cryptoService not initialized.");
copy-paste mistake
```suggestion
      throw new Error("ContainerService.encryptService not initialized.");
```

2022-08-30 05:08 UTC, eliykat commented on libs/common/src/models/domain/attachment.ts
> +      // TODO: error?
You're right, I was just being cautious in case there was some weird behaviour I wasn't accounting for here. But really, if it's not an org cipher then `orgId == null` and we should just get the user key directly.

2022-08-30 05:15 UTC, eliykat commented on libs/common/src/models/domain/send.ts
>        model.key = await cryptoService.decryptToBytes(this.key, null);
`this.key` is the `EncString` being decrypted. The user's key for decryption is never passed in here (it's the `null` argument in this call), so we'll always need to get the key from a service.

2022-08-30 05:32 UTC, eliykat commented
@MGibson1 I noticed that as a result of these changes, any error thrown in `cryptoService.getOrgKey` or `cryptoService.getKeyForUserEncryption` will not be caught and will abort the whole vault decryption. Previously these calls were in the try/catch block. In practice I'm not sure what the risk is here, but given that the result is effectively crashing the whole app, I thought it was best to catch these errors.

Ideally we'd log any decryption errors to console, but that could spam the console with hundreds and hundreds of log statements, so I'm not sure about that.

2022-08-31 13:57 UTC, MGibson1 commented on libs/common/src/models/domain/attachment.ts
> +      // TODO: error?
My thinking was the reason we were doing the weird orgId if available stuff was because previously the key was being pulled from cryptoService without the cipher context. Once we pull it out, it makes sense to start being more reasonable with the logic, right?

2022-08-31 14:28 UTC, MGibson1 requested changes
Can you add a [jsdoc @throws](https://jsdoc.app/tags-throws.html) on the method that's causing these try/catches?

2022-09-01 04:35 UTC, eliykat commented on libs/common/src/models/domain/encString.ts
> +      console.error(e);
Gah! alright, I'll just remove it - it wasn't the main purpose of this PR anyway. We can have better logging when we get rid of container service.

2022-09-01 04:58 UTC, eliykat commented
There were some try/catches already here, around the `cryptoService.decryptToUtf8` call. I presume these were to catch whatever might go wrong during decryption, e.g. a mac failure, corrupted data, etc. The starting point is that I want to maintain that error handling.

Because `cryptoService` got its own keys, that also used to catch any errors in retrieving the keys. Now that we've pulled the key getter methods out, I still want to make sure those calls are also covered by the try/catch, for the same reason.

I am being cautious here because an error thrown at this stage will, if not caught, abort decryption of the whole vault and basically make the app unusable.

2022-09-02 00:47 UTC, MGibson1 approved these changes

2022-09-02 01:15 UTC, merged