Ec 497 fix memory leaks in tests
bitwarden/clients pull request #3421
Opened 2022-08-31 03:45 UTC by eliykat

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [x] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

There is a bug in node, or Jest, or ts-jest, causing tests to leak memory. See this issue thread and this comment specifically for more information: https://github.com/kulshekhar/ts-jest/issues/1967#issuecomment-994916049

There are various workarounds, and I previously added the `maxWorkers: 3` option to avoid it crashing CI altogether. That has worked so far in some but not all cases. It still uses lots of heap memory and can overflow depending on the weather, day of the week, etc.

One recommended option is to use `isolatedModules: true` (for ts-jest, [see docs](https://huafu.github.io/ts-jest/user/config/isolatedModules)), which reduces heap usage to about 30% of normal levels (from ~3gb to just under 1gb), but removes typechecking.

This PR enables that option, and then runs some manual typechecking on test files in `libs/`. This is because test code in each `apps/` folder, and all production code, is typechecked during normal CI build workflows. So we just make sure that `libs/**/*.spec.ts` is covered as well.

This can be reverted when the upstream issue is fixed, see this ticket for more info, and https://bitwarden.atlassian.net/browse/TDL-128 as the follow-up tech debt item.

Requesting a review from devops as well, as this touches build pipelines.

## Code changes

- add `isolatedModules: true` to jest config
- add typechecking step to test workflow. I thought it was tidier to have it here, and unlikely that anyone would use it as a workflow script in `package.json`.

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-08-31 13:35 UTC, MGibson1 requested changes

2022-08-31 13:35 UTC, MGibson1 commented on .github/workflows/test.yml
> +          npx tsc --noEmit --project ./libs/electron/tsconfig.spec.json
I would like to use some glob matching to do this instead, but when I do, I get 9 `tsconfig.spec.json` files. Are you skipping some on purpose?

my list:
- apps/browser/tsconfig.spec.json
- apps/cli/tsconfig.spec.json
- apps/web/tsconfig.spec.json
- bitwarden_license/bit-web/tsconfig.spec.json
- libs/angular/tsconfig.spec.json
- libs/common/tsconfig.spec.json
- libs/components/tsconfig.spec.json
- libs/electron/tsconfig.spec.json
- libs/node/tsconfig.spec.json

recommended script:
```bash
for p in **/tsconfig.spec.json ; do npx tsc --noEmit --project $p ; done
```

2022-08-31 13:35 UTC, MGibson1 commented on .github/workflows/test.yml
> +          npx tsc --noEmit --project ./libs/electron/tsconfig.spec.json
It seems the difference is probably just libs vs all the spec projects, but since we use the same `jest.config.js` for all projects, I think we need to check types on all of the spec projects.

2022-08-31 13:59 UTC, joseph-flinn commented
Other than @MGibson1's comment, everything looks good to me.

2022-09-01 04:12 UTC, eliykat commented on .github/workflows/test.yml
> +          npx tsc --noEmit --project ./libs/electron/tsconfig.spec.json
Yes, I'm intentionally skipping everything not in `libs`, because those spec files are included in the typescript compilation for each client and will be typechecked at that time.

For example - `apps/web/**/*.spec.ts` files are included here: https://github.com/bitwarden/clients/blob/master/apps/web/tsconfig.json#L19, so the web build will fail if they have type errors.

I figured that we only need to check `libs/**/*.spec.ts` in this workflow because we don't have any build step that includes these files already.

The glob pattern is a nicer one though, I've added that and also removed the increased memory allocation given that it's no longer required.

I will note that CI is nowhere near as fast as local, the Github Action ends up taking about the same time as our tests do now - which is fine.

2022-09-01 09:07 UTC, Hinton commented on .github/workflows/test.yml
> +          npx tsc --noEmit --project ./libs/electron/tsconfig.spec.json
Thoughts on just extracting the spec files from the specs directory which would include them in the regular compilation for libs?

2022-09-01 23:15 UTC, eliykat commented on .github/workflows/test.yml
> +          npx tsc --noEmit --project ./libs/electron/tsconfig.spec.json
`libs` is not compiled specifically though, as far as I know. (i.e. we never compile with `libs/**/tsconfig.json` as a target; `libs/*` are not real packages, only path mappings - my understanding at least.) All our compilations use the entrypoints in `apps/**/tsconfig.json`. So I don't think just extracting `libs/**/*.spec.ts` from the specs directory would include it in regular (app) compilations, you'd have to add an entrypoint in each app `tsconfig.json` as well, which I don't really think is necessary. This workaround is a bit of a special and fairly limited case.

2022-09-07 16:41 UTC, MGibson1 approved these changes

2022-09-07 22:05 UTC, merged