Ps 1291/apply to from json pattern to state
bitwarden/clients pull request #3425
Opened 2022-08-31 21:16 UTC by MGibson1

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

As we move deeper into Manifest V3, we need to be sure our state is properly serialized. This PR builds on the patterns established in #2970 to ensure our unserializable items are handled appropriately.

We should expect these (de)serializers to simplify as our memory cache is moved from StateService into BehaviorSubjects living on observables.

## Code changes
### Misc Fixes
- **session-sync.decorator**: Completes a BehaviorSubject that was left dangling in tests
- **cipher.service**: equivalentDomain is initialized to null, but not properly null checked here
- **encrypt.service**: We should be awaiting promises in async methods, even if we directly return them, just as good practice.

### Core Changes
- **utils**: I am regularly asking for a buffer array from nulls. This works in the reverse due to `new Uint8Array(null)` returning an empty array. Moving null checking in here simplifies all usages of this method.
- **account.ts**: Add to/fromJSON where necessary due to unserializable data
- **state.ts**: Add fromJSON to ensure we appropriately deserialize Account data
- **state.service**: Cleans up some hacks now better handled by better Account deserialization.
- **state-migration.service**: Handles stricter type requirements.

Other changes are spec files to validate changes.

2022-09-02 04:02 UTC, eliykat reviewed
Started looking at this, will be able to finish on Monday.

2022-09-02 04:02 UTC, eliykat commented on libs/common/src/misc/utils.ts
> +    if (str == null) {
I worry a bit about the opportunity for `null` propagation here, particularly because this is used deep in the `CryptoFunctionService`s. But that's probably a debugging concern only, I expect it'll just fail somewhere else in the code.

I see that this method is mostly used for RSA keys, do you know why we use this encoding instead of B64 (which we otherwise use for byte arrays)? 🤔 (unrelated to your changes, just asking out of curiosity)

2022-09-05 10:14 UTC, eliykat requested changes

2022-09-05 10:14 UTC, eliykat commented on libs/common/src/services/stateMigration.service.ts
> +      pinProtected: Object.assign(new EncryptionPair<string, EncString>(), {
0.o why are we modifying an old migration?

2022-09-05 10:14 UTC, eliykat commented on libs/common/src/models/domain/account-settings.spec.ts
> +      accountSettings.pinProtected = EncryptionPair.fromJSON<string, EncString>({
I think using mocks/spies is clearer, which you've done in the rest of your tests. (e.g. verifying that `fromJSON` is called.) Is there any need to integrate with `EncryptionPair` here?

2022-09-05 10:14 UTC, eliykat commented on libs/common/src/models/domain/acount-keys.spec.ts
> +      const actual = JSON.stringify(keys.toJSON());
Actually calling `JSON.stringify` in these tests makes the assertions more difficult. Generally we just call `toJSON` and compare the resulting object, can we do that here?

If you do want to use `JSON.stringify`, then it will call `toJSON()` for you, so it's either one or the other.

2022-09-05 10:14 UTC, eliykat commented on libs/common/src/models/domain/acount-keys.spec.ts
> +      expect(actual).toContain(`"cryptoMasterKey":${JSON.stringify(symmetricKey.toJSON())}`);
`JSON.stringify` will recursively call all `toJSON` methods on all nested objects, we don't need to test this. To me, I'd just look at the `toJSON` method that you've implemented and only test that explicit behaviour - in this case, whether it sets the `publicKeySerialized` property. Which is basically what your next test does.

2022-09-12 14:32 UTC, MGibson1 commented on libs/common/src/models/domain/account-profile.spec.ts
> +    it("should deserialize to an instance of itself", () => {
kind of, this is a runtime check, which is stronger than the type checking done by the compiler.

I also wanted to get a test in on this class, but there isn't much more to test given that no more initialization is required for this class.

2022-09-12 14:40 UTC, MGibson1 commented on libs/common/src/models/domain/account.ts
> +        ? encryptedFromJson(obj.encrypted as any)
I don't! thank you.

2022-09-13 00:11 UTC, MGibson1 commented on libs/common/src/models/domain/account.ts
> +  private decryptedSerialized?: string;
It's a pattern to serialize unserializable data (right now just `ArrayBuffer`).

It's difficult to determine the type of data from serialized JSON, so this property is only populated on serialization if `decrypted` is an `ArrayBuffer`, and it's only used on deserialization to re-populate the `decrypted` field.

This pattern is extracted from the `StateService` in a few locations where it was needed.

2022-09-13 00:13 UTC, MGibson1 commented on libs/common/src/models/domain/account.ts
> +        this.decrypted instanceof ArrayBuffer ? Utils.fromBufferToByteString(this.decrypted) : null,
Not sure I follow you're concern, but you _can't_ pass `ArrayBuffer` around between instances, since it's not serialized to JSON.

Currently, application context is passed around through our own construct -- `LocalBackedSessionStorage`, rather than relying on purely the chrome.storage.session API we're provided.

The reason for this is the limited size of session storage -- 1MB. We'd fill that pretty quickly with decrypted ciphers and whatnot.

2022-09-13 00:15 UTC, MGibson1 commented on libs/common/src/models/domain/account.ts
> +  private publicKeySerialized?: string;
Here it could be superseded, but I don't like the idea of changing data types for serialization, so I preferred another property like in `EncryptionPair`.

However, `EncryptionPair` used generics and required another property, here we could just always (de)serialize to a string.

2022-09-13 00:16 UTC, MGibson1 commented on libs/common/src/models/domain/account.ts
> +  // Issue raised https://github.com/sindresorhus/type-fest/issues/457
I ended up converting `Account` to always rely on `Record<Tkey, TValue>` and converting to a `Map` in the `StateService`. I think this is a nice middle ground, where we want to use `Map`s, but need to store as `Record`s. Right now, one of `StateService`'s jobs is to convert between storage and usage models.

2022-09-13 00:21 UTC, MGibson1 commented on libs/common/src/models/domain/account.ts
> +    return Object.assign(new AccountTokens(), obj);
Doesn't matter, we were never setting it, so it was always null. I've deleted the whole thing.

2022-09-13 00:23 UTC, MGibson1 commented on libs/common/src/models/domain/account.ts
> +  static fromJSON(json: any): Account {
I was for `AccountKeys`, but those are "fixed" now. Changed to a real type.

2022-09-13 00:23 UTC, MGibson1 commented on libs/common/src/models/domain/acount-keys.spec.ts
> +
good eye! ty

2022-09-13 00:26 UTC, MGibson1 commented on libs/common/src/models/domain/state.ts
> +  // TODO, make Jsonify<State,TGlobalState,TAccount> work. It currently doesn't because Globals doesn't implement Jsonify.
Currently, no. `GlobalState` is well tested as serializable, since we currently rely on it to be.

2022-09-13 00:28 UTC, MGibson1 commented on libs/common/src/services/state.service.ts
> -    return (
yes

2022-09-13 00:30 UTC, MGibson1 commented on libs/common/src/services/state.service.ts
> +    return State.fromJSON(stateJson);
They don't need to go through, but I can't see how it could hurt them. In effect, you're just reinitializing them with the exact same property info, assuming the initializer is right. It's just unnecessary work.

You're right that this is a bit of a smell, but it indicates that `state` retrieval should be on the `StorageService`, not `StateService`. That's a change I'm not terribly interested in doing right now.

2022-09-13 00:33 UTC, MGibson1 commented on libs/common/src/services/stateMigration.service.ts
> +      pinProtected: Object.assign(new EncryptionPair<string, EncString>(), {
Because previously there were no type requirements on `pinProtected` -- it was an `any`.

Now, we need to instantiate an `EncryptionPair`. There is no difference in the loaded data.

2022-09-13 00:36 UTC, MGibson1 commented on libs/common/src/models/domain/account-settings.spec.ts
> +      accountSettings.pinProtected = EncryptionPair.fromJSON<string, EncString>({
It's to make sure the proper decrypted property initializer is used. Wherever I needed to call `fromJSON` on `EncryptionPair` with an initializer, I'm using actual value tests -- sometimes in conjunction with spies.

2022-09-16 04:38 UTC, eliykat commented on libs/common/src/models/domain/account-profile.spec.ts
> +    it("should deserialize to an instance of itself", () => {
Sure - I'm okay with it, mostly because we can't enforce static method signatures via a class or interface, so I see this as an alternative safeguard.

2022-09-16 04:39 UTC, eliykat commented on libs/common/src/misc/utils.ts
> +    if (str == null) {
Gotcha, thanks for the explanation

2022-09-16 04:44 UTC, eliykat commented on libs/common/src/models/domain/account.ts
> +        this.decrypted instanceof ArrayBuffer ? Utils.fromBufferToByteString(this.decrypted) : null,
> you can't pass ArrayBuffer around between instances

Then my concern doesn't apply. This was an issue I encountered in mv2, because it allows you to pass whole objects between the popup & background page, just wanted to double check.

2022-09-16 06:14 UTC, eliykat commented on libs/common/src/services/state.service.ts
> +    return State.fromJSON(stateJson);
I think that's _probably_ true based on your current implementation, but I think it's risky (i.e. at risk of regressions). It would be easy to use an initializer that cannot be called repeatedly on its return value, I don't think there's anything inherent in the patterns here that prevents that or makes that an obvious mistake. 

e.g. if we got rid of `publicKeySerialized` like I want to (in comment above), I think that would cause an error here - which you might say is an argument for keeping it 😁  - but I think it points to a larger problem of calling a JSON initializer on something that is may not be a JSON value.

2022-09-16 06:14 UTC, eliykat commented on libs/common/src/models/domain/account.ts
> +    return Object.assign(new AccountTokens(), obj);
Good spot! I love tidying up relics like this 🧹

2022-09-16 06:17 UTC, eliykat commented
Note that a lot of my comments above are responding to your comments, Github just doesn't include the thread context for some reason.

2022-09-16 17:22 UTC, MGibson1 commented on libs/common/src/models/domain/account.ts
> +  private publicKeySerialized?: string;
yeah, I suppose you're right. I've updated buffer array serialization

2022-09-16 17:23 UTC, MGibson1 commented on libs/common/src/models/domain/account.ts
> +  private decryptedSerialized?: string;
yeah, you've convinved me. I've updated ArrayBuffer serialization/deserialization

2022-09-16 20:46 UTC, MGibson1 commented on libs/common/src/models/domain/account.ts
> +  // Issue raised https://github.com/sindresorhus/type-fest/issues/457
I've run into issues with these changes and have reverted them. I'll try your approach on monday

2022-09-16 20:47 UTC, MGibson1 commented on libs/common/src/models/domain/account.ts
> +  static fromJSON(json: any): Account {
I've run into issues with these changes and have reverted them. I'll try again on monday

2022-09-16 20:49 UTC, MGibson1 commented
> Note that a lot of my comments above are responding to your comments, Github just doesn't include the thread context for some reason.

Gotta do i

2022-09-16 20:50 UTC, MGibson1 commented
oops tried to cancel a comment and accidentally closed...

2022-09-20 01:08 UTC, eliykat requested changes
Not sure if this was ready for review yet, but it mostly looks good, just a few minor things before we merge.

2022-09-20 01:08 UTC, eliykat commented on libs/common/src/models/domain/account.ts
> +      environmentUrls: Object.assign(new EnvironmentUrls(), obj?.environmentUrls),
This still needs to be done (all good if you haven't gotten to it yet, just want to cover everything outstanding in this review).

2022-09-20 14:58 UTC, MGibson1 commented on libs/common/src/models/domain/account.ts
> -  decryptedSerialized?: string;
It's live in prod, but in-memory only.

2022-09-20 14:59 UTC, MGibson1 commented on libs/common/src/abstractions/storage.service.ts
> +  get<T>(key: string, options?: MemoryStorageOptions<T>): Promise<T>;
Yes, though now that I think about it, we might want initializers on default storage as well... I'm not going to implement that here, so it still seems right to limit it to the one storage location it's relevant.

2022-09-20 18:56 UTC, MGibson1 commented
This should be ready to go. Please take a look at `DeepJsonify`. It's a slight modification to the Jsonify method we're using.

Unfortunately, the upstream has been updated pretty substantially and is incompatible with this solution.

2022-09-21 03:14 UTC, eliykat requested changes

2022-09-21 03:14 UTC, eliykat commented on libs/common/src/models/domain/account.ts
> +  // Issue raised https://github.com/sindresorhus/type-fest/issues/457
I think your solution here is a good one. It works and it's easy to understand. (I actually hadn't seen `Object.fromEntries` before, that's neat)

2022-09-21 03:18 UTC, eliykat commented
Best I can tell, the only remaining `@withPrototype` decorators (and related decorators) are on `AccountData` objects, because it doesn't have JSON methods. Do you expect we'll add JSON methods to `AccountData` at some stage and then remove those decorators entirely? (or they'll naturally disappear when `StateService` is refactored and the omniscient account objects disappear)

2022-09-21 14:15 UTC, MGibson1 commented on libs/common/src/types/DeepJsonify.ts
> +            } // Not Jsonable because its toJSON() method does not return JsonValue
We actually apply `DeepJsonify` to each property on the return. That way it's OK to return `this` from a `toJSON` method, and it'll just try to make sure `this` is Jsonifyable.

2022-09-21 14:33 UTC, MGibson1 commented
https://bitwarden.atlassian.net/browse/PS-1523

A little of column A, a little of column B.

We definitely want to serialize those properly, but it's not worth doing until we know what will be required.

2022-09-22 00:04 UTC, eliykat commented on libs/common/src/types/DeepJsonify.ts
> +            } // Not Jsonable because its toJSON() method does not return JsonValue
Dude that's awesome. ok great

2022-09-22 00:11 UTC, eliykat approved these changes
Nice work on this, the deep-jsonify formatting is still off, but didn't want to hold up the whole PR for it. Your call whether you fix it.

2022-09-22 00:11 UTC, eliykat commented on libs/common/src/types/deep-jsonify.ts
> +export type DeepJsonify<T> =
You added this file to `.prettierIgnore` but it's still using prettier formatting. Maybe prettier caught it anyway?

2022-09-22 01:28 UTC, MGibson1 commented on libs/common/src/types/deep-jsonify.ts
> +export type DeepJsonify<T> =
two things: 1) workspace mode doesn't use prettier ignore by default and 2) I didn't add to eslint.

2022-09-22 10:16 UTC, eliykat approved these changes
I disabled auto-merge because there are changes in Chromatic that I don't understand, but I still wanted to get an approval in on the code. Please make sure Chromatic is OK before merging.

2022-09-22 12:51 UTC, merged