[EC 456] Component Library Content Switching Tabs
bitwarden/clients pull request #3452
Opened 2022-09-06 20:24 UTC by shane-melton

## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Add support for content switching tabs in addition to routing tabs. This implementation takes a lot of inspiration from the [Angular Material tabs](https://material.angular.io/components/tabs/overview) ([source here](https://github.com/angular/components/tree/main/src/material/tabs)). 

In order to better support both content tabs and routing tabs (similar to Angular Material), the existing routing tab component was renamed to `<bit-tab-nav-bar>` (with `<bit-tab-link>` items) and the content switching tab component is now called `<bit-tab-group>` (with `<bit-tab>` items).

### `<bit-tab-nav-bar>`

The underlying routing tab remains mostly unchanged, with some improvements to ARIA support (`link` role, `aria-disabled`, `aria-current`) and keyboard navigation (arrow keys and spacebar, [per spec](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tablist_role#keyboard_interactions)).

Example usage:
```
<bit-tab-nav-bar label="Main">
      <bit-tab-link [route]="['active']">Active</bit-tab-link>
      <bit-tab-link [route]="['item-2']">Item 2</bit-tab-link>
      <bit-tab-link [route]="['item-3']">Item 3</bit-tab-link>
      <bit-tab-link [route]="['disable']" [disabled]="true">Disabled</bit-tab-link>
</bit-tab-nav-bar>
```

### `<bit-tab-group>`

The content tab component supports dynamic tabs, label templates, and optional content preservation. ARIA support was also implemented, including `tab` and `tabpanel` roles, `tabIndex`, `aria-selected`, and `aria-labeledby` attributes.

By default, each tab's content is only rendered to the DOM when the tab is selected (unless the `preserveContent` flag is `true`, in which case it is preserved).

Example usage:
```
<bit-tab-group label="Main Content Tabs">
    <bit-tab label="First Tab">First Tab Content</bit-tab>
    <bit-tab label="Second Tab">Second Tab Content</bit-tab>
    <bit-tab>
      <ng-template bit-tab-label>
        <i class="bwi bwi-search tw-pr-1"></i> Template Label
      </ng-template>
      Template Label Content
    </bit-tab>
    <bit-tab [disabled]="true" label="Disabled">
      Disabled Content
    </bit-tab>
</bit-tab-group>
```

## Code changes

### Content Tabs Changes
- **libs/components/src/tabs/tab-group.component.ts:** Update the `bit-tab-group` component to support content switching and template labels.
- **libs/components/src/tabs/tab-item.component.html:** Removed/replaced by the `bit-tab-list-item` directive.
- **libs/components/src/tabs/tab-label.directive.ts:** Directive used for identifying `<ng-template>` tags that will be used as the tab label instead of a plain text label.

- **libs/components/src/tabs/tab.component.ts:** Add the `bit-tab` component defining tabs and their respective content and labels. Supports both text and template labels for tab headers.

### Routing Tabs Changes
- **libs/components/src/tabs/tab-link.component.html:** Add tab nav link component to be used within the `bit-tab-nav-bar` component. Uses an underlying  `<a>` tag and `[routerLink]` and `routerLinkActive` directives.

- **libs/components/src/tabs/tab-nav-bar.component.ts:** Add the `bit-tab-nav-bar` component which handles rendering the tab links and keyboard navigation.

### Shared Changes
- **libs/components/src/tabs/tabs.module.ts:** Update the module to only export the necessary public components/directives. Keeps implementation specific directives internal to avoid polluting public API.
- **libs/components/src/tabs/tab-list-container.directive.ts:** Internal helper directive used for styling the tab header items in both the content and router tab components.
- **libs/components/src/tabs/tab-list-item.directive.ts:** Internal helper directive used for styling and interacting with tab header items.

- **libs/components/src/tabs/tabs.stories.ts:** Update and add additional tab stories to storybook.
## Screenshots

Content Tabs:
![image](https://user-images.githubusercontent.com/8764515/188728191-9b13236f-ccc5-41c0-9a50-167181b384fa.png)

Route Tabs (content is only off center due to storybook story):
![image](https://user-images.githubusercontent.com/8764515/188728500-96e40cdd-56f3-4bb7-bcbb-bad1eee4ce09.png)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-09-06 20:26 UTC, shane-melton commented on libs/components/src/tabs/tab-link.component.html
> +  [routerLink]="disabled ? null : route"
`[routerLink]` is set to null when disabled to effectively disable the link. [See docs here](https://angular.io/api/router/RouterLink#properties)

2022-09-06 20:29 UTC, shane-melton commented on libs/components/src/tabs/tab.component.ts
> +export const BIT_TAB_GROUP = new InjectionToken<any>("BIT_TAB_GROUP");
For some more context, these `BIT_*` `InjectionToken<>` are used to help prevent circular dependencies as the components depend on each other.

2022-09-07 07:44 UTC, coroiu commented on libs/components/src/tabs/tab-label.directive.ts
> +  selector: "[bit-tab-label], [bitTabLabel]",
question: why two different selector types?

2022-09-07 07:45 UTC, coroiu commented on libs/components/src/tabs/tab-label.directive.ts
> +  providers: [{ provide: BIT_TAB_LABEL, useExisting: TabLabelDirective }],
question: do we need to provide the tab label? I doesn't seem to be used anywere

2022-09-07 07:48 UTC, coroiu commented on libs/components/src/tabs/tab-link.component.ts
> +  @Input() disabled = false;
nit: fix inconsistent formatting :)

2022-09-07 08:51 UTC, coroiu commented on libs/components/src/tabs/tab.component.ts
> +    if (value && value.closestTab === this) {
suggestion: have you tried modifying the content child decorator `@ContentChild(TabLabelDirective, { descendants: false })` instead of using `closestTab`?

2022-09-07 08:53 UTC, coroiu commented on libs/components/src/tabs/tab-label.directive.ts
> +export const BIT_TAB = new InjectionToken<any>("BIT_TAB");
suggestion: use `unknown` instead of any

2022-09-07 09:25 UTC, coroiu commented on libs/components/src/tabs/tab-link.component.ts
> +export class TabLinkComponent implements FocusableOption, AfterViewInit, OnDestroy {
question: why not use an anchor host tag `a[bit-tab-link]`? I suspect we could get rid of `@HostListener("keydown", ["$event"])` if we did that, but I'm sure there are lots of downsides as well. Maybe you could expand a little on the reasoning for this decision?

2022-09-07 09:36 UTC, coroiu commented on libs/components/src/tabs/tab-label.directive.ts
> +export const BIT_TAB_LABEL = new InjectionToken<TabLabelDirective>("BitTabLabel");
suggestion: this injection token uses different name format, change to `BIT_TAB_LABEL`

2022-09-07 09:36 UTC, coroiu commented on libs/components/src/tabs/tab-label.directive.ts
> +export const BIT_TAB = new InjectionToken<any>("BIT_TAB");
question: shouldn't this be placed in `tab.component.ts` ?

2022-09-07 09:47 UTC, coroiu requested changes
All in all good work! I especially like how well the accessibility features work! I've added some questions and suggestions and also have some general things I've noticed

1. **nit:** `any` is used a few places, I think `unknown` is generally preferred as a more type-safe alternative. Maybe you could do a quick search/replace? 

2. **issue:** the tab header is missing a gray container/padding (see figma)

3. **question:** `forwardRef` and your comment about circular dependencies makes me a bit uneasy. I've noticed that the CDK source has the same things. Have you given this any though? Do we know why? Does complexity increase a lot by trying to get rid of the circular dependencies?

4. **suggestion:** In the rest of the CL, directives seem to have `camelCase` selectors while custom tags (usually components) have `kebab-case`. Just go through and tweak the namings a bit to make sure we follow the same convention

2022-09-07 13:47 UTC, coroiu commented on libs/components/src/tabs/tab-group.component.html
> +<div class="tw-py-5">
issue: I think this might need to be changed to `tw-pt-5` otherwise we get a huge empty space at the bottom of dialogs (see example in screenshot below). Either that or we need to modify the dialog padding `tw-pb-8` which is also quite big by itself. @Hinton did you double check that padding with UX?

![image](https://user-images.githubusercontent.com/2285588/188894113-e8a4a2c7-85ea-4cc1-b220-bc2854968ee9.png)

2022-09-07 23:04 UTC, shane-melton commented on libs/components/src/tabs/tab-label.directive.ts
> +  providers: [{ provide: BIT_TAB_LABEL, useExisting: TabLabelDirective }],
Good catch, we don't need it

2022-09-07 23:26 UTC, shane-melton commented on libs/components/src/tabs/tab-label.directive.ts
> +export const BIT_TAB_LABEL = new InjectionToken<TabLabelDirective>("BitTabLabel");
Removed the InjectionToken as it was not actually necessary.

2022-09-07 23:26 UTC, shane-melton commented on libs/components/src/tabs/tab-label.directive.ts
> +export const BIT_TAB = new InjectionToken<any>("BIT_TAB");
Removed the InjectionTokens as they were not actually necessary for our implementation.

2022-09-07 23:27 UTC, shane-melton commented on libs/components/src/tabs/tab-label.directive.ts
> +  selector: "[bit-tab-label], [bitTabLabel]",
Good catch, we should only have the one

2022-09-07 23:38 UTC, shane-melton commented on libs/components/src/tabs/tab.component.ts
> +    if (value && value.closestTab === this) {
Actually, this also seems to be a requirement for Angular Materials implementation -- theirs is much more complex with animations and other _material_ things compared to ours

2022-09-08 00:03 UTC, shane-melton commented on libs/components/src/tabs/tab-link.component.ts
> +export class TabLinkComponent implements FocusableOption, AfterViewInit, OnDestroy {
Using a directive instead of a component may be possible, however it does add a decent amount of complexity and burdens consumers of the directive with following implementation/style details. 

- Tracking the active tab is done via a `routerLInkActive` directive on the templates `<a>` tag. We'd need to ensure the same setup was performed for each `<a>` tag in the `<bit-tab-nav-bar>`.
- Styling is done via the `bitTabListItem` directive. So they'd need to add that to every `<a>` tag.
- ARIA support would need to be duplicated by the consumer of the component or the directive would need to specify those, likely using more `@HostBindings()`.
- The `[routerLink]` value needs to be `null` when the tab is disabled, so that would be left for consumers to follow.

Overall I find using an explicit component/tag to be more consumer friendly here and makes it less likely the implementation/style will break be incorrectly implemented.

2022-09-08 06:37 UTC, coroiu commented on libs/components/src/tabs/tab-link.component.ts
> +export class TabLinkComponent implements FocusableOption, AfterViewInit, OnDestroy {
You make a compelling argument 😄 Maybe it would be more feasible when they complete the proposed `@HostDirective` decorator https://github.com/angular/angular/issues/8785

Small note: I didn't mean changing to a directive, only changing the host tag but keeping it as a component. However I see now that there would be no point using a component since the template would only consist of `<ng-content>` and then we might as well use directives!

**Another question btw:** What happens if you add `tabindex=-1` to the anchor tag? Could that be a way to get rid of the `@HostListener("keydown", ["$event"])`?

2022-09-08 07:52 UTC, Hinton reviewed
Please ensure we provide attribution if any code is copied from CDK

2022-09-08 07:53 UTC, Hinton commented on libs/components/src/tabs/tab-group.component.html
> +<div class="tw-py-5">
Yes, we can't add padding or margin to the bottom.

2022-09-08 07:56 UTC, Hinton commented
Can we also create two sub-folders, one for nav items and another for content tabs? Will make it easier to separate them.

2022-09-08 08:16 UTC, Hinton commented on libs/components/src/tabs/tab-group.component.ts
> +  constructor(private _changeDetectorRef: ChangeDetectorRef) {
Change detector is unused

2022-09-08 08:16 UTC, Hinton commented on libs/components/src/tabs/tab-group.component.ts
> +  _getTabContentId(id: number): string {
Is the goal to only use this internally in the component? If so use `protected` instead of underscore, which is supported since Angular 14.

2022-09-08 15:14 UTC, shane-melton commented on libs/components/src/tabs/tab-link.component.ts
> +export class TabLinkComponent implements FocusableOption, AfterViewInit, OnDestroy {
Haha thanks, and yeah I stumbled upon that proposal as well and agree that it would make it more feasible to use an anchor tag host once/if able to add additional directives via a `@HostDirective`.

And unfortunately the `tabindex=-1` still doesn't allow the tab to be selected via the spacebar, so I think we may be stuck with the `@HostListener` for now.

2022-09-08 18:39 UTC, shane-melton commented on libs/components/src/tabs/tab-list-item.directive.ts
> +export class TabListItemDirective implements FocusableOption {
The `FocusKeyManager` used by the group and navbar components require a publicly accessible `focus()` method on the items it controls ARIA support. 

We could possibly make the `elementRef` public on the directive and pass/map that into the `FocusKeyManager` constructor, but exposing the `elementRef` publicly seems less ideal when compared to encapsulating the `focus()` method explicitly.

2022-09-08 18:51 UTC, shane-melton commented on libs/components/src/tabs/tab-group.component.ts
> +  _getTabContentId(id: number): string {
Yep, that's the intention. I did that originally, but my editor was giving warnings that the `protected` method "cannot be resolved when using the AOT compiler." My guess is my editor isn't entirely aware of the change in Angular 14, but it does work appear to be working correctly so I'm good with changing this.

2022-09-08 18:53 UTC, shane-melton commented on libs/components/src/tabs/tab-group.component.html
> +<div class="tw-py-5">
Switched to `tw-pt-5` to avoid adding extra padding to the bottom of content tabs

2022-09-08 20:15 UTC, shane-melton commented
> All in all good work! I especially like how well the accessibility features work! I've added some questions and suggestions and also have some general things I've noticed
> 
> 1. **nit:** `any` is used a few places, I think `unknown` is generally preferred as a more type-safe alternative. Maybe you could do a quick search/replace?
> 2. **issue:** the tab header is missing a gray container/padding (see figma)
> 3. **question:** `forwardRef` and your comment about circular dependencies makes me a bit uneasy. I've noticed that the CDK source has the same things. Have you given this any though? Do we know why? Does complexity increase a lot by trying to get rid of the circular dependencies?
> 4. **suggestion:** In the rest of the CL, directives seem to have `camelCase` selectors while custom tags (usually components) have `kebab-case`. Just go through and tweak the namings a bit to make sure we follow the same convention

Thanks for the review and suggestions @coroiu!

1. Good call, the couple uses of `any` are now `unknown`.
2. I added an additional wrapper to style the background gray and give that small spacing above the tabs.
3. The circular dependency with the `forwardRef` seems mostly unavoidable here for the tab links and nav bar. The tab nav links need to communicate to the navbar when the active status changes (from the internal `routerLinkActive` directive) via the `updateActiveLink()` method. It's probably possible to keep track of the active route from the nav bar, but that would require subscribing to the active route and matching/checking against all the routes in the tab links which seems more cumbersome. At least when compared to using the `forwardRef` to communicate between the components directly. But I'm open to re-evaluating this if you see any easier/better way.
4. Done, thanks for bringing that up, much more consistent now.

2022-09-13 07:24 UTC, coroiu submitted a review, later dismissed
Good work! Sorry for taking so long to approve, I wanted to try it on my own branch to see how it looks in a dialog, and as you can see it works nicely!

![image](https://user-images.githubusercontent.com/2285588/189835686-53ee3453-7925-4723-8036-de52f629635f.png)

There are some paddings to be worked out but I don't think those are an issue for the tab components. I think I'll upload a PR that allows for the removal of the dialog padding. 

Regarding `forwardRef`, you've clearly thought it through and so I'll trust your conclusions! Even if there was a better way I don't think it's worth the effort right now, and I feel it's more important to get this merge! Maybe when someone revisits this in the future they might get some good ideas 🙂

2022-09-13 07:35 UTC, coroiu commented
Sorry for dismissing my approval but I just noticed something in the figma design when it comes to the paddings

Here is the design for the tab component (which your PR mirrors very nicely)
![image](https://user-images.githubusercontent.com/2285588/189838151-4d50ee72-ec88-47ce-b670-ec82ac838a12.png)

And here is an example of the tabs being used in a dialog
![image](https://user-images.githubusercontent.com/2285588/189838722-cade0a84-fafd-4ebf-bd08-46ce42a00607.png)

As you can see the tabs have a slight padding that matches with the content. I guess this could be added by a wrapper outside of the scope of the tab component, but I'm not sure if that's the best way. Do we need to support both types?

2022-09-13 15:12 UTC, danielleflinn commented
> do we need to support both cases (with and w/o padidng), or if this is just a miss in figma?
Nope this was a miss in Figma; I'll update to include the padding.

2022-09-13 16:21 UTC, shane-melton commented
Nice catch @coroiu! Padding is all fixed and matching the updated Figma now

2022-09-13 17:37 UTC, shane-melton commented
@coroiu It was also decided with @danielleflinn to add content padding to the tabs and adjust the bottom border of tab header to span the entire content area (to match the examples in tabbed dialogs). We'll still need another PR for the dialog component to optionally remove its content padding (e.g. when the content is a tab group) otherwise we'll still get double padding in dialogs.

2022-09-13 17:44 UTC, danielleflinn approved these changes

2022-09-14 06:55 UTC, coroiu submitted a review, later dismissed
Awesome work!

2022-09-16 09:44 UTC, Hinton reviewed
I haven't re-reviewed this, but I believe my concerns were resolved so should be good.

2022-09-26 21:41 UTC, vvolkgang approved these changes
Merge from master dismissed the previous approval, approving again.

2022-09-26 21:41 UTC, merged