Prevent new line feed when selecting password
bitwarden/clients pull request #3460
Opened 2022-09-07 18:32 UTC by dnicolson

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

This pull request prevents selecting a trailing new line feed (`0x0A`) when selecting a password or triple clicking the password.

## Code changes

This fixes an issue that only seems to affect Electron/Chromium, the issue is not reproducible in Safari or Firefox with the Electron HTML.

The issue appears to be triggered by a combination of whitespace between DOM elements and the use of the `user-select` CSS property on the buttons to the right, with a reduced example the whitespace change was enough to fix the issue.

## Screenshots

https://user-images.githubusercontent.com/2276355/188950138-1e593426-2391-4786-9df3-330708cfdba3.mov

<img width="643" alt="Hex" src="https://user-images.githubusercontent.com/2276355/188950151-6f3ac227-e035-4e68-a848-88a8bf449ea0.png">

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-07-19 11:21 UTC, aj-rosado commented
Hello @dnicolson , thank you for your contribution! 
We appreciate your effort in trying to fix the problem. However, upon further testing, we found that the issue with copying a new line feed still persists with the current changes.
We welcome further contributions or suggestions. Thanks again!

2023-08-11 12:51 UTC, aj-rosado requested changes
Hello @dnicolson , thank you again for your collaboration. Really appreciate your efforts in trying to solve this problem.

Despite the latest updates that have been implemented, I am still encountering the problem of copying the line feed when selecting text, both on the password generator and within the vault 😕

We would greatly appreciate any further contributions or suggestions you might have. Thank you once again!

2023-08-11 16:06 UTC, dnicolson commented
This fix only applies to the generator, are you referring to https://github.com/bitwarden/clients/pull/5887 for within the vault?

I just tested it again and it seems to work:

https://github.com/bitwarden/clients/assets/2276355/96e85e8c-5f78-4d73-8201-0797e60b7a04

2023-08-11 16:30 UTC, aj-rosado commented
> This fix only applies to the generator, are you referring to #5887 for within the vault?
> 
> I just tested it again and it seems to work:
> 
>  Screen.Recording.2023-08-11.at.17.58.54.mov

I haven't tested the https://github.com/bitwarden/clients/pull/5887 yet. 
I'm still able to reproduce the issue on the generator on this branch, I'm testing on a Mac, are you testing on a Windows?


https://github.com/bitwarden/clients/assets/109146700/065cb24a-727a-4262-a1d3-d07eb3378df3

2023-08-11 17:04 UTC, dnicolson commented
Yes, the Mac desktop application. Maybe there is a race condition, what if you replace `setImmediate` with `setTimeout` as in https://github.com/bitwarden/clients/pull/5887.

2023-08-11 17:29 UTC, aj-rosado commented
> Yes, the Mac desktop application. Maybe there is a race condition, what if you replace `setImmediate` with `setTimeout` as in #5887.

SetTimeout seems to solve it 😄 . With SetTimeout the changes on the `misc.scss` are not even necessary as the directive now seems to properly sanitize the text like on other clients.

The vault items are still not copying properly but I guess the https://github.com/bitwarden/clients/pull/5887 will fix it.

Could you please update the branch to use the `SetTimeout` and remove the changes on the `misc.scss` ?

Thank you again for your contribution 😃

2023-08-11 17:42 UTC, dnicolson commented
I've replaced `setImmediate` with `setTimeout`.

ed383cf is still needed as it prevents the extra whitespace in the text selection, it doesn't affect the copying.

2023-08-16 13:45 UTC, aj-rosado requested changes
Thank you again for your contribution @dnicolson , could you please make this small change?

2023-08-23 13:38 UTC, aj-rosado approved these changes
Thank you @dnicolson for your work on this. I really appreciate it. Changes are looking good to me. 

Still needs approval from @bitwarden/tech-leads.

2023-08-24 12:07 UTC, djsmith85 approved these changes

2023-08-24 12:10 UTC, djsmith85 requested changes

2023-08-24 12:10 UTC, djsmith85 commented on libs/angular/src/directives/copy-text.directive.ts
> +    const timeout = this.platformUtilsService.getClientType() === "desktop" ? 100 : 0;
Sorry a little too fast on the approval, just one little nit. Could we use the ClientType enum instead of the string here.

2023-08-25 20:59 UTC, djsmith85 approved these changes

2023-08-28 09:52 UTC, aj-rosado approved these changes
Passing it to QA! 🎉

2023-09-01 10:06 UTC, merged

2023-09-01 10:07 UTC, aj-rosado commented
Thank you your contribution @dnicolson , this has been approved by QA and merged to master 🎉 

This fix will be part of a future release. 😄