[PS-1092] Organization Service Observables
bitwarden/clients pull request #3462
Opened 2022-09-07 19:29 UTC by justindbaur

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Adds a `organizations$` observable so that the latest organization data can be subscribed to. 

## Code changes

- Provide an observable for current users organizations
- Subscribe to that observable throughout places in the UI so it is reactive

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-09-13 22:14 UTC, MGibson1 reviewed
As you pointed out, I'm concerned about the full sync moves. It feels possible that some esoteric flow expects the sync to occur exactly where it currently is, not right after update.

Just concerned about losing this element of control. @eliykat: Can you speak to this regarding key connector?

2022-09-13 22:14 UTC, MGibson1 commented on libs/common/spec/services/organization/organization.service.spec.ts
> +    activeAccountUnlocked = new BehaviorSubject(true);
Should call `complete` on these in an `afterEach`

2022-09-13 22:14 UTC, MGibson1 commented on libs/common/spec/services/organization/organization.service.spec.ts
> +    //   );
Remove commented code

2022-09-13 22:14 UTC, MGibson1 commented on libs/common/spec/services/organization/organization.service.spec.ts
> +    await new Promise((r) => setTimeout(r, 500));
I'm surprised you need a timeout in a teardown method, or am I misunderstanding what this is for?

2022-09-13 22:14 UTC, MGibson1 commented on libs/common/src/abstractions/sync/syncNotifier.service.abstraction.ts
> +  send: (event: SyncEventArgs) => void;
I'd just call this next to be consistent with observables.

2022-09-13 22:30 UTC, MGibson1 requested changes

2022-09-13 22:30 UTC, MGibson1 commented on libs/common/src/services/organization/organization-api.service.ts
> +    // TODO: Do I broadcast anything?
Remove todos and probably explain logic on why not.

2022-09-13 22:30 UTC, MGibson1 commented on libs/common/src/services/state.service.ts
> +   * @depracated Do not call this directly, use OrganizationService
spelled `deprecated`. Not sure if this is misspelled across PR or just this file

2022-09-13 22:30 UTC, MGibson1 commented on libs/common/src/services/organization/organization.service.ts
> +export function getOrganizationById(id: string) {
this feels a little weird. I might like it, but I am forced to ask -- why just this helper?

There are also examples of filtering names or whatnot

2022-09-13 22:30 UTC, MGibson1 commented on libs/common/src/services/organization/organization.service.ts
> +      .pipe(filter(isSuccessfullyCompleted))
just one pipe needed.

2022-09-13 22:30 UTC, MGibson1 commented on libs/common/src/services/organization/organization.service.ts
> +    const organizationsMap = await this.stateService.getOrganizations({ userId: userId });
Is this going back to stateService because of the `userId` parameter?

If so, this makes sense since we're grabbing it from disk, iirc

2022-09-13 22:30 UTC, MGibson1 commented on libs/common/src/services/organization/organization.service.ts
> +    const organizations = await this.getAll(userId);
would be nice to use the cache if userId is null, just to avoid grabbing from disk

2022-09-13 22:30 UTC, MGibson1 commented on libs/common/src/services/organization/organization.service.ts
> +    return await this.stateService.setOrganizations(organizations);
shouldn't this trigger an observable update?

2022-09-13 22:30 UTC, MGibson1 commented on libs/common/src/services/organization/organization.service.ts
> +  private async updateStateAndObservables(organizationsMap: { [id: string]: OrganizationData }) {
why not leverage this more? you basically should always be using it, right?

Or get rid of it and just make the two calls, but using once seems unnecessary.

2022-09-13 22:30 UTC, MGibson1 commented on apps/cli/src/commands/convertToKeyConnector.command.ts
> +      // need to do this here?
@eliykat: some key connector expertise here, too, if you will

2022-09-14 02:32 UTC, eliykat commented on libs/angular/src/components/remove-password.component.ts
> +      this.actionPromise = this.organizationApiService.leave(this.organization.id);
The full sync commands have been moved to the `OrganizationApiService`.

2022-09-14 02:39 UTC, eliykat commented on apps/cli/src/commands/convertToKeyConnector.command.ts
> +      // need to do this here?
`removeConvertAccountRequired` is just removing a flag set in `StateService`, saved in localStorage. I believe that flag was added so that we could persist the need for conversion in CLI (which doesn't have a continuously running state) and browser (which has different contexts with their own state).

However, each time a sync occurs, we check from scratch whether the user needs migration, and remove the flag if they don't: https://github.com/bitwarden/clients/blob/master/libs/common/src/services/sync/sync.service.ts#L347

So if anything, we could delete both the `fullSync` invocation (handled by `organizationApiService`) _and_ `removeConvertAccountRequired` (handled by `fullSync`).

2022-09-14 02:40 UTC, eliykat commented on apps/cli/src/commands/convertToKeyConnector.command.ts
> +      // need to do this here?
QA should do a smoketest on Key Connector though, just to make sure we don't trap users in an infinite loop if I've missed something here.

2022-09-15 19:57 UTC, justindbaur commented on apps/browser/src/popup/vault/vault-select.component.ts
> +      });
I have refactored this a bit to use more observables on the page.

2022-09-15 20:10 UTC, justindbaur commented on apps/web/src/app/components/organization-switcher.component.ts
> +  @Input() activeOrganization: Observable<Organization> = null;
Nope, this shouldn't have been wrapped in an observable and it was being passed in by value.

2022-09-15 20:11 UTC, justindbaur commented on apps/web/src/app/organizations/settings/account.component.ts
> +      this.formPromise = this.organizationApiService.save(this.organizationId, request);
Moved into `save()`

2022-09-15 20:13 UTC, justindbaur commented on apps/web/src/app/organizations/sponsorships/families-for-enterprise-setup.component.ts
> +    this.existingFamilyOrganizations$ = this.organizationService.organizations$
Duh, good catch!

2022-09-15 20:18 UTC, justindbaur commented on apps/web/src/app/settings/sponsored-families.component.ts
> +    this.availableSponsorshipOrgs$.pipe(takeUntil(this._destroy)).subscribe((orgs) => {
I don't think I follow, wouldn't I still need to subscribe to it actually run that `switchMap`?

2022-09-15 20:18 UTC, justindbaur commented on apps/web/src/app/vault/vault-filter/organization-filter/organization-options.component.ts
> +      this.actionPromise = this.organizationApiService.leave(org.id);
`leave()` now does the full sync.

2022-09-15 21:01 UTC, justindbaur commented on libs/common/src/services/organization/organization.service.ts
> +    const organizations = await this.getAll(userId);
I took a deeper look and no one is calling this method with a `userId` parameter so I just removed it and it looks at the cache no matter what.

2022-09-16 12:26 UTC, justindbaur commented on libs/common/src/services/organization/organization.service.ts
> +    return await this.stateService.setOrganizations(organizations);
It doesn't actually get used, it shouldn't be there 😮‍💨

2022-09-16 12:42 UTC, justindbaur commented on libs/common/src/services/organization/organization.service.ts
> +  private async updateStateAndObservables(organizationsMap: { [id: string]: OrganizationData }) {
Done, I meant to leverage it more.

2022-09-19 14:03 UTC, justindbaur commented on libs/common/src/services/organization/organization.service.ts
> +    const organizationsMap = await this.stateService.getOrganizations({ userId: userId });
Yep, that's exactly why. I could check if it's undefined and if so grab the cached ones though, would that be better?

2022-09-19 14:06 UTC, justindbaur commented on libs/common/src/services/organization/organization.service.ts
> +export function getOrganizationById(id: string) {
I couldn't really find other examples of filtering by other than the id. Could you point me to one?

2022-09-19 17:43 UTC, justindbaur commented on libs/common/spec/services/organization/organization.service.spec.ts
> +    await new Promise((r) => setTimeout(r, 500));
This isn't a teardown, it's a helper for setting up the service in a slightly different way from all the other tests. And since my pipe is async it needs to wait just a little bit. I was able to get it down to 50ms though.

2022-09-19 20:23 UTC, justindbaur commented on libs/angular/src/components/share.component.ts
> +    this.organizationService.organizations$.subscribe((orgs) => {
I added a takeUntil and changed the `organizations` property on this component to an observable but I didn't totally get rid of the subscribe. I can't really think of a great way to move that to a `switchMap`.

2022-09-19 20:24 UTC, justindbaur commented on apps/web/src/app/organizations/sponsorships/families-for-enterprise-setup.component.ts
> +    this.existingFamilyOrganizations$.pipe(takeUntil(this._destroy)).subscribe((orgs) => {
I'd love to get with you to go over how you see that happening, I couldn't think of a clean solution.

2022-09-19 20:27 UTC, justindbaur commented on apps/cli/src/commands/convertToKeyConnector.command.ts
> +      // need to do this here?
I will make sure they do a test on this part.

2022-09-21 16:34 UTC, jlf0dev requested changes

2022-09-21 16:34 UTC, jlf0dev commented on libs/angular/src/vault/vault-filter/components/vault-filter.component.ts
> +
@justindbaur this is a cool little upgrade, but I actually have a pretty big refactor coming for the vault filter that creates the observable in the `VaultFilterService`. I think this might just cause conflicts in the end, so might want to leave it out for now.

2022-09-21 16:47 UTC, MGibson1 approved these changes
One comment request, but otherwise looks good to me. I'll let Jake be the final review from now on.

2022-09-21 16:47 UTC, MGibson1 commented on libs/angular/src/services/jslib-services.module.ts
> +      deps: [ApiServiceAbstraction, SyncServiceAbstraction],
Really surprised about these deps. Is it because your api service forces syncs and you get everything from the sync?

I think I want a comment on the class explaining why the dep tree is odd.

2022-09-22 14:24 UTC, justindbaur commented on libs/angular/src/services/jslib-services.module.ts
> +      deps: [ApiServiceAbstraction, SyncServiceAbstraction],
Added a comment.

2022-09-22 14:52 UTC, justindbaur commented on apps/browser/src/popup/vault/vault-select.component.ts
> +      // I am???
@Hinton Do you know why I would be getting this linting error here?

2022-09-22 15:34 UTC, jlf0dev submitted a review, later dismissed
LGTM

2022-09-23 09:00 UTC, Hinton commented on apps/browser/src/popup/vault/vault-select.component.ts
>  // eslint-disable-next-line rxjs-angular/prefer-takeuntil
I believe we can remove this comment n ow that we implement `OnDestroy`?

2022-09-23 09:01 UTC, Hinton commented on apps/browser/src/popup/vault/vault-select.component.ts
> +      .pipe(takeUntil(this._destroy))
`takeUntil` needs to be last. The reason being that we want to stop all observables. `concatMap` essentially creates a new observable which we now aren't unsubscribing to,

2022-09-23 09:01 UTC, Hinton commented on apps/browser/src/popup/vault/vault-select.component.ts
> +      // I am???
I wrote a comment.

2022-09-23 09:02 UTC, Hinton commented on apps/web/src/app/organizations/sponsorships/families-for-enterprise-setup.component.ts
>  // eslint-disable-next-line rxjs-angular/prefer-takeuntil
We should be able to remove this now that we implement OnDestroy.

2022-09-23 11:38 UTC, justindbaur commented on apps/browser/src/popup/vault/vault-select.component.ts
> +      .pipe(takeUntil(this._destroy))
Thank you that's what I was missing.

2022-09-23 12:30 UTC, Hinton approved these changes
My concerns have been addressed

2022-09-27 20:25 UTC, merged