Ps 976 moving of read only organization collection items to different folder not possible
bitwarden/clients pull request #3474
Opened 2022-09-09 05:19 UTC by dgoodman-bw

## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

This fixes a bug where users with readonly permissions for collection ciphers cannot change the folder of those ciphers. 

The Edit Cipher form currently has a mix of fields that a user can edit when they have readonly permissions and fields that they can't. To make it more clear to users what actions they can take on the form, fields they are not able to edit have been made readonly.

## Code changes

All `add-edit-custom-fields.component.html` and `add-edit.component.html` files:
If a user has readonly permissions for a cipher, all fields aside from Favorite and Folder are set to readonly.

All `*.scss` files: 
Added class `readonly` to use on `<select>` objects, intended to mimic built in readonly behavior (the user can't change the value, but screen readers can still read the value)

`cipher.service.ts`:
When the user does not have permission to edit the cipher, a new Api endpoint is called. This endpoint can only change the Folder and Favorite value of the cipher.

There is a companion server PR

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-09-14 20:10 UTC, MGibson1 requested changes

2022-09-14 20:10 UTC, MGibson1 commented on apps/browser/src/popup/scss/base.scss
> +  }
A third thing: It's probably a good idea to communicate these selects are disable.

In browser and desktop, the design language is probably to just keep it as a `<span>`, but interested in what @bitwarden/dept-design has to say

2022-09-14 20:10 UTC, MGibson1 commented on libs/common/src/services/api.service.ts
> +
@cyprain-okeke in case this PR is in before your API refactor

2022-09-14 20:10 UTC, MGibson1 commented on libs/common/src/services/cipher.service.ts
> +      }
Both of these outer `if` paths should be extracted to `CreateWithServer` and `UpdateWithServer` or something.

2022-09-25 15:16 UTC, dgoodman-bw commented on apps/browser/src/popup/scss/base.scss
> +  }
> 1. is this the "right" way to handle readonly selects? typically readonly doesn't disable all pointer-events -- you can still click to focus, for example.

Good call, it's not really a good way to handle this. This approach to handling selects has now been replaced. The new implementation displays the values in readonly text input fields and only shows the selects if the user is able to edit the field.

2022-09-25 15:16 UTC, dgoodman-bw commented on apps/browser/src/popup/vault/add-edit-custom-fields.component.html
> +        [disabled]="!cipher.edit && editMode"
This has been updated to not display the element rather than disable it

2022-09-26 19:45 UTC, MGibson1 approved these changes

2022-09-26 19:46 UTC, MGibson1 commented
Needs QA in conjunction with https://github.com/bitwarden/server/pull/2257

2022-10-14 14:28 UTC, MGibson1 submitted a review, later dismissed

2022-10-25 18:57 UTC, djsmith85 approved these changes

2022-10-25 19:24 UTC, merged