Desktop/Browser: use readonly/disabled fields in cipher view
bitwarden/clients pull request #3485
Opened 2022-09-10 23:21 UTC by patrickhlauke

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Currently, in both the desktop and browser versions, when viewing a cipher, most fields lack any underlying structure - the label and value are simply `<div>`s and `<span>`s.

This PR switches the view to use `readonly` (and in the case of boolean custom fields, `disabled`, as you can't have a `readonly` checkbox currently) form fields with a proper `<label>`. This provides an unambiguous structure.

As a side effect, navigating with the keyboard now also sets focus to each value. To avoid failing the WCAG requirement for visible focus, this PR also introduces a focus indication for these readonly fields (a subtle bottom border using the same muted color as the label). 

## Code changes

- **apps/browser/src/popup/vault/view.component.html:** Remove redundant `aria-readonly="true"` if there is already a `readonly` attribute ... the `aria` one is superfluous
- **apps/browser/src/popup/scss/misc.scss** and **apps/desktop/src/scss/misc.scss**: add extra focus styles for when readonly fields (and, in the case of `.sr-only` inputs, their visible sibling `<div>`)
- **apps/desktop/src/app/vault/view.component.html**, **apps/desktop/src/app/vault/view-custom-fields.component.html**, **apps/browser/src/popup/vault/view.component.html**, **apps/browser/src/popup/vault/view-custom-fields.component.html**: change the generic `<div>`/`<span>`s used to show a fake label and value to use actual `<label>` and `<input>`/`<textarea>` elements. As an aside, this also harmonises the desktop markup to be more in line withe the popup one.

## Screenshots

The visual change introduced by this PR is the border bottom on readonly fields when they receive focus.

![browser popup screenshot showing a readonly field with focus, with a bottom border](https://user-images.githubusercontent.com/895831/189504884-6feec0ea-b2f8-42b2-a4d7-809138678b4b.png)

![desktop screenshot showing a readonly field with focus, with a bottom border](https://user-images.githubusercontent.com/895831/189504899-f026da47-4251-4890-b3f3-4f4693ec8d9e.png)

A (fairly low res) video of navigating through the current view of a test item in the browser popup using chrome/nvda (using cursor navigation first, then using `Tab`/`Shift+Tab`), compared to the experience (at about 1 minute in) after this PR is applied. Possibly a bit more verbose, but particularly when tabbing, things are more explicitly announced.

https://user-images.githubusercontent.com/895831/189504913-a76af25e-85fa-442f-97ea-e6af6726a1d5.mp4

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-09-10 23:23 UTC, patrickhlauke commented
/cc @danielleflinn because of the visible change with the focusable readonly fields

2022-09-10 23:29 UTC, patrickhlauke commented
Note that depending on when things get hopefully merged, this will need to be harmonised with https://github.com/bitwarden/clients/pull/3321, https://github.com/bitwarden/clients/pull/2660, and https://github.com/bitwarden/clients/pull/3347

2022-09-12 20:56 UTC, danielleflinn commented
Hi @patrickhlauke! Thanks for another great accessibility contribution :) 

Can you provide more context around the WCAG requirement for a visible focus indicator? I'm assuming this relates to WCAG SC 2.4.7. Does the existing View Item focus state (highlight text) not meet the focus visible requirement? 
cc: @bitwarden/dept-design

2022-09-12 22:22 UTC, patrickhlauke commented
@danielleflinn yes, it's 2.4.7. looking at the current situation (let's just take the browser popup as an example), it's fine except for the `<textarea>` (e.g. a note) in the view - it takes focus, but has no focus indication. so that needed to be addressed. and then now with my change, since there's more things that receive focus (like the TOTP and the password / "hidden" fields), and they wouldn't show the highlight (since for some of these I visually hide the actual control that receives focus, so that it can still use the custom colourised version for the password when revealed, which you couldn't have if just using `<input type="text">`) ... so to sidestep the issue, decided to give a more consistent and explicit focus style for all these extra new scenarios (and the old case of the `<textarea>`)

2022-09-13 21:40 UTC, patrickhlauke commented
Following https://github.com/bitwarden/clients/pull/3321 being merged, I've updated this PR to incorporate the changes from there (making the `<label>` elements draggable)

2022-09-14 18:54 UTC, danielleflinn commented
Thanks for the explanation @patrickhlauke . We definitely should provide a visible focus indicator for the fields you mentioned above that do not have the highlight. Rather than introducing a new focus UI pattern, could you use UI more consistent with existing patterns? Either the fake text-highlight you proposed or something similar to the focus outline that is used for the icon buttons should work (Design has a preference for the former).

2022-09-14 20:26 UTC, danielleflinn commented
@patrickhlauke can you also provide a screen recording of the revised chrome/nvda screen reader functionality similar to the one you uploaded showing current screen reader functionality?

2022-09-14 20:29 UTC, patrickhlauke commented
> @patrickhlauke can you also provide a screen recording of the revised chrome/nvda screen reader functionality similar to the one you uploaded showing current screen reader functionality?

the video in the OP shows the before and (at about 1:00) after (but only for the popup, desktop app is pretty much the same)

2022-09-14 20:31 UTC, patrickhlauke commented
> Thanks for the explanation @patrickhlauke . We definitely should provide a visible focus indicator for the fields you mentioned above that do not have the highlight. Rather than introducing a new focus UI pattern, could you use UI more consistent with existing patterns? Either the fake text-highlight you proposed or something similar to the focus outline that is used for the icon buttons should work (Design has a preference for the former).

i'll have a look. not 100% i can fake text highlighting, as i don't think i can force the browser-native highlighting, so would need to pick some foreground and background colour explicitly. will have a try anyway.

2022-09-19 18:39 UTC, jtouchstonebw commented
The design team has discussed the following options and is ok with either of these options for read-only focus states. Whichever one is easier to implement will work for us. 
![Extension- View item Read only focus state 1@2
![Extension- View item Read only focus state 2@2x](https://user-images.githubusercontent.com/95641831/191091203-af464aa2-2ce5-49a2-b637-df2d76acb278.jpg)
x](https://user-images.githubusercontent.com/95641831/191091182-5e986885-19ba-4636-98df-76675cb5c40c.jpg)

2022-10-02 01:11 UTC, patrickhlauke commented
a heads-up that i'm actually taking some time to make a more radical change proposal here:

* making the `readonly` fields also non-focusable with `tabindex="-1"`
* making sure that all fields have an equivalent copy action button (including `<textarea>`, with a copy button floating in the top-right of the area itself)

this makes the keyboard experience more consistent (compared to current state, where some fields are already readonly inputs, and are focusable despite having an explicit copy button, while others are just static text with a copy button) and cleaner (no need for duplicate focus stops - once on the readonly input, and then on the copy button)

I should have something by end of this weekend for consideration

2022-10-02 22:30 UTC, patrickhlauke commented
@danielleflinn as mentioned, I completely changed approach/took it further with this PR - updated the opening comment to explain the changes.

2022-10-02 23:42 UTC, patrickhlauke commented
additional point: for the changes to the json string files, I only made changes to the `en` version. Please let me know if changes (such as the renaming of the `copyVerificationCodeTotp` string for desktop to `copyVerificationCode`, should also be made as part of the PR, and I can include them. Also happy to include `en-gb` variant and `en-IN` if needed.

2022-10-03 18:56 UTC, patrickhlauke commented
> PS: Only need to add/remove entries from the en/messages.json. This is our master/source for all translations. The rest is done in Crowdin and then pulled back into the clients (~1-2 weeks)

cool, thanks for confirming (I knew it was the case for new strings, but wasn't sure due to that renamed string, but as i'm backing it out now anyway the issue is moot

2022-10-03 19:32 UTC, patrickhlauke commented
@djsmith85 

> Rename of `copyVerificationCodeTotp`

reverted that specific change from this PR. as said, for the other stuff, not sure it'd make sense to split over separate PRs as the new copy buttons do rely on the new strings.

Can, hover, back out the `::selection` change and move to a standalone PR

2022-10-03 19:43 UTC, patrickhlauke commented
@djsmith85 

> Can, hover, back out the `::selection` change and move to a standalone PR

Done - see https://github.com/bitwarden/clients/pull/3675

2022-10-03 19:45 UTC, djsmith85 commented
@patrickhlauke Thank you.

I meant: to extract the buttons with their accompanying strings/messages into a separate PR, keeping the other changes here. I don't see the strings needed for anything else than the buttons (example: copyCardholderName)

2022-10-03 19:47 UTC, patrickhlauke commented
oh, i also completely misread your original comment Daniel. i somehow read it as splitting the copy buttons into one PR, and then the messages change into another PR.

so making this just a change to readonly fields.

i guess this *could* be done, but would feel a bit icky as it just changes the underlying semantics without fixing the issue of keyboard/AT users (assuming i kept them non-focusable). or, if kept focusable, it'd go back to introducing an issue of a lack of focus indication for non-input fields (like passwords/secret fields/textareas), and i wouldn't want to initially push a PR that makes things worse from an #a11y point of view

2022-10-03 19:56 UTC, patrickhlauke commented
if it's ok (though understand not ideal/easy to deal with), i'd like to keep this as a unit and deal with any merge conflicts etc as they arise, unless there's an explicit aspect that would prevent this/stop this from being considered

2022-10-03 20:03 UTC, djsmith85 commented
Thanks Patrick, thats a valid concern, breaking things again if those two potential PRs do not get merged at the same time/make the cut for a release.

I'll leave this up to @bitwarden/dept-design to decide. Once they are good with the changes this will get passed on to a developer review. 

I was only concerned about the scope of the changes in one PR.... Watching out for possibly, my future self 😉 😂

2022-10-12 09:45 UTC, patrickhlauke commented
also, some foreshadowing: as a possible follow-up to this, once all "rows" have at least a "Copy" button, it's then worth considering only showing the action buttons when focus is within a row (`:focus-within`) and/or the mouse is hovering over it. and as a bonus, then adding a touch/mouse handler (not needed for keyboard) that also fires "Copy" as the default action whenever a user clicks/taps anywhere else on the row...similar to what a particular other password manager does...

![two rows - username and password - with one hovered. the hovered one shows a "Copy" option, the other one doesn't](https://user-images.githubusercontent.com/895831/195309672-b3b81cd2-d349-48ff-9f2a-01c8dc98788c.png)

but that's a topic/suggestion for another day. however, this PR would pave the way towards this, if that's a direction you're wanting to go.

2022-12-05 21:17 UTC, danielleflinn requested changes
Design is good with the changes outlined; the team especially appreciates the addition of the copy button on all fields. Please update the new strings to use sentence casing; once this is done, we'll get it approved and reviewed by engineering.

2022-12-05 22:36 UTC, patrickhlauke commented on apps/desktop/src/locales/en/messages.json
> +    "message": "Copy Cardholder Name"
@danielleflinn done

2022-12-05 22:38 UTC, patrickhlauke commented on apps/desktop/src/locales/en/messages.json
> +    "message": "Copy Cardholder Name"
oh sorry, i stupidly just did that one, but you meant all of them of course. give me a minute :)

2022-12-05 22:48 UTC, patrickhlauke commented on apps/desktop/src/locales/en/messages.json
> +    "message": "Copy Cardholder Name"
@danielleflinn there...all done properly this time. not being in the US, I still assume that "Social Security Number" is remains capitalised?

2022-12-06 00:29 UTC, danielleflinn commented on apps/desktop/src/locales/en/messages.json
> +    "message": "Copy Cardholder Name"
Thanks! We actually are using "Social Security number" as it appears on the US government website. Thanks for checking!

2022-12-06 16:35 UTC, djsmith85 commented
@patrickhlauke I know this is a long PR, with discussion and splitting things out over time. 

We love the addition of the copy buttons and would like to ask if you'd be up to adding them, also to the vault-items (login, card, identity) in the web-vault.

Either way you decide, we really appreciate the work you have done so far, and we'll obviously wrap-up the review here.

2022-12-08 11:27 UTC, djsmith85 commented
> @djsmith85 sorry, my email's been out of action the last two days, so not seen notifications and only just stumbled across this comment (and comments you left on the other two PRs). I'll grab some time this week to address this (don't think I ever tried running the web version locally for testing, so that will be exciting...)

@patrickhlauke No worries and thank you, Here's a [link](https://contributing.bitwarden.com/getting-started/clients/web-vault/)  to our setup guide to start up the web vault. Let me know if that works for you.

2022-12-10 01:11 UTC, patrickhlauke commented
@djsmith85 perhaps a silly question, but as I don't normally use the web vault: is there no straight "View" view for entries? I only ever see the "Edit" view right away when choosing an item

![screenshot of the edit dialog for a test card item](https://user-images.githubusercontent.com/895831/206821180-520aa021-0a91-46ef-9adb-04d889c8baf5.png)

2022-12-10 19:05 UTC, patrickhlauke commented
@djsmith85 done ... though admittedly it starts to look a bit busy, particularly because there is no distinction between viewing and editing items in the web vault - this makes keyboard navigation itself possibly more tedious, as now there's always two focus stops per field.

![screenshot of an identity item in the web vault, now with copy buttons on all fields](https://user-images.githubusercontent.com/895831/206871257-8739fbde-2ff7-474d-9f8b-7d664a927d89.png)

taking a step back, is there any plan to actually make the web vault the same/similar to the desktop version?

2022-12-12 17:56 UTC, danielleflinn approved these changes

2022-12-12 19:20 UTC, patrickhlauke commented
@danielleflinn 

> For the notes field copy button, can we move the copy button so it is next to the field label (similar to the "check password" action on the Password input)?

Do you mean just for the web vault, or the desktop/browser as well? And, if you meant just for the web one, note that I tweaked this further from that last screenshot (I've now added this to the OP) to match the approach I took on desktop and browser

![image](https://user-images.githubusercontent.com/895831/207134597-096d622c-f638-4081-af83-1da921bb3687.png)

I think this looks quite slick, but let me know if it needs changing (and if you meant it for desktop/browser as well?)

2022-12-12 19:26 UTC, danielleflinn commented
This works; thanks for providing the updated screenshot; that said it looks like the right top/bottom corners of the notes field have lost their roundness in web vault? Can you double check the corner radius is still being applied?

2022-12-12 19:28 UTC, patrickhlauke commented
@danielleflinn ah, well spotted. it's because that copy button (with hard corners) is actually on top of the textarea. I can apply an extra patch to make *that* specific copy button have a top-right rounded corner though (this wasn't an issue on desktop/browser because there the copy buttons don't have their own button-y stylings)

2022-12-12 19:46 UTC, patrickhlauke commented
@danielleflinn fixed

![screenshot with zoomed-in notes textarea, showing rounded corners all around](https://user-images.githubusercontent.com/895831/207139734-88101393-0c0f-4b22-a2ed-3ade83b3ef39.png)

2022-12-12 20:00 UTC, danielleflinn submitted a review, later dismissed
Looks good thanks Patrick!

2022-12-12 20:57 UTC, patrickhlauke commented
@danielleflinn once this is merged, I may have a crack at the new functionality/behaviour I hinted at ... having those copy buttons only visually appear when mouse is hovering over the field / keyboard focus is on the button (provided you think that's a direction the design team would be happy to go for)

2022-12-14 18:52 UTC, danielleflinn commented
@patrickhlauke you can hold off on only showing the copy buttons on hover. Design avoids only showing actions on hover to improve discoverability of features.

2022-12-16 15:00 UTC, patrickhlauke commented
@Hinton a few aspects in your question that could probably do with a much longer explanation, but I'll try to summarise it ... happy to chat more in depth about it though:

* there is no standard construct for marking up static key/value pairs in a semantic/structural way. the closest you come to it is using a `<table>` with proper `<th>`/`<td>` relationships (which is overkill  for individual key/value pairs, and very inflexible if you want to do it for many key/value pairs without also having a table-like visual presentation) or a description list `<dl>` (with key in `<dt>` and value in `<dd>`) - though the latter is exposed in a strange way in most screen readers.
* using `aria-label`, `aria-labelledby`, `aria-describedby` on static elements without a semantic role (e.g. a regular `<span>` or `<div>`) does not work consistently ... you need to "hang" those on elements that already have a (intrinsic, by virtue of their element itself, or explicit, using `role="..."`) role that expects to have a label/description. see https://www.tpgi.com/short-note-on-aria-label-aria-labelledby-and-aria-describedby/ - so there's also no good/natural way to use ARIA to mark up a key/value pair
* in terms of abusing/perverting HTML elements, because the item view is essentially the read-only version of the edit view, and you can flip between them, it feels less like an abuse of HTML as such. if this was purely a standalone page (with no "edit" view related to it), i'd go for something like the `<dl>` or `<table>` approach, but because there's already the precedent of having the proper inputs when editing, it feels ok (to me) to say that the view itself uses readonly fields.
* "Inputs are quite a bit more restrictive in terms of how we can visually display them. A good example of this is the card numbers" indeed, inputs are restrictive ... but for those cases (see also passwords), note that I actually used a visually hidden input (with the `sr-only` class) and kept the visible, nicely formatted/coloured/etc text (but made that `aria-hidden="true"` so it's not double-announced by screen readers) - see for instance this https://github.com/bitwarden/clients/pull/3485/files#diff-aa27c4cb976574a37f6d42b3e54f39215545c6876a070d3dbf85c3b9bf6db947R30 - so i don't think there's a risk of "degraded experience and/or capability for future changes"
* "Some browser also seem to persist form values in memory longer than non form values, possibly since forms sometimes persist when navigating backwards." not sure what you mean here...you saying that in some browsers, even if the underlying value changed (e.g. the item was edited), it will show the old value? not something i've encountered, and it shouldn't really happen?
* "My other concern is that we are planning on migrating our other clients to the component library after we've completely removed bootstrap from the web vault. This will necessitate large changes to the application and unless we write up guidelines for using inputs (which restricts what we can visually display) I suspect these changes won't be re-applied." as mentioned above, there should not be any restrictions here, since for the values that have special display, the real `<input>` is visually hidden, and the formatted/styled text is there as before, just set to `aria-hidden="true"`

2022-12-23 00:43 UTC, patrickhlauke commented
I'll need a bit of time to resolve the merge conflicts. hoping to carve out some time tomorrow.

2022-12-23 13:44 UTC, patrickhlauke commented
merge conflicts addressed

2023-01-05 12:05 UTC, Hinton commented
What about using something like https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/rowheader_role?

That would let us simplify the required changes to just adding roles to the container, label and value? I haven't tested how well supported those wai-roles are though.

2023-01-05 12:37 UTC, patrickhlauke commented
> What about using something like https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/rowheader_role

you can't just use that in isolation. at that point, you need to effectively build an ARIA table/grid. doable, sure, but then you need to decide if you want to make lots of "mini-tables" for each key/value pair (making it extremely verbose in terms of screen reader output, as it will keep announcing that you're in a table with 1 column and 2 rows or similar) or turn the whole section/view into a giant single grid/table using ARIA. you'd then also need to remove all of that ARIA in edit mode.

2023-01-14 11:08 UTC, patrickhlauke commented
it would probably be good to get a go/no-go decision on this at some point. just to reiterate that the "label with a read-only input when viewing, turning into a label with editable input when editing" approach is, in my view, not as exotic/uncommon - see for instance https://getbootstrap.com/docs/5.3/forms/form-control/#readonly-plain-text (though in bitwarden's case, we're additionally making them inputs non-focusable by default with `tabindex="-1"` because we're also providing custom "Copy" buttons, which makes the ability to set focus to the readonly inputs for copy/pasting purposes when navigating with a keyboard redundant)

2023-01-25 10:41 UTC, patrickhlauke commented
@Hinton @danielleflinn any more thoughts on this?

2023-02-07 01:20 UTC, patrickhlauke commented
@Hinton @djsmith85 should I work on fixing the merge conflicts, or abandon this PR?

2023-02-12 23:48 UTC, patrickhlauke commented
doing a merge on desktop (rather than relying on github's automatic merge/update) seems to have worked fine, without needing to do any manual conflict resolution (unless i somehow managed to mess things up locally)

2023-02-26 00:55 UTC, patrickhlauke commented
i don't want to constantly push on this, but at this point i'm getting concerned that this PR will start going out of sync with other stuff being merged. luckily there's only been two recent cases where some merge conflicts were flagged by github, though then merging locally on desktop seemed to resolve things without the need for any intervention. but it would be good to know what's preventing this currently from being merged. is it just too much of a change? too many concerns with the use of `readme` inputs?

2023-03-06 10:48 UTC, patrickhlauke commented
@djsmith85 @danielleflinn @Hinton ping?

2023-04-18 23:54 UTC, patrickhlauke commented
@djsmith85 @Hinton  is it worth me resolving the merge conflicts, or should I just close this PR now? any indication would be appreciated...

2023-05-01 10:34 UTC, patrickhlauke commented
as we're coming up to 11 months that this PR has been left here, and the merge conflicts are now just piling up as a result... going to close it. shame that this didn't even deign a response though folks...not impressed.

2023-05-01 10:34 UTC, closed without merging