Upgrade windows-rs
bitwarden/clients pull request #3516
Opened 2022-09-13 21:15 UTC by Hinton

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Lots of breaking changes 😢.

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-09-13 21:17 UTC, MGibson1 commented
I'd prefer to get tests running in pipeline prior to merging this one

2022-09-16 15:52 UTC, MGibson1 reviewed
just one clarification

2022-09-16 15:52 UTC, MGibson1 commented on apps/desktop/desktop_native/Cargo.toml
> +manual_test=[]
I'm interested in your thoughts on inverting this to `pipeline_test`.

I assume it's that these prompts are annoying and should never be executed automatically? I think I can get behind that since they cause popups and steal focus.

2022-09-16 16:10 UTC, Hinton commented on apps/desktop/desktop_native/Cargo.toml
> +manual_test=[]
That seems annoying since it means those tests won't be run automatically right? I think it's easy to accidentally forget a test and not have it run in CI that way.

2022-09-19 17:33 UTC, MGibson1 approved these changes

2022-09-29 13:10 UTC, vgrassia requested changes

2022-09-29 13:31 UTC, vgrassia approved these changes

2022-10-24 09:46 UTC, Hinton commented
QA approved, only pipeline changes since @MGibson1 review.

2022-10-24 09:46 UTC, merged