[EC-272] Web workers using EncryptionService
bitwarden/clients pull request #3532
Opened 2022-09-15 06:18 UTC by eliykat

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Very quick POC to illustrate what the web workers PR would look like extending `EncryptionService` instead of creating a new service.

This is rough and not for detailed feedback - just to consider the overall design of the services.

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-09-15 06:26 UTC, eliykat commented on libs/common/src/services/multithreadEncrypt.service.ts
> +  private clear$ = new Subject<void>();
This is now making `EncryptService` stateful, which I am not a fan of. The base version is still stateless, maybe that's fine. But given that all this code will only ever apply to decrypting items, maybe that's an argument for `ItemEncryptService`; I'm not sure.

2022-09-15 06:28 UTC, eliykat commented on libs/common/src/services/multithreadEncrypt.service.ts
> +      keys: keys instanceof SymmetricCryptoKey ? keys : Array.from(keys.entries()),
Taking a single key or a map of keys is difficult to manage, probably not a great approach.

2022-09-15 07:20 UTC, eliykat commented on libs/common/src/services/cryptography/typeMap.ts
> +const typeMap = new Map<string, any>([
I'm not sure that this isn't just adding complexity and maintenance overhead. I wonder whether this is a YAGNI (you aint gonna need it) situation where we should just lock it to Cipher objects for now. They're the only objects we decrypt en masse that would justify a worker; maybe the `multithreadEncryptService` (or whatever) detects whether the `IEncryptable` is `instanceof Cipher` and sends it off to the worker, or otherwise just calls the base class decryption logic for everything else.

2022-09-15 20:51 UTC, MGibson1 commented on libs/common/src/services/multithreadEncrypt.service.ts
> +  private clear$ = new Subject<void>();
This was always going to be stateful because it needs to track the worker and restart it if needed, right?

2022-09-15 20:54 UTC, MGibson1 commented on libs/common/src/services/multithreadEncrypt.service.ts
> +    return await firstValueFrom(
I believe this is a problem -- It appears to assume the first value returned from the worker will be in lock-step to the values this call should make, but I don't think there's any guarantee of that.

Imagine the worker is doing something (time A), then we make a new queued message, then the worker finishes before and returns (time B). We now have a message in our `workerMessages` observable that will be taken to be the response to any calls make to enqueue work between times A and B.

2022-09-16 04:08 UTC, eliykat commented on libs/common/src/services/multithreadEncrypt.service.ts
> +    return await firstValueFrom(
The `filter` operator should address that, it'll only emit a value that matches the message ID, and that's the value caught by `firstValueFrom`.

2022-09-16 04:09 UTC, eliykat commented on libs/common/src/services/multithreadEncrypt.service.ts
> +      keys: keys instanceof SymmetricCryptoKey ? keys : Array.from(keys.entries()),
Fixed by only accepting a single key.

2022-09-16 04:10 UTC, eliykat commented on libs/common/src/services/multithreadEncrypt.service.ts
> +  private clear$ = new Subject<void>();
Yes, definitely. It just feels like it's muddying a class that we explicitly wrote to be stateless. Maybe it doesn't matter because it's all internal state, it's very different to `CryptoService` depending on `StateService`.

2022-09-16 04:12 UTC, eliykat commented on libs/common/src/services/cryptography/typeMap.ts
> +const typeMap = new Map<string, any>([
I'm less concerned about this the more I think about it. Generally applicable code is probably easier to maintain than carving out exceptions for individual cases.

2022-09-19 17:59 UTC, MGibson1 commented on libs/angular/src/services/jslib-services.module.ts
> +      useClass: MultithreadEncryptService,
Shouldn't this depend on some feature flag since we don't want multithread in all clients?

2022-09-19 17:59 UTC, MGibson1 commented on libs/common/src/abstractions/abstractEncrypt.service.ts
> +    keys: SymmetricCryptoKey | Map<string, SymmetricCryptoKey>
Should take a single key to decrypt all `IDecryptable[]` items

2022-09-19 17:59 UTC, MGibson1 commented on libs/common/src/abstractions/crypto.service.ts
> +  getKeysForVaultDecryption: () => Promise<Map<string, SymmetricCryptoKey>>;
I don't think this method is necessary if `IEncryptService` changes the signature of keys to a single key

2022-09-19 17:59 UTC, MGibson1 commented on libs/common/src/services/crypto.service.ts
> +  }
can remove once EncryptServices' signature changes to require a single key

2022-09-19 17:59 UTC, MGibson1 commented on libs/common/src/services/cryptography/typeMap.ts
> +const typeMap = new Map<string, any>([
I had expected this to map to json Initializer functions, rather than constructors.

```typescript
const typeMap = new Map<string, (obj: JsonValue) => unknown)>([
["Cipher", Cipher.fromJSON],
["CipherView", CipherView.fromJSON],
]);

2022-09-19 17:59 UTC, MGibson1 commented on libs/common/src/services/multithreadEncrypt.service.ts
> +            return itemClass.fromJSON(jsonItem) as T;
I don't like how this has to assume a static interface we have no ability to enforce. See my comment on the type map

2022-09-19 17:59 UTC, MGibson1 commented on libs/common/src/services/multithreadEncrypt.service.ts
> +  private workerMessages$: Observable<any>;
It looks like this shouldn't be a class property. It's reconstructed each time `decryptItems` is called.

2022-09-20 00:02 UTC, eliykat commented on libs/angular/src/services/jslib-services.module.ts
> +      useClass: MultithreadEncryptService,
Yep, it's a (mental) TODO item, will implement this shortly. Will just be a simple ternary condition.

2022-09-20 00:03 UTC, eliykat commented on libs/common/src/abstractions/abstractEncrypt.service.ts
> +    keys: SymmetricCryptoKey | Map<string, SymmetricCryptoKey>
Already done as you suggested. Maybe you were reviewing an old commit?

2022-09-20 00:03 UTC, eliykat commented on libs/common/src/abstractions/crypto.service.ts
> +  getKeysForVaultDecryption: () => Promise<Map<string, SymmetricCryptoKey>>;
Yep I agree, already removed when I changed the signature of `encryptService.decryptItems`.

2022-09-21 04:03 UTC, eliykat commented on libs/common/src/services/cryptography/typeMap.ts
> +const typeMap = new Map<string, any>([
This is now done. I changed to using an object literal so that we can extract the keys and require it in the `IDecryptable` and `IDecrypted` interfaces.

2022-09-21 04:14 UTC, eliykat commented on libs/common/src/services/multithreadEncrypt.service.ts
> +  private workerMessages$: Observable<any>;
I wouldn't say it's reconstructed; when we create a new worker, we set up an observable to listen to its messages, and each `decryptItems` call subscribes to that.

I take your point though, it is awkward and probably unnecessary. I've moved this down into the method scope.

2022-09-21 04:35 UTC, eliykat commented on libs/common/src/services/multithreadEncrypt.service.ts
> +            return itemClass.fromJSON(jsonItem) as T;
Addressed in other comment thread

2022-09-21 15:23 UTC, MGibson1 reviewed
A few notes

2022-09-23 06:27 UTC, eliykat commented on libs/common/src/interfaces/IDecrypted.ts
> +}
Not every class requires a `toJSON` method though. Often we can just rely on the default behaviour, which wouldn't satisfy this constraint.

2022-09-29 19:27 UTC, MGibson1 commented on libs/common/src/interfaces/IDecrypted.ts
> +}
right, but in those cases you can satisfy with just a `toJSON() { return this;}`. It also makes it very explicit that you need to think about jsonification.

2022-10-03 01:24 UTC, eliykat commented on libs/common/src/interfaces/IDecrypted.ts
> +}
I was pushing back against this a little because we already tried "make everyone implement `toJSON` methods to show they've thought about it" when we were first dealing with serialization. And we didn't end up going in that direction.

However, I realised that I can implement your suggestion as an optional property. _If_ the class has a `toJSON` method, it must make sure it returns an object with an initializerKey. If the class doesn't have a `toJSON` method, then it'll have default serialization behaviour which will preserve the initializerKey anyway. Happy days, I think.

2022-10-06 19:35 UTC, MGibson1 requested changes
Looks great. I know 23 comments seems like a lot, but it's just a bunch of nits and suggestions.

2022-10-06 19:35 UTC, MGibson1 commented on libs/common/src/services/cipher.service.ts
> +    return decCiphers;
Dang, this is way better

2022-10-06 19:35 UTC, MGibson1 commented on libs/common/src/services/cryptography/classInitializers.ts
> +import { InitializerKey } from "./initializerKey";
It feels a little excessive to split this enum out into another file

2022-10-06 19:35 UTC, MGibson1 commented on libs/common/src/services/cryptography/classInitializers.ts
> +const classInitializers: Record<InitializerKey, (obj: any) => any> = {
It's odd to name this file after a portion of it that _isn't_ exported. I don't think I disagree, just pointing it out. If you have a different name that is more discriptive for this module, I think that would be preferable. Especially after moving `InitializerKey` into here.

2022-10-06 19:35 UTC, MGibson1 commented on libs/common/src/services/cryptography/initializerKey.ts
> +  CipherView = 1,
These shouldn't be numbers, they should just be the class name as a string.
 
If you make them numbers, we'll be forever looking at this file to remember what things are, but TS has no such limitation on enum values.

2022-10-06 19:35 UTC, MGibson1 commented on libs/common/src/services/cryptography/encrypt.worker.ts
> +    const initializer = getInitializer<IDecryptable<any>>(jsonItem.initializerKey);
Seems like the type parameter on `getInitializer` is more of a hindrance than a boon

2022-10-06 19:35 UTC, MGibson1 commented on libs/common/src/services/cryptography/classInitializers.ts
> +export function getInitializer<T>(className: InitializerKey): (obj: Jsonify<T>) => T {
Presumably `T` must extend `IDecryptable`, right?

2022-10-07 02:53 UTC, eliykat commented on libs/angular/src/services/jslib-services.module.ts
>      },
I've changed this to use `useFactory` with a factory function to instantiate the correct provider. Historically we've used inline callbacks for our factories, but I think having it as a separate function helps keep the (already very large) `providers` array readable.

2022-10-07 03:00 UTC, eliykat commented on apps/web/tsconfig.json
> +    "../../libs/common/src/services/**/*.worker.ts"
The only new addition here is `*.worker.ts` - the others have just been bumped to separate lines by prettier.

I found that TS wasn't including the worker file in the compilation by default, presumably it doesn't follow `import.meta` statements when building out its module tree.

2022-10-07 03:05 UTC, eliykat commented on apps/web/src/app/tests/preloaded-english-i18n.module.ts
> +import eng from "../../locales/en/messages.json";
Upgrading the modules to ES2020 means that the old syntax will now import the JSON contents as a module, instead of an object. This threw errors because `i18nService` expects it to be an object; making this change restored the old behaviour and fixed the error.

See https://stackoverflow.com/questions/71009393/why-is-default-required-in-importing-json-file-in-js-code which might explain it better.

2022-10-07 03:24 UTC, eliykat commented on libs/common/src/services/cipher.service.ts
>      });
I don't really like using `reduce` for this kind of operation, it feels awkward. (If I had to put my finger on it, maybe because it's dealing with mutable objects in a functional paradigm.) Here's a fairly direct re-write:

```ts
    const groupedCiphers = ciphers.reduce((group, cipher) => {
      group[cipher.organizationId] ??= [];
      group[cipher.organizationId].push(cipher); // note: push returns the new length, not the array
      return group;
    }, {} as { [orgId: string]: Cipher[] });
```

which is more LOC and harder to read than a simple `forEach` loop.

You can be [trickier with it](https://stackoverflow.com/questions/14446511/most-efficient-method-to-groupby-on-an-array-of-objects) but that starts to feel like code golf to me (and maybe less performant, e.g. array unpacking on every iteration).

I _do_ like map/reduce in general though, I'm open to other examples if I'm just not utilizing it properly.

2022-10-07 03:32 UTC, eliykat commented on libs/common/src/services/cryptography/classInitializers.ts
> +import { InitializerKey } from "./initializerKey";
Initially I had it in this file, but it causes a circular import: `Cipher` imports `InitializerKey` from this file, which also (in the `classInitializers` object imports `Cipher`. Splitting it out avoids this.

2022-10-07 06:59 UTC, eliykat commented on libs/common/src/services/cryptography/initializerKey.ts
> +  CipherView = 1,
> If you make them numbers, we'll be forever looking at this file to remember what things are

Why is that? To me the benefit of enums is that you're just looking at the symbol name in the code and you don't have to care about the underlying value. Maybe unless you're inspecting objects in the debugger?

My reasoning is that this `initializerKey` is being attached to every single instance of these classes, it's more efficient for it to be a number enum than a string. Both when de/serializing large numbers of ciphers, and for other existing operations in the app.

2022-10-09 22:05 UTC, eliykat commented on libs/common/src/abstractions/abstractEncrypt.service.ts
> +import { IDecryptable } from "../interfaces/IDecryptable";
I've renamed as follows:
* `AbstractEncryptService` -> `EncryptService`
* `EncryptService` -> `EncryptServiceImplementation`
* `MultithreadEncryptService` -> `MultithreadEncryptServiceImplementation`

Filenames are also updated accordingly per the ADR.

Given that we're already touching import paths, I've also taken the opportunity to move `EncryptServiceImplementation` into the `cryptography` folder.

2022-10-09 22:09 UTC, eliykat commented on libs/common/src/interfaces/IDecryptable.ts
> +export interface IDecryptable<T extends IInitializerMetadata> extends IInitializerMetadata {
Renamed

2022-10-09 22:09 UTC, eliykat commented on libs/common/src/interfaces/IDecryptable.ts
> +import { SymmetricCryptoKey } from "../models/domain/symmetricCryptoKey";
Done

2022-10-09 22:09 UTC, eliykat commented on libs/common/src/interfaces/IInitializerMetadata.ts
> +import { InitializerKey } from "../services/cryptography/initializerKey";
Done

2022-10-09 22:14 UTC, eliykat commented on libs/common/src/services/cryptography/classInitializers.ts
> +const classInitializers: Record<InitializerKey, (obj: any) => any> = {
Per my other comment, I haven't moved `InitializerKey` here, but I have renamed both the function and the file to `GetClassInitializer`, which I do think is more descriptive.

2022-10-09 22:16 UTC, eliykat commented on libs/common/src/interfaces/IInitializerMetadata.ts
> + * will survive serialization. The enum can then be matched to a constructor or factory method for deserialization.
Done. I just referred to the filename, as that's searchable and a full path is likely to go out of date.

2022-10-09 22:18 UTC, eliykat commented on libs/common/src/interfaces/IDecryptable.ts
> +export interface IDecryptable<T extends IInitializerMetadata> extends IInitializerMetadata {
I went with `TDecrypted` to keep in with the theme (decryptable -> decrypt -> decrypted)

2022-10-09 22:34 UTC, eliykat commented on apps/desktop/config/development.json
> +    "multithreadDecryption": false
I have no strong opinions on it, but seeing as how you suggested it I've gone ahead and done it.

In the process I found that we're not using the `base.json` settings in `config.js`, and we're only merging the config objects 1-level deep, which is overriding rather than merging the flag settings. I've fixed this in desktop, I'm not sure if you have a better idea for how to achieve this. We probably need to update other clients as well.

2022-10-09 22:45 UTC, eliykat commented on libs/common/src/services/cryptography/encrypt.worker.ts
> +    const initializer = getInitializer<IDecryptable<any>>(jsonItem.initializerKey);
Maybe. It's unfortunate that we can't be any more specific, but it does describe the return value as much as possible, which I still prefer even if it ends with `any`.

2022-10-09 22:49 UTC, eliykat commented on libs/common/src/services/cryptography/classInitializers.ts
> +export function getInitializer<T>(className: InitializerKey): (obj: Jsonify<T>) => T {
Not necessarily, because we use it to reconstruct the `View` objects on the way back. It should extend `InitializerMetdata` though, so I've added that.

2022-10-09 22:54 UTC, eliykat commented on libs/common/src/abstractions/abstractEncrypt.service.ts
> +import { IDecryptable } from "../interfaces/IDecryptable";
> We use abstractions and interfaces pretty interchangeably. What do you think about just sticking them in the same folder?

The abstractions folder is exclusively used for abstract services at the moment. I'm not sure whether to start mixing other uses in - it seems useful to have services & their abstractions in on place. Maybe we need a structure like server, where we have an "implementations" folder nested under the abstractions:

```
> services
   some.service.ts
   > implementations
      some.service.implementation.ts
```

2022-10-09 23:03 UTC, eliykat commented on libs/common/src/services/cryptography/multithreadEncrypt.service.ts
> +        defaultIfEmpty([])
Yep! The idea is to avoid a dangling promise if the worker is terminated. It's probably unlikely to ever happen though, the timer is set at 3 minutes and no decryption operation should take that long. But I felt that it should be handled.

For some reason the rxviz share link isn't working, but copy & paste this to https://rxviz.com/ if you want to test.

```
const { interval } = Rx;
const { take, takeUntil, defaultIfEmpty } = RxOperators;

const clear$ = interval(1000).pipe(
  take(1)
)

const webWorker$ = interval(5000).pipe(
  take(1),
  takeUntil(clear$),
	defaultIfEmpty(50))

webWorker$
```

2022-10-09 23:31 UTC, eliykat commented on libs/common/src/services/cipher.service.ts
> +    );
Thank you for pointing out the `Promise.all` thing, now that I look at it again I have no idea why I kept following that pattern! I guess I looked at it once and thought "yep that makes sense". We can also chain `.sort()` on this.

2022-10-09 23:34 UTC, eliykat commented on libs/common/src/services/encrypt.service.ts
> +    await Promise.all(promises);
We don't need to flatten this result (1 array in -> 1 array out). Otherwise done

2022-10-09 23:56 UTC, eliykat commented on libs/common/src/services/cipher.service.ts
>      });
I always find `reduce` a bit awkward for constructing a new object from an existing object like this. I'm not sure I have a great answer why, maybe it's the mix of mutable state + functional programming, maybe I'm just less used to using it. I usually find a `forEach` loop to be simpler to read, this situation included.

Perhaps `reduce` communicates the pattern more effectively though. I've rewritten using `reduce` but (departing from your example below) I've kept the object literal rather than a `Map`. A `Map` just makes us do more work later to unpack it into a usable format, and the handy null assignment operator (`??=`) makes the existing code slightly more terse.

2022-10-11 21:23 UTC, MGibson1 commented on libs/common/src/abstractions/abstractEncrypt.service.ts
> +import { IDecryptable } from "../interfaces/IDecryptable";
Keeping them separate seems fine with me, I just brought it up because interfaces are rare in this repo. Other examples seem to have classes implementing the interface right next to the interface.

2022-10-11 21:26 UTC, MGibson1 commented on apps/desktop/config/development.json
> +    "multithreadDecryption": false
oof yeah, we should probably fix that. I think it's working in web, but CLI, Browser, and Desktop appear to be env config + local.

2022-10-11 21:34 UTC, MGibson1 commented on libs/common/src/services/cryptography/classInitializers.ts
> +import { InitializerKey } from "./initializerKey";
hmm how unfortunate. OK

2022-10-11 21:35 UTC, MGibson1 commented on libs/common/src/services/cryptography/initializerKey.ts
> +  CipherView = 1,
I was primarily thinking about debugging. I might be wrong, though. I wasn't thinking about perf, and that's kind of the point of this changeset.

2022-10-11 21:37 UTC, MGibson1 commented on libs/common/src/services/cryptography/encrypt.worker.ts
> +    const initializer = getInitializer<IDecryptable<any>>(jsonItem.initializerKey);
Yeah, I hadn't gotten to the Multithreaded implementation yet, I think this helps us there. I'm in favor of it.

2022-10-11 21:40 UTC, MGibson1 commented on libs/common/src/services/cryptography/multithreadEncrypt.service.ts
> +        defaultIfEmpty([])
very cool.

Yeah, rxviz has terrible url handling. What's even crazier is that is promises to work by offering share links 🤣

2022-10-11 21:40 UTC, MGibson1 approved these changes
:shipit: 🚀 🌔

2022-10-12 04:55 UTC, eliykat commented
Sending to QA to test on the feature branch before merging 🚀  Applying the `hold` label so I don't forget in the meantime.

2022-10-18 01:56 UTC, eliykat commented
Resolved merge errors and added `MultithreadEncryptService` to the `EncryptServiceFactory`. Will wait until it's through QA before requesting another review.

2022-10-27 06:23 UTC, eliykat commented
This has passed QA but needs a fresh approval for the following changes:
* merging master into this branch to keep it up to date
* adding `multithreadEncryptService` to `encryptServiceFactory` so that it can be used in mv3
* fixing some import statements and updating filename conventions
* disabled a failing test - I've spent a fair bit of time trying to come up with a fix for this, I think we need to add babel or another transformer to the jest config in order to transpile or remove the `import.meta` statement from tests. However I haven't been able to figure that out and we need to merge this for the Nov release, so I'm temporarily disabling it for now.

2022-10-27 18:17 UTC, djsmith85 submitted a review, later dismissed
@eliykat This is looking great and awesome work on this.

Could you please, if you haven't yet, create 2 task (TDL?) so we can re-visit enabling the disabled test -> apps/browser/src/clipboard/clear-clipboard.spec.ts.disabled

and also to check if Node and Jest support ESM as mentioned in apps/web/src/app/core/index.ts

2022-10-27 18:46 UTC, shane-melton approved these changes
Last few commits look good to me as well! Very cool improvement to the encryption service!

2022-10-27 21:20 UTC, eliykat commented
Follow up ticket for fixing testing environment: https://bitwarden.atlassian.net/browse/EC-648

2022-10-27 21:22 UTC, djsmith85 approved these changes

2022-10-27 21:38 UTC, merged