Handle already verified email when resending verification email
bitwarden/clients pull request #3552
Opened 2022-09-16 18:36 UTC by schang1146

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Fix for #2800 where clicking the "Send Email" button in the warning box pops up an error telling the user that the email is already verified.

## Code changes

- **apps/web/src/app/settings/verify-email.component.ts**
Added some logic to check if an email is already verified or not when a user clicks on the "Send Email" button.
Added an EventEmitter to the verify-email component so that it can let its parent know that the email's already verified and that it can close the warning box.
Added code to pop-up a Toast briefly letting the user know that their email is verified.

- **apps/web/src/app/vault/vault.component.html**
Added the EventEmitter to the template to call a new function `updateVerifyEmail`.

- **apps/web/src/app/vault/vault.component.ts**
Added new function `updateVerifyEmail` to update `this.showVerifyEmail` variable.

Feel free to let me know if naming could be better 😅

## Screenshots

I'm getting better at this but the quality is poop.

https://user-images.githubusercontent.com/20074034/190708338-59206a2e-9f3b-4bd8-b601-32ea758a0e72.mp4

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-09-23 08:54 UTC, Hinton requested changes
Hi @schang1146,

Thanks for the contribution! This looks like a great start. I've done an initial review and added a few comments.

2022-09-23 08:54 UTC, Hinton commented on apps/web/src/app/settings/verify-email.component.ts
> +  @Output() verifiedEmitter = new EventEmitter<boolean>();
Angular convention is to prefix event emitters outputs `on`. What do you think about calling this `onVerified`?

2022-09-23 08:54 UTC, Hinton commented on apps/web/src/app/settings/verify-email.component.ts
> +    await this.apiService.refreshIdentityToken();
The purpose of the `actionPromise` is to lock the button from being pressed multiple times. We will need to add all async calls to that promise. I believe creating an async lambda function and putting all calls in it should work.

2022-09-23 20:55 UTC, schang1146 commented on apps/web/src/app/settings/verify-email.component.ts
> +  @Output() verifiedEmitter = new EventEmitter<boolean>();
I like that naming scheme. I'll make that change.

2022-09-23 21:19 UTC, schang1146 commented on apps/web/src/app/settings/verify-email.component.ts
> +    await this.apiService.refreshIdentityToken();
Ah gotcha, didn't look deep enough at what that was doing - my bad! Working on that now.

2022-09-23 21:46 UTC, schang1146 commented on apps/web/src/app/settings/verify-email.component.ts
> +  @Output() verifiedEmitter = new EventEmitter<boolean>();
Renamed all instances of `verifiedEmitter` to `onVerified`.

2022-09-23 21:48 UTC, schang1146 commented on apps/web/src/app/settings/verify-email.component.ts
> +    await this.apiService.refreshIdentityToken();
Done with the changes, let me know what you think.

Added a `getIsVerified` async function to add to `actionPromise` that has all the calls needed to double check a user's email verification status.

2022-09-27 16:41 UTC, Hinton commented on apps/web/src/app/settings/verify-email.component.ts
> +  async getIsVerified(): Promise<boolean> {
Could we change this method to also include the `postAccountVerifyEmail`? That way all the async logic needed for the `actionPromise` happens here and there is no need to assign `actionPromise` multiple times.

 At the same time we should rename this function since we're no longer just checking if it's verified.

The end result would be something like:
```ts
async send()
  if (this.actionPromise != null)
		return;
	}
	
	try {
		this.actionPromise = this.verifyEmail()
	} catch (e) {
	  this.logService.error(e);
	}
	this.actionPromise = null;
}
```

2022-09-27 16:41 UTC, Hinton commented on apps/web/src/app/vault/vault.component.ts
> +  updateVerifyEmail(bool: boolean) {
We should look into a better name for this method. Since we are inverting the condition it's not a simple update. I think `emailVerified(verified: boolean)` might work better.

2022-09-28 20:25 UTC, schang1146 commented on apps/web/src/app/vault/vault.component.ts
> +  updateVerifyEmail(bool: boolean) {
Thanks for helping me with the naming. Pushed it up.

2022-09-28 20:27 UTC, schang1146 commented on apps/web/src/app/settings/verify-email.component.ts
> +  async getIsVerified(): Promise<boolean> {
Yep, I grouped up the async logic into the (now-renamed) function `verifyEmail` so that we're only assigning to `actionPromise` and `await`-ing it once.

2022-09-29 09:30 UTC, Hinton approved these changes
I think this looks good, thanks for working through the review comments. Going to have our QA team test this before merging.

2022-09-29 09:30 UTC, Hinton commented on apps/web/src/app/settings/verify-email.component.ts
> +  }
I typically prefer to use guards clauses here. But not a strong preference.

```suggestion
    if (await this.tokenService.getEmailVerified()) {
      this.onVerified.emit(true);
      this.platformUtilsService.showToast("success", null, this.i18nService.t("emailVerified"));
      return;
    }
    
    await this.apiService.postAccountVerifyEmail();
    this.platformUtilsService.showToast(
      "success",
      null,
      this.i18nService.t("checkInboxForVerification")
    );
  }
```

2022-09-29 17:07 UTC, schang1146 commented on apps/web/src/app/settings/verify-email.component.ts
> +  }
I like the suggestion! I don't mind making those changes, feel free to commit the suggestion or I can make them and test it out later tonight (PST time).

2022-09-30 08:35 UTC, Hinton approved these changes
Thanks!

2022-10-28 14:08 UTC, Hinton commented
Merging this into a feature branch to let QA test it first.

2022-10-28 14:08 UTC, merged

2023-05-10 06:10 UTC, nikhilagastya commented
hey is this issue still open?

2023-05-10 06:23 UTC, schang1146 commented
I think the issue's closed. Haven't heard further feedback that it's broken.

#2810 wasn't closed because the PR was linked after it was merged.

2023-05-10 09:57 UTC, djsmith85 commented
@schang1146 Thanks again for the contribution and for raising this.
@nikhilagastya I'm going to close #2810 but if the issue persists, please comment on there and we can re-open if needed

2023-05-10 16:49 UTC, nikhilagastya commented
Sure @djsmith85 ,thanks alot !