Ps 1081/split out api methods into api cipher attachment api
bitwarden/clients pull request #3554
Opened 2022-09-17 10:45 UTC by cyprain-okeke

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
Added abstractions for CipherAttachmentApiServiceAbstraction

Added implementations for CipherAttachmentApiServiceAbstraction in CipherAttachmentApiService

Updated all references to new CipherAttachmentApiServiceAbstraction

Deleted methods in CipherService abstraction and apiService that relates to Cipher attachment.

Fixed the import path for CipherAttachmentApiServiceAbstraction

## Code changes

- **libs/common/src/abstractions/cipher/cipher-attachment-api.service.abstraction.ts:** added the file and moved attachment cipher services from abstractions/api.service.ts to it.
- **libs/common/src/services/cipher/cipher-attachment-api.service.ts:** added the file implementation for the abstractions/cipher-attachment-api.service.abstraction.ts.

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-09-27 16:49 UTC, MGibson1 requested changes
Next round of changes

2022-09-27 16:49 UTC, MGibson1 commented on libs/common/spec/services/cipher.attatchment.service.spec.ts
> +  const cipher: CipherView = new CipherView();
Use jest-mock-extended, not substitute: https://adr.bitwarden.com/decisions/0006-clients-use-jest-mocks

2022-09-27 16:49 UTC, MGibson1 commented on libs/common/spec/services/cipher.attatchment.service.spec.ts
> +    };
use jest-mock-extended, then this should be a spy automatically

2022-09-27 16:49 UTC, MGibson1 commented on libs/common/spec/services/cipher.attatchment.service.spec.ts
> +      );
I don't think you need to mock implementation. You can watch the calls with any spy.

2022-09-27 16:49 UTC, MGibson1 commented on libs/common/src/services/cipher/cipher-attachment-api.service.ts
> +  }
With the changes happening due to #3553, we can remove support for these methods.

2022-09-27 18:39 UTC, cyprain-okeke commented on libs/angular/src/components/share.component.ts
>    @Input() cipherId: string;
Yes , CipherId is used in other like apps/desktop/src/app/vault/vault.component.ts, apps/browser/src/popup/vault/share.component.ts

2022-09-27 18:57 UTC, cyprain-okeke commented on libs/angular/src/components/attachments.component.ts
>    @Input() cipherId: string;
I have to remove it as  @Input() and created a cipherId because it is used by other AttachmentsComponent that extends the BaseAttachmentsComponent

2022-09-27 22:02 UTC, cyprain-okeke commented on libs/common/src/services/cipher/cipher-attachment-api.service.ts
> +  }
the method has been removed

2022-10-03 19:09 UTC, MGibson1 requested changes

2022-10-03 19:09 UTC, MGibson1 commented on apps/browser/src/popup/vault/attachments.component.ts
> +import { FileUploadService as FileUploadServiceAbstraction } from "@bitwarden/common/abstractions/fileUpload.service";
This should be a dependency on CipherAttachmentApiService, not components directly.

2022-10-03 19:09 UTC, MGibson1 commented on libs/common/src/services/fileUpload.service.ts
> +    private cryptoService: CryptoService
All these new dependencies are unexpected. This is a slim functionality service that shouldn't have many other dependencies.

2022-10-03 19:09 UTC, MGibson1 commented on libs/common/src/services/fileUpload.service.ts
> +        await this.cipherAttachmentApiService.deleteCipherAttachmentAdmin(
What I meant was for `cipherAttachmentApiService` to depend on `fileUploadService`, and `fileUploadService` would take care of the specifics regarding azure vs bitwarden file uploads.

2022-10-04 21:06 UTC, MGibson1 requested changes
Looks like this is getting really close!

Just a few small issues left

2022-10-04 21:06 UTC, MGibson1 commented on libs/common/spec/services/cipher.service.spec.ts
> +      expect(result.organizationId).toEqual(model.organizationId);
This doesn't seem to be testing much, what's the goal here?

2022-10-05 23:00 UTC, MGibson1 requested changes

2022-10-05 23:00 UTC, MGibson1 commented on libs/common/src/services/fileUpload.service.ts
> +  }
Wish we could keep these in cipherAttachmentApi... can you think of a way to keep them there without a circular reference?

We could have a revert callback in the signature of `cipherAttachment` or better yet, catch the throw in the attachment api service and handle reverting there.

2022-10-06 12:31 UTC, cyprain-okeke commented on libs/common/src/abstractions/fileUpload.service.ts
> +  deleteCipherAttachment: (id: string, attachmentId: string) => Promise<any>;
this deleteCipherAttachmentAdmin is used outside the class. Which Why I still leave it in the abstract

2022-10-10 19:22 UTC, MGibson1 approved these changes
looks basically ready to go. Nice job 👍 

LMK if you need me to re-review should you make some more commits from the small comments I left.

2022-10-10 19:22 UTC, MGibson1 commented on libs/common/src/services/cipher/cipher-attachment-api.service.ts
> +  private async creatBlobObject(
please correct spelling

2022-10-10 19:22 UTC, MGibson1 commented on libs/common/src/services/cipher/cipher-attachment-api.service.ts
> +  async saveAttachmentRawWithServer(
Does this method need to be public?

2022-10-10 19:22 UTC, MGibson1 commented on libs/common/src/services/cipher/cipher-attachment-api.service.ts
> +  async shareManyWithServer(
This method appears to be unused

2022-10-10 20:23 UTC, cyprain-okeke commented on libs/common/src/services/cipher/cipher-attachment-api.service.ts
> +  async saveAttachmentRawWithServer(
Yes, because is used in /clients/apps/cli/src/commands/create.command.ts  and /clients/libs/angular/src/components/attachments.component.ts

2022-10-10 20:26 UTC, cyprain-okeke commented on libs/common/src/services/cipher/cipher-attachment-api.service.ts
> +  async shareManyWithServer(
the method is called in /clients/apps/web/src/app/vault/bulk-share.component.ts

2022-10-10 21:08 UTC, MGibson1 approved these changes

2022-10-26 19:57 UTC, djsmith85 commented on apps/cli/src/commands/share.command.ts
> +import { CipherAttachmentApiServiceAbstraction } from "./../../../../libs/common/src/abstractions/cipher/cipher-attachment-api.service.abstraction";
Please update the import path to use `@bitwarden/common`

2022-10-27 09:31 UTC, djsmith85 requested changes
@cyprain-okeke This is only a partial review but  @justindbaur and me will continue later today. These are just some findings from last night.

2022-10-27 11:37 UTC, cyprain-okeke commented on libs/angular/src/components/attachments.component.ts
>      this.cipher = await this.cipherDomain.decrypt();
since the this.loadCipher() returns this.cipherDomain, Matt requested that I remove it because we already have this.cipherDomain

2022-10-27 11:47 UTC, djsmith85 commented on libs/angular/src/components/attachments.component.ts
>      this.cipher = await this.cipherDomain.decrypt();
Yes, if `this.loadCipher()` is only present and called within the BaseAttachment component I'd agree. The [OrgVaultAttachment-component](https://github.com/bitwarden/clients/blob/abe68b0f0001daf18f0bceb59753ffabb9ceab51/apps/web/src/app/organizations/vault/attachments.component.ts#L54-L57) relies on `loadCipher()` being called by the [BaseComponent](https://github.com/bitwarden/clients/blob/abe68b0f0001daf18f0bceb59753ffabb9ceab51/libs/angular/src/components/attachments.component.ts#L19) during `init()` which will be triggered with `ngOnInit()`. If that does not happen then the logic encapsulated on `Org/Vault/Attachment.loadCipher()` will never be executed.

2022-10-27 12:36 UTC, cyprain-okeke commented on libs/angular/src/components/attachments.component.ts
>      this.cipher = await this.cipherDomain.decrypt();
The previous logic inside the loadCipher() is "await this.cipherService.get(this. cipherId)". Where this.cipherId is input from the calling component. But I remove cipherId and do "await this.cipherService.get(this. cipherId)" from the calling component and return this.cipherDomain. Which was while it seems loadCipher() is no longer needed.

2024-03-21 12:42 UTC, closed without merging