Ps 1291 fix extension icon updates
bitwarden/clients pull request #3571
Opened 2022-09-20 21:42 UTC by MGibson1

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Adds icon updating to manifest V3

Also extracts badges in general to a separate concern from main background and context menus.

## Code changes

TODO

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

# Draft
waiting on #3425

2022-10-11 13:27 UTC, justindbaur requested changes

2022-10-11 13:27 UTC, justindbaur commented on apps/browser/src/background/service_factories/two-factor-service.factory.ts
> -  const service = await factory(
Does this service not actually need to be inited or are we removing that responsibility from the factories?

2022-10-11 13:27 UTC, justindbaur commented on apps/browser/src/background/service_factories/storage-service.factory.ts
> +    if (BrowserApi.manifestVersion == 3) {
nit: Strict equals

2022-10-11 13:27 UTC, justindbaur commented on apps/browser/src/browser/browserApi.ts
> +      ? (win as any).opr.sidebarAction
I don't _think_ you need to `win as any` for `opr` stuff now.

2022-10-11 13:27 UTC, justindbaur commented on apps/browser/src/browser/browserApi.ts
> +      : (win as any).chrome.sidebarAction;
Here either I believe.

2022-10-11 13:27 UTC, justindbaur commented on apps/browser/src/decorators/session-sync-observable/session-syncer.ts
> +    if (BrowserApi.manifestVersion != 3) {
nit: Strict equals

2022-10-11 13:27 UTC, justindbaur commented on apps/browser/src/listeners/update-badge.ts
> +};
Hopefully these can utilize what's in [here](https://github.com/bitwarden/clients/blob/master/apps/browser/src/globals.d.ts).

2022-10-11 16:42 UTC, MGibson1 commented on apps/browser/src/background/service_factories/two-factor-service.factory.ts
> -  const service = await factory(
not quite sure why these changes were included, we should be init-ing. Thanks

2022-10-11 18:25 UTC, justindbaur submitted a review, later dismissed

2022-10-19 13:46 UTC, MGibson1 commented
Ready to go from QA. Needs merging for safari tests

2022-10-19 13:54 UTC, justindbaur approved these changes
LGTM

2022-10-19 13:55 UTC, merged