[PS-817] Add Generate Password Shortcut to MV3
bitwarden/clients pull request #3575
Opened 2022-09-21 15:28 UTC by justindbaur

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Add ability to generate a password with `Ctrl+Shift+9` (by default) and have the password get cleared from the clipboard based on the users setting. This also fixes the autofill that was broken at some point. In addition it also takes advantage of the service factories.

## Code changes

- **apps/browser/src/background.ts:** Add alarms listener.
- **apps/browser/src/globals.d.ts:** Add types for Opera stuff
- **apps/browser/src/content/miscUtils.ts:** Add helper content script for copying text to the clipboard.
- **apps/browser/src/listeners/onCommandListener.ts:** Add in a handler for generating and copying password.
- **apps/browser/src/services/browserPlatformUtils.service.ts:** Change various checks to be MV3 safe since window is unreferencable. Also remove unnecessary `any` casts.
- **apps/browser/src/manifest.v3.json:** Add reference to new content script.
- **libs/common/src/abstractions/passwordGeneration.service.ts:** Add types for password generation options.

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-09-29 16:55 UTC, MGibson1 commented
We need to decide how we're going to organize commands. I, personally, would like a file-per-feature approach rather than what is currently in the code, which is more of a file-per-listener approach.

for example, this PR wouldn't use `onCommandListenter` and `onAlertListener`. It would just be a `generate-password` file, which would expose listeners for registration in `background.ts`. I have an example of this structure in #3571.

2022-09-29 19:25 UTC, MGibson1 commented on apps/browser/src/listeners/onCommandListener.ts
>  const doAutoFillLogin = async (tab: chrome.tabs.Tab): Promise<void> => {
All of the changes to this method are unrelated to this work, can you please revert and we'll handle separately?

2022-09-30 14:18 UTC, justindbaur commented on apps/browser/src/background/service_factories/event-service.factory.ts
> +    useNoopService: boolean;
Removed it

2022-10-05 23:31 UTC, MGibson1 requested changes

2022-10-05 23:31 UTC, MGibson1 commented on apps/browser/src/background/service_factories/generate-password-to-clipboard-command.factory.ts
> +export function generatePasswordToClipboardCommandFactory(
I'm not convinced I want these commands to have factories.

2022-10-05 23:31 UTC, MGibson1 commented on apps/browser/src/browser/sendTabsMessage.ts
> +export const sendTabsMessage = <T = unknown>(
I feel like we usually put this kind of thing in BrowserApi, I kind of like this better...

2022-10-05 23:31 UTC, MGibson1 commented on apps/browser/src/content/misc-utils.ts
> +    case "copyText":
Just confirming -- our messages are totally sandboxed command and all, right? I don't see another way of doing this, but I don't want to expose to outside scripts that we're putting something in the clipboard.

2022-10-05 23:31 UTC, MGibson1 commented on apps/browser/src/listeners/on-alarm-listener.ts
> +export const onAlarmListener = async (alarm: chrome.alarms.Alarm) => {
This is not likely to be how alarms end up working. I think it's better to tackle clearing later when we know how they'll be done.

@djsmith85 alternatively, can you give some tips on the required changes here?

2022-10-05 23:31 UTC, MGibson1 commented on apps/browser/src/listeners/onCommandListener.ts
> +  const command = await generatePasswordToClipboardCommandFactory(cache, options);
If we get rid of the command factory, this line will simply change to `new generatePasswordToClipboardCommand(factory, factory)`, which seems fine.

2022-10-05 23:31 UTC, MGibson1 commented on apps/browser/webpack.config.js
> +  config.entry["content/misc-utils"] = "./src/content/misc-utils.ts";
any reason to not go this route for mv2 as well?

I know we don't _need_ to, but fewer differences is better.

2022-10-06 13:09 UTC, justindbaur commented on apps/browser/webpack.config.js
> +  config.entry["content/misc-utils"] = "./src/content/misc-utils.ts";
I don't believe the clipboard API has across the board compatibility yet with how we want to use it. Safari still locks it behind certain user gestures. https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard

2022-10-06 14:11 UTC, djsmith85 commented on apps/browser/src/listeners/on-alarm-listener.ts
> +export const onAlarmListener = async (alarm: chrome.alarms.Alarm) => {
This looks good to me for now. The onAlarmsListener will be similar to what we are doing for the OnCommandsListener. A switch on the alarm's name and then passing off handling the alarm event to a specific service.

2022-10-06 14:12 UTC, justindbaur commented on apps/browser/src/listeners/on-alarm-listener.ts
> +export const onAlarmListener = async (alarm: chrome.alarms.Alarm) => {
I have no expectation that this would be the final form of this and it's a relatively small amount of code so it can be moved to where ever it's needed pretty easily.

2022-10-06 14:15 UTC, djsmith85 commented on apps/browser/src/browser/browserApi.ts
> +
Is this aiming to replace the existing `BrowserApi.tabSendMessage` at some point?

2022-10-06 14:18 UTC, justindbaur commented on apps/browser/src/browser/browserApi.ts
> +
It would replace some and another `Promise` based one would replace others but all would have tighter limits on types. There aren't a ton of different tabs messages I can try to type them to the best of my ability and replace the existing one if you'd like.

2022-10-06 17:54 UTC, djsmith85 commented on apps/browser/src/browser/browserApi.ts
> +
Talked about this with Justin, and changing these call-sites and adding types is out of scope for this PR.

Still love the idea but should be followed up via a tech debt ticket.

2022-10-06 19:39 UTC, MGibson1 commented on apps/browser/src/listeners/on-alarm-listener.ts
> +export const onAlarmListener = async (alarm: chrome.alarms.Alarm) => {
I thought the alarm system was going to be something that iterated through a set of chores to determine if work was needed rather than fire a specific alarm.

The method used here requires use to have many more alarms if we're looking to get > 1 min resolution

Write
Preview
Add heading text
Add bold text, <Cmd+b>
Add italic text, <Cmd+i>
Add a quote, <Cmd+Shift+.>
Add code, <Cmd+e>
Add a link, <Cmd+k>
Add a bulleted list, <Cmd+Shift+8>
Add a numbered list, <Cmd+Shift+7>
Add a task list, <Cmd+Shift+l>
Directly mention a user or team
Reference an issue or pull request
Add saved reply
Attach files by dragging & dropping, selecting or pasting them.
Styling with Markdown is supported
Update comment
Cancel

2022-10-11 19:19 UTC, djsmith85 approved these changes
This is looking good!

2022-10-14 12:59 UTC, MGibson1 approved these changes

2022-10-17 20:47 UTC, MGibson1 approved these changes

2022-10-18 17:03 UTC, merged