Sentence case web vault
bitwarden/clients pull request #3577
Opened 2022-09-21 16:36 UTC by danielleflinn

## Type of change
Copy updated. Transition web vault strings to use sentence case for all UI elements, except the following terms:

• Branded Names: Provider(s) + Provider Portal, Send(s) + Send, Directory Connector
• Plan Names: Premium, Families, Teams, Enterprise

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [X] Other
```

## Objective

Currently the use of Title and Sentence case is inconsistent throughout the web vault. To improve the UI consistency, readability, and localization, this change updates strings to use sentence case. 

## Code changes
locales/en/messages.json

## Screenshots

<img width="995" alt="Screen Shot 2022-09-21 at 8 48 20 AM" src="https://user-images.githubusercontent.com/43477473/191552059-88675804-3928-4857-8fba-54ace97194d7.png">

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-09-22 10:38 UTC, patrick-bitwarden commented on apps/web/src/locales/en/messages.json
> +    "message": "Proceeding will also log you out of your current session, requiring you to log back in. You will also be prompted for two-step login again, if setup. Active sessions on other devices
"setup" is a noun, this would be "set up."

2022-09-22 10:59 UTC, patrick-bitwarden commented on apps/web/src/locales/en/messages.json
> +    "message": "Two-step Login adds a layer of protection to your accounts. Turn on two-wtep login using Bitwarden Authenticator for these accounts or use an alternative method."
typo here: "wtep"

2022-09-22 10:59 UTC, patrick-bitwarden commented on apps/web/src/locales/en/messages.json
> +    "message": "GB of storage to Rrmove"
Typo: "rrmove"

2022-09-22 10:59 UTC, patrick-bitwarden commented on apps/web/src/locales/en/messages.json
> +    "message": "Turned off two-step login."
Excellent change.

2022-09-22 10:59 UTC, patrick-bitwarden commented on apps/web/src/locales/en/messages.json
> +    "message": "Items in disabled organizations cannot be accessed. Contact your organization owner for assistance."
Should we stop using "disabled" here too?

2022-09-22 10:59 UTC, patrick-bitwarden commented on apps/web/src/locales/en/messages.json
> +    "message": "You've been invited to setup a new Provider. To continue, you need to log in or create a new Bitwarden account."
Can you explain why Provider is a proper noun? Send makes sense to me, but this doesn't seem like the same circumstance.

2022-09-22 10:59 UTC, patrick-bitwarden commented on apps/web/src/locales/en/messages.json
> +    "message": "Vault export disabled"
As above, should we remove "disabled" here?

2022-09-22 10:59 UTC, patrick-bitwarden commented on apps/web/src/locales/en/messages.json
> +    "message": "Single Sign On service URL"
Inconsistent with elsewhere - here you have "Single Sign On" and elsewhere you have "Single sign-on"

2022-09-22 10:59 UTC, patrick-bitwarden commented on apps/web/src/locales/en/messages.json
> +    "message": "Key connector error: make sure key connector is available and working correctly."
Is "Key Connector" on the level of "Send"?

2022-09-22 10:59 UTC, patrick-bitwarden commented on apps/web/src/locales/en/messages.json
> +    "message": "The SCIM API key successfully rotated",
I think remove "The" to be consistent with other messages (e.g., "Account saved")

2022-09-22 16:16 UTC, danielleflinn commented on apps/web/src/locales/en/messages.json
> +    "message": "You've been invited to setup a new Provider. To continue, you need to log in or create a new Bitwarden account."
Because one of our interfaces is the 'Provider Portal' there was desire from product to keep any reference to Provider capitalized.

2022-09-22 16:17 UTC, danielleflinn commented on apps/web/src/locales/en/messages.json
> +    "message": "Single Sign On service URL"
Just missed this one; nice catch.

2022-09-22 17:16 UTC, danielleflinn commented on apps/web/src/locales/en/messages.json
> +    "message": "Key connector error: make sure key connector is available and working correctly."
Re-discussed this with technical writing and aligned on keeping it uppercase. Thanks for the callout

2022-09-22 19:35 UTC, fschillingeriv commented on apps/web/src/locales/en/messages.json
> +    "message": "Lost access to all of your two-factor providers? Use your recovery code to deactivate all two-factor providers from your account."
Should we change the 2 instances "two-factor" here to "two-step" to match what we usually call the offering. May not be critical, since they're common synonyms.

2022-09-22 19:35 UTC, fschillingeriv commented on apps/web/src/locales/en/messages.json
>      "message": "FIDO U2F Security Key"
Maybe lowercase "security key" here to match other instances?

2022-09-22 19:37 UTC, fschillingeriv commented on apps/web/src/locales/en/messages.json
>      "message": "“File password”  and “Confirm File Password“ do not match."
Should lowercase " "Confirm file password" here to match the string it's referencing.

2022-09-22 19:38 UTC, fschillingeriv commented on apps/web/src/locales/en/messages.json
>      "description": "Minimum Special Characters"
Should probably lowercase the description here as well.

2022-09-22 19:38 UTC, fschillingeriv commented on apps/web/src/locales/en/messages.json
>      "description": "To clear something out. example: To clear browser history."
"Example" should be uppercased to match others, I think

2022-09-22 19:39 UTC, fschillingeriv commented on apps/web/src/locales/en/messages.json
> +    "message": "Proceeding will change your account email address. It will not change the email address used for two-factor authentication. You can change this email address in the two-step login set
Ditto comment above about changing "two-factor" to "two-step"

2022-09-22 19:40 UTC, fschillingeriv commented on apps/web/src/locales/en/messages.json
>      "message": "Enabling two-step login can permanently lock you out of your Bitwarden account. A recovery code allows you to access your account in the event that you can no longer use your normal t
Should we change the "ex." to match other places we're gotten rid of the latin abbreviations?

2022-09-22 19:42 UTC, fschillingeriv commented on apps/web/src/locales/en/messages.json
> +    "description": "Vault Health Reports can be used to evaluate the security of your Bitwarden individual or organization vault."
IMO "Vault health reports" should be sentence-case as well

2022-09-22 19:43 UTC, fschillingeriv commented on apps/web/src/locales/en/messages.json
>      "message": "URLs that start with http:// don’t use the best available encryption. Change the Login URIs for these accounts to https:// for safer browsing."
I think "logins" should be lowercase when referring to item types

2022-09-22 19:43 UTC, fschillingeriv commented on apps/web/src/locales/en/messages.json
> +    "message": "Two-step Login adds a layer of protection to your accounts. Set up two-step login using Bitwarden Authenticator for these accounts or use an alternative method."
Probably lowercase L in "Two-step login"

2022-09-22 19:44 UTC, fschillingeriv commented on apps/web/src/locales/en/messages.json
> +    "message": "Two-step Login adds a layer of protection to your accounts. Set up two-step login using Bitwarden Authenticator for these accounts or use an alternative method."
Same with "authenticator"

2022-09-22 19:50 UTC, fschillingeriv commented on apps/web/src/locales/en/messages.json
> +    "message": "GB of storage to Remove"
Definitely a lowercase "r" in "remove"

2022-09-22 20:22 UTC, fschillingeriv approved these changes

2022-09-22 20:22 UTC, fschillingeriv commented on apps/web/src/locales/en/messages.json
> +    "message": "You've been offered a free Bitwarden Families Plan organization. To continue, you need to log in to the account that received the offer."
Find&Replace says this is the only "Plan" that's caps!

2022-09-22 20:22 UTC, fschillingeriv commented on apps/web/src/locales/en/messages.json
>      "description": "Premium Membership"
Find&Replace says this is the only "Membership" that's capitalized!

2022-09-23 13:44 UTC, fschillingeriv commented on apps/web/src/locales/en/messages.json
>      "message": "Required if Entity ID is not a URL."
Totally agree, but does that mean line `4681` should be capitalized?

2022-09-23 13:48 UTC, danielleflinn commented on apps/web/src/locales/en/messages.json
>      "message": "Required if Entity ID is not a URL."
Nope; they are 2 different fields in the SSO form. Line `4681` starts with 'SP' so 'entity' can remain lowercase and there is a separate field that is called `Entity ID`

2022-10-12 12:11 UTC, patrick-bitwarden requested changes
Found a handful of things to fix, sorry for the delay!

2022-10-12 12:11 UTC, patrick-bitwarden commented on apps/web/src/locales/en/messages.json
> +    "message": "Turn on SSO"
Is the verb tense right on this prompt? Should it be "SSO turned on." or "SSO activated."? It seems like yes, based on other similar prompts (like vaultAccessedByProvider).

2022-10-12 12:11 UTC, patrick-bitwarden commented on apps/web/src/locales/en/messages.json
> +    "message": "Turn off SSO"
Same as above.

2022-10-12 12:11 UTC, patrick-bitwarden commented on apps/web/src/locales/en/messages.json
> +    "message": "Activate Key Connector"
Same as above.

2022-10-12 12:11 UTC, patrick-bitwarden commented on apps/web/src/locales/en/messages.json
> +    "message": "Deactivate Key Connector"
Same as above.

2022-10-19 17:45 UTC, merged