Sentence case browser
bitwarden/clients pull request #3578
Opened 2022-09-21 16:46 UTC by danielleflinn

## Type of change
Copy updated. Transition web vault strings to use sentence case for all UI elements, except the following terms:

• Branded Names: Provider(s) + Provider Portal, Send(s) + Send, Directory Connector
• Plan Names: Premium, Families, Teams, Enterprise

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Currently the use of Title and Sentence case is inconsistent throughout the product. To improve the UI consistency, readability, and localization, this change updates strings to use sentence case.

## Code changes

_locales/en/messages.json

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-09-22 22:43 UTC, patrick-bitwarden requested changes
Just one suggestion here.

2022-09-22 22:43 UTC, patrick-bitwarden commented on apps/browser/src/_locales/en/messages.json
> +    "message": "Auto-filled item and saved URI"
Should we make this match? "Item auto-filled and URI saved" is clunky, but I am raising it up anyway.

2022-09-22 22:47 UTC, danielleflinn commented on apps/browser/src/_locales/en/messages.json
> +    "message": "Auto-filled item and saved URI"
Both are a bit clunky; but your suggestion does match our confirmation writing guidelines better so I will update.

2022-09-26 14:55 UTC, patrick-bitwarden approved these changes

2022-10-12 00:38 UTC, merged