[PS-1530]Sentence case desktop
bitwarden/clients pull request #3579
Opened 2022-09-21 16:58 UTC by danielleflinn

## Type of change

Copy updated. Transition web vault strings to use sentence case for all UI elements, except the following terms:

• Branded Names: Provider(s) + Provider Portal, Send(s) + Send, Directory Connector
• Plan Names: Premium, Families, Teams, Enterprise

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [X] Other
```

## Objective

Currently the use of Title and Sentence case is inconsistent throughout the product. To improve the UI consistency, readability, and localization, this change updates strings to use sentence case.

## Code changes

locales/en/messages.json

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-09-22 22:33 UTC, patrick-bitwarden requested changes
Looks good, just one change!

2022-09-22 22:33 UTC, patrick-bitwarden commented on apps/desktop/src/locales/en/messages.json
> +    "message": "Social security number"
This is a proper noun and should probably stay as it was.

2022-09-22 22:35 UTC, danielleflinn commented on apps/desktop/src/locales/en/messages.json
> +    "message": "Social security number"
Thoughts on 'Social Security number'? Looking at their [website](https://www.ssa.gov/ssnumber/) it looks like they keep the 'number' part lowercase.

2022-09-22 22:39 UTC, patrick-bitwarden commented on apps/desktop/src/locales/en/messages.json
> +    "message": "Social security number"
Yes, I think that's the right way to go!

2022-09-22 22:39 UTC, danielleflinn commented on apps/desktop/src/locales/en/messages.json
> +    "message": "Social security number"
All updated and I'll make sure the other clients follow suite. Thank you for the review!

2022-09-22 22:48 UTC, patrick-bitwarden approved these changes

2022-10-13 13:24 UTC, patrick-bitwarden requested changes
Just the one typo.

2022-10-13 13:24 UTC, patrick-bitwarden commented on apps/desktop/src/locales/en/messages.json
>      "description": "Make the first letter of a work uppercase."
Here's that "work" for "word typo again.

2022-10-13 15:05 UTC, patrick-bitwarden approved these changes

2022-10-18 21:46 UTC, danielleflinn commented
@patrick-bitwarden apologies on dismissing the stale review. QA caught 1 typo but we are good to go with this now pending a code review.

2022-10-21 11:08 UTC, patrick-bitwarden approved these changes

2022-10-21 15:23 UTC, merged