Enable strict templates
bitwarden/clients pull request #3601
Opened 2022-09-23 12:25 UTC by Hinton

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Enable `strictTemplates` for Angular https://angular.io/guide/template-typecheck#strict-mode. This provides a couple of benefits but most noteworthy to us are:

- Better VsCode support thanks to Angular Language Services which requires strict templates. (This enables jumping to variables from templates, type checking and more)
- Identify type errors in templates.

## Code changes

Most of the changes done were:

- Wrap with `$any`.
	- Any reference to `.loading` needed to be wrapped with `$any()` since angular can't understand that we add a `loading` element to the native element. This will go away with https://github.com/bitwarden/clients/pull/3548.
	- Wrong types, we add `checked` and a few other attributes to existing objects without changing the types. This is technically wrong but changing it now is to invasive. We should continue to refactor and eliminate these.
- Remove unknown variables
- Add variables which were only used by sub-components.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-11-22 11:31 UTC, Hinton commented on apps/browser/src/popup/vault/vault-select.component.html
> -          [ngClass]="{ active: !myVaultOnly && !selectOrganizationId }"
These weren't available, and we don't seem to have an active class for browser.

2022-11-22 11:43 UTC, Hinton commented on apps/web/src/app/organizations/vault/ciphers.component.ts
> -  accessEvents = false;
Moved to base component.

2022-11-22 11:47 UTC, Hinton commented on apps/web/src/app/settings/organization-plans.component.html
> -          <small *ngIf="selectablePlan.hasPremiumAccessOption && premiumAccessAddon">
Can we safely remove this? `premiumAccessAddon` was always null.

2022-11-22 11:48 UTC, Hinton commented on apps/web/src/app/settings/organization-plans.component.html
> -            {{ selectablePlan.premiumAccessOptionCost | currency: "$" }} {{ "monthAbbr" | i18n }} =
`premiumAccessOptionCost` is always null which makes this whole block seem weird.

2022-11-24 02:23 UTC, eliykat requested changes

2022-11-24 02:23 UTC, eliykat commented on apps/browser/src/popup/vault/current-tab.component.ts
> +  protected async load() {
TIL you can access protected methods from templates 🤯 maybe we should be using `protected` as the default for methods that are called from the template, instead of `public`? (or maybe it's not that important given that you shouldn't be calling methods on other components classes anyway)

2022-11-24 09:53 UTC, Hinton commented on apps/browser/src/popup/vault/current-tab.component.ts
> +  protected async load() {
I think it's good practice to always use the most strict. JS itself doesn't have visibility decorators on methods which means it's just a compiler check.

2022-11-24 09:54 UTC, Hinton commented on apps/browser/src/popup/accounts/set-password.component.ts
> +  @ViewChild(PasswordStrengthComponent) passwordStrengthComponent: PasswordStrengthComponent;
We probably can, but I didn't want to significantly change anything. Maybe the more appropiate solution is to just remove the viewchild and the references?

2022-11-24 09:55 UTC, Hinton commented on apps/web/src/app/tools/import-export/import.component.html
>      </ng-container>
Keeper is disabled. It's commented out in the ts file due to some reason.

2022-11-24 09:57 UTC, Hinton commented on apps/web/src/app/settings/two-factor-recovery.component.html
> -        [organizationId]="organizationId"
Yes, but there is no OrganizationID member in `two-factor-recovery`

2022-11-24 10:06 UTC, Hinton commented on bitwarden_license/bit-web/src/app/providers/manage/people.component.html
> -            <span *ngIf="u.type === userType.Custom">{{ "custom" | i18n }}</span>
Not for providers, copy pasta I think.

2022-11-24 10:06 UTC, Hinton commented on bitwarden_license/bit-web/src/app/providers/manage/people.component.html
> -                <a
Yes

2022-11-24 10:12 UTC, Hinton commented on apps/browser/src/popup/accounts/set-password.component.ts
> +  @ViewChild(PasswordStrengthComponent) passwordStrengthComponent: PasswordStrengthComponent;
Seems we refactored this for some reason but never updated the set-password.

2022-11-24 10:16 UTC, Hinton commented on apps/web/src/app/tools/import-export/export.component.html
> -        [disabled]="form.loading || disabled"
True, updated.

2022-11-28 01:01 UTC, eliykat commented on apps/web/src/app/tools/import-export/import.component.html
>      </ng-container>
True, looks like Daniel disabled it - I've followed up with him.

2022-11-28 01:02 UTC, eliykat approved these changes

2022-11-28 01:02 UTC, eliykat commented
Please create a tech debt ticket to clean up remaining references to those deprecated plan options.

2022-11-28 17:59 UTC, merged

2022-11-28 18:00 UTC, Hinton commented
TDL-212 is the ticket for the plans.