[EC-449] Event log user for SCIM events
bitwarden/clients pull request #3643
Opened 2022-09-28 14:12 UTC by r-tome

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [X] Other
```

## Objective

Currently in the Event Log, SCIM events are captured under the user “Unknown”. The user should be “SCIM”.
These changes parse property `SystemUser` from the events API response to display on the events table.

## Code changes

Related server changes on [this PR](https://github.com/bitwarden/server/pull/2306).

- **apps/web/src/app/organizations/manage/events.component.ts:** Displaying the `SystemUser` value on each Event row
- **libs/common/src/enums/eventSystemUser.ts:** Added new Enum to identity the possible `EventSystemUser` types
- **libs/common/src/models/response/eventResponse.ts:** Parsing the `SystemUser` property value from the API response

## Screenshots

![image](https://user-images.githubusercontent.com/108268980/192801782-10acc630-cf08-440b-b197-9ec69c30bb86.png)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-10-17 15:57 UTC, MGibson1 requested changes

2022-10-17 15:57 UTC, MGibson1 commented on apps/web/src/app/organizations/manage/events.component.ts
> +
This only solved the userName in web viewer, please also update CLI and exporters (check out InstallationId on `EventResponse` and update both accordingly -- probably that model needs a `getUserName` helper)

2022-10-20 09:22 UTC, r-tome commented on apps/web/src/app/organizations/manage/events.component.ts
> +
As we've discussed: the CLI does not have an Events command. The exporter has been updated.

2022-11-02 08:26 UTC, eliykat requested changes

2022-11-02 08:26 UTC, eliykat commented on libs/common/src/enums/event-system-user.ts
> +export enum EventSystemUser {
I think it's convenient to use the enum key in the UI, but it's unusual. A developer would not generally expect this (usually it's just for our convenience when reading the code), so I think we should flag it explicitly.

```suggestion
// Note: the enum key is used to describe the EventSystemUser in the UI. Be careful about changing it.
export enum EventSystemUser {
```

2022-11-02 08:26 UTC, eliykat commented on bitwarden_license/bit-web/src/app/providers/manage/events.component.ts
> -    return userId != null && this.providerUsersUserIdMap.has(userId)
This is used for Provider events, e.g. adding or removing a provider user. SCIM only applies to Organization events. So I don't think we need any changes here, other than to bring in the `installationId` stuff that you removed from the base component.

2022-11-02 08:26 UTC, eliykat commented on apps/web/src/app/organizations/manage/events.component.ts
> +      if (r.systemUser != null) {
Please refactor to avoid this nested `if`.

2022-11-02 09:58 UTC, eliykat approved these changes

2022-11-09 12:13 UTC, merged