PS 1569 update on command listener
bitwarden/clients pull request #3647
Opened 2022-09-28 19:27 UTC by MGibson1

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Cleanup `onCommandListener` to use service factories.

Also removes NoopEventService, since that's not in line with how we really want autofill to behave.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-09-29 13:15 UTC, justindbaur commented
This would have a lot of merge conflicts with #3575 Where I also convert the on command listener to use service factories.

2022-10-07 09:48 UTC, djsmith85 requested changes

2022-10-07 09:48 UTC, djsmith85 commented on apps/browser/src/listeners/onCommandListener.ts
> +  const cachedServices: CachedServices = {};
Shouldn't we use/preserve the cachedServices instead of wiping it everytime we autofill?

2022-10-11 16:23 UTC, MGibson1 commented
Removed Needs-qa due to low risk and MV3 specificity

2022-10-11 16:24 UTC, merged