[EC-87] Edit Group Dialog
bitwarden/clients pull request #3651
Opened 2022-09-29 20:17 UTC by shane-melton

## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Implements the new Edit Group dialog with tabs for Group Info, Members, and Collections. This depends on https://github.com/bitwarden/clients/pull/3563 being merged first and there is a TODO to implement the ng-select once the CL integration is completed in https://github.com/bitwarden/clients/pull/3383.

## Code changes

- **app/organizations/manage/group-add-edit.component.ts:** Updates the add/edit group modal component to use the Dialog component and content tabs along with the bulk of the implementation changes.

- **app/organizations/manage/groups.component.ts:** Update the Group Tab/table to support opening the Dialog component and navigating to the correct tab depending on which column the users clicks. (e.g. clicking on Collections will open the Collection tab in the dialog)

- **apps/web/src/scss/base.scss:** The `base.scss` styles were conflicting with the CL button styles, so the css selector was modified to exclude `bitButton`/`bitIconButton` directives. 

- **libs/angular/src/pipes/user-type.pipe.ts:** Helper pipe to convert the `OrganizationUserType` enum to a i18n string for rendering.

## **FormSelectionList Utility**
<img width="852" alt="image" src="https://user-images.githubusercontent.com/8764515/193126633-68b9b86b-201a-4022-b7ff-dc7d0a21ffe3.png">

The `FormSelectionList.ts` is utility class to aid in creating these "selection list controls" (as seen above). It supports selecting/deselecting items, keeping items sorted, and synchronizing the selected items with an array of FormControls/values to be used with Reactive Forms. 

The primary reasoning behind this utility is that it is difficult to keep Reactive Form controls in sync with other component data like a list of `OrganzationUserDetails`. The `OrganzationUserDetails` is used for rendering the control (e.g. the user's name, email, role, etc.) while only the user Id is necessary for the `FormControl`. There was [a proposal](https://github.com/angular/angular/issues/19686) to allow storing metadata on a FormControl which would likely be applicable here, but it's not currently being considered by Angular.

The `FormSelectionList` utility makes it easy to toggle items between the selected/unselected state and provide starting form values for selected items (e.g. starting permission values for Collections). It also keeps the two lists (selected and deselected) sorted to avoid iterating/re-sorting the lists on every change detection cycle (which could be expensive for larger lists).   

#### Example Usage
```ts
// Creating the selection list and defining the FormControl factory and sorting comparator 
collectionList = new FormSelectionList<CollectionView, GroupCollectionSelection>(
  (item) =>
    this.formBuilder.group({
      id: item.id,
      permission: this.initialPermission, // Validators could be specified here if desired
    }),
  (a, b) => this.i18nService.collator.compare(a.name, b.name)
);

// Using the FormSelectionList in a FormGroup
groupForm = this.formBuilder.group({
  accessAll: new FormControl(false),
  name: new FormControl("", Validators.required),
  externalId: new FormControl(""),
  members: this.memberList.formArray,
  collections: this.collectionList.formArray, // The formArray is also strongly typed 
});

// Populating the collection list and selecting the initial values
this.collectionList.populateItems(
  this.collections,
  this.group.collections.map((gc) => ({
    id: gc.id,
    permission: convertToPermission(gc),
  }))
);

// Selecting an item based with a starting form value
this.collectionList.selectItem(addedId, {
  permission: this.initialPermission,
});

// Deselecting an item
this.collectionList.deselectItem('some-id')
```

## Screenshots

<img width="1324" alt="image" src="https://user-images.githubusercontent.com/8764515/193132915-08f80969-286e-43ec-86d7-3079145951f5.png">

<img width="1316" alt="image" src="https://user-images.githubusercontent.com/8764515/193132966-9db58176-dba2-4824-9cd5-3e9d1f0ba48a.png">

<img width="1315" alt="image" src="https://user-images.githubusercontent.com/8764515/193133014-5a589c4f-7ac6-4d84-b976-6f51bbb82fa1.png">

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-10-03 13:29 UTC, coroiu reviewed
Great work with the `FormSelectionList`. I wonder if could be moved into a general CL component together with the actual table view

2022-10-03 13:29 UTC, coroiu commented on apps/web/src/app/organizations/manage/groups.component.ts
> +    });
suggestion: use the new dialog service from CL

2022-10-03 13:29 UTC, coroiu commented on libs/angular/src/utils/FormSelectionList.ts
> +export class FormSelectionList<
**suggestion:** Since this is such a general class that is supposed to be used in a lot of places, can make sure that it is properly tested?

2022-10-03 20:52 UTC, shane-melton commented on apps/web/src/app/organizations/manage/groups.component.ts
> +    });
I believe this is using the CL dialog service, is there something more you're referring to?

2022-10-03 20:53 UTC, shane-melton commented on libs/angular/src/utils/FormSelectionList.ts
> +export class FormSelectionList<
Yep, I plan to add tests for this one

2022-10-04 08:39 UTC, coroiu commented on apps/web/src/app/organizations/manage/groups.component.ts
> +    });
Oh yeah you are correct, it's not being used like I expected it to so I thought it was the old service :)

**suggestion:** don't use direct references to the underlying component instance. Instead use `DIALOG_DATA` to inject inputs and use `dialogRef.close` to return the result of the dialog. For example see: https://github.com/bitwarden/clients/pull/3638/files#diff-9ceff1fb28f1502333c7eae9166a561b952e1370535f1cd9760884bfa53fc8ad

2022-10-28 06:53 UTC, coroiu commented on apps/web/src/app/organizations/manage/group-add-edit.component.html
> +<form #form [formGroup]="groupForm" (ngSubmit)="submit()" [appApiAction]="formPromise">
suggestion: consider replacing `appApiActions` using the new async actions

I have to do a full review of the changes to this PR, but I saw this row mentioned in my own PR and wanted to comment on it straight away

2022-11-01 13:42 UTC, coroiu requested changes

2022-11-01 13:42 UTC, coroiu commented on apps/web/src/app/organizations/manage/group-add-edit.component.html
> +<form #form [formGroup]="groupForm" (ngSubmit)="submit()" [appApiAction]="formPromise">
suggestion: here too, use the new async actions

2022-11-01 13:42 UTC, coroiu commented on apps/web/src/app/organizations/manage/group-add-edit.component.html
> +      <div *ngIf="loading">
issue: I think we're handling loading differently. Collection dialog shows spinner without dialog while loading. This dialog shows spinner inside dialog if I understand this correctly

2022-11-01 13:42 UTC, coroiu commented on apps/web/src/app/organizations/manage/group-add-edit.component.html
> +      <bit-tab-group *ngIf="!loading" [preserveContent]="true" [selectedIndex]="tabIndex">
question: is it necessary to preserve content? Also a curiosity from my side: is it possible to write `<bit-tab-group preserveContent [selectedIndex]="tabIndex">`?

2022-11-01 13:42 UTC, coroiu commented on apps/web/src/app/organizations/manage/group-add-edit.component.html
> +            <input bitInput type="text" formControlName="name" required />
suggestion: Remove `required`. It should be automatically applied by `bitInpu` when using `Validators.required`

2022-11-01 13:42 UTC, coroiu commented on apps/web/src/app/organizations/manage/group-add-edit.component.ts
> +  protected resultType = GroupAddEditDialogResultType;
suggestion: use PascalCase is possible
```suggestion
  protected PermissionMode = PermissionMode;
  protected ResultType = GroupAddEditDialogResultType;
```

2022-11-01 13:42 UTC, coroiu commented on apps/web/src/app/organizations/manage/group-add-edit.component.html
> +        [bit-dialog-close]="resultType.Canceled"
thought: ohhhh, I did not know this 👍  feels like an odd naming scheme, I'm guessing it's a bug and it should say `[bitDialogClose]="resultType.Canceled"`

2022-11-01 13:42 UTC, coroiu commented on apps/web/src/app/organizations/manage/group-add-edit.component.ts
> +}
suggestion: remove the numbers, they'll be assigned automatically

2022-11-01 13:42 UTC, coroiu commented on apps/web/src/app/organizations/manage/group-add-edit.component.ts
> +}
Oh now I get it, it's used for specifying index, ignore this! :D

2022-11-01 13:42 UTC, coroiu commented on apps/web/src/app/organizations/manage/group-add-edit.component.ts
> +    await Promise.all([collectionsPromise, membersPromise]);
issue: there is a pretty big difference between how this dialog fetches data and how the collection dialog does it. I know it's a dialog but it still feels like we could benefit from using observables. Take a look at how I've done it, I'm curious to hear your thoughts

https://github.com/bitwarden/clients/blob/c5e4ff06cda8a3323e6d2d61e78bfdb95f031657/apps/web/src/app/organizations/shared/components/collection-dialog/collection-dialog.component.ts#L67-L159

2022-11-01 13:42 UTC, coroiu commented on apps/web/src/app/organizations/manage/group-add-edit.component.ts
> +        this.formPromise = this.groupService.postGroup(this.organizationId, request);
suggestion: In the collection admin service I just create a method `save` and let the service figure out exactly what it needed to do. It also takes `View` as an input

https://github.com/bitwarden/clients/blob/c5e4ff06cda8a3323e6d2d61e78bfdb95f031657/apps/web/src/app/organizations/core/services/collection-admin.service.ts#L52-L61

2022-11-01 13:42 UTC, coroiu commented on apps/web/src/app/organizations/manage/groups.component.html
> +              <button type="button" bitMenuItem (click)="edit(g, 1)">
suggestion: Maybe use the enum here to specify tab since we already have it

2022-11-01 13:42 UTC, coroiu commented on apps/web/src/app/organizations/manage/groups.component.ts
>        }
thought: Not sure what is best here but I just converted the result into promise. Looked a little bit simpler to read

https://github.com/bitwarden/clients/blob/c5e4ff06cda8a3323e6d2d61e78bfdb95f031657/apps/web/src/app/organizations/manage/collections.component.ts#L141-L146

2022-11-01 13:42 UTC, coroiu commented on apps/web/src/app/organizations/services/abstractions/group/group.service.abstraction.ts
>  export class GroupServiceAbstraction {
suggestion: We can skip abstractions if we're not placing the services inside the common lib

2022-11-01 22:21 UTC, shane-melton commented on apps/web/src/app/organizations/manage/group-add-edit.component.ts
> +}
Yeah, I wanted to be explicit here because the value is significant

2022-11-01 22:23 UTC, shane-melton commented on apps/web/src/app/organizations/manage/groups.component.html
> +              <button type="button" bitMenuItem (click)="edit(g, 1)">
Good idea!

2022-11-01 22:27 UTC, shane-melton commented on apps/web/src/app/organizations/manage/group-add-edit.component.html
> +        [bit-dialog-close]="resultType.Canceled"
Ah, you're right, I missed that it shouldn't be snake-case for the directive. Should probably be fixed in another ticket that can be merged to `master` directly though

2022-11-01 22:31 UTC, shane-melton commented on apps/web/src/app/organizations/manage/group-add-edit.component.html
> +      <bit-tab-group *ngIf="!loading" [preserveContent]="true" [selectedIndex]="tabIndex">
It might actually be possible to leave off `preserveContent` as the form values are tracked by the reactive `formGroup`. Although, I don't exactly know what effect adding/removing the DOM repeatedly will have on the reactive form. Seemed safer to just keep the content in the DOM like you would a normal form (where removing the form elements would wipe their value).

And yep, its possible, but we need to do something like this for the `preserveContent` input:
https://github.com/bitwarden/clients/blob/7c4f3ac5e9550072d25ebdc34598c8a8bdec1f7a/libs/components/src/dialog/dialog/dialog.component.ts#L11-L17

2022-11-01 22:51 UTC, shane-melton commented on apps/web/src/app/organizations/manage/group-add-edit.component.html
> +      <div *ngIf="loading">
Oh, where does the Collection dialog spinner render then? 

@danielleflinn Do you know how these dialog/modal components should look while in a "loading" state? (Maybe this could be a feature of the dialog component/service since it appears to be a fairly common practice)

2022-11-01 23:50 UTC, danielleflinn commented on apps/web/src/app/organizations/manage/group-add-edit.component.html
> +      <div *ngIf="loading">
Are we calling all data for each content tab before opening the dialog? 

The spinner being in the dialog follows our pattern for existing modal loading states, though it does result in a visual "jump" of the modal height once the content loads (at least in production org admin views). We'll likely continue following this pattern for now but let me double check with the rest of the design team. 

I agree if we keep the spinner in the modal it would make sense to include it in the dialog component/service.

2022-11-01 23:56 UTC, shane-melton commented on apps/web/src/app/organizations/manage/group-add-edit.component.html
> +      <div *ngIf="loading">
The API calls are happening right when the dialog is initialized, which I believe means it is firing API request immediately after the Dialog is opened. 

And okay, I'll keep the spinner in the dialog for now, and we can re-evaluate moving this in another ticket after you're able to confer with the rest of the design team.

2022-11-02 07:40 UTC, coroiu commented on apps/web/src/app/organizations/manage/group-add-edit.component.html
> +      <div *ngIf="loading">
@danielleflinn This is how the edit collection dialog looks at the moment (throttled network).

![Recording 2022-11-02 at 08 23 29](https://user-images.githubusercontent.com/2285588/199425760-54039f3d-4608-4951-88cd-83822eb25b3a.gif)

The reasoning for adding spinners outside the dialog is because I made the dialog header also dependent on the data it's loading. It previously got some pre-fetched data from the component that was opening it, but I wanted it to be as standalone as possible.

![image](https://user-images.githubusercontent.com/2285588/199426504-8a47c540-d491-4c92-902c-9d698c7b79dd.png)

I realize now however that this is different from how the old dialogs worked.

![Recording 2022-11-02 at 08 35 40](https://user-images.githubusercontent.com/2285588/199427662-aed2adb9-a6d5-4d8d-9e42-d1230a14d351.gif)

I personally like the spinner outside the modal a lot better (the old user access dialog just looks weird while loading), but I'll change it back if you don't like it! And if we change it back, maybe we can like, center the spinner or something? 😄

2022-11-02 07:43 UTC, coroiu commented on apps/web/src/app/organizations/manage/group-add-edit.component.html
> +      <bit-tab-group *ngIf="!loading" [preserveContent]="true" [selectedIndex]="tabIndex">
Reason I ask is that I don't preserve the content and I've never had any issues. I didn't even realize it might be a problem 😅 I think it's safe to remove it from DOM

Never mind the attribute then!
We should have a rule that boolean attributes should be coerced like the snippet above :)

2022-11-02 07:51 UTC, coroiu commented on apps/web/src/app/organizations/manage/group-add-edit.component.html
> +        [bit-dialog-close]="resultType.Canceled"
Yeah skip and fix in another PR

2022-11-02 09:32 UTC, coroiu commented
Btw I renamed my dialog to `collection-dialog.component.ts` instead of `collection-add-edit.component.ts`

2022-11-02 15:57 UTC, danielleflinn commented on apps/web/src/app/organizations/manage/group-add-edit.component.html
> +      <div *ngIf="loading">
Thanks for the explanation @coroiu ; I talked with the team and we want to keep the existing spinner pattern for now. Design will work on developing a more comprehensive strategy for loadings states across pages, clients, and dialogs for future improvement.

2022-11-03 08:39 UTC, coroiu commented on apps/web/src/app/organizations/manage/groups.component.ts
> +      positionStrategy: this.overlay.position().global().centerHorizontally(),
issue: this blocks clicks on the backdrop for the whole width of the dialog. Make the following adjustment to fix :) 

```suggestion
      positionStrategy: this.overlay.position().global().centerHorizontally().top(),
```

2022-11-08 14:57 UTC, shane-melton commented on apps/web/src/app/organizations/manage/groups.component.html
> +              <button type="button" bitMenuItem (click)="edit(g, 1)">
Done

2022-11-08 14:58 UTC, shane-melton commented on apps/web/src/app/organizations/manage/groups.component.ts
> +      positionStrategy: this.overlay.position().global().centerHorizontally(),
Fixed, nice catch!

2022-11-08 14:58 UTC, shane-melton commented on apps/web/src/app/organizations/manage/group-add-edit.component.ts
> +  protected resultType = GroupAddEditDialogResultType;
Done

2022-11-08 14:58 UTC, shane-melton commented on apps/web/src/app/organizations/manage/group-add-edit.component.html
> +            <input bitInput type="text" formControlName="name" required />
Done

2022-11-10 04:19 UTC, shane-melton commented on apps/web/src/app/organizations/manage/group-add-edit.component.ts
> +          this.changeDetectorRef.detectChanges();
I'm not the biggest fan of using `ChangeDetectorRef` here myself, but it was one of the simpler alternatives I could think of. Another option would be wrapping the `groupForm.patchValue` in a `setTimeout(..., 0)`, but I thought `detectChanges` was more explicit.

For context as to why this is necessary:

The access selector component is almost too smart for its own good and will not let you select values that are not available in the list of selectable `items`. So, when we assign `this.members` (the `items`) and immediately patch the form value before Angular's change detection has a chance to run, no values are actually assigned for the `members` form control. This wasn't a problem before when there were `await`s between everything which allowed the change detection to run in between and populate the available `items`. 

We'll probably need to tweak the access selector component to support selected values that don't exist yet, but that is a bit out of scope for ticket.

2022-11-10 04:24 UTC, shane-melton commented on apps/web/src/app/organizations/services/abstractions/group/group.service.abstraction.ts
>  export class GroupServiceAbstraction {
I'm actually kind of fan of keeping the abstraction to keep consistent with `libs/common`. With that said, I'm still open to removing it if its more trouble than its worth.

2022-11-10 04:27 UTC, shane-melton commented on apps/web/src/app/organizations/views/collection-access-selection.view.ts
> +export class CollectionAccessSelectionView extends View {
@coroiu I pretty much cloned this from your branch. I tried to cherry-pick it, but was struggling to pick it cleanly. We'll need to keep an eye out when we merge both branches.

2022-11-10 04:31 UTC, shane-melton commented on apps/web/src/app/organizations/manage/group-add-edit.component.html
> +      <bit-tab-group *ngIf="!loading" [preserveContent]="true" [selectedIndex]="tabIndex">
I tried removing the `preserveContent` directive, and didn't see any issues either 🤷 So its removed now

> We should have a rule that boolean attributes should be coerced like the snippet above :)

Agreed, I think it looks much better than having `[attribute]="true"`

2022-11-10 04:32 UTC, shane-melton commented on apps/web/src/app/organizations/manage/group-add-edit.component.html
> +<form #form [formGroup]="groupForm" (ngSubmit)="submit()" [appApiAction]="formPromise">
Done, those new async actions are so much nicer to use!

2022-11-10 04:32 UTC, shane-melton commented on apps/web/src/app/organizations/manage/group-add-edit.component.html
> +<form #form [formGroup]="groupForm" (ngSubmit)="submit()" [appApiAction]="formPromise">
Done

2022-11-10 12:45 UTC, coroiu approved these changes
Looking good! 

It seems I managed to re-create those duplicated response comments that you managed to make on my own PR. Apparently they happen when you start reviewing file changes, go back and start responding to conversations, and then going back and committing your review. I understand what the GitHub team was trying to accomplish but... no. 😅

2022-11-10 12:45 UTC, coroiu commented on apps/web/src/app/organizations/manage/group-add-edit.component.ts
> +        this.group = group;
Nice refactor!

2022-11-10 12:45 UTC, coroiu commented on apps/web/src/app/organizations/manage/group-add-edit.component.ts
> +          this.changeDetectorRef.detectChanges();
Thanks for the explanation! I agree that it's a good compromise to be able to merge this PRs. Let's look into this again in a future PR

2022-11-10 12:45 UTC, coroiu commented on apps/web/src/app/organizations/services/abstractions/group/group.service.abstraction.ts
>  export class GroupServiceAbstraction {
I removed the abstraction when I moved the collection admin service after I talked with Oscar who told me that they don't use abstractions either in secret manager

2022-11-10 12:45 UTC, coroiu commented on apps/web/src/app/organizations/views/collection-access-selection.view.ts
> +export class CollectionAccessSelectionView extends View {
No worries, thanks for heads-up! Guess this will teach me to create better commits, you never know when they might get cherry-picked 😁

2022-11-10 12:45 UTC, coroiu commented on apps/web/src/app/organizations/manage/group-add-edit.component.html
> +<form #form [formGroup]="groupForm" (ngSubmit)="submit()" [appApiAction]="formPromise">
Glad you like them! 😄

2022-11-10 12:45 UTC, coroiu commented on apps/web/src/app/organizations/manage/group-add-edit.component.ts
> +    await Promise.all([collectionsPromise, membersPromise]);
Really like the changes you made! Resolving comment

2022-11-10 12:45 UTC, coroiu commented on apps/web/src/app/organizations/manage/group-add-edit.component.ts
> +        this.formPromise = this.groupService.postGroup(this.organizationId, request);
I saw that you added a save method to the group service, looks nice, resolving!

2022-11-11 10:41 UTC, coroiu commented on apps/web/src/app/organizations/manage/group-add-edit.component.html
> +      <bit-tab-group *ngIf="!loading" [preserveContent]="true" [selectedIndex]="tabIndex">
Sounds good to me! Resolving!

2022-11-14 21:08 UTC, merged