[SG-58] Avatar color selector
bitwarden/clients pull request #3691
Opened 2022-10-05 01:14 UTC by BrandonM-Bitwarden

## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

We want to add the ability for users to select the avatar color that will represent an account in the header of the app, so that they can better distinguish between accounts with similar or the same initials. 

## Code changes

Backend: https://github.com/bitwarden/server/pull/2330

\+ dynamic-avatar.component – A component that encapsulates the bit-avatar component and listens for changes in the avatar color values via the AvatarService.
\+ selectable-avatar.component – A component that encapsulates the bit-avatar component and reacts to click events by toggling their selection state and firing events.
~ navbar.comonent – Changed bit-avatar to dynamic-avatar so it can react to changes.
\+ change-avatar.component – The components that gets put into a modal and allows users to pick avatar colors as needed.
~ profile.component - Changed bit-avatar to dynamic-avatar so it can react to changes and added a button to open the change-avatar modal.
~ loose-components.module – Added needed component references.
~ organization-name-badge.component – Made color rely on a state lookup and fallback to default.
~ messages.json – language stuff.
~ jslib-services.module – Added new services references.
\+ avatar-update.service – Added service that handles loading and saving colors from state and api along with emitting events.
~ api.service – Added new avatar color API endpoints.
~ state.service – Added new avatar color state endpoints.
~ utils.ts – Added RegEx Validator for hex colors.
~ account.ts – Added color property.
\+ update-avatar.request – Added request body model for API endpoint save call.
~ profile.response – Added color property.
~ avatar.component – Added more sizes and title input.

## Screenshots
![chrome_5YNFJhjWCM](https://user-images.githubusercontent.com/107377945/200408318-5aa002ac-127f-4de9-b6ac-85fbcf19023f.png)
Button to open modal

![chrome_2jg2iCiTSY](https://user-images.githubusercontent.com/107377945/200408227-044383cc-9df9-4793-97ac-f1d8ae697d41.png)
Avatar change modal

![chrome_ot1HiOjtPD](https://user-images.githubusercontent.com/107377945/200408236-2c527e00-cbe1-4a4d-9120-d7e05c32be0d.png)
Custom color picker

![chrome_o3atJpgh1A](https://user-images.githubusercontent.com/107377945/200408241-6ad2efa0-4aa9-4d40-8258-1554736cdc0c.png)
Avatar colors 

![chrome_ROvPPDpMRz](https://user-images.githubusercontent.com/107377945/200408255-c618230c-b7f8-43d1-8d1a-30cc45f22c04.png)
Colors used elsewhere!

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-10-13 13:27 UTC, differsthecat reviewed
I'm not seeing this change here, but can you update the `OrganizationNameBadgeComponent` to use the color selected by the user?

2022-10-24 09:41 UTC, Hinton commented
I skimmed the PR, since I've migrated the old avatars to the new component library component. Some things to consider:

1. Should the users custom color be visible to everyone or only themselves?
	- If only for themselves, how do we handled it in user lists like organization people?
	- If not only for themselves, we need a way to send in the required data vs fetching it from state
2. To me it feels like we should be building a new "smart" component on top of the avatar component. The avatar component currently handles a few different use cases.
	- Users (themselves & other users)
	- Organizations & Providers

2022-11-07 18:45 UTC, differsthecat commented on libs/common/src/services/stateMigration.service.ts
> +        (await this.get<string>(v1Keys.avatarColor)) ?? defaultAccount.settings.avatarColor,
Any reason this is here? I don't think we need this as this is a new setting for state service and not something that needs to be migrated but correct me if I am wrong.

2022-11-08 21:42 UTC, differsthecat commented on libs/common/src/services/account/avatar-update.service.ts
> +    return color;
Is adding this setting to state service to prevent too many calls to the server to get this value?
What happens here if the user sets a different color in a different browser? Will it always load the value in state if it has been set before?

2022-11-14 14:30 UTC, differsthecat commented on libs/common/src/services/account/avatar-update.service.ts
> +    return color;
Got it; if we are saving the value to the database, I think we need to retrieve it from there as well and not only load the value from state service. Then if a user changes the color in another browser, it should be applied to all browsers.

I think think the best approach here may be to add this value to the user's profile. If you look at the `emailVerified` value on a user, you can see how this is handled. The value is saved in state service, but it is updated in sync service when a sync happens. This way if a user updates their avatar color in one browser, it will apply to all others after a sync.

2022-11-14 15:07 UTC, differsthecat commented on libs/common/src/abstractions/account/avatar-update.service.ts
> +}
Is the reason a lot of these services and such are in libs as opposed to web because we anticipate bringing this functionality to other clients?

2022-11-14 19:11 UTC, differsthecat commented on libs/common/src/services/account/avatar-update.service.ts
> +    return color;
No problem 🙂

2022-11-16 20:14 UTC, differsthecat submitted a review, later dismissed
There's a failing build on CLI because of the addition of avatar service to sync service; I'd try setting the value in state service instead of injecting the avatar service here.

2022-11-17 14:11 UTC, differsthecat submitted a review, later dismissed
Looks good @BrandonM-Bitwarden !

2022-11-17 14:33 UTC, Hinton requested changes

2022-11-17 20:12 UTC, differsthecat commented on libs/common/src/services/account/avatar-update.service.ts
> +      });
The color from the profile is retrieved in sync service on page load, so there will still be an extra call to get it here if the value is not set. With it being set in sync service, if it is there it should theoretically already be set in the state, so this check on the color being defined is not needed. Does that make sense?

2022-11-18 12:13 UTC, Hinton commented on libs/common/src/services/account/avatar-update.service.ts
> +      });
On local testing it seems to always fire off a request to the profile endpoint. Since that information is already available in the sync response I don't se much point in having a race condition for this? It will just be additional network traffic and server load.

2022-11-18 12:16 UTC, Hinton commented on apps/web/src/app/components/dynamic-avatar.component.ts
> +  }
I would agree that `EventEmitter` are suitable for events, however we're trying to move towards a reactive presentational layer. By splitting the state in two methods you require that every component first fetches the state from disk, and then listen for updates. This will easily lead towards someone forgetting to listen for update events.

This is explained in more details in https://adr.bitwarden.com/decisions/0003-observable-data-services

2022-11-18 12:18 UTC, Hinton commented on apps/web/src/app/components/dynamic-avatar.component.ts
> +  }
Additionally the logic in dynamic-avatar.component.ts could use the `async` pipe which removes most of the boilerplate. `[color]="color$ | async"`

2022-11-21 14:02 UTC, differsthecat approved these changes

2023-01-01 15:27 UTC, trmartin4 commented
Approving this to be PRed into `master`, as it has been fully tested in the `changes/SG-58` branch.

2023-01-01 15:29 UTC, trmartin4 approved these changes

2023-01-01 15:30 UTC, merged