Proposal - Decrypt refactor
bitwarden/clients pull request #3732
Opened 2022-10-10 14:03 UTC by Hinton

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-10-11 00:11 UTC, eliykat reviewed
I've also been noodling away on this, please review #3738 as an alternative proposal and let me know what you think.

The biggest difference is that I don't want to have this pattern where we:
* pass an object to a decrypt method
* that method passes a service into a method on the object
* there are several levels of nested decrypt calls, passing down the same parameters each time, which you have to trace to find the actual decryption call still nested in `EncString`.

To me that is the real source of the tech debt here, it feels like decryption happens from the inside out, it's difficult to understand and extend. `ContainerService` is just a symptom of that. I'd like to flatten it out to a method which acts on an object.

2022-10-11 08:13 UTC, Hinton commented on libs/common/src/models/view/folderView.ts
> +  ) => Promise<T>;
Yes, we still have type safety though since the method in crypto service enforces the method definition.

2022-10-11 08:25 UTC, Hinton commented
One goal that hasn't been noted in this PR, is the potential use case for a domain model to have multiple views with different amount of data.

I kept the `decrypt` method for a few reasons,
1. to limit the scope of the refactor.
2. Support objects that decrypt differently attachments seems to have some custom logic, and there has been some discussion around potentially having an EncObject which contains a json blob instead of individual fields.

2022-10-12 00:45 UTC, eliykat commented
> Support objects that decrypt differently attachments seems to have some custom logic, and there has been some discussion around potentially having an EncObject which contains a json blob instead of individual fields.

Just a note on this topic, I'd like to avoid having lots of custom logic here or different ways of encrypting objects. I'd rather define a few ways of encrypting objects (e.g. individual EncStrings or an encrypted blob) and make people implement those, rather than give every object the ability to do something different.

> One goal that hasn't been noted in this PR, is the potential use case for a domain model to have multiple views with different amount of data.

Nice idea!

2022-10-12 01:29 UTC, MGibson1 commented on libs/common/src/services/crypto.service.ts
> +    // If the item has an organizationId, use the org key, otherwise use the user key
IMO it's the responsibility of the domain to know if it's encrypted and what key will decrypt it.

2022-10-12 01:59 UTC, MGibson1 commented
I don't particularly like that it's the `View`'s responsibility to determine what data on the `Domain` is encrypted and what is not. To me, #3738 and this are complimentary -- #3732 describes the data flow and #3738 is a better interface for defining encrypted data/decryption. @eliykat, the big change that would be necessary in your PR is updating the `decryptable` interface to belong on the `View` instead of the `Domain`. This would enable @Hinton's idea of multiple views for a given domain. The issue is how do we expose to the `encryptservice` which fields to decrypt and which are not needed? Not sure on that one, yet...

The other issue I see here is this doesn't solve the central issue of how to grab the key to my liking. I think I'd like to see an interface on `Domain` that determines the appropriate key, given a 2d array of `[Id, Key][]`.

2022-10-12 11:51 UTC, Hinton commented
I don't mind having an interface on Domain to determine which key is used to encrypt things.

Something that came to mind are Attachments, Name is an `EncString`, but the key has custom logic, and the data is encrypted using the key. Not sure if we have more edge cases for how things are encrypted/decrypted.

2022-10-12 21:22 UTC, eliykat commented on libs/common/src/services/crypto.service.ts
> +    // If the item has an organizationId, use the org key, otherwise use the user key
Just to round off this train of thought, if the domain service gets and supplies its own key, then we don't need this method at all. The domain service just calls the static decrypt method on the View object directly.

2022-10-12 21:44 UTC, eliykat commented on libs/common/src/models/view/folderView.ts
> +    view.name = await cryptoService.decryptToUtf8(model.name, key);
I like pulling the `cryptoService` call up here because we're not descending into the EncString. But we lose the error handling code which catches any error and substitutes `[error: cannot decrypt]`, which imo is important to avoid aborting an entire vault decryption due to 1 corrupted cipher.

2022-10-12 21:57 UTC, eliykat commented on libs/angular/src/components/folder-add-edit.component.ts
> +      this.folder = await this.cryptoService.decrypt(FolderView, folder);
To your point about where decryption happens: I was thinking that `FolderService` should only be handing out View objects, not Domain objects. But then I suppose that leads to a proliferation of methods for different folder view classes. Maybe `this.folderService.get(this.folderId, FolderViewClass)`?

2022-10-13 22:17 UTC, eliykat commented on libs/common/src/services/crypto.service.ts
> +      : await this.getOrgKey(orgId);
I liked the idea of the `keyId` we discussed, e.g. `const key = this.getKey(model.keyId)`

Where `model` implements an interface for `keyId`, it returns a guid or `null` for user's key.

2022-10-13 22:19 UTC, eliykat commented on libs/common/src/services/crypto.service.ts
> +    // If the item has an organizationId, use the org key, otherwise use the user key
Resolving this as we agreed that this method will live on `CryptoService` for now.

Ideally we'll refactor it later so that encrypt/decrypt can get its own key from `KeyService`, and we have a static `KeyService` implementation that can be pre-seeded with keys for stateless contexts.

2022-10-14 08:14 UTC, Hinton commented on libs/common/src/services/crypto.service.ts
> +      : await this.getOrgKey(orgId);
Something that occurred to me is the need for views to know which key to use.

2022-10-14 09:56 UTC, Hinton commented on libs/common/src/models/view/folderView.ts
> +    view.name = await cryptoService.decryptToUtf8(model.name, key);
That seems reasonable, and I agree that does seem kind of nice.

2022-10-17 03:34 UTC, eliykat commented on libs/common/src/services/crypto.service.ts
> +      : await this.getOrgKey(orgId);
For decrypting - view factories get the `keyId` from domain model and passes it to `cryptoService` (or whatever service we end up using) when decrypting 

For encrypting - I suppose the view also implements the same `keyId` interface to persist this information and passes it to the service when encrypting (in a similar way)

(some exceptions apply, e.g. Send/Attachments)

Is this what you mean?

2022-10-17 03:37 UTC, eliykat commented on libs/common/src/models/view/folderView.ts
> +    view.name = await cryptoService.decryptToUtf8(model.name, key);
I realised that this is arguably putting the decrypt method on the Domain, but given that the "view" is just a `string`, this might just be an exception to the rule. Same with `EncArrayBuffer` -> `ArrayBuffer`. Or maybe the view/domain distinction just doesn't really make sense at this level, so it doesn't matter anyway.

2022-10-21 02:53 UTC, eliykat commented on libs/angular/src/components/folder-add-edit.component.ts
> +      this.folder = await this.cryptoService.decrypt(FolderView, folder);
I realised this doesn't make any sense with reactive data

2022-10-31 10:05 UTC, Hinton commented on libs/common/src/services/crypto.service.ts
> +  }
Assuming we want to move this to encryption service, I envision we would lift this block of code, and keep `getKeyFromIdentifier` in the crypto service.

2022-10-31 10:06 UTC, Hinton commented on libs/common/src/models/view/folderView.ts
> +    view.name = await cryptoService.decryptToUtf8(model.name, key);
Implemented, let me know what you think.

2022-11-04 04:31 UTC, eliykat reviewed
Only one minor comment so far, unfortunately I didn't get to spend a lot of time on this today. I'll continue Monday.

2022-11-04 04:31 UTC, eliykat commented on libs/common/src/models/view/folder.view.ts
> +    const view = new FolderView(model);
Are we still using constructors in this pattern? I don't like that it exposes a public method which does not properly initialize the object (because it doesn't handle encStrings). I'd rather move the current constructor logic into this static factory method.

2022-11-04 08:15 UTC, Hinton commented on libs/common/src/models/view/folder.view.ts
> +    const view = new FolderView(model);
That's a fair point, I don't mind removing the constructor.

2022-11-10 01:37 UTC, eliykat commented on libs/common/src/abstractions/crypto.service.ts
> +  encryptView: <V extends Encryptable<EncryptableDomain<V>>>(
I wish we had method overloading 😞 I'd like some way of distinguishing this from the existing encrypt/decrypt methods, maybe `decryptItem` and `encryptItem`? (but it's also used for some things like Folders, which are not vault items - any ideas?)

2022-11-10 01:37 UTC, eliykat commented on libs/common/src/models/domain/folder.ts
> -    this.buildDomainModel(
I also prefer just manually mapping it, it's much more discoverable and straightforward, and gets rid of these opaque mapping methods in the base class.

2022-11-10 01:37 UTC, eliykat commented on libs/common/src/models/domain/folder.ts
> +    this.name = new EncString(obj.name);
`buildDomainModel` has a null check before instantiating the EncString, which we need to put back in. But it's verbose to repeat it on every line, and we can't move it into the constructor (which always creates the object). Maybe a helper method, like `newIfNotNull(val: any, ctor: Constructor)`, so we can use it for dates as well?

2022-11-10 01:37 UTC, eliykat commented on libs/common/src/models/view/encryptable.ts
> +  keyIdentifier(): string | null;
This would be tidier as a getter. It should never need an argument.

2022-11-10 01:37 UTC, eliykat commented on libs/common/src/models/view/folder.view.ts
> +    folder.name = await cryptoService.encrypt(this.name, key);
I think it would be clearest if we assigned encrypted & unencrypted properties in separate blocks of code. (i.e. just separated by some whitespace)

2022-11-10 01:37 UTC, eliykat commented on libs/common/src/models/view/folder.view.ts
> +    view.name = await model.name.decryptWithCryptoService(cryptoService, key);
Need a null check on any EncString method calls

2022-11-10 01:52 UTC, eliykat commented
I'm still a little unsure what the end state of `CryptoService` and `EncryptService` is. The duplicated interfaces between them are starting to get messy.

iirc, the last we discussed was potentially changing `CryptoService` to be `KeyService`, then have `EncryptService` depend on `KeyService` so that it can fetch its own keys (with a static key store for web workers). That brought up circular dependency issues that we did not fully resolve. (see my [notes](https://bitwarden.atlassian.net/wiki/spaces/~805680025/pages/283148305/Notes+Item+Decryption#CryptoService%2FKeyService-%E2%86%94%EF%B8%8E-EncryptSevice-dependency)). While we don't need to do all of this in 1 PR, I'd like to know where we're going with it.

2022-11-10 09:50 UTC, Hinton commented on libs/common/src/models/view/folder.view.ts
> +    view.name = await model.name.decryptWithCryptoService(cryptoService, key);
We really need to use strict 😢

2022-11-10 09:53 UTC, Hinton commented
@eliykat I understand and I didn't want to muddle this PR with any refactoring of `CryptoService`.

I agree with the move to `KeyService` and have `EncryptService` depend on `KeyService`. But I view that as something we'll get around to at a later stage. I would like to refactor `CryptoService` to observables and do this refactor prior which should make that change fairly simple.

2022-11-18 12:46 UTC, Hinton commented on libs/common/src/abstractions/crypto.service.ts
> +  encryptView: <V extends Encryptable<EncryptableDomain<V>>>(
`decryptView`  and `encryptView`? I partially feel like we need a low level service that handles primities, and a higher level that handles domain <-> view. Or somehow fit EncString and EncArrayBuffer into the same interface. Perhaps a task for a late date though.

2022-11-18 13:55 UTC, Hinton commented on libs/common/src/models/domain/folder.ts
> +    this.name = new EncString(obj.name);
I managed to add a type safe nullable factory.

2022-11-18 14:52 UTC, Hinton commented on libs/common/src/models/view/encryptable.ts
> +  keyIdentifier(): string | null;
So I went back and forth on this a bit. It seems the `fromJson` interface doesn't really like readonly getters. We could probably tweak the type to ignore them but that also feels like a hassle, and it might just be simpler to keep the function. That way we are certain it won't leak into json serializations should someone incorrectly use a property instead of getter.

2022-11-22 19:04 UTC, Hinton commented on libs/common/src/interfaces/decryptable.interface.ts
> +export interface OldDecryptable<TDecrypted extends InitializerMetadata>
I didn't have time to figure out a good name for this. But I envision that this needs to be rethought as there won't be a `decrypt` operation on the domain, and we instead want to convey

```json
{
  "domain": cipher,
  "view": CiperView,
}
```

We might need a mapper that converts strings to instances ...

2022-11-30 20:57 UTC, MGibson1 commented on libs/common/src/models/domain/folder.ts
> +    return null;
please comment that folders are always in the user context

2022-11-30 20:57 UTC, MGibson1 commented on libs/common/src/models/domain/folder.ts
> -    this.buildDomainModel(
I agree

2022-11-30 20:57 UTC, MGibson1 commented on libs/common/src/interfaces/crypto.interface.ts
> +export interface Encryptable<Domain> {
Please prefix type parameters with `T`

```suggestion
export interface Encryptable<TDomain> {
```

2022-11-30 20:57 UTC, MGibson1 commented on libs/common/src/interfaces/decryptable.interface.ts
> +export interface OldDecryptable<TDecrypted extends InitializerMetadata>
That is indeed what `InitializeMetadata` does.

I think we need to figure out a way to combine this interface definition with the crypto.interface ones.  The idea was that we eventually want to be able to support any domain/view being encrypted/decrypted in a web worker. 

The big impact is that we need to have (de)serialization guaranteed for any domain/view pair.

I've played a little bit and they're almost compatible. The big additional data is the to/from json information and inclusion of an enum flag to map the appropriate deserializer. There are some issues with `DecryptableDomain` and `Decryptable` separation, but I think those are surmountable.

2022-11-30 20:57 UTC, MGibson1 commented on libs/common/src/models/view/folder.view.ts
> +    return null;
Please comment that folders are always user-encrypted

2022-12-01 12:58 UTC, Hinton commented on libs/angular/src/components/folder-add-edit.component.ts
> +      const folder = await this.cryptoService.encryptView(this.folder);
I agree. I would probably argue that the save folder action should accept a folder view instead, and delegate the encryption action to the service. But not have an explicit `encyrpt/decrypt` action on the service.

2022-12-01 18:44 UTC, MGibson1 commented on libs/angular/src/components/folder-add-edit.component.ts
> +      const folder = await this.cryptoService.encryptView(this.folder);
❤️ sounds much better.

2022-12-01 18:48 UTC, MGibson1 commented on patch.diff
> +diff --git a/apps/desktop/desktop_native/Cargo.lock b/apps/desktop/desktop_native/Cargo.lock
Looks like you have a patch mistakenly checked in

2022-12-02 15:59 UTC, Hinton commented
I've removed the `Cipher` changes from this again, and changed the target to a new feature branch. My thinking is that we'll review this to ratify the general patterns, get QA to begin testing folders while I move the cipher portions to a new PR and we can review it prior to merging the feature branch.

This lets QA test both potions in isolation and we don't introduce the change until we've migrated Ciphers which prevents us from having 3 ways of doing encryption/decryption of domain models.

2022-12-05 04:42 UTC, eliykat requested changes
Mostly minor comments given that the cipher changes have been taken out and I think we've discussed the folder stuff quite a bit already.

To be honest I'm struggling with the various type/interface names (`Decryptable`/`Encryptable`) etc, but I don't have any better suggestions for them. I'll chew on it though.

2022-12-05 04:42 UTC, eliykat commented on libs/common/src/models/view/folder.view.ts
> +    folder.name = this.name != null ? await encryptService.encrypt(this.name, key) : null;
I think we can also use `NullableFactory` here as well, right?

2022-12-05 04:42 UTC, eliykat commented on libs/common/src/services/crypto.service.ts
> +    return this.encryptService.decryptDomain(view, domain as DecryptableDomain, key);
Also, while it's strictly unnecessary, I think we have a practice of always `await`ing async methods, even if it's a tail call. I don't feel strongly about it but it does feel a bit safer to me.

2022-12-05 04:42 UTC, eliykat commented on libs/common/src/interfaces/crypto.interface.ts
> +  return new c(...(args as any[]));
You shouldn't have to type cast here if you type it like this in the parameters. e.g.

```ts
export function nullableFactory<T extends new (...args: any[]) => any>(
  // <snip>
  return new c(...args);
}
```

2022-12-05 04:42 UTC, eliykat commented on libs/common/src/interfaces/crypto.interface.ts
> +): InstanceType<T> | undefined {
Why `| undefined`? Shouldn't it be `| null`?

2022-12-05 04:42 UTC, eliykat commented on libs/common/src/interfaces/crypto.interface.ts
> +export function nullableFactory<T extends new (...args: any) => any>(
`nullableFactory` seems broadly useful to me, I think it should stand outside of the crypto-specific code.

2022-12-05 04:42 UTC, eliykat commented on libs/common/src/interfaces/decryptable.interface.ts
> +export interface OldDecryptable<TDecrypted extends InitializerMetadata>
I agree with @MGibson1 above. To expand slightly, I think you'd have `DecryptableDomain` and `Encryptable` extend `InitializerMetadata`, as they represent the instantiated objects that are being passed to/from the web worker. That effectively replaces this `OldDecryptable` interface.

In addition, you'd have an additional `InitializerKey` property on the `DecryptableDomain` to represent the view it decrypts to.

You've reverted the cipher changes, so we can discuss further in the cipher PR.

2022-12-05 09:02 UTC, Hinton commented on libs/common/src/interfaces/crypto.interface.ts
> +  keyIdentifier(): string | null;
As previously covered, making it a getter will include it in serialization. A method lives on the prototype which avoids that hassle.

2022-12-05 09:03 UTC, Hinton commented on libs/common/src/models/view/folder.view.ts
> +    folder.name = this.name != null ? await encryptService.encrypt(this.name, key) : null;
Not really, it's not a constructor. We could make a nullable factory that accepts an argument with a factory in it.

2022-12-05 09:06 UTC, Hinton commented
We can discuss it in the future PR, but I don't want to mix in any knowledge of views in the domain. Since domain is in the center and the ambition to support multiple views per domain.

2022-12-06 04:39 UTC, eliykat commented on libs/common/src/interfaces/crypto.interface.ts
> +  keyIdentifier(): string | null;
ah right, yes I thought I mentioned it before but didn't see your response.

2022-12-06 04:41 UTC, eliykat commented on libs/common/src/models/view/folder.view.ts
> +    folder.name = this.name != null ? await encryptService.encrypt(this.name, key) : null;
True. It's a similar pattern though (call a method if value isn't null), and this ternary condition will be repeated 100 times as we encrypt properties on objects under this new pattern.

2022-12-12 01:42 UTC, eliykat reviewed
Looks good to me, but I'd like a final review from @MGibson1.

2022-12-13 16:18 UTC, MGibson1 requested changes

2022-12-13 16:18 UTC, MGibson1 commented on apps/browser/src/popup/settings/folder-add-edit.component.ts
> +      cryptoService
I think this review comment got buried, but I don't think components should use CryptoService. `FolderApiService` should instead accept a `FolderView` and encrypt it prior to upload.

2023-01-27 11:32 UTC, Hinton commented on libs/common/src/interfaces/decryptable.interface.ts
> +export interface OldDecryptable<TDecrypted extends InitializerMetadata>
We have a working version of this in https://github.com/bitwarden/clients/pull/4473,

2023-06-13 23:27 UTC, eliykat commented
Removing myself from reviewers on the understanding this will be done in the SDK instead.

2023-09-01 11:33 UTC, closed without merging