[CL-41] Typography directive
bitwarden/clients pull request #3741
Opened 2022-10-11 11:58 UTC by Hinton

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-10-11 11:58 UTC, Hinton commented on libs/components/src/typography/typography.directive.ts
> +  h1: ["tw-text-3xl", "tw-font-semibold"],
Do we want to use h1 as name, or have more semantic meaning?

2022-10-12 05:57 UTC, coroiu commented
Ah yeah, fair point about bootstrap messing that up!

2022-10-12 05:57 UTC, coroiu commented on libs/components/src/typography/typography.directive.ts
> +  h1: ["tw-text-3xl", "tw-font-semibold"],
I think this looks fine!

2022-10-12 06:01 UTC, coroiu reviewed
Started reviewing and then realized that this PR is marked as `draft` 🤷

2022-10-12 06:01 UTC, coroiu commented on libs/components/src/typography/typography.directive.ts
> +    return styles[this.bitTypography] ?? ["hi"];
question: what is `hi`?

2022-10-12 06:01 UTC, coroiu commented on libs/components/src/typography/index.ts
> +// export * from "./typography.module";
comment

2022-10-13 11:44 UTC, Hinton commented on libs/components/src/typography/typography.directive.ts
> +    return styles[this.bitTypography] ?? ["hi"];
A friendly, informal, casual greeting said upon someone's arrival.

2022-10-13 11:50 UTC, Hinton commented
We need to figure out what margins to use. @danielleflinn something you can assist with perhaps?

2022-12-23 17:37 UTC, willmartian commented
What is the benefit to a directive-based approach over CSS classes?

2023-01-05 11:46 UTC, Hinton commented
None really. The jira ticket covers the different approaches and for our use case classes works just as well as angular directives.

If I remember correctly the thinking was that we already have directives and introducing classes as another abstraction layer could be confusing.

2023-01-16 14:41 UTC, coroiu commented
With directives we could add a flag that e.g. disables bottom margin. CSS classes could do the same but I guess it would be easier to discover the proper way of doing it by checking the directive source code

2023-01-16 14:41 UTC, coroiu requested changes
Looks good, except for typo 😄

2023-01-16 14:41 UTC, coroiu commented on libs/components/src/stories/typography.stories.mdx
> +<h1 bitTypotgraphy="h1">H1</h1>
typo: 
```suggestion
<h1 bitTypography="h1">H1</h1>
```

same for the rest of the rows in this file

2023-01-18 12:08 UTC, coroiu requested changes
You missed the rest of the typos in `typography.stories.mdx`

2023-02-03 07:52 UTC, coroiu approved these changes

2023-02-03 09:32 UTC, merged