Use `aria-describedby` for all help blocks/hints
bitwarden/clients pull request #3802
Opened 2022-10-16 23:15 UTC by patrickhlauke

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

Desktop app in Windows with NVDA - note how help blocks/hints are announced when fields that have them receive focus

https://user-images.githubusercontent.com/895831/196063110-acb8ebe2-355a-4202-aa7d-a5a791cb63e2.mp4

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-10-17 01:05 UTC, patrickhlauke commented
i believe i caught every possible permutation/instance, but because these aren't always consistently implemented at the moment in terms of classes/tags, and because some controls have many different variations, it's possible something may have slipped through the cracks. suggest carefully reviewing this with a screen reader to make sure all possible iterations are covered.

2022-11-28 15:40 UTC, danielleflinn submitted a review, later dismissed

2022-12-05 21:07 UTC, djsmith85 requested changes
@patrickhlauke Awesome work, as always. Thank you.

I have reviewed the code and also tested browser and desktop with NVDA on Win. Everything besides the username-generator options gets announced as intended.

2022-12-05 21:10 UTC, djsmith85 commented
The export-component(apps\desktop\src\app\vault\export.component.html) in the desktop could also use a masterPasswordHelp help-box like in browser.

2022-12-05 22:54 UTC, patrickhlauke commented on apps/desktop/src/app/vault/generator.component.html
> +                    aria-describedby="usernameType_{{ o.value }}_Help"
interesting...wonder why I didn't pick it up at the time ... fairly sure I tried to compile these to test. no matter, I'll see what I can do to address these

2022-12-05 23:21 UTC, patrickhlauke commented on apps/desktop/src/app/components/user-verification.component.html
> +      aria-describedby="masterPasswordHelp"
@djsmith85 any idea where/how i would see this particular component in action? just so I can work out what the context for it is?

2022-12-06 00:50 UTC, patrickhlauke commented on apps/desktop/src/app/vault/generator.component.html
> +                    aria-describedby="usernameType_{{ o.value }}_Help"
ah, it throws the error, but still launches in the end. fixed.

2022-12-06 00:52 UTC, patrickhlauke commented on apps/browser/src/popup/generator/generator.component.html
> +              aria-describedby="type_{{ o.value }}_Help"
Fixed

2022-12-06 00:53 UTC, patrickhlauke commented on apps/browser/src/popup/accounts/login.component.html
> +              aria-describedby="masterPasswordHelp"
Decided that for the most basic login form, there's really no need for any additional help, so removed this

2022-12-06 00:56 UTC, patrickhlauke commented on apps/desktop/src/app/components/user-verification.component.html
> +      aria-describedby="masterPasswordHelp"
ah, think i've addressed this (in both the export and delete dialogs)

2022-12-06 01:07 UTC, patrickhlauke commented
> The export-component(apps\desktop\src\app\vault\export.component.html) in the desktop could also use a masterPasswordHelp help-box like in browser.

done

2022-12-06 12:43 UTC, djsmith85 requested changes
@patrickhlauke This is looking good and I have tested all changes (browser/desktop with NVDA on Win). Just 2 small things and we can pass this on to QA.

2022-12-06 12:43 UTC, djsmith85 commented on apps/desktop/src/app/vault/generator.component.html
> +                    attr.aria-describedby="usernameType_{{ o.value }}_Help"
Wouldn't the same changes done with 6dec4ba also work here? Removing the need to add the `aria-describedby`

2022-12-06 12:43 UTC, djsmith85 commented on apps/browser/src/popup/components/user-verification.component.html
> +      aria-describedby="masterPasswordHelp"
This will need to be changed to `confirmIdentityHelp` so it gets announced in `apps/browser/src/popup/settings/export.component.html`

2022-12-07 20:21 UTC, patrickhlauke commented on apps/browser/src/popup/components/user-verification.component.html
> +      aria-describedby="masterPasswordHelp"
Fixed

2022-12-07 20:22 UTC, patrickhlauke commented on apps/desktop/src/app/vault/generator.component.html
> +                    attr.aria-describedby="usernameType_{{ o.value }}_Help"
Yup, good catch.

2022-12-07 20:26 UTC, patrickhlauke commented on apps/desktop/src/app/vault/generator.component.html
> +                    attr.aria-describedby="usernameType_{{ o.value }}_Help"
Fixed

2022-12-07 22:02 UTC, djsmith85 submitted a review, later dismissed
Thank you @patrickhlauke. Changes are looking good and passing this on to QA.

2022-12-19 14:56 UTC, djsmith85 commented
@patrickhlauke Two findings from QA:
**Browser:**
_When editing a send, the text below the deletion date is not recognized by the screen reader reliably_ (`send-add-edit.component.html` / `efflux-dates.component.html`). There might be an issues depending on which browser is used (`deletionDateHelp` vs. `deletionDateCustomHelp`

**Desktop:**
_In the Environment Url Settings, the text “For advanced users…….“ is not not recognized by the screen reader._
Not sure how to best solve this one, as it's below all individual url inputs. Ideally it gets announced with the baseUrl part or when focusing Custom Environment)

2022-12-20 16:07 UTC, patrickhlauke commented
@djsmith85 having a look at these last few issues tonight

2022-12-20 22:03 UTC, patrickhlauke commented
@djsmith85 both issues addressed

for deletion date help text, I went for the same `id` in both native and custom cases

for the custom environment (which was an issue not just on desktop, but also in the browser extension), made the entire custom environment `<div>` a `role="group"` with an explicit `aria-label` and `aria-describedby` pointing to that text in the footer.

video recording (windows/chrome/nvda for the extension, then at 0:33 windows/nvda for the desktop app) showing the new behaviour - note how the group, it's label ("Custom Environment") and the description ("For advanced users...") is announced when entering the group, but then isn't repeated each time. It is also announced when entering the group from the other way (e.g. from the Save control, navigating backwards with `Shift+Tab`).

https://user-images.githubusercontent.com/895831/208775515-a607deec-040d-4722-943b-a76392c508b6.mp4

2022-12-20 22:25 UTC, djsmith85 approved these changes
@patrickhlauke Changes are looking good and I have passed this back to QA.

2022-12-21 19:48 UTC, djsmith85 commented
@patrickhlauke Thank you for the fixes and the changes have been approved by QA.

2022-12-21 19:48 UTC, merged

2022-12-21 22:03 UTC, patrickhlauke commented
super, thanks @djsmith85 / QA team