Rename requests and responses to follow naming convention
bitwarden/clients pull request #3806
Opened 2022-10-17 09:42 UTC by Hinton

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Follow up to #3621 which completes the migration of the `models` directory.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-10-17 19:56 UTC, MGibson1 requested changes

2022-10-17 19:56 UTC, MGibson1 commented on libs/common/src/services/api.service.ts
> +      new TokenTwoFactorRequest(),
Please double check this class rename. I can't seem to find it in the diffs here

2022-10-18 08:13 UTC, Hinton commented on libs/common/src/services/api.service.ts
> +      new TokenTwoFactorRequest(),
The filename should be updated, and all references as well.

2022-10-18 08:14 UTC, Hinton commented on libs/common/src/abstractions/auth.service.ts
> +import { TokenTwoFactorRequest } from "../models/request/identity-token/token-two-factor.request";
It didn't make much sense to use camelCase in folder names.

2022-10-18 13:34 UTC, MGibson1 submitted a review, later dismissed

2022-10-18 16:52 UTC, MGibson1 approved these changes

2022-10-18 17:01 UTC, merged