Browser Ext UI Update
bitwarden/clients pull request #3842
Opened 2022-10-19 23:59 UTC by DanHillesheim

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x ] Other
```

## Objective

CSS-only UI update

## Code changes

Minor CSS rule changes across CSS files

## Screenshots

![Screen Shot 2022-10-19 at 5 58 17 PM](https://user-images.githubusercontent.com/79476558/196826278-e12d319c-cd69-41f9-80e2-30483d9df664.png)

![Screen Shot 2022-10-19 at 5 58 24 PM](https://user-images.githubusercontent.com/79476558/196826305-bc6df79c-e6cb-4317-acc0-a40e479d6cf4.png)

2022-10-20 08:14 UTC, Hinton reviewed
Overall just a few minor suggestions. Mainly to remove commented code (since it will be tracked in the git history), and to remove styling that gets overridden by the themify mixin.

I think we should remove the desktop changes completely? To minimize the impact of these changes.

2022-10-20 08:14 UTC, Hinton commented on apps/browser/src/popup/scss/box.scss
> +    // border-bottom: 1px solid #000000;
```suggestion
```

2022-10-20 08:14 UTC, Hinton commented on apps/desktop/src/scss/box.scss
```suggestion
```

2022-10-20 08:14 UTC, Hinton commented on apps/browser/src/popup/scss/box.scss
> +
```suggestion
```

2022-10-20 08:14 UTC, Hinton commented on apps/browser/src/popup/scss/buttons.scss
> +  // width: 100%;
```suggestion
```

2022-10-20 08:14 UTC, Hinton commented on apps/browser/src/popup/scss/box.scss
> +  margin: 10px 0 20px;
Can we add the last property of the margin (I'm guessing it resolves to 0, but it's somewhat obscured when only 3 of the 4 properties are defined).

2022-10-20 08:14 UTC, Hinton commented on apps/browser/src/popup/scss/box.scss
> +        background-color: $background-color;
The themeify below will set a color for you.

2022-10-20 08:14 UTC, Hinton commented on apps/browser/src/popup/scss/box.scss
> +  background-color: $background-color;
Same here, I don't believe we need to set a background color if we also use the themify.

2022-10-20 08:14 UTC, Hinton commented on apps/browser/src/popup/scss/pages.scss
> +  background-color: $box-background-color;
Same here, I think we can remove this.

2022-10-20 08:14 UTC, Hinton commented on apps/browser/src/popup/scss/pages.scss
> +    background-color: #e6e9ed;
Same remove? (If that's not possible we should extract it to a variable, or use the variable instead.

2022-10-20 08:14 UTC, Hinton commented on apps/browser/src/popup/scss/pages.scss
> +        color: $brand-primary;
needed?

2022-10-20 12:33 UTC, kspearrin requested changes
Comments are just about using variables for something that they weren't meant for. We should change existing variable values or create new ones to represent the changes in how they are being applied.

2022-10-20 12:33 UTC, kspearrin commented on apps/browser/src/popup/scss/box.scss
> +        background-color: themed("backgroundColor");
This seems like abuse the `backgroundColor` variable. Why not change `boxBackgroundHoverColor` value or make something new for this case?

2022-10-20 12:33 UTC, kspearrin commented on apps/browser/src/popup/scss/box.scss
> +      background-color: themed("backgroundColor");
Same

2022-10-20 12:33 UTC, kspearrin commented on apps/browser/src/popup/scss/box.scss
> +      background-color: themed("boxBorderColor");
Same. Feels like abusing an existing variable that was meant for something else.

2022-10-20 12:33 UTC, kspearrin commented on apps/browser/src/popup/scss/buttons.scss
> +    background-color: themed("boxBackgroundColor");
Same

2022-10-20 15:07 UTC, danielleflinn commented on apps/browser/src/popup/scss/box.scss
> +    // border-bottom: 1px solid #000000;
I agree with Oscar's above comment, we should open a separate PR that focuses on Desktop changes that are similar to these. The goal would be to release both PRs around the same time, but keeping them separate would allow for easier reversion if anything goes wrong.

2022-10-20 15:40 UTC, DanHillesheim commented on apps/browser/src/popup/scss/pages.scss
> +    background-color: #e6e9ed;
I will add this to my cleanup.

2022-10-20 15:41 UTC, DanHillesheim commented on apps/browser/src/popup/scss/box.scss
> +  background-color: $background-color;
Same as above.

2022-10-20 15:41 UTC, DanHillesheim commented on apps/browser/src/popup/scss/pages.scss
> +  background-color: $box-background-color;
Same as above.

2022-10-20 15:41 UTC, DanHillesheim commented on apps/browser/src/popup/scss/pages.scss
> +        color: $brand-primary;
Double checking.

2022-10-20 15:44 UTC, DanHillesheim commented on apps/browser/src/popup/scss/box.scss
> +        background-color: themed("backgroundColor");
Initially was trying to avoid making anything net-new, but could look at something different here for the sake of clarity.

2022-10-20 15:44 UTC, DanHillesheim commented on apps/browser/src/popup/scss/box.scss
> +      background-color: themed("backgroundColor");
Same as above.

2022-10-20 15:44 UTC, DanHillesheim commented on apps/browser/src/popup/scss/box.scss
> +      background-color: themed("boxBorderColor");
Same as above.

2022-10-20 15:44 UTC, DanHillesheim commented on apps/browser/src/popup/scss/buttons.scss
> +    background-color: themed("boxBackgroundColor");
Same as above.

2022-10-20 19:34 UTC, danielleflinn reviewed
Other general UI bugs design noticed:

- On the Tab page, if there is not a matching login, and you hover over the ‘Add a Login’ card, the background changes as if the full container were clickable. This is unexpected.
- The expandable content sections like the ones in Options or Send, should have a hover state. Existing production version shows a background color change. 
- In the Edit Item view, the URI and custom field boxes extend to the edge of the window instead of having the new padding.
- The Options in settings and New send page fields looks off, all helper text does not look grouped with the actual option. This might require a structural change to the HTML where we move all `box-footer` divs into the box containers below the `<input>` or `<select>` elements. 
- When in New/Edit Send if you expand the options section, the checkbox’s label above expands to 2 lines to make room for the scrollbar. However, only 1 letter is on the 2nd line. Design would expect the full word ‘save’ to move down to the 2nd line. 
- The PIN field in the Unlock with PIN modal has an odd background color and the top/bottom of the field blends in with the modal background.

Feel free to ping me on any of the Design comments if you need clarification.

2022-10-20 19:34 UTC, danielleflinn commented on apps/browser/src/popup/scss/box.scss
> +  border-radius: 6px;
Can we look at using the same border radius for the vault filter, search bar, and callouts?

2022-10-20 19:34 UTC, danielleflinn commented on apps/browser/src/popup/scss/box.scss
> +      background-color: themed("boxBorderColor");
Design prefers to remove the background color on the selects and keep the border only, this way the label is still visually grouped with the select container.

2022-10-20 19:34 UTC, danielleflinn commented on apps/browser/src/popup/scss/pages.scss
> +  font-size: $font-size-xlarge;
Design prefers the previous text size as it will allow more characters to display on a single line before wrapping.

2022-10-20 19:34 UTC, danielleflinn commented on apps/browser/src/popup/scss/pages.scss
>    .generated-wrapper {
Design Feedback:
- Can we remove the background and border on the generated text? We don’t use this treatment anywhere else in the extension so it feels a bit out of place.
- Can we keep the copy/generate icon buttons `flex-row`? We don't stack icon buttons like this elsewhere in the product and in the item forms we display the copy / generate buttons in a row so this pattern is already familiar to the user. To improve alignment with the text, we could align the icons to the top or the container and add top margin so these are aligned with the baseline of the generated text.
- The left and right padding on the generated text seems like too much; Design suggests reducing to 15px on all sides.

2022-10-20 19:34 UTC, danielleflinn commented on apps/browser/src/popup/scss/pages.scss
> +        color: $brand-primary;
Maybe instead of changing the icon button color on hover we match the hover treatment of the icon buttons in the popup header? (bwi-external link and bwi-plus)

2022-10-20 19:34 UTC, danielleflinn commented on apps/browser/src/popup/scss/box.scss
> -    border-bottom: 1px solid #000000;
Since we removed the borders from the boxes, Solarize Dark theme seems to need adjustments as there is nothing visually separating the rows.

2022-10-20 22:35 UTC, DanHillesheim commented on apps/browser/src/popup/scss/pages.scss
> +  font-size: $font-size-xlarge;
reduced as requested

2022-10-20 22:41 UTC, DanHillesheim commented on apps/browser/src/popup/scss/pages.scss
>    .generated-wrapper {
I have a few questions here. 


> Design Feedback:
> 
> * Can we remove the background and border on the generated text? We don’t use this treatment anywhere else in the extension so it feels a bit out of place. 
> * Can we keep the copy/generate icon buttons `flex-row`? We don't stack icon buttons like this elsewhere in the product and in the item forms we display the copy / generate buttons in a row so this pattern is already familiar to the user. To improve alignment with the text, we could align the icons to the top of the container and add top margin so these are aligned with the baseline of the generated text.
> * The left and right padding on the generated text seems like too much; Design suggests reducing to 15px on all sides.


First bullet: Are you talking about the input box where the password/passphrase is displayed? If so, I understand the concern, but my feedback would be that it needs to be different so that it's recognizable and can be visually acquired without much effort. I'm happy to discuss though. It was one of the items I think needed the most help visually.
Second bullet: I stacked them to give the password/passphrase box more horizontal space. It seems in this use case it fits the purpose well, but if the prevailing opinion is to revert, then no problem.
Third bullet: Agreed, I'm not sure why that was changed that way.

2022-10-20 22:41 UTC, DanHillesheim commented on apps/browser/src/popup/scss/pages.scss
> +        color: $brand-primary;
I added a similar treatment as suggested. Hopefully, this will suffice.

2022-10-20 22:42 UTC, DanHillesheim commented on apps/browser/src/popup/scss/box.scss
> -    border-bottom: 1px solid #000000;
I addressed the issue for the most part. I think there's a little more cleanup to do possibly.

2022-10-20 23:06 UTC, danielleflinn commented on apps/browser/src/popup/scss/pages.scss
>    .generated-wrapper {
> First bullet: Are you talking about the input box where the password/passphrase is displayed? 

Yes this is what the team was referring to.

> Second bullet: 

@sukhleenb and I both agreed we prefer these to be flex-row. 

 The Design team will discuss both of these though and will get back to you early next week. Thanks @DanHillesheim!

2022-10-20 23:22 UTC, danielleflinn commented on apps/browser/src/popup/scss/box.scss
> -    border-bottom: 1px solid #000000;
Looks good! Only bit of feedback is we should probably add a new lighter variable for the hover color so that the hover state is retained.

2022-10-21 08:47 UTC, Hinton commented on apps/browser/src/popup/scss/box.scss
> +        // background-color: $background-color;
```suggestion
```

2022-10-21 08:47 UTC, Hinton commented on apps/browser/src/popup/scss/pages.scss
> +  // background-color: $box-background-color;
```suggestion
```

2022-10-21 08:47 UTC, Hinton commented on apps/desktop/src/scss/box.scss
> -
Please look into reverting this and do it in a separate PR.

2022-10-21 08:47 UTC, Hinton commented on apps/browser/src/popup/scss/box.scss
> +            }
We don't seem to be using a theme here.

2022-10-21 08:47 UTC, Hinton commented on apps/browser/src/popup/scss/box.scss
> +  margin: 10px 0 20px;
In this case I prefer to write it out, it's fine if it's a shorthand for 1 or 2 values though.

2022-10-24 14:11 UTC, SchneiderSam commented
@DanHillesheim and @danielleflinn Wow. Interesting how small changes make a tool more modern. I think it looks much better than the current one. Thanks for working on the UI.

2022-10-26 22:28 UTC, DanHillesheim commented
@danielleflinn  Take a look at the generator. I think we decided on the border only and moving the buttons back to their side-by-side orientation. As far as the other items I believe I addressed it all. 

@kspearrin @Hinton I believe I got all of the colors mentioned into new variables and the themify variables rectified. Take a look and if there is any other feedback I'll make time tomorrow to get it all done. 

As a side note, I made an attempt to adjust the vaults dropdown to also have the same look - this is a new item in this commit.

2022-10-27 08:46 UTC, Hinton commented on apps/browser/src/popup/scss/box.scss
> +        // background-color: $background-color;
This is still relevant.

2022-10-27 08:47 UTC, Hinton commented on apps/desktop/src/scss/box.scss
> -
Please re-add the newline to completely exclude desktop from this pr.

2022-10-27 08:52 UTC, Hinton reviewed
Almost all my previous comments seems to be resolved. Note I haven't gone into the css changes in detail as long term they will be replaced with tailwind, and as long as design is happy and the changes are isolated we should be good.

We seem to be using various paddings and margins, from odd numbers to even. Sometimes it's 6, sometimes 7, 10 or 15. Not sure if we need all those different padding sizes, or if it looks odd with minor differences. But it's not something I've dug into.

2022-10-27 08:52 UTC, Hinton commented on apps/browser/src/popup/scss/buttons.scss
> +    border-color: none;
Should be outside the themify block.

2022-10-27 14:56 UTC, kspearrin commented on apps/browser/src/popup/scss/pages.scss
> +      border-color: themed("genBorderColor");
Seems really odd to me that we have some separate defined variable for this one use case.

2022-10-27 14:56 UTC, kspearrin commented on apps/browser/src/popup/scss/pages.scss
> +          background-color: themed("hoverColorTransparent");
same

2022-10-28 20:12 UTC, danielleflinn requested changes
@DanHillesheim 
Last week I believe we aligned on the following:
- the generator either having no outline or the outline wrapping around both the generated text and icon buttons. Can you update the generator page to reflect one of these options?
-  using only a border on the select field areas (no fill). Can you update the selects to have no fill?

I'm also still not seeing the solarize theme hover state on the non-form elements. This should be fixed before releasing so users understand which items are clickable.

Thanks for your work on this!

Edit: we should look at doing a fast follow to this work where we address the issue noted above around helper text not being grouped with the form field it relates to.

2022-10-28 21:26 UTC, danielleflinn approved these changes
Design feedback addressed!

2022-10-28 22:04 UTC, danielleflinn approved these changes

2022-10-29 15:27 UTC, kspearrin approved these changes

2022-10-31 10:56 UTC, Hinton approved these changes
Looks good! Now we just need QA to test it before merging.

2022-10-31 17:08 UTC, danielleflinn commented
@DanHillesheim  Just noticed the hover state for the right header button is short. the background should extend to the top and bottom of the header area (see hover state on left button). This bug appears on all right buttons in the header regardless of which view you are in. 
 
<img width="375" alt="Screen Shot 2022-10-31 at 10 05 18 AM" src="https://user-images.githubusercontent.com/43477473/199066936-290c2550-332e-4ab2-ab30-5918fbe49583.png">

2022-10-31 18:25 UTC, DanHillesheim commented
> @DanHillesheim Just noticed the hover state for the right header button is short. the background should extend to the top and bottom of the header area (see hover state on left button). This bug appears on all right buttons in the header regardless of which view you are in.
> 
> <img alt="Screen Shot 2022-10-31 at 10 05 18 AM" width="375" src="https://user-images.githubusercontent.com/43477473/199066936-290c2550-332e-4ab2-ab30-5918fbe49583.png">

@danielleflinn I'll get a fix in for that shortly

2022-10-31 21:24 UTC, DanHillesheim commented
Latest commit will fix the button height issue. I have other recommendations for the markup, but I will save them for another release.

2022-10-31 21:49 UTC, danielleflinn approved these changes

2022-11-01 13:06 UTC, kspearrin approved these changes

2022-11-01 13:06 UTC, merged

2022-12-18 08:51 UTC, 7R0D3N commented
> Contributor

Hi Team,
Bitwarden support asked me to drop a comment here regarding my dislike of the new oversized boxes for each credential.
I only have 11 favourites, but now I cannot view them all via the chrome addin without scrolling. 
The previous condensed view is much better, IMHO.  Screen real estate is valuable, and Bitwarden needs much more now to show fewer credentials than before the updated comfort view. An option to switch back to the condensed view to see more entries without the need to scroll would be appreciated. :)
Thankyou for your excellent work!

![image](https://user-images.githubusercontent.com/46618691/208289035-ba7ed72f-4728-49fb-960b-2d3d8170d750.png)