Toggle directive experiment
bitwarden/clients pull request #3850
Opened 2022-10-20 09:51 UTC by Hinton

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Trying to figure out a way to have an elegant toggle directive for input types.

- Adds support for icons to regular buttons, essentially just puts the bwi classes in the button.
	- Should we look into merging the button and icon button components?
- Is having directive with a template based reference to an input the best way to solve this?
	- Pros: We can focus on the input
	- Con: It's annoying that things happens magically.

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-10-20 22:13 UTC, eliykat reviewed
The basic structure of your solution looks good to me. From a dev perspective, I'm in favour of having more succinct markup, with the logic encapsulated in the directive. One of the goals of the CL is to reduce copy/paste boilerplate in the markup, and both your alternatives would still have unnecessary boilerplate.

Maybe this is slightly less discoverable, but it's a simple directive to understand - I don't think it's "magic". This is a tradeoff for the whole CL - it's our own specialised component library, you have to learn it if you're doing UI work.

> Should we look into merging the button and icon button components?

While the button can easily house an icon, the specific "icon button" styles required by design were different enough that I thought it would excessively crowd and complicate the button component. But maybe you can find a way to reconcile those two, or maybe we can push the icon button-specific styling down to the icon itself using a directive, e.g.:

```html
<button bitButton>
  <i icon="bwi-trash" icon-style="button"></i>      <!-- applies padding and size for an icon button -->
</button>
`

2022-10-24 06:37 UTC, coroiu commented on libs/components/src/input/input.directive.ts
> +  // eslint-disable-next-line @typescript-eslint/explicit-member-accessibility
question: why not just remove `public`?

2022-10-28 13:13 UTC, coroiu submitted a review, later dismissed
Small non-blocking comment, looks good otherwise

2022-10-28 13:13 UTC, coroiu commented on libs/components/src/form-field/form-field.stories.ts
> +      <button bitSuffix bitButton bitPasswordInputToggle></button>
thought (non-blocking): Seems redundant to have both this and the standalone stories for the toggle button 🤷

2022-10-28 13:16 UTC, Hinton commented on libs/components/src/form-field/form-field.stories.ts
> +      <button bitSuffix bitButton bitPasswordInputToggle></button>
Yes, I should probably remove it from that story.

2022-10-28 14:23 UTC, coroiu submitted a review, later dismissed
All good

2022-10-28 15:17 UTC, danielleflinn commented
Storybook looks fine. 
> Should we look into merging the button and icon button components?
We could, we'd need to be able to support the following for the icon buttons:
• "ghost" styling
• alternate padding so that when only an icon is used the button is square. Note how the "icon" button story is a rectangle and the icon-button is a square. (I'd recommend adding text to the right of the icon in the "icon" story as we currently use that pattern in the web vault quite a bit but don't have a story for it in Storybook)
• the smaller size for when this icon button is needed within other components where the full padding is too much (example: vertical navigation or a table row)

2022-10-28 15:18 UTC, danielleflinn commented
Storybook looks fine. 
> Should we look into merging the button and icon button components?

We could, we'd need to be able to support the following for the icon buttons:

- "ghost" styling
-  alternate padding so that when only an icon is used the button is square. Note how the "icon" button story is a rectangle and the icon-button is a square. (I'd recommend adding text to the right of the icon in the "icon" story as we currently use that pattern in the web vault quite a bit but don't have a story for it in Storybook)
- the smaller size for when this icon button is needed within other components where the full padding is too much (example: vertical navigation or a table row)

2022-11-04 12:17 UTC, Hinton commented on libs/components/src/input/input.directive.ts
> +  // eslint-disable-next-line @typescript-eslint/explicit-member-accessibility
🤯

2022-11-10 01:01 UTC, eliykat requested changes
I haven't reviewed in detail given that it's already been approved, but this did jump out at me.

2022-11-10 01:01 UTC, eliykat commented on libs/components/src/input/input.directive.ts
> +  }
I think `setTimeout` is a hack to avoid angular change detection errors, right?

I've previously looked at this and I believe this is the correct way to do it: https://github.com/bitwarden/clients/blob/master/libs/angular/src/components/lock.component.ts#L115-L119

From memory, it's how Angular does it internally (in the CDK or maybe Material).

2022-11-10 01:02 UTC, eliykat commented
Is there a Jira ticket for this?

2022-11-10 10:03 UTC, Hinton commented on libs/components/src/input/input.directive.ts
> +  }
It is. That change does seem useful.

2022-11-10 12:25 UTC, coroiu commented on libs/components/src/input/input.directive.ts
> +  }
Ah cool! Very good to know!

2022-11-10 21:37 UTC, eliykat reviewed
As discussed in Slack, can you please add `spellcheck="false"` to the input associated with the toggle, to avoid browser spellchecking when it toggles to a plaintext input.

It might also be worth attaching the other attributes in the `InputVerbatimDirective`, but that might be mixing concerns. I mostly mention `spellcheck` because it's a security concern.

2022-11-11 13:29 UTC, Hinton commented on libs/components/src/input/input.directive.ts
> +  }
Changed to `runOutsideAngular` not sure why that didn't work before.

2022-11-11 13:40 UTC, Hinton commented
@eliykat added spellcheck. I also wired up some tests and fixed the setTimeout.

2022-11-14 15:18 UTC, danielleflinn submitted a review, later dismissed

2022-11-14 16:11 UTC, coroiu reviewed
Looks good, mostly added comments to the tests. I'm basing the suggestions on my own newly published unit test conventions document https://bitwarden.atlassian.net/wiki/spaces/DEV/pages/312737793

2022-11-14 16:15 UTC, Hinton commented on libs/components/src/input/input.directive.ts
> +  }
Apparently not. Neither is `setType`. Will have to figure out if we should allow access to the property or go through setters.

2022-11-15 08:27 UTC, coroiu commented on libs/components/src/input/input.directive.ts
> +  }
I've used a separate function in #4057 because it allows me to use different types (the property supports more values that the generic interface allows for)

https://github.com/bitwarden/clients/blob/c36da10581b7fd0464af514636fb2b6a375c24c2/libs/components/src/icon-button/icon-button.component.ts#L5

https://github.com/bitwarden/clients/blob/c36da10581b7fd0464af514636fb2b6a375c24c2/libs/components/src/icon-button/icon-button.component.ts#L138-L140

2022-11-16 01:25 UTC, eliykat commented on libs/components/src/form-field/password-input-toggle.spec.ts
> +  });
I don't understand how this is necessarily better. In both approaches you're asserting multiple things per test (which I think is fine).

Oscar's approach groups the assertions by the thing being tested (testing the icon, then testing the input type), your approach groups by state (initial state vs. toggled state). I think the former approach better separates and describes the behaviour we're testing.

For example, your test names aren't accurate - I wouldn't expect `should toggle type to text when current type is password` to test the button icon, for example. To properly describe the test, it would have to be called `should toggle type to text, change the icon button to bwi-eye-slash, and spellcheck to false, when current type is password`.

Now that I write that out, maybe that does suggest that we could extract the "toggled" state to a describe block, like

```ts
describe("when toggled", () => {
  beforeEach(() => toggleInput());

  it.todo("sets the input to text");
  it.todo("sets the icon to bwi-eye-slash");
  it.todo("sets spellcheck to false");
});
```

2022-11-16 01:25 UTC, eliykat commented on libs/components/src/input/input.directive.ts
> +  }
Why is a setter required? For type safety?

2022-11-16 01:25 UTC, eliykat commented on libs/components/src/input/input.directive.ts
> +    this.ngZone.runOutsideAngular(() => {
This also makes sense as a solution! And is simpler.

2022-11-16 01:26 UTC, eliykat commented
Mostly just responded to @coroiu's review, otherwise looks good to me.

2022-11-17 14:48 UTC, coroiu commented on libs/components/src/input/input.directive.ts
> +  }
I'm guessing to block getting the value?

2022-11-17 22:00 UTC, eliykat approved these changes
Nicely done, and thanks for adding the spellcheck stuff!

2022-11-18 12:01 UTC, coroiu approved these changes
Awesome work with the tests!

2022-11-28 13:04 UTC, merged