[EC-14] Part II: Add Collection Rows to Vault List
bitwarden/clients pull request #3875
Opened 2022-10-21 17:00 UTC by jlf0dev

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

This PR is for the second half of [EC-14](https://bitwarden.atlassian.net/browse/EC-14), more specifically: 
- [EC-71](https://bitwarden.atlassian.net/browse/EC-71): Add Collections as rows in the vault table
- [EC-62:](https://bitwarden.atlassian.net/browse/EC-62) Update Collection row options
- [EC-60](https://bitwarden.atlassian.net/browse/EC-60): Add Collection column
- [EC-59](https://bitwarden.atlassian.net/browse/EC-59): Create Header

This PR is a follow up to #3440, where we refactored the vault filter extensively to make the collection rows possible. There are some minor UI changes in that PR that I will not repeat here, might be worth a look.

This PR has a server dependency [TBA]

Overview of features added:
- Vault table now uses the table in the component library
- Vault table now has a header
    - Header includes a checkbox for select all. In the end user vault, this will select all ciphers. In the org vault, this will select ciphers and collections
    - Header also includes an options button, where you can perform bulk actions on the selected items
- Collections are now rows in the vault _only when a Collection Filter is applied_
- Collections rows are navigatable, you can select a Collection to "drill down" (basically apply that filter)
- Paging in the vault should take into account Collection rows, as well as Cipher rows
- You can perform actions on Collections only in the org vault
    - Deleting is the only option that currently works, Access and Edit Info will be added once [EC-73](https://bitwarden.atlassian.net/browse/EC-73) is finished
- The org vault table now includes a column for "Collections" and "Groups"
    - "Collections" is available when filter by cipher type
    - "Groups" is available when filtering by collection

Known issues:
- Access and Edit Info added once [EC-73](https://bitwarden.atlassian.net/browse/EC-73) is finished
- Collections are not currently searchable, they will be hidden once a search is initiated
- [EC-424](https://bitwarden.atlassian.net/browse/EC-424) will follow up this to remove the leftover Action and New Item menus

## Code changes

The main technical ideas include:
- I used the `selectedCollectionNode.children` from the `vault-filter.model` to show the Collection Rows in the vault. This allows me to navigate easily in the vault list by setting the `selectedCollectionNode` to whatever child was selected.
- The organization vault gets the ciphers and collections from the API as opposed to the sync used in the end user vault. I added new endpoint that returns me collections with associated groups (hence the server dependency).
- There is an endpoint added to allow bulk delete of collections (another server dependency).
    - most of the bulk operations logic has been moved into the ciphers component. The bulk actions component will be removed in [EC-424](https://bitwarden.atlassian.net/browse/EC-424)
- I have added badge components for showing the groups and collections in the org vault.
- 

## Screenshots

End User Vault:
![image](https://user-images.githubusercontent.com/24985544/197249026-a5f21065-9e32-41b1-8970-e4df0e36fb73.png)

Org Admin Vault:
![image](https://user-images.githubusercontent.com/24985544/197249339-2dd1b814-bc0d-4de3-88da-a608e00092dc.png)

![image](https://user-images.githubusercontent.com/24985544/197249419-161074a6-49ce-46fb-9bbf-626a4c106345.png)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-10-25 13:59 UTC, coroiu reviewed
I've only made it through half of the PR but I wanted to submit my comments before continuing. 

One thought I had in general is the handling of collections inside the ciphers component. We're handling them completely separately which results in a few edge cases that we need to add complex code for. Couldn't we add an encapsulation object that supports both collections and ciphers that we can use to display each row instead? That way we won't have to write paging logic or calculate selection logic  for two different types of objects.

I was thinking about something along the line of 

```
interface CipherRow {
  name: string;
  selected: boolean;
  value: CipherView | CollectionView;
}
```

2022-10-25 13:59 UTC, coroiu commented on apps/web/src/app/organizations/vault/ciphers.component.ts
> +  }
suggestion: remove function and use `checkCollection` directly

2022-10-25 13:59 UTC, coroiu commented on apps/web/src/app/organizations/vault/ciphers.component.ts
> +    (c as any).checked = select == null ? !(c as any).checked : select;
issue: we should probably avoid casting objects to `any`. Can we solve this in another way? Can we use two separate functions instead? Or maybe check the type with `instanceof` ?

2022-10-25 13:59 UTC, coroiu commented on apps/web/src/app/organizations/vault/ciphers.component.ts
> +  }
suggestion: would it be possible to split this function into two? One called `setCollectionCheck(c, select: boolean)` and one called `toggleCollectionCheck(c)` ?

2022-10-25 13:59 UTC, coroiu commented on apps/web/src/app/organizations/vault/ciphers.component.ts
> +    return this.activeFilter.selectedCollectionNode?.children.filter((c) => !!(c as any).checked);
issue: casting to `any`

2022-10-25 13:59 UTC, coroiu commented on apps/web/src/app/organizations/vault/ciphers.component.ts
> +  getSelectedCollections(): TreeNode<CollectionFilter>[] {
suggestion: convert this to a getter

```
get selectedCollections(): ...
```

2022-10-25 13:59 UTC, coroiu commented on apps/web/src/app/organizations/vault/ciphers.component.ts
> +  getSelectedCollectionIds(): string[] {
suggestion: same here, convert to getter

2022-10-25 13:59 UTC, coroiu commented on apps/web/src/app/organizations/vault/ciphers.component.ts
> +  }
question: I'm assuming these are placeholder for my own dialog, but do we need 2 placeholders? Shouldn't it be the same dialog?

2022-10-25 13:59 UTC, coroiu commented on apps/web/src/app/organizations/vault/collection-badge/collection-name.badge.component.ts
> +export class CollectionNameBadgeComponent {
I think @shane-melton has implemented this exact same component but added it to the CL.
See https://github.com/bitwarden/clients/pull/3563/files#diff-c382ceccac4254a27dc9c5ee5242e0ce45671e7e46a33116d43ab0326ef7a49fR9

suggestion: talk with Shane  😅

2022-10-25 14:03 UTC, coroiu commented on apps/web/src/app/organizations/vault/ciphers.component.ts
> +    return this.organization?.canEditAnyCollection && c.hasOldAttachments;
That's probably a bad idea which is gonna come back to bite us when we turn on strict mode. Ignore the suggestion.

2022-10-25 19:09 UTC, jlf0dev commented on apps/web/src/app/organizations/vault/ciphers.component.ts
> +  showOrganizationBadge = false;
good catch, removed.

2022-10-25 19:16 UTC, jlf0dev commented on apps/web/src/app/organizations/vault/ciphers.component.ts
>      this.deleted = deleted || false;
replaced

2022-10-25 22:19 UTC, jlf0dev commented on apps/web/src/app/organizations/vault/ciphers.component.ts
> +  getSelectedCollections(): TreeNode<CollectionFilter>[] {
converted

2022-10-25 22:19 UTC, jlf0dev commented on apps/web/src/app/organizations/vault/ciphers.component.ts
> +  getSelectedCollectionIds(): string[] {
converted

2022-10-25 22:21 UTC, jlf0dev commented on apps/web/src/app/organizations/vault/ciphers.component.ts
> +  }
I think the UI has two buttons, one for accessing each tab. I guess it could be a single method with a parameter though.

2022-10-25 22:23 UTC, jlf0dev commented on apps/web/src/app/organizations/vault/vault-filter/vault-filter.service.ts
> +  private _collections = new ReplaySubject<CollectionGroupDetailsView[]>(1);
A behavior subject must have an initial value, this won't be set until we set the org and call the api.

2022-10-25 22:24 UTC, jlf0dev commented on apps/web/src/app/organizations/vault/vault-filter/vault-filter.service.ts
> +      const collectionResponse = await this.apiService.getManyCollectionsWithDetails(org.id);
Agreed, there's a lot that will need to be moved over following our work here.

2022-10-25 22:27 UTC, jlf0dev commented
Started addressing some of the feedback.

Just so you're aware, I also did some work on removing nested subscriptions in [0bce28f](https://github.com/bitwarden/clients/pull/3875/commits/0bce28fcdca379a1f159a6cd1c1188947d3f0966). It was a pretty self contained change.

2022-10-26 00:15 UTC, jlf0dev commented on apps/web/src/app/organizations/vault/ciphers.component.ts
> +  }
The organization vault actually has a different behavior when you select a collection versus the end user vault. So I was overriding `selectCollection` here in the org vault and using it to check a collection (a behavior we don't have in the end user vault)

2022-10-26 00:22 UTC, jlf0dev commented on apps/web/src/app/organizations/vault/ciphers.component.ts
>        await super.applyFilter(f);
I _wish_ I could prove that the apply filter isn't called before an organization is loaded. To be fair, the only route that will kick this off from outside the component is a `reload()` coming from the `vault.component`, but I can't prove that it won't happen. Something is very wrong if we don't load the organization before everything else though.

I could add a guard that returns early here? What were you imagining it would look like?

2022-10-26 05:40 UTC, coroiu commented
> I very much agree with your idea, but I am reluctant to make a view model change like that when we're close to a deadline. I'll take a look though and see how involved it would be.

I was thinking the type would be entirely contained inside the cipher component, so no repo-wide view model changes

2022-10-26 05:42 UTC, coroiu commented on apps/web/src/app/organizations/vault/ciphers.component.ts
> +    }
> I'm hoping this particular method (refreshing the current collection) might be fixed once we transition the model to be an observable, that way collection changes will bubble up and the UI will update.

Yeah I was thinking the same thing, ok let's leave it like it is for now then!

2022-10-26 05:57 UTC, coroiu commented on apps/web/src/app/organizations/vault/vault-filter/vault-filter.service.ts
> +  private _collections = new ReplaySubject<CollectionGroupDetailsView[]>(1);
https://medium.com/javascript-everyday/behaviorsubject-vs-replaysubject-1-beware-of-edge-cases-b361153d9ccf

I don't think we're negatively impacted by the slightly different behavior (at the moment), but I think it would be nice just out of consistency.

If we're worried about the initial `null` value then we can filter it out

```ts
private _collections = new ReplaySubject<...>(1);
collections$ = this._collections.pipe(filter(c => c != null));
```

If I haven't convinced you with this message then I will drop my case 😁

2022-10-28 15:01 UTC, coroiu commented on apps/web/src/app/vault/ciphers.component.html
> +              *ngIf="organization && col.node.name !== 'Unassigned'"
question: Will `col.node.name !== 'Unassigned'"` work on vaults with other languages?

2022-11-01 12:46 UTC, coroiu requested changes
I've gone through the whole PR now! Ping me when the changes are ready to be reviewed :)

2022-11-01 12:46 UTC, coroiu commented on apps/web/src/app/vault/ciphers.component.html
> +              profileName="{{ profileName }}"
nit:
```suggestion
              [profileName]="profileName"
```

2022-11-01 12:46 UTC, coroiu commented on apps/web/src/app/vault/ciphers.component.html
> +              (onOrganizationClicked)="onOrganizationClicked(c.organizationId)"
thought(non-blocking): this should probably called `(click)` but it's not a change from this PR so don't worry about it 🙂

2022-11-01 12:46 UTC, coroiu commented on apps/web/src/app/organizations/vault/collection-badge/collection-name.badge.component.ts
> +  @Input() collections: CollectionView[];
question: why do we need both `collectionIds` and `collections`? Doesn't the `CollectionView` contain ids?

2022-11-01 12:46 UTC, coroiu commented on apps/web/src/app/vault/pipes/get-collection-name.pipe.ts
> +    return collections.find((o) => o.id === value)?.name;
thought: This is quite inefficient, but for only a few collections the impact is probably negligible. Not sure if there are any organizations with hundreds of collections and/or groups paired with many ciphers that are assigned to many of the previously mentioned collections and/or groups.

2022-11-01 12:46 UTC, coroiu commented on apps/web/src/locales/en/messages.json
> +    "message": "Edit Info"
question: Aren't we moving away from sentence case?
```suggestion
    "message": "Edit info"
```

2022-11-01 12:46 UTC, coroiu commented on libs/common/src/abstractions/organization/organization.service.abstraction.ts
> +    org.isManager
question: do we need to modify this in any way given the discussions we've had about this?
eg.
https://github.com/bitwarden/clients/pull/3913#pullrequestreview-1160124167

2022-11-02 15:07 UTC, jlf0dev commented on apps/web/src/app/organizations/vault/ciphers.component.ts
> +    (c as any).checked = select == null ? !(c as any).checked : select;
Introduced `VaultItemRow` to avoid casting to `any`

2022-11-02 15:09 UTC, jlf0dev commented on apps/web/src/app/organizations/vault/ciphers.component.ts
> +  }
I'm not sure more methods would be an ideal situation, but I have simplified it to be `checkRow` instead of having one for each. The logic is also a lot easier to read with null coalescing:
``` javascript
    item.checked = select ?? !item.checked;
```

2022-11-02 15:09 UTC, jlf0dev commented on apps/web/src/app/organizations/vault/ciphers.component.ts
> +    return this.activeFilter.selectedCollectionNode?.children.filter((c) => !!(c as any).checked);
Introduced `VaultItemRow`

2022-11-02 15:10 UTC, jlf0dev commented on apps/web/src/app/organizations/vault/ciphers.component.ts
> +    const [modal] = await this.modalService.openViewRef(
Yep! Refactored each bulk action to be a dialog that uses the dialog service now!

2022-11-02 15:18 UTC, jlf0dev commented on apps/web/src/app/organizations/vault/vault-filter/vault-filter.component.ts
> +      this.activeFilter.resetFilter();
Each vault (org vault/end user vault) has a default filter selected. This was my (less than ideal honestly 😅 ) way of setting the filter when the page loads.

We need a better way to do this but I haven't come up with it yet. Once we integrate the model with the vault filter service I think it will be easier

2022-11-09 14:15 UTC, coroiu commented on apps/web/src/app/organizations/vault/ciphers.component.ts
> +  }
Ah right! Ignore this then! :)

2022-11-10 09:58 UTC, coroiu reviewed
New dialogs looking good!

2022-11-10 09:58 UTC, coroiu commented on apps/web/src/app/shared/shared.module.ts
> +  DialogModule,
suggestion(non-blocking): instead of adding the dialog module to the shared module we could instead move each dialog into it's own module and then simply load those modules inside of `VaultModule`. That way we don't increase the size of the shared module and at the same time get rid of stuff from the oversized `loose-components.module` which will help with lazy loading in the future.

So basically we would get a folder for each dialog, and then import them inside the vault-module file.

```
  - web/src/vault
    - bulk-delete-dialog
       bulk-dialog-dialog.module.ts
    - bulk-move-dialog
       bulk-move-dialog.module.ts
     vault.module.ts

2022-11-10 10:01 UTC, coroiu commented on apps/web/src/app/organizations/vault/ciphers.component.ts
> +    const [modal] = await this.modalService.openViewRef(
And it's looking good!!

2022-11-10 10:02 UTC, coroiu commented on apps/web/src/app/organizations/vault/vault-filter/vault-filter.component.ts
> +      this.activeFilter.resetFilter();
Ok let's leave as-is for now then!

2022-11-10 10:04 UTC, coroiu commented on apps/web/src/app/vault/bulk-delete.component.ts
> +    this.formPromise = Promise.all(deletePromises);
Which you have now done! Marking this as resolved

2022-11-10 10:05 UTC, coroiu commented on apps/web/src/app/vault/bulk-delete.component.ts
>      const deleteRequest = new CipherBulkDeleteRequest(this.cipherIds, this.organization.id);
In the interest of getting these PRs merge we can view this as a non-blocking suggestion. Feel free to ignore!

2022-11-11 17:24 UTC, jlf0dev commented on apps/web/src/app/shared/shared.module.ts
> +  DialogModule,
Moved all the dialogs into one module 👍

2022-11-11 17:33 UTC, jlf0dev commented on apps/web/src/app/vault/bulk-move-dialog.component.ts
> +  formPromise: Promise<any>;
removed

2022-11-11 17:35 UTC, jlf0dev commented on apps/web/src/app/vault/bulk-delete-dialog.component.ts
>    formPromise: Promise<any>;
Yeah I guess we can remove this, I was planning on taking advantage of it before I started using your handy new `bitAction` 😄

2022-11-11 18:12 UTC, jlf0dev commented on apps/web/src/app/vault/bulk-actions.component.ts
> +    const result = (await lastValueFrom(dialog.closed)) as BulkMoveDialogResult | undefined;
Good idea, removed all that

2022-11-11 18:16 UTC, jlf0dev commented on apps/web/src/app/organizations/vault/ciphers.component.ts
>      }
javascript 😠

2022-11-11 18:17 UTC, jlf0dev commented on apps/web/src/app/organizations/vault/ciphers.component.ts
> +    this.deleted = deleted ?? false;
fixed!

2022-11-15 15:17 UTC, jlf0dev commented on apps/web/src/app/vault/ciphers.component.html
> +              *ngIf="organization && col.node.name !== 'Unassigned'"
Nice catch, forgot to come back and clean this up 😅

2022-11-15 15:20 UTC, jlf0dev commented on apps/web/src/app/vault/ciphers.component.html
> +    class="!tw-table-fixed"
I accidentally left this in there, but its not needed. Originally I wanted to keep the table header visible even if there wasn't any ciphers (and this would stop the columns from changing sizes), but noticed all the other tables would be different. Every other table hides the whole table if its empty. 

I think in the future, maybe VVR, we can change that? I think it would be a better user experience.

2022-11-15 15:37 UTC, jlf0dev commented on apps/web/src/app/organizations/vault/ciphers.component.ts
> +    this.deleted = deleted ?? false;
Oh wow so this broke a lot. We're probably passing in a `null` or `undefined` value to `deleted`. We need the default assignment to catch those instances.

2022-11-15 15:40 UTC, jlf0dev commented on apps/web/src/app/vault/ciphers.component.html
> +    *ngIf="filteredCiphers.length || (filteredCollections?.length && showCollections)"
We actually were able to simplify this to just `filteredCiphers.length || filteredCollections.length` during our pair programming 😄 

(we can also remove the optional chaining from collections since we initialize everything to an empty array now)

2022-11-16 07:36 UTC, coroiu commented on apps/web/src/app/organizations/vault/ciphers.component.ts
> +    this.deleted = deleted ?? false;
What how? 😅

2022-11-21 12:07 UTC, coroiu commented on libs/common/src/abstractions/organization/organization.service.abstraction.ts
> +    org.isManager
Resolving as change was reverted

2022-11-30 14:52 UTC, jlf0dev commented on apps/web/src/app/organizations/vault/vault.component.ts
> +      await this.syncService.fullSync(false);
Yeah i'm not sure how this is working, but moved below the subscription

2022-11-30 15:01 UTC, jlf0dev commented on apps/web/src/app/organizations/vault/vault.component.ts
> +            (await this.cipherService.get(cipherId)) != null
moved to switchMap

2022-11-30 16:33 UTC, jlf0dev commented on apps/web/src/app/organizations/vault/vault.component.ts
> +    });
added to both vaults

2022-11-30 16:33 UTC, jlf0dev commented on apps/web/src/app/organizations/vault/vault.component.ts
> +      .subscribe(async ([qParams, params]) => {
added

2022-11-30 16:35 UTC, jlf0dev commented on libs/common/src/misc/serviceUtils.spec.ts
> +describe("serviceUtils", () => {
These tests have previously been reviewed in #4092

2022-12-05 09:08 UTC, coroiu reviewed
In general I think this PR looks good to go, comments are mostly non-blocking and can be ignored. Otherwise some nitpicks and a question for design regarding the full-width layout

2022-12-05 09:08 UTC, coroiu commented on apps/web/src/app/vault/ciphers.component.html
> +        <td bitCell class="tw-w-72" (click)="selectRow(col)">
question: How does this work with full width layout? How is it *supposed* to work? 

Should we use percentage widths for the columns sizes in the vault ciphers list? @bitwarden/dept-design

2022-12-05 09:08 UTC, coroiu commented on apps/web/src/app/vault/vault.component.ts
> +        first(),
question: why only `first` ?

2022-12-05 14:52 UTC, jlf0dev commented on apps/web/src/app/vault/vault.component.ts
> +        first(),
These are operations that should be done the first time we navigate to the vault, but not every time we change the query parameters (to view a certain cipher, etc.)

2022-12-05 14:55 UTC, jlf0dev commented on apps/web/src/app/vault/bulk-action-dialogs/bulk-move-dialog/bulk-move-dialog.component.ts
> +  selector: "app-vault-bulk-move",
renamed

2022-12-05 17:59 UTC, danielleflinn commented on apps/web/src/app/vault/ciphers.component.html
> +        <td bitCell class="tw-w-72" (click)="selectRow(col)">
Yes percentage widths makes sense to me. I think that is how we have the component library tables.

2022-12-07 19:43 UTC, jlf0dev commented on apps/web/src/app/vault/ciphers.component.html
> +        <td bitCell class="tw-w-72" (click)="selectRow(col)">
Removed the hardcoded values and replaced with percentages in [1281e3f](https://github.com/bitwarden/clients/pull/3875/commits/1281e3fa0236a30a7b154e99a76566738b156368)

One thing to note is that this will cause the table columns to change width based on whats visible. The only way to fix this is would be to add `table-layout:fixed` to our component. I think thats outside of the scope of this PR but is something we should consider moving forward to VVR.

2022-12-08 16:19 UTC, coroiu approved these changes
Looks good!

2022-12-19 17:40 UTC, merged