[EC-342] Gate custom permissions behind enterprise plan
bitwarden/clients pull request #3907
Opened 2022-10-27 13:58 UTC by r-tome

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [X] Other
```

## Objective

Update the Invite User and Edit User modals need to have updated descriptions for each user type. Only allow selecting the 'Custom' type if the organization has an Enterprise license.

## Code changes

This pull request has a [related pull request](https://github.com/bitwarden/server/pull/2352) in the server repo.

- **apps/web/src/app/organizations/manage/user-add-edit.component.html:** Description of what was changed and why
- **apps/web/src/app/organizations/manage/user-add-edit.component.ts:** 
- **apps/web/src/locales/en/messages.json:** Add 
- **libs/common/src/models/data/organization.data.ts:** Add 'useCustomPermissions' property
- **libs/common/src/models/domain/organization.ts:** Add 'useCustomPermissions' property
- **libs/common/src/models/response/profile-organization.response.ts:** Add 'useCustomPermissions' property and get the matching value from the API response

## Screenshots

<img width="797" alt="image" src="https://user-images.githubusercontent.com/108268980/198298672-c6a19deb-732c-46b7-a81c-5e1ae0d4805a.png">
<img width="795" alt="image" src="https://user-images.githubusercontent.com/108268980/198298772-32518080-a587-4634-ba6c-58a160148b6d.png">

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-11-11 02:17 UTC, eliykat requested changes

2022-11-11 02:17 UTC, eliykat commented on apps/web/src/locales/en/messages.json
> +    "message": "Custom roles is an <a href=\"https://bitwarden.com/contact/\" target=\"_blank\">enterprise feature</a>. Contact our support team to upgrade your subscription",
There's no good way around it, you have to split it into 3 parts. Including HTML in it is a problem for 2 reasons:

1. it's difficult for translators to translate because now there's code in the string
2. it risks injection attacks, a translator could put malicious HTML or even Javascript in here and it would be injected into the webpage, because you're inserting it as HTML. (Keeping in mind that translations are synced from CrowdIn, an external source)

When you split it, make sure to include descriptions containing the full sentence, so that translators have context when they translate each part. See here as an example: https://github.com/bitwarden/clients/blob/master/apps/web/src/locales/en/messages.json#L1299-L1305

2022-11-11 02:17 UTC, eliykat commented on apps/web/src/app/organizations/manage/user-add-edit.component.html
> +              <small [innerHTML]="'customDescNonEnterprise' | i18n"></small>
Move the i18n strings out of innerHTML when you split them up. See my other comment for more info.

2022-11-11 02:17 UTC, eliykat commented on apps/web/src/app/organizations/manage/user-add-edit.component.ts
> +      organization.useCustomPermissions && organization.planProductType === ProductType.Enterprise;
Do you need to check the `planProductType` here? Only enterprise should have `useCustomPermissions` set to `true`.

2022-11-11 02:17 UTC, eliykat commented on apps/web/src/app/organizations/manage/user-add-edit.component.ts
> +    if (!this.canUseCustomPermissions && this.type === OrganizationUserType.Custom) {
CodeScene is giving you a cyclomatic complexity warning here. Please try some refactoring to reduce the length/complexity of this method. There's nothing wrong with the code you've added, it's just tipped it over the edge.

I'd recommend extracting the 2 branches of `if (this.editMode)` into 2 separate methods, e.g.

```ts
if (this.editMode) {
  updateUser();
} else {
  inviteUser();
}
```

2022-11-11 02:17 UTC, eliykat commented on apps/web/src/locales/en/messages.json
> +    "message": "Create, delete, and manage access in assigned collections."
```suggestion
    "message": "Create, delete, and manage access in assigned collections"
```

2022-11-15 11:08 UTC, r-tome commented on apps/web/src/app/organizations/manage/user-add-edit.component.html
> +            [attr.disabled]="!canUseCustomPermissions || null"
Otherwise it adds the attribute `disabled=false` and the browser ignores the actual value, it just checks if the disabled attribute is present and the button is disabled.

2022-11-15 11:22 UTC, r-tome commented on apps/web/src/locales/en/messages.json
> +    "message": "Custom roles is an <a href=\"https://bitwarden.com/contact/\" target=\"_blank\">enterprise feature</a>. Contact our support team to upgrade your subscription",
I did not think of injection attacks, that is an excellent point. I've split this text into 3 parts.

2022-11-15 11:23 UTC, r-tome commented on apps/web/src/app/organizations/manage/user-add-edit.component.ts
> +      organization.useCustomPermissions && organization.planProductType === ProductType.Enterprise;
You are correct, `useCustomPermissions` check is enough.

2022-11-17 06:25 UTC, eliykat approved these changes

2022-12-06 09:50 UTC, merged