Desktop/Browser/Web: tweak disclosure widget design
bitwarden/clients pull request #3951
Opened 2022-11-02 23:18 UTC by patrickhlauke

## Type of change

```
- [x] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Currently, there are disclosure widgets that use the `bwi-chevron-down` (when closed) and `bwi-angle-up` (when open), and have the icon positioned after their text.

The up/down chevron looks slightly confusing, and is not consistent with other disclosure widgets that use `bwi-angle-right` (when closed) and `bwi-angle-down` (when open) (e.g. in the left-hand column on desktop/web). These other disclosure widgets also have the icon positioned to the left or the text, not the right.

This PR changes the former type of disclosure widget control to match the latter.

In addition, this PR makes a first tiny change to the web interface, to use `<button>` for the one disclosure widget (in "Send") it uses.

## Code changes

- **apps/browser/src/popup/send/send-add-edit.component.html**, **apps/browser/src/popup/settings/options.component.html**,  **apps/desktop/src/app/accounts/settings.component.html**, **apps/desktop/src/app/send/add-edit.component.html**: move the icon to the start of the `<button>`, change the `bwi-...` icons used
- **apps/browser/src/popup/scss/box.scss** and **apps/desktop/src/scss/box.scss**: change the margin from left to right to account for new icon position
- **apps/web/src/app/send/add-edit.component.html**: change the structure to `<h3><button>...</button></h3>` (to match changes made to desktop/browser apps ages ago), move the icon to the start of the `<button>`, change the `bwi-...` icons used
- **apps/web/src/scss/buttons.scss**: add new styles for the new button (since the web version doesn't use/have the same `.box .box-header-expanded` styles as desktop/browser
- **libs/components/src/link/link.stories.ts**: change the storybook examples to have icon before text, use correct `bwi-...` icon

## Screenshots

Before/after comparisons (where the "before" is the current master branch, NOT the latest stable release - incidentally, nice work on the browser style refresh, hoping to see this make its way to the desktop app and eventually the web)

### Desktop

Send before:

![desktop-send-before](https://user-images.githubusercontent.com/895831/199619210-2a0ed4c4-aae5-43e6-aed3-246638f837a0.png)

![desktop-send-before2](https://user-images.githubusercontent.com/895831/199619222-93db5492-b35d-4b22-894e-4563a70097ca.png)

Send after:

![desktop-send-after](https://user-images.githubusercontent.com/895831/199619248-2244559a-6ffd-4aad-86ec-f9a9c860d592.png)

![desktop-send-after2](https://user-images.githubusercontent.com/895831/199619255-f3f0005a-44b7-4abe-8f7b-a3be59362581.png)

---

Settings before:

![desktop-settings-before](https://user-images.githubusercontent.com/895831/199619291-5faf55cf-2614-4744-baa3-cfb8c728aa66.png)

Settings after:

![desktop-settings-after](https://user-images.githubusercontent.com/895831/199619302-eadbf4e8-7c5e-48c8-8907-fbd12547879c.png)

### Browser

Send before:

![browser-send-before](https://user-images.githubusercontent.com/895831/199619347-c6f2fd40-fc29-489d-9e52-d2bb25b164d2.png)

![browser-send-before2](https://user-images.githubusercontent.com/895831/199619365-0c485ad9-fd9f-4173-9414-0cdc52cb8c58.png)

Send after:

![browser-send-after](https://user-images.githubusercontent.com/895831/199619383-158b7a56-b030-4d6d-bf32-2d1766aa2af3.png)

![browser-send-after2](https://user-images.githubusercontent.com/895831/199619391-65e7dc02-97a8-49bf-9099-295c8f7e5ea9.png)

---

Options before:

![browser-options-before](https://user-images.githubusercontent.com/895831/199619456-93f55416-264c-4f34-9eff-79d0a7c91829.png)

![browser-options-after](https://user-images.githubusercontent.com/895831/199619468-5ffe346d-1462-4c91-afd7-b2622898aed3.png)

### Web

Send before:

![web-send-options-before](https://user-images.githubusercontent.com/895831/199619531-b067109c-5d7d-440d-b373-ec1486ac5c8e.png)

![web-send-options-before2](https://user-images.githubusercontent.com/895831/199619545-ed08645c-6482-4f7e-b111-b9c0337f5842.png)

Send after:

![web-send-options-after](https://user-images.githubusercontent.com/895831/199619567-2a5640d7-32d9-4043-86c3-fc97f9c14ff3.png)

![web-send-options-after2](https://user-images.githubusercontent.com/895831/199619579-0cf180ea-284b-4ea4-a930-f4bead7c93c5.png)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-11-03 08:33 UTC, patrickhlauke commented
/cc @danielleflinn and the design team

2022-11-07 18:55 UTC, danielleflinn requested changes
Thank you for this contribution. Can you also address the expand/collapse button in the desktop generator dialog? Currently it uses different icons than these other instances while providing the same behavior.

2022-11-07 19:26 UTC, patrickhlauke commented
> Can you also address the expand/collapse button in the desktop generator dialog?

Ah, that one slipped me by. Sure thing, will sort that tonight.

2022-11-07 20:51 UTC, patrickhlauke commented
@danielleflinn done. also spotted the same +/- icon in the custom environment component, and changed that as well

2022-12-03 10:14 UTC, patrickhlauke commented
@danielleflinn would you mind re-reviewing this to clear the "changes requested"?

2022-12-05 15:41 UTC, danielleflinn submitted a review, later dismissed

2022-12-05 15:42 UTC, patrickhlauke commented
thanks @danielleflinn

2022-12-05 19:46 UTC, djsmith85 requested changes
@patrickhlauke: Thank you again for your work on improving our clients.

Just had a quick search for `bwi-chevron-up` and I see at least 3 instances that would need to be checked:

- `apps\browser\src\popup\vault\vault-select.component.html`
- `apps\desktop\src\app\layout\account-switcher.component.html`
- `bitwarden_license\bit-web\src\app\organizations\manage\sso.component.html`

@danielleflinn Should we also update `libs\components\src\stories\icons.stories.mdx` with this PR?

I'll do a thorough review, once the changes have been made.

2022-12-05 19:49 UTC, patrickhlauke commented
> Just had a quick search for `bwi-chevron-up` and I see at least 3 instances that would need to be checked:
> 
> * `apps\browser\src\popup\vault\vault-select.component.html`
> * `apps\desktop\src\app\layout\account-switcher.component.html`
> * `bitwarden_license\bit-web\src\app\organizations\manage\sso.component.html`

Will check again, but from memory those act more like `<select>` dropdowns, so there it makes sense to have the up/down chevron. This here is specifically for expand/collapse disclosure widgets

> @danielleflinn Should we also update `libs\components\src\stories\icons.stories.mdx` with this PR?

I'll have a quick look there as well, just in case.

2022-12-05 21:40 UTC, danielleflinn approved these changes

2022-12-06 13:12 UTC, djsmith85 requested changes
@patrickhlauke Nice work on this and just one small thing I noticed while testing.

2022-12-06 13:12 UTC, djsmith85 commented on apps/web/src/app/send/add-edit.component.html
> +          <h3 class="mb-0 mr-2">
The markup looks good and behaves correctly, but when focussed, it looks weird with the jagged outline:
![image](https://user-images.githubusercontent.com/2670567/205920680-a88a3ac3-474d-47e8-b556-d6008ad1ebbc.png)

2022-12-07 22:51 UTC, patrickhlauke commented on apps/web/src/app/send/add-edit.component.html
> +          <h3 class="mb-0 mr-2">
@djsmith85 Fixed (with an admittedly ugly super-specific patch, but I can't quite work out where within the cascade the line height gets messed up).

![screenshot showing the fixed focus outline on Options](https://user-images.githubusercontent.com/895831/206313895-c0954bbe-0755-43ae-ad45-3988e2da7eca.png)

2022-12-08 11:57 UTC, djsmith85 approved these changes
@patrickhlauke: Changes are looking good and are ready to get passed on to QA.

2022-12-15 14:13 UTC, djsmith85 commented
@patrickhlauke Received approval from QA. Thank you for your work on this and this will be included in the next release.

2022-12-15 14:13 UTC, merged

2022-12-15 14:56 UTC, patrickhlauke commented
perfect, thank you @djsmith85 @danielleflinn