[EC-683] Remove Search Pipe
bitwarden/clients pull request #3981
Opened 2022-11-04 18:50 UTC by jlf0dev

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Angular recommends that you [don't add filtering or sorting logic to pipes](https://angular.io/guide/styleguide#do-not-add-filtering-and-sorting-logic-to-pipes), as these can be called frequently which can hurt performance. We don't use our `search.pipe` and `search-ciphers.pipe` much throughout our codebase, so it's best to get rid of the pipes now.

I've moved all the search logic to the `search.service`, added unit tests, and replaced all occurrences. 

## Code changes

See commit log for more information

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-11-04 19:20 UTC, shane-melton requested changes
I like the search service instead of the pipe, but, we'll need to re-look at using it in `getters` as I believe we'll still suffer from performance problems.

2022-11-04 19:20 UTC, shane-melton commented on apps/web/src/app/organizations/manage/collections.component.html
> +  <h1>{{ "collections" | i18n }} HI</h1>
Hi there!

(Probably should remove this haha)

2022-11-04 19:20 UTC, shane-melton commented on apps/web/src/app/organizations/manage/collections.component.ts
> +    return this.searchService.searchBasic(this.collections, this.searchText, "name", "id");
I don't believe we can put the call to the `searchService` in a `getter` accessed by the template. Angular will execute/call the `getter` for every change detection cycle because it can't know if the value changed without calling the `getter`.

We'd need to put the filtered results in a property and update it via the search service each time the search text changes (or the source list of collections change). That way Angular knows when the filtered results change and doesn't need to call the `searchService` itself (we would control it explicitly)

2022-11-07 14:02 UTC, Hinton reviewed
Hmm interesting,

Sort and Filter pipes seems to be a fairly debated topic for Angular. Our pipes are pure meaning they won't suffer from the issues described since they only update if the reference has changed. However they do suffer from the slightly odd behavior of not updating when the source array is changed since the reference is identical.

In general there's nothing wrong with this change, but I would like to investigate if we could move towards implementing a DataSource similar to Angular Material, https://material.angular.io/components/table/api#MatTableDataSource

2022-11-08 17:14 UTC, jlf0dev commented
> Our pipes are pure meaning they won't suffer from the issues described since they only update if the reference has changed
This is a good point that I completely missed. Considering the amount of additional code we would have to write in order to avoid using getters (which as @shane-melton pointed out, introduces the same problems) means that there isn't a strong enough reason to make this change yet. A DataSource is a better direction to move towards.

Going to close this for now.

2022-11-08 17:14 UTC, closed without merging