add run-name for releases to include their workflow trigger
bitwarden/clients pull request #3996
Opened 2022-11-07 16:25 UTC by Eebru-gzy

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [x] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
This PR updates the workflow runs to include their `workflow_dispatch` name in each run, this separates `dry run` releases runs from the actual releases runs.

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-11-07 16:36 UTC, vgrassia requested changes

2022-11-07 16:37 UTC, vgrassia commented
I tested the workflows on your branch and it seems like they work as intended.  When making changes to workflows in the future, it's always a good idea to run them (if possible) before marking a PR for review.

2022-11-07 17:01 UTC, Eebru-gzy commented
> I tested the workflows on your branch and it seems like they work as intended. When making changes to workflows in the future, it's always a good idea to run them (if possible) before marking a PR for review.

Noted, thanks

2022-11-08 15:02 UTC, vgrassia approved these changes

2022-11-08 15:02 UTC, merged