fix: manage zoom factor when opening / closing the application
bitwarden/clients pull request #4050
Opened 2022-11-13 16:27 UTC by CristianAUnisa

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Fix #2623
Zoom factor is saved into window state when closing the application and it's restored when opening it.
I'd like help with testing it on Windows and MacOS so I'm marking this as a draft pr.

## Code changes

- **window-state.ts:** Added optional zoomFactor property.
- **window.main.ts:** Added isClosing property to avoid assigning the zoomFactor property inside the window callbacks; wait for dom to be ready to restore the zoom factor.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-11-18 05:53 UTC, djsmith85 requested changes
@CristianAUnisa Thank you for your contribution and great work on this, just some minor things.

Any specific reason to only apply the zoomfactor on "dom-ready" instead on window creation?

After adjusting the `zoomFactor`'s type to `number`: I can confirm that, the zoomFactor is remembered and applied, on application starts under Windows 🎉

2022-11-18 05:53 UTC, djsmith85 commented on libs/common/src/models/domain/window-state.ts
> +  zoomFactor?: string;
Based on the [docs](https://www.electronjs.org/docs/latest/api/web-contents#contentszoomfactor) `zoomFactor` should be of type `number`.

Because it's currently marked as string, this also throws an exception when the desktop app is first booted up. Likely because of this [line](https://github.com/bitwarden/clients/pull/4050/files#diff-87ddc677c70c152b6e5d783dbf2b629395d10ddedfe2cfdf2eaf971e4cc6988cR134)

2022-11-18 05:53 UTC, djsmith85 commented on libs/electron/src/window.main.ts
>    private windowStates: { [key: string]: any } = {};
Using `WindowState` instead of any would give us types

2022-11-18 05:53 UTC, djsmith85 commented on libs/electron/src/window.main.ts
> +                this.win.webContents.zoomFactor = this.windowStates[mainWindowSizeKey].zoomFactor;
I don't think this is necessary as the window should have rendered and set the zoomFactor initially

2022-11-18 07:38 UTC, CristianAUnisa commented
Hey, I'm going to fix the issues this afternoon, thank you for the answer.

Regarding why I used the dom-ready event, I tried with the win.on show, ready and many other ones but I always had some other issues; the zoom factor would be preserved but if I tried to increase or decrease it after starting the application, the zoom wouldn't be calculated from the zoom factor I set (imagine starting the application with a zoom of 150%, you increase it and the ui elements get smaller, like it was increased from 100% to 110%). I took inspiration from the Standard Notes code like two users reported in the issue and it felt the most reliable way of setting it, but unfortunately I only have a small notebook with Linux for now; I'm going to run the automated and manual tests again after the new changes, but would you prefer if I squash them into a single commit?

2022-11-18 12:02 UTC, djsmith85 commented
@CristianAUnisa 
Ah I see, but the [issue](https://github.com/electron/electron/issues/7779) you are referring to which gets mentioned on the [standardnotes-app](https://github.com/standardnotes/desktop/pull/355/files#diff-9dd2ef73375d4789f09ba7e171931d29ed03f909b40595a3837a25ae26c6440eR12), is from an ancient electron version. Very likely, this was fixed, and we do not need to rely on that event. It's worth testing, especially since the values (numbers) should now be assigned and persisted properly.

If we can remove the listener, we might also not need to the `isClosing`-flag. I'd appreciate if you could test out those ideas and if they work I'more than happy to review and test them.

If you can, please just push additional commits instead of squashing, as that would re-write git-history. My comments from the review, would still point to lines of code which you already addressed.

If this is good to go, the whole PR will get squashed anyway before merging into master.

2022-11-18 19:53 UTC, CristianAUnisa commented on libs/electron/src/window.main.ts
>    private windowStates: { [key: string]: any } = {};
May I ask you what do you mean in this context?

2022-11-18 20:07 UTC, CristianAUnisa commented
@djsmith85 I tested the app again without the "dom-ready" listener without success:

- By setting the zoom factor attribute while creating the BrowserWindow in webContents
- By setting it after the window has been showed with win.show()

It didn't work; the window would show with a zoom factor saved probably from the closing event before the last one. The subsequent zoom factor is calculated based on the last zoom factor saved instead. I'm wondering about why this is happening because it feels like electron already attempts unsuccessfully to restore the previous zoom factor.

2022-11-22 20:55 UTC, djsmith85 commented on libs/electron/src/window.main.ts
>    private windowStates: { [key: string]: any } = {};
I meant using the type `WindowState` instead of `any`. This will give us type-information for anywhere where we access `windowStates`.

```suggestion
  private windowStates: { [key: string]: WindowState } = {};
```

2022-11-25 17:54 UTC, CristianAUnisa commented
@djsmith85 I pushed your suggestions. I'm trying again to find another way instead of listening to the "dom-ready" event. In the meanwhile, I could use WebContents.once instead of WebContents.on to remove the listener after the callback has been launched.

2022-12-06 14:53 UTC, djsmith85 requested changes
@CristianAUnisa I had another look at this today and played around with your code. I currently also see no other way of implementing this. Besides that your proposed solutions works fine 👍 .

Please pull in the lastest changes from master, resolving the merge conflict and I'll quickly re-review and then this should be ready to get passed on to QA.

Thank you for your time and great work on this ❤️

2022-12-07 10:15 UTC, djsmith85 approved these changes
@CristianAUnisa This is looking good and will now be passed on to QA for testing.

Once we get the approval from QA, this will get merged into `master`

2022-12-15 23:20 UTC, djsmith85 commented
@CristianAUnisa Just received approval from QA 🎉  This is ready to get merged and will be included in an upcoming release. 

Great work on this 👍

2022-12-15 23:20 UTC, merged