[CL-58] Make icon button compatible with bit suffix directive
bitwarden/clients pull request #4057
Opened 2022-11-14 14:55 UTC by coroiu

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

### Bug
Icon buttons didn't quite work as prefix/suffix elements in an input group. The reason was that the prefix/suffix directives assumed a default `secondary` button styling, which does not match the default behavior of the icon button.

### Complication
While attempting to fix the styling I noticed that the `secondary` was pretty different from the styling that's supposed to be applied when using the button as part of an input group. It's also difficult to override styles inside the directive leading to higher that necessary complexity.

### Fix
I chose to simply allow buttons to have their styling removed, granting directives a clean slate from which to freely style their element.

## Code changes

- **libs/components/src/async-actions/in-forms.stories.ts** Added an example of suffix being used with `[bitAction]`
- **libs/components/src/button/button.component.ts** Allow styling to be set to `undefined`. `secondary` is still the defaut.
- **libs/components/src/icon-button/icon-button.component.ts** Allow styling to be set to `undefined`. `main` is still the default.
- **libs/components/src/form-field/form-field.stories.ts** Add examples of `bitIconButton` as prefix and suffix
- **libs/components/src/form-field/prefix.directive.ts** Automatically set button styling to `undefined` and take over styling. Handle case where prefix is applied to a non-button element.
- **libs/components/src/form-field/suffix.directive.ts** Same as prefix.

## Screenshots

See storybook

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-11-14 14:57 UTC, coroiu commented on libs/components/src/form-field/prefix.directive.ts
> +];
**point-of-interest:** this is the part I'm least satisfied. I think we need to think over how we apply styles, but I think it's out-of-scope in this PR to to fix.

2022-11-15 17:24 UTC, danielleflinn submitted a review, later dismissed

2022-11-16 03:50 UTC, eliykat reviewed
Directives might combine in different ways, but I don't like that one is overriding the behaviour of another in this way; and I think this causes other problems here, like allowing an unstyled button. It all feels a bit awkward.

Would it solve any problems if we think of the styling as belonging to the `ButtonComponent` (as a `ButtonType`), rather than belonging to the `BitSuffixDirective`?

* if the button detects the presence of the `BitSuffixDirective`, it applies the `ButtonType.Suffix` styling, and ignores the `@Input buttonType` value
* if the suffix directive detects that it's attached to a button, it doesn't apply any styling - the button component takes the lead. Otherwise, it applies the `StaticContentClasses`, because it knows that it's the only directive in town 😎  (and it's not a button)

I've said `Button` and `BitSuffixDirective` above, but the same goes for `IconButton` and `BitPrefixDirective`.

Advantages:
* no unstyled buttons
* not using `undefined` as an explicit value (always dangerous in JS imo)
* not calling methods on other directives, each directive just adjusts its own behaviour
* I think it's easier to think about conceptually, but that may be subjective

Disadvantages:
* perhaps more implicit - would probably want to add some comments explaining how the directives interact

Unresolved:
* Styles are still repeated - at the moment they're repeated between `BitSuffix` and `BitPrefix`, with this they're repeated between `Button` and `IconButton`. Not the end of the world, I guess it might be an argument for combining the 2 buttons, which we've mentioned before. But out of scope here.

2022-11-17 06:13 UTC, eliykat commented
> I would like to add what I feel is the main disadvantage of moving the styles: component bloat. I think, ideally, that directives should be like building blocks that we can combine together to get the result that we want, and the advantage is that we get nicely bundled single-responsibility directives.

Nicely put, I agree - this is what I was trying to get at when referring to one directive "overriding" another (or overriding a component). Or to put it another way, I think they need to be neatly composable, and it doesn't feel that way at the moment. (in general, not specifically this PR, although I do think this is the basic issue we're coming up against)

> Moving the styles to the components would mean that their modules would contain code that might never actually be used unless you're in a context that uses forms. It's like 10 rows of code though so I might be exaggerating a bit here 😄, though I do think it will make the code slightly harder to read. Will the button need to contain styles for every type of usage that we're eventually going to add?

According to our current approach - yes! The button component contains styling for every use case, even if those aren't actually used (e.g. you might never use a danger button, but it's all part of the package). Including styling for use in forms doesn't seem any different to me.

> This is an interesting point and it's one of the core concepts I had to change perspective on to arrive at the solution that I did. I think this boils down to "what is a component?". Does it have to have a style?

My expectation is that the CL provides preconfigured options so that you can only use the styling provided. Being able to remove styling from a component went against this expectation for me. (e.g. this lets a developer drop out of the CL styling and apply their own: `<bit-button [type]="undefined" class="my-nonstandard-classes">`).

> Couldn't we instead just combine directives and do something like the following? (This is very much raw thoughts so it's an honest question! Does it give you any inspirations?)
> [examples]

This could work! Let's try out some options when we catch up.

2022-11-17 09:52 UTC, coroiu commented on libs/components/src/shared/button-like.abstraction.ts
> +  setButtonType: (value: "primary" | "secondary" | "danger" | undefined) => void;
suggestion from @eliykat: don't use undefined
```suggestion
  setButtonType: (value: "primary" | "secondary" | "danger" | "unstyled") => void;
```

2022-11-21 01:20 UTC, eliykat commented on libs/components/src/form-field/form-field.stories.ts
> -        <i aria-hidden="true" class="bwi bwi-lg bwi-eye"></i>
Note that this had `bwi-lg` in the class list, which isn't included in your refactor. The icons are currently too small.

2022-11-21 11:57 UTC, coroiu commented on libs/components/src/shared/button-like.abstraction.ts
> +  setButtonType: (value: "primary" | "secondary" | "danger" | undefined) => void;
Fixed!

2022-11-21 15:36 UTC, danielleflinn requested changes
The focus state is showing up as the same color as the background layer. Can we update this to primary-700 like Figma shows? 
Storybook:
<img width="178" alt="Screen Shot 2022-11-21 at 7 34 18 AM" src="https://user-images.githubusercontent.com/43477473/203095443-d07cda7a-3bf8-46c6-a5e4-4642a1d6fc89.png">
Figma:
<img width="285" alt="Screen Shot 2022-11-21 at 7 35 16 AM" src="https://user-images.githubusercontent.com/43477473/203095490-17b8517c-1590-484e-886e-af281040bc1e.png">

2022-11-22 15:39 UTC, coroiu commented
@danielleflinn I went a bit further and re-did the focus ring because they were just weird and didn't match figma at all. I had to implement some margin "hacks" to get the border to work, but it's been tested on Firefox, Chrome and Safari. Here are some comparisons:

#### Master
![Recording 2022-11-22 at 16 29 47](https://user-images.githubusercontent.com/2285588/203355286-4e2cb878-0e78-4ff9-8014-04522294e27a.gif)

#### This PR
![Recording 2022-11-22 at 16 35 56](https://user-images.githubusercontent.com/2285588/203355915-416206b4-ccf1-449e-aac7-87c60c68e543.gif)

(some of the borders on the GIFs look like they are double size, but they don't actually look like that. If the GIFs are opened full-size the double border goes away :))

2022-11-22 16:37 UTC, danielleflinn approved these changes
Thanks for adjusting the focus styles to match Figma 🎉

2022-11-23 04:41 UTC, eliykat requested changes
Nice work on this one and good discussions 😁 Just a couple of minor queries before merging.

2022-11-23 04:41 UTC, eliykat commented on libs/components/src/button/button.component.spec.ts
> +      Array.from(buttonDebugElement.nativeElement.classList).some((klass: string) =>
At first I thought you might have lapsed into Swedish? Then I realised that you're just avoiding the `class` keyword 😁  as good a solution as any

2022-11-23 04:41 UTC, eliykat commented on libs/components/src/form-field/form-field.stories.ts
> -        <i aria-hidden="true" class="bwi bwi-lg bwi-eye"></i>
Fair enough! I should've compared to Figma ;)

2022-11-23 04:41 UTC, eliykat commented on libs/components/src/shared/button-like.abstraction.ts
> +  setButtonType: (value: "primary" | "secondary" | "danger" | "unstyled") => void;
We shouldn't repeat this type definition in multiple places. I suggest moving the `ButtonTypes` definition from the `BitButtonComponent` to this file, then each of the implementations (`BitButton` and `BitIconButton`) can import it.

2022-11-23 04:41 UTC, eliykat commented on libs/components/src/button/button.component.spec.ts
> +      Array.from(buttonDebugElement.nativeElement.classList).some((klass: string) =>
Nice tests by the way!

2022-11-23 04:41 UTC, eliykat commented on libs/components/src/form-field/suffix.directive.ts
> +      "focus-visible:tw-ml-[-1px]",
This is hectic. What's going on here, are you shrinking the margin to fit in the focus ring?

2022-11-23 08:46 UTC, coroiu commented on libs/components/src/shared/button-like.abstraction.ts
> +  setButtonType: (value: "primary" | "secondary" | "danger" | "unstyled") => void;
They are different, this type is the minimum required alternatives. Icon button implements more of them.

2022-11-23 08:55 UTC, coroiu commented on libs/components/src/form-field/suffix.directive.ts
> +      "focus-visible:tw-ml-[-1px]",
Haha yeah so all of these buttons that are next to each other depend on their neighbors borders, otherwise we would get double borders wherever two buttons meet. However this means that if we want to use the borders to signify focus then parts of the ring will be missing on the side where we depend on the border of our neighbor.

The rules you commented on fixes this by re-adding the border. This results in double border, so then we extend one side to overlap our neighbor to get rid of the extra border. Hope that makes sense!

(Negative margins are a documented and supported use-case 🙂)

2022-11-23 09:33 UTC, coroiu commented
@eliykat Sorry for pushing new commits, this should be the last! I've switched all buttons with icons to use icon button so that they get the correct padding.

2022-11-23 13:51 UTC, coroiu commented on libs/components/src/button/button.component.spec.ts
> +      Array.from(buttonDebugElement.nativeElement.classList).some((klass: string) =>
Credit goes to Oscar I thin :D

2022-11-24 03:35 UTC, eliykat commented on libs/components/src/shared/button-like.abstraction.ts
> +  setButtonType: (value: "primary" | "secondary" | "danger" | "unstyled") => void;
It still seems preferable to reuse it in at least the abstraction and bitButton, and potentially extend it in bitIconButton, to centralise the shared variants. But that's just a preference, so I won't worry about it.

2022-11-24 03:37 UTC, eliykat commented on libs/components/src/form-field/suffix.directive.ts
> +      "focus-visible:tw-ml-[-1px]",
Gotcha, thank you for explaining your CSS trickery 😁

2022-11-24 03:56 UTC, eliykat requested changes
I mean _really_, these buttons should also be using the new password toggle directive... but don't you dare make those changes in this PR 😁

2022-11-24 03:56 UTC, eliykat commented on bitwarden_license/bit-web/src/app/organizations/manage/scim.component.html
>      >
Not sure what happened, here, but you still need to move the icon out of the button and set `bitIconButton="bwi-clone"`

2022-11-24 03:56 UTC, eliykat commented on bitwarden_license/bit-web/src/app/organizations/manage/sso.component.html
> +          bitIconButton="bwi-clone"
This also still has the icon in the button element.

2022-11-24 03:58 UTC, eliykat commented
Also please make sure QA take a quick look at the updated UI where you've updated it to use the CL button. That means this is not a purely CL PR, it needs QA before merge.

2022-11-24 08:27 UTC, coroiu commented
> I mean really, these buttons should also be using the new password toggle directive... but don't you dare make those changes in this PR 😁

haha I've actually spoken to Oscar about it and he wanted me to merge this before he went ahead with his password toggle

2022-11-24 08:29 UTC, coroiu commented on bitwarden_license/bit-web/src/app/organizations/manage/scim.component.html
>      >
I have no idea but good catch, fixed!

2022-11-24 08:29 UTC, coroiu commented on bitwarden_license/bit-web/src/app/organizations/manage/sso.component.html
> +          bitIconButton="bwi-clone"
Fixed as well!

2022-11-27 21:42 UTC, eliykat approved these changes
:shipit:

2022-11-28 13:48 UTC, coroiu commented
@Hinton merged his password toggle after all so I've added support for it here

2022-11-28 14:26 UTC, Hinton submitted a review, later dismissed
The password toggle changes looks good

2022-11-28 15:55 UTC, danielleflinn submitted a review, later dismissed

2022-11-28 16:39 UTC, danielleflinn commented
We should add a label to the Password toggle button for "show" and "hide" so screen readers announce the button's function.

2022-11-29 09:27 UTC, coroiu commented
@Hinton @danielleflinn Merge conflict resolution dismissed your approvals so I thought thet if I needed you to re-review I might as well fix the a11y stuff :)

2022-11-29 09:56 UTC, Hinton reviewed
I feel like there is some overlap with https://github.com/bitwarden/clients/pull/4129/files, and we should keep this PR to just the buttons.

2022-11-29 12:41 UTC, coroiu commented
@Hinton I can remove the last two commits but just like I mentioned in your PR we're still going to have significant overlap in both source code but also QA testing effort

2022-11-29 13:13 UTC, coroiu commented
@Hinton I've removed the out-of-scope updated, but please be aware of considerable remaining overlap

2022-11-29 16:40 UTC, danielleflinn submitted a review, later dismissed

2022-11-29 18:47 UTC, Hinton commented
@coroiu do you want me to merge my changes into this PR and we can have QA test all of it at the same time?

2022-11-30 22:48 UTC, eliykat commented
My suggestion is to just limit this PR to the component library changes only. In general I don't think we should mix new component library features + prod code. Then we can merge this PR without waiting QA, and combine both your updates to prod code in a single separate PR.

Packing more updates into a single PR just increases time-to-merge.

2022-12-01 08:18 UTC, coroiu commented
> My suggestion is to just limit this PR to the component library changes only. [...] Then we can merge this PR without waiting for QA, and combine both your updates to prod code in a single separate PR.

I agree but in this case we're dealing with updates to already existing components. Doesn't that mean that no matter how we proceed QA needs to test that the forms continue to work as expected? Might as well update the forms too look correct?

2022-12-02 00:38 UTC, eliykat commented
Yeah that's true, I suppose this was just a change that happened to cut across a few existing components. I don't really mind how we break it up then, sounds like you and @Hinton have already figured out the overlap between your PRs, so I'll just re-review this one.

2022-12-02 01:39 UTC, eliykat requested changes
Looks good except for a DI error below. Also, please avoid force pushing, it drops all commit history and makes it extremely hard to review additional changes only.

2022-12-02 01:39 UTC, eliykat commented on libs/components/src/form-field/password-input-toggle.stories.ts
> -import { ButtonModule } from "../button";
I'm getting an error on this story: 

`ERROR NullInjectorError: R3InjectorError(StorybookModule)[I18nService -> I18nService -> I18nService]:`

2022-12-05 10:04 UTC, coroiu commented on libs/components/src/form-field/password-input-toggle.stories.ts
> -import { ButtonModule } from "../button";
Good catch, fixed!

2022-12-06 04:32 UTC, eliykat approved these changes

2022-12-19 22:13 UTC, eliykat approved these changes

2022-12-19 22:14 UTC, merged