[CL-14] Progress Component
bitwarden/clients pull request #4060
Opened 2022-11-14 22:52 UTC by rr-bw

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-11-15 11:57 UTC, Hinton reviewed
I don't think we want to mix password strength logic with the progress component. That would be a different component utilizing the progress component.

2022-11-21 16:37 UTC, rr-bw commented on libs/components/src/progress/progress.stories.ts
> +      url: "https://www.figma.com/file/Zt3YSeb6E6lebAffrNLa0h/Tailwind-Component-Library?node-id=1717%3A15868",
Can't seem to get this to go the correct location within the Figma file. It keeps redirecting.

2022-11-21 16:42 UTC, Hinton commented on libs/components/src/progress/progress.stories.ts
> +      url: "https://www.figma.com/file/Zt3YSeb6E6lebAffrNLa0h/Tailwind-Component-Library?node-id=1717%3A15868",
Try `https://www.figma.com/file/Zt3YSeb6E6lebAffrNLa0h/Tailwind-Component-Library?node-id=1881%3A18185&t=AM0acaIJ00BUhZKz-4`

2022-11-21 16:44 UTC, Hinton commented on libs/components/src/progress/progress.component.ts
> +  @Input() type: ProgressTypes = "progress";
I wonder if we should just have an optional text which can be used to show a custom text instead of having a `strength`  option?

2022-11-21 16:47 UTC, Hinton commented on libs/components/src/progress/progress.component.html
> +  }}"
We should either move all classes to typescript or use `ngClass` for size.

2022-11-21 16:47 UTC, Hinton commented on libs/components/src/progress/progress.component.html
> +    }}"
Same here.

2022-11-21 16:47 UTC, Hinton commented on libs/components/src/progress/progress.component.html
> +    }}</ng-container>
```suggestion
    <ng-container *ngIf="showText && size !== 'small' && barWidth > 3">
      {{ textContent }}
    </ng-container>
```

2022-11-21 16:47 UTC, Hinton commented on libs/components/src/progress/progress.component.html
> +    <ng-container *ngIf="showText && size !== 'small' && barWidth > 3">{{
We could extract the if logic into a helper in the component.

2022-11-25 13:02 UTC, Hinton commented on libs/components/src/progress/progress.component.ts
> +   * Only display text if size is not small, or if barWidth is above 3%,
Comments that describe the behavior of code has a habit of ending out of sync with the actual behavior. I tend to prefer to focus on the why instead of how.

I.e.
`Hide the text if it can't fit in the inner bar`

2022-11-25 13:02 UTC, Hinton commented on libs/components/src/progress/progress.component.ts
> +   */
```suggestion
```

2022-11-27 07:11 UTC, rr-bw commented on libs/components/src/progress/progress.component.ts
> +  @Input() type: ProgressTypes = "progress";
I'm not sure I've understood you correctly on this one. I removed the strength option along with colors, and added a custom text field (see latest commit). Was I supposed to keep the colors? Let me know if I've misunderstood something.

2022-11-28 09:11 UTC, Hinton commented on libs/components/src/progress/index.ts
> +export * from "./progress.component";
@rr-bw we definitely do want the barrel file, it just doesn't have to expose the `progress.component` line. We shouldn't need direct access to the `ProgressComponent` class.

2022-11-28 09:33 UTC, Hinton commented on libs/components/src/progress/progress.component.ts
> +  @Input() text: string;
Please mark this as optional (for when we turn on strict mode).

```suggestion
  @Input() text?: string;
```

2022-12-06 23:22 UTC, rr-bw commented on libs/components/src/progress/progress.component.html
> +      <div class="tw-pr-1">{{ textContent }}</div>
@Hinton I've reworked the show/hide text functionality to make it more dynamic based on the width of the text, rather than a fixed percent.

2022-12-08 13:58 UTC, Hinton approved these changes
LGTM, thanks @rr-bw. We should get @bitwarden/dept-design to review this first before merging.

2022-12-08 15:25 UTC, danielleflinn requested changes
Let's add a configuration point for background color.

2022-12-08 21:34 UTC, rr-bw commented
> 

@danielleflinn No problem. Option added.

2022-12-08 21:35 UTC, rr-bw commented
> Let's add a configuration point for background color.

@danielleflinn No problem, I've added the option.

2022-12-09 00:15 UTC, danielleflinn approved these changes

2022-12-09 09:16 UTC, Hinton approved these changes

2023-01-10 18:23 UTC, closed without merging