Ps 1854 split split services between backgrond and visualizations
bitwarden/clients pull request #4075
Opened 2022-11-17 00:38 UTC by MGibson1

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

This PR solves our regression for Firefox `DeadObjects`. What's happening is that our Services live perpetually in a background page, but subscriptions occur on the popup/popout/sidebar time scale. If a user closes any of those, the Angular life cycle `ngOnDestroy` does not fire, which leaves dead objects watching our Services' Observables -- no good.

This PR uses tech we prepared for Manifest V3, which allows for synchronization of rxjs Subjects through messages and a shared memory buffer. In the case of MV3, this is chrome.storage.session. For MV2, we can just reuse the background page's memory storage.

A bunch of work was done to ensure good Account serialization for Browser state since the account observable is now a synced object.

Future improvements to this would to to avoid utilizing `fromJSON` methods for accounts that are not serialized. Detection will be a problem, but the object's prototype should be a reliable indication of whether or not hydrating through a deserializer is necessary. This is relevant because `StateService`'s State is being constantly run through the deserializer despite the fact that it's safely stored without worry about serialization consequences in a memory map.

## Code changes

TODO

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

# Draft Reason

I want a chance to take another look at this PR before really submitting, but I want to get it out there for people to look over.

2022-11-17 20:29 UTC, MGibson1 commented
Note: we may add a `BrowserOrganizationService` to this as well. Perhaps more services to come (can be separate PRs)

2022-11-22 13:11 UTC, djsmith85 requested changes

2022-11-22 13:11 UTC, djsmith85 commented on apps/browser/src/services/browser-policy.service.ts
> +  constructor(stateService: BrowserStateService, organizationService: OrganizationService) {
Do we need the constructor here? The other `browser-xxx.service`'s don't have an overload.

2022-11-22 13:11 UTC, djsmith85 commented on libs/common/src/models/domain/organization.ts
> +  static fromJSON(json: Jsonify<Organization>) {
Missing an early return in case the json is null

```suggestion
  static fromJSON(json: Jsonify<Organization>) {
  if (json == null) {
      return null;
    }
```

2022-11-22 13:11 UTC, djsmith85 commented on apps/browser/src/popup/services/services.module.ts
> +      deps: [StateService],
Should we be depending on an instance of StateService or on an abstraction like on [Line 210](https://github.com/bitwarden/clients/pull/4075/files#diff-210fa6ef76ade2d9a5dc1a77eefb240c2c0f71e951d00ac6fcdc38e83fe328f8R210)?

Same question for SettingService.

2022-11-23 14:11 UTC, djsmith85 approved these changes

2022-11-23 14:20 UTC, djsmith85 approved these changes

2022-11-23 22:26 UTC, merged