[PS-1879] Fix Key Connector Migration Flow
bitwarden/clients pull request #4080
Opened 2022-11-17 20:26 UTC by justindbaur

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

This partially reverts the usage of `SyncNotifierService` that was added in #3462. This fixes key connector users being either not forced to convert to key connector at the right time and not being able to leave an organization that has SSO. 

## Code changes

- **libs/common/src/services/sync/sync.service.ts:** Comment out references to `SyncNotifierService` and remove the requirement to inject it. Instead replace it with OrganizationService so that it can save organization state in the order it did before. I left in the next calls but commented them out because ideally pretty soon in the future we figure out a way to get them to work. 
- **apps/web/webpack.config.js:** Added a reference to the default url we use for key connector so that it can work locally.
- **libs/common/src/services/organization/organization.service.ts:** Added a replace method that handles saving to state and updating observables while also being publicly available. I also left the sync subscription but commented out because it will ideally be added back very soon. Also added a tracking ticket in the comment [Ticket](https://bitwarden.atlassian.net/browse/TDL-208)

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-11-17 20:54 UTC, MGibson1 reviewed
I'm not necessarily sold on the value of keeping the code around -- it's still locked in git history after all.

My 2 cents is to remove and reference the commit hash that removes them (the one this PR will get when squashed) in the ticket you put in code

2022-11-17 20:54 UTC, MGibson1 commented on apps/web/webpack.config.js
> +                  http://localhost:5000
what's this?

2022-11-17 20:56 UTC, justindbaur commented on apps/web/webpack.config.js
> +                  http://localhost:5000
Default URL for local dev key connector. I couldn't save the key connector config or convert to key-connector unless this was in there.

2022-11-17 21:26 UTC, MGibson1 commented on apps/web/webpack.config.js
> +                  http://localhost:5000
thanks sounds good

2022-11-17 21:29 UTC, MGibson1 requested changes
Sorry, missed in item on previous review

2022-11-17 21:29 UTC, MGibson1 commented on libs/common/src/abstractions/organization/organization.service.abstraction.ts
> +  replace: (organizations: { [id: string]: OrganizationData }) => Promise<void>;
This method should be part of an internal implementation. See `FolderService` abstract file for expectations there. -- Sorry I didn't notice this before.

2022-11-17 21:29 UTC, MGibson1 commented on libs/common/src/services/organization/organization.service.ts
>  export class OrganizationService implements OrganizationServiceAbstraction {
Should implement the Internal version (which extends `OrganizationServiceAbstraction`)

2022-11-17 21:29 UTC, MGibson1 commented on libs/common/src/services/sync/sync.service.ts
> +    private organizationService: OrganizationService,
Should inject the `InternalOrganizationService` abstraction.

2022-11-18 14:50 UTC, MGibson1 approved these changes

2022-11-18 21:38 UTC, merged