[PS 1504]Windows CLI - JSON Exports Missing Folders
bitwarden/clients pull request #4113
Opened 2022-11-23 21:29 UTC by cyprain-okeke

## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
Fixing the Bug that is related to the "folders" array being empty sometimes when you export your vault

## Code changes

- **clients/libs/common/src/services/export.service.ts:** Replace the firstValueFrom the folderViews$ Observable with getAllDecryptedFromState

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-11-23 22:04 UTC, djsmith85 requested changes
Please also address the other case where folders are retrieved for an export (`getEncryptedExport`).

The tests for export.service are also failing. They are mocking the observables which are not used anymore.

2022-11-30 15:34 UTC, MGibson1 requested changes

2022-11-30 15:34 UTC, MGibson1 commented on libs/common/src/services/folder/folder.service.ts
> +  async getAll(): Promise<Folder[]> {
Please rename to `getAllFromState` to conform to the existing naming convention informing of direct state calls

2022-12-01 12:49 UTC, djsmith85 approved these changes

2022-12-05 20:43 UTC, MGibson1 approved these changes

2022-12-14 14:44 UTC, merged