Make autofill doc-scanner traverse into ShadowRoot
bitwarden/clients pull request #4119
Opened 2022-11-25 15:30 UTC by RafaelKr

This PR is another take on fixing autofill inside ShadowRoot. Thanks to @chadm-sq there was a previous attempt in #2283 but this just had a recursive usage of `querySelectAll`. The problem with that implementation is that `querySelector` and `querySelectorAll` methods don't traverse into elements with closed ShadowRoot. Please read my comment in that PR for more information https://github.com/bitwarden/clients/pull/2283#issuecomment-1325452953

To also support closed ShadowRoots we need a `TreeWalker` in combination with `openOrClosedShadowRoot`. Note that `openOrClosedShadowRoot` is only available to WebExtensions. This PR is my take on it.

This change is fully backward compatible. If `openOrClosedShadowRoot` is not available it will always return undefined and we will never traverse into ShadowRoots just as the behavior was before this change.

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
Autofill finds relevant elements within open and closed ShadowRoots.

## Code changes

**apps/browser/src/content/autofill.js:**
- Query elements by using a TreeWalker instead of document.querySelector[All]. The reason for this is that querySelectorAll doesn't traverse into elements with ShadowRoot.
- Recursively traverse into elements with openOrClosedShadowRoot inside TreeWalker loop.
- Use new query logic everywhere inside `autofill.js`. This also means we need to use filter functions to find elements with specific nodeNames and/or attributes instead of CSS selector strings.
- Add two new `instanceof Element` checks to prevent `Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'." errors`.

This change to `openOrClosedShadowRoot` is fully backward compatible. If `openOrClosedShadowRoot` is not available it will always return undefined and we will never traverse into ShadowRoots just as the behavior was before this change.
Also all other changes should be fully backward compatible.

## Testing requirements
- Normal log-ins still auto-fill.
- Pages with shadow roots now auto-fill. E.g. [login.clear.com.br](https://login.clear.com.br/)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
**I did NOT add any unit tests yet. I leave this to the Bitwarden team.**

- ~~If this change requires a **documentation update** - notify the documentation team~~
- ~~If this change has particular **deployment requirements** - notify the DevOps team~~

2022-11-28 05:32 UTC, eliykat reviewed
Hey @RafaelKr, thanks for looking into this further!

I've reviewed the main shadowroot/traversal logic and added some comments below.

I also created a codepen for testing, which you can toggle between `open`/`closed` or no shadowroot at all (`none`). See here: https://codepen.io/eliykat/pen/ZERRZqv. Your PR worked for me (once I made the adjustments in my comments below to get it to compile).

My main question is about this [not-very-fun warning from MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/openOrClosedShadowRoot):

> Non-standard: This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.

Are there any standard/less experimental ways of traversing a closed shadowroot, that you know of? (I'll also raise this with the team for discussion.)

2022-11-28 05:32 UTC, eliykat commented on apps/browser/src/content/autofill.js
> +      // Firefox 63+
What about other browsers that don't support `openOrClosedShadowRoot` at all? (e.g. Safari)

We probably want a noop version or leave it null and check for null.

2022-11-28 05:32 UTC, eliykat commented on apps/browser/src/content/autofill.js
>                    0 == confirmResult)) ? true : false;
This failed to compile for me. Here's how I fixed it, but please double check:

```suggestion
        return savedURLs.some(url =>
          url.indexOf('https://') === 0) &&
          'http:' === document.location.protocol &&
          0 < passwordInputs.length &&
          (confirmResult = confirm('Warning: This is an unsecured HTTP page, and any information you submit can potentially be seen and changed by others. This Login was originally saved on a secure (HTTPS) page.\n\nDo you still wish to fill this login?'),
            0 == confirmResult) ? true : false;
```

2022-11-28 05:32 UTC, eliykat commented on apps/browser/src/content/autofill.js
> +                  el.attributes.type.toLowerCase() === 'password';
`el.attributes.type` is an object, not a string:

```js
typeof document.getElementById('password').attributes.type;  // 'object'
```

MDN says that `attributes` is a `NamedNodeMap` object, which I'm not really familiar with ([source](https://developer.mozilla.org/en-US/docs/Web/API/Element/attributes)). I would just use `getAttribute`:

```js
            const nodeType = el.getAttribute('type');
            return el.nodeName === 'INPUT' &&
                typeof nodeType === 'string' &&
                nodeType.toLowerCase() === 'password';
```

2022-11-28 05:32 UTC, eliykat commented on apps/browser/src/content/autofill.js
> +      els = els || [];
Do we need the `els` parameter? I can't see that it's used anywhere, and the existing function doesn't take it. (I admit I've only eyeballed it though.) In general I'd prefer to return new objects, not mutate existing ones.

2022-11-28 07:29 UTC, RafaelKr commented on apps/browser/src/content/autofill.js
>                    0 == confirmResult)) ? true : false;
Interesting, for me it did compile, though I didn't actually test this change and also wondered how it was written like this in the first place. I'll just take your suggested changes.

2022-11-28 07:35 UTC, RafaelKr commented on apps/browser/src/content/autofill.js
> +      // Firefox 63+
Browsers which don't support it would just behave as they did before this change, they won't traverse into ShadowRoots. But you brought the idea to my mind, that we should be able to just use `return element.openOrClosedShadowRoot || element.shadowRoot;`, so it works at least for open ShadowRoots in browsers which don't support it.

2022-11-28 07:39 UTC, RafaelKr commented on apps/browser/src/content/autofill.js
> +      els = els || [];
Yes we need it for the recursive call on line 96. The TreeWalker doesn't traverse into ShadowRoots by itself. ShadowRoot is like an own new `document`. And we need to run another TreeWalker on that document.

2022-11-28 08:01 UTC, RafaelKr commented on apps/browser/src/content/autofill.js
> +                  el.attributes.type.toLowerCase() === 'password';
Good catch! I adjusted it in all my changes.

2022-11-28 08:11 UTC, RafaelKr commented
Hey @eliykat, thanks for reviewing this so quickly!

> My main question is about this [not-very-fun warning from MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/openOrClosedShadowRoot):
> 
> > Non-standard: This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.
> 
> Are there any standard/less experimental ways of traversing a closed shadowroot, that you know of? (I'll also raise this with the team for discussion.)

Thanks for pointing this out, this made me think about it again and I noticed we can just use `return element.openOrClosedShadowRoot || element.shadowRoot;`, so we fallback to `element.shadowRoot` for every browser which doesn't support `element.openOrClosedShadowRoot`.

So we now have the two ways `chrome.dom.openOrClosedShadowRoot` (Chrome) and `element.openOrClosedShadowRoot` (Firefox) and every other browser uses `element.shadowRoot` which just finds open ShadowRoots, not closed ones.

2022-11-28 08:37 UTC, RafaelKr commented
@eliykat I have no Safari, could you please test if it works for open ShadowRoot there?

2022-11-28 21:53 UTC, chadm-sq commented on apps/browser/src/content/autofill.js
>    MODIFICATIONS FROM ORIGINAL
I think this reverence for the original is a boat-anchor tied to our necks.

2022-11-28 22:11 UTC, chadm-sq approved these changes
Good enough! Thank you. I have one nit.

2022-11-28 22:11 UTC, chadm-sq commented on apps/browser/src/content/autofill.js
> +   * It has the advantage over querySelectorAll that it traverses into ShadowRoot.
```suggestion
   * Returns elements like Document.querySelectorAll does, but traverses the document and shadow 
   * roots, yielding a visited node only if it passes the predicate in filterCallback.
```

2022-11-28 22:11 UTC, chadm-sq commented on apps/browser/src/content/autofill.js
> +            els = queryDocAll(doc, nodeShadowRoot, filterCallback, els);
Doesn't matter much, but I am not a fan of reassigning the value that we also mutate in the called recursion. Can we not just have queryDocAll return its own array, and when returning from recursing, extend ours with the results?

```suggestion
            els.push(...queryDocAll(doc, nodeShadowRoot, filterCallback));
```

2022-11-29 13:14 UTC, RafaelKr commented on apps/browser/src/content/autofill.js
>    MODIFICATIONS FROM ORIGINAL
IMO the whole autofill should be rebuild to also share logic with form submission handling.
Probably best would be to rebuild it also with TypeScript from the ground up.

2022-11-29 13:16 UTC, RafaelKr commented on apps/browser/src/content/autofill.js
> +          // renamed queryDoc to queryDocAll and moved to top
That's right, but previously `queryDoc` used querySelectorAll which is now reflected in `queryDocAll`.

2022-11-29 13:27 UTC, RafaelKr commented on apps/browser/src/content/autofill.js
> +          (confirmResult = confirm('Warning: This is an unsecured HTTP page, and any information you submit can potentially be seen and changed by others. This Login was originally saved on a secure
Ah yeah, damn 😆
But this shouldn't be the scope of this PR, we should fix it afterwards. I'm also not happy about this ugly construct overall, but it's not my code, just had to update it 😅

2022-11-29 13:28 UTC, RafaelKr commented
Thanks for your review @chadm-sq! I addressed all of your feedback.

2022-11-30 02:53 UTC, eliykat commented on apps/browser/src/content/autofill.js
>                    0 == confirmResult)) ? true : false;
Yes, and removed an extra `)` at the end. These lines are almost impossible to read.

2022-11-30 03:00 UTC, eliykat commented on apps/browser/src/content/autofill.js
>    MODIFICATIONS FROM ORIGINAL
I suspect it's due to the copyright notice at the top of the document - we need to separate out the original code (governed by the copyright notice) and our code (governed by LICENSE.txt). I'm not 100% sure though.

2022-11-30 03:01 UTC, eliykat commented on apps/browser/src/content/autofill.js
> +          (confirmResult = confirm('Warning: This is an unsecured HTTP page, and any information you submit can potentially be seen and changed by others. This Login was originally saved on a secure
I agree, I wouldn't worry about it for this PR.

2022-11-30 05:36 UTC, eliykat commented on apps/browser/src/content/autofill.js
> +            els = queryDocAll(doc, nodeShadowRoot, filterCallback, els);
I also prefer to avoid mutation here. I think that `concat`ing the arrays might be faster than the spread operator (given that it's purpose built for combining 2 arrays, which is all we're doing here) - but I don't have any data to back that up. Either is probably fine.

I take your point about performance, but I'm not too concerned about it here. We can benchmark later if it's an issue.

2022-11-30 06:13 UTC, eliykat commented on apps/browser/src/content/autofill.js
> +      // Firefox 63+
Good idea!

2022-11-30 06:23 UTC, eliykat commented
I'll test this on Safari (as requested), plus a few other major browsers. I've also asked for a second set of eyes from the team, as `autofill.js` is fairly arcane and not covered by automated testing.

2022-11-30 06:57 UTC, RafaelKr commented
Thanks @eliykat! I just did 2 new changes:

1. I unnested an if-statement by using `continue` in [bitwarden/clients@`6f80de7` (#4119)](https://github.com/bitwarden/clients/pull/4119/commits/6f80de7d89ffc4d03359e31f1ed5bd26a005401c)
2. I missed one occurence where I didn't handle attribute values correctly. I just fixed this and pushed this as a fixup to ea1c84b https://github.com/bitwarden/clients/blob/ea1c84b623881dd775c9c9b41bc27b05a20a343b/apps/browser/src/content/autofill.js#L694-L695

2022-11-30 08:13 UTC, RafaelKr commented on apps/browser/src/content/autofill.js
> +            els = queryDocAll(doc, nodeShadowRoot, filterCallback, els);
I built a little benchmark over here: https://jsbench.me/fhlb3cqqj2/1

My results in Firefox 107 on Linux Mint `Mozilla/5.0 (X11; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0` are:
```
Array.concat
3846427.63 ops/s ± 0.53%
90.71 % slower

Array.push with spread operator
10707846.38 ops/s ± 0.23%
74.14 % slower

Array.push directly onto elements
41413583.66 ops/s ± 1.18%
Fastest
```

So for a DOM with a lot of elements and many ShadowRoots, as can happen when using https://ionicframework.com/ as an example, the direct `Array.push` has a significant performance- and probably also memory benefit.

A reason why I really care about performance is that I have to use the Dashlane Password Manager for work and on pages with a lot of inputs it often happens that the page gets very slow. After some seconds Firefox shows a toolbar at the top of the page saying something like "Dashlane is slowing down your browser, would you like to stop it?"

Maybe we can add a comment explaining why I implemented it like that instead?

2022-11-30 17:41 UTC, chadm-sq commented on apps/browser/src/content/autofill.js
> +  }
```suggestion
  function queryDocAll(doc, rootEl, filterCallback) {
      accumulation = [];
      accumulatingQueryDocAll(doc, rootEl, filterCallback, accumulation);  // mutates accumulation
      return accumulation;
  }
  
  function accumulatingQueryDocAll(doc, rootEl, filterCallback, accumulation) {
      if (typeof filterCallback !== 'function') {
          filterCallback = function () { /* noop */ };
      }

      var treeWalker = doc.createTreeWalker(rootEl, NodeFilter.SHOW_ELEMENT);
      var node;

      while (node = treeWalker.nextNode()) {
        if (filterCallback(node)) {
            accumulation.push(node);
        }

        // If node contains a ShadowRoot we want to step into it and also traverse all child nodes inside.
        var nodeShadowRoot = getShadowRoot(node);

        if (!nodeShadowRoot) {
          continue;
        }

        // recursively traverse into ShadowRoot
        accumulatingQueryDocAll(doc, nodeShadowRoot, filterCallback, accumulation);
    }
  }
```

2022-11-30 18:20 UTC, RafaelKr commented on apps/browser/src/content/autofill.js
> +  }
Thank you very much @chadm-sq! I like that. I commited it with an descriptive message. To be more explicit I renamed `accumulation` to `accumulatedNodes` and also added the `var` keyword in an own commit.

2022-11-30 18:22 UTC, RafaelKr commented on apps/browser/src/content/autofill.js
> +            els = queryDocAll(doc, nodeShadowRoot, filterCallback, els);
Resolved by af893d3 / 3dc542b
Thanks @chadm-sq!

2022-12-01 01:42 UTC, eliykat commented on apps/browser/src/content/autofill.js
> +            els = queryDocAll(doc, nodeShadowRoot, filterCallback, els);
Good point! Kudos for taking the time to benchmark.

2022-12-01 07:57 UTC, RafaelKr commented
I just tweaked the commit messages for documentation purposes a little bit.
From my side this is now ready to merge.

2022-12-01 17:51 UTC, RafaelKr commented on apps/browser/src/content/autofill.js
> +            els = queryDocAll(doc, nodeShadowRoot, filterCallback, els);
BTW this is the message I was talking about. Happened on a page with 1110 input fields (Shopware 6 detailed role privileges page).

![image](https://user-images.githubusercontent.com/14234815/205124557-36380222-7dd6-4754-bca1-403183526945.png)

2022-12-01 19:51 UTC, chadm-sq commented on apps/browser/src/content/autofill.js
> +            els = queryDocAll(doc, nodeShadowRoot, filterCallback, els);
I'll be keen to know if bitwarden gives a similar warning, @RafaelKr .

Ooo, optimization for the future? We don't need to scan the entire document. I bet the displayed and on-screen (p1 < .top < p2) elements only matter. If we can't see them, we don't need to try to fill them.

2022-12-01 20:03 UTC, RafaelKr commented on apps/browser/src/content/autofill.js
> +            els = queryDocAll(doc, nodeShadowRoot, filterCallback, els);
Nope, never seen this one for Bitwarden. Personally I used LastPass before Bitwarden, also I've never seen it for that.
I'm not sure what Dashlane is doing to produce this warning, I don't know how this would perform on a low-end device.

I also don't like Dashlane at all, many Features are implemented in a bad way or not at all. Maybe we'll switch to Bitwarden for work when we have some time to do so ;)

So you mean we should also check for hidden elements and don't traverse them? Maybe a good idea, but only after implementing the mutation observer. Because many pages can toggle between login and register forms and maybe for Single Page Applications Bitwarden wouldn't recognize that change.

2022-12-12 00:26 UTC, eliykat requested changes
A few suggestions and questions, thanks.

By the way, I raised it internally and there's no strict requirement to continue tracking modifications via comments. We'll keep the pattern in this PR for now, but I'll aim to remove them soon so that we can make changes a little easier.

PS. please avoid force pushes from this point on, so that we keep the commit history intact :)

2022-12-12 00:26 UTC, eliykat commented on apps/browser/src/content/autofill.js
> +              elStyle = el.getComputedStyle && theEl instanceof Element ? el.getComputedStyle(theEl, null) : theEl.style;
I assume that `instanceOf Element` is here because `querySelector` only returns `Elements`, but the new query methods return a larger set which includes non-`Elements`. Is that right? In that case, it seems safer and more compatible with existing code expectations to filter out non-`Element`s in the query methods, so that we don't have to check for this on a per-caller basis.

2022-12-12 00:26 UTC, eliykat commented on apps/browser/src/content/autofill.js
> +            0 == confirmResult) ? true : false;
Looking at this again, I'd appreciate it if you could unpick this code a bit. The old code only called `querySelectorAll` if there was a mismatch in protocol, now we're calling it every time, even though it won't be needed in 99% of cases. And the `savedURLs.some` statement is still terrible to review 😅 I'd appreciate it if you could just break it down into a series of regular `if` statements (or whatever makes sense), and only get the passwordInputs if actually required.

2022-12-12 00:26 UTC, eliykat commented on apps/browser/src/content/autofill.js
> -                  'span[data-bwautofill]');
Can we just use `Element.matches` instead of rewriting all this logic?

In general I think it's good to pass functions rather than interpolated CSS selector strings. But here the selector is pretty concise and doesn't really need to be a function.

2022-12-12 00:26 UTC, eliykat commented on apps/browser/src/content/autofill.js
> +              return el.nodeName === 'FORM' &&
typo?

```suggestion
              return el.nodeName === 'INPUT' &&
```

2022-12-12 01:36 UTC, eliykat commented
I've given this a quick test on Safari (using my Codepen, plus quick regression test on Facebook, Google and Amazon login pages). As expected, it fills open ShadowDOMs but not closed ShadowDOMs (given that Safari does not have those experimental APIs), and no regressions on those sites. QA will give it a more rigorous going over, but for now that looks good to me.

I also did a rough fairly non-scientific benchmark: I placed `console.time`/`timeEnd` statements around the calls to `collect` and `fill` in the message listener at the bottom of `autofill.js`. I took the average and the median times for all calls to each function for each of the above sites. Variance between `master` and this branch was +/- 2.2ms at the most, and I expect there would be a large variance between repeated tests anyway. As I said, non-scientific. But I wanted some idea of how these changes affected the overall speed of this, and I think we're good here.

2022-12-14 12:23 UTC, RafaelKr commented on apps/browser/src/content/autofill.js
> +      }
You're right, I thought to make `filterCallback` optional, but it should never be optional. So probably we should just remove this check?

2022-12-14 12:25 UTC, RafaelKr commented on apps/browser/src/content/autofill.js
> -          var theForms = Array.prototype.slice.call(queryDoc(theDoc, 'form')).map(function (formEl, elIndex) {
I asked myself the same question. And yes, maybe it was added by the original bundler, I see no other reason for it.

2022-12-14 12:31 UTC, RafaelKr commented on apps/browser/src/content/autofill.js
> +                  typeof node.attributes['data-onepassword-title'].value === 'string';
Ah yeah, we can just remove the typeof check at all.

2022-12-14 12:33 UTC, RafaelKr commented on apps/browser/src/content/autofill.js
> +      }
I just removed the whole if statement in both queryDoc functions.

2022-12-14 13:15 UTC, RafaelKr commented on apps/browser/src/content/autofill.js
> +              elStyle = el.getComputedStyle && theEl instanceof Element ? el.getComputedStyle(theEl, null) : theEl.style;
Your assumption is correct. If it's not there we will get these errors:
`TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.`

For the `input` inside the shadow root on https://login.clear.com.br/ the line `el = (el = el.ownerDocument) ? el.defaultView : {};` assigns Window to `el`.
`el.ownerDocument` is the `document` and `defaultView` of that is the `Window`.

But I think we can remove the `instanceof Element` inside `selectAllFromDoc`. I did this right now.

2022-12-14 13:20 UTC, RafaelKr commented on apps/browser/src/content/autofill.js
> -                  'span[data-bwautofill]');
We could use `selectAllFromDoc` with the selectors instead of functions everywhere. But we probably should check the performance then because it will run `.matches` on EVERY node and I don't know if this is less performant than the check we're doing now.
Should I maybe push this in a different branch and you do your perfromance checks again?

2022-12-14 13:23 UTC, RafaelKr commented on apps/browser/src/content/autofill.js
> +              return el.nodeName === 'FORM' &&
Of course! Good catch. Fixed.

2022-12-14 13:46 UTC, RafaelKr commented
Thanks for your time, benchmarks and feedback, I appreciate it.

I addressed most of your feedback now, some feedback with some questions.

I also untangled the conditions for the `urlNotSecure` function. One thing I did is checking for `document.location.protocol === 'https:'` instead of `document.location.protocol !== 'http:'`. I'm not 100% sure if this is fine or if we better should keep it the other way.

2022-12-14 13:47 UTC, RafaelKr commented on apps/browser/src/content/autofill.js
> +            0 == confirmResult) ? true : false;
I just did it now. Please see https://github.com/bitwarden/clients/pull/4119#issuecomment-1351386326

> I also untangled the conditions for the urlNotSecure function. One thing I did is checking for document.location.protocol === 'https:' instead of document.location.protocol !== 'http:'. I'm not 100% sure if this is fine or if we better should keep it the other way.

2022-12-14 15:05 UTC, chadm-sq approved these changes

2022-12-14 15:05 UTC, chadm-sq commented on apps/browser/src/content/autofill.js
> +      // END MODIFICATION
You can move this up a few lines.

2022-12-14 15:14 UTC, RafaelKr commented on apps/browser/src/content/autofill.js
> +      // END MODIFICATION
Actually the `isSandboxed` function is a modification from here https://github.com/bitwarden/clients/pull/3860

2022-12-19 04:26 UTC, eliykat commented on apps/browser/src/content/autofill.js
> -                  'span[data-bwautofill]');
That's a fair point. Let's leave it as is.

2022-12-19 04:41 UTC, eliykat commented on apps/browser/src/content/autofill.js
> +            0 == confirmResult) ? true : false;
Thanks for calling that out. I'd prefer to keep the old logic, i.e. `document.location.protocol !== 'http:'` so that it doesn't trip a HTTPS-related warning on other (non-HTTP) protocols. (Seems unlikely but I can imagine it)

Otherwise, this method looks much better!

2022-12-19 04:47 UTC, eliykat commented on apps/browser/src/content/autofill.js
> +              elStyle = el.getComputedStyle && theEl instanceof Element ? el.getComputedStyle(theEl, null) : theEl.style;
I'm fine with having this check if there's a chance it can return a non-`Element` object and break autofill. What I meant to suggest was that we should move the `instanceOf Element` check into the query methods themselves, so that all callers are guaranteed to always receive an `Element` as a result.

2022-12-19 04:53 UTC, eliykat reviewed
Responded to comment threads above ☝️ and resolved merge conflicts (to save myself having to review a merge commit)

CI checks are running here: https://github.com/bitwarden/clients/tree/fix/autofill-shadow-root-ci

2023-01-16 14:22 UTC, djsmith85 requested changes
@RafaelKr Thank you for your contribution ❤️  These changes are really appreciated, and we hope to see some improvements with more sites being able to autofill 💪 

I pair-reviewed your changes end of last week with @eliykat as with autofill it's always a good idea to get a second pair of eyes and to discuss the code-flow and changes.

The changes are looking great and using the Treewalker API was a neat idea.

The call-sites that you changed to use your new methods all check out.

The only thing I'm requesting is a re-vert of the changes to `urlNotSecure`. The rest looks great, and I have manually tested on Windows with Chrome and Firefox.

2023-01-16 14:57 UTC, RafaelKr commented on apps/browser/src/content/autofill.js
>        }
I reverted the changes by merging master and using the `urlNotSecure` from master. Afterwards I replaced `document.querySelectorAll` with `queryDocAll`. Is this as expected?

2023-01-16 15:03 UTC, RafaelKr commented
Hey @djsmith85, thanks for reviewing! ❤️ I just updated the `urlNotSecure` (hopefully the way you expected!). It's now the same as on master, but using `queryDocAll` instead of `document.querySelectorAll`.

I didn't test things again, as I unfortunately currently have less time available. But if you test this on a http page for which you saved https credentials and it shows the confirm dialog I think its finally ready to ship! 😊

2023-01-16 15:20 UTC, RafaelKr commented
I just addressed the CodeScene analysis violations. Now we don't have violations left, only a warning.

2023-01-16 17:16 UTC, RafaelKr commented on apps/browser/src/content/autofill.js
> +              elStyle = el.getComputedStyle && theEl instanceof Element ? el.getComputedStyle(theEl, null) : theEl.style;
I removed the `instanceOf Element` check from the `selectAllFromDoc` function as it's not required there. But in case of functions `isElementVisible` and `canSeeElementToStyle` the reassignment to a non-element happens inside these functions itself. As noted before it happens when `el.defaultView` is assigned when the `input` element is inside a shadow root, so the check is required inside those methods.

2023-01-16 19:32 UTC, djsmith85 commented on apps/browser/src/content/autofill.js
>        }
Yes, thank you, this addresses my comment.

2023-01-16 19:45 UTC, djsmith85 approved these changes
@RafaelKr Thank you for promptly addressing the feedback. Apologies for the long wait on a review.

@eliykat From my side this is good to go. Please add your review and update the CI-branch.

2023-01-19 21:39 UTC, eliykat commented on apps/browser/src/content/autofill.js
> +              elStyle = el.getComputedStyle && theEl instanceof Element ? el.getComputedStyle(theEl, null) : theEl.style;
Gotcha! thanks for the additional explanation.

2023-01-19 21:41 UTC, eliykat commented
CI branch has been updated, I'll get a final review + quick test in on this next week.

2023-01-23 02:12 UTC, eliykat requested changes

2023-01-23 02:12 UTC, eliykat commented on apps/browser/src/content/autofill.js
> +                          return node.nodeName === 'LABEL' && node.attributes.for && node.attributes.for.value === elId;
Sorry for not picking this up earlier, but I just noticed that `Element.attributes.[attributeName].value` will return whatever case is used in the DOM. [CodePen example](https://codepen.io/eliykat/pen/eYjVRRX).  (I thought I'd checked this, but I'd only checked `Element.nodeName`, which behaves differently.) We need to normalize the case for any comparison. You seem to have picked this up in most places, but not everywhere.

Relatedly, this made me look up the recommended method of accessing attributes: it seems to be [Element.hasAttribute](https://developer.mozilla.org/en-US/docs/Web/API/Element/hasAttribute) and [Element.getAttribute](https://developer.mozilla.org/en-US/docs/Web/API/Element/getAttribute). MDN links to [quirksmode.org](https://quirksmode.org/dom/core/#attributes) which discourages the indexed `attributes` property due to cross-browser issues, and existing code uses `getAttribute`.

getAttribute says that it [lowercases automatically](https://developer.mozilla.org/en-US/docs/Web/API/Element/getAttribute#lower_casing), but I haven't found that to be the case in my testing.

So I think the best pattern would be (for example) `node.hasAttribute('for') && node.getAttribute('for').toLowerCase()` - everywhere we want to check an attribute value. It may be worth sticking in a helper function.

2023-01-23 09:27 UTC, RafaelKr commented on apps/browser/src/content/autofill.js
> +          return false;
If I know it correctly the autofill.js is not transpiled. So I didn't use a `Set` thinking about browser support.
What do you think, should we still use it?
https://caniuse.com/mdn-javascript_builtins_set

2023-01-23 09:39 UTC, RafaelKr commented on apps/browser/src/content/autofill.js
> +                          return node.nodeName === 'LABEL' && node.attributes.for && node.attributes.for.value === elId;
Thanks for the heads up, good catch! I will update this soon.

> getAttribute says that it [lowercases automatically](https://developer.mozilla.org/en-US/docs/Web/API/Element/getAttribute#lower_casing), but I haven't found that to be the case in my testing.

Maybe you did understand they lowercase the return value? But it states "`getAttribute()` lower-cases its argument before proceeding". So they're probably talking about the argument you're passing to the function, meaning `node.getAttribute('for')` and `node.getAttribute('FOR')` are the same.  
Altough it's strange that they don't mention this for `hasAttribute`, which does the same. I just checked that quickly in your CodePen, `console.log(el.hasAttribute('TYPE'))` returns `true`.

2023-01-23 11:13 UTC, RafaelKr commented on apps/browser/src/content/autofill.js
> +                          return node.nodeName === 'LABEL' && node.attributes.for && node.attributes.for.value === elId;
I now reworked the attribute handling. Everything I did is included in the commit message.
With my refactoring no helper function was required. I think it's much more readable now.

2023-01-24 02:06 UTC, eliykat commented on apps/browser/src/content/autofill.js
> +          return false;
Good point about it not being transpiled. The answer is it's _probably_ fine, `Set` has been with us for almost a decade. But I'm inclined to play it safe and stick with the same language/feature set as the rest of the file.

2023-01-24 02:07 UTC, eliykat commented on apps/browser/src/content/autofill.js
> +                          return node.nodeName === 'LABEL' && node.attributes.for && node.attributes.for.value === elId;
I agree, much more readable, and I think what you've done makes sense. Thanks!

2023-01-24 02:15 UTC, eliykat commented
Looks great, thanks again @RafaelKr! I'll pass it on to our QA team for testing.

2023-02-06 15:48 UTC, RafaelKr commented
@eliykat GitHub still shows you requested changes. When clicking on the link it shows nothing. Seems to be a bug? Does this matter for your QA team? I could re-request a review.

2023-02-06 21:38 UTC, eliykat approved these changes
Sometimes those can hang around, or maybe I need to give an approving review to dismiss them. Nothing required from you @RafaelKr , thanks.

2023-02-19 22:26 UTC, eliykat approved these changes
This has passed QA and will be in the March release. Thanks all for your work on this tricky bit of code, @RafaelKr , @chadm-sq , and @djsmith85.

2023-02-19 22:43 UTC, merged

2023-02-20 08:55 UTC, RafaelKr commented
Was a pleasure to iterate through this with you guys! Thanks for merging.

2023-04-05 22:01 UTC, trmartin4 commented
Hello @RafaelKr.  I am an Engineering Manager at Bitwarden.  Our team had to revert these changes out of the browser and release `2023.3.1` version due to performance issues that several of our users saw.  These appeared to be isolated to Firefox and Edge and were on sites that had a lot of input fields (e.g. an admin panel maintaining lists of entities), and the slowdown appeared to be in the `TreeWalker` implementation.

I wanted to make you aware, and also see if you would be willing to help work through these issues and hopefully come up with a solution that addresses ShadowRoot without these particular performance issues in an edge case.

2023-04-05 23:19 UTC, RafaelKr commented
> Hello @RafaelKr.  I am an Engineering Manager at Bitwarden.  I first wanted to thank you so much for this contribution.  Unfortunately, our team had to revert these changes out of the browser and release `2023.3.1` version due to performance issues that several of our users saw.  These appeared to be isolated to Firefox and Edge and were on sites that had a lot of input fields (e.g. an admin panel maintaining lists of entities), and the slowdown appeared to be in the `TreeWalker` implementation.
> 
> I wanted to make you aware, and also see if you would be willing to help work through these issues and hopefully come up with a solution that addresses ShadowRoot without these particular performance issues in an edge case.  We don't want to disregard all of the work you have done and want to see a solution that can achieve both.

Hello @trmartin4. Thank you very much for reaching out. First, I'm sorry for the inconvenience I may have caused for some of the Bitwarden users. I already saw the revert today but didn't have time to look further into it.

I'm willing to have a look at this the coming days and see what I can do.

According to many performance tests I checked out before writing the first PoC for this PR `TreeWalker` itself is very performant. Even more performant than `document.querySelectorAll` which was used previously. So I assume it's not `TreeWalker` itself but some other part of the code I changed. I'm confident I'll be able to pinpoint bottlenecks and find a solution for these parts.

Quickly skimming through some related issues I saw you were able to confirm the performance regression internally. Could you maybe provide a link to the specific page(s) where you were able to reproduce the issue?

If I can pinpoint the bottleneck(s) I'll try to write an own reproduction page which can later be used to test for performance regressions.

I'll have a deeper look into this as soon as I find time for it. Probably I can provide a fix by the end of the month, so maybe we can try again with 2023.4 or 2023.5

Best regards

2023-05-30 11:41 UTC, VeloAddict commented
I have Bitwarden Version 2023.4.0 on Chrome Version 113.0.5672.126.
I can't manage to make Bitwarden work with inputs in shadow dom.
Other password manager work.
If I use the copy custom field name I get: "Unable to identify a valid form element. Try inspecting the HTML instead." 


<img width="577" alt="image" src="https://github.com/bitwarden/clients/assets/36549/b5fec4a6-1a33-428b-b97c-0f007279c511">
<img width="582" alt="image" src="https://github.com/bitwarden/clients/assets/36549/53cd70b2-ead3-4187-9749-3992d91f9102">

2023-05-30 11:44 UTC, RafaelKr commented
@VeloAddict this PR was reverted due to a performance regression. Unfortunately I didn't have time to debug and resolve the issue yet.

2023-06-12 19:12 UTC, cagonzalezcs commented
@RafaelKr 

Hello, I'm a Front End Engineer with Bitwarden. Thank you for providing this contribution, even if it had to be reverted due to the experienced performance issues. Todd asked our team to investigate possible bottlenecks with the implementation, and I believe that we have found a path forward that leverages part of your implementation to deeply query all possible ShadowDOM elements.

What we found was that using your TreeWalker implementation for querying all elements relating to found fillable elements was proving to be fairly expensive. (An example of this would be when the implementation attempts to find label text for an element using the method `getLabelTag` at line 287 of the implementation.) 

We found that if we instead handle query logic relating to individual found elements a bit more conservatively, and only use the TreeWalker API to initially query all possible elements found within the DOM/ShadowDOM, performance improves dramatically.

We have a larger scale refactor that is in the works for `autofill.ts` which modernizes and cleans up the implementation. Within this refactor, we will be applying a fix heavily inspired by your work that will address the issues Bitwarden's extension has with autofilling ShadowDOM elements.

I'll make sure to link this ticket to the PR that addresses that problem when it is ready for review.

2023-06-13 08:58 UTC, RafaelKr commented
@cagonzalezcs 

Hello Cesar, thank you very much for your feedback, I really appreciate it. Also I love this moving forward, I had a little sneak peak at your [pm-2130-shadow-dom-experiment](https://github.com/bitwarden/clients/tree/pm-2130-shadow-dom-experiment) branch and it's very good to see this rebuilt from the ground up. The current implementation of course has by far too much queries all walking through the full DOM and running it just initially to collect all relevant elements is a much better solution.

I don't know how much of all the discussion you followed, but I would like to give you a heads up to my comments https://github.com/bitwarden/clients/pull/2066#issuecomment-1326558758 and https://github.com/bitwarden/clients/pull/2066#issuecomment-1327312681. There I already suggested collecting the elements just once, but more importantly I suggested also using it not only for autofill but move the collecting logic into an own service and use it also for the saving/updating logic.

Also I had the idea to experiment with MutationObserver in this service, which could make it possible to really run the full DOM traversal only on initial page load and then only listen to changes from then on.

2023-06-13 19:55 UTC, cagonzalezcs commented
@RafaelKr 

Thanks for providing that context, it'll be helpful as our team continues to work through improving the autofill behavior. I like your idea for implementing some kind of watcher logic using MutationObservers to anticipate changes in the DOM structure. I had some thoughts around that as well, but held off on any deep investigation of how we'd approach implementing and leveraging behavior surrounding that API. 

Right now, the efforts we're working through involve refactoring the existing behavior of the autofill content script in a near parity manner. We're approaching it that way to ensure we introduce as little as risk as possible for breaking the behavior overall, while setting ourselves up to more easily add features and bug fixes down the line. While it is still in progress, that work can be previewed within PR #5453  

We've got a couple of tasks that we're working to complete in order to ensure feature parity of this refactor with the legacy autofill content script, but once this is merged in, the fix for ShadowDOM elements and other improvements are going to follow.

2024-06-04 15:54 UTC, martinmckenna commented
is this still reverted? is there an open ticket about autofill not working with the shadowDOM?

2024-06-04 17:32 UTC, cagonzalezcs commented
This PR is reverted, but was used in re-working the ShadowDOM support with the PR linked above your comment. 

If a specific website isn't working, then likely its a different issue.

2024-06-04 18:52 UTC, martinmckenna commented
hmm yeah my shadow root email field is being auto-filled, but not the password. The input has a `<label>` of "password" and `type="password"` so not sure if I'm missing something else.

The [login.clear.com.br](https://login.clear.com.br/) in OP seems to work though and the only difference I see is the `name="password"` property

2024-06-04 21:50 UTC, cagonzalezcs commented
A bug was introduced where ShadowDOM elements that contain any child nodes are ignored. This has been resolved in a recently merged PR - https://github.com/bitwarden/clients/pull/9063

I'm willing to bet that's the issue you're seeing with the element. 

That work should be released with an upcoming release of the extension.

2024-06-04 22:00 UTC, cagonzalezcs commented
That fix doesn't relate to MV3 specifically, and any updates to the extension moving forward for the moment will be cross-version compatible with MV2 on FF/Safari and MV3 on Chrome. 

That said, the next update should begin rolling out next week if nothing causes a delay.

2024-06-04 22:14 UTC, cagonzalezcs commented
We worked to solidify MV3 in Chrome first due to the hard deadline that Google set for sunsetting MV2. The process for that implementation was approached in a backwards compatible manner for a variety of reasons.

The largest reason for this is due to differences in how Chrome's background service worker and FF/Safari's non-persistent background events page function. 

That said, it is our intent to move forward with support of MV3 on FF/Safari in the near future, though our current focus is stability of MV3 in Chrome.

Regarding [incognito support in Firefox, that has been addressed](https://github.com/bitwarden/clients/pull/8921) thanks in part to the work done for MV3. You should be seeing better functionality when using the extension between an incognito context and the main browsing context in FF (similar to how Chrome handles the behavior).