Sm 73
bitwarden/clients pull request #4144
Opened 2022-11-29 15:43 UTC by cd-bitwarden

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-12-26 16:17 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/secret.service.ts
> +  private async getProjectIds(projects: SecretProjectView[]): Promise<string[]> {
This function isn't necessary, I'm going to change it to how we do this elsewhere

2022-12-26 16:18 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.ts
> +    if (secret != null) {
I don't think we need this check here, load data is only called when we have a secretId to load.

2022-12-29 17:52 UTC, coltonhurst reviewed
Thanks for your work on this! Some small comments.

Also, after testing, I believe when creating a new secret & passing a projectId to the dialog, it does not automatically attach the projectId to the secret like it did before.

To test this, from within a project, create a new secret. The secret when created should automatically be associated with that project. You can see this in `project-secrets.component.ts`, where we pass projectId here:

```
openNewSecretDialog() {
    this.dialogService.open<unknown, SecretOperation>(SecretDialogComponent, {
      data: {
        organizationId: this.organizationId,
        operation: OperationType.Add,
        projectId: this.projectId,
      },
    });
  }
```

2022-12-29 17:52 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.ts
> +  removeProjectAssociation = async (id: string) => {
Just curious - any specific reason why we are declaring the function like this? Instead of something like:

`async removeProjectAssociation(id: string) {`

2022-12-29 17:52 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.ts
> +    // Remove current project list, only one project association allowed.
We might not need this comment?

2022-12-29 17:52 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/secret.service.ts
> +    const projectIds: string[] = [];
I think we can do this function with `map` in one line without a loop? Just a thought if you think changing makes it more simple/clear.

2022-12-29 17:52 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/secret.service.ts
> +    let projectsMappedToSecretsView: SecretProjectView[] = [];
I'm probably missing something, but any reason why these changes (lines 155-165) can't just be this?

```
if (secretResponse.projects != null) {
  secretView.projects = await this.decryptProjectsMappedToSecrets(
    orgKey,
    secretResponse.projects
  );
}
```

2022-12-29 17:52 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.html
> +                  <button
When removing the project, and then attempting to add it back again, we may want to consider clearing the dropdown so that a project can be selected again?

https://user-images.githubusercontent.com/5691612/209989892-7a8138cb-e255-45af-8861-4018dce32ddc.mov

2022-12-29 18:11 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.ts
> +  removeProjectAssociation = async (id: string) => {
No, I had just copied a function from somewhere else and it was defined like that 😄

2022-12-29 18:13 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/secret.service.ts
> +    let projectsMappedToSecretsView: SecretProjectView[] = [];
It could be written like this, I changed it 👍

2022-12-29 18:14 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.html
> +                  <button
ooh nice catch, thank you!

2022-12-29 18:14 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/secret.service.ts
> +    const projectIds: string[] = [];
I was thinking that earlier actually, thanks!

2022-12-30 21:44 UTC, coltonhurst requested changes
@cd-bitwarden Thanks for fixing the dropdown issue!

However, the [aforementioned issue](https://github.com/bitwarden/clients/pull/4144#pullrequestreview-1232637592) when creating a secret within a project still exists. Currently on the master branch, when creating a secret within a project, the secret is automatically added to that project by default.

However, that's no longer currently happening; please let me know if you want to discuss further and I can explain!

https://user-images.githubusercontent.com/5691612/210113618-6f67fee0-bfe9-4978-82e9-802e8d76ac92.mov

2023-01-03 19:19 UTC, coltonhurst requested changes
Thanks for the update about SM-100! A few more comments and I think we should be good.

Do you mind informing QA that the behavior change here (regarding creating a secret within a project) is fixed in a later PR? That way they don't classify it as a regression. Also, just a thought- we may want to try and keep behavior changes within the same PR, that way it's not broken until the other PR is merged. I may be missing something if this is necessary in this case though!

2023-01-03 19:19 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/secret.service.ts
> +        secretListView.projects = projectsMappedToSecret.filter((p) => projectIds.includes(p.id));
Maybe we can turn all of these lines into one? I think you'll still need line 180 but 181-185 could become:

`secretListView.projects = projectsMappedToSecret.filter(p => s.projects.map(x => x.id).includes(p.id));`

I believe that still accomplishes what you want, but please feel free to edit if it doesn't.

2023-01-03 23:05 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.ts
> +    this.destroy$.next();
done 😄

2023-01-03 23:05 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.ts
> +    this.formGroup.get("project").setValue(""); //set the selected to nothing;
removed 👍

2023-01-03 23:08 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/secret.service.ts
> +        secretListView.projects = projectsMappedToSecret.filter((p) => projectIds.includes(p.id));
I'm a little confused, decryptProjectsMappedToSecrets does handle the mapping already

2023-01-04 14:45 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/secret.service.ts
> +        secretListView.projects = projectsMappedToSecret.filter((p) => projectIds.includes(p.id));
Your most recent commit looks great and addresses everything from this comment. Does everything work as expected? If so I think we are good, let me know if I can help explain anything, I'm not sure what you mean :)

2023-01-04 14:46 UTC, coltonhurst approved these changes
Thanks for the fixes!

2023-01-04 15:49 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/secret.service.ts
> +        secretListView.projects = projectsMappedToSecret.filter((p) => projectIds.includes(p.id));
Yeah I'm 99% sure I left that comment on an old comment that said something different, everything works 😄

2023-01-04 22:29 UTC, closed without merging

2023-01-04 22:30 UTC, cd-bitwarden commented
Closing because I had to open a PR with a commit signature (https://github.com/bitwarden/clients/pull/4382)