[SM-360] Add support for never expiring access tokens
bitwarden/clients pull request #4150
Opened 2022-11-29 22:11 UTC by Thomas-Avery

## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

The purpose of this PR is to add the ability to create never expiring access tokens for the secrets manager project.

This client update is tied to the server side update https://github.com/bitwarden/server/pull/2450

## Code changes

- bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/access-list.component.html
bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/access-list.component.ts

In the access list table, show `Never` localized text for never expiring tokens.

- bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/access.service.ts
bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/models/responses/access-token-creation.response.ts
bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/models/responses/access-tokens.response.ts
bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/models/view/access-token.view.ts

Support null values for `ExpireAt` in access token models.

- bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/dialogs/access-token-create-dialog.component.ts

Allow never expiring tokens to be created in the create access token dialog.

## Screenshots

![image](https://user-images.githubusercontent.com/43214426/204658992-b235810e-dbb6-4f96-8555-5a2ac1ea03dd.png)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-11-29 23:52 UTC, willmartian requested changes
One small note, but everything else looks good here!

2022-11-29 23:52 UTC, willmartian commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/access-list.component.html
> +      <td bitCell>{{ getExpiration(token) }}</td>
When you put a helper function into template like this, it will rerun every time the component renders (possibly causing performance issues). To memoize the logic, you can either convert your helper function into a custom Pipe, or just move the logic into the template:

```njk
      <td bitCell>{{ token.expireAt === null ? ('never' | i18n) : (token.expireAt | date:"medium") }}</td>
```

2022-11-30 16:38 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/access-list.component.html
> +      <td bitCell>{{ getExpiration(token) }}</td>
Great catch @willmartian I didn't know about this. 

I have this fixed and a similar date time getter fix proposed in:

https://github.com/bitwarden/clients/pull/4150/commits/6436e5271066aafec38f47629a836a774d3e2a40

2022-11-30 21:32 UTC, willmartian approved these changes
💯 LGTM

2022-12-01 12:29 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/dialogs/expiration-options.component.ts
> +  currentDate: Date = new Date();
```suggestion
  currentDate = new Date();
```

2022-12-01 15:40 UTC, Hinton approved these changes

2022-12-01 16:20 UTC, merged