Split folder service back/foreground
bitwarden/clients pull request #4209
Opened 2022-12-09 16:38 UTC by MGibson1

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Also splits for folderApiService, since that depends on folderService.

TODO: this split will need to be done for any dependents of a split service.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

# Draft Reason
This is to test fixes and potentially early-merge before fixing all references to services

2022-12-15 12:26 UTC, djsmith85 requested changes
@MGibson1: Changes are looking good so far.

Please add `ThemingService` as I think that is currently the last one.

2022-12-15 23:30 UTC, MGibson1 commented
Theming service does not exist in background, but I added PolicyApiService, thanks

2022-12-16 00:12 UTC, djsmith85 requested changes

2022-12-16 00:12 UTC, djsmith85 commented on apps/browser/src/popup/services/services.module.ts
> +        organizationService: OrganizationService
OrganizationService should also be removed from here.

2022-12-16 00:56 UTC, djsmith85 submitted a review, later dismissed

2023-01-30 19:04 UTC, merged