[EC-781] User can bypass master password requirements policy by canceling password reset and pasting invite link
bitwarden/clients pull request #4218
Opened 2022-12-13 12:56 UTC by r-tome

## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Fix this issue:
> If the user follows the invite link and logs in with their current Master Password, but clicks Cancel on the Master Password Reset page, they are dropped into their existing account. Copying and pasting the invitation link again into the same browser session appears to bypass the Master Password Reset screen, as the user receives an invitation success toast and is immediately moved to an Accepted state in the Organization

This is solved by forcing authenticated users to go through the same flow as unauthenticated users and login again to go through the existing password check .

## Code changes

- **apps/web/src/app/accounts/accept-organization.component.html:** Removed unnecessary condition due to authenticated users also needing to login
- **apps/web/src/app/accounts/accept-organization.component.ts:** Forcing the user to login to evaluate if the user's current password meets the Organization password policy requirements
- **apps/web/src/app/accounts/update-password.component.html:** Fix existing issue on submitting the update password form
- **apps/web/src/app/common/base.accept.component.ts:** Getting the email value from the query parameters also for authenticated requests

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-12-20 23:37 UTC, eliykat requested changes

2022-12-20 23:37 UTC, eliykat commented on apps/web/src/app/accounts/accept-organization.component.ts
> +      await this.unauthedHandler(qParams);
Suggestion: make this an early return and remove the `else` expression to reduce nesting.

2022-12-20 23:37 UTC, eliykat commented on apps/web/src/app/accounts/accept-organization.component.ts
> +      await this.stateService.setActiveUser(null);
I don't think this is the right way to log out a user - it looks like it's mostly used internally in `StateService` and also in desktop account switching. That suggests it probably leaves some data behind (given that switching accounts does not log you out). If we're taking a user to a login page, they're going to assume that they've been logged out, so let's make sure we do that.

In web, the standard way is to send a `logOut` message via `messagingService`, which is handled here: https://github.com/bitwarden/clients/blob/master/apps/web/src/app/app.component.ts#L223. See how that calls all the services to make sure they clean up their data.

The downside is that this logout method also redirects you, you'll have to figure out how to still run the `unauthedHandler` logic.

2022-12-20 23:37 UTC, eliykat commented on apps/web/src/app/accounts/accept-organization.component.ts
> +      // Forcing the user to login to evaluate if the user's current password meets the Organization password policy requirements
Can you please add a comment giving more information about when this code path is executed. e.g.

```ts
// User has clicked an invitation link and is visiting this component for the first time
```

And then at the start of the `else` block:

```ts
// User has already logged in and passed the Master Password policy check
```

2022-12-28 20:58 UTC, MGibson1 commented on apps/web/src/app/accounts/accept-organization.component.ts
> +    }
This is handled in a confusing way to me, we can update to remove the need to comment with some better naming
```suggestion
    const needsReAuth = (await this.stateService.getOrganizationInvitation()) != null;
    if (!needsReAuth) {
      // Accepting an org invite requires authentication from a logged out state
      this.messagingService.send("logout", { redirect: false });
      return;
    }
```

Also, it's not necessary to reference unauthHandler since if you log out, it'll handle as an unauth. To me, those two things really clear up what's happening here.

2022-12-29 10:44 UTC, r-tome commented on apps/web/src/app/accounts/accept-organization.component.ts
> +    }
Thanks for the suggestion, that does look simpler. I tried not referencing `unauthHandler` but it did not handle as an unauth, it only fires the first time and it's handled as authenticated. I've extracted the logic to a new method `prepareOrganizationInvitation` which then is called on both cases.

2022-12-29 14:40 UTC, MGibson1 approved these changes

2022-12-29 16:20 UTC, merged