Add files individual packages hash files to release
bitwarden/clients pull request #4254
Opened 2022-12-16 12:12 UTC by michalchecinski

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [x] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **scripts/export_sha_to_files.py:** Add script to extract SHA hashed for desktop packages from the electron `.yml` files.
- **.github/workflows/release-desktop.yml:** Add steps to get files containing SHA hash for desktop files

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-12-19 22:49 UTC, vgrassia requested changes
@michalchecinski 

I think your Python script is a great starting point.

I did notice that the `sha512` values in the `latest-*.yml` files are base64 encoded binary strings, which aren't going to be easy for users to check against.  As an example, I had to use the command `openssl dgst -binary -sha512 Bitwarden-Installer-2022.12.0.exe | base64` to generate a matching string. We're also going to need a `sha512` hash for every artifact that is uploaded to our releases for each repository.

I would turn your Python script into an action in our `gh-actions` repository, update the script to generate a `sha512` checksum for each downloaded artifact and then put all of the hashes in a single file.  [Debian](https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/SHA512SUMS) does something similar.

2022-12-21 16:57 UTC, michalchecinski commented
Thanks @vgrassia for the input! I'll continue working on those after the Holidays :)

2023-01-02 17:29 UTC, michalchecinski commented
@vgrassia PR with github action for calculating SHA checksums: https://github.com/bitwarden/gh-actions/pull/95

2023-01-18 15:10 UTC, vgrassia requested changes

2023-01-18 15:10 UTC, vgrassia commented on .github/workflows/release-desktop.yml
> +            apps/desktop/artifacts/sha256-checksums.txt"
```suggestion
            apps/desktop/artifacts/${{ env.RELEASE_CHANNEL }}.yml,
            apps/desktop/artifacts/${{ env.RELEASE_CHANNEL }}-linux.yml,
            apps/desktop/artifacts/${{ env.RELEASE_CHANNEL }}-mac.yml,
            apps/desktop/artifacts/sha256-checksums.txt"
```

We should still upload the `latest*.yml` files just in case users have been using them.

2023-01-30 16:19 UTC, vgrassia approved these changes

2023-01-30 16:19 UTC, merged