[EC-667] Collection modal add search function
bitwarden/clients pull request #4291
Opened 2022-12-21 13:55 UTC by coroiu

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Add new searchable select to collection dialog. This implementation is a quick fix and we need to address the fact that we now have two different select implementations: multi-select and the regular select. The latter is not defined in the figma CL documentation.

## Screenshots

![image](https://user-images.githubusercontent.com/2285588/208921757-fd49b427-3a0e-42ad-9b6c-82e722a4be19.png)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-12-21 16:27 UTC, danielleflinn commented
@coroiu good call; can you add a story to the jira Component Library board?

2022-12-22 08:50 UTC, coroiu commented
@danielleflinn done! [CL-77 [Bug ?] Multi-select dropdown is missing hover state on selected items](https://bitwarden.atlassian.net/browse/CL-77)

2022-12-22 21:41 UTC, shane-melton requested changes
Looks good, only issue is there is no way to "un-nest" a collection and put it at the top level. Once that's fixed, we should be good to go!

2022-12-23 08:24 UTC, coroiu commented on libs/components/src/select/select.component.ts
> +  protected set breadcrumbList(value: QueryList<OptionComponent<T>>) {
Oh copy-pasta, interesting that this slipped by :)

2022-12-23 09:09 UTC, coroiu commented on apps/web/src/app/organizations/shared/components/collection-dialog/collection-dialog.component.html
> +              <bit-option
`ng-select` has an `x` that the user can press to clear the field and set `parent` to null

2022-12-23 09:10 UTC, coroiu commented on apps/web/src/app/organizations/shared/components/collection-dialog/collection-dialog.component.html
> +              <bit-option
Which of course is not visible in the screenshot because it disappears when the dropdown is open 😄

2022-12-23 10:02 UTC, coroiu commented
This PR seems to be broken in more ways than one. I think this will have to wait until after OAVR v2

2022-12-28 16:03 UTC, danielleflinn commented on apps/web/src/app/organizations/shared/components/collection-dialog/collection-dialog.component.html
> +              <bit-option
I think in Figma I had added a "No collection" select which is the default selected / null value. If its too difficult to add that as an options, we can rely on the `x` for reseting the field as null.

2023-01-11 13:05 UTC, coroiu commented on apps/web/src/app/organizations/shared/components/collection-dialog/collection-dialog.component.html
> +              <bit-option
@danielleflinn  Ah yes now I see, I've been looking at the handover documentation which instead has a `-- Select --` placeholder and does not mention `No collection`. We can't have placeholder and `No collection` so we have to choose. The simplest solution would be to keep placeholder and use the X to remove any parent collection. Question is if the accessibility is acceptable

See: [Figma link](https://www.figma.com/file/3tWtMSYoLB0ZLEimLNzYsm/End-user-%26-admin-Vault-Refresh?node-id=2288%3A54636&t=r1v2y4UACrMwnssr-0)
![image](https://user-images.githubusercontent.com/2285588/211808972-cefff920-5067-48bd-a99d-044a8863b536.png)

2023-01-11 16:10 UTC, danielleflinn commented on apps/web/src/app/organizations/shared/components/collection-dialog/collection-dialog.component.html
> +              <bit-option
Hm I prefer the "No collection" solution over the "-- Select --" placeholder. But if that is too difficult we can likely just use the "x", as a user can still clear the selected item using the backspace/delete key.

2023-01-12 11:56 UTC, coroiu commented on libs/components/src/select/select.component.ts
> +  protected set breadcrumbList(value: QueryList<OptionComponent<T>>) {
Fixed!

2023-01-12 12:14 UTC, coroiu commented on apps/web/src/app/organizations/shared/components/collection-dialog/collection-dialog.component.html
> +              <bit-option
I've removed the `x` and replaced it with "No collection" :)

2023-01-26 01:24 UTC, shane-melton requested changes
Looks really good! Only one small issue is that the search text is very difficult to read when using the dark theme due to the search text staying black.
<img width="502" alt="image" src="https://user-images.githubusercontent.com/8764515/214734459-139ab6bf-ec8f-4a28-82f8-0ddb43818629.png">

2023-01-26 18:25 UTC, shane-melton approved these changes
Looks good!

2023-02-06 14:52 UTC, jlf0dev approved these changes

2023-02-06 14:54 UTC, merged