Ec 550 members role tab
bitwarden/clients pull request #4297
Opened 2022-12-21 22:36 UTC by jlf0dev

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Small amount of changes for the Role Tab.
- Renamed "User Type" to "Member Role"
- Renamed `user-admin-view` to `organization-user-admin-view`
- Added type to existing form group

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-12-22 12:59 UTC, coroiu commented
Shouldn't the `NestedCheckboxComponent` also be migrated/updated to use reactive forms somehow?

2022-12-22 19:16 UTC, shane-melton requested changes
Only one small thing we need to fix with regards to the the user type radio using both the reactive form control and `[disabled]` directive.

Once that is fixed I think we're good to go and can merge! Nice job!

2022-12-22 19:16 UTC, shane-melton commented on apps/web/src/app/organizations/members/components/member-dialog/member-dialog.component.html
> +                [disabled]="!canUseCustomPermissions || null"
Using the `[disabled]` directive here is throwing the following warning in Angular. I think we'll have to handle this the "reactive" way. 

Also, I don't think we need the `[value]` assignment above if using the `formControlName`
```
It looks like you're using the disabled attribute with a reactive form directive. If you set disabled to true
  when you set up this control in your component class, the disabled attribute will actually be set in the DOM for
  you. We recommend using this approach to avoid 'changed after checked' errors.

  Example:
  form = new FormGroup({
    first: new FormControl({value: 'Nancy', disabled: true}, Validators.required),
    last: new FormControl('Drew', Validators.required)
  });
```

2022-12-22 19:47 UTC, shane-melton approved these changes
LGTM!

2022-12-22 19:54 UTC, merged

2022-12-23 08:21 UTC, coroiu commented
Oh that's why we were using `[attr.disable]`. Not the best way but since we're not using `bitRadio` yet I guess it works for the time being