SM-365: Add scaffolding for settings, import, and export components
bitwarden/clients pull request #4323
Opened 2022-12-27 15:34 UTC by coltonhurst

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Adds importing and exporting for SM items.

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-01-26 17:38 UTC, Hinton requested changes

2023-01-26 17:38 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-export.component.html
> +  </bit-form-field>
Also this won't show correctly if the org is using key connector.

2023-01-26 17:38 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-export.component.ts
> +    this.doExport();
We should await this.

2023-01-26 17:38 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-export.component.ts
> +  }
I would expect this logic to be owned by the service which simplifies testing, and lets us reuse it should we implement more export places.

2023-01-26 17:38 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.ts
> +        if (file.type === "text/html") {
?

2023-01-26 17:38 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.ts
> +    await Swal.fire({
This should be a configurable simple dialog.

2023-01-26 17:38 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/responses/exported-secret.response.ts
> +    this.projectIds = projectIds == null ? null : projectIds.map((id: any) => id.toString());
```suggestion
    this.projectIds = projectIds?.map((id: any) => id.toString());
```

2023-01-26 17:38 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/responses/sm-export.response.ts
> +    this.secrets = secrets == null ? null : secrets.map((k: any) => new ExportedSecret(k));
```suggestion
    this.projects = projects?.map((k: any) => new ExportedProject(k));
    this.secrets = secrets?.map((k: any) => new ExportedSecret(k));
```

2023-01-26 17:38 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/responses/exported-secret.response.ts
> +export class ExportedSecret extends BaseResponse {
```suggestion
export class ExportedSecretResponse extends BaseResponse {
```

2023-01-26 17:38 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/responses/exported-project.response.ts
> +export class ExportedProject extends BaseResponse {
```suggestion
export class ExportedProjectResponse extends BaseResponse {
```

2023-01-27 05:07 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/layout/header.component.html
> +  <sm-new-menu *ngIf="!hideSearchAndNewMenu"></sm-new-menu>
Sounds good.

2023-01-27 05:14 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-export.component.html
> +    </select>
We are not supporting different formats currently, but the dropdown was added based on the designs, and for whenever we add more formats in the future. For that component, within `ngOnInit()` the dropdown is disabled, so `json` is the only option. I should have added some screen shots in the PR, I'll add them!

2023-01-27 05:16 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-export.component.html
> +  </bit-form-field>
Bummer. This was based on the designs provided; thoughts on how we should approach this?

2023-01-27 05:19 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/layout/navigation.component.html
> +<bit-nav-group icon="bwi-cog" [text]="'settings' | i18n" route="settings">
Sounds good.

2023-01-27 05:20 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/models/porting/sm-export.ts
> +export class SMExport {
Updated, should we keep the `SM` prefix on the other classes?

2023-01-27 05:21 UTC, coltonhurst commented on apps/web/src/locales/en/messages.json
> +  },
Oops, I left out something. It should be used now!

2023-01-27 05:21 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-export.component.html
> +    <small class="form-text text-muted">{{ "confirmIdentity" | i18n }}</small>
Didn't know we had this, awesome!

2023-01-27 05:22 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-export.component.ts
> +    this.doExport();
Fixed 👍

2023-01-27 05:23 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.ts
> +        if (file.type === "text/html") {
This and other pieces of the import were taken from the password manager import logic.

2023-01-27 05:53 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-export.component.ts
> +  }
Great point, I've moved it to `sm-porting.service.ts`.

2023-01-27 05:54 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/responses/exported-secret.response.ts
> +    this.projectIds = projectIds == null ? null : projectIds.map((id: any) => id.toString());
Fixed

2023-01-27 05:54 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/responses/sm-export.response.ts
> +    this.secrets = secrets == null ? null : secrets.map((k: any) => new ExportedSecret(k));
Fixed

2023-01-27 05:54 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/responses/exported-secret.response.ts
> +export class ExportedSecret extends BaseResponse {
Updated

2023-01-27 05:55 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/responses/exported-project.response.ts
> +export class ExportedProject extends BaseResponse {
Updated

2023-01-27 15:48 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.ts
> +        if (file.type === "text/html") {
The password importer supports xml and other formats that we don't.

2023-01-28 20:51 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.ts
> +        if (file.type === "text/html") {
Removed the check for the `text/html` file type. Please let me know if we should update any other areas of the file reading during import.

2023-01-29 05:51 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-export.component.html
> +  </bit-form-field>
@Hinton Thoughts on this as the solution? (just using the existing flow that supports key connector?)

https://github.com/bitwarden/clients/pull/4596

2023-02-01 15:37 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-export.component.html
> +  </bit-form-field>
https://github.com/bitwarden/clients/pull/4596 was merged, resolving this

2023-02-02 17:55 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.ts
> +    await Swal.fire({
Updated

2023-02-03 13:56 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-export.component.html
> +    <select bitInput required formControlName="format">
This is applied by the validators.

```suggestion
    <select bitInput formControlName="format">
```

2023-02-03 13:56 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-export.component.ts
> +    protected fileDownloadService: FileDownloadService,
```suggestion
    private fileDownloadService: FileDownloadService,
```

2023-02-03 13:56 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-export.component.ts
> +  }
Future TD, We should extract this logic into a service so we don't have to have intimate knowledge of that component.

2023-02-03 13:56 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.html
> +<form #form (ngSubmit)="submit()" class="tw-max-w-xl">
Please use the new `[bitSubmit]` https://components.bitwarden.com/?path=/story/component-library-async-actions-in-forms-documentation--page

2023-02-03 13:56 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.html
> +  <br />
Prefer to use margin here instead of br.
```suggestion
  <div class="tw-my-3>
    {{ "or" | i18n }}
  </div>
```

2023-02-03 13:56 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.html
> +  <div>
Any reason to have a wrapping div here?

2023-02-03 13:56 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.html
> +  <br />
```suggestion
```

2023-02-03 13:56 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.html
> +  <button bitButton type="submit" buttonType="primary" [disabled]="loading">
```suggestion
  <button bitButton bitFormButton type="submit" buttonType="primary">
```

2023-02-03 13:56 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.ts
> +  loading = false;
```suggestion
```

2023-02-03 13:56 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.ts
> +  fileContents: string;
FormGroup for format and content.

2023-02-03 13:56 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.ts
> +    this.loading = true;
Use the new submit logic.

2023-02-03 13:56 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.ts
> +    }
I think this can be cleaned up slightly. We can extract the logic related to the file field to it's own method. It would accept a `HTMLInputElement` and spit out a string.

If content is set use that, if file is set use that, else show an error.

2023-02-03 13:56 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.ts
> +  }
We don't really need to do this on select right? We could just check it while validating the form.

2023-02-03 13:56 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-porting.service.ts
> +  }
Let's extract these to an api service.

2023-02-03 13:56 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-porting.service.ts
> +        errorMessage += "\n\n";
How come we first parse it to a string, then split it up again? Can we just make our own error model?

```ts
type ImportErrorLine {
  id: number;
  type: "project" | "secret";
  key: string;
  error: strin;
}

type ImportError {
  lines: ImportErrorLine[];
}
```

2023-02-03 13:56 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-porting.service.ts
> +  }
You can use https://angular.io/api/common/formatDate here.

```ts
const locale = await firstValueFrom(this.i18nService.locale$)
const dateString = formatDate(new Date(), "yyyyMMddHHmmss", locale);
```

2023-02-03 18:35 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-export.component.ts
> +  }
Created an internal ticket for this.

2023-02-07 15:53 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.ts
> +  }
As discussed, we do need this so we can (done in a different location) show the user the selected file name. There are other ways based on the context this is in, but this is the simplest.

2023-02-07 16:05 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/models/porting/sm-export.ts
> +export class SMExportProject {
Updated

2023-02-07 16:05 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/dialog/import-error-dialog.component.html
> +  <div bitDialogFooter class="tw-flex tw-flex-row tw-items-center tw-gap-2">
Class removed

2023-02-07 16:06 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/dialog/import-error-dialog.component.html
> +        <tr bitRow *ngFor="let item of errorInfoList" length="100%">
Length not needed, removed

2023-02-07 16:07 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/dialog/sm-import-error-dialog.component.ts
> +      this.close(SMImportErrorDialogResult.ErrorDuringDialog);
It was added so that if there was an error trying to show the server errors, it would handle it well. I removed it, let me know if we need to add it back at some point.

2023-02-07 16:07 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.ts
> +  }
Removed

2023-02-07 16:07 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-export.component.html
> +    <select bitInput required formControlName="format">
Removed

2023-02-07 16:07 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-export.component.ts
> +    protected fileDownloadService: FileDownloadService,
Fixed

2023-02-07 16:07 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.html
> +<form #form (ngSubmit)="submit()" class="tw-max-w-xl">
Updated

2023-02-07 16:08 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.html
> +  <br />
Switched to using margin

2023-02-07 16:08 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.html
> +  <br />
Removed

2023-02-07 16:09 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.html
> +  <button bitButton type="submit" buttonType="primary" [disabled]="loading">
Updated

2023-02-07 16:09 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.ts
> +  loading = false;
Removed

2023-02-07 16:09 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.ts
> +  fileContents: string;
Updated

2023-02-07 16:13 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.ts
> +    this.loading = true;
Updated to this form: `submit = async () => {`

2023-02-07 17:46 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-porting.service.ts
> +  }
Perfect, thanks!

2023-02-08 05:22 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-porting.service.ts
> +        errorMessage += "\n\n";
Great point, thanks for pointing this out. I refactored the error flow, please let me know your thoughts.

2023-02-08 10:12 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-porting.service.ts
> +  }
Updated

2023-02-08 10:12 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.ts
> +    }
Updated

2023-02-09 11:44 UTC, Hinton reviewed
Getting there, a few more comments and we should be good.

2023-02-09 11:44 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/models/responses/sm-exported-secret.response.ts
> +export class SecretsManagerExportedSecretResponse extends BaseResponse {
Filename seems wrong.

2023-02-09 11:44 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.html
> +      {{ this.formGroup.get("fileSelected")?.value?.name ?? ("noFileChosen" | i18n) }}
This should work.

```suggestion
      {{ formGroup.value.fileSelected?.name ?? ("noFileChosen" | i18n) }}
```

You could also set `accept="application/JSON"` on the file selector which by default filters out non json files.

2023-02-09 11:44 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.html
> +  <div class="form-group">
Form groups are a bootstrap class. please change it to `bit-form-field`.

2023-02-09 11:44 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.html
>    <div>
This should also be a `bit-form-field` if you want hint to work correctly.

2023-02-09 11:44 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.ts
> +    pastedContents: new FormControl("", [Validators.required]),
Probably want to remove required here, only one of them at a time is required.

2023-02-09 11:44 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.ts
> +    this.formGroup.get("fileSelected")?.setValue(file);
It doesn't feel like `fileSelect` should be a form control, since we don't bind it to an input.

2023-02-09 11:44 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.ts
> +    this.formGroup.get("pastedContents").setValue("");
You can use https://angular.io/api/forms/FormGroup#reset

2023-02-09 21:43 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/models/responses/sm-exported-secret.response.ts
> +export class SecretsManagerExportedSecretResponse extends BaseResponse {
Apologies I must be missing something, what seems wrong with the filename?

2023-02-09 22:22 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.ts
> +    this.formGroup.get("pastedContents").setValue("");
Great point, updated

2023-02-09 22:22 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.ts
> +    this.formGroup.get("fileSelected")?.setValue(file);
Fair point, updated

2023-02-09 22:22 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.html
> +      {{ this.formGroup.get("fileSelected")?.value?.name ?? ("noFileChosen" | i18n) }}
Updated, great point, thank you!

2023-02-09 22:23 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.html
> +  <div class="form-group">
Updated!

2023-02-09 22:23 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.ts
> +    pastedContents: new FormControl("", [Validators.required]),
Updated

2023-02-09 22:23 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.html
>    <div>
Based on other comment, left this as div b/c `selectedFile` isn't bound to the formGroup anymore

2023-02-10 09:17 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/models/responses/sm-exported-secret.response.ts
> +export class SecretsManagerExportedSecretResponse extends BaseResponse {
I was certain there was a typo in `exported`, but I must have been mistaken. Sorry.

2023-02-10 09:19 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.html
> +  <div>
Should be a bit-form-field since you are using bit-hint below.

2023-02-10 09:26 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.html
>    <div>
Form fields aren't required to be bound to formControls. The styling for this will stop working after migrating away from bootstrap since all the default styles will be removed.

`bit-hint` also won't work outside form fields.

2023-02-10 09:26 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.html
> +      <button type="button" class="btn btn-outline-primary" (click)="fileSelector.click()">
bitButton.

2023-02-10 09:26 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.ts
> +      });
Why are we fetching the org using the ID, and then using the org object to grab the ID?

2023-02-10 20:34 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.html
>    <div>
Okay, sounds good. I've updated it but it required adding `"file"` to the `InputTypes` type. Do we need to update anything else to accommodate this change?

2023-02-10 20:34 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.html
> +      <button type="button" class="btn btn-outline-primary" (click)="fileSelector.click()">
Updated

2023-02-10 20:34 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.ts
> +      });
Great point- fixed

2023-02-13 02:04 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/models/responses/sm-exported-secret.response.ts
> +export class SecretsManagerExportedSecretResponse extends BaseResponse {
No worries!

2023-02-13 09:08 UTC, Hinton approved these changes
LGTM!

2023-02-13 09:08 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.html
>    <div>
No that should be enough.

2023-02-13 15:52 UTC, merged