[SG 623] Send Service Refactor
bitwarden/clients pull request #4327
Opened 2022-12-27 22:26 UTC by differsthecat

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-12-29 16:33 UTC, MGibson1 commented on apps/browser/src/popup/services/services.module.ts
> +      useFactory: getBgService<SendApiService>("sendApiService"),
This should probably use a factory specific to visualization contexts, not the bg service (due to dependence on state service)

You also seems to be missing a definition for `provide: SendService` and `provide: InternalSendService` that should use a non-bg factory

2022-12-29 16:36 UTC, MGibson1 commented on libs/common/src/services/fileUpload.service.ts
> +    private sendApiService: SendApiService
Rather than requiring specifically a send service, an interface should be devised here that works for both cipherAttachments and send files, then you can use `InjectionToken`s to specify a send-compliant file upload service or a cipher attachment compliant one

2022-12-29 16:36 UTC, MGibson1 commented on libs/common/src/services/fileUpload.service.ts
> +    private sendApiService: SendApiService
I don't want to tie this to a specific domain, flow should move in the opposite direction.

Another way to do that would be to provide callbacks for posting files, deleting files, and renewing file upload urls

2022-12-29 21:52 UTC, differsthecat commented on apps/browser/src/popup/services/services.module.ts
> +      useFactory: getBgService<SendApiService>("sendApiService"),
I tried playing around with this and have a couple of questions :) 
1. Both PolicyApiService and FolderApiService use the background services; what do you mean use a factory specific to visualization contexts?
2. There is a SendService defined, but it uses the bg factory. If I were to switch it to using BrowserSendService, would this be the correct way to provide it?
```{
      provide: SendService,
      useFactory: (
        cryptoService: CryptoService,
        i18nService: I18nService,
        cryptoFunctionService: CryptoFunctionService,
        stateServiceAbstraction: StateServiceAbstraction,
        sendApiService: SendApiService,
        fileUploadService: FileUploadService
      ) => {
        return new BrowserSendService(
          cryptoService,
          i18nService,
          cryptoFunctionService,
          stateServiceAbstraction,
          sendApiService,
          fileUploadService
        );
      },
      deps: [
        CryptoService,
        CryptoFunctionService,
        I18nService,
        StateServiceAbstraction,
        SendApiService,
        FileUploadService,
      ],
    },```
    
    I'm running into injection issues doing it like that, do I need to have the right combination of providing background services for it's service dependencies?

2022-12-30 16:12 UTC, MGibson1 commented on apps/browser/src/popup/services/services.module.ts
> +      useFactory: getBgService<SendApiService>("sendApiService"),
1. not for long it won't (#4209)
2. yes, that is generally right, but I would put the deps and arguments to the factory in the same order, IDK if this is required, but It might cause your injection issue -- what is the issue?

2023-01-23 14:09 UTC, differsthecat commented on apps/browser/src/popup/services/services.module.ts
> +      useFactory: getBgService<SendApiService>("sendApiService"),
@MGibson1 I was able to fix SendService and InternalSendService, but I still see the error that `global.ContainerService` is not defined when not using the background service. I ensured the services provided and the order matched the factory definition, but it still throws that error.

2023-01-23 14:10 UTC, differsthecat commented on libs/common/src/services/fileUpload.service.ts
> +    private sendApiService: SendApiService
@MGibson1 Thank you for your help on this!

2023-02-21 22:22 UTC, MGibson1 commented on libs/common/src/abstractions/send/send-api.service.abstraction.ts
> +  removePasswordWithServer: (id: string) => Promise<any>;
All methods in this class are assumed to update server, no need to call it out

2023-02-21 22:22 UTC, MGibson1 commented on libs/angular/src/components/send/send.component.ts
> +    const sends = await firstValueFrom(this.sendService.sendViews$);
What do you think about updating this component to use the observable vs promising it?

2023-02-21 22:22 UTC, MGibson1 commented on libs/common/src/models/domain/send.ts
> +    return Object.assign(new Send(), obj, { name: EncString.fromJSON(obj.name), revisionDate });
Should have the same serialization treatment for all dates (expiration and delete are missing)

2023-02-21 22:22 UTC, MGibson1 commented on libs/common/src/services/send/send-api.service.ts
> +    this.sendFileUploadService = new SendFileUploadService(this, fileUploadService);
The other option is to get rid of this class and accept that `upload` is part of the `SendApiService` itself.

That's a fair amount of complexity to add to this class, but it gets rid of this odd service creation. I'd feel better is this was named a helper or something and was used just to generate methods vs being a service with an odd life cycle

2023-02-23 19:18 UTC, differsthecat commented on apps/browser/src/popup/send/send-groupings.component.ts
> +      sendApiService
It extends the base SendComponent, which calls the send API service to update server data for sends

2023-02-23 19:24 UTC, differsthecat commented on libs/common/src/services/send/send-api.service.ts
> +    this.sendFileUploadService = new SendFileUploadService(this, fileUploadService);
Yeah, I'm playing around with that and like it better. The sendApiService is the only one that needs to call these methods so it makes sense.

2023-02-23 20:04 UTC, differsthecat commented on libs/common/src/types/file-upload-api-methods.ts
> +export type FileUploadApiMethods = {
Moved, there did have to be an export outside the directory as both file upload service and abstraction need the type.

2023-02-23 20:06 UTC, differsthecat commented on libs/common/src/abstractions/send/send-api.service.abstraction.ts
> +  removePasswordWithServer: (id: string) => Promise<any>;
Good point, removed!

2023-02-23 20:53 UTC, differsthecat commented on libs/angular/src/components/send/send.component.ts
> +    const sends = await firstValueFrom(this.sendService.sendViews$);
:face-palm: fixed

2023-02-27 21:12 UTC, differsthecat commented on libs/common/src/models/domain/send.ts
> +    return Object.assign(new Send(), obj, { name: EncString.fromJSON(obj.name), revisionDate });
Updated, along with correct serialization for text!

2023-03-01 23:39 UTC, MGibson1 requested changes
This is almost there, but there are still some lingering issues with serialization of the `Send` type.

The `SendView.fromJSON` method might be a good place to look for inspiration.

2023-03-01 23:39 UTC, MGibson1 commented on libs/angular/src/components/send/send.component.ts
> +      this.sends = sends;
Can you make a ticket to transition this component to utilizing the observable stream directly?

2023-03-01 23:39 UTC, MGibson1 commented on libs/common/src/models/domain/send.ts
> +      text: EncString.fromJSON(obj.text.text),
This line doesn't look right to me. The object has a property like this
```
{..., text: SendText,...}
``` 
which should generate
```
{...,text: {text: EncString, hidden: boolean}...}
```

I think you're missing a level.

2023-03-01 23:39 UTC, MGibson1 commented on libs/common/src/models/domain/send.ts
> +      text: EncString.fromJSON(obj.text.text),
Two more notes on this
1. I think this is better handled with a call to a static `fromJSON` method in the `SendText` class, so it can own its own instantiation
2. you're missing the `file` property so you should do the same for `SendFile` object

2023-03-02 15:02 UTC, differsthecat commented on libs/angular/src/components/send/send.component.ts
> +      this.sends = sends;
Sure! What do you mean by using the stream directly? Do you have an example of what you mean?

2023-03-02 21:33 UTC, MGibson1 commented on libs/angular/src/components/send/send.component.ts
> +      this.sends = sends;
Sure. I might be mis-naming it, sorry! [I mean piping it ](https://github.com/bitwarden/clients/blob/master/apps/web/src/app/layouts/navbar.component.html#L23) in the template rather than storing the value locally and binding to that.

I don't see any usages of `this.sends` that couldn't be done through some pipe operations, but I might be wrong. That's why I think a ticket to do it is appropriate rather than further slow this PR down

2023-03-02 21:33 UTC, MGibson1 submitted a review, later dismissed

2023-03-02 21:34 UTC, differsthecat commented on libs/angular/src/components/send/send.component.ts
> +      this.sends = sends;
Got it, thank you!

2023-03-21 17:42 UTC, MGibson1 requested changes

2023-03-21 17:42 UTC, MGibson1 commented on libs/common/src/models/domain/send.ts
> +      file: obj.file ? SendFile.fromJSON(obj.file) : null,
It's better to handle null in the `fromJSON` methods.

It should also be handled here on line 109

```typescript
  static fromJSON(obj: Jsonify<Send>) {
    if (obj == null) {
      return null;
    }

    const revisionDate = obj.revisionDate == null ? null : new Date(obj.revisionDate);
```

2023-03-21 17:46 UTC, differsthecat commented on libs/common/src/models/domain/send.ts
> +      file: obj.file ? SendFile.fromJSON(obj.file) : null,
Ah, good to know, I'll make that change.

2023-03-21 18:30 UTC, differsthecat commented on libs/common/src/models/domain/send.ts
> +      file: obj.file ? SendFile.fromJSON(obj.file) : null,
Fixed!

2023-03-21 20:45 UTC, MGibson1 submitted a review, later dismissed

2023-03-24 01:04 UTC, MGibson1 approved these changes
:shipit:

2023-03-28 16:07 UTC, gbubemismith approved these changes

2023-03-28 16:37 UTC, merged