[EC 911] Prevent Table from overflowing
bitwarden/clients pull request #4377
Opened 2023-01-04 16:24 UTC by jlf0dev

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Whenever an item was added with a long name, our vault table would expand to accommodate instead of wrapping the text. This caused issues when we had notification boxes on the side.

This PR should prevent this behavior.
## Code changes

- **table.component.html:** Set the style `word-break: break-word`. We can't use the tailwind version of this because they use `overflow-wrap: break-word` which doesn't seem to work on tables.
- **vault-items.component.html:** Allow the badge column in the table to shrink instead of splitting it 50/50 with the name column
- **badge.directive.ts:** Adding the `word-break: break-word` on the table would also apply this to the badges. We need to prevent badges from wrapping anyway, so i've set them to be `inline-block` in the directive.

## Screenshots

Before:
![image](https://user-images.githubusercontent.com/24985544/210601213-bd875875-8f33-4eb9-81e0-792af11c3d2d.png)

After:
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/24985544/210601349-43eb4d70-a578-4be5-b5cd-99db39e13552.png">

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/24985544/210601468-89f1caea-43ef-4c2d-bd83-f6c52b9f4629.png">

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-01-04 23:28 UTC, shane-melton requested changes
We might need a slightly different solution since `word-break: break-word` is deprecated and using the `style` attribute will likely cause CSP issues.

It looks like that [deprecation note](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break) mentions using a combination of `word-break: normal` and `overflow-wrap: anywhere` to get the desired affect instead.

2023-01-04 23:28 UTC, shane-melton commented on libs/components/src/table/table.component.html
> +  [style.word-break]="'break-word'"
thought: I think this might cause us some CSP issues by using `style` directly on a tag. 

Also, it looks like `word-break: break-word` is [deprecated](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break). 
> Note: While `word-break: break-word` is deprecated, it has the same effect, when specified, as `word-break: normal` and `overflow-wrap: anywhere` — regardless of the actual value of the [overflow-wrap](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap) property.

2023-01-05 09:54 UTC, Hinton commented on libs/components/src/badge/badge.directive.ts
> +      "tw-inline-block",
We're jumping back and forth on this https://github.com/bitwarden/clients/pull/3089. The padding needs to be adjusted back and the previous issues with this approach needs to be resolved.

2023-01-05 10:56 UTC, coroiu commented on libs/components/src/badge/badge.directive.ts
> +      "tw-inline-block",
Nice catch, took me a while to figure out why we did this change in the first place. Good thing I added screenshots in the original PR!

The issue with `inline-block` is how it calculates it's height, I've had to deal with this issue in other places as well, see: https://github.com/bitwarden/clients/pull/3954. The way I understand it `tw-inline-block` makes the element take up the entire height of it's parents `line-height`. This results in issues like the following:

### `inline-block`
![image](https://user-images.githubusercontent.com/2285588/210762765-0f9e0aa9-bc27-4a48-982f-283003c948ce.png)

### `inline`
![image](https://user-images.githubusercontent.com/2285588/210762710-6f4c2fe4-b5b8-4656-9db9-c6cdd7bfbe36.png)

Something I've learned after https://github.com/bitwarden/clients/pull/3954 however, is that `button` elements are not allowed to be `inline`, meaning that `<button bitBadge` should already be rendered as `inline-block` so this change shouldn't really change anything. Maybe `display: inline` on a `button` changes `word-break` behavior but not `height` calculation.

2023-01-05 14:55 UTC, jlf0dev commented on libs/components/src/table/table.component.html
> +  [style.word-break]="'break-word'"
Glad you said something, I was wondering why the CSP was suddenly throwing errors 😆 

Turns out I can achieve the same effect by using `tw-break-all` on the `td`. It uses `word-break: break-all` under the hood, but seems to work out just as well.

2023-01-05 14:58 UTC, jlf0dev commented on libs/components/src/badge/badge.directive.ts
> +      "tw-inline-block",
I had no idea of the history here, thanks for the further explanation @coroiu.

Turns out that we already had `tw-whitespace-nowrap` on the badge directive, but it was incorrectly spelled as `tw-whitespace-no-wrap` so it wasn't being applied. Changing that back stops the wrapping, so I don't need it to be `inline-block` after all 😄

2023-01-05 16:23 UTC, coroiu commented on libs/components/src/badge/badge.directive.ts
> +      "tw-inline-block",
That's really good to hear 'cause I did not want to get into `inline-block` again haha :D

2023-01-05 19:44 UTC, merged