[PS-2120] Forcing vault to refresh when the vault is purged or new items are imported
bitwarden/clients pull request #4380
Opened 2023-01-04 19:24 UTC by aj-rosado

## Type of change

```
- [ x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

There are some cases that the vault is not synced after a successful call to purge or import. Added a flag to force it.

## Code changes

- **sync.service.ts:** Added a public flag that allows components to force the service to execute the `FullSync` method until the end.
- **purge-vault-component.cs, import.component.cs:** Setting the `ShouldForceSync` flag to true, after a successful call to import or purge.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-01-05 13:39 UTC, MGibson1 requested changes
I don't think this is the right way to go about this.

The SyncService (and most services) are singletons and setting this at the service level will cause all syncs to be forced for the entire application.

this needs to be solved on an interaction-by-interaction basis. Why is `this.syncService.fullSync(true)` not sufficient?

2023-01-05 14:08 UTC, aj-rosado commented
> I don't think this is the right way to go about this.
> 
> The SyncService (and most services) are singletons and setting this at the service level will cause all syncs to be forced for the entire application.
> 
> this needs to be solved on an interaction-by-interaction basis. Why is `this.syncService.fullSync(true)` not sufficient?

After the next successful sync the variable was set to false again, so the FullSync would be forced only on the next call. The idea is after the purge or import is completed, the next call to FullSync should always run, because we know there are changes.
When the user navigates to the vault (after purge or import he is navigating there) it will call the FullSync to check changes so was avoiding an extra call to FullSync, but calling `this.syncService.fullSync(true)` should be sufficient.

2023-01-11 19:43 UTC, MGibson1 approved these changes

2023-01-11 19:44 UTC, MGibson1 commented
this is the route we want to go forward with on PS-2120

2023-01-11 22:47 UTC, merged