[EC-887] Fix Managers can see options to edit/delete Collections they aren't assigned to
bitwarden/clients pull request #4395
Opened 2023-01-05 22:36 UTC by shane-melton

## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

It was discovered that Manager users would still see collections in the vault that the did not have access to. This is the intended behavior, as Managers have permission to create Collections by default. However, even though Managers can view all collections, they do not always have permission to edit all collections, so this PR removes the edit/delete controls when they do not have the appropriate permissions. It also introduces a new warning message indicating they do not have sufficient privileges to view all the items in a collection they do not have access to. 

There is a required server change for this PR.

## Code changes

- **apps/web/src/app/organizations/vault/vault-items.component:** Add logic to the component to hide controls for collections that are read only for a user. Also, show new "missing permission" message in case a user filters to a collection they do not have access to view items in.
- **collection-admin.service.ts and view/response:** Add the new `assigned` property for determining user access

## Screenshots

### Showing disabled controls 
User only has access to collection "Another One" so it is the only row that shows the checkbox and 3 dots menu
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/8764515/210892387-5fd11db8-efd6-44d3-988a-b67e18bc937b.png">

### Missing permission to view all items
The User does not have access to the "Alpha" collection, but they still have permission to view all collections so a message is displayed below the table indicating that they do not have permission to view all items. _Note: They also do not have access to "Nest" or "Test" so the controls are hidden for those rows_
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/8764515/210892469-3b1dfe7b-c577-4f8c-9c6c-c78e13e5d8b5.png">

### Viewing an assigned nested collection
The User has access to "Charlie" so they can see all the items within.
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/8764515/210892934-e2ff52c7-2ebc-4010-a1ef-3d30fa3c8523.png">

### Viewing an assigned collection with no items
The User has access to "Another One" but it contains no items, so the normal "no items" message is displayed.
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/8764515/210893118-6372e652-683e-4101-a2e2-83f73212640e.png">

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-01-06 20:17 UTC, jlf0dev requested changes
Everything looks good, I just need help with a small change I missed 😄

2023-01-06 20:17 UTC, jlf0dev commented on apps/web/src/app/organizations/vault/vault-items.component.ts
>      if (item instanceof TreeNode && item.node.name == "Unassigned") {
Can you do me a favor and change this to check for a `null` node id instead of checking if the name is "Unassigned"? I must have missed this before.

2023-01-11 00:00 UTC, shane-melton commented on apps/web/src/app/organizations/vault/vault-items.component.ts
>      if (item instanceof TreeNode && item.node.name == "Unassigned") {
Oh, missed this comment, fixed; thanks for pointing that out!

2023-01-12 17:45 UTC, jlf0dev approved these changes

2023-01-12 18:48 UTC, merged