Fix encrypted export using fixed PBKDF2 iterations
bitwarden/clients pull request #4479
Opened 2023-01-15 12:58 UTC by quexten

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
The encrypted export format contains fields for the KDF type and iteration count, but it was only statically set to PBKDF2 and 100.000 iterations. As a user I would expect it to follow my vault's KDF settings, should I choose to configure them with higher iteration counts/other kdf functions. This pull request changes the export and import to remove the hardcording, such that they work with different iteration counts and different KDF types.

## Code changes
We just inject the stateservice into the export service to get the KDF type and iterations, and write them into the exported json/use them to encrypt.

2023-02-15 07:24 UTC, quexten commented
Just noting: This needs some modifications as it was written before argon2 support and thus does not yet consider the extra fields.

2023-03-27 03:10 UTC, quexten commented
Since this branch was from before argon2 support, I had to re-base it and change change it to support argon2. Should be good to go now.

2023-03-28 14:43 UTC, djsmith85 requested changes
@quexten Thanks again for your great work around adding argon2-support.

Changes are looking good and are functional. Just some minor things to clean this up and then I'll pass it on to QA.

2023-03-28 14:43 UTC, djsmith85 commented on libs/common/src/services/export.service.ts
> +      kdfParallelism: kdfConfig.parallelism,
As we are grabbing the KdfType and KdfConfig [above](https://github.com/bitwarden/clients/pull/4479/files#diff-87f65ffd577624941b6e5784ff1d324a525e879381eaf512ca7d2afa97fcb1b1R63-R64), we shouldn't need to grab them again from stateService. Could you please move them into a local variable.

2023-03-28 14:43 UTC, djsmith85 commented on libs/common/src/services/export.service.ts
>      const jsonDoc: any = {
The BitwardenPasswordProtectedImporter has a [type](https://github.com/bitwarden/clients/pull/4479/files#diff-d7515d7978950b63d009c8f639c8b688efc0499bf6eb5fdff44f36845eb396b4L13) defined to describe the input. Could you please extract it and re-use that definition to remove the `any`.

2023-03-28 19:40 UTC, quexten commented on libs/common/src/services/export.service.ts
>      const jsonDoc: any = {
With the latest commits, I have extracted the `BitwardenPasswordProtectedFileFormat` interface to a dedicated file `bitwarden-password-protected-types.ts`, similar to how it is done in other importers. This is imported and used instead of the any type.

2023-03-28 23:46 UTC, djsmith85 approved these changes, later dismissed
@quexten Changes are looking good. Passing this onto QA for testing.

I just fixed the linting issues by executing `npm run lint:fix` and merged current master into your branch/fork.

2023-03-29 00:07 UTC, djsmith85 approved these changes

2023-03-31 11:49 UTC, djsmith85 commented
@quexten: QA has approved your changes and this is ready to get merged. Thank you again for your contribution and your changes will be included in the next release (2023.4)

2023-03-31 11:49 UTC, merged