Allow dropdown menu to overflow and scroll when needed
bitwarden/clients pull request #4495
Opened 2023-01-17 18:15 UTC by BlackDex

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

When a user is a member of a lot of organizations and has a small screen device (or rotated 90 degrees) and want's to select an organization or maybe even add a new organization, that isn't possible because those links in the menu are not visible because they overflow the screen.

## Code changes

This PR simply adds the `tw-overflow-x-auto` class to the menu `div` and will automatically add a scrollbar when needed.

- **libs/components/src/menu/menu.component.html:** adds the `tw-overflow-x-auto` class to the menu `div` to allow auto overflow to add a scrollbar when needed.

## Screenshots

![image](https://user-images.githubusercontent.com/610450/212978163-5c22b1ee-5aa9-4954-8ed9-73f2325c999c.png)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-01-23 18:17 UTC, jtouchstonebw commented
@BlackDex Could you attach a screen recording of the behavior? It is hard to tell from the screenshot what the results will be. TIA!

2023-01-24 13:52 UTC, BlackDex commented
@jtouchstonebw Sure. Here is the result. I have one both with and without the scrolling patch.


| Without scrolling patch |With scrolling patch|
| -------------------------- | -------------------------- |
|![without_scrolling](https://user-images.githubusercontent.com/610450/214311970-6a5a806d-d29e-4da3-9ade-9747f5e250df.gif)|![with_scrolling](https://user-images.githubusercontent.com/610450/214312181-4a7bbbb7-18a6-43c4-9468-3f281a03fd61.gif)|

Hope this is what you wanted.

2023-03-28 18:05 UTC, jtouchstonebw approved these changes

2023-09-29 14:24 UTC, BlackDex commented
@jtouchstonebw Any update on this? Is there more info needed or changes?

2023-09-29 21:21 UTC, willmartian requested changes
Hey @BlackDex! Thanks for this fix and for your patience in hearing back.

2023-09-29 21:21 UTC, willmartian commented on libs/components/src/menu/menu.component.html
> +    class="tw-flex tw-shrink-0 tw-flex-col tw-rounded tw-border tw-border-solid tw-border-secondary-500 tw-bg-background tw-bg-clip-padding tw-py-2 tw-overflow-x-auto"
We probably want to use `tw-overflow-y-auto` instead of `x`. 

(I'm not sure why `x` is even working in this instance.)

2023-11-21 20:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitwarden/clients?pullRequest=4495) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/bitwarden/clients?pullRequest=4495) before we can accept your contribution.<br/>**18** out of **24** committers have signed the CLA.<br/><br/>:white_check_mark: dderpym<br/>:white_check_mark: ttalty<br/>:white_check_mark: KL4RKS<br/>:white_check_mark: pejeio<br/>:white_check_mark: arnabrahman<br/>:white_check_mark: rr-bw<br/>:white_check_mark: jprusik<br/>:white_check_mark: xnick<br/>:white_check_mark: justindbaur<br/>:white_check_mark: cagonzalezcs<br/>:white_check_mark: aj-rosado<br/>:white_check_mark: MGibson1<br/>:white_check_mark: cubemike99<br/>:white_check_mark: kspearrin<br/>:white_check_mark: Jingo88<br/>:white_check_mark: Hinton<br/>:white_check_mark: limisk<br/>:white_check_mark: willmartian<br/>:x: amorask-bitwarden<br/>:x: github-actions[bot]<br/>:x: dani-garcia<br/>:x: JaredSnider-Bitwarden<br/>:x: danielleflinn<br/>:x: trmartin4<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitwarden/clients?pullRequest=4495) it.</sub>

2023-11-21 20:43 UTC, closed without merging

2023-11-21 20:52 UTC, BlackDex commented
Going to close this one in favor of #6941 since trying to merge/rebase/ff the changes didn't go as expected.