[SM-378] Enable SM on a user basis
bitwarden/clients pull request #4497
Opened 2023-01-17 19:32 UTC by Hinton

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-01-27 22:43 UTC, willmartian reviewed
I haven't worked with most of these code areas, but I don't see any obvious errors. 👍 

Could you add a code comment somewhere that distinguishes between `useSecretsManager` and `accessSecretsManager`? Is `useSecretsManager` just if the org in general has access to SM?

2023-01-30 10:21 UTC, Hinton commented
The `use` prefix is commonly used for organization wide feature toggles.

2023-01-30 16:01 UTC, willmartian submitted a review, later dismissed

2023-01-30 16:20 UTC, shane-melton requested changes
I only have one small nit pick about switching over some css classes to their Tailwind counterparts to avoid further mixing both style systems in the same template where possible -- I believe we've got this dialog almost entirely converted over to Tailwind.

Otherwis, this looks good to me!

2023-01-30 16:20 UTC, shane-melton commented on apps/web/src/app/organizations/members/components/member-dialog/member-dialog.component.html
> +            <h3 class="mt-4">
small nit: Can we update some of the classes used in this section to use the `tw-` prefix when possible to avoid mixing in additional non Tailwind classes?

2023-01-30 16:57 UTC, shane-melton approved these changes

2023-01-30 19:46 UTC, willmartian submitted a review, later dismissed

2023-01-31 17:54 UTC, willmartian approved these changes

2023-01-31 18:03 UTC, merged