[BEEEP] Implement clipboard logic in rust
bitwarden/clients pull request #4516
Opened 2023-01-19 21:27 UTC by Hinton

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Experiments with using rust to manage the clipboard on electron. Which allows for better integration with native OSes features.

## Code changes

- **file.ext:** Description of what was changed and why

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-09-27 14:35 UTC, dani-garcia approved these changes

2023-09-28 13:01 UTC, MGibson1 requested changes
Just the one main concern

2023-09-28 14:40 UTC, Hinton commented on apps/desktop/desktop_native/src/biometric/windows.rs
I think this was changed in a rust upgrade.

2023-09-28 15:15 UTC, MGibson1 submitted a review, later dismissed

2023-09-28 15:15 UTC, MGibson1 commented on apps/desktop/desktop_native/src/biometric/windows.rs
hopefully

2023-10-02 16:46 UTC, MGibson1 approved these changes

2023-10-02 16:50 UTC, merged