[PS-1823] Allowing diacritics on email domain
bitwarden/clients pull request #4561
Opened 2023-01-25 12:32 UTC by aj-rosado

## Type of change
```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Allowing emails with diacritics on domain characters, making it consistent with server and mobile.
Some browsers are automatically converting emails to punycode, reverting it back to unicode

## Code changes
- **Utils.ts:** Added a new error case to the pattern type, if the regex is the one we use to validate the emails, return the email error message
- **Other files:** Replaced Validators.Email, that doesn't allow diacritics, by the regex pattern we use on server side. Added Punycode library to ensure that email is in unicode format.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-01-30 19:32 UTC, MGibson1 requested changes

2023-01-30 19:32 UTC, MGibson1 commented on apps/browser/src/popup/accounts/home.component.ts
> +// eslint-disable-next-line
Please specify the rule to disable and give a reason

```typescript
// punycode needs to be required here to override built-in node module
// https://github.com/mathiasbynens/punycode.js#installation
// eslint-disable-next-line @typescript-eslint/no-var-requires
const punycode = require("punycode/");
```

2023-01-30 19:32 UTC, MGibson1 commented on apps/desktop/src/app/accounts/login.component.ts
> +// eslint-disable-next-line
Please specify the rule to disable and give a reason

2023-01-30 19:32 UTC, MGibson1 commented on apps/web/src/app/accounts/trial-initiation/billing.component.ts
> +// eslint-disable-next-line
Please specify the rule to disable and give a reason

2023-01-30 19:32 UTC, MGibson1 commented on apps/web/src/app/settings/organization-plans.component.ts
> +// eslint-disable-next-line
Please specify the rule to disable and give a reason

2023-01-30 19:32 UTC, MGibson1 commented on libs/angular/src/components/login.component.ts
> +// eslint-disable-next-line
Please specify the rule to disable and give a reason

2023-01-30 19:32 UTC, MGibson1 commented on libs/angular/src/components/register.component.ts
> +// eslint-disable-next-line
Please specify the rule to disable and give a reason

2023-01-30 19:32 UTC, MGibson1 commented on libs/common/src/misc/utils.ts
> +  static regexpEmail = /^[\x00-\x7F]+@.+\.\p{L}+$/u;
This is likely not enough of a regex. In server we benefit by using .NET to parse our email addresses first and apply _it's_ validation prior to doing our extended validation copied here. What's more is that a match on this regex is a _failure_.

Here is [Angular's current regex for emails](https://github.com/angular/angular/blob/4dcbb6aef9ec6d1f1fe9a926d0b40c72139a013b/packages/forms/src/validators.ts#L127), though it would be nice to continue using their validator or reference this regex directly

I take it you made this change because the validator was being processed prior to un-punycoding the email, correct?

2023-01-30 19:32 UTC, MGibson1 commented on libs/components/src/form-field/error.component.ts
> +        return this.error;
Why does this case in particular need special custom error message handling?

2023-01-31 11:03 UTC, aj-rosado commented on libs/components/src/form-field/error.component.ts
> +        return this.error;
Pattern error were falling under the default case. I'm keeping the same behaviour for other pattern errors that are not related to our email validation

2023-01-31 11:07 UTC, aj-rosado commented on libs/common/src/misc/utils.ts
> +  static regexpEmail = /^[\x00-\x7F]+@.+\.\p{L}+$/u;
Angular regex doesn't accept accented characters. Although, I agree we should have a stronger regex server side. I will try find a similar version of the angular one accepting diacritics

2023-01-31 19:01 UTC, MGibson1 commented on libs/components/src/form-field/error.component.ts
> +        return this.error;
Gotcha.

Two options I see, then
1. extract the default handling to a helper and call it in both locations
2. make a custom validator for emails rather than relying on the built in pattern matcher that's used all over.

What do you think?

2023-01-31 19:06 UTC, aj-rosado commented on libs/components/src/form-field/error.component.ts
> +        return this.error;
Just committed a change with 2.

2023-02-01 20:59 UTC, MGibson1 requested changes
quick move request

2023-02-01 20:59 UTC, MGibson1 commented on libs/common/src/misc/utils.ts
> +  }
Can we move this validator to our angular lib validators?

I don't love importing angular here.

2023-02-08 19:16 UTC, MGibson1 requested changes

2023-02-09 09:40 UTC, Hinton commented on apps/browser/src/popup/accounts/home.component.ts
> +// eslint-disable-next-line
Have we verified you can't simply use import punycode? Webpack 5 which we use no longer bundles built in node modules.

2023-02-09 09:46 UTC, Hinton commented on libs/angular/src/validators/emailAllowingDiacritics.validator.ts
> +  return Utils.regexpEmail.test(punycode.toUnicode(control.value)) ? null : { email: true };
That seems awful ... would have been nice if angular just provided a method to run the validation directly on values.

2023-02-09 11:59 UTC, aj-rosado commented on apps/browser/src/popup/accounts/home.component.ts
> +// eslint-disable-next-line
It is deprecated on node

https://nodejs.org/api/punycode.html#punycode_punycode

I've tried using the suggested change [url.domainToASCII](https://nodejs.org/api/url.html#urldomaintoasciidomain) and [url.domainToUnicode](https://nodejs.org/api/url.html#urldomaintounicodedomain) but with no success

2023-02-09 12:40 UTC, Hinton commented on apps/browser/src/popup/accounts/home.component.ts
> +// eslint-disable-next-line
I know it's deprecated in node.js. But this isn't node, this is a web browser which gets bundled using webpack. While webpack has previously bundled compatible builds of some built in modules, they stopped doing so in version 5. If you try to import `punycode` using es6 import, it will resolve to the node module.

The type definitions still points to node however which marks this as deprecated.

```ts
import * as punycode from "punycode";
```

2023-02-13 22:49 UTC, trmartin4 commented
`CODEOWNERS` doing its job here, I think.  We actually had [SG-824](https://bitwarden.atlassian.net/browse/SG-824) for a very similar problem, with the outcome of the spike being implemented by the Auth team.

2023-02-14 18:54 UTC, MGibson1 commented on libs/angular/src/validators/emailAllowingDiacritics.validator.ts
> +  return Utils.regexpEmail.test(punycode.toUnicode(control.value)) ? null : { email: true };
The regex here is worse imo, but I'm ok being overturned.

2023-02-14 19:27 UTC, MGibson1 commented on libs/angular/src/validators/email-allow-diacritics.validator.ts
> +    /^(?=.{1,254}$)(?=.{1,64}@)[a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+)*@[\p{L}.!#$%&'*+/=?^_`{|}~-](?:[\p{L}.!#$%&'*+/=?^_`{|}~-]{0,61})?\.(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0
going to have to break this down to discuss, which is why I'm not thrilled about owning the regex.

The matching group immediately following the `@` (`[\p{L}.!#$%&'*+/=?^_`{|}~-]`), why is the `.` added relative to angular. I'm fairly certain at least that the first letter of a domain can't be `.`

I think that's the only remarkable difference, but it's hard to tell.

2023-02-15 12:07 UTC, aj-rosado commented on libs/angular/src/validators/email-allow-diacritics.validator.ts
> +    /^(?=.{1,254}$)(?=.{1,64}@)[a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+)*@[\p{L}.!#$%&'*+/=?^_`{|}~-](?:[\p{L}.!#$%&'*+/=?^_`{|}~-]{0,61})?\.(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0
You're right and it is not valid server side so shouldn't be valid on clients.

I think we might not get other alternative than own the regex, if we want to make mobile and clients consistent. Right now mobile gives much more freedom on the email validation and this is causing some users that register on mobile not being able to login on clients. 

I've tried to make this regex to be as restrictive as server. I guess server should be the most restrictive one, to not cause the issue of having users that can login on one platform and can't on the other.

2023-02-24 14:04 UTC, closed without merging

2023-02-24 14:06 UTC, aj-rosado commented
Team will proceed with a different solution.