Add autofill field comments
bitwarden/clients pull request #4568
Opened 2023-01-25 21:32 UTC by trmartin4

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-01-31 05:21 UTC, eliykat requested changes
Amazing work @trmartin4! Thank you for sharing what you've figured out.

2023-01-31 05:21 UTC, eliykat commented on apps/browser/src/content/autofill.js
> +       * Clean up the string `s` to non-printable characters and trim it.
```suggestion
       * Clean up the string `s` to remove non-printable characters and whitespace.
```

(I assume)

2023-01-31 05:21 UTC, eliykat commented on apps/browser/src/content/autofill.js
> +       * Determine if the element is "viewable" on the screen
I'd love it if you could clarify what "visible" vs. "viewable" means between these two functions. I've come across it before but never looked into it deeply.

2023-01-31 05:21 UTC, eliykat commented on apps/browser/src/content/autofill.js
> +       * Do a fill by query operation
```suggestion
       * Find all elements matching `query` and fill them using the value `op` from the fill script
```

2023-02-05 22:57 UTC, trmartin4 commented on apps/browser/src/content/autofill.js
> +       * Determine if the element is "viewable" on the screen
I've added some more detailed documentation.  Let me know what you think.  It required quite a bit of testing to try to understand what it's doing, but I think I've got a pretty good idea and was able to convey that in the comments.

2023-02-07 03:25 UTC, eliykat requested changes

2023-02-07 03:25 UTC, eliykat commented on apps/browser/src/autofill/content/autofill.js
> +          // Store the element we're checking
This comment is unnecessary

2023-02-07 03:25 UTC, eliykat commented on apps/browser/src/autofill/content/autofill.js
>                }
I appreciate that you've gone deeper on this, but the risk here is that you've started changing code which is very difficult to understand, difficult to test, and not covered by any unit or automated testing. While your changes are much more readable, I don't think this is worth it for the scope of this PR. I recommend restoring the previous code and just having a shorter/more general comment.

2023-02-09 23:42 UTC, trmartin4 commented on apps/browser/src/autofill/content/autofill.js
>                }
I've removed any changes to the code and just combined the comments into one block at the top.

2023-02-10 00:55 UTC, eliykat approved these changes
Nice work!

2023-02-10 14:51 UTC, merged