Kdf Configuration Options for Argon2
bitwarden/clients pull request #4578
Opened 2023-01-26 14:42 UTC by quexten

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Implement the extra parameters required for argon2 configuration.

## Code changes

- Introduce new KDFConfiguration object (encapsulates iterations, memory, parallelism)
- Replace all references to kdfiterations with kdfConfig
- change-kdf.component.html, change-kdf.component.ts: Introduce extra UI for configuration

## Screenshots

See https://github.com/bitwarden/clients/pull/4468

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-01-26 14:43 UTC, quexten commented
Not yet applied are the changes suggested by the Bitwarden design team in #4468

2023-01-26 15:07 UTC, quexten commented
Reposting feedback from Design team here as reference:

              Feedback from Bitwarden Design:

- Update the form so that there is not a large gap on the left side when Argon2id is selected
- Use sentence case on field labels
- Helper text: "Higher Argon 2 iterations, memory, and parallelism..." (update order to match field order and use the oxford comma)
- In Callout, update sentence to "...WebAssembly, you cannot change your KDF algorithm to Argon2." Remove the “}” that is appearing at the end of the callout’s text in the previously posted screenshot
- If after submit we know the submission failed from lack of WebAssembly support, show an error toast notification with the following: "Browser does not support WebAssembly. Try again with a different browser"
- Update the PBKDF2 encryption text based warning to use the warning callout. This provider better UI consistency between the 2 encryption options. 

![image](https://user-images.githubusercontent.com/43477473/214447233-8ff9fe84-a68c-4832-9b4c-3d845a19da4f.png)

_Originally posted by @danielleflinn in https://github.com/bitwarden/clients/issues/4468#issuecomment-1402843848_

2023-01-26 15:09 UTC, quexten commented
> Reposting feedback from Design team here as reference:
> 
> ```
>           Feedback from Bitwarden Design:
> ```
> 
>     * Update the form so that there is not a large gap on the left side when Argon2id is selected
> 
>     * Use sentence case on field labels
> 
>     * Helper text: "Higher Argon 2 iterations, memory, and parallelism..." (update order to match field order and use the oxford comma)
> 
>     * In Callout, update sentence to "...WebAssembly, you cannot change your KDF algorithm to Argon2." Remove the “}” that is appearing at the end of the callout’s text in the previously posted screenshot
> 
>     * If after submit we know the submission failed from lack of WebAssembly support, show an error toast notification with the following: "Browser does not support WebAssembly. Try again with a different browser"
> 
>     * Update the PBKDF2 encryption text based warning to use the warning callout. This provider better UI consistency between the 2 encryption options.
> 
> 
> ![image](https://user-images.githubusercontent.com/43477473/214447233-8ff9fe84-a68c-4832-9b4c-3d845a19da4f.png)
> 
> _Originally posted by @danielleflinn in [#4468 (comment)](https://github.com/bitwarden/clients/pull/4468#issuecomment-1402843848)_

Applied some of the feedback, regarding warning consistency, title case and the layout of the fields. New screenshots:

![screenshot](https://user-images.githubusercontent.com/11866552/214871787-4b0d7a77-f137-415f-8a30-f6233c421c68.png)
![screenshot1](https://user-images.githubusercontent.com/11866552/214871791-8bd3ae8b-6ae2-4eca-8e3e-7f38727d44c3.png)

2023-01-26 15:18 UTC, quexten commented
Ok, further swapped field order and added oxford comma now. 
![screenshot](https://user-images.githubusercontent.com/11866552/214874058-097059a8-c01a-47d9-946c-14900e20adcd.png)

I believe the feedback has now all been applied.

2023-01-26 15:29 UTC, quexten commented
By the way about the defaults: OWASP recommends 19MiB as a **minimum for authentication**. Since  larger parameter choices for argon2 still run very fast (much faster than 600k rounds of PBKDF2 for example), we could go above OWASP's minimum recommendation, as long as we ensure it will run acceptable for all users. This will ensure fewer need in the future for upgrading defaults / existing accounts.

RFC9106 for example states much higher recommendations:
![screenshot](https://user-images.githubusercontent.com/11866552/214875751-c3aba8fa-237f-43c3-a607-363857c8c88a.png)

So as a uniformly safe option we could go with iterations=3, memory=64(MiB) and parallelism=4
On my system it runs in ~350ms

2023-01-26 15:54 UTC, quexten commented
Ah, sure I agree this is not something that transfers to other systems. My point is that OWASP's 19MiB are conservative when it comes to encrypting something as juicy as a password manager ;)


Specs:
Runtime: Firefox 109
CPU: Intel Core i7-1185G7 (laptop)
Library is the same argon2-browser implementation we use in this PR, in the non-SIMD compiled version, tested here: https://antelle.net/argon2-browser/

2023-01-26 16:12 UTC, quexten commented
As grb writes on the community forums:
> OWASP recommendations are apparently cribbed from Steve Thomas, who explains the rationale for his recommendations in the Info section at the bottom of his [Minimum Password Settings](https://tobtu.com/minimum-password-settings/) page. The settings are designed to throttle an attacker’s hash speeds to 10kH/s/GPU. Of note is that this is the recommendation when using passwords for authentication purposes only. As I’ve noted in [another post](https://community.bitwarden.com/t/increasing-the-default-number-of-pbkdf2-for-existing-accounts/49550/15), when the password is used for encryption, hash rates should ideally be much slower (<1kH/s/GPU).

2023-01-26 16:17 UTC, danielleflinn commented on apps/web/src/locales/en/messages.json
> +    "message": "Higher Argon2 memory, iterations, and parallelism can help protect your master password from being brute forced by an attacker."
Should this also follow the field order: "iterations, memory, and parallelism"?

2023-01-26 16:18 UTC, quexten commented on apps/web/src/locales/en/messages.json
> +    "message": "Higher Argon2 memory, iterations, and parallelism can help protect your master password from being brute forced by an attacker."
Nice find! I'll fix this.

2023-01-26 16:18 UTC, danielleflinn commented on apps/web/src/locales/en/messages.json
> +    "message": "Setting your iterations, memory, and parralellism too high could result in poor performance when logging in. We recommend changing these individually in small increments and then test
Typo? Should be "parrallelism"

2023-01-26 16:21 UTC, quexten commented on apps/web/src/locales/en/messages.json
> +    "message": "Higher Argon2 memory, iterations, and parallelism can help protect your master password from being brute forced by an attacker."
Fixed in 2ccb3f2ddb3af86ef9ff13ab0eabcdc980147f3c

2023-01-26 16:21 UTC, quexten commented on apps/web/src/locales/en/messages.json
> +    "message": "Setting your iterations, memory, and parralellism too high could result in poor performance when logging in. We recommend changing these individually in small increments and then test
Fixed in 2ccb3f2ddb3af86ef9ff13ab0eabcdc980147f3c

2023-01-26 16:24 UTC, danielleflinn commented
Looks good from a Design perspective. Thank you for adding those tweaks.

2023-01-26 16:27 UTC, kspearrin commented
Are you planning to introduce this KdfConfig object to the mobile app PR?

2023-01-26 16:41 UTC, jabashque commented
Just as a reference, I tried using the same https://antelle.net/argon2-browser/ in Fennec F-Droid 109.1.1 on a Samsung Galaxy S4, running Android 5.0.1. I specified the same parameters: iterations=3, memory=64(MiB) and parallelism=4. Using Argon2id and the "Run WebAssembly" option (no webworker or SIMD), it takes 4-5 seconds to complete.

I'd imagine it would run faster natively, but even so, 4-5 seconds on an old device is probably still acceptable for something like a password manager.

2023-01-27 14:09 UTC, Audionut commented
Same settings is ~800ms on a Samsung Galaxy S21U Exynos here. Considering this is likely to be an optional parameter......

Parallelism option makes no difference here, on any device or browser.

2023-01-27 18:23 UTC, kspearrin submitted a review, later dismissed

2023-01-27 19:11 UTC, quexten commented
> By the way about the defaults: OWASP recommends 19MiB as a **minimum for authentication**. Since larger parameter choices for argon2 still run very fast (much faster than 600k rounds of PBKDF2 for example), we could go above OWASP's minimum recommendation, as long as we ensure it will run acceptable for all users. This will ensure fewer need in the future for upgrading defaults / existing accounts.
> 
> RFC9106 for example states much higher recommendations: ![screenshot](https://user-images.githubusercontent.com/11866552/214875751-c3aba8fa-237f-43c3-a607-363857c8c88a.png)
> 
> So as a uniformly safe option we could go with iterations=3, memory=64(MiB) and parallelism=4 On my system it runs in ~350ms



> As grb writes on the community forums:
> 
> > OWASP recommendations are apparently cribbed from Steve Thomas, who explains the rationale for his recommendations in the Info section at the bottom of his [Minimum Password Settings](https://tobtu.com/minimum-password-settings/) page. The settings are designed to throttle an attacker’s hash speeds to 10kH/s/GPU. Of note is that this is the recommendation when using passwords for authentication purposes only. As I’ve noted in [another post](https://community.bitwarden.com/t/increasing-the-default-number-of-pbkdf2-for-existing-accounts/49550/15), when the password is used for encryption, hash rates should ideally be much slower (<1kH/s/GPU).

@kspearrin  What do you think about going with higher defaults for argon2 such as iterations=3, memory=64(MiB), parallelism=4, compared to OWASP's minimums due to the comments above?

2023-01-27 23:27 UTC, kspearrin commented
@quexten I am ok with that, since it is called out in the RFC. We should still leave the validation to allow lower limits for devices that might have issues with such default values.

2023-01-27 23:29 UTC, kspearrin commented on libs/common/src/services/crypto.service.ts
>          salt,
I think we may need to hash the salt here. sha256 should do. Argon2 needs at least 8 bytes of salt data or it will error. So an email of something like a@b.co would cause a problem.

2023-01-28 00:43 UTC, quexten commented on libs/common/src/services/crypto.service.ts
>          salt,
Yeah, need to change that in the mobile PR too then.

2023-01-28 01:20 UTC, quexten commented on libs/common/src/services/crypto.service.ts
>          salt,
Changed in ce7eaad1a07d02fe722f9193b5cefd3490e19adc

2023-01-28 01:20 UTC, quexten commented
> @quexten I am ok with that, since it is called out in the RFC. We should still leave the validation to allow lower limits for devices that might have issues with such default values.

Updated to the RFC's values in [a79f2f6](https://github.com/bitwarden/clients/pull/4578/commits/a79f2f62dce7a4c5928488806d6401478c8995c8)

2023-01-28 01:22 UTC, kspearrin requested changes

2023-01-28 01:22 UTC, kspearrin commented on libs/common/src/services/crypto.service.ts
> +      const saltHash = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(salt));
Please use the cryptoPrimitiveService.hash function

2023-01-28 01:38 UTC, quexten commented on libs/common/src/services/crypto.service.ts
> +      const saltHash = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(salt));
Fixed in [c4033ee](https://github.com/bitwarden/clients/pull/4578/commits/c4033ee4d337b2a2d49d9d6c592cd112e0c575ad)

2023-01-28 01:43 UTC, kspearrin submitted a review, later dismissed

2023-01-29 22:10 UTC, jabashque commented
Would it be possible to raise the minimum memory value from 16 MiB to maybe 32 MiB or 48 MiB? I do understand the need to accommodate old devices like my Galaxy S4, where 64 MiB with 3 iterations takes 4-5 seconds to compute a hash with argon2-browser wasm. However, dropping it down to 48 MiB brings it down to 3-4 seconds, which I feel may be usable enough.

Also, I know that the phones would be using a native argon2 library instead, which would run much faster. I use these old phones as a reference for people who may have very old x86_64 desktops/laptops or slow ARM Chromebooks. They will be using the browser extension quite a lot, and argon2-browser would be needed there.

That being said, my quest to find an x86_64 computer that runs argon2-browser slower than my Galaxy S4 is still ongoing. Even my ThinkPad T400 with an Intel Core 2 Duo P8400 takes 1.5 seconds at worst for  iterations=3, memory=64(MiB) and parallelism=4. I'm charging up an old AT&T Samsung Galaxy S3 now to try and benchmark that...

2023-01-30 12:57 UTC, kspearrin commented
The defaults are now 64mb, 3 iterations, 4 parallelism. I don't see any harm in letting people to set lower memory values that are still considered acceptable if they choose to lower them to accommodate older/slower devices.

2023-01-30 13:13 UTC, kspearrin approved these changes

2023-01-30 13:33 UTC, jabashque commented
I suppose my question is whether we should allow users to set the amount of memory used to as low as 16 MiB, since there's more at stake here. As others mentioned earlier in the thread, OWASP's recommendation was based off what Sc00bz posted, and Sc00bz [clarified](https://infosec.exchange/@sc00bz/109599362314030488) that those recommendations were made with _authentication_ in mind, not _encryption_. After all, that explanation was why Bitwarden's defaults got bumped up to 64 MiB.

Since Bitwarden is targeting more than just power users as an audience, there is inevitably going to be someone who knows just enough to be dangerous, i.e. knows enough to lower the Argon2id settings to the lowest possible to speed up key stretching, but doesn't know enough to actually realize the risks that that brings. Lowering how much one could shoot oneself in the foot by preventing the user from setting such low values would probably be in the best interest of the users. 

If you do want to play it safe still, 32 MiB as a minimum is still fine, from my experience. It is still going to be somewhat too low for something like encryption, but it's still better than letting the user lower it down to 16 MiB, and it still allows for more tolerable login times if they happen to be using a device that's that weak in the first place. On my Galaxy S3 (argon2-browser), with t=3,p=4,m=32768(KiB), it takes 3-4 seconds. I have yet to encounter another device in the wild that's slower than my Galaxy S3 so far, and if I do, there's a high chance that it won't be practical for daily tasks without being frustratingly laggy.

2023-01-30 13:53 UTC, quexten commented
> I suppose my question is whether we should allow users to set the amount of memory used to as low as 16 MiB, since there's more at stake here. As others mentioned earlier in the thread, OWASP's recommendation was based off what Sc00bz posted, and Sc00bz [clarified](https://infosec.exchange/@sc00bz/109599362314030488) that those recommendations were made with _authentication_ in mind, not _encryption_. After all, that explanation was why Bitwarden's defaults got bumped up to 64 MiB.
> 
> Since Bitwarden is targeting more than just power users as an audience, there is inevitably going to be someone who knows just enough to be dangerous, i.e. knows enough to lower the Argon2id settings to the lowest possible to speed up key stretching, but doesn't know enough to actually realize the risks that that brings. Lowering how much one could shoot oneself in the foot by preventing the user from setting such low values would probably be in the best interest of the users.
> 
> If you do want to play it safe still, 32 MiB as a minimum might be all right, from my experience. It is still going to be somewhat too low for something like encryption, but it's still better than letting the user lower it down to 16 MiB, and it still allows for more tolerable login times if they happen to be using a device that's that weak in the first place. On my Galaxy S3 (argon2-browser), with t=3,p=4,m=32768(KiB), it takes 3-4 seconds. I have yet to encounter another device in the wild that's slower than my Galaxy S3 so far, and if I do, there's a high chance that it won't be practical for daily tasks without being frustratingly laggy.
> 
> I still need to look around harder to see if there's any pitfalls with using Argon2id with 2 iterations instead of 3, but I suppose keeping the minimum allowed iteration value as 2 would be fine for now, especially since it would also help with lowering the key derivation time if the user needs it.

**16MiB, 2 iterations, 1 parallelism is still not easy to crack / insecure.**
The parameters don't exactly fit but for 16M, 32 iterations, 1 parallelism on a  RX 5700 GPU argon2-gpu-bench on [opencl gets ~13 hashes per second](https://crypto.stackexchange.com/questions/90036/why-does-the-gpu-get-a-comparatively-bigger-advantage-to-the-cpu-when-using-high). Extrapolating form the iterations it should be ~200 hashes per second for 16M, 2 iterations, 1 parallelism. This is very slow for brute-force cracking.

2023-01-30 14:06 UTC, jabashque commented
> 16MiB, 2 iterations, 1 parallelism is still not easy to crack / insecure. The parameters don't exactly fit but for 16M, 32 iterations, 1 parallelism on a RX 5700 GPU argon2-gpu-bench on [opencl gets ~13 hashes per second](https://crypto.stackexchange.com/questions/90036/why-does-the-gpu-get-a-comparatively-bigger-advantage-to-the-cpu-when-using-high). Extrapolating form the iterations it should be ~200 hashes per second for 16M, 2 iterations, 1 parallelism. This is very slow for brute-force cracking.
> 
> When it comes to resistance against brute-force cracking, PBKDF2 is a much more "dangerous" choice for a user compared to the minimum argon2 values. (And of course a user always has the option to pick an insecure master password, in which case no KDF settings will help).

Understandable; I guess at the end, me arguing for higher minimum values for the argon2 parameters is rather shortsighted when there's other, larger user footguns available, like if the user doesn't switch from PBKDF2 to Argon2id in the first place.

2023-01-30 14:07 UTC, merged