Unix biometrics unlock via PAM
bitwarden/clients pull request #4586
Opened 2023-01-27 15:13 UTC by quexten

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
This adds biometrics support on Linux (Unix) via PAM. I tested it to work with fprintd configured. Howdy (face unlock) *should* also work but I have not tested it. Further, there is no gui with the default fprintd. This can be done in the PAM service (using fingerprint-gui for example).

Still missing is a default PAM service file. Can we expect a Linux user to configure this themselves as long as we document it?
Sample policy for fprintd:

```
# /etc/pam.d/bitwarden
#
# PAM configuration file for the bitwarden biometrics
#
auth sufficient pam_fprintd.so
```

## Code changes

- Cargo.toml: Add pam-client and whoami libraries
- settings.component.ts: Remove unavailability message for Unix
- messages.json: Add PAM i18n texts
- main.ts: Add loading of unix PAM biometrics service
- biometric.unix.main.ts: Implement biometrics service (Mostly based on the windows counterpart since that also calls rust)
- unix.rs: Implement calls to PAM for authentication

2023-01-27 16:11 UTC, quexten commented
Ok there seems to be an issue still with accounts that do not have biometrics enabled. On my first test account it works great, on my other 2 test accounts it does not work. Need to triage this.

2023-01-27 16:27 UTC, quexten commented
> Ok there seems to be an issue still with accounts that do not have biometrics enabled. On my first test account it works great, on my other 2 test accounts it does not work. Need to triage this.

Actually nevermind, it works just fine. The problem was that due to the lack of UI feedback with just fprintd, I didn't realize I had to authenticate my fingerprint to enable the setting.

2023-01-29 11:32 UTC, quexten commented
Hmm, we could also use polkit instead of PAM directly. This would then be system level authentication, instead of biometrics directly. If the user has biometrics configured, that will be used, if not it will prompt for system password. Also this has native GUIs on most desktop environments so it would be a more integrated experience.

2023-01-29 20:47 UTC, quexten commented
> Hmm, we could also use polkit instead of PAM directly. This would then be system level authentication, instead of biometrics directly. If the user has biometrics configured, that will be used, if not it will prompt for system password. Also this has native GUIs on most desktop environments so it would be a more integrated experience.

Yeah I tested with kde polkit agent and gnome polkit agent and they provide a better experience. Will have to update this PR to use polkit.

2023-01-30 01:49 UTC, quexten commented
![screenshot](https://user-images.githubusercontent.com/11866552/215370997-bd8ae762-335c-4124-9d15-a4459ed8f113.png)

Implemented polkit instead of pam, this is what it looks like with KDE's polkit agent.

2023-01-30 02:12 UTC, quexten commented
```
cat /usr/share/polkit-1/actions/com.bitwarden.Bitwarden.policy  
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE policyconfig PUBLIC
 "-//freedesktop//DTD PolicyKit Policy Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/PolicyKit/1.0/policyconfig.dtd">

<policyconfig>
    <action id="com.bitwarden.Bitwarden.unlock">
      <description>Unlock Bitwarden</description>
      <message>Authenticate to unlock Bitwarden</message>
      <defaults>
        <allow_any>auth_self</allow_any>
        <allow_inactive>auth_self</allow_inactive>
        <allow_active>auth_self</allow_active>
      </defaults>
    </action>
</policyconfig>
```
This is the polkit policy that needs to be installed for it to work. I'm not entirely sure how to best do this with electron builder, didn't find a build-in function for this. Maybe someone from the team can share some insight?

On some platforms we could use the afterInstall options / afterRemove options, and on the others just disable it and document for the user to set up this polkit policy themselves if they want this feature to work?

2023-02-01 00:13 UTC, quexten commented
One note: Biometrics for browser extensions will not work if:
- The browser is installed as snap or flatpak.
- The Bitwarden Desktop app is installed as snap or flatpak

This is unrelated to this pull request, but due to how native messaging works, and how flatpak/snap sandbox applications. There is an open pull request for xdg-desktop-portal support which might fix this:
https://github.com/flatpak/xdg-desktop-portal/pull/705

Aside from that, I tested AppImage to correctly work with the desktop application, and I expect the same to be the case for the other formats which don't have special sandboxing.

2023-03-22 05:28 UTC, tchellomello commented
Any plans on getting this merged?

2023-03-22 06:10 UTC, jonajia commented
+1

2023-03-31 21:58 UTC, quexten commented
Well, from my side this is mostly good to go.

The only thing missing is a way to get the Polkit policy installed. I looked at [electron builder's options](https://www.electron.build/generated/linuxtargetspecificoptions) for this but this will only work on some package formats. The electron builder documentation isn't entirely clear on this (it lists some, but not .deb for example, but then fpm supports .deb again). AppImage won't work at all.

Another option is to install this policy during runtime (when the user first activates biometrics). This would require elevating privileges with polkit, but should not be an issue.

I need input on which approach the Bitwarden team would prefer here.

On another note, since I didn't want to have the desktop app and IPC proxy constantly running in the background, I've re-implemented (a subset of) the protocol in a single go application. Other than that it works in the same way (biometrics with polkit, secret stored in the system's secret service). In case this is also useful to someone following this thread here is the link:
https://github.com/quexten/bw-bio-handler

2023-04-07 12:53 UTC, alba4k commented
Let's hope this gets merged as soon as possible

2023-04-18 17:24 UTC, MGibson1 commented
Thank you for this, @quexten. Please know that I've had literally daily reminders to get information to you as soon as possible once the security work related to [overhauling biometrics was done and merged](https://github.com/bitwarden/clients/pull/5234).

That work changes the API around biometrics pretty significantly. Linux will have similar security model issues that Windows does in that security is entirely user-based. DBus in particular offers difficulties. Any application running as a user has unfettered access to messages -- that's kind of the point. Therefore, we need messages to be encrypted secrets rather than plaintext like there are here.

We can do that in at least one of two ways
1. encryption by a libsecret challenge-derived password
2. encryption by a secret stored in the bitwarden local data

I also don't know of any way to use polkit or libsecret to do an analogous user key signing we're doing for Windows -- do you?

If we can't find a way to do the same kind of challenge signing, we'll have to require an alternate unlock on app start and use the established client-key-half method as a non-optional requirement.

2023-04-18 20:02 UTC, quexten commented
Thank you for the update on this @MGibson1!

> That work changes the API around biometrics pretty significantly. Linux will have similar security model issues that Windows does in that security is entirely user-based. DBus in particular offers difficulties. Any application running as a user has unfettered access to messages -- that's kind of the point. Therefore, we need messages to be encrypted secrets rather than plaintext like there are here.

Yeah I was also concerned about this when writing the PR but did not want to introduce changes in how the secrets are stored/derived in this PR. I had a brief look and very much agree with the changes in your linked merged PR though.

> I also don't know of any way to use polkit or libsecret to do an analogous user key signing we're doing for Windows -- do you?

No, polkit only checks whether a user is allowed to do something, libsecret does not protect against attacks from the user's session. So using them directly in the rust desktop library to do this is not possible as far as I can tell. That being said, I do have a suggestion of how to still implement this behaviour below.

Assuming I understand the requirements correctly, getting a symmetric encryption secret, not accessible by the user session, locked behind biometrics, there are two additional approaches I could think of:

1. There is a security model which is per-application on Linux: The Secret portal allows per application secrets to be retreived for sandboxed apps such as Flatpak (Snap?). Other sandboxed applications cannot access them. Although they are also only separated between sandboxed applications, but not from processes running un-sandboxed under the user. Biometrics would then still just return true/false, but the application can just retrieve it's secret.
This would only apply to very specific Linux distros that make heavy use of Flatpaks, where the threat-model only includes other sandboxed applications. Given that Bitwarden is not even officially distributed as Flatpak, this is probably not the way to go, but it still felt relevant to mention here.

2. The better option in this case, which more closely resembles the new Windows behaviour, is to store the secret in a file inaccessible to the user in the app directory (owned by a new user or only readable by root with `chmod 000`). To access the key, an executable would be invoked, that verifies the user's biometrics via polkit. The binary would have permission to read the secret via capabilities or the suid bit to elevate privileges and read and return the secret. 
This would prevent attacks from the user-session, and provide a secret protected by biometrics, but it would also be another (albeit small) binary to maintain.

Of course the approach you listed of requiring an alternative unlock method (the master password/pin) at least once on startup would also work and be the simpler one implementation wise.

2023-04-19 16:28 UTC, NicolaF commented
Hi all,

Since we're already messing with system config (PAM initially, now polkit), another option could be to do something similar to pam_gnome_keyring.so (it tries to unlock the gnome keyring on login using the user input password)

We could implement something in the same vein to derive an encryption key from the user password and pass it to a daemonized bitwarden service.

This requires that the users opens its Desktop session with password (not biometrics), but this is already an issue with gnome keyring (if you log in with biometrics, you have to manually unlock your keyring with your password afterwards). I personally use pam_fprintd for everything but graphical login (session unlock, console login, sudo,...)

Another solution I would be fine with is to just warn the user that enabling bio unlock will lower the security.

Regards,
Nicolas

2023-04-22 13:48 UTC, jivanpal commented
@MGibson1 

> This is an interesting approach, but I'm unsure about delivery. I'm not familiar enough with our distribution channels to know if we could have this separate executable bundled across all of them.

This would be simple enough for native packages like DEB and RPM, but I don't think it's feasible for sandboxed versions like AppImage and Snap.

Aside: Is there an official Flatpak version of Bitwarden? I see [*com.bitwarden.desktop* on Flathub](https://flathub.org/apps/com.bitwarden.desktop), but I don't see it mentioned on the website at <https://bitwarden.com/download/>.

2023-04-22 19:06 UTC, quexten commented
> I think the guaranteed way forward will be to wire up a non-optional require password on app start and eventually work in ways to expand our linux biometric feature offering as the above ideas develop.

Yeah, agreed.

> If you're more interested in fleshing out the above ideas, totally cool. My point is that I'd also entertain a PR dedicated to just enabling biometric after first unlock on Linux.

I'm OK with just making this PR only enable biometrics after first unlock. Improvements can come in a separate PR. 
I did not yet check what's required to bring this PR up-to-date with the current master though.
Other than that, as mentioned above, only a way to install the polkit policy is missing. 
Currently I'm inclined towards copying with something like `pkexec cat bitwarden.policy ..` during runtime when the user asks to enable biometrics, as this will work with all package formats.

### Some more points on how biometric unlock could work without the additional unlock on boot requirement (for a separate PR):
> Is it possible to enable this kind of functionality by executing sub-processes from the electron main thread as a part of the native messaging library? I'm thinking the effect would be something like running. `sudo -u bitwarden cat ./biometric-signing.crt`

Yeah, that's the idea. Sudo works by being owned by root, and having the suid flag set. Thus the effective user id gets switched to root. In case of "-u bitwarden" sudo would then switch from root to the bitwarden user and execute cat. In this case it could then read the signing cert.

I don't believe we can just use sudo though, since this is missing the biometrics check (unless the user specifically configures pam modules), so we would have to enter the user's password in the app and pass that to sudo. If we wanted to just use existing executables, then  `pkexec --user bitwarden cat ...` would be a more suitable approach as this uses polkit (and thus biometrics, if configured). Furthermore, the user would have to have permission to sudo, which might not be the case on locked down systems.

An issue here would be that the polkit message is unintuitive. Instead of something like "authenticate to unlock bitwarden", it is:
![image](https://user-images.githubusercontent.com/11866552/233800106-d662fe1d-58d9-4441-9c07-2623052ffb57.png)

Compared to using a custom polkit policy (which is used in the current PR):
![image](https://user-images.githubusercontent.com/11866552/233800075-75c1e9db-66af-482a-b1e5-69e9167c0822.png)

Given this, a small binary that is owned by the bitwarden user, and has the suid bit set would be a nicer solution as it doesn't require sudo permissions, and have a nice authentication message. In that case, the native messaging library would call something like: `./biometrics-vault ./biometric-signing`.
And combined with the polkit policy, the polkit message also makes sense.

I have not looked at all of the packaging formats, but given that the node ipc proxy is also a separate process (in appimage this runs under a directory under /tmp f.e), I don't think this should be an issue?


@jivanpal 
> This would be simple enough for native packages like DEB and RPM, but I don't think it's feasible for bundled and sandboxed versions like AppImage and Snap.

I believe you meant Flatpak and Snap, since AppImage isn't really sandboxed. Regardless, even if it doesn't work with them (which I have not verified/tested), we could fall back to unlock with another non-biometric factor on startup in that case.

Also, I'm not sure if Flatpak and Snap will work with biometric authentication at all, since I would expect polkit to be sandboxed away, and I do not see an xdg portal or similar for it. 1Password does no offer biometrics (system authentication) on snap/flatpak f.e. On these systems I would just set biometrics available to false for now, and a separate PR could update that in the future.

> Aside: Is there an official Flatpak version of Bitwarden? I see [com.bitwarden.desktop on Flathub](https://flathub.org/apps/com.bitwarden.desktop), but I don't see it mentioned on the website at https://bitwarden.com/download/.

This is a community provided wrapper. The very bottom of the FlatHub page says:
> This wrapper is not verified by, affiliated with, or supported by 8bit Solutions LLC.

2023-07-04 05:50 UTC, quexten commented
When I force-pushed the re-base of this PR for the reworked desktop biometrics, some automation in GitHub requested a review, but this is not ready for a review so I have converted the PR to a draft for now.

2023-07-04 19:20 UTC, quexten commented
The PR is in a working state again, and even does set-up of the polkit policy now. I think it should be in a state that's good enough for review now, albeit it does not have a biometrics derived key, and thus should require the password/pin on restart.

Since it's been a while since I have worked on this request, and in the meantime a biometrics rework happened, I'll summarize the changes of this PR.

Currently, the PR implements biometric unlock via polkit. For this to work, a polkit policy has to be created in `/usr/share/polkit-1/actions/`. When first enabled in the settings, the desktop client elevates privileges via polkit (pkexec) to write the Bitwarden unlock policy to the directory.

For unlocking, the rust module is invoked, which uses the zbus_polkit crate to authenticate using the polkit policy.

Checking whether system authentication is available, is done by checking whether the polkit policy directory exists. This verifies that polkit is at least installed on the system, and not prevented from access by a sandbox (like when running in snap/flatpak).

**This should be presence only, there is no biometrics-derived key implemented in this PR. Because of this, the default setting is "Require password or PIN on app start".**

I mostly stuck to how the mac service was implemented, and did not look closely at the windows version.

Minor question for debate: I left the messages as "Unlock with Polkit" / "Polkit settings" etc. However, I don't think a regular user would know what Polkit is, so would "Unlock with System Authentication" be better for discoverability?

2023-07-05 04:31 UTC, quexten commented
> Those are all interesting options.
> 
> > The Secret portal allows per application secrets to be retreived for sandboxed apps such as Flatpak (Snap?).
> 
> I like this approach, but, as you point out, it's not sufficient for the same reasons Windows UWP isn't a solution. The threat model is from non-sandboxed applications and since it provides no sandboxing from those applications, it really only provides security for systems which exclusively run Flatpak. I don't know of any that have invested that far.
> 
> > store the secret in a file inaccessible to the user in the app directory
> 
> This is an interesting approach, but I'm unsure about delivery. I'm not familiar enough with our distribution channels to know if we could have this separate executable bundled across all of them. We could rework the download experience to be an installer-type thing...
> 
> Is it possible to enable this kind of functionality by executing sub-processes from the electron main thread as a part of the native messaging library? I'm thinking the effect would be something like running.
> 
> ```shell
> sudo -u bitwarden cat ./biometric-signing.crt
> ```
> 
> Please forgive my ignorance here, this is all pretty exploratory for me.
> 
> > pass it to a daemonized bitwarden service.
> 
> I'd like to avoid a daemonized process if we can. We could enable other great features (like getting rid of session tokens in CLI) that I've thought though in the past, but requiring one is also a barrier to entry that would be good to avoid.
> 
> I think the guaranteed way forward will be to wire up a non-optional `require password on app start` and eventually work in ways to expand our linux biometric feature offering as the above ideas develop.
> 
> If you're more interested in fleshing out the above ideas, totally cool. My point is that I'd also entertain a PR dedicated to just enabling biometric after first unlock on Linux.

By the way, I thought about this a bit more. Instead of having a cert file on the filesystem (dangerous in case full disk encryption is not present), it would be better to leverage the TPM for this (if available). That way, even if the disk contents are leaked (stolen, leaked from a disk backup etc.), it would not aid in cracking the offline vault. But that is out of scope for this PR.

And on this point:
> I think the guaranteed way forward will be to wire up a non-optional `require password on app start` and eventually work in ways to expand our linux biometric feature offering as the above ideas develop.

Right now it is the default require password on app start, but it is possible to turn it off. Should I change the PR to not even give the option for not having to enter the password on app start? (I'm ok with either, though when giving the option the security implications should be made clear).

2023-07-11 21:47 UTC, MGibson1 commented
I have this on my todo list for the week. Thanks for the update!

> Right now it is the default require password on app start, but it is possible to turn it off. Should I change the PR to not even give the option for not having to enter the password on app start? (I'm ok with either, though when giving the option the security implications should be made clear).

Yes, barring your TPM expansion, the split key model is the only way I can see to meet our security requirements.

2023-07-12 12:31 UTC, alba4k commented
Wouldn't it be an option to provide a check to always use polkit without any sort of password, and just provide a warning explaining how unsecure that choice might be?

2023-07-29 23:49 UTC, alba4k commented
that's a loong weekly schedule

2023-08-12 15:09 UTC, quexten commented
> I have this on my todo list for the week. Thanks for the update!
> 
> > Right now it is the default require password on app start, but it is possible to turn it off. Should I change the PR to not even give the option for not having to enter the password on app start? (I'm ok with either, though when giving the option the security implications should be made clear).
> 
> Yes, barring your TPM expansion, the split key model is the only way I can see to meet our security requirements.

Forced the enter password on application start now by removing the UI settings on Linux.

2023-10-06 03:42 UTC, Glass2721 commented
Hey, just wanted to briefly say that this PR is greatly valued with continued interest.

It would be great to hear what bitwarden developers (eg. @MGibson1) think about it's status.

2023-10-25 15:25 UTC, Vcele commented
It's been nearly another month, are there any updates on this? @MGibson1

2023-10-25 15:32 UTC, alba4k commented
@quexten would probably need to update it

2023-10-25 15:38 UTC, quexten commented
> @quexten would probably need to update it

From my perspective it's missing a review from Bitwarden's side. There are no further code changes planned from my side at the moment.

After being reviewed, but before getting merged I will revisit the Polkit policy installation as I have noticed in another project that this requires SElinux related permissions change of the the Polkit file on some distributions.

2023-10-25 15:41 UTC, Vcele commented
Ok that seems appropriate, anyways thanks for your efforts 🙏

2023-11-03 23:23 UTC, Glass2721 commented
I've contacted Bitwarden support with the following questions about this pull request:

> Is bitwarden no longer planning to complete and merge this pull request? (ie. forever abandoning this pull request?)
> 
> When does bitwarden plan to continue reviewing/working on this pull request again?

Bitwarden (support) has fully replied with the following answer [emphasis added]:

> I've spoken to the dev team, and can confirm that while this is still on the radar, the team has not yet been able to get round to it.
> ​
> _The required investigation appears to be quite large, which is proving the root of the problem._
> 
> Please do continue to keep an eye on this - it has not been abandoned.  Thank you for your patience.

Personal Opinion:
Based on the answer I received, I don't believe Bitwarden considers this pull request to be currently important or relevant. Don't hold your breath: It could be **_many years_** until this pull request is completed/merged.

If you need this feature, you should consider other password managers that support linux biometrics (eg. 1Password)

2023-11-03 23:23 UTC, Glass2721 commented
Also, @quexten: If I download a web browser's binaries directly from their website, will biometrics still work with the browser extension?

2023-11-04 06:17 UTC, quexten commented
> Also, @quexten: If I download a web browser's binaries directly from their website, will biometrics still work with the browser extension?

This is not really part of this PR as browser<->desktop communication was already in Bitwarden (even for linux) before this PR. But nevertheless, it *should* work with most chromium or firefox based browsers. For some, it might require you to manually set up the `com.8bit.bitwarden.json` file, as Bitwarden does this for a fixed number of browsers.

Keep in mind that if either the browser or the desktop app are in snap or flatpak format, then it will currently not work, as browser<->native IPC is currently not supported for sandboxed environments.

2023-11-04 12:16 UTC, ebits21 commented
> I've contacted Bitwarden support with the following questions about this pull request:
> 
> 
> 
> > Is bitwarden no longer planning to complete and merge this pull request? (ie. forever abandoning this pull request?)
> 
> > 
> 
> > When does bitwarden plan to continue reviewing/working on this pull request again?
> 
> 
> 
> Bitwarden (support) has fully replied with the following answer [emphasis added]:
> 
> 
> 
> > I've spoken to the dev team, and can confirm that while this is still on the radar, the team has not yet been able to get round to it.
> 
> > ​
> 
> > _The required investigation appears to be quite large, which is proving the root of the problem._
> 
> > 
> 
> > Please do continue to keep an eye on this - it has not been abandoned.  Thank you for your patience.
> 
> 
> 
> Personal Opinion:
> 
> Based on the answer I received, I don't believe Bitwarden considers this pull request to be currently important or relevant. Don't hold your breath: It could be **_many years_** until this pull request is completed/merged.
> 
> 
> 
> If you need this feature, you should consider other password managers that support linux biometrics (eg. 1Password)

Hopefully not, keepassXC just merged support. It would be realllly nice to be able to use my fingerprint reader on Linux and my thinkpad!

2023-12-10 22:24 UTC, alba4k commented
Truely sucks how slow the merging of this pull request is being...

2023-12-26 05:28 UTC, githubuser6000 commented
@quexten, apologies for the unsolicited ping. I saw your repo on goldwarden. Do you have a GitHub sponsors or Patreon link? I'd be more than happy to redirect the subscription I pay to Bitwarden to you instead. I see you way too often on GitHub and the discourse forums adding features, and imho, you deserve every penny. 

I don't even want cloud sync, I can do it myself (as long as there is a way to merge changes properly I guess?). But I'd love to support these features as you bake them fresh outta the oven. I hope someday the funds are enough to get your code through an audit too.

2023-12-28 16:08 UTC, quexten commented
@githubuser6000 Thanks for the kind words! I don't have any Github Sponsors or Patreon, and due to tax reasons, this would be rather complicated to set up for me at the moment.

> I don't even want cloud sync, I can do it myself (as long as there is a way to merge changes properly I guess?). But I'd love to support these features as you bake them fresh outta the oven.

Well, for Goldwarden specifically, "cloud-sync" is provided out of the box. A no-cloud sync (offline) mode is not currently available, but I'm open to feature requests.

> I hope someday the funds are enough to get your code through an audit too.

Given the project's rather small size, this is tough for anything aside from a community-based audit.

Regardless, if you want to discuss further about Goldwarden, please do so on the GitHub project in the discussions in order not to have unrelated discussion on this PR :)

2024-01-24 03:39 UTC, alexandru0-dev commented
@djsmith85 any info about this pr?

2024-01-30 10:48 UTC, quexten commented
FYI investigating to improving the platform APIs related to biometric authentication - especially for Flatpak/Snap, but please don't let that influence the discussion around this PR. It's a more long-term project: https://github.com/flatpak/xdg-desktop-portal/discussions/1275

2024-04-12 15:42 UTC, popy2k14 commented
@MGibson1 or any other bitwarden team member. Please review/merge this!
Missing that so badly on linux.

thx

2024-04-25 22:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitwarden/clients?pullRequest=4586) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/bitwarden/clients?pullRequest=4586) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: quexten<br/>:x: DigitallyRefined<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitwarden/clients?pullRequest=4586) it.</sub>

2024-04-25 22:47 UTC, quexten commented
Sorry about the review ping. @DigitallyRefined brought this PR up to date and submitted that as a PR to my branch (quexten:feature/unix-biometrics), which I merged, so this PR should be up to date again.

2024-05-12 14:55 UTC, popy2k14 commented
@quexten any chance to get an built Debian package for use in Debian/Ubuntu/mint?

Thx

2024-05-12 16:49 UTC, DigitallyRefined commented
> any chance to get an built Debian package for use in Debian/Ubuntu/mint?

I've created a test build (using`.deb`, `.rpm` and `.AppImage` formats) based off this branch with install instructions at:  
https://github.com/DigitallyRefined/clients/releases

I've been using it for a few weeks and I've not encountered any issues (yet!) 👍

2024-05-12 19:49 UTC, popy2k14 commented
> > any chance to get an built Debian package for use in Debian/Ubuntu/mint?
> 
> I've created a test build (using`.deb`, `.rpm` and `.AppImage` formats) based off this branch with install instructions at: https://github.com/DigitallyRefined/clients/releases
> 
> I've been using it for a few weeks and I've not encountered any issues (yet!) 👍

@DigitallyRefined thx for the link/build.
I have installed it and followed the instructions (polkit xml and setting...) but sadly bitwarden could not be unlocked with polkit.
However, howdy is working on login.
Also there are no files created in ~/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts like goldwarden did with it's setup command. Brave is setup correctly to the instructions.

Any hint's?

thx

2024-05-12 20:15 UTC, popy2k14 commented
I have solved it by manually creating the directory `~/.config/google-chrome/NativeMessagingHosts/` start deb install again and copy the file `com.8bit.bitwarden.json` to `~/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts`.

After lokking at the source in the function generateManifest() here: https://github.com/bitwarden/desktop/blob/d7674f5c91cc620fbcb0c48347c78c4cbafff8ab/src/main/nativeMessaging.main.ts#L139
it's exactly like quexten stated, just a few browsers are supported: firefox, chrome and edge.

Unlock bitwarden app with polkit now works and also from browser.

thx a lot for the build!
I really hope bitwarden team is finally merging this!

2024-05-13 05:54 UTC, popy2k14 commented
@DigitallyRefined is it normal that i have to unlock the bitwarden desktop client (your build) first with the master password to get unlocking the browser plugin with biometrics working?
Also the "Unlock with polkit" button in the desktop client just shows up after unlocking with pw one time after boot/login.

is that like it should be?

P.s.: in windows with hello, the unlocking with biometrics just works without unlocking the desktop client first

2024-05-13 06:15 UTC, quexten commented
@popy2k14 
From the clients perspective, polkit only provides authentication/authorization, but no cryptographic keys. Thus, it's not possible to unlock on boot securely, so unlock is disabled intentionally. Thus, the first secret on boot needs to come from the master password. The alternative here would be to implement a TPM based approach, basically re-implementing a part of Windows hello, though this requires a fairly large amount of development effort. 

The other option would be https://github.com/flatpak/xdg-desktop-portal/discussions/1275 and letting the desktop environment handle storage of cryptographic secrets.

2024-05-13 07:04 UTC, popy2k14 commented
@quexten thx for the explanation and that this behaviour is currently intended (because of security).
Coming from windows, this was unclear to me.

2024-05-19 12:19 UTC, savely-krasovsky commented
> Thus, the first secret on boot needs to come from the master password.
@quexten current Bitwarden Windows implementation also recommends to use master-password to unlock it first time.

2024-05-24 07:15 UTC, fxzxmicah commented
> > Thus, the first secret on boot needs to come from the master password.
> 
> @quexten current Bitwarden Windows implementation also recommends to use master-password to unlock it first time.

My master password is also complicated, so it's a nightmare to enter it every time the computer boots.

2024-05-29 16:42 UTC, quexten commented
Brought this up to date, has proper detection of sandboxing with helpful prompts to guide the user to setup steps / automatic setup when possible.

2024-06-13 22:38 UTC, almereyda commented
Would it seem suitable to consider splitting this PR in multiple parts for individual review?

First one part for PolKit support with a blend of BitWarden Linux Desktop Clients?

- https://vault.bitwarden.com/download/?app=desktop&platform=linux AppImage
- https://github.com/flathub/com.bitwarden.desktop Flatpak
- https://snapcraft.io/bitwarden Snap

Then a part with support for a first blend of browser extensions

- Chrome, Firefox
- not (yet) Vivaldi, Opera, Brave, Tor-Browser

And parallely a part for biometrics support?

My intuition here is, that it would allow for an easier review and better feedback cycle, scoped logically by the implementation steps and not mixing the PolKit groundwork with the support for the browser extension and for biometrics.

2024-06-26 19:07 UTC, jlf0dev reviewed
Mostly just questions so I can get a better idea of how this works. Thanks for the patience!

2024-06-26 19:07 UTC, jlf0dev commented on apps/desktop/src/platform/main/biometric/biometric.unix.main.ts
> +  async init() {}
I think you can delete this

2024-06-27 14:12 UTC, quexten commented on apps/desktop/src/platform/main/biometric/biometric.unix.main.ts
> +          process = spawn("pkexec", ["chown", "root:root", policyPath + policyFileName]);
pkexec is like sudo but with polkit integration and a nice UI. So this does run as root. https://linux.die.net/man/1/pkexec

2024-06-27 14:39 UTC, quexten commented on libs/common/src/platform/abstractions/platform-utils.service.ts
> +  abstract biometricsSetup: () => Promise<void>;
Added tsdocs for the functions

2024-06-27 14:40 UTC, quexten commented on apps/desktop/src/platform/main/biometric/biometrics.service.abstraction.ts
Added tsdocs for the functions

2024-06-27 14:46 UTC, quexten commented on apps/desktop/src/platform/main/biometric/biometric.unix.main.ts
> +const policyPath = "/usr/share/polkit-1/actions/";
Well, the directory is owned by root and only root can write to it. That's why we elevate privileges with pkexec. I'm not exactly sure what happens right now, but we should probably inform the user somehow if pkexec fails (most likely if they enter the wrong password, / cancel the polkit prompt).

By the way, from a UX perspective this probably needs cleanup somehow (maybe in a follow up PR, it's not a blocker from my side), since right now this requires 3 authentication prompts (one for writing the file, another for changing the permissions and the last for applying the selinux label).

2024-06-27 14:50 UTC, quexten commented on apps/desktop/src/platform/main/biometric/biometric.unix.main.ts
> +  }
Added.

2024-06-27 15:42 UTC, quexten commented on apps/desktop/src/platform/main/biometric/biometric.unix.main.ts
> +      <message>Authenticate to unlock Bitwarden</message>
We can provide alternative translated descriptions / messages in the polkit policy file, now sure how we would use that with crowdin translations though. I do think there is also a way to dynamically modify the message using the polkit deails object (using the special polkit.messang and polkit.gettext_domain keys), but I'll have to check up on that. That way we could use the regular i18n service.

2024-06-27 15:47 UTC, quexten commented on apps/desktop/src/platform/main/biometric/biometric.unix.main.ts
> +        <allow_active>auth_self</allow_active>
A brief test of setting these to no (inactive and any, but leaving active on).

2024-07-01 17:26 UTC, MGibson1 requested changes
This looks really nicely wrapped up. Thank you.

I do have some concerns given our recent experience with libsecret, but this being an opt-in seems much safer than our foray into secure storage for tokens.

I think there are some small native tweaks to be made prior to merge

2024-07-01 17:26 UTC, MGibson1 commented on apps/desktop/src/app/accounts/settings.component.ts
> +        return "additionalPolkitSettings";
⛏️  No need for this, you disabled these additional settings in the template.

2024-07-02 09:42 UTC, quexten commented
@MGibson1 I need no re-verify the current behavior, but using https://github.com/bitwarden/clients/pull/9393 in combination with the client key half, should give a secure alternative since it should not be dumpable when https://github.com/bitwarden/clients/pull/9393 is active. Thus, the biometrics key is not needed to achieve the same level of security as Windows against same-session memory & secret service stealing software (not considering kernel level exploits, which I would assume would be problematic on Windows too though).

2024-07-02 11:28 UTC, quexten commented on apps/desktop/desktop_native/Cargo.toml
> +async-trait = "0.1.69"
Nice, Rust 1.75 seems to have added async traits. Removed the dependency!

2024-07-02 11:29 UTC, quexten commented on apps/desktop/desktop_native/Cargo.toml
> +zbus_polkit = "3.0.1"
Done, and also updated to a much newer zbus crate version since it was outdated. (@dani-garcia commented about this on another PR using the zbus crate).

2024-07-02 11:35 UTC, quexten commented on apps/desktop/src/app/accounts/settings.component.ts
> +        return "additionalPolkitSettings";
Removed this, thanks!

2024-07-02 11:38 UTC, quexten commented on apps/browser/src/platform/services/platform-utils/browser-platform-utils.service.ts
> +    if (platformInfo.os === "mac" || platformInfo.os === "win" || platformInfo.os === "linux") {
Might be covered by https://github.com/bitwarden/clients/pull/9851 because it passes the availability check through to desktop? (Though I believe desktop is missing a libsecret check in the osSupportsBiometrics).

2024-07-02 14:37 UTC, quexten commented on apps/browser/src/platform/services/platform-utils/browser-platform-utils.service.ts
> +    if (platformInfo.os === "mac" || platformInfo.os === "win" || platformInfo.os === "linux") {
Added availability check in the desktop app for libsecret. So this should be covered on browser too once 9851 is merged (I think).

2024-07-02 14:39 UTC, quexten commented
@MGibson1 @jlf0dev I added clientkeyhalf support to the PR now and it seems to be locally working, so combined with the memory protections this should give an adequate security level. One thing I'll note here: On Windows the "osKeyHalf" is non-optional, but the clientkeyhalf is. On linux the osKeyHalf does not exist, but the clientKeyHalf is always present. In the PR I'm passing the typescript level client key half, in as the rust-level osKeyHalf. It might make sense to rename the osKeyHalf in rust to "requiredKeyHalf" or "baseKeyHalf", and the clientKeyHalf to "optionalKeyHalf" or "extraKeyHalf", since this allows enforcing key requirements on a type level but also sharing the code while semantically making sense.

2024-07-03 18:39 UTC, MGibson1 requested changes
sorry, a few more issues with the fuller implementation I missed

2024-07-04 09:50 UTC, quexten commented on apps/desktop/src/platform/main/biometric/biometric.unix.main.ts
> +        osKeyPartB64: clientKeyHalfB64,
So do we make osKeyPart optional then? I considered that but decided against it because I like the type system level enforcement of the presence of at least one key. We could re-name to "required key" and "optional key" if that helps?

2024-07-04 10:29 UTC, quexten commented on apps/desktop/src/platform/main/biometric/biometric.unix.main.ts
Just to confirm my understanding of the key witness concept, is it to confirm that the clientKeyHalf is in sync with the oskey+clientkey protected userkey stored in secure storage?

I don't think it matters too much if we are saving it on e.g. every unlock since there is no user-interaction required for saving to at least gnome keyring and kwallet as backing secret services, (except for once for unlock, in case it is not already unlocked).

2024-07-04 10:44 UTC, quexten commented on apps/desktop/desktop_native/core/src/biometric/unix.rs
> +                return Ok(encrypted_secret);
Removed the whole match expression now. I think this was mostly left over from the windows code.

2024-07-04 11:52 UTC, quexten commented on apps/desktop/src/platform/main/biometric/biometric.unix.main.ts
> +        osKeyPartB64: clientKeyHalfB64,
[382f744](https://github.com/bitwarden/clients/pull/4586/commits/382f744742fb3a866cdaff85e8de47db6e9b3029) moved the clientKeyPart to be actually put into the clientKeyPart in rust; the oskeypart is just sha256(iv) and does not really add security, since there is no uv gated secret on linux (at the moment).

2024-07-04 11:53 UTC, quexten commented on apps/desktop/desktop_native/core/src/password/unix.rs
> +
My line of thinking was that we can make sure that it is not only listed on dbus but also actually responding. But the difference here is probably negligible.

2024-07-10 21:48 UTC, MGibson1 commented on apps/desktop/desktop_native/core/src/password/unix.rs
> +
well one of the categories of issues we ran into with that work was a present worker that failed to return an entry after we saved something to it. This might be better protection against something like that

2024-07-10 21:53 UTC, MGibson1 commented on apps/desktop/src/platform/main/biometric/biometric.unix.main.ts
I would say it as the witness ensures that any attempt to save the user key is necessary. The clientKeyHalf isn't really a part of it.

However, as along as there is no automatic user prompt, there's likely no problem. It just means we're writing to the store more often than we really need to.

2024-07-10 21:55 UTC, MGibson1 submitted a review, later dismissed

2024-07-11 11:46 UTC, quexten commented
@MGibson1 during prep for QA I noticed that the triple pkexec polkit prompt for setup is not very user friendly, so consolidated them into just one now.

2024-07-11 12:16 UTC, jlf0dev approved these changes, later dismissed

2024-07-11 19:28 UTC, MGibson1 submitted a review, later dismissed

2024-07-11 19:53 UTC, Vcele commented
🚀

2024-07-25 15:54 UTC, quexten commented
Resolved merge conflicts (sorry about the force push, had some unrelated prettier changes got pulled in so I had to pull those out and commit without the pre-commit hook).

2024-08-01 23:54 UTC, MGibson1 approved these changes, later dismissed

2024-08-02 13:05 UTC, quexten commented
Removed snap support for the first release of this feature since it requires additional investigation into the permissions for polkit.

2024-08-02 17:58 UTC, quexten commented
QA gave the green light for non-snap releases. Enabling auto-merge 🚀

2024-08-05 19:53 UTC, MGibson1 approved these changes

2024-08-06 15:04 UTC, jlf0dev approved these changes
🚀

2024-08-06 15:04 UTC, merged

2024-08-06 15:59 UTC, Vcele commented
How long will it take for these changes to make it in the release version?

2024-08-06 16:01 UTC, alba4k commented
at this point anything less than 2 years is good for me 🙈

We've been waiting for a while, lets say so

2024-08-06 16:27 UTC, quexten commented
@alba4k Is right. Probably 2024.8.0 if I have my schedule right.

2024-08-06 16:32 UTC, Vcele commented
Yes I'm really happy that this finally got merged. Thank you so much @quexten, this will really improve my experience with bitwarden on linux.

2024-08-07 04:16 UTC, littleblack111 commented
Thank you very much. This QoL improvement is massive @quexten

2024-08-07 08:21 UTC, junderw commented
Any USB Type-A fingerprint sensor recommendations?

I am using Arch Linux, so old packages shouldn't be a problem.

2024-08-07 09:17 UTC, materemias commented
> Any USB Type-A fingerprint sensor recommendations?
> 
> I am using Arch Linux, so old packages shouldn't be a problem.

I use a DigitalPersona U.are.U 4500, also on arch

2024-08-07 10:10 UTC, quexten commented
Yes, this is really more "polkit authentication", which at least on gnome (ubuntu/fedora) be default means "biometric or system password" authentication (as they support fingerprints out of the box), and *can* mean biometric authentication on other DE's if you configure the pam modules & make them be used by polkit. U2F PAM with yubikey should also work (untested though).

2024-08-24 10:43 UTC, robin-thoni commented
That's a really cool feature!

I can successfully manually lock, then unlock using polkit:
![image](https://github.com/user-attachments/assets/94d340b7-8242-4ce9-b29b-2cf92448c644)

But I can't start the app using polkit, while being already logged-in:
![image](https://github.com/user-attachments/assets/ffc537db-a279-4b01-8a33-3580b2ebd0bd)
If I do not set a PIN, it requires the master password to unlock.

Are we supposed to be able to start the app using polkit?

2024-08-24 11:25 UTC, savely-krasovsky commented
You was once able to unlock using Windows Hello even at first app start, but after they disabled it due to security reasons, but kept the option with warning. I guess same applies to Unix: it's probably just insecure to unlock vault with system authentication only, since master key should cached I somehow I guess. Hope @quexten will give more background.

2024-08-25 04:43 UTC, littleblack111 commented
But the browser integration doesn't seem to work?

2024-08-25 11:47 UTC, quexten commented
@robin-thoni @savely-krasovsky Yes, allowing biometric unlock on app start is only securely possible on Mac at the moment due to the limitations the platforms provide. On Windows and Linux, this introduces the risk that if an attacker gets access to your unlocked system (either it is shut down and not full disk encrypted, or it is running and already decrypted), then the attacker can steal all of the secrets necessary to unlock the vault.

I do think this should be better surfaced to the user because right now the option just disappears without the user knowing why. I also think we can add this as an opt-in feature, where you accept the risk; (1Password does the same with their tpm supported unlock, which has the same fundamental flaw).

There are some desktop biometrics options that need to be done first though.

2024-08-25 11:49 UTC, quexten commented
@littleblack111 Which browser and version, and which Bitwarden client (flatpak/deb/appimage/rpm) are you experiencing issues on? (It is expected to work in most cases).

2024-08-25 12:14 UTC, littleblack111 commented
From the arch extra repo. Chromium latest

2024-08-25 15:32 UTC, jivanpal commented
Browser integration working for me as follows:

- OS: Pop OS 22.04
- Bitwarden desktop client: AppImage from bitwarden.com
  - Version 2024.8.0
  - Shell 31.3.1
  - Renderer 126.0.6478.185
  - Node 20.15.1
  - Architecture x64
- Web browser: Google Chrome from official stable repo
  - Version: 127.0.6533.119
- Bitwarden browser extension version: 2024.8.0

Thanks for this, very nice to have!

2024-08-25 17:32 UTC, fneirotti commented
@littleblack111 @quexten I was facing the same issue but I think I've found where problem comes from. It may be only present itself in arch.

It's twofold:
1. According to this: https://github.com/bitwarden/clients/blob/f2be150b70827269020f9a2552c01294aac35258/apps/desktop/src/main/native-messaging.main.ts#L193-L213
The only browsers supported on linux are firefox, google-chrome and edge. If you have chromium or vivaldi the NativeMessagingHosts entry will not be generated.
2. But If you copy the generated file from the `google-chrome/NativeMessagingHosts` folder to the correct one, it doesn't work either. That's because the `path` is incorrect. It's set as `/usr/lib/electron31/electron` where it should've been `/usr/bin/bitwarden-desktop`

2024-08-25 23:11 UTC, savely-krasovsky commented
It's Arch Linux packaging problem I guess. They use generic electron binaries instead of supplied ones. It has some benefits, e.g. they can ship electron with security patches without waiting original developer.

In my case it doesn't work either, tried both version from Arch repos and Flatpak one. In my case Bitwarden extension for Firefox just don't have an option to enable integration.

2024-08-25 23:17 UTC, Ganic-Ismar commented
@savely-krasovsky the bitwarden extension from the firefox addon store doesnt have the most recent version for some reason - that might be your issue.

2024-08-25 23:31 UTC, quexten commented
Flatpak is expected not to work at the moment due to the sandboxing. An alternative mechanism, or at least special rules for allowing the ipc socket + manual setup instructions would be needed.

Arch is also not officially supported and not QA tested. Interesting, I do think it should be able to work with slight modifications to the native IPC. I have my mac dev machine configured to use generic electron for development, via a proxy script, but I think better solutions are possible. It does sound more like an issue that should be fixed by the maintainers on arch though.

2024-08-26 11:16 UTC, quexten commented
I'll try to get in touch with the downstream arch maintainers to resolve this, but it seems I need to wait for a arch gitlab account to be created for me. I'll update this issue when I got in touch.

2024-08-26 21:39 UTC, quexten commented
Tracking this on the aur gitlab here: https://gitlab.archlinux.org/archlinux/packaging/packages/bitwarden/-/issues/2

2024-08-27 12:39 UTC, savely-krasovsky commented
Can also confirm: `bitwarden 2024.8.0-2` fixes the problem and now everything works as expected.

2024-10-06 20:08 UTC, pedrocleis commented
> Can also confirm: `bitwarden 2024.8.0-2` fixes the problem and now everything works as expected.

Which version are you using? AppImage, Flathub, Snap?

2024-10-06 20:23 UTC, yochananmarqos commented
@pedrocleis The Arch package. See https://gitlab.archlinux.org/archlinux/packaging/packages/bitwarden/-/issues/2. I can't remember if 2024.8.0-2 actually fixed it, but 2024.9.0-1 certainly did.

2024-10-06 20:25 UTC, pedrocleis commented
Thank you, @yochananmarqos 
I'm currently using Ubuntu, the Flatpak/Snap weren't working, got it to work with the AppImage and some changes in the files. Thank you :)

2024-10-28 13:47 UTC, popy2k14 commented
I wanted to give this a shot on mint 22 with Brave browser.
Sadly, the manifest is just generated for firefox, google-chromium & edge.

So with a little workaround it's now working as it should (google-chrome not installed):

```
mkdir ~/.config/google-chrome/NativeMessagingHosts
cd ~/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts
ln -s ../../../google-chrome/NativeMessagingHosts/com.8bit.bitwarden.json com.8bit.bitwarden.json
```

Would be nice if more chromium based browsers will get supported by the client.

2024-11-19 10:00 UTC, jankatins commented
https://fosstodon.org/@jankatins/113376475091345067 :-)

2024-11-19 10:12 UTC, littleblack111 commented
anyways, firefox seem to work?

2024-11-19 10:36 UTC, Vcele commented
> https://fosstodon.org/@jankatins/113376475091345067 :-)

My problem is that I can't enable biometrics support in the desktop app. I get the "Automatic Setup not available" error as seen in the screenshot in the merge request description.

2024-11-19 10:40 UTC, quexten commented
@Vcele What distro/packaging format are you on?

2024-11-19 10:47 UTC, Vcele commented
> @Vcele What distro/packaging format are you on?

I was using Nix package manager on Nixos

2024-11-19 11:08 UTC, Vcele commented
https://github.com/NixOS/nixpkgs/issues/344073

Ok I was able to fix it with this

2024-11-19 13:15 UTC, quexten commented
I'm not sure what nix does, but manual setup will soon be unnecessary entirely. It was meant for just flatpak, but that is not needed anymore with https://github.com/bitwarden/clients/pull/12007 which adds both autosetup for flatpak, and also makes setup optional entirely by using a fallback policy. 

So it should work out of the box (soon).

2024-11-19 17:02 UTC, taaem commented
Is there a way (besides manual setup) to change the policyPath? 
I'm using Aeon Desktop, which by default has a read-only filesystem for `/usr` but a rw filesystem for `/etc`. I can manually put the policy into `/etc/polkit-1/actions/com.bitwarden.Bitwarden.policy` and everything is working fine. Is there a reason you install the policy into the `/usr` path and not `/etc` and is there a way to change that manually?

2024-12-23 23:13 UTC, pedrocleis commented
Hi, I've got the biometrics to work with the BitWarden AppImage desktop version but I'm unable to use with Firefox, I'm using AppImageLauncher (saw it on the BitWarden's downloads page).

I'm currently on:
- Kubuntu trixie/sid (oracular) x86_64
- Firefox 133.0.3
- Browser extension: Version: 2024.12.3 SDK: 'main (edee180)'
- Desktop app: Version 2024.12.1, SDK 'main (edee180)', Shell 32.1.1, Renderer 128.0.6613.137, Node 20.17.0, Architecture x64

This is the error I'm getting: 
![image](https://github.com/user-attachments/assets/0c2d3b2f-bfc8-45da-9cae-f0126fe8e653)

I've got this to work on another version of Ubuntu, but I don't remember how I did.
And yes, I've checked the "Allow browser integration" on the Desktop Settings page.

I saw that on the [BitWarden's Help Center](https://bitwarden.com/help/biometrics/#tab-browser-extension-2vCWb5iFg4OqKS0B2xXpqW) it says:
> Browser extensions support the same biometrics options as desktop; for Windows via [Windows Hello](https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/windows-hello) using PIN, Facial Recognition, or [other hardware that meets Windows Hello biometric requirements](https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/windows-hello-biometric-requirements), for macOS via [Touch ID](https://support.apple.com/en-us/HT207054), and for Linux (**Chromium-based browsers only**) with system authentication.

Do I have to use Chromium-based browser for it to work? @jankatins links says he's using Firefox and I got it to work with Firefox some months ago too.
Any help is greatly appreciated, I can post logs if necessary. :)

2025-05-06 20:41 UTC, alba4k commented
Same here, doesn't appear to be working anymore, as discussed in https://github.com/bitwarden/clients/issues/12697

2025-05-09 11:17 UTC, pedrocleis commented
Replying to my previous post, I finally got it to work.
The problem was that Firefox was installed through Snap and the BitWarden desktop app couldn't find it.

2025-10-19 11:20 UTC, Zujaj commented
I’m using Bitwarden on Ubuntu 24.04.3 LTS (Kernel 6.14.0-33-generic, x86-64) with Microsoft Edge 141.0.3537.85.

After installing the Bitwarden desktop app from Snap, I received the message:

“Browser integration not supported — unfortunately browser integration is currently not supported in the Linux version.”

This means I can’t use biometric unlock in the browser, which makes everyday use much harder. It works fine on Windows and macOS, so it’s disappointing that Linux users are missing out on this core feature.

Please consider adding browser ↔ desktop integration support for Linux — many of us rely on Edge or Chromium-based browsers for work, and this would make Bitwarden far more seamless to use.

Thank you for your great work maintaining Bitwarden, and I hope this feature can be prioritized soon.

2025-10-20 13:35 UTC, pedrocleis commented
Hi @Zujaj have you tried the .deb for the Ubuntu version?
I'm now using Fedora and it works fine with the .rpm
Is that a problem **only** with Edge or you can use with other browsers?
If you are not interested in the .deb version, the AppImages worked when I used (K)Ubuntu

2025-10-20 13:53 UTC, quexten commented
I did some prototyping before, and it's possible but rather complex to add support for snap and flatpak, both when considering the desktop app running sandboxed, and when considering the browser running sandboxed. Hopefully I'll find some time to split these out into individual PR's to get them merged: https://github.com/bitwarden/clients/pull/14836

2025-10-21 13:26 UTC, pedrocleis commented
ty so much @quexten i know that you are quite busy nowadays

2025-10-22 11:00 UTC, Zujaj commented
> Hi @Zujaj have you tried the .deb for the Ubuntu version? I'm now using Fedora and it works fine with the .rpm Is that a problem **only** with Edge or you can use with other browsers? If you are not interested in the .deb version, the AppImages worked when I used (K)Ubuntu

Sorry couldn't get back, can you share link to the .deb file? I couldn't find it in Release

2025-10-22 12:12 UTC, pedrocleis commented
> > Hi @Zujaj have you tried the .deb for the Ubuntu version? I'm now using Fedora and it works fine with the .rpm Is that a problem **only** with Edge or you can use with other browsers? If you are not interested in the .deb version, the AppImages worked when I used (K)Ubuntu
> 
> Sorry couldn't get back, can you share link to the .deb file? I couldn't find it in Release

No problem, mate
https://bitwarden.com/download/?app=desktop&platform=linux&variant=deb

2025-10-22 12:38 UTC, Zujaj commented
[Screencast from 2025-10-22 17-30-53.webm](https://github.com/user-attachments/assets/00407e0d-308b-4d09-a11f-e9f1e8254cf2)

Nope that didn't work as expected.

> > > Hi @Zujaj have you tried the .deb for the Ubuntu version? I'm now using Fedora and it works fine with the .rpm Is that a problem **only** with Edge or you can use with other browsers? If you are not interested in the .deb version, the AppImages worked when I used (K)Ubuntu
> > 
> > 
> > Sorry couldn't get back, can you share link to the .deb file? I couldn't find it in Release
> 
> No problem, mate https://bitwarden.com/download/?app=desktop&platform=linux&variant=deb

2025-12-15 01:28 UTC, 3v1n0 commented
Sorry I was quickly checking this, but it seems the wrong approach: the biometric unlock should happen via [fprintd API directly](https://fprint.freedesktop.org/fprintd-dev/), not via polkit (and potentially PAM)!

2025-12-15 08:51 UTC, quexten commented
@3v1n0 System Unlock (That's what "biometrics" is called on Linux) supports polkit, since polkit also supports `https://github.com/boltgolt/howdy`, which fprintd alone does not and because fprintd's support for fingerprint readers is quite limited. My test device died in the meantime, and I'm not sure any other engineers / QA engineers have a fprintd compatible test device. Polkit in the meantime can be used with the system password too.

(That said, it may be worth it to add an alternate fprintd backend, since it doesn't require installation of a policy, which would make at least flatpak support easier.)

Is there any specific problem you see with polkit? (Specifically security would be a point of interest here?)

2025-12-15 15:12 UTC, 3v1n0 commented
Speaking with the fprintd maintainer hat here, FWIW:

> @3v1n0 System Unlock (That's what "biometrics" is called on Linux) supports polkit, since polkit also supports `https://github.com/boltgolt/howdy`, which fprintd alone does not and because fprintd's support for fingerprint readers is quite limited.

Well, if we want to support biometrics of any sort, we should use specific protocols (so howdy and fprintd) one, not the generic PAM one that is just "whatever the user has configured on system".

Not to mention that by default the greatest majority of distros do not enable pam_fprintd.so (and for a good reason) by default.

> My test device died in the meantime, and I'm not sure any other engineers / QA engineers have a fprintd compatible test device.

It's very hacky, but [this](https://gitlab.freedesktop.org/3v1n0/fprintd-mock-runner) can fill the gap.

> Polkit in the meantime can be used with the system password too.

And not only, which is making the "biometrics unlock" just a system-authentication system unlock.
That may be fine but also misleading.

> (That said, it may be worth it to add an alternate fprintd backend, since it doesn't require installation of a policy, which would make at least flatpak support easier.)

I was always interested in defininig a more generic biometrics API in freedesktop space, but so far I've been blocked by technical limitations of all the methods we have at the moment.

> Is there any specific problem you see with polkit? (Specifically security would be a point of interest here?)

So, my main concerns are:
 - Polkit cannot define what method to use to unlock, it's just relying on PAM, so whatever the system is configured for
 - You may end up be able to unlock the bitwarden vault with the system password, which is something you may *not* want, if you just asked to _enable biometrics_
 - Most distros do not enable the PAM fprintd module by default

Then, there's a more generic one that is an architectural problem that we have with fingerprint or face recognition or any other similar kind of authentication system in linux: these are all "Yes/No" authentication systems and do not provide a secret to unlock a vault.

While ideally we should have a system security enclave that generates a secret that we can safely release with a biometric device and eventually use this secret to unlock the password vault (something is in the works for this though).

2025-12-15 17:26 UTC, quexten commented
Thank you @3v1n0 for your input on this. That certainly makes sense. I wish Linux had a good biometrics API we could switch to -- I had started a discussion on a local authentication portal here: https://github.com/flatpak/xdg-desktop-portal/discussions/1275 - but at some point did not continue the discussion.

As to this part:
> Then, there's a more generic one that is an architectural problem that we have with fingerprint or face recognition or any other similar kind of authentication system in linux: these are all "Yes/No" authentication systems and do not provide a secret to unlock a vault.

That's why currently on linux, biometric unlock is only available after first unlock, whereas on mac / (windows with ugly hacks) it is available before first unlock. The secret - after first unlock - is held in `memfd_secret` or `keyctl`, and the process holding it resists debugger attachment via ptrace, so it's secure despite other programs running in the same user-space. Ideally this secret would live outside of userspace though - persistently , and only released by biometrics.

Could you expand on this / provide a pointer to where this is happening?:
> While ideally we should have a system security enclave that generates a secret that we can safely release with a biometric device and eventually use this secret to unlock the password vault (something is in the works for this though).

If we had something similar to MacOS, where we have a keyring like service that biometrically locks items, that would be the ideal solution from my point of view.