[EC-859] update billing routes for owners of Managed orgs
bitwarden/clients pull request #4611
Opened 2023-01-31 17:56 UTC by jlf0dev

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

OAVR changed around the tab and routing slightly in the Org Admin Console. This fix allows owners of managed orgs to still access the Billing tab, but shows an icon saying to contact their Provider.
## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

<img width="1336" alt="image" src="https://user-images.githubusercontent.com/24985544/215843438-27950ce5-62c3-4e39-b066-4cbf7e22cfc5.png">

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-02-01 00:33 UTC, eliykat requested changes
Good to see this issue got picked up!

A few minor changes below. I also asked a broader question about rxjs patterns in `#code`, as I wanted to get some guidance myself before giving it as feedback. Check that out and tell me what you think (optional only).

2023-02-03 15:38 UTC, jlf0dev commented
Thanks for the feedback @eliykat, I've updated the observable and took the time to also update the settings and reporting tab observables as well.

Let me know what you think, I'm a fan of how much cleaner it looks.

2023-02-06 07:16 UTC, eliykat requested changes
This looks great, thanks for taking the time to rework the observables per the Slack discussion.

My only real recommendation is to go the next step and implement the `get$` method discussed in the Slack thread, e.g.

```ts
export class OrganizationService {
//...
  get$(id: string): Observable<Organization> {
    return this.organizations$.pipe(filter(o => o.id === id));
  }
//...
}
```

This is a bit out of scope, but is easy to add, and would already clean up some of the repeated `orgs.find` logic repeated in these components before it proliferates further.

Then you can do, e.g.

```ts
this.showPaymentAndHistory = this.route.params.pipe(
  map(params => organizationService.getOrgObservable(params.organizationId)),
  map(organization => !this.platformUtilsService.isSelfHost() && organization.canManageBilling));
```

Which I think is the tidiest ^_^

2023-02-06 07:16 UTC, eliykat commented on apps/web/src/app/organizations/reporting/reporting.component.ts
> +    );
I'm not 100% sure, but you may need to use the `startWith` operator to maintain the default behaviour/value. e.g. `startWith(true)`.

Previously, `showLeftNav` had an initial/default value of `true` before `ngOnInit` ran. Now we're replacing that boolean value with an observable with no initial value - I'm not sure how the `async` pipe handles that. What does it evaluate to in the template before the first value has emitted? I assume it's falsey but I don't know. Please feel free to correct me if it's not an issue :)

2023-02-06 07:18 UTC, eliykat commented on apps/web/src/app/organizations/settings/settings.component.html
> +            *ngIf="(organization$ | async)?.isOwner"
It seems like it would be easiest to do `*ngIf="organization$ | async as organization"` in the surrounding div, rather than the inline null checks in every `<a *ngIf...>`.

The `as` keyword will then extract the concrete value so you don't need to use the async pipe below.

2023-02-10 15:57 UTC, jlf0dev commented on apps/web/src/app/organizations/reporting/reporting.component.ts
> +    );
Good point, added

2023-02-10 15:58 UTC, jlf0dev commented on apps/web/src/app/organizations/settings/settings.component.html
> +            *ngIf="(organization$ | async)?.isOwner"
Good idea, added!

2023-02-10 16:26 UTC, jlf0dev commented
```js
this.showPaymentAndHistory$ = this.route.params.pipe(
  switchMap((params) => this.organizationService.get$(params.organizationId)),
  map((org) => !this.platformUtilsService.isSelfHost() && org.canManageBilling)
);
```

@eliykat theoretically this would subscribe to the observable from the organization service right? So this would still emit if the organization observable is updated? Just want to make sure someone agrees with that before we change it.

2023-02-13 01:29 UTC, eliykat reviewed
> ```ts
> this.showPaymentAndHistory$ = this.route.params.pipe(
>   switchMap((params) => this.organizationService.get$(params.organizationId)),
>   map((org) => !this.platformUtilsService.isSelfHost() && org.canManageBilling)
> );
> ```
> 
> @eliykat theoretically this would subscribe to the observable from the organization service right? So this would still emit if the organization observable is updated? 

I believe so! Good work using `switchMap`, my example was incorrect in that way.

Here's my understanding of what we're doing here, so you can check it: `switchMap` subscribes to the outer observable (route params), uses it to get an inner observable (the transformed `organizations$` observable), and then subscribes to the inner observable. If new orgs are emitted by `organizationService`, we'll get our updated org here via the inner subscription. If the params change, the outer observable will emit a new value, which will cancel the old inner subscription and set up a new one instead (using the new orgId, to get the right org). So I think we're good!

(Not that we're actually subscribing here, but that's what the async pipe is sugar for)

> Just want to make sure someone agrees with that before we change it.

Good call - @coroiu could you please double-check the logic here before we start implementing this pattern?

It otherwise looks good to me.

2023-02-13 01:37 UTC, eliykat commented on apps/web/src/app/organizations/reporting/reporting.component.html
> +      <div class="card" *ngIf="organization$ | async">
I think you can also use `as org` here as well, to minimise repeated use of the `async` pipe. Just keeps things readable.

2023-02-13 15:07 UTC, jlf0dev commented on apps/web/src/app/organizations/reporting/reporting.component.html
> +      <div class="card" *ngIf="organization$ | async">
👍

2023-02-14 08:16 UTC, coroiu commented on apps/web/src/app/organizations/reporting/reporting.component.ts
> +    );
I was curious about this as well, here's a stackblitz showing what happens :) 
https://stackblitz.com/edit/angular-async-pipe-vs-subscribe-xxmkvr?file=src%2Fapp%2Fapp.component.ts

2023-02-14 08:41 UTC, coroiu reviewed
Beautiful PR! 😁 Added some minor comments

@eliykat Your description of `switchMap` is correct! The beauty of it is that `switchMap` also unsubscribes to the inner observable, meaning that if the inner observable is based off of an http request then that will automatically get cancelled!

2023-02-14 08:41 UTC, coroiu commented on libs/common/src/services/organization/organization.service.ts
> +  get$(id: string): Observable<Organization> {
suggestion (non-blocking): This can (optionally) be future proofed

```suggestion
  get$(id: string): Observable<Organization | undefined> {
```

2023-02-14 08:41 UTC, coroiu commented on apps/web/src/app/organizations/reporting/reporting.component.ts
> +    );
suggestion: multicast this observable

```suggestion
    this.organization$ = this.route.params.pipe(
      switchMap((params) => this.organizationService.get$(params.organizationId)),
      shareReplay({ refCount: true, bufferSize: 1 })
    );
```

### Background
Because of how these observables are setup the application is going to subscribe to `this.organization$` 2 times. Once directly using

```html
<div class="card" *ngIf="organization$ | async as org">
```

and once indirectly through 

```html
<div class="col-3" *ngIf="showLeftNav$ | async">
```

Because of how observables work this means that we will be calling `this.organizationService.get$` twice for each update that comes through `this.route.params`. By multicasting we will avoid this and only perform the operation once. We use `shareReplay` instead of `share` to avoid race conditions, especially since we use `BehaviorSubject` as a backing storage which will emit instantaneously. The reason is that mutlicasting turns the observable hot after it gets its first subscriber, which means that any subscriber that comes after that will miss out on previously emited values.

2023-02-15 13:56 UTC, jlf0dev commented on apps/web/src/app/organizations/reporting/reporting.component.ts
> +    );
Thanks for the suggestion! Definitely a good catch

2023-02-15 14:00 UTC, coroiu approved these changes
💯

2023-02-21 02:58 UTC, eliykat submitted a review, later dismissed
In case it's required. I think this turned out great!

2023-02-27 21:27 UTC, vincentsalucci approved these changes

2023-02-27 21:31 UTC, merged