[EC-476] Add notificationBar edit flow
bitwarden/clients pull request #4626
Opened 2023-02-02 04:22 UTC by eliykat

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-02-07 01:34 UTC, eliykat commented on apps/browser/src/background/main.background.ts
> +        that.runtimeBackground.processMessage(message, that as chrome.runtime.MessageSender, null);
I'm not sure that this is right, but best I can tell, it is the type that `processMessage` is expecting.

2023-02-07 01:53 UTC, eliykat commented on apps/browser/src/autofill/background/notification.background.ts
> -import { LoginUriView } from "@bitwarden/common/vault/models/view/login-uri.view";
CodeScene is giving me a Primitive Obsession warning in this file. I could fix this by bringing over @justindbaur's typing here: https://github.com/bitwarden/clients/compare/feature/mv3-changes#diff-93027c5e0aa0add0f42851a645893846e5984db8a2d9d5c5af8ae5bdef83403eR1
And then passing whole objects around more often. That seemed too much for this PR, but happy to do it immediately after. (or now if the reviewer wants it)

2023-02-07 01:59 UTC, eliykat commented on apps/browser/src/autofill/background/notification.background.ts
> -import { LoginUriView } from "@bitwarden/common/vault/models/view/login-uri.view";
In general I'm wary of some of this CodeScene feedback as I can see that the mv3 team has refactors in the works here which will likely address them, and I'm already stepping on their toes a bit.

2023-02-14 03:39 UTC, justindbaur requested changes
A couple small nits and one thing to just think about. Love that it gets rid of some `any`.

2023-02-14 03:39 UTC, justindbaur commented on apps/browser/src/autofill/notification/bar.ts
> +    notificationEdit: chrome.i18n.getMessage("edit"),
You or @djsmith85 would probably know better than I but do translation strings that come straight from `chrome.i18n.getMessage()` need to handled any more specially than when done through our `I18nService`?

2023-02-14 03:39 UTC, justindbaur commented on apps/browser/src/background/main.background.ts
> +        that.runtimeBackground.processMessage(message, that as chrome.runtime.MessageSender, null);
I think I would rather a `as any` cast here. We luckily use the `sender` argument here very little but I'd rather lie through an any cast instead of casting it as something it is for sure NOT.

2023-02-14 03:39 UTC, justindbaur commented on apps/browser/src/popup/generator/generator.component.ts
> +  private addEditCipherInfo: AddEditCipherInfo;
😍

2023-02-14 03:39 UTC, justindbaur commented on apps/browser/src/background/models/addLoginQueueMessage.ts
> +    cipherView.name = cipherView.name.replace(/^www\./, "");
I'd rather wrap the first assignment than assign it twice.
```suggestion
    cipherView.name = (Utils.getHostname(message.uri) || message.domain).replace(/^www\./, "");
```

2023-02-14 22:26 UTC, eliykat commented on apps/browser/src/popup/generator/generator.component.ts
> +  private addEditCipherInfo: AddEditCipherInfo;
First thing I did 😁

2023-02-14 22:27 UTC, eliykat commented on apps/browser/src/background/main.background.ts
> +        that.runtimeBackground.processMessage(message, that as chrome.runtime.MessageSender, null);
Excellent point

2023-02-14 22:44 UTC, eliykat commented on apps/browser/src/autofill/notification/bar.ts
> +    notificationEdit: chrome.i18n.getMessage("edit"),
Not really. Our `messages.json` directory structure and JSON structure is set up to comply with the `chrome.i18n` api requirements: https://developer.chrome.com/docs/extensions/reference/i18n/. It'll fetch the string from there just like `i18nService.t` If anything, `i18nService.t` is basically an implementation of the `chrome.i18n.getMessage` api.

2023-02-16 02:04 UTC, justindbaur approved these changes
Looks great!

2023-02-16 04:04 UTC, merged