[SM-396] Self-enroll Secrets Manager
bitwarden/clients pull request #4666
Opened 2023-02-06 10:47 UTC by Hinton

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Adds support for self-enrolling to secrets manager.

## Code changes

- **apps/web/src/app/organizations/billing/organization-subscription-cloud.component.html**: Add enroll component to the subscription page.
- **apps/web/src/app/organizations/billing/secrets-manager/enroll.component.ts**: Add enroll component.
- **libs/common/src/abstractions/organization/organization-api.service.abstraction.ts**: Add new endpoint for enrolling to sm.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-02-07 22:39 UTC, shane-melton commented on apps/web/src/locales/en/messages.json
> +    "message": "Turn on organization access to the Secrets Manager at no charge during the Beta program. Users can be granted access to the Beta in Manage > Members."
This path is going to be different once the OAVR releases in February. The Members page will be on its own tab.

2023-02-07 23:25 UTC, shane-melton requested changes
Looks good; but we'll need to update the copy explaining how to grant beta access to members via the new Members tab in OAVRv2. The "Manage" tab will no longer exist.

2023-02-09 13:57 UTC, Hinton commented on apps/web/src/locales/en/messages.json
> +    "message": "Turn on organization access to the Secrets Manager at no charge during the Beta program. Users can be granted access to the Beta in Manage > Members."
Good catch.

2023-02-16 20:39 UTC, shane-melton approved these changes

2023-02-21 17:16 UTC, shane-melton approved these changes

2023-02-21 17:24 UTC, merged