[DEVOPS-1185] Split out the windows os from the new cli matrix build
bitwarden/clients pull request #4673
Opened 2023-02-06 17:02 UTC by michalchecinski

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [x] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Split *nix and windows cli builds.

## Code changes

- **.github/workflows/build-cli.yml:** Add new job outside of os matrix for building Windows CLI artifacts. Removed Windows-only steps from CLI build for macOS and linux.

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-02-07 15:20 UTC, joseph-flinn requested changes

2023-02-07 15:32 UTC, michalchecinski commented on .github/workflows/build-cli.yml
>        - name: Build & Package Unix
Done!

2023-02-07 18:57 UTC, joseph-flinn requested changes

2023-02-07 18:57 UTC, joseph-flinn commented on .github/workflows/build-cli.yml
>          run: npm run dist:${{ env.SHORT_RUNNER_OS }} --quiet
This whole step should be removed since this job is the Windows job and not the Unix one

2023-02-10 13:13 UTC, michalchecinski commented on .github/workflows/build-cli.yml
>          run: npm run dist:${{ env.SHORT_RUNNER_OS }} --quiet
Thanks for noticing. Done :)

2023-02-10 16:00 UTC, joseph-flinn approved these changes

2023-02-10 16:00 UTC, merged