[EC-1069] cannot save an item to a collection in the org vault view
bitwarden/clients pull request #4693
Opened 2023-02-08 15:08 UTC by coroiu

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Fix collections not being ~loaded~ overridden properly in the org vault.

## Code changes

- **apps/web/src/app/organizations/vault/add-edit.component.ts**: Add method to allow overriding collections.
- **apps/web/src/app/organizations/vault/vault.component.ts**: Use new method to override collections.

## Screenshots

![image](https://user-images.githubusercontent.com/2285588/217568828-6ba40184-e322-440c-b669-aa3887925bbd.png)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-02-08 15:13 UTC, coroiu commented on apps/web/src/app/organizations/vault/add-edit.component.ts
> +    this.writeableCollections = collections;
questions: Does anybody know why we have both of these? The only place `this.collections` is still used seems to be in `loadCollections` where it allows external components to override the automatically loaded collections. But I can't really figure out why we don't just use `this.writeableCollections` for that.

```ts
  protected loadCollections() {
    if (!this.organization.canEditAnyCollection) {
      return super.loadCollections();
    }
    return Promise.resolve(this.collections);
  }```

2023-02-08 15:15 UTC, coroiu commented on apps/web/src/app/organizations/vault/vault.component.ts
> +    );
For whatever reason (most likely race conditions) the original code works fine in the personal vault, but not here in the org vault. I'm hesitant to fix things that aren't broken so I haven't touched the personal vault, but I'm thinking maybe I should anyways... Thoughts?

2023-02-08 19:01 UTC, shane-melton requested changes
I think you definitely found the culprit, but I think we might be able to solve the problem by removing some of the "inheritance spaghetti" which should reduce some of these unexpected side effects. It should also get us one step closer to an eventual solution using the new `DialogService`.

Please see my replies to your comments for more details.

2023-02-09 00:41 UTC, shane-melton commented
Closing this in favor of https://github.com/bitwarden/clients/pull/4701

2023-02-09 00:41 UTC, closed without merging