[EC-775] [Technical Dependency] Refactor Vault Filters to be routable
bitwarden/clients pull request #4733
Opened 2023-02-13 12:24 UTC by coroiu

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-02-17 05:32 UTC, eliykat requested changes
Great PR, 10/10 would review again.

This will also need to be implemented for other clients (particularly desktop) after we've "perfected" it in the web vault. (and by "we" I mean the vault team ;) Can you please create a linked tech debt ticket for that?

2023-02-17 05:32 UTC, eliykat commented on apps/web/src/vault/org-vault/vault-filter/vault-filter.component.ts
> -  protected async removeInvalidCollectionSelection(collections: CollectionView[]) {
Similar problem to the individual component: the `Collections` heading should be selected by default, and also when a particular collection is selected but becomes invalid (due to the user changing orgs).

Again, that does seem to be the effect, I think you just need to add the visual highlight.

2023-02-17 05:32 UTC, eliykat commented on apps/web/src/vault/individual-vault/vault-filter/services/routed-vault-filter.service.ts
> +          collectionId: filter.collectionId ?? null,
I'm trying to understand your particular handling of `null` vs `undefined` here. 

Best I can tell, `createRoute` is transforming `null | undefined` to `null`, but then the `filter$` callback is transforming `null | undefined` to `undefined`. So what does it matter? It'll all end up as `undefined` in the `RoutedVaultFilterModel` object anyway.

Then `RoutedVaultFilterModel` is checking for `undefined` rather than nullish, even though you'll never get `null` there anyway, so it seems like a distinction without difference. Maybe future-proofing for strict mode?

I think we used to use `FolderId: null` for "No Folder", but it looks like you've (sensibly) replaced that with an `Unassigned` string constant, so I'm not sure why we need to keep drawing this distinction, rather than just testing for nullish.

2023-02-17 05:32 UTC, eliykat commented on apps/web/src/vault/individual-vault/vault-filter/shared/models/routed-vault-filter-bridge.model.ts
> +      return;
It might be a nit, but it seems simpler to me to just do

```ts
const folderId = (value != null && value.node.id === null) ? Unassigned : value.node.id;
this.bridgeService.navigate({
  ...this.routedFilter,
  folderId: folderId,
  type: null,
  collectionId: null,
});
```

and save me having to compare each property in each call to see what's different ;)

2023-02-17 05:32 UTC, eliykat commented on apps/web/src/vault/individual-vault/vault-filter/shared/models/routed-vault-filter.model.ts
> +  type?: string;
We could type this as a string union type.

2023-02-17 07:37 UTC, coroiu commented on apps/web/src/vault/individual-vault/vault-filter/services/routed-vault-filter-bridge.service.ts
> +            node: { id: "trash", name: "", icon: "", type: "trash" },
@jlf0dev Good point, will update!

@eliykat Yeah that was exactly the issue, I contemplated moving it from `VaultFilterComponent` to `VaultFilterService` but I really wanted to keep the modifications to a minimum, so this is what I ended up with it.

2023-02-17 07:38 UTC, coroiu commented on apps/web/src/vault/individual-vault/vault-filter/services/routed-vault-filter-bridge.service.ts
> +        return bridgeModel;
Huh, I wonder why I did this. Must've been a `console.log` here at some point 😅

2023-02-17 08:34 UTC, coroiu commented on apps/web/src/vault/individual-vault/vault-filter/services/routed-vault-filter-bridge.service.ts
> +export class RoutedVaultFilterBridgeService {
@jlf0dev Sure I can add the file descriptions I've used in the PR description field into the code!

@eliykat Yes exactly, this is a transitional class. As I mention in the Objective part of the PR description:

> This PR introduces an temporary bridge between URL filtering and the old state-in-code method. It enables us to move forward with refactoring the table and the navigation, and allow us to work on them separately.

2023-02-17 08:36 UTC, coroiu commented on apps/web/src/vault/individual-vault/vault-filter/services/routed-vault-filter-bridge.service.ts
> +    if (node.node.id === id) {
Haha yeah, hopefully we'll get rid of the TreeNode completely and not have to worry about it :D

2023-02-17 08:38 UTC, coroiu commented on apps/web/src/vault/individual-vault/vault-filter/services/routed-vault-filter-bridge.service.ts
> +  private findNode<T extends ITreeNodeObject>(
Huh, seems to be the exact same thing, nice catch!

2023-02-17 08:42 UTC, coroiu commented on apps/web/src/vault/individual-vault/vault-filter/services/vault-filter.service.ts
> +  protected buildCipherTypeTree(): Observable<TreeNode<CipherTypeFilter>> {
Yeeaaah, I know. I'm trying to keep changes to a minimum so I opted for duplication. It's not optimal but it is, like you say, transitional. The goal is to remove both `VaultFilterComponent` and `VaultFilterService` completely which is why I wasn't too worried about duplication across those files

2023-02-17 09:05 UTC, coroiu commented on apps/web/src/vault/individual-vault/vault-filter/services/routed-vault-filter.service.ts
> +          collectionId: filter.collectionId ?? null,
Ah yeah, a few things to unpack here.

### `filter$` and `RoutedVaultFilterModel`
I wanted to use `undefined` so that it's possible to create objects that are compatible with the `RouterVaultFilter` interface by simply omitting fields. As you mention `undefined` needs to be used to future-proof  for strict mode.

### `createRoute` converting to `null`
This is an unfortunate necessity due to the router implementation in angular. I set up the following requirements for the `createRoute` method:

 1. The object sent into `createRoute` as a parameter should match the object emitted by `filter$`
 2. Unrelated parameters in the URL should not be affected by the navigation resulting from `createRoute`. This keeps `cipherId` functionality intact.

To be able to meet (2) I had to use `queryParamsHandling: "merge"`, however that results in `undefined` being ignored, that's how it know to leave `cipherId` alone. So then I'm forced convert the fields that we care about into `null` to indicate that we actually want to clear those.

### Usage of `createRoute`
This is my bad and it's a good point, we shouldn't be creating `RouterVaultFilterModel` with `null` values, it defeats the whole point and makes the code incompatible with strict mode. I'll update this!

2023-02-17 09:12 UTC, coroiu commented on apps/web/src/vault/individual-vault/vault-filter/shared/models/routed-vault-filter-bridge.model.ts
> +      return;
Hmm, I try to stay away from variable instantiations using the ternary operator as a general rule because I think it just makes things harder to read.

But in this case I actually agree with you, seems to be a lot easier to read. Maybe I need to re-evaluate my rule 😁 I'll fix!

2023-02-17 09:13 UTC, coroiu commented on apps/web/src/vault/individual-vault/vault-filter/shared/models/routed-vault-filter.model.ts
> +  type?: string;
In what way? Which of the fields are you talking about?

2023-02-17 10:28 UTC, coroiu commented on apps/web/src/vault/individual-vault/vault-filter/services/routed-vault-filter-bridge.service.ts
> +            node: { id: "trash", name: "", icon: "", type: "trash" },
Fixed!

2023-02-17 12:10 UTC, coroiu commented on apps/web/src/vault/individual-vault/vault-filter/services/routed-vault-filter.service.ts
> +export class RoutedVaultFilterService implements OnDestroy {
Fixed!

2023-02-17 12:15 UTC, coroiu commented on apps/web/src/vault/individual-vault/vault-filter/services/routed-vault-filter-bridge.service.ts
> +  private findNode<T extends ITreeNodeObject>(
Fixed! `getTreeNodeObject` was a bit less generic, but I updated it's signature and removed `findNode`

2023-02-17 12:20 UTC, coroiu commented on apps/web/src/vault/individual-vault/vault.component.ts
> +        this.activeFilter = activeFilter;
Hmm yeah, it's an empty placeholder until we get the correct filter from the bridge service. If we remove it then we'll definitely risk `null` error. On the other hand leaving it will result in ignored navigation attempts until all the data has loaded and the bridge service is able to search through the tree nodes. I don't think this is a new issue though, it has probably been like this for a while. Not sure if even is an issue in practice, since if there is no data loaded then there is nowhere for the user to navigate to.

2023-02-17 12:22 UTC, coroiu commented on apps/web/src/vault/individual-vault/vault.component.ts
> -    this.vaultItemsComponent.showAddNew = !this.activeFilter.isDeleted;
Hmm I thought I explicitly checked this.

2023-02-17 13:14 UTC, coroiu commented on apps/web/src/vault/individual-vault/vault.component.ts
> -    this.vaultItemsComponent.showAddNew = !this.activeFilter.isDeleted;
Fixed! Moved the logic into a getter in `vault-items`. Org vault extends the individual vault component so the fix is automatically applied there.

2023-02-17 13:15 UTC, coroiu commented on apps/web/src/vault/org-vault/vault.component.ts
> -    this.vaultItemsComponent.showAddNew = !this.activeFilter.isDeleted;
Like mentioned above org vault extends the individual vault component so the fix is automatically applied here as well.

2023-02-17 14:06 UTC, coroiu commented on apps/web/src/vault/individual-vault/vault-filter/components/vault-filter.component.ts
> -  protected async removeInvalidFolderSelection(folders: FolderView[]) {
- `All items` is now properly selected. There is no longer a separate URL for it, instead a missing `type` parameter is interpreted as `All items`
- Folders are now properly deselected when changing organizations

2023-02-17 14:09 UTC, coroiu commented on apps/web/src/vault/org-vault/vault-filter/vault-filter.component.ts
> -  protected async removeInvalidCollectionSelection(collections: CollectionView[]) {
Are you sure that `Collections` heading should be selected by default? Clicking on `Collections` does not mean "show all items" instead it navigates to a page that only shows collections. I can agree that it's a bit confusing

2023-02-17 14:11 UTC, coroiu commented on apps/web/src/vault/individual-vault/vault-filter/services/routed-vault-filter.service.ts
> +          collectionId: filter.collectionId ?? null,
Fixed! I've updated the model to use `undefined` instead of `null` when creating the model

2023-02-17 14:17 UTC, coroiu commented on apps/web/src/vault/individual-vault/vault-filter/shared/models/routed-vault-filter-bridge.model.ts
> +      return;
Fixed!

2023-02-17 14:27 UTC, coroiu commented on apps/web/src/vault/individual-vault/vault-filter/shared/models/routed-vault-filter.model.ts
> +  type?: string;
Done! Had to add some typechecks and conversions but looks nice!

2023-02-17 14:34 UTC, coroiu commented
@eliykat Ticket already seems to exist [EC-517 [Tech Debt] Refactor Vault Filter in Browser and Desktop](https://bitwarden.atlassian.net/browse/EC-517)

2023-02-17 14:38 UTC, coroiu commented on apps/web/src/vault/individual-vault/vault-filter/services/routed-vault-filter-bridge.service.ts
> +export class RoutedVaultFilterBridgeService {
Instead of a TD ticket I added a task to the VVR story instead [EC-208 [Admin Console] Add Filters under Left Nav](https://bitwarden.atlassian.net/browse/EC-208)

2023-02-20 02:00 UTC, eliykat commented on apps/web/src/vault/individual-vault/vault-filter/services/routed-vault-filter-bridge.service.ts
> +export class RoutedVaultFilterBridgeService {
Looks good, and serves me right for not reading your PR description properly 🙈

2023-02-20 02:07 UTC, eliykat commented on apps/web/src/vault/individual-vault/vault-filter/services/routed-vault-filter.service.ts
> +        if (["favorites", "login", "card", "identity", "note"].includes(type)) {
No `"trash"`?

Suggestion: instead of declaring this as a type and then separately creating an array of possible values, we could declare the array _first_ and then derive the type from it.

2023-02-20 02:15 UTC, eliykat commented on apps/web/src/vault/individual-vault/vault-filter/services/routed-vault-filter.service.ts
> +        if (["favorites", "login", "card", "identity", "note"].includes(type)) {
No `"trash"`?

Suggestion: instead of declaring this as a type and then separately creating an array of possible values, we could declare the array _first_ (as the source of truth) and then derive the type from it. Then they can never get out of step, and you have both a runtime representation and a type system representation.

[Here's an example](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhgJwTAvDA2gcgGYhJgGhkwCNFMBdeCGUSKAbgCgmAbAU1gFsBPANUQAuGFB4AHdiGzwk6MAFcuJdggrNeA5Ghx5M6-olTEyCPUw2HtZAF5mgA) of deriving a union type from an array, based on [this comment](https://github.com/microsoft/TypeScript/issues/20965#issuecomment-1001243191).

Also, if this `if` statement allows all possible values of the type, TS _might_ do some magical type narrowing for you, which would make the `as RoutedVaultFilterItemType` cast in the next line unnecessary. I'm less sure on that though.

2023-02-20 02:15 UTC, eliykat commented on apps/web/src/vault/individual-vault/vault-filter/services/routed-vault-filter.service.ts
> +        if (["favorites", "login", "card", "identity", "note"].includes(type)) {
Lastly, it might be tidier to move this to its own private helper method, but I'll leave that totally up to you as to whether you think it's worth doing.

2023-02-20 02:15 UTC, eliykat commented on apps/web/src/vault/individual-vault/vault-filter/services/routed-vault-filter-bridge.service.ts
> +            node: { id: "trash", name: "", icon: "", type: "trash" },
lgtm but I'll let @jlf0dev resolve the thread when he's happy

2023-02-20 02:22 UTC, eliykat commented on apps/web/src/vault/individual-vault/vault-filter/services/vault-filter.service.ts
> +  protected buildCipherTypeTree(): Observable<TreeNode<CipherTypeFilter>> {
Yep makes sense to me!

2023-02-20 02:22 UTC, eliykat commented on apps/web/src/vault/individual-vault/vault-filter/shared/models/routed-vault-filter-bridge.model.ts
> +      return;
Ah so it's a style preference ;) whereas I love ternary assignments for how succinct they are - provided the logic isn't too complex.

2023-02-20 02:25 UTC, eliykat commented on apps/web/src/vault/individual-vault/vault-filter/shared/models/routed-vault-filter.model.ts
> +  type?: string;
I like it! I've left a separate comment re: some suggested improvements.

2023-02-20 02:30 UTC, eliykat commented on apps/web/src/vault/individual-vault/vault-filter/services/routed-vault-filter.service.ts
> +        if (["favorites", "login", "card", "identity", "note"].includes(type)) {
Update: the `trash` filter isn't working for me, maybe because it's omitted here?

2023-02-20 02:43 UTC, eliykat commented on apps/web/src/vault/individual-vault/vault-filter/components/vault-filter.component.ts
> -  protected async removeInvalidFolderSelection(folders: FolderView[]) {
This looks great! There is still one minor change in behaviour: currently if you select a folder or collection filter, `All items` is not selected, but now it is. I think that makes sense though, given that no item type filter is being applied within the folder/collection. So I'm not worried about it, just thought I'd mention it. Please mark as resolved if you're fine with it.

2023-02-20 02:47 UTC, eliykat commented on apps/web/src/vault/org-vault/vault-filter/vault-filter.component.ts
> -  protected async removeInvalidCollectionSelection(collections: CollectionView[]) {
> Are you sure that Collections heading should be selected by default?

Yep, I'm comparing against current behaviour in prod - go check it out.

You can also see that it's defined as the [default filter](https://github.com/bitwarden/clients/blob/master/apps/web/src/vault/org-vault/vault-filter/vault-filter.component.ts#L75) in the org vault component, which is referred to in this method.

2023-02-20 03:38 UTC, eliykat commented on apps/web/src/vault/individual-vault/vault-filter/services/routed-vault-filter.service.ts
> +          collectionId: filter.collectionId ?? null,
Thanks for the explanation! Makes sense to me. I expect that allowing `undefined` will be most useful when we're actually using `RoutedVaultFilterService` directly from components, whereas right now it's not immediately apparent.

I'd appreciate if you found some way to (at least partially) document this in comments, particularly the `queryParamsHandling` behaviour.

2023-02-20 03:50 UTC, eliykat commented on apps/web/src/vault/individual-vault/vault.component.ts
> +        this.activeFilter = activeFilter;
I think I agree - it just means we have an activeFilter object with all the default params, which will give us the default filter selection that we want to display anyway. And it loads very quickly, given that it's just parsing queryParams, not a longer async action, so I'm not sure what the user could do in that time anyway.

2023-02-20 03:51 UTC, eliykat reviewed
I think I've responded to everything above :)

2023-02-20 09:14 UTC, coroiu commented on apps/web/src/vault/individual-vault/vault-filter/components/vault-filter.component.ts
> -  protected async removeInvalidFolderSelection(folders: FolderView[]) {
Yeah I think this makes more sense than the previous logic! :) Resolving!

2023-02-20 09:17 UTC, coroiu commented on apps/web/src/vault/org-vault/vault-filter/vault-filter.component.ts
> -  protected async removeInvalidCollectionSelection(collections: CollectionView[]) {
Ooooh, it's the default in the org vault but not in the individual vault, that's why I wasn't seeing it! I'll take another look at this!

2023-02-20 15:17 UTC, coroiu commented on apps/web/src/vault/org-vault/vault-filter/vault-filter.component.ts
> -  protected async removeInvalidCollectionSelection(collections: CollectionView[]) {
This was an unexpectedly hard problem to solve. The problem is that with URL state we're can't just create default states because we need to respect whatever is written in the URL.

Eventually I fixed this by writing some very specific logic in the `bridge-service` so that the translation works differently depending on which vault the user is visiting. It really isn't optimal. Hopefully this is just a side-effect of weird vault filter design choices and will go away in the vertical navigation.

2023-02-20 15:20 UTC, coroiu commented on apps/web/src/vault/individual-vault/vault-filter/services/routed-vault-filter.service.ts
> +          collectionId: filter.collectionId ?? null,
Added some clarification to the method doc

2023-02-20 15:21 UTC, coroiu commented on apps/web/src/vault/individual-vault/vault-filter/services/routed-vault-filter.service.ts
> +        if (["favorites", "login", "card", "identity", "note"].includes(type)) {
Fixed!

2023-02-20 23:38 UTC, eliykat commented on apps/web/src/vault/individual-vault/vault-filter/services/routed-vault-filter.service.ts
> +        if (["favorites", "login", "card", "identity", "note"].includes(type)) {
Ooh I like the user defined type guard! That's a good solution I think.

2023-02-21 00:21 UTC, eliykat requested changes

2023-02-21 00:21 UTC, eliykat commented on apps/web/src/vault/individual-vault/vault-filter/services/routed-vault-filter-bridge.service.ts
> -        if (filter.collectionId !== undefined && filter.collectionId === Unassigned) {
I don't want to sweat transitional code style too much, but there's a lot of nested conditional logic here which is getting difficult to parse, even just for code review. I suggest pulling it out into some private methods - probably just at the top level `if` statement, e.g.

```ts
let legacyFilter: VaultFilter;
if (filter.organizationIdParamType === "path") { // or the new helper method I mentioned in another comment
  legacyFilter = createLegacyFilterForAdminConsole(...)
else {
  legacyFilter = createLegacyFilterForEndUser(...)
}

return new RoutedVaultFilterBridge(...)
```

(or ternary `if` if it floats your boat)

2023-02-21 00:25 UTC, eliykat commented on apps/web/src/vault/org-vault/vault-filter/vault-filter.component.ts
> -  protected async removeInvalidCollectionSelection(collections: CollectionView[]) {
It's messy, but at least you've been able to isolate it to the bridge service. I'm not sure how default filter selection will work in VVR so I'm happy to leave that question until we're actually doing that work.

2023-02-21 08:48 UTC, coroiu commented on apps/web/src/vault/individual-vault/vault-filter/services/routed-vault-filter.service.ts
> +      filter.organizationIdParamType === "path"
Actually I think I'll remove this again, it was part of another idea I had and not necessary for this PR. I don't like the distinction between path and query and I want to get rid of it as quick as possible, but I think we'll know more during our vvr work

2023-02-21 08:52 UTC, coroiu commented on apps/web/src/vault/individual-vault/vault-filter/services/routed-vault-filter.service.ts
>            safeType = type as RoutedVaultFilterItemType;
Same here

2023-02-21 09:21 UTC, coroiu commented on apps/web/src/vault/individual-vault/vault-filter/services/routed-vault-filter.service.ts
> +      filter.organizationIdParamType === "path"
Done!

2023-02-21 09:23 UTC, coroiu commented on apps/web/src/vault/individual-vault/vault-filter/services/routed-vault-filter-bridge.service.ts
> -        if (filter.collectionId !== undefined && filter.collectionId === Unassigned) {
Fixed! (using ternary if 😏)

2023-02-21 23:28 UTC, eliykat commented on apps/web/src/vault/individual-vault/vault-filter/shared/models/routed-vault-filter-bridge.model.ts
> +      type = value?.node.id as RoutedVaultFilterItemType;
Oh yes I did, I forgot that I'd narrowed my diff to particular commit range 😅  I did review this as well though, all good

2023-02-21 23:42 UTC, eliykat commented on apps/web/src/vault/individual-vault/vault-filter/services/routed-vault-filter.service.ts
> +      filter.organizationIdParamType === "path"
Looks good!

2023-02-21 23:43 UTC, eliykat approved these changes
Great work! Let's get it to QA :shipit:

2023-02-23 21:31 UTC, eliykat approved these changes

2023-03-06 07:34 UTC, merged