Remove ctor initialization in session sync
bitwarden/clients pull request #4755
Opened 2023-02-14 22:27 UTC by MGibson1

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Removes ctor initialization from session syncer, which seems to never work as intended. From my testing this resolves PS-2457 and PS-2464.

2023-02-14 23:02 UTC, justindbaur requested changes

2023-02-14 23:02 UTC, justindbaur commented on apps/browser/src/decorators/session-sync-observable/session-syncer.spec.ts
>        }).toThrowError("ctor or initializer must be provided");
Should be "initializer must be provided"

2023-02-15 03:47 UTC, justindbaur approved these changes

2023-02-16 14:44 UTC, djsmith85 approved these changes
LGTM

2023-02-16 14:48 UTC, justindbaur approved these changes

2023-02-16 15:36 UTC, merged