[EC-1070] Enforce master password policy on login
bitwarden/clients pull request #4795
Opened 2023-02-17 01:30 UTC by shane-melton

## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Implement a new option for the Master Password policy to enforce requirements on existing users during login (on all clients). If the new option is enabled, whenever a user logs in, their master password will be evaluated against the organization's password requirements. If it fails the requirements, the user will be redirected to the update password page and **forced** to update to a new master password that meets the requirements. The same requirements are also checked during an a vault unlock with master password to ensure existing SSO members are also compliant with the organization's policy.

> TODO: Verify implementation works with 2FA and modify as necessary

## Code changes

See commit messages for specific details, but as an overview on some of the big changes.

### **login.component and the CLI login command** 

The base login component was updated to support checking the user's master password after successful login. The general flow is as follows:

1. User completes a successful login request.
2. Before navigating to the vault, check if the auth response has the `EnforceMasterPasswordPolicyOnLogin` flag set.
3. If set, fetch all master password policies that apply to the user. Otherwise, continue login as before.
4. Evaluate the user's master password against policies with "EnforceOnLogin" enabled.
5. If any policies fail, redirect the user to the update password page with details regarding which org's policy failed.
6. User updates their password to meet **all** organization policy requirements and is logged out.
7. User logs in with their new master password and is taken to the vault.

### **lock.component.ts** 

A similar flow is applied when unlocking the vault. However, as there is no auth response, the ` EnforceMasterPasswordPolicyOnLogin` is not checked and policies are evaluated during every unlock. 

> TODO: Look into how to improve this, so it doesn't apply on every unlock.

## Screenshots

<img width="518" alt="image" src="https://user-images.githubusercontent.com/8764515/219524625-9be5c9e1-0aa3-49c2-bcbe-6fdebbe0ecc1.png">

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-03-28 04:37 UTC, eliykat requested changes
Partial review only, but just so you have some feedback in the meantime.

2023-03-28 04:37 UTC, eliykat commented on libs/common/src/auth/login-strategies/password-login.strategy.ts
> +        }
Suggestion: this better expresses your meaning and doesn't require the stateService call:

```ts
        if (result.requiresCaptcha || result.requiresTwoFactor) {
          // Save the flag to this strategy for later use as the master password is about to pass out of scope
          this.forcePasswordResetOptions = resetOptions;
        } else {
          // Authentication was successful, save the force update password options with the state service
          await this.stateService.setForcePasswordResetOptions(resetOptions);
          result.forcePasswordReset = true;
          result.forcePasswordResetOptions = resetOptions;
        }
```

2023-03-28 04:37 UTC, eliykat commented on libs/common/src/auth/login-strategies/password-login.strategy.ts
> +        }
Relatedly: do we need `this.forcePasswordResetOptions`? I assume it's a temp location so that it doesn't prevent navigation to 2FA or captcha components. But the stateService flag is only enforced by `authGuard`, which doesn't apply to those components because the user isn't authed yet.

Could we just save it to stateService here in all cases?

2023-03-29 04:36 UTC, eliykat requested changes
This is great work, despite the number of comments below. The only file I haven't reviewed yet is `login.command.ts` 💀 so I'll come back for that one, but plenty to action in the meantime.

2023-03-29 04:36 UTC, eliykat commented on libs/angular/src/auth/components/lock.component.ts
> +          (response as VerifyMasterPasswordResponse).masterPasswordPolicy
You should type the `apiService` method correctly rather than casting here.

2023-03-29 04:36 UTC, eliykat commented on libs/angular/src/auth/components/lock.component.ts
> +      this.logService.error(e);
Are you concerned about anything in particular here? None of these operations seem very risky.

2023-03-29 04:36 UTC, eliykat commented on libs/angular/src/auth/components/lock.component.ts
> +    return userInput;
Here it is repeated again 😁

2023-03-29 04:36 UTC, eliykat commented on libs/angular/src/auth/components/lock.component.ts
> +    );
This consistent pairing of method calls suggests that we should calculate the password strength inside `evaluateMasterPassword`, instead of always calling one method and then the other. I feel like I've already thrown a few tech debt-y things at you though, so we can call it out of scope. Just mentioning 🌱

2023-03-29 04:36 UTC, eliykat commented on libs/common/src/auth/models/response/verify-master-password.response.ts
You already have a `MasterPasswordPolicyResponse` object, I don't see any point in wrapping it in another response object like this. Just return it directly.

2023-03-29 04:36 UTC, eliykat commented on libs/common/src/auth/login-strategies/login.strategy.ts
> +  protected masterPasswordPolicy: MasterPasswordPolicyOptions = undefined;
This is a reasonable solution, but I'm a little wary about (1) adding properties to the base class that are only used by 1 strategy, and (2) adding more potential side effects.

What do you think about returning the `response` object from `this.startLogIn` (as well as `AuthResult`), so that individual strategies can access it directly for anything else that they need to do?

2023-03-29 04:36 UTC, eliykat commented on libs/common/src/auth/login-strategies/password-login.strategy.spec.ts
> +  });
I don't think this test case is necessary - you cover the 2 code flows effectively in the test cases below.

2023-03-29 04:36 UTC, eliykat commented on libs/common/src/auth/login-strategies/password-login.strategy.spec.ts
> +  it("saves force password reset options in state when the master password is weak and login was successful", async () => {
I think you're overdescribing your test cases - it just needs to describe the unit of behaviour, not summarize your `expect` statements.

I suggest: "given a successful login, forces the user to change their master password when it does not meet Master Password policy requirements"

2023-03-29 04:36 UTC, eliykat commented on libs/common/src/auth/login-strategies/password-login.strategy.spec.ts
> +  it("saves force password reset options to the strategy when the master password is weak and login requires 2FA", async () => {
Reword to match whatever you use for the above test case

2023-03-29 04:36 UTC, eliykat commented on libs/common/src/auth/login-strategies/password-login.strategy.spec.ts
Great work writing test cases! 👏 

I think the one case you haven't covered is the simple one: does _not_ force the user to change their master password if it meets Master Password policy requirements. (Or I guess if there are none?)

2023-03-29 15:59 UTC, shane-melton commented on libs/common/src/auth/login-strategies/password-login.strategy.ts
> +        }
Great suggestion, that is a lot clearer, thanks!

> Could we just save it to stateService here in all cases?

That was the plan originally, however, the `stateService` call is saving the `forcePasswordResetOptions` to the **_active_** account - which isn't available/created yet if 2FA or captcha prevented a successful auth initially.

2023-03-29 16:05 UTC, shane-melton commented on libs/common/src/auth/models/domain/force-password-reset-options.ts
> +export class ForcePasswordResetOptions {
Fair point; the options originally had other details/fields related to the organization that caused the reset. However, now that we've decided against that functionality, I agree that its overkill and the enum can be used alone and will get that updated.

2023-03-29 22:59 UTC, shane-melton commented on libs/common/src/auth/models/domain/auth-result.ts
> +  forcePasswordResetOptions?: ForcePasswordResetOptions = undefined;
Done, I added the `None=0` option

2023-03-29 23:22 UTC, shane-melton commented on apps/browser/src/auth/popup/update-temp-password.component.ts
Hmm, I would have thought I would have caught this myself; it was tedious updating the constructor in all 4 places and fixing the imports after merge conflicts 🤦

2023-03-29 23:25 UTC, shane-melton commented on libs/common/src/auth/login-strategies/password-login.strategy.ts
> +      (await this.stateService.getIsAuthenticated()) &&
I was able to tell from the `AuthResult`, but I don't believe we can use `setForcePasswordOptions` any earlier as it currently requires an auth'd and active account before it can save the reason.

2023-03-30 17:24 UTC, shane-melton commented on apps/web/src/app/admin-console/organizations/policies/master-password.component.ts
> +    enforceOnLogin: [null],
Done!

2023-03-30 17:27 UTC, shane-melton commented on apps/web/src/app/admin-console/organizations/policies/master-password.component.html
> +  </div>
Good point, updated to use the CL and removed Bootstrap; makes it a lot easier to read now too

2023-03-30 18:01 UTC, shane-melton commented on libs/angular/src/services/jslib-services.module.ts
> +        EncryptService,
Looks like it was implicitly depended on via the CryptoService, but once I added the password generation service as a dependency I started getting unexpected dependency errors.

2023-03-30 20:10 UTC, shane-melton commented on apps/web/src/auth/update-temp-password.component.html
> +          <div class="form-group" *ngIf="requireCurrentPassword">
I started to use the `UserVerificationComponent`, but I discovered it still uses Bootstrap classes which clashes with the new CL form controls I switched over to. It also does not allow modifying the input label, which we'd likely want to modify to be "Current master password" instead of simply "Master password" to avoid any potential confusion.

We can look into updating that component as well, but that does seem to even further increase the number of places this PR touches, so I'm personally leaning towards leaving that for another tech debt ticket. 

I was still able to start using the `Verification` object instead and make use of the `UserVerificationService.buildRequest()` method to hash the password / build the initial `PasswordRequest`. So whenever the `UserVerificationComponent` is updated to CL, we can very simply drop it in here.

2023-03-30 20:11 UTC, shane-melton commented on libs/angular/src/auth/components/update-temp-password.component.ts
> +    );
Per my other comment above,  I switched to this method, but held off on using the `UserVerificationComponent` for now as it doesn't use the CL yet.

2023-03-30 20:30 UTC, shane-melton commented on libs/angular/src/auth/components/update-temp-password.component.ts
I believe if we were to align these flows, we should require the current master password for both scenarios, as this page can technically be accessed at _any time_ during an authorized session. 

From my understanding, the admin reset flow didn't require the current password because the endpoint was only allowed for users that have the admin `ForcePasswordReset` flag set to `true`. So, not just any user could use the page to update their password. 

When I last checked in with Product about this they were okay with requiring the current password again for weak password (to avoid needing to temporarily store the master password hash in memory after login). I'll reach out again to see how they feel about requiring it again for admin password reset as well.

2023-03-30 20:42 UTC, shane-melton commented on libs/angular/src/auth/components/lock.component.ts
> +      this.logService.error(e);
Not particularly haha, but helping avoid completing locking users out for any unforeseen bugs in an ancillary feature seemed like a good idea

2023-03-30 20:49 UTC, shane-melton commented on libs/angular/src/auth/components/lock.component.ts
> +    );
Yep, totally agree; I actually started doing that earlier, but then ran into a circular dependency between the `PolicyService` and `PasswordGenerationService`. Which would have required even more refactoring to separate/clean those up, so I agree its probably out of scope for this PR.

2023-03-31 00:04 UTC, eliykat commented on apps/web/src/auth/update-temp-password.component.html
> +          <div class="form-group" *ngIf="requireCurrentPassword">
Sounds good to me, thanks for investigating! `UserVerificationComponent` is not strictly required here anyway - it covers the case where a user may be using Key Connector (so you need to send them an OTP instead of asking for their MP), but this flow only applies to users with an MP. So it is optional.

2023-03-31 00:06 UTC, eliykat commented on libs/angular/src/auth/components/update-temp-password.component.ts
Ok that's a fair point. Happy to leave it as is, just wanted to make sure there was a reason for the different behaviour.

2023-04-03 22:59 UTC, shane-melton commented on libs/common/src/auth/login-strategies/login.strategy.ts
> +  protected masterPasswordPolicy: MasterPasswordPolicyOptions = undefined;
Fair points; I went ahead with your idea of also returning the `response` from `this.startLogIn` and letting the password login strategy handle retrieving the master password policy details itself.

2023-04-03 23:02 UTC, shane-melton commented on libs/common/src/auth/login-strategies/password-login.strategy.spec.ts
Thanks! I updated the test names and added the additional test cases for when a password meets the requirements and when there no policies enforced on login.

2023-04-03 23:05 UTC, shane-melton commented on libs/common/src/auth/login-strategies/password-login.strategy.ts
> +    return userInput;
I updated the `passwordStrength` method to support accepting an optional `email` that will be parsed/split and added to the list of user inputs internally. This let us remove most of these repeated `getPasswordStrengthUserInput()` that dealt with the user's email.

2023-04-03 23:06 UTC, shane-melton commented on libs/common/src/auth/models/response/master-password-policy.response.ts
> +  requireSpecial = false;
Removed those default values

2023-04-03 23:06 UTC, shane-melton commented on apps/browser/src/auth/popup/update-temp-password.component.html
> +    <div class="box">
Done!

2023-04-03 23:07 UTC, shane-melton commented on apps/web/src/auth/update-temp-password.component.html
> +              name="MasterPasswordHash"
Fixed

2023-04-03 23:07 UTC, shane-melton commented on apps/web/src/auth/update-temp-password.component.html
Updated to CL

2023-04-03 23:07 UTC, shane-melton commented on libs/angular/src/auth/components/update-temp-password.component.ts
> +      }
Removed and using form validation instead

2023-04-03 23:07 UTC, shane-melton commented on libs/angular/src/auth/components/update-temp-password.component.ts
> +      }
Removed

2023-04-03 23:33 UTC, shane-melton commented on libs/angular/src/auth/components/lock.component.ts
> +    return userInput;
Removed/fixed in password generation service

2023-04-04 00:13 UTC, shane-melton commented on apps/desktop/src/app/app.component.ts
> +              this.router.navigate(["update-temp-password"]);
I agree that keeping everything in the `AuthGuard` would be most ideal; however, account switching in the desktop app doesn't reevaluate the guard when switching on the same page (e.g. the vault page). 

For example, if your on the vault page on an unlocked account, and then switch to an account that has the `forcePasswordResetReason` set in storage, the call to `this.router.navigate(["vault"]);` here would not trigger the `AuthGuard` which should redirect to the temp password page. I tried using the `this.router.navigate(["vault"], {onSameUrlNavigation: "reload"});` as well, to see if that would trigger the `AuthGuard` but didn't have any luck.

I'm definitely open to any other idea to not need this code, but it seemed like the most straightforward option to me.

2023-04-04 00:15 UTC, shane-melton commented
@eliykat Thanks for the review! I believe I've addressed all your feedback and this should be ready for another go!

2023-04-04 03:42 UTC, eliykat requested changes

2023-04-04 03:42 UTC, eliykat commented on apps/web/src/auth/update-temp-password.component.html
> +          </button>
You're missing the spinner that shows after the form has been submitted, during the async action. There's a directive for this you can find in the component library: `bit-action.directive.ts`.

2023-04-04 03:42 UTC, eliykat commented on apps/web/src/auth/update-temp-password.component.html
It pains me to see all the `[(ngModel)]` directives, but I think we need to draw the line somewhere 😂

2023-04-04 03:42 UTC, eliykat commented on libs/common/src/tools/generator/password/password-generation.service.ts
> +      .split(/[^A-Za-z0-9]/);
There's a subtle change in logic here with the `if` statement being removed. Will it still work if `atPosition` is `-1`?

2023-04-04 03:42 UTC, eliykat commented on libs/angular/src/shared/components/password-strength/password-strength.component.ts
> +      [...(this.name?.trim().toLowerCase().split(" ") ?? [])],
This unpacking looks unnecessary, you're just wrapping it in a new array anyway. `split` returns an array, so can you do this?

```suggestion
      this.name?.trim().toLowerCase().split(" ") ?? [],
```

Also, does `split` ever return null? do you need the null coalescing?

2023-04-04 03:42 UTC, eliykat commented on libs/common/src/tools/generator/password/password-generation.service.ts
> +    email: string = null
Consider swapping the order of these, `email` is always used, `userInputs` is rarely used. `passwordStrength(password, email)` is better than `passwordStrength(password, null, email)`. Just make sure to swap all the calling locations.

2023-04-04 03:42 UTC, eliykat commented on libs/common/src/tools/generator/password/password-generation.service.ts
> +  passwordStrength(
Please add a jsdoc comment here explaining the parameters, in particular that the email should be unparsed.

I also suggest `emailInput` or `emailUserInput` for consistency, given that it's a subset of the `userInputs`.

2023-04-04 03:42 UTC, eliykat commented on libs/common/src/tools/generator/password/password-generation.service.ts
Please make sure to flag this for QA, the logic looks sound but definitely something I want to be careful about.

2023-04-04 03:42 UTC, eliykat commented on libs/common/src/auth/login-strategies/password-login.strategy.ts
> +    const mpPolicies = this.getMasterPasswordPolicyOptionsFromResponse(identityResponse);
I liked `MasterPasswordPolicy` 😞 We should prefer full names over abbreviations, and it is 1 policy (even though it's an amalgamation of policies).

2023-04-04 03:42 UTC, eliykat commented on libs/common/src/auth/login-strategies/login.strategy.ts
> +  protected masterPasswordPolicy: MasterPasswordPolicyOptions = undefined;
I think this turned out well!

2023-04-04 04:01 UTC, eliykat reviewed
Todo: review the CLI changes

2023-04-04 23:20 UTC, shane-melton commented on apps/web/src/app/admin-console/organizations/policies/master-password.component.ts
> +    enforceOnLogin: new FormControl<boolean>(null),
Hmm, I always seem to run into issues when I don't use explicit `FormControl` definitions in `formBuilder.group<>()` with the `ControlsOf` interface as the generic type. But, after playing around with it again, I did find that if you specify the type on the fromGroup property (instead of in `groups<>()`) Typescript no longer complains and we can use the shorthand version for form group definitions avoiding all of the explicit `FormControl`s. (And we keep all of the strong typing info everywhere)

2023-04-04 23:26 UTC, shane-melton commented on apps/web/src/auth/update-temp-password.component.html
> +    <div class="tw-w-1/3">
Yep, its a fraction for one-third (33.33%) and is used to replace the bootstrap `col-4` which did essentially the same thing for its own 12 column system.

2023-04-04 23:41 UTC, shane-melton commented on libs/common/src/tools/generator/password/password-generation.service.ts
> +      .split(/[^A-Za-z0-9]/);
Oh good catch; it does still work, because `.substring()` will clamp `-1` -> `0` and simply return nothing (just like the original if statement did).

But, that's not immediately clear (unless you look up or know how `.substring()` behaves), so I went ahead and added the conditional back

2023-04-04 23:46 UTC, shane-melton commented on libs/angular/src/shared/components/password-strength/password-strength.component.ts
> +      [...(this.name?.trim().toLowerCase().split(" ") ?? [])],
Ah, yep, that's unnecessary unpacking. 

I wasn't worried about `split` returning null, but the `this.name?` could have been. However, looking again, we can just pass in null for `userInputs` anyway as `passwordStrength` safely handles the null case.

2023-04-05 00:01 UTC, shane-melton commented on libs/common/src/tools/generator/password/password-generation.service.ts
> +  passwordStrength(
Done!

2023-04-05 00:17 UTC, shane-melton commented on apps/desktop/src/app/app.component.ts
> +              this.router.navigate(["update-temp-password"]);
Unfortunately that didn't work with setting it to `always`. It appears **no** navigation event is being triggered because it is the same path/params and skips the guards entirely.

2023-04-05 00:20 UTC, shane-melton commented on libs/common/src/auth/login-strategies/password-login.strategy.ts
> +    const mpPolicies = this.getMasterPasswordPolicyOptionsFromResponse(identityResponse);
Abbreviation removed

2023-04-05 00:54 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/policies/master-password.component.html
Update: yes, please maintain all `id` attributes on form items.

2023-04-05 18:06 UTC, shane-melton commented on apps/web/src/app/admin-console/organizations/policies/master-password.component.html
Fixed!

2023-04-05 18:29 UTC, shane-melton commented on libs/components/src/form-field/error.component.ts
> +        return this.i18nService.t("inputMaxValue", this.error[1]?.max);
Updated the full example form story to include a new input with min/max validatiors.

2023-04-05 18:53 UTC, shane-melton commented on apps/web/src/auth/update-temp-password.component.html
> +          </button>
Spinner added with `[loading]="form.loading"`. We should be able to get rid of the old `form.loading` and use the `bitFormButton` directive once the base change password component is updated to use reactive forms (plus we'll be able to remove all those `[(ngModel)]` directives)

2023-04-05 18:55 UTC, shane-melton commented on apps/web/src/auth/update-temp-password.component.html
Totally agree, I briefly looked at updating it to a reactive form, but it would require updating the base password change component and that touches a lot of other areas 😞

2023-04-05 21:48 UTC, shane-melton commented on libs/angular/src/auth/components/update-temp-password.component.ts
>      }
The state service will always return `None` so there should be no concern for `undefined`. 

And good point, I originally kept it for "backwards compatibility" in case there was some odd way of directing a user to the component; but I did another search and don't see anywhere that could happen. So, I went ahead an updated the check for `None` to redirect the user home `/` (which will handle if they're authed, locked, etc and take them to the right place)

2023-04-07 02:54 UTC, eliykat commented on libs/common/src/tools/generator/password/password-generation.service.ts
> +      .split(/[^A-Za-z0-9]/);
I thought the same thing, no harm in being explicit here.

2023-04-07 03:20 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/policies/master-password.component.ts
> +    enforceOnLogin: new FormControl<boolean>(null),
I meant this, which also works:

```ts
  data = this.formBuilder.group<ControlsOf<MasterPasswordPolicyOptions>>({
    minComplexity: new FormControl(null),
    minLength: new FormControl(null, [Validators.min(Utils.minimumPasswordLength)]),
    requireUpper: new FormControl(null),
    requireLower: new FormControl(null),
    requireNumbers: new FormControl(null),
    requireSpecial: new FormControl(null),
    enforceOnLogin: new FormControl(null),
});
```

But you made it work without the `FormControl` definitions, which is probably better again!

2023-04-07 04:00 UTC, eliykat requested changes

2023-04-07 14:04 UTC, jlf0dev reviewed
As a whole this is looking really good to me. @eliykat has some great feedback so I'll let him handle the final approval 👍

2023-04-11 20:52 UTC, shane-melton commented on apps/cli/src/auth/commands/login.command.ts
> +          `Your master password does not meet one or more of your organization policies. In order to access the vault, you must update your master password now via the web vault. You have been logged
Backticks were left over from when I was putting the organization name in the message. Switched back to quotes as its no longer needed.

2023-04-11 20:52 UTC, shane-melton commented on apps/cli/src/auth/commands/login.command.ts
> +    await this.syncService.fullSync(true);
Removed!

2023-04-11 20:52 UTC, shane-melton commented on apps/web/src/auth/update-temp-password.component.html
Fixed!

2023-04-11 20:55 UTC, shane-melton commented on apps/cli/src/auth/commands/login.command.ts
Thanks! That makes sense to me and I'll keep it in mind for future CLI work, but I think I'd like to leave this one alone for now in the interest of getting this through QA / merged sooner.

2023-04-12 00:31 UTC, eliykat approved these changes
Great work!

2023-04-13 14:16 UTC, djsmith85 approved these changes
Changes that affect files belonging to team-tools are looking good.

Although I'd like to think about extracting the password-strength-checking into it's own service as it's rarely needed and drags the big fat dependency of zxcvbn around.

2023-04-17 03:46 UTC, eliykat approved these changes

2023-04-17 14:35 UTC, merged