[PS-2390] Passing folder and collection id on import. LastPass import matching folders
bitwarden/clients pull request #4802
Opened 2023-02-18 13:33 UTC by aj-rosado

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
Passing some missing data as folder and collection Ids so that we can match the import folders and collections with existing collections.
Added possibility to LastPass import add to existing folders/collections when exists a groupingsid on the csv

## Code changes
- **lastpass-csv-importer.ts:** Added groupingid from csv file as folder or collection id
- **Other files:** Passing collections id, external id and folder id on requests.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-02-21 15:41 UTC, djsmith85 requested changes
@aj-rosado Nice work on this. Just some things to make the code cleaner and a request to discuss a detail with product

2023-02-21 15:41 UTC, djsmith85 commented on libs/common/src/vault/models/request/folder.request.ts
> +  id: string;
Please use the existing FolderWithIdRequest instead of extending FolderRequest

2023-02-21 15:41 UTC, djsmith85 commented on libs/common/src/models/request/collection.request.ts
> +  id: string;
Please create and use CollectionWithIdRequest analogue to FolderWithIdRequest and FolderRequest

2023-02-21 15:41 UTC, djsmith85 commented on libs/common/src/importers/bitwarden-json-importer.ts
>          const collection = CollectionWithIdExport.toDomain(c);
If we extend CollectionWithIdExport to have its own `toDomain` and `toView` methods, which set the Id, we won't need to set them here separately

2023-02-21 15:41 UTC, djsmith85 commented on libs/common/src/importers/bitwarden-json-importer.ts
>          const folder = FolderWithIdExport.toDomain(f);
If we extend FolderWithIdExport to have its own `toDomain` and `toView` methods, which set the Id, we won't need to set them here separately

2023-02-21 15:41 UTC, djsmith85 commented on libs/common/src/importers/lastpass-csv-importer.ts
> +      const groupingId = value.groupingid;
I know part of the task was to support this for Lastpass, but if we are starting to ask people to extend the source-file, we might as well come up with a standard-name that can be used with all importers and that gets used when detected: Something like `BWCollectionId`. Let's discuss this with product again.

2023-03-09 21:48 UTC, djsmith85 requested changes
@aj-rosado: Nice work. Just some small changes

2023-03-09 21:48 UTC, djsmith85 commented on libs/common/src/models/request/collection-with-id.request.ts
> +export class CollectionWithIdRequest {
This can be implemented in the same way FolderWithIdRequest is done. This ensures that the rest of the request is identical with the CollectionRequest if that ever gets extended.

2023-03-09 21:48 UTC, djsmith85 commented on libs/common/src/services/collection.service.ts
> +    collection.externalId = model.externalId;
Still not sure about including/mapping the externalId here. Maybe @eliykat or @differsthecat have some thoughts on it, as from what I can tell this was introduced for/by DirectoryConnector

2023-03-10 04:16 UTC, eliykat commented on libs/common/src/services/collection.service.ts
> +    collection.externalId = model.externalId;
I'm not sure how DC would use it - afaik, DC only syncs users and groups, not collections. I could be wrong though.

My guess is that it's for the public API. i.e. we don't use it ourselves but it is available for third party integrations/scripts to use.

2023-03-13 13:09 UTC, differsthecat commented on libs/common/src/services/collection.service.ts
> +    collection.externalId = model.externalId;
It's been a while since I touched Directory Connector, but I'm not aware of collections being used in any way by it either.

2023-03-16 19:36 UTC, djsmith85 commented on libs/common/src/services/collection.service.ts
> +    collection.externalId = model.externalId;
@eliykat, @differsthecat Thank you both, for your input. As setting the externalId is not necessary to accomplish the import into folders/collection I've asked André to remove it. 
If we find another use for it, we might add it with a future PR.

2023-03-16 19:44 UTC, djsmith85 submitted a review, later dismissed
Changes are looking great.

2023-03-23 18:45 UTC, djsmith85 submitted a review, later dismissed

2023-04-05 18:11 UTC, djsmith85 approved these changes

2023-04-05 18:15 UTC, merged