[PM-1071] Display import-details-dialog on successful import
bitwarden/clients pull request #4817
Opened 2023-02-21 19:29 UTC by djsmith85

## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
Instead of relying on an error flow to request a password, the functionality is now provided by a mandatory callback which the `import.component` needs to provide to the `import.service`. This enables all/future importers to easily request a password by simply calling the callback.

On successful import, display a dialog, detailing the total amount of items imported and into which types these were imported.

## Code changes

**Tech Debt:**
- Prefer callback over error-flow to prompt for password (777f9c9)
- Fix up test cases (652c6d1)

**Feature work:**
- In preparation for the other dialogs (success, error)
  - Move file-password-prompt into dialog-folder (149dc0a)
- Add import success dialog (705e3c6)

## Screenshots
![image](https://user-images.githubusercontent.com/2670567/220440060-90d38faa-1682-4c6f-9dcb-158d00794656.png)

Requesting a review, by @bitwarden/dept-design to check on the UI, but also the used language.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-02-22 16:34 UTC, jtouchstonebw commented
@djsmith85 Do we need to show anything for item types that the user didn't attempt to import?

2023-02-23 12:43 UTC, djsmith85 commented
As requested by @danielleflinn, here's a quick video showing the import and import-success dialog:

![import-success](https://user-images.githubusercontent.com/2670567/220908876-d65875f2-dcaa-4532-8e3d-b9ddba80e181.gif)

@jtouchstonebw: Not sure if I follow. Everything that is present in the source file will be imported, so far the selected importer supports importing an item type.

2023-02-23 16:55 UTC, danielleflinn commented
@djsmith85 thanks for adding the recording! I agree with @jtouchstoneb. It would be beneficial to hide any item types from the table that have "0" imported (so Card, Secure Note, Identity, and Collection in your example). That way the user has less to review when looking at this confirmation. This will also keep the modal tidier when we expand to additional or custom item types.

2023-02-23 17:16 UTC, djsmith85 commented
@danielleflinn, @jtouchstonebw Thank you for the feedback. With the same import example as above the dialog would look like this:

![image](https://user-images.githubusercontent.com/2670567/220980961-30e0d06f-69f7-47d1-b959-32369894c2c6.png)

2023-02-27 17:34 UTC, danielleflinn requested changes
This looks good to me, with a minor copy tweak

2023-02-27 17:34 UTC, danielleflinn commented on apps/web/src/locales/en/messages.json
> +    "message": "We were able to import a total of $AMOUNT$ items.",
"A total of $AMOUNT$ items were imported."

2023-02-27 19:42 UTC, danielleflinn approved these changes

2023-03-17 15:10 UTC, aj-rosado submitted a review, later dismissed
Looking great!

2023-03-20 13:38 UTC, MGibson1 commented on libs/common/src/importers/importer.ts
> +  promptForPassword_callback: () => Promise<string>;
I don't like adding this to an interface implemented by every importer for exclusively bitwarden ones.

Why not just add this to the password protected constructor only?

2023-03-24 11:08 UTC, aj-rosado submitted a review, later dismissed

2023-04-03 19:29 UTC, MGibson1 reviewed
Nothing big, just a few questions

2023-04-04 10:45 UTC, djsmith85 commented on libs/importer/src/services/import.service.ts
> +  // BitwardenJsonImporter,
Nope, no good reason

2023-04-04 12:47 UTC, MGibson1 approved these changes

2023-04-06 13:27 UTC, aj-rosado submitted a review, later dismissed

2023-04-06 20:40 UTC, MGibson1 approved these changes

2023-04-06 20:41 UTC, merged