Fix last active (auto logout issue)
bitwarden/clients pull request #4835
Opened 2023-02-23 10:29 UTC by phyzical

## Type of change
```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
fixes #2482 

There is a bug where the lastActive is not updated unless the following window level functions occur
```
 this.ngZone.runOutsideAngular(() => {
      window.onmousedown = () => this.recordActivity();
      window.ontouchstart = () => this.recordActivity();
      window.onclick = () => this.recordActivity();
      window.onscroll = () => this.recordActivity();
      window.onkeypress = () => this.recordActivity();
    });
```

But for example bio metrics login does not trigger these.

initially i just added a event to trigger a scroll for successful bio metrics login which solved the issue but there was other users that reported they do not use bio metrics that had the issue so i went about replicating the recordActivity functionality on a successful login instead

I do feel this is a bit of a botch so i am open to better ways to solve this.

i tried exporting the existing recordActivity but i didn't have much luck.

P.S Great get started docs was able to replicate and see what caused the issue within 15 minutes 👍

2023-02-23 10:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitwarden/clients?pullRequest=4835) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bitwarden/clients?pullRequest=4835) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitwarden/clients?pullRequest=4835) it.</sub>

2023-02-28 05:54 UTC, phyzical commented on apps/browser/src/background/main.background.ts
> +
```suggestion
```

2023-02-28 05:54 UTC, phyzical commented
I had a thought that there might just be another window level on event we could leverage and looks like onblur seems to work well enough

2023-03-28 16:11 UTC, MGibson1 commented
I agree that `onblur` makes some sense here, but I'm confused about why this is ocuring in the first place. [We should be recording  activity on login/unlock already ](https://github.com/bitwarden/clients/blob/master/apps/desktop/src/app/app.component.ts#L159).

It's possible the `activeUserId` is still null at this stage while unlocking, but I would love to unwrap that and either include a fix for that null issue in this, or keep the #2482 open until that problem is solved.

What do you think @phyzical? Did you already investigate why `recordActivity` on login/unlock was not preventing process reload?

2023-03-29 01:30 UTC, phyzical commented
@MGibson1 hmm i dont think i checked specifically what that switch was reporting, but i can have a look this afternoon.

i wonder if ngRun is tied to the popup window being open maybe? so these logins close the window before the full swing of callbacks fire (total swing in the dark guess :D) 

But yeah ill have a closer scan around this piece of code as i don't remember seeing it when i was reviewing what could be the issue

2023-03-29 02:11 UTC, phyzical commented
@MGibson1  had a quick look, spent 5 minutes debugging why i couldnt see the event thats firing, 

and then realized this code linked is on the desktop client, is it expected that a state update on the desktop client should then update the state of the browser client? 

(also this code was added after i started looking into the issue and thats why i never saw it)

i will have to spend a bit more time to workout how to build the desktop client locally to verify the linked code fixes it or not

2023-03-30 15:51 UTC, MGibson1 commented
Oh my, I've been thinking about the desktop the _entire_ time. I'm sorry. No, the two are totally unrelated when it comes to activity recording 😳 .

What it means is that we want to add a similar activity recording to the unlock/log in messages in browser as well. Should be a copy-pasta.

2023-03-31 02:04 UTC, phyzical commented
i think thats what i did originally and felt it was a bit wrong :D @MGibson1 i will update the pr tonight if it isnt done already by then 👍

2023-04-01 03:02 UTC, phyzical commented
@MGibson1 alright should be done now (i hope) i had to pipe up the "unlocked" message to the root messageService as thats where all the lastActive logic was run from lmk if there was  better way to go about this

i assume this check failure is unrelated to my changes as i dont remember it last time i pushed

2023-04-10 17:56 UTC, MGibson1 requested changes
Thank you for updating this, and I'm sorry for the delay. I take full responsibility there. I think there's a better way to grab the unlock event, using observables, but otherwise this seems right on the money 🥳 .

---
#### pipeline failure stuff 
The sonarcloud thing is some static code analysis we're trying out for early detection of possible security risks. I actually don't have access to determine exactly what it's complaining about... Something I've brought up as a feedback item 👎 .

Codescene is just reporting potential areas of high mental overhead. Useful to determine whether something is going to need some refactoring or love soon/now.

Both of those seem safe to ignore for the moment.

2023-04-11 01:47 UTC, phyzical commented
@MGibson1 thanks for the hand hold, i think i have done it as suggested but i cant actually verify it as working due to a compilation error from master. i tried rejigging it to compile but no go.


![image](https://user-images.githubusercontent.com/5182053/231033450-7dec3885-aac2-4782-b5dc-663471c36b98.png)


lmk when this is resolved and i can test the changes to confirm it as working

2023-04-12 12:27 UTC, djsmith85 commented
That compiler error is from a [community PR](https://github.com/bitwarden/clients/pull/4479) which I merged recently. This only seems to come up locally and should go away once I get a chance to finish https://github.com/bitwarden/clients/pull/5070. The import/dependency then moves to libs/exporter instead of libs/importer.

2023-04-12 12:34 UTC, MGibson1 commented
Thank you @djsmith85!

For now, just replace the line with

```typescript
//eslint-disable-next-line
import { BitwardenPasswordProtectedFileFormat } from "../../../importer/src/importers/bitwarden/bitwarden-password-protected-types";
```

and you should be rocking and rolling. Fair warning: don't want to commit that, though

2023-04-13 14:04 UTC, MGibson1 commented
That's odd. You're right there are no errors there but surely if nothing is produced that's an error... Frustrating.

2023-04-19 09:31 UTC, djsmith85 commented
@phyzical, @MGibson1 #5070 has been reviewed and merged into master

2023-04-19 10:21 UTC, phyzical commented
@djsmith85 thanks for the heads up, but still seem to be getting a bunch of errors relating to popup scss?

```
> @bitwarden/browser@2023.3.1 build /Users/phyzical/Sites/phyzical-clients/apps/browser
> webpack

Building Manifest Version 2 app
==================================================
envConfig
{
  "dev_flags": {},
  "flags": {
    "showPasswordless": true
  },
  "devFlags": {
    "storeSessionDecrypted": false,
    "managedEnvironment": {
      "base": "https://localhost:8080"
    }
  }
}
==================================================
main:
  assets by path _locales/ 3.8 MiB 58 assets
  assets by path images/ 66.5 KiB 21 assets
  assets by path popup/ 11.9 MiB 15 assets
  assets by path content/ 93.3 KiB 6 assets
  assets by path *.js 6.98 MiB
    asset vendor.js 3.54 MiB [compared for emit] (name: vendor) (id hint: commons2) 1 related asset
    + 2 assets
  assets by path notification/ 17.2 KiB
    asset notification/bar.js 8.97 KiB [compared for emit] (name: notification/bar)
    + 2 assets
  assets by path *.json 3.43 KiB
    asset manifest.json 2.94 KiB [compared for emit] [from: src/manifest.json] [copied]
    asset managed_schema.json 509 bytes [compared for emit] [from: src/managed_schema.json] [copied]
  asset background.html 161 bytes [compared for emit]
  orphan modules 479 KiB (javascript) 590 KiB (asset) 1.06 KiB (runtime) [orphan] 156 modules
  runtime modules 16.5 KiB 39 modules
  modules by path ../../ 7.44 MiB
    modules by path ../../node_modules/ 5.97 MiB 823 modules
    modules by path ../../libs/ 1.48 MiB
      modules by path ../../libs/common/src/ 1.05 MiB 419 modules
      modules by path ../../libs/angular/src/ 419 KiB 76 modules
      modules by path ../../libs/exporter/src/ 15.7 KiB
        modules by path ../../libs/exporter/src/vault-export/services/*.ts 14.8 KiB 2 modules
        ../../libs/exporter/src/vault-export/index.ts 110 bytes [built] [code generated]
        ../../libs/exporter/src/export-helper.ts 828 bytes [built] [code generated]
  modules by path ./src/ 1.48 MiB (javascript) 5.69 KiB (css/mini-extract) 179 modules
  fs (ignored) 15 bytes [built] [code generated]
  crypto (ignored) 15 bytes [built] [code generated]

  WARNING in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss)
  Module Warning (from ../../node_modules/sass-loader/dist/cjs.js):
  Deprecation Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

  Recommendation: math.div($number, $number * 0 + 1) or calc($number / ($number * 0 + 1))

  More info and automated migrator: https://sass-lang.com/d/slash-div

  ../../node_modules/sweetalert2/src/scss/_core.scss 529:11  strip-units()
  ../../node_modules/sweetalert2/src/scss/_core.scss 531:13  @import
  ../../node_modules/sweetalert2/src/scss/_theming.scss 8:9  @import
  ../../node_modules/sweetalert2/src/sweetalert2.scss 4:9    @import
  src/popup/scss/plugins.scss 2:9                            @import
  src/popup/scss/popup.scss 11:9                             root stylesheet
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  WARNING in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss)
  Module Warning (from ../../node_modules/sass-loader/dist/cjs.js):
  Deprecation Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

  Recommendation: math.div(strip-units($swal2-icon-size), 5) or calc(strip-units($swal2-icon-size) / 5)

  More info and automated migrator: https://sass-lang.com/d/slash-div

  ../../node_modules/sweetalert2/src/scss/_core.scss 531:13  @import
  ../../node_modules/sweetalert2/src/scss/_theming.scss 8:9  @import
  ../../node_modules/sweetalert2/src/sweetalert2.scss 4:9    @import
  src/popup/scss/plugins.scss 2:9                            @import
  src/popup/scss/popup.scss 11:9                             root stylesheet
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  2 warnings have detailed information that is not shown.
  Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

  ERROR in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss) 7:36-118
  Module not found: Error: Can't resolve '@bitwarden/angular/src/scss/bwicons/fonts/bwi-font.svg' in '/Users/phyzical/Sites/phyzical-clients/apps/browser/src/popup/scss'
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  ERROR in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss) 8:36-118
  Module not found: Error: Can't resolve '@bitwarden/angular/src/scss/bwicons/fonts/bwi-font.ttf' in '/Users/phyzical/Sites/phyzical-clients/apps/browser/src/popup/scss'
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  ERROR in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss) 9:36-119
  Module not found: Error: Can't resolve '@bitwarden/angular/src/scss/bwicons/fonts/bwi-font.woff' in '/Users/phyzical/Sites/phyzical-clients/apps/browser/src/popup/scss'
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  ERROR in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss) 10:36-120
  Module not found: Error: Can't resolve '@bitwarden/angular/src/scss/bwicons/fonts/bwi-font.woff2' in '/Users/phyzical/Sites/phyzical-clients/apps/browser/src/popup/scss'
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  ERROR in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss) 11:36-122
  Module not found: Error: Can't resolve '@bitwarden/angular/src/billing/images/cards/visa-light.png' in '/Users/phyzical/Sites/phyzical-clients/apps/browser/src/popup/scss'
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  ERROR in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss) 12:36-122
  Module not found: Error: Can't resolve '@bitwarden/angular/src/billing/images/cards/amex-light.png' in '/Users/phyzical/Sites/phyzical-clients/apps/browser/src/popup/scss'
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  ERROR in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss) 13:36-129
  Module not found: Error: Can't resolve '@bitwarden/angular/src/billing/images/cards/diners_club-light.png' in '/Users/phyzical/Sites/phyzical-clients/apps/browser/src/popup/scss'
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  ERROR in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss) 14:36-126
  Module not found: Error: Can't resolve '@bitwarden/angular/src/billing/images/cards/discover-light.png' in '/Users/phyzical/Sites/phyzical-clients/apps/browser/src/popup/scss'
   @ ./src/popup/scss/popup.scs [...]

2023-04-20 10:27 UTC, phyzical commented
@MGibson1 after the fixes and fixing my node version i am able to confirm this fixes the issue

2023-04-20 10:33 UTC, phyzical commented
ah i see you requested id3 metadata not just the lyrics im not super familiar so ill have to do a bit more reading on this..

2023-04-20 12:50 UTC, MGibson1 requested changes

2023-04-20 12:50 UTC, MGibson1 commented on apps/browser/src/popup/app.component.ts
> +      });
Unfortunately `recordActivity` is async, which makes the subscription way more annoying. In general, we use [`concatMap`](https://www.learnrxjs.io/learn-rxjs/operators/transformation/concatmap) to handle awaiting things we need to subscribe to.

I think that's what we want here, too, because the order of the execution matters -- we don't want an earlier event to overwrite a later timestamp.

```suggestion
    this.stateService.activeAccountUnlocked$
      .pipe(
        filter((unlocked) => unlocked),
        concatMap(async () => {
          await this.recordActivity();
        }),
        takeUntil(this.destroy$)
      )
      .subscribe();
```

2023-04-21 01:23 UTC, phyzical commented
@MGibson1 ah yep thanks for the suggestion, implemented and retested as working

2023-04-21 11:18 UTC, MGibson1 approved these changes

2023-04-21 11:19 UTC, MGibson1 commented
Excellent, thanks! I'll get this set up for internal QA testing and merge once that's completed. Might be a little while, QA is a little swamped at the moment prepping for a release.

2023-05-03 19:19 UTC, MGibson1 commented
Good news! This just passed QA. Thank you so much on iterating on this. I think we ended up with a nice fix. I appreciate your work on it.

2023-05-03 19:26 UTC, kapitainsky commented
It took more than a year but if it works happy days. BW rocks.

2023-05-03 19:28 UTC, MGibson1 approved these changes

2023-05-03 19:28 UTC, merged