[AC-431] Add new organization invite process
bitwarden/clients pull request #4841
Opened 2023-02-23 16:29 UTC by r-tome

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-02-28 15:40 UTC, JaredSnider-Bitwarden approved these changes
LGTM 👍

2023-03-01 03:53 UTC, eliykat requested changes

2023-03-01 03:53 UTC, eliykat commented on apps/web/src/app/shared/loose-components.module.ts
> +    AcceptInitOrganizationComponent,
We shouldn't add components to `loose-components.module.ts` - I'd like this to be in an appropriate feature module (potentially with the standard `AcceptOrganizationComponent`). We probably can't do it right now, because Vince is currently reorganizing the Admin Console folder structure, but please make a follow-up tech debt task to move this afterwards.

2023-03-01 03:53 UTC, eliykat commented on apps/web/src/auth/accept-init-organization.component.html
> +<div class="mt-5 d-flex justify-content-center" *ngIf="loading">
This looks identical to `accept-organization.component.html` - can we just use that template? Reusing templates isn't great, but I think it's better than just duplicating it.

2023-03-01 03:53 UTC, eliykat commented on apps/web/src/auth/accept-init-organization.component.ts
> +      );
Nit: you don't need `async` / `await` here because you're chaining promises anyway (which is what `async` / `await` is sugar for) and you `await this.actionPromise` below.

2023-03-01 03:53 UTC, eliykat commented on libs/common/src/abstractions/organization-user/organization-user.service.ts
> +   * Accept an organization user invitation and initialize the organization
I think this needs a bit more explanation to make it clear this isn't the standard flow.

```suggestion
   * Accept an invitation to initialize and join an organization created via the Admin Portal **only**.
   * This only used once for the initial Owner, because it includes the organization's encryption keys.
   * This should not be used for organizations created via the Web client.
```

2023-03-01 03:53 UTC, eliykat commented on apps/web/src/auth/accept-init-organization.component.ts
> +    request.keys = new OrganizationKeysRequest(orgKeys[0], orgKeys[1].encryptedString);
I assume you're following the existing code in `OrganizationPlansComponent` (which is correct), but I think we can make this a bit more readable:

```ts
const [encryptedOrgShareKey, orgShareKey] = await this.cryptoService.makeShareKey();
const [orgPublicKey, encryptedOrgPrivateKey] = await this.cryptoService.makeKeyPair(orgShareKey);

request.key = encryptedOrgShareKey.encryptedString;
request.keys = new OrganizationKeysRequest(orgPublicKey, encryptedOrgPrivateKey.encryptedString);
```

You also need to create and encrypt the Default Collection for the org, see here: https://github.com/bitwarden/clients/blob/master/apps/web/src/app/settings/organization-plans.component.ts#L341-L345

2023-03-02 11:04 UTC, r-tome commented on apps/web/src/auth/accept-init-organization.component.ts
> +      );
If I don't `async` / `await` here then it doesn't wait for the response to show the success toast.

Is this is what you're referring to:
```
this.actionPromise = this.prepareAcceptRequest(qParams).then((request) => {
      this.organizationUserService.postOrganizationUserAcceptInit(
        qParams.organizationId,
        qParams.organizationUserId,
        request
      );
```

2023-03-09 01:44 UTC, eliykat commented on apps/web/src/auth/accept-init-organization.component.ts
> +      );
You need to return the return value of `postOrganizationUserAcceptInit` up the promise chain. Your arrow function has curly braces so it needs an explicit `return` statement, or just remove the curly braces.

Like this:

```this.actionPromise = this.prepareAcceptRequest(qParams).then((request) =>
      this.organizationUserService.postOrganizationUserAcceptInit(
        qParams.organizationId,
        qParams.organizationUserId,
        request
      )
    );
```

2023-03-09 01:51 UTC, eliykat commented on libs/common/src/abstractions/organization-user/organization-user.service.ts
> +   * This only used once for the initial Owner, because it includes the organization's encryption keys.
```suggestion
   * This is only used once for the initial Owner, because it also creates the organization's encryption keys.
```

Typo in my own suggestion 😁  and a slight tweak while I'm at it.

2023-03-09 01:51 UTC, eliykat commented on apps/web/src/auth/accept-init-organization.component.html
> +<div class="mt-5 d-flex justify-content-center" *ngIf="loading">
We decided to use the existing component as there was too much duplication here.

2023-03-09 03:21 UTC, eliykat requested changes
Minor feedback, otherwise looking good pending the server PR.
See also my responses above to any unresolved threads.

2023-03-09 03:21 UTC, eliykat commented on apps/web/src/auth/accept-organization.component.ts
> +    await this.stateService.setOrganizationInvitation(null);
This isn't new, but this seems risky to me:

* we call the async function `acceptFlow`, which reads the org invitation from `stateService`
* we clear the org invitation
* _then_ we `await` acceptFlow

Promises start executing immediately, so this could cause a race condition where the invitation is cleared before it's read.

Can we clear the org invitation after `await this.actionPromise` instead?

2023-03-09 15:42 UTC, r-tome commented on apps/web/src/auth/accept-init-organization.component.ts
> +      );
> Your arrow function has curly braces

That was it! Great suggestions here, thanks!

2023-03-10 03:22 UTC, eliykat commented on apps/web/src/auth/accept-organization.component.ts
> +    }
iirc, we only do this to check the user's password against the Master Password policy. But if the org is created via the Admin Portal it won't have a MP policy yet, so I thought this was OK to keep in the `acceptFlow` only. Let me know if there's another reason we need it here.

2023-03-10 10:41 UTC, r-tome commented on apps/web/src/auth/accept-organization.component.ts
> +    }
That is true. I couldn't get it working inside the `acceptFlow` promise so I just moved it to the `else` statement.

2023-03-23 08:09 UTC, eliykat approved these changes

2023-03-24 02:20 UTC, eliykat approved these changes

2023-03-30 10:37 UTC, merged