Adding the ability to edit service account name
bitwarden/clients pull request #4845
Opened 2023-02-23 18:46 UTC by cd-bitwarden

## Type of change

```
- [ ] Bug fix
- [ x ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Add ability to edit Service Account 

## Code changes
messages.json - adding 2 new strings for Edit Service Account and for Service Account Updated

overview.component.ts - adding new value to be passed into service account dialog
service-account-dialog.component.ts - making title dynamic based on editing/creating, hiding data that needs to be hidden.
service-account.service - adding new API call to call updateAsync for Service Accounts
service-accounts.component.ts - Adding ability to update in EditMode
## Screenshots

![image](https://user-images.githubusercontent.com/106776772/221001114-ba7566e2-f43a-4b19-9a17-b12c3a070860.png)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-02-24 10:27 UTC, Hinton reviewed
Some small comments. Mainly that we need to add a server api for fetching a single service account.

2023-02-24 10:27 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/dialog/service-account-dialog.component.ts
> +    )[0];
This would only work if the service account is first in the list. We should add an endpoint that returns a single service account.

2023-02-24 10:27 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/dialog/service-account-dialog.component.ts
> +    this.formGroup.setValue({ name: serviceAccount.name });
These do the exact same thing.

2023-02-24 10:27 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/dialog/service-account-dialog.component.html
> +      <div *ngIf="showProjectsSecretsInfo">
We should just remove the access from here for now. Access is managed after the service account is created. (Since it's not implemented yet and we don't have time)

2023-02-24 10:27 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/dialog/service-account-dialog.component.ts
> +      this.secrets = await this.secretService.getSecrets(this.data.organizationId);
We can remove these since we don't be doing access policies through the add dialog.

2023-02-24 10:27 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-accounts.component.ts
> +  async ngOnInit() {
There is no await here right? The await in the switchMap won't cause ngOnInit to return a promise.

2023-02-28 23:12 UTC, cd-bitwarden commented
@Hinton thank you for the suggestions, I've applied them, and have created a Server side PR as well for this item.

https://github.com/bitwarden/server/pull/2755

2023-03-01 15:12 UTC, Hinton commented on apps/web/src/locales/en/messages.json
> -  },
This seems unrelated?

2023-03-01 20:55 UTC, cd-bitwarden commented on apps/web/src/locales/en/messages.json
> -  },
added it back, this is a change from a different branch

2023-03-02 13:04 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/models/requests/service-account-update.request.ts
> +  name: EncString;
```suggestion
  name: string;
```

2023-03-02 13:04 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/dialog/service-account-dialog.component.ts
> +    this.formGroup.get("name").setValue(serviceAccount.name);
I personally prefer patchValue in this cases.

```suggestion
    this.formGroup.patchValue({ name: serviceAccount.name});
```

2023-03-02 13:04 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/dialog/service-account-dialog.component.ts
> +  showProjectsSecretsInfo = true;
SM-579 is reworking this, and we probably still want to show the project selector on edit so that users can move secrets.

2023-03-07 00:53 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/dialog/service-account-dialog.component.ts
> +  showProjectsSecretsInfo = true;
Just to be clear: other than just being able to edit the name, I now need to allow them to edit projects as well?

2023-03-07 09:19 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/dialog/service-account-dialog.component.ts
> +  showProjectsSecretsInfo = true;
Sorry, I mixed up projects and service accounts. Seems we don't have a task for removing the project list for service accounts yet but the figmas have been updated.

2023-03-07 09:59 UTC, Hinton commented on apps/web/src/locales/en/messages.json
> +  },
This already exists slightly above, line 5851-5854.

2023-03-07 10:02 UTC, Hinton reviewed
This looks good once we resolve the spinner, duplicated i18n and linting error.

2023-03-07 10:02 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/dialog/service-account-dialog.component.ts
> +  protected loading = false;
Loading isn't wired up to anything? Should we show a spinner on edit when loading is true?

2023-03-07 14:31 UTC, cd-bitwarden commented on apps/web/src/locales/en/messages.json
> +  },
Thanks!

2023-03-07 14:34 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/dialog/service-account-dialog.component.ts
> +  protected loading = false;
Yes i'll add the spinner when loading :)

2023-03-07 16:46 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/dialog/service-account-dialog.component.ts
> +  showProjectsSecretsInfo = true;
Im confused by your message, it sounds like there could be a typo, do you want me to remove the projects from the **service Account Dialog** completely?

2023-03-07 18:33 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/dialog/service-account-dialog.component.html
> +    <div *ngIf="loading" class="tw-text-center">
The convention is usually to place this inside the bitDialogContent. Not sure what happens if you have a diloag without title

2023-03-07 18:35 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/dialog/service-account-dialog.component.html
> +    <div *ngIf="loading" class="tw-text-center">
Yeah I noticed that haha 😆

2023-03-07 18:41 UTC, cd-bitwarden commented on apps/web/src/locales/en/messages.json
> +  "editServiceAccount":{
Should I add a description here?

2023-03-08 16:24 UTC, Thomas-Avery requested changes
A few things to address

2023-03-08 16:24 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/dialog/service-account-dialog.component.html
> +          <input formControlName="name" bitInput />
Looks like for projects we limit the name length to max of 1000. 

Should we be doing the same thing here? 

```
        <input formControlName="name" maxlength="1000" bitInput />
```

2023-03-08 16:24 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/models/requests/service-account-update.request.ts
> +}
This is the same model `ServiceAccountRequest`? 

Can we just use `ServiceAccountRequest`?

2023-03-08 16:24 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-account.service.ts
> +  }
If we use the same `ServiceAccountRequest` model looks like, we can just use `getServiceAccountRequest` as they do the same thing.

2023-03-08 16:24 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-accounts-list.component.html
> +        </button>
```suggestion
        <button type="button" bitMenuItem (click)="editServiceAccountEvent.emit(serviceAccount.id)">
          <i class="bwi bwi-fw bwi-pencil" aria-hidden="true"></i>
            {{ "editServiceAccount" | i18n }}
        </button>
```

I don't think we need the span here do we?

2023-03-08 16:24 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-accounts.component.ts
> +
We can just update our import statement to use the `service-account-dialog.component's` Operation Type. 

Then remove this `OperationType` declaration.

That way, we don't have to keep two enums in sync. 

```
import {
  OperationType,
  ServiceAccountDialogComponent,
  ServiceAccountOperation,
} from "./dialog/service-account-dialog.component";
```

2023-03-08 17:41 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/dialog/service-account-dialog.component.html
> +          <input formControlName="name" bitInput />
Sure I can add that, great idea 😄

2023-03-08 17:43 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/dialog/service-account-dialog.component.ts
> +      await await this.serviceAccountService.getByServiceAccountId(
oh gosh I wonder why lint didn't throw an error because of that 🤣

2023-03-08 17:51 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/models/requests/service-account-update.request.ts
> +}
yeah good idea :) I wasn't sure if we always wanted to make a specific update one even if it was the same.

2023-03-08 20:49 UTC, Thomas-Avery approved these changes
Looks good, thank you!

2023-03-08 20:50 UTC, merged