[SM-249] Adding detailed description of which secrets are unable to be deleted
bitwarden/clients pull request #4849
Opened 2023-02-23 22:48 UTC by cd-bitwarden

## Type of change

```
- [ ] Bug fix
- [ x ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Updating Modal for bulk delete error for Secrets

messages.json - adding messages relating to deleting secrets and encountering errors while doing so.
overview.component.cs - passing through orgId that's now needed
project-secrets.component.cs  - passing through orgId that's now needed
secret-delete.component.html - using a public variable instead of the data object now, because I had to make the data object private.
secret-delete.component.ts - logic for implementing openBulkStatusDialog
secret.service.ts - swapping from toast popup error to bulk status dialog error

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-02-27 09:49 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/secret.service.ts
> +          new EncString(element.objectDescription),
Not sure I completely follow. When making the delete request we should probably already know the secret name, so is there a reason for sending it back from the API instead of using the local values?

2023-02-28 23:19 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/secret.service.ts
> +          new EncString(element.objectDescription),
At the moment the only thing we require to call Delete is the secretIds, I'd prefer we keep it that way vs making us pass in the secret object. Doing it this way also keeps it consistent with how we utilize bulkOperationStatus in other areas. I can definitely be persuaded otherwise if you feel strongly about this 😄

2023-02-28 23:23 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/secret.service.ts
> +          new EncString(element.objectDescription),
I might be misunderstanding your suggestion though 🤔

2023-03-02 13:10 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/secret.service.ts
> +          new EncString(element.objectDescription),
Depends I guess. We've now tied `name` to the bulk delete responses. If we need more portions in the future that necessitates adding even more data to the response.

Since the previous response was essentially `[ { id, error } ]`, we could fairly easily just build a `Record<id, error>`, and join that with the entity clientside which gives access to the whole secret entity + the error. I don't know if we expect to add more information to this table in the future though.

2023-03-07 15:57 UTC, Thomas-Avery requested changes
Looks good overall. A few things to check with the dialog. 

It does look like maybe this was based off another PR as we have the removal of can write stuff in here too? 

Let's get the merge conflicts fixed and merge in the latest version of master, and I think that this will be updated and fixed.

2023-03-07 15:57 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-delete.component.ts
> +    this.dialogRef.close(this.secretIds);
If I'm understanding correctly, I don't believe we need to return a list of secret Ids on dialog close.

We could just do something like this

```
  get title() {
    return this.data.secrets.length === 1 ? "deleteSecret" : "deleteSecrets";
  }

  get submitButtonText() {
    return this.data.secrets.length === 1 ? "deleteSecret" : "deleteSecrets";
  }

  delete = async () => {
    const bulkResponses = await this.secretService.delete(this.data.secrets);

    if (bulkResponses.find((response) => response.errorMessage)) {
      this.openBulkStatusDialog(bulkResponses.filter((response) => response.errorMessage));
      this.dialogRef.close();
      return;
    }

    const message =
      this.data.secrets.length === 1 ? "softDeleteSuccessToast" : "softDeletesSuccessToast";
    this.platformUtilsService.showToast("success", null, this.i18nService.t(message));

    this.dialogRef.close();
  };
```

And remove 

```
secretIds = this.data.secrets.map((secret) => secret.id);
```


Note for this part:

```
    if (bulkResponses.find((response) => response.errorMessage)) {
      this.openBulkStatusDialog(bulkResponses.filter((response) => response.errorMessage));
      this.dialogRef.close();
      return;
    }
```

I do believe we need to add `this.dialogRef.close();` before returning and finishing execution, or we will have stacked dialogs.

2023-03-07 15:57 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-delete.component.html
> +    <div *ngIf="secretIds.length === 1">
Would need to change this if we modified bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-delete.component.ts


```
<div *ngIf="data.secrets.length === 1">
```

2023-03-07 20:19 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-delete.component.html
> +    <div *ngIf="secretIds.length === 1">
I did this check with a property on the .ts instead of on the html file

2023-03-07 20:33 UTC, merged