[SM-568] Delete service accounts
bitwarden/clients pull request #4881
Opened 2023-02-27 16:24 UTC by Hinton

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Implement delete service accounts. Uses the same logic as folders.

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-02-28 14:27 UTC, willmartian submitted a review, later dismissed
Looks good 🥳

 A couple of small items:

2023-02-28 14:27 UTC, willmartian commented on apps/web/src/locales/en/messages.json
> +      }
Placeholder should reference service account, not project.

2023-03-06 15:07 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/dialog/service-account-delete-dialog.component.ts
> +    return this.i18nService.t("deleteProjectInputLabel", this.dialogConfirmationMessage);
I agree.

2023-03-06 16:32 UTC, Thomas-Avery requested changes
Looks good, just a few minor symbol changes for readability.

2023-03-06 16:32 UTC, Thomas-Avery commented on apps/web/src/locales/en/messages.json
> +    "message":  "Deleting service account $PROJECT$ is permanent and irreversible.",
`Deleting service account $PROJECT$`

`Deleting service account $SERVICEACCOUNT$`

2023-03-06 16:32 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-account.service.ts
> +    this._serviceAccount.next(null);
`projects: ServiceAccountView[]`

Probably want to rename this to `serviceAccounts`. Reads like we are deleting projects.

2023-03-06 16:32 UTC, Thomas-Avery commented on apps/web/src/locales/en/messages.json
> +      "project": {
`project` -> `serviceAccount`

2023-03-06 16:32 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-account.service.ts
> +      bulkOperationStatus.name = projects.find((project) => project.id == element.id).name;
`project` -> `serviceAccount`

2023-03-06 17:17 UTC, Thomas-Avery requested changes

2023-03-06 17:17 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-account.service.ts
> +    );
```suggestion
    const serviceAccountIds = serviceAccounts.map((serviceAccount) => serviceAccount.id);
    const r = await this.apiService.send(
      "POST",
      "/service-accounts/delete",
      serviceAccountIds,
      true,
      true
    );
```

2023-03-06 17:17 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-account.service.ts
> +      bulkOperationStatus.name = serviceAccounts.find((project) => project.id == element.id).name;
```suggestion
      bulkOperationStatus.name = serviceAccounts.find((serviceAccount) => serviceAccount.id == element.id).name;
```

2023-03-06 19:09 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-account.service.ts
> +    );
Sorry, I mixed it up and thought we for some reason were fetching project ids for a service account.

2023-03-06 19:09 UTC, Thomas-Avery approved these changes
LGTM

2023-03-06 19:25 UTC, merged