[SM-572] Hide Project's People and Service accounts tabs based on permission
bitwarden/clients pull request #4885
Opened 2023-02-27 21:11 UTC by Thomas-Avery

## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

When a user just has read access to the project, don't display “People” and “Service accounts” tabs.

## Code changes

- bitwarden_license/bit-web/src/app/secrets-manager/projects/project/project.component.html
bitwarden_license/bit-web/src/app/secrets-manager/projects/project/project.component.ts

Display tabs if the user has write permission to the project.

## Screenshots

![image](https://user-images.githubusercontent.com/43214426/221685788-5eda3eb7-f903-43ce-8614-7e3bef50c7a2.png)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-02-27 21:16 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/projects/project/project.component.ts
> +  }
This isn't ideal because in the case where the user doesn't have write access, we're relying on the endpoint to throw an exception right now 404.

Another option is we could add a new endpoint to the server that takes a project ID and organization user ID and return true or false if they have write access.

2023-02-28 04:48 UTC, willmartian requested changes
Nice work! Two things:

2023-02-28 04:48 UTC, willmartian commented on bitwarden_license/bit-web/src/app/secrets-manager/projects/project/project.component.ts
> +        this.userHasWriteAccess = await this.userHasWriteAccessToProject(params.projectId);
Setting class properties in a pipe is a bad pattern. If you absolutely need to set a class property, do so in a subscription. 

Even better, let's think about how we can transform our existing observable into a new one.

```ts
this.project$ = ...

this.userHasWriteAccess$ = this.project$.pipe(
  switchMap(project => this.userHasWriteAccessToProject(project.id))
)
```

2023-02-28 04:48 UTC, willmartian commented on bitwarden_license/bit-web/src/app/secrets-manager/projects/project/project.component.ts
> +      this.validationService.showError(e);
Should we still return false on error?

2023-02-28 16:11 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/projects/project/project.component.ts
> +        this.userHasWriteAccess = await this.userHasWriteAccessToProject(params.projectId);
Swapped to a different server implementation, but thanks for the review :D

2023-02-28 16:50 UTC, willmartian commented on bitwarden_license/bit-web/src/app/secrets-manager/projects/project/project.component.ts
> +        this.userHasWriteAccess = await this.userHasWriteAccessToProject(params.projectId);
Np!!

2023-03-01 15:52 UTC, willmartian submitted a review, later dismissed

2023-03-01 16:44 UTC, willmartian approved these changes

2023-03-02 15:02 UTC, merged