[EC-1086] The Remove individual vault Enterprise Policy prevents Service Users and Provider admins from creating new vault items via the Provider Portal.
bitwarden/clients pull request #4909
Opened 2023-03-02 12:10 UTC by coroiu

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

When single vault policy was in effect the `organizationId` that the user belonged to was was always set for new ciphers. This was overwriting the client organization's id when a provider was trying to create new items in their clients vault.

## Code changes

Check that the `AddEditComponent` hasn't already been provided with an organization id before fetching `organizationId` from policy settings. Organization ids are only provided inside of the org-vault and the user is only allowed to access org-vaults of organizations they belong to or are otherwise allowed to administrate, as such the organization id must be a valid id if supplied.

## Screenshots

![image](https://user-images.githubusercontent.com/2285588/222407315-ddf760e4-d6bc-425e-b29e-9cceac7afa5a.png)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-03-07 04:28 UTC, eliykat requested changes
These components 🤯

2023-03-07 04:28 UTC, eliykat commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +      comp.organizationId = this.organization.id;
This is also set in the `additionalComponentParameters` callback passed in by `cloneCipher` and `addCipher`. If it's now included in the `defaultComponentParameters`, you can remove it from the additional params specified by those callers.

2023-03-07 12:22 UTC, coroiu commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +      comp.organizationId = this.organization.id;
True, fixed!

2023-03-07 23:48 UTC, eliykat approved these changes
Nice work!

2023-03-09 09:56 UTC, r-tome approved these changes
Looks great!

2023-03-09 14:20 UTC, merged