[PM-283] Fix Reports UI behavior for premium and free users
bitwarden/clients pull request #4926
Opened 2023-03-03 23:03 UTC by gbubemismith

## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

This fixes the behaviour of the reports UI for both premium and free users on a free organization where a report is clicked; users should be directed to an upgrade modal rather than the reports.
## Code changes

Refactored `apps/web/src/app/reports/pages/cipher-report.component.ts` by moving the `checkAccess` method to  `apps/web/src/app/reports/shared/report-list/report-list.component.ts` to reduce duplicated code and centralize all access checks in one component. Also added a click event to the `app-report-card` child component to check if the user's organization is a free organization. 

Additionally, the reference to the `checkAccess` method has been removed from all reports that previously needed it. This further simplifies the codebase by eliminating redundant references and streamlining the access control logic.

## Screenshots

https://user-images.githubusercontent.com/13024008/222851021-1ab44965-4a7c-4b2d-92e1-4b4c35802b72.mov

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-03-06 14:34 UTC, differsthecat reviewed
Is part of this work to make the reports cards when they are not accessible greyed out like it is for individual users?

![Screenshot 2023-03-06 at 9 30 19 AM](https://user-images.githubusercontent.com/8926729/223139883-887d6841-eed5-44e2-83b9-e67f4b974e86.png)

The Figma also shows an `Upgrade` badge on the cards as well for orgs in place of the Premium badge individual users in this state see.

2023-03-06 15:48 UTC, gbubemismith commented
@differsthecat thanks. I missed the upgrade label from Figma.

2023-03-08 14:31 UTC, differsthecat approved these changes
Looks good @gbubemismith !

2023-03-17 09:14 UTC, Hinton requested changes
I have a few concerns with this PR. For some background, the report components were refactored by @coroiu and I in https://github.com/bitwarden/clients/pull/3204, as an effort to showcase best practices while making presentational components.

This [article](https://blog.angular-university.io/angular-2-smart-components-vs-presentation-components-whats-the-difference-when-to-use-each-and-why/) covers the differences between a presentational component and smart components, and showcases when they should be used. TLDR: A presentational component is a component that only reacts on inputs and outputs, and causes no side effects. Presentational components are easily reuseable and promote loose coupling since they only know about their own state.

With that out of the way, I would suggest looking at how access is handled in the individual vaults since this is an already solved problem for individual reports. In an effort to stay consistent I believe we should reuse the same pattern here.

Individual reports use the guard `HasPremiumGuard` which blocks navigation to certain reports and opens the premium dialog. While refactoring the cards we explored a few different options such as putting the prompts within the card component but since a guard was needed to prevent direct navigation to reports either way, we wanted to avoid duplicating the logic and ultimately settled on keeping the links intact for disabled reports, and simply used the guard to show the dialog.

Other than the badge change I don't believe the generic card and list components needs to be modified, as they were already built with organizations in mind. Feel free to reach out to me if you want some guidance or want to discuss best practices.

2023-03-17 19:47 UTC, gbubemismith commented
Thanks @Hinton would review this and make the necessary changes

2023-03-21 17:15 UTC, gbubemismith commented on apps/web/src/app/organizations/reporting/reports-home.component.ts
> +  organization: Organization;
Yeah was still doing to some clean ups.

2023-03-21 17:15 UTC, gbubemismith commented on apps/web/src/app/organizations/reporting/reports-home.component.ts
> +  }
okay thanks

2023-03-21 17:16 UTC, gbubemismith commented on libs/common/src/models/domain/organization.ts
> +  get isUpgradeRequired() {
I think `isFreeOrg` sounds better

2023-03-22 10:46 UTC, Hinton reviewed
Some minor comments and we should be good.

2023-03-22 10:46 UTC, Hinton commented on apps/web/src/app/organizations/guards/org-upgrade-required.guard.ts
> +export class OrganizationUpgradeRequiredGuard implements CanActivate {
Should we rename this, now that the permission is changed? `IsPaidOrgGuard` or `OrganizationNotFreeGuard`

2023-03-22 10:46 UTC, Hinton commented on apps/web/src/app/organizations/reporting/reports-home.component.ts
>    async ngOnInit(): Promise<void> {
This is no longer async.

2023-03-22 10:46 UTC, Hinton commented on apps/web/src/app/organizations/reporting/reports-home.component.ts
>      router.events
If you want, you could change homepage to be async and get rid of the `destroy$` variable completely.

2023-03-22 10:46 UTC, Hinton commented on apps/web/src/app/organizations/tools/exposed-passwords-report.component.ts
> +  async ngOnInit() {
Not async.

2023-03-22 10:46 UTC, Hinton commented on apps/web/src/app/reports/pages/exposed-passwords-report.component.ts
> +    super.load();
```suggestion
    await super.load();
```

2023-03-22 13:38 UTC, gbubemismith commented on apps/web/src/app/organizations/guards/org-upgrade-required.guard.ts
> +export class OrganizationUpgradeRequiredGuard implements CanActivate {
`IsPaidOrgGuard ` sounds good

2023-03-22 20:31 UTC, djsmith85 approved these changes

2023-03-22 20:34 UTC, djsmith85 requested changes
Sorry pre-approved, but the linter isn't happy.
I think @Hinton mentioned that with the new prettier version, there will be some changes to spacing (`i18n :` vs `i18n:`, space). 

Run `npm ci` locally and then `npm run prettier`. That should fix all the lint-issues

2023-03-22 20:55 UTC, gbubemismith commented
> Sorry pre-approved, but the linter isn't happy. I think @Hinton mentioned that with the new prettier version, there will be some changes to spacing (`i18n :` vs `i18n:`, space).
> 
> Run `npm ci` locally and then `npm run prettier`. That should fix all the lint-issues

Thanks for that

2023-03-23 09:14 UTC, Hinton approved these changes
Great work! Thanks for iterating on this, looks good from my side,

Don't forget to accept the UI changes.

2023-03-23 14:22 UTC, danielleflinn commented
Looks good; could we make the Storybook upgrade story include the badge-primary instead of the success colored badge? 
https://62a88a6de5b807fa98886113-nhjujltnot.chromatic.com/?path=/story/web-reports-card--requires-upgrade

2023-03-23 17:07 UTC, gbubemismith commented
> Looks good; could we make the Storybook upgrade story include the badge-primary instead of the success colored badge? https://62a88a6de5b807fa98886113-nhjujltnot.chromatic.com/?path=/story/web-reports-card--requires-upgrade

@danielleflinn I think the changes are reflected.

2023-03-24 10:41 UTC, Hinton submitted a review, later dismissed

2023-03-24 11:54 UTC, djsmith85 approved these changes

2023-03-30 17:33 UTC, differsthecat approved these changes
New changes look good!

2023-03-30 20:27 UTC, merged