[AC-434] Hide billing screen for reseller clients
bitwarden/clients pull request #4955
Opened 2023-03-08 15:53 UTC by r-tome

## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
If an organization is managed by a Reseller, any Owner of that organization should only see billing information that is relevant to the organization. 

## Code changes

- **apps/web/src/app/organizations/billing/organization-billing-routing.module.ts:** Changed access to variable `canAccessBilling`
- **apps/web/src/app/organizations/billing/organization-billing-tab.component.ts:** Changed access to variable `canAccessBilling`
- **apps/web/src/app/organizations/billing/organization-subscription-cloud.component.html:** Hiding subscription information if User does not have permissions do manage billing
- **apps/web/src/app/organizations/billing/organization-subscription-cloud.component.ts:** Getting subscription info even if user cannot manage billing
- **apps/web/src/app/organizations/billing/organization-subscription-selfhost.component.html:** Changed check to variable `canAccessBilling`
- **libs/common/src/enums/providerType.ts:** Enum containing Provider types
- **libs/common/src/models/data/organization.data.ts:** Added `ProviderType` property
- **libs/common/src/models/domain/organization.ts:** Added `ProviderType` property 
- **libs/common/src/models/response/profile-organization.response.ts:** Added `ProviderType` property

## Screenshots
![image](https://user-images.githubusercontent.com/108268980/223761184-d1bbfe94-e8ea-4c9b-ba03-1fce5b5c07c1.png)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-03-16 04:19 UTC, eliykat requested changes

2023-03-16 04:19 UTC, eliykat commented on libs/common/src/models/domain/organization.ts
> +    );
I don't understand this boolean logic - it's pretty hard to parse. I also think the names are unclear.

I suggest breaking it down into individual permissions to better express what's going on here:

* `canEditSubscription` - returns true if
  * `(isOwner && !hasProvider)` - you're an owner of an org with no provider, OR
  * `(isProviderUser && hasProvider)` - you're a providerUser managing that org (implicitly an MSP)
  * this means that you can't edit the sub if you're a Provider client (MSP or Reseller)
* `canViewSubscription` - returns true if 
  * `(isOwner && !hasProvider)` - you're an owner of an org with no provider, OR
  *  `(isOwner && hasProvider && providerType == Reseller)` - you're a Reseller client
* `canEditPaymentMethods` - same as canEditSub
* `canViewBillingHistory` - same as canEditSub

Then the content follows these rules:
* if you can view the sub, you can see the basic subscription details on the Subscription page. If not, you get the billing obfuscation image (the `app-org-subscription-hidden` component)
* if you can view & edit the sub, you also get the rest of the subscription details
* if you can edit payment methods, you can access that tab
* if you can view billing history, you can access that tab

I think that works but please double check me and make sure it works.

There are 2 secondary things I'm trying to do here:
* use more granular permissions (not just "billing" but different aspects of billing)
* use clear create/edit/view/delete language rather than "manage" which has always been unclear to me

2023-03-16 04:19 UTC, eliykat commented on apps/web/src/app/organizations/billing/organization-subscription-cloud.component.html
You're still showing the SM Beta opt-in, is that correct?

2023-03-17 09:25 UTC, r-tome commented on apps/web/src/app/organizations/billing/organization-subscription-cloud.component.html
It is not, I've verified with Sukhleen. Its now hidden.

2023-03-21 03:28 UTC, eliykat requested changes

2023-03-21 03:28 UTC, eliykat commented on apps/web/src/app/organizations/billing/organization-subscription-cloud.component.html
>      </ng-container>
Take a look at line 86/87 above (the nested `ng-container`). It displays some provider information, but now that's going to be hidden if `!canEditSubscription`, which is going to be anyone with a provider. So that info will never be visible.

But - that's actually a problem at the moment. If `!manageBilling` then the `sub` never loads and this section is not shown. Only the provider (MSP) would ever see it, and they already know who the provider is 😂  Can you check if we can just delete it? Just so we don't have dead templating hanging around.

2023-03-21 03:28 UTC, eliykat commented on apps/web/src/app/organizations/billing/organization-subscription-cloud.component.html
Please stick an `*ngIf="userOrg.canEditSubscription"` on line 94/96 (the `ng-container` wrapping the buttons). It looks like the `showChangePlan` and `ShowChangePlanButton` getters will hide them in this case anyway, but it's easier and safer to make this explicit.

2023-03-21 03:29 UTC, eliykat commented on libs/common/src/models/domain/organization.ts
> +    );
I really like this change! Boolean logic gets confusing really quick, I like using ternary expressions to simplify it where possible.

2023-03-22 15:05 UTC, r-tome commented on apps/web/src/app/organizations/billing/organization-subscription-selfhost.component.ts
> +    if (this.userOrg.canEditSubscription) {
Correct, fixed to also use `canView`.

2023-03-22 15:33 UTC, r-tome commented on apps/web/src/app/organizations/billing/organization-subscription-cloud.component.html
>      </ng-container>
Ooh nicely spotted! Its not in the Figma so I think we want to delete it. I've asked Sukhleen

2023-03-23 03:31 UTC, eliykat requested changes
Most recent changes look good, only outstanding items are:
1. my feedback below (to clarify my previous suggestion)
2. removing unauthorised data from the subscription model.

2023-03-23 03:31 UTC, eliykat commented on libs/common/src/models/domain/organization.ts
> +  }
This is what I meant in my previous comment: Edit implies (gives permissions to) View

```suggestion
  get canViewSubscription() {
    if (this.canEditSubscription) {
      return true;
    }
    
    return this.hasProvider && this.providerType === ProviderType.Msp
      ? this.isProviderUser
      : this.isOwner;
  }
```

I think this is cleaner than the other way around, where Edit might fail because they don't have View. Instead, assume that if they can Edit then they can View.

2023-03-23 03:31 UTC, eliykat commented on libs/common/src/models/domain/organization.ts
> +    return this.canViewSubscription && (this.hasProvider ? this.isProviderUser : this.isOwner);
Then revert this recent change:

```suggestion
    return this.hasProvider ? this.isProviderUser : this.isOwner;
```

2023-03-23 14:52 UTC, r-tome commented on libs/common/src/models/domain/organization.ts
> +  }
That makes perfect sense!

2023-03-28 00:08 UTC, eliykat requested changes

2023-03-28 00:08 UTC, eliykat commented on apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html
> +                  (userOrg.canEditSubscription ? ", " + (nextInvoice.amount | currency : "$") : "")
Andreas made some changes to this page here: https://github.com/bitwarden/clients/pull/4897 We should make sure not to accidentally overwrite his work.

It looks like your feature branch is out of date, please merge master -> feature, then feature -> this branch and resolve merge conflicts. Then I can approve :)

2023-03-28 08:49 UTC, r-tome commented on apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html
> +                  (userOrg.canEditSubscription ? ", " + (nextInvoice.amount | currency : "$") : "")
The amount is gone which simplifies this a lot. Updated!

2023-03-29 04:46 UTC, eliykat approved these changes
👏

2023-04-03 09:57 UTC, merged