[AC-974] [Technical Dependency] Refactor Vault Tables
bitwarden/clients pull request #4967
Opened 2023-03-09 14:39 UTC by coroiu

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-03-13 13:14 UTC, coroiu commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +      shareReplay({ refCount: false, bufferSize: 1 })
**point-of-interest:** This method of setting up observables is new to our codebase. This is creating observables that will continue to run in the background even if no template is actively subscribing to it. Basically the same as having `subscribe` inside of an `ngOnInit` but we're creating observables that we need to subscribe to with the `async` pipe.

The reason I had to do this is because of a `ExpressionChangedAfterItHasBeenCheckedError`, but there are performance advantages too. I'd love to expand on the issue and the alternatives that I've considered, but it's too complex to describe here in a github comment.

The important feedback here should be if we think that this negatively impacts readability. If we feel that is the case, then I will change to using `ngOnInit`

2023-03-22 23:44 UTC, shane-melton requested changes
Looks really good, nice work! This should make working with the vault a lot easier especially for the VVR. 

Mostly small comments and thoughts here and there, please feel free to reach out if you have any questions about the few issues I did see.

2023-03-22 23:44 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/vault-header/vault-header.component.ts
> +  @Output() onEditCollection = new EventEmitter<{ tab: "info" | "access" }>();
thought: Hmm, I can see why we're using the string types for the tab when we have the enum - Its a lot easier to use in the template as a string. But should we use the enum for the event type and translate the string -> enum in the component?

2023-03-22 23:44 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault-filter/shared/models/filter-function.ts
thought: This is likely out of scope, but couldn't we tweak this function to simply return false whenever a specific filter is active and the cipher does **not** pass that filter. That way we can avoid assigning `cipherPassesFilter` and checking it in every other condition (effectively short circuiting the method when an item no longer passes the filter). 

Whenever `cipherPassesFilter` is set to `false`, all the following `if` statements becomes effectively ignored so I don't think it would break any functionality.

2023-03-22 23:44 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault-filter/services/routed-vault-filter-bridge.service.ts
> +      "MyVault"
thought: Should we define these _special_ IDs as constants somewhere?

2023-03-22 23:44 UTC, shane-melton commented on apps/web/src/app/vault/components/vault-items/vault-items.module.ts
> +// eslint-disable-next-line no-restricted-imports
question: I don't think we're using any restricted imports here, are we?

2023-03-22 23:44 UTC, shane-melton commented on apps/web/src/app/vault/components/vault-items/vault-items.component.html
> +        <th bitCell class="tw-min-w-fit tw-text-right">
Welp this solves the more obscure logic I had put in https://github.com/bitwarden/clients/pull/5034

2023-03-22 23:44 UTC, shane-melton commented on apps/web/src/app/vault/components/vault-items/vault-item-event.ts
> +    }
nit: Can we put these each on a single line to match the others?

2023-03-22 23:44 UTC, shane-melton commented on apps/web/src/app/vault/components/vault-items/vault-item-event.ts
suggestion (non-blocking): Most of these event types are actions/verbs (`edit`, `clone`, `delete`, `moveToFolder`)  and are clear what should happen when triggered. However, its not immediately clear to me what `attachments`, `collections`, `access`, and `events` are supposed to mean/do. 

Could we possibly change these to be more verb like, such as `viewEvents`?

2023-03-22 23:44 UTC, shane-melton commented on apps/web/src/app/vault/components/vault-items/vault-item-event.ts
> +      type: "attachements";
typo: `attachments`

2023-03-22 23:44 UTC, shane-melton commented on apps/web/src/app/vault/components/vault-items/vault-cipher-row.component.ts
> +    this.onEvent.emit({ type: "attachements", item: this.cipher });
typo: `attachments`

2023-03-23 08:04 UTC, coroiu commented on apps/web/src/app/vault/org-vault/vault.component.html
> +        [showPremiumFeatures]="true"
My understanding is that organizations always have premium features, but I might be wrong?

2023-03-23 08:08 UTC, coroiu commented on apps/web/src/app/vault/individual-vault/vault-filter/services/routed-vault-filter-bridge.service.ts
> +      "MyVault"
I have considered it, and already done it for the new constants `All` and `Unassigned`, but these old constants as just gonna get removed soon enough anyways 🤷

2023-03-23 08:09 UTC, coroiu commented on apps/web/src/app/vault/components/vault-items/vault-items.component.html
> +        <th bitCell class="tw-min-w-fit tw-text-right">
Oh yeah! Maybe we can just fix it with this PR then? :)

2023-03-23 20:31 UTC, differsthecat reviewed
This is awesome @coroiu , just some small comments!

2023-03-23 20:31 UTC, differsthecat commented on apps/web/src/app/vault/components/vault-items/vault-items.component.ts
> +  selector: "app-new-vault-items",
Do you have any issue with this being just `app-vault-items`? It makes sense in the context of this PR, but once merged the old one will be deleted.

2023-03-23 20:31 UTC, differsthecat commented on apps/web/src/app/vault/components/vault-items/vault-item-event.ts
Agree with this; maybe just a little more specific like `editCollections`, `editAttachments`

2023-03-23 20:31 UTC, differsthecat commented on apps/web/src/app/vault/individual-vault/organization-badge/organization-name-badge.component.html
> +  [routerLink]="[]"
Do we need the empty routerLink here?

2023-03-23 20:31 UTC, differsthecat commented on apps/web/src/app/vault/individual-vault/vault-filter/services/routed-vault-filter-bridge.service.ts
> +      "MyVault"
We have a tech debt item on Vault to address this 😎 
https://bitwarden.atlassian.net/browse/PM-1534

2023-03-23 20:31 UTC, differsthecat commented on apps/web/src/app/vault/individual-vault/vault-filter/shared/models/filter-function.spec.ts
Amazing, thank you for these 🙏

2023-03-23 20:31 UTC, differsthecat commented on apps/web/src/app/vault/org-vault/vault.component.html
> +        [showPremiumFeatures]="true"
I'm pretty sure only paid orgs do; we currently check the `useTotp` property on an org to determine this (I'm not a huge fan of this but I think it's the best way to determine a free vs paid org)

2023-03-23 20:42 UTC, differsthecat commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +        // disable warning for March release -> add await this.isLowKdfIteration(); when ready
Not yet as far as I'm aware. We are getting sporadic cases of users that changed their kdf iterations getting completely locked out of their vault with no way back in. We haven't been able to nail it down yet, so we want to keep this warning out for now.

2023-03-24 08:00 UTC, coroiu commented on apps/web/src/app/vault/components/vault-items/vault-items.component.ts
> +  selector: "app-new-vault-items",
Oh of course not, totally forgot about this one, nice catch!

2023-03-24 09:12 UTC, coroiu commented on apps/web/src/app/vault/components/vault-items/vault-item-event.ts
> +    }
Fixed!

2023-03-24 09:13 UTC, coroiu commented on apps/web/src/app/vault/components/vault-items/vault-item-event.ts
> +      type: "attachements";
Fixed!

2023-03-24 09:15 UTC, coroiu commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +    if (event.type === "attachements") {
Fixed!

2023-03-24 09:15 UTC, coroiu commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +    if (event.type === "attachements") {
Fixed!

2023-03-24 09:33 UTC, coroiu commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +    }
Honestly I just moved this code from the old vault items component and didn't really read through it. Did you have a specific method of checking `typeI18Key`?

I seems copying `securityCode` is not supported in the web vault, but is supported in other clients. It might have just tagged along during a copy-paste at some point in time. I'll remove it!

2023-03-24 09:39 UTC, coroiu commented on apps/web/src/app/vault/org-vault/vault.component.ts
>      // eslint-disable-next-line rxjs-angular/prefer-takeuntil, rxjs/no-async-subscribe
Apparently we could :)
Fixed both!

2023-03-24 09:42 UTC, coroiu commented on apps/web/src/app/vault/individual-vault/vault.component.ts
>      // eslint-disable-next-line rxjs-angular/prefer-takeuntil, rxjs/no-async-subscribe
Fixed!

2023-03-24 09:42 UTC, coroiu commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +    if (!(await this.repromptCipher([c]))) {
Done!

2023-03-24 09:54 UTC, coroiu commented on apps/web/src/app/vault/individual-vault/vault-filter/services/routed-vault-filter-bridge.service.ts
> +      "MyVault"
Nice! I added a comment to it explaining that it will be fixed as part of the VVR work!

2023-03-24 12:11 UTC, coroiu commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +  async editCollection(c: CollectionView, tab: "info" | "access"): Promise<void> {
Fixed!

2023-03-24 12:11 UTC, coroiu commented on libs/common/src/misc/utils.ts
> +  static asyncToObservable<T>(generator: () => Promise<T>): Observable<T> {
Thank you, sir! 😁

2023-03-24 12:13 UTC, coroiu commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +        this.copy(event.item, event.item.login.password, "Password", "password");
Yeah, should be fixed now! Really good catch!

2023-03-24 12:13 UTC, coroiu commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +    if (typeI18nKey === "password" || typeI18nKey === "verificationCodeTotp") {
Should be fixed!

2023-03-24 12:14 UTC, coroiu commented on apps/web/src/app/vault/org-vault/vault-header/vault-header.component.html
> +        <span class="sr-only">{{ "loading" | i18n }}</span>
Fixed!

2023-03-24 12:15 UTC, coroiu commented on apps/web/src/app/vault/components/vault-items/vault-items.module.ts
> +// eslint-disable-next-line no-restricted-imports
Nope, not sure why I added this! Removed!

2023-03-24 13:04 UTC, coroiu commented on apps/web/src/app/vault/components/vault-items/vault-item-event.ts
Totally agree, fixed!

2023-03-24 13:04 UTC, coroiu commented on apps/web/src/app/vault/components/vault-items/vault-item-event.ts
> +      type: "attachements";
Fixed

2023-03-24 13:17 UTC, coroiu commented on apps/web/src/app/vault/individual-vault/organization-badge/organization-name-badge.component.html
> +  [routerLink]="[]"
Good point, I've simplified it from 
```[routerLink]="[]"```
to
```routerLink```

I still needs to be present though, since it's the selector for the directive

2023-03-24 13:27 UTC, trmartin4 commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +        // disable warning for March release -> add await this.isLowKdfIteration(); when ready
We are still trying to isolate the error with some automated tests and have as yet been unsuccessful.  I'd like to leave it off for now.

2023-03-24 13:29 UTC, coroiu commented on apps/web/src/app/vault/individual-vault/vault-filter/shared/models/filter-function.ts
That's a very clever idea! It's a bit out of scope but it was a quick fix since that piece of the code is so well tested! 

Fixed!

2023-03-24 13:30 UTC, coroiu commented on apps/web/src/app/vault/org-vault/vault.component.html
> +        [showPremiumFeatures]="true"
Forgot about free organizations! Fixed to check `useTotp`

2023-03-24 13:36 UTC, coroiu commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +    firstSetup$
Yeah I don't necessarily think having multiple subscriptions is inherently bad. My opinion is that it boils down to what we're subscribing to. In this case the first subscription only depends on `this.route.queryParams` while the other depends on a whole group of combined data sources. By splitting them up we're able to create an application that reacts faster! We are able to open the cipher dialog almost immediately, while continuing to load the rest of the data in the background. I think this is a better approach compared to the older "show nothing then BAM" approach 😄

2023-03-24 19:51 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +    firstSetup$
Thanks for confirming my understanding! I agree and think its the better approach, even if it kind of looks odd at first.

2023-03-24 19:51 UTC, shane-melton commented on apps/web/src/app/vault/components/vault-items/vault-items.component.html
> +        <th bitCell class="tw-min-w-fit tw-text-right">
Yeah, that'd probably be best actually!

2023-03-24 19:53 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/vault-header/vault-header.component.ts
> +  @Output() onEditCollection = new EventEmitter<{ tab: "info" | "access" }>();
Sweet, that's even better, thanks!

2023-03-24 20:01 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +    }
Yeah, more type checking is probably needed here in the future I think (`aType` isn't clear to me either). But your changes fix the problem I saw and reduces the unchecked magic strings a bit more, so nice work!

2023-03-24 20:05 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/vault.component.html
> +        [showPremiumFeatures]="true"
>I'm not a huge fan of this but I think it's the best way to determine a free vs paid org

Agreed, it seems odd to use `useTotp` for "premium" status of an organization. But, if that's what we have for now then I think we're good to go here!

2023-03-24 20:06 UTC, shane-melton submitted a review, later dismissed
Looks good to go to me! Nice work on those fixes!

2023-03-27 12:37 UTC, differsthecat submitted a review, later dismissed
Awesome stuff, thanks @coroiu !

2023-04-04 16:00 UTC, danielleflinn submitted a review, later dismissed
Looks great in storybook; thanks for adding those stories!

2023-04-04 16:07 UTC, differsthecat submitted a review, later dismissed
This looks great @coroiu !

2023-04-04 16:07 UTC, differsthecat commented on apps/web/src/app/vault/components/vault-items/vault-collection-row.component.html
> -    routerLink
Nice catch, sorry if my comment before caused this!

2023-04-05 07:52 UTC, coroiu commented on apps/web/src/app/vault/components/vault-items/vault-collection-row.component.html
> -    routerLink
Haha yeah no worries 😁 Did not expect the behavior to change, know I now!

2023-04-05 12:14 UTC, differsthecat approved these changes

2023-04-11 14:00 UTC, danielleflinn submitted a review, later dismissed

2023-04-11 15:50 UTC, differsthecat submitted a review, later dismissed

2023-04-13 15:40 UTC, coroiu commented
@differsthecat PR just passed QA! Just needs one final review then it's off to master! I've enabled auto-merge, but if doesn't trigger, please press the merge button for me! 🙏

2023-04-13 15:44 UTC, differsthecat commented on apps/web/src/app/vault/components/vault-items/vault-cipher-row.component.ts
> +  }
Quick question about this, do the filter badges still work and have their own behavior when making the whole row clickable?

2023-04-13 18:06 UTC, danielleflinn commented on apps/web/src/app/vault/components/vault-items/vault-cipher-row.component.ts
> +  }
@differsthecat I think so since in Storybook the badge still shows as being clickable: https://62a88a6de5b807fa98886113-xsjtxrgwsi.chromatic.com/?path=/story/web-vault-items--individual

2023-04-13 18:47 UTC, differsthecat commented on apps/web/src/app/vault/components/vault-items/vault-cipher-row.component.ts
> +  }
Oh perfect, thanks @danielleflinn and @coroiu !

2023-04-13 18:48 UTC, differsthecat approved these changes

2023-04-13 18:48 UTC, merged