[AC-1011] Admin Console / Billing code ownership
bitwarden/clients pull request #4973
Opened 2023-03-09 18:47 UTC by vincentsalucci

## Type of change
- [ ] Bug fix
- [ ] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective
> Re-structure code in preparation for code ownership

## Code changes
- Moved all code into corresponding domains `admin-console/billing` 
- Updated all import files as necessary

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-03-16 22:19 UTC, MGibson1 requested changes
There are some add/remove issues. You can either handle by squashing all commits but these on your or removing these moves and doing a separate PR. Somehow we have to get these identified as moves on master.

2023-03-16 22:19 UTC, MGibson1 commented on libs/angular/src/billing/images/cards/amex-dark.png
Did you double check the webpack linking of these images? I didn't move these for the auth team, there are build implications to it.

2023-03-16 22:19 UTC, MGibson1 commented on libs/angular/src/billing/images/cards/amex-dark.png
It looks like these are being used in scss files, maybe that's the only location they're used?

2023-03-17 18:04 UTC, vincentsalucci commented on apps/web/src/app/admin-console/organizations/settings/two-factor-setup.component.ts
> +  templateUrl: "../../../../auth/settings/two-factor-setup.component.html",
Created. https://bitwarden.atlassian.net/browse/AC-1204

2023-03-17 18:07 UTC, vincentsalucci commented on apps/web/src/app/admin-console/organizations/tools/import-export/org-import.component.ts
> +  templateUrl: "../../../../tools/import-export/import.component.html",
Created https://bitwarden.atlassian.net/browse/AC-1205

2023-03-17 18:08 UTC, vincentsalucci commented on apps/web/src/app/admin-console/organizations/tools/inactive-two-factor-report.component.ts
> +  templateUrl: "../../../reports/pages/inactive-two-factor-report.component.html",
Created https://bitwarden.atlassian.net/browse/AC-1206

2023-03-17 18:13 UTC, vincentsalucci commented on apps/web/src/app/admin-console/organizations/tools/unsecured-websites-report.component.ts
> +  templateUrl: "../../../reports/pages/unsecured-websites-report.component.html",
Created https://bitwarden.atlassian.net/browse/AC-1208

2023-03-17 18:14 UTC, vincentsalucci commented on apps/web/src/app/admin-console/organizations/tools/weak-passwords-report.component.ts
> +  templateUrl: "../../../reports/pages/weak-passwords-report.component.html",
Created https://bitwarden.atlassian.net/browse/AC-1209

2023-03-17 18:28 UTC, differsthecat commented on apps/desktop/src/admin-console/vault/collections.component.html
I think Vault is going to take ownership of collections, especially after the Flexible Collections work. Do you want to leave these where they are for now?

2023-03-17 18:30 UTC, vincentsalucci commented on apps/web/src/app/organizations/shared/index.ts
> +// TODO Enable the below export when shared folder migration is complete
Honestly, I don't remember but I also don't see why it can't be for now. Updated.

2023-03-17 20:03 UTC, vincentsalucci commented on libs/angular/src/billing/images/cards/amex-dark.png
Hmm. I /think/ these are fine. I updated the base path in the `scss` file (in an earlier commit) that references the icons themselves and that seemed to alleviate any build issues. Is there something I'm missing?

2023-03-17 20:26 UTC, vincentsalucci commented on apps/browser/src/admin-console/background/service-factories/collection-service.factory.ts
> +} from "../../../background/service_factories/state-service.factory";
Sadge.

2023-03-17 20:32 UTC, vincentsalucci commented on apps/web/src/app/admin-console/organizations/vault/collections.component.ts
> +  templateUrl: "../../../vault/individual-vault/collections.component.html",
Created https://bitwarden.atlassian.net/browse/AC-1211

2023-03-20 17:09 UTC, vincentsalucci commented on apps/browser/src/services/browser-organization.service.ts
Reverted out of `admin-console` domain and created tracking task: https://bitwarden.atlassian.net/browse/AC-1215

2023-03-20 17:16 UTC, vincentsalucci commented on apps/cli/src/models/response/organization-user.response.ts
Reverted out of `admin-console` and tracking task created: https://bitwarden.atlassian.net/browse/AC-1216

2023-03-20 19:11 UTC, vincentsalucci commented on apps/desktop/src/admin-console/vault/collections.component.html
As discussed: moved `collections.component.(ts/html)` for `web/desktop/browser` to the `vault` domain. Thanks 👍

2023-03-20 20:14 UTC, vincentsalucci commented on apps/web/src/app/organizations/organization.module.ts
Reverted out of `admin-console` and tracking task created: https://bitwarden.atlassian.net/browse/AC-1219

2023-03-20 20:55 UTC, vincentsalucci commented on libs/common/src/models/request/organization-api-key.request.ts
Reverted out of `admin-console` and tracking task created: https://bitwarden.atlassian.net/browse/AC-1220

2023-03-21 21:07 UTC, MGibson1 approved these changes

2023-03-21 21:07 UTC, MGibson1 commented
Looks good, please make sure the icon question is tested on QA

2023-03-22 15:03 UTC, merged