Improve state migrations
bitwarden/clients pull request #5009
Opened 2023-03-15 21:35 UTC by MGibson1

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Our current state migration scheme amounted to adding a method to a big file. This establishes some more expandable best-practices around migrating state.

Key features are type safety, test-ability, supporting dev rollback, minimum state version support, and focusing migration work to just writing a migration + (optional) rollback.

## Code changes
- Remove `StateMigrationService`
- **state-migrations/index**: expose migrate method
- **migrate**: The location it's all wired together. Migrations and their order are defined in the `builder` helper method, and migrate executes the migrations.
  - Every one of our migrations (except migrations 1) has dealt with only unsecure, on-disk storage. We will likely need to develop other helper methods to branch out migrations on secure storage in the future, likely with a separate version tag.
  - current version is keyed to known locations in on-disk storage.
  - Failed migrations throw an error and stop future migrations. This is roughly the same behavior as before, but with a more well-defined interface. In the future we should work on surfacing these migration issues for user's to handle or decide to delete the offending data and log them out.
- **migration-builder**: Handles type magic related to migration ordering. Builds an internal list of migrations to perform and executes them on calling `migrate`.
  - Also handles changing the state version number by asking the migrator to do it in the given direction.
- **migration-helper**: Helper class to hold often-used migration methods.
  - Note that methods in this helper are relatively permanent. It's better to re-use code than write a helper method based on temporary state concerns.
  - That being said, I added a temporary state concern to get all the accounts :trollface:
- **old migration implementations**
  - 2to3: FixPremium migration. Reads premium from access token
  - 3to4: RemoveEverBeenUnlocked migration. Removes this key from accounts
  - 4to5: AddKeyTypeToOrgKeys. Adds a type to organization keys stored in an account
  - 5to6: RemoveLegacyEtmKey: removes this key from storage
- **MoveStateVersionMigrator**: Moves state version to the root. In general, we want most things to be moved to root. We'll know they belong to an account by a key prefixing scheme. this is just the first to avoid a deep storage structure.
- **MinVersionMigrator**: From time to time it will happen that migrations need to be deprecated due to some issue with the way they were written. This is the case with our `1to2` migration now. It references Account objects so old migrations are at the whim of current object structure. This migration fails if the current version is less than the minimum supported version.
- **Migrator**:
  - The other half of the type magic in `TTo` and `TFrom`
  - Default update version implementation
  - Default should migrate implementation

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-03-17 12:47 UTC, Hinton reviewed
A light initial review. I like the direction this is going towards. I do think we need to add some documentation on how this all works.

2023-03-17 12:47 UTC, Hinton commented on libs/common/src/state-migrations/migrate.ts
> +export const builder: MigrationBuilder<number> = MigrationBuilder.create()
Can we add some comments covering how this works? What the numbers are for etc.

2023-03-17 12:47 UTC, Hinton commented on libs/common/src/state-migrations/migrate.ts
> +    // Nothing to migrate
Why do we not want to do anything if version < 0?

And do we want to add some light logging here?

2023-03-17 12:47 UTC, Hinton commented on libs/common/src/state-migrations/migration-builder.ts
> +  rollback<
Do we currently support rollback?

2023-03-17 12:47 UTC, Hinton commented on libs/common/src/state-migrations/migration-helper.ts
> +export class MigrationHelper {
This seems to tightly couple the account structure to all migrations?

2023-03-17 12:47 UTC, Hinton commented on libs/common/src/state-migrations/migrations/3-fix-premium.ts
> +  }
This code looks to be duplicated

2023-03-20 23:10 UTC, MGibson1 commented on libs/common/src/state-migrations/migration-builder.ts
> +  rollback<
No. This feature would primarily exist to support development, like in most ORMs

2023-03-20 23:16 UTC, MGibson1 commented on libs/common/src/state-migrations/migration-helper.ts
> +export class MigrationHelper {
There's nothing in here that specifies anything about storage except the `getAccount` helper. Even that only assumes that an `authenticatedAccounts` key exists that holds keys to an object at the root.

I chose to add the method for now because it's going to be used in almost all migrations as we transition away from deep storage models. We can deprecate when necessary. We could also move it to a separate file and set up linting rules against importing it when we're through. That might be a better isolation model for when this helper transitions from helpful to dangerous.

2023-03-20 23:19 UTC, MGibson1 commented on libs/common/src/state-migrations/migrations/3-fix-premium.ts
> +  }
migrations that are pre version 7 need to use a different method to update version, since `stateVersion` is stored within the `global` object.

I chose to repeat that method for migrationd 3-6 simply because I don't want anyone using it outside of these four migrations.

2023-03-20 23:47 UTC, MGibson1 commented on libs/common/src/state-migrations/migrate.ts
> +    // Nothing to migrate
logging and comment added

2023-03-20 23:47 UTC, MGibson1 commented on libs/common/src/state-migrations/migrate.ts
> +export const builder: MigrationBuilder<number> = MigrationBuilder.create()
commented the builder class with jsdocs.

The types basically don't let you do it wrong, but the docs are a good idea, too

2023-03-22 10:14 UTC, Hinton commented on libs/common/src/state-migrations/migrations/3-fix-premium.ts
> +  }
Should we add a note that you should not copy this into new migrations? I can easily see people doing that while trying to write migrations.

2023-03-23 19:26 UTC, MGibson1 commented on libs/common/src/state-migrations/migrations/3-fix-premium.ts
> +  }
Hmm. We could. I didn't think it necessary since there's a default implementation.

I'll add notes on why overriding was necessary

2023-08-09 01:40 UTC, eliykat requested changes
I like it!

2023-08-09 01:40 UTC, eliykat commented on libs/common/src/state-migrations/migrate.ts
> +  .with(MoveStateVersionMigrator, 7, CURRENT_VERSION);
I understand now what you were saying in Slack about this.

My instinct is that these runtime values should be provided by the migration subclasses, it's weird to fix them via the type system but still require the values to be passed in from the outside caller. Why require the caller to know about this? Why require the caller to pass in values when the values are already fixed?

You could do this:

```ts
export abstract class Migrator<TFrom extends number, TTo extends number> {
  abstract fromVersion: TFrom;
  abstract toVersion: TTo;
```

and then

```ts
export class RemoveEverBeenUnlockedMigrator extends Migrator<3, 4> {
  readonly fromVersion = 3;
  readonly toVersion = 4;
```

but then, this also compiles even though they're `null`

```ts
export class RemoveEverBeenUnlockedMigrator extends Migrator<3, 4> {
  readonly fromVersion: 3;
  readonly toVersion: 4;
```

So you'd need the null check in the constructor anyway. It does make them fully internal to the migrator class though, which might still be an improvement? What do you think?

EDIT: or!! you already solve this problem with `MinVersionMigrator`!

```ts
export class MinVersionMigrator extends Migrator<0, MinVersion> {
  constructor() {
    super(0, MIN_VERSION);
  }
```

Why not do that for everyone?

2023-08-09 01:40 UTC, eliykat commented on libs/common/src/state-migrations/migrate.ts
> +  .with(MoveStateVersionMigrator, 7, CURRENT_VERSION);
I wish the TS could transform the type to its corresponding value at compile time 🤔

2023-08-09 01:40 UTC, eliykat commented on libs/common/src/state-migrations/migrations/min-version.ts
This effectively prevents pre-account switching states from migrating, right? You've permanently deleted the account switching migration code and added this to block that path? I'm not sure about that. It seems unlikely that there's anyone out there who still needs it, but should we support the full historical upgrade path for consistency? Why include other old migrations but not the first one? (Or the second?)

2023-08-09 01:40 UTC, eliykat commented on libs/common/src/state-migrations/migrate.ts
> +import { AbstractStorageService } from "../abstractions/storage.service";
I don't like this as a solution, it normalizes disabling eslint rules and you have to do it in a handful of places to make it pass linting. I think it would be better to add more exceptions to your eslint rule if these imports are in fact permitted.

2023-08-09 01:40 UTC, eliykat commented on libs/common/src/state-migrations/migration-builder.spec.ts
> +  it("should be able to create a new MigrationBuilder", () => {
This is a style nit, but the jest output already reads just fine without prefixing every test with `should`.

```
MigrationBuilder
  * creates a new MigrationBuilder
  * can add a migrator
  * can add a rollback
```

etc

2023-08-09 01:40 UTC, eliykat commented on libs/common/src/state-migrations/migrations/5-add-key-type-to-org-keys.ts
> +  }
I don't love that you've overridden this method in an identical fashion for all migrations to date. 🤔  But I can't think of a better solution. It's better than adding another layer of inheritance, or introducing legacy logic into the base `Migrator` class.

2023-08-09 01:40 UTC, eliykat commented on libs/common/src/state-migrations/migration-builder.ts
> +  rollback<
Can you expand on this? How does it support development - by letting us switch branches at different `stateVersion`s without having to manually reset our `data.json`?

Where would the rollback version of the migrationBuilder be created/called from?

2023-08-11 00:58 UTC, MGibson1 commented on libs/common/src/state-migrations/.eslintrc.json
these rules apply only to this directory. I didn't want to restrict import anywhere but here!

2023-08-11 01:18 UTC, MGibson1 commented on libs/common/src/state-migrations/migrate.ts
> +  builder.migrate(migrationHelper);
It's because the builder is a `const` (singleton), but the migration helper only exists when migrations are running (think `transient`)

2023-08-11 01:22 UTC, MGibson1 commented on libs/common/src/state-migrations/migrate.ts
> +    return;
when `currentVersion` fails to determine the version of the file, it returns -1

https://github.com/bitwarden/clients/blob/improve-state-migrations/libs/common/src/state-migrations/migrate.ts#L51-L54

This basically just refuses to migrate files we can't read.

2023-08-11 01:46 UTC, MGibson1 commented on libs/common/src/state-migrations/migrate.ts
> +  .with(MoveStateVersionMigrator, 7, CURRENT_VERSION);
you can do it that way (that's how the `minVersionMigrator` works), I just thought that it's actually nicer to be able to see the version numbers you have to use when specifying migration order. If we want, we can swap over to what you suggest with no code change, just defining those properties

2023-08-11 01:49 UTC, MGibson1 commented on libs/common/src/state-migrations/migrations/min-version.ts
yes. I don't see a compelling reason to keep migration code around indefinitely. We aren't loosing data, just requiring a sign out/sign in to replace the file.

Those particular migrations have been supported for about a year and a half at this point. They were also written in a way that inhibits our ability to update account models.

2023-08-11 01:54 UTC, MGibson1 commented on libs/common/src/state-migrations/migrate.ts
> +import { AbstractStorageService } from "../abstractions/storage.service";
I might be OK lifting the limitation of logService or storageService, but I don't think it's possible to do it without coding in _where_ those files are located, which will be annoying to maintain.

As for the lint rules as a whole: It's not that imports should be totally impossible, just that you absolutely need to think about and explain why it's OK to import. The rules exist to require conscious thought when importing from the project as a whole. I don't think the number of times that it's relevant to import matters much to me vs making sure they're all justified.

2023-08-11 01:55 UTC, MGibson1 commented on libs/common/src/state-migrations/migration-builder.spec.ts
> +  it("should be able to create a new MigrationBuilder", () => {
I think you just replaced "should" with "can" (maybe makes more sense)

2023-08-11 01:57 UTC, MGibson1 commented on libs/common/src/state-migrations/migrations/5-add-key-type-to-org-keys.ts
> +  }
yeah, the good news is that you don't have to do it anymore after the 8th migration.

I think this is the lesser of available evils

2023-08-11 02:05 UTC, MGibson1 commented on libs/common/src/state-migrations/migration-builder.ts
> +  rollback<
while developing code that requires migrations, you would update the `migrationBuilder` definition to something like

```typescript
export const builder: MigrationBuilder<number> = MigrationBuilder.create()
  .with(MinVersionMigrator)
  .with(FixPremiumMigrator, 2, 3)
  .with(RemoveEverBeenUnlockedMigrator, 3, 4)
  .with(AddKeyTypeToOrgKeysMigrator, 4, 5)
  .with(RemoveLegacyEtmKeyMigrator, 5, 6)
  .with(MoveBiometricAutoPromptToAccount, 6, 7)
  .with(MoveStateVersionMigrator, 7, CURRENT_VERSION)
  .rollback(MoveStateVersionMigrator, CURRENT_VERSION, 7);
```

As pointed out elsewhere, these files aren't really that valuable. You definitely can just recreate them. The thing is, it _is_ annoying to recreate a data file that complies with the previous schema while developing the next schema. Rather than having to swap branches, log out, and log in, you can just update the builder and revert.

It might be that I just saw the opportunity and am searching for a problem for it. 🤷 Hard to say, I haven't written many of these.

2023-08-11 02:09 UTC, MGibson1 commented on libs/common/src/services/state.service.ts
> +    }
I think the `stateVersion` stuff is a bad merge. I thought I'd deleted it.

I want to move it because I don't think the version belongs to some other object, but the file as a whole. I also don't want any nested items at all.

2023-08-14 23:46 UTC, eliykat commented on libs/common/src/state-migrations/.eslintrc.json
Yes but that is specified in the `target` property when configuring rule. It doesn't depend on the location of `eslintrc`. See for example the root `eslintrc`: https://github.com/bitwarden/clients/blob/master/.eslintrc.json#L89-L111

That said, if you want it here to keep things organized that's fine with me.

2023-08-14 23:56 UTC, eliykat commented on libs/common/src/state-migrations/migrate.ts
> +  builder.migrate(migrationHelper);
Right you are.

My next question then is, why is `MigrationBuilder` a singleton? `migrate` will only ever be called once per app execution (basically as part of bootstrapping), the benefit of creating it in `migrate` is that we know it'll be freed once migrations are done, rather than (presumably) hanging around for the lifetime of the app.

2023-08-15 00:59 UTC, eliykat commented on libs/common/src/services/state.service.ts
> +    }
You now have broken references to the old location of `stateVersion`, e.g. https://github.com/bitwarden/clients/blob/improve-state-migrations/libs/common/src/services/state.service.ts#L2317-L2325

2023-08-15 01:05 UTC, eliykat commented on libs/common/src/state-migrations/migrations/min-version.ts
Alright, that makes sense. I think we need to have some way to resolve this problem for the user though. At the moment, this will just throw an error which will presumably abort app initialization. Restarting the app won't fix it. We need to at least tell the user to clear their data file, although this is a semi-technical process that doesn't really fit in a toast. Maybe we could automatically clear & recreate the data file?

2023-08-15 01:06 UTC, eliykat commented on libs/common/src/state-migrations/migrate.ts
> +import { AbstractStorageService } from "../abstractions/storage.service";
> I don't think the number of times that it's relevant to import matters much to me vs making sure they're all justified.

Well, at a certain point, it might mean your rule is no longer justified :P but that's fair enough, and better than hardcoding the location of exceptions.

2023-08-15 01:13 UTC, eliykat commented on libs/common/src/state-migrations/migration-builder.spec.ts
> +  it("should be able to create a new MigrationBuilder", () => {
"can" replaces "be able to", not "should".

To continue the pattern as an example

```
MigrationBuilder
  * migrate
    * runs migrations
    * runs rollbacks
    * updates version on migrate
    * updates version on rollback
    * doesn't run the migrator...
    * doesn't update the version...
```

This might just be my personal preference though, it's probably academic. Feel free to resolve this thread.

2023-08-15 01:24 UTC, eliykat commented on libs/common/src/state-migrations/migrate.ts
> +  .with(MoveStateVersionMigrator, 7, CURRENT_VERSION);
Looking at this again, I agree with you that it's clearer to see them at the `MigrationBuilder` level.

My only (optional) recommendation here is to extend the pattern to `MinVersionMigrator` as well, I can't see any reason that would be treated differently, and it would really simplify the `MigrationBuilder.with` and `MigrationBuilder.addMigrator` interfaces if they only received 1 type of parameter.

e.g. this
```ts
    with<>(migrator: new (from: TFrom, to: TTo) => TMigrator, fromVersion: TFrom, toVersion: TTo)
```

instead of 
```ts
 with<>(...migrate: [new () => TMigrator] | [new (from: TFrom, to: TTo) => TMigrator, TFrom, TTo])
```

which I had to stare at for a little bit before I understood what was going on.

2023-08-15 01:30 UTC, eliykat commented on libs/common/src/state-migrations/migrate.ts
> +    return;
Makes sense, although if this is the case it'll just return early and `stateService` will try to bootstrap an invalid state. I think we need to handle it explicitly, maybe let it through to `MinVersionMigrator` so it can be handled the same as an invalid version number (i.e. deleting & recreating `data.json`).

2023-08-15 01:37 UTC, eliykat commented on libs/angular/src/services/jslib-services.module.ts
> -    },
I don't understand how `migrate` is a pure function, my understanding is that pure functions don't have side effects, but running migrations is just a series of side-effects (i.e. writing to `data.json` on disk).

I agree with you that the code is nicely separated and it's within the domain of `StateService`, so I'm OK with considering it an extension/responsibility of that service rather than a separate service that needs DI.

2023-08-15 01:39 UTC, eliykat commented on libs/common/src/state-migrations/migration-builder.ts
> +  rollback<
Thanks for the info! Let's leave it in and see if it's useful.

2023-08-15 03:40 UTC, eliykat requested changes
I also responded to any unresolved threads above, please make sure you check those out.

Please resolve conflicts :)

2023-08-15 03:40 UTC, eliykat commented on libs/common/src/state-migrations/migrator.ts
> +  : never;
I forgot to say that this is cool 😎  `infer` feels like some magic! I'm glad we spent so long on the `jsonify` stuff because I learned a lot from it.

2023-08-15 03:40 UTC, eliykat commented on libs/common/src/state-migrations/migration-helper.spec.ts
> +  },
Suggestion only: I recommend disambiguating the contents of these accounts, this way the test will throw if the sut happens to mix them up:

```suggestion
  "c493ed01-4e08-4e88-abc7-332f380ca760": {
    otherStuff: "otherStuff1",
  },
  "23e61a5f-2ece-4f5e-b499-f0bc489482a9": {
    otherStuff: "otherStuff2",
  },
```

Same for the individual migration specs where applicable.

2023-08-15 03:40 UTC, eliykat commented on libs/common/src/state-migrations/migration-helper.spec.ts
> +export function mockMigrationHelper(storageJson: any): MockProxy<MigrationHelper> {
Very nice testing work here 👏

2023-08-15 03:40 UTC, eliykat commented on libs/common/src/state-migrations/migrations/3-fix-premium.ts
> +};
ooh nice way to separate this from the current account type

2023-08-15 03:40 UTC, eliykat commented on libs/common/src/state-migrations/migrations/3-fix-premium.ts
> +    await Promise.all(accounts.map(async ({ userId, account }) => fixPremium(userId, account)));
nit: Unnecessary async (and in subsequent migrations)

```suggestion
    await Promise.all(accounts.map(({ userId, account }) => fixPremium(userId, account)));
```

2023-08-15 03:40 UTC, eliykat commented on libs/common/src/state-migrations/migrations/3-fix-premium.ts
> +        }
The try/catch is new, but I'm not sure we want to silently swallow exceptions here. If there's an unexpected error, I think we want to throw loudly rather than let the user proceed in an unknown state. Or to put it another way, this would proceed as if the migration has been applied when it hasn't.

2023-08-15 06:44 UTC, eliykat commented
Also please link a Jira ticket

2023-08-15 15:59 UTC, MGibson1 commented on libs/common/src/state-migrations/migrate.ts
> +  builder.migrate(migrationHelper);
We actually initialize `StateServices` pretty constantly, at least in the browser.

It's pretty cheap to initialize these objects, though. I just liked keeping the definition of migrations separate from the function. I'll move the definition into the migrate method.

2023-08-15 16:27 UTC, MGibson1 commented on libs/common/src/services/state.service.ts
> +      this.storageService.save(keys.stateVersion, CURRENT_VERSION);
I decided the best way to deal with this is to not care about file versioning at all outside of the migrator (this is also why I wanted to move it out of `Globals`. Our code should just assume that the file is migrated and consistent with the expected schema.

It's the migrator's job to make sure that's true and any file hints we have to facilitate that, should be within the migrator

2023-08-15 16:27 UTC, MGibson1 commented on libs/common/src/state-migrations/migrator.ts
> +  : never;
ditto!

2023-08-15 17:01 UTC, MGibson1 commented on libs/common/src/state-migrations/migrations/3-fix-premium.ts
> +        }
Yes, this was one of the few changes I made to the migrations. We definitely _do_ want to silently not perform this migration.

The result of an error here would mean that you cannot open the application, a silent failure means you're logged out. I think the recoverable situation is way better and that this was a missed bug in the original implementation.

Honestly. I'd love to set min version to 6 and not worry about any of these migrations.

2023-08-24 19:42 UTC, MGibson1 commented on libs/common/src/state-migrations/migrations/min-version.ts
I'm not following why this is a show stopper -- it's exactly what would happen today should the migrator fail.

I'd love to solve this issue, but I think it's more involved that we'd like. The idea would be to popup a warning and ask the user if they'd like to delete the local copy or fail to start and fix it themselves. The issue is that that involves a user-feedback loop at a point in the application that it's not ready to do anything. Today, we also call these migrations many times and potentially in quick succession.

To handle better, we need to separate out migration from the initialization of state service. I think this PR goes in that direction -- one of the reason I didn't want `migrate` to be a service -- but I don't think we're ready to actually broach this yet.

2023-08-28 04:19 UTC, eliykat commented on libs/common/src/state-migrations/migrations/3-fix-premium.ts
> +        }
I agree with your point about the recoverable vs. non-recoverable situations. Let's leave it then.

> Honestly. I'd love to set min version to 6 and not worry about any of these migrations.

If you wanted, you could raise the discussion more broadly about a deprecation period for this code, then drop everything outside of that period immediately. The last migration was you, 4 months ago, and the one before that was me, more than 12 months ago. A very generous period of 6 months would let us delete almost all of these migrations.

I understand if you'd rather not delay the PR further though when you've already done the work.

2023-08-28 04:23 UTC, eliykat commented on libs/common/src/services/state.service.ts
> +      this.storageService.save(keys.stateVersion, CURRENT_VERSION);
I like moving all these concerns into the migrator. Nice one.

2023-08-28 04:32 UTC, eliykat commented on libs/common/src/state-migrations/migrations/min-version.ts
> I'm not following why this is a show stopper -- it's exactly what would happen today should the migrator fail.

Because this PR introduces a new, expected situation where we intentionally cause the migrator to fail. Previously the migrator could fail due to an unexpected error, in which case all bets are off, but if we're closing off this migration path for the user then we should tell them what to do next.

I love the idea of detecting invalid data files and offering to delete & recreate them, but I agree this level of interactivity is out of scope, and I guess we don't want to do it unprompted.

Maybe this isn't as bad as I first thought, the `minVersionError` at least throws a descriptive error, and it's not exactly expected that anyone is trying to migrate 2 year old data.

2023-08-28 04:35 UTC, eliykat submitted a review, later dismissed
I've replied to the 2 unresolved comment threads above, but they're non-blocking and all the latest changes look good.

However, I regret to inform you that I'm not the only codeowner 😁

2023-08-29 13:58 UTC, justindbaur reviewed
This looks really good, just a few small comments. The `Promise.allSettled` comment applies to most of the migrations though.

2023-08-29 13:58 UTC, justindbaur commented on libs/common/src/state-migrations/migrations/3-fix-premium.ts
> +    await Promise.all(accounts.map(({ userId, account }) => fixPremium(userId, account)));
Maybe `Promise.allSettled` instead? Not that it would be super likely that one account succeeds and one fails but the more accounts we could recover in that situation the better.

2023-08-29 13:58 UTC, justindbaur commented on libs/common/src/state-migrations/migrations/3-fix-premium.ts
> +    const global: { stateVersion: number } = (await helper.get("global")) || ({} as any);
Do we break anything with `{} as unknown` instead?

2023-08-29 13:58 UTC, justindbaur commented on libs/common/src/state-migrations/migrator.ts
> +export type VersionFrom<T> = T extends Migrator<infer TFrom, any>
~~`any`~~ -> `unknown`?

2023-08-29 13:58 UTC, justindbaur commented on libs/common/src/state-migrations/migrator.ts
> +export type VersionTo<T> = T extends Migrator<any, infer TTo>
Here as well ~~`any`~~ -> `unknown`.

2023-08-29 16:11 UTC, MGibson1 commented on libs/common/src/state-migrations/migrations/3-fix-premium.ts
> +    await Promise.all(accounts.map(({ userId, account }) => fixPremium(userId, account)));
I would certainly prefer to migrate more rather than fewer, but `allSettled` will never reject and one rejection needs to stop the migration, since the file will not be in the anticipated state.

Similar to other migration failures, we can build out a user-interactive system to handle these kinds of cases, where we could prompt to delete an account that failed to migrate. However, I'm not sure the juice is worth the squeeze there.

2023-08-29 16:15 UTC, MGibson1 commented on libs/common/src/state-migrations/migrations/3-fix-premium.ts
> +    const global: { stateVersion: number } = (await helper.get("global")) || ({} as any);
Yes, but we can redefine the global type to `Record<string, unknown>` and remove the `any`

2023-08-29 16:20 UTC, MGibson1 commented on libs/common/src/state-migrations/migrator.ts
> +export type VersionFrom<T> = T extends Migrator<infer TFrom, any>
we can change these to number, but it doesn't matter. The point is to extract the `TFrom` and not care about the `TTo` type on the migrator.

This is an appropriate use of `any` to me. I'll update because it's not technically necessary and there's some value in not having any `any`

2023-08-29 16:39 UTC, jprusik approved these changes
changes in autofill LGTM

2023-08-29 16:40 UTC, justindbaur commented on libs/common/src/state-migrations/migrator.ts
> +export type VersionFrom<T> = T extends Migrator<infer TFrom, any>
Yeah the best solution would be some sort of discard of that type param but until that exists I like unknown. It makes the fewest promises.

2023-08-29 16:48 UTC, justindbaur approved these changes
Love it ❤️

2023-08-29 16:55 UTC, cagonzalezcs approved these changes
Looks good from my side.

2023-08-29 17:05 UTC, differsthecat approved these changes
This looks great, love the comprehensive tests you added 💙 

I won't hold the PR up for this, but it looks like state migrations will go to not having an owner; is this what we want? I think it makes sense that the tech leads should be the ones to approve changes to this code as it will be updated and added to by everyone, but this does seem like a very 'platform' kind of thing.

2023-08-29 20:21 UTC, jlf0dev approved these changes
Approving for Auth

2023-08-30 17:57 UTC, merged