[AC-1104] Fix access import/export with custom permission
bitwarden/clients pull request #5014
Opened 2023-03-16 23:51 UTC by shane-melton

## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Allows organization users with import/export permissions to use the organization import/export pages even with the **Remove individual vault** and **Remove individual vault export** policies enabled (they should not apply to organization vaults). 

## Code changes

- Adjust the `importBlockedByPolicy` and `disabledByPolicy` flags to have overridable `getters` in the base import/export components, so that the organization import/export components can always return false.
- Cleanup some logic in the export component to properly disable the form when appropriate. 

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-03-20 06:37 UTC, eliykat requested changes
It would be nice to
* avoid subscribing in the base class if we're not going to use it
* use the async pipe instead of managing our own subscriptions

...but both would be pretty major changes affecting all clients, that should probably be lead by the Tools Team, so we don't have to (probably shouldn't?) do them here.

That said, I think the change below is pretty reasonable.

2023-03-20 06:37 UTC, eliykat commented on apps/web/src/app/tools/import-export/import.component.ts
>      );
We should subscribe to this so that we get values over time, rather than just on page load (as with `ExportComponent`).

2023-03-20 19:22 UTC, shane-melton commented on apps/web/src/app/tools/import-export/import.component.ts
>      );
Good point, updated to use a subscription instead of awaiting `firstValueFrom`.

2023-03-20 19:26 UTC, shane-melton commented
Thanks for the review!

> It would be nice to
> 
> * avoid subscribing in the base class if we're not going to use it
> * use the async pipe instead of managing our own subscriptions
> 
> ...but both would be pretty major changes affecting all clients which should probably be lead by the Tools Team, so we don't have to (probably shouldn't?) do them here.

I agree with both of your points and the caveat that it'll require some significant refactoring to the components/clients that'd probably be best left to the Tools Team. 

I did still make the simple change you requested; thanks for catching that discrepancy between the import/export components!

2023-03-21 23:40 UTC, eliykat submitted a review, later dismissed

2023-04-07 00:36 UTC, eliykat requested changes
Nice clean up on the rxjs logic.

2023-04-07 00:36 UTC, eliykat commented on apps/web/src/app/tools/import-export/import.component.ts
> +      }
Navigation is something that we do on a successful import. So I recommend deleting `this.successNavigate` and putting the navigation logic in `this.onSuccessfulImport` as required.

I also prefer having class methods that you can override, rather than setting callbacks in `ngOnInit`. But I'll leave that up to you.

2023-04-24 23:56 UTC, eliykat approved these changes
Much tidier, nice work 👏

2023-05-30 23:29 UTC, eliykat approved these changes

2023-05-30 23:30 UTC, merged