[SM-670] Restrict UI actions based on user permission
bitwarden/clients pull request #5090
Opened 2023-03-27 20:50 UTC by Thomas-Avery

## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

The purpose of this PR is to restrict UI actions that the current user doesn't have permission to preform related to projects.

## Code changes

- apps/web/src/locales/en/messages.json

New message for no items project -> secrets tab.

- bitwarden_license/bit-web/src/app/secrets-manager/models/view/project-list.view.ts
bitwarden_license/bit-web/src/app/secrets-manager/models/view/project.view.ts
bitwarden_license/bit-web/src/app/secrets-manager/projects/models/responses/project-list-item.response.ts
bitwarden_license/bit-web/src/app/secrets-manager/projects/models/responses/project.response.ts
bitwarden_license/bit-web/src/app/secrets-manager/projects/project.service.ts
bitwarden_license/bit-web/src/app/secrets-manager/projects/project/project.component.ts

Updating response models to contain current user's permission.

- bitwarden_license/bit-web/src/app/secrets-manager/projects/project/project-secrets.component.html
bitwarden_license/bit-web/src/app/secrets-manager/projects/project/project-secrets.component.ts

Grab current project to check permissions and display a custom no items message if the user only has read access.

- bitwarden_license/bit-web/src/app/secrets-manager/shared/access-policies/dialogs/access-removal-dialog.component.ts

Now that we are including permissions in server responses; on access removal going from read/write → read-only, we want to invoke an access policy refresh from the accessPolicyService. 

This will force the project list to refresh and give us up-to-date permissions on the projects.

- bitwarden_license/bit-web/src/app/secrets-manager/shared/projects-list.component.html
bitwarden_license/bit-web/src/app/secrets-manager/shared/projects-list.component.ts

Added UI restrictions based on access.

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-03-31 16:44 UTC, coltonhurst requested changes
Looks pretty good so far, however Export for projects is broken. We may need to check Import also.

2023-03-31 20:28 UTC, coltonhurst requested changes
Looks like the above has been fixed in the [equivalent server PR](https://github.com/bitwarden/server/pull/2822). Thank you!

When creating a secret, we probably shouldn't show projects in the project dropdown that the user only has read access to. I know the action results in an error, but it might be good UX to just not show it. Any thoughts?

<img width="748" alt="pic" src="https://user-images.githubusercontent.com/5691612/229223306-56a1f65a-e677-46c4-967f-c4afc02c5f2f.png">

2023-04-03 14:27 UTC, Thomas-Avery commented
> Looks like the above has been fixed in the [equivalent server PR](https://github.com/bitwarden/server/pull/2822). Thank you!
> 
> When creating a secret, we probably shouldn't show projects in the project dropdown that the user only has read access to. I know the action results in an error, but it might be good UX to just not show it. Any thoughts?
> 
> <img alt="pic" width="748" src="https://user-images.githubusercontent.com/5691612/229223306-56a1f65a-e677-46c4-967f-c4afc02c5f2f.png">

Good idea I've added that.

2023-04-04 21:10 UTC, coltonhurst approved these changes
Looks good, thank you!

2023-04-19 18:53 UTC, willmartian requested changes
Good job here. A couple small comments:

2023-04-19 18:53 UTC, willmartian commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.ts
> +      this.projects = this.projects.filter((p) => p.write);
Why are we calling `this.projects = this.projects.filter((p) => p.write)` in both `loadData` and `loadProjects`? I'm a little confused here

2023-04-19 19:31 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.ts
> +      this.projects = this.projects.filter((p) => p.write);
I cleaned it up https://github.com/bitwarden/clients/pull/5090/commits/dcadd7c367ef8c6c3b44f99ee2ebb1c4e6b81af2

The idea is, if we have a read-only secret, we need to load all the projects so the read only project association is displayed correctly.

2023-04-19 20:11 UTC, willmartian commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/projects-list.component.ts
> +    this.selection.changed.pipe(takeUntil(this.destroy$)).subscribe((_) => {
We don't need the `ngOnInit`. 

On line 42, after we initialize `selection`, we can initialize `hasWriteAccessOnSelected$`:

```ts
selection = new SelectionModel<string>(true, []);
protected hasWriteAccessOnSelected$ = this.selection.changed.pipe(map(_ => this.selectedHasWriteAcess()))
```

2023-04-19 20:14 UTC, willmartian commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.ts
> +      this.projects = this.projects.filter((p) => p.write);
Gotcha, thank you 👍

2023-04-19 21:39 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/projects-list.component.ts
> +    this.selection.changed.pipe(takeUntil(this.destroy$)).subscribe((_) => {
Take two https://github.com/bitwarden/clients/pull/5090/commits/96892db91fe6b239fed59e8b8478a1f32e7a62fc

2023-04-19 23:58 UTC, willmartian commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/projects-list.component.ts
> +    this.selection.changed.pipe(takeUntil(this.destroy$)).subscribe((_) => {
Perfect!

2023-04-20 00:00 UTC, willmartian approved these changes
Nice job! 🌈

2023-04-26 18:09 UTC, merged