[AC-358] SelfHosted update subscription page
bitwarden/clients pull request #5101
Opened 2023-03-28 20:45 UTC by shane-melton

## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Add subscription expiration clarification to the self hosted organization subscription page.

- Replace "Expiration" with "Subscription Expiration"
- Add link to help documentation regarding organization licenses
- Add helper text beneath subscription expiration that helps clarify a subscriptions grace period
  - Hidden if it is not possible to accurately determine the organization's grace period

See required server PR here: https://github.com/bitwarden/server/pull/2826

## Code changes

- **libs/common/src/billing/models/response/organization-subscription.response.ts:** Add a new `selfHostSubscriptionExpiration` property. This property, if present, will not include any grace period. The grace period will still be present in the existing `expiration` property.

- **apps/web/src/app/billing/organizations/organization-subscription-selfhost.component.html:** Make the necessary template changes.
  - Change expiration label
  - Add helper text and link to documentation
  - Change text color when subscription is expired
  - Support fallback in case subscription expiration field is missing (older licenses)
 

## Screenshots

### Active Subscription
<img width="996" alt="image" src="https://user-images.githubusercontent.com/8764515/228360787-93903f5c-0cb2-4061-b503-abb100dc19d1.png">

### Expired Subscription w/ Grace period
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/8764515/228361330-68ab5aaf-280b-4df0-8cf8-320cc71f5301.png">

### Active subscription with unknown grace period
If a self hosted instance is using an older API and/or license file without the separate `SubscriptionExpiration` field we fallback to the original implementation that shows the one expiration value.
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/8764515/228361527-cf8d7d98-4b89-4fff-84f8-a000be578ea8.png">

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-04-18 04:29 UTC, eliykat requested changes
This looks solid, but I think we can make some improvements in this area while you're here. Let me know what you think.

2023-04-18 04:29 UTC, eliykat commented on libs/common/src/billing/models/response/organization-subscription.response.ts
> +  selfHostSubscriptionExpiration: string;
Nit: missing a line break between this line and the constructor definition

```suggestion
  selfHostSubscriptionExpiration: string;

```

2023-04-18 04:29 UTC, eliykat commented on apps/web/src/locales/en/messages.json
> +    "message": "After your subscription expires, you have 60-days to apply an updated license file to your organization. Grace period ends $GRACE_PERIOD_END_DATE$.",
Dash/hyphen is unnecessary

```suggestion
    "message": "After your subscription expires, you have 60 days to apply an updated license file to your organization. Grace period ends $GRACE_PERIOD_END_DATE$.",
```

2023-04-18 04:29 UTC, eliykat commented on apps/web/src/app/billing/organizations/organization-subscription-selfhost.component.ts
>    }
This has bothered me for a while - we have a bare `response` object and then we use getters on the Angular components to be able to work with it. Really these should be getters on the subscription object, and we should generally make the subscription object more understandable.

For example: is the expiration date `expiration`, `upcomingInvoice.date`, `subscription.trialEndDate`, `subscription.periodEndDate`, or `subscription.cancelAtEndDate`?? why is there even a nested subscription object? etc. Messing with the API is difficult but we can start to abstract some of this for easier consumption by components.

I suggest that you introduce the pattern now of an `OrganizationSubscription` domain class, which can present the data from the `OrganizationSubscriptionResponse` in a more usable way. For example, it can properly construct `Date` objects and also contain these getters above. If you can align it with the cloud subscription component then great, but they seem to use different fields, so if you wanted to limit your refactor you could make it a more specific `SelfHostedOrganizationSubscription` class.

Again, it doesn't have to be a total overhaul, I'd just like to start introducing the pattern so that others will follow it. Let me know what you think or if you have another suggestion.

2023-04-18 04:29 UTC, eliykat commented on libs/common/src/billing/models/response/organization-subscription.response.ts
> +    );
The name `selfHostSubscriptionExpiration` doesn't really communicate that it doesn't include the grace period, and imo it doesn't clearly distinguish it from the other expiration-related properties here.

How about something like `expirationWithoutGracePeriod`, and a jsdoc comment on the regular `expiration` property to note that it does include the grace period for self-hosted subs?

The domain object (see comment above) could help with stuff like this, but given that we're introducing this property now, we have the opportunity to have clear naming from the jump.

2023-04-19 18:44 UTC, shane-melton commented on apps/web/src/app/billing/organizations/organization-subscription-selfhost.component.ts
>    }
Went ahead an introduced a `SelfHostedOrganizationSubscriptionView` to encapsulate/replace many of the getters in the component itself as we discussed. Should get us moving in the right direction and provide a pattern for when we refactor the cloud component.

2023-04-19 18:45 UTC, shane-melton commented on libs/common/src/billing/models/response/organization-subscription.response.ts
> +    );
Great point! Renamed to `ExpirationWithoutGracePeriod` to be more explicit.

2023-04-20 01:35 UTC, eliykat requested changes
The view object is working great I think.

2023-04-20 01:35 UTC, eliykat commented on libs/common/src/billing/models/view/self-hosted-organization-subscription.view.ts
> +  constructor(orgSub: OrganizationSubscriptionResponse) {
I suggest `response` as a more standardised name for the response object parameter.

2023-04-20 01:35 UTC, eliykat commented on libs/common/src/billing/models/view/self-hosted-organization-subscription.view.ts
> +  }
I think this fallback behaviour is confusing. It means the getter can return two very different dates depending on the license file version.

I recommend removing the fallback and just letting it be `null` if not available, explaining this in the jsdoc:

```ts
  /**
   * Date the subscription expires, excluding the grace period.
   * This will be `null` for older (< v12) license files because they do not include this date.
   * In this case, you have to rely on the `expirationWithGracePeriod` instead.
   */
```

And then account for this when using it in the component, e.g. "if hasSeparateGracePeriod, show both dates separately, else just show withGracePeriod". It's all more explicit and less likely to cause a mix up in the future.

Once you do that, you also have no need for getters, you can just make the properties public.

2023-05-01 05:53 UTC, eliykat requested changes
Just 1 minor suggestion then good to go 👍

2023-05-01 05:53 UTC, eliykat commented on libs/common/src/billing/models/view/self-hosted-organization-subscription.view.ts
> +  get isExpired() {
I like that you've been very explicit about whether each getter includes or excludes the grace period. I suggest doing the same thing here, e.g. `isExpiredAndOutsideGracePeriod`. (I don't think `isExpiredWithGracePeriod` would be very clear in this case)

2023-05-01 17:04 UTC, shane-melton commented on libs/common/src/billing/models/view/self-hosted-organization-subscription.view.ts
> +  get isExpired() {
Good point, done!

2023-05-03 01:10 UTC, eliykat approved these changes

2023-05-15 14:38 UTC, merged

2023-05-15 17:32 UTC, fschillingeriv commented on apps/web/src/app/billing/organizations/organization-subscription-selfhost.component.html
> +        href="https://bitwarden.com/help/licensing-on-premise/#update-a-renewed-organization-license "
@shane-melton Just want to point out that this article has been drastically re-written; if possible, could you change the anchor in the slug to #update-organization-license? NBD if not, as-is it won't bounce, it just won't directly scroll to the relevant section.

2023-05-15 17:40 UTC, shane-melton commented on apps/web/src/app/billing/organizations/organization-subscription-selfhost.component.html
> +        href="https://bitwarden.com/help/licensing-on-premise/#update-a-renewed-organization-license "
Can do! I opened a [PR here](https://github.com/bitwarden/clients/pull/5455) to update the link anchor.