[PM-1086] Cipher key encryption and decryption update
bitwarden/clients pull request #5114
Opened 2023-03-30 11:06 UTC by LRNcardozoWDF

## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Update cipher encryption and decryption flow through use of an individual cipher key. The new encryption flow must be wrapped in a feature flag.

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-04-11 14:20 UTC, gbubemismith commented
This looks good to me. Additional reviews on this would be appreciated

2023-04-12 12:59 UTC, differsthecat reviewed
The logic here looks sound, but I have roped in @MGibson1 to see if we can make these changes with the new encryption/decryption updates in mind. I don't see a straightforward way to do so, but he may have a better idea.

2023-04-12 18:25 UTC, differsthecat commented on libs/angular/src/vault/components/add-edit.component.ts
> +        );
I talked with @djsmith85 and he had a good suggestion around this. 

This additional code to get the CipherKey as a parameter in the decrypt function can be easily missed in future development as the keyt is an optional parameter, but in practice really isn't with this new change. Instead of passing it here as a parameter, you can make `cipherService` a required parameter to the `decrypt()` function on Cipher, and in that method call `await cipherService.getCipherKey(cipher.organizationId)`. That way, the Cipher model handles implementation detail and the user isn't misled into thinking the key is optional. What do you think about that @LRNcardozoWDF ?

2023-04-12 20:27 UTC, MGibson1 commented on libs/common/src/vault/services/cipher.service.ts
> +    }
This is a large enough change that I don't think it's appropriate to tack this into a previously existing method that already does too much.

My gut reaction looking at this a bit is to offload key identification to somewhere else (Cipher domain, key generation service, a different cipherService method, I'm not sure), but if we just require the key to be given in the signature of this method all of a sudden a bunch of these problems just go away.

2023-04-13 13:45 UTC, differsthecat commented on libs/common/src/vault/services/cipher.service.ts
> +    }
If we require the key to be provided here, I feel like that would shove the responsibility of getting and managing the key to the callers of this function, which doesn't feel right. Putting it on the Cipher domain class may work, we would have to pass in cryptoService as a parameter in the method, but looking at the refactor Oscar has in progress, he is doing that with the `encrypt()` on the cipher view.

2023-04-14 16:36 UTC, gbubemismith commented on libs/angular/src/components/share.component.ts
I think this is because the key is not updated on the Ciphers table. I have a PR for this.

2023-04-24 21:39 UTC, LRNcardozoWDF commented on libs/common/src/vault/services/cipher.service.ts
> +  }
@MGibson1 Thank you for your review on this. I followed one of your suggestions and opted to split the code into two different methods here in `cipherService`. I believe this approach fixes your concern.

2023-04-24 21:44 UTC, LRNcardozoWDF commented on libs/common/src/vault/services/cipher.service.ts
> +      cipher.forceKeyRotation = false;
Added this to ensure we persist the property as false if it was set as true.

2023-04-28 17:44 UTC, differsthecat commented on libs/angular/src/vault/components/add-edit.component.ts
> +        );
Thank you @LRNcardozoWDF , this is great!

2023-04-28 17:45 UTC, differsthecat reviewed
This looks good from my perspective, I will wait to approve until @MGibson1 has a chance to take a look!

2023-05-03 18:47 UTC, MGibson1 requested changes
Biggest design question here is whether or not `forceKeyRotation` needs to be persisted at all.

I'd also like to see some expansion of our tests to support this new feature.

2023-05-03 18:47 UTC, MGibson1 commented on libs/common/src/vault/models/data/cipher.data.ts
> +    this.forceKeyRotation = response.forceKeyRotation;
I think I'm not understanding this field. It doesn't make sense to be persisted to me.

Data models are serializable versions of Domains -- they're mostly outdated, we just need to work on getting them delete.

What makes this field be useful in a persisted fashion? isn't this an action to be taken while encrypting?

2023-05-03 18:47 UTC, MGibson1 commented on libs/common/src/vault/models/domain/attachment.ts
> +    cipherEncKey?: SymmetricCryptoKey
I'm confused why this was resolved, the parameter is still here

2023-05-03 18:47 UTC, MGibson1 commented on libs/common/src/vault/models/domain/cipher.ts
> +  forceKeyRotation: boolean;
Same comment as for the `Data` model.

2023-05-03 18:47 UTC, MGibson1 commented on libs/common/src/vault/models/domain/cipher.ts
> +    encKey = encKey ?? (await cipherService.getCipherKey(this.organizationId));
If you get rid of this helper and just call it from the crypto service directly, you can get rid of the method signature change.

2023-05-03 18:47 UTC, MGibson1 commented on libs/common/src/vault/models/domain/cipher.ts
> +    const forceKeyRotation = obj.forceKeyRotation;
booleans are jsonifiable, there's no need to add this as a special case

2023-05-03 18:47 UTC, MGibson1 commented on libs/common/src/vault/models/request/cipher.request.ts
> +    this.key = cipher.key != null ? cipher.key.encryptedString : null;
```suggestion
    this.key = cipher.key?.encryptedString;
```

2023-05-03 18:47 UTC, MGibson1 commented on libs/common/src/vault/models/response/cipher.response.ts
> +  forceKeyRotation: boolean;
Same concerns here as `data` model

2023-05-03 18:47 UTC, MGibson1 commented on libs/common/src/vault/services/cipher.service.ts
> +      cipher.forceKeyRotation = false;
Repeating just for clarity, but I don't see why this boolean is persisted at all. Hopefully it can just go away

2023-05-03 18:47 UTC, MGibson1 commented on libs/common/src/vault/services/cipher.service.ts
> +  }
This looks a lot better. I like how both encryption techniques clearly use the same encryption method, just with different keys 👍

2023-05-03 18:47 UTC, MGibson1 commented on libs/common/src/vault/models/domain/cipher.spec.ts
Please expand tests to ensure that 
1. cipher encryption is not used when flag is false
2. ciphers without encryption keys are upgraded when flag is true
3. keys are rotated when force rotation is true
4. encryptCipher is called no matter encryption method.

2023-05-08 19:08 UTC, MGibson1 commented on libs/common/src/services/crypto.service.ts
> +  async makeCipherKey(): Promise<SymmetricCryptoKey> {
I'm not sure what I expect, but It feels like all these key methods are duplicative.

2023-05-08 19:21 UTC, MGibson1 commented on libs/common/src/vault/models/view/cipher.view.ts
> +  forceKeyRotation: boolean;
Ah, that's an interesting case, but I don't think closing that backdoor requires client interaction.

As a part of the job that detects Ciphers with expired Sends, the server should re-encrypt the Cipher with the owning user's public key. Then, on the client, when an rsa-encrypted cipher is detected, we can rotate its key and reupload.

That way, the hole is closed immediately by the server and doesn't require jobs to be run client-side, just an extra step during decryption.

2023-05-09 13:24 UTC, trmartin4 commented on libs/common/src/services/crypto.service.ts
> +  async makeCipherKey(): Promise<SymmetricCryptoKey> {
Could we put this on the backlog for the Platform team to take on refactoring these services?  Or potentially a follow-up tech debt item for either Vault or Auth to tackle (as both have pending changes to `makeXKey()` methods)?

It appears that the only duplicated part is the generation of a random 64-byte array to serve as a key.  I think it would be great if we could refactor these to be more clear about what each one does - the naming and the intent of the existing methods is very confusing for new engineers trying to understand what method to use.

2023-05-13 20:29 UTC, trmartin4 commented on libs/common/src/services/crypto.service.ts
> +  async makeCipherKey(): Promise<SymmetricCryptoKey> {
@MGibson1 I've created https://bitwarden.atlassian.net/browse/PM-2255 for this refactoring.  Would it be OK to remove it from the scope of this request?

2023-05-16 16:46 UTC, MGibson1 commented on libs/common/src/services/crypto.service.ts
> +  }
I feel this is a concern that is better encapsulated on the `cipher` object and it being here is a bit of an inappropriate intimacy on that domain.

2023-05-16 16:46 UTC, MGibson1 commented on libs/common/src/vault/models/domain/cipher.ts
> +      encKey = await cryptoService.getKeyForCipherKeyEncryption(this.organizationId);
```suggestion
      encKey = await (this.organizationId != null ? cryptoService.getOrgKey(this.organizationId) : cryptoService.getKeyForUserEncryption();
```

As said in crypto service, I feel this logic is better suited here. wrote this without IDE help, btw, please double check 😏

2023-05-16 16:46 UTC, MGibson1 commented on libs/common/src/vault/services/cipher.service.spec.ts
> +        jest.spyOn<any, string>(cipherService, "encryptCipher");
I recommend moving this to a `beforeEach`

2023-05-16 16:46 UTC, MGibson1 commented on libs/common/src/vault/services/cipher.service.spec.ts
> +        });
I recommend moving this to a `beforeEach` method and changing from a hard-coded value to a shared variable that you can set in the test itself

```typescript
describe("encryptedCipher", () => {
  let enableCipherKeyEncryption: boolean;
  
  beforeEach(() => {
    process.env.FLAGS = JSON.stringify({
      enableCipherKeyEncryption: enableCipherKeyEncryption,
    });
  });

  it("sets the flag", () => {
    enableCipherKeyEncryption = false;
  });
});
```

2023-05-16 16:46 UTC, MGibson1 commented on libs/common/src/vault/services/cipher.service.spec.ts
> +      it("is called when enableCipherKeyEncryption is true", async () => {
It's quite weird that these two tests are identical. Largely to me that indicates that this isn't really testing anything and is just a burden to future changes.

Maybe we can change the expect to include arguments and validate that the key being used is the correct one? Or perhaps you meant to spy on `encryptWithCipherKey` instead?

2023-05-16 16:46 UTC, MGibson1 commented on libs/importer/src/importers/bitwarden/bitwarden-json-importer.ts
> +      const encKey = await this.cryptoService.getKeyForCipherKeyEncryption(cipher.organizationId);
Along the lines of removing this method due to inappropriate intimacy, this usage probably indicates that we should have a `getKey` helper on the domain itself, rather than using it in that single location.

2023-05-19 13:45 UTC, LRNcardozoWDF commented on libs/common/src/vault/services/cipher.service.spec.ts
> +        });
The flag will be initiated with the value enableCipherKeyEncryption has before the test starts. The new value assigned to the enableCipherKeyEncryption will only take effect in the next test.

2023-05-19 13:53 UTC, LRNcardozoWDF commented on libs/common/src/vault/services/cipher.service.spec.ts
> +      it("is called when enableCipherKeyEncryption is true", async () => {
Yeah, what I wanted to do was indeed spy on encryptWithCipherKey, changed that in the last commit.

2023-05-19 14:26 UTC, MGibson1 commented on libs/common/src/vault/models/domain/cipher.ts
> +  async decrypt(encKey: SymmetricCryptoKey): Promise<CipherView> {
The decryptable interface specifies nullable here. I think it's a bad idea to deviate, but I would prefer if the interface required the key.

2023-05-19 14:27 UTC, MGibson1 commented on libs/common/src/vault/models/domain/cipher.ts
> +        model.login = await this.login.decrypt(this.organizationId, encKey);
orgIds should no longer be necessary on these decrypt calls

2023-05-21 12:59 UTC, MGibson1 reviewed
Looks like you forgot to remove the crypto service method.

I'm going on vacation, but other than that method, it looks good. Feel free to dismiss my change request if needed.

2023-05-21 12:59 UTC, MGibson1 commented on libs/common/src/abstractions/crypto.service.ts
> +  getKeyForCipherKeyEncryption: (orgId?: string) => Promise<SymmetricCryptoKey>;
Wasn't this removed to CipherService again?

2023-05-21 12:59 UTC, MGibson1 commented on libs/common/src/services/crypto.service.ts
> +  }
I'm it looks like this did get moved to CipherService. Please remove here

2023-05-21 12:59 UTC, MGibson1 commented on libs/common/src/vault/services/cipher.service.spec.ts
> +        });
It shouldn't be. The flagEnabled method is supposed to check at runtime, not cache them

Not a huge deal, though

2023-05-21 12:59 UTC, MGibson1 commented on libs/importer/src/importers/bitwarden/bitwarden-json-importer.ts
> +      const encKey = await this.cryptoService.getKeyForCipherKeyEncryption(cipher.organizationId);
This should change over to the cipher service method

2023-05-22 17:44 UTC, gbubemismith commented
@LRNcardozoWDF I noticed we aren't using LaunchDarkly for feature flags. I recommend using it as it won't require creating a new PR to disable or enable this feature in the future. You can reference [this](https://github.com/bitwarden/clients/pull/5406/files#diff-5a1fb4b7f5ce90ae53e21d6b9cf870d01cfc8b9cdead53a86764f1ac07f3f192) or [this](https://github.com/bitwarden/clients/pull/5308) as a guide on how I have used them on the client or better still the [docs](https://contributing.bitwarden.com/contributing/featureflags), and the flag can be mocked efficiently thereby addressing @MGibson1 concerns.

2023-05-22 17:53 UTC, gbubemismith commented on libs/common/src/vault/services/cipher.service.ts
> +    if (flagEnabled("enableCipherKeyEncryption")) {
This can be replaced with the launchdarkly feature flag implementation.  You would bend up having something like this; 

`if(await this.configService.getFeatureFlagBool(FeatureFlag.CipherKeyEncryption))`

2023-05-22 18:10 UTC, trmartin4 commented on libs/common/src/vault/services/cipher.service.ts
> +    if (flagEnabled("enableCipherKeyEncryption")) {
A feature flag called `enable-cipher-key-encryption` has already been defined in LaunchDarkly for this purpose, so it will be available when needed.

2023-05-23 13:22 UTC, gbubemismith commented on libs/common/src/vault/services/cipher.service.ts
> +    if (flagEnabled("enableCipherKeyEncryption")) {
@LRNcardozoWDF using the LD feature flags won't be needed anymore based on the new information I got on this feature.

2023-05-23 14:11 UTC, gbubemismith commented on libs/common/src/vault/services/cipher.service.spec.ts
> +        });
@LRNcardozoWDF, do you want to look at this change, or can we overlook this?

2023-05-23 16:35 UTC, trmartin4 commented on libs/common/src/vault/services/cipher.service.spec.ts
> +        });
@gbubemismith and @LRNcardozoWDF, I created https://bitwarden.atlassian.net/browse/PM-2365 to capture this work, and we agreed that the PR can now be approved in its current state.

2023-05-23 22:35 UTC, merged