[EC-850] ProviderUser permissions should prevail over member permissions
bitwarden/clients pull request #5162
Opened 2023-04-05 08:10 UTC by eliykat

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

ProviderUsers who are also members do not get provider permissions. e.g. a ProviderUser who is also an Owner cannot access the Billing tab for an org, because they get the billing obfuscation image telling them to contact their provider.

This is because `syncService.syncProfile` only saves a providerOrg if it doesn't already exist in the synced organizations (of which you are a member). This PR fixes that syncing logic and updates some other related logic to make sure that provider permissions flow through where the providerUser is also a member.

## Code changes

- **libs/common/src/admin-console/models/data/organization.data.ts** - add an `isMember` property. Combined with the existing `isProviderUser` property, we can represent all states: being just a member, just a providerUser, or both.
- **libs/common/src/vault/services/sync/sync.service.ts** - extract org sync logic to a new method. Set `isProviderUser` and `isMember` flags on all organizations.
- **libs/common/src/admin-console/models/domain/organization.ts** - update role checks to make sure that the user's providerUser status flows down through the various getters, ensuring that it overrides their org membership role.
- **libs/common/src/admin-console/abstractions/organization/organization.service.abstraction.ts** - update `isNotProviderUser` method to be `isMember` - which seems to be the intention when you inspect the calling locations. We used to assume that being a providerUser and being a member were mutually exclusive, but that is no longer the case.

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-04-05 23:41 UTC, eliykat commented on libs/common/src/admin-console/models/data/organization.data.ts
> +    }
Point of interest: I included this `options` parameter because without this data, the `OrganizationData` is incomplete. And it's nicer than having multiple boolean params.

2023-04-05 23:45 UTC, eliykat commented on libs/common/src/admin-console/abstractions/organization/organization.service.abstraction.ts
> +  return org.isMember;
We might consider replacing this with a map function, or a pre-filtered `memberOrganizations$` observable, given that it's a common requirement (and assumption). I haven't done this yet because I wasn't sure if it was necessary, and several calling locations use this function to filter an array rather than an observable stream (i.e. they haven't transitioned to observables yet). So I've left it for now, but any reviewer can request it.

2023-04-10 20:56 UTC, shane-melton requested changes
This looks good! I only saw one small issue and had a slightly out of scope question about how we sort organizations in one spot. Nice work!

2023-04-10 20:56 UTC, shane-melton commented on libs/common/src/vault/services/sync/sync.service.ts
> +      organizations[o.id].isMember = true;
I believe we can remove this line, as its set by the new `options` object provided above.

2023-04-10 20:56 UTC, shane-melton commented on libs/common/src/vault/services/sync/sync.service.ts
> +  private async syncProfileOrganizations(response: ProfileResponse) {
Nice refactor extracting this method!

2023-04-10 20:56 UTC, shane-melton commented on libs/common/src/admin-console/models/data/organization.data.ts
> +    }
Seems like a clean solution to me, and helps insure we're always explicit about the users role for each organization.

2023-04-10 20:56 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault/vault-select.component.ts
> +      .pipe(map((orgs) => orgs.filter(isMember).sort((a, b) => a.name.localeCompare(b.name))));
This is likely out of scope, but should we update this to use the `i18nService` instead of `localeCompare` while here?

Something like
```sort((a, b) => this.i18nService.collator.compare(a.name, b.name))```
or
```sort(Utils.getSortFunction(this.i18nService, "name")```

2023-04-10 20:56 UTC, shane-melton commented on libs/common/src/admin-console/abstractions/organization/organization.service.abstraction.ts
> +  return org.isMember;
I think it could be a good idea to create a pre-filtered `memberOrganizations$` observable as its such a common requirement/assumption. We could also pre-sort that observable while we're at it, as that also seems fairly common. (it would also simplify imports a bit, by not requiring `isMember()` everywhere)

We might still want keep this function (but mark it for deprecation) for areas that haven't transitioned to observables yet - if we want to avoid refactoring _all_ of the calling locations to use the observable pattern in this PR. Unless, of course, you want to try and tackle that as well at this point.

2023-04-11 04:57 UTC, eliykat commented on apps/browser/src/vault/popup/components/vault/vault-select.component.ts
> +      .pipe(map((orgs) => orgs.filter(isMember).sort((a, b) => a.name.localeCompare(b.name))));
Updated to use the `Utils` method

2023-04-13 04:53 UTC, eliykat commented
All feedback addressed, although I thought it best to leave the sorting pipe to those components that need it, rather than sorting all orgs every time a new value is emitted.

2023-04-13 16:43 UTC, shane-melton submitted a review, later dismissed
Nice work!

Just saw one line that seemed out of place for the work in this PR, but my guess is its the result of resolving a merge conflict and is fine. No reason to hold up the PR over it though.

2023-04-13 16:43 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault-filter/services/vault-filter.service.ts
> +      const orgNodes: TreeNode<OrganizationFilter>[] = [];
Not quite sure where this came from or why this line was missing. Perhaps a something odd happened after the merge with `master`?

Don't see any need to prevent merging though, but I wanted to mention it.

2023-04-17 01:36 UTC, eliykat commented on apps/web/src/app/vault/individual-vault/vault-filter/services/vault-filter.service.ts
> +      const orgNodes: TreeNode<OrganizationFilter>[] = [];
It was a merge conflict, it shows up in the individual commit diff because it's an addition _to this branch_, but if you look at the total diff for the PR (comparing against master) it's not.

2023-04-17 01:43 UTC, eliykat commented
@shane-melton just had to resolve some more merge conflicts from Rui's Resellers work. The only conflicts were in `organization.ts` which were minimal. Let me know if you have any questions about it

2023-04-17 02:16 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault-filter/services/vault-filter.service.ts
> +      const orgNodes: TreeNode<OrganizationFilter>[] = [];
Ah, thanks for confirming!

2023-04-17 02:18 UTC, shane-melton approved these changes

2023-04-17 03:09 UTC, merged