[PM-1699] Updated low kdf iterations warning
bitwarden/clients pull request #5170
Opened 2023-04-05 20:03 UTC by gbubemismith

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [X] Other
```

## Objective
Update the low KDF warning card.

## Code changes

Changed the card body massage from `Increase your KDF encryption settings to improve the security of your account.` to `Update your encryption settings to meet new security recommendations and improve account protection.` and the link message to `Update KDF settings`.

## Screenshots

https://user-images.githubusercontent.com/13024008/230195570-12535b61-a0a6-4d30-af23-de4bedc39af3.mov

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-04-06 09:50 UTC, djsmith85 requested changes

2023-04-06 09:50 UTC, djsmith85 commented on apps/web/src/locales/en/messages.json
>    "lowKdfIterationsDesc": {
Please also change the translation-key as your change in the source-string won't change the existing translations. Changing the key deletes all existing translations and all translators will get notified about a new string to translate.

2023-04-06 09:50 UTC, djsmith85 commented on apps/web/src/locales/en/messages.json
>      "message": "Change KDF settings"
This should be removed as it's only occurrence is the place that got change with `updateKdfSettings`

2023-04-11 10:48 UTC, djsmith85 approved these changes
@gbubemismith Thanks, this is looking good now.

2023-04-25 13:01 UTC, differsthecat submitted a review, later dismissed

2023-04-25 13:02 UTC, differsthecat commented
@gbubemismith This looks good, looks like there are some conflicts that need to be resolved

2023-05-04 01:38 UTC, eliykat commented
AC Team's review is requested here, but the only changes to our files are imports that are out of order. Note that linting is failing.

I think you need to run linting & prettier locally, then push changes. That should fix the job and drop off the extra teams from the reviewers.

2023-05-04 12:16 UTC, gbubemismith commented
> AC Team's review is requested here, but the only changes to our files are imports that are out of order. Note that linting is failing.
> 
> I think you need to run linting & prettier locally, then push changes. That should fix the job and drop off the extra teams from the reviewers.

I think my ide was messing the files up a bit when I was merging. Everything looks good now.

2023-05-04 13:46 UTC, merged