[PM-1400] Update IconComponent to use OnPush ChangeDetection
bitwarden/clients pull request #5181
Opened 2023-04-07 16:02 UTC by differsthecat

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

OnPush ChangeDetection prevents components from running extra change detection cycles when other events happen around them, but the data within them does not change. In the vault page, there are a lot of instances of the IconComponent, so using this strategy could bring performance improvements.
 
## Code changes

- **StateService:** Add observable for the disableFavicon setting so the IconComponent can react to these changes.
- **IconComponent:** Use `ChangeDetectionStrategy.OnPush` and subscribe to changes to the `disableFavicon` setting.

## Screenshots

UI remains the same

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-04-11 10:51 UTC, Hinton reviewed
There are some caveats to `OnPush` change detection, namely that the input actually have to change. Modifying a property on the CipherView object would not qualify as a change, since it's still the same object.

I don't think we will encounter that here, but worth being aware of.

2023-04-11 10:51 UTC, Hinton commented on libs/common/src/services/state.service.ts
> +  disableFavicon$ = this.disableFaviconSubject.asObservable();
While this works, I don't believe this is the correct place to add the subject. We're working on moving out business logic from the state service into specialized services where this type of subjects should live.

Thoughts on moving it to the `SettingsService`? And actually have that service manage the settings.

2023-04-11 10:51 UTC, Hinton commented on libs/angular/src/vault/components/icon.component.ts
> +    this.stateService.disableFavicon$.pipe(takeUntil(this.destroy$)).subscribe((v) => {
We should only subscribe to the observable once. We seem to be subscribing to the event whenever the inputs are changed, this will cause the load event to be triggered multiple times for a single instance.

Do we know if this might have a performance impact since we could theoretically be subscribing to a lot of observables?

2023-04-11 13:42 UTC, differsthecat commented
> There are some caveats to `OnPush` change detection, namely that the input actually have to change. Modifying a property on the CipherView object would not qualify as a change, since it's still the same object.
> 
> I don't think we will encounter that here, but worth being aware of.

@Hinton Good call out, I did in fact do testing around this, and it is not an issue because in web and browser the cipher object is re-fetched and in desktop the list is reloaded.

2023-04-11 17:35 UTC, differsthecat commented on libs/common/src/services/state.service.ts
> +  disableFavicon$ = this.disableFaviconSubject.asObservable();
Settings service looks like a good candidate; I'll try moving it there and see if I can get rid of the instances of
```ts
const disableFavicon = await this.stateService.getDisableFavicon();
await this.stateService.setDisableFavicon(!!disableFavicon);
```

2023-04-11 17:46 UTC, differsthecat commented on libs/angular/src/vault/components/icon.component.ts
> +    this.stateService.disableFavicon$.pipe(takeUntil(this.destroy$)).subscribe((v) => {
Got it, did some testing, and added `first()` to it to only get it once.

I did some testing on this using Firefox's performance profiler for web and `console.time` for desktop, and from what I observed it takes the same amount of time to load a large vault (with 4k logins) with the latest on master and on this branch. 

Clicking around and editing though feels snappier because the icons instantly load.

**master** (notice the cascading loading of icons):
https://user-images.githubusercontent.com/8926729/231245599-a6bdc4df-c3d6-4550-b95f-663f5f28c8c4.mov


**this branch** (instant loads):
https://user-images.githubusercontent.com/8926729/231245656-94b3a7fb-cdfe-4867-82b1-507a86679912.mov

2023-04-13 15:53 UTC, Hinton commented on libs/angular/src/vault/components/icon.component.ts
> +    });
We should be able to simplify this and use `firstValueFrom` here. Which should also let us get rid of the destroy subject.

```suggestion
    this.imageEnabled = !await firstValueFrom(this.settingsService.disableFavicon);
    this.load();
```

2023-04-13 17:53 UTC, differsthecat commented on libs/angular/src/vault/components/icon.component.ts
> +    });
This turns it into a promise, which because of the OnPush Change detection, it never reacts to the changes. It needs to get the event from the observable in order to change.

2023-04-13 17:55 UTC, differsthecat commented on apps/browser/src/popup/app.component.ts
> +    this.settingsService.setDisableFavicon(await this.stateService.getDisableFavicon());
I'm not the biggest fan of doing this, but I didn't like the alternative way of fixing it, which was updating the base icon component with some more fundamental changes to handle this case only used by the extension. This to me seemed like the best way to handle it.

2023-04-17 09:15 UTC, Hinton commented on libs/angular/src/vault/components/icon.component.ts
> +    });
Not following, maybe I'm missing something. `ngOnChanges` is executed when the input is changed. Both `o$.pipe(first())` and `firstValueFrom(o$)` retrieves only the first value from an observable. Since the observable is a subject it will always have a value and will immediately resole with the setting.

If you want it to continue to react on changes in the `disabledFavicon$` observable, instead of just getting the first value, the observable needs to be moved into the `ngOnInit` and `first()` needs to be removed so that it is notified about further messages.

2023-04-17 09:15 UTC, Hinton commented on apps/browser/src/popup/app.component.ts
> +    this.settingsService.setDisableFavicon(await this.stateService.getDisableFavicon());
What's unique with the browser extension? I would expect the subscription in the settings service would handle assigning correct value to this.

2023-04-19 16:42 UTC, differsthecat commented on apps/browser/src/popup/app.component.ts
> +    this.settingsService.setDisableFavicon(await this.stateService.getDisableFavicon());
It appears to be a race condition happening between when the account changes are fetched and the popup contents are rendered. Here is a demonstration of it with this code removed:

https://user-images.githubusercontent.com/8926729/233141021-647b5ecb-099d-417c-8a62-06f16bba9e3b.mov

When the popup is first rendered, it does not have the value yet in settings service, so when the icon component is loaded, it gets a falsy value for disabeFavicon.

The more I think about it, I wonder if this is a symptom of a larger problem with how our state management works, at least for the popup. I know we are wanting to majorly refactor state service, maybe behavior like this would be fixed with those changes.

2023-04-19 17:44 UTC, differsthecat commented on libs/angular/src/vault/components/icon.component.ts
> +    });
Moved it to ngOnInit, thank you!

2023-04-20 08:50 UTC, coroiu requested changes
Added some information about challenges with `OnPush` when dealing with smart/connected components. Sorry for not reviewing this sooner!

2023-04-20 08:57 UTC, coroiu commented on libs/angular/src/vault/components/icon.component.ts
> +  }
I just saw that you and @Hinton had already discussed the challenge with `OnPush` not triggering change detection if the internals of the `CipherView` changes so you were already up to date on that! The issue I'm describing here is slightly different though, because this deals with updates coming form observables not triggering change detection, instead of changes to `CipherView` not triggering changes.

2023-04-20 09:51 UTC, coroiu commented
Vault items component storybook stories are broken because it's missing a mocked `SettingsService` btw :)

2023-04-20 13:04 UTC, coroiu commented
@differsthecat on chromatic :) https://62a88a6de5b807fa98886113-srsdieaquy.chromatic.com/?path=/story/web-vault-items--individual

2023-04-25 18:10 UTC, differsthecat commented on libs/angular/src/vault/components/icon.component.ts
> +  }
Thank you so much for this thorough write up @coroiu ! 🙌 

I looked over your experiment with a refactor, and I think it is the correct direction to go for this! The reason you are not seeing the icons for the web vault is because of how the icon URL is calculated when running locally. The same issue is present when running master. 

I did some performance testing as well with your changes and they perform just as well! 

Would you mind if I cherry-picked the changes from your test branch to this branch? I believe it is the correct direction for the icon component 🙂

2023-04-26 17:48 UTC, differsthecat commented on apps/browser/src/popup/app.component.ts
> +    this.settingsService.setDisableFavicon(await this.stateService.getDisableFavicon());
This was resolved by a refactor of the observables.

2023-04-26 17:50 UTC, differsthecat commented
@coroiu I cherry-picked your refactor and fixed the broken storybook stories. Can you take another look? 🙂

2023-04-27 09:18 UTC, coroiu reviewed
Looking good! Just a minor issue then approved!

2023-04-27 09:18 UTC, coroiu commented on apps/web/src/app/vault/components/vault-items/vault-items.stories.ts
> +        },
issue: I think you missed a `}` bracket somewhere
```suggestion
        {
          provide: SettingsService,
          useValue: {
            disableFavicon$: new BehaviorSubject(false).asObservable(),
            async getDisableFavicon() {
              return false;
            },
          } as Partial<SettingsService>,
        },
```

2023-04-27 13:39 UTC, coroiu approved these changes
🔥 🔥 🔥

2023-04-28 19:07 UTC, merged