[PM-1803] Fail on unsupported export format
bitwarden/clients pull request #5197
Opened 2023-04-11 14:26 UTC by ajorgensen

Issue #5194: https://github.com/bitwarden/clients/issues/5194

## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

The cli previously would take any value for the export format and default to unencrypted json if it wasn't a supported format. This behavior is a little dangerous because if for instance typed "json_encrypted" instead of "encrypted_json" and naively saved the file you might be surprised to learn the payload was not actually encrypted even though the command completed successfully.

This change adds a guard clause when converting the string value passed in via `--format` into the type `ExportFormat` to ensure that the format provided is one of the supported types.

## Code changes

- **apps/cli/src/commands/export.command.ts**: Added guard clause for export format
- **libs/common/src/abstractions/export.service.ts**: Added list of supported export formats and method to validate that a string is a valid export format.

2023-04-13 13:51 UTC, djsmith85 requested changes
Hi @ajorgensen and thank you for your contribution.

I've actually previously ran into this, while testing something else, so I'm very happy to see you pick this up.

Just one small thing and then we can pass this on to QA.

2023-04-13 13:51 UTC, djsmith85 commented on libs/common/src/abstractions/export.service.ts
> +}
Please move the function and make it a private method in the export.command. It's likely only ever going to be used there.

2023-04-14 19:30 UTC, djsmith85 approved these changes
@ajorgensen Nice work on this and thank you for the quick change response.

This is looking good and passing this on to QA.

2023-04-14 19:32 UTC, ajorgensen commented
No problem at all, happy to help!

2023-04-17 19:53 UTC, djsmith85 commented
@ajorgensen QA has approved your changes and this is ready to merge. Thanks again for your contribution and they will be included in the upcoming release.

2023-04-17 19:54 UTC, merged

2023-04-17 20:04 UTC, ajorgensen commented
Awesome thanks!