[SM-673] redirect from SM root to overview page
bitwarden/clients pull request #5202
Opened 2023-04-12 15:45 UTC by willmartian

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

When users land on `/sm` they are now redirected to their first available organization with access to SM. If the user does not have access to SM, they are redirected to the vault. 

## Code changes

- **bitwarden_license/bit-web/src/app/secrets-manager/sm.guard.ts:** Updated guard to redirect based on available orgs. Rewrote the guard to no longer use the deprecated `CanActivate` interface and to use the new `CanActivateFn` pattern.

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-04-18 13:09 UTC, coltonhurst requested changes
This looks great! Have we considered adding an additional check to first switch to an org they are an owner of? If a user is in 2+ orgs where SM is activated, they might expect to start in the org that they own (or are possibly an admin of).

That's more of a nice-to-have though, there might not be many cases like this for a while.

2023-04-24 15:05 UTC, coltonhurst submitted a review, later dismissed
After further discussion on the above comment, we will approach handling which org is loaded by default in a different way for the future. For now this will handle the redirect perfectly, thanks @willmartian

2023-04-28 14:06 UTC, coltonhurst approved these changes

2023-05-01 14:19 UTC, willmartian commented
[2d17b5c](https://github.com/bitwarden/clients/pull/5202/commits/2d17b5c991df9707fed549127176d56c85b3385d) fixes a bug where the redirect was not working properly after logging in, due to a service initialization race condition. The workaround is also used in the `OrganizationPermissionsGuard` [here](https://github.com/bitwarden/clients/blob/sm/SM-673-redirect-from-root/apps/web/src/app/admin-console/organizations/guards/org-permissions.guard.ts#L26) and should be considered a temporary workaround.

Big thanks to @eliykat for pointing me in the right direction here!

2023-05-03 14:05 UTC, coltonhurst approved these changes
Looks great, thanks for the support @eliykat!

2023-05-05 18:48 UTC, merged