[PM-1839] Bug fix kdf modal
bitwarden/clients pull request #5211
Opened 2023-04-14 11:03 UTC by Dhruwang

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Fixed : [Change KDF modal cannot be closed in the expected way #5091
](https://github.com/bitwarden/clients/issues/5091)

In '[Encryption key settings](https://vault.bitwarden.com/#/settings/security/security-keys)', when we click on "Change KDF" , it triggers a modal to open.

In that modal there is a button at bottom named "cancel" which when clicked on, does nothing. Instead it should close the modal.

## Code changes

made changes in "change-kdf-confirmation.component.html"

Added bitDialogClose derivative to cancel button , which means that clicking on the button will close the dialog.

The [bit-dialog-close] input is set to false, which means that false will be passed back to the parent component when the dialog is closed.

Overall, this button will close the dialog and pass back false as the result when it is clicked.

## Screenshots

Before

https://user-images.githubusercontent.com/67850763/232026953-016e4737-2c96-4daa-8732-afdcbdc124f9.mp4

After 

https://user-images.githubusercontent.com/67850763/232027248-bcf4d514-a37a-4b71-a912-d418ae62e235.mp4

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-04-14 11:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitwarden/clients?pullRequest=5211) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bitwarden/clients?pullRequest=5211) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitwarden/clients?pullRequest=5211) it.</sub>

2023-04-16 05:09 UTC, Dhruwang commented
@justindbaur can you please review this pr ?

2023-04-21 11:40 UTC, Hinton requested changes
One minor adjustment, adding `bitDialogClose` should be enough.

2023-04-21 11:40 UTC, Hinton commented on apps/web/src/app/settings/change-kdf/change-kdf-confirmation.component.html
> +      [bit-dialog-close]="false"
This shouldn't be needed.

```suggestion
```

2023-04-21 13:35 UTC, Dhruwang commented
Thank you @Hinton !
Committed changes

2023-04-25 08:52 UTC, Dhruwang commented on apps/web/src/app/settings/change-kdf/change-kdf-confirmation.component.html
> +    >
Ya sure

2023-06-28 05:27 UTC, closed without merging