[AC-1120] Implement 'New' button dropdown in Individual Vault
bitwarden/clients pull request #5235
Opened 2023-04-18 13:26 UTC by differsthecat

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-04-19 04:07 UTC, eliykat requested changes

2023-04-19 20:22 UTC, differsthecat commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +        )[0].id,
Yes, great catch!

2023-04-19 20:40 UTC, differsthecat commented on apps/web/src/app/vault/individual-vault/vault.module.ts
> +    CoreOrganizationModule, // Needed to open the CollectionDialogComponent
Ah I missed it is in it's own module!

2023-04-19 20:45 UTC, differsthecat commented on apps/web/src/app/vault/individual-vault/vault.module.ts
> +    CoreOrganizationModule, // Needed to open the CollectionDialogComponent
I remember why I did it this way. The CollectionDialongComponent uses GroupService, which unless I import the CoreOrganizationModule, is null here.

2023-04-20 20:06 UTC, differsthecat commented on apps/web/src/app/admin-console/organizations/shared/components/collection-dialog/collection-dialog.component.html
> +            <bit-select bitInput formControlName="selectedOrg" (ngModelChange)="changeOrg($event)">
That is much cleaner, thank you!

2023-04-20 20:07 UTC, differsthecat commented on apps/web/src/app/admin-console/organizations/shared/components/collection-dialog/collection-dialog.component.ts
> +  async loadOrg() {
I'd rather be on the safe side, added!

2023-04-20 20:15 UTC, differsthecat commented on apps/web/src/app/admin-console/organizations/core/services/collection-admin.service.ts
> +    await this.collectionService.upsert(c);
That's a really good point; I was trying to keep my changes to the CollectionDialog Component as minimal as possible, but I think the way to go here is as you suggest; pass in the collections, and when the collection is created, pass that back from the modal in the result and call `upsert()` from the Vault Component.

2023-04-21 19:35 UTC, differsthecat commented on apps/web/src/app/admin-console/organizations/core/services/collection-admin.service.ts
> +    await this.collectionService.upsert(c);
@eliykat This line in the ticket you quoted was something I had added with my understanding at the time of how this should work:
> Make sure the list of collections in the collection modal only includes ones the user can create collections in.

I am not sure that is what is expected though. If we want to be consistent, then they should work the same regardless of what vault you are in (org or individual), especially since you are allowed to (from my testing) create collections nested under ones you do not have access to. But at the same time, it doesn't make a whole lot of sense to me that it is allowed.

I'll rope in Product and see what their thoughts are on this.

2023-04-25 15:43 UTC, differsthecat commented on apps/web/src/app/admin-console/organizations/core/services/collection-admin.service.ts
> +    await this.collectionService.upsert(c);
I checked in with Product, and we do want to filter out collections when opening this dialog from the Individual Vault.

I approached this by passing in the collectionIds (which are ones the user has permission to) to the CollectionDialog, and filtering out collections that do not match. I did it this way as it made more sense to me to keep the responsibility of the CollectionDialog in getting the collections, partially because the CollectionAdminView has additional fields that the Individual Vault should not have to handle (groups and users).

I also removed the call to `collectionService.upsert()` from the CollectionAdminService and instead return the collection from the `save()` method, which the IndividualVault responds to and calls `collectionService.upsert()`

2023-05-05 00:33 UTC, eliykat commented
Just noting that I'm holding off on any further review until we have AC-1383 done, to sort out code ownership for collection related stuff.

2023-06-13 09:28 UTC, djsmith85 approved these changes

2023-06-14 13:15 UTC, differsthecat commented on apps/web/src/app/vault/individual-vault/vault.module.ts
> +    CoreOrganizationModule, // Needed to open the CollectionDialogComponent
Removed this as the GroupService changes fixed this dependency 😎

2023-06-15 12:14 UTC, differsthecat commented
@eliykat This PR is ready for review again! With the file move changes, it's now only touching vault code 🥳

2023-06-15 16:09 UTC, gbubemismith approved these changes
This looks good. Nice job @differsthecat

2023-06-16 14:54 UTC, micahblut commented
Should we remove the "+" next to folders in the left nav to avoid duplicate ways of doing the same task?

2023-06-16 15:00 UTC, differsthecat commented
> Should we remove the "+" next to folders in the left nav to avoid duplicate ways of doing the same task?

@micahblut I can do that in this PR, it makes sense to do so!

2023-06-20 05:52 UTC, eliykat requested changes

2023-06-20 05:52 UTC, eliykat commented on apps/web/src/app/vault/individual-vault/vault-filter/components/vault-filter.component.ts
> -      },
I think that this was the only vault filter section using the `+` add button. Can we delete the [templating for this](https://github.com/bitwarden/clients/blob/master/apps/web/src/app/vault/individual-vault/vault-filter/shared/components/vault-filter-section.component.html#L38-L46)? Plus the `showAddButton` getter.

(not a rhetorical question - this part of the code is curly, so I might be wrong)

2023-06-20 05:52 UTC, eliykat commented on apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.ts
> +    this.loadOrg(this.params.organizationId, this.params.collectionIds);
Optional, but I think it's handy: you can jump start a `valueChanges` observable with `startWith`. For example, instead of this:

```ts
      this.formGroup.controls.selectedOrg.valueChanges
        .pipe(takeUntil(this.destroy$))
        .subscribe((id) => this.loadOrg(id, this.params.collectionIds));

        // repeating ourselves
        this.loadOrg(this.params.organizationId, this.params.collectionIds);
```

You can do this:


```ts
      this.formGroup.controls.selectedOrg.valueChanges
        .pipe(takeUntil(this.destroy$), startWith(this.params.organizationId))
        .subscribe((id) => this.loadOrg(id, this.params.collectionIds));
```

Although now that I look at it again, if you set up that subscription before `patchValue` instead of after, it should be triggered by `patchValue` anyway, and you won't need either `startWith` or the initial call.

2023-06-20 05:52 UTC, eliykat commented on apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.ts
> +        });
You can delete the subscribe call and use the async pipe in the template instead, which is generally preferable. Then you don't need `takeUntil` either.

2023-06-20 05:52 UTC, eliykat commented on apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.ts
> +}
Suggestion: an interface would be more lightweight here.

2023-06-20 05:52 UTC, eliykat commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +      // deletion is implemented in the individual vault.
Is this a TODO for this PR or a later PR? Can you point to a Jira ticket?

Do we need a workaround in the meantime - will this cause unexpected behaviour in its current form?

2023-06-20 16:28 UTC, differsthecat commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +      // deletion is implemented in the individual vault.
AC-1347 has this work; I added the ticket # to the comment to clarify. There is currently no way to hit this until AC-1347 is implemented, but I wanted to add this to help whoever may pick that one up.

2023-06-20 17:30 UTC, differsthecat commented on apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.ts
> +    this.loadOrg(this.params.organizationId, this.params.collectionIds);
That's a good point, but after playing with it a bit, I realized there was a reason there is the extra `loadOrg()` call and that is to handle the case where the collection dialog is opened by the user in the org vault. I moved the call the `patchValue` to be below the selectredOrg subscription and added extra comments to clarify. See [this commit](https://github.com/bitwarden/clients/pull/5235/commits/348b67b7502aa83abdc0c414ab58fa7318ab2a65) for the changes I did!

2023-06-20 18:28 UTC, differsthecat commented on apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.ts
> +        });
Ah that was a perfect one for that, updated!

2023-06-21 00:12 UTC, eliykat commented on apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.ts
> +    this.loadOrg(this.params.organizationId, this.params.collectionIds);
I understand your updated code better, thanks!

2023-06-21 00:13 UTC, eliykat approved these changes
Great work!

2023-06-27 15:36 UTC, merged