[AC-1088] Set no-wrap to 'select all' column on groups table
bitwarden/clients pull request #5236
Opened 2023-04-18 13:44 UTC by r-tome

## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

This is to fix a bug on the Groups table that is making the 'select all' column to overflow. When a Group has assigned Collections with long names it causes that column to occupy all available space.

## Code changes

- **apps/web/src/app/admin-console/organizations/manage/groups.component.html:** Disabled the 'select all' column overflow

## Screenshots
Previous:
![image](https://user-images.githubusercontent.com/108268980/232796682-822199dd-fa75-43a0-b1da-0e8b162deefe.png)

No-wrap:
<img width="1318" alt="image" src="https://user-images.githubusercontent.com/108268980/232796531-4370d3cc-bd49-4a69-86b2-9f4352a27cb4.png">

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-05-01 00:11 UTC, eliykat requested changes
You've done this correctly, but my advice was bad 😁  I tagged you in a discussion in `#code` where we discussed `EllipsisPipe`. @coroiu pointed out that CSS can do this for us with the [text-overflow](https://www.w3schools.com/cssref/css3_pr_text-overflow.php) property. The equivalent tailwind classes are [here](https://tailwindcss.com/docs/text-overflow).

Please
* mark `EllipsisPipe` as deprecated using `@deprecated`, see [here](https://github.com/bitwarden/clients/blob/master/apps/browser/src/services/browserPlatformUtils.service.ts#L85-L87) for an example
* use Tailwind CSS to hide the extra characters. This is now going into component library stuff, so here are some pointers:
  * `BadgeListComponent` is just a loop around `BadgeDirective`s, which are responsible for displaying the individual badges. I think it's best to add the text-overflow class at the individual badge level so that we have consistent behaviour - see the `BadgeDirective.classList` method
  * then we need a way of limiting the size of each badge to make sure the text gets truncated. You probably need an input binding (`@Input()`) on `BadgeListComponent` where you can specify a max width for each badge, then use that to set a [max width using Tailwind classes](https://tailwindcss.com/docs/width).
  * make sure you're running Storybook locally (`npm run storybook`) to preview the badge components without needing to refresh your whole web vault each time

@coroiu does this sound like a reasonable approach to you?

2023-05-01 09:45 UTC, Hinton commented
@bitwarden/dept-design mind weighing in on the badge truncation changes? Do we need sizes and if so, what should they be.

2023-05-02 17:03 UTC, jtouchstonebw commented
> @bitwarden/dept-design mind weighing in on the badge truncation changes? Do we need sizes (or just a simple boolean) and what should the sizes be.

The design team discussed it and we are in agreement that for now we only see the need for setting a max character count for truncation.

2023-05-04 23:17 UTC, eliykat reviewed
Please add stories for a truncated badge and a truncated badge list. See `badge.stories.ts` and `badge-list.stories.ts` and the Storybook documentation. This is so we have examples of the `truncate` option at components.bitwarden.com, and we'll get a failing test if someone accidentally changes the `truncate` behaviour in the future.

2023-05-07 22:38 UTC, eliykat requested changes
This is looking really good!

@r-tome one more small change I discussed with Oscar is to make truncation the default behaviour. It's probably what devs want 90% of the time.

Changing the default will affect everywhere the component is currently used, but it's only used in a few places at the moment. You can just review these usages & mark them for QA regression testing. (You can also set `[truncate]="false"` on them to preserve existing behaviour but it would be better to align them with default behaviour)

@bitwarden/dept-design could you please approve these Storybook changes?

2023-05-09 16:55 UTC, Hinton commented on libs/components/src/badge/badge.directive.ts
> +          : ["tw-inline"]
Any reason we switch between `tw-inline-block` and `tw-inline`? That might cause design inconsistencies if you enable truncate.

2023-05-10 11:43 UTC, r-tome commented on libs/components/src/badge/badge.directive.ts
> +          : ["tw-inline"]
Good question, I had to use `tw-inline-block` for `tw-truncate` to work but it should be used for both cases.

2023-05-10 12:30 UTC, r-tome commented
> Changes look good. I think we need to add a <title> attribute for when the text is truncated so a user can hover and still see the full name of the item. Is that something that makes sense to add at the component level?

Thanks for the suggestion @danielleflinn. I've had a go at implementing that at the component level. If the badge is set to truncate and no title is defined then the title attribute is added.

2023-05-10 15:15 UTC, danielleflinn submitted a review, later dismissed

2023-05-11 08:19 UTC, Hinton commented on libs/components/src/badge/badge.directive.ts
> +  }
We should be able to use [`@HostBinding`](https://angular.io/api/core/HostBinding) here.

2023-05-12 01:06 UTC, eliykat requested changes

2023-05-12 01:06 UTC, eliykat commented on libs/components/src/badge-list/badge-list.component.html
> +    [attr.title]="truncate ? item : null"
This is duplicating your code in `BadgeDirective`. You should be able to let `BadgeDirective` handle setting the title if required.

2023-05-30 04:53 UTC, eliykat commented
LGTM, please resolve conflicts and I can approve.

2023-05-30 05:04 UTC, eliykat requested changes
Just double checked this and the individual badge component is no longer truncating: https://62a88a6de5b807fa98886113-fztjbgvlea.chromatic.com/?path=/story/component-library-badge--primary

The `title` tooltip is also picking up a random line break and comma from somewhere: https://62a88a6de5b807fa98886113-fztjbgvlea.chromatic.com/?path=/story/component-library-badge-list--truncated. Maybe because you're using `innerText`, it's picking up DOM whitespace and/or children?

The changes otherwise look good once these are resolved.

2023-05-31 15:17 UTC, r-tome commented
> Just double checked this and the individual badge component is no longer truncating: https://62a88a6de5b807fa98886113-fztjbgvlea.chromatic.com/?path=/story/component-library-badge--primary
> 
The individual badge should be truncating when the toggle is switched on.

> The `title` tooltip is also picking up a random line break and comma from somewhere: https://62a88a6de5b807fa98886113-fztjbgvlea.chromatic.com/?path=/story/component-library-badge-list--truncated. Maybe because you're using `innerText`, it's picking up DOM whitespace and/or children?
> 
A comma is added on the badge-list component for screen readers, that is what was being picked up. I've modified this to exclude it from the tooltip text.

Good looking out @eliykat , thanks again!

2023-05-31 22:41 UTC, eliykat approved these changes
Great work!

2023-06-05 06:43 UTC, Hinton commented on libs/components/src/badge/badge.directive.ts
> +    return this.truncate ? this.el.nativeElement.childNodes[0].textContent.trim() : null;
I think this leaks badge-list implementation behaviors to the badge component. It will also produce unexpected behavior if we ever create a badge with emphasis, itallic or links in it. Any reason the commas were placed inside the badge instead of outside?

Ideally we would want to avoid using nativeElement directly. But not sure we could do that without moving title to the badge-list component.

2023-06-05 15:17 UTC, r-tome commented on libs/components/src/badge/badge.directive.ts
> +    return this.truncate ? this.el.nativeElement.childNodes[0].textContent.trim() : null;
Very good point @Hinton, I've moved the comma out from each badge and modified the `title` text to be retrieved using `this.el.nativeElement.textContent.trim()`

2023-06-06 21:01 UTC, Hinton commented on libs/components/src/badge/badge.directive.ts
> +    // If the text is truncated then a tooltip is added with the full text except the comma that is added for screen readers on badge lists
Comment is no longer relevant.

2023-06-06 21:02 UTC, Hinton commented on libs/components/src/badge/badge.directive.ts
> +      "tw-align-text-top",
This should be placed next to the other font related classes.

2023-06-07 10:48 UTC, r-tome commented on libs/components/src/badge/badge.directive.ts
> +      "tw-align-text-top",
Yes, it is required because `tw-truncate` requires `tw-inline-block` which then slightly moves the text in relation to other badges that don't have `truncate` enabled.

2023-06-08 09:00 UTC, Hinton approved these changes
It's unfortunate that we need to use nativeElement to get the text content, but short of changing the badge to accept an input which might remove functionality it's as good as it's going to get.

CL changes looks good.

2023-06-12 09:56 UTC, merged