[SM-664] Checking if the user has selected access tokens to revoke, if not err…
bitwarden/clients pull request #5299
Opened 2023-04-27 14:38 UTC by cd-bitwarden

…or message

## Type of change

```
- [ x ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Check if the user has selected access token to revoke, if not show error message

## Code changes

apps/web/src/locales/en/messages.json - adding localization for the phrase of "no access tokens selected to revoke"
bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/access-tokens.component.ts - checking if the tokens exist that we are trying to delete before doing logic to revoke them

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-04-27 16:14 UTC, coltonhurst requested changes
Looks good, just one question about the description in `messages.json`.

2023-04-27 16:14 UTC, coltonhurst commented on apps/web/src/locales/en/messages.json
> +    "description": "Toast message after trying to delete access tokens but not selecting and access tokens."
Should this be `"Toast error message after trying to delete access tokens but not selecting any access tokens."`? (Main change was changing `and` to `any`)

2023-04-27 20:48 UTC, coltonhurst requested changes
Looks great! One other thought - to match other areas we could check `!tokens?.length` up front to reduce indentation in the `revoke` function, and to handle if tokens is ever `null` or `undefined`. Let me know what you think?

```
if (!tokens.length) {
  this.platformUtilsService.showToast(
    "error",
    null,
    this.i18nService.t("noAccessTokenSelected")
  );
  return;
}

if (!(await this.verifyUser())) {
  return;
}

await this.accessService.revokeAccessTokens(
  this.serviceAccountId,
  tokens.map((t) => t.id)
);

this.platformUtilsService.showToast("success", null, this.i18nService.t("accessTokenRevoked"));
```

2023-05-04 18:54 UTC, Thomas-Avery approved these changes
LGTM

2023-05-09 13:56 UTC, merged