[PM-2100] Create Unit Test Suite for autofill.service.ts
bitwarden/clients pull request #5371
Opened 2023-05-04 20:23 UTC by cagonzalezcs

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

The object of this PR is to build a test suite for `autofill.service.ts`. The scope of these changes should encompass unit tests nearly exclusively, and should not represent any changes in logic. Some organization of the code might occur, but core logic should remain unchanged.

## Code changes

TBD

## Screenshots

TBD

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-06-27 14:56 UTC, cagonzalezcs commented on apps/browser/src/autofill/services/autofill.service.ts
> +        } else if (
Note for reviewers -  This change and other changes found within this method address a logical error that was being encountered when testing. We should be attempting a check within `fieldAttrsContain` against longer values before shorter ones (ie. testing `mm/yyyy` before `mm/yy`).

The method `fieldAttrsContain` is written in such a manner that `mm/yyyy` would pass agains the check for `mm/yy` enacting the wrong logic.

2023-06-27 14:56 UTC, cagonzalezcs commented on apps/browser/src/autofill/services/autofill.service.ts
> +        AutofillService.fieldIsFuzzyMatch(f, AutoFillConstants.TotpFieldNames)
Note for reviewers -  An issue was found when calling this method where we would attempt to treat other text fields as the TOTP field.

This check provides a guard against that.

2023-06-27 14:56 UTC, cagonzalezcs commented on apps/browser/src/autofill/services/autofill.service.ts
> +    return Boolean(str && str !== "");
Note for reviewers -  When we do not cast this as a Boolean, we potentially return the passed `str` value. For instance, if we pass `''` to the method, this expression will pass back `''` instead of `'false`. This change fixes that to ensure we are passing back a boolean value.

2023-06-27 15:32 UTC, cagonzalezcs commented on apps/browser/src/autofill/services/autofill.service.ts
> -      const passwordFieldsForForm: AutofillField[] = [];
Note to reviewers - This variable and the logic enacted on the `passwordFields` array have been removed. We do not use `passwordFieldsForForm` anywhere within this method or file.

2023-06-27 16:36 UTC, jprusik commented on apps/browser/src/autofill/services/autofill.service.ts
> +  ): Promise<string | null> {
With the early return, should this be

```suggestion
  ): Promise<string | null> | null {
```

2023-06-27 16:38 UTC, jprusik commented on apps/browser/src/autofill/services/autofill.service.ts
> +  ): Promise<AutofillScript | null> {
same here:

```suggestion
  ): Promise<string | null> | null {
```

2023-06-27 16:53 UTC, cagonzalezcs commented on apps/browser/src/autofill/services/autofill.service.ts
> +  ): Promise<string | null> {
Hmm... not quite, if a method is delineated as an `async` method, then all values returned from the method are wrapped in a Promise, this includes void return values. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function#description 

As a result, this method will return a Promise with a potential `null` value, even if the `await`-ed method is not hit.

2023-06-27 16:54 UTC, cagonzalezcs commented on apps/browser/src/autofill/services/autofill.service.ts
> +  ): Promise<AutofillScript | null> {
Same comment as above.

2023-06-27 16:54 UTC, jprusik commented on apps/browser/src/autofill/services/autofill.service.ts
> +        AutofillService.fieldIsFuzzyMatch(f, AutoFillConstants.TotpFieldNames)
I like narrowing the cases where we take a chance at where a TOTP should go, given it's role as a credential. 👍

2023-06-27 16:58 UTC, jprusik commented on apps/browser/src/autofill/services/autofill.service.spec.ts
> +              ["focus_by_opid", "password-field"],
would be nice to reference these as constants, but nbd imo

2023-06-27 17:03 UTC, jprusik approved these changes
some non-blocking nits, but lgtm, especially given that this won't be seeing production for quite a while (and will be tested along the way), still

2023-06-27 18:26 UTC, jprusik commented on apps/browser/src/autofill/services/autofill.service.ts
> +  ): Promise<string | null> {
ah right - I totally missed the `async` 😅

2023-06-28 20:14 UTC, djsmith85 reviewed
@jprusik, @cagonzalezcs 
Could one of you please move the `autofill-mocks.ts` into a subfolder (new one or existing autofill 🤷 ?) and if needed: Create a line in the [CODEOWNERS](https://github.com/bitwarden/clients/blob/master/.github/CODEOWNERS) so that any autofill related tests are owned by `team-client-integrations-dev`

2023-06-28 20:15 UTC, djsmith85 requested changes
@jprusik, @cagonzalezcs 
Could one of you please move the `autofill-mocks.ts` into a subfolder (new one or existing autofill 🤷 ?) and if needed: Create a line in the [CODEOWNERS](https://github.com/bitwarden/clients/blob/master/.github/CODEOWNERS) so that any autofill related tests are owned by `team-client-integrations-dev`

2023-06-28 20:50 UTC, cagonzalezcs commented
> @jprusik, @cagonzalezcs Could one of you please move the `autofill-mocks.ts` into a subfolder (new one or existing autofill 🤷 ?) and if needed: Create a line in the [CODEOWNERS](https://github.com/bitwarden/clients/blob/master/.github/CODEOWNERS) so that any autofill related tests are owned by `team-client-integrations-dev`

Sure, I'll make these updates.

2023-06-28 21:04 UTC, cagonzalezcs commented
@djsmith85 

I've moved the jest utils files into the `/src/autofill/jest` directory. Based on what I see of the `CODEOWNERS` file, these should now fall under the ownership of the Client Integrations team

2023-06-28 22:05 UTC, djsmith85 approved these changes

2023-06-29 19:53 UTC, Hinton commented on jest.config.js
> +  },
Seems odd we need this in the root file? I would assume only browser needing it if at all.

2023-06-29 20:49 UTC, cagonzalezcs commented on jest.config.js
> +  },
@Hinton Hmm, let me update that and test it. 

It definitely makes sense to scope the config as closely as possible to the affected area.

I made this change some time ago, so I do not remember the warning provided... but I believe that Jest was complaining about how we were transforming typescript files, or at least the way that was defined within our config.

2023-06-29 20:53 UTC, cagonzalezcs commented on jest.config.js
> +  },
Hm.... someone must have fixed the warning between when I added this change and now. Running tests with this code removed does not show the same issue as was previously present.

I'm removing it, thank you for catching that!

2023-07-06 15:08 UTC, cagonzalezcs commented
This ticket has been validated by QA. I'm going to hold off on merging this into #5453 for the moment. I'd like to avoid bloating the review of that PR, so I'll hold off on merging this until #5453 is approved.

2023-08-02 14:49 UTC, cagonzalezcs commented
Merging this branch into the work done for PM-2130 (#5453) to minimize how many reviews have to be completed in order to move autofill v2 into master.

2023-08-02 14:49 UTC, merged