[PM-2147] [BEEEP] Open login form used to unlock extension in a separate window instead of a tab
bitwarden/clients pull request #5384
Opened 2023-05-05 20:21 UTC by cagonzalezcs

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Reimplementing the workflow for how we handle a user who is attempting an autofill when their vault is locked. 

With this implementation, we are now opening the password prompt in a window that will always be focused and presented at the top left corner of the currently active browser window. Users can now enter their password in this window and the vault will unlock and autofill the password in the exact same manner as before. 

Anytime a user re-attempts a autofill with a locked vault, we first check for existing windows that contain the login form and close them before re-opening the login prompt in the top left corner of the currently active window.

We now also display a notification to the user in the same UI design that is used to display the "Add/Update Cipher" notification. This notification has the ability to re-open the prompt to login to the vault.

## Code changes

TBD

## Screenshots

https://user-images.githubusercontent.com/16629865/236561334-103e8e96-57cc-424c-b4af-f21472af16fd.mov

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-05-09 17:32 UTC, danielleflinn commented
This is awesome. Thanks for working on this user experience bug. 

@cagonzalezcs How did you decide on opening the window in the top left? 

Also can you explain more of your thinking behind adding the notification and "Unlock" prompt? Is this in case the user accidentally closes the unlock window, the notification will allow the user to re-open without having to use the shortcut again/re-attempt auto-fill through the context menu?

2023-05-15 13:17 UTC, cagonzalezcs commented
@danielleflinn 

So the goal with moving the opening position from a new tab to the window at the top left is done to solve two issues:

1. Ensure that the user's attention is not diverted in as harsh of a manner as opening a new tab and completely changing context presents.
2. Ensuring that the context for the user login action, ie. autofilling a password into a specific website, is not lost in some manner.

I opted to open the window in the top left corner of the currently active browser because of how that mechanism works when opening any new window in a browser using a keystroke. For instance, if you press CMD + N on the MacOS version of Chrome/Firefox, a new window opens int the top left corner of the currently active window. As a result, our mechanism for opening this window for users should mimic that default action.

The goal of the notification was to ensure that users had an “anchor” to reference when being required to login when triggering an autofill. This requirement came through a conversation I had with @djsmith85 regarding potential pitfalls surrounding having the login form open in a new window rather than a new tab. He felt that it was too easy for users to potentially lose the login window behind another browser window, and this notification allows the user the ability to quickly recall the login form if that does happen.

Also, yes if the user closes the login window, they can open it either using this notification or another autofill keystroke.

2023-05-15 17:10 UTC, danielleflinn commented
@cagonzalezcs Thanks for clarifying the window placement. For the [save passkey in Bitwarden](https://www.figma.com/file/K7u674lSE0UJrAFK9ikzT9/Passkeys?type=design&node-id=178-11737&t=PLq34huulwN8Fe5V-4) work, the window opens in the top right–the thinking there was to keep the window near the extension icon where users are already used to looking for it. Initially I thought it might be good to standardize the window placement but perhaps this is not as big of a deal as I originally thought since the passkey popout is not triggered by a keystroke.

2023-05-17 13:28 UTC, cagonzalezcs commented
@danielleflinn 

Hmm... it'd make sense to keep this consistent with other plans for the extension. Shouldn't be a huge issue to modify it to open in the top right either. I'll do that this Friday when we have some BEEEP time.

2023-05-19 20:16 UTC, cagonzalezcs commented
@danielleflinn 

I've updated the implementation to have the window open in the top right corner rather than the top left corner, as you suggested. I think the implementation works better that way as well, given that the notification shows a CTA which can be confusing to end users. Now that we are opening the window over that region, we hide the CTA and  if a user moves the window away from the original position the CTA presents itself as a quick way to re-position the login form.

The video within the description shows the new behavior in action.

2023-06-01 13:19 UTC, LRNcardozoWDF reviewed
@cagonzalezcs awesome job! This looks good to me, additional reviews on this would be appreciated.

2023-06-01 14:43 UTC, LRNcardozoWDF approved these changes

2023-06-12 08:31 UTC, djsmith85 requested changes

2023-06-13 10:30 UTC, djsmith85 approved these changes
@cagonzalezcs Awesome work on this 🚀 Code-wise and testing this locally, this is looking great.

I'm approving this, as it works and should be moved on to QA.

One thing to look at and discuss with product/design is the edit view. This was introduced with https://github.com/bitwarden/clients/pull/4808. Currently the window will close after unlocking and then the add-edit-view is opened in a new tab. It might be nicer to keep the window open and then navigate to that page. I know, piling on more complexity to the retry-commands

2023-06-28 16:02 UTC, djsmith85 approved these changes
Approval for team-leads-eng

2023-07-03 14:50 UTC, cagonzalezcs commented
@eliykat made an excellent observation when reviewing this BEEEP. He saw that when we were opening the popup window, we were not showing the address bar to the end user. This facilitates a potential spoofing attack, which could potentially allow someone to trick a user to enter their master password into a website that looks exactly like our login page.

As a result, I've made a modification to how we open this login prompt window. Though the overall UI presentation looks less clean, we will now open the window as a normal window instead of a popup. This unfortunately forces us to show the prompt for login as a fully featured window, with all of the UI elements of a normal window visibly present. I attempted to find a manner in which we could facilitate ONLY showing the address bar, but [a longstanding issue within the extensions API](https://bugs.chromium.org/p/chromium/issues/detail?id=108875&q=popup%20bar&colspec=ID%20Pri%20Mstone%20ReleaseBlock%20OS%20Area%20Feature%20Status%20Owner%20Summary) prevents us from doing so.

That said, the user's experience is similar in scope to my original intentions for this change... and showing the address bar is such a vital requirement to ensure users know where they are entering their password that I think we can afford to have a slightly "busier" presentation. The video below shows the change in action:


https://github.com/bitwarden/clients/assets/16629865/93539f52-bd6a-4c4d-965b-92b3c93050f8

2023-07-13 16:34 UTC, cagonzalezcs commented
@djsmith85 

Along with the change requested by Thomas, there were some bug fixes brought forward from QA that we needed to apply to these changes. As a result, your review/approval of this PR is now stale. 

When you have some time, could you please re-approve this PR? If you'd like to review the changes that made your review stale, you can check out the following commits.

- https://github.com/bitwarden/clients/commit/a7c6f9962dcb795b00d2f017f6a8edce3547a588
- https://github.com/bitwarden/clients/pull/5384/commits/55e837bf698541fccfe9790bf390d6d1514febb1
- https://github.com/bitwarden/clients/pull/5384/commits/eeebe8319924ea32a39dbe0d0b649dcbe9d11c86

Please let me know if you have any questions on this.

Thank you!

2023-07-13 16:41 UTC, jprusik approved these changes

2023-07-13 17:34 UTC, djsmith85 approved these changes

2023-07-13 19:01 UTC, MGibson1 requested changes

2023-07-13 19:01 UTC, MGibson1 commented on apps/browser/src/platform/browser/browser-api.ts
> +    const url = chrome.extension.getURL("popup/index.html?uilocation=popout");
:warning: It feels jarring to assume that all logged out popups should be closed when you pop up from the notification window.

popups are routed there automatically when locked, so this effectively closes all popups, always.

I believe what you're doing is ensuring you don't get 100 open windows, which is great, but can we do it through keeping a reference to the created window elsewhere instead? That way we don't mess up people's flow should they feel they need 6 different popouts open.

2023-07-13 20:29 UTC, jprusik commented on apps/browser/src/platform/browser/browser-api.ts
> +  }
This is addressed in the follow-on bugfix here:
https://github.com/bitwarden/clients/pull/5621

2023-07-13 21:24 UTC, MGibson1 commented on apps/browser/src/platform/browser/browser-api.ts
> +  }
yup, that looks like it addresses the concern

2023-07-13 21:27 UTC, cagonzalezcs commented on apps/browser/src/platform/browser/browser-api.ts
> +    const url = chrome.extension.getURL("popup/index.html?uilocation=popout");
@MGibson1 

I agree with the assertion that closing all popups when attempting to unlock a vault is aggressive. I purposefully put that behavior in place, but am willing to approach the implementation differently.

That said, my approach here takes into consideration behavior the I observed from the extension itself. A user does not have the ability to pop out the vault UI while the extension is in a locked state. I also observed that when the vault is being locked manually within the extension settings, that all other popups close promptly. My assumption from those two observations is that if the vault is locked, checking for any existing popups and closing them ensures we do not show multiple instances of the login prompt window.

I went ahead and tested the auto-locking behavior of a vault when a vault timeout of 1 minute is set, and a set of popout views are currently open. It appears that we do not actually lock the vault at all when any number of popout views are present. This can be seen in the video below, should this be the case or is the expected UX different from our implementation?


https://github.com/bitwarden/clients/assets/16629865/8d39fac6-522d-4cf1-9364-dedb2863086f

2023-07-13 21:27 UTC, cagonzalezcs commented on apps/browser/src/platform/browser/browser-api.ts
> +  static getWindow(windowId?: number): Promise<chrome.windows.Window> | void {
Sure, I'll get up a change that puts this closer to `getTab`.

2023-07-13 21:28 UTC, cagonzalezcs commented on apps/browser/src/platform/browser/browser-api.ts
> +  }
@MGibson1 

Is @jprusik approach a methodology that better fits your concern? 

I can either pull his work for these specific methods into my PR, or we can wait until his PR is merged to provide a more generic method for handling opening and close the login prompt window.

Just let me know.

2023-07-13 21:56 UTC, cagonzalezcs commented on apps/browser/src/platform/browser/browser-api.ts
> +  }
If I remember correctly, I placed the method for opening the window within the BrowserApiService class because I had seen another method named `openBitwardenExtensionTab` within the service.

Digging through the code, what might make sense here is to incorporate the calls to open/close the login prompt window within the `VaultTimeoutService` that is instantiated in the main background script. Either that or create a new service that would handle this behavior. There is a `PasswordRepromptService` class within the `/browser/vault/popup/services/` folder, but this service is structured as an Angular specific Injectable....

2023-07-13 22:00 UTC, cagonzalezcs commented on apps/browser/src/platform/browser/browser-api.ts
> +  static getWindow(windowId?: number): Promise<chrome.windows.Window> | void {
@MGibson1 

This has been pushed up.

2023-07-14 13:45 UTC, cagonzalezcs commented on apps/browser/src/platform/browser/browser-api.ts
> +    const url = chrome.extension.getURL("popup/index.html?uilocation=popout");
@MGibson1 

Was revisiting this concern early today, so I realized why I opted to hold off on your suggested implementation. The `BrowserApi` class is structured to function entirely as a set of static utility methods. I approached these additions in a similar manner, which puts us in a position where we are unable to rely on stateful values within the classes to update and reference.

If this approach is considered too aggressive, there might be merit to having me move this functionality to a separate service that maintains state. 

Would you like me to refactor this implementation to do that?

2023-08-02 19:14 UTC, MGibson1 approved these changes
Very clean changes, I like it

2023-08-07 14:56 UTC, jprusik approved these changes

2023-08-07 21:06 UTC, merged

2023-10-03 14:09 UTC, Camusensei commented
Hi. Just noticed the change in my extension and could not understand some things. Maybe if I knew how to find the page for PM-2147 so feel free to direct me to it if the answers are there.

First is the reason, it's not explained here. Why the change? Historically it would open the popout, then it was changed to a new tab, now to a new window. I'm fine either way, but why these changes?

And the second one is that I don't see the bitwarden extension tag in firefox like shown in the video, so any extension could be showing me the popup and I wouldn't know (unless I remembered the bitwarden extension tag, and always made the effort of maximizing the window to see the address) . Should I open a bug for that?

Thanks!!!

2023-10-05 09:41 UTC, cagonzalezcs commented
@Camusensei Thank you for the feedback.

More context on the "why" for this change can be found with this comment: https://github.com/bitwarden/clients/issues/6412#issuecomment-1739853982

For your second concern, unfortunately we do not have control over how the tag is displayed to the end user. That said, the relevant information for verifying that this window is showing a Bitwarden extension page should be easily accessible. Unfortunately Firefox truncates the extension tag that precedes the URL, however if you click on it you should see the full context of the tag.

![Screenshot 2023-10-05 at 4 40 08 AM](https://github.com/bitwarden/clients/assets/16629865/7906ab3d-1450-4f74-a814-353d408be714)

As a result, this is working as intended and does not require a bug report. 

If you have any further questions or concerns please feel free to open a ticket with support or an issue on this repository.

2023-10-16 00:21 UTC, maximevhw commented
Hello, I could not find anything in the setting so i thought i'd ask.
Is there a way to disable the seperate window? I much preferred everything happening withing the extension viewport. 
Atl east having a setting would be wonderfull since everyone has different preferences. But for me this is kinda anoying,

2023-10-16 03:07 UTC, Camusensei commented
> Hello, I could not find anything in the setting so i thought i'd ask. Is there a way to disable the seperate window? I much preferred everything happening withing the extension viewport. Atl east having a setting would be wonderfull since everyone has different preferences. But for me this is kinda anoying,

Hello. I asked the same question and this was the answer:
> More context on the "why" for this change can be found with this comment: [#6412 (comment)](https://github.com/bitwarden/clients/issues/6412#issuecomment-1739853982)
The comment contains among other things this explanation:
> we are unfortunately limited in how we can programmatically open the extension popup window. If I could facilitate your described workflow, I would definitely have opted to open it in that manner instead of in a new window.

2023-10-17 20:44 UTC, clemensrieder commented
This is a super-annoying change. I unlock my extension using biometrics (MacBook Air + Chrome browser). The popup window disappears but can be restored with CMD + SHIFT + T. I regularly use this shortcut to reopen tabs. Still, I absolutely **never** want to reopen my extension in a separate window. Unfortunately, it will reopen the Bitwarden extension looking like this:

<img width="1616" alt="Bildschirmfoto 2023-10-17 um 22 37 43" src="https://github.com/bitwarden/clients/assets/68914047/03c00894-8b91-4636-b953-823267980a32">

2023-10-18 05:32 UTC, fiskfisk33 commented
Is there any way to revert to the old behaviour in settings somewhere I'm missing?

2023-10-29 17:42 UTC, Jamie4224 commented
Same question here, I have an issue with this in combination with pinned tabs where the newly opened window does not close after password verification. This is very bothersome as I need to close the window manually every time. It would be nice if it was configurable to use a new window or new tab.

Also see my response here with reproduction steps: This is also a problem when using an extension that permanently pins a tab in every window, since the window does not close after the autofill, see my reaction here: https://github.com/bitwarden/clients/issues/6707#issuecomment-1784177023