[PM-2014] Passkey registration
bitwarden/clients pull request #5396
Opened 2023-05-08 14:11 UTC by coroiu

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

WIP

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-05-11 21:10 UTC, kspearrin reviewed
I dont really see any issues, but someone else from the auth team should probably review this.

2023-05-15 20:39 UTC, jlf0dev reviewed
Overall looking good, thanks for creating the new auth module.

2023-05-15 20:39 UTC, jlf0dev commented on apps/web/src/app/auth/core/services/webauthn/webauthn.service.ts
> +        this.platformUtilsService.showToast(
Should we be handling errors in the service?

2023-05-15 20:39 UTC, jlf0dev commented on apps/web/src/app/auth/core/services/webauthn/webauthn.service.ts
> +  ): Promise<PublicKeyCredential | undefined> {
I'm curious about the choice of `undefined` for these. I would usually return `null` in this case because it indicates the intentional absence of something rather than "this thing doesn't exist". It gives the user an idea that if they changed the inputs, there could be something here.

I don't think it really matters either way, just figured I'd mention it.

2023-05-15 20:39 UTC, jlf0dev commented on apps/web/src/app/auth/settings/fido2-login-settings/create-credential-dialog/create-credential-dialog.component.ts
> +    this.dialogRef.disableClose = true;
I like the step system you've got here, but I think CodeScene has a good point that maybe we should break the logic up a little bit

2023-05-15 20:39 UTC, jlf0dev commented on apps/web/src/app/auth/settings/fido2-login-settings/fido2-login-settings.component.ts
> +  selector: "app-fido2-login-settings",
Should we use "Passkey" even for internal references like this? Just want to standardize either way

2023-05-16 06:46 UTC, coroiu commented on apps/web/src/app/auth/settings/fido2-login-settings/fido2-login-settings.component.ts
> +  selector: "app-fido2-login-settings",
Neither I or Kyle have used the term "passkey" anywhere else so I'm not sure if we wanna start now. Good point though, not sure who gets to decide 🤷

2023-05-16 06:54 UTC, coroiu commented on apps/web/src/app/auth/core/services/webauthn/webauthn.service.ts
> +        this.platformUtilsService.showToast(
Since I'm sharing this service across components it felt like the logical thing to do. It's sort of related to https://github.com/bitwarden/clients/pull/5377#discussion_r1187392545 

> We've been pushing for using more view models in our UI components and stop using request/responses, but nobody has really talked about the fact that api errors are technically also responses which currently bubble up all the way to the UI.

But maybe a PR isn't the best place to discuss changes to convention. What do you think? Should I move the error handling to the components for now?

2023-05-16 12:03 UTC, coroiu commented on apps/web/src/app/auth/settings/fido2-login-settings/create-credential-dialog/create-credential-dialog.component.ts
> +    this.dialogRef.disableClose = true;
Refactored the submit method and CodeScene seems to be happy with the new changes. Not sure if I think this is more readable, but maybe it's just down to personal preference :)

2023-05-16 14:29 UTC, coroiu commented on apps/web/src/app/auth/core/services/webauthn/request/webauthn-response.request.ts
> +export abstract class WebauthnResponseRequest {
Oh yeah, same here, I just gave up haha

2023-05-16 14:29 UTC, coroiu commented on apps/web/src/app/auth/core/services/webauthn/webauthn.service.ts
> +        this.platformUtilsService.showToast(
Moved all error handling to the component after our discussion in slack

2023-05-16 14:39 UTC, jlf0dev commented on apps/web/src/app/auth/settings/fido2-login-settings/create-credential-dialog/create-credential-dialog.component.ts
> +    this.dialogRef.disableClose = true;
Might just be more future-proof now. Thanks!

2023-05-29 19:02 UTC, jlf0dev approved these changes
This looks good to me, great work @coroiu!

2023-08-28 15:20 UTC, coroiu commented on apps/web/src/app/auth/settings/webauthn-login-settings/create-credential-dialog/create-credential-dialog.component.html
> +        </bit-form-field>
issue: this should use user-verification prompt

2023-08-28 19:45 UTC, jlf0dev requested changes
Couple minor things

2023-09-20 22:22 UTC, willmartian commented on libs/components/src/badge/badge.directive.ts
> +  @Input() align: TextAlignment = "textTop";
Why is this input necessary? Could you provide a screenshot/repro of the issue you were trying to resolve by adding this?

2023-09-21 09:42 UTC, coroiu commented on apps/web/src/app/auth/settings/fido2-login-settings/fido2-login-settings.component.ts
> +  selector: "app-fido2-login-settings",
Bringing this up here https://bitwarden.slack.com/archives/C04N1TX1CGM/p1695289328036529

2023-09-21 12:50 UTC, coroiu commented on apps/web/src/app/auth/settings/webauthn-login-settings/create-credential-dialog/create-credential-dialog.component.html
> +        </bit-form-field>
Tech debt that will be fixed as part of https://bitwarden.atlassian.net/browse/PM-3722

2023-09-21 13:30 UTC, Hinton requested changes
Some initial thoughts before diving into the service and components.

2023-09-21 13:30 UTC, Hinton commented on apps/web/src/app/app.module.ts
> +    AuthModule,
This should probably be in `OssModule`. Rebase on lastest master and you'll get a comment suggesting to not modify this.

2023-09-21 13:33 UTC, coroiu commented on apps/web/src/app/auth/core/services/webauthn/webauthn.service.ts
> +  ): Promise<CredentialCreateOptionsView | undefined> {
lol fair point 👍 I'll fix

2023-09-22 08:43 UTC, Hinton commented on apps/web/src/app/auth/core/services/webauthn/webauthn.service.ts
> +  readonly loading$ = this._loading$.asObservable();
It feels a bit odd that it's an observable since presumably you just want a single return value? And that multiple places can subscribe to it.

2023-09-22 08:51 UTC, coroiu commented on apps/web/src/app/auth/core/services/webauthn/webauthn.service.ts
> +  readonly loading$ = this._loading$.asObservable();
Not sure I follow, it's just like using a `BehaviorSubject` or `ReplaySubject` ?

2023-09-25 11:55 UTC, Hinton commented on apps/web/src/app/auth/core/services/webauthn/webauthn.service.ts
> +  readonly loading$ = this._loading$.asObservable();
Fair, let me try and expand on the comment.

My concerns are that:
- We're exposing a subject.
- It's trying to be "to clever" which makes it hard to understand.
- It's unintuitive that subscribing to `credentials$` has side effects.
	- IF it has no current active subscriptions it fires off an API request on subscribe
	- It clears it's value on unsubscribe

2023-09-25 12:35 UTC, coroiu commented on apps/web/src/app/auth/core/services/webauthn/webauthn.service.ts
> +  readonly loading$ = this._loading$.asObservable();
- We're exposing a subject.
We're not? 

- It's trying to be "to clever" which makes it hard to understand.
Hmmm, I mean, fair enough, but I mean, what's the limit for complexity here? It's not really that complicated?
I think services one can argue that `BehaviorSubject` that subscribe to other observables and then use `next` on their on inner subject are at least equally complicated? This here is just one single clear chain of piped operators.

- It's unintuitive that subscribing to credentials$ has side effects.
This is how observables based on e.g. the `HttpClient` work? And it doesn't really have side-effects in it's traditional sense, everything is idempotent?

I don't really think I understand what the feedback here is. It seems like the thread started with a question, which then resulted in a criticism of the design, but I'm still not really sure if I understand what change is being suggested?

Here are some questions and answer that hopefully answers helps

**What is this doing?**
Offering an observable that components can subscribe to, to get all existing passkeys.

**Why is it doing this?**
Because we want to build more reactive code.

**Why are we making this reactive?**
Because this way it doesn't matter what component is making a modification. If the dialog, which is self contained, edits something, then the list refreshes. If we remove an item, the list refreshes. 

**Why a reactive service? Why not create the observable in the component?**
Two reasons:

- It makes the components simpler so that they no longer have to keep track of which button/UI action triggers a refresh of data.

- It decouples components. Parent components no longer have to await child components such as dialogs, check the result, and then know what to do with it.

2023-09-26 09:48 UTC, coroiu commented on libs/components/src/badge/badge.directive.ts
> +  @Input() align: TextAlignment = "textTop";
**Without**
![image](https://github.com/bitwarden/clients/assets/2285588/21d69495-8bfa-41a4-9655-21c9a328db8a)

**With**
![image](https://github.com/bitwarden/clients/assets/2285588/040e5f00-f2c9-4b2b-8ab0-8853a242164d)

2023-09-26 11:11 UTC, coroiu commented on libs/components/src/badge/badge.directive.ts
> +  @Input() align: TextAlignment = "textTop";
I tried fixing this with a simple `<span class="tw-align-middle"` but the directive overrides the class

2023-09-27 09:05 UTC, coroiu commented on apps/web/src/app/auth/auth.module.ts
> +    WebauthnLoginSettingsModule, // TODO: Remove when `app/settings/change-password.component.ts` has been moved to `app/auth/settings/.`
Sort of fixed, it's better now, but I tweaked the todo-comment in `loose-components` which still needs a refactor.

2023-09-27 09:05 UTC, coroiu commented on apps/web/src/app/auth/core/services/webauthn/request/webauthn-attestation-response.request.ts
> +export class WebauthnAttestationResponseRequest extends WebauthnResponseRequest {
Thank you for pointing this out, should be much better now! Please reach out if you can think of any way to make it even clearer!

2023-09-27 09:06 UTC, coroiu commented on apps/web/src/app/app.module.ts
> +    AuthModule,
Fixed!

2023-09-27 09:06 UTC, coroiu commented on apps/web/src/app/auth/core/services/webauthn/webauthn-api.service.ts
> +@Injectable({ providedIn: CoreAuthModule })
Fixed

2023-09-27 09:06 UTC, coroiu commented on apps/web/src/app/core/core.module.ts
> +  imports: [CommonModule, JslibServicesModule, CoreAuthModule],
Fixed

This is most likely gonna be moved again in a future PR

2023-09-27 09:08 UTC, coroiu commented on apps/web/src/app/auth/core/services/webauthn/webauthn.service.ts
> +  ): Promise<CredentialCreateOptionsView | undefined> {
Fixed, it was a remnant from before a refactor when this function contained error handling

2023-09-27 09:20 UTC, coroiu commented on apps/web/src/app/auth/core/services/webauthn/webauthn.service.ts
> +  readonly loading$ = this._loading$.asObservable();
Fixed. I also added some clarifying comments surrounding how the observable behaves

2023-09-28 08:08 UTC, coroiu commented on libs/components/src/badge/badge.directive.ts
> +  @Input() align: TextAlignment = "textTop";
@willmartian Two questions for you:

Do you think that we should change the syntax from
```
<span align="textTop"
```
to
```
<span align="text-top"
```

And do you think we should change the attribute name to something other than `align`, since that is actually an standard HTML attribute?

2023-09-29 03:44 UTC, willmartian commented on libs/components/src/badge/badge.directive.ts
> +  @Input() align: TextAlignment = "textTop";
I want to avoid creating inputs that simply override CSS styles. It feels unmaintainable/unflexible (and could spiral out of control until we recreate all of CSS in Angular lol). 

1. I'm not sure we need to have text alignment set on the `bitBadge` implementation to begin with. It was introduced [here. ](https://github.com/bitwarden/clients/pull/5236#discussion_r1220359306) It seems to me that middle alignment should be the default if anything, but I would need to assess and verify this.
2. Couldn't you accomplish your goal by marking the class as important? `!tw-align-middle`. 
3. Better yet, it is more semantically correct to not have the badge in the heading element at all. Putting `tw-align` on the heading element should also work. See this [repro.](https://62a88a6de5b807fa98886113-bjubgjeorh.chromatic.com/?path=/story/component-library-badge--alignment)

Lmk what you think!

2023-09-29 09:41 UTC, coroiu commented on libs/components/src/badge/badge.directive.ts
> +  @Input() align: TextAlignment = "textTop";
Fair enough! Thanks for the help, I'll fix this with (2)!

I'm not sure about the semantics, it is technically a part of the heading, but yeah. Either way, changing the heading to `inline` breaks the built in margins, so I'll just go with `!tw-align-middle`

2023-10-03 13:45 UTC, willmartian approved these changes
CL & Platform changes look good! ✅

2023-10-03 13:48 UTC, jlf0dev approved these changes
Always enjoy reading your code @coroiu, thanks for the new Auth modules 🚀

2023-10-06 09:50 UTC, Hinton approved these changes
This review uses [Conventional Comments](https://conventionalcomments.org/). Feel free to resolve them in a follow up PR, but if so, please ensure the issues gets resolved promptly.

2023-10-06 09:50 UTC, Hinton commented on apps/web/src/app/auth/settings/webauthn-login-settings/delete-credential-dialog/delete-credential-dialog.component.html
**suggestion (non-blocking):** This could use the `loading` attribute of dialog, https://components.bitwarden.com/?path=/story/component-library-dialogs-dialog--loading. Might be a good follow up PR.

2023-10-06 09:50 UTC, Hinton commented on apps/web/src/app/auth/settings/webauthn-login-settings/webauthn-login-settings.component.html
> +    <td class="tw-p-2 tw-pl-0 tw-font-semibold">{{ credential.name }}</td>
**thought:** I wonder if we should improve the typography docs, this feels like a header?

2023-10-06 09:50 UTC, Hinton commented on apps/web/src/app/auth/settings/webauthn-login-settings/webauthn-login-settings.component.ts
> +  protected readonly MaxCredentialCount = 5;
**thought:** Should this be extracted to a constant somewhere? It doesn't feel like a presentation concern.

2023-10-06 09:50 UTC, Hinton commented on apps/web/src/app/auth/settings/webauthn-login-settings/webauthn-login-settings.component.html
> +    <td class="tw-py-2 tw-pl-10 tw-pr-0">
**question:** Why are we padding this left? Is the intention to right align the button?

2023-10-06 09:50 UTC, Hinton commented on apps/web/src/app/auth/settings/change-password.component.html
> +  class="tw-mb-14"
**question:** Why `mb-14` how did we get that number.

**thought:** We're kind of random with the margins for sections. Would it make sense to envision components to handle spacing for sections?

2023-10-06 09:50 UTC, Hinton commented on apps/web/src/app/auth/settings/settings.module.ts
> +export class SettingsModule {}
**suggestion:** Would it make sense to call this module `AuthSettings` since `Settings` without context is non descriptive.

2023-10-06 09:54 UTC, coroiu commented on apps/web/src/app/auth/settings/webauthn-login-settings/webauthn-login-settings.component.html
> +    }}</span>
Did you see the conversation with Will above? https://github.com/bitwarden/clients/pull/5396#discussion_r1332229450

2023-10-06 10:15 UTC, Hinton commented on apps/web/src/app/auth/settings/webauthn-login-settings/webauthn-login-settings.component.html
> +    }}</span>
No, feels like a good topic for the CL to discuss though. I'm split and can see benefits to both approaches.

2023-10-09 13:26 UTC, coroiu commented on apps/web/src/app/auth/auth.module.ts
> +    WebauthnLoginSettingsModule, // TODO: Remove when `app/settings/change-password.component.ts` has been moved to `app/auth/settings/.`
I went ahead and removed `AuthModule` from `LooseComponentsModule` completely since it wasn't needed any more

2023-10-09 13:36 UTC, coroiu commented on apps/web/src/app/auth/settings/webauthn-login-settings/delete-credential-dialog/delete-credential-dialog.component.html
Fixed as part of:
https://github.com/bitwarden/clients/pull/6532

2023-10-09 13:38 UTC, coroiu commented on apps/web/src/app/auth/settings/webauthn-login-settings/webauthn-login-settings.component.html
> +      <span bitTypography="body1" class="tw-text-muted">
Can we agree on marking this as `won't fix` seeing as this changes substantially in (and is also fixed by) https://github.com/bitwarden/clients/pull/6525 ?

2023-10-09 13:55 UTC, coroiu commented on apps/web/src/app/auth/settings/webauthn-login-settings/webauthn-login-settings.component.html
> +    <td class="tw-p-2 tw-pl-0 tw-font-semibold">{{ credential.name }}</td>
No idea, in my mind it feels more like a https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl

2023-10-09 14:00 UTC, coroiu commented on apps/web/src/app/auth/settings/webauthn-login-settings/webauthn-login-settings.component.ts
> +  protected readonly MaxCredentialCount = 5;
I agree, just not sure where else it would go. Moved it to the admin service as part of: https://github.com/bitwarden/clients/pull/6532

2023-10-09 14:10 UTC, coroiu commented on apps/web/src/app/auth/settings/change-password.component.html
> +  class="tw-mb-14"
Went for making it look as close as possible to the figma design. `mb-14` seemed like it captured the design at the time.

I think that sounds like a good idea, and I think we should start by defining standard spacings as part of our design system

2023-10-09 14:12 UTC, coroiu commented on apps/web/src/app/auth/settings/settings.module.ts
> +export class SettingsModule {}
Fair, fixed as part of: https://github.com/bitwarden/clients/pull/6532

2023-10-09 14:16 UTC, coroiu commented on apps/web/src/app/auth/core/services/webauthn-login/webauthn-login-api.service.ts
> +    const request = await this.userVerificationService.buildRequest(verification);
True, fixed as part of: https://github.com/bitwarden/clients/pull/6532

2023-10-09 15:19 UTC, JaredSnider-Bitwarden approved these changes
Looks great to me. Reviewed on call with Andreas 🚀 !

2023-10-10 13:04 UTC, Hinton approved these changes

2023-10-10 13:10 UTC, merged