[PM-2054] Updated Password Generator History to use Component Library on Web
bitwarden/clients pull request #5414
Opened 2023-05-09 15:28 UTC by aj-rosado

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Update the Password generator history to use Component Library on Web client

## Code changes

Update to use Component Library 

## Screenshots

**Before:**
<img width="1479" alt="password-history-old-empty" src="https://github.com/bitwarden/clients/assets/109146700/b5c241ff-7d2d-4e16-acea-0e4d35ac6b52">
<img width="1479" alt="password-history-old-copied" src="https://github.com/bitwarden/clients/assets/109146700/3bbb9c95-7326-4d7a-b710-02c1229d496d">
<img width="1479" alt="password-history-old-layout" src="https://github.com/bitwarden/clients/assets/109146700/a22c14bd-4161-4ef7-909a-4c1d1ae7df02">

**After:**
<img width="1479" alt="password-history-new-copied" src="https://github.com/bitwarden/clients/assets/109146700/e2848327-8301-442f-aaee-d697d54454b4">
<img width="1479" alt="password-history-new-layout" src="https://github.com/bitwarden/clients/assets/109146700/a29ed1d1-95bd-4a3e-9b35-e85832def652">
<img width="1479" alt="password-history-new-empty" src="https://github.com/bitwarden/clients/assets/109146700/71739105-88a0-4353-8fdb-2d2f409725ba">

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-05-09 16:47 UTC, djsmith85 requested changes
@aj-rosado: Thanks for tackling this.

Just some minor clean-up.

There's still a Lint issue, execute `npm ci`, followed by `npm run prettier`. This should resolve the issue on `apps/web/src/app/tools/password-generator-history.component.html`

2023-05-09 16:47 UTC, djsmith85 commented on apps/web/src/app/tools/generator.component.ts
>      private modalService: ModalService
As the modalService is replaced by the DialogService, we can remove it from the ctor and the import

2023-05-10 10:59 UTC, djsmith85 submitted a review, later dismissed
Changes are looking good

2023-05-10 12:01 UTC, Hinton reviewed
Looks good, some minor feedback, nothing blocking but I think we can clean it up slightly further. Would appreciate @djsmith85 thoughts on the table use as well.

2023-05-10 18:15 UTC, aj-rosado commented on apps/web/src/app/tools/password-generator-history.component.html
> +    </ul>
Changed and updated screenshots

2023-05-11 08:19 UTC, Hinton approved these changes
Looks great thanks!

2023-05-15 09:49 UTC, djsmith85 approved these changes

2023-05-15 11:01 UTC, merged