radd new storage to replace MasterKey with UserSymKey
bitwarden/clients pull request #5498
Opened 2023-05-23 15:58 UTC by jlf0dev

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-05-23 18:41 UTC, JaredSnider-Bitwarden commented on libs/common/src/abstractions/state.service.ts
> +  getUserSymKeyAuto: (options?: StorageOptions) => Promise<string>;
If we are renaming this, can we think of a better name than auto? Why is it suffixed with auto today?

2023-05-23 18:42 UTC, JaredSnider-Bitwarden commented on libs/common/src/abstractions/state.service.ts
> +  getMasterKey: (options?: StorageOptions) => Promise<MasterKey>;
Do we need a `getMasterKeyAuto()`? Also, can we think of a better name than auto? Why is it suffixed with auto today?

2023-06-20 15:27 UTC, jlf0dev commented on libs/common/src/auth/services/auth.service.ts
> +    // We need to change this to using a different method (possibly server auth code + user sym key)
TODO is pretty self explanatory, but wanted to mention that we have future work to handle the cases where the user won't have a Master Key.

2023-06-20 15:27 UTC, jlf0dev commented on libs/common/src/platform/models/domain/account.ts
> -  cryptoMasterKeyB64?: string;
Still not sure where this was used, but wanted to call it out just in case.

2023-06-20 15:33 UTC, jlf0dev commented on libs/common/src/platform/services/crypto.service.ts
> +    return new SymmetricCryptoKey(decUserKey) as UserSymKey;
For decryption methods, I've opted to return the key instead of setting it.

2023-06-20 21:14 UTC, MGibson1 commented on apps/browser/src/platform/services/browser-state.service.ts
> +      accountCache.subscribe(this.accountDiskCacheSubject);
This will cause dead object issues in FF as the reference to acountDiskCacheSubject is torn out from under the account cache object.

2023-06-22 21:10 UTC, MGibson1 requested changes
This does read a lot cleaner, and starts to establish some better hygiene around key use. The PR bounces back and forth between `UserKey` and `UserSymKey`. We should pick one.

I like `UserKey` because it's symmetric with `OrganizationKey`. However, I don't think it matters which is standardized. Up to you.

The attachment issue noted in cipher.service and crypto.service, I think is a bug that'll need to be addressed.

2023-06-22 21:10 UTC, MGibson1 commented on libs/common/src/platform/services/crypto.service.ts
> +    const privateEnc = await this.encrypt(keyPair[1], key);
Please call encrypt from encrypt service. This helper is deprecated and, in fact, just calls `getUserKeyFromMemory` as you do above

2023-06-22 21:10 UTC, MGibson1 commented on libs/common/src/platform/services/crypto.service.ts
> +    await this.stateService.setUserSymKeyPin(await this.encrypt(key.key, pinKey));
Please call encrypt from encrypt service. This helper is deprecated

2023-06-22 21:10 UTC, MGibson1 commented on libs/common/src/platform/services/crypto.service.ts
> +      protectedSymKey = await this.encrypt(newSymKey, encryptionKey);
Please call encrypt from encrypt service. This helper is deprecated.

2023-06-22 21:10 UTC, MGibson1 commented on libs/common/src/platform/services/crypto.service.ts
> +      protectedSymKey = await this.encrypt(newSymKey, stretchedEncryptionKey);
Please call encrypt from encrypt service. This helper is deprecated.

2023-06-23 15:08 UTC, jlf0dev commented on apps/browser/src/platform/services/browser-crypto.service.ts
> +    userId?: string
I went ahead and removed it. I agree that its outside of the scope of the service to decide, but better safe than sorry.

2023-06-23 15:14 UTC, jlf0dev commented on apps/cli/src/auth/commands/unlock.command.ts
> +      await this.cryptoService.setMasterKey(masterKey);
I've been still setting the master key for now because I haven't had a chance to remove the dependency from _everything_ yet. Namely login with device. I figured this gets us close enough to where new auth/decryption methods don't need to save a master key equivalent. And we can eventually remove the rest without too much effort.

2023-06-23 15:17 UTC, jlf0dev commented on apps/web/src/app/admin-console/organizations/members/components/reset-password.component.ts
> +          const existingUserSymKey = new SymmetricCryptoKey(decValue) as UserSymKey;
Fixed!

2023-06-23 20:23 UTC, jlf0dev commented on libs/common/src/platform/models/domain/account.ts
> +  // deprecated keys
👍

2023-06-26 14:22 UTC, jlf0dev commented on apps/web/src/app/auth/settings/emergency-access/emergency-access.component.ts
> +    const userKey = await this.cryptoService.getUserKeyFromMemory();
Fixed [here](https://github.com/bitwarden/clients/pull/5498/commits/167f404f917c2df3299d38ce5a816c71484f3197). I've been following this pattern everywhere else, but I keep thinking about combining the `getUserKeyFromMemory` and `getUserKeyFromStorage` again. The problem is that once I do that it makes sense to set the user key in memory again from the getter like before. Something I would really like to avoid.

2023-06-26 15:36 UTC, jlf0dev commented on libs/common/src/auth/login-strategies/password-login.strategy.ts
> +    await this.cryptoService.setUserSymKeyMasterKey(response.key);
Do you prefer `setUserSymKeyMaster`? The last `Key` here is a part of `MasterKey`. You're right, that might be confusing, I'm not sure how to make it more clear without also seeing the pattern with the other keys.

2023-06-26 17:43 UTC, jlf0dev commented on libs/common/src/services/vaultTimeout/vaultTimeoutSettings.service.ts
> +      aUserSymKeyPinIsSet || anOldUserSymKeyPinIsSet,
I keep questioning myself here but I swear this code has to have been mutually exclusive:
```typescript
  async isPinLockSet(): Promise<[boolean, boolean]> {
    const protectedPin = await this.stateService.getProtectedPin();
    const pinProtectedKey = await this.stateService.getEncryptedPinProtected();
    return [protectedPin != null, pinProtectedKey != null];
  }
```
I was trying to match the previous behavior as closely as possible, but you're right. Changed to a type [here](https://github.com/bitwarden/clients/pull/5498/commits/71ebb17a566a2f0023e4950c9e69d1fc3c4d559c).

2023-06-26 17:48 UTC, jlf0dev commented on libs/common/src/platform/services/crypto.service.ts
> +    }
I do have a method called `makeUserKey` in the crypto service that does the exact same for users, but uses the Master Key. Are you saying we need one that can take in the User Key that does the same? I can't find anywhere in the code we need that though.

2023-06-26 19:22 UTC, jlf0dev commented on libs/common/src/platform/services/crypto.service.ts
> +  async getPrivateKey(): Promise<ArrayBuffer> {
The other getKey methods didn't have an encrypted counterpart. Do we need to keep this same pattern of clearing decrypted data when updating encrypted data?

2023-06-26 19:28 UTC, jlf0dev commented on libs/common/src/platform/services/crypto.service.ts
> +      }
done. There's still quite a lot of references to biometric in the base class but we can probably keep moving those later

2023-06-26 19:32 UTC, jlf0dev commented on libs/common/src/platform/services/crypto.service.ts
> +        break;
We don't have any state for this. Eventually the `protectedPin` will be an indicator if we have a pin saved or not, but until then we have to do some logic to figure it out. If that's what you're referring to.

2023-06-26 19:49 UTC, jlf0dev commented on apps/browser/src/safari/safari/SafariWebExtensionHandler.swift
> +                    let passwordName = userId + "_user_biometric"
I've added another fallback key to look for in safari. AFAIK the migration should happen on unlock when the user key is set and the bio key is refreshed.

2023-06-27 03:11 UTC, jlf0dev commented on libs/common/src/vault/services/cipher.service.ts
> +    const dataEncKey = await this.cryptoService.makeOrgDataEncKey(orgKey);
[This commit](https://github.com/bitwarden/clients/pull/5498/commits/f1761c6afc5ee640eb9037b4bf1d2c21ecef20b2) should fix this. Starting to realize how verbose this API is, and I didn't even really taken into account the fact that the key could be missing from memory

2023-06-27 03:11 UTC, jlf0dev commented on libs/common/src/platform/services/crypto.service.ts
> +    }
https://github.com/bitwarden/clients/pull/5498/commits/f1761c6afc5ee640eb9037b4bf1d2c21ecef20b2

2023-06-27 13:09 UTC, jlf0dev commented on libs/common/src/platform/services/crypto.service.ts
> +  async makeShareKey(): Promise<[EncString, SymmetricCryptoKey]> {
Renamed to `makeOrgKey` and make it generic to return either an `OrgKey` or `ProviderKey`

2023-06-27 13:17 UTC, jlf0dev commented on apps/desktop/src/platform/services/electron-crypto.service.ts
> +  protected override async retrieveUserKeyFromStorage(
👍

2023-06-27 13:55 UTC, jlf0dev commented on apps/desktop/src/platform/services/electron-crypto.service.ts
> +      await this.migrateBiometricKeyIfNeeded(userId);
We should always have a `retrieve` (now `get`) before we store. I was hoping to avoid having too much migration code littered throughout the login process, but I think you're right, better safe than sorry. I've added code to clear out the old keys in the set as well.

2023-06-27 14:04 UTC, jlf0dev commented on apps/web/src/app/auth/settings/emergency-access/emergency-access-takeover.component.ts
Good point, probably going to be done in the next iteration.

2023-07-05 20:07 UTC, MGibson1 reviewed
I don't think I see anything alarming anymore. Is the cache working well?

2023-07-05 20:24 UTC, jlf0dev commented on apps/browser/src/platform/services/browser-state.service.ts
> +  // to delete the cache in the constructor above.
Exactly, unfortunately we can't determine which context send the message.

2023-07-05 20:36 UTC, jlf0dev commented on apps/browser/src/platform/services/browser-state.service.ts
> +              this.deleteDiskCache(key);
I'm mostly worried about timing here. I don't actually know if we're guaranteed to have this listener fire before code running in another context, and setting the disk cache may create invalid state. Deleting the disk cache on the other hand is much safer.

2023-07-05 20:51 UTC, jlf0dev commented on libs/common/src/services/vaultTimeout/vaultTimeoutSettings.service.ts
> +export type PinLockType = "DISABLED" | "ENABLED" | "ENABLED_WITH_MP_ON_RESET";
Updated

2023-07-05 21:11 UTC, jlf0dev commented
> I don't think I see anything alarming anymore. Is the cache working well?

Tested the cache on Firefox and Chrome and seems to work well. There are quite a lot of calls to the cache now, but I couldn't find any issues.

2023-07-06 18:21 UTC, differsthecat approved these changes
The changes for Vault look good, I appreciate the stronger typing you added for a lot of our test files!

2023-07-06 20:52 UTC, JaredSnider-Bitwarden commented on libs/common/src/platform/services/crypto.service.ts
> +  async setUserKeyMasterKey(userKeyMasterKey: string, userId?: string): Promise<void> {
Question re the naming of this method:
- To me, `UserKeyMasterKey` implies the opposite of the JSDoc comment: "The master key encrypted user key to set" as we've been using `MasterKey(UserKey)` in all our documentation to mean "Master key encrypted User Key". 
- Should we potentially just write out the whole thing for clarity: `setMasterKeyEncryptedUserKey()`?

2023-07-07 13:54 UTC, jlf0dev commented on libs/common/src/platform/services/crypto.service.ts
> +  async setUserKeyMasterKey(userKeyMasterKey: string, userId?: string): Promise<void> {
Fair point. Renamed to be more clear.

2023-07-12 21:43 UTC, shane-melton approved these changes
The Admin Console changes look good to me! Really appreciate the explicit names and types for the various keys, makes following along the much easier!

2023-07-17 13:38 UTC, jlf0dev commented on apps/browser/src/platform/services/browser-state.service.ts
> +    // instance of our state service that is shared so we can remove this.
Changed wording here to suggest we need to finalize a way of handling caching with multiple state services

2023-07-18 13:22 UTC, differsthecat reviewed
The changes for Vault are fine, though the method name `setMasterKeyEncryptedUserKey` feels a little clunky.

Another question on this though, was the DuckDuckGo native test runner tested with these changes and confirm that it works? I see there were updates to the native messaging service and handler. Will QA run through it? I can assist with that if need be.

2023-07-18 13:29 UTC, jlf0dev commented
Thanks @differsthecat, I'll confirm with QA that we'll run through the Duck Duck Go flows and verify they work.

2023-07-18 13:30 UTC, differsthecat approved these changes
Thanks @jlf0dev , this looks good from Vault!

2023-07-18 14:21 UTC, djsmith85 submitted a review, later dismissed
@jlf0dev Awesome work on this 🚀 ! Approving for team-tools-dev

2023-07-18 17:29 UTC, cyprain-okeke commented on apps/web/src/app/billing/settings/organization-plans.component.ts
> +          const orgKey = await this.cryptoService.makeOrgKey<OrgKey>();
Can we have more description around the purpose of makeOrgkey, it seems to do two different things, Make the key and encrypt it.

2023-07-19 00:51 UTC, djsmith85 submitted a review, later dismissed

2023-07-20 17:49 UTC, jlf0dev commented on apps/web/src/app/billing/settings/organization-plans.component.ts
> +          const orgKey = await this.cryptoService.makeOrgKey<OrgKey>();
This is the key that sits encrypted by the user's public key on the `OrganizationUser` or `ProviderUser` tables. It's the Organization Key that encrypts organization data.

Creating and encrypting keys is a pretty common operation on the crypto service you can see in the other make__Key methods. It's useful because when we create them we usually are about to send them to the server anyway.

I went ahead and updated the JSDOC in [59c222b](https://github.com/bitwarden/clients/pull/5498/commits/59c222b48595c3f8efed489e349c895ee4029448) to hopefully make that a little clearer, but let me know if that's still confusing.

2023-07-20 18:49 UTC, trmartin4 commented on apps/web/src/app/billing/settings/organization-plans.component.ts
> +          const orgKey = await this.cryptoService.makeOrgKey<OrgKey>();
So this is making the org key for a new org, got it.  

Can you clarify what is meant by using `shareKey` to describe this key in the implementation of `makeOrgKey`?  I think that's what confused us a bit when looking at this.

⛏️ Perhaps just changing that to `orgKey` here might help: https://github.com/bitwarden/clients/blob/3de0125564704ba6cd772d211e57fbe4d94b6633/libs/common/src/platform/services/crypto.service.ts#L435

2023-08-07 17:44 UTC, jlf0dev commented
Closing as we will merge this migration branch into our feature branch instead of `master`

2023-08-07 17:44 UTC, closed without merging