[PM-2367] BEEEP: Extract password strength from password-generation-service
bitwarden/clients pull request #5502
Opened 2023-05-23 20:45 UTC by djsmith85

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

The passwordGenerationService drags in fairly large dependencies (ie. EFF-wordlist and zxcvbn). The passwordGenerationService is needed for commonly used components like login or lock, but only require parts of that service. Password strength for example can be enforced by policy on login, but will only be needed if the user is part of an org and that policy is enabled.

In other cases (`WeakPasswordReport`) we are only interested in the password strength score and thus we only need to load the passwordStrengthCheckService instead of the full old passwordGenerationService.

Possibly this can be taken a step further in a future PR with introducing a lazily loaded module, to further defer loading of `EFFWordlist` and `zxcvbn`.

## Code changes

- **Extract passwordStrength from passwordGenerationService -** dfd9500979c3648684a7f36ca8bd7fc399f362b3
  - Extract passwordStrength from password-generation.service.ts
  - Create new password-strength.service.ts
  - Create new password-strength.service.abstraction.ts
  - Register new password-strength service (libs/angular/src/services/jslib-services.module.ts)
  - Fix usages in libs
- **Fix usage in web -** b6c6665c4e6c3e93a3f781eb28f51944d371977a
- **Fix usage in desktop-** e3c4174c22fc750d0a8b80c8f61e9bbfff7d167b
- **Fix usage in CLI-** 6e86421c1a88041bc80ad16bd95895326405f85e
- **Fix usage in browser-** bc4896192b8c75f892e18439a7001062578ce636
  - Move password-generation-factory to tools

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-06-08 04:58 UTC, eliykat requested changes
Nice refactor! I've reviewed the whole thing as I know Tools is still a small team.

2023-06-08 04:58 UTC, eliykat commented on libs/angular/src/services/jslib-services.module.ts
You also need to update the `deps` array for `AuthService` in this file.

2023-06-09 11:42 UTC, djsmith85 commented on libs/angular/src/services/jslib-services.module.ts
@eliykat Thanks a lot for the review. I have merged master (platform move) and fixed the dep for AuthService

2023-06-11 22:06 UTC, eliykat approved these changes

2023-06-13 21:22 UTC, merged