[SM-650] Updating search and select all to work together properly
bitwarden/clients pull request #5510
Opened 2023-05-24 20:44 UTC by cd-bitwarden

## Type of change

```
- [ x ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

This functionality should work the same way it works in the Password Manager vault - if a user selects All when the page is filtered, All items from the searched view should selected, not all items.

## Code changes

projects-list.component.ts, secrets-list.component.ts, service-account-list.component.ts - all updated to toggle depending on the filtered list of items, and isAllSelected is updated to look at the correct list of items.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-05-30 20:21 UTC, Thomas-Avery requested changes
This currently doesn't clear selections made prior to entering a value in the search field. 

This can lead to cases where a bulk delete effects previously selected values that aren't presented to the user, and select all not working as expected.

<del>We shouldn't need to make any changes to `libs/components/src/table/table-data-source.ts`. 

<del>Look at how we have a working implementation of this at `apps/web/src/app/vault/components/vault-items/vault-<del>items.component.ts` and copy the pattern used there. 

<del>Note the use of `editableItems` to keep a list of items the search string is presenting to the user.

After further review, looks like we will have to have filteredData exposed.

2023-06-26 20:26 UTC, Hinton commented on libs/components/src/table/table-data-source.ts
> +    this.filteredData = data;
We diverge slightly from the CDK, I think we can use the same implementation. https://github.com/angular/components/blob/main/src/material/table/table-data-source.ts#L92-L96

2023-06-26 20:27 UTC, Thomas-Avery commented on libs/components/src/table/table-data-source.ts
> +    this.filteredData = data;
Looking at the CDK source code this is based on, they have something like the following for `set data` and `set filter`

```
  set data(data: T[]) {
    this._data.next(data ? [...data] : []);

    if (!this._renderChangesSubscription) {
      this.filterData(data, null);
    }
  }
```

```
 set filter(filter: string) {
    this._filter.next(filter);

    if (!this._renderChangesSubscription) {
      this.filterData(this.data, filter);
    }
  }
```

With comments explaining, `filteredData` won't be populated if there isn't any re-render subscription.

@Hinton Do you see any concerns with having something like this on the setters? This is outside my area of expertise.

2023-06-27 17:27 UTC, Hinton commented on libs/components/src/table/table-data-source.ts
> +    this.filteredData = data;
No, should be fine. That's how the CDK does it. We just need to make certain to apply it to both, and to check the subscription.

2023-06-28 20:20 UTC, Thomas-Avery reviewed
This feedback will be applicable to all the list component changes, but just wrote it for one.

2023-06-28 20:20 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/projects-list.component.ts
> +      return numSelected === numRows;
If `filteredData` contains the filtered set of data that has been matched by the filter string, or all the data if there is no filter.

Shouldn't we be able to use just `filteredData` length here? 

```
      const numSelected = this.selection.selected.length;
      const numRows = this.dataSource.filteredData.length;
      return numSelected === numRows;
```

2023-06-28 20:20 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/projects-list.component.ts
> +      }
Same thing here, if `filteredData` has all data without the filter shouldn't we be able to just use that? 

```
  toggleAll() {
    if (this.isAllSelected()) {
      this.selection.clear();
    } else {
      this.selection.select(...this.dataSource.filteredData.map((s) => s.id));
    }
  }
```

2023-06-29 16:21 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/projects-list.component.ts
> +      return numSelected === numRows;
makes sense to me! 
![image](https://github.com/bitwarden/clients/assets/106776772/ead9a0fc-c415-4e34-9be3-68434aeb640c)

2023-06-29 20:28 UTC, Thomas-Avery approved these changes
Looks good, thank you!

2023-06-29 22:22 UTC, Hinton commented on libs/components/src/table/table-data-source.ts
> +      this.filterData(data, "");
I expect we want to use the active filter here.

2023-06-29 22:23 UTC, Hinton commented on libs/components/src/table/table-data-source.ts
> +    if (!this._renderChangesSubscription) {
Same comment as above?

2023-06-30 01:32 UTC, cd-bitwarden commented on libs/components/src/table/table-data-source.ts
> +      this.filterData(data, "");
Hey Oscar, thanks for the review! Can you explain more what you mean?

2023-06-30 12:24 UTC, Hinton commented on libs/components/src/table/table-data-source.ts
> +      this.filterData(data, "");
We might have filters set that should still apply when changing the data.

2023-06-30 14:34 UTC, Hinton commented on libs/components/src/table/table-data-source.ts
>    private filterData(data: T[], filter: string): T[] {
`filter` is currently unused. We should either use it, or remove the variable.

2023-06-30 18:24 UTC, cd-bitwarden commented on libs/components/src/table/table-data-source.ts
>    private filterData(data: T[], filter: string): T[] {
Thank you for noticing that! I've removed it :)

2023-06-30 19:52 UTC, Thomas-Avery requested changes

2023-06-30 19:52 UTC, Thomas-Avery commented on libs/components/src/table/table-data-source.ts
> +      map(([data, filter]) => this.filterData(data))
```suggestion
      map(([data]) => this.filterData(data))
```

We won't need filter here if we are removing it from the method's parameters.

2023-06-30 20:03 UTC, Thomas-Avery approved these changes
LGTM

2023-07-01 12:02 UTC, Hinton approved these changes

2023-07-08 13:59 UTC, merged