[AC-1423] Update organization subscription cloud page
bitwarden/clients pull request #5614
Opened 2023-06-14 17:31 UTC by shane-melton

## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Update the Organization Subscription Cloud page in preparation for Secrets Manager billing. This PR depends on incoming server changes from https://github.com/bitwarden/server/pull/2942 to function properly. However, it will gracefully fallback if the new properties in `subscription.response.ts` are missing/empty.

## Code changes

### - organization-subscription-cloud.component.html and secrets-manager/enroll.component.html

- Remove bootstrap classes and replace with Tailwind and CL components/directives
- Restructure leading subscription details to be horizontal and line items to expand to full page width 
- Adjust `<h1-4>` headings to better match the semantic structure of the page for multi-product support
- Prefix line items with their respective product name and indent addon line items to indicate it belongs to the parent subscription item.
- Add support for rendering line items for PM and SM for free organizations.

### - organization-subscription-cloud.component.ts
- Add separate `lineItems` property to that can be sorted by product type
- Add helper to sort billing subscription items by product type and "addon" status
- Add helper to render a product types name

### - models/data/organization.data.ts
- Add `usePasswordManager` field that was added in https://github.com/bitwarden/server/pull/2980

### - billing/enums/bitwarden-product-type.enum.ts
- Introduce `BitwardenProductType` enum to clients.
  - Incoming server change from: https://github.com/bitwarden/server/pull/2942

### - billing/models/response/subscription.response.ts
- Add new fields for `bitwardenProduct` and `addonSubscriptionItem` to allow the rendering of product headings and the indentation of addon items.

### - libs/components/src/progress/progress.component.ts
- Introduce a new `minWidth` input to the progress bar CL component to support a minimum width that is always rendered, regardless of what the value of the progress bar is. Helpful for showing a the percentage label for low percentages (e.g. when used to show the amount of storage an organization is using, instead of an empty bar)
- Add a new storybook story to show an example of using `minWidth`

## Screenshots

### Subscribed to both PM and SM

![image](https://github.com/bitwarden/clients/assets/8764515/b0db1ef7-7f63-4386-83a9-04b895afcfda)

### Free Organization
![image](https://github.com/bitwarden/clients/assets/8764515/ed3d215b-9f2f-47f1-99b5-67563dcac97b)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-06-20 06:27 UTC, eliykat requested changes
Quick review only, looks pretty good though. I'll go over the templating again in more detail.

2023-06-20 06:27 UTC, eliykat commented on apps/web/src/app/billing/organizations/secrets-manager/enroll.component.html
This component is being deleted in #5617. I suggest reverting these changes to avoid confusion/merge conflicts. (although I love the enthusiasm for replacing Bootstrap 😁 )

2023-06-20 06:27 UTC, eliykat commented on apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts
> +      : -1;
This is quite difficult to read, can you please break it out into regular `if` statements?

2023-06-20 06:27 UTC, eliykat commented on libs/components/src/progress/progress.component.ts
> +
Maybe the text should just appear even if the bar is empty? It seems strange that it's at 0% but the bar is part filled. I've requested a review from @bitwarden/dept-design to check.

2023-06-20 06:27 UTC, eliykat commented on libs/common/src/billing/models/response/subscription.response.ts
> +    this.addonSubscriptionItem = this.getResponseProperty("AddonSubscriptionItem");
I can't see this server-side, where is this being added?

2023-06-21 01:17 UTC, eliykat requested changes

2023-06-21 01:17 UTC, eliykat commented on apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html
> +  <div class="tw-flex-col">
This doesn't have any effect because it's not in a flex container. It looks right though, so you can just delete this div.

2023-06-21 02:03 UTC, eliykat commented on apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html
> +                  >
You said this will fall back gracefully if the new properties aren't present, but in this case it'll call `productName(null)` which returns null and results in an empty/missing string.

2023-06-21 23:59 UTC, shane-melton commented on apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html
> +  <div class="tw-flex-col">
Done

2023-06-21 23:59 UTC, shane-melton commented on apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html
> +            <ng-container *ngIf="!subscription && userOrg.isFreeOrg">
Updated to `userOrg.isFreeOrg` as its sufficient on its own.

2023-06-22 00:00 UTC, shane-melton commented on apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html
> +<div class="tw-mb-2 tw-border-0 tw-border-b tw-border-solid tw-border-secondary-300">
Good point; I removed the border/horizontal line.

2023-06-22 00:00 UTC, shane-melton commented on apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts
> +      : -1;
Done!

2023-06-22 00:05 UTC, shane-melton commented on libs/components/src/progress/progress.component.ts
> +
I reverted the change to the CL for now, as I haven't got a definitive response back from design yet. This way we can merge as is to avoid blocking our other PRs; we can re-evaluate this again before the final merge with `master`.

2023-06-22 00:55 UTC, shane-melton commented on libs/common/src/billing/models/response/subscription.response.ts
> +    this.addonSubscriptionItem = this.getResponseProperty("AddonSubscriptionItem");
Tweaked this to use an enum like we discussed today; server PR is here: https://github.com/bitwarden/server/pull/3037

Currently in a draft state until we determine a way to find the `BitwardenProductType` from a Stripe Subscription Item.

2023-06-22 00:55 UTC, shane-melton commented on apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html
> +                  >
Fixed to fallback to "Password Manager" if the property is missing.

2023-06-22 10:02 UTC, eliykat commented on libs/components/src/progress/progress.component.ts
> +
Good call, thanks

2023-06-22 10:03 UTC, eliykat commented on libs/common/src/billing/models/response/subscription.response.ts
> +    this.addonSubscriptionItem = this.getResponseProperty("AddonSubscriptionItem");
Given that we're only merging into a feature branch here, I'm going to assume you figure out that PR. Let's get this one merged in the meantime.

2023-06-22 10:16 UTC, eliykat requested changes

2023-06-22 10:16 UTC, eliykat commented on apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts
> +    // Both are addon products, sort by enum value
Love the additional comments here, thank you!

2023-06-22 10:16 UTC, eliykat commented on apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts
> +    return 1;
I thought we sorted addon products to the bottom though? So that we have seats, then storage, for example? This makes it sound like it's sorting it: storage, then seats.

2023-06-22 10:16 UTC, eliykat commented on libs/common/src/billing/enums/addon-product-type.enum.ts
Sorry, I missed that we do get the addon product name in its own property (`BillingSubscriptionItemResponse.name`). I thought we just assumed the name (storage/service accounts) from the combination of bitwardenProduct and addOnProduct (when it was a bool). Your initial approach, without this enum, makes more sense to me now. But I'll leave it to you as to which you prefer.

2023-06-22 15:38 UTC, shane-melton commented on apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts
> +    return 1;
Ah, that's just me getting the comment backwards from the logic 🤦 Will fix!

2023-06-22 16:27 UTC, shane-melton commented on libs/common/src/billing/enums/addon-product-type.enum.ts
No worries! Switched back to the boolean

2023-06-22 23:16 UTC, eliykat approved these changes

2023-06-22 23:17 UTC, merged