Individual Vault Items Feature
bitwarden/clients pull request #5623
Opened 2023-06-15 20:13 UTC by trmartin4

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-08-31 14:55 UTC, cagonzalezcs submitted a review, later dismissed

2023-08-31 15:14 UTC, differsthecat approved these changes
Vault changes look good!

2023-08-31 21:14 UTC, MGibson1 requested changes

2023-08-31 21:14 UTC, MGibson1 commented on libs/common/src/platform/services/crypto.service.ts
> +
I would like to see this use https://github.com/bitwarden/clients/pull/6162

2023-08-31 21:14 UTC, MGibson1 commented on libs/common/src/vault/models/view/cipher.view.ts
> +    const key = obj.key == null ? null : SymmetricCryptoKey.fromJSON(obj.key);
I don't see a reason the key is part of the view

2023-08-31 21:14 UTC, MGibson1 commented on libs/common/src/vault/services/cipher.service.spec.ts
> +import { Substitute } from "@fluffy-spoon/substitute";
We are trying to remove this dependency. Can you please convert to jest-mock-extended?

2023-08-31 21:14 UTC, MGibson1 commented on libs/common/src/vault/models/domain/cipher.ts
>      const model = new CipherView(this);
I don't think all these nulls are necessary. I understand you're trying to force the decrypt to use the `encKey`, but that's the behavior of `EncString` anyways. How do you feel about reverting all these deletions of `this.organizationId`?

If not, Please add comment that decrypt calls are forced to have a `null` organizationId becuase we want to force the encryption string.

I think the ideal would actually to have a precursor PR that removed the optional symmetric key from `encString` decrypt.

2023-09-01 01:53 UTC, trmartin4 commented on libs/common/src/platform/services/crypto.service.ts
> +
Are you proposing that we wait until #6162 is in `master` and then merge it in?  Just making sure we handle it appropriately.

2023-09-01 13:34 UTC, aj-rosado approved these changes
Tools changes LGTM

2023-09-01 18:57 UTC, trmartin4 commented on apps/web/config/development.json
> +    "enableCipherKeyEncryption": true
We are keeping this set to `true` for QA to test on the feature branch.  We will submit a second PR to disable this in `master`.

2023-09-01 18:57 UTC, trmartin4 commented on apps/web/config/qa.json
> +    "enableCipherKeyEncryption": true
We are keeping this set to `true` for QA to test on the feature branch.  We will submit a second PR to disable this in `master`.

2023-09-01 18:58 UTC, trmartin4 commented on apps/web/config/selfhosted.json
> +    "enableCipherKeyEncryption": true
We are keeping this set to `true` for QA to test on the feature branch.  We will submit a second PR to disable this in `master`.

2023-09-01 19:12 UTC, trmartin4 commented on libs/common/src/vault/models/domain/cipher.ts
>      const model = new CipherView(this);
I talked to @LRNcardozoWDF, and we've created a tech debt ticket for this (https://bitwarden.atlassian.net/browse/PM-3762) as well as added a comment.

2023-09-02 16:51 UTC, MGibson1 commented on libs/common/src/platform/services/crypto.service.ts
> +
Yes, I think that's the best way to do it

2023-09-02 19:01 UTC, trmartin4 commented on libs/common/src/vault/models/view/cipher.view.ts
> +    const key = obj.key == null ? null : SymmetricCryptoKey.fromJSON(obj.key);
This has been addressed with https://github.com/bitwarden/clients/pull/5623/commits/242570cf3bd55052cf250f5ec3850137ac927e37.

2023-09-02 19:02 UTC, trmartin4 commented on libs/common/src/vault/services/cipher.service.spec.ts
> +import { Substitute } from "@fluffy-spoon/substitute";
This has been addressed with https://github.com/bitwarden/clients/pull/5623/commits/559b9e3383bf7bbec45f7bb90c773bd0293bcbff.

2023-09-02 19:03 UTC, trmartin4 commented on libs/common/src/platform/services/crypto.service.ts
> +
I will keep an eye on #6162 👍 .

2023-09-02 19:05 UTC, trmartin4 commented on libs/common/src/vault/models/domain/cipher.ts
>      const model = new CipherView(this);
The comment was added here: https://github.com/bitwarden/clients/commit/1e903dcfdf8790f08834d8d3ef3b6d9a3cf544de.

2023-09-03 19:26 UTC, trmartin4 commented on libs/common/src/platform/services/crypto.service.ts
> +
Actually, since cipher key encryption is going to be disabled for several releases (to allow client decryption to propagate), I think it may be OK to merge this independently and then follow up after #6162 merges to adjust `makeCipherKey()` to use the new encryption method.  We can try to get them both in before the `2023.9` release - I will post for codeowners for #6162 as well

2023-09-04 06:12 UTC, eliykat commented on libs/common/src/vault/services/cipher.service.ts
> +  }
I haven't done a full review, but this jumped out at me; why are we calling `configApiService` directly instead of using `configService`?

Also, won't this wreck our configService endpoint for bulk operations? e.g. rotating your encryption key?

2023-09-04 15:19 UTC, trmartin4 commented on libs/common/src/vault/services/cipher.service.ts
> +  }
This was an issue that we already discovered and have a follow-up item to address in the next sprint (for October release) https://bitwarden.atlassian.net/browse/PM-2814.  Due to the fact that we will not be enabling the encryption side of this code for several releases, we want to push to get this body of work through to `master` since it has been QA tested.

2023-09-04 19:09 UTC, MGibson1 commented on libs/common/src/vault/services/cipher.service.ts
> +  }
I don't think that makes sense. There's a cost associated with establishing code in the master branch as something we want to be doing, not just it works as tested by QA.

2023-09-04 19:11 UTC, MGibson1 commented on libs/common/src/vault/models/domain/cipher.ts
>      const model = new CipherView(this);
This is an item that would cleanly be merge-able as in another PR prior to this to set the stage for this one. I don't understand pushing it as a tech debt when we don't need to

2023-09-04 20:34 UTC, trmartin4 commented on libs/common/src/vault/services/cipher.service.ts
> +  }
Understood.  I was myopic in my previous comment and focused on moving forward on the current body of work.  The duration and scope of this branch has given us headaches with merge conflicts and re-validation as it continues to live on, and I was focused on that instead of the quality of the PR contents.  @eliykat thank you for calling this out, as it would have caused issues once the flag was enabled.  We'll get this in the next sprint and hold off this PR until it's resolved.

2023-09-05 03:42 UTC, eliykat commented on apps/web/config/development.json
> +    "enableCipherKeyEncryption": true
Doesn't `qa.json` and `selfhosted.json` cover this?

2023-09-05 03:53 UTC, eliykat commented
AC Team changes otherwise look good. @MGibson1 I presume you're reviewing on behalf of tech-leads so I haven't done a review of all the unowned files (of which there are many). But lmk if you want any help there.

2023-09-06 20:58 UTC, MGibson1 commented
@eliykat I'm on quite a limited schedule for the next few weeks, it might be good to have you take over for me

2023-09-06 21:05 UTC, trmartin4 commented on libs/common/src/vault/models/domain/cipher.ts
>      const model = new CipherView(this);
Looking at the scope of the ideal change, it would affect Sends and Collections as well, which I don't feel comfortable introducing into the scope of this (already large) PR.  I've taken the suggested approach to replace the `null` `orgId` with the `organizationId`, as it will be ignored in `decrypt()`.  I have fixed this with https://github.com/bitwarden/clients/pull/6208. I hope you are OK with this compromise.

2023-09-06 21:15 UTC, trmartin4 commented on libs/common/src/vault/services/cipher.service.ts
> +  }
I have a PR to fix this, but I plan to wait until https://github.com/bitwarden/clients/pull/5602 is tested and merged so that I can build upon that work instead of causing merge conflicts.

2023-09-06 21:22 UTC, trmartin4 commented on libs/common/src/platform/services/crypto.service.ts
> +
#6162 should be through QA tomorrow.  Once this is done and it's in `master` I'll merge it in here and adjust our method call.

2023-09-07 16:35 UTC, trmartin4 commented on libs/common/src/platform/services/crypto.service.ts
> +
Addressed this with https://github.com/bitwarden/clients/pull/6222.

2023-09-08 14:37 UTC, trmartin4 commented on libs/common/src/vault/services/cipher.service.ts
> +  }
This has been addressed with https://github.com/bitwarden/clients/pull/5623/commits/95fb06451451595b88fea4009e290a9400eadd8d.

2023-09-08 20:28 UTC, trmartin4 commented on libs/common/src/vault/services/cipher.service.ts
> +  }
Thanks to @eliykat's refactor in #5602 , we have an improved implementation of this merged with https://github.com/bitwarden/clients/commit/bd9755c46828a63af8476464e0c8a6157a3aa076 into the feature branch.

2023-09-08 20:30 UTC, closed without merging