[PM-2733] Master Password Does not Reprompt onEdit after Cancelling M…
bitwarden/clients pull request #5659
Opened 2023-06-22 21:11 UTC by cagonzalezcs

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

During testing of #5635 , QA found an issue where copying the password of a vault item, that requires a master password re-prompt, would allow a user to edit the item without a re-prompt for the edit action. In review of the bug, I found that we were storing the most recent result from a master password re-prompt. 

If a user enacts a copy of a vault item password, we store the result of the re-prompt that allows the user to finish the copy action. Since this copy action does not unload the `view` component used to display the vault item, the value indicating that a re-prompt has occurred never gets set back to false. 

I've put together some changes that address this issue. First, anytime we are triggering a master password re-prompt on an action that will not unload the `view` component, we now disregard the result of the re-prompt, forcing a subsequent re-prompt on sensitive actions. The actions that trigger a re-prompt but do not refresh the component include:

- Toggling visibility of a vault item password
- Toggling visibility of a vault item credit card number
- Toggling visibility of a vault item credit card security code
- Copying a value 

I've also done some refining of the user experience, some details that I'd like to ask @danielleflinn to review and verify are desired from a UX perspective. These can be removed or altered if necessary. The following adjustments have been put in place:

- When toggling a protected field (password, cc number, cvv), if the field is currently not visible then we will re-prompt users for the password (if the item has re-prompt active). If the field is visible, and the user clicks toggle we will not re-prompt the user and set the visibility for the field to hide the element.
- When attempting to copy a protected field, if the field is not currently visible we will re-prompt the user in order to allow the copy. If the field has been toggled to a visible state, then we will not re-prompt the user if they opt to copy the value using the copy button.

The behavior described above can be see in the video attached to this PR.

## Code changes

- **libs/angular/src/vault/components/view.component.ts:** Modified the `promptPassword` method to indicate whether the `passwordReprompted` value should be stored. Will ignore the return value of the password re-prompt if indicated to not store the value. Added a method `copiedFieldIsVisible` which triggers when `copy` is run. This ensures that a password re-prompt only occurs if the field is currently not visible to the user. Added a method `failedPasswordRepromptForFieldToggle` which is used when toggling the visibility of a vault item password, credit card number, or credit card security code. This ensures that users are required to pass a re-prompt if the field is hidden, but do not have to re-prompt in order to hide the field from a visible state.
- **libs/angular/src/vault/services/password-reprompt.service.ts:** Modified the method `protectedFields` to reference the newly added enum `PasswordRepromptProtectedFields` as an array of values.
- **libs/common/src/enums/password-reprompt-protected-fields.enum.ts:** Added an enum for `PasswordRepromptProtectedFields` which allows us to share these values between the `PasswordRepromptService` and `ViewComponent` classes.

## Videos

### Original Behavior

https://github.com/bitwarden/clients/assets/16629865/468e7b09-a3f2-437a-b2d0-cd69eface122

### Fixed Behavior

https://github.com/bitwarden/clients/assets/16629865/4690bee1-cf2a-4566-9a41-ee48c08f506b

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-06-22 21:18 UTC, danielleflinn commented
The updated user experience looks good. Thanks for working on this one!

2023-06-27 17:26 UTC, djsmith85 requested changes

2023-06-27 17:26 UTC, djsmith85 commented on libs/common/src/enums/password-reprompt-protected-fields.enum.ts
Please move this file into `libs/common/src/vault/enums/` and possibly rename it to `cipher-reprompt-protected-fields.enum.ts` , as we might accept other ways to pass the re-prompt

2023-06-28 14:45 UTC, cagonzalezcs commented on libs/common/src/enums/password-reprompt-protected-fields.enum.ts
@djsmith85 

You've got it, this change has been pushed up.

2023-07-03 21:03 UTC, cagonzalezcs commented
@djsmith85 

When you find some time, is there anything else I should improve within this implementation?

2023-07-04 10:47 UTC, djsmith85 reviewed
Just two small naming-related things. 

Through the file-move I initially requested, the code-ownership is now with team-vault-dev, so I'm going to let them do the final review.

2023-07-04 10:47 UTC, djsmith85 commented on libs/angular/src/vault/components/view.component.ts
> +  async failedPasswordRepromptForFieldToggle(isFieldShowing = false): Promise<boolean> {
Just from the methodName it is not clear what this method does and what has or is failing.

2023-07-04 10:47 UTC, djsmith85 commented on libs/angular/src/vault/components/view.component.ts
> +  copiedFieldIsVisible(fieldType: string): boolean {
Maybe just my personal preference, but I think `IsCopiedFieldVisible` is neater.

2023-07-05 15:21 UTC, cagonzalezcs commented on libs/angular/src/vault/components/view.component.ts
> +  copiedFieldIsVisible(fieldType: string): boolean {
Sounds good, I've modified the name of this method to `isCopiedFieldVisible` as suggested.

2023-07-06 23:45 UTC, djsmith85 approved these changes
@cagonzalezcs Thank you for the name changes. This clarifies what the methods are doing.

Leaving the final review to `team-vault-dev`

2023-07-09 18:48 UTC, cagonzalezcs commented
Closing this PR as per discussion within PM-2733's ticket. We're approaching the master password re-prompt process in a different manner down the line, and incorporation of this code will force us to rework certain aspects of the affected files later one.

2023-07-09 18:48 UTC, closed without merging