[AC-1418] Add secrets manager manage subscription component
bitwarden/clients pull request #5661
Opened 2023-06-22 22:22 UTC by shane-melton

## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Introduce a new manage subscription component to the billing tab for secrets manager subscriptions.

**Depends on server changes in https://github.com/bitwarden/server/pull/3036**

## Code changes

- `organization-subscription-cloud.component.ts` - Add the new `app-sm-adjust-subscription` component hidden behind a the `sm-ga-billing` feature flag.
- `sm-adjust-subscription.component.ts` - The new `app-sm-adjust-subscription` component; used to manage SM seats and additional service accounts (and their optional auto-scaling limits)
- `organization-subscription-update.request.ts` - Updated the request to support updating SM and PM subscriptions via the same endpoint. This requires pending server changes in https://github.com/bitwarden/server/pull/3036
- Updates various response objects to include new SM billing details and add the `sm-ga-billing` feature flag. Did my best to duplicate the incoming changes from https://github.com/bitwarden/clients/pull/5617 to avoid potential conflicts when merging.

## Screenshots

![image](https://github.com/bitwarden/clients/assets/8764515/ecc3e83e-1e8f-42e0-8058-96cc546d10fe)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-06-23 04:26 UTC, eliykat reviewed
Please resolve conflicts now that we've started to merge work into the feature branch.

2023-06-26 07:38 UTC, eliykat reviewed
See also my comment on the matching server PR here: https://github.com/bitwarden/server/pull/3036#discussion_r1241707369

That will require matching client-side updates for the endpoint.

2023-06-27 23:57 UTC, shane-melton commented
@eliykat Conflicts have been resolved and I updated the component to use the new endpoint being added in https://github.com/bitwarden/server/pull/3036/files

Should be ready for review again!

2023-06-28 03:34 UTC, eliykat requested changes

2023-06-28 03:34 UTC, eliykat commented on apps/web/src/app/billing/organizations/secrets-manager/sm-adjust-subscription.component.html
> +    <input bitInput id="smSeatCount" formControlName="seatCount" type="number" step="1" min="0" />
You're using reactive form validation, so you don't need the native html validators:

```suggestion
    <input bitInput id="smSeatCount" formControlName="seatCount" type="number" step="1" />
```

2023-06-28 03:34 UTC, eliykat commented on apps/web/src/app/billing/organizations/secrets-manager/sm-adjust-subscription.component.html
> +  <bit-form-field class="tw-w-2/3">
Not essential, but it would look a bit nicer if it matched the width of the existing inputs. Eyeballing them, they look more like 1/2 width rather than 2/3.

2023-06-28 03:34 UTC, eliykat commented on apps/web/src/app/billing/organizations/secrets-manager/sm-adjust-subscription.component.html
> +      [min]="formGroup.value.seatCount"
Remove html validation (and so on throughout the rest of this file)

2023-06-28 03:34 UTC, eliykat commented on libs/common/src/billing/models/request/organization-sm-subscription-update.request.ts
> +   * The number of seats to add or remove from the subscription.
Nice work clearly labelling that this is a diff and not a total. I didn't know it worked like this.

2023-06-28 03:34 UTC, eliykat commented on libs/common/src/admin-console/models/response/organization.response.ts
> +  maxAutoscaleSmServiceAccounts?: number;
Where are these properties being added server side?

2023-06-28 03:34 UTC, eliykat commented on libs/common/src/admin-console/models/response/organization.response.ts
For some reason I can't find `secretsManagerPlan` on this object in the server code, where will this be / has this been added?

2023-06-28 18:13 UTC, shane-melton commented on libs/common/src/admin-console/models/response/organization.response.ts
After our discussion the other day I thought it was to be added in one of the upcoming server tickets as I saw you added the `sercretsManagerPlan` in AC-1420 [here](https://github.com/bitwarden/clients/pull/5617/files#diff-0137e271eb58f9526709a86b3e4f2600e5cd92d8156803a414a010997aef8c7a). 

@cyprain-okeke Do you know where/when we are adding the `secretsMangerPlan` to the organization response?

2023-06-28 18:22 UTC, shane-melton commented on apps/web/src/app/billing/organizations/secrets-manager/sm-adjust-subscription.component.html
> +  <bit-form-field class="tw-w-2/3">
I had 1/2 originally to match the PM subscription options, but then it caused some weird line wrapping for our long helper texts for the SM options. So I extended switched to 2/3 to better match the new designs in Figma and prevent the line wrapping. Perhaps we should update the PM component to use 2/3 as well? 

[The Figma](https://www.figma.com/file/wJ8Fztmrgd3Bq1icnac3Hv/GA_Sign-up-and-upgrade?node-id=45%3A4194&mode=dev) shows the inputs being about 460px wide, which is close to the value 2/3 gets us (480px), whereas 1/2 comes out to 355px.

@bitwarden/dept-design Any thoughts on the preferred width for these inputs in both the SM and PM subscription forms?

2023-06-28 18:33 UTC, shane-melton commented on apps/web/src/app/billing/organizations/secrets-manager/sm-adjust-subscription.component.html
> +    <input bitInput id="smSeatCount" formControlName="seatCount" type="number" step="1" min="0" />
The reactive form validation doesn't need the native html validators; but they are required in order to enforce the limit on the native number input increment/decrement controls. Quick demo showing with the native validator and without:

https://github.com/bitwarden/clients/assets/8764515/efe0eeb1-cfd6-4925-b127-ad7d2d0529b9

2023-06-28 18:41 UTC, shane-melton commented on apps/web/src/app/billing/organizations/secrets-manager/sm-adjust-subscription.component.ts
> +  }
I was re-using the same pattern in the organization plans component that we used in [AC-1420](https://github.com/bitwarden/clients/pull/5617). I don't expect them to ever be negative normally, but its to avoid showing negative totals in case a user still types a negative seat number (not that it would every submit with negative value due to the validator).

https://github.com/bitwarden/clients/blob/86ccff78cb78c9e6a45077c62fa9250557d2419e/apps/web/src/app/billing/settings/organization-plans.component.ts#L276-L279

2023-06-28 18:43 UTC, shane-melton commented on apps/web/src/app/billing/organizations/secrets-manager/sm-adjust-subscription.component.html
> +      [min]="formGroup.value.seatCount"
I think we should keep these in order to enforce the limit when using the native number increment/decrement controls. Demonstration here: https://github.com/bitwarden/clients/pull/5661#discussion_r1245608659

2023-06-28 20:59 UTC, shane-melton commented on apps/web/src/app/billing/organizations/secrets-manager/sm-adjust-subscription.component.html
> +      {{ formGroup.value.seatCount || 0 }} &times; {{ options.seatPrice | currency }} =
Done!

2023-06-28 21:19 UTC, shane-melton commented on apps/web/src/app/billing/organizations/secrets-manager/sm-adjust-subscription.component.ts
> +      : Math.round((this.options.additionalServiceAccountPrice / 12 + Number.EPSILON) * 100) / 100;
Ah, I didn't realize the currency pipe [took care of rounding](https://github.com/angular/angular/blob/a5bd5ddbaace240610f0fef537ca759ab7241e35/packages/common/src/i18n/format_number.ts#L64) and handling any weird floating point errors for us. 

Updated to simply divide by 12.

2023-06-29 01:53 UTC, eliykat commented on apps/web/src/app/billing/organizations/secrets-manager/sm-adjust-subscription.component.ts
> +  }
Sure. I guess we can't be promising refunds for negative seats 😁

2023-06-29 01:56 UTC, eliykat commented on apps/web/src/app/billing/organizations/secrets-manager/sm-adjust-subscription.component.html
> +    <input bitInput id="smSeatCount" formControlName="seatCount" type="number" step="1" min="0" />
I didn't know this, thanks for the demo! As discussed, please follow up to see if we can put this in our CL somehow.

2023-06-29 02:00 UTC, eliykat commented on libs/common/src/admin-console/models/response/organization.response.ts
This might be my bad - I seem to recall that I had some local changes to wire up response models, but I never made a server PR for them. Could you please handle this? And maybe just double check our other models to make sure we haven't missed anything.

2023-06-29 02:00 UTC, eliykat commented on libs/common/src/admin-console/models/response/organization.response.ts
> +  maxAutoscaleSmServiceAccounts?: number;
D'oh! must've had the wrong branch checked out.

2023-06-29 02:03 UTC, eliykat commented on apps/web/src/app/billing/organizations/secrets-manager/sm-adjust-subscription.component.html
> +  <bit-form-field class="tw-w-2/3">
That all sounds reasonable to me. Really we need to update all the nested components to use TW so that we can align the layout. We don't have time to do that currently but I'll defer to @bitwarden/dept-design as to how they want it managed in the meantime. I don't think the different widths look that bad as long as we log it as a follow-up, but then again, I'm not a designer 😁

2023-06-29 02:04 UTC, eliykat reviewed
LGTM pending:
1. server side changes
2. design feedback

I'll hold off on approval until then, but if those are sorted out and I'm offline then feel free to get an approval from anyone.

2023-06-29 16:08 UTC, shane-melton commented on apps/web/src/app/billing/organizations/secrets-manager/sm-adjust-subscription.component.html
> +  <bit-form-field class="tw-w-2/3">
Thanks for the info! I'll go ahead and increase the the PM subscription form to be the 2/3 width so it all matches (still using bootstrap there, as updating everything to TW is out of scope at the moment like Thomas mentioned)

2023-06-29 16:09 UTC, shane-melton commented on libs/common/src/admin-console/models/response/organization.response.ts
No worries! I can take care of it and open a server PR; I'll also double check the other models!

2023-07-03 01:42 UTC, eliykat approved these changes

2023-07-03 01:42 UTC, eliykat commented on apps/web/src/app/billing/organizations/secrets-manager/sm-adjust-subscription.component.html
> +  <bit-form-field class="tw-w-2/3">
Looks good, thank you both!

2023-07-03 05:34 UTC, eliykat commented on libs/common/src/billing/models/request/organization-subscription-update.request.ts
> +  maxAutoscaleSeats?: number;
Thinking about this further. I think we should just send the total number, for 2 reasons:
1. it's less confusing, we can just communicate in totals and let the server figure out the delta. Having the client figure out the delta is a bit weird imo, not really a client-side responsibility
2. it's idempotent - the same request can be sent multiple times and it'll only be processed once. Compare "set my seat count to 10" to "increase my seat count by 2". The latter will result in excess charges if accidentally sent multiple times, the former won't.

If you agree then #3036 can be updated accordingly.

2023-07-03 19:01 UTC, shane-melton commented on libs/common/src/billing/models/request/organization-subscription-update.request.ts
> +  maxAutoscaleSeats?: number;
I agree, sending the total number makes more sense for those reasons you lsited. Do we also want PM subscription updates to do the same? Seems like it would be weird to have PM use deltas and SM use totals, but I recognize its additional refactor work on a limited time budget.

2023-07-03 22:51 UTC, shane-melton commented on libs/common/src/billing/models/request/organization-subscription-update.request.ts
> +  maxAutoscaleSeats?: number;
Per our discussion, created a followup task (AC-1476) to make this change to both the PM and SM endpoints.

2023-07-03 22:51 UTC, merged