[PM-1826] [Tech debt] Migrate file-password-prompt to dialog
bitwarden/clients pull request #5666
Opened 2023-06-23 13:19 UTC by djsmith85

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
Migrate file-password-prompt to dialog which also cleaned up any custom tailwind class usage

## Code changes
- **apps/web/src/app/tools/import-export/dialog/file-password-prompt.component.html:** Replace to use bitDialog
- **apps/web/src/app/tools/import-export/dialog/file-password-prompt.component.html:** Replace usage of ModalRef to DialogRef
- **apps/web/src/app/tools/import-export/import.component.ts:** Get result from new dialog
- **libs/importer/src/importers/bitwarden/bitwarden-password-protected-importer.ts:** Fix issue with cancel/empty password returned

## Screenshots
**BEFORE:**
![image](https://github.com/bitwarden/clients/assets/2670567/15f3442f-e0f9-4718-ac3d-94a4a20826c9)

**AFTER:**
![image](https://github.com/bitwarden/clients/assets/2670567/77d41837-4823-498f-a71d-ad7690cb09fa)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-06-23 13:26 UTC, aj-rosado submitted a review, later dismissed
Changes are looking good to me!

2023-06-23 13:46 UTC, aj-rosado submitted a review, later dismissed

2023-06-23 13:50 UTC, Hinton commented on apps/web/src/app/tools/import-export/dialog/file-password-prompt.component.html
> +    </button>
I don't think you need the click handler here. `bitDialogClose` should handle it for you.

2023-06-23 14:23 UTC, djsmith85 commented on apps/web/src/app/tools/import-export/dialog/file-password-prompt.component.html
> +    </button>
Nice catch!!

2023-06-23 18:37 UTC, danielleflinn requested changes
@djsmith85 looks like we lost the spacing between the instructional text and the text field. Can we add that back in? `tw-m-6` should work well.

2023-06-26 14:11 UTC, danielleflinn requested changes
@djsmith85 margin should only be above the field.

2023-06-26 14:39 UTC, danielleflinn approved these changes

2023-06-26 14:46 UTC, Hinton approved these changes

2023-06-26 21:32 UTC, aj-rosado approved these changes

2023-06-27 15:06 UTC, Hinton commented on apps/web/src/app/tools/import-export/dialog/file-password-prompt.component.html
> +    </button>
Should probably wrap the input and submit button in a form instead, and use the form submit.

2023-06-29 19:49 UTC, Hinton approved these changes

2023-06-29 19:59 UTC, aj-rosado approved these changes

2023-06-29 19:59 UTC, merged