[SM-771] add bulk add sm dialog
bitwarden/clients pull request #5669
Opened 2023-06-23 19:54 UTC by willmartian

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-06-24 04:54 UTC, willmartian commented on apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-enable-sm.component.html
> +          <td bitCell>{{ u.type | userType }}</td>
This was copied from `apps/web/src/app/admin-console/organizations/members/people.component.html`.

2023-06-26 18:55 UTC, Thomas-Avery reviewed
Looks good overall, only have one suggestion.

2023-06-26 18:55 UTC, Thomas-Avery commented on apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-enable-sm.component.ts
> +  };
`[bitAction]` has it own error handling and logging of errors built in. 

We can utilize that by doing something like 

```
  enableAccess = async () => {
    await this.organizationUserService.putOrganizationUserBulkEnableSecretsManager(
      this.data.orgId,
      this.dataSource.data.map((u) => u.id)
    );
     this.platformUtilsService.showToast(
        "success",
        null,
        this.i18nService.t("enabledAccessToSecretsManager")
      );
      this.dialogRef.close();
  };
```

This would make it to where we wouldn't have to pass back results from the dialog. 

It would also make errors more than just a generic message for all cases.

What are your thoughts?

2023-06-26 20:52 UTC, willmartian commented on apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-enable-sm.component.ts
> +  };
Nice, much cleaner. Didn't realize `bitAction` handled errors. [9ac8941](https://github.com/bitwarden/clients/pull/5669/commits/9ac8941b3569d122bb5787694b3224dfd9a37776)

2023-06-27 19:50 UTC, Thomas-Avery approved these changes
LGTM

2023-06-28 04:15 UTC, eliykat requested changes
Thanks @willmartian !

2023-06-28 04:15 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-enable-sm.component.ts
Filename should include `dialog` to correctly reflect the component name:

`bulk-enable-sm-dialog.component.ts`

2023-06-28 04:15 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-enable-sm.component.ts
> +  static open(dialogService: DialogServiceAbstraction, data: BulkEnableSecretsManagerDialogData) {
I've seen these methods as separate helper functions before, but it's much tidier having it as a static class member 👏

2023-06-28 04:15 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-enable-sm.component.ts
> +  enableAccess = async () => {
Maybe a nit: I like the convention that submit methods are always called `submit`.

2023-06-28 04:15 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-enable-sm.component.html
> +                    {{ u.name ?? u.email }}
The `| userName` pipe seems to be intended for this purpose.

2023-06-28 04:15 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-enable-sm.component.html
> +                  <button type="button" bitLink>
This button doesn't do anything. Per the Figma it looks like it should just be text.

2023-06-28 04:59 UTC, willmartian commented on apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-enable-sm.component.ts
> +  enableAccess = async () => {
Sounds like a reasonable nit. 👍

2023-06-28 05:02 UTC, willmartian commented on apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-enable-sm.component.ts
> +  static open(dialogService: DialogServiceAbstraction, data: BulkEnableSecretsManagerDialogData) {
Yeah it is nice! Too bad TypeScript can't have static methods on interfaces, otherwise we could enforce this pattern for all dialogs.

2023-06-28 05:30 UTC, willmartian commented
I suppose we need to only show this new option for organizations that have SM enabled. Added that check in [7388e0e](https://github.com/bitwarden/clients/pull/5669/commits/7388e0ea550989b70322ca73d8dbd9c1a5e126ab) based on how it is implemented in [member-dialog.component.ts](https://github.com/bitwarden/clients/blob/47fa659c355ce47f4b96d325be4cb7eed2e03da8/apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts#L170).

2023-06-28 15:44 UTC, Thomas-Avery approved these changes
Looks good, thank you

2023-06-29 01:35 UTC, eliykat approved these changes

2023-06-29 14:01 UTC, Thomas-Avery approved these changes

2023-06-29 16:42 UTC, merged