[AC-1119] [PM-1923] Import into a specified folder or collection
bitwarden/clients pull request #5683
Opened 2023-06-26 13:02 UTC by djsmith85

## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

[Flexible collections]
- Enable users to select their target-vault(individual and organizational vaults) for importing, without needing to navigate between (`Tools ->Import data` and `Organization -> Select Org -> Settings -> Import data`)
- Enable users to select a folder/collection as a new root for the import (optional)
  - If nothing is selected, the import will proceed as before, importing cipher into their assigned folders/collections
  - If selected, all items without a folder or collection assigned to them will be mapped onto the selected target
  - Any folder/collections present in the import file will be moved to a sub-folder/sub-collection of the selected target
[Tech debt]
- Migrate the import page to [Reactive Forms](https://angular.io/guide/reactive-forms) and replace existing markup to use components from the [Component Library](https://components.bitwarden.com/)

Feature request from the Community Forum: https://community.bitwarden.com/t/allow-importing-into-a-folder-to-cordon-off-the-imports-results-from-your-well-kept-vault/
## Code changes

### UI rework:
- **apps/web/src/app/tools/import-export/import.component.html:** Reactive forms and 
- **apps/web/src/app/tools/import-export/import.component.ts:** Retrieve vaults (individual/orgs), folders and collections for the new dropdowns. Pass on selected import target(folder/collection) on to `import.service`
- **apps/web/src/app/admin-console/organizations/tools/import-export/org-import.component.ts:** Import Formbuilder and pass into to ImportComponent ctor
- **libs/common/src/admin-console/abstractions/organization/organization.service.abstraction.ts:** Helper function to filter out any organizations from the dropwdown, where a member does not have the right permissions to either import or export.

### Enabling import into a specific folder or collections
-  **libs/importer/src/services/import.service.ts:** Add ability to pass in an optional folderId/collectionId which will be used as new root for any items being imported.
- **libs/importer/src/services/import.service.abstraction.ts:** Extend interface to receive selected import target (null | folderId | collectionId)
- **libs/importer/src/services/import.service.spec.ts:** Added unit tests for old behaviour when no target is selected, and with a selected target.
- **apps/web/src/app/tools/import-export/import.component.ts:** Retrieve vaults (individual/orgs), folders and collections for the new dropdowns. Pass on selected import target(folder/collection) on to `import.service`
- **apps/web/src/app/admin-console/organizations/tools/import-export/org-import.component.ts:** Import folder-, org- and collection-service and pass onto ImportComponent ctor
- 

## Screenshots
**BEFORE:**
![image](https://github.com/bitwarden/clients/assets/2670567/2b36aa0b-e097-43a9-b23d-93ee8cd1842b)

**AFTER:**

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-06-28 08:37 UTC, aj-rosado submitted a review, later dismissed
LGTM

2023-06-30 15:39 UTC, shane-melton requested changes
The AC code changes look good to me, nice work!

I just see a few small issues/suggestions that we can clean up regarding the use of the CL form components and async actions; let me know if you have any questions!

2023-06-30 15:39 UTC, shane-melton commented on apps/web/src/app/tools/import-export/import.component.html
> +    <bit-select bitInput name="importVault" formControlName="vaultSelector">
issue: `bitInput` should be removed as it is not allowed on `bit-select`. `bit-select` already implements `BitFormFieldControl` so its not necessary. This also applies to the other `bit-selects` further down that should be updated.

Similarly, `name` is not a supported attribute for the `bit-select` component, and should probably be replaced with `id` (if needed for automated tests, otherwise we can likely just remove it entirely).

2023-06-30 15:39 UTC, shane-melton commented on apps/web/src/app/tools/import-export/import.component.html
> +    <bit-label for="importVault">{{ "importDestination" | i18n }}</bit-label>
issue: `bit-label` doesn't require/support the `for` attribute which should be removed. The `bit-form-field` automatically finds the `bit-label` and creates a native `<label>` tag with a `for` attribute pointing towards the `BitFormFieldControl` for us. This also applies to the other `bit-labels` further down that should be updated.

2023-06-30 15:39 UTC, shane-melton commented on apps/web/src/app/tools/import-export/import.component.html
> +    <br />
question: Can we remove this line break? I'm not seeing any changes with / without it in Chromium at least.

2023-07-04 03:45 UTC, eliykat requested changes
Reviewed `messages.json` for `team-leads-dev`, as that's the only file owned by that team.

2023-07-04 03:45 UTC, eliykat commented on apps/web/src/locales/en/messages.json
> +    "message": "Required, if file contains unassigned items.",
The comma is unnecessary and also doesn't match the Figma.

```suggestion
    "message": "Required if file contains unassigned items.",
```

2023-07-04 03:45 UTC, eliykat commented on apps/web/src/locales/en/messages.json
> +    "description": "Located as a hint under the import target. Will be appended by either folder or collection, depending if the user is importing into an individual or an organizational vault."
I prefer using placeholders here (e.g. `File structure will import into selected $DESTINATION$`) because I think it provides clearer guidance for how to use and how to translate the string. Even if the placeholder value is itself translated, that's fine.

2023-07-04 03:45 UTC, eliykat commented on apps/web/src/locales/en/messages.json
> +    "description": "Located as a hint under the import target. Members of an org have to assign all items to a collection"
No abbreviations:

```suggestion
    "description": "Located as a hint under the import target. Members of an organization have to assign all items to a collection"
```

2023-07-05 20:13 UTC, shane-melton requested changes
Nice work! I only have a few more comments/suggestions and then I think we'll be all set!

2023-07-05 20:13 UTC, shane-melton commented on apps/web/src/app/tools/import-export/import.component.ts
> +      return;
issue: We should call `this.formGroup.markAllAsTouched();` here if the `formGroup` is invalid; otherwise the template will not always update and show which field is invalid.

suggestion: We can move this valid check to the `submit` method so that it can fire before the `org-import.component`'s additional confirmation dialog. Otherwise, they get the org import confirmation/warning dialog, and then the form will show a problem.

2023-07-05 20:58 UTC, shane-melton approved these changes
Changes look good to me! Nice job!

2023-07-06 10:29 UTC, aj-rosado approved these changes

2023-07-07 00:12 UTC, eliykat submitted a review, later dismissed

2023-08-01 15:37 UTC, aj-rosado submitted a review, later dismissed
Changes are looking good to me!

2023-08-03 10:07 UTC, djsmith85 commented
Re-requesting review from @aj-rosado due to merging PR #5933

2023-08-03 10:16 UTC, aj-rosado approved these changes
LGTM

2023-08-04 22:03 UTC, vvolkgang approved these changes
Given that @shane-melton  and @eliykat previously approved it, I went through the recent commits and none had Admin Console related changes.

2023-08-04 22:05 UTC, merged