[PM-1509] Accessibility for <code> elements
bitwarden/clients pull request #5686
Opened 2023-06-26 17:27 UTC by rr-bw

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-06-26 21:41 UTC, danielleflinn requested changes
@rr-bw thanks for working on this. Design had flag this for web in [PM-621](https://bitwarden.atlassian.net/browse/PM-621). Can you update the web code variables to the variables below (copied from PM-621)?

Light: `#C01176`
Dark: `#F08DC7`

If these also work for any of the other client themes, it would be good to keep them consistent.

2023-06-26 23:02 UTC, rr-bw commented
@danielleflinn My bad, I missed that. I've updated those two values across clients. For the Nord theme `#F08DC7` just barely fails accessibility requirements, so I stuck with `#FFA1CC`. Let me know if you'd like something different.

2023-06-26 23:04 UTC, danielleflinn approved these changes
Great! Thank you for checking those against Nord;` #FFA1CC` will be fine.

2023-06-28 13:53 UTC, jlf0dev submitted a review, later dismissed

2023-06-28 17:59 UTC, cagonzalezcs submitted a review, later dismissed
Changes look good, I see some other hardcoded values. Down the line, I wonder if it makes sense to also set this up as referenceable variables

2023-07-05 17:19 UTC, Hinton requested changes
We should sync the tailwind and scss variables.

2023-08-28 19:34 UTC, Hinton commented on apps/web/src/scss/variables.scss
> +$code-color-dark: #f08dc7;
The variable names aren't aligned with the convention in this file. The light color should be under the light variables.
```suggestion
$lightCodeColor: #c01176;
$darkCodeColor: #f08dc7;
```

2023-08-31 18:55 UTC, Hinton approved these changes

2023-09-01 20:18 UTC, merged