DEVOPS-1449 - Add DevOps to CODEOWNERS
bitwarden/clients pull request #5694
Opened 2023-06-27 16:36 UTC by vgrassia

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [X] Other
```

## Objective

This PR allows the DevOps team to update and approve PRs to the Web client configuration and also to any GitHub workflows in the repository.

## Code changes

- **.github/CODEOWNERS:** Update as described above.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-06-27 16:38 UTC, joseph-flinn requested changes

2023-06-27 16:38 UTC, joseph-flinn commented on .github/CODEOWNERS
> +apps/web/package.json @bitwarden/dept-devops
I don't think DevOps should be the only codeowners for `package.json`. Maybe we could also include the default for what it currently is?

2023-06-27 16:45 UTC, withinfocus commented on .github/CODEOWNERS
> +apps/web/package.json @bitwarden/dept-devops
I would say the `package.json` files everywhere are shared and we probably shouldn't assign ownership.

2023-06-27 17:00 UTC, vgrassia commented on .github/CODEOWNERS
> +apps/web/package.json @bitwarden/dept-devops
I've updated the paths to not specify an owner, which I believe removes the requirement for those files.  I'm not sure if this is the right path forward or not.

2023-06-27 17:03 UTC, withinfocus commented on .github/CODEOWNERS
> +apps/web/package.json @bitwarden/dept-devops
We just aren't setting an owner.

2023-06-27 17:33 UTC, Hinton commented on .github/CODEOWNERS
> +/apps/web/package.json
I don't think we should unset the owner. I think this is a scenario where we might need a new team consisting of team-leads and devops.

2023-06-27 17:35 UTC, Hinton commented on .github/CODEOWNERS
> +/apps/web/package.json
I think we can also put both teams on it, and it's enough that one approves it.

2023-06-28 16:04 UTC, vgrassia commented on .github/CODEOWNERS
> +/apps/web/package.json
Leaving off any owners in the lines above should make them unowned and allow anyone to edit and approve changes to those files.

2023-06-28 17:36 UTC, withinfocus approved these changes
I support this, but let's wait for a @Hinton approval too.

2023-06-28 18:37 UTC, merged

2023-06-28 18:38 UTC, vgrassia commented
@Hinton This was already set to auto-merge and I forgot, please let me know if you don't agree with the changes and I'll revert the PR.

2023-06-29 15:15 UTC, Hinton commented on .github/CODEOWNERS
> +/apps/web/package.json
Not really following. I want the package and configs to be owned to prevent accidental breakage or bloat in those files. I do recognize that both devops and teams currently have to make changes to them hence why having both devops and team-leads which forces 1 person from either team to approve it makes sense to me.