[PM-2747] Add Support for Feature Flag of Autofill Version
bitwarden/clients pull request #5695
Opened 2023-06-27 21:51 UTC by cagonzalezcs

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

The objective of this PR is to introduce a methodology that allows us to conditionally set whether the Browser Extension is using Autofill v1 or v2. 

The changes in this PR modify how we handle injection of autofill content scripts. Instead of statically injecting those scripts on `document_start` through declarations within the `manifest.json file`, we now dynamically trigger injection of the scripts from the extension background through a message, `triggerAutofillScriptInjection`, that is sent to the background on `document_start` of the page. 

This allows us to check the configurationService to identify if the feature flag for Autofill v2 has been set, and conditionally set either the v1 or v2 version of the script to load.

## Code changes

- **apps/browser/package.json:** Removal of the build command used to conditionally load autofill v2 within the Webpack build process. We will be using LaunchDarkly to handle switching to the autofill v2 version.
- **apps/browser/src/autofill/content/abstractions/autofill-init.ts** Moving the global extension of the Window object to a separate file within the scope of the autofill feature. 
- **apps/browser/src/autofill/content/abstractions/trigger-autofill-script-injection.ts:** Typing information for the `TriggerAutofillScriptInjection` class
- **apps/browser/src/autofill/content/autofill-init.ts:** Adding a conditional that ensure we do not duplicate injection of the `AutofillInit` class
- **apps/browser/src/autofill/content/trigger-autofill-script-injection.spec.ts:** Tests for the `TriggerAutofillScriptInjection` class.
- **apps/browser/src/autofill/content/trigger-autofill-script-injection.ts:** Currently this represents a very small class that is mean to call the extension background and indicate that the scripts associated with autofill should be inserted. Down the line, we'd like to refine this implementation to handle checks for form elements before calling to inject Autofill
- **apps/browser/src/autofill/globals.d.ts:** Global extension of the `Window` object to verify that we can potentially have the `AutofillInit` and `TriggerAutofillScriptInjection` classes present on the global `window`.
- **apps/browser/src/autofill/services/abstractions/autofill.service.ts:** Modified the typing information for the `AutofillService` class to incorporate a public reference to the `injectAutofillScripts` method.
- **apps/browser/src/autofill/services/autofill.service.spec.ts:** Added tests to validate behavior of the `AutofillService.injectAutofillScripts` method.
- **apps/browser/src/autofill/services/autofill.service.ts**: Added a method to the service that identifies which version of autofill is being injected, then injects all associated autofill content scripts.
- **apps/browser/src/background/runtime.background.ts:** Added an expected message, `triggerAutofillScriptInjection`, which calls on the `AutofillService` to inject all autofill content scripts
- **apps/browser/src/manifest.json:** Removed the static declaration for autofill scripts and added a static declaration for the content script that triggers injection of autofill scripts./
- **apps/browser/src/platform/browser/browser-api.spec.ts:** Added a test for the added `BrowserApi.executeScriptInTab` method.
- **apps/browser/src/platform/browser/browser-api.ts:** Added a static method `executeScriptInTab` which creates a promise that is resolved within the callback of `chrome.tabs.executeScript`. This helper method will also conditionally call the updated extension manifest v3 `scripting` API.
- **apps/browser/webpack.config.js:** Updated this webpack configuration to remove the behavior for the autofill v2 npm command, and add the trigger script to the build.
- **libs/common/src/enums/feature-flag.enum.ts:** Added a feature flag enum for `EnableAutofillV2`.

2023-06-28 16:20 UTC, cagonzalezcs commented on apps/browser/src/background/main.background.ts
> +    this.configApiService = new ConfigApiService(this.apiService, this.authService);
I'm a bit concerned about this addition. The `ConfigService` instance within the extension background originally pointed to an abstract class of `ConfigApiService`. As a result, calls to the service present within the extension background were silently failing and being ignored.

Since we need to check `/config` for the `autofill-v2` feature flag, we need to ensure that an instantiated class of `ConfigApiService` is present. 

However, I was noticing that we make SEVERAL calls to the config when initializing the extension... This likely isn't something we want to do, and I'm wondering if it's worth exploring implementing a cached/stored value within the `ConfigService`.

@MGibson1 Can I please ask for your opinion on this? Just want to make sure we're not hammering the API unnecessarily. That said, if this isn't a huge concern then I'll hold off on caching the config response.

2023-06-29 01:26 UTC, eliykat commented
I have nothing to add here except that I didn't know you could dynamically inject scripts, this looks like a cool solution and I'm glad you followed up on it! 👏

2023-07-03 20:27 UTC, cagonzalezcs commented
> I haven't reviewed, but just wanted to say that this looks like a cool solution and I'm glad you followed up on it! 👏 I didn't know you could dynamically inject content scripts like this.

Thank you! Yeah, it definitely changes up how flexible you can be with execution of content scripts... we're considering expanding this behavior down the line to selectively inject autofill behavior, rather than loading it on each page... For now though, these changes should allow us to easily set up a feature flag in place.

2023-08-21 22:26 UTC, cagonzalezcs commented on apps/browser/src/autofill/content/notification-bar.ts
> +  const activeUserStorageValue = await getFromLocalStorage(activeUserIdKey);
@jprusik I might need to ask you to take a look at this resolution of our merge conflict. 

I should have called this out on #5868 but when doing `await chrome.storage.local.get` we're not actually awaiting any of the behavior that happens within the callback function. What needs to happen is that we need to only await the storage value that comes from `chrome.storage.local.get`, then handle logic around that to ensure that we have a clear order of execution. 

Let's talk on this at a later time, but I had to do some rewriting of the usage of that extension API in order to present the same logical flow.

2023-08-29 19:48 UTC, MGibson1 requested changes
A few style changes

2023-08-29 19:48 UTC, MGibson1 commented on apps/browser/src/platform/browser/browser-api.spec.ts
> +    jest.clearAllMocks();
Please move to `afterEach` lifecycle method for consistency (unless there's some reset that needs to happen before the rest, but I don't think there is).

2023-08-29 20:23 UTC, cagonzalezcs commented on apps/browser/src/platform/browser/browser-api.spec.ts
> +describe("BrowserApi", function () {
Sounds good, I'll ensure we write these using arrow functions moving forward. I've updated the method specifically referenced in this file.

2023-08-29 20:24 UTC, cagonzalezcs commented on apps/browser/src/platform/browser/browser-api.spec.ts
> +    jest.clearAllMocks();
Sure, no problem. I've updated the clear to work on an afterEach basis.

2023-08-29 20:24 UTC, cagonzalezcs commented on apps/browser/src/platform/browser/browser-api.spec.ts
> +    } as any;
Sounds good, I've removed the mocks from this file and moved them over to the `test.setup.ts` file.

2023-08-29 20:25 UTC, cagonzalezcs commented on apps/browser/webpack.config.js
> +if (autofillVersion == 2) {
Agreed, this has been removed along with the npm script call within package.json.

2023-08-29 20:43 UTC, jprusik commented on apps/browser/src/autofill/content/notification-bar.ts
> +  const activeUserStorageValue = await getFromLocalStorage(activeUserIdKey);
Looks good to me and tested as working (not launching the banner on vault domain) on autofill v1

2023-08-29 20:43 UTC, jprusik approved these changes

2023-08-29 21:21 UTC, MGibson1 requested changes

2023-08-29 21:21 UTC, MGibson1 commented on apps/browser/src/platform/browser/browser-api.spec.ts
> +      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
These ignores aren't necessary if you cast `chrome.scripting.executeScript` to `jest.Mock`

2023-08-29 21:30 UTC, merged