[AC-1473] SM beta ending callout
bitwarden/clients pull request #5719
Opened 2023-06-30 14:44 UTC by willmartian

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

This PR introduces a callout on the organization subscriptions page that alerts the user the SM beta is ending. 

The callout will dynamically show the number of days remaining before the end of the grace period. 

The callout should only be visible to organizations that have not paid for SM. 

## Code changes

- **apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html:** Added bit-callout and extra row to table
- **libs/common/src/platform/misc/utils.ts:** Added `daysRemaining` util function
- **apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html:** Added bit-callout and extra row to table
- Added `secretsManagerBeta` field to the following models and responses:
  - `libs/common/src/admin-console/models/response/organization.response.ts`
  - `libs/common/src/admin-console/models/response/profile-organization.response.ts`
  - `libs/common/src/admin-console/models/data/organization.data.ts`
  - `libs/common/src/admin-console/models/domain/organization.ts`

## Screenshots

<img width="1724" alt="image" src="https://github.com/bitwarden/clients/assets/17113462/d3fcb1a5-cafe-4ada-a185-cd12a7219bc9">

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-06-30 14:53 UTC, willmartian commented
- I am toggling the callout's visibility based on the new `Organization.SecretsManagerBeta` field (still to be implemented on the server). Does this flag suffice, or do I need to add additional logic to the check?

- I added the `Organization.SecretsManagerBeta` field to`organization.response.ts` AND `profile-organization.response.ts`. Is this correct? Not familiar with the latter.

2023-06-30 14:54 UTC, willmartian commented
Blocked by #5661

2023-06-30 18:20 UTC, shane-melton requested changes
Looks pretty good, nice work! Just need to fix a few tiny issues and double check a date and then I think we'll be good to go!

2023-06-30 18:20 UTC, shane-melton commented on apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html
suggestion: I think we should also probably hide the SM "Free Organization" row that can show above the new SM Beta row. Otherwise, if a Free org is also flagged as a beta user, they'll see both the Free SM and SM Beta line items.

You should be able to just tweak the "free" row to use something like:
`*ngIf="userOrg.userSecretsManager && !userOrg.secretsManagerBeta"`

2023-06-30 18:23 UTC, shane-melton commented
> * I am toggling the callout's visibility based on the new `Organization.SecretsManagerBeta` field (still to be implemented on the server). Does this flag suffice, or do I need to add additional logic to the check?

I think that should suffice; the only other condition I could see adding is checking if `UseSecretsManager` is also enabled. But, that's likely redundant as if `SecretsManagerBeta` is enabled, then `UseSecretsManager` should also always be enabled.

> * I added the `Organization.SecretsManagerBeta` field to`organization.response.ts` AND `profile-organization.response.ts`. Is this correct? Not familiar with the latter.

Yep, those are the two responses that need the property added. `organizaiton.response.ts` is used primarily by the organization API service and the `profile-organization.response.ts` is used by the sync/state/organization services.

2023-07-06 04:30 UTC, eliykat commented on libs/common/src/admin-console/models/response/profile-organization.response.ts
> +  secretsManagerBeta: boolean;
As far as I know (please correct me if I'm wrong), we only need this value in the `organization-subscription-cloud` component, not elsewhere in the app. In that case, we can just add it to the `organizationResponse`, or even the `organizationSubscriptionResponse` (being the most specific location), and avoid muddling other models with it.

2023-07-06 04:31 UTC, eliykat commented on libs/common/src/platform/misc/utils.ts
> +    return Math.max(0, Math.round(diffTime / (1000 * 60 * 60 * 24)));
Please use a const declaration to describe what these numbers are.

2023-07-06 04:34 UTC, eliykat requested changes
I just gave this a quick look over to answer @Thomas-Avery's questions about where we need the new property added. imo we should just add it where we need it and avoid adding it to sync data.

I also merged in the target branch & resolved conflicts to fix the diff for my review.

2023-07-07 15:09 UTC, willmartian commented on libs/common/src/admin-console/models/response/profile-organization.response.ts
> +  secretsManagerBeta: boolean;
Two other areas I am aware of include the Admin Panel and [within Secrets Manager itself](https://bitwarden.atlassian.net/browse/SM-820).

2023-07-07 16:09 UTC, willmartian commented on apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html
Fixed here: [db1e326](https://github.com/bitwarden/clients/pull/5719/commits/db1e326bb058327b5eac50d86029dfd7ecf4eb0f)

2023-07-07 16:09 UTC, willmartian commented on libs/common/src/admin-console/models/domain/organization.ts
Fixed here: [c797d92](https://github.com/bitwarden/clients/pull/5719/commits/c797d92acad98ed14261d40467ef131d1bf938bd)

2023-07-07 16:09 UTC, willmartian commented on libs/common/src/platform/misc/utils.ts
> +    return Math.max(0, Math.round(diffTime / (1000 * 60 * 60 * 24)));
Fixed here: [4ae7b85](https://github.com/bitwarden/clients/pull/5719/commits/4ae7b8512feeebbb183ad9a262e3300fa16309b3)

2023-07-07 16:21 UTC, willmartian commented on apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts
> +  secretsManagerBetaDaysRemaining = Utils.daysRemaining(new Date(2023, 9, 1));
Updated the dates to match what is in Figma. Also updated the i18n message to accept dynamic dates. 

<img width="912" alt="image" src="https://github.com/bitwarden/clients/assets/17113462/af0d01ec-86a0-443d-8578-6047033904a2">

2023-07-07 20:20 UTC, willmartian commented on libs/common/src/admin-console/models/response/profile-organization.response.ts
> +  secretsManagerBeta: boolean;
Ignore the above. I talked with @Thomas-Avery and he cleared this up for me. Refactored to use the `OrganizationSubscriptionResponse`: [ea3bfa0](https://github.com/bitwarden/clients/pull/5719/commits/ea3bfa09913d9255ccafefb02dd8d8c05b5dbc46)

2023-07-10 03:41 UTC, eliykat commented on libs/common/src/admin-console/models/response/profile-organization.response.ts
> +  secretsManagerBeta: boolean;
Thanks for investigating!

2023-07-10 03:43 UTC, eliykat reviewed
LGTM, but re-reading the callout text, it doesn't make sense to me. As your screenshot shows, you can be on a Teams or Enterprise plan with SM Beta, which means the callout is asking you to upgrade to something you already have. Right?

There's also no call to action, there's no self-serve pathway for users to do this, so it's unclear what they're supposed to do.

It's a question for product, but perhaps it should say "contact our Customer Success team to add Secrets Manager to your paid subscription"?

PS. Thanks for handling the show/hide on the manage subscription component!

2023-07-10 16:18 UTC, jtouchstonebw commented
> LGTM, but re-reading the callout text, it doesn't make sense to me. As your screenshot shows, you can be on a Teams or Enterprise plan with SM Beta, which means the callout is asking you to upgrade to something you already have. Right?
> 
> There's also no call to action, there's no self-serve pathway for users to do this, so it's unclear what they're supposed to do.
> 
> It's a question for product, but perhaps it should say "contact our Customer Success team to add Secrets Manager to your paid subscription"?
> 
> PS. Thanks for handling the show/hide on the manage subscription component!

There should be an "Upgrade plan" CTA button below the callout in this view.

2023-07-10 20:36 UTC, willmartian commented
> There should be an "Upgrade plan" CTA button below the callout in this view.

It was my understanding that the scope of this ticket only included the callout and the table row. 

Does the "Upgrade plan" button + showing/hiding the upgrade section need to be added to this PR, or is being captured elsewhere?

2023-07-10 23:55 UTC, jtouchstonebw commented
> 

Updated my comment above

2023-07-11 14:40 UTC, willmartian commented
Thanks @eliykat and @jtouchstonebw ! Updated the copy here: [b40f44c](https://github.com/bitwarden/clients/pull/5719/commits/b40f44c4aeaed742ec2169c03f2bea1993590c15)

2023-07-11 19:34 UTC, jtouchstonebw approved these changes

2023-07-12 17:40 UTC, shane-melton reviewed
Looks good to me and all of my comments/issues have been resolved, nice work!

2023-07-12 17:40 UTC, shane-melton approved these changes

2023-07-13 01:01 UTC, eliykat approved these changes
Do we want to include a link to the Contact Us form so that they know how to contact CS?

I'll approve in the meantime. Adding a `hold` label, as the feature branch has been stabilized so that QA can test the first tranche of SM billing changes. We'll merge this after the feature branch has been merged - no action required in the meantime.

2023-07-14 01:26 UTC, eliykat commented
Updated to the round-2 feature branch. Merge when ready.

2023-07-14 13:35 UTC, merged