[PM-2169] Update Password Reprompt Modal to use Component Library
bitwarden/clients pull request #5720
Opened 2023-06-30 16:13 UTC by gbubemismith

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-07-07 16:56 UTC, differsthecat commented on libs/angular/src/vault/components/password-reprompt.component.ts
> +    @Optional() protected modalRef: ModalRef
Instead of doing the optional services in the base service, could you define the constructor in the web service and not inject the dialogRef and modalRef's in the super call? That would align with how we do this in other places.
An example of this is in `apps/web/src/app/vault/org-vault/vault-filter/vault-filter.service.ts`

2023-07-11 06:13 UTC, willmartian reviewed
Thanks for your work on this @gbubemismith !

Some feedback:

I don't think we should mix usages of `DialogService` and `ModalService` based on the client. This leaves the component in a partially migrated state that misses two overarching goals here:

1. Migrating _from_ the `ModalService` because of deprecations in Angular v16.
2. Migrating _to_ the Component Library's `DialogService` in multiple clients for design consistency & code reuse.

I would recommend that we pause work on this ticket until `DialogService.open` is usable in the browser and desktop clients, which I am tracking [here.](https://bitwarden.atlassian.net/browse/CL-106) That way we can migrate the component a single time, instead of needing to update it again after the above is finished. :)

2023-08-22 16:43 UTC, willmartian requested changes
The web dialog looks good. 

We don't need the browser/desktop versions of these components anymore. Lets delete them (and their respective services if possible). Then we can move the base dialog with the new template to `libs/vault` and export it from there into each client.

2023-08-22 16:57 UTC, willmartian commented
> Then we can move the base dialog with the new template to `libs/vault` and export it from there into each client.

The vault lib was recently merged in [here](https://github.com/bitwarden/clients/pull/6083). Let me know if you have any issues with it!

2023-08-28 21:29 UTC, willmartian commented on apps/browser/tsconfig.json
> -      "@bitwarden/vault": ["../../libs/auth/src"]
This change fixes I typo I made when creating `@bitwarden/vault` in https://github.com/bitwarden/clients/pull/6083.

2023-08-29 13:18 UTC, Hinton commented on libs/vault/src/components/password-reprompt.component.ts
> +  }
You can remove this, the `bitPasswordInputToggle` handles this for you.

2023-08-29 13:20 UTC, Hinton commented on libs/vault/src/components/password-reprompt.component.ts
> +  selector: "app-password-reprompt",
I think we should use `vault` as the prefix here. Will let consumers know at a quick glance whom the owner of the component is. https://angular.io/guide/styleguide#component-custom-prefix

2023-08-29 21:26 UTC, willmartian commented on libs/vault/src/components/password-reprompt.component.ts
> +  selector: "app-password-reprompt",
Yes, agreed, `vault-` instead of `app-`. 

(I will look into enforcing this with `@angular-eslint/component-selector` and `directive-selector` in the team-owned libs.)

2023-08-29 21:56 UTC, willmartian requested changes
One final change request from me:

2023-08-29 21:56 UTC, willmartian commented on libs/vault/src/components/password-reprompt.component.html
> +      <button bitButton buttonType="secondary" bitDialogClose type="button" data-dismiss="modal">
`data-dismiss` is not needed in CL dialogs. The same functionality is covered by `bitDialogClose`.

2023-08-29 21:56 UTC, willmartian commented on libs/vault/src/components/password-reprompt.component.ts
> +    JslibModule,
It looks like the only part of the `JsLibModule` being used here is the `I18nPipe`. 

No action needed in this PR, more of a note to me/@bitwarden/team-platform-dev: it might be good to make this pipe standalone so devs can include it in standalone components without bringing in the entire `JsLibModule`.

2023-08-30 00:34 UTC, eliykat submitted a review, later dismissed
AC Team changes look good

2023-08-30 15:30 UTC, JaredSnider-Bitwarden submitted a review, later dismissed
LGTM from the auth perspective! Nice work on this refactor!

2023-08-30 17:32 UTC, willmartian submitted a review, later dismissed
Great work here, @gbubemismith. LGTM 💯

2023-09-05 15:53 UTC, differsthecat approved these changes
Thanks for your hard work on this @gbubemismith , it looks good!

2023-09-07 10:27 UTC, Hinton reviewed
My concerns were resolved.

2023-09-20 16:54 UTC, differsthecat submitted a review, later dismissed
Approving from before

2023-09-20 17:07 UTC, willmartian commented on libs/angular/src/vault/components/password-reprompt.component.ts
> +    if (!(await this.cryptoService.compareAndUpdateKeyHash(this.masterPassword, null))) {
Is this intentional or was this an accidental change from resolving the merge conflict?

2023-09-20 17:24 UTC, gbubemismith commented on libs/angular/src/vault/components/password-reprompt.component.ts
> +    if (!(await this.cryptoService.compareAndUpdateKeyHash(this.masterPassword, null))) {
It's a change from master on the password-reprompt,component.ts

2023-09-20 17:27 UTC, willmartian commented on libs/angular/src/vault/components/password-reprompt.component.ts
> +    if (!(await this.cryptoService.compareAndUpdateKeyHash(this.masterPassword, null))) {
It looks like your change is reverting master from the change that was made here: https://github.com/bitwarden/clients/commit/30d8168c2e5c96739a4c02fa7dc7306911198d32

CC @differsthecat

2023-09-20 17:28 UTC, differsthecat commented on libs/angular/src/vault/components/password-reprompt.component.ts
> +    if (!(await this.cryptoService.compareAndUpdateKeyHash(this.masterPassword, null))) {
We definitely want to keep that change in there; it fixes the reprompt if users have logged in with biometrics.

2023-09-20 17:41 UTC, gbubemismith commented on libs/angular/src/vault/components/password-reprompt.component.ts
> +    if (!(await this.cryptoService.compareAndUpdateKeyHash(this.masterPassword, null))) {
@willmartian, that file doesn't exist anymore on this PR because we decided to make the component a standalone component

2023-09-20 17:55 UTC, gbubemismith commented on libs/angular/src/vault/components/password-reprompt.component.ts
> +    if (!(await this.cryptoService.compareAndUpdateKeyHash(this.masterPassword, null))) {
I see what happened the actual change is here https://github.com/bitwarden/clients/pull/5720/files#diff-3cee42f4d20ca18ea2bc33ddbfa7a7459a8117215ef876b00d6d111583628a5bR49

2023-09-20 18:08 UTC, willmartian submitted a review, later dismissed

2023-09-26 02:52 UTC, eliykat approved these changes
AC Team changes are approved

2023-09-26 14:00 UTC, willmartian submitted a review, later dismissed

2023-09-26 19:02 UTC, jlf0dev approved these changes

2023-09-26 19:25 UTC, shane-melton submitted a review, later dismissed

2023-10-03 13:41 UTC, willmartian approved these changes

2023-10-03 14:33 UTC, JaredSnider-Bitwarden submitted a review, later dismissed
👍

2023-10-03 15:31 UTC, shane-melton approved these changes

2023-10-03 15:51 UTC, differsthecat submitted a review, later dismissed
@gbubemismith Looks like you need an approval from @bitwarden/tech-leads , but @shane-melton should be a part of that group. I'll ask to get him added and approve only because he has approved and I had looked at this previously.

2023-10-04 14:06 UTC, willmartian approved these changes

2023-10-04 15:03 UTC, shane-melton approved these changes

2023-10-04 15:46 UTC, JaredSnider-Bitwarden approved these changes
Merges look good!

2023-10-05 01:16 UTC, eliykat approved these changes

2023-10-05 02:56 UTC, merged