[PM-1977] Display passkeys properly on the desktop
bitwarden/clients pull request #5763
Opened 2023-07-07 21:28 UTC by gbubemismith

## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Passkeys will be listed in the vault alongside Login items in the browser clients. Anywhere users filter to login item type, passkeys will also be displayed using the same sort order (eg, if a list of login items is sorted by name, the login item “A” will display, then the passkey item “B”, then the login item “C”

When the launch icon is selected on the Application field, launch the top domain of the rpId.

Passkeys item cannot be cloned.

Non-discoverable passkeys = 2FA

Display a passkey field on the Login item above the TOTP field.

Login items with the passkey field can be cloned, but the user is warned that the passkey field will not be included in the cloned item.
## Code changes

- **apps/desktop/src/vault/app/vault/add-edit.component.html:** Added view for `Fido2Key` when editing.
- **apps/desktop/src/vault/app/vault/vault.component.ts:** Added launch option to `Fido2Key` vault item
- **apps/desktop/src/vault/app/vault/view.component.html:** Added vault view for Fido2Key to align with the Figma designs.
-  **libs/angular/src/vault/vault-filter/models/vault-filter.model.ts:** Modified the filter so `Login` and `Fido2Key` would be treated as a single type when building the filter.

## Screenshots
<img width="970" alt="Screenshot 2023-07-07 at 5 26 42 PM" src="https://github.com/bitwarden/clients/assets/13024008/b2d70b70-c0ac-4731-bd1a-f64eb04cff6c">
<img width="969" alt="Screenshot 2023-07-07 at 5 26 59 PM" src="https://github.com/bitwarden/clients/assets/13024008/4f1b2388-20d0-47c7-8ae0-c757593d368b">
<img width="968" alt="Screenshot 2023-07-07 at 5 27 12 PM" src="https://github.com/bitwarden/clients/assets/13024008/702ab580-46ca-4a83-b7ad-c028acb29f19">
<img width="696" alt="Screenshot 2023-07-07 at 5 27 23 PM" src="https://github.com/bitwarden/clients/assets/13024008/0373ce9a-9dea-4007-8dbd-9bbd1e0b02b6">

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-07-10 12:20 UTC, coroiu requested changes

2023-07-10 12:20 UTC, coroiu commented on apps/desktop/src/vault/app/vault/add-edit.component.html
> +                [readonly]="!cipher.edit && editMode"
question: aren't passkey usernames readonly? Or am I misremembering things? :)

2023-07-10 12:20 UTC, coroiu commented on apps/desktop/src/vault/app/vault/add-edit.component.html
> +              {{ "dateCreated" | i18n }} {{ cipher.creationDate | date : "MM/dd/y" }}
issue: date format should depend on locale
```suggestion
              {{ "dateCreated" | i18n }} {{ cipher.creationDate | date : "medium" }}
```

2023-07-10 12:20 UTC, coroiu commented on apps/desktop/src/vault/app/vault/view.component.html
> +            {{ "dateCreated" | i18n }} {{ cipher.creationDate | date : "MM/dd/y" }}
issue: same here, can we use another date format?

2023-07-10 12:20 UTC, coroiu commented on apps/desktop/src/vault/app/vault/view.component.html
> +              [appA11yTitle]="'launch' | i18n"
issue: this doesn't seem right, `appA11yTitle` directive already sets `aria-label`. Don't use both

2023-07-10 12:20 UTC, coroiu commented on apps/desktop/src/vault/app/vault/view.component.html
> +              [appA11yTitle]="'copyUri' | i18n"
issue: same a11y issue

2023-07-10 12:20 UTC, coroiu commented on libs/angular/src/vault/vault-filter/models/vault-filter.model.ts
> +        }
question: do we have any tests for this?

2023-07-10 12:20 UTC, coroiu commented on libs/common/src/vault/models/view/cipher.view.ts
> +
issue: this doesn't seem right, why are we checking keys on a class? From personal experience `Object.keys` is also very slow. Can't we just use `this.type === CipherType.Fido2Key` ?

2023-07-10 12:39 UTC, gbubemismith commented on apps/desktop/src/vault/app/vault/add-edit.component.html
> +              {{ "dateCreated" | i18n }} {{ cipher.creationDate | date : "MM/dd/y" }}
The date format is based on the Figma designs as well

2023-07-11 08:49 UTC, coroiu commented on apps/desktop/src/vault/app/vault/add-edit.component.html
> +              {{ "dateCreated" | i18n }} {{ cipher.creationDate | date : "MM/dd/y" }}
Figma designs usually use `en-US` locale, I've added a comment in Figma to ask about locale-dependent dates

2023-07-11 08:51 UTC, coroiu reviewed
👍 just waiting on answer from Danielle here: https://www.figma.com/file/K7u674lSE0UJrAFK9ikzT9?node-id=233:28788&mode=design#494289573

2023-07-11 14:53 UTC, coroiu commented on apps/desktop/src/vault/app/vault/add-edit.component.html
> +              {{ "dateCreated" | i18n }} {{ cipher.creationDate | date : "MM/dd/y" }}
Got a response, you can use the `short` format

2023-07-11 14:58 UTC, gbubemismith commented on apps/desktop/src/vault/app/vault/add-edit.component.html
> +              {{ "dateCreated" | i18n }} {{ cipher.creationDate | date : "MM/dd/y" }}
Yeah just saw that. I would be making the changes to the other clients as well

2023-07-12 08:53 UTC, coroiu approved these changes
👍

2023-07-21 16:39 UTC, merged