Implement ProtonPass json importer
bitwarden/clients pull request #5766
Opened 2023-07-08 06:53 UTC by quexten

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

This PR implements an importer for the ProtonPass password manager. ProtonPass exports as (encrypted/unencrypted) Zip files. This archive contains a data.json. The importer takes the (unencrypted) JSON file and extracts Logins (including custom fields and TOTP secrets) and secure notes.

The only other type, email aliases, are discarded (as I'm not sure they have a corresponding Bitwarden representation).

ProtonPass has different "vaults". Right now, these are ignored but we could map these to folders.

## Code changes

- **protonpass-json-importer.ts** Implement the importer
- All other files: Implement the code to load and show the importer correctly

## Screenshots

![image](https://github.com/bitwarden/clients/assets/11866552/c61c104a-3a98-491f-a954-475b6c1d54e7)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-07-10 16:23 UTC, djsmith85 requested changes
Very nice work on this, @quexten 🚀. Both of your recent PRs are picking up on work; we were aiming for the next sprint or shortly after 👍. We really appreciate your contributions!

Love the types!! This is not an exhaustive review, just some pointers while the PR is fresh. 

As import/export formats change frequently, our team likes to have unit tests for the importers. This enables us to quickly verify any changes in the structure and add a new test before we proceed with the implementation of new fields.

2023-07-10 16:23 UTC, djsmith85 commented on libs/importer/src/importers/protonpass/protonpass-json-importer.ts
> +    if (results == null || results.vaults == null || results.encrypted) {
If the file is encrypted, we should show the user a specific message, why the import did not succeed/does not support encrypted files. For example like its done in the [passky-json-importer](https://github.com/bitwarden/clients/blob/master/libs/importer/src/importers/passky/passky-json-importer.ts#L20-L24C6). Although please use i18n, which I missed there.

2023-07-10 16:23 UTC, djsmith85 commented on apps/web/src/app/tools/import-export/import.component.html
> +    </ng-container>
Currently this importer only supports the extracted zip file. To make it easier for users to import, we could also enable to import via zip, file (data.json) or file content (textarea).

As an example for the needed changes you could have a look at the 1pux import. 
Specifically [here for web](https://github.com/bitwarden/clients/blob/master/apps/web/src/app/tools/import-export/import.component.ts#L228-L230) and [here for cli](https://github.com/bitwarden/clients/blob/master/apps/cli/src/tools/import.command.ts#L69C1-L70).

We are planning to refactor that part of the extraction/unzipping at some point, but adding to the existing logic is fine for now.

2023-07-10 16:23 UTC, djsmith85 commented on libs/importer/src/importers/index.ts
> +export { ProtonPassJsonImporter } from "./protonpass/protonpass-json-importer";
Please export in alphabetical order

2023-07-12 17:20 UTC, quexten commented on apps/web/src/app/tools/import-export/import.component.html
> +    </ng-container>
Added support for Protonpass (Zip) now as a separate importer (well, using the same ProtonPassJsonImporter class in the background). I renamed the `extract1PuxContent` methods to `extractZipContent` and added a filepath property since otherwise it would have just been duplicated.

> file (data.json) or file content (textarea).
Both of these are covered by the Protonpass (json) importer.

2023-07-13 18:11 UTC, quexten commented
@djsmith85 One issue is that protonpass allows multiple totp codes, some as extra fields. Right now this case is not handled, as bitwarden only allows 1 totp code per login. How should this be handled?

Either we could split this into 2 ciphers, with one totp code on each, or we could add the totp secret as an extra field (but users wouldn't see the 2FA codes in Bitwarden. They would have to create a new entry manually from the secret).

2023-07-13 18:20 UTC, djsmith85 commented
> @djsmith85 One issue is that protonpass allows multiple totp codes, some as extra fields. Right now this case is not handled, as bitwarden only allows 1 totp code per login. How should this be handled?
> 
> Either we could split this into 2 ciphers, with one totp code on each, or we could add the totp secret as an extra field (but users wouldn't see the 2FA codes in Bitwarden. They would have to create a new entry manually from the secret).

Retaining all data is the most important thing, when migrating data. So I try to keep the data together, if it was previously on the same entry. I'd likely take the first one and map it into the totp-field and the 2nd as a custom field, if present.

I can't say how common a 2nd totp seed is, but in anyway we are migrating it and the user can decide if they want to create a 2nd entry for it.

2023-07-13 19:19 UTC, quexten commented
Ok, changed it to add them as a hidden field, and added a test case for it.

2023-08-01 18:24 UTC, djsmith85 commented on apps/web/src/app/tools/import-export/import.component.html
> +    </ng-container>
@quexten: I've gotten some feedback from product, regarding the import-options and instructions. We would like to only show the instructions for the zip-file (`protonpasszip`) as a ProtonPass export defaults to a zip.

For the dropdown we would like to show `"ProtonPass (zip/json)"`

2023-08-01 22:10 UTC, quexten commented on apps/web/src/app/tools/import-export/import.component.html
> +    </ng-container>
> We would like to only show the instructions for the zip-file (protonpasszip) as a ProtonPass export defaults to a zip.

That makes sense from a usability perspective.

> For the dropdown we would like to show "ProtonPass (zip/json)"

Note: At the moment, no other importer does this. All importers (1password, Bitwarden, etc.) distinguish by file type. Regardless, I suppose we could just check the file extension, and then split code-paths here: https://github.com/bitwarden/clients/blob/741ea7744d5c53e30d10bda67f4cebf3dbc1d543/apps/web/src/app/tools/import-export/import.component.ts#L227-L233

2023-08-01 22:55 UTC, quexten commented on apps/web/src/app/tools/import-export/import.component.html
> +    </ng-container>
Implemented in 65abdcd2f9bb1d7633b617f996e576154a8013ac.

2023-08-02 14:56 UTC, djsmith85 requested changes
@quexten Overall awesome work on this ❤️ 🚀 We really appreciate your contributions❗ 

I've added some comments during my review and it would be nice to also include the following:

- Adding support for the other item types ("creditCard", "note"). "alias" will currently stay unmapped.
- Extending the unit tests to be more extensive and include the new cases (folder/collection support, other item types

This is just to meet user expectations as closely as possible (migrating all data, if feasible).

2023-08-02 14:56 UTC, djsmith85 commented on libs/importer/src/importers/protonpass/protonpass-json-importer.ts
> +      for (const item of vault.items) {
As the `vaults` in ProtonPass could likely be seen as folders we should add them here
```suggestion
    for (const [, vault] of Object.entries(results.vaults)) {
      this.processFolder(result, vault.name);
      for (const item of vault.items) {
```

2023-08-02 14:56 UTC, djsmith85 commented on libs/importer/src/importers/protonpass/types/protonpass-json-type.ts
> +  type: string;
We should specify which types ProtonPass  currently exports
```suggestion
  type: "login" | "alias" | "creditCard" | "note";
```

2023-08-02 14:56 UTC, djsmith85 commented on libs/importer/src/importers/protonpass/protonpass-json-importer.ts
> +
If we follow my suggestion to treat `vaults` as folders, then we should treat them as collection when importing in an organizational context
```suggestion
    if (this.organization) {
      this.moveFoldersToCollections(this.result);
    }
```

2023-08-02 14:56 UTC, djsmith85 commented on libs/importer/src/importers/protonpass/types/protonpass-json-type.ts
> +  state: number;
The state-property seems to indicate if an item is active (1) or in the trash (2). I'll ask product if we want to include trashed/deleted items on import.

2023-08-02 15:08 UTC, djsmith85 commented on apps/web/src/app/tools/import-export/import.component.html
> +    </ng-container>
Thanks for adding this. I've created a task to do the follow-up for the 1pux importer. I'll likely wait until your work has been merged.

2023-08-02 17:17 UTC, quexten commented on apps/web/src/app/tools/import-export/import.component.ts
> +    if (this.format === "protonpass" && file.type === "application/zip") {
Ah, good catch. I was testing on Firefox / fedora 38.

2023-08-02 17:27 UTC, quexten commented
> Adding support for the other item types ("creditCard", "note"). "alias" will currently stay unmapped.

I think notes are already supported. Credit cards were not in protonpass at the time I wrote the PR. I'll add them to the PR.

2023-08-02 17:33 UTC, djsmith85 commented
> > Adding support for the other item types ("creditCard", "note"). "alias" will currently stay unmapped.
> 
> I think notes are already supported. Credit cards were not in protonpass at the time I wrote the PR. I'll add them to the PR.

Notes on an item are imported, but not the specific type (note) which would map to a `secure note` in Bitwarden. Possibly this was also just recently added. Thank you for the contribution!!

2023-08-02 19:47 UTC, quexten commented
> > > Adding support for the other item types ("creditCard", "note"). "alias" will currently stay unmapped.
> > 
> > 
> > I think notes are already supported. Credit cards were not in protonpass at the time I wrote the PR. I'll add them to the PR.
> 
> Notes on an item are imported, but not the specific type (note) which would map to a `secure note` in Bitwarden. Possibly this was also just recently added. Thank you for the contribution!!

Actually secure notes not importing is a bug (apparently the call to `this.convertToNoteIfNeeded(cipher);` did not work).

I added tests for the note type now to make sure this is caught. Also credit card import should now work. Since Bitwarden doesn't have a pin (only CVV), I set it up such that a hidden field called "PIN" is created.

2023-08-02 19:48 UTC, quexten commented on libs/importer/src/importers/protonpass/types/protonpass-json-type.ts
> +  type: string;
Added this.

2023-08-02 20:07 UTC, quexten commented on libs/importer/spec/test-data/protonpass-json/protonpass.json.ts
> +  // not using types because Map<string, ProtonPassVault> does not convert to json
Thanks, this works :)

2023-08-02 20:18 UTC, quexten commented
> Extending the unit tests to be more extensive and include the new cases (folder/collection support, other item types

I added tests for notes / cards and collections/folders now.

2023-08-02 20:51 UTC, djsmith85 requested changes
@quexten Thank you for the speedy update of the PR

Only some really small nits

2023-08-02 20:51 UTC, djsmith85 commented on libs/importer/spec/protonpass-json-importer.spec.ts
> +    expect(creditCardCipher.card.code).toBe("333");
We should add an `expect` for the customfield with the `pin` from the CC here

2023-08-02 20:51 UTC, djsmith85 commented on libs/importer/src/importers/protonpass/protonpass-json-importer.ts
> +      const vault: ProtonPassVault = vaultEntry;
We don't necessarily need to re-assign the vaultEntry into vault and specify the type. The type is already present, because we know what the type of vaultEntry is.

2023-08-02 20:51 UTC, djsmith85 commented on libs/importer/src/importers/protonpass/protonpass-json-importer.ts
> +            const loginContent: ProtonPassLoginItemContent = item.data
I don't think we need to tell `loginContent` which type it is, if we are casting item.data.content into a specific type.

2023-08-02 20:51 UTC, djsmith85 commented on libs/importer/src/importers/protonpass/protonpass-json-importer.ts
> +            const creditCardContent: ProtonPassCreditCardItemContent = item.data
Unnecessary type assignment:  Same as with `loginContent`

2023-08-02 21:09 UTC, djsmith85 commented on libs/importer/src/importers/protonpass/types/protonpass-json-type.ts
> +  state: number;
My assumption was correct -> [ItemState](https://github.com/protonpass/android-pass/blob/01e33b74cf45ab5741cc623267e2911d899b6b4c/pass/domain/src/main/kotlin/proton/pass/domain/ItemState.kt#L21-L24)

We should extend the types to reflect the active/trashed state.

For now, it would be good to skip trashed items on import

2023-08-02 22:09 UTC, quexten commented on libs/importer/src/importers/protonpass/protonpass-json-importer.ts
> +      const vault: ProtonPassVault = vaultEntry;
Ah, you're right. After switching to Record<string,...> in ProtonPassJsonFile, Object.entries provides the correct type. It provided `any` when using Map<string,...> in my editor.

2023-08-02 22:27 UTC, quexten commented on libs/importer/src/importers/protonpass/types/protonpass-json-type.ts
> +  state: number;
Added an enum to represent this and they are skipped on import. A test case also added for this.

2023-08-02 22:30 UTC, quexten commented on apps/web/src/app/tools/import-export/import.component.ts
> +    if (this.format === "protonpass" && file.type === "application/zip") {
Actually unresolving this to make sure the new behaviour is as intended. I now made the check rather broad, checking for application/zip, application-x-zip-compressed, and for whether the filename ends in ".zip". Let me know if this is as intended.

2023-08-03 10:50 UTC, djsmith85 approved these changes, later dismissed
@quexten All changes are looking great and thank you so much for the quick turnaround on requested changes. A pleasure to work together on this.

I only found one little issue while testing this and have provided a fix.

I'm going to pass this on to QA and will let you know in which release your work gets included, once they've given the green light.

Thanks again for your contributions!

2023-08-16 14:16 UTC, djsmith85 commented
@quexten Had to fix a minor issue with the folder-assignment, but QA has tested everything and given their go.

The importer will be available in the `2023.9`-release.
Thanks again for you work on this!

2023-08-16 14:16 UTC, djsmith85 approved these changes

2023-08-16 14:17 UTC, merged

2023-09-08 21:09 UTC, djsmith85 commented
Hi @nyakojiru, roughly in 2 weeks time

2023-09-20 00:15 UTC, Arcdub commented
Hi @djsmith85 it's been 2 weeks 😃 any update?

2023-09-20 08:25 UTC, djsmith85 commented
Hi @Arcdub, to get notified when new releases are out, please have a look at https://bitwarden.com/help/releasenotes/#release-announcements