Adding UUID under the secret name on secrets list
bitwarden/clients pull request #5773
Opened 2023-07-10 19:35 UTC by cd-bitwarden

## Type of change

```
- [ ] Bug fix
- [ x ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

**bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.html** - visual changes of adding the UUID under the secret name and having clicking the copy button trigger the copy UUID event.

**bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.ts** - Adding the logic for what happens when you click the copy UUID button

## Screenshots

![image](https://github.com/bitwarden/clients/assets/106776772/ca427388-4a16-4416-8899-af08c3a9a8d2)
## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-07-11 19:23 UTC, Thomas-Avery requested changes

2023-07-11 19:23 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.html
> +              ></i>
Let's use the `bitIconButton` here, so this can be navigated to via the keyboard.

https://62a88a6de5b807fa98886113-tygewhzfbq.chromatic.com/?path=/docs/component-library-icon-button--docs&globals=backgrounds.grid:!false

Based on the FIGMA the title and aria-label should be `Copy UUID`

2023-07-11 19:23 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.ts
> +    );
We don't need to await anything since we are passing the `id` directly.

Should be able to just use what we do for `copySecretName`.

To stay consistent with the FIGMA label for the button, the toast should read `UUID copied`. Note will need to add an i18n entry for this.

```
    platformUtilsService.copyToClipboard(id);
    platformUtilsService.showToast(
      "success",
      null,
      i18nService.t("valueCopied", i18nService.t("uuid"))
    );
```

2023-07-13 21:39 UTC, Thomas-Avery requested changes
One minor thing and should be good to go.

2023-07-13 21:39 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.html
> +                [attr.aria-label]="'copyUuid' | i18n"
```
size="small"
```

The padding seems a little large here compared to the FIGMA. 

What do you think about using the BitIconButton size property here?

2023-07-17 18:44 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.html
> +                [attr.aria-label]="'copyUuid' | i18n"
Done, thanks :)

2023-07-17 22:31 UTC, Thomas-Avery submitted a review, later dismissed
LGTM

2023-08-02 16:40 UTC, cd-bitwarden commented
@Thomas-Avery QA found a spot that was missing the auto focus so I added it 😄

2023-08-02 17:00 UTC, Thomas-Avery approved these changes
Looks good

2023-08-04 20:18 UTC, merged