Auth/[PM-1260- Existing User - Login with Trusted Device (Flow 2)
bitwarden/clients pull request #5775
Opened 2023-07-10 21:22 UTC by JaredSnider-Bitwarden

## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-07-11 12:17 UTC, coroiu commented on libs/common/src/auth/login-strategies/login.strategy.spec.ts
> +    it("for trusted device encryption, it persists a device key if it exists on login", async () => {
nit: 
```suggestion
    it("persists a device key for trusted device encryption when it exists on login", async () => {
```

2023-07-11 12:44 UTC, coroiu commented
Found multiple bugs: 

**1. Client is not able to decrypt vault items after logout/login with trusted device**
![image](https://github.com/bitwarden/clients/assets/2285588/9f9e898b-9f9f-41c5-b8cf-cc1fce3981f4)

Reproduction steps:

1. Login with an SSO user that has never logged in before (to cause auto enrollment)
2. Trust device and continue to vault
3. Create a new vault item with name and some notes (or something)
4. Log out
5. Log back in again 
6. Observe that vault item cannot be decrypted, console shows log in screenshot above

**2. Seems like organization keys are not properly set**
![image](https://github.com/bitwarden/clients/assets/2285588/f99e5213-18ae-45ec-a23e-4dd9d6d0eb73)


1. Login with an SSO user that has never logged in before (to cause auto enrollment)
2. Trust device and continue to vault
3. Create a new vault item with name and some notes (or something)
4. Log out
5. Log in with admin and confirm new user into organization
6. Log out
7. Log back in with the new SSO user
8. Observe that the user is not a part of the organization, but client cannot decrypt and complains that private key is missing

2023-07-11 14:02 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/login-strategies/sso-login.strategy.ts
> +    if (!deviceKey || !encDevicePrivateKey || !encUserKey) {
TBH, I find the first version easier to read without missing the negation.

2023-07-11 14:05 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/device-trust-crypto.service.implementation.ts
> +      console.warn("TDE: Failed to decrypt user key with device key. Removing device key.", e);
I wasn't sure if this was allowed, but Jake had mentioned that we had this type of logic in the crypto service elsewhere so this was fine. I can remove if there is a hard rule against any debug warnings for certain error states in prod.

2023-07-11 14:06 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/models/response/user-decryption-options/user-decryption-options.response.ts
> +}
It was just the shortest way I could indicate they were interfaces.

2023-07-11 14:09 UTC, JaredSnider-Bitwarden commented on libs/common/src/platform/services/state.service.ts
> +    // Must manually instantiate the SymmetricCryptoKey class from the JSON object
It is not deserialized into an instance of the `SymmetricCryptoKey` class when it comes out of state. The top level `Account.fromJSON()` does not run which leaves the object as:

```TypeScript
{
    base64: "..."
}
```

Which cannot be used for decryption.

2023-07-11 14:17 UTC, JaredSnider-Bitwarden commented on libs/common/src/platform/models/domain/account-keys.spec.ts
> +// TODO: add device key to tests
Argh, yes! Thank you for catching that!

2023-07-11 14:25 UTC, coroiu commented on libs/common/src/auth/services/device-trust-crypto.service.implementation.ts
> +      console.warn("TDE: Failed to decrypt user key with device key. Removing device key.", e);
If we want the logging in prod why not use `LogService` ?

2023-07-11 14:26 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/device-trust-crypto.service.implementation.ts
> +      console.warn("TDE: Failed to decrypt user key with device key. Removing device key.", e);
That's a fair point. For now, I'm going to remove it.

2023-07-11 22:43 UTC, JaredSnider-Bitwarden commented
> Found multiple bugs:
> 
> **1. Client is not able to decrypt vault items after logout/login with trusted device** ![image](https://user-images.githubusercontent.com/2285588/252665745-9f9e898b-9f9f-41c5-b8cf-cc1fce3981f4.png)
> 
> Reproduction steps:
> 
> 1. Login with an SSO user that has never logged in before (to cause auto enrollment)
> 2. Trust device and continue to vault
> 3. Create a new vault item with name and some notes (or something)
> 4. Log out
> 5. Log back in again
> 6. Observe that vault item cannot be decrypted, console shows log in screenshot above


This has been resolved:

https://github.com/bitwarden/clients/assets/116684653/3693ea33-1228-40b6-8835-1dfbc5952ef4


> **2. Seems like organization keys are not properly set** ![image](https://user-images.githubusercontent.com/2285588/252666071-f99e5213-18ae-45ec-a23e-4dd9d6d0eb73.png)
> 
> 1. Login with an SSO user that has never logged in before (to cause auto enrollment)
> 2. Trust device and continue to vault
> 3. Create a new vault item with name and some notes (or something)
> 4. Log out
> 5. Log in with admin and confirm new user into organization
> 6. Log out
> 7. Log back in with the new SSO user
> 8. Observe that the user is not a part of the organization, but client cannot decrypt and complains that private key is missing

This has been partially resolved. 

https://github.com/bitwarden/clients/assets/116684653/9a010fe1-cc32-445a-9f0d-9951b21f7ce2

Users no longer get errors for the private key missing, but the user is not getting the organization ciphers for some reason.

2023-07-11 22:44 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/models/response/user-decryption-options/user-decryption-options.response.ts
> +}
I left this open as I'm not sure if this is an issue or not.

2023-07-12 14:27 UTC, coroiu approved these changes
🔥

2023-07-12 14:47 UTC, justindbaur requested changes
Very good stuff, one tiny request.

2023-07-12 14:47 UTC, justindbaur commented on apps/browser/src/background/service-factories/devices-api-service.factory.ts
> +    "DevicesApiService",
```suggestion
  cache: { devicesApiService?: DevicesApiServiceAbstraction } & CachedServices,
  opts: DevicesApiServiceInitOptions
): Promise<DevicesApiServiceAbstraction> {
  return factory(
    cache,
    "devicesApiService",
```

2023-07-12 14:49 UTC, justindbaur approved these changes

2023-07-12 16:14 UTC, merged