for secrets manager show SM title
bitwarden/clients pull request #5780
Opened 2023-07-11 02:45 UTC by cd-bitwarden

## Type of change

```
- [ ] Bug fix
- [ x ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

The page title should change from Bitwarden Web Vault to Bitwarden Secrets Manager if they are inside of secrets manager
## Code changes

apps/web/src/app/core/router.service.ts - check if the url contains SM , if so show in the title Bitwarden Secrets Manager
apps/web/src/locales/en/messages.json - adding to messages for "Bitwarden Secrets Manager" and "Bitwarden Web Vault"

- **file.ext:** Description of what was changed and why

## Screenshots

![image](https://github.com/bitwarden/clients/assets/106776772/570db629-bdce-4945-b29c-f6de67115a8a)
## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-07-11 14:48 UTC, djsmith85 requested changes

2023-07-11 14:48 UTC, djsmith85 commented on apps/web/src/locales/en/messages.json
> +    "message": "$APP_NAME$",
The key should be changed if we changing context for the translators.

2023-07-11 14:48 UTC, djsmith85 commented on apps/web/src/app/core/router.service.ts
> +
If this is the only place we use the `pageTitle` couldn't we just use `i18nService.t("bitWebVault")` and `i18nService.t("bitSecretsManager")` directly. Why use a placeholder if we have to have this conditional anyway

2023-07-13 13:42 UTC, cd-bitwarden commented on apps/web/src/app/core/router.service.ts
> +
Yeah I agree, we can do it that way instead 👍

2023-07-13 17:56 UTC, djsmith85 commented on apps/web/src/locales/en/messages.json
> +    "message": "$APP_NAME$",
@cd-bitwarden If the meaning of a message changes and we need to ensure that the translations are correct, then we need to change the key "pageTitle" and everywhere it is used. This essentially deletes all translations with key "pageTitle" and translators get a notification about a new string that needs translation.

If based on the other comment below, we can get rid of "pageTitle" even better

2023-07-13 19:49 UTC, cd-bitwarden commented on apps/web/src/locales/en/messages.json
> +    "message": "$APP_NAME$",
It looks like one place uses the pageTitle, so I reverted my changes to that message, and instead use the simple bitWebVault and bitSecretsManager instead 👍

2023-07-14 12:57 UTC, djsmith85 approved these changes
Changes are looking good.

2023-07-14 12:59 UTC, djsmith85 commented
@cd-bitwarden: Should we remove the `pagetitle` completely and replace it https://github.com/bitwarden/clients/blob/61d5b2df9c43c048c772c4d72c1c64a047a9b432/apps/web/src/app/layouts/navbar.component.html#L3 with `'bitWebVault'` ?

2023-07-18 19:50 UTC, Thomas-Avery approved these changes
Looks good.

2023-07-18 20:18 UTC, djsmith85 approved these changes

2023-07-20 10:30 UTC, Hinton approved these changes
Please add the jira ticket in the PR name.

2023-07-27 00:53 UTC, merged