[PM-2804] Migrate Send List to Component Library
bitwarden/clients pull request #5796
Opened 2023-07-12 15:11 UTC by aj-rosado

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Update the send page to use the Component Library, updating the list, headers, no items and search.
As discussed on the task with @danielleflinn we will keep the filters layout for now.

## Code changes

- **loose-components.module.ts:** Added `NoItemsModule` and `SearchModule` that will be used by the Send
- **apps/web/src/app/tools/send/send.component.html:** Updated items to use the ComponentLibrary and TailWind classes
- **libs/angular/src/tools/send/send.component.ts:** Changed the icon when there are no items to list
- **apps/web/src/locales/en/messages.json:** Added new Messages for the no-items screen

## Screenshots
**Old Layout:**
<img width="1205" alt="Screenshot 2023-07-12 at 16 07 20" src="https://github.com/bitwarden/clients/assets/109146700/bee58e09-0ab5-4a6d-9915-f554a83d09fd">
<img width="1205" alt="Screenshot 2023-07-12 at 16 07 28" src="https://github.com/bitwarden/clients/assets/109146700/8c0a86da-e7e7-416b-af2d-f06d1a5ff517">
<img width="1205" alt="Screenshot 2023-07-12 at 16 07 39" src="https://github.com/bitwarden/clients/assets/109146700/5f985f8e-3738-4800-b38c-04938f72a8f1">

**New Light Layout:**
<img width="1205" alt="Screenshot 2023-07-12 at 15 46 54" src="https://github.com/bitwarden/clients/assets/109146700/010aa8a2-a0c4-43b3-9226-b994308ad83d">
<img width="1205" alt="Screenshot 2023-07-12 at 15 47 05" src="https://github.com/bitwarden/clients/assets/109146700/464b5ffb-1ed3-4192-9b61-efa4fbf41950">
<img width="1205" alt="Screenshot 2023-07-12 at 15 47 15" src="https://github.com/bitwarden/clients/assets/109146700/719a291f-36fb-4459-be7c-1a10e96a717a">

**New Dark Layout:**
<img width="1195" alt="Screenshot 2023-07-12 at 15 44 48" src="https://github.com/bitwarden/clients/assets/109146700/6efcdc56-2c91-4a83-b496-d647912520df">
<img width="1205" alt="Screenshot 2023-07-12 at 15 45 03" src="https://github.com/bitwarden/clients/assets/109146700/9e2dcdbd-9921-42f5-b57d-90f14a797e23">
<img width="1195" alt="Screenshot 2023-07-12 at 15 44 41" src="https://github.com/bitwarden/clients/assets/109146700/290a1edb-05a4-4460-91c9-9bd6811cb27d">

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-07-12 15:21 UTC, danielleflinn commented on apps/web/src/app/tools/send/send.component.html
> +              <button type="button" bitLink href="#" appStopClick appStopProp (click)="editSend(s)">
I think this should be a [icon-button](https://components.bitwarden.com/?path=/docs/component-library-icon-button--docs) like we have in the Vault items table. Can you update?

2023-07-12 20:17 UTC, willmartian requested changes
Looking good! A few comments:

2023-07-12 20:17 UTC, willmartian commented on apps/web/src/app/tools/send/send.component.html
> +              <button type="button" bitLink href="#" appStopClick appStopProp (click)="editSend(s)">
`href` not necessary:

```suggestion
              <button type="button" bitLink appStopClick appStopProp (click)="editSend(s)">
```

2023-07-12 20:17 UTC, willmartian commented on apps/web/src/app/tools/send/send.component.html
> +            <th bitCell>{{ "options" | i18n }}</th>
If in scope, it would be nice if the columns were sortable: [`bitSortable` and `TableDataSource`](https://components.bitwarden.com/?path=/docs/component-library-table--docs#data-source)

2023-07-12 21:22 UTC, danielleflinn commented on apps/web/src/app/tools/send/send.component.html
> +            <th bitCell>{{ "options" | i18n }}</th>
If @aj-rosado feels it is in scope of this ticket to make the columns sortable, feel free. But if not, the Vault team has an item in the backlog that will handle updating the page to include sort-ability

2023-07-18 10:41 UTC, Hinton commented on apps/web/src/app/tools/send/send.component.ts
> +  `;
Please move the svg to it's own file, and run it through a minifier https://jakearchibald.github.io/svgomg/

2023-07-18 10:41 UTC, Hinton commented on apps/web/src/app/tools/send/send.component.html
> +            >
@willmartian Do we expect people to need css classes for the no-item component?

2023-07-18 10:41 UTC, Hinton commented on apps/web/src/app/shared/loose-components.module.ts
> +    SendComponent,
This import should be moved to the app.module.

2023-07-18 10:41 UTC, Hinton commented on apps/web/src/app/tools/send/send.component.html
>            </small>
We need to do something about this, but might be out of scope for now. We're essentially abusing the `appApiAction` to catch errors and to show a spinner. The spinner could be handled by just checking if `actionPromise` is null, but that would silently swallow errors.

2023-07-18 10:41 UTC, Hinton commented on apps/web/src/app/tools/send/send.component.html
> +              <button type="button" bitLink appStopClick appStopProp (click)="editSend(s)">
The row is already clickable.

2023-07-18 13:59 UTC, aj-rosado commented on apps/web/src/app/tools/send/send.component.html
> +            >
As discussed with @danielleflinn it was missing a little bit of space between title and image. It may depend on the svg, some may have more empty space than others

2023-07-18 14:00 UTC, aj-rosado commented on apps/web/src/app/tools/send/send.component.html
>            </small>
I will open a tech-debt task for this

2023-07-18 14:58 UTC, danielleflinn commented on apps/web/src/app/tools/send/send.component.html
> +            <th bitCell>{{ "options" | i18n }}</th>
Awesome! Can make sure the filled arrow up icon is indicating the default alphabetical sort order to the end user? See https://components.bitwarden.com/?path=/story/component-library-table--data-source

2023-07-18 15:05 UTC, aj-rosado commented on apps/web/src/app/tools/send/send.component.html
> +            <th bitCell>{{ "options" | i18n }}</th>
@danielleflinn set the name as default and updated the screenshots!

2023-07-19 12:15 UTC, Hinton commented on apps/web/src/app/tools/send/send.component.html
> +            >
That seems a bit annoying. Would be nice if we could either trim all svg and add the padding to the base element, or increase the height of this svg to not need it.

As it is, if we ever want to re-use that svg image we now need to remember to apply the exact same padding otherwise it looks inconsistent.

2023-07-19 17:06 UTC, danielleflinn commented on apps/web/src/app/tools/send/send.component.html
> +            >
Looks good to me thanks!

2023-07-20 09:40 UTC, Hinton commented on apps/web/src/app/tools/send/send.component.html
> +            >
Perfect thanks!

2023-07-20 09:53 UTC, Hinton commented on apps/web/src/app/tools/send/send.component.html
> +                size="small"
We had some discussions in slack regarding icon sizes, I believe it settled on changing these to regular size but not sure if that work should be done afterwards to keep it consistent between the vault page and send.

2023-07-21 17:43 UTC, danielleflinn commented on apps/web/src/app/tools/send/send.component.html
> +                size="small"
Let's go ahead and update them now to the regular size. Thanks for calling this out @Hinton

2023-07-24 12:07 UTC, aj-rosado commented on apps/web/src/app/tools/send/send.component.html
> +                size="small"
Updated the layout and the screenshots

2023-07-24 14:52 UTC, danielleflinn submitted a review, later dismissed

2023-07-24 14:58 UTC, Hinton approved these changes
LGTM, thanks for iterating on this.

2023-07-24 16:24 UTC, willmartian submitted a review, later dismissed
Looks good to me as well! Thank you for your efforts 🫡

2023-07-24 16:38 UTC, djsmith85 approved these changes

2023-07-27 15:39 UTC, djsmith85 approved these changes

2023-07-31 10:58 UTC, Hinton approved these changes

2023-07-31 11:04 UTC, merged