[PM-1339] Allow Rotating Device Keys
bitwarden/clients pull request #5806
Opened 2023-07-13 02:01 UTC by justindbaur

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Add client side components for rotating the trusted device keys of the current device.

Related server PR: bitwarden/server#3096

## Code changes

- **change-password.component.ts:** Refactor to deconstruct the tuple to its named elements and add a call to the `DeviceTrustCryptoService` to facilitate the rotation of the current device keys so that it can stay trusted.
- **update-devices-trust.request.ts:** Added API models for the request body that is sent to the server to rotate a users devices trusted device keys.
- **protected-device.response.ts:** Added a model that returns device information including it's more sensitive parts. 
- **device-trust-crypto.service.implementation.ts:** Added logic for getting and rotating the keys of the current users device so that once logged out they can re-auth with SSO and still keep trust.
- **device-trust-crypto.service.spec.ts:** Added test asserting expected behavior.

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-07-17 16:19 UTC, djsmith85 requested changes
@justindbaur 
Could you please move the following files into auth-owned folders:
`libs/common/src/abstractions/devices/devices-api.service.abstraction.ts`
`libs/common/src/abstractions/devices/requests/update-devices-trust.request.ts`
`libs/common/src/abstractions/devices/responses/protected-device.response.ts`
`libs/common/src/services/devices/devices-api.service.implementation.ts`
and likely also 
`apps/web/src/app/settings/change-password.component.ts`, but please verify with @jlf0dev on the last one

2023-07-17 23:37 UTC, JaredSnider-Bitwarden reviewed
Excellent work on this! Few minor questions.

2023-07-17 23:37 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/settings/change-password.component.ts
> +    const [newUserKey, newProtectedUserKey] = await this.cryptoService.makeUserKey(masterKey);
Nit pick (non blocking): `newProtectedUserKey` is generic, but we can be more clear by being a tiny bit more verbose with something like `masterKeyEncUserkey`

2023-07-17 23:37 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/settings/change-password.component.ts
>      const privateKey = await this.cryptoService.getPrivateKey();
Nit pick (non blocking): `userPrivateKey` ?

2023-07-17 23:37 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/settings/change-password.component.ts
> +    const [newUserKey, newProtectedUserKey] = await this.cryptoService.makeUserKey(masterKey);
Love the clarity you've added here with the array destructuring and `new` prefix!

2023-07-17 23:37 UTC, JaredSnider-Bitwarden commented on libs/common/src/abstractions/devices/responses/protected-device.response.ts
> +   * Intended to be the users symmetric key that is encrypted in some form, the current way to encrypt this is with
Nit: `encrypt` --> `decrypt`

2023-07-17 23:37 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/device-trust-crypto.service.implementation.ts
> +    // TODO: For device management, allow this method to take an array of device ids that can be looped over and individually rotated
Legend.

2023-07-17 23:37 UTC, JaredSnider-Bitwarden commented on libs/common/src/abstractions/devices/responses/protected-device.response.ts
> +    this.encryptedPublicKey = this.getResponseProperty("encryptedPublicKey");
These two keys should be converted to `EncString` here, right? 

See `TrustedDeviceUserDecryptionOptionResponse` for what I did previously (based on seeing this pattern elsewhere).

2023-07-17 23:37 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/device-trust-crypto.service.implementation.ts
> +      new EncString(currentDeviceKeys.encryptedPublicKey),
Note: if you convert the `ProtectedDeviceResponse` to create `EncString` then you won't need to do this here.

2023-07-17 23:37 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/device-trust-crypto.service.implementation.ts
> +  async rotateDevicesTrust(newUserKey: UserKey, masterPasswordHash: string): Promise<void> {
Double checked logic against our tech breakdown, and it looks perfect!

2023-07-17 23:37 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/device-trust-crypto.service.spec.ts
> +    // TOOD Add tests for decryptUserKeyWithDeviceKey when types are available
This comment should be removed. I think I already did once.

2023-07-17 23:37 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/device-trust-crypto.service.spec.ts
Awesome work testing the new function and key rotation logic!

However, you might want to review the https://contributing.bitwarden.com/contributing/testing/unit/naming-conventions/ for the test names' adherence to the latest naming conventions. I just learned about those myself recently!

2023-07-17 23:37 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/device-trust-crypto.service.spec.ts
> +            data.fill(17, 0, 1);
Nit: you could put 17 into a named variable for easier testing clarity vs testing for magic num 17 later on

2023-07-17 23:37 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/device-trust-crypto.service.spec.ts
> +          devicesApiService.getDeviceKeys.mockImplementation((deviceIdentifier, secretRequest) => {
TIL about `mockImplementation`! TY!

2023-07-19 11:57 UTC, justindbaur commented on libs/common/src/abstractions/devices/responses/protected-device.response.ts
> +   * Intended to be the users symmetric key that is encrypted in some form, the current way to encrypt this is with
Are you sure about that? This is a copy of the comment on server. This references the public key which is only used for encryption.

2023-07-19 12:36 UTC, justindbaur commented on libs/common/src/auth/services/device-trust-crypto.service.spec.ts
> +    // TOOD Add tests for decryptUserKeyWithDeviceKey when types are available
Maybe something weird with the merge. Removed it.

2023-07-19 15:15 UTC, justindbaur commented on libs/common/src/auth/services/device-trust-crypto.service.spec.ts
Updated the names, I wasn't totally sure how to name my "inner" describe, I feel like it doesn't read quite as well now the the `when` condition coming after but I did my best and let me know if you have any ideas.

2023-07-19 18:23 UTC, JaredSnider-Bitwarden approved these changes
Awesome work!

2023-07-19 18:23 UTC, JaredSnider-Bitwarden commented on libs/common/src/abstractions/devices/responses/protected-device.response.ts
> +   * Intended to be the users symmetric key that is encrypted in some form, the current way to encrypt this is with
Oh, I misread this. I'm sorry!

2023-07-20 15:01 UTC, djsmith85 approved these changes
Approving the file moves I requested!

2023-07-20 17:04 UTC, merged