829-A11y fixing H3 complaint aside added and h3 turned into header
bitwarden/clients pull request #5853
Opened 2023-07-18 22:32 UTC by cd-bitwarden

## Type of change

```
- [ x ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Stop A11y from complaining about H3 tag, instead update component to not use H3 since it doesn't make sense
## Code changes

libs/angular/src/components/callout.component.html - changing div to aside, and h3 to header to maintain look but stop A11y from complaining

- **file.ext:** Description of what was changed and why

## Screenshots

![image](https://github.com/bitwarden/clients/assets/106776772/a6c0931f-64e1-4d82-8ec0-c8b2407cb4db)

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-07-19 18:26 UTC, willmartian requested changes

2023-07-19 18:26 UTC, willmartian commented on libs/angular/src/components/callout.component.html
The actual changes look good, but this is the wrong component. The callout used in SM is the `bit-callout` component, which [is part of the CL](https://github.com/bitwarden/clients/blob/master/libs/components/src/callout/callout.component.html). 

(If you want to change `app-callout` as well, make sure to double check this change doesn't introduce any visual diffs. At a quick glance, you would need to update any css like `h3.callout-heading`)

2023-07-20 15:11 UTC, cd-bitwarden commented
![image](https://github.com/bitwarden/clients/assets/106776772/6079ba49-a50c-48bd-a01f-3d6b896bd4cc)

2023-07-21 17:30 UTC, willmartian approved these changes
Looks good! Thanks 💯

2023-07-24 19:39 UTC, willmartian requested changes
Hey @cd-bitwarden,

Was chatting with @danielleflinn about this ticket, and she pointed out that `aside` elements also need a unique id on their label/heading. (good catch, thanks!)

Here is [an example](https://github.com/bitwarden/clients/blob/master/libs/components/src/dialog/directives/dialog-title-container.directive.ts#L11) of how we do so in `bit-dialog`. We should put an `id` on the `header`, and then reference it with `aria-labelledby` on the `aside`. 

Please find more info here: https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/complementary.html

2023-07-25 19:37 UTC, willmartian approved these changes
LGTM

2023-08-16 21:19 UTC, cd-bitwarden commented
Closing PR because Will created a PR that has these changes

2023-08-17 20:29 UTC, willmartian commented
I think this one was closed by mistake. Reopening! 🌈

2023-08-19 13:39 UTC, merged