[AC-1486] Feature: Secrets Manager billing - round 2
bitwarden/clients pull request #5854
Opened 2023-07-19 00:02 UTC by eliykat

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-08-02 12:33 UTC, differsthecat approved these changes
This looks good for Vault, the only change I see for us is a service name change in SyncService.

2023-08-03 12:26 UTC, MGibson1 requested changes
These are relatively small issues. Should be quick to fix, but feel free to barrel over my review if needed.

2023-08-03 12:26 UTC, MGibson1 commented on libs/common/src/platform/misc/utils.ts
> +    const msPerDay = ms * seconds * minutes * hours;
Why allocate and calculate this every time the method is called? It's a constant (86400000)
```suggestion
    const msPerDay = 86400000;
```

2023-08-03 12:26 UTC, MGibson1 commented on libs/common/src/platform/misc/utils.ts
> +    return Math.max(0, Math.round(diffTime / msPerDay));
likely this should be a ceiling. I'm not sure how the deactivation will work, but it probably doesn't use a round to determine if we should deactivate an account 😉

2023-08-03 15:46 UTC, MGibson1 commented on libs/common/src/platform/misc/utils.ts
> +    return Math.max(0, Math.round(diffTime / msPerDay));
yup, I had the direction wrong in my head! thanks

2023-08-03 15:47 UTC, MGibson1 approved these changes

2023-08-03 16:23 UTC, cyprain-okeke commented on apps/web/src/app/billing/organizations/secrets-manager/sm-subscribe.component.html
> +                | i18n : (monthlyCostPerServiceAccount | currency : "$")
change monthlyCostPerServiceAccount to monthlyCostPerServiceAccounts

2023-08-04 09:20 UTC, r-tome approved these changes
LGTM

2023-08-04 09:20 UTC, r-tome commented on apps/web/src/app/billing/organizations/secrets-manager/sm-subscribe.component.html
> +                | i18n : (monthlyCostPerServiceAccount | currency : "$")
Its the value for a singular service account

2023-08-04 13:26 UTC, cyprain-okeke approved these changes
it looks great

2023-08-04 21:52 UTC, differsthecat approved these changes

2023-08-04 21:52 UTC, merged