[PM-2452] Popover Component
bitwarden/clients pull request #5889
Opened 2023-07-24 22:58 UTC by rr-bw

- setup popover component template and basic story
- add a11y features

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-08-10 04:24 UTC, willmartian requested changes
Hey @rr-bw, great initial work here!

One general note: The popover component will not only be used with the `?` icon button (it is just a common usage). Rather than tightly coupling this to an individual button, I would follow the approach in `<bit-menu>` and `[bitMenuTargetFor]`: https://github.com/bitwarden/clients/blob/master/libs/components/src/menu/menu-trigger-for.directive.ts

2023-08-10 04:24 UTC, willmartian commented on libs/components/src/tw-theme.css
> +}
In addition to Oscar's suggestion on Slack, another approach that avoids using `@apply` is [arbitrary group modifiers](https://tailwindcss.com/docs/hover-focus-and-other-states#arbitrary-groups).

```
panelClass: ['group', 'bit-popover-right']
```

```html
  <!-- Right popover arrow -->
  <div class="group-[.bit-popover-right]:tw-visible tw-invisible ..."></div>
  
  <!-- Left popover arrow -->
  <div class="group-[.bit-popover-left]:tw-visible tw-invisible ..."></div>
```

2023-08-10 04:44 UTC, willmartian commented
@bitwarden/dept-design We might need more positions that cover when popover targets are in a corner of the viewport. As an example, [Shoelace](https://shoelace.style/components/tooltip#placement) uses `top-start`, `top`, `top-end`, `right-start`, `right`... etc. 

https://github.com/bitwarden/clients/assets/17113462/12a2ce77-f437-4414-941d-700e28020402

2023-08-10 13:45 UTC, danielleflinn commented
@willmartian great call out. I will updated the Figma docs to include those additional positions.

2023-08-21 20:49 UTC, willmartian requested changes
The popover does not gracefully handle overflowing content. We should be able to fix this with a mixture of Tailwind's [word break](https://tailwindcss.com/docs/word-break) and [text overflow](https://tailwindcss.com/docs/text-overflow) utilities. 

### Header:

<img width="491" alt="Screenshot 2023-08-21 at 4 37 46 PM" src="https://github.com/bitwarden/clients/assets/17113462/a55648e7-5568-476f-a053-2f9a1dd3297c">

### Body content:

<img width="491" alt="Screenshot 2023-08-21 at 4 39 15 PM" src="https://github.com/bitwarden/clients/assets/17113462/236a7e74-cb21-46c6-abe2-4772c2e08031">

2023-08-21 20:49 UTC, willmartian commented on libs/components/src/popover/popover.component.html
> +          <h3 class="tw-mb-0 tw-font-semibold">{{ header }}</h3>
I don't think `h3` is accurate here, semantically.

[Opinions are split ](https://stackoverflow.com/questions/60504268/which-header-should-we-choose-for-modal-dialogs/60504771#60504771)on the best heading level for dialogs, whether it should be `h1` since it is outside of the normal page flow or `h2` since each page should have a single `h1`. 

Regardless, we shouldn't use an `h3` here, since it is only valid if an `h2` exists on the page, which might not always be the case.

Lets update this to be a `h2` and the outermost div to be a `section` element.

2023-08-21 20:49 UTC, willmartian commented on libs/components/src/popover/popover.module.ts
@rr-bw After seeing [Angular's recommendation for library authors](https://angular.io/guide/standalone-components#standalone-components-for-library-authors), I went back on my opinion here just a bit and added a module _of_ standalone components.

2023-09-13 21:55 UTC, danielleflinn approved these changes

2023-09-20 20:14 UTC, willmartian requested changes
I don't think functionality relating to walkthrough/tours should be in the CL. That seems like a specific application of the popover component, rather than a variant that needs to be built in. For an example of what I mean, [see](https://github.com/bitwarden/clients/blob/master/bitwarden_license/bit-web/src/app/secrets-manager/layout/org-switcher.component.html) Secret Manager's `org-switcher` component. It adds functionality *on top of*  the CL's `nav-group` component through composition. 

Additionally, the `WalkthroughService` approach seems a bit too inflexible. A dev might need to:
- Customize the number of buttons or button text. 
- Control the order of the popovers. Currently, popup order is tied to appearance in the DOM. What if a dev needs to skip a step or skip to the end?

Let us consider the alternative--if a dev needed to wire up a walkthrough from scratch, what would be required?

```html
      <button
        type="button"
        [bitPopoverTriggerFor]="myPopover1"
        #popTrigger1="popoverTrigger"
      >...</button>
      <button
        type="button"
        [bitPopoverTriggerFor]="myPopover2"
        #popTrigger2="popoverTrigger"
       >...</button>

      <bit-popover [header]="'Popover 1'" #myPopover1>
        <p>Foobar 1</p>
        <button 
          bitButton 
          buttonType="primary" 
          type="button"
          (click)="popTrigger2.openPopover()"
          (click)="popTrigger1.closePopover()"
        >
          Next
        </button>
      </bit-popover>

      <bit-popover [header]="'Popover 2'" #myPopover2>
        <p>Foobar 2</p>
        <button 
          bitButton 
          buttonType="secondary" 
          type="button"
          (click)="popTrigger1.openPopover()"
          (click)="popTrigger2.closePopover()"
        >
          Back
        </button>
      </bit-popover>
```

While this does require the dev to manually create the buttons, I don't think it is so bad. Plus, it is entirely flexible. If we did want to consolidate that into a reusable component, I could *maybe* see something like:

```html
<bit-popover>
  ...
  <tour-buttons 
    previous="popTrigger1"
    current="popTrigger2"
    next="popTrigger3"
  ></tour-buttons>
</bit-popover>
```

Which would not require a service, wrapper component, or the popover component knowing anything about walkthroughs. 

All that being said, lets limit this PR to not include any walkthrough specific functionality at this time.

2023-09-26 18:47 UTC, rr-bw commented
@willmartian Make sense. I reverted back to no Walkthrough mode. Let me know what you think.

2023-09-27 19:56 UTC, willmartian commented on libs/components/src/popover/popover-trigger-for.directive.ts
> +  isOpen = false;
@jtouchstonebw mentioned the potential need to open a popover when the page first loads. 

Could we make this an input and perhaps rename it to something like `popoverOpen`? 

```html
<button bitPopoverTriggerFor="myPopover" [popoverOpen]="true">
```

We can then use a setter to call `openPopover` and `closePopover` whenever the input changes.

2023-09-27 19:56 UTC, willmartian commented on libs/components/src/popover/popover-trigger-for.directive.ts
> +  isOpen = false;
(As always, lmk if you would approach that in a different way!)

2023-10-06 20:12 UTC, rr-bw commented on libs/components/src/popover/popover-trigger-for.directive.ts
> +  isOpen = false;
@willmartian I had some trouble with the setter method and found I had to use `ngAfterViewInit()`. Either way, you can now set the popover to be initially open on page load.

2023-10-13 03:11 UTC, willmartian approved these changes
LGTM 💯 

Thanks for your work on this and for iterating with me.

2023-10-23 14:09 UTC, danielleflinn approved these changes

2023-10-23 16:22 UTC, merged