[PM-3169] Login decryption options in extension popup
bitwarden/clients pull request #5909
Opened 2023-07-27 14:37 UTC by coroiu

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-08-02 18:33 UTC, JaredSnider-Bitwarden approved these changes
Tested all PM-3169 scenarios locally, and all the issues were resolved. Required fixing the TDE Login with MP flow w/ a small edit to the `LockGuard`, but overall, this was an incredibly well done refactor of our guard logic. Thank you for your work on this!

2023-08-03 12:10 UTC, justindbaur requested changes
A few questions and a few change requests but great work (to both you and Andreas).

2023-08-03 12:10 UTC, justindbaur commented on libs/angular/src/auth/components/sso.component.ts
> +          await this.stateService.setUserSsoOrganizationIdentifier(ssoOrganizationIdentifier);
Do I have these steps right:
1. Save organization identifier into state
2. Navigate to login decryption options
3. Pull identifier from state
4. Use it to check the enroll status of the user
5. Never delete that information

If that is the case can we pass that information to the next page via query parameter?

2023-08-03 12:10 UTC, justindbaur commented on libs/common/src/platform/abstractions/state.service.ts
> +    value: Partial<string>,
Why the `Partial<string>`? TypeScript seems to just resolve it to `string`. https://www.typescriptlang.org/play?#code/C4TwDgpgBASlC8UAKBDATsAligNgHgGdg1MA7AcwD4BuIA

2023-08-04 21:17 UTC, justindbaur approved these changes
Thank you for all the changes and our discussion. Looks great.

2023-08-04 21:17 UTC, justindbaur commented on libs/angular/src/auth/components/base-login-decryption-options.component.ts
> +        // TODO: discuss how this doesn't make any sense to show here
Just be sure to have that discussion.

2023-08-04 21:55 UTC, merged