Trusted Device Encryption feature
bitwarden/clients pull request #5950
Opened 2023-08-03 17:50 UTC by trmartin4

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-08-14 18:46 UTC, cyprain-okeke approved these changes
Looks Good.

2023-08-14 19:25 UTC, shane-melton approved these changes
Changes related to AC look good!

2023-08-14 22:25 UTC, differsthecat submitted a review, later dismissed
These changes look good for Vault 👍

2023-08-15 16:41 UTC, shane-melton submitted a review, later dismissed

2023-08-15 17:34 UTC, Hinton commented on apps/browser/src/background/nativeMessaging.background.ts
> +            } else if (message.keyB64) {
Please note the deprecation version, assign a ticket and set a due date for removal.

2023-08-15 17:34 UTC, cagonzalezcs submitted a review, later dismissed
Looks good

2023-08-15 17:43 UTC, Hinton commented on apps/browser/src/platform/services/browser-crypto.service.ts
> +      // this will check for an auto key, but that is acceptable
Please write why.

2023-08-15 17:43 UTC, Hinton commented on apps/browser/src/safari/safari/SafariWebExtensionHandler.swift
> +                    }
Please provide a deprecation window for this. I assume desktop will migrate the key.

2023-08-15 17:52 UTC, Hinton commented on apps/desktop/src/platform/services/electron-crypto.service.ts
> +      const oldKey = await this.stateService.hasCryptoMasterKeyBiometric({ userId: userId });
How long are we supporting the old way? Are we migrating it? (Add a comment, link to a ticket)

2023-08-15 17:53 UTC, Hinton commented on apps/desktop/src/services/native-messaging.service.ts
> +          // with older browser extensions
Add a note for deprecated version, link to a jira ticket.

2023-08-15 17:58 UTC, Hinton commented on libs/common/src/services/vault-timeout/vault-timeout.service.ts
> +    await this.migrateKeyForNeverLockIfNeeded();
Document deprecated version, link to jira ticket with due date.

2023-08-15 20:44 UTC, trmartin4 commented on apps/browser/src/safari/safari/SafariWebExtensionHandler.swift
> +                    }
Added comment

2023-08-15 20:46 UTC, trmartin4 commented on apps/browser/src/background/nativeMessaging.background.ts
> +            } else if (message.keyB64) {
Added comment.

2023-08-15 20:46 UTC, trmartin4 commented on apps/desktop/src/platform/services/electron-crypto.service.ts
> +      const oldKey = await this.stateService.hasCryptoMasterKeyBiometric({ userId: userId });
Added comment, assuming a 3-release backward compatibility, as is our current standard (2023.8.1, 2023.9, and 2023.10).

2023-08-15 20:47 UTC, trmartin4 commented on apps/desktop/src/services/native-messaging.service.ts
> +          // with older browser extensions
Done!

2023-08-15 20:47 UTC, trmartin4 commented on libs/common/src/services/vault-timeout/vault-timeout.service.ts
> +    await this.migrateKeyForNeverLockIfNeeded();
Done!

2023-08-15 21:32 UTC, jprusik commented on apps/browser/src/autofill/services/autofill.service.ts
> +    ) {
conflict resolution - we removed the null check in https://github.com/bitwarden/clients/pull/5621/files#diff-ff919521412a590452c7e201f94d1c80997766b29cf4870faa84275768edc6a8L237

```suggestion
    if (
      cipher.reprompt !== CipherRepromptType.None &&
      await this.userVerificationService.hasMasterPasswordAndMasterKeyHash()
    ) {
```

2023-08-15 21:34 UTC, jprusik commented on apps/browser/src/autofill/browser/cipher-context-menu-handler.ts
> +        (await this.userVerificationService.hasMasterPasswordAndMasterKeyHash()))
```suggestion
      await this.userVerificationService.hasMasterPasswordAndMasterKeyHash()
```

2023-08-15 22:08 UTC, JaredSnider-Bitwarden commented on apps/browser/src/autofill/browser/cipher-context-menu-handler.ts
> +        (await this.userVerificationService.hasMasterPasswordAndMasterKeyHash()))
Resolved w/ #6042

2023-08-15 22:08 UTC, JaredSnider-Bitwarden commented on apps/browser/src/autofill/services/autofill.service.ts
> +    ) {
Ty for catching these! Resolved w/ #6042!

2023-08-15 22:32 UTC, jprusik approved these changes

2023-08-15 22:54 UTC, cagonzalezcs submitted a review, later dismissed

2023-08-15 23:17 UTC, trmartin4 commented on apps/browser/src/platform/services/browser-crypto.service.ts
> +      // this will check for an auto key, but that is acceptable
This has been resolved by https://github.com/bitwarden/clients/pull/6041.

2023-08-15 23:21 UTC, shane-melton approved these changes

2023-08-16 13:16 UTC, cagonzalezcs approved these changes

2023-08-16 17:26 UTC, differsthecat commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/header.component.html
> +              <button *ngIf="canLock$ | async" bitMenuItem type="button" (click)="lock()">
This is causing some issues with the UI Tests build action and causing the header to not be present: https://www.chromatic.com/review?appId=62a88a6de5b807fa98886113&number=5950&type=linked&view=changes

I think the stories located here: `bitwarden_license/bit-web/src/app/secrets-manager/shared/header.stories.ts` need to be updated with the new `canLock` observable returning true.

2023-08-16 17:29 UTC, cagonzalezcs submitted a review, later dismissed

2023-08-16 17:56 UTC, differsthecat commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/header.component.html
> +              <button *ngIf="canLock$ | async" bitMenuItem type="button" (click)="lock()">
Messed with this locally and these appear to be the changes you will have to make to fix it:

<img width="1197" alt="Screenshot 2023-08-16 at 1 54 12 PM" src="https://github.com/bitwarden/clients/assets/8926729/ef1edebd-8501-4277-ac30-2a0fe6b9f545">

2023-08-16 19:01 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/device-trust-crypto.service.implementation.ts
> +    this.platformUtilsService.showToast("success", null, this.i18nService.t("deviceTrusted"));
We think having the toast centralized is more maintainable and avoids unnecessary repetition across n components  - even if it is a presentational concern. The presentational concern is tied specifically to the successful completion of the device trust process so I would argue it's fine to centralize it here.  Further, we also leverage this logic in the `SsoLogInStrategy` which doesn't have a super clean way of transmitting up whether a device was trusted or not currently with a decent bit of refactoring for not a lot of benefit.

2023-08-16 19:17 UTC, JaredSnider-Bitwarden commented on apps/browser/src/auth/popup/login-decryption-options/login-decryption-options.component.html
The `login-decryption-options.component` _is essentially_ a locked state / screen for users who have not decrypted their vault yet and need to be presented with vault decryption options. 

TDE users can have a MP, PIN, or biometric unlock enabled which means that they can actually lock their vault according to the traditional sense as well. 

So, this leads to having two slightly different locked states:
- Locked pre-decryption --> Login Decryption Options Component 
- Locked post-decryption --> Existing Lock Component 

Note: I'm using decryption to mean has a user key set in memory. 

Our latest plan is to investigate consolidating these separate components into a single lock component in the future.

2023-08-16 19:18 UTC, JaredSnider-Bitwarden commented on apps/browser/src/background/main.background.ts
> +
Those are two different services: 
userVerificationApiService (note the Api) !== userVerificationService

2023-08-16 19:46 UTC, JaredSnider-Bitwarden commented on libs/angular/src/auth/components/lock.component.ts
> +    //   This will result in the user not being able to unlock their vault and having to log out.
This comment wasn't updated after we handled all of the "NOT handled" scenarios. We're in process of cleaning up the comment.  

We've also created a tech debt item for investigating your recommended lock component and state service refactors: https://bitwarden.atlassian.net/browse/PM-3515

2023-08-16 19:54 UTC, JaredSnider-Bitwarden commented on apps/desktop/src/app/app-routing.module.ts
> +    canActivate: [lockGuard()],
`lockGuard` is a higher order function that must be invoked in order for it to return the `CanActivateFn` so it can be executed as a route guard. More simple, arrow based functional guards can be passed in without being called.

2023-08-16 20:17 UTC, JaredSnider-Bitwarden commented on libs/common/src/services/devices/devices.service.implementation.ts
We've created https://bitwarden.atlassian.net/browse/PM-3516 and added it to our TDE Tech debt initiative.

2023-08-16 20:29 UTC, trmartin4 commented on libs/common/src/platform/models/domain/account.ts
> +  >();
I've captured this as https://bitwarden.atlassian.net/browse/PM-3517 in our TDE backward compatibility removal epic.

2023-08-16 20:29 UTC, jlf0dev commented on apps/web/src/app/settings/security-keys.component.ts
> +    this.showChangeKdf = await this.userVerificationService.hasMasterPassword();
If you're referring to user's that are passwordless and don't use key connector, they will not have a `MasterKey` so there's no reason to be able to update their kdf iterations. If you're referring to key connector users, this is the same logic as before.

2023-08-16 20:30 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/settings/security-keys.component.ts
> +    this.showChangeKdf = await this.userVerificationService.hasMasterPassword();
Re your second question: the @bitwarden/team-vault-dev team completed work as part of [PM-3038](https://bitwarden.atlassian.net/browse/PM-3038) to not show the KDF iterations warning for users without a master password.

2023-08-16 20:33 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/user-verification/user-verification.service.ts
> +    return !(await this.stateService.getUsesKeyConnector({ userId }));
This is split out from the account decryption options for backwards compatibility for new clients with older servers as account decryption options was added as part of the TDE initiative. We will add a TODO with a timeframe for removing the old code + a tech debt item so it doesn't get lost

2023-08-16 20:36 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/user-verification/user-verification.service.ts
> +    return !(await this.stateService.getUsesKeyConnector({ userId }));
https://bitwarden.atlassian.net/browse/PM-3518

2023-08-16 20:49 UTC, jlf0dev commented on apps/web/src/app/core/init.service.ts
> +      await (this.vaultTimeoutService as VaultTimeoutService).init(true);
Are these dependencies injected? It seems like this could be a dangerous assumption. Also a pretty dangerous change here

2023-08-16 21:00 UTC, jlf0dev commented on apps/browser/src/platform/services/browser-state.service.spec.ts
> +    // turn off account cache for tests
Account cache uses the storage listener we registered, but the test doesn't have that api

2023-08-16 21:03 UTC, jlf0dev commented on libs/angular/src/auth/components/lock.component.ts
> +        );
I've moved this to the crypto service for consolidation. The only way to migrate is to have the pin, and I didn't want to introduce code asking for the pin earlier when it should be one of the first things done in most situations.

2023-08-16 21:12 UTC, JaredSnider-Bitwarden commented on apps/browser/src/popup/services/services.module.ts
Could you clarify a bit here what you mean? We don't have any browser specific implementation requirements for either the `DeviceTrustCryptoService` or the `AuthReqCryptoService` that would require us to create those implementations as far as we can tell? 

Aside: we added `devices-api.service` and `devices.service` and didn't add them in the browser services.module w/ logic to grab the background service... Should we have?

2023-08-16 21:16 UTC, jlf0dev commented on libs/common/src/abstractions/api.service.ts
> +  postAdminAuthRequest: (request: PasswordlessCreateAuthRequest) => Promise<AuthRequestResponse>;
Captured as tech debt: [PM-3519](https://bitwarden.atlassian.net/browse/PM-3519)

2023-08-16 23:00 UTC, JaredSnider-Bitwarden commented on apps/browser/src/auth/popup/lock.component.ts
> +      document.getElementById(this.pinEnabled ? "pin" : "masterPassword").focus();
Good callout. I've added an optional chaining check on desktop and browser: `?.focus()` to avoid undefined errors (which I just was able to make occur on desktop).

2023-08-16 23:11 UTC, JaredSnider-Bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/header.component.html
> +              <button *ngIf="canLock$ | async" bitMenuItem type="button" (click)="lock()">
Thank you for the catch and for the fix. We've resolved the issues [here](https://github.com/bitwarden/clients/pull/6051)

2023-08-17 12:23 UTC, MGibson1 commented on apps/browser/src/background/main.background.ts
> +
No, like 20 lines up there's another initialization of the API and non-API services

2023-08-17 12:26 UTC, djsmith85 requested changes
Partial review as I was waiting on resolved merge conflicts yesterday. Will continue review after some of the things mentioned by me and others have been resolved.

2023-08-17 12:33 UTC, MGibson1 commented on apps/browser/src/popup/services/services.module.ts
I agree, there's no requirements today to implement a browser-specific version that does the whole context syncing thing.

However, should you want to expand the devices service to subscribe to something at a later date, you'll hit the same issues you have with the `AuthRequestCryptoService`. You can avoid that by using the background instance for now.

2023-08-17 12:36 UTC, MGibson1 commented on apps/desktop/src/app/app-routing.module.ts
> +    canActivate: [lockGuard()],
Yes, but the question is _why_ is it a higher order function? There are no options to the thing, so you could just define `lockGuard` to be whatever method is always returned by `lockGuard()`, right?

I looked into this a bit and I think it'd be a net loss in type safety because angular doesn't seem to define a union type for the return value of `CanActivateFn`s

2023-08-17 12:38 UTC, MGibson1 commented on libs/common/src/auth/services/user-verification/user-verification.service.ts
> +    return !(await this.stateService.getUsesKeyConnector({ userId }));
ah, that makes sense! thank you

2023-08-17 16:30 UTC, JaredSnider-Bitwarden commented on apps/browser/src/background/main.background.ts
> +
🤦 oh.

2023-08-17 17:09 UTC, JaredSnider-Bitwarden commented on apps/browser/src/background/main.background.ts
> +
Resolved here: https://github.com/bitwarden/clients/pull/6051/commits/e728234f3b76efb3bd101c510f849eecc2c405f1

2023-08-17 17:26 UTC, JaredSnider-Bitwarden commented on apps/browser/src/popup/app-routing.module.ts
> +import { redirectGuard } from "../../../../libs/angular/src/auth/guards/redirect.guard";
Ty for catching that. I've updated the import + added an index file for the guards + updated imports as requested: https://github.com/bitwarden/clients/pull/6051/commits/653e8aec07047e511ccdafa6d152662288dec03f

2023-08-17 18:33 UTC, JaredSnider-Bitwarden commented on apps/browser/src/popup/services/services.module.ts
Per huddle discussion:
1. Keeping `DeviceTrustCryptoService` and `AuthReqCryptoService` as is
2. Added `devices.service` to `main.background` and `services.module` to head off any future issues (https://github.com/bitwarden/clients/pull/6051/commits/9937dc6f9b7003e2869cd9d86b8cb8ba23b84f62)

2023-08-17 18:33 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/core/init.service.ts
> +      await (this.vaultTimeoutService as VaultTimeoutService).init(true);
Resolved together in huddle: https://github.com/bitwarden/clients/pull/6051/commits/55a797d4ff571a1942686a32fdcbb5ad0311b5ae

2023-08-17 18:34 UTC, JaredSnider-Bitwarden commented on libs/angular/src/auth/components/lock.component.ts
> +    //   This will result in the user not being able to unlock their vault and having to log out.
Completed work: https://github.com/bitwarden/clients/pull/6051/commits/76cf5d37b193137a83f3a4e413c2f2ff428fa107

2023-08-17 18:35 UTC, JaredSnider-Bitwarden commented on apps/browser/src/popup/services/services.module.ts
> +    },
Simplified here: https://github.com/bitwarden/clients/pull/6051/commits/9318e26ec5f57d2e1055ff5dfe01379fd0151ad2

2023-08-17 18:58 UTC, JaredSnider-Bitwarden commented on apps/browser/src/auth/popup/login-decryption-options/login-decryption-options.component.html
Per discussion with design, the lock component consolidation will be redone in the future.

2023-08-17 19:12 UTC, JaredSnider-Bitwarden reviewed
@jlf0dev and I addressed all outstanding requested changes. Awaiting further re-reviews.

2023-08-17 19:16 UTC, shane-melton approved these changes

2023-08-17 19:18 UTC, MGibson1 submitted a review, later dismissed

2023-08-17 19:27 UTC, Thomas-Avery submitted a review, later dismissed

2023-08-17 19:49 UTC, cagonzalezcs submitted a review, later dismissed

2023-08-18 11:41 UTC, djsmith85 requested changes
Completed my full review.

`en/messages.json`-files: If the message of any of them changes the key and all of it's usages will need to be changed. This is to ensure that the textual change is enforced in the translations in CrowdIn. All occurrences marked with `Message changed without key-update`

2023-08-18 11:41 UTC, djsmith85 commented on apps/web/src/app/core/init.service.ts
> +      await (this.vaultTimeoutService as VaultTimeoutService).init(true);
Why is it okay to change the pattern on desktop but keep it with browser and web?

`await (this.vaultTimeoutService as VaultTimeoutService).init(true);` vs `await this.vaultTimeoutService.init(true); `

2023-08-18 11:41 UTC, djsmith85 commented on libs/common/src/services/devices/devices.service.implementation.ts
> +export class DevicesServiceImplementation implements DevicesServiceAbstraction {
:question: Should this service and it's abstraction be owned by team-auth or team-platform?

2023-08-18 12:30 UTC, trmartin4 commented
> Completed my full review.
> 
> `en/messages.json`-files: If the message of any of them changes the key and all of it's usages will need to be changed. This is to ensure that the textual change is enforced in the translations in CrowdIn. All occurrences marked with `Message changed without key-update`

Thank you!  With regard to your comment that "If the message of any of them changes the key and all of its usages will need to be changed" - are you saying that if we change the message for a key that is used only once, we need to change the key so that it will trigger a CrowdIn update?

2023-08-18 12:56 UTC, trmartin4 commented on apps/web/src/locales/en/messages.json
> +    "message": "SSO required",
Its current structure is in order to separate out the links from the text, but I've created https://bitwarden.atlassian.net/browse/PM-3539 to address the issue.  That's a great catch, and I didn't appreciate the implication of defined sentence structure here.

2023-08-18 13:35 UTC, differsthecat submitted a review, later dismissed
Looks good for Vault!

2023-08-18 13:37 UTC, trmartin4 commented on apps/web/src/locales/en/messages.json
> +    "message": "policy,",
Addressed in https://github.com/bitwarden/clients/pull/6066

2023-08-18 13:37 UTC, trmartin4 commented on apps/web/src/locales/en/messages.json
> +    "message": "SSO required",
Addressed in https://github.com/bitwarden/clients/pull/6066

2023-08-18 13:37 UTC, trmartin4 commented on apps/desktop/src/locales/en/messages.json
> +    "message": "Login initiated"
Addressed in https://github.com/bitwarden/clients/pull/6066

2023-08-18 14:01 UTC, cyprain-okeke submitted a review, later dismissed
Changes on billing looks good

2023-08-18 14:58 UTC, JaredSnider-Bitwarden commented on libs/common/src/services/devices/devices.service.implementation.ts
> +export class DevicesServiceImplementation implements DevicesServiceAbstraction {
We've created https://bitwarden.atlassian.net/browse/PM-3516 and added it to our TDE Tech debt initiative.

2023-08-18 15:06 UTC, JaredSnider-Bitwarden commented on apps/browser/src/background/main.background.ts
> +      this.userVerificationService
🤦 ty for catching that. Resolved here: https://github.com/bitwarden/clients/pull/6068/commits/968c4e8cbc513e603d01d559cd891280f6a91fad

2023-08-18 15:20 UTC, JaredSnider-Bitwarden commented on libs/angular/src/services/jslib-services.module.ts
> +          logoutCallback
The `deps` array lists all the dependencies required for the factory function in the same order they appear as parameters in the function.  As we have `LOCKED_CALLBACK` and `LOGOUT_CALLBACK` defined as injection tokens, they will be provided and passed in accordingly. 

I have removed the use of `any` and correctly typed the callbacks here (which required slight updates to the `VaultTimeoutService` as well): https://github.com/bitwarden/clients/pull/6068/commits/9e57e209d81731ba0ef2938800afa75266b931dd

2023-08-18 15:30 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/core/init.service.ts
> +      await (this.vaultTimeoutService as VaultTimeoutService).init(true);
@djsmith85 , great callout. I didn't know that we had the same issue on web (the `VaultTimeoutService` is not used in the `InitService` on browser). I've resolved this here: https://github.com/bitwarden/clients/pull/6068/commits/5720bd67d8449929def69a26278913985ce55a23

2023-08-18 16:56 UTC, JaredSnider-Bitwarden commented on libs/angular/src/services/jslib-services.module.ts
> +          logoutCallback
The `VaultTimeoutService` has an `init` method which wasn't part of the public `VaultTimeoutServiceAbstraction`, and we (@MGibson1 and I) solved it this way vs creating another abstraction (`VaultTimeoutInitableServiceAbstraction`) so that we could just get a concrete implementation in all the places which leveraged the `init` method.

2023-08-18 16:58 UTC, Thomas-Avery approved these changes

2023-08-18 17:03 UTC, cagonzalezcs approved these changes

2023-08-18 17:41 UTC, vvolkgang approved these changes
New changes aren't related to AC, approving on behalf of Shane.

2023-08-18 17:44 UTC, cyprain-okeke approved these changes
LGTM

2023-08-18 18:03 UTC, justindbaur approved these changes
Looks like all other platform comments have been addressed and the last 3 (one merge commit) commits added after look good.

2023-08-18 18:03 UTC, justindbaur commented on libs/angular/src/services/jslib-services.module.ts
> +        logoutCallback: (expired: boolean, userId?: string) => Promise<void>
😍

2023-08-18 18:05 UTC, merged

2023-08-21 09:21 UTC, Hinton commented on libs/angular/src/services/jslib-services.module.ts
> +          logoutCallback
That doesn't have anything to do with my complaint. You can replace the useFactory with a useClass and still keep the DI wireup for the abstract.

2023-08-21 15:48 UTC, JaredSnider-Bitwarden commented on libs/angular/src/services/jslib-services.module.ts
> +          logoutCallback
Ah, I'm sorry. I see what you mean now. Thank you very much for #6076.