[AC-1336] Indicate unpaid subscriptions on payment screen
bitwarden/clients pull request #5962
Opened 2023-08-04 17:51 UTC by cturnbull-bitwarden

## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
When a subscription has a state of "unpaid," some text will now appear to say that "Your payment method will be charged for any unpaid subscriptions."

## Code changes

- **locales\en\messages.json:** Add unpaid subscriptions charge message
- **payment-method.component.ts:** Add subscription status to payment method component
- **payment-method.component.html:** Add warning message for unpaid subscriptions

## Screenshots

![image](https://github.com/bitwarden/clients/assets/133619638/6baa54d8-e2d1-4a94-9bb8-df60ebfb364f)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-08-15 15:26 UTC, cyprain-okeke reviewed
it good look

2023-08-15 15:27 UTC, cyprain-okeke commented on apps/web/src/locales/en/messages.json
> +  "paymentChargedWithUnpaidSubscription": {
Please confirm his message with product team

2023-08-15 15:40 UTC, cyprain-okeke submitted a review, later dismissed

2023-08-15 23:43 UTC, eliykat requested changes

2023-08-15 23:43 UTC, eliykat commented on apps/web/src/app/billing/settings/payment-method.component.ts
> +      const subPromise = this.organizationApiService.getSubscription(this.organizationId);
`OrganizationSubscriptionResponse` is a subclass of `OrganizationResponse`, so this should be able to replace the `orgPromise` call.

2023-08-16 19:37 UTC, cturnbull-bitwarden commented on apps/web/src/app/billing/settings/payment-method.component.ts
> +      const subPromise = this.organizationApiService.getSubscription(this.organizationId);
Nice suggestion, I just pushed an update cleaning this up

2023-08-17 23:26 UTC, eliykat approved these changes
Nicely done

2023-08-28 13:58 UTC, merged