Feature addition - Toggle Hardware Acceleration [Desktop]
bitwarden/clients pull request #5968
Opened 2023-08-05 08:34 UTC by prithvi2k2

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Added a toggle for disabling/enabling hardware acceleration (enabled by default) on Desktop client - Addresses Issue #2615 

## Code changes

- **`apps/desktop/src/`**
  - `app/accounts/settings.component.html`: Added checkbox-type form group for toggling feature
  - `app/accounts/settings.component.ts`: Updates state of checkbox for the feature on change
  - `locales/en/messages.json`: Added title and description for the feature setting
  - `main.ts`: On (re)start of application, disables hardware acceleration if turned off
  
- **`libs/common/src/platform/`**
    - `services/state.service.ts`: Getter/setter of boolean `enableHardwareAcceleration`
    - `abstractions/state.service.ts`: Getter/setter declarations
    - `models/domain/global-state.ts`: Global state boolean variable declaration

Discussion at PR #2896 by @evelez7 and @Hinton helped me immensely in quickly understanding the requirements.

## Screenshots
![Screenshot 2023-08-05 135937](https://github.com/bitwarden/clients/assets/72189314/389e0736-5ef8-41fd-a22f-0bcd081b23a3)

2023-08-05 08:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitwarden/clients?pullRequest=5968) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bitwarden/clients?pullRequest=5968) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitwarden/clients?pullRequest=5968) it.</sub>

2023-08-06 07:21 UTC, prithvi2k2 commented
Requesting @djsmith85 and @Hinton for PR review

2023-08-06 07:24 UTC, prithvi2k2 reviewed
Reviewed

2023-08-08 12:49 UTC, prithvi2k2 commented
What does "EnforceLabel : Expected -- Waiting for status to be reported" even mean? It's been waiting since I've opened the PR... Is there something I need to do to get through it?

2023-08-08 13:32 UTC, djsmith85 commented
@prithvi2k2: This is just job of the build-pipeline (checking for specific labels). Everything required by you has been checked and your contribution has been passed on to review by the product team.

2023-08-08 13:34 UTC, prithvi2k2 commented
Thank you for the confirmation @djsmith85

2023-10-03 04:21 UTC, prithvi2k2 commented
Hello @djsmith85 , it's been a long wait for review... I don't mind if it takes even longer as I know how busy the team can get involved in other priority tasks, but is there any chance this PR can be considered for hacktoberfest by adding a `hacktoberfest-accepted` label? It'll be helpful to me

2023-10-03 07:28 UTC, djsmith85 commented
@prithvi2k2 I have passed the feedback onto the product team, which is reviewing your contribution.

2024-03-14 01:32 UTC, prithvi2k2 commented
Hello @trmartin4 , Please suggest any necessary changes if needed... I'm still willing to work on it and get it merged to be a part of Bitwarden Developer Community

2024-03-14 01:44 UTC, prithvi2k2 commented
It's been several months since this pull request was submitted, and I've updated my forked branch with the latest changes from the Bitwarden main branch. I would highly appreciate it if you could take a moment to review my updates

2024-03-14 17:42 UTC, trmartin4 commented
Thank you!  We're going to have a review from our design team to make sure there are no adjustments to the UI necessary, and then we'll progress the change through our internal PR review and QA.

2024-03-18 19:09 UTC, justindbaur requested changes
All these review comments are part of the changes @Hinton made.

2024-03-18 19:09 UTC, justindbaur commented on apps/desktop/src/services/desktop-settings.service.ts
> +    deserializer: (v: boolean) => v ?? true,
Don't apply the default on the `deserializer`, do it in a `pipe(map())` when returning the value. While the `deserializer` will run since this is disk, we don't make the guarantee that it will. It should only be used to reapply the prototype not apply defaults.

2024-03-18 19:09 UTC, justindbaur commented on apps/desktop/src/services/desktop-settings.service.ts
This class should be under platform ownership, you can see where I am planning on putting it in [this PR](https://github.com/bitwarden/clients/pull/8369/files#diff-5dfb02fdd18f3393e29fee64a9d9c2c2dfa651e36cceeeb9aa81bd28a1fe73e5).

2024-03-18 19:09 UTC, justindbaur commented on libs/common/src/platform/state/state-definitions.ts
> +export const DESKTOP_SETTINGS_DISK = new StateDefinition("desktopSettings", "disk");
Order this alphabetically with the rest of platforms states.

2024-03-18 20:55 UTC, justindbaur submitted a review, later dismissed

2024-03-19 09:14 UTC, Hinton commented
This was handed off to QA yesterday and is currently scheduled to be tested in the near future.

2024-03-21 13:40 UTC, justindbaur approved these changes

2024-03-21 13:43 UTC, merged