[SM-877] Updating trash to have ability to copy UUID
bitwarden/clients pull request #5986
Opened 2023-08-08 03:03 UTC by cd-bitwarden

## Type of change

```
- [ x ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Add ability to copy UUID from Trash page for secret.
## Code changes

**bitwarden_license/bit-web/src/app/secrets-manager/trash/trash.component.html** - Set up copy event
**bitwarden_license/bit-web/src/app/secrets-manager/trash/trash.component.ts** - Adding services and call to logic for copying UUID
## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-08-08 14:39 UTC, nsbgit approved these changes
LGTM

2023-08-08 21:19 UTC, Thomas-Avery requested changes
The layout of this in the trash section doesn't look like the other secret lists and the FIGMA.

Looks like we need to adjust the ordering of some `<div>`s related to if the name appears for trash or not inside `secrets-list.component.html`

![image](https://github.com/bitwarden/clients/assets/43214426/85d6ac1f-fe86-4628-a9d2-0799618fb189)

vs 

![image](https://github.com/bitwarden/clients/assets/43214426/8e5912b3-b9b1-4dc4-9c82-121b1b5b6a37)

2023-08-15 00:13 UTC, cd-bitwarden commented
> The layout of this in the trash section doesn't look like the other secret lists and the FIGMA.
> 
> Looks like we need to adjust the ordering of some `<div>`s related to if the name appears for trash or not inside `secrets-list.component.html`
> 
> ![image](https://user-images.githubusercontent.com/43214426/259232469-85d6ac1f-fe86-4628-a9d2-0799618fb189.png)
> 
> vs
> 
> ![image](https://user-images.githubusercontent.com/43214426/259233069-8e5912b3-b9b1-4dc4-9c82-121b1b5b6a37.png)

Thank you for catching this 😺

2023-08-15 15:24 UTC, Thomas-Avery requested changes

2023-08-15 15:24 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.html
> +            <div *ngIf="trash">{{ secret.name }}</div>
If I'm understanding this correctly, when `trash` is true, we will get an extra div? 

```
            <div>
                // button doesn't display but div is still included
            </div>
            <div *ngIf="trash">{{ secret.name }}</div>
```

What do you think about either moving the `*ngIf="!trash"` to the div or something like an else block? https://angular.io/api/common/NgIf#showing-an-alternative-template-using-else

2023-08-15 20:45 UTC, Thomas-Avery approved these changes
Looks good, thank you!

2023-08-24 17:27 UTC, cd-bitwarden commented
@Thomas-Avery there were some merge conflicts I had to resolve, can you please give one last review? 😄 Thank you!

2023-08-28 15:03 UTC, Thomas-Avery approved these changes
LGTM

2023-08-28 15:03 UTC, merged