[PM-2207], [PM-1245], [PM-3302] Make browser login, lock, and 2fa components handle configurable redirect routes
bitwarden/clients pull request #5989
Opened 2023-08-08 18:22 UTC by gbubemismith

## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
Prepare the `login`, `lock` and `2fa` components to handle different success routes instead of the current hard-coded success routes. `PM-1245`, `PM-3302` -> Add login and unlock logic to the fido2 popout.

## Code changes

- **apps/browser/src/auth/popup/home.component.ts:**
- **libs/angular/src/auth/components/lock.component.ts:**
- **libs/angular/src/auth/components/two-factor.component.ts:**
- **libs/angular/src/auth/components/login.component.ts:**

  Added `redirectPath` and `sessionId` query parameters which would be sent before allowing connection to the fido2 
  component. The `redirectPath` would hold the component to redirect to after successful login, and the `session id` is the 
  fido2 session id.

- **apps/browser/src/platform/browser/browser-api.ts:** Introduced `ngZone` as an optional parameter to the browser API `messageListener` to fix an issue on the `fido2Component` due to a change detection error where the page doesn't get updated with the latest changes on the `data$` observable.
- **apps/browser/src/services/fido2/browser-fido2-user-interface.service.ts:** Introduced the `ensureUnlockedVault` method to verify the user's authentication status and navigate accordingly. Enhanced the `connect` method to manage the creation of different popouts depending on the user's authentication status and also oversee the closure of the popout window
- **apps/browser/src/vault/popup/components/fido2/fido2.component.ts:** Injected `ngZone` to be used by the message listener.

## Screenshots

https://github.com/bitwarden/clients/assets/13024008/0b77be84-29d6-4baa-941d-9c2ebbd9e3cc

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-08-21 21:08 UTC, jlf0dev requested changes
Mostly had some nits and questions I'd like addressed.

2023-08-21 21:08 UTC, jlf0dev commented on libs/angular/src/auth/components/two-factor.component.ts
> +        this.sessionId = qParams?.sessionId;
Seems strange to access using `?` operator after you've already accessed `qParams`. If `qParams` can be null, can you update all the other places? Or if not you can probably remove this.

2023-08-22 10:03 UTC, coroiu requested changes

2023-08-22 10:03 UTC, coroiu commented on apps/browser/src/services/fido2/browser-fido2-user-interface.service.ts
>      );
issue: I think we should refactor how we pass along redirection parameters to make the process a bit more generic. Like @jlf0dev mentioned in his own comment, seeing `sessionId` in the `home` component can be a bit unexpected. A common solution is to nest the parameters, i.e. URL-encoding the `sessionId` inside a generic `redirectUrl` parameter.

See example here: https://github.com/bitwarden/clients/compare/PM-2207...PM-2207-acoroiu-review

2023-08-23 08:41 UTC, coroiu reviewed
Can't approve due to build errors

2023-08-25 08:18 UTC, coroiu approved these changes

2023-08-25 08:18 UTC, coroiu commented on apps/web/src/app/auth/login/login.component.ts
> +// eslint-disable-next-line rxjs-angular/prefer-takeuntil
question: are we sure that we should be disabling this check?

2023-08-25 18:25 UTC, gbubemismith commented on apps/web/src/app/auth/login/login.component.ts
> +// eslint-disable-next-line rxjs-angular/prefer-takeuntil
Added this because of `Subject destroy$ not a class property` linter error

2023-08-29 15:53 UTC, jlf0dev approved these changes
Looks good!

2023-08-29 15:53 UTC, jlf0dev commented on apps/browser/src/services/fido2/browser-fido2-user-interface.service.ts
Just want to note that we need to determine the owner of these services before merging to master.

2023-08-29 17:18 UTC, gbubemismith commented on apps/browser/src/services/fido2/browser-fido2-user-interface.service.ts
I think the `vault` can own this; what do you think?

2023-08-30 11:47 UTC, coroiu commented on apps/browser/src/platform/browser/browser-api.ts
>    static messageListener$() {
The comment here is slightly outdated, and @Hinton has commented something similar in another branch that maybe we shouldn't put the observable version of `messageListener$` here in the `BrowserApi`. 

I see absolutely no reason why we couldn't support both. And the issue with these callbacks running outside of Angular is an issue no matter the mechanism used to subscribe to these things.

I think adding an observable version of this here promotes the usage of rxjs while also providing documentation for anyone on how to easily transition into angular zone by using the new `runInsideAngular` operator. If platform decides that this code is not used widely enough to warrant an addition to `BrowserApi` then we can just move it somewhere else :)

2023-08-30 11:58 UTC, coroiu commented on apps/browser/src/platform/browser/browser-api.ts
>    static messageListener$() {
For reference, this is how the workaround used to look:

https://github.com/bitwarden/clients/blob/a512563f4e53458e2f649030c6d2f4c73b4d6aa1/apps/browser/src/platform/browser/browser-api.ts#L247-L259

2023-08-30 13:52 UTC, gbubemismith commented on apps/browser/src/platform/browser/browser-api.ts
>    static messageListener$() {
Yeah that comment isn't needed anymore

2023-08-30 15:32 UTC, MGibson1 commented on apps/browser/src/platform/browser/browser-api.ts
>    static messageListener$() {
@coroiu, that previous version still uses observables. What I'm asking is if arrow callbacks are used is the zone correctly identified? I would expect that it is since the purpose of arrow function expressions is to bind the current context implicitly to the function

2023-08-30 15:47 UTC, willmartian requested changes

2023-08-30 16:09 UTC, gbubemismith commented on apps/browser/src/services/fido2/browser-fido2-user-interface.service.ts
> +    );
That's correct. Thanks for pointing that out

2023-08-30 16:44 UTC, gbubemismith commented on apps/web/src/app/auth/login/login.component.ts
> +    super.ngOnDestroy();
I did this to fix the component inheritance bug.

2023-08-30 23:06 UTC, willmartian commented on apps/web/src/app/auth/login/login.component.ts
> +    super.ngOnDestroy();
Which bug in particular? There used to be a bug in Angular where lifecycle events were not inherited unless explicitly called with `super`, but that is no longer the case: https://stackblitz.com/edit/stackblitz-starters-xxubl8?file=src%2Fmain.ts

2023-08-31 18:43 UTC, Hinton requested changes
Maybe I'm missing something, but it seems we're trying to (yet again) replicate the deep-linking that we support in the web vault. I would be hesitant to introduce a new way to handle especially in the base classes.

In https://github.com/bitwarden/clients/pull/6058/files#diff-12f6d0334175fde38b87b611d5d3742b92484936e6c08cf028ee17e672b1bbc6 I propose introducing a `BrowserRouterService` which identical to the web router service, would track redirects to the login page and on successful login return the user to the previous page.

I believe that is more scalable solution long term than manually parsing query params across numerous components.

2023-08-31 21:39 UTC, gbubemismith commented on apps/browser/src/platform/browser/browser-api.ts
>    static messageListener$() {
@MGibson1, the bug would still surface with the callback version, so I added a similar comment on the callback version

2023-09-01 07:19 UTC, coroiu commented on apps/browser/src/platform/browser/browser-api.ts
>    static messageListener$() {
> Why does the implementation of messageListener$ differ so much from messageListener? The callback version is doing more than just calling chrome.runtime.onMessage.addListener.

@willmartian 1) It supports responding to messages, something that isn't compatible with the observable interface. 2) It has special handling to avoid some memory leak, a fix that was added pretty recently.

@gbubemismith My suggestion here is that we tweak `messageListener$` to use `messageListener()` instead of calling `chrome.runtime.onMessage.addListener` directly. That way we don't have to duplicate any memory leak workarounds.

> What I'm asking is if arrow callbacks are used is the zone correctly identified

Ah, right! @gbubemismith is correct, you still need to manually run code inside `ngZone` when using the callback version. Check out `browser / app.component`: https://github.com/bitwarden/clients/blob/ac1c7f9c8f8ad0979cf0a00a28212366ef0e9b00/apps/browser/src/popup/app.component.ts#L83-L148 

This is because the issue is not execution context but the fact that angular isn't aware that the function is running. In short `ngZone` works by monkey-patching all native browser functions that could potentially cause code to execute, e.g. `setTimeout`, `Promise.then`, `addEventListener`, etc. This patch adds a wrapper that triggers `change detection` at the end of those resulting event loop ticks (technically `change detection` will re-add itself to the event loop until the queue is empty). The issue is hat `chrome.runtime.onMessage.addListener` isn't being patched. Here is a list of patched standard APIs https://github.com/angular/angular/blob/HEAD/packages/zone.js/STANDARD-APIS.md

2023-09-01 08:36 UTC, Hinton commented on apps/browser/src/platform/browser/browser-api.ts
>    static messageListener$() {
We might be able to monkeypatch this using zone.js logic directly. Here is an example of how they did it on message port.

https://github.com/angular/angular/blob/main/packages/zone.js/lib/browser/message-port.ts

Worth a shot just changing `MessagePort` to `chrome.runtime` and check if it "works". That way we will never have to think about it and it will just work. ™️

2023-09-01 10:59 UTC, gbubemismith commented on apps/browser/src/platform/browser/browser-api.ts
>    static messageListener$() {
@coroiu I had already done that with my latest commit yesterday

2023-09-05 09:13 UTC, coroiu commented on apps/browser/src/platform/browser/browser-api.ts
>    static messageListener$() {
@Hinton Good point, that would be a good fix towards master directly. I'll open a new PR where we can continue this discussion

2023-09-07 10:05 UTC, Hinton reviewed
I think the routing logic is much improved. We should look into consolidating the router services in the future.

2023-09-11 12:12 UTC, Hinton commented
This branch seems to contain portions of #6188? Should it be pointing to #6188 so we don't have to review those changes twice.

2023-09-11 13:02 UTC, Hinton commented on apps/browser/src/vault/popup/components/fido2/fido2.component.ts
> +      .pipe(runInsideAngular(this.ngZone), takeUntil(this.destroy$))
We seem to be mixing polyfill and `runInsideAngular`.  Can we just remove the polyfill and `runInsideAngular` and get the pending PR to master QA tested and merged?

2023-09-11 13:04 UTC, Hinton commented on apps/browser/src/platform/popup/services/browser-router.service.ts
> +  constructor(private router: Router, private stateService: StateService) {
```suggestion
  constructor(router: Router) {
```

2023-09-12 10:35 UTC, Hinton approved these changes
I believe my concerns are resolved.

2023-09-12 20:05 UTC, willmartian approved these changes
Looks great to me! 🌈  Thanks @gbubemismith

2023-09-12 21:19 UTC, merged