AC-1333 vault report org ciphers
bitwarden/clients pull request #5998
Opened 2023-08-09 19:48 UTC by Jingo88

```
- [ ] Bug fix
- [ X ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

The reports pages should show the user any ciphers from an organization they were invited to and have `Can Edit` access to that collection. 

They should not be seeing any `Can View` items.

Added the `app-org-badge` to the reports with `disabled=true`. They are not yet clickable, reports badge flow will come in a future ticket. 

## Code changes

- filtering of `Can Edit` ciphers done in `app/reports` ts files with `.filter((c) => c.edit);`
- `app/reports` pages brought in `OrganizationService` to subscribe to organizations for `app-org-badge` logic
- files in `admin-console/organizations/tools` were updated to have services sent to parent class
- html files in `app/reports` given the `app-org-badge` component
- spec files added for each reports page
- created a `reports-ciphers.mock` for reusable mock data between specs

## Video of Can Edit Logic 

https://github.com/bitwarden/clients/assets/8302660/8b056294-626b-4346-9a91-a2b474e3128b

2023-08-09 20:10 UTC, differsthecat commented on apps/web/src/app/reports/pages/exposed-passwords-report.component.html
> +          </td>
❓ Does this still show if the user doesn't belong to any organizations?

2023-08-10 14:23 UTC, Jingo88 commented on apps/web/src/app/reports/pages/exposed-passwords-report.component.html
> +          </td>
It should act the same as vault and will show the "Me" badge. I will be updating the JIRA ticket so the "no Me" bullet in the description is removed

2023-08-10 14:24 UTC, differsthecat commented on apps/web/src/app/reports/pages/exposed-passwords-report.component.html
> +          </td>
I think if a user doesn't belong to an org, it shouldn't show the badge at all. I beleive that's how the vault works?

2023-08-14 04:28 UTC, eliykat requested changes
Not a complete review, just a few things that jumped out at me.

2023-08-14 04:28 UTC, eliykat commented on apps/web/src/app/reports/pages/inactive-two-factor-report.component.ts
> +      });
Suggestion: don't subscribe and just use an async pipe in the template. Then you can drop the `this.destroy$` pattern as well :)

2023-08-14 04:28 UTC, eliykat commented on apps/web/src/app/reports/pages/weak-passwords-report.component.ts
> +  }
You can use `Utils.isNullOrWhitespace(c.login.username)`

2023-08-14 04:28 UTC, eliykat commented on apps/web/src/app/shared/loose-components.module.ts
> +    PipesModule,
Do these need to be added here as well as `ReportsModule`?

2023-08-14 04:28 UTC, eliykat commented on apps/web/src/app/reports/pages/inactive-two-factor-report.component.ts
> +      });
Same goes for the other reports below that follow this pattern.

2023-08-14 19:43 UTC, Jingo88 commented on apps/web/src/app/reports/pages/inactive-two-factor-report.component.ts
> +      });
This is a great suggestion and just pushed up those changes for all the reports pages. There's a chance subscribing an assigning might make an appearance later on for a new design flow regarding filtering ciphers in reports. But we can cross that bridge when we get there. 

[Related ticket for reference](https://bitwarden.atlassian.net/browse/AC-1586)

2023-08-14 19:44 UTC, Jingo88 commented on apps/web/src/app/reports/pages/weak-passwords-report.component.ts
> +  }
Updated. awesome thanks for this snippet.

2023-08-14 19:56 UTC, Jingo88 commented on apps/web/src/app/shared/loose-components.module.ts
> +    PipesModule,
I'm not 100% sure as the reason, but when these modules are missing from either the `LooseComponentsModule` or the `ReportsModule` the `app-org-badge` isn't being recognized in any of the reports child page components.

2023-08-14 20:03 UTC, Jingo88 commented on apps/web/src/app/shared/loose-components.module.ts
> +    PipesModule,
When those modules are removed from either the `ReportsModule` or the `LooseComponentsModule` we get an invalid error for the `app-org-badge` I believe this is due to the `ReportsModule` declaring all the base reports pages, and the `LooseComponentsModule` declaring all the reports inside `admin-console/organizations/tools` since those components extend the base reports pages

2023-08-14 20:54 UTC, eliykat commented
We discussed internally that Tools Team should own the reports components. They're not marked as CODEOWNERS yet but I suggest we treat them as such for this PR (i.e. require a review from that team before merging).

2023-08-23 11:13 UTC, djsmith85 requested changes

2023-08-23 11:13 UTC, djsmith85 commented on apps/web/src/app/reports/pages/reused-passwords-report.component.ts
> +  organizations$: Observable<Organization[]>;
If the `organizations$`is going to be part of every report, we should move it to the base-component.

2023-08-23 19:46 UTC, Jingo88 commented on apps/web/src/app/reports/pages/reports-ciphers.mock.ts
> +    id: "cbea34a8-bde4-46ad-9d19-b05001228ab6",
Ah yeah i copy pasta'd those objects. Updated them for clarity. thanks

2023-08-23 19:47 UTC, Jingo88 commented on apps/web/src/app/reports/pages/exposed-passwords-report.component.spec.ts
> +  });
Updated: added extra expects checking for the edit value

2023-08-23 19:48 UTC, Jingo88 commented on apps/web/src/app/reports/pages/reused-passwords-report.component.ts
> +  organizations$: Observable<Organization[]>;
Refactored and moved up to the base component. thanks!

2023-08-24 12:16 UTC, djsmith85 approved these changes
Changes are looking good.

2023-09-08 04:27 UTC, eliykat commented on apps/web/src/app/shared/loose-components.module.ts
> +    PipesModule,
Oof! Didn't realise that we still have all the org reports in here. How awful 😁

2023-09-08 04:28 UTC, eliykat approved these changes
My changes have been addressed, thank you!

2023-09-08 04:29 UTC, eliykat commented on apps/web/src/app/reports/pages/inactive-two-factor-report.component.ts
> +      });
Maybe you can find some way to pipe + filter the observable when it comes time for that ;) but see how you go.

2023-09-08 14:54 UTC, willmartian commented on apps/web/src/app/shared/loose-components.module.ts
> +    PipesModule,
@Jingo88 is there a ticket to remove these report components/modules from the `LooseComponentsModule`? If not, could you create one?

2023-09-08 14:55 UTC, willmartian approved these changes
Platform changes look 👍

2023-10-04 03:50 UTC, eliykat submitted a review, later dismissed

2023-10-04 17:18 UTC, Jingo88 commented
Updated to include QA findings. `Reused Password Count` fixed to only include count of user passwords. Password reports updated to only include `Can Edit` permission, removing any `Can Edit except passwords` permissions. 

New video of updates included in description

2023-10-05 01:51 UTC, eliykat commented on apps/web/src/app/reports/pages/reused-passwords-report.component.ts
> +        }
Now passwords are only included in the reused password count if:
* they're a personal item, or
* they're an organizational item and you're an owner

But why have this limitation? Especially when you're filtering for `c.edit && c.viewPassword` below, which ensures you're only showing items that the user can view & edit.

2023-10-05 16:38 UTC, Jingo88 commented on apps/web/src/app/reports/pages/reused-passwords-report.component.ts
> +        }
This is my fault, I misunderstood the context of the QA findings. The Owner logic has been removed and I've refactored the `reused password report component` to only include `Can Edit` cipher access to the list in reports, as well as the count. 

e.g. `Can View` items will not show in the list, and will not impact the count even if their passwords match. 

New count video added to PR description

2023-10-13 05:20 UTC, eliykat requested changes
The logic looks right to me but looking at it again, I think we could be a bit more efficient in the approach.

2023-10-13 05:20 UTC, eliykat commented on apps/web/src/app/reports/pages/exposed-passwords-report.component.ts
> +    this.ciphers = exposedPasswordCiphers.filter((c) => c.edit && c.viewPassword);
This filters the passwords after they've already been sent to HIBP. It also doesn't remove them from the `exposedPasswordMap`.

I suggest this check is included in the early return above (in the `allCiphers.forEach` callback) where we filter out other items we don't want to show in this report.

2023-10-13 05:20 UTC, eliykat commented on apps/web/src/app/reports/pages/inactive-two-factor-report.component.ts
> +      this.ciphers = inactive2faCiphers.filter((c) => c.edit);
Same here, you could filter out this cipher earlier and skip all the domain parsing and lookup logic.

Not related to this PR, but is the `promises` variable actually used here?

2023-10-13 05:20 UTC, eliykat commented on apps/web/src/app/reports/pages/reused-passwords-report.component.ts
> +  getAllCiphers(): Promise<CipherView[]> {
Why is this no longer `protected`?

2023-10-13 05:20 UTC, eliykat commented on apps/web/src/app/reports/pages/weak-passwords-report.component.ts
> +    this.ciphers = this.weakPasswordCiphers.filter((c) => c.edit && c.viewPassword);
Same here, could filter out earlier and avoid calculating password strength for ciphers you're going to ignore anyway.

2023-10-16 23:43 UTC, shane-melton commented on apps/web/src/app/reports/pages/exposed-passwords-report.component.html
> +          <td>
question: Should this column be hidden when being viewed from the organization reports tab?

2023-10-24 14:42 UTC, Jingo88 commented on apps/web/src/app/reports/pages/exposed-passwords-report.component.html
> +          <td>
thanks for pointing this out. I removed the badge from the org reports. Added a video showing this in the PR description

2023-10-24 14:42 UTC, Jingo88 commented on apps/web/src/app/reports/pages/exposed-passwords-report.component.ts
> +    this.ciphers = exposedPasswordCiphers.filter((c) => c.edit && c.viewPassword);
Thanks good call. has since been updated

2023-10-24 14:43 UTC, Jingo88 commented on apps/web/src/app/reports/pages/reused-passwords-report.component.ts
> +  getAllCiphers(): Promise<CipherView[]> {
ah thanks, Added protected back and updated the specs to address it.

2023-10-24 22:13 UTC, shane-melton commented on apps/web/src/app/reports/pages/exposed-passwords-report.component.html
> +          <td>
Nice, thanks for doing that!

2023-10-24 22:23 UTC, shane-melton approved these changes
My comment was resolved and looks good to go!

2023-10-27 08:55 UTC, eliykat approved these changes
Looks good, thanks! A couple of optional suggestions, up to you.

2023-10-27 08:55 UTC, eliykat commented on apps/web/src/app/reports/pages/exposed-passwords-report.component.ts
> +    this.ciphers = [...exposedPasswordCiphers];
Is there any need to clone the `exposedPasswordCiphers` array? Why not just `this.ciphers = exposedPasswordCiphers`?

2023-10-27 08:55 UTC, eliykat commented on apps/web/src/app/reports/pages/exposed-passwords-report.component.ts
> +      const { type, login, isDeleted, edit, viewPassword, id } = ciph;
⛏️  nit: I suggest `c` or `cipher`, not something in between :P

2023-10-27 14:22 UTC, Jingo88 commented on apps/web/src/app/reports/pages/exposed-passwords-report.component.ts
> +    this.ciphers = [...exposedPasswordCiphers];
ah you're right. they are in the same place so it wouldn't matter. I wrote that out of habit for reducing pass by references

2023-10-27 15:27 UTC, Jingo88 commented on apps/web/src/app/reports/pages/exposed-passwords-report.component.ts
> +      const { type, login, isDeleted, edit, viewPassword, id } = ciph;
haha i def agree with that sentiment, but as i was working in the files I kind of wanted a name longer than c and also something to different cause there's so many lines with `cipher` in here.

2023-10-31 15:57 UTC, djsmith85 approved these changes

2023-11-01 20:38 UTC, willmartian approved these changes

2023-11-17 16:58 UTC, merged