[CL-107] add bit-layout component
bitwarden/clients pull request #6016
Opened 2023-08-11 15:49 UTC by willmartian

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-08-14 10:37 UTC, Hinton requested changes
A few teaks.

2023-08-14 10:37 UTC, Hinton commented on bitwarden_license/bit-web/src/app/secrets-manager/layout/layout.component.html
> +  <nav slot="sidebar">
I view `nav` as being more related to the sidebar content than the outlet. I.e. should we move in `nav` into the `navigation.component`?

This would clean up this component slightly.

```html
<bit-layout>
  <router-outlet name="sidebar" slot="sidebar"></router-outlet>
  <router-outlet></router-outlet>
</bit-layout>
```

2023-08-14 10:37 UTC, Hinton commented on libs/components/src/layout/layout.stories.ts
> +    template: /*html*/ `
This needs to be uppercase to work.

```suggestion
    template: /* HTML */ `
```

2023-08-14 10:37 UTC, Hinton commented on libs/components/src/layout/layout.stories.ts
> +    template: `
Add `html` here to?

```suggestion
    template: /* HTML */ `
```

2023-08-14 10:37 UTC, Hinton commented on libs/components/src/layout/layout.component.ts
> +  }
This is an implementation detail of the web vault currently. Would it make more sense to keep that logic in web for now?

2023-08-14 21:47 UTC, willmartian commented on libs/components/src/layout/layout.stories.ts
> +    template: /*html*/ `
@Hinton Are you using a specific vscode extension? I am using [Inline HTML](https://marketplace.visualstudio.com/items?itemName=pushqrdx.inline-html), which expects a lowercase comment. 

Perhaps we could add this (or a different extension) as a recommended workspace extension?

2023-08-14 21:47 UTC, willmartian commented on bitwarden_license/bit-web/src/app/secrets-manager/layout/layout.component.html
> +  <nav slot="sidebar">
Good call. Resolved in [0d7a7f7](https://github.com/bitwarden/clients/pull/6016/commits/0d7a7f7c63ec06817949d5838ec4fdd384c95a40).

2023-08-14 22:12 UTC, Hinton commented on libs/components/src/layout/layout.stories.ts
> +    template: /*html*/ `
Prettier handles it if it's uppercase and has spaces. https://github.com/prettier/prettier/blob/feb6b519ee0e23eeb272227825ad84ecf1af05ab/src/language-js/embed.js#L289. An alternative is to define a html template literal i.e.
```ts
html`
```

2023-08-15 02:34 UTC, willmartian commented on libs/components/src/layout/layout.component.ts
> +  }
That is fine.

As far as I can tell, it looks like the `layout_frontend` class is only utilized by unauthed pages? Could this class be removed from the [web vault body](https://github.com/bitwarden/clients/blob/71e076b305bc9275bd90b2f13d0ef7d908e23efa/apps/web/src/index.html#L16), so we don't need so many calls to `classList.remove("layout_frontend")`?

2023-08-15 09:25 UTC, Hinton commented on libs/components/src/layout/layout.component.ts
> +  }
I don't have confidence in that being possible. I believe there are scenarios in dev mode where you bypass the auth pages and`layout_frontend` is added to the index.html.

I think it would be nicer if we nested routes in the web vault in a way that lets us have a single place for removing the class though. (Or have a router guard that does it)

2023-08-15 09:27 UTC, Hinton commented on libs/components/src/layout/layout.stories.ts
> +    template: /* HTML */ ` <bit-layout></bit-layout> `,
```suggestion
    template: /* HTML */ `<bit-layout></bit-layout>`,
```

2023-08-16 19:36 UTC, Thomas-Avery requested changes
Looks good. 

Will need to run `npm run prettier` to get lint to pass.

2023-08-16 22:44 UTC, Thomas-Avery approved these changes

2023-08-17 08:55 UTC, Hinton approved these changes

2023-08-23 22:54 UTC, merged