[CL-103] add Tailwind breakpoints
bitwarden/clients pull request #6021
Opened 2023-08-11 22:42 UTC by willmartian

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Enable breakpoints in the base Tailwind config. This will allow devs to target different screen sizes using Tailwind's [responsive modifiers](https://tailwindcss.com/docs/responsive-design).

```html

<img class="tw-w-16 md:tw-w-32 lg:tw-w-48" src="...">
```

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-08-14 08:40 UTC, Hinton requested changes
Could we not use the default tailwind screens? The only difference seems to be the existence of `xs` which I'm not sure we need, do we plan on having different logic for screens sub 640xp and sub 360px.

2023-08-14 08:40 UTC, Hinton commented on libs/components/tailwind.config.base.js
> +    theme: {
We seem to have nested `theme.theme.screens` here. I believe we're falling back to the built in screens.

2023-08-15 03:05 UTC, willmartian commented on libs/components/tailwind.config.base.js
> +    theme: {
Fixed nested `theme.theme.screens` in [172255b](https://github.com/bitwarden/clients/pull/6021/commits/172255b90edd30c2bcd4225a8bf1ce7c7580037c)

2023-08-15 09:18 UTC, Hinton commented on libs/components/tailwind.config.base.js
> +      xs: "360px",
Tailwind uses a mobile first breakpoint system by default. Which we are extending here. Mobile first means you design for your smallest resolution first and then gradually move upwards and apply rules that apply for larger resolutions.

Adding a rule for `xs` means we can style displays smaller than `360px` differently. Is that what we want?

2023-08-15 09:18 UTC, Hinton commented on libs/components/tailwind.config.base.js
> +      sm: "676px",
Tailwind uses 640, for reference the iPhone SE 2020 in landscape mode is 667px. This means we won't be able to style displays for that resolution.

2023-08-15 09:18 UTC, Hinton commented on libs/components/tailwind.config.base.js
> +      xl: "1200px",
Any reason for diverging from tailwinds default? I.e. `1024` and `1280`. In the past this has caused confusion amount developers.

2023-08-15 14:13 UTC, danielleflinn commented on libs/components/tailwind.config.base.js
> +      xl: "1200px",
Let's use the tailwind defaults for breakpoints so that things are consistent with the Tailwind documents.

2023-08-15 14:13 UTC, danielleflinn commented on libs/components/tailwind.config.base.js
> +      xs: "360px",
We can remove the `xs` size for now and add it in if in the future we see a need for it.

2023-08-15 17:57 UTC, willmartian commented on libs/components/tailwind.config.base.js
> +      xl: "1200px",
Resolved in [f54ee7b](https://github.com/bitwarden/clients/pull/6021/commits/f54ee7bef4a307e7f3ec6eb7323d44e91b40de78)

2023-08-15 17:57 UTC, willmartian commented on libs/components/tailwind.config.base.js
> +      sm: "676px",
Using default breakpoints, resolved in [f54ee7b](https://github.com/bitwarden/clients/pull/6021/commits/f54ee7bef4a307e7f3ec6eb7323d44e91b40de78)

2023-08-15 17:58 UTC, willmartian commented on libs/components/tailwind.config.base.js
> +      xs: "360px",
Resolved in [f54ee7b](https://github.com/bitwarden/clients/pull/6021/commits/f54ee7bef4a307e7f3ec6eb7323d44e91b40de78)

2023-08-15 18:04 UTC, Hinton approved these changes

2023-08-15 22:23 UTC, merged