[PM-3455] Allow adding and autofilling Cards and Identities via Context Menu
bitwarden/clients pull request #6050
Opened 2023-08-16 18:25 UTC by jprusik

## Type of change

- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

Add items to the Bitwarden context menu to allow users to autofill Cards and Identities as well as add Login, Card, or Identity ciphers when none of a given type are available.

## Code changes

- Updated context menu groupings and text labels
- When a cipher type is not available, and an action for that type is selected in the context menu, the submenu for that action will allow the user to create a cipher of that type
  - This includes login ciphers; previously the submenu would read "no matching logins"
- Additionally, allow identity and card autofills via messages to enable testing and future feature work

## Screenshots

![Screenshot 2023-09-07 at 4 25 55 PM](https://github.com/bitwarden/clients/assets/1556494/f8d8f1d2-af9c-4236-b8e2-feb0b6c3bdf8)
![Screenshot 2023-09-07 at 4 26 23 PM](https://github.com/bitwarden/clients/assets/1556494/89f7868a-8c33-4346-847b-600e3f306d9c)
![Screenshot 2023-09-07 at 4 22 33 PM](https://github.com/bitwarden/clients/assets/1556494/57149f50-6c24-428c-9592-c2041cb871ac)
![Screenshot 2023-09-07 at 4 23 01 PM](https://github.com/bitwarden/clients/assets/1556494/c39f635d-04e1-4056-bfcd-c885f310439f)
![Screenshot 2023-09-08 at 10 49 28 AM](https://github.com/bitwarden/clients/assets/1556494/1b193e0a-1b0a-4a95-80e7-d724e1d04a36)
![Screenshot 2023-09-08 at 10 49 22 AM](https://github.com/bitwarden/clients/assets/1556494/583036ec-0fc2-4a27-8c46-1ee46082dfb4)
![Screenshot 2023-09-08 at 10 26 35 AM](https://github.com/bitwarden/clients/assets/1556494/0fd20861-8403-47a7-9615-629fd712795c)

2023-09-07 20:46 UTC, jprusik commented on apps/browser/src/background/runtime.background.ts
> +          }
These are not exposed to any UI at the moment - for now they primarily enable our automated testing around these features.

2023-09-07 20:48 UTC, jprusik commented on apps/browser/src/vault/popup/components/vault/add-edit.component.ts
> +      this.messagingService.send("closeTab", { delay: 500 });
1 second felt a little too unnatural for feedback to user actions for this, so I bumped it down a bit

2023-09-07 21:10 UTC, jprusik commented on libs/common/src/vault/services/cipher.service.ts
> +        !cipherIsLogin
Opinionated change, not strictly required for this PR:

This check added here because `includeOtherTypes` can include the Login cipher type, which results in returning all vault Login ciphers, which appears to be unintended behaviour and is antithetical to the implied purpose of a method named `getAllDecryptedForUrl`.

2023-09-08 20:28 UTC, danielleflinn submitted a review, later dismissed

2023-09-12 10:20 UTC, Hinton requested changes

2023-09-12 10:20 UTC, Hinton commented on apps/browser/src/platform/popup/abstractions/browser-popout-window.service.ts
> +  openCipherCreation(
I don't think we want to add every single type of action here. Platform would want a single function that accepts an arbitrary url and the creation of the url should be located in team owned code.

2023-09-12 10:20 UTC, Hinton commented on apps/browser/src/background/runtime.background.ts
I would like for us to figure out a way to not have every command in this file.

2023-09-12 16:23 UTC, jprusik commented on apps/browser/src/platform/popup/abstractions/browser-popout-window.service.ts
> +  openCipherCreation(
Hey @Hinton thanks for taking a look at these changes!

Is this a concern of this PR/context menu update? It seems like a broader architectural issue and question around how we should handle browser popups (which this PR is unopinionated about).

2023-09-12 18:01 UTC, cagonzalezcs requested changes
Solid start, provided feedback and suggestions.

Biggest change request here is removal of the "open a new tab" workflow, which is a conflict with the UX we are expecting for end users to work through.

2023-09-12 18:01 UTC, cagonzalezcs commented on apps/browser/src/vault/popup/components/vault/add-edit.component.ts
> +    }
This is going to close the popout in cases where the user is not leveraging a single use popout. This needs to be updated to reference the sender tab id to verify that a popout should close after the current action is complete.

2023-09-12 20:43 UTC, jprusik commented on apps/browser/src/vault/popup/components/vault/add-edit.component.ts
> +    }
Ah yeah, I missed this one; thanks 👍

2023-09-12 20:52 UTC, jprusik commented on apps/browser/src/platform/popup/abstractions/browser-popout-window.service.ts
> +  openCipherCreation(
I don't have strong opinions on the browser popout service at this time; I do think we should handle it as a separate concern to gather broader consensus before execution.

This PR doesn't care though - we're essentially adding new entry points to existing experiences; what those experiences are/will be doesn't affect the construction of those entry points.

2023-09-13 13:52 UTC, Hinton commented on apps/browser/src/platform/popup/abstractions/browser-popout-window.service.ts
> +  openCipherCreation(
Since this PR adds more non-generic methods it's a concern with this PR. Platform shouldn't own a multitude of methods to do different things in the popout service.

2023-09-15 19:41 UTC, jprusik commented on apps/browser/src/autofill/browser/main-context-menu-handler.ts
> +      id: `${AUTOFILL_CARD_ID}_${SEPARATOR_ID}` + 1,
Ah yeah, that was a holdover from a different submenu configuration - don't need it here as there's only one separator in these menus.

2023-09-15 20:37 UTC, jprusik commented on apps/browser/src/autofill/browser/context-menu-clicked-handler.ts
> +          break;
Imo, ternaries are fine for simple assignments like this. We still need to check `menuItemId` to break early, which could be simply checking if `cipherType` is truthy after assignment.

Keep in mind that the cases here are not actions - they're parent menu items, which now conditionally have subitems that trigger actions (like creating a new cipher) on the basis of cipher type, not action grouping.

I'll play around with this a bit, but I originally went back and forth on trying to refactor this entirely; I ended up erring on the side of changing as little as possible for the time being.

2023-09-18 16:18 UTC, jprusik commented on apps/browser/src/background/runtime.background.ts
> +          const addEditCipherUrl = isNewCipher
Agreed - the only remaining place this was being called from was the notification bar. Addressed in 51d74fc2982e292661a9b16ec154436a8c62b06b

2023-09-18 16:19 UTC, jprusik commented on apps/browser/src/background/runtime.background.ts
> +        }
I'm not sure this check is strictly needed, but given the typing guidance, erred on the side of caution.

2023-09-18 18:22 UTC, jprusik commented on apps/browser/src/background/runtime.background.ts
> +            await this.autofillService.doAutoFillNonLoginActiveTab(
👍 27609f2417eec17dc58011e9d1e27be51f9f65ca

2023-09-18 18:23 UTC, jprusik commented on apps/browser/src/vault/popup/components/vault/add-edit.component.ts
> +    }
d335cd5323b1360ea3ace92813794dd4c974b9eb

2023-09-18 20:36 UTC, jprusik commented on apps/browser/src/vault/popup/components/vault/add-edit.component.ts
> +      this.messagingService.send("closeTab", { delay: 500 });
> _1 second felt a little too unnatural for feedback to user actions for this, so I bumped it down a bit_

This is unrelated, and addressed in separate incoming work, so removing it from this set of changes.

2023-09-18 20:44 UTC, jprusik commented on apps/browser/src/autofill/services/autofill.service.ts
> +    const cipher: CipherView = ciphers[0] || null;
We don't; this is for scenarios where the user could not indicate the intended cipher (e.g. selecting "unlock vault" from the "Autofill Card" submenu), so we take our best guess as to user intent. Since we're not including keyboard updates for autofilling these types of ciphers, having a method like `getNextCipherForUrl` didn't make sense to me. I figured we can return to it in a future iteration if we decide it's worthwhile.

2023-09-18 20:51 UTC, cagonzalezcs submitted a review, later dismissed
Looks good, move forward with this and we'll incorporate fixes for the Popouts within the refactor PR.

2023-09-18 20:55 UTC, jprusik commented on apps/browser/src/platform/popup/abstractions/browser-popout-window.service.ts
> +  openCipherCreation(
@cagonzalezcs has begun work to address that concern in https://github.com/bitwarden/clients/pull/6296 - if this PR goes out before that one, he'll address this there, if that PR goes out first, I'll update this PR with service changes.

2023-09-18 20:56 UTC, jprusik commented
Hey @Hinton - please give this PR another look when you have a chance.

2023-09-19 20:23 UTC, gbubemismith submitted a review, later dismissed

2023-09-19 20:51 UTC, jprusik commented
![Screenshot 2023-09-19 at 4 50 37 PM](https://github.com/bitwarden/clients/assets/1556494/9fe8166d-795a-4f77-ac88-5e2f5168dae1)

resolved against one-liner merged to master from https://github.com/bitwarden/clients/pull/6242

2023-09-20 18:17 UTC, cagonzalezcs approved these changes

2023-09-21 10:17 UTC, Hinton approved these changes
My concerns will be addressed in #6296. Not sure which orders these will be merged, but since #6296 changes a few things related to add-edit component and those needs to be rebased and re-tested prior to merge.

2023-09-29 21:20 UTC, merged

2023-10-01 18:32 UTC, cagonzalezcs commented on apps/browser/src/vault/popup/components/vault/add-edit.component.ts
> +      this.messagingService.send("closeTab", { delay: 500 });
@bwbug No worries, you're more than welcome to jump in on the discussion.

Currently there are no plans for modifying the `Tab` view of the extension, or any of the views within the extension popup in a significant manner. The work done within this PR was to facilitate greater access to autofilling items within the context menu explicitly, and doesn't really have much to do with the vault popup itself.