PM-1224 Ensure Passkeys Not Requested From Iframes
bitwarden/clients pull request #6057
Opened 2023-08-17 16:03 UTC by Jingo88

```
- [ ] Bug fix
- [ X ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Do not allow passkeys to be requested from iframes.

## Code changes

* Added an `isNotIframeCheck` method to the `page-script` file. The return boolean value will be passed to the `mapCredentialCreationOptions` inside `navigator create/get` methods. 
* Added the `DOM Exception NotAllowedError` logic to the `assertCredential` inside the `fido2-client.service`

## Screenshots

* The below images are looking at passkey requests from a iframe login on the [icloud website](https://www.icloud.com/)

BEFORE Implemented Code passkeys were requested

![icloud_iframe_passkey_before](https://github.com/bitwarden/clients/assets/8302660/695ce8ed-5340-4559-9401-a41295205984)

AFTER Implementing iframe check

![icloud_iframe_passkey_after](https://github.com/bitwarden/clients/assets/8302660/10f53aa6-161f-44f8-a68e-10d8fe9c63a6)

2023-08-17 17:47 UTC, gbubemismith requested changes
This is looking good. Just a small comment

2023-08-17 17:47 UTC, gbubemismith commented on apps/browser/src/vault/fido2/content/page-script.ts
>          // TODO: Fix sameOriginWithAncestors!
I think we can remove the TODO comments

2023-08-17 17:47 UTC, gbubemismith commented on apps/browser/src/vault/fido2/content/page-script.ts
>          // TODO: Fix sameOriginWithAncestors!
same here

2023-08-18 21:12 UTC, gbubemismith commented on libs/common/src/vault/services/fido2/fido2-client.service.ts
> +  errorCheckHandler(params: any, enableFido2VaultCredentials: boolean, parsedOrigin: any) {
Can we have a different name for this function? e.g. `validateRequestParameters`,  `verifyCredentialRequest`

2023-08-18 21:17 UTC, gbubemismith commented on libs/common/src/vault/services/fido2/fido2-client.service.ts
> +  errorCheckHandler(params: any, enableFido2VaultCredentials: boolean, parsedOrigin: any) {
I noticed that params and parsedOrigin are both typed as any. This makes the code more error-prone since we lose the benefits of type-checking. It might make more sense to have a separate interface or type for the `ErrorParams`

2023-08-18 21:23 UTC, gbubemismith requested changes
I like how you've modularized the error handling into a separate function. It makes things a lot cleaner. Thanks for doing this.

2023-08-24 17:09 UTC, gbubemismith approved these changes
LGTM!

2023-08-25 08:09 UTC, coroiu reviewed
Some minor comments and then one very complicated, sorry :)

2023-08-25 08:09 UTC, coroiu commented on apps/browser/src/vault/fido2/content/page-script.ts
> +const isNotIframeCheck = () => {
nit(non-blocking): use `function` to define functions

2023-08-25 08:09 UTC, coroiu commented on apps/browser/src/vault/fido2/content/page-script.ts
> +  }
question: why are putting this in a try catch? Couldn't we simply write?:

```
return window.self === window.top
```

2023-08-25 08:09 UTC, coroiu commented on apps/browser/src/vault/fido2/content/page-script.ts
> +const isNotIframeCheck = () => {
suggestion: could we rename this to something that doesn't use negations in the function/variable name? Or maybe just name it `isSameOriginWithAncestors` to align with established terminology?

2023-08-29 19:19 UTC, gbubemismith commented on apps/browser/src/vault/fido2/content/page-script.ts
> +  }
I think this was used in case accessing `window.top` throws an exception and a similar function exists in `notification-bar.ts`

2023-08-29 19:21 UTC, gbubemismith commented on apps/browser/src/vault/fido2/content/page-script.ts
> +const isNotIframeCheck = () => {
Yeah that makes sense

2023-08-30 08:22 UTC, coroiu commented on libs/common/src/vault/services/fido2/fido2-client.service.ts
> +    }
Interesting, the webauthn spec does not include this check in their algorithm. Must be a mistake, nice addition!

issue: Could you add test cases for this?

2023-09-08 16:00 UTC, merged