PM-1722 gracefully fail if site prompts user for passkey on load
bitwarden/clients pull request #6089
Opened 2023-08-22 20:27 UTC by Jingo88

```
- [ ] Bug fix
- [ X ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Some sites will prompt you to use your passkey the moment you navigate to their sign-in page. Our objective is to gracefully fail that request, and the user will have to take some form of action (clicking use passkey, typing in username, etc) to use their passkey. 

## Code changes

page-script has been updated to look for an `mediation` key in the `options` argument for `navigate credentials get`. It will throw an error if the mediation value is `optional`

## Testing Locally

I found two sites that will prompt for using an existing passkey on load. With the new `mediation optional` logic the users will have to take action to use their passkeys. Those sites are [Kayak](https://www.kayak.com/) and [BestBuy](https://www.bestbuy.com/)

## Screenshots

Kayak after the user submits their email

![kayak_passkey](https://github.com/bitwarden/clients/assets/8302660/9208f97f-800d-4dc6-9874-c573256ec53c)

BestBuy after the user clicks "sign in with passkey"

![bestbuy_passkey](https://github.com/bitwarden/clients/assets/8302660/f3fd6aac-d640-4ce2-8d2c-00fceb9fbfc7)

2023-08-23 05:43 UTC, gbubemismith reviewed
Thanks for working on this. LGTM! @coroiu, would you mind reviewing this as well?

2023-08-23 08:37 UTC, coroiu requested changes
Hmm, are we sure that we

2023-08-23 08:37 UTC, coroiu commented on apps/browser/src/vault/fido2/content/page-script.ts
> +  if (options?.mediation && options.mediation !== "optional") {
suggestion: simplify:)
```suggestion
  if (options?.mediation !== "optional") {
```

2023-08-23 08:37 UTC, coroiu commented on apps/browser/src/vault/fido2/content/page-script.ts
> +    throw new Error("Webauthn Conditional UI not supported in this browser.");
issue: I'm not sure that we wanna short circuit the request like this. The browser might still have native support for conditional UI and throwing an error here will effectively disable that support

2023-08-23 20:33 UTC, Jingo88 commented on apps/browser/src/vault/fido2/content/page-script.ts
> +    throw new Error("Webauthn Conditional UI not supported in this browser.");
Thanks for the suggestion. I moved the the logic into the try catch and updated the error to throw a `FallbackRequestedError`

2023-08-23 20:34 UTC, Jingo88 commented on apps/browser/src/vault/fido2/content/page-script.ts
> +  if (options?.mediation && options.mediation !== "optional") {
I tried shortening the logic to `options?mediation !== "optional` however some sides don't pass the `mediation` keyword at all, and in those cases I believe well want to keep the `options?.mediation` conditional and skip throwing the error.

2023-08-24 14:25 UTC, coroiu commented on apps/browser/src/vault/fido2/content/page-script.ts
> +    throw new Error("Webauthn Conditional UI not supported in this browser.");
Looks good!

2023-08-24 14:26 UTC, coroiu approved these changes
Looks good!

2023-09-08 13:28 UTC, merged