[PM-3612] Bug - Reprompt prevents autofill keyboard shortcut from cycling fill ciphers
bitwarden/clients pull request #6096
Opened 2023-08-23 18:39 UTC by jprusik

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-08-23 18:40 UTC, jprusik commented on apps/browser/src/autofill/services/autofill.service.ts
> -      (await this.userVerificationService.hasMasterPasswordAndMasterKeyHash())
This isn't relevant if the cipher is available

2023-08-28 17:02 UTC, jprusik commented on apps/browser/src/autofill/services/autofill.service.ts
> +    if (cipher.reprompt !== CipherRepromptType.None) {
`hasMasterPasswordAndMasterKeyHash` was causing issues when testing, so I opted for `hasMasterPassword` instead, which is closer to what we actually care about for this check, anyway.

updated in 81cb9d2bd2a7f1787afa774d6e69c13529de1fdd

2023-08-28 20:30 UTC, jprusik commented on apps/browser/src/autofill/services/autofill.service.ts
> +      (await this.userVerificationService.hasMasterPassword())
Per discussion here: https://github.com/bitwarden/clients/pull/6096#discussion_r1307687653

`hasMasterPasswordAndMasterKeyHash` was preventing cipher rotation from working properly (for some yet-to-be-determined reason) when I was testing. Taking it out of the check or replacing it with `hasMasterPassword` immediately allowed cipher rotation to work properly again.

Since we do not want to reprompt if the use has no master password to enter (a dead-end user path), that leaves us with `hasMasterPassword`.

@trmartin4 brought up the case where a user has a master password but hasn't logged in with it recently because their organization set up passwordless and they now use that to log in. In that case, the user will be reprompted even though passwordless is active on their account.

I would argue this is beneficial behaviour in that case because ideally, we wouldn't disable/circumvent reprompt at all, as a clear indicator of the user's intent/desire. In this case, the user can still benefit from the reprompt they originally requested (and can turn it off at any time).

2023-08-30 17:33 UTC, cagonzalezcs requested changes

2023-08-30 17:33 UTC, cagonzalezcs commented on apps/browser/src/autofill/services/autofill.service.ts
> +      }
```suggestion
      if (fromCommand) {
        this.cipherService.updateLastUsedIndexForUrl(tab.url);
      }
      
      await BrowserApi.tabSendMessageData(tab, "passwordReprompt", {
        cipherId: cipher.id,
        action: "autofill",
      });
```

As per our conversation, if we handle updating the cipher before the reprompt, we allow users the ability to close the reprompt window and cycle the next cipher. If the reprompt successfully goes through, then we treat that as the most recently filled element and remain at a status quo.

2023-08-30 19:25 UTC, cagonzalezcs approved these changes
Looks good

2023-09-08 14:25 UTC, merged