[PM-3226] Adding session to ReferenceEventRequest
bitwarden/clients pull request #6114
Opened 2023-08-25 15:28 UTC by aj-rosado

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Adding the session value to reference data on trial-initiation

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-08-25 20:36 UTC, djsmith85 approved these changes

2023-08-30 16:35 UTC, JaredSnider-Bitwarden approved these changes
LGTM!

2023-08-30 17:12 UTC, jlf0dev requested changes
Please leave a comment explaining the regex

2023-08-30 17:12 UTC, jlf0dev commented on apps/web/src/app/auth/trial-initiation/trial-initiation.component.ts
> +      const regex = /_ga_QBRN562QQQ=([^.]+)\.([^.]+)\.(\d+)/;
Can you please leave a comment explaining the intention of the regex?

2023-08-30 20:06 UTC, jlf0dev approved these changes
Thanks! LGTM

2023-08-30 20:27 UTC, merged

2023-08-30 20:27 UTC, aj-rosado commented
Merging as requested by QA to test on cloud