[PM-2806] Migrate send access to Component Library
bitwarden/clients pull request #6139
Opened 2023-08-29 15:13 UTC by aj-rosado

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

The main objective of this task is the migration to ComponentLibrary.
Used the opportunity to refactor a bit the SendAccess class to make it simpler creating separate components for the content.
Also made the components standalone.

## Code changes

Created new **SendPasswordComponent**, **SendFileComponent** and **SendTextComponent** that separates the different send screens logic making it more modular. All sends use component library and changed the **SendPasswordComponent** logic to use ReactiveForms.

- **App.module.ts:** Added new standalone components
- **Access.component.html:** Changed the layouts to use Component Library. Removed specific screen code and replaced by components
- **Access.component.ts:** Changed to standalone component, removed and adapted code that made sense to have his own component. 
- **messages.json**: Updated text messages to new screens

## Screenshots

### Old Layouts

**Send Access Text**
<img width="558" alt="old_text_send" src="https://github.com/bitwarden/clients/assets/109146700/60d8a10f-4c5a-4208-8c72-22c0c30827c4">

**Send Access Text Hidden**
<img width="558" alt="old_text_hidden_send" src="https://github.com/bitwarden/clients/assets/109146700/b7494c44-a523-4e61-9fea-915e2f4c03e0">
<img width="558" alt="old_text_hidden_visible_send" src="https://github.com/bitwarden/clients/assets/109146700/516219eb-2617-4379-bba4-cc576709f4eb">

**Send Access File**
<img width="558" alt="old_file_send" src="https://github.com/bitwarden/clients/assets/109146700/b47d5320-c3cb-4e2e-b472-bc24ecfa3773">

**Send Access Password**
<img width="558" alt="old_password_send" src="https://github.com/bitwarden/clients/assets/109146700/12bb9615-181a-4a63-a85d-db23e3d48b8a">

**Send Email Hidden**
<img width="558" alt="old_email_hidden_send" src="https://github.com/bitwarden/clients/assets/109146700/a67fb706-f51c-4efa-b619-c15bd766e480">

**Unexpected Er
<img width="558" alt="old_unexpected_error_Send" src="https://github.com/bitwarden/clients/assets/109146700/136940d4-cb9d-4654-bb96-653dd38733b8">
ror**

### New Layouts

**Send Access Text**
<img width="558" alt="text_send" src="https://github.com/bitwarden/clients/assets/109146700/9fab7e94-2518-4026-93a2-85debd5a0eba">

**Send Access Text Hidden**
<img width="558" alt="text_hidden_send" src="https://github.com/bitwarden/clients/assets/109146700/da4a0fc4-708e-42fb-b7ea-1e64f2d19058">
<img width="558" alt="text_hidden_visible_send" src="https://github.com/bitwarden/clients/assets/109146700/536a2c02-36f6-4c3f-a321-6e0fdb1511a5">

**Send Access File**
<img width="558" alt="file_send" src="https://github.com/bitwarden/clients/assets/109146700/8599f249-6009-4d4f-ad4e-d9c9d9f2dd7e">

**Send Access Password**
<img width="558" alt="password_protected_send" src="https://github.com/bitwarden/clients/assets/109146700/df694d99-e98e-4100-9411-c6d258df25ec">

**Send Email Hidden**
<img width="558" alt="email_hidden_send" src="https://github.com/bitwarden/clients/assets/109146700/c359d019-62ec-47c8-a888-dbf708a719be">

**Expired Send**
<img width="558" alt="expired_send" src="https://github.com/bitwarden/clients/assets/109146700/52bc2a6b-4991-49ef-be2d-35c0db82248f">

**Unexpected Error**
<img width="558" alt="unexpected_error_send" src="https://github.com/bitwarden/clients/assets/109146700/cf457431-e4e7-4ff9-84b8-2d192893c019">

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-08-29 20:44 UTC, danielleflinn submitted a review, later dismissed

2023-08-31 19:08 UTC, Hinton reviewed
@willmartian can you review the CL changes here.

I believe there are a few non migrated classes, old form submission logic, and the breakup into multiple components might be somewhat odd.

2023-08-31 19:08 UTC, Hinton commented on apps/web/src/app/app.module.ts
> +    SendAccessPasswordComponent,
We have two app.module files. This only adds them to one. There is a `OssModule` that can be used here.

2023-08-31 19:08 UTC, Hinton commented on apps/web/src/app/app.module.ts
> +    SendAccessPasswordComponent,
Can any of these components be used independently? If not they shouldn't be imported here.

2023-09-06 01:15 UTC, willmartian commented on apps/web/src/app/tools/send/access.component.html
> +      </div>
This `div` isn't needed; put `*ngIf` on `app-send-access-password`

2023-09-06 14:33 UTC, willmartian requested changes
Good work! 

I'm not sure I see the value in splitting `send-access-file`, `send-access-password`, and `send-access-text` out of `access.component`. 

Reasons to split a component out: 
1. It is reusable elsewhere
2. It is very complex

I don't think these will be reused, and as for complexity, they are no more complex than any other form control. I think splitting it out actually adds some complexity because now you are passing data with `Inputs` and `Outputs`. Lmk your thoughts!

2023-09-06 14:33 UTC, willmartian commented on apps/web/src/app/tools/send/send-access-file.component.html
> +  [block]="true"
Rather than tracking the loading state manually, we should use an [async action](https://components.bitwarden.com/?path=/docs/component-library-async-actions-standalone-documentation--docs) here.

2023-09-06 14:33 UTC, willmartian commented on apps/web/src/app/tools/send/send-access-file.component.ts
> +  downloading = false;
Protected or public?

2023-09-06 14:33 UTC, willmartian commented on apps/web/src/app/tools/send/send-access-password.component.html
> +      [block]="true"
Instead of a click handler here, we can use `bitSubmit` on the `form` element: https://components.bitwarden.com/?path=/docs/component-library-async-actions-in-forms-documentation--docs

2023-09-06 14:33 UTC, willmartian commented on apps/web/src/app/tools/send/send-access-password.component.ts
> +  formGroup = this.formBuilder.group({
Protected vs public

2023-09-06 14:33 UTC, willmartian commented on apps/web/src/app/tools/send/send-access-password.component.ts
> +  }
Protected vs public

2023-09-06 14:33 UTC, willmartian commented on apps/web/src/app/tools/send/send-access-text.component.html
> +</bit-form-field>
Can we use a reactive form control instead of `ngModel`? Even though this isn't a true form, it is probably best to stick to one or the other everywhere.

2023-09-06 14:33 UTC, willmartian commented on apps/web/src/app/tools/send/send-access-text.component.ts
Use protected for data that is only used in the template.

2023-09-06 14:33 UTC, willmartian commented on apps/web/src/app/tools/send/access.component.html
> +    <img class="logo logo-themed" alt="Bitwarden" />
We should either remove `logo` and `logo-themed` and replicate them with Tailwind classes, or create a followup ticket in Jira and do it later.

2023-09-06 14:33 UTC, willmartian commented on apps/web/src/locales/en/messages.json
Instead of changing the values of `downloadFile` and `sendCreatorIndentifier`, we need to create new i18n entries with different keys. As currently written, my understanding is that Crowdin would only update the English i18n here, and this change would not propagate to other languages for translators to pick up. Could you verify this @Hinton ?

2023-09-06 15:25 UTC, aj-rosado commented
> Good work!
> 
> I'm not sure I see the value in splitting `send-access-file`, `send-access-password`, and `send-access-text` out of `access.component`.
> 
> Reasons to split a component out:
> 
> 1. It is reusable elsewhere
> 2. It is very complex
> 
> I don't think these will be reused, and as for complexity, they are no more complex than any other form control. I think splitting it out actually adds some complexity because now you are passing data with `Inputs` and `Outputs`. Lmk your thoughts!

I agree with your reasoning regarding splitting a component. We will add a new Send type in the future that will be more complex than the existing ones, me and @djsmith85 thought this would be a good opportunity to split this component to reduce the complexity and separate the logic before adding more types to send

I also agree that currently it isn't big or complex enough to justify this change and that it actually adds complexity, although I believe that can help with addition of new send types and keeping the logic separated from each other

I'm happy to have more opinions on this 😄

2023-09-06 21:28 UTC, djsmith85 commented on apps/web/src/locales/en/messages.json
@aj-rosado: Yes, the keys here need to be change when the content of the message is changed.

2023-09-26 10:28 UTC, aj-rosado commented on apps/web/src/app/tools/send/access.component.ts
>  // eslint-disable-next-line rxjs-angular/prefer-takeuntil
this is necessary because we are not implementing the `ngOnDestroy`

In all cases we are using the `this.route.params.subscribe` we are not implementing the `ngOnDestroy` and we are disabling the `prefer-takeuntil`

2023-09-26 10:29 UTC, aj-rosado commented on apps/web/src/app/tools/send/icons/expired-send.icon.ts
> +export const ExpiredSend = svgIcon`
This svg is already optimized

2023-09-26 10:30 UTC, aj-rosado commented on apps/web/src/app/tools/send/access.component.html
> +    <img class="logo logo-themed" alt="Bitwarden" />
This affects other components and I believe it goes a bit out of scope for this task. I would prefer to do it in a different ticket

2023-10-10 15:08 UTC, aj-rosado commented on apps/web/src/app/tools/send/send-access-password.component.html
> +      #password
not necessary and removed

2023-10-10 15:08 UTC, aj-rosado commented on apps/web/src/app/tools/send/send-access-password.component.html
> +<div class="form-group" [formGroup]="formGroup">
replaced by tw-mb-3

2023-11-01 20:48 UTC, willmartian submitted a review, later dismissed
CL and Tailwind usage LGTM, thanks @aj-rosado 🥳

2023-11-02 10:48 UTC, djsmith85 requested changes

2023-11-02 10:48 UTC, djsmith85 commented on apps/web/src/locales/en/messages.json
> +  },
This might be included due to a wrongly resolved merge-conflict. This likely does not belong to Send.

2023-11-02 10:52 UTC, aj-rosado commented on apps/web/src/locales/en/messages.json
> +  },
yes, that key value was duplicated

2023-11-02 10:54 UTC, djsmith85 submitted a review, later dismissed
Awesome work on this @aj-rosado !

2023-11-09 09:34 UTC, djsmith85 approved these changes

2023-11-17 16:06 UTC, willmartian approved these changes

2023-11-17 16:07 UTC, merged