[PM-2855] [PM-3034] Add Setting to Enable Autofill Overlay
bitwarden/clients pull request #6194
Opened 2023-09-05 20:45 UTC by cagonzalezcs

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

The changes for this PR address three specific concerns:

- We are setting up the autofill overlay to load behind a Launch Darkly feature flag, ensuring we can work with the overlay feature in a conditional manner. The overlay is distinctly tied to Autofill v2, so in order to enable the feature you will need to ensure that both feature flags for `autofill-v2` and `autofill-overlay` are set to a value of `true`.
- The autofill settings page within the extension now presents logic that allows end users the ability to enable/disable autofill as desired. It also has two appearance settings that allow the user the ability to show the overlay list on click of the icon, or on focus of a valid input field. 
- The logic for showing the autofill callout now takes into consideration whether or not a user has the autofill overlay setting turned on. If so, it does not show the callout. 

The one thing that is missing from this implementation is dynamic updating of content script behavior based on the user's chosen options. That's a bigger task overall, and involves more than just the autofill overlay, so we will be addressing it in a future PR.

## Code changes

- **apps/browser/src/_locales/en/messages.json:** Content to be translated representing the settings labels for the autofill overlay.
- **apps/browser/src/autofill/background/overlay.background.ts:** Adjustment to how we are opening the autofill overlay to make a differentiation when the overlay should open on focus of the input element, or on click of the shown icon element.
- **apps/browser/src/autofill/content/abstractions/autofill-init.ts:** Updating the typing info to include a data value for when the overlay should be forced to a fully opened state.
- **apps/browser/src/autofill/content/autofill-init.spec.ts:** Updating the testing suite for `AutofillInit`, which reflects the change in initialization of the class due to the new bootstrap process we're employing.
- **apps/browser/src/autofill/content/autofill-init.ts:** Updates to facilitate the conditional initialization of the `AutofillOverlayContentService` class. With these changes, it is now possible to skip initialization of the overlay logic entirely.
- **apps/browser/src/autofill/content/bootstrap-autofill-overlay.ts:** Bootstraps initialization of autofill v2 with the autofill overlay feature's logic in place
- **apps/browser/src/autofill/content/bootstrap-autofill.ts:** Bootstraps initialization of autofill v2 without the autofill overlay feature.
- **apps/browser/src/autofill/services/abstractions/autofill-overlay-content.service.ts:** Update typing information for the `openAutofillOverlay` public method
- **apps/browser/src/autofill/services/abstractions/autofill.service.ts:** Update typing information for the `InjectAutofillScripts` method of the `AutofillService` class
- **apps/browser/src/autofill/services/autofill-overlay-content.service.ts:** Applying updates to the core autofill content script to facilitate conditionally rendering the overlay's appearance based on user settings. This includes implementing a check within local storage to identify if the overlay should be shown on focus of an input field or on click of the overlay button.
- **apps/browser/src/autofill/services/autofill.service.spec.ts:** Updates to the testing of the `AutofillService` class to facilitate differences in how we inject the autofill logic
- **apps/browser/src/autofill/services/autofill.service.ts:** Updates the `injectAutofillScripts` logic to facilitate conditionally presenting the autofill overlay to the end user based on the set feature flag, and the user setting. If the feature flag or the user setting are not set to show the overlay, then we do not inject that logic for the autofill content script.
- **apps/browser/src/autofill/services/collect-autofill-content.service.ts:** Applying logic to conditionally call the `setupAutofillOverlayListenerOnField` method from the `AutofillOverlayContentService` class. Allows for collecting page details without the overlay dependency present.
- **apps/browser/src/autofill/utils/autofill-overlay.enum.ts:** Adding an enum for the two ways that the autofill overlay can present itself. Used within the settings component as well as the overlay content script
- **apps/browser/src/background/runtime.background.ts:** Incorporating a call to the Launch Darkly feature flag when injecting the autofill scripts
- **apps/browser/src/popup/settings/autofill.component.html:** Updates to the autofill settings component to ensure that users can set the autofill overlay on/off and update the appearance of the overlay itself. These will only appear if the launch darkly feature flag is set.
- **apps/browser/src/popup/settings/autofill.component.ts:** Adding the server config observer to this component to conditionally show the autofill overlay settings. Also adding code required to view and update the autofill overlay settings.
- **apps/browser/src/vault/popup/components/vault/current-tab.component.ts:** Adding logic to potentially hide the autofill callout if the overlay is currently set in the extension.
- **apps/browser/webpack.config.js:** Updating the core autofill v2 scripts to facilitate conditionally initializing autofill v2 with and without the overlay feature
- **libs/common/src/abstractions/settings.service.ts** Adding a public method `getEnableAutoFillOverlay` to the settings service.
- **libs/common/src/enums/feature-flag.enum.ts** Adding the autofill overlay feature flag
- **libs/common/src/platform/abstractions/config/server-config.ts:** Adding a helper method `isAutoFillOverlayActive` to facilitate identification of the autofill overlay feature flag within the autofill settings component.
- **libs/common/src/platform/abstractions/state.service.ts:** Adding methods required to get and set the values that enable the autofill overlay and control the overlay's appearance
- **libs/common/src/platform/models/domain/account.ts:** Adding methods that allow for validating if the overlay is set within a user account and the manner in which the overlay should appear.
- **libs/common/src/platform/services/state.service.ts:** Adding methods required to get and set the values that enable the autofill overlay and control the overlay's appearance. The logic for this is very similar to the methodology used to set the autofill on load setting and it's default values.
- **libs/common/src/services/settings.service.ts:** Adding a method for identifying if the autofill overlay is currently enabled

## Screenshots

https://github.com/bitwarden/clients/assets/16629865/24fd5a25-b421-43aa-9e9d-f1b1bbc9c578

2023-09-11 20:52 UTC, cagonzalezcs commented
Merging this work in, wanna say thank you once again to @RafaelKr for the inspiration on this approach.

2023-09-12 10:30 UTC, Hinton requested changes
Server config shouldn't have to be modified. Settings service and state service seems to be used interchangeable. The purpose of the settings service was to remove direct calls to state service from components.

2023-09-12 10:30 UTC, Hinton commented on libs/common/src/platform/abstractions/config/server-config.ts
> +  }
This doesn't belong to the generic server config. Please use the config service feature flag functionality for this.

2023-09-12 10:30 UTC, Hinton commented on libs/common/src/abstractions/settings.service.ts
> +  getAutoFillOverlayAppearance: () => Promise<number>;
Settings should have setters.

2023-09-12 10:30 UTC, Hinton commented on apps/browser/src/popup/settings/autofill.component.ts
> +  }
This should probably call the settings service.

2023-09-12 10:30 UTC, Hinton commented on apps/browser/src/autofill/utils/autofill-overlay.enum.ts
> +  OnFieldFocus: 2,
Is the plan to support both options?

2023-09-12 15:48 UTC, cagonzalezcs commented on libs/common/src/platform/abstractions/config/server-config.ts
> +  }
This has been removed, as suggested. The boolean flag check is now being done through the config service.

2023-09-12 15:49 UTC, cagonzalezcs commented on libs/common/src/abstractions/settings.service.ts
> +  getAutoFillOverlayAppearance: () => Promise<number>;
Setter methods have been added for the `enableAutoFillOverlay` and `autoFillOverlayAppearance` settings. These are being used now instead of the state service.

2023-09-12 15:50 UTC, cagonzalezcs commented on apps/browser/src/popup/settings/autofill.component.ts
> +  }
These those methods have been updated to call the settings service rather than the state service.

2023-09-12 15:51 UTC, cagonzalezcs commented on apps/browser/src/autofill/utils/autofill-overlay.enum.ts
> +  OnFieldFocus: 2,
@Hinton That is correct, both options are implemented within the overlay and all a user to either present the list of vault items on focus, or to show the list on click of the button.

https://www.figma.com/file/PObYTVXo0re9GwyKJxC8CG/Overlay-popup-interface?type=design&node-id=1241-1766&mode=design&t=lLj6DusA5tuoG5e1-4

2023-10-04 13:59 UTC, merged