[PM-3726] migrate legacy user's encryption key
bitwarden/clients pull request #6195
Opened 2023-09-05 21:49 UTC by jlf0dev

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Legacy encryption users have been unable to login following the key migration. Although we included code to account for legacy accounts within the crypto service, we made the assumption during the login process that a user key should always be available.

The PR detects these accounts and creates a new migration component for them. This new migration component is only available on web currently, so other clients will have their login process short circuited with an error directing them to migrate on web.
## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

![image](https://github.com/bitwarden/clients/assets/24985544/e5890ac5-4c1b-46ad-9d0c-6669db53c4c6)
<img width="1757" alt="image" src="https://github.com/bitwarden/clients/assets/24985544/a967faf3-c784-4247-af0e-7f79e75dfe1d">
<img width="375" alt="image" src="https://github.com/bitwarden/clients/assets/24985544/df7c7f1f-541b-4be2-b6ff-01a8b237d9c1">

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-09-05 23:48 UTC, ike-kottlowski reviewed
Looks good overall. I wonder though, if we have a plan to remove this code after all users have been migrated? This code feels almost like a "one off" that might add bloat to the code base in the long run. Just a thought.

2023-09-05 23:48 UTC, ike-kottlowski commented on apps/cli/src/auth/commands/login.command.ts
> +          "Encryption key migration required. Please login through the web vault to update your encryption key."
I think this should be `this.i18nService.t("encryptionKeyMigrationRequired")` instead of a string. 🤔

2023-09-06 00:45 UTC, JaredSnider-Bitwarden reviewed
Awesome work on this! 

Several clarifying questions below + tests are failing at the moment.

2023-09-06 00:45 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/migrate-encryption/migrate-legacy-encryption.component.ts
> +  selector: "migreate-legacy-encryption",
Nitpick: `migreate` --> `migrate`

2023-09-06 00:45 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/migrate-encryption/migrate-legacy-encryption.component.ts
> +      await this.migrationService.updateKeysAndEncryptedData(
This calls `this.apiService.postAccountKey(request)` and the end. 
#3170 addressed the logout race condition with this logic on key rotation, and it will benefit this process server side as well. 

However, what happens if the user is on an older server? Is there any way to mitigate the race condition which could log the user out before the `updateEmergencyAccesses(...)` and `updateAllAdminRecoveryKeys(...)` can run?

2023-09-06 00:45 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/migrate-encryption/migrate-legacy-encryption.component.ts
Clean component implementation! Nice work on extracting the steps into the service!

2023-09-06 00:45 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/migrate-encryption/migrate-legacy-encryption.service.spec.ts
Tests! 🙌 💯

2023-09-06 00:45 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/login-strategies/password-login.strategy.ts
> +    return !response.key;
❓ : Will this catch key connector users as well?

2023-09-06 00:45 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/migrate-encryption/migrate-legacy-encryption.service.spec.ts
⚠️ : the `migrateFromLegacyEncryptionService › createNewUserKey › validates master password and legacy user` test is failing

2023-09-06 00:45 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/migrate-encryption/migrate-legacy-encryption.service.ts
> +// TODO: This service should be expanded and used for user key rotations in change-password.component.ts
Nice call! This could centralize that distributed logic. Should we create a tech debt item for this?

2023-09-06 00:45 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/migrate-encryption/migrate-legacy-encryption.service.ts
> +  async createNewUserKey(masterPassword: string): Promise<[UserKey, EncString]> {
Nit pick (non blocking): As this action is specifically scoped for legacy users only, we could include legacy in the name so that if we do centralize the logic for creating the user key (ex: `change-password.component.ts`)  in the future it is still clear

2023-09-06 00:45 UTC, JaredSnider-Bitwarden commented on libs/common/src/vault/services/cipher.service.ts
> -    const hasKey = await this.cryptoService.hasUserKey();
What's the reason for this removal again?

2023-09-06 00:45 UTC, JaredSnider-Bitwarden commented on libs/angular/src/auth/components/login.component.ts
> +        return;
Nit: a clarifying comment might be useful for explaining why we early return here - if you track down the translation it's clear enough, but could prevent the need for doing even that.

2023-09-06 00:45 UTC, JaredSnider-Bitwarden commented on libs/angular/src/auth/guards/lock.guard.ts
> +
❓ is this to catch existing users who are already logged in after a lock to let them know that they need to migrate? 

If so, shouldn't this also consider the client that the user is on and only redirect on web (`this.platformUtilsService.getClientType() == ClientType.Web`)?

2023-09-06 15:27 UTC, jlf0dev commented on libs/common/src/vault/services/cipher.service.ts
> -    const hasKey = await this.cryptoService.hasUserKey();
We already get the User Key here with legacy support. We shouldn't be blocking users without User Keys here since they will need to retrieve decrypted ciphers to migrate them

2023-09-06 15:28 UTC, JaredSnider-Bitwarden commented on libs/common/src/vault/services/cipher.service.ts
> -    const hasKey = await this.cryptoService.hasUserKey();
Ah, ok. That makes sense. Thank you for the clarification!

2023-09-06 19:09 UTC, jlf0dev commented on libs/common/src/auth/login-strategies/password-login.strategy.ts
> +    return !response.key;
Confirmed with CloudOps that there are no SSO users with legacy accounts

2023-09-06 19:09 UTC, jlf0dev commented on apps/web/src/app/auth/migrate-encryption/migrate-legacy-encryption.component.ts
> +      await this.migrationService.updateKeysAndEncryptedData(
I've switched the order of these, did we account for older servers in the initial fix?

2023-09-06 19:11 UTC, jlf0dev commented on apps/web/src/app/auth/migrate-encryption/migrate-legacy-encryption.service.ts
> +  async createNewUserKey(masterPassword: string): Promise<[UserKey, EncString]> {
Hopefully legacy in the service name will communicate that. We might want to pull this logic out if we consolidate in the future anyway

2023-09-06 19:12 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/migrate-encryption/migrate-legacy-encryption.component.ts
> +      await this.migrationService.updateKeysAndEncryptedData(
No, the initial fix was purely server side to no longer log the users out on `postAccountKey(...)`

2023-09-06 19:12 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/migrate-encryption/migrate-legacy-encryption.service.ts
> +  async createNewUserKey(masterPassword: string): Promise<[UserKey, EncString]> {
Fair!

2023-09-06 19:34 UTC, JaredSnider-Bitwarden submitted a review, later dismissed
LGTM!

2023-09-06 19:34 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/migrate-encryption/migrate-legacy-encryption.component.ts
> +      await this.migrationService.updateKeysAndEncryptedData(
Per slack discussion, swapping the order seems the best option for now -- even acknowledging that this could introduce a scenario in which emergency access keys and admin acct recovery keys are updated and the `postAccountKey` fails but this should not be as likely.  The pro of this approach is that, for users who do this migration against older servers, they will not be prematurely logged out before the other keys can be updated after posting their new account key.

2023-09-06 21:06 UTC, justindbaur approved these changes
Platform changes look good, just one question for @djsmith85's expertise on locale file stuff.

2023-09-06 21:06 UTC, justindbaur commented on apps/desktop/src/locales/en/messages.json
> +  "encryptionKeyMigrationRequired": {
@djsmith85 What's the rule on updating locale keys again? Should we avoid changing the key or is this correct when we also update the message?

2023-09-06 21:10 UTC, gbubemismith approved these changes
Looks good from the vault's perspective

2023-09-06 21:10 UTC, gbubemismith commented on libs/common/src/vault/services/cipher.service.ts
> -    const hasKey = await this.cryptoService.hasUserKey();
Thanks for clarifying this

2023-09-06 21:12 UTC, cagonzalezcs approved these changes
Looks really solid overall, just presented a couple of non-blocking nits.

This doesn't touch autofill, but let me know if you'd like a re-review/approval at some point.

2023-09-06 21:12 UTC, cagonzalezcs commented on apps/web/src/app/auth/migrate-encryption/migrate-legacy-encryption.component.html
> +          />
Accessibility Nit - Does this `<bit-label>` component directly relate to the subsequent `<input>` label somehow? Ideally the label for the form would have a `for="<id>` value for each input field (ie. `for="masterPassword` in this case)

2023-09-06 21:12 UTC, cagonzalezcs commented on apps/web/src/app/auth/migrate-encryption/migrate-legacy-encryption.service.ts
> +
Very minor nit here, but in cases where I'm attempting to identify if a value exists within an array of values, using a Set data type is usually more performant.

```suggestion
    const allowedStatuses = new Set([
      EmergencyAccessStatusType.Confirmed,
      EmergencyAccessStatusType.RecoveryInitiated,
      EmergencyAccessStatusType.RecoveryApproved,
    ]);

    const filteredAccesses = emergencyAccess.data.filter((d) => allowedStatuses.has(d.status));

```

`.has()` identifies whether a value exists in `O(1)` runtime, while `.includes()` identifies values in `O(n)`. 

Not a blocking request, just a consideration.

2023-09-06 21:16 UTC, djsmith85 commented on apps/desktop/src/locales/en/messages.json
> +  "encryptionKeyMigrationRequired": {
@justindbaur Thanks for the ping.
If the message is changed then the key need to be changed for the translations to be removed in Crowdin. Additionally we need to check if the previous key was used elsewhere/possibly within a different context and also update all usages within the clients.

2023-09-06 21:20 UTC, djsmith85 requested changes

2023-09-06 21:20 UTC, djsmith85 commented on apps/web/src/locales/en/messages.json
> -  },
The removal/replacement of this key in the browser/desktop message.json files is fine. For web though this is still used in the [change-password.component.ts](https://github.com/bitwarden/clients/blob/6f82a9914ba9e8935f7d55865269b44f18afee9c/apps/web/src/app/auth/settings/change-password.component.ts#L150)
Please check if this also needs to be changed or removed.

2023-09-06 21:48 UTC, jlf0dev commented on apps/web/src/app/auth/migrate-encryption/migrate-legacy-encryption.component.html
> +          />
Good catch, added.

2023-09-06 21:49 UTC, jlf0dev commented on apps/web/src/app/auth/migrate-encryption/migrate-legacy-encryption.service.ts
> +
Nice! TIL

2023-09-06 21:49 UTC, jlf0dev commented on apps/web/src/locales/en/messages.json
> -  },
Thanks, almost missed that one

2023-09-06 22:03 UTC, djsmith85 commented on apps/web/src/app/auth/migrate-encryption/migrate-legacy-encryption.component.html
> +          />
Based on [this comment](https://github.com/bitwarden/clients/pull/5683#discussion_r1247993202) from @shane-melton, the bit-label does not need/support a for-attribute. The bit-form-field takes care of it

2023-09-06 23:47 UTC, JaredSnider-Bitwarden submitted a review, later dismissed
New changes look good to me! Nice work 👍

2023-09-07 08:09 UTC, Hinton commented on apps/web/src/app/auth/migrate-encryption/migrate-legacy-encryption.component.html
> +        <app-callout type="warning">{{ "updateEncryptionKeyWarning" | i18n }}</app-callout>
Should be using the bit component instead of the deprecated app-callout.

2023-09-07 08:10 UTC, Hinton commented on apps/web/src/app/auth/migrate-encryption/migrate-legacy-encryption.component.html
> +          />
Missing  a password toggle.

2023-09-07 08:34 UTC, Hinton requested changes
The migration service seems to expose to many functions that can be accidentally misused. I suspect we would want to add the checks to the `AuthGuard`, as well to ensure the users can't bypass the migrate page.

I'm a bit concerned what the impact will be of the removed userKey checks everywhere.

2023-09-07 08:34 UTC, Hinton commented on apps/web/src/app/auth/migrate-encryption/migrate-legacy-encryption.component.html
> +        <button type="submit" bitButton bitFormButton buttonType="primary" [block]="true">
```suggestion
        <button type="submit" bitButton bitFormButton buttonType="primary" block>
```

2023-09-07 08:34 UTC, Hinton commented on apps/web/src/app/auth/migrate-encryption/migrate-legacy-encryption.service.ts
I don't believe the public interface of this service is correct. We're exposing partial migration methods which can break an account if called in the wrong order. I think there should be a single public method that takes everything needed to migrate an account ensuring the integrity of the data.

There are future improvements server side since the current 3 request approach can cause partial migrations on network loss. But that's out of scope.

2023-09-07 08:34 UTC, Hinton commented on apps/web/src/app/oss.module.ts
> +    MigrateLegacyEncryptionModule,
The intention wasn't to tack on every single module here. Auth should make a single module that contains functionality needed in the initial bundle. (Other routes can be lazy routed)

2023-09-07 08:34 UTC, Hinton commented on libs/angular/src/auth/guards/lock.guard.ts
> +      if (platformUtilService.getClientType() === "web") {
ClientType is an enum and should use the enum in comparisons.

```suggestion
      if (platformUtilService.getClientType() === ClientType.Web) {
```

2023-09-07 14:44 UTC, jlf0dev commented on apps/web/src/app/oss.module.ts
> +    MigrateLegacyEncryptionModule,
Moved the migration to be a standalone component. This route shouldn't be hit very often (if ever) so its a good candidate for lazy loading.

2023-09-07 16:47 UTC, Hinton submitted a review, later dismissed
I'm not going to block this. **Please ensure this service gets refactored before anyone else uses it!** I also think the migration service knows far to much about HOW to encrypt things, which should be internal concerns of those domains.

2023-09-15 20:31 UTC, JaredSnider-Bitwarden reviewed
Nice work! One small tweak

2023-09-15 20:31 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/oss-routing.module.ts
> +        loadComponent: () =>
🏅 good call on lazy loading this component!

2023-09-15 20:31 UTC, JaredSnider-Bitwarden commented on libs/common/src/services/vault-timeout/vault-timeout.service.ts
> +        // Legacy users should be logged out since we're not on the web vault and can't migrate.
❓ Shouldn't this include a check for `isLegacyUser(...)` AND client is not web below to match the above comment?

2023-09-17 22:47 UTC, jlf0dev commented on libs/common/src/services/vault-timeout/vault-timeout.service.ts
> +        // Legacy users should be logged out since we're not on the web vault and can't migrate.
Fixed!

2023-09-18 01:57 UTC, JaredSnider-Bitwarden commented on libs/common/src/services/vault-timeout/vault-timeout.service.ts
> +        // Legacy users should be logged out since we're not on the web vault and can't migrate.
❓ won't the current change prevent legacy users who aren't on web from being logged out (which is what the comment originally stated was the goal)? Also, I thought that `await this.cryptoService.migrateAutoKeyIfNeeded(userId)` needs to run on web clients?

I envisioned the change to be: 
```TypeScript
// Legacy users should be logged out when not on web b/c we can only migrate on web
 if (this.platformUtilsService.getClientType() != ClientType.Web 
 && await this.cryptoService.isLegacyUser(null, userId)) {
          await this.logOut(userId);
 }
```

Please let me know if I missed something!

2023-09-18 11:53 UTC, djsmith85 submitted a review, later dismissed
Approving as the changes I requested (messages and bit-label) have been addressed.

2023-09-18 12:32 UTC, jlf0dev commented on libs/common/src/services/vault-timeout/vault-timeout.service.ts
> +        // Legacy users should be logged out since we're not on the web vault and can't migrate.
The web client can't set the vault timeout to never, meaning we shouldn't need to migrate. This also means the migrate method will only be run for other clients, and now will log them out if they are a legacy user.

It was a little confusing to reason about so I moved the client check into the migrate method as an early return.

2023-09-18 14:31 UTC, JaredSnider-Bitwarden approved these changes
LGTM!

2023-09-18 14:40 UTC, JaredSnider-Bitwarden commented on libs/common/src/services/vault-timeout/vault-timeout.service.ts
> +        // Legacy users should be logged out since we're not on the web vault and can't migrate.
Ah, thank you for the explanation and refactor. I forgot that the auto key isn't used on web; sorry about that!

2023-09-19 13:55 UTC, Hinton commented on libs/common/src/services/vault-timeout/vault-timeout.service.ts
> +    // Web can't set vault timeout to never
Technically we can in dev mode.

2023-09-19 13:55 UTC, Hinton approved these changes

2023-09-19 16:10 UTC, gbubemismith approved these changes

2023-09-20 19:57 UTC, merged