[SM-896] When org is disabled disable the logic and show warning symbols
bitwarden/clients pull request #6225
Opened 2023-09-07 18:38 UTC by cd-bitwarden

## Type of change

```
- [ ] Bug fix
- [ x ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

apps/web/src/app/admin-console/components/organization-switcher.component.html
apps/web/src/app/layouts/product-switcher/product-switcher-content.component.ts
apps/web/src/app/layouts/product-switcher/product-switcher-content.component.ts
apps/web/src/locales/en/messages.json
bitwarden_license/bit-web/src/app/secrets-manager/layout/org-switcher.component.html
bitwarden_license/bit-web/src/app/secrets-manager/layout/org-switcher.component.ts
bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.html
bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.ts
bitwarden_license/bit-web/src/app/secrets-manager/projects/dialog/project-dialog.component.ts
bitwarden_license/bit-web/src/app/secrets-manager/projects/project/project-secrets.component.ts
bitwarden_license/bit-web/src/app/secrets-manager/projects/project/project.component.ts
bitwarden_license/bit-web/src/app/secrets-manager/projects/projects/projects.component.ts
bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.ts
bitwarden_license/bit-web/src/app/secrets-manager/secrets/secrets.component.ts
bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/dialog/service-account-dialog.component.ts
bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-accounts.component.ts
bitwarden_license/bit-web/src/app/secrets-manager/shared/new-menu.component.ts
libs/components/src/navigation/nav-group.component.html
libs/components/src/navigation/nav-group.component.ts
libs/components/src/navigation/nav-item.component.ts
## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-09-07 19:21 UTC, willmartian requested changes

2023-09-07 19:21 UTC, willmartian commented on libs/components/src/navigation/nav-group.component.html
Showing a warning icon is a pretty specific usecase--a little _too specific_ and unrelated to warrant being built in to the API of a reusable navigation component. 

Lets abstract the change here. Rather than adding the input `showWarningIcon` to `nav-item` and `nav-group`, we just need to give developers access to the `end` slot of the `nav-group`. That way, a dev can add anything they want there depending on their usecase: a warning icon, a checkmark, a cowboy emoji, etc.

Current:

```html
  <ng-container slot="start" *ngIf="variant === 'tree'">
    <ng-container *ngTemplateOutlet="button"></ng-container>
  </ng-container>
  <ng-container slot="end" *ngIf="variant !== 'tree'">
    <ng-container *ngTemplateOutlet="button"></ng-container>
  </ng-container>
```

Suggested:

```html
  <ng-container slot="start" *ngIf="variant === 'tree'">
    <ng-container *ngTemplateOutlet="button"></ng-container>
  </ng-container>
  <ng-container slot="end">
    <ng-content select="[slot=end]"></ng-content>
    <ng-container *ngIf="variant !== 'tree'">
      <ng-container *ngTemplateOutlet="button"></ng-container>
    </ng-container>
  </ng-container>
```

(The key bit is `<ng-content select="[slot=end]">` inside of `<ng-container slot="end">`. This will transclude the `nav-group` children into the `nav-item`.)

That way, all of the logic pertaining to warning icons can stay contained within the org switcher component where it is most relevant.

2023-09-07 19:21 UTC, willmartian commented on bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.ts
Rather than tracking and passing `organizationEnabled`, `organizationName`, and `organizationId` separately, should we just use the whole organization object? CC @Thomas-Avery

2023-09-07 19:21 UTC, willmartian commented on bitwarden_license/bit-web/src/app/secrets-manager/projects/project/project-secrets.component.ts
> +        this.organizationEnabled = params.organizationEnabled;
Is `organizationEnabled` stored in the route?

2023-09-11 20:36 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.ts
I'd like to know @Thomas-Avery 's opinion on this, the organization object has a lot of other information we don't need, I'm not sure at what point we'd want to pass the whole object 😄

2023-09-12 18:17 UTC, cd-bitwarden commented on libs/components/src/navigation/nav-group.component.html
@willmartian with your suggested changes how would I then specify we want the warning icon? 😄

2023-09-12 18:25 UTC, willmartian commented on libs/components/src/navigation/nav-group.component.html
You could slot it into the the `org-switcher`'s `nav-group` just like you are doing with the `nav-item`:

```html
<bit-nav-group
  *ngIf="activeOrganization$ | async as activeOrganization"
  [text]="activeOrganization.name"
  [ariaLabel]="['organization' | i18n, activeOrganization.name].join(' ')"
  icon="bwi-business"
  [route]="['../', activeOrganization.id]"
  [(open)]="open"
  [exactMatch]="true"
>
 ...
 <i slot="end" *ngIf="!activeOrganization.enabled" class="bwi bwi-exclamation-triangle"></i> 
```

2023-09-14 14:26 UTC, willmartian requested changes
Good work! 

Rather than manually passing `organizationEnabled` into all of the dialog data, would it make more sense to throw an error in the service or return an error response from the server and then react to that with an error toast?

Left some other comments below:

2023-09-14 14:26 UTC, willmartian commented on libs/components/src/navigation/nav-item.component.ts
> +  @Input() showWarningIcon: boolean;
I don't think this is used and should be removed.

2023-09-14 14:26 UTC, willmartian commented on libs/components/src/navigation/nav-group.component.ts
> +  @Input() showWarningIcon: boolean;
I don't think this is used and should be removed.

2023-09-14 14:26 UTC, willmartian commented on libs/components/src/navigation/nav-group.component.html
> +  [showWarningIcon]="showWarningIcon"
I don't think this is used and should be removed.

2023-09-14 14:26 UTC, willmartian commented on apps/web/src/app/admin-console/components/organization-switcher.component.html
These should use Tailwind classes, so `tw-text-danger` instead of `text-danger`.

2023-09-14 14:26 UTC, willmartian commented on bitwarden_license/bit-web/src/app/secrets-manager/layout/org-switcher.component.html
> +  [showWarningIcon]="!activeOrganization.enabled"
I don't think this is used and should be removed.

2023-09-14 14:26 UTC, willmartian commented on bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.html
> +</bit-no-items>
Shouldn't we be showing this on all the other SM pages as well? (If so, we probably want to look into using a route guard.)

2023-09-14 14:55 UTC, cd-bitwarden commented
> Good work!
> 
> Rather than manually passing `organizationEnabled` into all of the dialog data, would it make more sense to throw an error in the service or return an error response from the server and then react to that with an error toast?
> 
> Left some other comments below:

Since we already know if their org is enabled or disabled, I prefer to not even make a call to the server side 

> Good work!
> 
> Rather than manually passing `organizationEnabled` into all of the dialog data, would it make more sense to throw an error in the service or return an error response from the server and then react to that with an error toast?
> 
> Left some other comments below:

I personally don't prefer doing that, because we already know they can't access anything because we have access to the organization enabled information, so I'm not a fan of making a call to the server side just for it to fail 🤔

2023-09-14 15:23 UTC, Thomas-Avery commented
With a single disabled organization looks like we can still import/export data and modify secrets, project, service accounts and trash in their individual pages. 

Based on the FIGMA I would expect to see the “organization suspended” banner on each of those pages. 

We will also need a server PR to enforce these constraints for the server and other forms of access to SM (CLI, sdk, etc.)

2023-09-14 16:02 UTC, Hinton commented on apps/web/src/app/admin-console/components/organization-switcher.component.html
> +      class="text-danger tw-ml-3 tw-rounded tw-border tw-border-solid tw-border-danger-500"
Why did we change from tailwind to bootstrap class here?

2023-09-14 20:49 UTC, cd-bitwarden commented
> With a single disabled organization looks like we can still import/export data and modify secrets, project, service accounts and trash in their individual pages.
> 
> Based on the FIGMA I would expect to see the “organization suspended” banner on each of those pages.
> 
> We will also need a server PR to enforce these constraints for the server and other forms of access to SM (CLI, sdk, etc.)

Sorry I have not created the server PR yet, this will fix a lot of the issues you've seen 😄

2023-09-14 21:39 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.html
> +</bit-no-items>
The design comments on the left of the FIGMA read like we want this on every page.

Specifically, “an empty state should display in every page telling user the org’s status and ways to remediate.”

Let's double-check with design and if we do need it on every page let's look into using a route guard.

2023-09-20 22:45 UTC, cd-bitwarden commented on libs/components/src/icon/icons/noAccess.ts
> +  <path class="tw-stroke-warning-500" d="M126.798 54.727a2.635 2.635 0 1 0 0-5.27 2.635 2.635 0 0 0 0 5.27Z"/>
@willmartian What class can I add to this so that it fills in the exclamation point properly? Right now it's not filling in the circle part of it. Also tw-stroke-warning isn't the right color, however I tried replacing warning with error and it still was not red, can you please advise? 🥺

2023-09-20 22:46 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.html
> +</bit-no-items>
added the route guard 👍 thank you Thomas and Will

2023-09-21 17:13 UTC, willmartian commented on libs/components/src/icon/icons/noAccess.ts
> +  <path class="tw-stroke-warning-500" d="M126.798 54.727a2.635 2.635 0 1 0 0-5.27 2.635 2.635 0 0 0 0 5.27Z"/>
> What class can I add to this so that it fills in the exclamation point properly?

`tw-fill-[your-color-here]`

> tw-stroke-warning isn't the right color, however I tried replacing warning with error and it still was not red

You would use `tw-stroke-danger-500`, see the color reference [here.](https://components.bitwarden.com/?path=/docs/documentation-colors--docs) (I always forget if it is "error" or "danger".) If that doesn't work, could you try rebuilding the web app and see if that fixes it? 🤞

2023-09-21 18:44 UTC, willmartian requested changes

2023-09-21 21:07 UTC, cd-bitwarden commented on libs/components/src/icon/icons/noAccess.ts
> +  <path class="tw-stroke-warning-500" d="M126.798 54.727a2.635 2.635 0 1 0 0-5.27 2.635 2.635 0 0 0 0 5.27Z"/>
thanks Will!

2023-09-21 21:08 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/layout/org-switcher.component.ts
> +  }
good catch, we aren't using it anymore :)

2023-09-21 22:20 UTC, Thomas-Avery requested changes
A few minor things to take a look at.

2023-09-21 22:20 UTC, Thomas-Avery commented on apps/web/src/locales/en/messages.json
> +    "message": "Secrets in suspended organizations cannot be accessed. Please contact your organization owner for assistance."
This is used in the Organization suspended banner/icon and reads differently than what is in the FIGMA. 

“Suspended organizations cannot be accessed. Please contact your organization owner for assistance.”

2023-09-21 22:20 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/org-suspended.component.html
> +  <ng-container slot="title">{{ "organizationIsDisabled" | i18n }}</ng-container>
The title doesn't have as much space between it and the icon as it does in the FIGMA.

We can wrap `{{ "organizationIsDisabled" | i18n }}` in a div and use `tw-mt-X` to add a top margin.

2023-09-22 01:16 UTC, cd-bitwarden commented on apps/web/src/app/admin-console/components/organization-switcher.component.html
> +        <i class="bwi bwi-exclamation-triangle tw-text-danger" aria-hidden="true"></i>
Great question, I know we want consistency with the warning symbol using tw-text-danger when in side bars like this, so I'll have to ask Jaclyn if we also want this change to effect the admin consoles org switcher also. I assume her answer will be yes, but I'll let you know 😄

2023-09-22 17:15 UTC, cd-bitwarden commented on apps/web/src/app/admin-console/components/organization-switcher.component.html
> +        <i class="bwi bwi-exclamation-triangle tw-text-danger" aria-hidden="true"></i>
Removing this change, as it's not actually necessary.

2023-09-25 22:03 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/org-suspended.component.ts
> +  }
```suggestion
export class OrgSuspendedComponent implements OnInit, OnDestroy {
  constructor(private organizationService: OrganizationService, private route: ActivatedRoute) {}

  protected organizationName: string;
  protected NoAccess: Icon = Icons.NoAccess;
  private destroy$ = new Subject<void>();

  ngOnInit() {
    this.route.params.pipe(takeUntil(this.destroy$)).subscribe((params) => {
      this.organizationName = this.organizationService.get(params.organizationId)?.name;
    });
  }
```

It looks like we are setting `this.organizationName` on line 24 and 30.
 
I don't think our `ngOnInit` needs to be async because `this.organizationService.get` isn't async. 

Need to add implements `OnDestroy` onto the class.

2023-09-26 19:05 UTC, cd-bitwarden commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +  protected noAccessIcon = Icons.NoAccess;
You're right we don't need to have this here

2023-09-27 00:17 UTC, willmartian commented on bitwarden_license/bit-web/src/app/secrets-manager/layout/org-switcher.component.html
> +    class="bwi bwi-exclamation-triangle tw-mt-1 !tw-text-danger"
Is `tw-mt-1` necessary? We don't use it L24-L28

2023-09-27 00:30 UTC, willmartian commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/org-suspended.component.ts
> +  }
Avoid subscriptions unless you need to access a value synchronously. Since we are only using `organizationName` in the template, we don't need to access it synchronously. Instead, we can bind to the raw observable with an `async` pipe. 

```ts
class OrgSuspendedComponent {
  organizationName$ = this.route.params.pipe(
    map(params => this.organizationService.get(params.organizationId)?.name)
  );
}

```html
<sm-header [title]="organizationName$ | async">
```

2023-09-28 14:03 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/org-suspended.component.ts
> +  }
you're an mvp, thanks!

2023-09-28 15:34 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/layout/org-switcher.component.html
> +    class="bwi bwi-exclamation-triangle tw-mt-1 !tw-text-danger"
Yes this is needed it's for when you select the disabled org from the list, it puts the symbol in a slightly higher than desired spot :)

2023-09-28 19:00 UTC, willmartian approved these changes
Good work! 🚀 Thanks for iterating on the CL nav components with me to fit your use-case :)

2023-09-28 19:50 UTC, Thomas-Avery approved these changes
Looks good, thank you for your work on this!

2023-09-29 01:51 UTC, eliykat requested changes

2023-09-29 01:51 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/guards/org-permissions.guard.ts
I think this guard is now doing too much and it doesn't really work anymore.

In particular:
* `hasPermissions` used to return a boolean to indicate whether the user has permissions. Now it can return a truthy value (a `UrlTree`) to indicate a negative (the user doesn't have permissions), which is confusing and is likely to cause people to misread this logic. Similarly, the happy path now does double duty to allow navigation or redirect on a failure state.
* more fundamentally - this guard has PM + AC specific logic in the `!hasPermissions` if block, which is irrelevant for SM use and will generally be skipped when called from your routing module (and if not skipped, won't do anything). You've effectively overridden it via the callback, but that's not what it's there for.
 
I think this shows there is very little shared code here and you'd be better creating a new route guard for SM use. This would also let you get substantive route guard logic out of the routing module.

2023-09-29 01:51 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/guards/org-permissions.guard.ts
> +      state: RouterStateSnapshot
I might be missing a usage somewhere, but `state` looks unused.

2023-10-03 20:11 UTC, cd-bitwarden commented on apps/web/src/app/admin-console/organizations/guards/org-permissions.guard.ts
Admin Console responded, and requested we break this apart into a separate guard, so I have done so 😄 closing this comment

2023-10-04 01:00 UTC, eliykat requested changes
All comments are suggestions only once you revert the AC changes, and I'll defer to SM Team if these aren't concerns. :)

2023-10-04 16:09 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/guards/sm-org-enabled.guard.ts
> +  if (!org.enabled) {
@differsthecat can we please talk about this in the team sync tomorrow so we can decide if we want to do something like this? 😄

2023-10-04 20:41 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/sm-routing.module.ts
> +              organizationPermissions: (org: Organization) => org.canAccessSecretsManager,
Thomas Avery and I checked on the canActivateSM guard including this logic and we determined it won't work there. I went ahead and removed the organizationpermissionguard and moved that login into the org-enabled guard 😄

2023-10-04 20:42 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/guards/sm-org-enabled.guard.ts
> +  }
Looks like we don't need the Auth guard stuff there, so I removed it.

2023-10-04 23:08 UTC, eliykat reviewed
LGTM pending the "break glass access" question above!

2023-10-04 23:08 UTC, eliykat commented on bitwarden_license/bit-web/src/app/secrets-manager/guards/sm-org-enabled.guard.ts
> +  if (org == null || !org?.canAccessSecretsManager) {
Nit: you don't need the `?` because you already test if `org` is null.

```suggestion
  if (org == null || !org.canAccessSecretsManager) {
```

2023-10-05 15:55 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/guards/sm-org-enabled.guard.ts
> +  if (!org.enabled) {
@eliykat the break glass functionality will be defined and handled in a new ticket. I believe @maxkpower is creating this ticket.

2023-10-05 16:12 UTC, Thomas-Avery requested changes

2023-10-05 16:12 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/sm-routing.module.ts
> +              organizationPermissions: (org: Organization) => org.canAccessSecretsManager,
Now that we are no longer using `OrganizationPermissionsGuard` do we still need this? 

I thought it was only being used in the `permissionsCallback`.

2023-10-05 17:08 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/sm-routing.module.ts
> +              organizationPermissions: (org: Organization) => org.canAccessSecretsManager,
you're right, we don't need it anymore :)

2023-10-05 21:04 UTC, Thomas-Avery approved these changes
Looks good, thank you for all the work on this great job!

2023-10-05 23:55 UTC, eliykat approved these changes
Thanks for following up on my feedback!

2023-10-09 19:40 UTC, Jingo88 commented on apps/web/src/app/layouts/product-switcher/product-switcher-content.component.ts
> +        routeOrg?.canAccessSecretsManager && routeOrg?.enabled == true
would this still work?

`routeOrg?.canAccessSecretsManager && routeOrg?.enabled`

2023-10-09 19:40 UTC, Jingo88 commented on bitwarden_license/bit-web/src/app/secrets-manager/layout/org-switcher.component.html
> +        *ngIf="org.enabled == false"
Would this work as? `*ngIf="!org.enabled"`

2023-10-09 19:40 UTC, Jingo88 submitted a review, later dismissed
LGTM. just left two super tiny nitpick questions.

2023-10-10 16:30 UTC, willmartian submitted a review, later dismissed
LGTM 🤠

2023-10-12 15:58 UTC, Thomas-Avery approved these changes

2023-10-13 02:45 UTC, willmartian approved these changes

2023-10-16 14:29 UTC, merged