[BEEEP] [PM-1935] Migrate vault lock screen to component library
bitwarden/clients pull request #6237
Opened 2023-09-08 16:23 UTC by Hinton

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Migrate the vault lock screen to the component library. I extracted the "card" view to a separate component so we don't have to duplicate those classes.

There are future work here:
- use the card component on the register page since the padding of that differs slightly. Not sure if that's intentionally or accidental.
- Migrate to `bitSubmit` requires that we do it on all clients.

## Code changes

- **apps/web/src/app/auth/card.component.ts:** "Card" style component used on the auth pages.
- **apps/web/src/app/auth/lock.component.html**: Changed to use the component library.
- **apps/web/src/app/auth/login/login.component.html**: Use card component and simplify css classes.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-10-09 09:05 UTC, djsmith85 reviewed
Should the card-component be moved into libs/components? As it doesn't depend on anything Bitwarden/PasswordManager-specific it could easily be moved elsewhere. 

This would also make it easier to be re-used on web and desktop

2023-10-13 08:49 UTC, Hinton commented
@djsmith85 it's not a component the CL team will support. It's strictly for sharing the container behavior for the auth pages.

2023-10-13 09:02 UTC, djsmith85 commented
> @djsmith85 it's not a component the CL team will support. It's strictly for sharing the container behavior for the auth pages and avoid inconsistencies which has already started to appear.

Then into libs/auth? Tools will need the `card.component` for the `send/access.component. Or the `card.component`will be part of the [AnonLayout](https://github.com/bitwarden/clients/pull/6424) which the SendAccess page will use?

2024-05-08 19:45 UTC, rr-bw commented
@Hinton Is this still in being worked on? I'm happy to review once merge conflicts are resolved. No rush from me though.

2024-05-22 00:05 UTC, rr-bw requested changes
I believe we should use AnonLayout here, based on the [Figma design for the lock component](https://www.figma.com/design/81uGWWdQVAQfKDiR4qltoq/Email-Verification-[Create-account]?node-id=536-49011&t=FK0lR4AWGWiTONe6-0). 

Something like:
```typescript
import {
  AnonLayoutWrapperComponent,
  AnonLayoutWrapperData,
  LockIcon,
} from "@bitwarden/auth/angular";

...

{
  path: "",
  component: AnonLayoutWrapperComponent,
  children: [
    {
      path: "lock",
      children: [
        {
          path: "",
          component: LockComponent,
        },
      ],
      canActivate: [deepLinkGuard(), lockGuard()],
      data: {
        pageTitle: "yourVaultIsLocked",
        pageIcon: LockIcon,
      } satisfies AnonLayoutWrapperData,
    },
  ],
},
```

2024-05-22 09:45 UTC, Hinton commented
@rr-bw this PR has been pending review for 8 months. I rebased it on request but I don't have the capacity in the forseeable future to allocate any resources to expanding the scope of the PR. The Auth team is welcome to take ownership of the PR.

2024-05-22 16:25 UTC, rr-bw commented
@Hinton Yes I think that's best. I talked with Todd and Auth will take it from here.

2024-05-30 20:34 UTC, rr-bw submitted a review, later dismissed

2024-07-03 18:06 UTC, jlf0dev requested changes

2024-07-03 18:06 UTC, jlf0dev commented on apps/web/src/app/auth/lock.component.ts
> +  });
Can we change this to trigger on submit instead of the default on blur?

2024-07-03 19:09 UTC, danielleflinn commented on apps/web/src/app/auth/lock.component.ts
> +  });
I'm good with this change!

2024-07-03 19:11 UTC, danielleflinn commented
Design nit: Could we change the title to just "Your vault is locked"? 
It feels really long right now and I think entering the MP to unlock is implied.

2024-07-07 21:58 UTC, jlf0dev approved these changes
Thank you so much for shepherding this through and taking the time to verify the changes that were requested! You rock @rr-bw 👏

2024-07-09 22:38 UTC, willmartian approved these changes
LGTM!

2024-07-10 00:19 UTC, merged