Fix field names when importing from 1Password 1Pux files
bitwarden/clients pull request #6261
Opened 2023-09-12 00:47 UTC by felipecrs

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Fixes #3365.

## Code changes

This PR builds on https://github.com/bitwarden/clients/pull/4959, but:

- Fixes the implementation which was breaking existing tests.
    - The previous implementation was actually wrong: the id field should be preferred in some occasions.
    - Comments were added to the code to make such occasions more clear
    - The actual problem was that, in fact, the regex was too strict and not all machine generated ids were being flagged.
- Rebase the code against latest master branch and fix conflicts.
- Adds one more test data which I found from my own account's export, where the id could have 32 characters rather than only 26.

2023-09-12 00:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitwarden/clients?pullRequest=6261) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/bitwarden/clients?pullRequest=6261) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: rituraj00<br/>:x: felipecrs<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitwarden/clients?pullRequest=6261) it.</sub>

2023-09-12 00:52 UTC, felipecrs commented on libs/importer/src/importers/onepassword/types/onepassword-1pux-importer-types.ts
> +  indexAtSource?: number;
My export with more than 500 items don't have this set at all. Maybe this was set by previous versions of 1password, but it's definitely not being set anymore. Either way we can make it compatible with both cases by making it optional.

2023-10-30 18:49 UTC, ttalty requested changes
Please see my review on the first/original PR for this topic: https://github.com/bitwarden/clients/pull/4959

Both of these fixes do work. However there really is no need to check for the computer generated id. I went into more details on the PR linked.

2023-12-22 21:26 UTC, ttalty commented
I just merged in a PR that takes care of these custom fields. 
https://github.com/bitwarden/clients/pull/7190

2023-12-22 21:26 UTC, closed without merging