Auth/pm 3275/tde update set password for authn and non mp users
bitwarden/clients pull request #6281
Opened 2023-09-13 18:04 UTC by JaredSnider-Bitwarden

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-10-06 14:23 UTC, r-tome reviewed
It looks great to me, nice work! However, I'd like someone with more Angular knowledge to review it.

2023-10-11 00:14 UTC, shane-melton requested changes
Nice work! I've gone through about 90% of it; I just need to finish going over the API changes and how they relate to the related server changes.

Most of my comments are hopefully just clarifying questions to make sure I'm on the same page and a few small suggestions. Otherwise, I just saw one small issue with an `async` subscribe method that the linter missed. 

Also, I really appreciate the cleanup of the `ForcePasswordResetReason` enum and all the additional comments; makes following along much easier!

2023-10-11 00:14 UTC, shane-melton commented on libs/angular/src/components/set-password.component.ts
> +      keyPair &&
nit: Can we add the explicit `!== null` check here since we're adding it to the type definition?

2023-10-11 00:14 UTC, shane-melton commented on libs/common/src/platform/models/domain/account.ts
> +  forcePasswordResetReason?: ForceSetPasswordReason;
question: Should we look into renaming this as well to match?

2023-10-11 00:14 UTC, shane-melton commented on libs/common/src/vault/services/sync/sync.service.ts
> +    if (response.forcePasswordReset) {
thought: We should look into what it would take to re-name this response model property to add more emphasis that its related to an admin action and to help avoid confusion with the other force set password reasons. I don't necessarily think it has to be done now, but it think it would be worthwhile to look into to help avoid confusion in the future.

2023-10-11 15:19 UTC, JaredSnider-Bitwarden commented on apps/cli/src/auth/commands/login.command.ts
Yes, we currently do not support logging in with TDE on the CLI so it's not something we need to handle right now.

2023-10-11 16:45 UTC, JaredSnider-Bitwarden commented on libs/angular/src/auth/components/sso.component.ts
> +      if (authResult.forcePasswordReset == ForceSetPasswordReason.AdminForcePasswordReset) {
Great point. I've refactored the SSO & 2FA components in light of the feedback, and I tested all the affected scenarios (TDE and MP encryption org logins with a user with and w/out 2FA - with an admin having reset their password prior to login).

2023-10-11 16:49 UTC, JaredSnider-Bitwarden commented on libs/angular/src/auth/components/two-factor.component.ts
> +      // Set flag so that auth guard can redirect to set password screen after decryption (trusted or untrusted device)
My comment was not as clear as I would have liked. 

I've refactored it to be:
```
// Set flag so that auth guard can redirect to set password screen after decryption (trusted or untrusted device)
// Note: we cannot directly navigate to the **set password screen** in this scenario as we are in a pre-decryption state, and
// if you try to set a new MP before decrypting, you will invalidate the user's data by making a new user key.
```

We can directly navigate in other flows. It's just that, within the context of TDE login and decryption, we cannot yet navigate the user to set a password until after decryption b/c you will end up creating a new user key and potentially losing the ability to decrypt existing vault items.

2023-10-11 18:34 UTC, JaredSnider-Bitwarden commented on libs/angular/src/components/set-password.component.ts
> +        next: async (orgAutoEnrollStatusResponse: OrganizationAutoEnrollStatusResponse) => {
Ah, great catch. I've refactored the observable chain to remove the async subscribe via sequential `switchMaps` and `tap` operations. I couldn't use `combineLatest` as we needed sequential calls in order to get the org id from the org SSO id.

2023-10-11 18:37 UTC, JaredSnider-Bitwarden commented on libs/common/src/vault/services/sync/sync.service.ts
> +    if (response.forcePasswordReset) {
Great idea. I've captured this as a tech debt item https://bitwarden.atlassian.net/browse/PM-4298.

2023-10-11 18:42 UTC, shane-melton commented on libs/common/src/vault/services/sync/sync.service.ts
> +    if (response.forcePasswordReset) {
Thanks!

2023-10-12 09:02 UTC, Hinton commented on libs/common/src/admin-console/services/policy/policy-api.service.ts
> +  async getMasterPasswordPolicyOptsForOrgUser(
**note:** This method doesn't belong on an ApiService, and should be moved to a regular service. ApiServices should only contain direct send methods.

But not a new issue.

2023-10-12 18:08 UTC, JaredSnider-Bitwarden commented on libs/common/src/admin-console/services/policy/policy.service.ts
> +    }
That's a good question. I leveraged the new `mapPolicyFromResponse(...)` method in the `policy-api.service` to process a master password policy response, and I wasn't sure if it was a possible scenario so I decided to handle it just in case since the existing `mapPoliciesFromToken(...)` method did so as well.

2023-10-12 18:13 UTC, JaredSnider-Bitwarden commented on libs/common/src/admin-console/services/policy/policy.service.ts
> +    }
I could add `| null` to make it clear that they handle null:
`mapPolicyFromResponse(policyResponse: PolicyResponse | null)`
`mapPoliciesFromToken(policiesResponse: ListResponse<PolicyResponse | null>)`

2023-10-12 18:29 UTC, JaredSnider-Bitwarden commented on libs/common/src/admin-console/services/policy/policy-api.service.ts
> +  async getMasterPasswordPolicyOptsForOrgUser(
I could integrate the `getMasterPasswordPolicyOptsForOrgUser(...)` into the `policy.service`  (leaving it a more standalone method without using the `upsert(...)` to incompletely update the `_policies` subject) if you wish.

2023-10-12 19:06 UTC, JaredSnider-Bitwarden commented on libs/common/src/models/response/profile.response.ts
> +  hasManageResetPasswordPermission: boolean;
Hmm... currently it is an aggregated user permission on the server. 
If the TDE user has any orgs that they are a member of where they have the manage password reset, then they must set a password. But TDE requires single org... so it probably could be on the org.

I guess the question comes down to whether or not we want to expose this as an org permission on all orgs and aggregate it into a user permission client side or keep what I have where the aggregation is done on the server.

2023-10-12 20:48 UTC, JaredSnider-Bitwarden commented on libs/common/src/admin-console/services/policy/policy-api.service.ts
> +  async getMasterPasswordPolicyOptsForOrgUser(
Or capture it as tech debt

2023-10-12 22:04 UTC, ike-kottlowski reviewed
Generally, this looks good. I do have a concern that @Hinton has already brought up as it pertains to organizations and the generic application of a master password assignment.

One question is: If a user is a member of _n_ number of orgs and one of those orgs transitions to TDE, what happens to that user?

2023-10-12 22:06 UTC, JaredSnider-Bitwarden commented
> One question is: If a user is a member of _n_ number of orgs and one of those orgs transitions to TDE, what happens to that user?

@ike-kottlowski , they will be removed from the org ([source](https://bitwarden.com/help/policies/#single-organization)).

2023-10-13 16:10 UTC, Hinton commented on libs/common/src/models/response/profile.response.ts
> +  hasManageResetPasswordPermission: boolean;
So far I don't believe we have any org aggregated permissions, it's all per org and the client does the aggregation. I would prefer if we keep things consistent unless we have a good reason to diverge?

2023-10-13 16:17 UTC, JaredSnider-Bitwarden commented on libs/common/src/models/response/profile.response.ts
> +  hasManageResetPasswordPermission: boolean;
Ok, I'll investigate refactoring this.

2023-10-16 19:14 UTC, JaredSnider-Bitwarden commented on libs/common/src/admin-console/services/policy/policy-api.service.ts
> +  async getMasterPasswordPolicyOptsForOrgUser(
Created https://bitwarden.atlassian.net/browse/PM-4362

2023-10-16 19:15 UTC, JaredSnider-Bitwarden commented on libs/common/src/models/response/profile.response.ts
> +  hasManageResetPasswordPermission: boolean;
Per discussion with @Hinton , we already had the information we needed on the sync to determine if the user had the `manageResetPassword` permission in an org. So, I've removed the flag from the sync `ProfileResponse`, and updated the logic in the `SyncService`

2023-10-16 20:37 UTC, shane-melton submitted a review, later dismissed
Nice work on this and thanks for addressing my comments! Looks good to me!

2023-10-17 15:09 UTC, ike-kottlowski approved these changes

2023-10-17 15:26 UTC, r-tome approved these changes

2023-10-19 08:27 UTC, Hinton approved these changes

2023-10-19 14:52 UTC, Hinton approved these changes

2023-10-19 15:00 UTC, r-tome approved these changes

2023-10-19 15:27 UTC, shane-melton approved these changes

2023-10-19 15:32 UTC, ike-kottlowski approved these changes

2023-10-27 19:19 UTC, ike-kottlowski approved these changes

2023-10-30 16:07 UTC, shane-melton approved these changes

2023-11-01 23:17 UTC, shane-melton approved these changes

2023-11-02 10:02 UTC, r-tome approved these changes

2023-11-03 15:23 UTC, Hinton approved these changes

2023-11-03 15:33 UTC, merged