PM-2559 Messaging Rework for Passkey Bug
bitwarden/clients pull request #6282
Opened 2023-09-13 19:27 UTC by Jingo88

```
- [ X ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

This PR is in response to a Passkeys defect in Firefox. When a user closes the passkey popup, they will sporadically receive a no response hanging type of bug on the website. Firefox seems to have stricter handling of promises and therefore the `messagerhandler` inside `content-script` will sometimes receive an error of `response is undefined` prematurely. The objective of this PR is to prevent the default returns from the messageListener

## Code changes

Update the `messageListener` inside the `browser-api` to take in the callback that was passed instead of creating a new one and returning true. 
Update corresponding files that call `BrowserApi.messageListener`. Remove their async/awaits as well as their sendResponses

## Video

Video of Firefox Passkey Fix. It no longer hangs after multiple popup closes.

https://github.com/bitwarden/clients/assets/8302660/58c92593-b54d-44e0-bd4c-c475fd1ced26

2023-09-13 19:59 UTC, cagonzalezcs approved these changes
👍

2023-09-19 12:48 UTC, coroiu reviewed
Waiting on @Jingo88 to double check return values for all callers of `messageListener`, as discussed in a slack huddle

2023-09-20 18:13 UTC, Jingo88 commented
> Waiting on @Jingo88 to double check return values for all callers of `messageListener`, as discussed in a slack huddle

updated listeners are working as expected

2023-09-21 10:19 UTC, Hinton commented on apps/browser/src/popup/app.component.ts
> +        if (msg.userId == null || msg.userId === this.stateService.getUserId()) {
`getUserId` is an async operation, `msg.userId === function` will never be true.

2023-09-21 11:47 UTC, coroiu reviewed
Looks ok from my perspective, I'll let Oscar give the last approval

2023-09-21 11:47 UTC, coroiu commented on apps/browser/src/background/runtime.background.ts
> +    BrowserApi.messageListener("runtime.background", backgroundMessageListener);
praise: Nice! I was about to write a whole comment about how this will un-bind `this`, until I realized that `backgroundMessageListener` was already an arrow function, and that the arrow function on row 74 was actually redundant!

2023-09-21 11:47 UTC, coroiu commented on apps/browser/src/autofill/background/context-menus.background.ts
> +            });
question(non-blocking): why are changing from async/await to promise-then syntax? I usually think that the former is easier to read and more consistent with the majority of the code-base

2023-09-21 18:53 UTC, Jingo88 commented on apps/browser/src/popup/app.component.ts
> +        if (msg.userId == null || msg.userId === this.stateService.getUserId()) {
Is there a flow that leads me to that second if argument? I've gotten to this piece of logic from browser > settings > lock now, and every time it seems that `msg.userId === null`.

2023-09-21 21:51 UTC, cagonzalezcs commented on apps/browser/src/autofill/background/context-menus.background.ts
> +            });
@coroiu 

I agree with your sentiment here. What would make sense is to pull this behavior out to a separate method so we could still consider the async/await approach.

That suggestion aside, I advised Jason on these changes and can give a reason for why, in this instance, we're avoiding using the `await` keyword.

When using the `chrome.runtime.onMessage.addListener` API, any callback that is passed to the listener needs to be structured as a syncrhonous callback. This is due to how the `sendMessage` parameter is structured to respond when a message from `chrome.runtime.sendMessage` is received. 

The issue that we were seeing in this ticket was occurring because we were setting up the callbacks for `onMessage.addListener` as `async` methods, which by default return a `Promise<void>`. Because of that, we were experiencing race conditions where some `chrome.runtime.sendMessage` calls that were expecting a response from the `onMessage` listener were receiving `undefined` values. 

This MDN article explains a bit more on the issue - https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage#parameters

I think if @Jingo88 were to pull this behavior out to a private method, they could then place the method in the `onMessage` callback function without having to use a `.then` chain.

2023-09-21 21:54 UTC, cagonzalezcs commented on apps/browser/src/autofill/background/context-menus.background.ts
> +            });
```suggestion
          handleUnlockCompletedCommand();
            
            [...]
            
            async handleUnlockCompletedCommand() {
                await this.contextMenuClickedHandler.cipherAction(msg.data.commandToRetry.msg.data, msg.data.commandToRetry.sender.tab);
               BrowserApi.tabSendMessageData(sender.tab, "closeNotificationBar");
            }
```

Something akin to this.

2023-09-22 08:02 UTC, coroiu commented on apps/browser/src/autofill/background/context-menus.background.ts
> +            });
Ohhhhhhhh of course! I never occured to me that making the functions `async` would cause them to return a `Promise` behind the scenes, which would be a truthy value. Someone if 100% going to fall for this again and having no idea what the issue is! Could we maybe force the callbacks to return `boolean | void` and add a comment explaining why `Promises` are forbidden?

2023-09-22 15:03 UTC, cagonzalezcs commented on apps/browser/src/autofill/background/context-menus.background.ts
> +            });
I think that would be would be a solid idea.

2023-09-26 09:09 UTC, coroiu requested changes

2023-09-26 09:09 UTC, coroiu commented on apps/browser/src/popup/app.component.ts
> +    (window as any).bitwardenPopupMainMessageListener = async (msg: any, sender: any) => {
issue: making this function `async` causes the exact scenario that we are trying to avoid, because this function is passed directly to `messageListener` in multiple places, for example on row 132 of this file

```
BrowserApi.messageListener("app.component", (window as any).bitwardenPopupMainMessageListener);
```

2023-09-27 07:42 UTC, coroiu commented on apps/browser/src/popup/app.component.ts
> +    const userIdFromState = await this.stateService.getUserId();
question: why are we not just removing this completely if it isn't used? This would probably break if account switching was implemented, since this variable would not be up-to-date and would not reflect the actual `userId` in use when the message listener would be called

2023-09-27 13:27 UTC, coroiu approved these changes
💯 🔥

2023-09-27 13:28 UTC, coroiu commented on apps/browser/src/autofill/background/context-menus.background.ts
> +            });
Leaving open to make it easier to find in the future

2023-09-27 13:51 UTC, merged