[3914] Refactor Browser Extension Popout Windows
bitwarden/clients pull request #6296
Opened 2023-09-14 19:44 UTC by cagonzalezcs

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Refactor how the browser extension uses pop-out windows, and migrate the logic within `BrowserPopoutWindowService` to the `PopupUtilsService` to consolidate behavior. We're also updating any potential popups that open in a tab to open within a new window to facilitate consistency in the implementation.

## Code changes

- **apps/browser/src/auth/popup/two-factor.component.ts:** As we are updating all "Extension Tab" instances of the popup to a "Window Popout" implementation, the change in this file facilitates closing a potential TwoFactorAuth popout. 
- **apps/browser/src/background/main.background.ts:** Removing `BrowserPopoutWindowService` and replacing usage of the service with the `PopupUtilsService`
- **apps/browser/src/background/runtime.background.ts:** Updating references to the `browserPopoutWindowService`, and changing opening an Add/Edit cipher popup. 2FA popup, and AuthResults popup from opening in a tab to a window.
- **apps/browser/src/platform/browser/browser-api.ts:** Expanding the `getWindow` method to function with or without a window ID value. If an id is not provided, the method attempts to grab the current window that the user has active.Adding a `updateWindowProperties` method to facilitate repositioning and focusing any single use popout windows that might exist. Removing `openBitwardenExtensionTab` and `closeBitwardenExtensionTab` as those represent deprecated methods for facilitating user interactions with the popup outside of the popup itself.
- **apps/browser/src/platform/popup/abstractions/browser-popout-window.service.ts**: Removal of unused abstraction.
- **apps/browser/src/platform/popup/browser-popout-window.service.ts:** Removal of unused class.
- **apps/browser/src/popup/services/popup-utils.service.ts:** This represents the bulk of the implementation, facilitating a migration of the logic within the `BrowserPopoutWindowService` class, and pulling logic for opening popout windows that show the extension vault outside of the scope of the Platform team. Instead of holding references to existing windows, we now depending on a set query param to identify single actin popouts. 
- **apps/browser/src/vault/popup/components/vault/add-edit.component.ts:** Updating logic for the Add/Edit component to facilitate the modified methodology for showing the vault popup outside of the actual extension popup. 

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-09-14 21:40 UTC, jprusik commented on apps/browser/src/popup/services/popup-utils.service.ts
> +    };
Non-blocking opinion; if we're allowing window shape to be overridden, we might as well allow position overrides as well. `url` should not be overridden since we want to ensure only URLs in guardrailed scenarios (via `popupWindowUrl`) can be used

```suggestion
    const windowOptions = {
      left: senderWindow.left + senderWindow.width - popupWidth - offsetRight,
      top: senderWindow.top + offsetTop,
      ...defaultPopoutWindowOptions,
      url: parsedUrl.toString(),
    };
```

2023-09-15 08:44 UTC, Hinton requested changes
I think it's a good start. I would like to see more code owned though.

2023-09-15 08:44 UTC, Hinton commented on apps/browser/src/popup/services/popup-utils.service.ts
> +  }
This portion of the code should be owned by different teams, which I believe necessitates that it gets moved out of this service.

Something like this could work.

```ts
this.popupUtilsService.openPopup(buildTwoFactorUrl(webAuthnResponse, remember));
```

Or something similar to the strong typing for dialogs.

```ts
function openTwoFactorPopup(popupUtilsService, response, remember) {
  popupUtilsService.open(....)
}
```

2023-09-15 08:44 UTC, Hinton commented on apps/browser/src/popup/services/popup-utils.service.ts
I would like this service to be owned by some team. We don't need more code in limbo since non owned code tends to be hard to review, and slow to get reviews for.

2023-09-15 08:44 UTC, Hinton commented on libs/common/src/enums/browser-popout-type.enum.ts
I would ideally like to see these types moved to the teams responsible for them. Maybe using `Opaque<String>` and prefixing keys with the team to avoid collisions.

It's also only relevant for browser and shouldn't be in libs.

2023-09-15 22:55 UTC, cagonzalezcs commented on libs/common/src/enums/browser-popout-type.enum.ts
Done, removed this file and placed relevant enums in a team specific directory, with a prefix to the actual key value relating to the team.

2023-09-15 22:56 UTC, cagonzalezcs commented on apps/browser/src/popup/services/popup-utils.service.ts
Hm, I'm game for discussion on this, but it seems like something that likely would relate more to either the Vault Team or the Platform Team... 

I'm also open to having Autofill own the file, as well as the `browser/src/popup` directory.

2023-09-15 22:57 UTC, cagonzalezcs commented on apps/browser/src/popup/services/popup-utils.service.ts
> +  }
@Hinton 

I took your feedback into consideration and did a rework of the structure to provide more ownership of the popout behavior based on teams and scope of what the popout is attempting to accomplish.

Looking forward to your feedback. If we're moving in the right direction, I'll start working on incorporating Unit Tests.

2023-09-17 22:56 UTC, cagonzalezcs commented on apps/browser/src/popup/services/popup-utils.service.ts
> +    };
Good call, updated the implementation to fit your suggestion.

2023-09-18 09:17 UTC, Hinton commented on apps/browser/src/popup/services/popup-utils.service.ts
Platform is fine in my opinion.

2023-09-18 09:38 UTC, Hinton reviewed
We're a bit back to having two classes again. Albeit one is static and one isn't.

I think we need to write up some guidance on which to use. I think the only stateful portion of `PopupUtilsService` is knowing if the extension is running in private mode which doesn't feel like something it should know.

2023-09-19 09:48 UTC, cagonzalezcs commented on apps/browser/src/popup/services/popup-utils.service.ts
The methods within this util file are now owned by platform within the `BrowserPopupUtils` class.

2023-09-19 10:21 UTC, Hinton commented on apps/browser/src/platform/browser/browser-api.ts
> +      chrome.windows.getCurrent({ populate: true }, (window) => resolve(window))
We could use the shorthand here.
```suggestion
      chrome.windows.getCurrent({ populate: true }, resolve)
```

2023-09-19 10:21 UTC, Hinton commented on apps/browser/src/platform/popup/browser-popup-utils.ts
> +   * @returns {boolean}
This information is already in the typescript signature. I'm hesitant to start adding documentation that easily gets out of sync. Se my expanded discussion in slack https://bitwarden.slack.com/archives/C04LE162PHA/p1695117976087669

2023-09-19 10:21 UTC, Hinton commented on apps/browser/src/popup/services/popup-close-warning.service.ts
> +    this.unloadSubscription = fromEvent(window, "beforeunload").subscribe(
Do you know if we're keeping track of this subscription somewhere to ensure it gets cleaned up for safari?

2023-09-19 10:21 UTC, Hinton commented on apps/browser/src/popup/services/services.module.ts
> +    { provide: PopupCloseWarningService, useFactory: () => new PopupCloseWarningService() },
```suggestion
    PopupCloseWarningService,
```

2023-09-19 10:59 UTC, cagonzalezcs commented on apps/browser/src/popup/services/popup-close-warning.service.ts
> +    this.unloadSubscription = fromEvent(window, "beforeunload").subscribe(
Hm, I'm unsure on that, though from my understanding of the usage of this class, we should be cleaning up the behavior anytime we are exiting the `add-edit.component.ts` component on submission or when the component is closing.

Am I correct in stating that this is cleaned up as soon as the component DOM is out of scope?

2023-09-19 11:00 UTC, cagonzalezcs commented on apps/browser/src/platform/browser/browser-api.ts
> +      chrome.windows.getCurrent({ populate: true }, (window) => resolve(window))
Good call, done.

2023-09-19 11:00 UTC, cagonzalezcs commented on apps/browser/src/vault/popup/utils/vault-popout-window.ts
> +}
Sure, it does span multiple team socpes.

Done.

2023-09-19 11:01 UTC, cagonzalezcs commented on apps/browser/src/popup/services/services.module.ts
> +    { provide: PopupCloseWarningService, useFactory: () => new PopupCloseWarningService() },
This has been taken care of.

2023-09-19 11:12 UTC, cagonzalezcs commented on apps/browser/src/platform/popup/browser-popup-utils.ts
> +   * @returns {boolean}
Done, I've removed typing information for all JSDoc comments present above class methods. These now have brief descriptions on the purpose of the param, and typing information is gathered from the Typescript implementation.

2023-09-19 15:13 UTC, Hinton submitted a review, later dismissed

2023-09-20 18:53 UTC, jprusik approved these changes

2023-09-20 19:35 UTC, JaredSnider-Bitwarden approved these changes
Auth changes look good after a short discussion with @cagonzalezcs! Great work here!

2023-09-20 21:45 UTC, audrey-jensen commented on apps/browser/src/tools/popup/send/send-groupings.component.ts
> +      window.setTimeout(() => BrowserPopupUtils.setContentScrollY(window, this.state?.scrollY), 0);
`setContentScrollY` is always used with `setTimeout`:

* https://github.com/bitwarden/clients/blob/autofill/pm-3914-refactor-browser-extension-popouts/apps/browser/src/tools/popup/send/send-groupings.component.ts
* https://github.com/bitwarden/clients/blob/autofill/pm-3914-refactor-browser-extension-popouts/apps/browser/src/tools/popup/send/send-type.component.ts
* https://github.com/bitwarden/clients/blob/autofill/pm-3914-refactor-browser-extension-popouts/apps/browser/src/vault/popup/components/vault/vault-filter.component.ts
* https://github.com/bitwarden/clients/blob/autofill/pm-3914-refactor-browser-extension-popouts/apps/browser/src/vault/popup/components/vault/vault-items.component.ts

Should the `setTimeout` functionality always be included in the setContentScrollY method?

2023-09-20 21:45 UTC, audrey-jensen commented on apps/browser/src/platform/popup/browser-popup-utils.ts
> +  static setContentScrollY(win: Window, scrollY: number, scrollingContainer = "main"): void {
Consider including promise support if you incorporate setTimeout into this method. Async support is included in other methods in the same class:

https://github.com/bitwarden/clients/blob/cd5e44be142382176221f8ca8a048bea1efa2a69/apps/browser/src/platform/popup/browser-popup-utils.ts#L84-L187

Unlike those methods, this promise would be driven by hand.

```js
const promise = new Promise<void>((resolve) => {
    // let the UI update element positions
    setTimeout(()=> {
            if(scrollY != null) {
                const content = 0// ...
                content.scrollTop = scrollY;
            }
            resolve();
        }, 
        timeout);
    });
    
return promise;
```

2023-09-20 22:31 UTC, cagonzalezcs commented on apps/browser/src/platform/popup/browser-popup-utils.ts
> +  static setContentScrollY(win: Window, scrollY: number, scrollingContainer = "main"): void {
That's a solid idea, given the fact that several locations using this method are set against a `setTimeout` with a value of `0` to debounce the behavior to the next browser computation tick... 

Can it be something that I tackle in a future tech debt ticket? I'd like to avoid introducing additional scope to this ticket if possible.

2023-09-20 22:33 UTC, cagonzalezcs commented on apps/browser/src/tools/popup/send/send-groupings.component.ts
> +      window.setTimeout(() => BrowserPopupUtils.setContentScrollY(window, this.state?.scrollY), 0);
As mentioned in the other comment, I think it's a great idea to rework this method in that manner.

i'll set up a ticket to tackle this tech debt in the future to avoid further extending the life of this PR.

2023-09-21 14:04 UTC, cagonzalezcs commented on apps/browser/src/tools/popup/send/send-groupings.component.ts
> +      window.setTimeout(() => BrowserPopupUtils.setContentScrollY(window, this.state?.scrollY), 0);
As per my other comment, this change is now present.

2023-09-21 14:18 UTC, JaredSnider-Bitwarden approved these changes
New changes LGTM!

2023-09-21 14:53 UTC, audrey-jensen requested changes
Please remove the awaits from callsites for `BrowserPopupUtils.setContent(...)`. The other feedback is optional.

2023-09-21 14:53 UTC, audrey-jensen commented on apps/browser/src/tools/popup/send/send-groupings.component.ts
> +      await BrowserPopupUtils.setContentScrollY(window, this.state?.scrollY);
Adding await here changes the behavior of the method. With the plain setTimeout call, execution of the method continues. With the await, execution blocks until after the scroll state is set. The await should probably be removed here and in the other 3 places this method is called.

```suggestion
     BrowserPopupUtils.setContentScrollY(window, this.state?.scrollY);
```

2023-09-21 14:53 UTC, audrey-jensen commented on apps/browser/src/tools/popup/send/send-type.component.ts
> +        await BrowserPopupUtils.setContentScrollY(window, this.state?.scrollY);
```suggestion
        BrowserPopupUtils.setContentScrollY(window, this.state?.scrollY);
```

2023-09-21 14:53 UTC, audrey-jensen commented on apps/browser/src/vault/popup/components/vault/vault-filter.component.ts
> +        await BrowserPopupUtils.setContentScrollY(window, this.state?.scrollY);
```suggestion
        BrowserPopupUtils.setContentScrollY(window, this.state?.scrollY);
```

2023-09-21 14:53 UTC, audrey-jensen commented on apps/browser/src/vault/popup/components/vault/vault-items.component.ts
> +          this.scrollingContainer
```suggestion
        BrowserPopupUtils.setContentScrollY(
          window,
          this.state.scrollY,
          0,
          this.scrollingContainer
```

2023-09-21 14:53 UTC, audrey-jensen commented on apps/browser/src/platform/popup/browser-popup-utils.spec.ts
> +  describe("setContentScrollY", () => {
A test should be added here to ensure that the promise completes after the scroll position is set.

2023-09-21 14:53 UTC, audrey-jensen commented on apps/browser/src/platform/popup/browser-popup-utils.ts
> +    scrollingContainer = "main"
I wonder whether `delay` and `scrollingContainer` should be passed in as an options object instead of individual parameters.

```ts
interface ScrollOptions {
    /** Amount of time in ms to wait before scrolling the popup. */
    delay: number;
    /** the element type (e.g. h1, p) to scroll. The first element found is scrolled. */
    scrollingContainer: string;
}

setContentScrollY(
    win: Window, 
    scrollY : number, 
    options: ScrollOptions = { delay: 0, scrollingContainer: "main" }
) { // ...
```

2023-09-21 15:35 UTC, cagonzalezcs commented on apps/browser/src/tools/popup/send/send-groupings.component.ts
> +      await BrowserPopupUtils.setContentScrollY(window, this.state?.scrollY);
Updated

2023-09-21 15:36 UTC, cagonzalezcs commented on apps/browser/src/vault/popup/components/vault/vault-filter.component.ts
> +        await BrowserPopupUtils.setContentScrollY(window, this.state?.scrollY);
Updated

2023-09-21 15:36 UTC, cagonzalezcs commented on apps/browser/src/vault/popup/components/vault/vault-items.component.ts
> +          this.scrollingContainer
Updated

2023-09-21 15:36 UTC, cagonzalezcs commented on apps/browser/src/platform/popup/browser-popup-utils.spec.ts
> +  describe("setContentScrollY", () => {
Test has been added.

2023-09-21 15:36 UTC, cagonzalezcs commented on apps/browser/src/platform/popup/browser-popup-utils.ts
> +    scrollingContainer = "main"
Added, and I've also gone ahead and updated how we query the scrolling container to reference a query selector rather than an element.

2023-09-21 17:40 UTC, Hinton submitted a review, later dismissed

2023-09-21 17:43 UTC, audrey-jensen approved these changes

2023-09-28 19:41 UTC, Hinton approved these changes

2023-10-04 19:05 UTC, jlf0dev approved these changes
Looks good for Auth 👍

2023-10-05 21:48 UTC, JaredSnider-Bitwarden approved these changes
👍

2023-10-06 13:42 UTC, audrey-jensen submitted a review, later dismissed

2023-10-06 16:01 UTC, Hinton submitted a review, later dismissed

2023-10-06 21:10 UTC, jprusik approved these changes

2023-10-17 14:34 UTC, audrey-jensen submitted a review, later dismissed
Refreshing my approval after the merge from `master`.

2023-10-17 16:47 UTC, cagonzalezcs commented
> Refreshing my approval after the merge from `master`.

Please hold off on re-approvals for the moment. This work will need to deal with merge conflicts coming in from the passkeys implementation that is merging soon.

2023-10-18 14:33 UTC, audrey-jensen approved these changes

2023-10-18 14:39 UTC, jprusik commented on apps/browser/src/autofill/browser/context-menu-clicked-handler.ts
> +            action: info.parentMenuItemId,
non-blocking nit; since `info.parentMenuItemId` is the switch statement being evaluated, and this code path is for when that value is `COPY_PASSWORD_ID`, I'd argue this change unnecessarily obscures the value being passed here; it doesn't benefit from portability and being explicit saves time when reading the code.

2023-10-18 15:08 UTC, cagonzalezcs commented on apps/browser/src/autofill/browser/context-menu-clicked-handler.ts
> +            action: info.parentMenuItemId,
Fair enough, went ahead and added those in place.

2023-10-18 16:43 UTC, gbubemismith commented on apps/browser/src/vault/popup/components/vault/add-edit.component.ts
> +      this.location.back();
I believe this might be unnecessary as we expect the popout to close following the addition of a passkey

2023-10-18 16:45 UTC, cagonzalezcs commented on apps/browser/src/vault/popup/components/vault/add-edit.component.ts
> +      this.location.back();
Let me test with it being removed, but I wasn't experiencing that behavior.

2023-10-18 16:47 UTC, jprusik submitted a review, later dismissed

2023-10-18 16:50 UTC, gbubemismith commented on apps/browser/src/vault/popup/components/vault/add-edit.component.ts
> +      this.location.back();
It doesn't currently change the behaviour, but I don't think we need it

2023-10-18 16:51 UTC, cagonzalezcs commented on apps/browser/src/vault/popup/components/vault/add-edit.component.ts
> +      this.location.back();
@gbubemismith 

Actually, yeah this is needed in this implementation. It might be due to a difference in how we are closing the popout, but the popout will not close from the add-edit component on submission if we do not push the user back to the fido2 component.

2023-10-18 16:52 UTC, cagonzalezcs commented on apps/browser/src/vault/popup/components/vault/add-edit.component.ts
> +      this.location.back();
If you add the passkey without going to to the add/edit route, then it closes normally as well.

2023-10-18 17:18 UTC, jprusik submitted a review, later dismissed

2023-10-18 17:53 UTC, cagonzalezcs commented on apps/browser/src/vault/popup/components/vault/add-edit.component.ts
> +      this.location.back();
Resolved this on the side with Gbubemi

2023-10-18 17:58 UTC, gbubemismith approved these changes
Looks good from the Vault team's perspective.

2023-10-18 18:37 UTC, jprusik approved these changes

2023-10-18 23:13 UTC, gbubemismith approved these changes

2023-10-19 08:42 UTC, Hinton commented on apps/browser/src/platform/popup/browser-popup-utils.ts
> +   */
**question**: This sounds more like a builder, and it appends singleActionKey at the end which isn't consistent with a parser?

2023-10-19 12:45 UTC, cagonzalezcs commented on apps/browser/src/platform/popup/browser-popup-utils.ts
> +   */
Good point, let me update the name and description to fit that. 

I think I kept it that way because we originally were using the `URL` API to parse the route. Turns out that using that to set search params breaks routing within the popout (due to the placement of the hash). 

Updating this now.

2023-10-19 13:44 UTC, Hinton approved these changes

2023-10-19 13:45 UTC, Hinton commented on apps/browser/src/platform/popup/browser-popup-utils.ts
> +    popoutTabs.forEach((tab) => BrowserApi.removeTab(tab.id));
👍

2023-10-19 13:58 UTC, jprusik approved these changes

2023-10-19 14:07 UTC, gbubemismith submitted a review, later dismissed

2023-10-19 14:27 UTC, audrey-jensen submitted a review, later dismissed

2023-10-19 16:21 UTC, JaredSnider-Bitwarden reviewed
What a fantastic, well tested set of changes! Just a few notes below:

2023-10-19 16:21 UTC, JaredSnider-Bitwarden commented on apps/browser/src/auth/popup/utils/auth-popout-window.spec.ts
> +      closeTwoFactorAuthPopout();
Potential issue: missing `await`?

2023-10-19 16:21 UTC, JaredSnider-Bitwarden commented on apps/browser/src/auth/popup/utils/auth-popout-window.spec.ts
> +    });
Minor (nit-pick):  can you use `AuthPopoutType.unlockExtension` to prevent magic string use?

2023-10-19 16:21 UTC, JaredSnider-Bitwarden commented on apps/browser/src/auth/popup/utils/auth-popout-window.ts
> +  await BrowserApi.tabSendMessageData(senderTab, "bgUnlockPopoutOpened");
Minor (non-blocking): in the future iterations, hopefully we can use types or enums for stuff like `bgUnlockPopoutOpened` to get rid of these magic strings.

2023-10-19 16:21 UTC, JaredSnider-Bitwarden commented on apps/browser/src/autofill/background/notification.background.ts
> +      case "bgUnlockPopoutOpened":
Much better name!

2023-10-19 16:21 UTC, JaredSnider-Bitwarden commented on apps/browser/src/autofill/browser/context-menu-clicked-handler.ts
> +            action: COPY_VERIFICATIONCODE_ID,
Nit pick (non-blocking):  `COPY_VERIFICATIONCODE_ID` feels slightly weird when all the constants have _ between each word. `COPY_VERIFICATION_CODE_ID` would match better.

2023-10-19 18:21 UTC, cagonzalezcs commented on apps/browser/src/platform/popup/browser-popup-utils.ts
> +    return win.location.href.indexOf(`${searchParam}=${searchValue}`) > -1;
@JaredSnider-Bitwarden 

Actually, I had used a similar methodology prior to the current changes in place. Turns out a significant flaw exists with how Angular routes in our popout application though. Because the routes of our popup is structured with a hash before the path is set, we run into an issue where search params are not correctly interpreted by the `URL` API.

`chrome-extension://cdnjlehnglahbmidpmefcbfjcibnoacf/popup/index.html#/lock`

So something like the following:

`chrome-extension://cdnjlehnglahbmidpmefcbfjcibnoacf/popup/index.html#/lock?queryParam=thisParam`

Doesn't actually show as having a parameter in place. When you use the `URL` API to set the search params, the URL will format as such

`chrome-extension://cdnjlehnglahbmidpmefcbfjcibnoacf/popup/index.htm?queryParam=thisParaml#/lock`

The problem with that being that it seems to break routing in angular when setting the query params in such a manner. 

I know it's less elegant to check the whole href, but doing it in this manner sets the query params in place while avoiding breaking routing within the Angular app... that's why I structured it so. Down the line it might be a good idea to fix how Angular is routing, but that's definitely out of the scope of this ticket.

2023-10-19 18:22 UTC, JaredSnider-Bitwarden commented on apps/browser/src/platform/popup/browser-popup-utils.ts
> +    return win.location.href.indexOf(`${searchParam}=${searchValue}`) > -1;
Oh wow, yeah, that's a massive flaw. Thank you for the explanation!

2023-10-19 18:47 UTC, cagonzalezcs commented on apps/browser/src/auth/popup/utils/auth-popout-window.spec.ts
> +      openSsoAuthResultPopout({ code: "code", state: "state" });
So in an effort to try to get this PR moving forward, I decided to apply your feedback to the PR for [PM-3036](https://github.com/bitwarden/clients/pull/6514).

The requested changes are non critical concerns, as the missing `awaits` in the tests are not going to invalidate the unit test itself. That said, with a preference to follow your example and await any promises, I've applied those values in this file from the PR linked above - https://github.com/bitwarden/clients/pull/6514/files#diff-6259f63bb80bd9c5064a3d6655b599ec7cc3a037152dc9990a53d284c50a03b9

2023-10-19 18:47 UTC, cagonzalezcs commented on apps/browser/src/auth/popup/utils/auth-popout-window.spec.ts
> +      openTwoFactorAuthPopout({ data: "data", remember: "remember" });
Addressed in the PR form PM-3036 - https://github.com/bitwarden/clients/pull/6296#discussion_r1365972458

2023-10-19 18:48 UTC, cagonzalezcs commented on apps/browser/src/auth/popup/utils/auth-popout-window.ts
> +  await BrowserApi.tabSendMessageData(senderTab, "bgUnlockPopoutOpened");
Good catch, I've addressed this in the PR for PM-3036 as well.

https://github.com/bitwarden/clients/pull/6514/files#diff-6259f63bb80bd9c5064a3d6655b599ec7cc3a037152dc9990a53d284c50a03b9

2023-10-19 18:49 UTC, cagonzalezcs commented on apps/browser/src/auth/popup/utils/auth-popout-window.spec.ts
> +    });
Good catch, I've addressed this in the PR for PM-3036 as well.

https://github.com/bitwarden/clients/pull/6514/files#diff-6259f63bb80bd9c5064a3d6655b599ec7cc3a037152dc9990a53d284c50a03b9

2023-10-19 18:49 UTC, cagonzalezcs commented on apps/browser/src/auth/popup/utils/auth-popout-window.ts
> +  await BrowserApi.tabSendMessageData(senderTab, "bgUnlockPopoutOpened");
Ah yeah, this is a solid idea. We have tons of messages present within the extension, however.... might be a good BEEEP project to try to consolidate all of them into enum values. 

I'll keep it in mind for tomorrow.

2023-10-19 18:50 UTC, cagonzalezcs commented on apps/browser/src/autofill/browser/context-menu-clicked-handler.ts
> +            action: COPY_VERIFICATIONCODE_ID,
I agree, though this change does touch a number of files. I've gone ahead and address it in the PR for PM-3036, similar to the other concerns.

2023-10-19 18:51 UTC, JaredSnider-Bitwarden approved these changes
Awesome work!

2023-10-20 14:18 UTC, jlf0dev submitted a review, later dismissed

2023-10-20 16:57 UTC, gbubemismith approved these changes

2023-10-20 18:23 UTC, jprusik approved these changes

2023-10-23 15:48 UTC, jprusik submitted a review, later dismissed

2023-10-24 13:49 UTC, jprusik approved these changes

2023-11-08 17:49 UTC, jprusik approved these changes

2023-11-08 17:51 UTC, MGibson1 approved these changes

2023-11-08 17:52 UTC, audrey-jensen approved these changes

2023-11-08 17:56 UTC, gbubemismith approved these changes

2023-11-08 18:49 UTC, JaredSnider-Bitwarden approved these changes
LGTM!

2023-11-08 18:57 UTC, merged