[PM-3980] Add a creationDate field to the Fido2Key object
bitwarden/clients pull request #6334
Opened 2023-09-18 20:37 UTC by gbubemismith

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
Add `creationDate` field to the `Fido2Key` object; this field will specifically capture and represent the timestamp of when the passkey is created. 

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-09-19 10:23 UTC, LRNcardozoWDF approved these changes
LGTM!

2023-09-19 12:52 UTC, gbubemismith commented on libs/common/src/models/export/fido2key.export.ts
> +  creationDate: Date = null;
Since I didn't plan to have the `creationDate` encrypted, I decided to keep it consistent with how we store dates.

2023-09-19 12:52 UTC, gbubemismith commented on libs/common/src/models/export/fido2key.export.ts
> +  creationDate: Date = null;
Missed that too : (

2023-09-20 12:03 UTC, coroiu approved these changes

2023-09-21 08:53 UTC, coroiu commented on libs/common/src/models/export/fido2key.export.ts
> +    view.discoverable = !!req.discoverable;
@djsmith85 asked me about the `!!` operation, and I think we should change this to be consistent with how we convert Domain -> View
```suggestion
    view.discoverable = discoverable === "true"
```

2023-09-21 09:27 UTC, djsmith85 requested changes

2023-09-21 09:27 UTC, djsmith85 commented on libs/common/src/models/export/fido2key.export.ts
>    constructor(o?: Fido2KeyView | Fido2KeyDomain) {
Assignment of `discoverable` and `creationDate` needs to be added in the constructor

2023-09-21 10:11 UTC, djsmith85 requested changes
`fido2key.export.ts` should also be exported through `models/export/index.ts`

2023-09-21 14:08 UTC, djsmith85 approved these changes

2023-09-21 14:39 UTC, coroiu approved these changes

2023-09-21 16:30 UTC, merged