[PM-3812] Unify Create and Login Passkeys View
bitwarden/clients pull request #6403
Opened 2023-09-25 19:18 UTC by gbubemismith

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-09-26 04:07 UTC, gbubemismith commented
I had to compress the video to upload it. Unfortunately, it cut out the top.

2023-09-28 12:49 UTC, Hinton reviewed
We seem to be mixing in a lot of passkey knowledge in various components. That's not going to scale and is quite confusing.

We also seem to be setting `uilocation` in various places, that's typically a search value not a query param and persists across redirects and pages.

The popup utils are changing a fair bit in https://github.com/bitwarden/clients/pull/6296.

2023-09-28 12:49 UTC, Hinton commented on apps/browser/src/popup/scss/base.scss
> +    .auth-header {
This shouldn't be in base.scss.

2023-09-28 12:49 UTC, Hinton commented on apps/browser/src/platform/popup/abstractions/browser-popout-window.service.ts
This will all change with https://github.com/bitwarden/clients/pull/6296. Please ensure that PR is merged before this lands in master.

2023-09-28 12:55 UTC, coroiu reviewed
I have not performed a comprehensive review! Waiting for an eventual solution to Oscars comments

2023-09-28 17:07 UTC, trmartin4 commented
> We seem to be mixing in a lot of passkey knowledge in various components. That's not going to scale and is quite confusing. I believe this needs to be extracted in some way.

@Hinton, can you offer a way that this could be extracted?  After consulting with Auth we may take an iterative approach in which we introduce the passkey logic in the components and then refactor into an extracted abstraction separately.  We would like to understand how you see this being abstracted first.

2023-09-28 17:16 UTC, trmartin4 commented on apps/browser/src/platform/popup/abstractions/browser-popout-window.service.ts
@cagonzalezcs had talked with @gbubemismith and preferred for Passkeys to land in `master` prior to his PR.  I'd like to make sure we are on the same page as to the order here.

2023-09-28 19:45 UTC, Hinton commented
@trmartin4 the concern is that the following components are tightly coupled to passkeys:

- Home
- Lock
- Login
- two-factor-options
- Vault add-edit

If we ever want the passkey "prompt" to be able to navigate to other pages those would need to contain the duplicated code.

2023-09-29 07:50 UTC, coroiu commented
@Hinton 
I chatted with @gbubemismith a little bit about this, after asked me if I had ideas on how to address your concerns. He might have already discussed this with you, in which case the following will be more for future reference! 

It appears that one of the main culprits is the `Use browser` button. 

![image](https://github.com/bitwarden/clients/assets/2285588/1a6ff86b-c1ae-4403-9a09-aa04600b193a)

I tentatively suggested that he could try wrapping that button in a separate component 

```html
<app-fido2-browser-fallback></app-fido2-browser-fallback>
```

and move all navigation and show/no-show logic into it, thereby consolidating most of the `fido2` logic. It's still not generic, and still requires putting that component into the templates of all those places you mentioned.

2023-09-29 09:19 UTC, Hinton commented on apps/browser/src/platform/popup/abstractions/browser-popout-window.service.ts
I would have preferred the other way around since #6296 seems ready to merge while passkeys in vault have a few bugs and things to fix first. But either works.

2023-09-29 09:33 UTC, Hinton commented on apps/browser/src/vault/popup/components/fido2/fido2.component.html
> +      <a [routerLink]="[]" *ngIf="data.fallbackSupported" (click)="abort(true)">
This differs from the other places, why is this the only place we care about checking `fallbackSupported`?

2023-09-29 10:00 UTC, Hinton commented
Aborting requests doesn't seem to return the correct error message.

2023-09-29 10:28 UTC, Hinton reviewed
I dug into the suggestion by @coroiu in https://github.com/bitwarden/clients/compare/PM-3812/unify-ui-create-passkeys...PM-3812/review-feedback and while I think it's an improvement I had hoped to exclude it completely from the components into perhaps a layout but that doesn't seem quite feasible.

My primary concern is that we're adding new flows for home, login, 2fa, add-edit component. This means that whenever these components change in the future care must be taken to test and preserve the passkey flows. And care must be taken to never diverge from these flows which I believe will lead to bugs in the future. (Closing the add-edit page already terminates the flow which as a user I find confusing).

Most of the browser functionality requires the vault to be logged in if not unlocked so it's somewhat puzzling that we explicitly handle logged out vaults for passkeys when we don't do so for autofill notifications. And that we have to add in-app cancel buttons to various pages. Did we consider just using the browser popup closed as a cancellation action by itself?

Ultimately these components will be owned and maintained by the auth team so it's up to them to decide if they want the burden of maintaining the fido2 flows.

An alternative path forward would be to build new page level components for these functionalities but the maintenance burden of that seems high especially since we have to support many login approaches and the codebase isn't built to handle this currently.

2023-09-29 10:28 UTC, Hinton commented on apps/browser/src/auth/popup/home.component.ts
> +    });
I think we can conclude that query params is not a good place for `uilocation` to live. Can we create a tech debt ticket to persist uilocation in a popup service instead?

In the meanwhile for this PR lets change this to use `queryParamsHandling: "merge"`.

2023-10-04 18:03 UTC, JaredSnider-Bitwarden approved these changes
LGTM! Reviewed together with @gbubemismith on a call.

2023-10-04 19:11 UTC, Jingo88 approved these changes

2023-10-04 19:59 UTC, Jingo88 commented
LGTM. Just a quick question, are we concerned at all about some of the CodeScene complexity warnings?

2023-10-04 21:30 UTC, Hinton requested changes
This review follows the [Conventional Comments](https://conventionalcomments.org/) labels. There are a few blockers here, as well as a few suggestions and some notes. 

I think the Fido2 component is weirdly written which will be difficult to maintain. But I've not explicitly marked any blockers on it other than resolving the selected component which is very confusing currently.

2023-10-04 21:30 UTC, Hinton commented on libs/common/src/vault/services/fido2/fido2-client.service.ts
> +    }
**question:** We don't typically do explicit null checks in our application. Is there an explicit concern that `tab` might be null, that doesn't apply to `params` for example.

2023-10-04 21:30 UTC, Hinton commented on apps/browser/src/vault/popup/components/vault/view.component.ts
> +    });
**suggestion:** This leaks some of the inner workings of the `BrowserFido2UserInterfaceSession` into the component. I believe a cleaner approach would be to have an explicit `abrot` method on the service which just takes the `SessionId`.

2023-10-04 21:30 UTC, Hinton commented on apps/browser/src/vault/popup/components/vault/add-edit.component.ts
> +    });
**suggestion:** This leaks some of the inner workings of the `BrowserFido2UserInterfaceSession` into the component. I believe a cleaner approach would be to have an explicit `abrot` method on the service which just takes the `SessionId`.

2023-10-04 21:30 UTC, Hinton commented on apps/browser/src/vault/popup/components/vault/add-edit.component.ts
> +  uilocation?: "popout" | "popup" | "sidebar" | "tab";
**note**: Ensure this gets cleaned up with the refactor for popout.

2023-10-04 21:30 UTC, Hinton commented on apps/browser/src/vault/popup/components/fido2/fido2.component.ts
> +  hostname: string;
**question:** Are these actually public? Variables used in the template should use `protected`.

2023-10-04 21:30 UTC, Hinton commented on apps/browser/src/vault/popup/components/fido2/fido2-cipher-row.component.ts
> +  }
**issue:** Direct element access in angular is highly discouraged. This would typically be handled in the template instead.

2023-10-04 21:30 UTC, Hinton commented on apps/browser/src/vault/popup/components/fido2/fido2-cipher-row.component.ts
> +  @Input() selectedCipher: CipherView;
**question:** Why would the row need to know the selected cipher?

I would suggest structuring the row as a presentational component with clear inputs.

2023-10-04 21:30 UTC, Hinton commented on apps/browser/src/vault/popup/components/fido2/fido2.component.ts
**suggestion:** This component seems to be doing a lot of things. It's not in my pureview but testing this will be close to impossibe. And I highly suggest breaking out the business logic into a service that can be tested.

**note:** At a quick glance the component seems to be keeping track of many different states which is often a sign of codesmell.

2023-10-05 12:41 UTC, gbubemismith commented on apps/browser/src/popup/scss/base.scss
> +  width: 100%;
This isn't needed anymore. It got in from the previous work on the home and login component.

2023-10-05 12:42 UTC, gbubemismith commented on apps/browser/src/popup/scss/pages.scss
> +app-fido2 {
I would clean up the redundant styles on this. Thanks.

2023-10-05 16:24 UTC, trmartin4 commented on apps/browser/src/vault/popup/components/fido2/fido2.component.ts
The Vault team agreed with that assessment and already had plans to do this refactoring, as the `Fido2Component` has grown from its original implementation.  We will be addressing that in https://bitwarden.atlassian.net/browse/PM-4231 either this sprint or next.

2023-10-05 18:18 UTC, gbubemismith commented on libs/common/src/vault/services/fido2/fido2-client.service.ts
> +    }
There's no genuine concern; I just wanted to be extra safe, but this can be removed.

2023-10-09 10:30 UTC, Hinton commented on apps/browser/src/vault/popup/components/fido2/fido2-cipher-row.component.ts
> +  }
Resolved with [b8edd62](https://github.com/bitwarden/clients/pull/6403/commits/b8edd62d23c9a45d86ebbd1e1636a301b7e6165f)

2023-10-09 10:37 UTC, Hinton commented on apps/browser/src/vault/popup/components/vault/view.component.ts
> +    });
Resolved with https://github.com/bitwarden/clients/pull/6403/commits/2668fbed6c26d536f61e00bc2620371430959b97

2023-10-09 10:38 UTC, Hinton commented on apps/browser/src/vault/popup/components/vault/add-edit.component.ts
> +    });
https://github.com/bitwarden/clients/pull/6403/commits/2668fbed6c26d536f61e00bc2620371430959b97

2023-10-09 10:38 UTC, Hinton commented on apps/browser/src/popup/scss/base.scss
> +  width: 100%;
Resolved with https://github.com/bitwarden/clients/pull/6403/commits/9754fb020d556c2dabc3c18f4fdb4f408a25f102.

2023-10-09 10:39 UTC, Hinton commented on apps/browser/src/auth/popup/lock.component.html
Resolved with https://github.com/bitwarden/clients/pull/6403/commits/d76a3fc3fcadd828ab99dbc6a459b31a74ca3130

2023-10-09 10:39 UTC, Hinton commented on apps/browser/src/vault/popup/services/fido2-state.service.ts
Removed in https://github.com/bitwarden/clients/pull/6403/commits/d76a3fc3fcadd828ab99dbc6a459b31a74ca3130.

2023-10-09 10:40 UTC, Hinton commented on libs/common/src/vault/services/fido2/fido2-authenticator.service.spec.ts
> +  let tab!: any;
Resolved with [`e579f17` (#6403)](https://github.com/bitwarden/clients/pull/6403/commits/e579f172e4b747f7078b707f9b17f3485e4c6b61)

2023-10-09 10:40 UTC, Hinton commented on libs/common/src/vault/services/fido2/fido2-client.service.spec.ts
> +  let tab!: any;
Resolved with [`e579f17` (#6403)](https://github.com/bitwarden/clients/pull/6403/commits/e579f172e4b747f7078b707f9b17f3485e4c6b61)

2023-10-09 10:40 UTC, Hinton commented on libs/common/src/vault/services/fido2/fido2-client.service.ts
> +    }
Resolved with [`e579f17` (#6403)](https://github.com/bitwarden/clients/pull/6403/commits/e579f172e4b747f7078b707f9b17f3485e4c6b61)

2023-10-09 15:55 UTC, Hinton approved these changes
Two notes.

2023-10-09 15:55 UTC, Hinton commented on apps/browser/src/vault/fido2/browser-fido2-user-interface.service.ts
> +  const route = inject(ActivatedRoute);
**note**: This can be a bit confusing to follow, routes are usually tightly coupled to routeable components and it might not be obvious the component expects these query params.

2023-10-09 15:55 UTC, Hinton commented on apps/browser/src/vault/popup/components/fido2/fido2-use-browser-link.component.ts
> +    });
**question:** Should this use `abortPopout`? I noticed the fallbackRequested is different but it's otherwise the same message.

2023-10-09 15:58 UTC, gbubemismith commented on apps/browser/src/vault/popup/components/fido2/fido2-use-browser-link.component.ts
> +    });
Yeah, I can modify `abortPopout` to have a  `fallbackRequested` parameter.

2023-10-09 17:32 UTC, Hinton approved these changes

2023-10-10 20:34 UTC, merged