{SM-847] Updated Delete service account modal to be default size, not small
bitwarden/clients pull request #6405
Opened 2023-09-25 20:42 UTC by cd-bitwarden

## Type of change

```
- [ x ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/dialog/service-account-delete-dialog.component.html 
 - made the delete service account modal bigger by setting dialogSize to default
## Code changes

Updated modal size to Default instead of small

## Screenshots

![image](https://github.com/bitwarden/clients/assets/106776772/71a293da-8dc8-4742-87e3-cc31ffb2cd4f)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-09-28 19:45 UTC, Thomas-Avery requested changes

2023-09-28 19:45 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/dialog/service-account-dialog.component.html
> +  <bit-dialog dialogSize="default">
If we are updating the size of the creation/edit dialog for service accounts, we will probably want to update the project create/edit dialog too.

2023-10-05 17:38 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/dialog/service-account-dialog.component.html
> +  <bit-dialog dialogSize="default">
okay i updated project-dialog.component.html as well 😄

2023-10-05 20:53 UTC, Thomas-Avery approved these changes
LGTM

2023-10-05 21:20 UTC, cd-bitwarden commented
Ready to be tested

2023-10-10 16:35 UTC, merged