[PM-3388] AnonLayout Component
bitwarden/clients pull request #6424
Opened 2023-09-27 15:31 UTC by rr-bw

## Type of change

- New feature development

## Objective

Create a bare-bones AnonLayout component for use in unauthenticated pages.

## Code changes

- Add AnonLayout files and Stories
  - `libs/auth/src/components/anon-layout`
- Update Tailwind config settings
  - `libs/components/tailwind.config.base.js`
  - `libs/components/tailwind.config.js`

## Screencast

https://github.com/bitwarden/clients/assets/102181210/009f2b73-ea4b-4333-89af-0448804557bf

2023-09-27 20:56 UTC, willmartian commented
Would it make sense to put this component in [libs/auth](https://github.com/bitwarden/clients/tree/master/libs/auth)? I imagine it might be used across clients in the future.

2023-10-06 19:39 UTC, jlf0dev reviewed
Nice! A video demonstrating the responsiveness might be a quick way to see it in action.

2023-10-06 19:39 UTC, jlf0dev commented on libs/auth/src/components/anon-layout.stories.ts
> +        <div class="tw-flex tw-flex-col tw-gap-4 tw-bg-secondary-100 tw-p-6">
Is this just the padding between the content and the border? If so should we include it in the layout?
Also, my css is a little fuzzy but why do we need the flex?

2023-10-06 21:17 UTC, rr-bw commented on libs/auth/src/components/anon-layout.stories.ts
> +        <div class="tw-flex tw-flex-col tw-gap-4 tw-bg-secondary-100 tw-p-6">
@jlf0dev

That `<div>` is just some arbitrary sample content, and the styling is just to make it look decent. It could be replaced with any content and styling. I've restructured it a bit and added more stories and comments to make it more clear than any content can go within the `<anon-layout>` tags.

The padding between the 1px border and the projected content is built into the anon-layout component on line 8 of `anon-layout.component.html` (`sm:tw-p-8`).

(As a side note, that `tw-flex, tw-flex-col tw-gap-4` was just a simple way of adding spacing between all of the inner `<div>` elements. That way you don't need to add something like `tw-mb-4` to each inner `<div>`.)

2023-10-06 21:33 UTC, rr-bw commented on libs/auth/src/components/anon-layout.stories.ts
> +        <div class="tw-flex tw-flex-col tw-gap-4 tw-bg-secondary-100 tw-p-6">
@jlf0dev Screenshot added :)

2023-10-13 03:30 UTC, willmartian approved these changes
CL changes look good. 

General question, how might this relate to the "card" component that @Hinton extracted in [this PR? ](https://github.com/bitwarden/clients/pull/6237/files)

Thinking about the ergonomics of the `secondary` slot. Will the content passed to it often be closely related to the content in the default slot? If so, do you envision it being a headache to split up the content across two router outlets? 

The alternative would be to only have **one** `ng-content` slot here and pass into it a "card" component followed by any other secondary content

(More so questions rather than concerns)

2023-10-13 18:28 UTC, jtouchstonebw approved these changes
LGTM 🧞‍♀️

2023-10-16 13:20 UTC, Hinton requested changes
Following up on @willmartian question.

What is the indented usage of the component? I think this determines how to implement the component.

Will it have a routeable layout component, with two router outlets? Are every route expected to use the layout itself? I would generally advice against every component directly using the layout as we miss the advantages of nested routes in Angular.

```ts
 {
    path: "",
    component: RouteableLayout,
    children: [
      {
        path: "",
        component: LoginComponent
      },
      {
        path: "",
        component: LoginComponent,
        outlet: 'footer'
      },
      ...
}
```

2023-10-16 13:20 UTC, Hinton commented on libs/components/tailwind.config.js
> +  "libs/auth/src/components/**/*.{html,ts,mdx}",
**question:** Is there a reason to use the `components` directory here?

```suggestion
  "libs/auth/src/**/*.{html,ts,mdx}",
```

2023-10-16 13:20 UTC, Hinton commented on libs/components/tailwind.config.base.js
> +    "../../libs/auth/src/components/**/*.{html,ts}",
**question:** Is there a reason to use the `components` directory here?

```suggestion
    "../../libs/auth/src/**/*.{html,ts}",
```

2023-10-16 13:20 UTC, Hinton commented on libs/auth/src/components/anon-layout.component.css
> +}
**question:** Any reason to not use bit-icon instead of implementing it using css?

2023-10-16 13:20 UTC, Hinton commented on libs/auth/src/components/anon-layout.component.html
**thought:** I think the naming of this component is kind of confusing. What are the reasoning behind calling it `anon`, would calling it `AuthLayout` work?

2023-10-16 13:20 UTC, Hinton commented on libs/auth/src/components/anon-layout.stories.ts
> +  title: "Web/Anon Layout",
**issue:** This should be under `auth`.

```suggestion
  title: "Auth/Anon Layout",
```

2023-10-16 13:20 UTC, Hinton commented on libs/auth/src/components/anon-layout.component.ts
> +  styleUrls: ["./anon-layout.component.css"],
**issue:** `styleUrls` requires CSP whitelisting, for this reason we typically do not use them in our codebase.

2023-10-16 13:23 UTC, Hinton commented on libs/auth/src/components/anon-layout.component.ts
> +  selector: "anon-layout",
**issue:** Should be prefixed with `auth-`.

2023-10-23 14:11 UTC, danielleflinn commented on libs/auth/src/components/anon-layout.component.html
Correct; since we will likley be using the component in the view Send link instance the Auth and Tools team felt we should choose a name that wouldn't tie the component to a specific team. Thus "Anon" short for Anonymous layout was chosen.

2024-01-05 22:06 UTC, rr-bw commented
@Hinton @willmartian

Sorry I'm finally getting back to this. For context for this conversation, first see Will's [comment](https://github.com/bitwarden/clients/pull/6424#pullrequestreview-1675633623), then Oscar's [comment](https://github.com/bitwarden/clients/pull/6424#pullrequestreview-1679952327), and then my response below.

The secondary content is more generic and presentational (click to go to Log in page, click to go to Register page, etc.). So it is not tightly coupled _logically_ to the primary content. I was thinking the best way to implement it is much like Oscar mentioned with nested routes.

So we'd created a routable layout component, say `anonymous-layout.component.ts`, in `web/src/app/layouts`. The contents would being something like:

```javascript
<auth-anon-layout>
  <router-outlet></router-outlet>
  <router-outlet slot="secondary" name="secondary"></router-outlet>
</auth-anon-layout>
```

and then control the content via the router Oscar showed.

That said, I could go either way on this. Let me know what y'all think and if you'd rather use one `ng-content` instead.

2024-01-12 13:31 UTC, Hinton commented
@rr-bw Sounds reasonable to me. @willmartian anything to add?

2024-01-12 13:33 UTC, Hinton commented on libs/auth/src/components/logo.svg
Is this the same logo as `bitwaden-logo.ts`?

2024-01-12 13:33 UTC, Hinton commented on libs/auth/src/components/icon-lock.ts
You can probably minify this and decrease the size by ~50%, https://svgomg.net/

2024-01-12 13:33 UTC, Hinton commented on libs/auth/src/components/bitwarden-logo.ts
You can probably minify this and decrease the size by ~30%, https://svgomg.net/

2024-01-23 16:46 UTC, willmartian commented on libs/auth/src/components/anon-layout.stories.ts
> +    ),
Is this wrapper necessary? It is used in `bit-layout` because it has a fixed position, but otherwise it isn't needed.

2024-01-23 16:46 UTC, willmartian commented on libs/auth/src/components/bitwarden-logo.ts
@bitwarden/dept-design, is this logo color correct in dark mode? 

<img width="562" alt="image" src="https://github.com/bitwarden/clients/assets/17113462/b13043d8-d6fd-47d5-8a29-696ed9572e29">


@rr-bw we typically update svgs to use our Tailwind color palette by removing the `fill` property and applying a clas: https://tailwindcss.com/docs/fill

2024-01-23 16:46 UTC, willmartian commented on libs/auth/src/components/anon-layout.component.html
> +    <h2 class="tw-mt-4">{{ subTitle }}</h2>
1. These should likely use the `bitTypography` directives instead of custom text styles: https://components.bitwarden.com/?path=/docs/component-library-typography--docs

2. Will every page have a `title` and `subtitle`? If not, we should mark these both with `*ngIf="title"` and `*ngIf="subTitle"` respectively to avoid having empty header elements on the page.

2024-01-23 16:46 UTC, willmartian commented on libs/auth/src/components/anon-layout.component.ts
> +  @Input() subTitle: string;
"subtitle" is one word and doesn't need to be camelCase

2024-01-23 16:46 UTC, willmartian commented on libs/auth/src/components/bitwarden-logo.ts
Also, should we add an accessible title to the logo? (Maybe just "Bitwarden")?

2024-01-24 18:40 UTC, danielleflinn commented on libs/auth/src/components/bitwarden-logo.ts
Logo color in both themes should be `primary-500`. And I think adding the accessibility title is a great point. Looking at our current login layout we use "Bitwarden" – that should be fine to use here too.

2024-01-25 13:57 UTC, willmartian requested changes

2024-01-25 13:57 UTC, willmartian commented on libs/auth/src/components/anon-layout.component.html
> +      ></bit-icon>
For SVGs, I believe we want to use the `<title>` element within the SVG body instead of `appA11yTitle`

2024-01-25 23:21 UTC, willmartian submitted a review, later dismissed
LGTM 🚀

2024-01-29 19:45 UTC, danielleflinn requested changes
As @rr-bw and I discussed, a few small UI changes to make this inline with Figma:

- Update the style of the Page title to heading 2 
- On smaller screens (same breakpoint as when we start shrinking the logo), the heading style should drop to heading 3
- In the storybook stories: update the stories to just say "The page title"
- Also remove the background highlight in the stories to be more consistent with how we present other component documentation

Thank you for all the amazing work on this! It's come together so well 🥳

2024-01-29 21:18 UTC, danielleflinn requested changes

2024-01-29 21:18 UTC, danielleflinn commented on libs/auth/src/components/anon-layout.component.html
> +>
@rr-bw sorry one last tweak. Can we drop the `tw-gap-12` to` tw-gap-9`? 
In Figma I'd missed the margin we have on the typography components to I think this spacing looks a bit nicer in Storybook.

2024-01-29 21:18 UTC, danielleflinn commented on libs/auth/src/components/anon-layout.component.html
> +  <div class="tw-mb-auto tw-mx-auto tw-max-w-md tw-grid tw-gap-12">
Same for this grid-gap. Can we drop this to `tw-gap-9`?

2024-01-29 21:49 UTC, danielleflinn approved these changes
Looks good! Thanks again for all your hard work on this!

2024-01-29 21:58 UTC, willmartian approved these changes

2024-02-01 16:26 UTC, jlf0dev requested changes
Can we move these to a feature folder under `angular`? Something like `libs/auth/src/angular/anon-layout`?

2024-02-05 13:40 UTC, jlf0dev submitted a review, later dismissed
Thank you! Excellent work, looking forward to seeing this used 🙌

2024-02-05 16:17 UTC, danielleflinn submitted a review, later dismissed

2024-02-05 22:16 UTC, willmartian approved these changes
LGTM! Thanks @rr-bw

2024-02-08 17:17 UTC, rr-bw commented on libs/auth/src/angular/anon-layout/bitwarden-logo.ts
> +    <path class="tw-fill-primary-500" d="M32.041 24.546V5.95H18.848v33.035c2.336-1.22 4.427-2.547 6.272-3.98 4.614-3.565 6.921-7.051 6.921-10.46Zm5.654-22.314v22.314c0 1.665-.329 3.317-.986 4.953-.65
@Hinton Fixed!

2024-02-09 14:01 UTC, Hinton commented on libs/auth/src/angular/anon-layout/anon-layout.component.ts
> +  year = "2023";
**issue:** Please make these protected, as the less public members the better.

2024-02-09 20:15 UTC, rr-bw commented on libs/auth/src/angular/anon-layout/anon-layout.component.ts
> +  year = "2023";
@Hinton Fixed!

2024-02-09 20:21 UTC, rr-bw commented on libs/auth/src/angular/anon-layout/anon-layout.component.ts
> +    }
@Hinton Good catch. Design shows only one optional icon (the Lock). I removed the switch statement and also refactored both the icons (Logo and Lock) into an icons folder. This way we can re-use the icons in auth code later if needed, and continue making use of `<bit-icon>`. This is the same pattern we use [here](https://github.com/bitwarden/clients/blob/de40e0687c493071eff3616664f966d40e8ad12d/apps/web/src/app/auth/login/login-via-webauthn/login-via-webauthn.component.ts#L12)

2024-02-09 21:28 UTC, rr-bw commented on libs/auth/src/angular/anon-layout/anon-layout.component.ts
> +    }
@danielleflinn Well in that case I probably should revert back to the the way I had it. That is, in the future if we need another icon, the developer can simply add to the switch statement (the lines Oscar highlighted above), and using a specific icon would look something like `<bit-icon [icon]="lock">` or `<bit-icon [icon]="unlock">` depending on the icon. I can still keep the part where I refactored the icons into their own folder.

2024-02-10 01:07 UTC, rr-bw commented on libs/auth/src/angular/anon-layout/anon-layout.component.ts
> +    }
@Hinton Since we will want to add additional icons in the future, I reverted back to my original implementation with the switch statement. This way the foundation is already set for new icons when that time comes.

2024-02-12 13:41 UTC, coroiu commented on libs/auth/src/angular/anon-layout/anon-layout.component.ts
> +    }
Also keep in mind that the switch statement requires you to import all the icons used in this file which means that tree-shaking won't work, i.e. the icons will always be a part of the resulting bundle

2024-02-15 13:02 UTC, Hinton approved these changes

2024-02-15 18:33 UTC, jlf0dev approved these changes

2024-03-06 17:32 UTC, merged