[PM-4110] Enterprise SSO for Passkeys Popout
bitwarden/clients pull request #6428
Opened 2023-09-27 19:55 UTC by gbubemismith

## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
Enterprise Single Sign-On does not land `fido2` page after successful login.

## Code changes
Enterprise SSO does not redirect back to the `fido2` because on successful login, the tab is refreshed, and the `previousUrl` state is lost. To fix this, I added new functions `persistPreviousUrl` and `getAndClearPreviousUrl` on the router service to persist the previousUrl in storage. 

- **apps/browser/src/platform/popup/services/browser-router.service.ts:** Added `persistPreviousUrl` to persist the previousUrl in storage and `getAndClearPreviousUrl` to fetch and clear the previousUrl from storage.
- **apps/browser/src/vault/fido2/browser-fido2-user-interface.service.ts:** Added the stateService so the previousUrl can be cleared if the popout times-out or the user closes the window before authenticating. 

## Screenshots

https://github.com/bitwarden/clients/assets/13024008/4e917626-f4bc-4bf1-98cf-b0b44e2b5650

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-09-27 21:04 UTC, ike-kottlowski requested changes
Overall looks like similar to the approach the web is taking. If and when we migrate to a unified routing scheme between the Browser and Web Clients the changes will be minor.

Looks good!

2023-09-27 21:04 UTC, ike-kottlowski commented on libs/common/src/platform/services/state.service.ts
> +      await this.getGlobals(this.reconcileOptions(options, await this.defaultOnDiskLocalOptions()))
I'm not sure what the implications are int eh extension but in the web client there is an issue using the `defaultOnDiskLocalOptions` as it uses Local Storage instead of Session Storage. If a user has two tabs open the local storage is shared between them causing usability issues with navigation. 

My concern is by saving `previousUrl` into Local Storage it may impact the web client. I would suggest using the `defaultOnDiskOptions` instead, since it uses session storage instead of local storage. Which will restrict the scope of the `GlobalState.previousUrl` to the tab you are in.

```suggestion
      this.reconcileOptions(options, await this.defaultOnDiskOptions())
```

2023-09-28 11:52 UTC, Hinton reviewed
We don't want to persist this state to disk. And it needs to be reset should the user abort the flow somewhere. Currently if they open the popup manually they would still be redirected to the fido page.

2023-09-29 13:59 UTC, Hinton commented
I've tried thinking up possible solutions to this problem. I think we should only persist urls in state when the user leaves for SSO. And on first popup we should clear the value. It might also be appropriate to have a timeout to ensure the user doesn't end up in some old flow after a minute 🤔

2023-10-03 16:10 UTC, gbubemismith commented
I will close this PR since we've chosen not to include this feature in the MVP.

2023-10-03 16:10 UTC, closed without merging