[PM-3565] Enforce higher minimum KDF
bitwarden/clients pull request #6440
Opened 2023-09-28 18:40 UTC by Hinton

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Changes minimum iterations for PBKDF2 to 100 000. Also oonverts the constants into ranges to ensure there is only a single place for all checks.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-10-12 18:28 UTC, Jingo88 submitted a review, later dismissed

2023-10-13 09:09 UTC, aj-rosado reviewed
The description states that we are increasing to 100 000 but seems wrong as we are increasing to 600 000

2023-10-13 09:09 UTC, aj-rosado commented on libs/common/src/enums/kdf-type.enum.ts
>  export const SEND_KDF_ITERATIONS = 100000;
Any reason to not increase the Send KDF?

2023-10-13 13:08 UTC, djsmith85 commented on libs/common/src/enums/kdf-type.enum.ts
>  export const SEND_KDF_ITERATIONS = 100000;
@aj-rosado: We have [PM-3384](https://bitwarden.atlassian.net/browse/PM-3384) tracking this.

2023-10-13 13:15 UTC, aj-rosado approved these changes

2023-10-16 09:22 UTC, djsmith85 requested changes
@Hinton Nice work and overall a far better solution using the ranges.

Just one small nit/observation

2023-10-16 09:22 UTC, djsmith85 commented on libs/common/src/enums/kdf-type.enum.ts
> +export const ARGON2_ITERATIONS = new RangeConstant(1, 10, 3);
The `ARGON2_ITERATIONS.min` is lower than previously set [here](https://github.com/bitwarden/clients/pull/6440/files#diff-34fe1b0da916c7483304b7b1d115a6b12653e6adaad5b94ac76e1b51a289a989L73)

2023-10-16 09:25 UTC, Hinton commented on libs/common/src/enums/kdf-type.enum.ts
> +export const ARGON2_ITERATIONS = new RangeConstant(1, 10, 3);
Interesting. Server used 1 as the minimum value.

2023-10-16 09:38 UTC, djsmith85 submitted a review, later dismissed

2023-10-16 17:09 UTC, MGibson1 approved these changes

2023-10-16 18:03 UTC, djsmith85 approved these changes

2023-10-16 19:37 UTC, Jingo88 approved these changes

2023-11-03 13:19 UTC, Hinton commented
I had to re-work the approach slightly. `makeKey` is used during login/unlock and other operations. I extracted all the validation into a separate function since it's unlikely we would want to prevent users from logging in.

2023-11-27 19:45 UTC, MGibson1 submitted a review, later dismissed

2023-11-27 20:32 UTC, djsmith85 submitted a review, later dismissed

2023-11-27 22:32 UTC, Jingo88 approved these changes

2023-11-28 17:05 UTC, djsmith85 submitted a review, later dismissed

2023-11-28 17:34 UTC, djsmith85 submitted a review, later dismissed

2023-11-29 13:41 UTC, MGibson1 approved these changes

2023-11-29 14:41 UTC, Jingo88 approved these changes

2023-11-30 11:56 UTC, djsmith85 approved these changes

2023-11-30 14:30 UTC, MGibson1 submitted a review, later dismissed

2023-12-04 21:01 UTC, Jingo88 submitted a review, later dismissed

2023-12-05 11:58 UTC, djsmith85 approved these changes

2023-12-05 14:53 UTC, Jingo88 approved these changes

2023-12-05 15:54 UTC, jlf0dev approved these changes

2023-12-05 15:55 UTC, merged