Fix protonpass importer when totp field is not a URL
bitwarden/clients pull request #6474
Opened 2023-10-01 20:27 UTC by quexten

## Type of change

Fixes:
https://www.reddit.com/r/Bitwarden/comments/16x9jna/proton_pass_bitwarden/

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

It seems under certain circumstances the ProtonPass importer fails due to being unable to parse a URL. The only place where the PP importer parses URLs is the TOTP field. This PR makes this more robust by simply copying the entire OTP URI when parsing fails or when the TOTP string does not start with otpauth://.

## Code changes

- protonpass.json.ts: Add totpCode test entry
- protonpass-json-importer.ts: Add make totpcode parsing more robust

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-10-25 17:03 UTC, ttalty requested changes
As stated in the comment on the importer file. The totp value can be assigned to the cipher's totp with just the secret or with the full uri string. There is no need for any checking for the uri or parsing it to a url to pull out the secret key.

2023-10-25 17:03 UTC, ttalty commented on libs/importer/src/importers/protonpass/protonpass-json-importer.ts
There is no need to parse the URL to get the secret. 

Setting the `cipher.login.totp` to the `logingContent.totpUri` value works in both scenarios. With or without the `otppath://` uri. This can be removed and the cipher totp can just be set to the input value. 

Instead of checking for othpath or even parsing the URL. Change line 55-62 to: 
`cipher.login.totp = this.getValueOrDefault(loginContent.totpUri);`

2023-10-25 17:49 UTC, quexten commented on libs/importer/src/importers/protonpass/protonpass-json-importer.ts
Thanks for the feedback, I have updated the PR.

By the way, the ProtonPass importer does not use `getValueOrDefault` for the other fields. Should this be added for consistency?

2023-10-25 18:27 UTC, ttalty commented on libs/importer/src/importers/protonpass/protonpass-json-importer.ts
You could yes. If you take a look at the lastpass-csv-importer.ts you will see that a lot of the properties are assigned using `getValueOrDefault`

2023-10-25 19:00 UTC, quexten commented on libs/importer/src/importers/protonpass/protonpass-json-importer.ts
Added getValueOrDefault for the other fields. For "cipher.name" the default is "--", since that seemed to also be used among the other importers.

2023-10-25 20:06 UTC, ttalty commented
Looks great! Thanks for the contribution!

2023-10-25 20:10 UTC, ttalty approved these changes
Changes look good

2023-10-31 17:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitwarden/clients?pullRequest=6474) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/bitwarden/clients?pullRequest=6474) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: quexten<br/>:x: ttalty<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitwarden/clients?pullRequest=6474) it.</sub>

2023-10-31 17:37 UTC, merged

2023-10-31 17:37 UTC, ttalty commented
@quexten This has been tested in QA and passes. Thank you for the contribution!