[PM-4198][TechDebt] Split up import and export modules
bitwarden/clients pull request #6483
Opened 2023-10-02 21:09 UTC by djsmith85

## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
Splitting up the import-export-modules (imports/routing)
These 2 functions should be separate module and will likely eventually be moved into libs/importer and libs/exporter

A not too far scenario is enabling and re-using the `import.component` (already converted to use CL) on desktop and browser.

An ideal follow-up will include re-using the export.component (also converted to CL but not merged) on desktop and browser.

## Code changes

 
File moves occurred due to the rename of import-export folder into a import-folder
### Import

- **apps/web/src/app/tools/import/import-routing.module.ts:** 
- **apps/web/src/app/tools/import/import.component.html:**
- **apps/web/src/app/tools/import/import.component.ts:**
- **apps/web/src/app/tools/import/import.module.ts:**
- 
### Org-Import 
- **apps/web/src/app/admin-console/organizations/tools/import/org-import-routing.module.ts:** 
- **apps/web/src/app/admin-console/organizations/tools/import/org-import.component.ts:** 
- **apps/web/src/app/admin-console/organizations/tools/import/org-import.module.ts:** 

### Export

- **apps/web/src/app/tools/vault-export/export-routing.module.ts:**
- **apps/web/src/app/tools/vault-export/export.component.html:**
- **apps/web/src/app/tools/vault-export/export.component.ts:**
- **apps/web/src/app/tools/vault-export/export.module.ts:**
### Org-Export
- **apps/web/src/app/admin-console/organizations/tools/vault-export/org-export-routing.module.ts:**
- **apps/web/src/app/admin-console/organizations/tools/vault-export/org-export.component.ts:**
- **apps/web/src/app/admin-console/organizations/tools/vault-export/org-export.module.ts:**

### Usage of the individual modules
- **apps/web/src/app/admin-console/organizations/settings/organization-settings-routing.module.ts:** Create individual routes for import and export and load their respective child-modules
- **apps/web/src/app/oss-routing.module.ts:** Create individual routes for import and export and load their respective child-modules
- 
## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-10-04 03:20 UTC, eliykat reviewed
Suggestion: could you move `admin-console/organizations/tools` under the `tools` folder in a separate PR first, then make your refactors? That would move most of it under your codeownership instead of ours and reduce the review work required from AC Team (now and in the future).

2023-10-05 02:49 UTC, eliykat requested changes
Seems pretty straightforward, just a few minor things.

2023-10-05 02:49 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/tools/import/org-import-routing.module.ts
> +    path: "import",
`import` is also in the path from the parent routing module, so currently this requires you to navigate to `tools/import/import`.

```suggestion
    path: "",
```

2023-10-05 02:49 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/settings/organization-settings-routing.module.ts
>        },
I'd like to maintain our current pattern of nesting this object to reflect the nesting of the routes. i.e.

```ts
        path: "tools",
        children: [
          {
            path: "import",
            loadChildren: () =>
              import("../tools/import/org-import.module").then((m) => m.OrganizationImportModule),
          },
          {
            path: "export",
            loadChildren: () =>
              import("../tools/vault-export/org-export.module").then((m) => m.OrganizationExportModule),
          },
        ]
      }
```

2023-10-05 02:49 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/tools/vault-export/org-export.module.ts
> +  imports: [SharedModule, LooseComponentsModule, OrganizationExportRoutingModule],
As a follow-up: it would be good to identify why this needs `LooseComponentsModule` and try to remove that dependency.

2023-10-05 02:49 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/tools/vault-export/org-export.module.ts
> +export class OrganizationExportModule {}
Why is export renamed `vault-export` but import is still just `import`? The `vault` seems redundant here.

In any case - if we're going with it, I think any naming scheme should be followed consistently, e.g. `OrganizationVaultExportModule`.

2023-10-05 13:46 UTC, djsmith85 commented on apps/web/src/app/admin-console/organizations/tools/vault-export/org-export.module.ts
> +export class OrganizationExportModule {}
This comes from the split up between vault-export and event-export (event-logging to csv). I wanted to differentiate between the two.

For import, we name it `import data`, as we didn't want to limit what things can be imported (vaults, individual passkeys, Sends, etc.)

So I'll definitely rename that component, with a plan to apply the same pattern of share-ability for the `export.component` across clients introduced with https://github.com/bitwarden/clients/pull/6504.

2023-10-05 16:49 UTC, audrey-jensen approved these changes
This seems like a really straightforward refactoring. My main concern is that it's not clear what the purpose of the modules are, which I've documented as tech debt. It's important, but not so important that we need to go deep on why or why not it should be done in this PR.

* ❓ - for questions
* ♻️ - for future improvements or indications of technical debt
* ⛏️ - for minor or nitpick changes

2023-10-05 16:49 UTC, audrey-jensen commented on apps/web/src/app/oss-routing.module.ts
> +            loadChildren: () => import("./tools/import/import.module").then((m) => m.ImportModule),
⛏️ Another place where spacing is inconsistent (with line 261)

2023-10-05 16:49 UTC, audrey-jensen commented on apps/web/src/app/tools/vault-export/export.module.ts
> +@NgModule({
♻️ Is there any documentation that should be provided about what `ExportModule` does?

2023-10-05 16:49 UTC, audrey-jensen commented on apps/web/src/app/tools/vault-export/export-routing.module.ts
>  @NgModule({
❓ Is there any documentation that should be provided about what `ExportRoutingModule` does?

2023-10-05 16:49 UTC, audrey-jensen commented on apps/web/src/app/tools/import/import.module.ts
> +export class ImportModule {}
♻️ Is there any documentation that should be provided about what `ImportModule` does?

2023-10-05 16:49 UTC, audrey-jensen commented on apps/web/src/app/tools/import/import-routing.module.ts
> +export class ImportRoutingModule {}
♻️ Is there any documentation that should be provided about what `ImportRoutingModule` does?

2023-10-05 16:49 UTC, audrey-jensen commented on apps/web/src/app/admin-console/organizations/tools/vault-export/org-export.module.ts
> +export class OrganizationVaultExportModule {}
♻️ Is there any documentation that should be provided about what `OrganizationVaultExportModule` does?

2023-10-05 16:49 UTC, audrey-jensen commented on apps/web/src/app/admin-console/organizations/tools/vault-export/org-export-routing.module.ts
> +export class OrganizationVaultExportRoutingModule {}
♻️ Is there any documentation that should be provided about what `OrganizationVaultExportRoutingModule` does?

2023-10-05 16:49 UTC, audrey-jensen commented on apps/web/src/app/admin-console/organizations/tools/import/org-import.module.ts
> +export class OrganizationImportModule {}
♻️ Is there any documentation that should be provided about what `OrganizationImportModule` does?

2023-10-05 16:49 UTC, audrey-jensen commented on apps/web/src/app/admin-console/organizations/tools/import/org-import-routing.module.ts
> +export class OrganizationImportRoutingModule {}
♻️ Is there any documentation that should be provided about what `OrganizationImportRoutingModule` does?

2023-10-06 01:17 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/tools/vault-export/org-export-routing.module.ts
Filename needs updating to match the new module name.

Same for the rest of the updated class names here.

2023-10-06 01:17 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/tools/import/org-import-routing.module.ts
Now that @audrey-jensen mentions it, it is a little strange to have routing modules with exactly 1 route in them. Do we expect to have more routes in them in the future, or should we just put the routes directly in the parent routing modules? (You can still keep the separate feature modules, they just wouldn't manage their own routing)

(That said - as an aside - the feature modules that only declare 1 component could probably be changed to standalone components. But this can cause unexpected issues with circular imports etc. so I understand if you don't want to tackle it here.)

2023-10-06 08:55 UTC, djsmith85 commented on apps/web/src/app/admin-console/organizations/tools/import/org-import-routing.module.ts
Yes this is something I've also always found weird. Good news thought that with #6504 the org-import-*.ts-files get removed as they are not needed anymore and the route module is moved up into [organization-settings-routing.module.ts](https://github.com/bitwarden/clients/pull/6504/files#diff-79c35fad065cf7622484df384dcbeabe2cc435847cc0075fcdefbd59b59ef835R52-R58). This is possible as the base-component is standalone and does all the heavy lifting we had to do before in web. It also also addresses [this comment](https://github.com/bitwarden/clients/pull/6483#discussion_r1346708637) albeit for import and not export.

As a follow-up to the whole "importer across all clients"-work, I'll be looking into applying this same pattern for the export (org-export and individual), which should remove AC as an owner for this.

2023-10-06 08:55 UTC, djsmith85 commented on apps/web/src/app/admin-console/organizations/tools/import/org-import.component.ts
> +  templateUrl: "../../../../tools/import/import.component.html",
I like the exported templateUrl, so we don't have these crazy path depths. This will be addressed in a different wayt with #6504. Which removes the need for an org-import.component

2023-10-09 20:06 UTC, audrey-jensen commented on apps/web/src/app/admin-console/organizations/tools/import/org-import.component.ts
> +  templateUrl: "../../../../tools/import/import.component.html",
@djsmith85 - please point out the part of #6504 (files and/or lines) that address this issue.

2023-10-09 20:08 UTC, audrey-jensen commented on apps/web/src/app/admin-console/organizations/tools/import/org-import-routing.module.ts
@djsmith85 - This can be resolved once my question is answered. Why are there two routing modules in this PR?

2023-10-09 20:23 UTC, djsmith85 commented on apps/web/src/app/admin-console/organizations/tools/import/org-import-routing.module.ts
There are two routes to get to the import page depending on the import goal
Tools -> Import data: Individual vault import
Organizations -> some Org -> Settings -> Import data: Organization Vault import

The same pattern applies to the export page (Individual export vs organization export)

For each of those we also have(had) an routing module which is imported with import.module or org-import.module (export.module/org-vault-export.module)

This work here is to split up the previously bundled ImportExportModule into separate modules and thus get a clearer path to clean up, or actually get rid of those additional modules.

The initial 2 routes to navigate to the import page or export page will stay.

2023-10-09 20:28 UTC, djsmith85 commented on apps/web/src/app/admin-console/organizations/tools/import/org-import.component.ts
> +  templateUrl: "../../../../tools/import/import.component.html",
With making the base import page shareable and making the [ImportWebComponent](https://github.com/bitwarden/clients/pull/6504/files#diff-f19b662a03d0452948a5d1a6d78a8c333bd818a7b38ec62bfcf8104f302a0990) standalone, I was able to update the routes ([Individual Import](https://github.com/bitwarden/clients/pull/6504/files#diff-17c8314ca7817cdf91219715d495025de2b28532de412b665e5576a549639bcc) and [Organizational Import](https://github.com/bitwarden/clients/pull/6504/files#diff-79c35fad065cf7622484df384dcbeabe2cc435847cc0075fcdefbd59b59ef835)) and remove the [import.module](https://github.com/bitwarden/clients/pull/6504/files#diff-8189ccaf2a2f0c4e40428fb92f35ebab840e0d39bf3c1620044ceb5bacac90de) and the [org-import.module](https://github.com/bitwarden/clients/pull/6504/files#diff-0280c4723f255fbde55d58d8f2f71794e2e8d908bb7d3685cb2320a50370d526) altogether

Standalone components take care of their dependencies and act like a module

2023-10-09 20:36 UTC, djsmith85 commented on apps/web/src/app/admin-console/organizations/settings/organization-settings-routing.module.ts
> +              import("../tools/import/org-import.module").then((m) => m.OrganizationImportModule),
Linter takes care spacing.
I guess because the import-path is longer it broke it onto a new line.

2023-10-09 20:36 UTC, djsmith85 commented on apps/web/src/app/oss-routing.module.ts
> +            loadChildren: () => import("./tools/import/import.module").then((m) => m.ImportModule),
Linter takes care spacing.
I guess because the import-path is longer it broke it onto a new line.

2023-10-09 20:50 UTC, djsmith85 commented on apps/web/src/app/tools/vault-export/export.module.ts
> +@NgModule({
Created PM-4263 to track adding docs

2023-10-09 20:50 UTC, djsmith85 commented on apps/web/src/app/tools/vault-export/export-routing.module.ts
>  @NgModule({
Created PM-4263 to track adding docs

2023-10-10 01:36 UTC, eliykat approved these changes

2023-10-10 16:47 UTC, audrey-jensen commented on apps/web/src/app/tools/vault-export/export.module.ts
> +@NgModule({
@djsmith85 indicated that he added a ticket to go back and fill in missing documentation. This PR will be merged without it.

2023-10-10 16:49 UTC, audrey-jensen approved these changes

2023-10-10 17:12 UTC, merged