Vault/pm 4185/checksum uris
bitwarden/clients pull request #6485
Opened 2023-10-02 21:51 UTC by MGibson1

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Icon service is the only time an encrypted piece of data is shared back to a bitwarden service. This change ensures that the encrypted string is the same as what was originally saved with the server through the use of a checksum.

## Code changes

- **login-uri.api/data:** Adds checksum to loginUri models for the api.
- **encrypt.service and implementation**: wraps crypto function service hash function to expose a b64 hash
- **login-uri**: add validation method for checksum of decrypted uri value. This is a unique concern to validate that the encrypted string we're using is the same one we originally saved. We don't want this being generic, since that actually removes the protection this provides
- **login**: If a checksum doesn't match, don't add it to the view when decrypting.
- **cipherService**: Add a checksum to the domain when encrypting.

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-10-03 07:19 UTC, Hinton approved these changes
How is the server portion handled, do we discard the data on older servers?

2023-10-03 07:19 UTC, Hinton commented on libs/common/src/platform/services/cryptography/encrypt.service.implementation.ts
> +  async hash(value: string | Uint8Array, algorithm: "sha1" | "sha256" | "sha512"): Promise<string> {
Do we want to support sha1?

2023-10-03 10:38 UTC, LRNcardozoWDF reviewed
Nice work, it looks good to me. I just left a couple of questions.

2023-10-03 10:38 UTC, LRNcardozoWDF commented on libs/common/src/vault/models/domain/login-uri.spec.ts
> +      const actual = await loginUri.validateChecksum("uri", null, null);
Do you think these are good candidates to move to `beforeEach` ?
```
const loginUri = new LoginUri();
const actual = await loginUri.validateChecksum("uri", null, null);
```

2023-10-03 10:38 UTC, LRNcardozoWDF commented on libs/common/src/vault/models/domain/login.spec.ts
> +  // it("Decrypts correctly", async () => {});
Is this a reminder to implement this test later?

2023-10-03 12:57 UTC, MGibson1 commented
> How is the server portion handled, do we discard the data on older servers?

unfortunately, yes. We parse the json we get for cipher data into the data db field, rather than preserving it. Otherwise, no server changes would have been necessary.

2023-10-06 15:39 UTC, MGibson1 commented
> How is the server portion handled, do we discard the data on older servers?
Unfortunately, yes. It's not parsed as part of the json object and just dropped.

2023-10-06 15:39 UTC, MGibson1 commented on libs/common/src/platform/services/cryptography/encrypt.service.implementation.ts
> +  async hash(value: string | Uint8Array, algorithm: "sha1" | "sha256" | "sha512"): Promise<string> {
It supports the same hashing available in cryptoFunctionService. Sha1 is still useful in certain scenarios -- I do doubt we'll use it realistically, though.

We're using sha256 for this feature

2023-10-06 15:40 UTC, MGibson1 commented on libs/common/src/vault/models/domain/login-uri.spec.ts
> +      const actual = await loginUri.validateChecksum("uri", null, null);
yep, that could simplify these tests, thank you

2023-10-06 15:40 UTC, MGibson1 commented on libs/common/src/vault/models/domain/login-uri.spec.ts
> +      const actual = await loginUri.validateChecksum("uri", null, null);
yep, that would simplify these tests, thank you

2023-10-06 15:41 UTC, MGibson1 commented on libs/common/src/vault/models/domain/login.spec.ts
> +  // it("Decrypts correctly", async () => {});
:flushed: that is a relic of moving a test into a describe. I should have deleted it. sorry

2023-10-19 21:30 UTC, shane-melton submitted a review, later dismissed
This looks good to me!

2023-10-23 13:22 UTC, Hinton approved these changes

2023-12-21 17:52 UTC, shane-melton approved these changes

2023-12-21 21:33 UTC, MGibson1 commented on libs/common/src/models/export/login-uri.export.ts
The issue with import/export isn't with export of the checksum, it's that we're validating checksum on import data.

Going this route invalidates all previous backups of vaults. We're interested in closing a bad-actor server vulnerability, not in removing trust from import files.

2023-12-22 15:18 UTC, trmartin4 commented on libs/common/src/models/export/login-uri.export.ts
After discussing with @LRNcardozoWDF we believe that this will not be an issue, since previous backups will not have a cipher key.

2023-12-22 15:56 UTC, willmartian submitted a review, later dismissed
Platform changes LGTM. One non-blocking question:

2023-12-22 15:56 UTC, willmartian commented on libs/common/src/platform/services/cryptography/encrypt.service.implementation.ts
> +  async hash(value: string | Uint8Array, algorithm: "sha1" | "sha256" | "sha512"): Promise<string> {
`CryptoFunctionService.hash` also accepts `"md5"`. Does that need to be included here?

2023-12-22 15:56 UTC, willmartian commented on libs/common/src/platform/services/cryptography/encrypt.service.implementation.ts
> +  async hash(value: string | Uint8Array, algorithm: "sha1" | "sha256" | "sha512"): Promise<string> {
And if the two `hash` methods are meant to share common parameters, should that be extracted into a shared type?

`type HashAlgorithm = "sha1" | "sha256" | "sha512" | "md5";`

2023-12-22 20:24 UTC, djsmith85 approved these changes

2023-12-28 19:34 UTC, shane-melton submitted a review, later dismissed

2024-01-23 20:42 UTC, shane-melton requested changes

2024-01-23 20:42 UTC, shane-melton commented on libs/common/src/vault/models/request/cipher.request.ts
> -            uri.uriChecksum = u.uriChecksum != null ? u.uriChecksum.encryptedString : null;
question: I might be missing something, but did we inadvertently remove setting `uriChecksum` property here? I don't see it being set above.

2024-01-24 13:51 UTC, LRNcardozoWDF commented on libs/common/src/vault/models/request/cipher.request.ts
> -            uri.uriChecksum = u.uriChecksum != null ? u.uriChecksum.encryptedString : null;
It seems so, nice catch, thank you!

2024-01-24 14:22 UTC, LRNcardozoWDF commented on libs/common/src/vault/models/request/cipher.request.ts
> -            uri.uriChecksum = u.uriChecksum != null ? u.uriChecksum.encryptedString : null;
Fixed in https://github.com/bitwarden/clients/pull/6485/commits/bdaa82099cd8554d190f630547762dffd26fb858

2024-01-24 14:43 UTC, willmartian approved these changes

2024-01-24 14:53 UTC, djsmith85 approved these changes
Approving for tools-owned files

2024-01-24 16:05 UTC, shane-melton approved these changes

2024-01-24 16:05 UTC, shane-melton commented on libs/common/src/vault/models/request/cipher.request.ts
> -            uri.uriChecksum = u.uriChecksum != null ? u.uriChecksum.encryptedString : null;
Thanks!

2024-01-24 17:22 UTC, merged