Flexible collections - add feature flags
bitwarden/clients pull request #6486
Opened 2023-10-03 03:44 UTC by eliykat

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Draft PR to show how we can add feature flags for the client-side changes in Flexible Collections.

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-10-09 15:10 UTC, Jingo88 approved these changes

2023-10-09 16:01 UTC, r-tome approved these changes

2023-10-09 23:44 UTC, shane-melton requested changes
Looks pretty solid to me, nice one! The biggest thing I saw was a few missing `$` for the new observable properties.

2023-10-09 23:44 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +  protected showBulkCollectionAccess = this.configService.getFeatureFlag$(
suggestion: Add a `$` suffix to the `showBulkCollectionAccess` observable to stay consistent with our naming conventions for observables.

2023-10-09 23:44 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +  protected showBulkEditCollectionAccess = this.configService.getFeatureFlag$(
suggestion: Same here with the `$` suffix for the observable.

2023-10-09 23:44 UTC, shane-melton commented on apps/web/src/app/admin-console/organizations/shared/components/access-selector/access-selector.component.ts
> +  protected canManagePermissionListItem = {
nit: I think this can be made private?

2023-10-10 01:14 UTC, eliykat commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +  protected showBulkCollectionAccess = this.configService.getFeatureFlag$(
Fixed

2023-10-10 01:14 UTC, eliykat commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +  protected showBulkEditCollectionAccess = this.configService.getFeatureFlag$(
Fixed

2023-10-10 01:15 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/shared/components/access-selector/access-selector.component.ts
> +  protected canManagePermissionListItem = {
Fixed

2023-10-10 17:58 UTC, shane-melton approved these changes

2023-10-11 04:02 UTC, eliykat commented
I realised that Storybook couldn't resolve the ConfigService dependency, so it seemed easier to go the other route and return it to be purely presentational, passing in a boolean to enable flexible collections or not.

2023-10-11 21:45 UTC, shane-melton approved these changes

2023-10-11 23:02 UTC, merged