[PM-4209] Enable importing on browser
bitwarden/clients pull request #6503
Opened 2023-10-04 21:52 UTC by djsmith85

Create import-dialog
Add routing and routing animations
Settings import items no longer navigates to help page but opens import page Extend messages.json to include all the necessary messages from shared components

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-10-11 14:54 UTC, aj-rosado requested changes

2023-10-11 14:54 UTC, aj-rosado commented on apps/browser/src/_locales/en/messages.json
> +    "description": "Used for the desktop menu item and the header of the import dialog"
Shouldn't this be for `browser` instead of `desktop`?

2023-10-11 14:54 UTC, aj-rosado commented on apps/browser/src/tools/popup/settings/import/import-browser.component.html
In send we have warning on browser to popout the extension in order to upload a file. I believe we should replicate that behaviour here.

https://github.com/bitwarden/clients/blob/56a122980351e2baf49b55002fd020b98c163a32/apps/browser/src/tools/popup/send/send-add-edit.component.html#L24

2023-10-12 16:46 UTC, djsmith85 commented on apps/browser/src/tools/popup/settings/import/import-browser.component.html
Great idea. This will be addressed once https://github.com/bitwarden/clients/pull/6564 is merged.

2023-10-17 15:19 UTC, cagonzalezcs submitted a review, later dismissed

2023-10-17 15:19 UTC, cagonzalezcs commented on apps/browser/src/popup/settings/settings.component.ts
> +    }
Just making a note for myself, this will need to be updated when the Browser Popout Window rework is merged in.

2023-10-19 15:30 UTC, cagonzalezcs approved these changes

2023-10-19 20:24 UTC, audrey-jensen approved these changes
Approving on behalf of @aj-rosado.

2023-10-19 20:28 UTC, djsmith85 commented on apps/browser/src/_locales/en/messages.json
> +    "description": "Used for the desktop menu item and the header of the import dialog"
Addressed with https://github.com/bitwarden/clients/pull/6503/commits/8a39510b4e0e1d9614fb87698974132761d84c33

2023-10-19 20:33 UTC, aj-rosado approved these changes

2023-10-19 20:33 UTC, merged