[PM-3036] Implement Autofill Overlay Unlock State
bitwarden/clients pull request #6514
Opened 2023-10-05 17:23 UTC by cagonzalezcs

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

This PR represents the bulk of the work necessary to have a secure autofill overlay implemented within the browser extension. I've tried to scope down the work on this ticket to some degree by implementing a single feature of the autofill overlay, the unlock vault view that appears in the overlay when the user focuses a form field.

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-10-05 18:05 UTC, SchneiderSam commented
The BW Icon is soooo big. Isn’t it possible to make it a little bit smaller?

2023-10-05 19:11 UTC, cagonzalezcs commented
> The BW Icon is soooo big. Isn’t it possible to make it a little bit smaller?

@SchneiderSam 

Thank you for the feedback, at the moment it is not possible to scale the icon through user settings and is built to match the design specifications as per our design team's guidance.

The icon itself also does adjust to the size of the input element, depending on the height, so it'll scale smaller for inputs that present in a smaller manner. However, this is a programmatic implementation and not subject to user settings. 

We'll keep in mind the idea of facilitating this in the future.

2023-10-12 14:00 UTC, LRNcardozoWDF approved these changes
Nice work, LGTM!

2023-10-18 18:36 UTC, jprusik approved these changes

2023-10-25 12:24 UTC, jlf0dev approved these changes
Had some nitpicks but nothing worth mentioning. Looks good!

2023-10-25 17:58 UTC, MGibson1 requested changes
A couple of small changes requested as a code owner. Please let me know if you'd like me to review all code more thoroughly

2023-10-25 17:58 UTC, MGibson1 commented on apps/browser/test.setup.ts
> +    }),
**nit**: This would be better as an array that you can remove from by reference as in the real implementation.

It would also allow for testing situations that have multiple listeners

2023-10-25 17:58 UTC, MGibson1 commented on apps/browser/test.setup.ts
> +    },
⚠️ It's quite weird to me to include methods here that are not part of the web api. My guess is that you're wanting to test a listener given to `chrome.runtime.onMessage.addListener`. 

If so, I think that's better done by mocking `addListener` with a trivial mock
``` typescript
...
addListener: jest.fn()
...
```

and pulling the parameters to it in your test / describe block setups:

```
chrome.runtime.onMessage.addListener as jest.spy).mock.calls[0][0]
```
That will give you the first argument (second index) of the first call (first index) to the `addListener` function.

You can pretty it up with testing classes, but we should keep the chrome api exposed by `test.setup` accurate, IMO

2023-10-25 17:58 UTC, MGibson1 commented on apps/browser/test.setup.ts
> +    }),
This comment may be irrelevant given the below

2023-10-25 17:58 UTC, MGibson1 commented on apps/browser/test.setup.ts
> +    },
This is general feedback for the `jest.fn`s added with default implementations. Since this file is used as a starting point for all tests we have or will have, it's important to keep un-opinionated about the mock

2023-10-25 17:58 UTC, MGibson1 commented on libs/common/src/services/website-icon.service.ts
Please move to vault team

2023-10-25 17:58 UTC, MGibson1 commented on libs/common/src/services/website-icon.service.ts
You can confer with them, but my preference would not be to call this a service or to encapsulate it in a class, but as a module with a static function.

Something like `libs/common/src/vault/icon/build-cipher-icon`
```typescript
...

export function buildCipherIcon {
...
}
```

**nit part**: I don't think `Data` is adding any information to this method name 🪓

2023-10-26 19:39 UTC, cagonzalezcs commented on apps/browser/test.setup.ts
> +    }),
I've stripped this detailed implementation out of the `test.setup.ts` file and opted to pass simple jest.fn() mocks. This was done in conjunction with the changes made to work with the standard approach for calling listener callbacks that you described in another comment.

2023-10-26 19:41 UTC, cagonzalezcs commented on apps/browser/test.setup.ts
> +    },
I had no idea that you could do this! I've reworked the entire implementation to facilitate this approach, and I agree it's a much more flexible approach to handling calling listener callbacks.

We're now structuring mocked calls to the chrome listeners using separate functions that I've pulled into the autofill team scoped `test-utils.ts`

2023-10-26 19:42 UTC, cagonzalezcs commented on libs/common/src/services/website-icon.service.ts
I've moved this file to the vault team under the directory you've recommended, and have made updates to the file as per your suggestions to simplify the implementation of the helper method.

2023-10-26 19:42 UTC, cagonzalezcs commented on libs/common/src/services/website-icon.service.ts
@LRNcardozoWDF 

When possible, can you please review the changes within https://github.com/bitwarden/clients/pull/6514/commits/7f04d9355a37eea92648dd7034af761b4d6de990 to verify that this works for the Vault team?

2023-10-26 21:32 UTC, MGibson1 approved these changes

2023-10-26 21:32 UTC, MGibson1 commented on apps/browser/src/autofill/jest/testing-utils.ts
these are great!

2023-10-27 12:19 UTC, merged