[PM-166] [PM-198] - Add Event Logs for CLI Actions
bitwarden/clients pull request #6527
Opened 2023-10-06 16:56 UTC by ttalty

## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Identify CLI events from desktop events for existing logging. Add additional logging for CLI events

## Code changes

- **messages.json:** Added the en locale entry for the CLI to display in the event logs correctly
- **device-type.enum.ts:** WindowsCLI, MacOsCLI, and LinuxCLI entries created
- **event.service.ts:** Get app info entries for new CLI device types
- **api.service.ts:** New CLI entries added to isDesktopClient
- **bw.ts:** EventCollectionService and EventUploadService added and created
- **get.command.ts:** EventCollectionService added and collect runs on getting a cipher
- **list.command.ts:** EventCollectionService added and collect runs for each cipher viewed
- **export.command.ts:** EventCollectionService added and collect runs when client exports the vault
- **send.command.ts:** EventCollectionService added to the initialization of the required commands
- **vault.command.ts:** EventCollectionService added to the initialization of the required commands
- **serve.command.ts:** EventCollectionService added to the initialization of the required commands
- **cli-platform-utils.service.ts:** getDevice modified to look for new CLI device types and getDeviceString replaces 'cli' instead of 'desktop'
-

2023-10-09 13:12 UTC, aj-rosado submitted a review, later dismissed
Great work on this 💯 
Changes are looking good! 🎉

2023-10-26 14:05 UTC, MGibson1 requested changes
There are many more actions with events that are possible in the CLI, is this meant to be exhaustive or just a start for viewing ciphers and exports? Why those two?

2023-10-26 14:05 UTC, MGibson1 commented on apps/web/src/app/core/event.service.ts
> +        return ["bwi-linux", this.i18nService.t("cli") + " - Linux"];
These should all probably use the `bwi-cli` icon

2023-11-09 16:54 UTC, ttalty commented on apps/web/src/app/core/event.service.ts
> +        return ["bwi-linux", this.i18nService.t("cli") + " - Linux"];
Changed the icons to use bwi-cli

2023-11-09 19:34 UTC, MGibson1 approved these changes
Thanks, this is a long time coming 🎉

2023-11-09 19:58 UTC, aj-rosado approved these changes
Looking good! 🎉

2023-11-09 20:17 UTC, merged