[SM-949] Add Event Logs to Service Account
bitwarden/clients pull request #6546
Opened 2023-10-10 14:39 UTC by differsthecat

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Add Event Logs tab to Service Accounts

## Code changes

- **bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/event-logs/service-account-event-log-api.service.ts:** Add service account event logs API service
- **bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/event-logs/service-accounts-events.component.html**: Add Component
- **bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/event-logs/service-accounts-events.component.ts:** Add Component that extends BaseEventsComponent
- **bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-account.component.html:** Add Event Logs tab link
- **bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-accounts-routing.module.ts:** Add Event logs route
- **bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-accounts.module.ts:** Add new component to the Service Accounts module

 ## Screenshots

https://github.com/bitwarden/clients/assets/8926729/418eff26-1cbd-4289-ab1b-85b0280b4a0b

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-10-10 17:22 UTC, Thomas-Avery requested changes
Looks great, thank you!

One minor thing to take a look at.

2023-10-10 17:22 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/event-logs/service-accounts-events.component.ts
> +    this.route.parent.params.subscribe(async (params) => {
```suggestion
    // eslint-disable-next-line rxjs/no-async-subscribe
    this.route.params.pipe(takeUntil(this.destroy$)).subscribe(async (params) => {
```

Do we want to use the `destroy$` here?

2023-10-10 17:23 UTC, differsthecat commented on bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/event-logs/service-accounts-events.component.ts
> +    this.route.parent.params.subscribe(async (params) => {
Ah yes, let's use that 🙂

2023-10-10 17:28 UTC, Thomas-Avery approved these changes
LGTM!

2023-10-19 15:45 UTC, coltonhurst approved these changes
This looks great, thanks @differsthecat and @Thomas-Avery

2023-10-19 21:56 UTC, merged