[PM-4280] MP reprompt not respected on passkey creation and retrieval
bitwarden/clients pull request #6550
Opened 2023-10-11 02:15 UTC by gbubemismith

… required prompts

## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
If a user has an item with MP reprompt turned on, then the user should be prompted for the MP when saving or retrieving a passkey.

## Code changes

We already ask for MP reprompt when the relying party requires user verification, and to maintain a good user experience; it made sense to combine both verification processes into a single reprompt. `handleUserVerification` checks if MP reprompt is required based on the cipher's properties if no verification is needed (MP reprompt and user verification from the relying party) then we return true if any of those conditions are met then we show the reprompt dialog and return the result.

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-10-11 13:17 UTC, coroiu requested changes

2023-10-11 13:17 UTC, coroiu commented on apps/browser/src/vault/popup/components/fido2/fido2.component.ts
> +
suggestion(non-blocking): Seems a bit odd to me that it take one part of data it needs as a parameter, and the other part it fetches straight from `this.`. I'd suggest choosing one of those approaches, preferably the functional approach by not using `this.` at all. 

```suggestion
  private async handleUserVerification(userVerification: boolean, cipher: CipherView): Promise<boolean> {
    const masterPasswordRempromptRequired = cipher && cipher.reprompt !== 0;

    if (!masterPasswordRempromptRequired && !userVerification) {
      return true;
    }

    return await this.passwordRepromptService.showPasswordPrompt();
  }

```

2023-10-11 13:17 UTC, coroiu commented on apps/browser/src/vault/popup/components/fido2/fido2.component.ts
> +      return true;
issue: we should not return `true` here, because the user has not actually been verified. 

This is a problem because this value gets returned directly to the authenticator on row 259
https://github.com/bitwarden/clients/blob/fd123ece4631ff2ff4d6661fb9f2b9d77f7b48dc/apps/browser/src/vault/popup/components/fido2/fido2.component.ts#L255-L260
Which is then sent to the RP, which will think that we performed a user verification, when in fact we never did

2023-10-11 14:38 UTC, gbubemismith commented on apps/browser/src/vault/popup/components/fido2/fido2.component.ts
> +      return true;
Good point

2023-10-12 14:09 UTC, coroiu commented on apps/browser/src/vault/popup/components/fido2/fido2.component.ts
> +    const masterPasswordRempromptRequired = cipher && cipher.reprompt !== 0;
typo:
```suggestion
    const masterPasswordRepromptRequired = cipher && cipher.reprompt !== 0;
```

2023-10-13 07:50 UTC, coroiu commented on libs/common/src/vault/services/fido2/fido2-authenticator.service.ts
> +
issue: we should probably add tests for this

2023-10-13 07:50 UTC, coroiu commented on libs/common/src/vault/services/fido2/fido2-authenticator.service.ts
> +
suggestion: consider merging this with the existing user verification check from line 125-129
https://github.com/bitwarden/clients/blob/dd7300fc5316add7f8f47a469c9d0372d9f0eefe/libs/common/src/vault/services/fido2/fido2-authenticator.service.ts#L125-L129

```suggestion

        if (!userVerified && (params.requireUserVerification || cipher.reprompt !== 0)) {
          this.logService?.warning(
            `[Fido2Authenticator] Aborting because user verification was unsuccessful.`
          );
          throw new Fido2AutenticatorError(Fido2AutenticatorErrorCode.NotAllowed);
        }

```

2023-10-13 07:50 UTC, coroiu commented on libs/common/src/vault/services/fido2/fido2-authenticator.service.ts
> +        if (cipher.reprompt !== 0 && !userVerified) {
issue: avoid magic numbers
```suggestion
        if (cipher.reprompt !== CipherRepromptType.None && !userVerified) {
```

2023-10-13 14:44 UTC, coroiu approved these changes
looking good

2023-10-13 15:56 UTC, merged