Address PR feedback
bitwarden/clients pull request #6572
Opened 2023-10-13 02:15 UTC by gbubemismith

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
This PR addresses feedback gotten from #4715 

## Code changes

The changes include cleaning up unused i18n tokens, cleaning up listeners for Safari and using a button instead of an `a` tag for `use browser`.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-10-13 16:50 UTC, Jingo88 approved these changes

2023-10-16 10:56 UTC, Hinton commented on libs/common/src/platform/models/domain/enc-string.ts
> +  }
I don't think we should introduce this pattern in this PR. If we want a `fromNullable` pattern lets do so in a clean PR to get input from people.

2023-10-16 13:36 UTC, gbubemismith commented on libs/common/src/platform/models/domain/enc-string.ts
> +  }
I agree with you on this @Hinton

2023-10-16 19:32 UTC, audrey-jensen requested changes
⚠️ - Blocks approval - for more significant problems or concerns needing attention
❓ - Blocks review - for questions

2023-10-16 19:32 UTC, audrey-jensen commented on libs/common/src/models/export/fido2-credential.export.ts
> +   * @returns Fido2CredentialView
⚠️ I'd explain that this is the `view` parameter when it's provided, and a new view otherwise.

2023-10-16 19:32 UTC, audrey-jensen commented on libs/common/src/models/export/fido2-credential.export.ts
> +   * @returns Fido2Credential
⚠️ Just like my comment on line 34, I'd point out how this interacts with the `domain` parameter.

2023-10-16 19:32 UTC, audrey-jensen commented on libs/common/src/models/export/fido2-credential.export.ts
> +   * Optional and can be either Fido2CredentialView or Fido2Credential
⚠️ The types are already documented in the method signature. I'd rephrase this to avoid talking about the types and instead focus on how the method behaves.

"The credential storing the data being exported. When not provided, an empty export is created instead." for example.

Note that this doesn't talk about the mechanics of the constructor--it talks about the parameter using the language of the export abstraction.

2023-10-16 19:32 UTC, audrey-jensen commented on libs/common/src/models/export/login.export.ts
> +    // Fido2credentials are currently not supported for imports.
❓ I thought this was an export? Why does this comment mention imports?

2023-10-16 19:37 UTC, gbubemismith commented on libs/common/src/models/export/login.export.ts
> +    // Fido2credentials are currently not supported for imports.
Sorry, it should be exports.

2023-10-16 20:46 UTC, trmartin4 commented on libs/common/src/platform/models/domain/enc-string.ts
> +  }
As this is already part of a very large PR, could we compromise on this by immediately introducing a separate PR with a clean change to introduce this method to `master` after the larger [clients PR](https://github.com/bitwarden/clients/pull/4715) has been merged?  I want to avoid pulling this larger discussion into the scope of this feature in a way that dilutes the conversation about this `fromNullable` change.

This feels like a small enough change that we wouldn't be accepting an inordinate amount of immediate-term technical debt while we allow the ultimate solution to undergo scrutiny in a separate PR.

2023-10-16 21:29 UTC, audrey-jensen commented on libs/common/src/platform/models/domain/enc-string.ts
> +  }
@trmartin4 - We've taken what was originally [a minor update to a single file]((https://github.com/bitwarden/clients/pull/4715#discussion_r1358466713) and are now wanting to apply it to the whole codebase. I'd much rather compromise by choosing the solution that scopes the issue to `fido2-credential-export.ts`:

```ts
function encrypt(val: string | null) {
    return val ? new EncString(val) : null;
}

domain.counter = encrypt(req.counter);
```

As to the wider concern, there's already enough outstanding tech debt in the tools code. I want to solve the immediate problem in the original PR, not get into a back-and-forth about a repo-wide micro-optimization that requires every engineering team to review the PR. That's how we got into this situation in the first place--the first PR is already too big from a "how many people do I need to coordinate to merge it" POV.

2023-10-16 21:47 UTC, audrey-jensen approved these changes
I disagree with the way the nullable stuff turned out, but won't be continuing to push on it.

2023-10-16 21:50 UTC, trmartin4 commented on libs/common/src/platform/models/domain/enc-string.ts
> +  }
That makes sense as well @audrey-jensen.  @gbubemismith are you ok with this more narrowly-scoped solution for this PR to avoid repetitive code and revisit the repo-wide `fromNullable` separately?

2023-10-17 09:07 UTC, Hinton approved these changes

2023-10-17 09:20 UTC, Hinton commented on libs/common/src/platform/models/domain/enc-string.ts
> +  }
I agree that we should try and limit the scope of the changes since the PR has been in flight for a long time.

My primary objection to the change was that it got added to `EncString`, in an already large PR. Platform has and will continue to require stricter criterias for inclusion of code, since it's at the bottom of our tech stack, and is consumed by all other teams. Any code introduced to platform, needs to have an expectaiton of stability since deprecating and getting rid of pattern here is difficult and will involv every team which shifts product priorities.

I would view a reasonable compromise as adding a helper to the tools model. Which solves the initial conern of code duplication in the tools model. It's also in my opinion fine for tools to introduce a local pattern and own the implementation. In this case it's a well known pattern and platform has an insentive to also solve it, which can either be done by lifting up a team specific implementation if it already exists, or by inventing a new pattern.

2023-10-17 13:56 UTC, jlf0dev approved these changes

2023-10-17 13:58 UTC, merged