[PM-4375] Reuse show file selector callout logic
bitwarden/clients pull request #6606
Opened 2023-10-17 15:03 UTC by aj-rosado

## Type of change

Separating the logic from the `FilePopoutCalloutComponent` into a new Service

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

The logic used on the `FilePopoutCalloutComponent` is also necessary to Parent Components. We are separating that logic into a service so that it can be used by all the components.

## Code changes

- **services.module.ts:** Added the new `FilePopoutUtilsService`
- **file-popout-callout.component.ts:** Removed the logic regarding which callout should be shown and using the new service that deals with that.
- **send-add-edit.component.ts:** Using the `FilePopoutUtilsService` to check if the callout is visible
- **file-popout-utils.service.ts:** Service containing all the logic if the callout should be visible and which text should present to the user

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-10-17 16:54 UTC, audrey-jensen requested changes
Overall this looks great! It just needs documentation.

2023-10-17 16:54 UTC, audrey-jensen commented on apps/browser/src/tools/popup/services/file-popout-utils.service.ts
> +export class FilePopoutUtilsService {
⚠️ Public and protected exported members should have documentation explaining their purpose and arguments.

2023-10-18 11:58 UTC, aj-rosado commented on apps/browser/src/tools/popup/services/file-popout-utils.service.ts
> +export class FilePopoutUtilsService {
Added documentation

2023-10-18 14:07 UTC, audrey-jensen commented on apps/browser/src/tools/popup/services/file-popout-utils.service.ts
> +export class FilePopoutUtilsService {
The constructor and the class itself also require documentation.

👍🏻 What you've already written is fantastic!

2023-10-18 14:52 UTC, aj-rosado commented on apps/browser/src/tools/popup/services/file-popout-utils.service.ts
> +export class FilePopoutUtilsService {
Added the missing documentation

2023-10-18 15:44 UTC, audrey-jensen approved these changes

2023-10-18 15:44 UTC, audrey-jensen commented on apps/browser/src/tools/popup/services/file-popout-utils.service.ts
> +  }
💭 Looking more closely at this, I wonder whether the user agent/navigator queries should be moved into the platform service.

```ts
private isUnsupportedMac(win: Window): boolean {
    return (
      this.platformUtilsService.isChrome() && 
      this.platformUtilsService.isMac() && 
      !this.platormUtilsService.isSupportedOS()
    );
  }
```

We can keep this conversation going outside of the PR. It's not a blocking issue.

2023-10-19 10:45 UTC, djsmith85 approved these changes
The changes are looking good.

2023-10-19 14:08 UTC, merged