Add State Provider Framework
bitwarden/clients pull request #6640
Opened 2023-10-19 20:05 UTC by justindbaur

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

PM-4342 PM-4343

This adds a framework for how a domain can own their own state and gain observable access to the state that you own, both globally and for a user. There is no implementation of this framework in this PR, a PR with an implementation will follow the merging of this. 

## Code changes

### `StateDefinition`
This is an object that will be created in a common file that is owned by platform and all creations of this type outside of there is strictly prohibited. It encapsulates the rule of 

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-10-19 22:19 UTC, MGibson1 reviewed
Early review just because I think you'll the very first comment I had 😄

2023-10-19 22:19 UTC, MGibson1 commented on apps/browser/src/platform/browser/from-chrome-event.ts
> +    // TODO: why do I need to fake this
it's because `T` is guaranteed to _extend_ `(...args: unknown[]) => void`, but not be equivalent, even if you alter to the above (which I think you should), T maybe a subtype.

In this case I don't see how it could be, but TS doesn't seem to know that.

The only way out that I know of is to use `infer` logic to extract:

```typescript
import { Observable } from "rxjs";

type EventParameters<T> = T extends chrome.events.Event<infer TEvent extends (...args: unknown[]) => void> ? Parameters<TEvent> : never;

export function fromChromeEvent<
  T extends chrome.events.Event<any>,
>(target: T): Observable<EventParameters<T>> {
  return new Observable<EventParameters<T>>((subscriber) => {
    const handler = (...args: EventParameters<T>) => {
      if (chrome.runtime.lastError) {
        subscriber.error(chrome.runtime.lastError);
        return;
      }
      subscriber.next(args);
    };
    target.addListener(handler);

    return () => target.removeListener(handler);
  });
}
```

My understanding of why it does this is because generic parameters _can_ be inferred, but they can also be specified, and if someone specified something that complied with the `extends` directive, you'd be assuming your type is equal to theirs. This implementation avoids using parameters to determine the `parameter` types for the event by specifying a different type that resolves to them and hard-coding that everywhere.

2023-10-19 22:19 UTC, MGibson1 commented on apps/browser/src/platform/browser/from-chrome-event.ts
> +  P extends unknown[] = Parameters<T>
```suggestion
  T extends (...args: P) => void,
  P extends unknown[] = Parameters<T>

```

2023-10-20 01:32 UTC, justindbaur commented on apps/browser/src/platform/browser/from-chrome-event.ts
> +    // TODO: why do I need to fake this
So I didn't quite do this but this did put me down the right path to where I ended up, if I just avoid trying to make an assertion about the whole function and then I can get a generic directly of the arguments without doing anything extra. I think it looks a lot nicer.

2023-10-20 02:24 UTC, MGibson1 requested changes
I think there's a bit more polish to do before this is ready

2023-10-20 02:24 UTC, MGibson1 commented on libs/common/src/platform/state/implementations/default-user-state.ts
> +// is reported updated by the storage service;
⚠️ This is done in this PR, please remove comment

2023-10-20 02:24 UTC, MGibson1 commented on libs/common/src/platform/state/implementations/default-user-state.ts
> +    // startWith?
⚠️ I don't understand this comment

2023-10-20 02:24 UTC, MGibson1 commented on libs/common/src/platform/state/implementations/default-user-state.ts
> +      share()
⚠️ I believe this should be a `shareReplay` to allow for some cached state value.

2023-10-20 02:24 UTC, MGibson1 commented on libs/common/src/platform/state/implementations/default-user-state.ts
> +      const storageUpdateSubscription = storageUpdates$.subscribe((data) => {
💭 Looking at this again, it seems fragile to have two separate watchers be responsible for the current value of a single observable. I might be being paranoid here, though

2023-10-20 02:24 UTC, MGibson1 commented on libs/common/src/platform/state/implementations/default-user-state.ts
> +const FAKE_DEFAULT = Symbol.for("fakeDefault");
⚠️ I don't understand what's happening with `FAKE_DEFAULT`, can you explain a bit?

2023-10-20 02:24 UTC, MGibson1 commented on libs/common/src/platform/state/implementations/default-user-state.ts
> +      .pipe(filter<T>((value) => value != FAKE_DEFAULT));
Why have `FAKE_DEFAULT` be part of the type at all?

2023-10-20 02:24 UTC, MGibson1 commented on libs/common/src/platform/state/implementations/default-user-state.ts
> +    const key = userKeyBuilder(activeUser.id, this.keyDefinition);
⚠️ Can we just pull first from `formattedKey$` and throw in null?

2023-10-20 02:24 UTC, MGibson1 commented on libs/common/src/platform/state/implementations/default-user-state.ts
> +    const key = userKeyBuilder(activeUser.id, this.keyDefinition);
actually, you already have a helper that does this with `createKey` for the `update` methods

2023-10-20 12:06 UTC, Hinton commented on libs/common/src/platform/abstractions/storage.service.ts
> +  }
The alternative is to just have `updates$: Observable;` in the interface right?

2023-10-20 12:43 UTC, MGibson1 commented on libs/common/src/platform/abstractions/storage.service.ts
> +  }
yes, and every storage service will have to do the work to instantiate a subject. It just comes down to if we want to treat these as interfaces or abstract base classes.

I think I lean more to interfaces, too

2023-10-20 12:46 UTC, MGibson1 requested changes

2023-10-20 12:46 UTC, MGibson1 commented on libs/common/src/platform/misc/key-builders.ts
> +  return `${keyDefinition.stateDefinition.name}_${userId}_${keyDefinition.key}` as StorageKey;
We should think about how we want this grouped in an alphanumeric file.

personally, my ordering hierarchy would be user > service > key, such that user data is clustered within the file. It makes less sense to me to group services.

2023-10-20 12:46 UTC, MGibson1 commented on libs/common/src/platform/misc/key-builders.ts
> +  return `${keyDefinition.stateDefinition.name}_global_${keyDefinition.key}` as StorageKey;
Save ordering preference I expect the base namespace to be global, not the state definition name

2023-10-24 20:46 UTC, justindbaur commented on libs/common/src/platform/state/implementations/default-user-state.ts
> +const FAKE_DEFAULT = Symbol.for("fakeDefault");
Matt and I discussed this in a meeting but I will include my reasoning here for posterity. 

This exists to essentially `ReplaySubject(1)` but have access to that buffer. Having the `FAKE_DEFAULT` be the seed value of the `BehaviorSubject` I can check it's value property for seeing if a real value has been retrieved and placed in it. It also gives me the ability to filter it out and not ever expose it to consumers while still allowing them to use `null` or `undefined` as valid values for their state.

2023-10-24 20:47 UTC, justindbaur commented on libs/common/src/platform/state/implementations/default-user-state.ts
> +      .pipe(filter<T>((value) => value != FAKE_DEFAULT));
See https://github.com/bitwarden/clients/pull/6640#discussion_r1370793281 as the reasoning.

2023-10-24 20:48 UTC, justindbaur commented on libs/common/src/platform/misc/key-builders.ts
> +  return `${keyDefinition.stateDefinition.name}_${userId}_${keyDefinition.key}` as StorageKey;
Went with the following key structures:

**Global:** `global_{service}_{key}`
**User:** `user_{userId}_{service}_{key}`

2023-10-24 20:49 UTC, justindbaur commented on libs/common/src/platform/misc/key-builders.ts
> +  return `${keyDefinition.stateDefinition.name}_global_${keyDefinition.key}` as StorageKey;
See: https://github.com/bitwarden/clients/pull/6640#discussion_r1370794823

2023-10-25 00:07 UTC, justindbaur commented on libs/common/src/platform/state/implementations/default-global-state.provider.ts
> +      // I have to cast out of the unknown generic but this should be safe if rules
Updated it, let me know if that is better.

2023-10-26 15:52 UTC, Hinton reviewed
I have some open ended questions around a few things. I'm primarily concerned about making secure storage rely on observables and potentially introducing more stickyness with memory.

I would like a deep dive of the proposed architecture in the contributing docs, and all the todos resolved.

2023-10-26 15:52 UTC, Hinton commented on apps/browser/src/platform/browser/from-chrome-event.ts
**question:** We've previously had issues with safari not unloading listeners correctly. Do we need to handle these here?

**question:** We typically have these things in the `BrowserApi`, any reason we're diverging from that pattern here.

2023-10-26 15:52 UTC, Hinton commented on apps/browser/src/platform/browser/from-chrome-event.ts
> +export function fromChromeEvent<T extends unknown[]>(
**issue:** Can we add some documentation to this. This example below might be slightly verbose.

```suggestion
/**
 * Converts a Chrome event to an Observable stream.
 *
 * @typeParam T - The type of the event arguments.
 * @param event - The Chrome event to convert.
 * @returns An Observable stream of the event arguments.
 *
 * @remarks
 * This function creates an Observable stream that listens to a Chrome event and emits its arguments
 * whenever the event is triggered. If the event throws an error, the Observable will emit an error
 * notification with the error message.
 *
 * @example
 * ```typescript
 * const onMessage = fromChromeEvent(chrome.runtime.onMessage);
 * onMessage.subscribe((message) => console.log('Received message:', message));
 * ```
 */
export function fromChromeEvent<T extends unknown[]>(
```

2023-10-26 15:52 UTC, Hinton commented on apps/cli/src/platform/services/lowdb-storage.service.ts
> +      this.updatesSubject.next({ key, value: obj, updateType: "save" });
**note**: Can we add some notes that CLI works slightly different in that we don't subscribe to a storage but rather directly update the subject.

2023-10-26 15:52 UTC, Hinton commented on apps/cli/src/platform/services/node-env-secure-storage.service.ts
> +  }
**question:**. Do we really want the secure storage to emit subjects? This might make sensitive things stickier.

2023-10-26 15:52 UTC, Hinton commented on libs/common/src/platform/state/state-definition.ts
> +// TODO: Where should this live
**issue:** Some remaining todos

2023-10-26 15:52 UTC, Hinton commented on apps/desktop/src/platform/services/electron-renderer-secure-storage.service.ts
> +  private updatesSubject = new Subject<StorageUpdate>();
**question:**. Do we really want the secure storage to emit subjects? This might make sensitive things stickier.

2023-10-26 17:26 UTC, justindbaur commented on apps/desktop/src/platform/services/electron-renderer-secure-storage.service.ts
> +  private updatesSubject = new Subject<StorageUpdate>();
Same thing: https://github.com/bitwarden/clients/pull/6640#discussion_r1373505688

2023-10-26 17:40 UTC, justindbaur commented on apps/browser/src/platform/browser/from-chrome-event.ts
We handle the unloading of listeners as much as we can from here. The tear down logic will remove the listener, it will be up to whomever subscribes to the observable to call `unsubscribe` on their subscription. 

I heavily based the logic and look of this to be like `fromEvent` in `rxjs`. Since it behaves very similarly I wanted it to have the similar developer experience, I can easily move it into their if you would like though.

2023-10-26 18:13 UTC, MGibson1 approved these changes

2023-10-26 18:18 UTC, justindbaur commented on apps/cli/src/platform/services/lowdb-storage.service.ts
> +      this.updatesSubject.next({ key, value: obj, updateType: "save" });
Most storage services implement their updates through the subject with the chrome apis being the exception. There is a comment on `updates$` member https://github.com/bitwarden/clients/pull/6640/files#diff-f6047d3082e1ad314c2ded6a7d2ddf0d3184648c448a41d574b1c742c0aa67b5 saying:

> Provides an {@link Observable} that represents a stream of updates that
> have happened in this storage service or in the storage this service provides
> an interface to.

2023-10-26 18:18 UTC, justindbaur commented on libs/common/src/platform/state/state-definition.ts
> +// TODO: Where should this live
All should be resolved.

2023-10-30 11:24 UTC, MGibson1 commented on apps/browser/src/platform/browser/from-chrome-event.ts
The issue is that if the browser Services are the subscribers, they don't unsubscribe because they're killed on popup closing.

In that case, the `fromChromeEvent` stream should be too, but have you tested this @justindbaur?

2023-10-30 17:29 UTC, justindbaur commented on apps/browser/src/platform/browser/from-chrome-event.ts
I updated this to use two new helpers I added in the BrowserApi to encapsulate adding and removing listeners that will be tracked in Safari. Let me know what you all think!

2023-10-31 12:16 UTC, dani-garcia reviewed
I can only comment on the browser-api changes made to avoid the Safari leaks, but they work correctly and the changes look great!

One small suggestion, now that we are generic over the events we handle, we can broaden the scope and combine the two lint rules in `.eslint.json` and do something similar to this:
```json
{
      "files": ["apps/browser/src/**/*.ts", "libs/**/*.ts"],
      "excludedFiles": ["apps/browser/src/autofill/{content,notification,background}/**/*.ts", "apps/browser/src/background/**/*.ts", "apps/browser/src/platform/background.ts"],
      "rules": {
        "no-restricted-syntax": [
          "error",
          {
            "message": "Using addListener in the browser popup produces a memory leak in Safari, use `BrowserApi.addListener` instead",
            "selector": "CallExpression > [object.object.object.name='chrome'][property.name='addListener']"
          }
        ]
      }
    }
```
I think I missed a couple of exclusions that are gonna trigger the lint, but that's the general idea

2023-11-03 08:44 UTC, Hinton commented on apps/browser/src/platform/browser/from-chrome-event.ts
Active components probably also doesn't unsubscribe properly when the popup is closed.

2023-11-03 09:30 UTC, Hinton commented on apps/cli/src/platform/services/node-env-secure-storage.service.ts
> +  }
Do we need to even provide a `updates$` for these services?

2023-11-03 09:30 UTC, Hinton commented on libs/common/src/platform/misc/key-builders.ts
**nit**: Would be nice to document the functions and their purpose.

2023-11-03 09:30 UTC, Hinton commented on libs/common/src/platform/misc/key-builders.ts
> +// eslint-disable-next-line import/no-restricted-paths
**question:** Would it make sense to lift these helpers into the `KeyDefinition` file if they are the expected way to build keys? Since they would most likely be tightly coupled to the definition. Or lift up into state at least.

2023-11-03 09:30 UTC, Hinton commented on libs/common/src/platform/state/key-definition.ts
> +      // TODO: Should we handle null for them, I feel like we should discourage null for an array?
Do we need to decide on this now, or follow up?

2023-11-03 09:30 UTC, Hinton commented on libs/common/src/platform/state/key-definition.ts
> +   */
```suggestion
  /**
   * Helper for defining a derived definition that will often be used alongside a given key
   *
   * @param keyDefinition The key definition detailing storage details for the derived state
   * @param deriveCallback The callback used to convert from the parent state to the derived state
   */
```

2023-11-03 09:30 UTC, Hinton commented on libs/common/src/platform/state/derived-state-definition.ts
**issue:** Can we add some documentation to these classes, how do `DerivedStateDefinition` differ from `KeyDefinition`. 

**question:** Is the name appropriate? without insight it feels like `DerivedKeyDefinition` would be more appropriate.

2023-11-03 09:30 UTC, Hinton commented on libs/common/src/platform/state/implementations/default-global-state.ts
> +  private seededPromise: Promise<void>;
**note:** Can we document what a `seededPromise` is? It's not obvious at a quick glance.

2023-11-03 09:30 UTC, Hinton commented on libs/common/src/platform/state/implementations/default-user-state.provider.ts
> +    protected accountService: AccountService, // Inject the lightest weight service that provides accountUserId$
**note:** Sounds like we would want to refactor this in the future?

2023-11-03 09:30 UTC, Hinton commented on libs/common/src/platform/state/implementations/default-user-state.provider.ts
> +    const locationDomainKey = `${keyDefinition.stateDefinition.storageLocation}_${keyDefinition.stateDefinition.name}_${keyDefinition.key}`;
**question:** Should we be building the key ourselves instead of the builder?

2023-11-03 17:27 UTC, justindbaur commented on libs/common/src/platform/state/implementations/default-user-state.provider.ts
> +    protected accountService: AccountService, // Inject the lightest weight service that provides accountUserId$
Nope actually, this comment was from when I was taking `StateService` but `AccountService` is the service I want to take for this, removed the comment.

2023-11-06 15:08 UTC, justindbaur commented on libs/common/src/platform/state/key-definition.ts
> +      // TODO: Should we handle null for them, I feel like we should discourage null for an array?
I made a decision, a null value will equal an empty array in this helper implementation, if others want null back in those cases they can still implement that themselves.

2023-11-06 15:26 UTC, justindbaur commented on apps/cli/src/platform/services/node-env-secure-storage.service.ts
> +  }
We do as it currently works, it's required in `AbstractStorageService` and both disk and memory implementing that interface is what makes this all work. We could make secure storage be it's own implementation and then we can remove this but for the time being I think it's fine, platform should be the only consumers of the storage services directly and errors should make themselves pretty apparent because they will quickly throw.

2023-11-06 20:26 UTC, justindbaur commented on libs/common/src/platform/state/implementations/default-global-state.ts
> +  private seededPromise: Promise<void>;
So this actually [has been taken](https://github.com/bitwarden/clients/commit/1cde8e0867ee64c4f3d9714cf028bc5984694a9a) out in some changes that will drop later but I can still give some context. Basically we want `await firstValueFrom(globalState.state$)` on a cold observable to act just like getting that information from state. With global state I don't have to bother with the user id at all so I knew where to get the state right from the constructor so I decided to start a promise to seed the initial `BehaviorSubject`. We would then await that promise when we needed a value in case it hadn't finished.

But as you can see in the linked commit, it's gone now and we just start the promise in the subscription of the observable. Which is more inline with how `DefaultUserState` works.

2023-11-07 14:28 UTC, MGibson1 approved these changes

2023-11-07 15:16 UTC, MGibson1 approved these changes

2023-11-07 15:19 UTC, MGibson1 submitted a review, later dismissed

2023-11-07 17:17 UTC, shane-melton approved these changes
Looks good for Vault! Thanks for creating the ticket!

2023-11-08 11:54 UTC, MGibson1 approved these changes

2023-11-09 22:06 UTC, merged