Ps/pm 2910/browser header component
bitwarden/clients pull request #6641
Opened 2023-10-19 21:26 UTC by MGibson1

Header component has a slots field with a left, center, right, and a right-most location for a current account, which will link to an account switcher.

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Iterative work to suppose browser account switching. Designs for which include a top-right current profile avatar (component to come in separate PR). This component should be visible basically always, unless we're on a login screen and no other accounts are known.

To facilitate this design, this component provides the same functionality as the current header pattern, with slots for left, center, and right header slots, but includes the current account component should it be available.

I included it's use in a few locations, but it will be required in more as we roll out the feature.

build-feature flagged since it would be UB to have two accounts with servers with conflicting configs enabling the feature.

## Code changes

- **gitignore**: add local config to browser configs
- **lock.component/vault-filter.component**: show usage of header component.
- **flags/base.config**: define flag
- **header.component**: wraps previous `header` into a `header-content` and uses content slots to pick content as previously done through css. Displays current account placeholder unless no authed accounts exist
- **base.scss**: `header-content` needs to be flex to allow slots to fill as before.

## Screenshots

**Flag off**
<img width="527" alt="image" src="https://github.com/bitwarden/clients/assets/18214891/180e1c0e-ba9a-4df0-902e-4d75a83f337a">

**Flag on and accounts$ emitting authed accounts (including the one being unlocked here)**
<img width="527" alt="image" src="https://github.com/bitwarden/clients/assets/18214891/84f02942-a253-49d2-b0c4-f18f76c19ff0">

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
  -  I'd love to, but we don't have storybook for browser 😭 
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-10-19 21:26 UTC, MGibson1 commented
you know... not what I look at it, I'm not happy with this being a center that isn't centered. I'm going to make the center actually in the middle...

2023-10-19 21:30 UTC, MGibson1 commented
That's better

2023-10-23 09:58 UTC, LRNcardozoWDF approved these changes
Looks good to me!

2023-10-23 19:08 UTC, andrebispo5 submitted a review, later dismissed
LGTM 👍

2023-10-24 09:13 UTC, LRNcardozoWDF submitted a review, later dismissed

2023-10-24 21:53 UTC, andrebispo5 approved these changes

2023-10-25 11:33 UTC, justindbaur submitted a review, later dismissed

2023-10-25 12:43 UTC, LRNcardozoWDF submitted a review, later dismissed

2023-10-25 13:03 UTC, djsmith85 requested changes

2023-10-25 13:03 UTC, djsmith85 commented on apps/browser/src/platform/popup/header.component.html
> +        TODO: Current Account
This should likely be a comment. Fine during dev, but we likely want to remove/hide it before the merge.

2023-10-25 13:19 UTC, MGibson1 commented on apps/browser/src/platform/popup/header.component.html
> +        TODO: Current Account
This is behind a compile time flag. It's totally inaccessible to production builds, and useful while we develop this in place

2023-10-25 13:20 UTC, djsmith85 commented on apps/browser/src/platform/popup/header.component.html
> +        TODO: Current Account
That's true, fine with me!

2023-10-25 15:11 UTC, andrebispo5 approved these changes

2023-10-25 15:11 UTC, justindbaur approved these changes

2023-10-25 15:29 UTC, djsmith85 approved these changes

2023-10-25 18:27 UTC, merged