Add Bulk Move to Project Action
bitwarden/clients pull request #6665
Opened 2023-10-23 11:19 UTC by justindbaur

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Add menu item on secrets list to allow the user to select multiple secrets and reassign their projects in one action. This works in conjunction to #6652 where people can import secrets without a project assignment and then they can assign them all to the project they want them a part of.

Server PR: <TODO>

## Code changes

- **apps/web/src/locales/en/messages.json:** Translation strings
- **bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-move-project.component.html:** Simple dialog component that allows the user to select from all the projects in their organization.
- **bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-move-project.component.ts:** Logic behind the above component that will show a summary of changes about to be made when the user selects a project. Also calls the server when the user clicks `move`. 
- **bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.html:** Menu item for starting this action from the secrets list component in the header of the table.

## Screenshots

https://github.com/bitwarden/clients/assets/19896123/cbd27a04-22cb-4f9a-8685-70d869b97d79

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-12-27 21:47 UTC, Thomas-Avery requested changes
A few minor things to take a look at. 

To note, I had to merge main in locally for both clients and server to get things running.

2023-12-27 21:47 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.html
> +  </button>
As a none admin user with mixed permissions (read only on some; write on others) on the selected secrets to move this will have a generic error message. 

![image](https://github.com/bitwarden/clients/assets/43214426/155f8dbf-ee39-4999-ac4c-a57fe425faf2)


I would suggest we follow a similar pattern used in the `projects-list.component.ts` to handle permission restrictions. We haven't migrated secret bulk deletes yet.

![image](https://github.com/bitwarden/clients/assets/43214426/be071ab5-42ac-4cbd-b2a6-0e5e674e93e5)

Basically inform the user secrets selected that they don't have permission to will be excluded. If the user doesn't have write permission to any secrets selected, don't show the option.

2023-12-27 21:47 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-move-project.component.ts
> +    private i18nService: I18nService,
Doesn't look like `i18nService` is used anywhere. 
Can it be removed?

2023-12-27 21:47 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-move-project.component.html
> +        [bitAction]="move"
Is there a reason to go with the custom `bitAction` over using `bitSubmit` on the form group? 

https://components.bitwarden.com/iframe.html?viewMode=docs&id=component-library-async-actions-in-forms-documentation--docs#2-add-directive-to-the-form-element

2023-12-27 21:47 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-move-project.component.ts
> +    }
```suggestion
  move = async () => {
    this.formGroup.markAllAsTouched();
    if (this.formGroup.invalid) {
      return;
    }
```

2023-12-29 18:04 UTC, justindbaur commented on apps/web/src/locales/en/messages.json
> +  },
Nope, that is way better, I didn't think to use that. Thanks!

2023-12-29 18:05 UTC, justindbaur commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.html
> +  </button>
Really good idea, added it, let me know how it looks/feels.

2023-12-29 18:05 UTC, justindbaur commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-move-project.component.html
> +        [bitAction]="move"
Nope, went with `bitSubmit`!

2024-01-03 20:53 UTC, Thomas-Avery requested changes
Looking good. 

One thing to take a look at and this should be good to go.

2024-01-03 20:53 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.html
> +  <button type="button" bitMenuItem *ngIf="!trash" (click)="bulkMoveToProject()">
```suggestion
  <button type="button" bitMenuItem *ngIf="!trash && hasWriteAccessOnSelected$ | async" (click)="bulkMoveToProject()">
```

What about something like this? In secrets-list.componenet.ts add something like.

```
  protected hasWriteAccessOnSelected$ = this.selection.changed.pipe(
    map((_) => this.selectedHasWriteAccess()),
  );

  private selectedHasWriteAccess() {
    const selectedSecrets = this.secrets.filter((secret) =>
      this.selection.isSelected(secret.id),
    );
    if (selectedSecrets.some((secret) => secret.write)) {
      return true;
    }
    return false;
  }
```

This will hide the bulk move option if the user has read-only access to all the secrets selected.

This will prevent the user from making a bulk move with 0 secrets and follows SM's pattern of access restriction.

2024-01-29 17:51 UTC, Thomas-Avery approved these changes
Looks good!

2025-08-14 15:31 UTC, closed without merging