[PM-3683] Remove ipcRenderer from electron-platform-utils
bitwarden/clients pull request #6679
Opened 2023-10-24 14:02 UTC by dani-garcia

## Type of change
```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
Removed all uses of `ipcRenderer` from electron-platform-utils.service.ts, and moves them to use the ipc preload, getting us step closer to enabling electron sandboxing.

I didn't change it because it's used in a fair few places, but it would seem like a good idea to make sure that `launchUri` only allows opening `https://` and `http://` URIs. It seems dangerous to be allowed to use it with `file://`, but I don't know if anyone depends on that functionality.

2023-10-26 09:59 UTC, Hinton commented on apps/desktop/src/services/electron-main-messaging.service.ts
> +    ipcMain.handle("launchUri", async (event, uri) => shell.openExternal(uri));
We have a whitelist in https://github.com/bitwarden/clients/blob/78248db59044d9796ee979be3300585c2e375da3/libs/common/src/vault/models/view/login-uri.view.ts#L8

2023-10-26 10:03 UTC, Hinton requested changes

2023-10-26 10:03 UTC, Hinton commented on apps/desktop/src/platform/preload.ts
> +    ipcRenderer.invoke("clipboard.write", message),
**suggestion:** Have a clipboard module with read/write? I think it better aligns with the considering clipboards as a sub entity.

2023-10-26 10:03 UTC, Hinton commented on apps/desktop/src/types/biometric-message.ts
>  export enum BiometricStorageAction {
**issue:** The name of this enum should be updated. `authenticate` is not a storage action.

2023-10-26 13:25 UTC, Hinton commented on libs/common/src/platform/misc/safe-urls.ts
> +    if (uri == null || uri === "") {
We have a `Utils.isNullOrWhitespace` that could be used here?

2023-10-26 13:47 UTC, dani-garcia commented on libs/common/src/platform/misc/safe-urls.ts
> +    if (uri == null || uri === "") {
Good point, changed now

2023-10-26 14:20 UTC, Hinton approved these changes

2023-10-30 12:29 UTC, LRNcardozoWDF approved these changes
LGTM!

2023-11-01 17:34 UTC, merged