[AC-1179][AC-1738] Event log for collection management setting
bitwarden/clients pull request #6699
Opened 2023-10-25 19:26 UTC by vincentsalucci

## Type of change

- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective
> When a collection management setting is updated and event log will be created and sent to the clients. Handle this event appropriately.

## Code changes
- **apps/web/src/app/core/event.service.ts**: added switch statement case to handle new enum type. added method to format the organization id short link for the event message
- **apps/web/src/locales/en/messages.json**: added new string for event message
- **libs/common/src/enums/event-type.enum.ts**: added new enum `Organization_CollectionManagement_Updated`

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-10-30 05:28 UTC, eliykat requested changes

2023-10-30 05:28 UTC, eliykat commented on apps/web/src/locales/en/messages.json
> +        "example": "Master Password"
Example needs updating.

`Modified collection management setting Master Password`? 😁

2023-10-30 05:28 UTC, eliykat commented on libs/common/src/enums/event-type.enum.ts
> +  Organization_CollectionManagemenet_Updated = 1609,
typo in `Management`. Also, the format seems to be `<Domain>_<DescriptionInCamelCase>`, so I don't think you need the second underscore.

```suggestion
  Organization_CollectionManagementUpdated = 1609,
```

2023-10-30 19:55 UTC, vincentsalucci commented on libs/common/src/enums/event-type.enum.ts
> +  Organization_CollectionManagemenet_Updated = 1609,
I personally like the naming scheme shown, but not enough to defend it and stand out from the remaining 98% of enums. Updated!

2023-10-30 19:55 UTC, vincentsalucci commented on apps/web/src/locales/en/messages.json
> +        "example": "Master Password"
Updated!

2023-10-31 02:37 UTC, eliykat commented on apps/web/src/locales/en/messages.json
> +        "example": "Limit Collection Creation/Deletion"
This is a hint to translators to tell them what will be inserted instead of `$ID$`. In this case I believe it's the orgId, not the name of the collection management setting. So:

```suggestion
        "example": "Unique ID"
```

2023-11-22 04:15 UTC, eliykat approved these changes

2023-11-22 21:17 UTC, willmartian approved these changes
Two nits :D

2023-11-22 21:17 UTC, willmartian commented on apps/web/src/app/core/event.service.ts
> +    a.setAttribute("href", "#/organizations/" + ev.organizationId + "/settings/account");
Thoughts on adding a lint rule to prefer template literals over concatenation?

https://eslint.org/docs/latest/rules/prefer-template

2023-11-22 21:17 UTC, willmartian commented on apps/web/src/locales/en/messages.json
> +        "example": "Unique ID"
I think this should be `"description"` over `"example"`, not sure if it makes much a difference in this case though

2023-11-27 17:58 UTC, vincentsalucci commented on apps/web/src/app/core/event.service.ts
> +    a.setAttribute("href", "#/organizations/" + ev.organizationId + "/settings/account");
I wouldn't mind - but that change would ripple into several areas of the code. This could be brought up to the larger group to gauge interest in the long term, though 👍

2023-11-27 18:08 UTC, merged