[AC-1122] Add new admin access to all collections and items settings
bitwarden/clients pull request #6703
Opened 2023-10-26 00:00 UTC by shane-melton

## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Add the checkbox for the new collection management setting created in this server PR https://github.com/bitwarden/server/pull/3379

## Code changes

- **apps/web/src/app/admin-console/organizations/settings/account.component:** Add the new checkbox and update the form group to support `allowAdminAccessToAllCollectionItems`
- **libs/common/src/admin-console/models/response/profile-organization.response.ts:** Add the new setting
- **libs/common/src/admin-console/models/response/organization.response.ts:** Add the new setting

## Screenshots

![image](https://github.com/bitwarden/clients/assets/8764515/04eab1c8-6669-4238-9c00-bd4408248318)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-11-01 19:04 UTC, vincentsalucci submitted a review, later dismissed

2023-11-02 16:04 UTC, LRNcardozoWDF submitted a review, later dismissed
LGTM!

2023-11-13 02:05 UTC, eliykat requested changes

2023-11-13 02:05 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/settings/account.component.html
> +  </bit-form-control>
v1 should be behind its own feature flag: `flexible-collections-v-1` (for some reason LaunchDarkly wasn't taking `v1`).

The timing might work out that MVP and v1 get released together anyway, but that's not a sure thing so we still want this flexibility.

2023-11-22 01:44 UTC, eliykat approved these changes

2023-11-22 11:39 UTC, LRNcardozoWDF approved these changes
Looks good to me!

2023-11-22 18:10 UTC, vincentsalucci submitted a review, later dismissed
I also have a PR that touches the `account.component`. If yours get merged first, I'll handle the conflicts 🎉

2023-11-27 19:20 UTC, vincentsalucci approved these changes

2023-11-27 19:44 UTC, merged