[PM-2417] Update LoginApprovalComponent on Desktop
bitwarden/clients pull request #6751
Opened 2023-11-01 11:22 UTC by andrebispo5

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Convert the usage of ModalService to DialogService.

## Code changes

- **apps/desktop/src/app/app.component.ts:** Add `DialogRef` to keep a reference to the current dialog.
- 
- **apps/desktop/src/app/app.module.ts:** Remove reference to LoginApprovalComponent
- 
- **apps/desktop/src/auth/login/login-approval.component.html:** Remove modal class and added bitDialog directive
- 
- **apps/desktop/src/auth/login/login-approval.component.ts:** Added parameter with notification id. Changed modal references to dialog.
 
## Screenshots
<img width="491" alt="image" src="https://github.com/bitwarden/clients/assets/4648522/0a79351e-d605-4b45-a555-f2ef85ed15ad">

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-11-03 04:29 UTC, eliykat requested changes
Review of tech-lead owned files only.

2023-11-03 04:29 UTC, eliykat commented on apps/desktop/src/app/app.component.ts
> +  private dialog: DialogRef = null;
Does this need to be a class property? It looks like it's only used in 1 method, it could be a local variable.

2023-11-03 14:25 UTC, andrebispo5 commented on apps/desktop/src/app/app.component.ts
> +  private dialog: DialogRef = null;
There are other instances of modalRef that will need to be migrated to dialogRef this will allow future migrations to use this reference to interact with the current dialog.

2023-11-23 21:50 UTC, eliykat commented on apps/desktop/src/app/app.component.ts
> +  private dialog: DialogRef = null;
But why do different methods need to interact with each others' dialogs? Each method that opens a dialog just opens it and subscribes to its `onClose` event - the `modal` class property already seems unnecessary today. I'm concerned that we're just following the same pattern here unnecessarily - although I could be missing something.

My suggestion is to update each method to use a local variable to hold its `DialogRef`, and then eventually remove `this.modal` when it's no longer being used.

2023-11-23 23:02 UTC, eliykat reviewed
See comment in thread above

2023-11-29 00:06 UTC, trmartin4 commented on apps/desktop/src/app/app.component.ts
> +  private dialog: DialogRef = null;
This has been changed in https://github.com/bitwarden/clients/pull/6751/commits/614fbcdde8f9fca60558c1b8d1423a0e7200e5c3.  @andrebispo5 was replicating the global dialog reference from the modal service, but he wasn't able to address this before being off on leave.  I believe I was able to address this, thanks to the wonderful docs [here](https://components.bitwarden.com/?path=/docs/documentation-migration--docs#dialogs).

2023-11-29 01:23 UTC, eliykat approved these changes
Yes this is a better way to handle it, thanks.

2023-12-01 04:02 UTC, eliykat approved these changes

2023-12-01 17:45 UTC, JaredSnider-Bitwarden reviewed
Looking great! Just two primary questions below 👇

2023-12-01 17:45 UTC, JaredSnider-Bitwarden commented on apps/desktop/src/app/app.component.ts
> +              await firstValueFrom(dialogRef.closed);
❓ is this necessary if nothing is being done w/ the value?

2023-12-01 17:45 UTC, JaredSnider-Bitwarden commented on apps/desktop/src/auth/login/login-approval.component.ts
> +export interface LoginApprovalDialogParams {
Typed params! Woo!

2023-12-01 17:45 UTC, JaredSnider-Bitwarden commented on apps/desktop/src/auth/login/login-approval.component.ts
> +    const closedWithButton = await firstValueFrom(this.dialogRef.closed);
❓ is this a behavior change? I feel like we should make this dialog not close if the user clicks outside of it because what if it is an accidental click and they want to approve the login request?

2023-12-01 17:45 UTC, JaredSnider-Bitwarden commented on apps/desktop/src/auth/login/login-approval.component.ts
> +  private async retrieveAuthRequestAndRespond(approve: boolean) {
🏅 fantastic naming improvement.

2023-12-01 20:28 UTC, trmartin4 commented on apps/desktop/src/auth/login/login-approval.component.ts
> +    const closedWithButton = await firstValueFrom(this.dialogRef.closed);
The intent was that this was not a behavior change.  This is supposed to replicate this behavior from the previous implementation, in which we were subscribing to the `closed` and denying the request.
![image](https://github.com/bitwarden/clients/assets/106564991/c0086d98-9928-412b-85ce-b7667be7715a)

2023-12-06 18:43 UTC, willmartian commented on apps/desktop/src/app/app.component.ts
> +              await firstValueFrom(dialogRef.closed);
@JaredSnider-Bitwarden @trmartin4 This most closely matches the code that is being replaced:

`this.openLoginApproval` is an async method that resolves when the modal is closed. 

When first migrated the fingerprint prompt, I did not respect this and there was a bug with the dialog opening **many** times when the broadcast service received its message. There might be a more "correct" fix to that, but I opted to make the more surgical code change that was least likely to change behavior.

2023-12-06 18:48 UTC, JaredSnider-Bitwarden commented on apps/desktop/src/app/app.component.ts
> +              await firstValueFrom(dialogRef.closed);
Ah, I see. That makes sense. Thank you for the clarification!

2023-12-06 18:49 UTC, JaredSnider-Bitwarden approved these changes
LGTM!

2023-12-06 18:50 UTC, willmartian approved these changes
LGTM as well 🚀

2023-12-07 00:28 UTC, eliykat approved these changes

2024-01-05 19:46 UTC, merged