Tools/pm 252 fix inconsistent generator configuration behavior
bitwarden/clients pull request #6755
Opened 2023-11-01 22:30 UTC by audrey-jensen

## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Fix inconsistent UI behavior on maximum and minimum values on Password Generator. 

The revised behavior operates as follows:

1. The password length increases when the minimums increase. 
   a. It does not decrease when they decrease.
   b. It cannot decrease beneath the sum of minimums.
   c. Digit and special character minimums are read from their controls.
   d. lowercase and uppercase set a minimum of 1 when checked and 0 when unchecked.
2. Display the minimum allowed length to the user. 
   a. Announce changes for assistive technology when the password length changes.
   b. Assistive technologies debounce requests to avoid flooding the user with status changes.
3. Add reactivity to include numbers and special characters.
   a. When "include" is unchecked, set the minimum to 0.
   b. When "include" is checked, set the minimum to the policy-defined minimum or 1 if no policy is defined.
   c. When the user changes "minimum" to 0, uncheck "include".
   d. When the user changes "minimum" to a number greater than 0, check "include"

## Code changes

UI Updates:
* **generator.component.html files** - Now output the minimum password length and update it as the value changes. Model binding now calls an explicit setter to update reactive fields described above. This setter saves the model.
* **messages.json** - added `minLength` label
* **generator.component.ts** - Added setters and auto-save logic. Added screen reader update after normalizing the options.

Library Updates:
* **password-generator-policy-options.ts** - Added documentation and a handy-dandy clone method to make this easy to copy.
* **password-generation.service.ts** Extracted logic into:
   * **passphrase-generator-options-evaluator.ts** - Logic responsible for applying passphrase policy and object sanitation. Ideally this logic would be embedded in the objects themselves, but that would require a substantial amount of downstream changes. I plan to implement that ideal in the SDK.
   * **password-generator-options-evaluator.ts** - Logic responsible for applying password policy and object sanitation. Ideally this logic would be embedded in the objects themselves, but that would require a substantial amount of downstream changes. I plan to implement that ideal in the SDK.
* **password-generator-options.ts** - Split the options into a union of a passphrase type and a password type. Documented them.

Unit tests:
* **passphrase-generator-options-evaluator.spec.ts**
* **password-generator-options-evaluator.spec.ts**

## Screenshots

I'll upload these Nov 2nd.

2023-11-02 04:00 UTC, eliykat reviewed
Just a few comments on AC Team stuff. I'll let Tools team dive into password generation stuff. :)

2023-11-02 04:18 UTC, eliykat commented on libs/angular/src/tools/generator/components/generator.component.ts
> +    }, 500);
Just saw this coming from `#code`.

Nothing wrong with this solution, but if you wanted to avoid the awkward `Timer` property and the `setTimeout` stuff, you could always just implement `passwordOptionsMinLengthForReader` as a `Subject<number>()`, then pipe it through `debounce` for consumption in the template.

2023-11-02 17:28 UTC, audrey-jensen commented on libs/angular/src/tools/generator/components/generator.component.ts
> +  private passwordOptionsMinLengthForReaderTimer: NodeJS.Timeout | null = null;
Unfortunately, because this is library code, the NodeJS.Timeout value has to be there or the code won't typehcheck. `setTimeout(...)` can also include a number according to the typescript definition, so I've added that.

2023-11-02 17:42 UTC, audrey-jensen commented on libs/angular/src/tools/generator/components/generator.component.ts
> +    }, 500);
I considered using RxJs in isolation here, but avoided it due to a combination of complexity and unfamiliarity. Specifically, I'm hesitant to adding subjects outside the service level, and exposing rxjs into templates that have been written procedurally.

Could you show me how that might work?

2023-11-02 18:08 UTC, audrey-jensen commented on libs/common/src/admin-console/models/domain/password-generator-policy-options.ts
> +   */
As far as I can tell, the password generator service [instantiates this type](https://github.com/bitwarden/clients/blob/e0c1d31080cb25ccb698e91eb23092701061002d/libs/common/src/tools/generator/password/password-generation.service.ts#L214-L290); it isn't used by the policy service whatsoever. The password generation service ensures that this object only contains active policies. I'm not sure whether it applies role checks, but doing so is outside the bounds of this bug report.

That said, I've updated the return value to include your comment.

> I wonder if this could be harmonized a little; I tend to think that PolicyService should not return any policy options if they're not going to do anything anyway. What do you think?

I'm taking the code in a different direction. There's *always* a policy in effect. What matters is whether it's an enterprise policy or the product's default/consumer policy. My goal is to make policy "nothing special" from the perspective of the algorithm.

As far as `PolicyService` is concerned, I'm hesitant to say how it should behave because I'm not certain of all the places it's used. Ideally, imo, its administration would be entirely separate from its application. The admin interfaces would include all the bits in their outputs, as well as have interfaces for saving and so forth. The consumer interface would be limited to read-only, pre-filtered results. 

For all I know, it may already work this way. It's not clear from its present implementation how it should be used. My main goals wrt policy in this PR are:

1. Clarify the meanings of the generator-specific parts, and
2. Don't break anything.

Extra emphasis on the 2nd one.

2023-11-03 04:03 UTC, eliykat commented on libs/angular/src/tools/generator/components/generator.component.ts
> +    }, 500);
Sure thing! Here's what I had in mind: https://github.com/bitwarden/clients/pull/6781 (untested)

2023-11-03 04:15 UTC, eliykat commented on libs/common/src/admin-console/models/domain/password-generator-policy-options.ts
> +   */
> As far as I can tell, the password generator service [instantiates this type](https://github.com/bitwarden/clients/blob/e0c1d31080cb25ccb698e91eb23092701061002d/libs/common/src/tools/generator/password/password-generation.service.ts#L214-L290); it isn't used by the policy service whatsoever. The password generation service ensures that this object only contains active policies.

Ah! I had this mixed up with the similar Master Password policy. (It imposes similar complexity requirements on your chosen master password, rather than passwords created by the generator.) In that case, PolicyService [provides an method](https://github.com/bitwarden/clients/blob/master/libs/common/src/admin-console/services/policy/policy.service.ts#L91-L149) to get a combined set of requirements of all applicable Master Password policies, so that consumers (i.e. components belonging to other teams) don't have to be concerned with that detail. I thought we did the same here, but alas.

>  I'm not sure whether it applies role checks, but doing so is definitely outside the scope of this PR.

Definitely! And outside the role of a password generator, which is why I'm banging on about the policy service interface and what its responsibilities are/should be. This is my own hobby horse though, so definitely a 💭 and not a requirement of your PR at all.

2023-11-03 15:32 UTC, audrey-jensen commented on libs/angular/src/tools/generator/components/generator.component.ts
> +    }, 500);
I love that! It's simpler and gets away from explicit types. I'll look into merging it Monday morning. Thanks!

2023-11-03 15:41 UTC, audrey-jensen commented on libs/common/src/admin-console/models/domain/password-generator-policy-options.ts
> +   */
> This is my own hobby horse though, so definitely a 💭 and not a requirement of your PR at all.

Apparently the pw generator is now one of mine, so I'd love to continue collaborating on it. I'm trying to get these kinds of things focused into the SDK, so that In the Future™ we can replace most of the generator service (if not all of it) with a library. I'd love to start collaborating on that, when opportunities present themselves.

One thing, for example, that is itching at the back of my mind is creating things like SdkSubject<T> that integrate reactive rust code 💭💭💭

2023-11-09 20:07 UTC, MGibson1 submitted a review, later dismissed
tech-lead code is fine, just an alias for text

2023-11-13 20:13 UTC, eliykat approved these changes
AC Team changes look good, let's keep collaborating on policy stuff, and I'm glad the rxjs snippet was helpful.

2023-11-19 09:12 UTC, djsmith85 requested changes
Nice job on this, especially appreciate all the tests.

Just some nits..

2023-11-19 09:12 UTC, djsmith85 commented on libs/common/src/tools/generator/password/password-generator-options-evaluator.spec.ts
> +    // TODO: test length, minNumber, and minSpecial
Seems this can be removed as the tests for those options are present below.

2023-11-22 20:32 UTC, audrey-jensen commented on libs/angular/src/tools/generator/components/generator.component.ts
> +    map((val) => val || 5),
Fixed by dff78c0.

2023-11-22 20:32 UTC, audrey-jensen commented on libs/common/src/tools/generator/password/password-generator-options-evaluator.spec.ts
> +    // TODO: test length, minNumber, and minSpecial
Removed in dfbb43.

2023-11-23 21:35 UTC, eliykat approved these changes

2023-11-24 11:39 UTC, djsmith85 approved these changes

2023-12-08 22:53 UTC, audrey-jensen commented
Here's a bit of an explanation of e03539e:

This fixes a UI desync bug that happens when an admin console rule required the length to be >= 9. In those situations, the value of the control cannot change, but the user can still try to change it. The normalization logic ensured that the policy wasn't violated and corrected the model. Unfortunately, angular's change detection works by comparing model values, and the correction happened in between runs. This caused it to compare the corrected value with the value prior to the user's edit. Those values are always identical, and so it never updated the control with the correct value from the business logic. Instead, it continued displaying the incorrect value.

The commit is a bit of a hack. It synchronizes the value of the control manually after normalization completes by monitoring the browser's "input" event. This prevents the value from ever breaking the rules. If the user types an invalid number it is immediately corrected, and since the system only allows single-digit inputs, there's no way the user can enter an invalid value. If we want to allow the user to enter arbitrary numbers then correct them after the fact, then I can switch it to the change event. The overall effect of that is that the reset happens only after the user's focus leaves the control.

When we update the control to use reactive forms, which I intend to do as I migrate the web generators to the component library (next up), this hack won't be necessary. The reactive update will run the save logic, and the refreshed value will sync back through Rx to the page. At that time I'll also try to find a way to expose the policy-controlled ranges for the controls, which should further constrain user behavior. The hack will remain in place for browser and desktop, until we wire them into the shared generator components.

2023-12-11 01:46 UTC, eliykat reviewed
I had a play around with this but also found no easy answers, it seems like the data flow issues are a product of how the component/form is currently designed. Definitely worth spending some more time on when you implement reactive forms (which may or may not fix the issue).

Anyway, if you're after a hack, this also works:

```ts
  async onPasswordOptionsMinNumberInput($event: Event) {
    // `savePasswordOptions()` replaces the null
    this.passwordOptions.number = null;

   // setTimeout schedules the change for the next event loop run
   // so change detection will catch it
   // hack hack hack
    setTimeout(() => this.savePasswordOptions(), 0);
 }
```

which you may or may not feel better about; at least it's not overwriting DOM properties.

I also wonder whether design have a preference for the behaviour here - we don't usually overwrite/prevent invalid values, we just show a validation error and prevent form submission. That would also solve the data flow issues.

Just my 2 cents - happy to approve the AC Team code changes either way.

PS. linting is broken

2023-12-11 01:46 UTC, eliykat commented on apps/web/src/app/tools/generator.component.html
>            min="0"
(non-blocking) shouldn't this be bound to the `enforcedPasswordPolicyOptions` minimum? A fixed value of 9 is not necessarily correct. I assume this is also what screen readers use. (not sure if this is what you meant by "try to find a way to expose the policy-controlled ranges for the controls" but thought I'd mention it anyway)

2023-12-12 18:44 UTC, audrey-jensen commented
> Anyway, if you're after a hack, this also works...

I prefer the hack that's already there because it's already written and debugged, but I'll keep the `setTimeout` hack in my pocket for when we update to Rx.

> I also wonder whether design have a preference for the behaviour here...

There's a deliberate focus on keeping it as close to the existing behavior, which automatically adjusts things all over the place. They do want to update the UI for this, but it's something better done comprehensively and focused on user intent. Maybe I'll be able to do some rework in 2024. 🤞🏻

> PS. linting is failing

Ty for pointing this out. Seems like that's because I need to `npm ci && npm prettier` on every branch after I pull in the prettier update from `master`. 😩

2023-12-12 18:45 UTC, audrey-jensen commented on apps/web/src/app/tools/generator.component.html
>            min="0"
Yes, but that's not something presently exposed by the service layer. It's an improvement I hope to get to with the componentization and Rx update that's following these PRs.

2023-12-12 22:46 UTC, eliykat approved these changes
Approving AC Team changes, will leave it to Tools team to give final yay or nay on workarounds

2023-12-12 23:37 UTC, djsmith85 approved these changes
Approving! 

I'm fine with the so called `hack` as it's only temporary with the follow-up to use reactivate forms. I've also been chatting with @justindbaur to make the services more reactive, which I know you've also commented on being an issue.

2023-12-13 00:17 UTC, merged