[AC-1747] deprecate access control indicator
bitwarden/clients pull request #6796
Opened 2023-11-03 21:18 UTC by willmartian

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

TODO

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-11-23 23:18 UTC, eliykat requested changes
These changes generally look good to me, thanks @willmartian!

`OrganizationUserView` also has an `AccessAll` property which doesn't look like it's dealt with here. It's consumed in `PeopleComponent`: https://github.com/bitwarden/clients/blob/ac/AC-1747/deprecate-access-control-indicator/apps/web/src/app/admin-console/organizations/members/people.component.ts#L244-L254

Do you think there's any benefit to overriding the value in the static `fromResponse` methods, so that you cannot actually instantiate it without having to deal with the feature flag logic? I don't feel strongly about it because it looks like you've caught it in all places anyway. But it would be extra protection against someone instantiating the object without properly handling this.

2023-11-23 23:18 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/core/views/group.view.ts
> +   * To be removed alongside `FeatureFlag.FlexibleCollections`.
This might be useful to clarify:

```suggestion
   * To be removed alongside `FeatureFlag.FlexibleCollections`.
   * This will always return `false` if Flexible Collections is enabled.
```

2023-11-23 23:18 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/core/views/organization-user-admin-view.ts
> +   * To be removed alongside `FeatureFlag.FlexibleCollections`.
Similarly:

```suggestion
   * To be removed alongside `FeatureFlag.FlexibleCollections`.
   * This will always return `false` if Flexible Collections is enabled.
```

2023-12-07 02:20 UTC, willmartian commented
> `OrganizationUserView` also has an `AccessAll` property which doesn't look like it's dealt with here. It's consumed in `PeopleComponent`: https://github.com/bitwarden/clients/blob/ac/AC-1747/deprecate-access-control-indicator/apps/web/src/app/admin-console/organizations/members/people.component.ts#L244-L254

Good catch, fixed in [86bcc6a](https://github.com/bitwarden/clients/pull/6796/commits/86bcc6a599f9f71ecd14325908f38540e75a8b96) and [582a524](https://github.com/bitwarden/clients/pull/6796/commits/582a524a0439f309829663ab9fad4406897b0bdd).

> Do you think there's any benefit to overriding the value in the static fromResponse methods, so that you cannot actually instantiate it without having to deal with the feature flag logic? I don't feel strongly about it because it looks like you've caught it in all places anyway. But it would be extra protection against someone instantiating the object without properly handling this.

I was originally planning on doing this, but:
1. Not all view models have `fromResponse` methods (such as the `OrganizationUserAdminView`) and would need to be dealt with wherever they are instantiated via constructor.
2. Even if a view models has a `fromResponse` method, there is nothing stopping a dev from just using the constructor instead. 

So I think we would need to be equally careful whether or not a parameter is added to the `fromResponse` method... which says to me to not even add it in the first place.

2023-12-12 03:40 UTC, merged