Auth/pm 2041/finish adding fido2 authn to web
bitwarden/clients pull request #6798
Opened 2023-11-05 17:07 UTC by JaredSnider-Bitwarden

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-11-15 10:30 UTC, coroiu requested changes
40 comments, sorry about that 😄 Overall it looks good, mostly just small comments, many of them questions, thoughts and nitpicks

2023-11-15 10:30 UTC, coroiu commented on libs/common/src/auth/services/webauthn-login/webauthn-login.service.spec.ts
> +      const webAuthnLoginService = setup(true);
suggestion(non-blocking): would you be open to changing the setup method to make it a bit easier to read? `setup(true)` doesn't say very much and requires that you go and read the implementation

Something like
```suggestion
      const webAuthnLoginService = createService({ featureFlag: true });
```

2023-11-15 10:30 UTC, coroiu commented on libs/common/src/auth/services/webauthn-login/webauthn-login.service.spec.ts
> +      expect(result.token).toEqual(token);
praise: nice, I don't usually make my tests this detailed 👍

2023-11-15 10:30 UTC, coroiu commented on libs/common/src/auth/services/webauthn-login/webauthn-login.service.spec.ts
> +    function buildCredentialAssertionOptions(): WebAuthnLoginCredentialAssertionOptionsView {
suggestion(non-blocking): Move this to the bottom?

2023-11-15 10:30 UTC, coroiu commented on libs/common/src/auth/services/webauthn-login/webauthn-login.service.spec.ts
> +
nit: whitespace

2023-11-15 10:30 UTC, coroiu commented on libs/common/src/auth/services/webauthn-login/webauthn-login.service.spec.ts
> +      expect(callArguments[0]).toBeInstanceOf(WebAuthnLoginCredentials);
thought: I'm not saying that you have to, but I personally would've skipped this test, or at least some of the assertions. I usually focus on testing logic, and in this case the `logIn` function doesn't actually do much on it's own, it just creates a class and then calls another method. The test is an order of magnitude more complex than the unit we are actually testing, and so in this case I don't think the ROI is worth it.

In my opinion tests have three main purposes:

1. To be used as a tool during implementation to make code easier and faster (TDD).
2. To serve as a guard-rail during refactors and allow developers to confidently make changes to the code, knowing that they haven't affected the behavior. But in this case, there is probably no change that you could make that would NOT cause the test to fail.
3. To define behavior, for any given input X the function should return the corresponding output Y. But the problem here is that the function doesn't actually define any behavior on it's own, it is completely dependent on the function that it calls internally. In that case it's better to just test those dependencies

2023-11-15 10:30 UTC, coroiu commented on libs/common/src/auth/services/webauthn-login/webauthn-login.service.ts
> +    this.enabled$ = from(this.configService.getFeatureFlag$(FeatureFlag.PasswordlessLogin, false));
suggestion: doesn't this already return an observable? 
```suggestion
    this.enabled$ = this.configService.getFeatureFlag$(FeatureFlag.PasswordlessLogin, false);
```

2023-11-15 10:30 UTC, coroiu commented on libs/common/src/auth/services/webauthn-login/webauthn-login.service.spec.ts
> +      expect(callArguments[0]).toBeInstanceOf(WebAuthnLoginCredentials);
I realize now that this is valid for `getCredentialAssertionOptions` as well

2023-11-15 10:30 UTC, coroiu commented on libs/common/src/platform/misc/utils.ts
> +  static fromB64ToArrayBuffer(b64: string): ArrayBuffer | null {
question: doesn't this duplicate `static fromB64ToArray(str: string): Uint8Array` ?

2023-11-15 10:30 UTC, coroiu commented on libs/common/src/platform/misc/utils.ts
> +  static hexStringToArrayBuffer(hexString: string): ArrayBuffer {
thought: platform will probably ask you to move this into an `auth` specific `utils`, if my previous experiences are anything to go by

2023-11-15 10:30 UTC, coroiu commented on libs/common/src/platform/misc/utils.ts
> +  static fromB64ToArrayBuffer(b64: string): ArrayBuffer | null {
we also have the `vault` specific `libs/common/src/vault/services/fido2/fido2-utils.ts` if that helps you with anything

2023-11-15 20:29 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/login/login-via-webauthn/login-via-webauthn.component.html
> +    >
That was some copy paste from the original PR: https://github.com/bitwarden/clients/pull/5493/files#diff-034618905f5c594d96c6babe382bbe7a90372fecf89369dec6343773c6413a32. 
I've resolved it.

2023-11-15 20:32 UTC, JaredSnider-Bitwarden commented on libs/angular/src/auth/components/base-login-via-webauthn.component.ts
> +        await this.setRememberEmailValues();
Good point. That will only probably come into play if we implemented non-discoverable credential support and we needed the email. Removing for now.

2023-11-15 20:35 UTC, JaredSnider-Bitwarden commented on libs/angular/src/auth/components/base-login-via-webauthn.component.ts
> +        await this.router.navigate([this.twoFactorRoute]);
Good point. Commented this out for now.

2023-11-15 21:31 UTC, JaredSnider-Bitwarden commented on libs/angular/src/auth/components/base-login-via-webauthn.component.ts
> +        this.validationService.showError(error);
Ok, after reviewing the slack thread, I've opted for a simple error of "Invalid Passkey. Please try again." as that message includes all the possible scenarios. I didn't want to use "This passkey has been removed and can no longer be used" as there were listed scenarios in the slack thread where that would be misleading (ex: user doesn't exist).

2023-11-15 21:49 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/webauthn-login/webauthn-login.service.spec.ts
> +  });
I mean, we are testing our setup method and confirming we can create an instance of the service? That seems important as it is required for the rest of the tests to pass?

2023-11-16 09:29 UTC, coroiu commented on apps/web/src/app/auth/login/login-via-webauthn/login-via-webauthn.component.html
> +    >
Reviewing my own code 🙃 Thanks!

2023-11-16 09:32 UTC, coroiu commented on libs/angular/src/auth/components/base-login-via-webauthn.component.ts
> +        this.validationService.showError(error);
Ok fair enough, I couldn't find any legitimate reason for any of those other errors (i.e. they would only occur if someone was doing something shady) which is why I opted for that error message. But on second though I think you are correct, trying to be clever has a tendency to come back and bite you down the line 👍

2023-11-16 09:35 UTC, coroiu commented on libs/common/src/auth/services/webauthn-login/webauthn-login.service.spec.ts
> +  });
I think a test that is so complicated that it itself needs to be tested is somewhat of a code smell. I also don't see any scenario in where the other tests would NOT fail (false-positive) if `setup` returned an undefined value

2023-11-16 16:18 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/abstractions/webauthn/webauthn-login.service.abstraction.ts
> +  >;
It can't return undefined so removing the undefined from the abstraction

2023-11-16 16:23 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/login-strategies/webauthn-login.strategy.ts
> +      );
Per discussion, will look at in another PR as we don't have the enc public key as part of the rotateable key set.

2023-11-16 20:23 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/webauthn-login/webauthn-login.service.spec.ts
> +      expect(callArguments[0]).toBeInstanceOf(WebAuthnLoginCredentials);
Adjusted per discussion on call.

2023-11-16 20:42 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/webauthn-login/webauthn-login.service.spec.ts
> +  });
Per discussion, going to keep this test.

2023-11-16 20:44 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/login-strategies/webauthn-login.strategy.spec.ts
> +  // it("handles invalid credentials", async () => {
Removed that test as part of finishing the tests.

2023-11-16 23:48 UTC, JaredSnider-Bitwarden commented on libs/angular/src/services/jslib-services.module.ts
> +    },
This complicated testing a bit with having to mock the window.navigator, but I got it working. 👍

2023-11-17 00:39 UTC, JaredSnider-Bitwarden commented on libs/common/src/platform/misc/utils.ts
> +  static hexStringToArrayBuffer(hexString: string): ArrayBuffer {
I'll wait and see if they request this during their review as the Utils already contains a buffer to hex conversion.

2023-11-20 15:18 UTC, coroiu commented on libs/angular/src/auth/components/base-login-via-webauthn.component.ts
> +        await this.router.navigate([this.successRoute]);
thought/issue: What happens if the server returns a 401 unauthorized? And what happens if the server for some reason were to return `requiresTwoFactor`? Would we try to log the user in?

2023-11-20 15:18 UTC, coroiu commented on libs/common/src/abstractions/api.service.ts
> +    request: PasswordTokenRequest | SsoTokenRequest | UserApiTokenRequest | WebAuthnTokenRequest
suggestion(non-blocking): should this be called `WebAuthnLoginTokenRequest`

2023-11-20 15:18 UTC, coroiu commented on libs/common/src/auth/services/webauthn-login/webauthn-login.service.ts
> +    private window: Window,
Issue: what happened with the DI token `WINDOW`? Did you maybe misunderstand me? :(

2023-11-20 15:18 UTC, coroiu commented on libs/common/src/platform/misc/utils.spec.ts
> +    // });
praise: nice catch! Since we're not running any of this in a Node environment (yet), do you think we can skip this?

2023-11-20 15:45 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/oss-routing.module.ts
>          component: LoginViaAuthRequestComponent,
Yeah, we introduced the discrepancy with TDE when we refactored the `LoginWithDevice` component to `LoginViaAuthRequestComponent` (used via b/c it was a long name), but we left the customer facing URL the same (`login-with-device`). 

I don't think that the URL necessarily has to match the component name. Via is a tiny bit shorter, but I can adjust the URL to match `login-via-passkey` if you think it is worth it?

2023-11-20 15:45 UTC, JaredSnider-Bitwarden commented on libs/common/src/platform/misc/utils.spec.ts
> +    // });
Ty! I left it commented out for now. It can be tackled later on.

2023-11-20 15:51 UTC, coroiu commented on libs/common/src/auth/services/webauthn-login/webauthn-login.service.ts
> +    private window: Window,
Nevermind, my bad!

2023-11-20 16:21 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/oss-routing.module.ts
>          component: LoginViaAuthRequestComponent,
Per discussion, keeping same

2023-11-20 17:06 UTC, JaredSnider-Bitwarden commented on libs/angular/src/auth/components/base-login-via-webauthn.component.ts
> +        await this.router.navigate([this.successRoute]);
Per discussion on call, we will add transition support handling just in case we ever add 2FA support on server. I talked through the copy verbiage with product.

2023-11-21 10:32 UTC, coroiu submitted a review, later dismissed

2023-11-21 17:30 UTC, justindbaur reviewed
Looked at all platform stuff and a cursory look at everything else.

2023-11-21 17:30 UTC, justindbaur commented on apps/web/src/app/auth/core/services/webauthn-login/webauthn-login-admin.service.ts
> +        } as any,
I know you didn't add this and it's just from formatting but can it be casted to `unknown` until we get typings?

2023-11-21 17:30 UTC, justindbaur commented on libs/common/src/platform/misc/utils.spec.ts
Very nice!

2023-11-21 17:30 UTC, justindbaur commented on libs/common/src/platform/misc/utils.ts
> +  static hexStringToArrayBuffer(hexString: string): ArrayBuffer {
I'm fine keeping this for now, thank you for the tests. If this implementation has to be changed often (I doubt it), and auth is still the only user at that point (probable) we can think about moving it.

2023-11-21 17:30 UTC, justindbaur commented on libs/common/src/auth/enums/authentication-type.ts
> +  WebAuthn = 4,
My only recommendation with adding an enum value is doing a cursory search for any greater than or less than comparisons using one of the values. Someone could have `authType > AuthenticationType.Sso; doThings()` and that could be a sly bug.  I don't think that is the case with this enum though, just my thoughts.

2023-11-21 17:30 UTC, justindbaur commented on libs/common/src/auth/services/webauthn-login/webauthn-login-api.service.ts
> +      this.environmentService.getIdentityUrl()
Is this a post that has an empty body? Should it be a `GET` instead as the name of the method implies?

2023-11-21 17:30 UTC, justindbaur commented on libs/common/src/auth/services/webauthn-login/webauthn-login.service.ts
> +        throw new Error("PRF information is not allowed to be sent to the server.");
Very nice, I like throwing here vs just overriding it to null or such so the error a developer has made is more in our face.

2023-11-21 17:32 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/enums/authentication-type.ts
> +  WebAuthn = 4,
Confirmed no sly bugs with numerical comparisons!

2023-11-21 17:45 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/webauthn-login/webauthn-login-api.service.ts
> +      this.environmentService.getIdentityUrl()
@coroiu , I don't have a good answer for this one.

2023-11-21 19:47 UTC, jlf0dev reviewed
Great work! I had some questions before approval but if its easier we can hop on a call to discuss

2023-11-21 19:47 UTC, jlf0dev commented on libs/angular/src/services/jslib-services.module.ts
> +    },
Do we need to declare these in jslib?

2023-11-22 08:57 UTC, coroiu commented on libs/common/src/auth/services/webauthn-login/webauthn-login-api.service.ts
> +      this.environmentService.getIdentityUrl()
Ah we missed this in the server PR! It probably should, it's a remnant from when we supported non-discoverable logis

2023-11-22 09:45 UTC, coroiu commented on libs/common/src/auth/login-strategies/webauthn-login.strategy.ts
> +  }
Some of these were needed for 2FA, and some were copy-pasta from a long time past (my old branch). None of them were actually used and the auth-flow worked fine without them, so I've removed them!

2023-11-22 10:28 UTC, coroiu commented on libs/common/src/auth/login-strategies/webauthn-login.strategy.ts
> +      await this.buildTwoFactor(credentials.twoFactor),
Removed!

2023-11-22 10:28 UTC, coroiu commented on libs/common/src/auth/login-strategies/webauthn-login.strategy.ts
> +  }
Fixed!

2023-11-22 10:28 UTC, coroiu commented on libs/common/src/auth/models/request/identity-token/webauthn-login-token.request.ts
> +    protected twoFactor: TokenTwoFactorRequest,
Removed completely!

2023-11-22 10:29 UTC, coroiu commented on libs/angular/src/auth/components/base-login-via-webauthn.component.ts
> +  // protected twoFactorRoute = "/2fa";
Removed

2023-11-22 10:34 UTC, coroiu commented on libs/common/src/auth/abstractions/webauthn/webauthn-login-prf-crypto.service.abstraction.ts
> +}
Done!

2023-11-22 10:50 UTC, coroiu commented on apps/web/src/app/auth/core/services/webauthn-login/webauthn-login-admin.service.ts
Done! I've added documentation where it was missing, and clarified some parts that were lacking

2023-11-22 10:50 UTC, coroiu commented on libs/angular/src/services/jslib-services.module.ts
> +    },
Yes? Why not?

2023-11-22 12:07 UTC, justindbaur approved these changes

2023-11-22 18:05 UTC, jlf0dev approved these changes

2023-11-22 18:24 UTC, merged