[PM-934] Autofill not working until page has been refreshed
bitwarden/clients pull request #6826
Opened 2023-11-07 22:40 UTC by cagonzalezcs

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

This set of changes fixes a number of issues surrounding context invalidation of content scripts within the extension. Within this PR, we are addressing the following problems:

- Upon installation of the extension, the content scripts for autofill and the context menu are not initialized for tabs that are open prior to installation. As a result, the autofill keystroke and context menu actions do not work within any stale tab until it is refreshed. 
- Upon locking the extension, the content scripts lose the contextual link with the extension background script. As a result, all autofill and context menu functionality is broken as soon as the extension is locked. 

These fixes should also address potential phantom issues where stale tabs lose the ability to autofill due to an extension update or some other process that interrupts the extension background. 

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-11-09 16:44 UTC, jprusik commented on apps/browser/src/autofill/background/tabs.background.ts
> +    await this.main.refreshMenu();
```suggestion
    await Promise.all([
      this.main.refreshBadge(),
      this.main.refreshMenu()
    ])
```

2023-11-09 16:49 UTC, jprusik commented on apps/browser/src/autofill/utils/utils.ts
> +/**
nit: rename file to `index.ts` (or move it out of it's own directory) so we can `import {...} from "../utils";` (instead of `../utils/utils`)?

2023-11-09 17:00 UTC, jprusik submitted a review, later dismissed

2023-11-09 17:18 UTC, cagonzalezcs commented on apps/browser/src/autofill/utils/utils.ts
> +/**
Done

2023-11-09 17:18 UTC, cagonzalezcs commented on apps/browser/src/autofill/background/tabs.background.ts
> +    await this.main.refreshMenu();
Done

2023-11-09 17:22 UTC, jprusik approved these changes

2023-11-09 20:02 UTC, MGibson1 requested changes

2023-11-09 20:02 UTC, MGibson1 commented on apps/browser/src/background/runtime.background.ts
> +        await this.autofillService.injectAutofillScripts(sender.tab, sender.frameId, true);
If we're removing this flag, can we just remove the parameter rather than hard code this value?

2023-11-09 20:21 UTC, cagonzalezcs commented on apps/browser/src/autofill/background/service_factories/autofill-service.factory.ts
> +        await configServiceFactory(cache, opts)
@MGibson1 

Hm.... if I were to call `AutofillService.init()` here, we'd see an attempt at re-injection and initialization each time an instance of the service factory was established... that happens in `content-menu-clicked-handler.ts`, `on-command-listener.ts`. 

I actually just want this `init` to trigger when the actual extension initializes, either from an installation or from a reload of the extension itself. That's why I structured the call within the `bootstrap` method of `main.background.ts`.

Does that make sense or should I be approaching this in a different manner? I for sure don't want that `init` call to be made anytime after the extension background script as finished it's own init process.

2023-11-09 20:26 UTC, cagonzalezcs commented on apps/browser/src/background/runtime.background.ts
> +        await this.autofillService.injectAutofillScripts(sender.tab, sender.frameId, true);
That isn't a hardcoded value for the flag, we're now referencing the feature flags directly within the autofill service. What that hardcoded value is for, however, is for identifying if we should be attempting to inject `autofiller.js` when triggering the injection of these scripts.

Since it's `autofill on load`, we don't want that script to be injected when the extension is first initializing. It'd be weird to see a currently open tab be filled when unlocking the extension, especially when I'm expecting that to happen on load of the page.

In either regard, I simplified the implementation within `runtime.background.ts` and moved the hard coded value into the `init` method of the autofill service. It should be less ambiguously defined there.

2023-11-09 20:50 UTC, MGibson1 commented on apps/browser/src/background/runtime.background.ts
> +        await this.autofillService.injectAutofillScripts(sender.tab, sender.frameId, true);
ah thanks, should have checked the method call rather than assuming it was the same signature/

2023-11-09 21:00 UTC, MGibson1 commented on apps/browser/src/autofill/background/service_factories/autofill-service.factory.ts
> +        await configServiceFactory(cache, opts)
I think I understand. I approached this trying to think through what this would look like when we start thinking about MV3 again, which is why those factories exist.

I do think this method is little out of character for the `init` pattern established elsewhere, where the `init` method initialized the _service_, not the extension.

It sounds like you're interested in running this code whenever the extension is installed -- can you just hook into the on install listeners for [mv2](https://github.com/bitwarden/clients/blob/master/apps/browser/src/background/runtime.background.ts#L317) and [mv3](https://github.com/bitwarden/clients/blob/master/apps/browser/src/platform/listeners/on-install-listener.ts#L29) with maybe a rename to `onInstall` or something?

2023-11-09 21:05 UTC, jprusik commented on apps/browser/src/autofill/background/tabs.background.ts
> +    await this.main.refreshMenu();
explanation: the first await will block the second; with Promise all, they don't block each other, but you still await the success of both

2023-11-09 21:39 UTC, cagonzalezcs commented on apps/browser/src/autofill/background/service_factories/autofill-service.factory.ts
> +        await configServiceFactory(cache, opts)
Ah yeah, that would work out better.

I've made modifications based on your feedback, having this load within the `onInstall` listener and I named the function to a more appropriately descriptive name.

2023-11-09 21:46 UTC, MGibson1 submitted a review, later dismissed

2023-11-09 21:50 UTC, jprusik approved these changes

2023-11-28 16:24 UTC, jprusik commented on apps/browser/src/autofill/services/autofill.service.ts
> +      if (tab.url?.startsWith("http")) {
no https?

```suggestion
    if (tab.url?.startsWith("http") || tab.url?.startsWith("https")) {
```

2023-11-28 17:19 UTC, jprusik requested changes
~Some small nits and open questions.~

Looks like there's a merge conflict that needs resolution as well.

2023-11-28 17:21 UTC, jprusik commented on apps/browser/src/autofill/services/autofill.service.ts
> +      if (tab.url?.startsWith("http")) {
lol yes, you're right, anything (including an "s"!) can come after `http`...

👍

2023-11-28 17:22 UTC, jprusik submitted a review, later dismissed

2023-11-28 17:53 UTC, cagonzalezcs commented on apps/browser/src/autofill/background/tabs.background.spec.ts
> +      tabsBackgorund["setupTabEventListeners"]();
Nice catch, fixing the typo.

2023-11-28 18:22 UTC, jprusik submitted a review, later dismissed

2023-11-28 21:26 UTC, jprusik approved these changes

2023-11-29 23:08 UTC, MGibson1 reviewed
This feels like a nit to me, but sync issues are sensitive these days. I'm honestly not sure why this used to be unlock or even why we trigger the reconnect.

2023-11-29 23:32 UTC, cagonzalezcs commented on apps/browser/src/background/runtime.background.ts
> +        await this.notificationsService.updateConnection(msg.command === "loggedIn");
@MGibson1 

So I made the call on this one, but logically it makes complete sense to swap this. 

This method triggers a full sync based on the passed param `msg.command === "loggedIn"`

Initially, it might have made sense to trigger this behavior on `unlock` as locking the extension at one point might not have triggered a reload like it does today. In effect, if a user modified vault values in the web app and then came to the extension to unlock it, they might be out of sync with their web vault.

That should be a problem at all anymore, realistically. The reason is that we trigger a reload of the extension anytime we lock it, and I found that we also attempt to trigger a full sync anytime the extension is re-initialized.

The one problem I did find, however, was that we do not seem to trigger a sync correctly shortly after the extension is freshly installed. We do attempt to trigger a full sync, but because the user is not authed it doesn't populate anything.

Triggering this sync on login, however, ensures that users who recently logged in have the latest version of their vault set. 

So with that said, could a user potentially become de-synced if they lock their extension, update their vault, then unlock it? Yes, that's possible. However, triggering this on unlock as well as login invites a duplicate call to sync the extension since the lock process already triggers a sync on init.

2023-11-30 12:36 UTC, MGibson1 commented on apps/browser/src/background/runtime.background.ts
> +        await this.notificationsService.updateConnection(msg.command === "loggedIn");
I'm actually not concerned with a desync possibility -- we have methods to rectify that. I'm concerned about whether or not it increases load on the sync endpoint and whether or not it's necessary. So to clarify: not the move, but the command change.

It sounds like the purpose of this is to get access to the user's autofillv2 and overlay settings asap, but those are locally stored, unsynced pieces of information. Is this about resolving server config?

2023-11-30 15:15 UTC, jprusik submitted a review, later dismissed

2023-11-30 20:53 UTC, cagonzalezcs commented on apps/browser/src/background/runtime.background.ts
> +        await this.notificationsService.updateConnection(msg.command === "loggedIn");
@MGibson1 

So the purpose is to ensure we have a sync vault as soon as the user has logged in from a fresh install. 

Here's what I'm seeing when we swap back the sync to happen on `unlocked` as opposed to `loggedIn`.


https://github.com/bitwarden/clients/assets/16629865/c2e01d16-db40-44cf-a42b-bdad66006924

2023-11-30 20:56 UTC, MGibson1 commented on apps/browser/src/background/runtime.background.ts
> +        await this.notificationsService.updateConnection(msg.command === "loggedIn");
hmm pretty convincing! thank you 🙇

2023-11-30 20:56 UTC, MGibson1 submitted a review, later dismissed

2023-12-04 15:31 UTC, jprusik approved these changes

2023-12-08 13:32 UTC, MGibson1 approved these changes

2023-12-12 15:30 UTC, jprusik approved these changes

2023-12-13 13:21 UTC, MGibson1 approved these changes

2023-12-13 16:25 UTC, merged