[AC-1812] Add link to Teams Starter trial, pricing to Teams trial pages
bitwarden/clients pull request #6844
Opened 2023-11-09 16:42 UTC by amorask-bitwarden

## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

This PR adds a link on the Teams Starter trial page that navigates to the Teams trial page. On the Teams trial page, it adds pricing above the main body.

## Code changes

- **teams1-content.component.html:** Add pricing above the main body.
- **teams3-content.component.html:** Add new bullet point with link to the Teams trial page.
- **trial-initiation.component.ts:** I'm not sure if this was by design, but the `pipe(first())` on the `queryParams` observable was making it impossible to actually trigger the query params subscription. Navigating to another `/register` layout would not actually change the layout. Just subscribing to the `queryParams` resolved that.

## Screenshots

Teams Trial with pricing:
![image](https://github.com/bitwarden/clients/assets/144709477/0f0ec608-44d4-458e-ab70-7df85a8e200b)

Teams Starter pricing with link:

https://github.com/bitwarden/clients/assets/144709477/c2cd204c-ef36-4598-a3ac-0fb645a4dc8a

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-11-09 17:25 UTC, cturnbull-bitwarden approved these changes

2023-11-09 18:59 UTC, JaredSnider-Bitwarden requested changes
Looks good except for one minor issue that needs to be resolved.

2023-11-09 18:59 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/trial-initiation/trial-initiation.component.ts
> +    this.route.queryParams.subscribe((qParams) => {
Issue ⚠️ :  Please edit this new subscription to use `takeUntil(...)` to avoid memory leaks:

`this.route.queryParams.pipe(takeUntil(this.destroy$)).subscribe(...)`

You can also remove the `// eslint-disable-next-line rxjs-angular/prefer-takeuntil` line.

2023-11-09 19:27 UTC, amorask-bitwarden commented on apps/web/src/app/auth/trial-initiation/trial-initiation.component.ts
> +    this.route.queryParams.subscribe((qParams) => {
@JaredSnider-Bitwarden Thank you for catching that. I've updated this based on your feedback here: https://github.com/bitwarden/clients/pull/6844/commits/be8e8d04ef5ec4b79e5e0dfaf1b1c76a35f6fa16

2023-11-09 19:28 UTC, JaredSnider-Bitwarden approved these changes
LGTM! Thank you for the fast fix!

2023-11-10 16:04 UTC, JaredSnider-Bitwarden approved these changes
LGTM!

2023-11-10 16:10 UTC, merged