[PM-4012] Vault Timing out on Chrome and Edge breaks passkeys until page is reloaded
bitwarden/clients pull request #6845
Opened 2023-11-09 17:25 UTC by gbubemismith

## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-11-14 09:00 UTC, coroiu requested changes
Nice work, noticed some issues that we need to resolve before we can merge

2023-11-14 13:48 UTC, gbubemismith commented on apps/browser/src/vault/fido2/content/content-script.ts
> +      window.postMessage({ type: "cleanup" }, "*");
Yeah, that makes sense since we communicate using the messenger.

2023-11-14 14:12 UTC, gbubemismith commented on apps/browser/src/vault/fido2/content/messaging/messenger.ts
> +  static forDOMCommunication(window: Window, memoIndex: string) {
There was a specific issue related to the cleanup of the `addEventListener`. The addEventListener adds an anonymous function as the event listener, and there was no easy way to clean it up on disconnect.

2023-11-14 14:22 UTC, gbubemismith commented on apps/browser/src/vault/fido2/content/content-script.ts
Thanks for this suggestion. I would look into this.

2023-11-14 20:09 UTC, gbubemismith commented on apps/browser/src/vault/fido2/content/page-script.ts
> +
Looking at this again, I think `finally` already does the cleanup job, so there was no need to move this out and attempt to clean it up again.

2023-11-15 14:27 UTC, gbubemismith commented on apps/browser/src/vault/services/fido2.service.ts
> +        port.postMessage({ command: "fido2ContentScriptInit" });
We need this for persisting the connection and informing us when the extension is reloaded

2023-11-15 14:34 UTC, gbubemismith commented on apps/browser/src/vault/fido2/content/messaging/messenger.ts
> +    }
I think it would make sense to

2023-11-16 13:47 UTC, coroiu requested changes

2023-11-16 13:47 UTC, coroiu commented on apps/browser/src/vault/fido2/content/page-script.ts
> +async function waitForFocus(fallbackWait = 500, timeout = 5 * 60 * 1000) {
question(non-blocking): why did we move `waitForFocus` all the way up here? Just curious :)

2023-11-16 13:47 UTC, coroiu commented on apps/browser/src/vault/fido2/content/page-script.ts
>  window.addEventListener("message", (event) => {
suggestion: could we maybe add support for the message handler to not return anything and then use `messenger.handler` here?

2023-11-16 13:47 UTC, coroiu commented on apps/browser/src/vault/fido2/content/messaging/messenger.ts
> +  static forDOMCommunication(window: Window, memoIndex: string) {
This was fixed on a slack huddle together!

2023-11-16 13:47 UTC, coroiu commented on apps/browser/src/vault/fido2/content/messaging/messenger.ts
> +  }
issue: We still don't abort the existing requests

2023-11-16 13:47 UTC, coroiu commented on apps/browser/src/vault/fido2/content/messaging/messenger.ts
> +  }
suggestion: I would solve this by adding `onDestroy = new EventTarget()` 

```ts
export class Messenger {
  private messageEventListener: (event: MessageEvent<MessageWithMetadata>) => void | null = null;
  private onDestroy = new EventTarget();
```

and then in `this.messageEventListener`

```ts
      const abortController = new AbortController();
      port.onmessage = (event: MessageEvent<MessageWithMetadata>) => {
        if (event.data.type === MessageType.AbortRequest) {
          abortController.abort();
        }
      };
      
      const onDestroyListener = () => abortController.abort();
      this.onDestroy.addEventListener("destroy", onDestroyListener):
      
      //...
      finally {
          this.onDestroy.removeEventListener(onDestroyListener);
          //...
```

and in `destroy()`

```ts
  async destroy() {
    this.onDestroy.dispatchEvent(new Event("destroy"));
  
    if (this.messageEventListener) {
      await this.sendDisconnectCommand();
      this.broadcastChannel.removeEventListener(this.messageEventListener);
      this.messageEventListener = null;
    }
  }
```

Disclaimer: I haven't worked with `EventTarget` before so the code above might not work properly, please check MDN for the proper API.

The reason I'm using `EventTarget` is to minimize the bundle size for the `content-script`

2023-11-16 13:47 UTC, coroiu commented on apps/browser/src/vault/fido2/content/messaging/messenger.ts
> +  }
Don't forget the tests :)

2023-11-17 07:50 UTC, coroiu requested changes

2023-11-17 07:50 UTC, coroiu commented on apps/browser/src/vault/fido2/content/messaging/messenger.ts
> +  private messengerId = generateUniqueId();
nit: could you move this together with the other `private` properties?

2023-11-17 07:50 UTC, coroiu commented on apps/browser/src/vault/fido2/content/messaging/messenger.ts
> +      });
issue: Could you add some tests for this?

2023-11-21 12:07 UTC, coroiu reviewed
Previous comments still valid

2023-11-21 12:07 UTC, coroiu commented on apps/browser/src/vault/fido2/content/messaging/messenger.ts
> +        onDestroyListener = () => reject(new Error("Extension is being destroyed"));
suggestion: Maybe return a fallback error instead? I think users are gonna be very confused if they get the error `Extension is being destroyed`

2023-11-21 12:09 UTC, coroiu commented
@cagonzalezcs Hey, I know this code is technically not owned by your team but you know a lot about the extension stuff so I added you here in case you might have some wisdom to share :)

2023-11-21 14:55 UTC, coroiu submitted a review, later dismissed
🔥

2023-11-22 15:09 UTC, cagonzalezcs approved these changes

2023-12-12 08:23 UTC, coroiu submitted a review, later dismissed

2023-12-12 17:48 UTC, cagonzalezcs approved these changes
Nice work overall, gave a couple of non-blocking nits. Let me know if you need a re-review.

2023-12-12 17:48 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/content/content-script.ts
> +  }
```suggestion
  if (!existingPageScript) {
    const s = document.createElement("script");
    s.src = chrome.runtime.getURL("content/fido2/page-script.js");
    s.id = "bw-fido2-page-script";
    (document.head || document.documentElement).appendChild(s);
    
    return;
  }
  
  // If the page-script already exists, send a reconnect message to the page-script
  messenger.sendReconnectCommand();
```
Nit, changes not required - You could consider doing an early return here to clean up the logic flow a bit.

2023-12-12 17:48 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/content/messaging/messenger.ts
> +      }
```suggestion
      if (event.origin !== windowOrigin || !this.handler) {
        return;
      }
```
Nit, changes not required - You could consider simplifying these return statements into a single conditional.

2023-12-12 18:13 UTC, cagonzalezcs approved these changes

2023-12-12 18:31 UTC, shane-melton approved these changes

2023-12-12 18:49 UTC, merged