Ps/pm 2910/add browser storage services
bitwarden/clients pull request #6849
Opened 2023-11-09 22:12 UTC by MGibson1

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-11-17 15:23 UTC, jlf0dev submitted a review, later dismissed
Auth files look good. I know @JaredSnider-Bitwarden might take a look as well but I’m going to approve for now

2023-11-17 15:23 UTC, jlf0dev commented on libs/common/src/auth/services/account.service.ts
> +    return this.accountsState.state$.pipe(map((accounts) => (accounts == null ? {} : accounts)));
Just so I understand, we’re returning an empty object if there are no accounts instead of null? Does this differentiate initialization vs empty somehow?

2023-11-17 15:36 UTC, justindbaur requested changes

2023-11-17 15:36 UTC, justindbaur commented on apps/browser/src/popup/services/services.module.ts
> +      },
```suggestion
      useClass: BrowserLocalStorageService,
```

2023-11-17 15:36 UTC, justindbaur commented on apps/browser/src/popup/services/services.module.ts
> +      },
```suggestion
      useClass: BrowserLocalStorageService,
```

2023-11-17 15:36 UTC, justindbaur commented on apps/cli/src/bw.ts
> +      null,
Should we at least use the `NoopMessagingService` defined below?

2023-11-17 15:36 UTC, justindbaur commented on libs/common/src/auth/services/account.service.ts
> +    );
I think we should pre-create the observables in the constructor and return the same instance over and over from the getter. This caused some issues with account switcher. I'm going to work on removing it from `AbstractChromeStorageService` too.

2023-11-20 12:48 UTC, MGibson1 commented on apps/browser/src/platform/storage/background-memory-storage.service.ts
> +      port.onMessage.addListener(this.onMessageFromForeground.bind(this));
I don't know, the port object should be cleaned up when the port is dropped, but I didn't test.

2023-11-20 12:56 UTC, MGibson1 commented on apps/browser/src/platform/storage/foreground-memory-storage.service.ts
> +  }
Perhaps it's not necessary anymore. The thinking was from back when this syncing occured in a `state` class. The idea being to initialize the state with a value. Today, that might be handled with the `getFromState` initial promises on subscribe.

2023-11-20 13:58 UTC, cagonzalezcs commented on apps/browser/src/platform/storage/background-memory-storage.service.ts
> +      port.onMessage.addListener(this.onMessageFromForeground.bind(this));
You likely don't need to in this case because you are using a named function reference. If this was an anonymous function, you'd be opening yourself up to potential memory leaks given how closures are handled in the function logic. 

That said, if you'd like to be meticulous about ensuring that this listener is deregistered, you could consider adding a `port.onMessage.removeListener` call within `onDisconnect` listener.

2023-11-20 14:55 UTC, cagonzalezcs submitted a review, later dismissed
Providing an approval on this, though I did have one nitpick that likely should be solved in a different PR.

2023-11-20 14:55 UTC, cagonzalezcs commented on libs/common/src/auth/services/account.service.ts
> +            JSON.stringify(accounts[userId]) !== JSON.stringify(newAccountInfo(accounts[userId]))
Do we have any concerns with the Object sizes when handling this comparison?

2023-11-20 22:03 UTC, MGibson1 commented on libs/common/src/auth/services/account.service.ts
> +            JSON.stringify(accounts[userId]) !== JSON.stringify(newAccountInfo(accounts[userId]))
we do, but @justindbaur pointed out ordering as an issue with spreads too 😲 

I bit the bullet and wrote an equality method

2023-11-20 22:20 UTC, MGibson1 commented on libs/common/src/auth/services/account.service.ts
> +    return this.accountsState.state$.pipe(map((accounts) => (accounts == null ? {} : accounts)));
The difference is that the `state$` doesn't emit until we've checked that nothing exists. You don't have to worry about if the `{}` will be filled once a promise is resolved, that's really the value in storage.

2023-11-21 01:39 UTC, justindbaur approved these changes
I'm good with this, just a thought about using `ObservableStorageService` as a super vs an additional interface.

2023-11-21 01:39 UTC, justindbaur commented on libs/common/src/platform/abstractions/storage.service.ts
> +export interface ObservableStorageService {
Why not make this be `export abstract class ObservableStorageService extends AbstractStorageService`? And should we do `updates$` only instead of the `get` to discourage using it like that?

2023-11-21 13:19 UTC, justindbaur submitted a review, later dismissed

2023-11-21 18:41 UTC, MGibson1 commented on apps/browser/src/background/main.background.ts
> +    );
You're right, but the alternative is relying yet again on session syncer to synchronize our in-memory cache of these things, which we know to be fragile.

2023-11-21 18:42 UTC, MGibson1 commented on apps/browser/src/platform/storage/background-memory-storage.service.ts
> +      port.onMessage.addListener(this.onMessageFromForeground.bind(this));
resolved, thank you for the hint there, @cagonzalezcs , you're definitely right that was the right direction. It's funny I'd forgotten about the `onDisconnect` callback that was literally staring me in the face

2023-11-21 19:16 UTC, justindbaur approved these changes

2023-11-21 19:17 UTC, cagonzalezcs approved these changes

2023-11-21 19:24 UTC, jlf0dev approved these changes

2023-11-21 21:35 UTC, merged