[AC-1782] Flexible collections import behavior in Password Manager and Admin Console
bitwarden/clients pull request #6888
Opened 2023-11-15 18:18 UTC by aj-rosado

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Add support to flexible collections on import. Users should be able to import into collections that they manage. Admins should keep the ability to import into any collection.

## Code changes

- **organization-settings-routing.module.ts:** Navigating to the new `AdminImportComponent`
- **admin-import.component.ts:** Import that provides the `CollectionAdminService` as the implementation of the abstract class `ImportCollectionServiceAbstraction`
- **collection-admin.service.ts:** Implements the new `ImportCollectionServiceAbstraction`
- **import.component.ts:** Changed the logic to work with the new flexible collections behavior, added `importCollectionService` to the constructor as optional parameter as it will only be retrieved when navigating through admin-console
- **organization.service.abstraction.ts:** Exposed a new method that checks if the user can import, an user that can create collection on that organization is able to import.
- **import-collection.service.abstraction.ts:** New abstraction service that provides a method to return all the organization collections
- **import.service.abstraction.ts:** changed the logic checking for unassigned as it was always returning false, the `collectionId` from the `cipher` is always set as null on the `bitwarden-json-importer`

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-01-24 12:42 UTC, djsmith85 requested changes
Changes are looking good, just some minor nits.

2024-01-24 12:42 UTC, djsmith85 commented on libs/importer/src/services/import-collection.service.abstraction.ts
> +  getAllAdminCollections: (organizationId?: string) => Promise<CollectionView[]>;
organizationId is not optional

2024-01-24 12:42 UTC, djsmith85 commented on apps/web/src/app/tools/import/admin-import.component.ts
> +    },
This is missing the dependency on `CollectionAdminService`

2024-01-24 12:42 UTC, djsmith85 commented on libs/importer/src/components/import.component.ts
> +      this.handleOrganizationImport();
Please rename to `handleOrganizationImportInit`

2024-01-24 12:42 UTC, djsmith85 commented on libs/importer/src/components/import.component.ts
> +      this.handleImport();
Please rename to `handleImportInit`

2024-01-24 12:42 UTC, djsmith85 commented on libs/importer/src/components/import.component.ts
> +    this.folders$ = this.folderService.folderViews$.pipe(
Please keep the comment: `// Filter out the `no folder`-item from folderViews$`

2024-01-24 15:06 UTC, djsmith85 approved these changes
Nice job @aj-rosado. Changes are looking good.

2024-01-24 17:11 UTC, djsmith85 submitted a review, later dismissed
Fixed linting issues and re-approving

2024-01-25 04:06 UTC, eliykat requested changes

2024-01-25 04:06 UTC, eliykat commented on libs/common/src/admin-console/abstractions/organization/organization.service.abstraction.ts
> +export function canAccessImport(i18nService: I18nService) {
What's the difference between `canAccessImportExport` (line 60) and `canAccessImport` (here)? Do you still need both? If so - can you rename them, or mark one as deprecated, or just move it inline, etc. Some way to make the distinction clearer.

2024-01-25 04:06 UTC, eliykat commented on libs/common/src/admin-console/abstractions/organization/organization.service.abstraction.ts
> +          (org.canCreateNewCollections && org.flexibleCollections) ||
It's possible that a custom user may have Import/Export permissions but does not have the ability to create collections. This line would break the import/export custom permission under flexible collections.

Based on what you've told me, I think this predicate should be more like `org.canAccessImportExport || (org.flexibleCollections && org.canCreateNewCollections)`.

2024-01-25 15:01 UTC, aj-rosado commented on libs/common/src/admin-console/abstractions/organization/organization.service.abstraction.ts
> +export function canAccessImport(i18nService: I18nService) {
I agree it is a bit confusing looking at it without context, we still need both permissions as we have cases we want to check if the user has the admin/owner/provider role or custom permission. 

In other cases we just need to know if he can create collections so I'm renaming it to clarify

2024-01-26 00:52 UTC, eliykat approved these changes

2024-01-26 09:48 UTC, djsmith85 approved these changes

2024-01-26 18:59 UTC, djsmith85 approved these changes

2024-01-29 09:44 UTC, r-tome approved these changes

2024-01-29 14:50 UTC, r-tome approved these changes

2024-01-29 14:54 UTC, djsmith85 approved these changes
The use of the CollectionAdminService instead of the direct use of the ApiService ensures all permission are checked accordingly.

Changes are looking good.

2024-01-29 15:11 UTC, merged