Increase click area of checkbox on vault
bitwarden/clients pull request #6911
Opened 2023-11-19 21:31 UTC by Spitfireap

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ X] UX Improvement
```

## Objective

Improve UX.

When selecting multiple items in the vault it is easy to mis-click and trigger the "show item" action which not only show the item information but also uncheck every previously checked checkbox. It is really hard to manage a great number of items.

The proposed change check the click event and if the mouse is above the checkbox's `<td>` the checkbox will trigger instead. 

[Forum link referring to this issue.](https://community.bitwarden.com/t/please-remove-clickable-area-around-checkbox/54417)

## Code changes

- **vault-cipher-row.component.html:** added an id to the `<td>` containing the checkbox for the click event check
- **vault-cipher-row.component.ts:** Updated the click event by providing the event's target. If the target contains the id, the input is then checked.

## Screenshots

old behavior: 

https://github.com/bitwarden/clients/assets/45575529/2b5c4979-4b4e-4ee4-910c-92489dd5d695

new behavior:

https://github.com/bitwarden/clients/assets/45575529/cc804d9e-4ac8-4f53-a825-4539a6e6b673

2023-11-29 16:46 UTC, danielleflinn approved these changes
This behavior seems to align with the Design request outlined in: [PM-3078](https://bitwarden.atlassian.net/browse/PM-3078)

@gbubemismith when you get to reviewing this for Vault please reference the internal task which outlines our desired fix for this UX bug.

2024-02-01 21:25 UTC, gbubemismith requested changes
@Spitfireap Thanks for fixing this bug. I have one suggestion, and we can get this approved.

2024-02-01 21:25 UTC, gbubemismith commented on apps/web/src/app/vault/components/vault-items/vault-cipher-row.component.ts
> +  protected click(target: HTMLSpanElement) {
nitpick: I think the target parameter can be changed to `HTMLElement` as it is a more general type.

2024-02-03 12:09 UTC, Spitfireap commented on apps/web/src/app/vault/components/vault-items/vault-cipher-row.component.ts
> +  protected click(target: HTMLSpanElement) {
@gbubemismith Change committed ;). 
The lint process applied some change on L.37. Do you want to keep them ?

2024-02-06 17:34 UTC, Spitfireap commented on apps/web/src/app/vault/components/vault-items/vault-cipher-row.component.ts
> +  protected click(target: HTMLSpanElement) {
My pleasure and done ! Thanks for your review.
I've deleted L.37 altogether (`activatedRouter` didn't seem to be used before). I'm not fluent enough in Angular to be sure it wasn't needed (even though I didn't see any regression). I would appreciate it if you could double-check.
On a side note I feel that making the clickable area for the checkbox wider than its visual appearance (as proposed initially) would still be an accessibility improvement...

2024-02-07 22:52 UTC, gbubemismith commented on apps/web/src/app/vault/components/vault-items/vault-cipher-row.component.ts
> +  protected click(target: HTMLSpanElement) {
One last thing: can you fix the conflict on your branch?

2024-02-08 17:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitwarden/clients?pullRequest=6911) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/bitwarden/clients?pullRequest=6911) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Spitfireap<br/>:x: gbubemismith<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitwarden/clients?pullRequest=6911) it.</sub>

2024-02-08 17:53 UTC, gbubemismith approved these changes

2024-02-12 18:10 UTC, gbubemismith commented
Hello @Spitfireap, Firstly, thank you for your work on this bug. I moved this to our QA team to test and received feedback on adding this behaviour to `collections` to keep things consistent. Given the excellent work you have already done, would you mind including this adjustment on the `VaultCollectionRowComponent`? Please know there's no pressure to take this on if you're not comfortable.

2024-02-14 15:04 UTC, gbubemismith commented
> @gbubemismith done :). So no discussion possible about making the clickable area for the checkbox bigger ?

Thanks for your quick response. I have started this discussion and am sure this suggestion will be considered.

2024-02-14 15:04 UTC, gbubemismith approved these changes

2024-02-14 22:45 UTC, gbubemismith commented
@Spitfireap Our QA team has approved this PR 🚀. Thanks for your work on this.

2024-02-14 22:52 UTC, merged