refactor username generation settings
bitwarden/clients pull request #6924
Opened 2023-11-21 02:17 UTC by audrey-jensen

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-11-21 20:23 UTC, ttalty submitted a review, later dismissed
Approved

2023-11-29 23:17 UTC, djsmith85 requested changes
Temp review, will revisit and have a look at the rest.
Comments on messages.json apply to all clients

2023-12-04 23:31 UTC, audrey-jensen commented on apps/browser/src/_locales/en/messages.json
> +      "simplelogin": "SimpleLogin"
Discussed out-of-band. The replacement code will store forwarder names in the forwarder implementations themselves and the list of forwarders will be lowered from the base component into the service.

2023-12-05 18:11 UTC, audrey-jensen commented on apps/browser/src/_locales/en/messages.json
> +      "simplelogin": "SimpleLogin"
Adjusted the implementation plan to consolidate metadata in a single structure. Addressed in 9545fc6.

2023-12-15 00:39 UTC, audrey-jensen commented
@MGibson1:
> Wow, I understand there are a lot of new specs, but can this be broken up?

My original plan was to do this across a few PRs, but I couldn't figure out how to do the settings changes in a piecemeal fashion. 😦

2023-12-21 13:09 UTC, MGibson1 commented on libs/common/src/state-migrations/migrations/10-factor-username-generator-settings.ts
> + * @remarks Exported for unit testing purposes only.
🥳

2023-12-21 13:09 UTC, MGibson1 commented on libs/common/src/state-migrations/migrations/10-factor-username-generator-settings.ts
> +    saveOnLoad: true,
🥳  this is a great way to do this 👍

2024-01-10 22:26 UTC, audrey-jensen commented on libs/common/src/state-migrations/migrations/10-factor-username-generator-settings.ts
> +    // old settings aren't compatible with the new UI, so we can't rollback
That makes sense. I could write a rollback that maps most of the settings back. The ones that become encrypted (API keys) would not, however. Do you think that would provide value? (It wasn't while I was working on this... this is not a feature that's regularly worked on.)

2024-01-10 22:27 UTC, audrey-jensen commented on libs/common/src/state-migrations/migrations/10-factor-username-generator-settings.ts
> +]);
Counternit: I usually do this so that my unit tests fail if I accidentally mutate static data.

2024-01-11 15:26 UTC, audrey-jensen commented on libs/common/src/state-migrations/migrations/10-factor-username-generator-settings.ts
> +]);
Addressed in [8bbb7be](https://github.com/bitwarden/clients/pull/6924/commits/8bbb7bee082496ebeb4a6534c96764f46277d50a).

2024-01-18 17:18 UTC, audrey-jensen commented
Withdrawing this PR. I'll try to incorporate its changes in a series of smaller PRs as I work through manifest v3.

2024-01-18 17:19 UTC, closed without merging