Assign ownership to many libs files
bitwarden/clients pull request #6928
Opened 2023-11-21 10:55 UTC by Hinton

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Assign ownership to many of the remaining libs/common files.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-11-22 01:36 UTC, eliykat submitted a review, later dismissed

2023-11-22 14:38 UTC, jlf0dev commented on libs/common/src/auth/iframe-component.ts
Should this be platform? Feels like the captcha is auth specific but not the iframe itself

2023-11-27 10:47 UTC, Hinton commented on libs/common/src/auth/iframe-component.ts
We only use iframes for auth concerns. Currently I can't think of any non auth related captcha can you?

2023-11-27 13:05 UTC, MGibson1 approved these changes
Great work, @Hinton. I know this was a slog, but so valuable.

I don't see any issues with the assignments. There are a few new files, but these appear to truly be new so no lost history either.

2023-11-27 13:19 UTC, jlf0dev submitted a review, later dismissed

2023-11-27 13:38 UTC, cagonzalezcs approved these changes
Looks good from my side.

2023-11-27 14:07 UTC, djsmith85 commented on libs/common/src/services/search.service.ts
Who is going to own search?

2023-11-27 14:08 UTC, djsmith85 commented on libs/common/src/models/request/register.request.ts
Should the reqister be part of auth?

2023-11-27 14:09 UTC, djsmith85 commented on apps/web/src/app/settings/purge-vault.component.ts
Should this be owned by vault?

2023-11-27 14:13 UTC, djsmith85 commented on apps/browser/src/background/webRequest.background.ts
This should be moved into ownership of @bitwarden/team-autofill-dev. This is related to autofilling/submitting basicAuth

2023-11-27 14:15 UTC, djsmith85 commented on apps/web/src/app/settings/delete-account.component.ts
This should be owned by owned by @bitwarden/team-auth-dev

2023-11-27 14:17 UTC, djsmith85 commented on apps/web/src/app/settings/api-key.component.ts
The api-keys should likely be owned by @bitwarden/team-auth-dev

2023-11-27 14:20 UTC, Hinton commented on libs/common/src/models/request/register.request.ts
It should, but moving requests are painful, and we're in the process of breaking out api services which would handle these ownerships.

2023-11-27 14:21 UTC, djsmith85 submitted a review, later dismissed
Changes are looking good.
As a follow-up I have added some comments that @bitwarden/tech-leads should review and discuss. Ideally moving more files into ownership of teams.

@Hinton The only minor thing I had seen that would have been nice: If a file had a previous import from i.e. `vault/enums`, it would have been nice to combine them instead of having two.

2023-11-27 14:21 UTC, Hinton commented on libs/common/src/services/search.service.ts
TBD. Realistically we might want to copy it and create a vault search and send search service. Or make a core search service and delegate details to models. But it doesn't have a clear owner yet.

2023-11-27 14:37 UTC, djsmith85 commented on apps/browser/src/background/models/addLoginQueueMessage.ts
Should be owned by @bitwarden/team-autofill-dev

2023-11-27 14:38 UTC, cagonzalezcs approved these changes

2023-11-27 14:43 UTC, cturnbull-bitwarden approved these changes

2023-11-27 14:48 UTC, cagonzalezcs submitted a review, later dismissed

2023-11-27 14:53 UTC, djsmith85 requested changes

2023-11-27 14:53 UTC, djsmith85 commented on apps/browser/src/auth/background/service-factories/totp-service.factory.ts
If the `totpService` is owned by vault, then the factory should also be owned by @bitwarden/team-vault-dev or is the assignment of the service wrong?

2023-11-27 15:06 UTC, jlf0dev commented on apps/web/src/app/settings/change-kdf/change-kdf.component.ts
Most likely auth

2023-11-27 15:15 UTC, jlf0dev approved these changes
Pretty sure CLI build is failing for everyone

2023-11-27 15:20 UTC, djsmith85 approved these changes

2023-11-27 15:38 UTC, shane-melton approved these changes

2023-11-27 16:54 UTC, MGibson1 commented on apps/web/src/app/settings/change-kdf/change-kdf.component.ts
yup, auth

2023-11-27 17:25 UTC, cagonzalezcs approved these changes

2023-11-27 19:05 UTC, cturnbull-bitwarden approved these changes

2023-11-27 19:08 UTC, MGibson1 approved these changes

2023-11-27 20:49 UTC, eliykat approved these changes

2023-11-27 20:59 UTC, merged