[PM-4690] Setting in the browser extension that turns off passkeys
bitwarden/clients pull request #6929
Opened 2023-11-21 13:08 UTC by kspearrin

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

New global setting that allows the user to disable passkey functionality in the browser extension.

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

![image](https://github.com/bitwarden/clients/assets/1190944/08c72a07-f04e-4f10-b4aa-a614a7c0e414)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-11-21 14:01 UTC, coroiu submitted a review, later dismissed
Looks good, tiny non-blocking nitpick

2023-11-21 14:01 UTC, coroiu commented on apps/browser/src/popup/settings/options.component.ts
> +  enablePasskeys = true;
Actually I see that the `stateService` already has explicit default handling `?? false`

2023-11-21 14:09 UTC, kspearrin commented on apps/browser/src/popup/settings/options.component.ts
> +  enablePasskeys = true;
Yea, I agree it could be confusing. This is mostly following the pattern established for existing settings, which have the same problem.

2023-11-21 14:14 UTC, coroiu commented on apps/browser/src/popup/settings/options.component.ts
> +  enablePasskeys = true;
Yeah, I remember creating a tech-debt ticket my first month at Bitwarden to rename a state property from `disable` to `enable`. Never got around to it :(

2023-11-22 08:15 UTC, coroiu submitted a review, later dismissed

2023-11-22 18:53 UTC, justindbaur requested changes

2023-11-22 18:53 UTC, justindbaur commented on libs/common/src/platform/services/state.service.ts
> +  }
Thoughts on making these `getEnablePasskeys` and `setEnablePasskeys`? Then treat undefined as true? I know we have an existing pattern on the disable but I prefer the actual value being stored be what is shown in the UI when we can.

2023-11-22 19:05 UTC, kspearrin commented on libs/common/src/platform/services/state.service.ts
> +  }
Done

2023-11-22 19:07 UTC, justindbaur submitted a review, later dismissed

2023-11-22 19:32 UTC, withinfocus approved these changes
Failing tests?

Left one optimization that isn't a blocker.

2023-11-22 19:32 UTC, withinfocus commented on libs/common/src/vault/services/fido2/fido2-client.service.ts
> +    const userEnabledPasskeys = await this.stateService.getEnablePasskeys();
🎨 Could move this up a line and return if false vs. getting the feature flag; I believe this will at times force an API call if the values are stale.

2023-11-22 20:27 UTC, kspearrin commented
All tests pass for me locally so not sure what is going on.

2023-11-22 20:48 UTC, gbubemismith commented
I confirmed the tests passed locally, but I am trying to understand why they all `FidoAuthenticatorService` fail here.

2023-11-22 20:48 UTC, gbubemismith approved these changes

2023-11-22 21:35 UTC, gbubemismith commented
> I confirmed the tests passed locally, but I am trying to understand why they all `FidoAuthenticatorService` fail here.

Wrong information, it appears `Fido2ClientService` tests are failing locally

2023-11-22 21:41 UTC, kspearrin commented
> > I confirmed the tests passed locally, but I am trying to understand why they all `FidoAuthenticatorService` fail here.
> 
> Wrong information, it appears `Fido2ClientService` tests are failing locally

Ok, I see tests passing under browser client, but tests at root are failing locally.

2023-11-22 21:42 UTC, gbubemismith commented
> > > I confirmed the tests passed locally, but I am trying to understand why they all `FidoAuthenticatorService` fail here.
> > 
> > 
> > Wrong information, it appears `Fido2ClientService` tests are failing locally
> 
> Ok, I see tests passing under browser client, but tests at root are failing locally.

Yeah it has to do with the `isFido2FeatureEnabled`

2023-11-22 22:14 UTC, justindbaur approved these changes

2023-11-22 22:15 UTC, withinfocus approved these changes

2023-11-22 22:21 UTC, gbubemismith commented on libs/common/src/vault/services/fido2/fido2-client.service.spec.ts
>      configService.getFeatureFlag.mockResolvedValue(true);
I think we need this anymore

2023-11-22 22:24 UTC, gbubemismith approved these changes
LGTM! Thanks for helping out with this

2023-11-23 08:58 UTC, coroiu approved these changes
Thanks for changing `disabled` -> `enabled`

2023-11-23 16:09 UTC, merged