Ps/ac 1786/deprecate manager role
bitwarden/clients pull request #6931
Opened 2023-11-21 15:25 UTC by willmartian

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Deprecates the ability to designate a user as `OrganizationUserType.Manager` behind `FeatureFlags.FlexibleCollections`

## Code changes

- **apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.html:** Hides the Manager option in the member dialog UI
- **apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts:** Maps Manager role to User role when form group loads
- **libs/common/src/admin-console/enums/organization-user-type.enum.ts:** Add deprecation comment to enum
- **libs/common/src/admin-console/models/domain/organization.ts:** Add deprecation comment to model

## Screenshots

`FeatureFlag.FlexibleCollections` is **false**:

![image](https://github.com/bitwarden/clients/assets/17113462/bd3f0108-a633-4e98-8245-158cab882400)

`FeatureFlag.FlexibleCollections` is **true**:

![image](https://github.com/bitwarden/clients/assets/17113462/cd3f01f8-6c5e-43dc-8cba-fa1ff6c7d667)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-12-06 01:41 UTC, eliykat requested changes
There are a few other places where this is displayed in the front-end and we have to do this mapping. However, I noticed that it's also used in the CLI: https://github.com/bitwarden/clients/blob/master/apps/cli/src/commands/list.command.ts#L220-L233

Given that we have less control over when the CLI is updated, I think we have to update these mappings on the server side. (As @r-tome initially suggested.)

Can you please revert changes to `member-dialog.component.ts` as that will be done server-side. I'll make a ticket. Then the rest of the changes should be good to go, thank you!

2023-12-07 16:16 UTC, willmartian commented
> Can you please revert changes to `member-dialog.component.ts` as that will be done server-side.

Done in [8245c67](https://github.com/bitwarden/clients/pull/6931/commits/8245c67e07ec7dd73e73546ee3fe2fd9eeb21bde). Thanks!

2023-12-11 02:21 UTC, eliykat requested changes
Please resolve merge conflicts, I think caused by the automatic re-basing.

2023-12-12 04:00 UTC, eliykat approved these changes

2023-12-12 14:43 UTC, merged