Implemented getPublicKey to follow WSC standards
bitwarden/clients pull request #6934
Opened 2023-11-21 15:44 UTC by gbubemismith

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
This fixes the issue raised https://github.com/bitwarden/clients/issues/6913 in adhering to W3C standards.

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-11-21 15:47 UTC, coroiu commented
I don't think SPKI is the correct key format

2023-11-22 08:13 UTC, coroiu requested changes

2023-11-22 08:13 UTC, coroiu commented on libs/common/src/vault/services/fido2/fido2-authenticator.service.ts
> +        pubKeyDer = await crypto.subtle.exportKey("spki", keyPair.publicKey);
issue: this is the wrong format. The key needs to be returned in `DER` format, a conversion we don't currently support. To merge this PR we need to implement that conversion and then also find a way to validate that the data we return can actually be read as `DER`, maybe using external applications that can read `DER`

2023-11-23 09:30 UTC, coroiu commented on libs/common/src/vault/services/fido2/fido2-authenticator.service.ts
> +        pubKeyDer = await crypto.subtle.exportKey("spki", keyPair.publicKey);
I can't approve before you publish the PR :)

2023-11-23 14:31 UTC, gbubemismith commented on libs/common/src/vault/services/fido2/fido2-authenticator.service.ts
> +        pubKeyDer = await crypto.subtle.exportKey("spki", keyPair.publicKey);
Well, it is not really the same thing, but when using the `WebCryptoAPI` for exporting the `SPKI, ` it's encoded using DER.

2023-11-24 08:55 UTC, coroiu approved these changes
Confirmed that this seems to be exporting the same format as chrome, at least according to https://lapo.it/asn1js/

2023-11-27 16:02 UTC, merged