[PM-4810][PM-4825][PM-4880] Fix encrypted import and add null check
bitwarden/clients pull request #6935
Opened 2023-11-21 17:04 UTC by LRNcardozoWDF

## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

This PR fixes some problems introduced in PM-4185:
- PM-4810 Bumped up minimum versions of IVIE;
- PM-4825 Fixed encrypted import;
- PM-4880 Add null check so vault items can load without errors.

## Code changes

- **login-uri.export.ts:** Added new field to export
- **login-uri.ts:** Added null check
- **cipher.service.ts:** Bumped up version

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-11-28 21:11 UTC, shane-melton approved these changes

2023-12-20 16:57 UTC, ttalty approved these changes

2023-12-20 18:32 UTC, djsmith85 requested changes
@LRNcardozoWDF:

Adding the checksum to the export model and skipping the validation will not solve the problem with the exports. I think it will also break importing existing/older backups which will not have that field yet.

The checksum is only used to verify the uri coming from the server and is not used for the import of backups scenario. 

We should rather look into generating the checksum when decrypting/creating the ciphers on import

2023-12-20 19:19 UTC, LRNcardozoWDF commented
@djsmith85 This validation is tied to the existence on the cipher key encryption, if a cipher doesn't have a key this validation won't occur. So existing/older backups will be imported without problem.

2023-12-21 13:34 UTC, djsmith85 approved these changes
After doing some more tests and speaking with @MGibson1 and @LRNcardozoWDF this is good to go.

2023-12-21 17:05 UTC, merged