[PM-3560] Adding the password complexity component to the password protected va…
bitwarden/clients pull request #6936
Opened 2023-11-21 19:28 UTC by ttalty

## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Add the password complexity meter to the vault export page. No policies need to be applied. Just a display of the complexity meter. 

## Code changes

- **apps/web/src/app/tools/vault-export/export.component.html:** Adding the password strength component to the vault export
- **libs/angular/src/tools/export/components/export.component.ts:** Importing the password strength component and the function to get the password strength.

## Screenshots

![image](https://github.com/bitwarden/clients/assets/144813356/2d7f6289-4a85-4590-b505-b00580306be1)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-11-21 20:47 UTC, audrey-jensen approved these changes
Just some nits to pick, nothing major or blocking.

2023-11-21 20:47 UTC, audrey-jensen commented on libs/angular/src/tools/export/components/export.component.ts
> +  getStrengthResult(result: zxcvbn.ZXCVBNResult) {
❓ Is the input a password? If so, I might call the parameter `password` instead of `result`.
⛏️ The method is Missing documentation.

2023-11-21 20:47 UTC, audrey-jensen commented on libs/angular/src/tools/export/components/export.component.ts
> +  filePasswordValue: string = null;
⛏️ It's not required, but it's helpful to add `| null` to members that support null values.
⛏️ The public members should be documented.

2023-11-21 21:11 UTC, audrey-jensen requested changes
Just realized there's a service that wraps zxcvbn. You should use the service.

2023-11-21 21:11 UTC, audrey-jensen commented on libs/angular/src/tools/export/components/export.component.ts
> +import zxcvbn from "zxcvbn";
⚠️ There's a service that provides password strength. You should use that instead of importing the library directly.

https://github.com/bitwarden/clients/blob/master/libs/common/src/tools/password-strength/password-strength.service.ts

2023-11-22 15:12 UTC, ttalty commented on libs/angular/src/tools/export/components/export.component.ts
> +  filePasswordValue: string = null;
No need to check the value or strength in the export component as the password strength component handles this.

2023-11-22 15:12 UTC, ttalty commented on libs/angular/src/tools/export/components/export.component.ts
> +  getStrengthResult(result: zxcvbn.ZXCVBNResult) {
No need to check the value or strength in the export component as the password strength component handles this.

2023-11-28 19:44 UTC, merged