Vertical Vault Navigation
bitwarden/clients pull request #6957
Opened 2023-11-23 13:10 UTC by Hinton

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

PoC for Vertical Vault Navigation refresh

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-01-23 23:08 UTC, Thomas-Avery submitted a review, later dismissed
Secrets Manager changes look good.

2024-01-24 07:04 UTC, shane-melton commented
@ike-kottlowski Apologies! The video had not been updated to reflect the latest changes. I uploaded a new video above and the title is updating correctly -- thanks for pointing that out!

As for the responsiveness, we have followup work (AC-933 and PM-2664) to make the tables/side nav more responsive for smaller devices.

2024-01-24 14:30 UTC, cturnbull-bitwarden submitted a review, later dismissed
Love it!

2024-01-24 14:35 UTC, MGibson1 requested changes
We will need to immediately do work to move this banner state to state providers. Can you just do it now?

2024-01-24 15:26 UTC, andrebispo5 approved these changes
Auth files look good.

2024-01-24 15:42 UTC, willmartian commented
> Also, I know we have a mobile app but is there consideration given to screen size?

@ike-kottlowski Yes. https://github.com/bitwarden/clients/pull/6383

2024-01-26 14:51 UTC, djsmith85 reviewed
Changes related to the the vertical nav bar and pages owned by tools look good.

Looking at the designs, I see some things missing:
- Vault and Send-filters are currently on their pages instead of the vertical nav bar
- Searchbar for the above mentioned filters has not been moved. Likely into the AppHeader ?
 
![image](https://github.com/bitwarden/clients/assets/2670567/9fa7237c-4250-4115-a726-07d01a1f8509)
That might be an issue for longer item names, because of the reduce screen space. Even though we are eliminating the full width setting and making this the default.

- Currently missing tooltips or word-wrap for menu items that are longer then the nav bar
![image](https://github.com/bitwarden/clients/assets/2670567/93b55a83-2298-4276-930f-72e5d33e1c84)

2024-01-26 15:41 UTC, willmartian commented
>    Currently missing tooltips or word-wrap for menu items that are longer then the nav bar

@djsmith85 Title tooltip added in https://github.com/bitwarden/clients/pull/7703

2024-01-26 15:56 UTC, shane-melton commented
@djsmith85 Thanks for the review! The vault/send filters are not being moved as part of this initial implementation of the vertical nav. We have a [separate epic](https://bitwarden.atlassian.net/browse/PM-3405) to migrate those filters after this.

2024-01-26 16:09 UTC, djsmith85 approved these changes

2024-02-09 14:49 UTC, willmartian requested changes
Multiple stories are not rendering properly in this PR. It looks like they are erroring with `NullInjectorError: No provider for StateService!`

2024-02-14 01:52 UTC, shane-melton commented
@willmartian I believe I fixed the two broken stories for the Product Switcher and Web Header. If there's another one that I missed please let me know!

2024-02-15 18:06 UTC, vincentsalucci approved these changes

2024-02-21 19:06 UTC, willmartian commented on apps/web/src/app/core/state/global-state.ts
> +  showWebBanner = true;
Is this still needed?

2024-02-21 20:29 UTC, shane-melton commented on apps/web/src/app/core/state/global-state.ts
> +  showWebBanner = true;
Nope, that was left over from the original state changes; I'll get it removed, thanks!

2024-02-22 02:27 UTC, willmartian commented on apps/web/src/app/billing/individual/subscription.component.html
> +  </bit-tab-nav-bar>
It looks like we accidentally dropped `*ngIf="!selfHosted"`

2024-02-22 20:40 UTC, shane-melton commented on apps/web/src/app/core/state/global-state.ts
> +  showWebBanner = true;
Fixed in [7bbfa85](https://github.com/bitwarden/clients/pull/6957/commits/7bbfa8589d8bdc99001ec77b106f88cbb58cf198)

2024-02-22 20:59 UTC, cturnbull-bitwarden commented on apps/web/src/app/billing/individual/subscription.component.html
> +  </bit-tab-nav-bar>
Agreed, details on the subscription are handled from the cloud instance and synced over via billing sync, or uploading a license

2024-02-22 21:06 UTC, shane-melton commented on apps/web/src/app/billing/individual/subscription.component.html
> +  </bit-tab-nav-bar>
Great catch! Fixed in [5cfae83](https://github.com/bitwarden/clients/pull/6957/commits/5cfae83e69ae35e5d11430aa06e269aec9f63ff6)

2024-02-23 00:12 UTC, willmartian submitted a review, later dismissed
Platform and CL changes look great to me. Thanks @shane-melton and @Hinton !

2024-02-23 00:14 UTC, ike-kottlowski approved these changes
Auth changes look good!

2024-02-23 09:28 UTC, Hinton commented on .github/CODEOWNERS
> +apps/web/src/app/layouts/header
@willmartian was this intentional? If not let's fix it in a separate PR to avoid requiring re-approvals here.

2024-02-23 09:54 UTC, Hinton reviewed
Great work @shane-melton and @willmartian. Thanks for bringing this over the finish line 🙌.

There ~is~ was 1 blocking issue which we need to resolve before this gets released.

2024-02-23 09:54 UTC, Hinton commented on apps/web/src/app/layouts/header/web-header.component.html
> +    target="_blank"
We're missing `rel="noreferrer"` here which should exist on all links with target blank. We can fix this in a separate PR but it **should** get fixed before this is released.

2024-02-23 09:54 UTC, Hinton commented on apps/web/src/app/layouts/user-layout.component.html
> +    -->
We should delete this comment, I probably used it as a reference while migrating things to nav-items. Can be done in a follow up PR.

2024-02-23 09:54 UTC, Hinton commented on bitwarden_license/bit-web/src/app/admin-console/providers/providers-layout.component.html
> +  ></app-payment-method-banners>
We seem to not be showing this for organizations currently? Should this be lifted into the layout component itself to avoid us repeating it in every layout?

2024-02-23 09:54 UTC, Hinton commented on apps/web/src/app/tools/reports/pages/weak-passwords-report.component.html
> -  </h1>
Did we want to remove the spinners for reports? I explored keeping them in https://github.com/bitwarden/clients/pull/7557

2024-02-23 13:43 UTC, willmartian commented on .github/CODEOWNERS
> +apps/web/src/app/layouts/header
Nope, good catch, the intention was for it to be owned by the CL team for now.

2024-02-23 13:52 UTC, willmartian commented on apps/web/src/app/tools/reports/pages/weak-passwords-report.component.html
> -  </h1>
We already show a spinner further down on the page, so I don't see additional value in having a spinner in the header. 

cc @bitwarden/team-tools-dev

2024-02-23 13:55 UTC, willmartian approved these changes

2024-02-23 16:29 UTC, vincentsalucci approved these changes

2024-02-23 16:55 UTC, Thomas-Avery approved these changes
SM changes LGTM

2024-02-23 17:01 UTC, shane-melton approved these changes

2024-02-23 17:20 UTC, jlf0dev approved these changes

2024-02-23 17:22 UTC, merged

2024-03-05 20:05 UTC, stefan0xC commented
The changes were released today as part of the `web-v2024.2.3`  release (cf. https://github.com/bitwarden/clients/commit/38d8fbdb5a7498b77d445bded30be00b9661a054), however [neither the release notes](https://github.com/bitwarden/clients/releases/tag/web-v2024.2.3) nor [the linked page](https://bitwarden.com/help/releasenotes/) mention anything about this rather big change. Was this intentional?

At least I wouldn't consider changing the whole layout as something that falls under "Bug fixes".