[AC-1758] Show banner when organization requires a payment method
bitwarden/clients pull request #7088
Opened 2023-12-04 19:54 UTC by amorask-bitwarden

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-12-05 20:33 UTC, willmartian commented
Congrats, first usage of `bit-banner` 🥳 

FYI, I made an [issue](https://bitwarden.atlassian.net/browse/CL-150) to create a `BannerService` to control app-wide banners. However, that is not a blocker for this PR.

2023-12-05 20:35 UTC, willmartian commented
Should this banner also be visible in Secrets Manager? cc @bitwarden/dept-design

2023-12-05 21:44 UTC, sukhleenb commented
I don't see it as a necessity because a user logging is first met with the password manager, and I'm assuming linking to the payment method page from SM would add complexities. We could probably revisit this once we support SM-only subscriptions.

2023-12-05 22:23 UTC, willmartian requested changes
Solid work! Some comments:

2023-12-05 22:23 UTC, willmartian commented on apps/web/src/app/components/add-payment-method-banners/add-payment-method-banners.component.ts
> +      .subscribe((billingBannerStates) => this.setBannerStates(billingBannerStates));
Rather than juggling/setting class properties (`this.organizations`, `this.bannerStates`), I would recommend thinking about how you can **transform** the data you _have_ into the data you _need_. RxJS is all about transforming data (via `.pipe`).

We have `this.organizationService.memberOrganizations$` and, based on the needs of the template, we need to transform it into a list of `OrganizationBannerState`.

```ts
this.banner$: Observable<OrganizationBannerState[]> = this.organizationService.memberOrganizations$.pipe(
  canAccessAdmin(this.i18nService),
  this.filterOutPayedOrgs(),
  this.mapOrgsToBannerStates(),
  this.filterOutClosedBanners(),
);
```

2023-12-06 13:46 UTC, amorask-bitwarden commented on apps/web/src/app/components/add-payment-method-banners/add-payment-method-banners.component.html
> +    {{ translateMaintainYourSubscription(bannerState.organizationName) }}
Oh sweet, didn't know you could do that with arguments.

2023-12-06 16:53 UTC, amorask-bitwarden commented
@willmartian Thank you for the detailed review. I've pushed up a commit that addresses your non-Tailwind feedback here: https://github.com/bitwarden/clients/pull/7088/commits/59865ca2e1f0b3ad0888aacb053de9df98ed45cc

Might need some help on the Tailwind part if you don't mind.

2023-12-08 16:41 UTC, cturnbull-bitwarden approved these changes

2023-12-08 16:52 UTC, Hinton commented on libs/common/src/admin-console/services/organization/organization-api.service.ts
> +  }
The api services are intended to act only as wrappers for requests. This seems to be business logic which should be placed in a regular service.

Think of it from a unit testing perspective, by wrapping all requests in a service we have a simple way to mock it. However by combining it with business logic you either have to partially mock the implementation to test it, or not test it.

2023-12-11 15:14 UTC, amorask-bitwarden commented on libs/common/src/admin-console/services/organization/organization-api.service.ts
> +  }
@Hinton That makes sense, thank you. I was struggling to find the correct place to put this given the `OrganizationService` is primarily a wrapper around the `StateService` and the `OrganizationApiService` is only for direct API invocations. I'll create another service for this though.

2023-12-12 16:31 UTC, Hinton commented on apps/web/src/app/components/add-payment-method-banners/add-payment-method-banners.component.ts
> +    }
I think it might be worth considering creating a new endpoint that evaluates if the admin belongs to an organization that has pending payments?

Historically we've thrown these things into the sync response but I'm hesitant to add even more things there.

2023-12-12 17:29 UTC, willmartian requested changes

2023-12-12 17:29 UTC, willmartian commented on apps/web/src/app/components/add-payment-method-banners/add-payment-method-banners.component.ts
> +      });
A general note: rather than setting a class property in a subscription, we can instantiate a class property with a piped observable. 

```ts
    protected organizationBannerStates$ =  combineLatest([this.organizations$, this.billingBannerService.billingBannerStates$])
      .pipe(
        switchMap(async ([organizations, billingBannerStates]) => {
          return await Promise.all(
            organizations.map(async (organization) => {
              const bannerState = await this.getBannerState(organization, billingBannerStates);
              return {
                organizationId: organization.id,
                organizationName: organization.name,
                showBanner: bannerState,
              };
            }),
          );
        })
      );
```

2023-12-12 17:29 UTC, willmartian commented on apps/web/src/app/components/add-payment-method-banners/add-payment-method-banners.component.ts
> +      });
Also, rather than having this property in the component class, do you think it should just be rolled into `billingBannerService.billingBannerStates$`?

2023-12-12 17:29 UTC, willmartian commented on apps/web/src/app/shared/shared.module.ts
Rather than adding `BannerModule` here, let's import it in the standalone component directly.

2023-12-12 17:29 UTC, willmartian commented on libs/common/src/billing/services/billing-banner.service.ts
> +  getPaymentMethodBannerId(organizationId: string) {
Set this to private if it is an internal helper method

2023-12-12 17:29 UTC, willmartian commented on libs/common/src/billing/services/billing-banner.service.ts
> +      .subscribe();
Avoid putting side effects (updating values) in pipe operators; this is what the subscription body is for.

```ts
this.stateService.activeAccountUnlocked$
      .pipe(
        concatMap(async (unlocked) => {
          if (!unlocked) {
            return {};
          }
          
          return this.stateService.getBillingBannerStates();
        });
      )
      .subscribe(this._billingBannerStates);
   ```

2023-12-13 18:46 UTC, willmartian commented on apps/web/src/app/components/add-payment-method-banners/add-payment-method-banners.component.ts
> +    }
Could we not have an endpoint that returns an array of payment pending orgs when given the admin? (I'm not a backend eng)

2023-12-13 20:17 UTC, amorask-bitwarden commented on apps/web/src/app/components/add-payment-method-banners/add-payment-method-banners.component.ts
> +    }
We could, but to me the problem isn't really the complexity of the endpoint, it's the hyper-specificity to this particular use case which makes it difficult to know where exactly it should go.

2023-12-14 15:54 UTC, amorask-bitwarden commented
@willmartian @Hinton I believe I've resolved the remainder of the smaller feedback.

I've also added a new endpoint, `/organizations/{id}/risks-subscription-failure` to the `OrganizationApiService`. It's not perfect, but it cuts the amount of initial requests down by half while keeping us in line with the current API structure/pattern. That endpoint was added here: https://github.com/bitwarden/server/pull/3515/commits/6202e5c28300abe95ba9d90276bd3f6c04b831d8

2023-12-14 21:56 UTC, willmartian reviewed
Nice work. I left two more small code-style comments, but platform changes LGTM. However, gonna ping @Hinton to make sure his feedback was also addressed.

2023-12-14 21:56 UTC, willmartian commented on apps/web/src/app/components/payment-method-banners/payment-method-banners.component.ts
> +            const response = await this.organizationApiService.risksSubscriptionFailure(
Nit pick: you don't need this `else` block since you are doing an early return.

2023-12-15 14:04 UTC, amorask-bitwarden commented
Hi @Hinton, do you think the approach outlined [here](https://github.com/bitwarden/clients/pull/7088#issuecomment-1856104253) acceptable?

2023-12-15 15:21 UTC, Hinton commented
@amorask-bitwarden Sounds like a good approach.

2023-12-15 16:20 UTC, willmartian submitted a review, later dismissed
Thanks for iterating on this @amorask-bitwarden!

2023-12-15 16:34 UTC, cturnbull-bitwarden approved these changes

2023-12-18 15:31 UTC, r-tome approved these changes

2023-12-18 15:49 UTC, willmartian approved these changes

2024-01-05 12:23 UTC, cturnbull-bitwarden submitted a review, later dismissed

2024-01-09 11:40 UTC, LRNcardozoWDF approved these changes
LGTM!

2024-01-09 14:16 UTC, r-tome approved these changes

2024-01-12 15:08 UTC, cturnbull-bitwarden approved these changes

2024-01-12 15:13 UTC, r-tome approved these changes

2024-01-12 15:31 UTC, LRNcardozoWDF approved these changes

2024-01-12 21:09 UTC, justindbaur requested changes
I'm very sorry to do this but we are gonna try to not add anymore state to `StateService`. We are trying to use the [super brand new state providers](https://add-state-provider-framework.contributing-docs.pages.dev/architecture/deep-dives/state/). The good thing is that they will do some of the observable stuff and account unlocked stuff for you. The bummer is I will have to have you make some changes. I'm gonna get a PR making a platform owned general `BannerService` that you can consume and get merged in on tuesday. Then I can talk you through it if you'd like. Again, sorry to do this so late into the PR.

2024-01-19 19:17 UTC, justindbaur commented
@amorask-bitwarden Sorry to yank you around a bit but after talking with @willmartian more about how this paradigm will fit in with more teams and more use cases we think we shouldn't actually have our own central service handling the banner states. Instead you can probably copy a lot of the state stuff from #7543 into the banner service you have now. You'd probably use `"billingBanner"` as the state name and you can use the static suffix you have now as the key name (we do prefer `camelCase` for the state and key names though). 

Again sorry for stalling this and please let me know if there is anything I can do to help.

2024-01-23 16:46 UTC, justindbaur requested changes
Just a couple of the leftover stuff to delete but the rest looks great!

2024-01-23 16:46 UTC, justindbaur commented on libs/common/src/platform/abstractions/state.service.ts
> +  ) => Promise<void>;
Should be save to delete this now.

2024-01-23 16:46 UTC, justindbaur commented on libs/common/src/platform/models/domain/account.ts
> +  billingBannerStates?: Record<string, boolean> = {};
This too

2024-01-23 16:46 UTC, justindbaur commented on libs/common/src/platform/services/state.service.ts
> +  }
Lastly this.

2024-01-23 17:30 UTC, justindbaur approved these changes
Looks great, thank you!

2024-01-23 17:40 UTC, cturnbull-bitwarden approved these changes

2024-01-23 17:41 UTC, r-tome approved these changes

2024-01-23 17:47 UTC, Jingo88 approved these changes

2024-01-23 17:47 UTC, merged