[SM-923] Project -> Service Accounts : Using new access selector for Project Service Account Access
bitwarden/clients pull request #7089
Opened 2023-12-04 20:40 UTC by cd-bitwarden

## Type of change

```
- [ ] Bug fix
- [ x ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Converting access policy logic to use the new logic.

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

![image](https://github.com/bitwarden/clients/assets/106776772/baf68223-b0d3-4dac-afb2-f98507dd2b46)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-12-05 16:08 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/access-policies/access-policy-selector/models/ap-item-view.type.ts
> +export function convertToProjectServiceAccountsAccessPolicyItemViews(
@Thomas-Avery looking back on this, it seems like I could have just updated it a little and used the convertPotentialGranteesToApItemTypeViewType(), and I shouldn't have renamed the export function from convertToAccessPolicyItemViews to convertToProjectPeopleAccessPolicyItemViews 🤔 what are your thoughts?

2023-12-05 16:25 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/access-policies/access-policy-selector/models/ap-item-view.type.ts
> +export function convertToProjectServiceAccountsAccessPolicyItemViews(
Do we want this to be generic, or do we intend on making specific ones for each scenario? I'm having a hard time remembering if we had a convo about this 🤔

2023-12-08 17:50 UTC, Thomas-Avery requested changes

2023-12-12 00:54 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/access-policies/access-policy.service.ts
> +  }
@Thomas-Avery I think I get what you're asking me to do, please double check this just to be sure 😆

2023-12-12 18:31 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/access-policies/access-policy.service.ts
> +    new Subject<ProjectServiceAccountsAccessPoliciesView>();
@Thomas-Avery are you okay with me removing this as a part of the SM-1030? It looks like removing it now properly effects other areas like access-removal-dialog.component.ts and service-account-people.component.ts, and a few others.

2024-01-02 22:11 UTC, Thomas-Avery approved these changes
Looks good

2024-04-23 14:50 UTC, Thomas-Avery commented
Closing this work moved to https://github.com/bitwarden/clients/pull/8789

2024-04-23 14:50 UTC, closed without merging