Auth/pm 4596/extract pin and bio unlock method logic into re useable services for user verification
bitwarden/clients pull request #7107
Opened 2023-12-05 20:50 UTC by JaredSnider-Bitwarden

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-12-06 09:32 UTC, coroiu reviewed
Looks very promising and very much aligned with my understanding of our conversion

2023-12-06 09:32 UTC, coroiu commented on libs/common/src/auth/services/user-verification/user-verification.service.ts
> +    }
praise: nice 👌

2023-12-06 09:32 UTC, coroiu commented on libs/common/src/auth/services/user-verification/user-verification.service.ts
> +    }
suggestion: simplify and make intention more explicit

```suggestion
return userKey != null;
```

2023-12-06 09:32 UTC, coroiu commented on libs/common/src/auth/services/user-verification/user-verification.service.ts
>    async verifyUser(verification: Verification): Promise<boolean> {
thought: we probably need to change these methods somehow. Something like

```ts
type ServerSideVerification = { type: OTP } & { type: MP };
type ClientSideVerification = ServerSideVerification & { type: PIN } & { type: Biometrics };
type Verification = ServerSideVerification & ClientSideVerification;

function isServerSideVerification(verification: Verification): verification is ServerSideVerification {
  return verification === OTP || verification === MP;
}

async verifyUser(verification: Verification) {
  //...
}

async buildRequest(verification: Verification) {
  if (!isServerSideVerification(verification)) {
    throw new Error("Server verification does not support PIN or Biometrics");
  }
}
```

2023-12-06 09:32 UTC, coroiu commented on libs/common/src/auth/services/pin-crypto.service.implementation.ts
suggestion: should we start putting these in `@bitwarden/auth`?

2023-12-06 09:36 UTC, coroiu commented on libs/common/src/auth/services/user-verification/user-verification.service.ts
>    async verifyUser(verification: Verification): Promise<boolean> {
And the `user-verification-prompt` could maybe get a new input `[verificationTarget]="client"`? Probably renamed to something much better than `verificationTarget` that I have full confidence in your ability to come up with 😁 Or some other solution honestly

2023-12-06 15:32 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/pin-crypto.service.implementation.ts
> +      default: {
Yeah, I didn't know about that until seeing this existing check either!

2023-12-07 22:31 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/user-verification/user-verification.service.ts
>    async verifyUser(verification: Verification): Promise<boolean> {
@coroiu , I have made a first draft attempt at this if you wish to provide early feedback!

2023-12-13 22:38 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/pin-crypto.service.implementation.ts
Moved into `@bitwarden/auth`

2023-12-14 00:19 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/user-verification/user-verification.service.ts
>    async verifyUser(verification: Verification): Promise<boolean> {
We reviewed the latest draft of type changes, and we discussed breaking out the user verification component changes into a separate task and PR.

2023-12-14 10:12 UTC, coroiu reviewed
Looks good, minor comments and one general question:

@JaredSnider-Bitwarden Everything will continue working as before because the `user-verfication.component` still only returns `VerificationType.OTP` or `VerificationType.MasterPassword` right?

2023-12-14 10:12 UTC, coroiu commented on libs/common/src/auth/services/user-verification/user-verification.service.ts
> +    }
question: would it make sense to move this into a separate `MasterPasswordCrypoService`? Not saying that it needs to be done now at this moment, just curious !

2023-12-14 10:12 UTC, coroiu commented on libs/auth/src/services/pin-crypto/pin-crypto.service.spec.ts
> +      it(`should successfully decrypt and return user key with valid, ${pinLockType} PIN (${migrationStatus} migration)`, async () => {
question: with valid what? Did you miss a word here or am I reading this wrong?

nit: deviates slightly from naming convention `should ... when`

2023-12-14 10:12 UTC, coroiu commented on libs/auth/src/services/pin-crypto/pin-crypto.service.spec.ts
> +      it(`should return null when ${pinLockType} PIN (${migrationStatus} migration) is incorrect and user key cannot be decrypted`, async () => {
nit: there's a closing parenthesis `)` after migration , but no corresponding opening parenthesis

2023-12-14 10:12 UTC, coroiu commented on libs/auth/src/services/pin-crypto/pin-crypto.service.spec.ts
> +    testCases.forEach(({ pinLockType, migrationStatus }) => {
suggestion: I'm wondering if maybe these variables should be described in a `describe("given...", => ` block instead of being interpolated into all of the test descriptions below

2023-12-14 10:12 UTC, coroiu commented on libs/auth/src/services/pin-crypto/pin-crypto.service.spec.ts
> +      it(`should return null when ${pinLockType} PIN (${migrationStatus} migration) doesn't match after successful user key decryption`, async () => {
nit: missing parenthesis again :D

suggestion: I think you are missing the word `pin` somewhere in here

```suggestion
      it(`should return null when the pin doesn't match after successful user key decryption`, async () => {
```

2023-12-14 23:19 UTC, JaredSnider-Bitwarden commented on libs/auth/src/services/pin-crypto/pin-crypto.service.implementation.ts
> +import { PinCryptoServiceAbstraction } from "../../abstractions/pin-crypto.service.abstraction";
Those must have got messed up when I moved the files or when I used auto-import to fix. Great catch!

2023-12-14 23:29 UTC, JaredSnider-Bitwarden commented
> Everything will continue working as before because the `user-verfication.component` still only returns `VerificationType.OTP` or `VerificationType.MasterPassword` right?

Yes, it should not affect existing flows but simply support the discussed addition of future flows for PIN & Biometric.

2023-12-14 23:30 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/user-verification/user-verification.service.ts
> +  private validateSecretExists(verification: VerificationWithSecret) {
Renamed to `validateSecretInput`

2023-12-14 23:31 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/user-verification/user-verification.service.ts
> +    }
Will discuss with @jlf0dev

2023-12-14 23:36 UTC, JaredSnider-Bitwarden commented on libs/auth/src/services/pin-crypto/pin-crypto.service.spec.ts
> +
@coroiu , updating these imports seems to have broken the tests? I'm not sure why b/c the imports are definitely valid. Do you know the use of `@bitwarden/common` would not work in a test file?

2023-12-15 01:15 UTC, JaredSnider-Bitwarden commented on libs/auth/src/services/pin-crypto/pin-crypto.service.spec.ts
> +      it(`should return null when ${pinLockType} PIN (${migrationStatus} migration) is incorrect and user key cannot be decrypted`, async () => {
There is an opening parenthesis. `(${migrationStatus} migration)` results in `(PRE migration)` or `(POST migration)`.

2023-12-15 01:17 UTC, JaredSnider-Bitwarden commented on libs/auth/src/services/pin-crypto/pin-crypto.service.spec.ts
> +      it(`should return null when ${pinLockType} PIN (${migrationStatus} migration) doesn't match after successful user key decryption`, async () => {
There is an opening parenthesis. 

`should return null when ${pinLockType} PIN (${migrationStatus} migration) doesn't match after successful user key decryption` also includes the word PIN in the middle of the two interpolated values? 

Here's an example: "should return null when TRANSIENT **PIN** (PRE migration) doesn't match after successful user key decryption

2023-12-15 01:18 UTC, JaredSnider-Bitwarden commented on libs/auth/src/services/pin-crypto/pin-crypto.service.spec.ts
> +      it(`should successfully decrypt and return user key with valid, ${pinLockType} PIN (${migrationStatus} migration)`, async () => {
"with valid, TRANSIENT PIN ..." is correct? I'm using a comma to separate two adjectives for the PIN noun.

2023-12-15 01:20 UTC, JaredSnider-Bitwarden commented on libs/auth/src/services/pin-crypto/pin-crypto.service.spec.ts
> +      it(`should successfully decrypt and return user key with valid, ${pinLockType} PIN (${migrationStatus} migration)`, async () => {
![image](https://github.com/bitwarden/clients/assets/116684653/2ec18f73-8139-49ca-9c31-69adcc4d6eea)

2023-12-15 01:21 UTC, JaredSnider-Bitwarden commented on libs/auth/src/services/pin-crypto/pin-crypto.service.spec.ts
> +      it(`should return null when ${pinLockType} PIN (${migrationStatus} migration) is incorrect and user key cannot be decrypted`, async () => {
![image](https://github.com/bitwarden/clients/assets/116684653/db50ea1d-427f-475e-8057-dbad0901f866)

2023-12-15 01:21 UTC, JaredSnider-Bitwarden commented on libs/auth/src/services/pin-crypto/pin-crypto.service.spec.ts
> +      it(`should return null when ${pinLockType} PIN (${migrationStatus} migration) is incorrect and user key cannot be decrypted`, async () => {
See https://github.com/bitwarden/clients/pull/7107#discussion_r1427456012 for full test run

2023-12-15 01:22 UTC, JaredSnider-Bitwarden commented on libs/auth/src/services/pin-crypto/pin-crypto.service.spec.ts
> +      it(`should return null when ${pinLockType} PIN (${migrationStatus} migration) doesn't match after successful user key decryption`, async () => {
See https://github.com/bitwarden/clients/pull/7107#discussion_r1427456012 for full test run

2023-12-15 13:40 UTC, jlf0dev commented on libs/common/src/auth/services/user-verification/user-verification.service.ts
> +    }
Considering we need a service to hold the state for the master key and key hash, I think this is a good idea. I'll start looking into doing this as part of our state provider refactors.

2023-12-18 09:31 UTC, coroiu commented on libs/auth/src/services/pin-crypto/pin-crypto.service.spec.ts
> +      it(`should successfully decrypt and return user key with valid, ${pinLockType} PIN (${migrationStatus} migration)`, async () => {
oh, I think it's the comma that trips me up :D

looks good without it!

2023-12-18 09:35 UTC, coroiu commented on libs/auth/src/services/pin-crypto/pin-crypto.service.spec.ts
> +      it(`should return null when ${pinLockType} PIN (${migrationStatus} migration) is incorrect and user key cannot be decrypted`, async () => {
omg I am blind, never mind :D

2023-12-18 09:36 UTC, coroiu commented on libs/auth/src/services/pin-crypto/pin-crypto.service.spec.ts
> +      it(`should return null when ${pinLockType} PIN (${migrationStatus} migration) doesn't match after successful user key decryption`, async () => {
Yep, blind :D

2023-12-18 10:07 UTC, coroiu approved these changes
Looks good, something is up with the tests but seem unrelated to these changes

2023-12-18 23:06 UTC, JaredSnider-Bitwarden commented on libs/auth/src/services/pin-crypto/pin-crypto.service.spec.ts
> +    testCases.forEach(({ pinLockType, migrationStatus }) => {
![image](https://github.com/bitwarden/clients/assets/116684653/2b3056c9-9521-46c3-98a2-17e2d82d42c4)
This ended up looking nice! Thank you for the suggestion!

2023-12-19 07:45 UTC, coroiu commented on libs/auth/src/services/pin-crypto/pin-crypto.service.spec.ts
> +    testCases.forEach(({ pinLockType, migrationStatus }) => {
Niiice! And thank you for making the change!

2024-01-02 16:31 UTC, JaredSnider-Bitwarden commented
Marking as draft to figure out circular dependency issues I introduced between the new `PinCryptoService`, the `UserVerificationService`, and the `VaultTimeoutSettingsService`.
<img width="992" alt="image" src="https://github.com/bitwarden/clients/assets/116684653/20047b7a-7a55-4f23-af11-5c7a6460a188">

2024-01-03 18:51 UTC, justindbaur submitted a review, later dismissed
Approving for platform

2024-01-03 18:57 UTC, jlf0dev approved these changes
Good stuff! Left some feedback but nothing blocking

2024-01-03 18:57 UTC, jlf0dev commented on libs/common/src/auth/services/user-verification/user-verification.service.ts
> +          throw new Error(this.i18nService.t("pinRequired"));
For future - this leads me to believe that we need classes of the verification types that can hold properties and behavior. You could then just call `verification.validateSecret` and it would handle the different types through inheritance. 
The tough part of this is getting the type specific verification logic thats held in another service, but you could just pass a callback on verification creation.

Just thoughts. Nothing to follow up here.

2024-01-03 19:14 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/user-verification/user-verification.service.ts
> +          throw new Error(this.i18nService.t("pinRequired"));
Agreed. I decided to just extend the custom types we had for now. Inheritance would probably solve this more cleanly.

2024-01-03 19:15 UTC, vincentsalucci submitted a review, later dismissed

2024-01-03 19:19 UTC, jlf0dev approved these changes

2024-01-03 19:20 UTC, justindbaur submitted a review, later dismissed

2024-01-03 19:20 UTC, vincentsalucci submitted a review, later dismissed

2024-01-10 21:47 UTC, justindbaur approved these changes

2024-01-10 22:05 UTC, vincentsalucci approved these changes

2024-01-12 17:41 UTC, jlf0dev approved these changes

2024-01-12 19:07 UTC, justindbaur submitted a review, later dismissed

2024-01-16 13:46 UTC, jlf0dev requested changes

2024-01-16 13:46 UTC, jlf0dev commented on libs/common/src/auth/types/verification.ts
> +}
I couldn't find any references to these, should we include them if they're not used yet?

2024-01-16 15:48 UTC, jlf0dev approved these changes

2024-01-16 19:50 UTC, vincentsalucci approved these changes

2024-01-16 19:51 UTC, JaredSnider-Bitwarden commented
Passed QA!

2024-01-16 19:52 UTC, merged