Ps/avoid state emit until updated
bitwarden/clients pull request #7124
Opened 2023-12-06 19:57 UTC by MGibson1

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Draft of closing update race conditions and cleaning up storage listening when there are no observers of state.

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-12-07 17:26 UTC, MGibson1 commented on libs/common/spec/utils.ts
> +      case "symbol":
My thinking is that anyone tracking a symbol expects some weird behavior. This is the best I can do to detect the `FAKE_DEFAULT` I wanted

2023-12-07 17:26 UTC, MGibson1 commented on libs/common/spec/utils.ts
> +export async function awaitAsync(ms = 1) {
This little await resolved a lot of async issues

2023-12-07 17:28 UTC, MGibson1 commented on libs/common/src/platform/state/implementations/default-active-user-state.spec.ts
> +    expect(emissions).toEqual([user1Data]);
This is a real different, but on inspecting what two emissions were occurring, I found that it was the same data twice.

I think that in moving the observable initialization around, I removed a double emit from this test.

2023-12-07 17:35 UTC, MGibson1 commented on libs/common/src/platform/state/implementations/default-active-user-state.ts
> +      shareReplay({ bufferSize: 1, refCount: false }),
This isn't new, just to make sure we always have a key available

2023-12-07 17:36 UTC, MGibson1 commented on libs/common/src/platform/state/implementations/default-active-user-state.ts
> +  // TODO: this should be removed
This TODO is in reference to wanting to update the public interface, the method was just moved and so is seen as new. No change vs old.

2023-12-11 15:44 UTC, justindbaur requested changes
Couple tiny things, thanks for the much better tests.

2023-12-11 15:44 UTC, justindbaur commented on libs/common/src/platform/state/implementations/default-active-user-state.spec.ts
>        id: userId as UserId,
Cast is now unnecessary.

2023-12-11 15:44 UTC, justindbaur commented on libs/common/src/platform/state/key-definition.spec.ts
> +      });
I say we throw in the constructor if they provide a value less than 0 instead of saving them silently.

2023-12-12 01:32 UTC, merged