[AC-1389] update collection dialog copy based on admin access setting
bitwarden/clients pull request #7137
Opened 2023-12-07 18:55 UTC by willmartian

…llectionItems setting

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

![image](https://github.com/bitwarden/clients/assets/17113462/74d559bf-77c3-4226-8f7f-f79e029bd5ab)

![image](https://github.com/bitwarden/clients/assets/17113462/bcd88339-7809-4439-bf5b-ce6d44965ead)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-12-11 05:20 UTC, eliykat commented on apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.ts
> +          if (flexibleCollections && !allowAdminAccessToAllCollectionItems) {
As discussed - this should use the v1 flag instead of the MVP flag (and make sure to update the variable name to reflect this)

2023-12-12 14:41 UTC, willmartian commented on apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.ts
> +          if (flexibleCollections && !allowAdminAccessToAllCollectionItems) {
Resolved via [f6af28c](https://github.com/bitwarden/clients/pull/7137/commits/f6af28c77da47548ef3a3c83e983e5a35a7af49a)

2023-12-12 22:58 UTC, eliykat commented on apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.ts
> +          if (flexibleCollectionsV1 && !allowAdminAccessToAllCollectionItems) {
Just clarified with Priya and this error does not depend on org.AllowAdminAccessToAllCollectionItems. Sorry for the confusion, the Jira ticket was wrong.

2023-12-14 00:35 UTC, willmartian commented on apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.ts
> +          if (flexibleCollectionsV1 && !allowAdminAccessToAllCollectionItems) {
No worries! Reverted the validator logic here [2cf6cf8](https://github.com/bitwarden/clients/pull/7137/commits/2cf6cf8f3c0e37b2e384658f1d460792e508ed01).

2023-12-14 04:46 UTC, eliykat requested changes

2023-12-14 04:46 UTC, eliykat commented on apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.ts
> +        .then((orgResponse) => orgResponse.allowAdminAccessToAllCollectionItems),
We shouldn't need an api call to get this property, it should be added to `organization.ts` (i.e. sync data).

@shane-melton do you agree - how do you want to go about adding this?

2023-12-18 20:32 UTC, shane-melton commented on apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.ts
> +        .then((orgResponse) => orgResponse.allowAdminAccessToAllCollectionItems),
Yep, it should be available in `organization.ts` and is already coming down in the sync data, its just not mapped yet. I have a commit to do just that in my work on AC-1124, so I can pull that out and target main to get it reviewed/merged independently.

2023-12-18 20:42 UTC, shane-melton commented on apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.ts
> +        .then((orgResponse) => orgResponse.allowAdminAccessToAllCollectionItems),
https://github.com/bitwarden/clients/pull/7268 addresses this and makes it available on the `organization`

2023-12-19 01:34 UTC, eliykat commented on apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.ts
> +        .then((orgResponse) => orgResponse.allowAdminAccessToAllCollectionItems),
@willmartian that PR is now merged, you should be able to upate from `main` and then access that property on the `organization` variable that is already available in this scope.

2023-12-28 05:09 UTC, eliykat reviewed
As discussed, this error depends on both the v1 flag and on `!org.AllowAdminAccessToAllCollectionItems`. This is not what I said previously, sorry for the confusion.

So your previous logic here was basically what we need: https://github.com/bitwarden/clients/pull/7137/commits/2cf6cf8f3c0e37b2e384658f1d460792e508ed01

Please also see previous feedback left above.

2023-12-29 23:40 UTC, willmartian commented on apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.ts
> +        .then((orgResponse) => orgResponse.allowAdminAccessToAllCollectionItems),
Resolved via [564aa66](https://github.com/bitwarden/clients/pull/7137/commits/564aa66ad730e3f29fa0c68f4df66243ec7c2c90)

2024-01-03 03:21 UTC, eliykat requested changes
One minor thing I noticed, otherwise looking good.

2024-01-03 03:21 UTC, eliykat commented on apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.html
> +            <span *ngIf="organization.allowAdminAccessToAllCollectionItems">{{
This defaults to true for all current orgs, which means it'll show in production today if we merge this now. It should also depend on the v1 flag, e.g.

```suggestion
            <span *ngIf="(flexibleCollectionsV1Enabled$ | async) && organization.allowAdminAccessToAllCollectionItems">{{
```

2024-01-03 03:23 UTC, eliykat requested changes

2024-01-03 03:23 UTC, eliykat commented on apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.html
> +          <div class="tw-mb-3">
This should be behind an `*ngIf="flexibleCollectionsV1Enabled$ | async"` so that we don't show it in production today.

2024-01-05 02:12 UTC, eliykat approved these changes

2024-01-05 02:51 UTC, gbubemismith approved these changes
LGTM

2024-01-05 03:26 UTC, merged