DEVOPS-1683 Refactor deploy-web workflow
bitwarden/clients pull request #7184
Opened 2023-12-12 03:39 UTC by urbinaalex17

## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [X] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Unify the deployment workflow for the web vault into a single workflow with the ability to choose different environments (Storage Accounts) with protection rules.

## Code changes

- **deploy-non-prod-web.yml -> deploy-web.yml:** Unify workflows
- ** deploy-eu-prod-web.yml:** No longer needed.
- ** deploy-eu-qa-web.yml:** No longer needed.

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-12-13 20:53 UTC, vgrassia requested changes

2023-12-13 20:53 UTC, vgrassia commented on .github/workflows/deploy-non-prod-web.yml
> +          branch: ${{ github.event.inputs.tag }}
```suggestion
          branch: ${{ inputs.tag }}
```

2023-12-13 20:53 UTC, vgrassia commented on .github/workflows/deploy-non-prod-web.yml
> +          ref: ${{ github.event.inputs.tag }}
```suggestion
          ref: ${{ inputs.tag }}
```

2023-12-13 20:53 UTC, vgrassia commented on .github/workflows/deploy-non-prod-web.yml
> +          description: 'Deployment from branch ${{ github.event.inputs.tag }}'
```suggestion
          description: 'Deployment from branch ${{ inputs.tag }}'
```

2023-12-13 20:53 UTC, vgrassia commented on .github/workflows/deploy-non-prod-web.yml
> +        if: ${{ success() }}
```suggestion
        if: success()
```

2023-12-13 20:53 UTC, vgrassia commented on .github/workflows/deploy-non-prod-web.yml
> +        if: ${{ failure() }}
```suggestion
        if: failure()
```

2023-12-13 20:53 UTC, vgrassia commented on .github/workflows/deploy-non-prod-web.yml
> +          tag: ${{ github.event.inputs.tag }}
```suggestion
          tag: ${{ inputs.tag }}
```

2023-12-13 20:53 UTC, vgrassia commented on .github/workflows/deploy-non-prod-web.yml
```suggestion
      tag:
        description: "Branch name to deploy (examples: 'main', 'feature/sm')"
        type: string
        default: main

```

2023-12-13 20:53 UTC, vgrassia commented on .github/workflows/deploy-non-prod-web.yml
> +        required: true
```suggestion
```

2023-12-13 20:53 UTC, vgrassia commented on .github/workflows/deploy-non-prod-web.yml
> +          tag: ${{ github.event.inputs.tag }}
```suggestion
          tag: ${{ inputs.tag }}
```

2023-12-14 21:15 UTC, mimartin12 requested changes

2023-12-14 21:15 UTC, mimartin12 commented on .github/workflows/deploy-non-prod-web.yml
>            fi
❓ Would a case statement improve readability here?

2023-12-14 21:15 UTC, mimartin12 commented on .github/workflows/deploy-non-prod-web.yml
> +        default: main
```suggestion
      tag:
        description: "Branch or Tag name to deploy (examples: 'main', 'feature/sm', 'web-v2023.12.0')"
        type: string
        default: main
```
🎨  Small improvement to the `description` to help be a bit clearer to the user.

2023-12-14 21:15 UTC, mimartin12 commented on .github/workflows/deploy-non-prod-web.yml
> +        default: main
```suggestion
      tag:
        description: "Branch or Tag name to deploy (examples: 'main', 'feature/sm', 'web-v2023.12.0')"
        type: string
        default: main
```
🎨 Small improvement to the description to help be a bit clearer to the user.

2023-12-16 00:38 UTC, urbinaalex17 commented on .github/workflows/deploy-non-prod-web.yml
> +        default: main
Would you happen to know if the actions support tags? 🤔 It seems like [download-artifacts](https://github.com/bitwarden/gh-actions/tree/main/download-artifacts) does not.

2023-12-16 01:01 UTC, urbinaalex17 commented on .github/workflows/deploy-non-prod-web.yml
>            fi
It would! I adjusted the code based on our standards. Thanks, @mimartin12!

2023-12-18 20:45 UTC, vgrassia requested changes

2023-12-18 20:45 UTC, vgrassia commented on .github/workflows/deploy-non-prod-web.yml
> +      tag:
```suggestion
      tag:
```

Should this be called `tag` if we don't currently support tags?

2023-12-18 20:50 UTC, mimartin12 commented on .github/workflows/deploy-non-prod-web.yml
> +      tag:
Does the workflow really not support tags? I was under the impression all the deploy workflows do.

2023-12-18 21:51 UTC, vgrassia requested changes

2023-12-18 21:51 UTC, vgrassia commented on .github/workflows/deploy-web.yml
> +        description: "Branch name to deploy (examples: 'main', 'feature/sm')"
```suggestion
        description: "Branch or Tag name to deploy (examples: 'main', 'feature/sm', 'web-v2023.12.0')"
```

2023-12-18 21:51 UTC, vgrassia commented on .github/workflows/deploy-web.yml
> +        description: "Branch name to deploy (examples: 'main', 'feature/sm')"
```suggestion
        description: "Branch or Tag name to deploy (examples: 'main', 'feature/sm', 'web-v2023.12.0')"
```

2023-12-18 22:01 UTC, vgrassia approved these changes

2023-12-18 23:09 UTC, mimartin12 approved these changes

2023-12-18 23:09 UTC, merged