[PM-536] Adding the 1password fix for custom sections and test cases
bitwarden/clients pull request #7190
Opened 2023-12-12 14:09 UTC by ttalty

## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```
## Objective

The 1Password importer was taking fields without a title and using the 26 character id for the field name. Causing confusion and no clarity on the field purpose. If the field has a title the title should be used. If no title the section title should be used. Finally if no title or section title is present. Don't use any id field and just use a blank field. 

## Code changes

- **libs/importer/spec/onepassword-1pux-importer.spec.ts:** Updating the test cases from the id fields to the actual title fields. Created a function to validate duplicate field names with different values. 
- **libs/importer/src/importers/onepassword/onepassword-1pux-importer.ts:** The 1Password 1pux file importer was using the 26 character id field instead of titles or section titles. Added an optional property to the getFieldName function for section title. Removed the regex test on the id field. The 26 character id field should not be used.

2023-12-12 19:49 UTC, audrey-jensen requested changes
❓ for questions
🎨 for suggestions / improvements
⚠️ for concerns needing attention
♻️ for indications of technical debt
⛏ for minor or nitpick changes

2023-12-12 19:49 UTC, audrey-jensen commented on libs/importer/spec/onepassword-1pux-importer.spec.ts
> +  expect(customFieldValues).toEqual(expectedValues.sort().toString());
⚠️ Jest performs a deep equality check, so there's no need to perform `toString()`. Just compare the arrays directly.

```
expect([1, 2, 3]).toEqual([1, 2, 3]) // succeeds
expect([1, 2, 3]).toEqual([1, 2, 4]) // fails
```

🎨 If the order can be guaranteed, consider removing the `.sort()` call and instead passing the items in w/ the expected order instead.

2023-12-12 19:49 UTC, audrey-jensen commented on libs/importer/spec/onepassword-1pux-importer.spec.ts
> +  expectedValues: any[],
❓ Looks like the field is always a string? If so, then the type of `expectedValue` should be string[].

🎨 If the type of the array elements is consistent--for example, it could be have type int[] or string[]--but the type passed into the check can vary, consider using a generic:

```ts
function validateDuplicateCustomField<T>(
    // ...
    expectedValues: T[],
) { 
    // ... 
}
```

2023-12-12 19:49 UTC, audrey-jensen commented on libs/importer/src/importers/onepassword/onepassword-1pux-importer.ts
> +      const fieldName = this.getFieldName(field.id, field.title, sectionTitle);
♻️ Looks like our new prettier format makes codescene unhappy. It's true that the method should be refactored into smaller pieces though.

2023-12-12 19:49 UTC, audrey-jensen commented on libs/importer/src/importers/onepassword/onepassword-1pux-importer.ts
> +        : "";
⛏️ I'd rewrite this nested ternary as if statements. The prettier makes it look distinctly line-noisy.

2023-12-12 20:59 UTC, ttalty commented on libs/importer/src/importers/onepassword/onepassword-1pux-importer.ts
> +        : "";
Fixed with if statements and a default return of an empty string.

2023-12-12 20:59 UTC, ttalty commented on libs/importer/src/importers/onepassword/onepassword-1pux-importer.ts
> +      const fieldName = this.getFieldName(field.id, field.title, sectionTitle);
Will refactor later. The processSectionFields function is fairly large.

2023-12-14 16:44 UTC, audrey-jensen approved these changes
Thanks for addressing my feedback! You're good to go! :)

2023-12-22 21:22 UTC, merged