Add state for everHadUserKey
bitwarden/clients pull request #7208
Opened 2023-12-13 16:33 UTC by MGibson1

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

This PR begins the migration of CryptoService into a service that provides observable data on accounts.

## Code changes

- **main.backgoround / factories / services.module / electron-crypto /browser-crypto / jslib-services **: Dependency changes and tagged type updates
- **lock guard, redirect guard, and tde-decryption-required guard**: These guard services dependend on awaiting a value from cryptoservice, but now await a firstValueFrom the observable. In the future, we should strive to convert these to entirely sync observable values, as reflected in the new TODO comment
- **fake-state-provider**: we were missing a fake implementation of `StateProvider`
- **cryptoService abstraction**: Remove promise get for migrated value. In practice, we were never reading a specific user's state so active user state was chosen to represent the value.
- **state.service abstraction**: Remove gettter/setter for migrated value
- **account model**: Remove migrated value
- **crypto.service impl**:
  - Creates key definition and uses it to provide the active user's value as well as update the value for during `setKey` for a user
  - Forces the more correct `UserId` type for user ids
- **state definition**: Defines disk namespace for crypto
- **migration helper**: We need to be able to migrate v9 to providers at least, otherwise we can never start using them!
- **10-migration**: Moves `account.profile.everHadUserKey` to a user-crypto scoped value :D

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-12-15 16:12 UTC, jlf0dev submitted a review, later dismissed
Auth calls look good 👍 

I don't see a reason to test this one, might need to re-evaluate on larger migrations

2024-01-10 15:47 UTC, justindbaur requested changes
Just not super comfortable with a property getter returning a different observable each time after the issues we've had.

2024-01-10 15:47 UTC, justindbaur commented on libs/common/src/platform/services/crypto.service.ts
> +  }
I'm still kinda nervous about returning obsvervables from property getters. I think this particular one would be fine but I'd rather it be a property that is set once in the constructor.

2024-01-10 16:10 UTC, justindbaur submitted a review, later dismissed

2024-01-10 16:39 UTC, justindbaur approved these changes

2024-01-10 16:51 UTC, jlf0dev approved these changes

2024-01-10 16:51 UTC, merged