Extract a danger-zone component
bitwarden/clients pull request #7220
Opened 2023-12-14 15:52 UTC by Hinton

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Extract a re-useable danger-zone component instead of needing to duplicate the code. I wasn't sure which team should own it, but defaulted to auth since ac is more an extension.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-12-14 15:53 UTC, Hinton commented on apps/web/src/app/auth/settings/account/danger-zone.component.html
> +  <div class="tw-flex tw-flex-row tw-gap-2">
@willmartian I wonder if we should make a button-group component that has this spacing.

2023-12-14 15:59 UTC, danielleflinn commented on apps/web/src/app/auth/settings/account/danger-zone.component.html
> +  <div class="tw-flex tw-flex-row tw-gap-2">
I like this idea, the button group component could also be used in the Dialog footer / form footers where we display a submit/cancel button if we wanted to keep spacing consistent.

2023-12-14 16:05 UTC, willmartian commented on apps/web/src/app/auth/settings/account/danger-zone.component.html
> +  <div class="tw-flex tw-flex-row tw-gap-2">
Yes, 100%. 

Created a Jira issue: https://bitwarden.atlassian.net/browse/CL-158
Prior art: https://shoelace.style/components/button-group

2023-12-14 16:08 UTC, danielleflinn requested changes
Looks like the text in Dark themes is rendering wrong (dark gray) in Storybook. 
<img width="354" alt="Screenshot 2023-12-14 at 8 07 36 AM" src="https://github.com/bitwarden/clients/assets/43477473/45b42eb4-2ff8-4e51-9904-099ff6cbcdda">

If we are keeping the component "Auth" owned, can we move it to the "Auth" collapsible section? 

Also what is the reasoning for keeping the "Danger zone" header out of the storybook component?

2023-12-14 16:12 UTC, Hinton commented
@danielleflinn that's only in storybook. Looks fine in the actual app.

2023-12-14 16:15 UTC, Hinton commented on apps/web/src/app/auth/settings/account/danger-zone.component.html
> +  <div class="tw-flex tw-flex-row tw-gap-2">
Shoelace is more of a toggle style. Our would just be the suggested gap between items. Which might mean it shouldn't be tied to button?

2023-12-14 16:48 UTC, Hinton commented
I lifted in the title in the danger-zone component. We can revisit the decision later. This did make the header inconsistent so I updated the "Change email" to also use the new style.

2023-12-14 17:06 UTC, willmartian approved these changes
Good refactor. One question:

2023-12-14 17:06 UTC, willmartian commented on apps/web/src/app/auth/settings/account/account.component.html
> +  <h1 bitTypography="h1">{{ "changeEmail" | i18n }}</h1>
For "Change Email", is removing the underline (was provided by `.secondary-header`) intended? cc @danielleflinn

2023-12-14 17:10 UTC, danielleflinn commented on apps/web/src/app/auth/settings/account/account.component.html
> +  <h1 bitTypography="h1">{{ "changeEmail" | i18n }}</h1>
Yes, Design is looking to move away from the underlines shown below the headers

2023-12-14 18:07 UTC, jlf0dev approved these changes

2023-12-15 15:06 UTC, danielleflinn approved these changes

2023-12-17 23:31 UTC, eliykat approved these changes

2023-12-18 17:34 UTC, merged