Add Sync Purpose
bitwarden/clients pull request #7289
Opened 2023-12-19 21:43 UTC by justindbaur

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

This will help us track which sync types are happening so we can better track when they are being to eager with their syncing.

## What to review
- That all purposes are unique
- That the purpose I chose for your code makes sense
- That I spelled everything correctly

## Code changes

- ApiService - Take the new purpose and set it into a header
- SyncService - make a purpose now required.
- _Everything else_ adding a purpose to the best of my ability.

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-12-19 21:47 UTC, shane-melton approved these changes

2023-12-19 21:59 UTC, withinfocus commented
Can we enumerate these so they are centralized and then enforce some naming standards and clarity?

2023-12-19 23:04 UTC, eliykat requested changes
LGTM but I agree that the sync purpose should be a union string type or something similar.

2023-12-19 23:14 UTC, jlf0dev commented
Don't we include device type in headers? Why do we need the client in the purpose string?

2023-12-20 02:01 UTC, justindbaur commented
@withinfocus @eliykat I did think about doing something like this but was worried it would actually _encourage_ reuse of the purpose string. Since an enum or string union is generally used as a list of allowed values but in our case it would be a list of not allowed values until you add your single entry and then that is the only value you're allowed to use. 

Plus an enum would only indicate we have a duplicate if we named the identifier the same but not if we named the identifier different but still had the value the same. The union wouldn't save us at all, it will just collapse the repeated entry into one. ([Ref](https://www.typescriptlang.org/play?#code/KYOwrgtgBAygniAxgBTAJwA4HsDOwCi40A3gFBQVQBKwAhjliAPIjBQC8UARGnQyAFpGwLgBpylGvUYBGDt17TBwsaQC+pUgBc4GNvCSpMuYAFUQAS0byJAHwV9GQ1lzsOlzkQG4gA))

@jlf0dev Very good point, for some reason I thought that was only being added to some api calls not all of them. Think it's alright to repeat the same purpose string in those cases then?

2023-12-20 13:53 UTC, jlf0dev commented
> Think it's alright to repeat the same purpose string in those cases then?
Seems like it would be be ok. I do like your goal here of keeping them unique enough to identify where it came from, but we might be able to find the client

2023-12-20 14:11 UTC, cturnbull-bitwarden submitted a review, later dismissed
Billing changes look good!

2023-12-20 18:19 UTC, jlf0dev approved these changes
Looks good!

2023-12-20 18:29 UTC, djsmith85 commented on apps/cli/src/tools/import.command.ts
> +        this.syncService.fullSync(true, "import");
I don't think we need to differentiate between `import.command` and `import.component`.

Both syncs are done after a successful import, as an import will create new ciphers/folders/collections on the server, which are not yet present on the client. 

I'm fine with using either one of the purpose-names.

2023-12-20 18:46 UTC, justindbaur commented on apps/cli/src/tools/import.command.ts
> +        this.syncService.fullSync(true, "import");
Good call, they are both now just `"import"`.

2023-12-20 18:51 UTC, jlf0dev submitted a review, later dismissed

2023-12-20 18:52 UTC, djsmith85 submitted a review, later dismissed
Approving for tools

2023-12-21 04:41 UTC, eliykat submitted a review, later dismissed

2023-12-21 18:49 UTC, shane-melton submitted a review, later dismissed

2023-12-21 20:07 UTC, Jingo88 submitted a review, later dismissed

2023-12-21 20:13 UTC, coltonhurst approved these changes
The SM changes look good 👍

2024-05-01 03:28 UTC, eliykat submitted a review, later dismissed

2024-05-03 07:05 UTC, djsmith85 approved these changes

2024-05-05 22:30 UTC, eliykat approved these changes

2024-05-08 17:31 UTC, cturnbull-bitwarden approved these changes

2024-05-08 22:23 UTC, Jingo88 approved these changes

2024-06-28 16:49 UTC, coltonhurst approved these changes
SM changes look good

2025-08-14 15:22 UTC, closed without merging