Update the content of the enterprise vault page
bitwarden/clients pull request #7291
Opened 2023-12-19 23:30 UTC by mark-youssef-bitwarden

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-12-19 23:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitwarden/clients?pullRequest=7291) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bitwarden/clients?pullRequest=7291) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitwarden/clients?pullRequest=7291) it.</sub>

2023-12-28 19:51 UTC, rr-bw requested changes
Looking good so far, just a few changes to make.

2023-12-28 19:51 UTC, rr-bw commented on apps/web/src/app/auth/trial-initiation/content/enterprise-content.component.html
> +    ></review-logo>
Since you aren't binding to any value in the `enterprise.component.ts` class file, you can just set these to a string without the `[]`.

```suggestion
    <review-logo
      logoClass="tw-w-8"
      logoSrc="../../images/register-layout/g2-logo.svg"
      logoAlt="G2 Logo"
    ></review-logo>
```

2023-12-28 19:51 UTC, rr-bw commented on apps/web/src/app/auth/trial-initiation/content/enterprise1-content.component.html
> +    ></review-logo>
Same here.

2023-12-28 19:51 UTC, rr-bw commented on apps/web/src/app/auth/trial-initiation/content/enterprise2-content.component.html
> +    ></review-logo>
Same here.

2023-12-28 19:51 UTC, rr-bw commented on apps/web/src/app/auth/trial-initiation/content/review-logo.component.html
> +  <img class="{{ logoClass }} mb-2" src="{{ logoSrc }}" alt="{{ logoAlt }}" />
Use [property binding](https://angular.dev/guide/directives#using-ngclass-with-an-expression) for `[src]` and `[alt]`. Using square brackets like `[src]` will make it so that `logoSrc` is treated as an expression, not as a string, from the `review-logo.component.ts` class file. (Of course, because the `logoSrc` property takes a string, the expression will ultimately evaluate to a string.)

As for the classes, for the classes that we want to remain constant we can use the regular `class=` syntax. But for conditional classes, we can use the built-in `[ngClass]` [attribute directive](https://angular.dev/guide/directives#using-ngclass-with-an-expression).

Also fix the missing `tw-` attribute on this class.

```suggestion
  <img class="tw-mb-2" [ngClass]="logoClass" [src]="logoSrc" [alt]="logoAlt" />
```

2023-12-28 20:17 UTC, mark-youssef-bitwarden commented
@rr-bw Thanks for the feedback! I've applied the feedback

2023-12-28 20:22 UTC, rr-bw approved these changes
Looks great! I will move this ticket to "Ready for QA"

2024-01-02 18:48 UTC, merged