[PM-5404]migrate acct decryption options to new service
bitwarden/clients pull request #7344
Opened 2023-12-22 15:57 UTC by jlf0dev

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-01-10 20:08 UTC, JaredSnider-Bitwarden commented on libs/common/src/platform/abstractions/state.service.ts
The state service grows ever smaller! Woo!

2024-01-10 20:11 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/user-verification/user-verification.service.ts
> -    return !(await this.stateService.getUsesKeyConnector({ userId }));
Also, do we want to do this removal as part of this PR? It could introduce side effects, and we didn't remove the marked for deprecation code in the `libs/common/src/auth/models/domain/user-decryption-options/user-decryption-options.ts` either.

2024-01-10 20:13 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/abstractions/user-decryption-options.service.abstraction.ts
Thank you for the docs!

2024-01-10 20:30 UTC, JaredSnider-Bitwarden commented on libs/common/src/state-migrations/migrations/10-move-user-decryption-options-to-state-provider.spec.ts
> +      decryptionOptions: {
Question: is it worth testing the scenario in which the account doesn't have `decryptionOptions` defined (the mysterious state we've seen with the sync issue and can't reproduce)?

2024-01-10 21:45 UTC, justindbaur reviewed
Just added a couple comments to existing threads. Just a couple minor things and then this is good to from platforms perspective.

2024-01-10 21:45 UTC, justindbaur commented on libs/common/src/state-migrations/migrations/10-move-user-decryption-options-to-state-provider.ts
> +      await helper.setToUser(userId, USER_DECRYPTION_OPTIONS, value ?? {});
Your state, your rules. You still won't be able to assume that it can never be null when getting this state. Because a brand new install won't run these migrations and you will be able to receive null back. 

But personally, this does feel wrong. According to the type `UserDecryptionOptions` `hasMasterPassword` is a required property but you are creating an object where it's not there.

2024-01-10 21:45 UTC, justindbaur commented on libs/common/src/state-migrations/migrations/10-move-user-decryption-options-to-state-provider.spec.ts
> +      decryptionOptions: {
This is a good idea, I try to be as defensive as possible in migrations and I think the actual migration code is defensive in this regard but might as well have a test asserting it too.

2024-01-12 14:48 UTC, jlf0dev commented on libs/common/src/auth/services/user-verification/user-verification.service.ts
> -    return !(await this.stateService.getUsesKeyConnector({ userId }));
This is a pretty self-contained ticket so I was ok removing it in this PR. I was also going to require testing key connector for this ticket anyways so it shouldn't expand the scope too much. 

We're past the backwards compatibility support window so all self hosted instances should be returning user decryption options at this point. That being said, please feel free to disagree and I can throw it back in there.

2024-01-12 14:50 UTC, jlf0dev commented on libs/common/src/auth/services/user-verification/user-verification.service.ts
> -    return !(await this.stateService.getUsesKeyConnector({ userId }));
I'm also planning to follow-up with a PR to remove the other code you mentioned.

2024-01-12 16:01 UTC, JaredSnider-Bitwarden commented on libs/common/src/state-migrations/migrations/10-move-user-decryption-options-to-state-provider.ts
> +      await helper.setToUser(userId, USER_DECRYPTION_OPTIONS, value ?? {});
Per discussion with @jlf0dev , he is going to make user decryption options null, and we are not going to initialize `hasMasterPassword` until we get a valid value from the server - assuming nothing about whether the user has a MP or not.

2024-01-12 16:09 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/device-trust-crypto.service.implementation.ts
> +    this.supportsDeviceTrust$ = this.userDecryptionOptionsService.userDecryptionOptions$.pipe(
Leaving this for now after discussion as we might decompose user decryptions options service in future and this maintains the current implementation pattern.

2024-01-16 13:53 UTC, jlf0dev commented on libs/common/src/state-migrations/migrations/10-move-user-decryption-options-to-state-provider.spec.ts
> +      decryptionOptions: {
I think this is tested with the third account right?

2024-01-16 14:19 UTC, shane-melton approved these changes
Vault changes look good to go!

2024-01-16 15:15 UTC, JaredSnider-Bitwarden commented on libs/common/src/state-migrations/migrations/10-move-user-decryption-options-to-state-provider.spec.ts
> +      decryptionOptions: {
Ah, yes. I missed that there was a 3rd account scenario tested with the complete absence of the account. I expected to see an account with just missing user decryption options, but I think that test is valid as well! Thank you!

2024-02-13 18:16 UTC, JaredSnider-Bitwarden reviewed
Holding off on finishing this review per discussion (awaiting state lifecycle changes). A few comments below:

2024-02-13 18:16 UTC, JaredSnider-Bitwarden commented on libs/auth/src/common/abstractions/user-decryption-options.service.abstraction.ts
> +  abstract userDecryptionOptionsById$(userId: string): Observable<UserDecryptionOptions>;
⚠️ should we mark the other properties as abstract as well?

2024-03-12 12:21 UTC, jlf0dev commented on libs/auth/src/common/models/domain/user-decryption-options.ts
> +  // }
I went ahead and removed these properties for now. We can add them back in later if needed.

2024-03-12 12:21 UTC, jlf0dev commented on libs/auth/src/common/abstractions/user-decryption-options.service.abstraction.ts
> +  abstract userDecryptionOptionsById$(userId: string): Observable<UserDecryptionOptions>;
Done!

2024-03-12 12:21 UTC, jlf0dev commented on libs/common/tsconfig.json
> +    "../auth/src/common/models/domain/user-decryption-options.ts"
Good catch, this wasn't supposed to be part of the PR.

2024-03-18 22:07 UTC, JaredSnider-Bitwarden requested changes
Really nice work! A few smaller issues and some questions below 👇

2024-03-18 22:07 UTC, JaredSnider-Bitwarden commented on libs/common/src/state-migrations/migrations/40-move-user-decryption-options-to-state-provider.ts
> +      await helper.set(userId, account);
💡  Justin showed me a good pattern to avoid setting non-existent data that you might want to use here to avoid potentially unnecessary writes (although all users probably will have user decryption options):  

```TypeScript
migrateAccount(...) {
     const value = account?.decryptionOptions;
      if (value != null) {
        await helper.setToUser(userId, USER_DECRYPTION_OPTIONS, value);
        delete account.decryptionOptions;
        await helper.set(userId, account);
      }
```

2024-03-18 22:07 UTC, JaredSnider-Bitwarden commented on libs/common/src/state-migrations/migrations/40-move-user-decryption-options-to-state-provider.spec.ts
> +    it("should set decryptionOptions provider value for each account", async () => {
Nit:  is `provider` copy pasta?

2024-03-18 22:08 UTC, JaredSnider-Bitwarden commented on libs/auth/src/common/services/user-decryption-options/user-decryption-options.service.ts
💡 should we have a small test file for this service?

2024-03-19 13:24 UTC, jlf0dev commented on libs/common/src/platform/state/state-definitions.ts
> +export const USER_DECRYPTION_OPTIONS_DISK = new StateDefinition("userDecryptionOptions", "disk");
This was a while ago, but I think my thoughts were that web local is available after the tab closes. We don't persist sessions for web so I couldn't see a reason to maintain it if the user didn't logout and just closed the tab.

2024-03-19 13:26 UTC, jlf0dev commented on libs/angular/src/services/jslib-services.module.ts
> +    useExisting: UserDecryptionOptionsServiceAbstraction,
I'm glad you caught that, I guess our type safety can't catch that 😁

2024-03-19 13:28 UTC, jlf0dev commented on apps/browser/src/auth/background/service-factories/device-trust-crypto-service.factory.ts
>  export type DeviceTrustCryptoServiceInitOptions = DeviceTrustCryptoServiceFactoryOptions &
Fixed!

2024-03-19 13:28 UTC, jlf0dev commented on libs/auth/src/common/abstractions/user-decryption-options.service.abstraction.ts
> +   * @remark This only checks what is stored on the server, not the local state.
This was meant to convey that it doesn't indicate if the user logged in with master password. Updated to clarify

2024-03-19 13:28 UTC, jlf0dev commented on apps/web/src/app/vault/individual-vault/vault-filter/components/organization-options.component.ts
> +    private UserDecryptionOptionsService: UserDecryptionOptionsServiceAbstraction,
Done!

2024-03-19 13:37 UTC, jlf0dev commented on libs/common/src/state-migrations/migrations/40-move-user-decryption-options-to-state-provider.ts
> +      await helper.set(userId, account);
Updated!

2024-03-19 13:38 UTC, jlf0dev commented on libs/common/src/state-migrations/migrations/40-move-user-decryption-options-to-state-provider.spec.ts
> +    it("should set decryptionOptions provider value for each account", async () => {
Like state provider value?

2024-03-19 13:55 UTC, jlf0dev commented on libs/auth/src/common/services/user-decryption-options/user-decryption-options.service.ts
Added!

2024-03-19 14:20 UTC, JaredSnider-Bitwarden commented on libs/auth/src/common/abstractions/user-decryption-options.service.abstraction.ts
> +   * @remark This only checks what is stored on the server, not the local state.
The clarified remark is great! Thank you!

2024-03-19 17:14 UTC, shane-melton reviewed
Vault changes look good, but I did have one question related to the sync service.

2024-03-19 17:14 UTC, shane-melton commented on libs/common/src/vault/services/sync/sync.service.ts
> -      return;
question:  Are we expecting `userDecryptionOptions` to ever equal null/undefined? I see we still have the check, but we're no longer returning early. Without the return, we're still going to throw an error below when we attempt to access `userDecryptionOptions.trustedDeviceOption` and it will kill the sync in progress (and likely cause infinitely repeating background sync attempts).

2024-03-19 17:40 UTC, shane-melton submitted a review, later dismissed

2024-03-19 17:41 UTC, shane-melton commented on libs/common/src/vault/services/sync/sync.service.ts
> -      return;
Chatted about this in another channel -- The change is intentional and sync is expected to fail should `userDecryptionOptions == null`

2024-03-19 19:11 UTC, JaredSnider-Bitwarden submitted a review, later dismissed
Awesome work! 🚀

2024-03-20 21:25 UTC, justindbaur submitted a review, later dismissed

2024-03-20 21:25 UTC, justindbaur commented on libs/common/src/platform/models/domain/account.ts
You deleted so much 😍

2024-03-20 21:42 UTC, shane-melton commented on libs/common/src/state-migrations/migrations/44-move-user-decryption-options-to-state-provider.spec.ts
>        helper = mockMigrationHelper(rollbackJSON(), 43);
question: I think we also need to update this migration number?

2024-03-20 21:45 UTC, jlf0dev commented on libs/common/src/state-migrations/migrations/44-move-user-decryption-options-to-state-provider.spec.ts
>        helper = mockMigrationHelper(rollbackJSON(), 43);
Good catch, updated

2024-03-20 21:52 UTC, shane-melton approved these changes

2024-03-20 21:53 UTC, justindbaur approved these changes

2024-03-20 21:59 UTC, JaredSnider-Bitwarden approved these changes

2024-03-21 00:33 UTC, merged