Combined State
bitwarden/clients pull request #7383
Opened 2023-12-28 15:26 UTC by justindbaur

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Add a `combinedState$: Observable<readonly [userId: UserId, state: T]>` to both of the `UserState` interfaces. 

To make this happen I reworked the guts of `SingleUserState` and `ActiveUserState` quite a bit to more fully leverage built in operators from `rxjs`. The core one is using `share` backed by a `ReplaySubject` and giving it an `timer` for unsubscribing from it's source when no one is subscribed to it.

## Code changes

- **DI:** All DI changes were removing the dependence on `EncryptService`. 
- **default-derived-state.ts:** Deleted, no longer used in this way and a full replacement of it's duties are coming later. 
- **spec files**: All test changes should be pretty minor, mostly reworking how internal details are acquired. 
- **user-state.ts:** Remove `createDerived` method, along with `getFromState` something we had wanted to remove for a while.
- The changes to `DefaultSingleUserState` and `DefaultActiveUserState` are best viewed from comments in the code. 

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-12-29 14:22 UTC, MGibson1 requested changes
I have a few simplification and test requests, but this does look much better!

Do you plan on a separate PR for global as well?

2023-12-29 14:22 UTC, MGibson1 commented on libs/common/src/platform/state/implementations/default-active-user-state.ts
> +      // Use withLatestFrom so that we do NOT emit when activeUserId changes because that
Just filter for matching keys here, we don't need to do work and complicate our switchmap for random updates from the storage location

2023-12-29 14:22 UTC, MGibson1 commented on libs/common/src/platform/state/implementations/default-active-user-state.ts
> +          return FAKE;
similarly, I'd rather filter for non-null users than complicate the switchmap

2023-12-29 14:22 UTC, MGibson1 commented on libs/common/src/platform/state/implementations/default-active-user-state.ts
> +        // if ever, called.
```suggestion
        // and just emit null. 
```

I don't think the frequency is relevant

2023-12-29 17:14 UTC, MGibson1 commented on libs/common/src/platform/state/implementations/default-single-user-state.ts
> +          const newSubject = new ReplaySubject<T>(1);
Just realized this isn't completed on refcount zero. We should either reuse this replay subject, or find a way to complete it

2024-01-01 21:00 UTC, justindbaur commented on libs/common/src/platform/state/implementations/default-active-user-state.spec.ts
> +    expect(emissions).toHaveLength(3);
This was from me debugging an error. I find the error message from this a whole lot more helpful than the diff view but I can remove it now.

2024-01-01 21:02 UTC, justindbaur commented on libs/common/src/platform/state/implementations/default-active-user-state.ts
> +      // Use withLatestFrom so that we do NOT emit when activeUserId changes because that
We don't have the full key until we also have the user id that's why I do the filtering inside the `switchMap`. I can do a normal `map` that takes the userId and creates the formatted key then do a `filter` and then do a `switchMap` though.

2024-01-01 21:16 UTC, justindbaur commented on libs/common/src/platform/state/implementations/default-active-user-state.ts
> +      // Use withLatestFrom so that we do NOT emit when activeUserId changes because that
I reworked it a bit so it's filtered outside the switchMap and I got rid of the filter for undefined. Let me know what you think.

2024-01-01 21:20 UTC, justindbaur commented on libs/common/src/platform/state/implementations/default-single-user-state.ts
> +          const newSubject = new ReplaySubject<T>(1);
I don't think we want to both the default functions using `share` don't do anything like that. They intentionally null it out to fully transition it back into a "cold" state. We only track it for testing purposes. Doing anything more than observing facts about it would be wrong I think. 

https://github.com/ReactiveX/rxjs/blob/6c2c59f9ee1101e43c9d4cc02276da78bb38cdd6/packages/rxjs/src/internal/operators/share.ts#L140C28-L140C28

https://github.com/ReactiveX/rxjs/blob/6c2c59f9ee1101e43c9d4cc02276da78bb38cdd6/packages/rxjs/src/internal/operators/shareReplay.ts#L167

2024-01-03 13:45 UTC, MGibson1 commented on libs/common/src/platform/state/implementations/default-single-user-state.ts
> +          const newSubject = new ReplaySubject<T>(1);
It looks like they're relying on their ref counts matching whatever the ref count the garbage collector detects to be equal. That's probably true, but I see no reason to depend on it when we already have an observable that is specifying when (and if) to cleanup and an handle to our ref counted subject. All that's required is changing the `resetOnRefCountZero` observable slightly from

```typescript
resetOnRefCountZero: () => timer(this.keyDefinition.cleanupDelayMs),
```
to
```typescript
resetOnRefCountZero: () => timer(this.keyDefinition.cleanupDelayMs).pipe(tap(() => this.replaySubject.complete()),
```

My bet is they don't do this because they lack a reference to the connector subject external to the share context.

2024-01-03 13:48 UTC, MGibson1 requested changes
replied to comment

2024-01-03 18:23 UTC, justindbaur commented on libs/common/src/platform/state/implementations/default-single-user-state.ts
> +          const newSubject = new ReplaySubject<T>(1);
I decided to refactor out even saving a reference at all. For most of the tests we can instead detect that we are no longer subscribed to storage updates/active user changes.  We do fully lose the ability to detect when we are in the "cooling down" phase but I decided to test that differently. I tested that by just making sure it doesn't go to the storage service for that data again if it's been unsubscribed from but shouldn't have cooled completely yet.

2024-01-04 13:27 UTC, MGibson1 commented on libs/common/src/platform/state/implementations/default-active-user-state.ts
> +      // Use withLatestFrom so that we do NOT emit when activeUserId changes because that
👍 this is what I was thinking

2024-01-04 13:29 UTC, MGibson1 approved these changes

2024-01-04 21:18 UTC, MGibson1 approved these changes

2024-01-04 21:30 UTC, merged