[PM-5455] Listen for Finish Message
bitwarden/clients pull request #7387
Opened 2023-12-28 21:47 UTC by justindbaur

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

The `Not you` button on this screen initiates a logout for the current account. If you have an additional account this will mean we switch accounts to the next account. We need to listen for that message and route them appropriately. 

## Code changes

- **apps/browser/src/auth/popup/utils/post-logout-message-listener.ts:** Create a helper listener for listening to post logout messages, this is because I believe this exact logic will be reused to fix a different bug. 
- **apps/browser/src/auth/popup/login-decryption-options/login-decryption-options.component.ts:** Override the `super.logOut` method by starting to listen to messages, doing the super implementation, then waiting until that message comes or we timeout. If the `switchAccountMessage` was sent, then route them to home.

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2023-12-28 22:51 UTC, ike-kottlowski approved these changes
I don't want to hold this up so I'm approving. 

However, ⛏️ I would like to have seen some tests for `login-decryption-options.component.ts`. I know testing a component has code smells but there is some logic (however minor) in the `component.ts`. 

I'm not sure how to test the `post-logout-message-listener.ts` but I feel like it should also have some sort of test to make sure it is throwing the error if neither of the accepted messages are sent.

2023-12-29 11:34 UTC, MGibson1 requested changes

2023-12-29 11:34 UTC, MGibson1 commented on apps/browser/src/auth/popup/utils/post-logout-message-listener.ts
> +export const postLogoutMessageListener$ = fromChromeEvent<
I'm a little bit worried that this pattern is spreading to more components. Ideally we don't want multiple distributed listeners like this since it increases memory footprint and is generally slow.

Is there another approach more in line with how we handle it today that you rejected?

2023-12-29 13:15 UTC, MGibson1 commented on apps/browser/src/auth/popup/utils/post-logout-message-listener.ts
> +export const postLogoutMessageListener$ = fromChromeEvent<
It turns out that navigating to `/` in app.component account switch finished listener fixes both this and PM-5453.

It's possible that's racy, though, since the account switch service also navigates. These routing reqs are starting to be previous route-dependent, which is inconsistent with our current way of handling them.

2023-12-29 13:27 UTC, justindbaur commented on apps/browser/src/auth/popup/utils/post-logout-message-listener.ts
> +export const postLogoutMessageListener$ = fromChromeEvent<
This listener isn't actually added until `firstValueFrom` or any subscribe is called on this. Both usages are pretty short lived so I'm not worried about the added memory footprint here. 

But yes, my alternative was navigating on `switchAccountFinish` in app.component but my understanding was this bug was already fixed previously and then then reintroduced after fixing something else. So my thinking was to make the fix more locally to these components to hopefully avoid unintended consequences. 

I do personally prefer that the routing is done very near the component instead of it just being a magical side effect of a message I sent.

2024-01-01 19:38 UTC, MGibson1 commented on apps/browser/src/auth/popup/utils/post-logout-message-listener.ts
> +export const postLogoutMessageListener$ = fromChromeEvent<
Ok, but this util is already kind of disassociated from the component, I don't think it's any better than expecting messages to produce consistent routing.

2024-01-01 20:58 UTC, justindbaur commented on apps/browser/src/auth/popup/utils/post-logout-message-listener.ts
> +export const postLogoutMessageListener$ = fromChromeEvent<
It is disassociated from the component, it relates directly to the initial message. I'm just trying to solve this in a way that has a low probability that it reintroduces other bugs. I don't love this fix in any way.

2024-01-02 15:05 UTC, merged