[AC-1492] Split export service
bitwarden/clients pull request #7462
Opened 2024-01-05 17:51 UTC by aj-rosado

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Export service is getting too big, we are splitting it into two different services to improve readibility and reusability preparing to add more logic int this services.

## Code changes

- **org-vault-export.service.ts:** Service with org related export methods
- **base-vault-export.service.ts:** Service with the export methods that are needed both for org and vault export
- **vault-export.service.ts:** Removed the org export logic and the logic necessary both on vault and org
- **org-vault-export.component.ts:** Swapped the `ExportService` with the new `OrgExportService`

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-01-08 20:51 UTC, r-tome approved these changes
LGTM!

2024-01-08 21:27 UTC, djsmith85 requested changes
Thank you for this refactor. I know it's slowing down progress on the flexible collection export, but I think this is needed to split up some of the concerns.

2024-01-08 21:27 UTC, djsmith85 commented on libs/exporter/src/vault-export/services/individual-vault-export.service.ts
> +    if (format === "csv") {
Please extract a private method for the csv export. This will reduce nesting with the below json export.

2024-01-08 21:27 UTC, djsmith85 commented on libs/exporter/src/vault-export/services/org-vault-export.service.abstraction.ts
> +  getOrganizationExport: (organizationId: string, format?: ExportFormat) => Promise<string>;
OrganizationId should not be optional on a organizational export

2024-01-08 21:27 UTC, djsmith85 commented on libs/exporter/src/vault-export/services/individual-vault-export.service.abstraction.ts
> +  getExport: (format?: ExportFormat) => Promise<string>;
The format should not be optional. If the format can be omitted like in the CLI, then it should be responsible of setting that default.

2024-01-08 21:27 UTC, djsmith85 commented on libs/exporter/src/vault-export/services/org-vault-export.service.ts
> +    } else {
⛏️  This else it not needed

2024-01-08 21:27 UTC, djsmith85 commented on libs/exporter/src/vault-export/services/org-vault-export.service.ts
> +    if (format === "csv") {
Please extract a private method for the csv export. This will reduce nesting with the below json export.

2024-01-08 21:28 UTC, djsmith85 commented
Thoughs on slimming down the exposed interface on vault-export? The idea being it encapsulates the routing code (individiual/organization, with/without password) so the component using it, does not need to do it again. See for example the export.command.

2024-01-11 12:02 UTC, djsmith85 requested changes
Just some smaller items and then this should be good to go.

2024-01-11 16:04 UTC, djsmith85 submitted a review, later dismissed
Thanks a bunch for this refactor 👍 Changes are looking good

2024-01-11 16:22 UTC, djsmith85 approved these changes

2024-01-11 16:45 UTC, r-tome submitted a review, later dismissed

2024-01-26 18:32 UTC, djsmith85 approved these changes

2024-01-29 09:38 UTC, merged