[PM-5364] Create SSO Login Service and add state ownership
bitwarden/clients pull request #7485
Opened 2024-01-09 14:42 UTC by jlf0dev

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Creates a SSO Login Service for holding state during login for sso related purposes. This service doesn't contain any logic yet as that would expand testing, and only tries to make a minimal amount of changes.

There are no migrations for the new state as they are only used as a cache during a sso login flow
## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-01-10 12:35 UTC, justindbaur submitted a review, later dismissed
There are no migrations for this disk state because this data is expected to be cleared after a successful login and it's incredibly unlikely/not worth the migration that someone updates the extension halfway through the SSO process right?

If that is the case this gets approval from platform. 

Very nice documentation!

2024-01-10 16:04 UTC, JaredSnider-Bitwarden reviewed
Excellent work on this! Just a few questions below 👇

2024-01-10 18:04 UTC, jlf0dev commented on libs/angular/src/auth/components/base-login-decryption-options.component.ts
>    async loadNewUserData() {
Yes, ran through the TDE user autoprovision flow to make sure the decryption options works correctly.

2024-01-10 18:04 UTC, jlf0dev commented on libs/common/src/auth/abstractions/sso-login.service.abstraction.ts
> +  getOrganizationIdentifier: () => Promise<string>;
Good call, updated

2024-01-10 18:08 UTC, JaredSnider-Bitwarden approved these changes
LGTM!

2024-01-10 19:38 UTC, JaredSnider-Bitwarden approved these changes
Nice work! Tests passing!

2024-01-10 19:57 UTC, justindbaur submitted a review, later dismissed

2024-01-16 14:22 UTC, shane-melton submitted a review, later dismissed
Changes owned by Vault look good! 

With that said, should Vault even own the `link-sso.directive`?

2024-02-07 15:16 UTC, jlf0dev commented
@shane-melton @justindbaur @JaredSnider-Bitwarden Had to resolve some conflicts, just need a review for merging. Thanks!

2024-02-07 16:34 UTC, JaredSnider-Bitwarden approved these changes

2024-02-07 17:30 UTC, shane-melton approved these changes

2024-02-08 17:04 UTC, justindbaur requested changes

2024-02-08 17:40 UTC, jlf0dev commented on libs/common/src/platform/services/state.service.ts
> -  }
Our sso flow currently takes you back to bitwarden in the same tab, so I can't think of any reason to use local storage, can you? This has also been through QA as well.

2024-02-08 17:42 UTC, justindbaur commented on libs/common/src/platform/services/state.service.ts
> -  }
That's fine with me then, just making sure.

2024-02-08 17:42 UTC, justindbaur approved these changes

2024-02-08 17:44 UTC, merged