emergency access tailwind migration POC
bitwarden/clients pull request #7492
Opened 2024-01-09 19:25 UTC by vinith-kovan

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ X ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-01-09 19:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitwarden/clients?pullRequest=7492) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bitwarden/clients?pullRequest=7492) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitwarden/clients?pullRequest=7492) it.</sub>

2024-01-12 04:10 UTC, willmartian requested changes
Hey @vinith-kovan, thanks for the PR!

I left some comments below. Many of them are general and should be followed wherever applicable. Also, please fill out the PR description (including screenshots/recording of before and after) to aid those reviewing the PR. 

Please let me know if you have any clarifying questions, either here in the PR or on Slack.

2024-01-12 04:10 UTC, willmartian commented on apps/web/src/app/auth/settings/emergency-access/emergency-access.component.ts
> +  };
Rather than passing callback methods to the dialog's data (also done elsewhere in this PR), we should instead make use of the dialog's return value. 

```ts
const dialogRef = openEmergencyAccessAddEditDialog(this.dialogService, {
      data: {
        name: this.userNamePipe.transform(details),
        emergencyAccessId: details?.id,
        readOnly: !this.canAccessPremium,
      },
    });
    
const result = await lastValueFrom(dialogRef.closed);

if (result === "saved") { ... }
if (result === "deleted") { ... }
```

This more closely matches what we are doing elsewhere in the codebase, and lets us call `dialogRef.close()` instead of `this.dialogService.closeAll()`, which is a change in functionality.

2024-01-17 17:58 UTC, willmartian requested changes

2024-01-17 17:58 UTC, willmartian commented on apps/web/src/app/auth/settings/emergency-access/view/emergency-access-view.component.html
> +            <div *ngIf="c.hasAttachments">
I don't believe we need the custom css classes here.

2024-01-17 17:58 UTC, willmartian commented on apps/web/src/app/auth/settings/emergency-access/view/emergency-access-view.component.html
> +                <button type="button" bitMenuItem appStopClick (click)="viewAttachments(c)">
The template reference variable has a confusing name, as it is on the menu and not the button itself. I would consider renaming to:

`#dropdownMenuButton` --> `#optionsMenu` 

(or something similar)

2024-01-17 17:58 UTC, willmartian commented on apps/web/src/app/auth/settings/emergency-access/takeover/emergency-access-takeover.component.html
> +            />
We should use `bitPasswordInputToggle` on inputs of `type="password"`

2024-01-17 17:58 UTC, willmartian commented on apps/web/src/app/auth/settings/emergency-access/takeover/emergency-access-takeover.component.ts
> +    @Inject(DIALOG_DATA) protected params: any,
`params` should be typed with `EmergencyAccessTakeoverParams`

2024-01-17 17:58 UTC, willmartian commented on apps/web/src/app/auth/settings/emergency-access/takeover/emergency-access-takeover.component.ts
> +   * Strongly typed helper to open a UserDialog
Update comment to reference correct component name

2024-01-17 17:58 UTC, willmartian commented on apps/web/src/app/auth/settings/emergency-access/emergency-access-add-edit.component.ts
> +   * Strongly typed helper to open a UserDialog
Update comment to reference correct component name

2024-01-22 15:54 UTC, willmartian requested changes
Thanks for your work on this @vinith-kovan. After you wrap up these review comments, could you attach new screenshots to the PR description? Then we can move the PR out of draft and into design review and codeowner review.

2024-01-22 15:54 UTC, willmartian commented on apps/web/src/app/auth/settings/emergency-access/emergency-access-add-edit.component.html
> +        <a
`bitDialogTitle` internally creates an `h1` element, meaning the next semantic element should be an `h2` element. However, _visually_, we want to use the `bitTypography` styles of `h3` inside of dialogs. So we should use the following combination:

`<h2 bitTypography="h3">` 

(This is unclear and needs to be documented more thoroughly.)

2024-01-22 15:54 UTC, willmartian commented on apps/web/src/app/auth/settings/emergency-access/emergency-access-add-edit.component.html
> +        appA11yTitle="{{ 'delete' | i18n }}"
We don't need to set `title` if we set `appA11yTitle`. (Furthermore, `title` isn't localized here. Be careful about introducing unlocalized text.)

2024-01-22 15:54 UTC, willmartian commented on apps/web/src/app/auth/settings/emergency-access/emergency-access.component.html
> +  <h1 bitTypography="h1">{{ "emergencyAccess" | i18n }}</h1>
For typography and headings, default to using bare CL components instead of recreating deprecated styles with Tailwind. 

We can remove this container div and just use the `h1` element with `bitTypography`.

2024-01-22 15:54 UTC, willmartian commented on apps/web/src/app/auth/settings/emergency-access/emergency-access.component.html
> +  <h2 bitTypography="h2">
For typography and headings, default to using bare CL components instead of recreating deprecated styles with Tailwind. 

We can remove this container div and just use the `h2` element with `bitTypography`.

2024-01-22 15:54 UTC, willmartian commented on apps/web/src/app/auth/settings/emergency-access/emergency-access.component.html
> +  <h2 bitTypography="h2">{{ "designatedEmergencyContacts" | i18n }}</h2>
For typography and headings, default to using bare CL components instead of recreating deprecated styles with Tailwind. 

We can remove this container div and just use the `h2` element with `bitTypography`.

2024-01-22 15:54 UTC, willmartian commented on apps/web/src/app/auth/settings/emergency-access/view/emergency-access-view.component.html
> +  <h1 bitTypography="h1">{{ "vault" | i18n }}</h1>
For typography and headings, default to using bare CL components instead of recreating deprecated styles with Tailwind. 

We can remove this container div and just use the `h1` element with `bitTypography`.

2024-01-22 15:54 UTC, willmartian commented on apps/web/src/app/auth/settings/emergency-access/emergency-access.component.html
> +      <td bitCell class="tw-p-3 tw-h-12 tw-max-w-20 tw-text-right tw-w-20">
I don't think these replacement classes for `table-list-options` are necessary.

2024-01-22 15:54 UTC, willmartian commented on apps/web/src/app/auth/settings/emergency-access/emergency-access.component.html
> +      <td bitCell class="tw-p-3 tw-h-12 tw-text-right tw-w-20">
I don't think these replacement classes for `table-list-options` are necessary.

2024-01-22 15:54 UTC, willmartian commented on apps/web/src/app/auth/settings/emergency-access/view/emergency-access-view.component.html
> +          <td bitCell class="tw-max-w-11 tw-text-center tw-w-11">
We probably don't need these replacement classes for `table-list-icon`. It looks like elsewhere we only use `class="tw-min-w-fit"`

2024-01-22 16:26 UTC, vinith-kovan commented on apps/web/src/app/auth/settings/emergency-access/emergency-access.component.html
> +  <h1 bitTypography="h1">{{ "emergencyAccess" | i18n }}</h1>
![image](https://github.com/bitwarden/clients/assets/156108204/60fb2c71-db33-4b26-bdaa-ee08fb1f3147)
![image](https://github.com/bitwarden/clients/assets/156108204/0052c236-12eb-4b98-b6b8-4e3d1086cee3)

if i remove this tailwind class, those underlines will be removed. Is that okay?

2024-01-22 16:32 UTC, willmartian commented on apps/web/src/app/auth/settings/emergency-access/emergency-access.component.html
> +  <h1 bitTypography="h1">{{ "emergencyAccess" | i18n }}</h1>
Yes. (And thanks for the screenshot comparison.)

The underlined headers are not part of the new component library design spec and can be left out generally.

2024-01-22 16:32 UTC, vinith-kovan commented on apps/web/src/app/auth/settings/emergency-access/view/emergency-access-view.component.html
> +          <td bitCell class="tw-max-w-11 tw-text-center tw-w-11">
![image](https://github.com/bitwarden/clients/assets/156108204/b3f6102a-4342-4a44-b3d4-00f73c43f083)
![image](https://github.com/bitwarden/clients/assets/156108204/ff2663db-c1d7-4eb0-97f0-7664b9f3e032)

if we remove this class we are facing this kind of spacing issues between avatar and text

2024-01-22 17:57 UTC, vinith-kovan commented on apps/web/src/app/auth/settings/emergency-access/emergency-access.component.html
> +  <h2 bitTypography="h2">
@willmartian  If i remove this container div add emeregency contact button will come down, because is handling flex property. Instead can i remove border classes only ?

2024-01-22 18:22 UTC, willmartian commented on apps/web/src/app/auth/settings/emergency-access/emergency-access.component.html
> +  <h2 bitTypography="h2">
@vinith-kovan Yes, that is fine

2024-01-22 19:20 UTC, willmartian commented on apps/web/src/app/auth/settings/emergency-access/view/emergency-access-view.component.html
> +          <td bitCell class="tw-max-w-11 tw-text-center tw-w-11">
Place `tw-max-w-full` on the second cell. That will force the first cell to shrink to its content width and is preferred over hardcoding the first cell's width to a specific amount.

2024-01-23 14:46 UTC, willmartian submitted a review, later dismissed
Changes look good to me 👍  

Moving this to design and codeowner review.

2024-01-23 20:06 UTC, danielleflinn requested changes
Please address the small UI tweaks noted and let me or @willmartian know if you have additional questions.

2024-01-23 20:06 UTC, danielleflinn commented on apps/web/src/app/auth/settings/emergency-access/takeover/emergency-access-takeover.component.html
> +          </bit-form-field>
Let's remove the spacing below the form here so the strength indicator is grouped with the password field.

2024-01-23 20:06 UTC, danielleflinn commented on apps/web/src/app/auth/settings/emergency-access/emergency-access-add-edit.component.html
> +      <h2 bitTypography="h3">
Let's update this radio group to use the the [radio group](https://components.bitwarden.com/?path=/story/component-library-form-radio-button--block) component. "User access" would be the label for the radio group  and the help icon should appear at the end of the label. This improves the accessibility of the implementation. 
 
 Note: we have an internal bug to fix the label size for the radio group component.

2024-01-24 00:21 UTC, willmartian commented on apps/web/src/app/auth/settings/emergency-access/view/emergency-access-view.component.html
> +                bitIconButton="bwi-cog"
Icon buttons using `bwi-cog` should be updated to use `bwi-ellipsis-v` when migrating pages. I will add this to the migration docs.

2024-01-24 00:38 UTC, danielleflinn commented on apps/web/src/app/auth/settings/emergency-access/view/emergency-access-view.component.html
> +                bitIconButton="bwi-cog"
Good catch; we should also be using the[ iconButton](https://components.bitwarden.com/?path=/story/component-library-icon-button--main) component here with the Main styling

2024-01-24 19:32 UTC, audrey-jensen requested changes
* ❓ - questions
* ⛏️ - nitpick changes
* 🎨 - suggestions / improvements
* ⚠️  - concerns needing attention
* 📝 - notes
* 💭 - idle thoughts
* 🤔 - open inquiry that's not necessarily an issue
* 👍🏻 - great changes

2024-01-24 19:32 UTC, audrey-jensen commented on apps/web/src/app/auth/settings/emergency-access/view/emergency-access-view.component.html
> +        <tr bitRow *ngFor="let c of ciphers">
⛏️ I'd use a longer name than `c` here. The code is fairly verbose, and it's easy to lose track of where it's used.

2024-01-24 19:32 UTC, audrey-jensen commented on apps/web/src/app/auth/settings/emergency-access/view/emergency-access-view.component.html
> +                <button type="button" bitMenuItem appStopClick (click)="viewAttachments(c)">
🤔 It might be worthwhile to introduce greater consistency in attribute order. Putting the declarations in between quoted attributes looks incorrect. I'd either put them all at the beginning or all at the end. If it's the linter doing this, though, then just ignore me.

2024-01-24 21:39 UTC, audrey-jensen commented on apps/web/src/app/auth/settings/emergency-access/emergency-access.component.html
> +<h2 bitTypography="h2">{{ "designatedEmergencyContacts" | i18n }}</h2>
@danielleflinn - is there a way the spacing issues could be bundled into a `bit-section` and `bit-heading` component?

2024-01-24 22:16 UTC, danielleflinn commented on apps/web/src/app/auth/settings/emergency-access/emergency-access.component.html
> +<h2 bitTypography="h2">{{ "designatedEmergencyContacts" | i18n }}</h2>
Yes the CL team has plans to add those but we don't want to hold up this PR waiting for the `bit-section` component to be implemented.

2024-01-25 21:05 UTC, willmartian commented on apps/web/src/app/auth/settings/emergency-access/view/emergency-access-view.component.html
> +                <button type="button" bitMenuItem appStopClick (click)="viewAttachments(c)">
Agreed, perhaps we should turn on a [lint rule](https://github.com/angular-eslint/angular-eslint/blob/main/packages/eslint-plugin-template/docs/rules/attributes-order.md) for this. I posed a question in #code for this.

2024-01-25 21:08 UTC, willmartian commented on apps/web/src/app/auth/settings/emergency-access/emergency-access.component.html
> +        ></button>
I don't believe so, only [void elements](https://html.spec.whatwg.org/multipage/syntax.html#elements-2) are permitted to self close.

2024-01-25 21:16 UTC, willmartian commented on apps/web/src/app/auth/settings/emergency-access/confirm/emergency-access-confirm.component.ts
> +  submit = async () => {
This is an existing pattern, which is [documented](https://components.bitwarden.com/?path=/docs/component-library-async-actions-standalone-documentation--docs#1-add-a-handler-to-your-component) within Storybook for form handlers that are passed to the `[bitAction]` and `[bitSubmit]` directives. 

Outside of CL specifics, it is a generally necessary to use arrow functions (or call `.bind`) when passing around functions as values, to properly preserve the `this` context.

2024-01-25 22:18 UTC, willmartian commented on apps/web/src/app/auth/settings/emergency-access/confirm/emergency-access-confirm.component.ts
> +export enum EmergencyAccessConfirmResultType {
@audrey-jensen 

>❓ Is an enum necessary here?

I also prefer types over enums. However, we use a mix of both in the codebase at this time. 

> ⛏️ The name is a little long. 

We have been following the following naming pattern for dialog components and associated helper types:
- Dialog data helper type: "EmergencyAccessConfirm**DialogData**"
- Dialog result helper type: "EmergencyAccessConfirm**DialogResult**"

If we want to change what the recommended pattern is, I'm all ears, but for the purposes of _this_ PR I think we should stick to the extant pattern. 

> 🎨 I also wonder what the purpose of this type is. Why doesn't it have more than one value?

Yes, at first glance it is weird that the dialog only has a single outcome represented in the return type, when in reality a user can confirm _or cancel_ the dialog. However, I think it makes a bit more sense when the usage is taken into account. 

The return value of a dialog is consumed through the `DialogRef.closed` observable, which is typed as the following:

`readonly closed: Observable<R | undefined>;`

 The type parameter `R` corresponds with the return value type. So if our return value type is defined as `"confirmed"`, we get a `closed` stream of `Observable<"confirmed" | undefined>`, which captures the binary outcome. So in summary, we are only typing the positive actions, and the negative actions (closing via `esc`, clicking the backdrop, or clicking a cancel button with `bitDialogClose` [no bound value]) are captured by `undefined`. 
 
 We inherit this behavior from the Angular CDK. I am happy to discuss and improvements the CL could make to this. :D

---

@vinith-kovan at this time, could you: 
- update the naming convention for the dialog types to follow this pattern:

    - Dialog data helper type: "EmergencyAccessConfirm**DialogData**"
    - Dialog result helper type: "EmergencyAccessConfirm**DialogResult**"

2024-01-25 23:34 UTC, willmartian commented on apps/web/src/app/auth/settings/emergency-access/confirm/emergency-access-confirm.component.ts
> +export enum EmergencyAccessConfirmResultType {
@vinith-kovan could you: 
- update the naming convention for the dialog types to follow this pattern:

    - Dialog data helper type: "EmergencyAccessConfirm**DialogData**"
    - Dialog result helper type: "EmergencyAccessConfirm**DialogResult**"

2024-01-26 05:25 UTC, willmartian commented on apps/web/src/app/auth/settings/emergency-access/confirm/emergency-access-confirm.component.ts
>    constructor(
I'm not immediately sold on documenting constructor parameters to this extent. 

If the goal is to document _why is this service needed_, that is answered by examining the usage.

If the goal is to document _what does this service do generally_, that documentation should live where the service is defined. 

(My opinions could be bad! But it is a big question, and as such, we might want to align on documentation goals/best practices outside of this PR.)

2024-01-26 05:29 UTC, willmartian commented on apps/web/src/app/auth/settings/emergency-access/confirm/emergency-access-confirm.component.ts
> +type EmergencyAccessConfirmParams = {
> ⚠️ As a parameter to the constructor, this type is public. It should be fully documented.

I think that following the naming convention [outlined here](https://github.com/bitwarden/clients/pull/7492#discussion_r1467080109) documents this type to a certain extent. I am not sure what else I would add to this, do you have a suggestion?

2024-01-26 05:49 UTC, willmartian commented on apps/web/src/app/auth/settings/emergency-access/confirm/emergency-access-confirm.component.ts
> +    return dialogService.open<EmergencyAccessConfirmResultType, EmergencyAccessConfirmParams>(
The second type param to `dialogService.open` can be removed:

```suggestion
    return dialogService.open<EmergencyAccessConfirmResultType>(
```

2024-01-26 17:47 UTC, jlf0dev approved these changes
Couple of nits but nothing blocking for me

2024-01-26 17:47 UTC, jlf0dev commented on apps/web/src/app/auth/settings/emergency-access/emergency-access-add-edit.component.ts
> +
nit: extra line

2024-01-26 17:47 UTC, jlf0dev commented on apps/web/src/app/auth/settings/emergency-access/takeover/emergency-access-takeover.component.ts
> +
nit: extra line

2024-01-31 20:38 UTC, danielleflinn requested changes
Looks great! I left 1 comment for a minor spacing issues.

2024-01-31 20:38 UTC, danielleflinn commented on apps/web/src/app/auth/settings/emergency-access/emergency-access.component.html
> +  <div class="tw-flex tw-items-center tw-gap-2">
Let's add ` tw-mb-2 `on this `div` and set the `bitTypography` to have `noMargin`. This should improve the horizontal alignment of this container and spacing between the button and table.

2024-01-31 20:53 UTC, jlf0dev approved these changes

2024-02-01 15:53 UTC, danielleflinn approved these changes

2024-02-02 20:00 UTC, audrey-jensen commented on apps/web/src/app/auth/settings/emergency-access/confirm/emergency-access-confirm.component.ts
> +  submit = async () => {
In that case, we should consider whether this pattern should be applied more broadly, perhaps by changing our linter.

2024-02-02 20:07 UTC, audrey-jensen commented on apps/web/src/app/auth/settings/emergency-access/confirm/emergency-access-confirm.component.ts
>    constructor(
Insofar as this PR is concerned, I'll accept that. It is, however, a pattern being established in the tools code more broadly. The reason for this is that tools code is incredibly diverse in its purpose. We maintain components whose primary purpose is integration and data transfer (sends, imports/exports, password generation, i18n, and notifications being the most prominent). 

Whereas a specific feature team might be able to rely on callsites to explain the usage of their code, tools code is applied in various ways across the product. It is important from the consumer's point of view that they can understand the purpose of a dependency. This facilitates the proper usage of our code, and ensures that if we need to change how a dependency operates, that we preserve its existing use.

2024-02-02 20:11 UTC, audrey-jensen commented on apps/web/src/app/auth/settings/emergency-access/confirm/emergency-access-confirm.component.ts
>    async ngOnInit() {
It's already started @jlf0dev. I've been doing it for months.

2024-02-02 20:17 UTC, audrey-jensen commented on apps/web/src/app/auth/settings/emergency-access/confirm/emergency-access-confirm.component.ts
> +type EmergencyAccessConfirmParams = {
Its members should be documented at a minimum.

Example: 
```
/** display name of the account requesting emergency access */
name: string,
/** identifies the account requesting emergency access */
userId: string,
/** traces a unique emergency request  */
emergencyAccessId: string
```

Those descriptions may be incorrect. I haven't fully traced where they originate.

2024-02-02 20:18 UTC, audrey-jensen commented on apps/web/src/app/auth/settings/emergency-access/confirm/emergency-access-confirm.component.ts
> +      this.dialogRef.close(EmergencyAccessConfirmResultType.Confirmed);
Resolved out of band. This is the correct way to approach this.

2024-02-02 20:21 UTC, audrey-jensen commented on apps/web/src/app/auth/settings/emergency-access/emergency-access-add-edit.component.ts
> +    this.editMode = this.loading = this.params.emergencyAccessId != null;
Resolving tech debt already present in the code is out of scope. In the future I'll focus on net-new tech debt only.

2024-02-02 20:28 UTC, audrey-jensen requested changes
One unresolved comment remaining. New public types must be documented.

2024-02-06 15:50 UTC, willmartian requested changes
@vinith-kovan, your latest commit introduces unrelated changes. (Note how additional codeowners were added). 

They may have been introduced by either an incorrect merge commit or by an out-of-date prettier configuration. I would try running `npm ci` and `npm run prettier` and see if that reverts the changes.

2024-02-06 20:46 UTC, audrey-jensen commented
My outstanding issue is resolved. Once the fix goes in for the unresolved changes I'll approve.

👍🏻 Thanks for adding the comments @vinith-kovan!

2024-02-07 13:45 UTC, willmartian approved these changes

2024-02-07 14:01 UTC, audrey-jensen approved these changes

2024-02-08 18:07 UTC, jlf0dev commented on apps/web/src/app/auth/settings/emergency-access/confirm/emergency-access-confirm.component.ts
>    async ngOnInit() {
@audrey-jensen just meant requiring it in Auth code 😁

2024-02-08 18:08 UTC, jlf0dev approved these changes

2024-02-08 18:21 UTC, audrey-jensen commented on apps/web/src/app/auth/settings/emergency-access/confirm/emergency-access-confirm.component.ts
>    async ngOnInit() {
Here's where I notice that the only tools code is the password strength meter and 🤦🏻‍♀️.

2024-03-05 02:47 UTC, willmartian commented
Since @vinith-kovan has write access to the repo now, and there were merge conflicts + QA changes requested, I am closing this in favor of https://github.com/bitwarden/clients/pull/7850. That way we don't have two manage two identical branches.

2024-03-05 02:47 UTC, closed without merging