[AC-1492] Managed collections export
bitwarden/clients pull request #7556
Opened 2024-01-15 13:37 UTC by aj-rosado

Added logic to show orgs on export that the user can export from

## Type of change

Supporting export of managed collections from individual vault

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Added new methods to create an export with encrypted and decrypted managed collections and ciphers.

## Code changes

- **export.component.ts:** Added flexible collection flag, added logic to export managed collections if the context is flexible collections and if an organization is selected. Added observable logic to get the managed organizations.
- **org-vault-export.service.ts:** Added methods to get Encrypted and Decrypted managed collections export.
- **vault-export.service.ts:** Added flag to select if this should be a managed data export or a full org data export.
- **rest: ** Added missing services for component.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-01-17 22:03 UTC, djsmith85 requested changes
Partial review: Mostly minor things! Closer look at the 2 remaining things tomorrow morning with a fresh ☕ 🧠  

- I'm going to have another look at `apps/web/src/app/tools/vault-export/export.component.html` as we talked about hiding the targetSelector dropdown

- `setIndividualVaultData`in `libs/angular/src/tools/export/components/export.component.ts`

2024-01-18 10:26 UTC, aj-rosado commented on libs/exporter/src/vault-export/services/org-vault-export.service.ts
> +    onlyManagedCollections = true,
The idea of defaulting it is to keep the old behaviour as default and provide the parameter only when we want to do the managed collections export

2024-01-18 12:51 UTC, djsmith85 approved these changes
@aj-rosado Nice work on this. Really enjoyed the pairing.

2024-01-18 19:34 UTC, addisonbeck commented on apps/web/src/app/admin-console/organizations/tools/vault-export/org-vault-export.component.ts
> -    this.flexibleCollectionsEnabled$ = this.route.parent.parent.params.pipe(
Is removing this intentional? I haven't been involved in the flexible collections work, but based on what I know about the state it's in I feel like this information would be in use. Gonna add @eliykat since he's been spearheading that effort from the dev side of things.

2024-01-18 19:45 UTC, djsmith85 commented on apps/web/src/app/admin-console/organizations/tools/vault-export/org-vault-export.component.ts
> -    this.flexibleCollectionsEnabled$ = this.route.parent.parent.params.pipe(
The removal is intentional as a user coming through AC (this component) we don't care if the organization has the flexible collections enabled or not. An export through this component will always be a full-export (someone with the right permissions creating a vault-backup).

An export via the Password Manager (Tools -> Export) will differentiate between individual and org vault exports. For an org-vault it will only export collections managed by that user.

2024-01-18 21:54 UTC, addisonbeck approved these changes

2024-01-18 21:55 UTC, addisonbeck commented on apps/web/src/app/admin-console/organizations/tools/vault-export/org-vault-export.component.ts
> -    this.flexibleCollectionsEnabled$ = this.route.parent.parent.params.pipe(
Makes sense. Thanks!

2024-01-22 04:26 UTC, eliykat reviewed
I didn't do an in-depth review as others have that covered, overall looks good but I have a couple of questions

2024-01-22 04:26 UTC, eliykat commented on libs/exporter/src/vault-export/services/org-vault-export.service.ts
> +    await Promise.all(promises);
Won't there be a race condition here, as you're not waiting for `decCollections` to be populated before using it to filter `decCiphers` line 183?

2024-01-22 04:26 UTC, eliykat commented on libs/exporter/src/vault-export/services/vault-export.service.ts
> +    onlyManagedCollections = false,
Is this ever set to true?

2024-01-22 10:25 UTC, aj-rosado commented on libs/exporter/src/vault-export/services/vault-export.service.ts
> +    onlyManagedCollections = false,
Yes, when is an export from an organization on individual vault. It returns only the user managed collections and makes this call as true

2024-01-22 11:57 UTC, aj-rosado commented on libs/exporter/src/vault-export/services/org-vault-export.service.ts
> +    await Promise.all(promises);
you're right! nice catch. I have solved it

2024-01-23 06:58 UTC, eliykat commented on libs/exporter/src/vault-export/services/vault-export.service.ts
> +    onlyManagedCollections = false,
Yes but then it just uses a literal value, it doesn't refer to the class property: https://github.com/bitwarden/clients/pull/7556/files#diff-e55d503a3761ad481dc3ebb66d922706bf4a39ae7807686d6a7ae6cb5ac734d6R201. Which makes me wonder whether the class property is still useful?

I'm not super familiar with Tools code so this is optional - feel free to mark this thread as resolved if you're OK with it.

2024-01-23 06:59 UTC, eliykat commented on libs/exporter/src/vault-export/services/org-vault-export.service.ts
> +    await Promise.all(promises);
Looks good!

2024-01-23 06:59 UTC, eliykat approved these changes

2024-01-26 18:00 UTC, merged