[AC-2003] Delete collection button is missing for users with Can Manage in individual vault
bitwarden/clients pull request #7569
Opened 2024-01-16 17:03 UTC by gbubemismith

## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-01-16 17:35 UTC, shane-melton requested changes
Just need to add one null check for providers. Otherwise this should be good to go afterwards.

2024-01-16 17:35 UTC, shane-melton commented on apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.ts
> +              this.collection.canDelete(organization, flexibleCollections) || collection.manage;
We should use `collection?.manage` in case the collection is not available in the sync data (e.g. for providers).

2024-01-16 22:30 UTC, shane-melton approved these changes
Thank you!

2024-01-18 17:06 UTC, ike-kottlowski submitted a review, later dismissed
Looks like there was just formatting changes in the auth files.

2024-01-23 15:54 UTC, shane-melton approved these changes

2024-01-23 20:13 UTC, merged