[PM-5362]Create MP Service for state provider migration
bitwarden/clients pull request #7623
Opened 2024-01-19 20:17 UTC by jlf0dev

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Creates a `MasterPasswordService` for `MasterKey`, `MasterKeyHash`, and `ForceSetPasswordReason`

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-01-22 14:26 UTC, MGibson1 requested changes
I think you're missing some complexity around `ForcePasswordReset`. That item is  stored differently in web vs other clients. For the new framework, that means different key definitions depending on the client -- likely either through DI or a different service in web that overrides it.

2024-03-20 20:15 UTC, rr-bw reviewed
Looking good so far from Auth. I'll do a final review after conflicts are resolved, migrations bumped, etc.

2024-03-20 20:15 UTC, rr-bw commented on libs/angular/src/auth/components/lock.component.ts
> +    );
What do you think about renaming this variable to `masterKeyHash` or `storedMasterKeyHash`? I know it's not a huge deal, but I noticed many times throughout our codebase and whitepaper we will use different terms and variables to refer to the same encryption property. It might be nice to standardize.

2024-03-20 20:15 UTC, rr-bw commented on apps/cli/src/auth/commands/unlock.command.ts
> +    const storedKeyHash = await firstValueFrom(this.masterPasswordService.masterKeyHash$(userId));
See comment [here](https://github.com/bitwarden/clients/pull/7623/files#diff-9f30ea765a7a568155802df6b5a9c7ab36051012b875a05ae08a52d4cc7016cdR221-R223) about naming

2024-03-20 20:15 UTC, rr-bw commented on libs/common/src/auth/abstractions/master-password.service.abstraction.ts
Could add some JSdocs if you want.

2024-03-20 22:38 UTC, MGibson1 requested changes
nice work, this is big, but a great start on the new paradigm

2024-03-20 22:38 UTC, MGibson1 commented on libs/common/src/platform/services/crypto.service.ts
> +    userId ??= (await firstValueFrom(this.accountService.activeAccount$))?.id;
**nit**: prefer `stateProvider.activeUserId$`. This is true for several locations in the file -- the existing style is different because this helper didn't exist when this was originally written.

2024-03-20 22:38 UTC, MGibson1 commented on libs/common/src/platform/services/crypto.service.ts
> +    masterKey ??= await firstValueFrom(this.masterPasswordService.masterKey$(userId));
**issue**: missing userId population guarantees.

2024-03-20 22:38 UTC, MGibson1 commented on libs/common/src/platform/services/crypto.service.ts
> +    userId ??= (await firstValueFrom(this.accountService.activeAccount$))?.id;
🥳

2024-03-20 22:38 UTC, MGibson1 commented on libs/common/src/platform/services/crypto.service.ts
>      await this.stateService.setMasterKeyEncryptedUserKey(userKeyMasterKey, { userId: userId });
**discussion**: My interpretation is that the goal is to move master key and master key hash. I'd like to submit this as an MVP for this service.

2024-03-20 22:38 UTC, MGibson1 commented on libs/common/src/platform/models/domain/account.ts
> -      cryptoMasterKey: SymmetricCryptoKey.fromJSON(obj?.cryptoMasterKey),
**issue**: why delete this and not the corresponding property?

2024-03-20 22:38 UTC, MGibson1 commented on apps/browser/src/auth/background/service-factories/master-password-service.factory.ts
> +}
These are better represented as the inverse, where you have an internal factory and then type it to the less specific `MasterPasswordServiceAbstraction`, which shouldn't need a cast

2024-03-20 22:38 UTC, MGibson1 commented on libs/common/src/auth/services/master-password/master-password.service.ts
> +});
**issue**: It _really_ seems like these should be `UserKeyDefinitions` with `clearOn` events set.

2024-03-20 22:38 UTC, MGibson1 commented on libs/common/src/state-migrations/migrations/32-move-force-set-password-to-state-providers.ts
> +export class MoveForceSetPasswordReasonToStateProviderMigrator extends Migrator<31, 32> {
**issue**: You need to migrate the key hash as well (it is on disk in state service)

2024-03-20 22:38 UTC, MGibson1 commented on libs/angular/src/services/jslib-services.module.ts
> +    },
**nit (that becomes more with `safeProvider` work)**: These make more sense the other way around so that you don't have to cast

2024-03-20 22:38 UTC, MGibson1 commented on libs/common/src/auth/services/master-password/master-password.service.ts
Each of these methods will throw if called with `userId == null`. You do a good job on currently passing in a userId where you can, but it is a good idea to defensively check for non-null userId and throw a more helpful error if called with null.

these throw should also be noted in your abstract docs with `@throws`

2024-03-20 22:38 UTC, MGibson1 commented on libs/angular/src/auth/components/set-password.component.ts
> +    const userId = (await firstValueFrom(this.accountService.activeAccount$))?.id;
Ideally this would use the same userId throughout the component, right?

2024-03-27 15:43 UTC, jlf0dev commented on libs/angular/src/auth/components/lock.component.ts
> +    );
Good callout. It was originally called the password hash but that was slightly misleading since it comes from the master key. We've been trying to update it where we can, but request/response objects are a little harder.

2024-03-27 15:43 UTC, jlf0dev commented on apps/cli/src/auth/commands/unlock.command.ts
> +    const storedKeyHash = await firstValueFrom(this.masterPasswordService.masterKeyHash$(userId));
Done!

2024-03-27 15:43 UTC, jlf0dev commented on libs/common/src/auth/abstractions/master-password.service.abstraction.ts
Glad ya'll mentioned this 👍

2024-03-27 15:44 UTC, jlf0dev commented on libs/common/src/platform/services/crypto.service.ts
> +    userId ??= (await firstValueFrom(this.accountService.activeAccount$))?.id;
Updated in the crypto service, wish it was more widely available but a lot of the calls are from components

2024-03-27 15:44 UTC, jlf0dev commented on libs/common/src/platform/services/crypto.service.ts
> +    masterKey ??= await firstValueFrom(this.masterPasswordService.masterKey$(userId));
Added 👍

2024-03-27 15:45 UTC, jlf0dev commented on libs/common/src/platform/services/crypto.service.ts
>      await this.stateService.setMasterKeyEncryptedUserKey(userKeyMasterKey, { userId: userId });
Migrated! Didn't add any more logic to the service to keep this PR as small as possible, but thats planned for the future.

2024-03-27 15:45 UTC, jlf0dev commented on libs/common/src/platform/models/domain/account.ts
> -      cryptoMasterKey: SymmetricCryptoKey.fromJSON(obj?.cryptoMasterKey),
Yep, missed it. Cleaned up the Account

2024-03-27 15:45 UTC, jlf0dev commented on apps/browser/src/auth/background/service-factories/master-password-service.factory.ts
> +}
Done!

2024-03-27 15:45 UTC, jlf0dev commented on libs/common/src/auth/services/master-password/master-password.service.ts
> +});
Agreed, updated.

2024-03-27 15:45 UTC, jlf0dev commented on libs/common/src/state-migrations/migrations/32-move-force-set-password-to-state-providers.ts
> +export class MoveForceSetPasswordReasonToStateProviderMigrator extends Migrator<31, 32> {
Done!

2024-03-27 15:45 UTC, jlf0dev commented on libs/angular/src/services/jslib-services.module.ts
> +    },
True, fixed.

2024-03-27 15:46 UTC, jlf0dev commented on libs/common/src/auth/services/master-password/master-password.service.ts
Yep, done. (I hope someday we turn on strict null checks)

2024-03-27 15:46 UTC, jlf0dev commented on libs/angular/src/auth/components/set-password.component.ts
> +    const userId = (await firstValueFrom(this.accountService.activeAccount$))?.id;
Yep, updated.

2024-03-27 16:03 UTC, MGibson1 commented on libs/common/src/auth/services/master-password/master-password.service.ts
same, thank you

2024-03-28 15:35 UTC, MGibson1 submitted a review, later dismissed

2024-04-04 12:07 UTC, MGibson1 approved these changes

2024-04-04 13:14 UTC, gbubemismith approved these changes

2024-04-04 14:18 UTC, rr-bw approved these changes

2024-04-04 14:22 UTC, merged