[PM-5264] Implement StateProvider in LoginService
bitwarden/clients pull request #7662
Opened 2024-01-24 07:20 UTC by rr-bw

- setup StateProvider in LoginService
- replace implementations

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-03-12 12:39 UTC, jlf0dev commented on libs/common/src/auth/services/remember-email.service.ts
> +});
Issue: I think there's some additional work here. Part of the reason we're using state providers is that we won't have persistent services anymore. What if we close this popup and continue the auth process in a different one, like we do sometimes in 2fa? Therefore, we can't just save data to the singleton service itself like we have been.

We'll need to save the `email` and `rememberEmail` pieces of state in their own memory based state providers. `saveEmailSettings` will then set the email on disk if required.

2024-03-12 18:22 UTC, rr-bw commented on libs/common/src/auth/services/remember-email.service.ts
> +});
Here's a walkthrough using Duo. I go through it twice in the video. The first time I don't set a remembered email, and the second time I set the remembered email (and it does persist). Let me know if this addresses your concerns.

https://github.com/bitwarden/clients/assets/102181210/b2981e6b-ca35-4d8a-9238-7621cfd553dc

2024-03-12 18:25 UTC, rr-bw commented on libs/common/src/auth/abstractions/remember-email.service.ts
>  }
Yes I agree on the renaming. Forgot about the JSdocs, will add those.

2024-03-15 20:23 UTC, rr-bw commented
@jlf0dev I made three main updates:
- Renamed `rememberedEmail` to `storedEmail`
- Renamed `RememberEmailService` to `EmailService`
   - I think typing `this.rememberEmailService.getEmail()` could confuse a dev into thinking they are actually getting the remembered/stored email, when in fact they are not.
- Refactored the base [login.component.ts](https://github.com/bitwarden/clients/pull/7662/files#diff-ea074c0be108845fe27a2f0d18931c73861f83cb4efbe8512c5d8d695da071be) to simplify logic

2024-03-18 16:48 UTC, rr-bw commented
> * Renamed `RememberEmailService` to `EmailService`
>   
>   * I think typing `this.rememberEmailService.getEmail()` could confuse a dev into thinking they are actually getting the remembered/stored email, when in fact they are not.

Follow-up from our discussion: We're renaming to `LoginEmailService` instead, since the service is just working with the email during the login process.

2024-03-18 18:19 UTC, jlf0dev requested changes

2024-03-18 18:19 UTC, jlf0dev commented on libs/common/src/auth/abstractions/login-email.service.ts
> +  saveEmailSettings: () => Promise<void>;
if we have a method to `saveEmailSettings()` do we need a `setStoredEmail` method? On that note, do we even need to expose a `getStoredEmail` method? Why don't we just use whatever we have stored on the service?

2024-03-18 18:19 UTC, jlf0dev commented on libs/common/src/auth/services/login-email.service.ts
> +  private storedEmail: GlobalState<string>;
comment: One day we can just expose this as an observable, will make this service super simple!

2024-03-19 22:20 UTC, willmartian submitted a review, later dismissed
Platform changes LGTM

2024-03-29 19:27 UTC, jlf0dev requested changes

2024-03-29 19:27 UTC, jlf0dev commented on libs/angular/src/auth/components/login-via-auth-request.component.ts
> +  // }
issue: please remove

2024-03-29 19:27 UTC, jlf0dev commented on apps/web/src/app/core/core.module.ts
> +      deps: [StateProvider],
issue: I'm pretty sure you can remove these and keep the one in jslib instead of having one for every client. We usually only declare it in these modules if we have a client specific override we want to register.

2024-03-29 21:10 UTC, jlf0dev approved these changes

2024-03-30 13:58 UTC, willmartian approved these changes

2024-03-30 18:00 UTC, merged