[PM-5533] Miigrate Asymmetric User Keys to State Providers
bitwarden/clients pull request #7665
Opened 2024-01-24 15:15 UTC by MGibson1

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Moves asymmetric user keys to state providers

### Draft reason 
Needs to be retargeted after #7649 

## Code changes

- **state service / account**: Remove asym keys
- **crypto service**: use state providers for asym keys.
  - The one weird part here was user key verification, for which I use the derive methods for decrypted private and public key definitions to validate proposed user keys.
- **user-key.state**: expanded to include asymmetric user keys
  - encrypted user private key stored on disk
  - decrypted user private key, derived from encrypted user private key
  - user public key, derived from decrypted user private key
- **derive-definition**: expanded the `from` factory method to allow derivations from other `DeriveDefinition`s, but requiring a new name

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-01-30 15:20 UTC, justindbaur requested changes
Couple minor things

2024-01-30 15:20 UTC, justindbaur commented on libs/common/src/platform/services/key-state/user-key.state.ts
> +    const userKey = await cryptoService.getUserKey();
Should this derive definition take `CombinedState<T>` so that it can pass the user id into this method?

2024-01-30 15:20 UTC, justindbaur commented on libs/common/src/platform/state/state-definitions.ts
> +
Should we try to enforce any styling of how these are laid out to best avoid merge conflicts? Team sections? Single line between all items? `disk` and `memory` of a single state grouped together like with `generator`?

2024-02-07 15:07 UTC, MGibson1 commented on libs/common/src/platform/state/state-definitions.ts
> +
I've been thinking team sections, but am open to whatever. Thus far it's kind of just random.

2024-02-14 19:10 UTC, justindbaur approved these changes

2024-02-14 19:36 UTC, justindbaur approved these changes

2024-02-14 20:04 UTC, merged