[PM-5277] Migrate Sync Service to State Provider
bitwarden/clients pull request #7680
Opened 2024-01-25 01:17 UTC by shane-melton

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Migrate the `lastSync` state to the State Provider framework.

## Code changes

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-01-26 15:15 UTC, justindbaur approved these changes
Very nice work, thank you!

2024-01-26 15:15 UTC, justindbaur commented on libs/common/src/platform/state/state-definitions.ts
> +export const SYNC_STATE = new StateDefinition("sync", "disk", { web: "memory" });
This is correct but also for future wanderers I want to explain why it's right because it's weird. 

In the main `StateService` the options `this.defaultOnDiskMemoryOptions()` dictated the `htmlStorageLocation` should be `HtmlStorageLocation.Memory` but as far as I can tell `HtmlStorageLocation.Memory` has no control over where the data is stored. The other two options on that enum do have control though. 

https://github.com/bitwarden/clients/blob/c0e157610e20f0e49da8363454e7a3594825b995/apps/web/src/app/core/html-storage.service.ts#L31-L37

This would mean that both not defining a `HtmlStorageLocation` and defining `Memory` would lead to it using `sessionStorage` on web. Since `"disk"` maps to `sessionStorage` on web there is no reason to say `{ web: "memory" }` if your previous state service options used `this.defaultOnDiskMemoryOptions()`. 

This designation **IS** accurate though because the web client overrides the last sync methods and reconciles the options using `this.defaultInMemoryOptions()`. All the other uses of `{set|get}Encrypted*` in web [`StateService`](https://github.com/bitwarden/clients/blob/c0e157610e20f0e49da8363454e7a3594825b995/apps/web/src/app/core/state/state.service.ts) will want to do what you did here.

2024-01-26 15:15 UTC, justindbaur commented on libs/common/src/vault/services/sync/sync.service.ts
> +const LAST_SYNC_KEY = new KeyDefinition<string | null>(SYNC_STATE, "lastSync", {
Nice `| null`!

2024-01-26 15:25 UTC, justindbaur requested changes

2024-01-26 15:25 UTC, justindbaur commented on libs/common/src/state-migrations/migrations/13-move-last-sync-to-state-provider.ts
> +      await helper.set(userId, account);
Actually sorry, got distracted, can you move the `helper.set` inside the if block next to the `delete` call. If you don't delete anything there is no need to actually re-save the account object.

2024-01-26 15:57 UTC, shane-melton commented on libs/common/src/state-migrations/migrations/13-move-last-sync-to-state-provider.ts
> +      await helper.set(userId, account);
Ah, good point, will do!

2024-01-26 16:10 UTC, shane-melton commented on libs/common/src/state-migrations/migrations/13-move-last-sync-to-state-provider.ts
> +      await helper.set(userId, account);
Moved in [3ddf619](https://github.com/bitwarden/clients/pull/7680/commits/3ddf619eaba866befe04916ad375a796b6e9a285)

2024-01-26 16:11 UTC, justindbaur submitted a review, later dismissed

2024-01-30 18:10 UTC, gbubemismith submitted a review, later dismissed

2024-02-06 19:55 UTC, gbubemismith approved these changes

2024-02-06 19:55 UTC, justindbaur submitted a review, later dismissed

2024-02-06 19:59 UTC, gbubemismith approved these changes

2024-02-06 20:00 UTC, merged