Vault/pm 5276
bitwarden/clients pull request #7682
Opened 2024-01-25 03:00 UTC by gbubemismith

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-01-30 20:40 UTC, justindbaur requested changes
You should also be able to delete `{set|get}{Encrypted|Decrypted}Folders` methods from state service and the associated properties off of the account object.

2024-01-30 20:40 UTC, justindbaur commented on apps/browser/src/popup/services/services.module.ts
>      },
You should be able to delete this and rely on the one supplied by `jslib-services.module.ts`.

2024-02-01 08:07 UTC, LRNcardozoWDF submitted a review, later dismissed
LGTM!

2024-02-01 13:20 UTC, justindbaur requested changes
Something I should have caught the first time but super close.

2024-02-01 13:20 UTC, justindbaur commented on libs/common/src/platform/state/state-definitions.ts
> +export const FOLDER_DISK = new StateDefinition("folder", "disk");
I should have noticed this on my first review sorry, but I believe you want the `{ web: "memory" }` override. Like @shane-melton did and I talked about [here](https://github.com/bitwarden/clients/pull/7680/files#r1467776755). 

Along with doing this you have some more methods you can delete from the web override of `StateService`.

2024-02-01 15:56 UTC, justindbaur approved these changes
Looks great, thanks!

2024-02-01 17:09 UTC, LRNcardozoWDF submitted a review, later dismissed

2024-02-06 17:57 UTC, shane-melton approved these changes

2024-02-06 19:50 UTC, justindbaur approved these changes

2024-02-06 19:51 UTC, merged