PM-5274 Migrate Collection Service State
bitwarden/clients pull request #7732
Opened 2024-01-29 18:49 UTC by Jingo88

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

* Update Collection Service to use new state provider
* Add migration files and unit tests

## Code changes

* `main.background` | `jslibs` | `collection service factory` - made necessary changes to switch from state service to state provider
* `collectionService`: create keys for encryptedCollections and derived decrypted. Replace stateService calls with new state provider calls
* `state-definitions` added
* `migrate` - version update

2024-02-01 00:30 UTC, MGibson1 requested changes
The encrypted type being used in `collection.service` isn't really what's needed. There's no need to persist the pattern in `Account` object of and `encrypted` and `decrypted` part of state -- that's one of the things we're trying to get away from.

You also need to remove `state.service` and `Account` references to the data your moving here.

2024-02-01 00:30 UTC, MGibson1 commented on libs/common/src/state-migrations/migrate.ts
> +    .with(CollectionMigrator, 12, CURRENT_VERSION)
this will need updated after merging in main. Should be easy

2024-02-01 00:30 UTC, MGibson1 commented on libs/common/src/state-migrations/migrations/14-move-collections-state-to-state-provider.ts
> +      const value = account?.data?.collections?.encrypted;
Please delete these properties from the `Account` object definition

2024-02-01 00:30 UTC, MGibson1 commented on libs/common/src/vault/services/collection.service.ts
> +  deserializer: (jsonData: any) => jsonData,
Please don't use `any`. This should be a `Jsonify` representation of your state, and this is your opportunity to ensure that it is deserialized appropriately.

2024-02-01 00:30 UTC, MGibson1 commented on libs/common/src/vault/services/collection.service.ts
> +  Record<string, { [id: string]: CollectionData }>
⚠️ This doesn't seem likely to be the type you want. What does the key of `Record<string, { [id: string]: CollectionData}>` represent? I suspect you want it to be the id of the collection, which is actually the key of the value of the type 😵.

2024-02-01 00:30 UTC, MGibson1 commented on libs/common/src/vault/services/collection.service.ts
> +  derive: async (collections: any, { collectionService }) => {
Do not use `any` type.

2024-02-01 00:30 UTC, MGibson1 commented on libs/common/src/vault/services/collection.service.ts
> +    if (collections.encrypted) {
⚠️ `encrypted` does not exist on your `collections` object. This is why you shouldn't use `any`.

2024-02-01 00:30 UTC, MGibson1 commented on libs/common/src/vault/services/collection.service.ts
> +    Record<string, { [id: string]: CollectionData }>
Why define this if it's private? it's already available privately through the `state$` parameter on `encryptedCollectionDataState`.

Same with `decryptedCollectionDataState$` below.

2024-02-07 14:12 UTC, MGibson1 requested changes

2024-02-07 14:12 UTC, MGibson1 commented on libs/common/src/vault/models/view/collection.view.ts
> +  constructor(c?: Partial<Collection | CollectionAccessDetailsResponse>) {
Why's this partial now? is data being lost in the deserialization?

2024-02-07 14:12 UTC, MGibson1 commented on libs/common/src/vault/services/collection.service.ts
> +      if (collections.hasOwnProperty(id)) {
huh? you're iterating over properties, then checking to see if the object has that property.

2024-02-07 14:12 UTC, MGibson1 commented on libs/common/src/vault/services/collection.service.ts
**blocking**: Please add a logout callback method that clears data on logout and call that method wherever `stateService.clean` is called (probably in a big promise above it).

2024-02-08 17:00 UTC, Jingo88 commented on libs/common/src/vault/services/collection.service.ts
I've added the derived forceValue to the clear method in CollectionService. I believe this covers all the calls for `stateService.clean` 

Question: Do we need to forceValue here if it is getting it's information from the encrypted?

2024-02-13 21:57 UTC, MGibson1 submitted a review, later dismissed
Looking good! thank you for iterating with me 😄

2024-02-13 23:50 UTC, gbubemismith commented on libs/common/src/state-migrations/migrations/18-move-collections-state-to-state-provider.spec.ts
> +      helper = mockMigrationHelper(rollbackJSON(), 17);
nitpick: I think the version should be 18 here since it's a rollback

2024-02-14 19:32 UTC, shane-melton requested changes
This is looking good! Only saw one issue and had a few other comments/questions.

2024-02-14 21:23 UTC, shane-melton requested changes
Thanks for making those changes! Only two small issues left and then I think we're good to go!

2024-02-14 21:23 UTC, shane-melton commented on libs/common/src/services/vault-timeout/vault-timeout.service.ts
> +    await this.collectionService.clearActiveUserCache();
issue: We should move this up and into the `if (userId == null || ...` block above. If we're locking a specific user then we do not want to clear the active user cache. See the folder service doing the same thing.

2024-02-14 21:23 UTC, shane-melton commented on libs/common/src/state-migrations/migrations/20-move-collections-state-to-state-provider.spec.ts
> +      helper = mockMigrationHelper(rollbackJSON(), 19);
issue: This should be 20, the rollback JSON starts as version 20, and is being rolled back to 19 in the test.

2024-02-14 21:32 UTC, shane-melton submitted a review, later dismissed
Looks good!

2024-02-14 21:48 UTC, shane-melton approved these changes

2024-02-14 22:01 UTC, MGibson1 approved these changes

2024-02-14 22:01 UTC, MGibson1 commented on libs/common/src/vault/services/collection.service.ts
> +      await this.stateProvider.getUser(userId, ENCRYPTED_COLLECTION_DATA_KEY).update(() => null);
No change necessary, but just FYI. There's a helper to do this on the `stateProvider` class, the `setUserState` method.

It's also not necessary to clear the decrypted value if you're clearing the encrypted value that backs it -- the derived value with always track the parent state.

2024-02-14 22:03 UTC, merged