[PM-5536] Migrate `ConfigService` to State Providers
bitwarden/clients pull request #7739
Opened 2024-01-29 22:14 UTC by justindbaur

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Migrate `ConfigService`'s server config to state providers. 

## Code changes

- Delete browser variant
- Update DI
- Tests
- Delete state service methods

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-01-30 14:18 UTC, MGibson1 requested changes
Only critical things are:
- that It looks like some constructor locations weren't updated for CLI and browser background factories.
- state definition TODO

Other items are service improvements we need to do, but aren't necessarily related to state providers

2024-01-30 14:18 UTC, MGibson1 commented on apps/browser/src/platform/services/browser-config.service.ts
I'm not sure we want to delete this.

Config service creates network requests that we don't want every view of the application to perform. It's sufficient for a background service to perform the requests and a foreground service to just supply state observables and hooks into the background such that the foreground can trigger updates (which we should disallow, but that's another discussion).

It's true the application already does this, though, so we _could_ backlog

2024-01-30 14:18 UTC, MGibson1 commented on libs/common/src/platform/state/state-definitions.ts
> +// TODO: Use disk-local for web
This change is merged in, please perform this TODO

2024-01-30 16:11 UTC, justindbaur commented on libs/common/src/platform/services/config/config.service.ts
> +export const SERVER_CONFIG_KEY = new KeyDefinition<ServerConfigData>(CONFIG_DISK, "serverConfig", {
You are correct, I'm not trying to reinvent it. I don't disagree though, MV3 will want it to track the last time it requested so we can make sure we aren't going to the server to often. I'll make another ticket tracking it but I don't think it should be a be a `Record<UserId, something>` that would be just reinventing user state inside of global state. It could still loop over user ids, just use single user state for each of them.

2024-01-30 20:18 UTC, justindbaur commented on apps/browser/src/platform/services/browser-config.service.ts
Good call, since the subject isn't directly state based we still need it. Restore the browser variant.

2024-01-30 20:19 UTC, justindbaur commented on libs/common/src/platform/services/config/config.service.ts
> +// QUESTION: Just server and not repeat "config"?
Changed it to drop the `config` part, both in variable name and the key name.

2024-01-31 13:23 UTC, MGibson1 requested changes
Sorry, I think I was unclear about restoring `BrowserConfigService`. That's linked to fixing the repeated network calls with a foreground and background version

2024-01-31 13:23 UTC, MGibson1 commented on apps/browser/src/platform/services/browser-config.service.ts
I actually think if we're not going to fix the repeated network calling by creating foreground/background variants until later, we _do_ want to delete this.

At the least we need to get rid of the `@browserSession` and `@sessionSync` decorators.

2024-01-31 13:29 UTC, justindbaur commented on apps/browser/src/platform/services/browser-config.service.ts
It doesn't repeat the network calls, the foreground variant passes in `subscribe = false` so only the background version does the calls but shares the info through `@sessionSync`.

2024-01-31 13:50 UTC, justindbaur commented
Closing in favor of a more full refactor, there are various parts of this service that will fail us in MV3. Since the primary driver of state provider migrations is MV3 this feels silly to do the migration like this without more fundamental changes. Changes that may change the shape of the state anyways.

2024-01-31 13:50 UTC, closed without merging