[PM-5275] Migrate state in Fido2ClientService to State Providers
bitwarden/clients pull request #7745
Opened 2024-01-30 18:07 UTC by gbubemismith

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-01-30 20:02 UTC, shane-melton requested changes
Awesome work! Thanks for going ahead and creating the `VaultSettingsService` and getting that started for us. 

I have a couple questions/suggestions, let me know that you think!

2024-01-30 21:31 UTC, gbubemismith commented on libs/common/src/platform/state/state-definitions.ts
> +export const FIDO2_DISK = new StateDefinition("fido2", "disk");
good point

2024-01-30 21:38 UTC, gbubemismith commented on apps/browser/src/background/main.background.ts
I think this should be done in the vault settings creation ticket

2024-01-30 22:32 UTC, gbubemismith commented on libs/common/src/platform/state/state-definitions.ts
> +export const FIDO2_DISK = new StateDefinition("fido2", "disk");
Addressed f0c4e2be0d51ea105272219a09e9a7297b767091

2024-01-30 22:33 UTC, gbubemismith commented on libs/common/src/vault/services/vault-settings/vault-settings.service.ts
> +    this.enablePasskeysState = stateProvider.getGlobal(USER_ENABLE_PASSKEYS);
Addressed here f0c4e2be0d51ea105272219a09e9a7297b767091

2024-01-30 22:33 UTC, gbubemismith commented on libs/common/src/vault/services/vault-settings/vault-settings.service.ts
> +  get enablePasskeys$(): Observable<boolean> {
Addressed here f0c4e2be0d51ea105272219a09e9a7297b767091

2024-01-30 22:33 UTC, gbubemismith commented on libs/common/src/state-migrations/migrations/14-move-enable-passkeys-to-state-providers.ts
> +    await helper.set("global", global);
Addressed here f0c4e2be0d51ea105272219a09e9a7297b767091

2024-01-31 00:02 UTC, shane-melton requested changes
Looks great! Thanks for making those changes I think it turned out well!

Only thing I noticed is we should still add `readonly` to `enablePasskeys$` in the abstraction class as well as the implementation so its exposed to consumers of the service.

2024-01-31 00:09 UTC, gbubemismith commented on libs/common/src/vault/abstractions/vault-settings/vault-settings.service.ts
> +  enablePasskeys$: Observable<boolean>;
Thanks I missed that

2024-01-31 18:06 UTC, shane-melton requested changes
Looks like we just need to get the tests working again and then we're good to go.

2024-01-31 18:06 UTC, shane-melton commented on libs/common/src/vault/services/fido2/fido2-client.service.spec.ts
> +    vaultSettingsService.enablePasskeys$ = of(true);
It looks like the tests are now failing due to assigning of the `readonly` value. I think we should be able to replace this line with: `jest.spyOn(vaultSettingsService, "enablePasskeys$", "get").mockReturnValue(of(true));`

2024-01-31 20:46 UTC, shane-melton submitted a review, later dismissed

2024-02-02 15:23 UTC, justindbaur requested changes
One minor request on the migration, but looks great!

2024-02-02 15:23 UTC, justindbaur commented on libs/common/src/vault/services/vault-settings/vault-settings.service.ts
> +    this.stateProvider.getGlobal(USER_ENABLE_PASSKEYS);
Kinda loving this style of initializing y'all are doing. Might update some documentation to show this off more prominently.

2024-02-02 15:23 UTC, justindbaur commented on libs/common/src/state-migrations/migrations/14-move-enable-passkeys-to-state-providers.ts
> +    }
I prefer the style of migration that you did in folder service. Basically chain `?.` on the value you care about. If it's not-null, migrate it and avoid re-updating any state if you didn't do any migration. https://github.com/bitwarden/clients/pull/7682/files#diff-571eee65ea4a963fe2b8f96fa783296f55c3111da94db0459b11d58697a4b107R29-R34

2024-02-05 14:38 UTC, justindbaur submitted a review, later dismissed

2024-02-05 20:54 UTC, shane-melton requested changes
Looks like there are some merge conflicts and the `CURRENT_VERSION` in `migrate.ts` has incremented again on `main`.

2024-02-06 20:08 UTC, shane-melton approved these changes

2024-02-06 20:08 UTC, justindbaur submitted a review, later dismissed

2024-02-06 20:12 UTC, shane-melton approved these changes

2024-02-06 20:13 UTC, justindbaur approved these changes

2024-02-06 20:15 UTC, merged