[PM-5560] Implement Autofill Settings state provider
bitwarden/clients pull request #7767
Opened 2024-02-01 15:07 UTC by jprusik

## Type of change

- Tech debt (refactoring, code cleanup, dependency upgrades, etc)

## Objective

- Implement Autofill Settings state provider
- Move handleActivateAutofillPolicy out of PolicyService

## Code changes

- Created Autofill Settings state service
- Replaced instances of state now handled by the Autofill Settings service with their appropriate counterparts
- Created migration script to upgrade or rollback state storage changes

## Notes

- We don't clear out the autofill settings on logout because: a) that's consistent with the current behaviour, and b) the values are only stored locally, so we don't want users to have to reconfigure the extension every time they log back in, and c) the keys/values are not secrets anyway

## TODO
- [x] ~Migration script~
- [x] ~PM-5352, ostensibly~

2024-02-01 15:55 UTC, cagonzalezcs reviewed
Awesome work on this, can't express that enough. Provided some minor nits, overall everything looks solid.

2024-02-01 15:55 UTC, cagonzalezcs commented on apps/browser/src/admin-console/services/browser-policy.service.ts
> +  }
Consistency in naming here could be helpful. We have one `AutofillSettingsService` observable named `activateAutoFillOnPageLoadFromPolicy$` and another named `autofillOnLoad$`.

I feel like maintaining `autofillOnPageLoad$` would be appropriate. `onLoad` can refer to a variety of contexts, would it be on extension load? on vault popup load?

2024-02-01 15:55 UTC, cagonzalezcs commented on apps/browser/src/admin-console/services/browser-policy.service.ts
> +  }
```suggestion
  private async setActivateAutoFillOnPageLoadFromPolicy(settingEnabled: boolean): Promise<void> {
    this.autofillSettingsService.setActivateAutoFillOnPageLoadFromPolicy(!settingEnabled);
  }
```

Nit: naming, the variable name here is kind of ambiguous.

Beyond that though, it seems kind of strange that we are setting the value as a negation `!autofillEnabled`.... I might not have context for why that would be necessary though, but it feels like that kind of action should happen by the caller of this private method, not the method itself...

`this.setActivateAutoFillOnPageLoadFromPolicy(true)` will actually set the value off? Hmm...

2024-02-01 15:55 UTC, cagonzalezcs commented on apps/browser/src/autofill/background/overlay.background.spec.ts
> -      describe("getAutofillOverlayVisibility message handler", () => {
Do we still have coverage of this extension message call?

2024-02-01 15:55 UTC, cagonzalezcs commented on apps/browser/src/autofill/background/overlay.background.ts
> +    getAutofillOverlayVisibility: async () => await this.getOverlayVisibility(),
```suggestion
    getAutofillOverlayVisibility: async () => await this.getOverlayVisibility(),
```

Nit: This `async/await` might be unnecessary, though that likely is unclear from the implementation. The implementation within `this.handleExtensionMessage` will handle resolving the promise from `this.getOverlayVisibility` before sending the value back in the `sendResponse` callback. 

The only way this would potentially be necessary is if `this.getOverlayVisibility` is returning a nested promise... 

For example, if `this.getOverlayVisibility` was structured in the following way, it might be necessary (note the missing `await`)

```
private async getOverlayVisibility(): Promise<Promise<InlineMenuVisibilitySetting>> {
  return firstValueFrom(this.autofillSettingsService.inlineMenuVisibility$);
}
```

This would effectively return a promise which on resolution returns a promise, which would then require a resolution. 

Since you're awaiting the `firstValueFrom`, you likely don't need to await the actual result from `this.getOverlayVisibility`.

2024-02-01 15:55 UTC, cagonzalezcs commented on apps/browser/src/autofill/popup/settings/autofill.component.ts
> +  protected autoFillOverlayVisibility: InlineMenuVisibilitySetting;
👏 👏 👏

2024-02-01 15:55 UTC, cagonzalezcs commented on apps/browser/src/autofill/services/autofill.service.ts
> +  async getShouldAutoCopyTotp(): Promise<boolean> {
Mental note: If we're flipping the contextual meaning of a state value like this, we're going to need to be extra sure that the implementation reflects that expected negation.

2024-02-01 15:55 UTC, cagonzalezcs commented on apps/browser/src/vault/popup/components/vault/current-tab.component.ts
> +      await this.autofillSettingsService.setActivateAutoFillOnPageLoadFromPolicy(false);
This is fun and verbose, and I love verbosity!

That said... would it be a good idea to set private methods to shorten and clean up this code? 

```
private async activateAutoFillOnPageLoadFromPolicy(): Promise<boolean> {
  return await firstValueFrom(this.autofillSettingsService.activateAutoFillOnPageLoadFromPolicy$);
}
```

Nit, of course.

2024-02-01 15:55 UTC, cagonzalezcs commented on libs/common/src/autofill/services/autofill-settings.service.ts
> +export abstract class AutofillSettingsServiceAbstraction {
Nit: From what I've seen, keeping the abstractions and constants in a single file is what Platform has been implementing.

If that's the pattern, let's keep it. I'd prefer if we implemented the implementation, abstractions, and constants in separate files though to keep the focus of each piece of code distinct, as we've done with other parts of the codebase.

2024-02-01 15:55 UTC, cagonzalezcs commented on libs/common/src/autofill/services/autofill-settings.service.ts
> +export class AutofillSettingsService implements AutofillSettingsServiceAbstraction {
Man, this is so visually and aesthetically pleasing to read through.... such a clean implementation

2024-02-01 17:09 UTC, jprusik commented on apps/browser/src/autofill/services/autofill.service.ts
> +  async getShouldAutoCopyTotp(): Promise<boolean> {
Yep - that was my intent, and it should be handled (and will need to be handled in the impending migration script as well), though certainly point out if I've missed flipping the logic somewhere.

Having to reason over a double negative ("it is true that it is not enabled") hinders quickly code scanning and I saw no reason it needed to remain that way, so now is the time to address it.

2024-02-01 17:14 UTC, jprusik commented on libs/common/src/autofill/services/autofill-settings.service.ts
> +export abstract class AutofillSettingsServiceAbstraction {
I noticed both patterns, and I don't have an opinion; left it this way for ease of development, but it's easy enough to move around if that's desired in the review.

2024-02-01 18:39 UTC, jprusik commented on apps/browser/src/autofill/background/overlay.background.ts
> +    getAutofillOverlayVisibility: async () => await this.getOverlayVisibility(),
ah yeah; whoops!

2024-02-01 19:34 UTC, jprusik commented on apps/browser/src/admin-console/services/browser-policy.service.ts
> +  }
bae53cc5a8bff38ece17338d44be22f6155fa46d

2024-02-01 19:34 UTC, jprusik commented on apps/browser/src/admin-console/services/browser-policy.service.ts
> +  }
naming handled in bae53cc5a8bff38ece17338d44be22f6155fa46d

2024-02-01 19:35 UTC, jprusik commented on apps/browser/src/autofill/background/overlay.background.spec.ts
> -      describe("getAutofillOverlayVisibility message handler", () => {
c0a161e27bccd78190b462bcbc00e1fbf83c729f

2024-02-01 19:38 UTC, jprusik commented on apps/browser/src/admin-console/services/browser-policy.service.ts
> +  }
> it feels like that kind of action should happen by the caller of this private method, not the method itself...

Good catch; I completely agree; will resolve...

2024-02-01 19:50 UTC, jprusik commented on apps/browser/src/admin-console/services/browser-policy.service.ts
> +  }
Okay, I'm not sure where the inversion in the private method came from (it wasn't in the original state service method) - I think it was a copy-paste typo.

This should be in line with the original logic now:
66ce97cdbc57759748d3a964dab5463dbe50c22a

2024-02-01 19:51 UTC, jprusik commented on apps/browser/src/vault/popup/components/vault/current-tab.component.ts
> +      await this.autofillSettingsService.setActivateAutoFillOnPageLoadFromPolicy(false);
ba8fce6421de8d1df34a554005006be53ea2a39e

2024-02-01 19:54 UTC, jprusik commented on libs/common/src/platform/services/state.service.ts
> -  }
Note to double-check: this wasn't used anywhere??

2024-02-05 18:19 UTC, MGibson1 commented
@jprusik, can you make sure to remove the settings values from account domain objects, too?

2024-02-05 18:52 UTC, jprusik commented
hrm, I missed this in `apps/browser/src/autofill/content/autofiller.ts` too:

![Screenshot 2024-02-05 at 1 51 55 PM](https://github.com/bitwarden/clients/assets/1556494/dabd6b57-955e-4e9e-9424-0b01559ae59d)

2024-02-05 21:51 UTC, MGibson1 requested changes

2024-02-05 21:51 UTC, MGibson1 commented on libs/angular/src/services/jslib-services.module.ts
you need to add the AutofillSettingService to this module, or it won't be avialble to the services that now depend on it.

That might mean creating a noop version if it's not relevant to clients other than browser

2024-02-05 21:51 UTC, MGibson1 commented on libs/common/src/state-migrations/migrations/15-move-autofill-settings-to-state-providers.ts
> +        }
Given that we still have settings defined in the account object, I think this is a little premature.

Once we've migrated all of them out, we can explicitly delete.

2024-02-05 22:19 UTC, jprusik commented on libs/common/src/state-migrations/migrations/15-move-autofill-settings-to-state-providers.ts
> +        }
https://github.com/bitwarden/clients/pull/7767/commits/c3049004e2523723ff59787d26587a556ccef459

2024-02-05 22:26 UTC, jprusik commented on libs/angular/src/services/jslib-services.module.ts
f8ac7e6007656b03545dd02597a4b2f4057cf255

2024-02-05 22:27 UTC, jprusik commented
> @jprusik, can you make sure to remove the settings values from account domain objects, too?
c3049004e2523723ff59787d26587a556ccef459

2024-02-06 21:46 UTC, MGibson1 approved these changes
This is looking good, but I did have one confusion about the implementation.

2024-02-06 21:46 UTC, MGibson1 commented on apps/browser/src/autofill/content/autofiller.ts
> +    doFillInterval = setInterval(() => doFillIfNeeded(), 500);
Doesn't this now ignore the autofill on page load setting?

2024-02-06 21:57 UTC, jprusik commented on apps/browser/src/autofill/content/autofiller.ts
> +    doFillInterval = setInterval(() => doFillIfNeeded(), 500);
The setting was moved to the injection point in the autofill service:
https://github.com/bitwarden/clients/pull/7767/commits/14621084b0802ee450039184a4c446f7f6c7b6f8#diff-ff919521412a590452c7e201f94d1c80997766b29cf4870faa84275768edc6a8R106-R108

A small resulting difference - before the autofiller content script would execute `setupExtensionEventListeners` regardless of the autofill on load setting. Now, that never executes if the autofill on load setting is false, because the autofiller content script isn't injected in that case. After chatting with @cagonzalezcs , this should be okay and even a bit preferable in terms of avoiding unneeded script injection.

2024-02-06 22:53 UTC, cagonzalezcs reviewed
Had some further thoughts, let me know if you have questions.

2024-02-06 22:53 UTC, cagonzalezcs commented on apps/browser/src/autofill/services/autofill.service.ts
> +
Nit: Can you please add some comments to this methods, similar to how `getOverlayVisibility` is decorated.

2024-02-06 22:53 UTC, cagonzalezcs commented on apps/browser/src/popup/services/services.module.ts
>  import { UserVerificationService } from "@bitwarden/common/auth/abstractions/user-verification/user-verification.service.abstraction";
Note: So this might be out of scope for this PR, but I wonder if we can remove the `getBgService` dependency on the `AutofillService` class now without concern.

2024-02-06 22:53 UTC, cagonzalezcs commented on libs/angular/src/services/jslib-services.module.ts
> +    },
Hmm... is this needed here? Might be worth asking @MGibson1  or @justindbaur about this file. I know that it is used when setting up dependencies within the Angular services module for the popup.... so as a result, you're duplicating the work done within `services.module.ts` in the `browser` scope of the project.

2024-02-07 16:25 UTC, jprusik commented on libs/angular/src/services/jslib-services.module.ts
> +    },
yeah, see https://github.com/bitwarden/clients/pull/7767#discussion_r1478942387

2024-02-07 17:14 UTC, jprusik commented on apps/browser/src/autofill/services/autofill.service.ts
> +
f706aff34cdd6525251549c6b65aaa5b8acd3693

2024-02-07 18:54 UTC, cagonzalezcs submitted a review, later dismissed

2024-02-07 21:11 UTC, shane-melton submitted a review, later dismissed
Changes for Vault look good!

2024-02-07 22:28 UTC, vincentsalucci approved these changes
AC changes approved.
CC: @addisonbeck @eliykat - `PolicyService` touched here, may cause some conflicts with our state service refacators.

2024-02-07 22:37 UTC, MGibson1 approved these changes

2024-02-07 22:48 UTC, eliykat requested changes

2024-02-07 22:48 UTC, eliykat commented on apps/browser/src/admin-console/services/browser-policy.service.ts
> +      .subscribe();
This is backwards - `autofillSettingsService` should subscribe to the public observable (`policyService.policies$`) from its constructor without `policyService` having to know about it. Why pass the observable into `autofillSettingService.handleActivateAutofillPolicy` when it can just subscribe itself to what it needs?

My intention was to delete this `BrowserPolicyService` class when we implement the StateProvider refactor for PolicyService. We can keep it around if there's a real need but I'm not seeing one currently.

2024-02-07 22:48 UTC, eliykat commented on libs/common/src/autofill/services/autofill-settings.service.ts
> +  }
Probably out of scope, and certainly out of my domain experience, but subscribing just to save a value to storage to get it out later seems like an antipattern. Why not just assign the result of this `pipe` directly to `activateAutofillOnPageLoadFromPolicy`?

2024-02-08 15:19 UTC, jprusik commented on libs/common/src/autofill/services/autofill-settings.service.ts
> +  }
Yeah, I probably could have been more thoughtful here (I did drop-in replacements and brought the logic over as-is). I'll take another pass on it and follow up with you offline.

2024-02-08 21:42 UTC, eliykat commented on libs/common/src/autofill/services/autofill-settings.service.ts
> +  }
If it helps, this can definitely be left for a separate PR 🎨. Only my [other comment](https://github.com/bitwarden/clients/pull/7767#discussion_r1482184787) is blocking. But it's your call!

2024-02-08 22:49 UTC, eliykat commented
@jprusik I've pushed some changes to show you what I'm thinking - I thought it was the easiest way to communicate my suggestion asynchronously. I'm happy to discuss further and please feel free to revert anything you don't want. I have not tested it manually.

2024-02-08 22:54 UTC, eliykat commented on libs/common/src/autofill/services/autofill-settings.service.ts
> +  }
We discussed and agreed this was out of scope for this PR.

2024-02-09 18:07 UTC, jprusik commented
> @jprusik I've pushed some changes to show you what I'm thinking - I thought it was the easiest way to communicate my suggestion asynchronously. I'm happy to discuss further and please feel free to revert anything you don't want. I have not tested it manually.

Thanks - looks like the WiP was pretty close, so I appreciate your help getting the last bit over the line 👍

2024-02-11 22:59 UTC, eliykat approved these changes
Nice work thank you 👍

2024-02-12 15:06 UTC, cagonzalezcs approved these changes

2024-02-12 20:36 UTC, MGibson1 approved these changes

2024-02-12 20:39 UTC, cagonzalezcs approved these changes

2024-02-12 21:48 UTC, shane-melton approved these changes

2024-02-12 21:54 UTC, vincentsalucci approved these changes

2024-02-12 22:11 UTC, merged

2024-02-28 17:11 UTC, jprusik commented
See also:

missed dependency injection for Dekstop:
https://github.com/bitwarden/clients/pull/8136/files

(thanks @justindbaur)

2024-03-21 08:13 UTC, silversword411 reviewed
Trying to find source of why "Copy TOTP automatically" is getting unchecked when previously checked

2024-03-21 08:13 UTC, silversword411 commented on apps/browser/src/popup/settings/options.component.ts
> +    this.enableAutoTotpCopy = await firstValueFrom(this.autofillSettingsService.autoCopyTotp$);
I'm trying to track down why the Bitwarden option "Copy TOTP automatically" which was previously checked and enabled by default has recently started getting unchecked on all my computers and browsers (as well as new installs, and new users. (I'm an IT MSP so am deploying and configuring Bitwarden constantly). 
The issue is discussed here: https://community.bitwarden.com/t/just-released-new-inline-auto-fill/61436/14

I see this was changed in Feb, which is around the time I started noticing that my TOTP wasn't getting automatically copied to the clipboard. 
Was this change what is causing that to happen?

I would globally just push out default settings using powershell/batch if I could figure out how to set default options via my RMM software using powershell/batch etc.
Setting options like "Copy TOTP automatically" to enabled.
Setting Autofill > Show auto-fill menu on form fields > When auto-fill icon is selected
And other settings. Any links to methods of doing that via scripts would be appreciated.

2024-03-22 00:03 UTC, silversword411 commented on apps/browser/src/popup/settings/options.component.ts
> +    this.enableAutoTotpCopy = await firstValueFrom(this.autofillSettingsService.autoCopyTotp$);
Derp....missed that PR 😆 Thx!

So there's nothing like admx/gpo/reg keys for implementing Bitwarden preferences on machines?

2024-03-27 16:17 UTC, jprusik commented on apps/browser/src/popup/settings/options.component.ts
> +    this.enableAutoTotpCopy = await firstValueFrom(this.autofillSettingsService.autoCopyTotp$);
I think [enterprise policies](https://bitwarden.com/help/policies/) would be the mechanism you'd typically want, though this particular setting does not have policy coverage at this time.