Wire up key definitions for OrganizationService
bitwarden/clients pull request #7781
Opened 2024-02-02 01:07 UTC by addisonbeck

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

This PR modifies `OrganizationService` to support the new `StateProvider` APIs for managing application state.

This is largely unimplemented code with no intended visible effects to the system. Implementing getting & updating the `organizations` value from `StateProvider` will the next step in this work.

## Code changes

1. Add a `KeyDefinition` object to `OrganizationService` to store the `organization` record in `StateProvider`.
1. Inject `StateProvider` and wiring up `OrganizationService` to read from the `organizations` key definition for the active user account.
1. Expand the capabilities of `OrganizationData` to be able to read itself from a JSON string. Previously this was handled directly by `StateService`.
1. Update tests to include requirements for testing against `StateProvider`.
1. Mark the existing `StateService`-backed `organizations` `Observable` and `BehaviorSubject` as deprecated.

## References

- [`AC-2009`: Transition OrganizationService to use StateProvider](
https://bitwarden.atlassian.net/browse/AC-2009)

2024-02-04 23:22 UTC, eliykat requested changes

2024-02-04 23:22 UTC, eliykat commented on libs/common/src/admin-console/models/data/organization.data.ts
> +    response: Partial<ProfileOrganizationResponse>,
Also, maybe @justindbaur can confirm here, but I don't think we need `fromJSON` methods on data classes. Data classes already represent the jsonified version of the domain object. `fromJSON` is usually needed on domain classes to instantiate Date objects and nested domain classes, and to make sure the object has the right prototype; none of those concerns apply here.

Today I believe we already just yank jsonified data from state and cast it as the data class, without actually instantiating it.

So this would mean you could revert your changes to this file, and your deserializer would just look like:

```ts
deserializer: (obj: OrganizationData) => obj,
```

2024-02-04 23:22 UTC, eliykat commented on libs/common/src/admin-console/services/organization/organization.service.state.ts
I prefer including key definitions at the top of the service that uses it, rather than in a separate file; it's < 5 lines of code and then it's right there. However we may have a standard practice that @justindbaur can point to.

2024-02-04 23:22 UTC, eliykat commented on libs/common/src/admin-console/services/organization/organization.service.ts
While I generally favour smaller PRs, in this case I think the LOC impact is small enough that we can just update the service in a single step rather than introducing dead/redundant code. Also, you've introduced a new public interface and marked the old one as deprecated, but other teams cannot actually start using the new one yet (i.e. they won't get any data from it). So I think that also points towards just doing it all in this PR.

2024-02-04 23:22 UTC, eliykat commented on libs/common/src/admin-console/services/organization/organization.service.ts
> +    );
The `activeUser` prefix is kinda wordy. I see the distinction you're making here, but is it a problem today that it's not expressly stated? It's not a naming convention we use anywhere else. Could it be clarified in a jsdoc comment instead?

Also, changing interface names is going to impact every team that uses it -> more PR reviewers. I suggest it's better to maintain the current interface to the extent we can, and then improve it in a separate ticket if desired. (I'm going to follow my own advice in the PolicyService PR.) That will also let you have a deprecation period where both interfaces are available in tandem, and push the update work onto other teams who use the interface.

(Some interfaces changes may be unavoidable though)

2024-02-05 14:29 UTC, justindbaur commented on libs/common/src/admin-console/models/data/organization.data.ts
> +    response: Partial<ProfileOrganizationResponse>,
So yes, if your data class doesn't do any "shaping" of the jsonified data, you don't need a `fromJSON` or anything and you can return the json-ed data. But I do think that if you are saying it's a `class` it should have the prototype. You could instead use an `interface` or `type` to represent your state since neither of those have a promise of a prototype in my opinion.

2024-02-05 14:38 UTC, addisonbeck commented on libs/common/src/admin-console/models/data/organization.data.ts
> +    response: Partial<ProfileOrganizationResponse>,
I took the first suggestion here, which was to reword the null check behavior in `OrganizationData`'s constructor. See https://github.com/bitwarden/clients/pull/7781/commits/432ca295cd05d0daa241bee28242af062bc48066 for implementation.

I couldn't get rid of `fromJSON()` - and I think doing so would involve a bit of unrelated refactoring work. `OrganizationData` has a `PermissionsApi` object on it that depends on the API model's inheritance chain and confuses the type safety.  In that sense we are shaping the data.  I'm not exactly sure how to best tackle that, but I do feel like it would be better to take as tech debt. I'll get that logged if you think that's acceptable, @eliykat.

2024-02-05 14:44 UTC, addisonbeck commented on libs/common/src/admin-console/services/organization/organization.service.state.ts
I agree with the sentiment here, but there were also tests added specific to the `KeyDefinition` to ensure deserializing works. The test doesn't have any dependency on the service itself, and would create a larger diff on the spec for `OrganizationService`. Both the amount of definitions and the amount of tests for state here are subject to potential growth. With that in mind I see a clear separation between the two pieces and would prefer to keep them apart. 

Let me know if you're strongly against this even considering these implications, I do think both sides have benefits and that inline definitions make the most *immediate* sense.

2024-02-05 14:54 UTC, addisonbeck commented on libs/common/src/admin-console/services/organization/organization.service.ts
I disagree, and think this PR already got too big and could have been smaller. In hindsight I wished I had just written the key definition and its spec, since that alone was a complete change that did end up generating some review discussion. I would like to avoid making this any larger. I removed the deprecation warning for now on https://github.com/bitwarden/clients/pull/7781/commits/83830df0988691624031feb2de98b9b28ce488ce. I don't *think* the new observable is exposed to callers, since it hasn't been added to the `OrganizationService` abstraction, but let me know if I'm misunderstanding how that works and I'll make it private.

2024-02-05 15:03 UTC, addisonbeck commented
@eliykat I realize that I didn't take a lot of the advice given here - let me know if you feel strongly about any of this and we can work it out.

2024-02-06 01:46 UTC, eliykat commented on libs/common/src/admin-console/models/data/organization.data.ts
> +    response: Partial<ProfileOrganizationResponse>,
> But I do think that if you are saying it's a class it should have the prototype. You could instead use an interface or type to represent your state since neither of those have a promise of a prototype in my opinion.

I agree, our current practice basically uses Data classes as types which I've never liked. My comment above was not _really_ intended as an endorsement of that 😁 more just describing current practice.

However I agree with both of you, and in particular @addisonbeck I didn't spot the nested `PermissionsApi` - although technically that's not instantiated either - but it's an argument for trying to maintain prototype chains here for sure. If we want to go this way, I'll update the PolicyService PR to match, and no follow-up ticket required.

Also, we have `Date` objects in this class! [ref](https://github.com/bitwarden/clients/blob/432ca295cd05d0daa241bee28242af062bc48066/libs/common/src/admin-console/models/data/organization.data.ts#L50-L51) That seems wrong to me as `Date`s should be represented as `string`s in data classes because they should be serializable. Any thoughts on that @addisonbeck, if you agree it's a problem do you want to tackle it here or in a separate ticket?

2024-02-06 02:46 UTC, eliykat requested changes
Responded to comment threads above plus one additional item below that I just noticed.

2024-02-06 02:46 UTC, eliykat commented on libs/common/src/admin-console/services/organization/organization.service.state.ts
Ah well, now that you mention it, I think the tests for this file actually belong to the `OrganizationData` class (i.e. the spec file should be `organization.data.spec.ts`) because that's the actual system under test - the `fromJSON` method. imo the KeyDefinition is a simple wiring up which doesn't need to be tested. That would mean the tests move into their own file and the KeyDefinition moves into the service file. Does that change how you think about it at all?

2024-02-06 02:46 UTC, eliykat commented on libs/common/src/admin-console/services/organization/organization.service.ts
> +    );
Good to know - I hadn't seen that! Thank you for the references.

2024-02-06 02:46 UTC, eliykat commented on libs/common/src/admin-console/services/organization/organization.service.ts
Good point about not updating the abstract class yet - I was just focusing on the method itself being public. That should be OK for now, and happy to roll with your preferences here.

2024-02-06 20:33 UTC, addisonbeck commented on libs/common/src/admin-console/services/organization/organization.service.state.ts
That's a good point and does solve all problems for me. Implemented on https://github.com/bitwarden/clients/pull/7781/commits/5711a0fc7049c4c4b540cdd43d3ec88abcef592f

2024-02-06 20:35 UTC, addisonbeck commented on libs/common/src/admin-console/models/data/organization.data.ts
> +  }
Good catch, this would have been a bug for sure. Implemented on https://github.com/bitwarden/clients/pull/7781/commits/441a7b52466a7f7499ce96d4c2c58d0a54c4c099

2024-02-06 23:39 UTC, eliykat approved these changes
Nice work 👍

2024-02-07 00:48 UTC, merged