PM-5955 Multiple Badges Overlap With Permissions Column
bitwarden/clients pull request #7843
Opened 2024-02-07 17:49 UTC by Jingo88

```
- [ X ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Update the badge component so it can be given a width that will not overlap with the column next to it, in this case the permissions column. Also updated the badges so the first two items will not be truncated. 

## Code changes

* `vault-collection-row` Added a viewchild to get the width of the Groups column to pass to the badge components
* `group-name-badge` Updated to take width input and pass it down to `badge-list`
* `badge-list` updated to apply a width to style if given. Updated to not truncate all badges, just the last one or a long one

## Screenshots

The below screenshow shows a Collection with collections

* 2 badges that fit
* 1 long badge
* 3 badges that do not fit
* 4 + badges

![Screenshot 2024-02-06 at 4 16 47 PM](https://github.com/bitwarden/clients/assets/8302660/67b3f732-3ba2-4d69-9b8a-4a72113603cc)

2024-02-08 11:55 UTC, LRNcardozoWDF submitted a review, later dismissed
LGTM!

2024-02-08 18:18 UTC, willmartian requested changes
Generally, I'm not a fan on passing in a specific pixel width to components. Pixels aren't responsive to the font size changing. I think a cleaner solution would be to have the badge list respect the width of its parent (in this case, the table cell). 

Also, I'm not thrilled with the way these convey info:
<img width="166" alt="image" src="https://github.com/bitwarden/clients/assets/17113462/06065d56-5f53-446c-9e6a-684d4732a2a8">

I would prefer that the 1st example displays as: [Admin] [+3 more]
3rd example: [Admin] [+2 more]

However, that change is a bit more complicated and would require inspecting the parent width with JS. We could also flex-wrap badges. 

@bitwarden/dept-design, what is the desired look/behavior for truncated badge lists?

2024-02-08 19:19 UTC, Jingo88 commented
Adding another option for design. if we don't need everything inline it would look like this

![Screenshot 2024-02-08 at 2 17 24 PM](https://github.com/bitwarden/clients/assets/8302660/714108d0-8996-4b16-b461-4cbcfb9200a0)

2024-02-08 20:20 UTC, sukhleenb commented
Definitely prefer your suggestion of wrapping the badges Will!

2024-02-08 20:20 UTC, sukhleenb approved these changes

2024-02-09 14:45 UTC, LRNcardozoWDF submitted a review, later dismissed

2024-02-12 21:52 UTC, willmartian requested changes

2024-02-12 21:52 UTC, willmartian commented on libs/components/src/badge-list/badge-list.component.html
> +<div [ngClass]="{ 'tw-inline-flex': variant !== 'secondary', 'tw-gap-2': true }">
I don't think we want to couple the color variant with the display mode. 

Also, this should still be a flex container to properly utilize `gap`. I think we just need to turn on [flex wrap](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-wrap) with `tw-flex-wrap`.

2024-02-12 21:52 UTC, willmartian commented on libs/components/src/badge-list/badge-list.component.html
> +    </ng-template>
I'm not sure if these changes are warranted. What if the first item in a badge list is very long? We would still want it to truncate, no?

2024-02-13 19:43 UTC, Jingo88 commented on libs/components/src/badge-list/badge-list.component.html
> +<div [ngClass]="{ 'tw-inline-flex': variant !== 'secondary', 'tw-gap-2': true }">
awesome thanks!

2024-02-14 00:31 UTC, willmartian approved these changes
LGTM! Thanks for iterating with me @Jingo88

2024-02-14 18:01 UTC, LRNcardozoWDF approved these changes

2024-02-20 17:08 UTC, merged