[PM-5572] Event upload and collection state provider migration
bitwarden/clients pull request #7863
Opened 2024-02-08 19:24 UTC by ttalty

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Migrate the event collection and event upload service to use the state provider. 

## Code changes

- **apps/browser/src/background/main.background.ts:** Removed the state service from the initialization of event upload and collection services. Added the account service. Also in the logout method userId no longer needs to be sent to uploadEvents.
- **apps/desktop/src/app/app.component.ts:** Upload events does not need a userId sent to it. 
- **libs/angular/src/services/jslib-services.module.ts:** Adding the state provider and account service abstraction for event upload and collection. 
- **libs/common/src/abstractions/event/event-upload.service.ts:** Removing userId from the upload events method abstraction.
- **libs/common/src/models/data/event.data.ts:** Adding the fromJSON method.
- **libs/common/src/platform/state/state-definitions.ts:** Creating the event collection memory definition.
- **libs/common/src/services/event/event-collection.service.ts:** Implementing the state provider. Getting the active user and then getting the single user state for events. Validation is performed on organizations and authenticated status which determines if the update to the user's event collection state should occur. 
- **libs/common/src/services/event/event-upload.service.ts:** Implementing the state provider. Active user is checked for authorization. The event collection from the user's state checked for records and if any are present they are uploaded. Then the state is cleared.

2024-02-09 17:35 UTC, audrey-jensen requested changes
💭 for thoughts that could benefit from discussion
🤔 for open inquiry
⚠️ for concerns needing attention (these are the requested changes)
🎨 for suggestions / improvements

2024-02-09 17:35 UTC, audrey-jensen commented on libs/common/src/services/event/event-collection.service.ts
> +      ),
🎨 I might split this out into a few lines. That would also allow you to inline your comments and easily set breakpoints for debugging.

2024-02-09 17:35 UTC, audrey-jensen commented on libs/common/src/services/event/event-collection.service.ts
> +        events = events == null ? [] : events;
🎨 This can be simplified using nullish coalescing. `events = events ?? [];`

2024-02-09 17:35 UTC, audrey-jensen commented on libs/common/src/services/event/event-collection.service.ts
> +    const organizations = await firstValueFrom(this.organizationService.organizations$);
🤔 It seems like these lines shouldn't be needed. They can be lazily calculated through the observable, instead. The main benefit is it avoids blocking on the `await`s.

2024-02-09 17:35 UTC, audrey-jensen commented on libs/common/src/services/event/event-upload.service.ts
> +        }
🎨 If you return the result of the comparison, then you're always working with an explicit boolean. As written, you're working with `true | undefined`.

2024-02-09 17:35 UTC, audrey-jensen commented on libs/common/src/services/event/event-upload.service.ts
> +      this.clearEvents(activeUserId);
🎨 I'd write this as a `take` instead of a `clear`. That way you can resolve all of the timing issues as the update occurs.

```typescript
private async takeEvents(userId?: UserId) {
  let items = new Promise<EventData[]>();
  await this.stateProvider.getUser(userId, EVENT_COLLECTION).update((current) => {
    items.resolve(current);
    return [];
  });

  // this return always completes synchronously
  return await items;
}
```

2024-02-09 17:35 UTC, audrey-jensen commented on libs/common/src/services/event/event-collection.service.ts
🤔 I wonder whether the event collector data should be encrypted. If it's plaintext, what prevents me from injecting arbitrary events by just editing the backing state?

2024-02-09 17:35 UTC, audrey-jensen commented on apps/browser/src/background/main.background.ts
> +    await this.eventUploadService.uploadEvents();
⚠️ When the user logs out, their event store needs to be deleted. As written, the _active user's event store_ will be deleted. I'd be explicit here, since it's not entirely clear from context when the active user state store changes. (That is, you could end up racing the state provider.)

2024-02-13 19:17 UTC, ttalty commented on libs/common/src/services/event/event-upload.service.ts
> +      this.clearEvents(activeUserId);
Implemented the change to using the takeEvents method similar to what you showed. Here is the code change we landed on:

```typescript
private async takeEvents(userId?: UserId): Promise<any> {
    let taken = null;
    await this.stateProvider.getUser(userId, EVENT_COLLECTION).update((current) => {
      taken = current ?? [];
      return [];
    });

    return taken;
  }
```

2024-02-13 19:18 UTC, ttalty commented on libs/common/src/services/event/event-upload.service.ts
> +        }
Returning the result of the comparison as suggested.

2024-02-13 19:20 UTC, ttalty commented on libs/common/src/services/event/event-collection.service.ts
> +    const organizations = await firstValueFrom(this.organizationService.organizations$);
Removed the organizations await here. The orgIds can be checked in the observable as suggested. I do think the userId is necessary though. Isn't the userId needed to get the user's state provider?

2024-02-13 19:20 UTC, ttalty commented on apps/browser/src/background/main.background.ts
> +    await this.eventUploadService.uploadEvents();
Added back. EventUpload now takes in the UserId object. The calling logic will supply the value cast to the type.

2024-02-13 19:21 UTC, ttalty commented on libs/common/src/services/event/event-collection.service.ts
> +      ),
Good catch. Broken out into a few lines and the comments added inline.

2024-02-13 19:33 UTC, ttalty commented on libs/common/src/services/event/event-collection.service.ts
Had a discussion with Daniel about this. Probably something to be considered in the future.

2024-02-13 22:27 UTC, audrey-jensen commented on libs/common/src/services/event/event-collection.service.ts
Hopefully the [not-too-distant future](https://github.com/bitwarden/clients/pull/7823).

2024-02-13 22:35 UTC, audrey-jensen commented on apps/browser/src/background/main.background.ts
> +    await this.eventUploadService.uploadEvents();
Just an FYI, this may be changing: #7919

2024-02-13 22:39 UTC, audrey-jensen approved these changes
These changes look good overall. I added a comment re: the incoming logout pattern. In short, that'll be changing soon. The other thing you might want to consider is adding documentation for the things you've changed.

2024-02-13 22:48 UTC, audrey-jensen commented on libs/common/src/services/event/event-collection.service.ts
> +    const organizations = await firstValueFrom(this.organizationService.organizations$);
Yes, but the active user can change. I'd probably pass in the userId as a parameter to avoid that possibility. That said, I'll accept your analysis of the code. You know it way better than me.

2024-02-15 13:48 UTC, MGibson1 requested changes

2024-02-15 13:48 UTC, MGibson1 commented on apps/browser/src/background/main.background.ts
> +    // Provide the userId of the user to upload events for
**discussion**: I don't believe this is a meaningful comment. It's not necessary to comment the purpose of parameters at call sites, just in the documentation of the public method itself.

If you feel it's ambiguous what `userId` does, change the name of the method to `uploadEventsFor`

2024-02-15 13:48 UTC, MGibson1 commented on libs/common/src/services/event/event-collection.service.ts
> +        shouldUpdate: (_, shouldUpdate) => shouldUpdate,
IMO this method is much clearer if you eagerly evaluate the `shouldUpdate$` observable with 

```typescript
    const [accountInfo, orgIds, cipher] = await firstValueFrom(
      zip(
        this.accountService.activeAccount$,
        this.organizationService.organizations$.pipe(
          map((orgs) => orgs?.filter((o) => o.useEvents)?.map((x) => x.id) ?? []),
        ),
        from(this.cipherService.get(cipherId)),
      ),
    );
```

up top. It removes a level of indentation throughout the method and makes the update call much more bog-standard.

2024-02-15 13:48 UTC, MGibson1 commented on libs/common/src/services/event/event-upload.service.ts
> +    );
**defect**: your user auth and userId are not necessarily in sync, please use `accountService.accounts` and find the account you're actually working with.

2024-02-15 13:48 UTC, MGibson1 commented on libs/common/src/services/event/event-upload.service.ts
> +      this.takeEvents(userId);
please fix this FIXME

2024-02-15 13:48 UTC, MGibson1 commented on libs/common/src/services/event/event-upload.service.ts
> +    const eventCollection = await firstValueFrom(eventStore.state$);
Your new `takeEvents` method is perfect to simplify this.

You'll need to wrap the api call in another try/catch to repopulate events on a failure, though.

2024-02-15 16:51 UTC, audrey-jensen commented on libs/common/src/services/event/event-collection.service.ts
> +        shouldUpdate: (_, shouldUpdate) => shouldUpdate,
I recommended against using `await firstValueFrom(...)`, because the "bog standard" code is also less reactive. It relies on procedures and closure, where instead we want the code to rely on data flow.

2024-02-15 17:00 UTC, audrey-jensen commented on libs/common/src/services/event/event-upload.service.ts
> +   */
🎨 This should document that it's returning the events it cleared.

2024-02-16 17:00 UTC, ttalty commented on libs/common/src/services/event/event-upload.service.ts
> +    const eventCollection = await firstValueFrom(eventStore.state$);
Used the `takeEvents` to grab the user's events. If failure on upload the catch will repopulate the events.

2024-02-16 17:00 UTC, ttalty commented on libs/common/src/services/event/event-upload.service.ts
> +   */
Modified the comment to better indicate what is going on.

2024-02-16 17:01 UTC, ttalty commented on libs/common/src/services/event/event-upload.service.ts
> +    );
After discussing with Daniel. We don't need to auth the upload events. The auth occurs on the collect. There are cases we would want to upload events for a locked/logged out user. Removed this check.

2024-02-16 17:02 UTC, ttalty commented on libs/common/src/services/event/event-collection.service.ts
> +        shouldUpdate: (_, shouldUpdate) => shouldUpdate,
I think I got this on point with what has been decided. Broke out the cipher observable from the zip.

2024-02-16 17:02 UTC, ttalty commented on apps/browser/src/background/main.background.ts
> +    // Provide the userId of the user to upload events for
Removed comment

2024-02-16 20:55 UTC, audrey-jensen commented on libs/common/src/services/event/event-collection.service.ts
> +        shouldUpdate: (_, shouldUpdate) => shouldUpdate,
Actually, my point was the `this.isEventCollectionEnabled` bit. I'm not sure if Matt is ok with that alternative, however.

2024-02-22 18:31 UTC, ttalty commented on libs/common/src/services/event/event-collection.service.ts
> +        shouldUpdate: (_, shouldUpdate) => shouldUpdate,
The recent push should have this fixed. Moved this to it's own private method for shouldUpdate.

2024-02-23 15:45 UTC, audrey-jensen approved these changes

2024-02-26 14:36 UTC, ttalty commented on libs/common/src/services/event/event-upload.service.ts
> -    const authed = await this.stateService.getIsAuthenticated({ userId: userId });
Yes we do not need to auth on upload. After discussion with Daniel we realized there could be a possibility to have user's events not uploaded.

2024-02-26 21:17 UTC, audrey-jensen submitted a review, later dismissed

2024-02-28 14:01 UTC, ttalty commented on libs/common/src/services/event/event-upload.service.ts
> -    const authed = await this.stateService.getIsAuthenticated({ userId: userId });
Authorization added back.

2024-02-28 19:38 UTC, MGibson1 submitted a review, later dismissed
nice work 👍 thank you

2024-03-05 13:15 UTC, MGibson1 approved these changes

2024-03-05 20:26 UTC, MGibson1 approved these changes

2024-03-12 14:30 UTC, MGibson1 submitted a review, later dismissed
looking good, thank you!

2024-03-12 18:15 UTC, MGibson1 submitted a review, later dismissed

2024-03-18 13:57 UTC, MGibson1 approved these changes

2024-03-18 18:36 UTC, MGibson1 approved these changes

2024-03-18 18:36 UTC, merged