Migrate existing organizations state from `StateService` → `StateProvider`
bitwarden/clients pull request #7895
Opened 2024-02-09 19:08 UTC by addisonbeck

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-02-12 20:40 UTC, justindbaur requested changes
I understand the desire for smaller PR's but I don't like that this will cause there to be 2 places the data is saved. The migration will delete it from the state service location but then if someone uses the application it will get saved there again. To finish this off you'd need another migration just deleting the data.

2024-02-12 21:01 UTC, addisonbeck commented
@justindbaur that makes sense. It is important to me to make incremental steps here for several reasons. Is there any good way for me to "queue" up a migration so that the migration can be written and tested without being implemented yet? I had thought of just removing it from the migration list & renaming the file without a number. Then applying the migration would just involve numbering the migration and applying it to the list. The still seems a little complicated though, so I'm wondering if you've got any better ideas?

2024-02-13 14:24 UTC, justindbaur commented
@addisonbeck There is no way to queue up a migration, moving the backing location of your data is kind of an all or nothing move. If you're trying to keep things small you can delete some of the type assertions in here: https://github.com/bitwarden/clients/pull/7895/files#diff-397e257f75aaf8565e7025b97bbf6d6c0830fb174aceaa38522097a74422f2dcR54-R103

If the properties aren't referenced in the migration code they don't really contribute, what's is most important are the types for the account object shape leading up to your data. Then your data can be represented with an `unknown`. 

Then, if you use the same observable names that the state service ones use you can switch over their backing data right now. Then you can have another 1 or 2 PR's that rename those observables to the new name if you want and one for deleting the state service methods and account property.

With those changes I think this PR would actually be slightly smaller.

2024-02-13 16:47 UTC, addisonbeck commented
Renaming the exposed methods & observables separately is a good idea. I'll go that route, thanks!

2024-02-15 00:09 UTC, addisonbeck commented
@justindbaur @eliykat This ended up getting bigger since many of `OrganizationService`'s methods were made async. Would y'all mind giving it a review before I open it up to teams to review the changes to `OrganizationService` callers?

2024-02-15 04:43 UTC, eliykat requested changes
Looking good overall!

2024-02-15 04:43 UTC, eliykat commented on apps/browser/src/admin-console/background/service-factories/organization-service.factory.ts
The only reason for the browser-specific service classes are to apply the `sessionSync` decorators, which are replaced by `StateProvider`. Therefore you can delete `BrowserOrganizationService` and instantiate `OrganizationService` here instead. (Assuming there is no additional code in the browser service that we need)

2024-02-15 04:43 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts
> +    const organization$ = of(await this.organizationService.get(this.params.organizationId)).pipe(
This can use `organizationService.get$` to get a real observable.

2024-02-15 04:43 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/members/people.component.ts
> +      concatMap(async (params) => await this.organizationService.get(params.organizationId)),
Same here, `concatMap` will take an observable as well.

2024-02-15 04:43 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/reporting/reports-home.component.ts
> +      concatMap(async (params) => await this.organizationService.get(params.organizationId)),
And here, use observable interface

2024-02-15 04:43 UTC, eliykat commented on libs/common/src/admin-console/abstractions/organization/organization.service.abstraction.ts
> +  get: (id: string) => Promise<Organization>;
I am generally in favour of removing all or most getter methods that return a promise, as they tend to encourage bad habits that leave us with a mix of promises and observables (which is where we are today, which is really fragile). Our interfaces should strongly favour exposing observables to encourage consistent reactive data flow throughout the application and "observable-first" logic. So here, for example, I'd deprecate the `get` method in favour of `get$`.

You don't need to do it in this PR as it's already bigger than you wanted, but I thought I'd mention it for consideration/discussion/follow-up.

2024-02-15 04:43 UTC, eliykat commented on libs/common/src/admin-console/services/organization/organization.service.ts
> +    this.memberOrganizations$ = this.organizations$.pipe(map((orgs) => orgs.filter(isMember)));
🎨  I don't think it makes any practical difference, but is there any reason for moving this into the constructor body vs. in the property definition? I like the property definition because then the definition and value are all in one place, and there's less in the ctor.

2024-02-15 04:43 UTC, eliykat commented on libs/common/src/admin-console/services/organization/organization.service.ts
>    }
You can use the new [getUserState](https://github.com/bitwarden/clients/blob/main/libs/common/src/platform/state/implementations/default-state.provider.ts#L24-L33) for this. It takes an optional `userId` as this is a common pattern in our services. [Slack discussion for reference](https://bitwarden.slack.com/archives/C02LPDKPML6/p1707243116762329)

I also recommend changing this and the other methods below to return observables (per comment above), but as I said, not required in this PR.

2024-02-15 04:43 UTC, eliykat commented on libs/common/src/admin-console/services/organization/organization.service.ts
>    }
🎨  Assuming you keep this for now, I suggest using `await firstValueFrom(this.get$(id))` so that the actual logic is in 1 method and this is just a wrapper. It makes it a one-liner as well.

2024-02-15 04:43 UTC, eliykat commented on libs/common/src/admin-console/services/organization/organization.service.ts
>      return new Organization(organization);
This seems identical to `get$` now, can it be deleted?

2024-02-15 04:43 UTC, eliykat commented on libs/common/src/admin-console/services/organization/organization.service.ts
> +    });
@justindbaur do we need to be concerned about shared object references when saving data to state? e.g. if we just did `await this.stateProvider.getActive(ORGANIZATIONS).update(() => organizations)`, is there a risk another method could update in-memory state by then altering that object? (@addisonbeck I assume that's the concern here)

2024-02-15 05:01 UTC, eliykat requested changes

2024-02-15 05:01 UTC, eliykat commented on bitwarden_license/bit-web/src/app/secrets-manager/projects/project/project.component.ts
> +      this.organizationEnabled = this.organizations[params.organizationId]?.enabled;
Possible race condition: `this.organizations` is not guaranteed to be populated by the time `this.organizationEnabled` is assigned its value. I see you're trying to avoid making this method async, but I think you have to commit to a little refactor here.

I suggest using `concatMap` to pass `param.organizationId` to `organizationService.get$`, then return both values so they're available in the subscribe block. (not sure if there's a more elegant way to do this)

2024-02-22 23:31 UTC, addisonbeck commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts
> +    const organization$ = of(await this.organizationService.get(this.params.organizationId)).pipe(
I've reworked these services based on feedback. More specific details posted in a standalone comment below.

2024-02-22 23:31 UTC, addisonbeck commented on apps/web/src/app/admin-console/organizations/members/people.component.ts
> +      concatMap(async (params) => await this.organizationService.get(params.organizationId)),
I've reworked these services based on feedback. More specific details posted in a standalone comment below.

2024-02-22 23:31 UTC, addisonbeck commented on apps/web/src/app/admin-console/organizations/reporting/reports-home.component.ts
> +      concatMap(async (params) => await this.organizationService.get(params.organizationId)),
I've reworked these services based on feedback. More specific details posted in a standalone comment below.

2024-02-22 23:31 UTC, addisonbeck commented on libs/common/src/admin-console/abstractions/organization/organization.service.abstraction.ts
> +  get: (id: string) => Promise<Organization>;
I've reworked these services based on feedback. More specific details posted in a standalone comment below.

2024-02-23 12:30 UTC, addisonbeck commented on libs/common/src/admin-console/services/organization/organization.service.ts
> +    this.memberOrganizations$ = this.organizations$.pipe(map((orgs) => orgs.filter(isMember)));
This was how this snippet looked in other places (documentation, other PRs, etc.), and that's the only reason I did it that way here. After the refactor of the service to be observable-forward this logic is moved. It's in a function, and not a property definition, but I the implementation makes sense the way it is. Let me know what you think!

2024-02-23 12:33 UTC, addisonbeck commented on libs/common/src/admin-console/services/organization/organization.service.ts
>    }
I used `getUserState` for a while, but ended up swapping back to using a conditional for this for a couple reasons:

1. `getUserState` doesn't change when the active user changes, and that isn't the behavior we want here
2.  You can't run `update`s from `getUserState` returns, so we'd need a conditional somewhere in the class anyway to facilitate `replace`'s need to accept a userId for updating.

The whole service has been refactored to use observables for all get operations, and that has been discussed elsewhere.

2024-02-23 12:35 UTC, addisonbeck commented on libs/common/src/admin-console/services/organization/organization.service.ts
>    }
I ended up deleting this method completely during the rewrite in favor of using `organizations$` with an exported operator to filter down to one organization for callers that only need one org.

2024-02-23 12:38 UTC, addisonbeck commented on libs/common/src/admin-console/services/organization/organization.service.ts
> +    });
I think this was detritus from initially hacking this together. The current implementation is the one-liner.

2024-02-23 18:41 UTC, addisonbeck commented on bitwarden_license/bit-web/src/app/secrets-manager/projects/project/project.component.ts
> +      this.organizationEnabled = this.organizations[params.organizationId]?.enabled;
I read about this a bit and ended up combining the `concatMap` solution you mentioned with a pattern of separately declaring observables for different chunks of logic and combining their streams with `combineLatest` before subscribing. Again, I'm no `RxJS` whiz, but this seemed like a clean solution. Let me know what you think.

2024-02-26 01:24 UTC, eliykat commented on libs/common/src/admin-console/services/organization/organization.service.ts
> +    this.memberOrganizations$ = this.organizations$.pipe(map((orgs) => orgs.filter(isMember)));
Thanks for clarifying. I do think it is just code style, so not something we need to get caught up on here.

2024-02-27 01:33 UTC, eliykat reviewed
I fear that my [previous comment](https://github.com/bitwarden/clients/pull/7895#discussion_r1490349272) sent you down the wrong path a bit. I didn't mean that we should overhaul the interface now, just mark some methods as deprecated or make simple substitutions where possible. I think this PR is now unwieldy, it touches 5 other teams for external review, has a diff of ~2k LOC, and would need a lot of manual regression testing.

I thought your last implementation was almost ready to go, my strong preference is to go back to that implementation so we can get this merged and move on to other StateProvider work. We can (and will!) continue to improve the interfaces to our services so we can always revisit this later as tech debt work.

2024-02-27 01:33 UTC, eliykat commented on apps/browser/src/popup/services/services.module.ts
> +      deps: [StateProvider],
This was mentioned in the tech lead sync - manifest v3 can't use `getBgService`, so we need to instantiate our own instance here. But given that we don't have a browser-specific service anymore, I think you could just remove it from here and rely on `jslib-services.module` to bootstrap it for you.

So to summarize, this stateProvider work replaces:
* browser-specific services, e.g. `BrowserOrganizationService`
* sharing the same service between the popup and background via `getBgService`

That's because they all address the same problem, i.e. keeping data in sync between foreground and background (and any other contexts).

2024-02-27 01:40 UTC, eliykat commented on libs/common/src/admin-console/services/organization/organization.service.ts
>    }
1. assuming we go back to this implementation and keep the promise interface, that doesn't really matter because it's getting the value once from that point-in-time anyway
2. you can use `setUserState` for updates

2024-02-27 23:35 UTC, addisonbeck commented on libs/common/src/admin-console/services/organization/organization.service.ts
>    }
I still think we should keep this in its current implementation for when we inevitably do away with the promise based interfaces. This service's data should be reactive to the currently active account by default, so we'd have to put it back later to achieve that. Let me know if you disagree here and it'll get swapped to using the helper methods from state provider as described.

2024-02-27 23:36 UTC, addisonbeck commented on libs/common/src/admin-console/services/organization/organization.service.ts
>    }
Resolving this since it doesn't apply to the service in its current state

2024-02-27 23:36 UTC, addisonbeck commented on libs/common/src/admin-console/services/organization/organization.service.ts
>      return new Organization(organization);
I brought it back to avoid making interface changes

2024-02-27 23:37 UTC, addisonbeck commented on apps/browser/src/popup/services/services.module.ts
> +      deps: [StateProvider],
Implemented as described

2024-02-28 00:02 UTC, addisonbeck commented
Apologies for the miscommunication about making interface changes. I was under the impression you asked for them. I'm not even remotely upset about reverting, as I was not enjoying how large the PR had gotten, even though I did think the changes were for the best.

That said, I didn't *completely* revert things. Here's how the change set looks now:
* There are 0 interface changes that impact callers. Every method signature that existed before still exists now and has not been altered. This means we don't have to bug other teams and can know where the bugs are coming from if they show up. Yay ✨
* I kept all of the new interface methods and mappers. I marked old methods as deprecated, and pointed them to the new ones in their function bodies. This isn't always the most elegant solution (there are several really bad uses of observables in order to facilitate the not-promise based methods that were checking the current value of `_organizations` without async/await), but it does mean we will have an easy time deleting them later.
* I kept all the mapper functions, and still wrote everything as if one observable and a collection of operator functions is the direction we'd go in later when we update callers. I know you had some concerns about this, and figured we'd still talk it through in more detail later, but I do have some arguments in favor of this pattern so I didn't want to scrap what was already written. 
* Once this has had some time to prove itself in production I'd like to handle updating callers to use observable patterns as tech debt on a team-by-team basis, or even more gradually if desired.

2024-02-28 04:46 UTC, eliykat requested changes

2024-02-28 04:46 UTC, eliykat commented on libs/common/src/admin-console/services/organization/organization.service.ts
>    }
This pattern doesn't work - you have a race condition for setting the value of `value`. Is there any reason you didn't use `firstValueFrom` - were you trying to avoid `async`? If so, I don't think there is any way to avoid it, you have to make this async and make callers await it.

(It not being async before was a side effect of using `BehaviorSubject`s, they have an internal cache you can access directly. Now that we don't use those anymore, you have to use `firstValueFrom` to achieve the same thing.)

2024-02-28 04:46 UTC, eliykat commented on libs/common/src/admin-console/services/organization/organization.service.ts
> +    return value;
Same here

2024-02-28 04:46 UTC, eliykat commented on libs/common/src/admin-console/services/organization/organization.service.ts
> +    });
Can be a 1-liner:

```suggestion
    await this.stateFor(userId).update(() => organizations);
```

2024-02-28 04:46 UTC, eliykat commented on libs/common/src/admin-console/models/domain/organization.ts
> +  }
Nice little move here 🧹

2024-02-28 04:46 UTC, eliykat commented on libs/common/src/admin-console/abstractions/organization/organization.service.abstraction.ts
I know we have exported functions in this file already, but given that your new ones are only used within `OrganizationService` at the moment, please move them into that file and do not export them. At the moment they're basically part of the implementation of that service so they should remain internal. 

Similarly, I think it's premature to mark existing methods as deprecated. We'll discuss what the OrganizationService interface should look like, but if we're keeping the current interface for now then we shouldn't be marking it as deprecated.

2024-02-28 04:46 UTC, eliykat commented on libs/common/src/admin-console/abstractions/organization/organization.service.abstraction.ts
> +export function mapToExcludeSpecialOrganizations() {
`Special` organizations is unclear (without reading the jsdoc), I suggest `ProviderOrganizations` instead.

2024-02-28 04:46 UTC, eliykat commented on libs/common/src/admin-console/services/organization/organization.service.ts
>      return Object.values(organizationsMap || {}).map((o) => new Organization(o));
`getOrganizationsFromState$` returns an observable that emits an array, not a record/map. You should be able to return it directly.

2024-02-28 17:13 UTC, addisonbeck commented on libs/common/src/admin-console/services/organization/organization.service.ts
> +    });
https://github.com/bitwarden/clients/pull/7895/commits/cea6af0d1bb54d1ac941d60e4d4261db45c5de95

2024-02-28 23:16 UTC, addisonbeck commented on libs/common/src/admin-console/services/organization/organization.service.ts
>      return Object.values(organizationsMap || {}).map((o) => new Organization(o));
Good catch, thank you

2024-02-28 23:16 UTC, addisonbeck commented on libs/common/src/admin-console/abstractions/organization/organization.service.abstraction.ts
> +export function mapToExcludeSpecialOrganizations() {
Renamed as suggested

2024-02-28 23:16 UTC, addisonbeck commented on libs/common/src/admin-console/abstractions/organization/organization.service.abstraction.ts
Moved

2024-02-28 23:16 UTC, addisonbeck commented on libs/common/src/admin-console/services/organization/organization.service.ts
>    }
Changed to promises

2024-02-28 23:16 UTC, addisonbeck commented on libs/common/src/admin-console/services/organization/organization.service.ts
> +    return value;
Changed to promises

2024-02-28 23:24 UTC, addisonbeck commented
A tech debt ticket has been created for paying the tech debt associated with this PR: The service's continued use of promises. https://bitwarden.atlassian.net/browse/AC-2252?focusedCommentId=52426

2024-03-01 03:05 UTC, eliykat requested changes
Very minor feedback only, mostly thoughts for later after I read through our other discussions. Thank you for a good review process and thinking critically about how our services should work!

2024-03-01 19:07 UTC, addisonbeck commented on libs/common/src/admin-console/services/organization/organization.service.ts
>    }
I agree. To me the best place for domain logic to exist is in the model the rule is about.

2024-03-01 19:08 UTC, addisonbeck commented on libs/common/src/admin-console/services/organization/organization.service.ts
> +    );
Yeah, I've already rewritten this function for the provider service too. I'll make a note for us to resolve this in some way in the tech debt item.

2024-03-01 21:53 UTC, addisonbeck commented on libs/common/src/admin-console/abstractions/organization/organization.service.abstraction.ts
> +   * provided.
Addressed on https://github.com/bitwarden/clients/pull/7895/commits/b6a163262d9ee94c2df294b371d7050f2713c701

2024-03-01 21:56 UTC, addisonbeck commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/new-menu.component.ts
> +        this.organizationEnabled = mapResult?.organization?.enabled;
That makes sense. I'll leave it for now (null checking is never explicitly bad), but code owners can chime in if they disagree.

2024-03-03 21:56 UTC, eliykat approved these changes

2024-03-03 23:28 UTC, eliykat reviewed
Github hid the test code from me and I missed it 🤦 tests are very thorough and this feedback is pretty minor, so please feel free to start chasing up reviews from others in the meantime.

2024-03-03 23:28 UTC, eliykat commented on libs/common/src/admin-console/services/organization/organization.service.spec.ts
> +      expect(result).not.toEqual(undefined || null || []);
This will evaluate to `expect(result).not.toEqual([]);`. Is that what you wanted? Or do you mean

```ts
expect(result).not.toEqual(undefined);
expect(result).not.toEqual(null);
expect(result).not.toEqual([]);
```
?

In any case, I suggest this assertion is unnecessary because the next assertion will fail if the value is undefined, null, or `[]`.

2024-03-03 23:28 UTC, eliykat commented on libs/common/src/admin-console/services/organization/organization.service.spec.ts
> +      ).toBeTruthy();
I'm having trouble following the data generation here. Why would the `id` be equal when the updated org has been generated with the `UPDATED` suffix? Doesn't that make the `id` different?

I also think the assertions here could be improved. This might replace my previous comment now that I see how you're using this - could you replace all this with:

```ts
expect(result).toEqual(mockData
  .map(x => new Organization(x)
  .splice(indexToUpdate, 1, anUpdatedOrganization));
```

Same in the next test.

2024-03-03 23:28 UTC, eliykat commented on libs/common/src/admin-console/services/organization/organization.service.spec.ts
> +      ).toBeTruthy();
(💭 As an aside, I think this is a risk with making your tests too programmatic; you end up reimplementing the logic of the SUT, or (for me at least) you have to reason too much about the logic of your test code to make sure that _it_ works how you expect. I much prefer static values, even if that's a bit repetitive. No need to action this sub-comment, I've followed your paradigm here in providing feedback, just wanted to mention it.)

2024-03-03 23:28 UTC, eliykat commented on libs/common/src/admin-console/services/organization/organization.service.spec.ts
> +  }): Promise<[UserId, OrganizationData[]]> {
This is always called with `createWithTestOrgs = true`, I suggest you remove the parameter to simplify it (unless you had some tests that used this that you expect to restore in the near future?)

2024-03-04 10:19 UTC, djsmith85 requested changes
Approving changes to tools, just one comment on the OrgService

2024-03-04 10:19 UTC, djsmith85 commented on libs/common/src/admin-console/services/organization/organization.service.ts
> +    return await firstValueFrom(this.organizations$.pipe(mapToSingleOrganization(id)));
We should remove this method, especially since `get` does the exact same thing.
If for some reason this breaks the CLI we need to address it, as the migration of storage will break the existing implementation.

2024-03-05 01:27 UTC, eliykat commented on libs/common/src/admin-console/services/organization/organization.service.ts
> +    return await firstValueFrom(this.organizations$.pipe(mapToSingleOrganization(id)));
> We should remove this method, especially since get does the exact same thing.

I agree, but we started to change the interface and that quickly got out of hand due to how widely this service is used. This will be handled in a follow-up ticket.

> If for some reason this breaks the CLI we need to address it, as the migration of storage will break the existing implementation.

It shouldn't break anything, it's just a wrapper to minimize impact on other areas of the code.

2024-03-05 13:53 UTC, djsmith85 commented on libs/common/src/admin-console/services/organization/organization.service.ts
> +    return await firstValueFrom(this.organizations$.pipe(mapToSingleOrganization(id)));
I only see 4 instances within the CLI where `getFromState` is used and they should be fine to be replaced with calling `get` instead.
I'm okay with handling this in a follow up ticket (presumably [AC-2252](https://bitwarden.atlassian.net/browse/AC-2252)), but then I'd prefer to keep the `@deprecated`-label for `getFromState` on the [OrgSvc-abstraction](https://github.com/bitwarden/clients/pull/7895/files#diff-f2058abda4c6915d9795428d41060ce253e3d71777e73061178c8af4e9b62040L103-L106) until then.

2024-03-05 22:53 UTC, addisonbeck commented on libs/common/src/admin-console/services/organization/organization.service.ts
> +    return await firstValueFrom(this.organizations$.pipe(mapToSingleOrganization(id)));
I added back the deprecation notice on 

[Add back a deprecation notice](https://github.com/bitwarden/clients/pull/7895/commits/36434d17497b86d16cc9e48914d41da4b0d2ea65)

2024-03-05 22:55 UTC, addisonbeck commented on libs/common/src/admin-console/services/organization/organization.service.spec.ts
> +  }): Promise<[UserId, OrganizationData[]]> {
I had this as an argument because it just seemed like a bit of a side effect of the function that may not always be desirable in the future. It's definitely not needed right now though, so I've removed it as request. This and the change to remove directly creating a non active account were implemented on

[Remove unecassary test logic](https://github.com/bitwarden/clients/pull/7895/commits/d91d84248683858ab61e2a1451ac0096d8a1b9ee)

2024-03-05 22:58 UTC, addisonbeck commented on libs/common/src/admin-console/services/organization/organization.service.spec.ts
> +      expect(result).not.toEqual(undefined || null || []);
Yeah, I was obviously misunderstanding the way the or operator would work in this context, whoops. Removed this assertion as requested on

[Remove complex and unecassary assertion](https://github.com/bitwarden/clients/pull/7895/commits/0429340e4e42bb4156f578b43f292601a62e2618)

2024-03-06 11:30 UTC, djsmith85 approved these changes

2024-03-06 16:23 UTC, Jingo88 approved these changes

2024-03-07 21:28 UTC, coltonhurst approved these changes
SM changes look good, thanks @addisonbeck

2024-03-08 16:00 UTC, justindbaur requested changes
Just one recommendation.

2024-03-08 16:00 UTC, justindbaur commented on libs/common/src/admin-console/services/organization/organization.service.ts
>  export const ORGANIZATIONS = KeyDefinition.record<OrganizationData>(
Just recently we added a new key definition type a `UserKeyDefinition` which offers the ability to clear user state during `lock` and/or `logout` events, the docs are still in progress but it's fully implemented already. I'd encourage you to convert this to that and then define the new required `clearOn` property like `["logout"]`. This would mean you can get rid of the changes in the various `logout` methods in app components and main for CLI and browser.

2024-03-11 04:15 UTC, eliykat approved these changes
Re-reviewed the tests, the additional changes look good, although [this comment](https://github.com/bitwarden/clients/pull/7895#discussion_r1510425117) doesn't appear to have been actioned. Given the number of changes/reviewers I consider it non-blocking but wanted to mention it just in case.

2024-03-12 11:57 UTC, cyprain-okeke approved these changes
Billing changes Looks good

2024-03-13 00:51 UTC, eliykat commented on libs/common/src/admin-console/services/organization/organization.service.spec.ts
>    }
I clearly blanked on this when we were discussing it. Because you're using `===` instead of Jest's `toEqual`, it's checking reference equality instead of value equality. This will always return false, which I'm assuming it is because your tests are failing.

I suggest moving the assertion inside this function:

```suggestion
  function isEqualExceptForIndex(x: any[], y: any[], indexToExclude: number) {
    // Clone the arrays to avoid modifying the reference values
    const a = [...x];
    const b = [...y];
    delete a[indexToExclude];
    delete b[indexToExclude];
    expect(a).toEqual(b);
  }
```

and then calling it on its own (not part of a jest expect statement):

```ts
// other assertions
isEqualExceptForIndex(a, b, 5);
```

Renaming it to `expectIsEqualExceptForIndex` might make that usage a bit clearer.

2024-03-13 19:12 UTC, addisonbeck commented on libs/common/src/admin-console/services/organization/organization.service.spec.ts
>    }
Good catch, implemented as suggested.

2024-03-13 19:13 UTC, addisonbeck commented on libs/common/src/admin-console/services/organization/organization.service.spec.ts
> +      ).toBeTruthy();
We talked about this a bit elsewhere - resolving with the change to `expectToEqualExceptForIndex`

2024-03-13 19:13 UTC, addisonbeck commented on libs/common/src/admin-console/services/organization/organization.service.spec.ts
> +    );
See comment below for more details, but this is resolved

2024-03-13 22:40 UTC, coltonhurst approved these changes
SM changes look good!

2024-03-14 00:12 UTC, eliykat submitted a review, later dismissed

2024-03-14 12:15 UTC, Jingo88 approved these changes

2024-03-14 12:28 UTC, justindbaur approved these changes

2024-03-14 15:19 UTC, djsmith85 submitted a review, later dismissed

2024-03-14 19:12 UTC, djsmith85 approved these changes

2024-03-14 23:22 UTC, eliykat submitted a review, later dismissed

2024-03-14 23:27 UTC, justindbaur approved these changes

2024-03-15 10:53 UTC, cyprain-okeke submitted a review, later dismissed

2024-03-15 18:59 UTC, Jingo88 submitted a review, later dismissed

2024-03-15 19:50 UTC, justindbaur approved these changes

2024-03-15 23:51 UTC, justindbaur approved these changes

2024-03-16 16:19 UTC, djsmith85 approved these changes

2024-03-17 22:12 UTC, eliykat approved these changes

2024-03-18 12:18 UTC, Jingo88 approved these changes

2024-03-18 16:58 UTC, cyprain-okeke approved these changes

2024-03-18 16:58 UTC, merged