[PM-5266] Create Avatar Service
bitwarden/clients pull request #7905
Opened 2024-02-12 05:45 UTC by rr-bw

- rename file, move, and update imports
- refactor and implement StateProvider
- remove comments

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-02-15 18:53 UTC, rr-bw commented on libs/common/src/state-migrations/migrations/22-move-avatar-color-to-state-providers.spec.ts
> +      sut = new AvatarColorMigrator(21, 22);
@justindbaur I've seen these version numbers ordered differently for the `rollback()` tests in other migration test files. See [here](https://github.com/bitwarden/clients/blob/fae12cd0e6f9fb2212e3d2bbc137d00791c62258/libs/common/src/state-migrations/migrations/19-migrate-require-password-on-start.spec.ts#L91-L92) and [here](https://github.com/bitwarden/clients/blob/fae12cd0e6f9fb2212e3d2bbc137d00791c62258/libs/common/src/state-migrations/migrations/18-move-autofill-settings-to-state-providers.spec.ts#L145-L146), for examples. Can you confirm that I have the correct order here?

2024-02-15 21:12 UTC, jlf0dev commented on apps/browser/src/auth/popup/account-switching/current-account.component.ts
>    ) {}
can we just get rid of the `CurrentAccountService` entirely and move the logic here in the component?

2024-02-16 18:59 UTC, rr-bw commented on apps/browser/src/auth/popup/account-switching/current-account.component.ts
>    ) {}
@jlf0dev Yea good call

2024-02-19 20:07 UTC, jlf0dev commented on apps/web/src/app/vault/components/vault-items/vault-items.stories.ts
> +          } as Partial<AvatarService>,
I think you could also do `from("#FF000")`, maybe. Would need to test that.

2024-02-19 20:08 UTC, jlf0dev commented
CLI is failing, probably just a missed dependency

2024-02-19 23:27 UTC, rr-bw commented on apps/web/src/app/vault/components/vault-items/vault-items.stories.ts
> +          } as Partial<AvatarService>,
I think you mean `of()`? Tested and it works.

2024-02-19 23:45 UTC, rr-bw commented on apps/browser/src/auth/popup/account-switching/current-account.component.ts
> +      await this.router.navigate(["/account-switcher"]);
Yes, tested and it still works.

2024-02-20 13:51 UTC, jlf0dev submitted a review, later dismissed
Looks good!

2024-03-08 14:47 UTC, justindbaur commented on libs/common/src/state-migrations/migrations/22-move-avatar-color-to-state-providers.spec.ts
> +      sut = new AvatarColorMigrator(21, 22);
I'm so sorry for missing this mention, but you are correct the rollback should be the "to" version which you have there. We've actually since gone back through the rest of the migration tests to fix them to have the correct version.

2024-03-08 15:08 UTC, justindbaur approved these changes
This looks fantastic, just a couple minor things. 

I'm so sorry for taking so long to give this a review. Always feel free to ping me to remind me.

2024-03-08 15:08 UTC, justindbaur commented on libs/common/src/state-migrations/migrations/30-move-avatar-color-to-state-providers.ts
> +        await helper.set(userId, account);
I like to move these two calls inside of the `if` block that moves it to the new key, it can help avoid an extra write when it was likely there was nothing to move.

2024-03-12 20:31 UTC, rr-bw commented on libs/common/src/auth/services/avatar.service.ts
> +  }
Absolutely. Does this look good? https://github.com/bitwarden/clients/pull/7905/commits/5326b04a92c043208fb996ed28ce2896aa180f0a

2024-03-12 20:41 UTC, justindbaur commented on libs/common/src/auth/services/avatar.service.ts
> +  }
Perfect, thanks!

2024-03-12 21:12 UTC, rr-bw commented
@justindbaur Thanks! Merged main and fixed the conflict.

2024-03-12 21:12 UTC, justindbaur approved these changes
Awesome, thanks!

2024-03-12 21:19 UTC, shane-melton requested changes
Vault changes look good! 

Though it looks like the test job is failing and we'll want that fixed before merging with `main`.

2024-03-14 15:34 UTC, shane-melton submitted a review, later dismissed
Vault looks good!

2024-03-14 15:36 UTC, justindbaur submitted a review, later dismissed

2024-03-14 15:47 UTC, justindbaur approved these changes

2024-03-14 15:48 UTC, shane-melton approved these changes

2024-03-14 16:56 UTC, merged