Provide life cycle event handler.
bitwarden/clients pull request #7919
Opened 2024-02-12 19:30 UTC by MGibson1

Services will register with the global events list and the `LifeCycleService` will ensure all handlers are called. This pattern allows for a single file to contain all information for the complete lifecycle of account state.

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Creates a pattern to move account lock and logout event handling into a service directly. This reduces spread of concerns related to that services' state hopefully to the single file.

More events can be registered and handled by updating `RegistrationTarget` and `LifeCycleService`s.

I've moved all logout concerns to this pattern. One important note while reviewing is that services _must_ be initialized in order for the decorator to register them for event hooks. This is because we currently need a real instance to operate on. **Please ensure any class you own is instantiated in all clients for any logout event or these callbacks may not run**.

## Code changes

### Life Cycle stuff
I created two life cycle events that are tied to account operations, but we can add arbitrary things eventually. There are two ways to register your handler
1. the `respondsTo` decorator -- registers your class on initialization as responding to the specified event
2. `LifeCycleService.register` -- registers the provided class to the provided event.

- **respondsTo**: Defines the decorator, known life cycle events, and the expected interface to respond to that event.
- **LifeCycleService**: actually executes registered event handlers. Event handlers are stored in a global variable

#### logout updates

These are all of the team-level updates. Please make sure that your services are instantiated in each client and the logout callback is appropriate.

### lock updates

I elected not to update lock in the same way as logout, but new usages of `respondsTo('lock')` will be called appropriately through the vault timeout service, for now (aside: is this really the right place to handle locks?)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-02-13 16:05 UTC, audrey-jensen requested changes
👍🏻 - kudos
⛏️ - nitpicks
⚠️ - concerns
❓ - open-ended questions
💭 - musings that might benefit from discussion

2024-02-13 16:34 UTC, MGibson1 commented on libs/common/src/platform/lifecycle/responds-to.decorator.ts
> +function isLifeCycleEventHandler<T extends LifeCycleEvent>(
I see where you're coming from, but the point of this method is to cast `T` into the desired handler through the `is` keyword.

2024-02-13 16:34 UTC, MGibson1 commented on libs/common/src/platform/lifecycle/responds-to.decorator.ts
> +};
yes

2024-02-13 16:37 UTC, audrey-jensen commented on libs/common/src/platform/lifecycle/responds-to.decorator.ts
> +function isLifeCycleEventHandler<T extends LifeCycleEvent>(
It creates a type assertion on line 61 allowing line 62 to type check properly?

2024-02-13 16:37 UTC, MGibson1 commented on libs/common/src/platform/lifecycle/responds-to.decorator.ts
> + * critical to be called, make sure your class is instantiated at application start.
Seems reasonable.

As for DI, I'd originally mentioned things like what you say, but DI isn't ubiquitous everywhere this is used and you actually don't need a singleton -- calling the constructor is more precise 👍

2024-02-13 16:42 UTC, MGibson1 commented on libs/common/src/platform/lifecycle/responds-to.decorator.ts
> +function isLifeCycleEventHandler<T extends LifeCycleEvent>(
it's a [type guard](https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-guards-and-differentiating-types), so it's line 72 `instance is LifeCycleInterface<T>` that does the type casting.

2024-02-13 16:43 UTC, MGibson1 commented on libs/common/src/platform/lifecycle/responds-to.decorator.ts
> +function isLifeCycleEventHandler<T extends LifeCycleEvent>(
oh just realized you're referencing where it's used. Yes, that's why it exists.

2024-02-13 17:00 UTC, audrey-jensen approved these changes
👍🏻 Looking forward to using this in tools services soon!

2024-02-13 19:16 UTC, jlf0dev approved these changes

2024-02-14 14:16 UTC, willmartian requested changes
Why is this decorator approach favored over a simple observable? Are there complexities that the following doesn't capture?

```ts
@Injectable({ providedIn: 'root' })
export class AccountLifecycleService {
  private _logout$ = new Subject<string>();
  logout$ = this._logout$.asObservable();

  logout(userId: string) {
    this._logout$.next(userId);
  }
}

@Injectable({ providedIn: 'root' })
export class FooService {
  constructor(private accountLifecycleService: AccountLifecycleService) {
    this.accountLifecycleService.logout$.subscribe((userId) => {
      console.log('FooService on logout', userId);
    });
  }
}
```

2024-02-14 15:00 UTC, MGibson1 commented
@willmartian There are concerns around subscribing.

First some specifics that you probably didn't mean to be part of your point: Angular is a no-no in most of these services, since they are used in non-angular contexts.

To the observable point, though. 
1. We would like things to be as lazy as possible
2. There are complications due to services running in multiple clients with different separations of background/foreground concerns. Browser is the odd-one-out here, where we want most work to be done in a background because there are many views.
3. These services aren't _really_ singletons and totally lack destruction

2024-02-15 17:02 UTC, MGibson1 commented
Since lock/logout are such special lifecycle events for state, we're going to build this into key definitions directly.

This will also allow us to save meta-data of known keys, which allows a fixup operation should crashes occur mid-deletions

2024-02-15 17:02 UTC, closed without merging