PM-4109 Vault Onboarding M2
bitwarden/clients pull request #7920
Opened 2024-02-12 20:10 UTC by Jingo88

```
- [ ] Bug fix
- [ X ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

- Users Web Vault will check if the Bitwarden Extension is installed and will complete the task in the onboarding component
- When all tasks completed the onboarding component will remain on the page until refresh/log out +log in
- Once the component is dismissed or all tasks are completed. Onboarding will not show again even if the user deletes extension, or deletes all items in vault
- The text for the Import Data field has been updated. The second sentence is dynamic based on if user is confirmed in orgs
- Install Link is now an `<a>` tag for A11y
- All features from Onboarding M1 remain the same

NOTE: The screen recording below will cover these use cases

## Code changes

- `content-message-handler` - add a listener that will post a message saying the extension does exist
- `vault-onboarding.component` 
   - check for organizations for dynamic text in import data. 
   - Made some logic updates to keep the onboarding component on screen while all tasks are completed, until the user refreshes or logs out
   - Added methods to post and listen for if extension exists
- `messages.json` updated text fields and descriptions
- spec files updated

## Screen Recording

https://github.com/bitwarden/clients/assets/8302660/90047a43-3e28-4e04-bdef-43f60a25037e

2024-02-20 18:54 UTC, cagonzalezcs commented on apps/browser/src/autofill/content/content-message-handler.ts
> +  checkIfBWExtensionInstalled: () => window.postMessage({ command: "hasBWInstalled" }),
Looks like we're missing a couple of things here.

- The typing information for this key hasn't been added to the `ContentMessageWindowEventHandlers` type. Minor nit, but it wouldn't be a bad idea to facilitate inclusion of that typing information
- This is a nit as well, but would it be possible to pull the `window.postMessage({ command: "hasBWInstalled" })` to a separate method to keep consistent with the way these handlers are called?
- We seem to be missing a test for this added handler

2024-02-20 23:59 UTC, shane-melton requested changes
We need to make sure we clean up any window event listeners we add. Otherwise, this looks good! Nice work!

2024-02-20 23:59 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault-onboarding/vault-onboarding.component.html
> +        <span *ngIf="orgs.length === 0">
question: Any concern for a `null` orgs array here? We always seem to have issues with org arrays being null on startup and throwing exceptions.

2024-02-20 23:59 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault-onboarding/vault-onboarding.component.ts
> +      window.addEventListener("message", (event) => this.getMessages(event));
issue: We need to make sure we remove this `eventListener` when this component is destroyed. At the moment, this appears to re-add a new listener every time the vault onboarding component is rendered. 

Ideally, we should be able to make use of the [`fromEvent`](https://rxjs.dev/api/index/function/fromEvent) rxjs function and subscribe with our normal `takeUntil(destroy$)` pattern so we don't have to worry about explicitly cleaning up the event listener.

2024-02-21 21:28 UTC, cagonzalezcs commented on apps/web/src/app/vault/individual-vault/vault-onboarding/vault-onboarding.component.ts
> +      window.addEventListener("message", (event) => this.getMessages(event));
Also keep in mind that if you pass an anonymous function to a handler, there is no way to clean up the listener's associate with that handler.

You need to ensure you name the method in order to properly call `window.removeEventListener` on it.

2024-02-22 15:06 UTC, Jingo88 commented on apps/browser/src/autofill/content/content-message-handler.ts
> +  checkIfBWExtensionInstalled: () => window.postMessage({ command: "hasBWInstalled" }),
thanks. cleaned up the typings and made a separate method

2024-02-22 15:07 UTC, Jingo88 commented on apps/web/src/app/vault/individual-vault/vault-onboarding/vault-onboarding.component.html
> +        <span *ngIf="orgs.length === 0">
hmmmm good call. So far I haven't run into anything other than `[]` but i'll put a null check in there for safety

2024-02-22 15:08 UTC, Jingo88 commented on apps/web/src/app/vault/individual-vault/vault-onboarding/vault-onboarding.component.ts
> +      window.addEventListener("message", (event) => this.getMessages(event));
awesome. appreciate it

2024-02-22 18:11 UTC, shane-melton requested changes
Looking good! Just one more question and small issue with the null check.

2024-02-22 19:41 UTC, Jingo88 commented on apps/web/src/app/vault/individual-vault/vault-onboarding/vault-onboarding.component.ts
> +      fromEvent<MessageEvent>(window, "message")
ah good calls. moved the code around. thanks

2024-02-22 19:42 UTC, shane-melton approved these changes

2024-02-22 21:45 UTC, cagonzalezcs approved these changes

2024-02-27 15:06 UTC, cagonzalezcs approved these changes

2024-02-27 15:14 UTC, shane-melton approved these changes

2024-02-27 15:18 UTC, merged