[PM-5272] Migrate CollapsedGroupings to State Provider
bitwarden/clients pull request #7954
Opened 2024-02-14 19:02 UTC by gbubemismith

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-02-14 20:00 UTC, shane-melton requested changes
Looks great! Only thing left is removing the `collapsedGroupings` from the `AccountSettings` model.

2024-02-14 20:00 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault-filter/services/vault-filter.service.spec.ts
kudos: Thanks for this example of mocking the state provider!

2024-02-15 02:00 UTC, gbubemismith commented on libs/angular/src/vault/vault-filter/services/vault-filter.service.ts
> +  private collapsedGroupingsState: ActiveUserState<string[]> =
I am liking the `Opaque<?>` type

2024-02-15 17:39 UTC, shane-melton submitted a review, later dismissed
Awesome, looks good and thanks for cleaning up those other deprecated account properties as well!

2024-02-15 17:55 UTC, MGibson1 commented on libs/angular/src/vault/vault-filter/services/vault-filter.service.ts
> +  private collapsedGroupingsState: ActiveUserState<string[]> =
I've tried this for vault filters before and even a simpler `Guid` generic is hard to apply because it's not very strict about what a filter is.

I would _absolutely love_ stricter requirements, but I think that's a taller order than one would expect.

2024-02-15 18:09 UTC, MGibson1 requested changes
One tests request and a couple of questions, please.

Otherwise this is looking good 👍

2024-02-15 18:09 UTC, MGibson1 commented on apps/web/src/app/vault/individual-vault/vault-filter/services/vault-filter.service.spec.ts
> -    it("updates observable when saving", (complete) => {
**blocking**: I think we discussed indirectly issues with the fake state wiring up from update to `state$` emitting data.

While I think that's internal to the state, I would replace this test to one that validates that it sets state when saving, which would validate that `collapsedGroupinsState.update` was called.

You can also verify that the next value is what was expected with the `nextMock` property on the fake state

2024-02-15 18:09 UTC, MGibson1 commented on libs/common/src/platform/models/domain/account.ts
> -  folders? = new TemporaryDataEncryption<FolderData>();
:warning: This doesn't appear to be related, is this intended?

2024-02-15 18:09 UTC, MGibson1 commented on libs/common/src/platform/models/domain/global-state.ts
> -  enablePasskeys?: boolean;
⚠️ This doesn't appear to be related, is this intended?

2024-02-15 18:41 UTC, gbubemismith commented on libs/common/src/platform/models/domain/global-state.ts
> -  enablePasskeys?: boolean;
I worked on the migration for `enablePasskeys` but forgot to remove the property.

2024-02-15 18:41 UTC, gbubemismith commented on libs/common/src/platform/models/domain/account.ts
> -  folders? = new TemporaryDataEncryption<FolderData>();
I worked on the migration for `folders ` but forgot to remove the property

2024-02-16 14:06 UTC, MGibson1 approved these changes

2024-02-16 17:52 UTC, Jingo88 approved these changes

2024-02-16 17:53 UTC, merged