DEVOPS-1743 Web Vault Migration workflow improvements
bitwarden/clients pull request #7966
Opened 2024-02-15 17:20 UTC by urbinaalex17

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Use `az storage blob sync` to sync the compile Web Vault code to the Storage Account to avoid downtime.

## Code changes

- **deploy-web:** Deployment commands and GitHub Workflow readability

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-02-15 21:09 UTC, vgrassia requested changes
Since this fix also applies to the production Web Vaults, we cannot use `preview` commands. Microsoft states that those commands can change at any time, including complete removal.

2024-02-15 21:44 UTC, mimartin12 requested changes
While we are here, it looks like this workflow could be updated so that the linter can pass.
https://github.com/bitwarden/clients/pull/7966/files#diff-875a32a9bd9123a01ecb0b1802809c712a8a04f695e979c262eb9380e6359efcL117

2024-02-19 04:22 UTC, alex8bitw commented
azcopy sync isn't in preview.  What version of azcopy are you using?  I have 10.23.0 and I don't see that message.

2024-02-23 15:31 UTC, mimartin12 requested changes

2024-02-23 15:31 UTC, mimartin12 commented on .github/workflows/deploy-web.yml
> +
⚠️ This should be refactored so that it's all a single action.
Similar to 
- https://github.com/bitwarden/devops/blob/main/.github/workflows/version-bump-backup-webhook.yml#L23
- https://github.com/bitwarden/devops/blob/main/.github/workflows/akuity-cd.yaml#L41

2024-02-23 17:43 UTC, urbinaalex17 commented on .github/workflows/deploy-web.yml
> +        run: cat apps/web/build/index.html
I concur. I didn't want to delete the debug steps as well because it's helpful when it comes to debugging.

2024-02-23 17:45 UTC, urbinaalex17 commented on .github/workflows/deploy-web.yml
> +          echo "sync-utility=azcopy" >> $GITHUB_OUTPUT
Once the `az storage blob sync` is in GA, we can easily switch to this utility. It uses `azcopy` under the hood.

2024-02-23 17:51 UTC, urbinaalex17 commented on .github/workflows/deploy-web.yml
> +
Suggestion applied. Thanks, @mimartin12!

2024-02-23 18:37 UTC, mimartin12 commented on .github/workflows/deploy-web.yml
> +          echo "sync-utility=azcopy" >> $GITHUB_OUTPUT
What would that migration look like? I see that we could update the toggle, correct me if I am wrong, but wouldn't we also remove the conditional logic, along with the `azcopy` command?

2024-02-26 04:38 UTC, urbinaalex17 commented on .github/workflows/deploy-web.yml
> +          echo "sync-utility=azcopy" >> $GITHUB_OUTPUT
We are not sure when that migration could happen. However, in the future, we would like to stick with `az storage blob sync` when it is GA. Assuming it's GA, we would be in an excellent place to update either update the toggle to `echo "sync-utility=az-sync"` and test or remove the conditional logic and the `azcopy` step altogether.

2024-02-26 14:38 UTC, urbinaalex17 commented on .github/workflows/deploy-web.yml
> +        run: cat apps/web/build/index.html
@mimartin12, you are right! As soon as `az storage blob sync` is in GA, we can safely delete the logic along with the `azcopy`. Unfortunately, we do not know for sure when it will happen, but we will be in an excellent place to make that migration easily.

2024-02-26 15:03 UTC, mimartin12 approved these changes
I am a concerned around the feature toggle as it introduces code rot that isn't timeboxed. From what I can tell, there is no planned date for when `az storage blob sync` is GA and some unknown around the value that it provides over `azcopy`. Everything else looks good though.

2024-02-27 18:38 UTC, vgrassia commented on .github/workflows/deploy-web.yml
> +        continue-on-error: true
Why do we have this set to `true`? Wouldn't we want it to fail to indicate there's a problem with our deployment?

2024-02-27 19:47 UTC, urbinaalex17 commented on .github/workflows/deploy-web.yml
> +        continue-on-error: true
Good catch! I totally forgot about it due to the testing I was performing. Thanks!  I removed that from the workflow

2024-02-27 19:48 UTC, vgrassia approved these changes

2024-02-27 19:48 UTC, merged