PM-5263 - Token Service state migration - (1) Got key and state defin…
bitwarden/clients pull request #7975
Opened 2024-02-16 01:03 UTC by JaredSnider-Bitwarden

…itions setup (2) Ported over core state service getTimeoutBasedStorageOptions method logic into local determineStorageLocation method (3) Updated majority of methods to use state provider state

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-02-20 13:43 UTC, Hinton commented on libs/common/src/auth/services/token.service.ts
> +      return;
I think we also want to clean up the old value here, i.e. delete from disk if it exists.

2024-02-20 13:43 UTC, Hinton commented on libs/common/src/auth/services/token.service.ts
> +    if (this.platformSupportsSecureStorage) {
Initially we won't have the data in secure storage, and we probably have to load it from disk.

2024-03-13 10:48 UTC, djsmith85 submitted a review, later dismissed
Approving changes for tools

2024-03-13 20:33 UTC, justindbaur requested changes
Really great stuff, basically just one request for a comment. Thanks for working on this, I know it had some challenges from being in the weird space with no user id but this came out great.

2024-03-13 21:03 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/abstractions/token.service.ts
Thank you!

2024-03-13 21:03 UTC, JaredSnider-Bitwarden commented on apps/cli/src/auth/commands/login.command.ts
> +            undefined,
Good call. Will do

2024-03-13 21:04 UTC, JaredSnider-Bitwarden commented on libs/common/src/state-migrations/migrations/3-fix-premium.spec.ts
Darn. I missed that in the write up. This was done intentionally after asking @MGibson1 what to do because that migration referenced the access token on the `account` which was removed in this PR. He told me to just remove it as it was 2+ years old.

2024-03-13 22:08 UTC, JaredSnider-Bitwarden commented
The latest commit finishes implementing the `clearTwoFactorToken` logic for all login strategies that support remembering a 2FA token (password, SSO, and auth request). I retested on desktop, browser, and web with a hard coded invalid 2FA token server side to test the clear logic for several of the scenarios.

2024-03-14 14:13 UTC, jlf0dev reviewed
Great work! Mostly just some questions I'd like to discuss before approving

2024-03-14 14:13 UTC, jlf0dev commented on libs/common/src/auth/services/token.service.ts
> +    const userId: UserId = await this.determineUserIdByAccessTokenOrActiveUser(accessToken);
Question: Do we ever not have the UserId on the access token? And should we ever be setting the access token if the userId on it isn't the currently active user? We might need a check here to verify that.

2024-03-14 14:13 UTC, jlf0dev commented on libs/common/src/auth/services/token.service.ts
> +    userId ??= await firstValueFrom(this.activeUserIdGlobalState.state$);
Question: If we only ever set the refresh token with access token, why is the userId optional here? and why are we using the active user id from state? I would think it would make more sense to compare here and make sure they are the same.

2024-03-14 14:13 UTC, jlf0dev commented on libs/common/src/auth/services/token.service.ts
> +    userId ??= await firstValueFrom(this.activeUserIdGlobalState.state$);
Not sure if this `userId` should be optional either.

2024-03-14 15:11 UTC, JaredSnider-Bitwarden commented on libs/auth/src/common/login-strategies/login.strategy.ts
> +  protected async buildTwoFactor(userProvidedTwoFactor?: TokenTwoFactorRequest, email?: string) {
Added jsdocs for the methods that I changed / touched in this PR.

2024-03-14 18:30 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/token.service.ts
> +    userId ??= await firstValueFrom(this.activeUserIdGlobalState.state$);
Per synchronous discussion, updated this to no longer have an optional user id. I'd originally left it in case we ever needed to make the method public like the others, but YAGNI rules apply.

2024-03-14 18:31 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/token.service.ts
> +    userId ??= await firstValueFrom(this.activeUserIdGlobalState.state$);
Per synchronous discussion, updated this to no longer have an optional user id. I'd originally left it in case we ever needed to make the method public like the others, but YAGNI rules apply.

We discussed the idea on comparing the access token user id vs the active one, but we decided that we should just use the access token value as that is enough without needing to consider the active user id.

2024-03-14 18:32 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/token.service.ts
> +    const userId: UserId = await this.determineUserIdByAccessTokenOrActiveUser(accessToken);
Per synchronous discussion, updated this to only ever get the user id from the access token.

2024-03-14 19:10 UTC, jlf0dev approved these changes
Great work!

2024-03-14 21:53 UTC, cagonzalezcs approved these changes
Providing an approval with some comments, let me know if you need a re-review.

2024-03-14 21:53 UTC, cagonzalezcs commented on libs/auth/src/common/utilities/index.ts
> +export * from "./decode-jwt-token-to-json.utility";
Any reason we're avoiding directly importing this from the `decode-jwt-token-to-json.utility` file?

I imagine there's a solid reason, just asking.

2024-03-14 21:53 UTC, cagonzalezcs commented on libs/common/src/auth/abstractions/token.service.ts
> +   */
👏 👏 👏 

Really love the way this file is documented and detailed.

2024-03-14 21:53 UTC, cagonzalezcs commented on libs/common/src/auth/services/sso-login.service.ts
> +    await this.ssoEmailState.update((_) => email);
Nit - Missing test coverage on a number of lines within this file, any plans to resolve that in a follow up?

Not blocking due to this, just wondering.

2024-03-14 21:53 UTC, cagonzalezcs commented on libs/common/src/auth/services/token.service.ts
> +    // TODO: re-eval this once we get shared key definitions for vault timeout and vault timeout action data.
General question here, but are each of these TODO's referenced in this PR set to be followed up by a specific Jira ticket?

2024-03-14 21:58 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/token.service.ts
> +    // TODO: re-eval this once we get shared key definitions for vault timeout and vault timeout action data.
I'm in process of migrating the `VaultTimeoutSettingsService` to `StateProvider` in #7925. It was blocked by this work so I jumped on this task. Once this PR is merged, I can proceed back to working on the `VaultTimeoutSettingsService` migration, and I planned on discussing refactoring these methods as part of that work with @jlf0dev. If we decide not to refactor those as part of that PR to keep scope down, I will create a separate Jira task for refactoring that logic and cleaning up the `TokenService` public API to remove the need to pass in vault timeout setting data.

2024-03-14 22:02 UTC, JaredSnider-Bitwarden commented on libs/auth/src/common/utilities/index.ts
> +export * from "./decode-jwt-token-to-json.utility";
Per a discussion with @willmartian , we want to move towards a team owned library model for our `libs/auth` directory so that we can have a public API people can consume and we can move around the internals as needed without any importers needing to know about the paths within our team's library. Thus, we simply expose `@bitwarden/auth/angular` for all Angular exports and `@bitwarden/auth/common` for all non-Angular code for now.

2024-03-14 22:17 UTC, willmartian commented on libs/auth/src/common/utilities/index.ts
> +export * from "./decode-jwt-token-to-json.utility";
Yup, cosigned. As an example, see how we import from `"@angular/core"` and not from `"@angular/core/some/file.ts"`. Likewise, all imports to the should be directly to `"@bitwarden/components"`.

2024-03-14 22:53 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/abstractions/token.service.ts
> +   */
Thank you very much!

2024-03-14 23:02 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/sso-login.service.ts
> +    await this.ssoEmailState.update((_) => email);
Good catch. I've created an Auth tech debt ticket [here](https://bitwarden.atlassian.net/browse/PM-6831) for this work.

2024-03-15 06:47 UTC, djsmith85 approved these changes

2024-03-15 13:41 UTC, cagonzalezcs submitted a review, later dismissed

2024-03-15 15:35 UTC, justindbaur approved these changes

2024-03-15 15:39 UTC, djsmith85 approved these changes

2024-03-15 15:40 UTC, cagonzalezcs approved these changes

2024-03-15 15:41 UTC, JaredSnider-Bitwarden commented
Per discussion with Auth team, we will be QA'ing this in `main`.

2024-03-15 15:50 UTC, merged