[AC-2008] [AC-2123] [Pt 2] Transition PolicyService to use StateProvider
bitwarden/clients pull request #7977
Opened 2024-02-16 01:24 UTC by eliykat

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-02-16 01:38 UTC, eliykat commented on libs/common/src/tools/generator/password/password-generation.service.ts
> +        : null;
Two comments here:
1. I have no idea why `PolicyService` would be null here, but I kept the null check out of caution
2. `getAll` used to return all policies, even those that were disabled or that didn't apply to the user. The new behavior is that it filters all policies through `policyService.enforcedPolicyFilter`. The main effect of this change is that **this method will not return policies if the user is exempt from them**. By default, owners, admins, and custom users with the "Manage policies" permission are exempt from policies - see `policyService.isExemptFromPolicy`. Tools Team, please let me know if you need a different rule applied to the PasswordGenerator policy.

2024-02-27 04:06 UTC, eliykat commented on libs/common/src/tools/generator/password/password-generation.service.ts
> +    }
2 notes:

1. I don't know why `this.policyService` would be null, but I've maintained that check out of caution.
2. This should theoretically use the new `getAll$` method, however that has some additional filtering logic which doubles up with this method own's logic below. This change basically maintains current behaviour for now.

2024-02-28 00:05 UTC, eliykat commented on libs/common/src/services/vault-timeout/vault-timeout-settings.service.ts
The new `policyService.getAll$` method filters out policies that do not apply to the user, so the separate call to `policyAppliesToUser` is no longer necessary.

2024-02-28 00:07 UTC, eliykat commented on libs/angular/src/tools/send/add-edit.component.ts
> +      )
This was the only location using the optional filter parameter, that has been removed in favour of just getting all policies and inspecting them yourself.

2024-02-28 12:52 UTC, aj-rosado approved these changes
Changes to Tools owned files are LGTM

2024-02-29 19:30 UTC, addisonbeck commented on libs/common/src/services/vault-timeout/vault-timeout-settings.service.ts
This change touches on a couple of reasons I was making a push for stateful services to export as few observables as possible, and why I would prefer they offer robust operator functions for handling any business logic.

* Without reading the JSDoc `policyService.getAll$` and `policyService.policies$` sound like they would return the same data.
* Mixing business rules (what a policy is, what humans expect them to do) with the very technology-oriented problem of state management makes finding, adding, and testing the inline business logic harder. These stateful services _could_ follow a pretty rigid pattern - if they stay dry and just handle exporting and updating state in a type safe way. Stateful services have a purpose that could be read as "this is a stateful service, it adds type safety to messing with state". This is not a solution to a business rule, it is a solution to a technical problem. "You probably only want enabled/applied policies" is a business rule, not a technical problem. 

With those two core issues in mind, isolating that business logic to operators does a few things to improve the codebase:
* It allows the service to be very straightforward. "I get state for you, and I update state when you need me to" is easier to test, easier to understand, and unlikely to need a lot of modification later (unless, for example, the backing state storage mechanism is changed 😄).
* It creates a more flexible querying system. Using operators for business rules stops us from being responsible for assuming what callers want the service's data to look like right now, and stops us from having to react to new ways the data might be needed in the future. If we notice a new commonly important business rule we can add a new operator function, but that won't ever require modifying the service directly, its interface, or any of its sibling operators. This seems like a massive boon to service stability.
* It allows us to unit test business logic in isolation from the core functionality of the service, since each rule would have its own home in a standalone function.
*  It reduces the amount of logic we keep in complex services that depend on DI for dispersion. 

That's some level of an explanation why ideally (for me) `policies$` would accept a `userId` parameter and the rest of this would go in an operator that can be mapped to. If it ends up being mapped to every time, I'd say that's a good kind of verbosity. It makes the data flow and expectations clear even in a calling component.

I don't necessarily want to do anything about this now, since we're talking about service structure separately, but I would say we should (similarly to the org service PR) not deprecate any methods on this service just yet. We need a really hardened vision for what the service should look like in an observable-forward codebase.

2024-02-29 20:02 UTC, addisonbeck requested changes

2024-02-29 20:43 UTC, addisonbeck commented
Something else I just noticed that I'm missing from my work that you might be too (or maybe you're saving it for another PR, I'm not sure), but we need to delete methods from `StateService` and properties from the account object.

2024-02-29 21:27 UTC, audrey-jensen commented on libs/common/src/services/vault-timeout/vault-timeout-settings.service.ts
While in a general sense I agree with everything you said, I think there's something that bears a bit more exploration:

> Stateful services have a purpose that could be read as "this is a stateful service, it adds type safety to messing with state". This is not a solution to a business rule, it is a solution to a technical problem. "You probably only want enabled/applied policies" is a business rule, not a technical problem.

There are places where stateful services and business problems overlap. When business logic depends on other observables--for example, knowing whether a policy applies to a specific user requires knowing their organization and some permissions--then you can end up creating efficiency problems with other lookups. Optimizing the dependency chain can be non-trivial in rx applications, unlike optimizing the hot path of procedural code.

In those situations, often the answer is to dive further into Rx.

* [Communicate facts](https://www.reactiveprinciples.org/patterns/communicate-facts.html)
* [Coordinate dataflow](https://www.reactiveprinciples.org/patterns/coordinate-dataflow.html)
* [Localize state](https://www.reactiveprinciples.org/patterns/localize-state.html)

And it's there we run into potential domain issues--localizing state, for example, would be an antipattern if the copied state is a cryptographic key.

Overall, negotiating and managing these concerns is why I 💯% agree we can't focus on it in this PR. 😄

2024-02-29 23:16 UTC, eliykat commented on apps/cli/src/bw.ts
> +      this.policyService.clear(userId as UserId),
Yes, I was mostly just following the existing pattern. Although I think the abstraction has a benefit - outside callers can just say "clear your state, I don't care how you do it" - which I think is nice and might actually be required if the service manages multiple pieces of state (not that this one does).

2024-02-29 23:20 UTC, eliykat commented on libs/common/src/admin-console/models/response/policy.response.ts
> +  id: PolicyId;
Yes, I like it and I'm in favour of doing it for all our models.

2024-02-29 23:57 UTC, eliykat commented on libs/common/src/services/vault-timeout/vault-timeout-settings.service.ts
Thank you both for your thoughtful answers. My current view is that this is an area where data & business logic do mix - outside callers **never** want policies that don't apply, and even giving them that option is likely to lead to misuse, as we see in the app today. That's why I marked the `policies$` observable as deprecated, for example.

In other words, I agree that the duplicate interfaces are confusing, but my solution is the opposite - instead of exposing the raw data and let callers apply the business rules, I want to only expose the data after business rules have been applied. I think the main reason I'd give for this is so that other teams don't footgun themselves by using `policies$` without piping it through the function we know they'll want anyway.

(Admittedly this is a bit of a unique problem - arguably these policies shouldn't be sent down in sync data at all. However, the server's sync endpoint is already has one of the highest loads so I don't want to add additional work there - although we can discuss that further if desired.)

Note that editing/administrating policies is done with direct API calls, not the sync data in PolicyService. The only consumers of this service are other domain areas that need to know if an action is restricted by a policy.

---

Again, this is all very domain specific. If we're just talking about the difference between `organizationService.organizations$.pipe(getById(orgId))` and `organizationService.get$(orgId)` then that's a bit more generally applicable. I do have some concerns about discoverability and verbosity, like you've seen how many callers there are for `organizationService.get($)`, are we really gonna make them all pipe their own data? I think for something like OrganizationService, we do in fact have a pretty good and stable idea of how other teams use our data, and I'm OK with designing an interface to meet those needs.

But! Let's discuss further, I'll line up a meeting.

2024-03-01 00:23 UTC, eliykat commented on libs/common/src/services/vault-timeout/vault-timeout-settings.service.ts
One final note, I doubt our positions are very far apart in practice, as most of these domain services are concerned with simple CRUD operations; it might just be figuring out where we draw the line on more complex "Read" helper methods, keeping them vs. moving them to mapping functions vs. removing them altogether and moving the business logic to the component.

2024-03-01 01:30 UTC, eliykat commented
@addisonbeck I think the only actionable feedback for this PR was to remove the deprecation warnings. I've done that, although for the reasons [explained above](https://github.com/bitwarden/clients/pull/7977#discussion_r1508324031) I've otherwise kept the general warnings about usage so that callers know what they're getting.

2024-03-01 19:13 UTC, addisonbeck approved these changes

2024-03-04 17:49 UTC, MGibson1 reviewed
I don't see any issues with the migration, but I do have two questions about the areas touched here

I'm also expecting removals of data from the `Account` object and methods from `StateService`.

2024-03-04 17:49 UTC, MGibson1 commented on libs/common/src/admin-console/abstractions/policy/policy.service.abstraction.ts
> +  get$: (policyType: PolicyType) => Observable<Policy>;
This interface really feels like a gotcha. The policy that happens to be first is _never_ what a consumer will care about. I looks like we probably already have a bug related to this in this interface being used in our password generator service

2024-03-04 17:49 UTC, MGibson1 commented on libs/common/src/services/vault-timeout/vault-timeout-settings.service.ts
> +      const action = policies[0].data.action;
Shouldn't this be the minimum of all the policies?

2024-03-05 03:49 UTC, eliykat commented on libs/common/src/admin-console/abstractions/policy/policy.service.abstraction.ts
> +  get$: (policyType: PolicyType) => Observable<Policy>;
It works where the policy requires that the Single Org Policy is enabled (see next comment). But I agree it's likely to be misleading, I just ended up avoiding interface changes here to limit PR size. We have follow-up work to clarify this service's interface and refine our domain service interfaces generally.

2024-03-05 03:51 UTC, eliykat commented on libs/common/src/services/vault-timeout/vault-timeout-settings.service.ts
> +      const action = policies[0].data.action;
The Vault Timeout Policy requires that the Single Org Policy is enabled as a prerequisite, more or less guaranteeing that there will only ever be 1 policy to check. Not my choice, I assume it was a tradeoff to simplify the implementation.

2024-03-05 03:54 UTC, eliykat commented
I was going to update StateService in a follow-up PR, but it's extremely straightforward, let's just do it here so we're done.

2024-03-05 19:39 UTC, addisonbeck approved these changes

2024-03-05 19:48 UTC, aj-rosado approved these changes

2024-03-05 21:13 UTC, MGibson1 commented on libs/common/src/admin-console/abstractions/policy/policy.service.abstraction.ts
> +  get$: (policyType: PolicyType) => Observable<Policy>;
In that case, can you limit the `PolicyType` taken to single org policies? That shouldn't change the interface.

2024-03-05 21:15 UTC, MGibson1 reviewed
I'd like to see that type change with this opportunity, but otherwise this looks good

2024-03-06 03:25 UTC, eliykat commented on libs/common/src/admin-console/abstractions/policy/policy.service.abstraction.ts
> +  get$: (policyType: PolicyType) => Observable<Policy>;
I'm not sure if I follow you - it's a reasonable request, but that would be a change to the interface. In any case, I tried it in https://github.com/bitwarden/clients/pull/7977/commits/a0295dbcc87879e1cf57fe20b10699b013d3ffb2, but as you mentioned this is currently used by the password generator code so it immediately throws compile errors. I agree that it's likely a defect and I'm following up with Tools Team, but I don't think it's one that needs to hold up this PR.

2024-03-06 13:25 UTC, MGibson1 commented on libs/common/src/admin-console/abstractions/policy/policy.service.abstraction.ts
> +  get$: (policyType: PolicyType) => Observable<Policy>;
The order this is being handled in really bothers me, we can't risk breaking policies because we're blocked by some other interface, and in so doing we're now limited in fixing this original issues. Quite frustrating.

2024-03-06 13:25 UTC, MGibson1 approved these changes

2024-03-06 15:33 UTC, audrey-jensen commented on libs/common/src/admin-console/abstractions/policy/policy.service.abstraction.ts
> +  get$: (policyType: PolicyType) => Observable<Policy>;
Just a note about the followup: The interface was used intentionally because I was under the impression that a user can have only 1 password generator policy. This is incorrect, but it shouldn't block this PR. The code that uses that interface isn't yet live.

2024-03-06 22:01 UTC, addisonbeck approved these changes

2024-03-07 03:46 UTC, eliykat commented on libs/common/src/admin-console/abstractions/policy/policy.service.abstraction.ts
> +  get$: (policyType: PolicyType) => Observable<Policy>;
Just to reiterate: 

> we can't risk breaking policies because we're blocked by some other interface

We are not breaking anything, the `get$` method already exists and works this way today (other than removing the unused filter parameter). You're right that the interface is not great but that is not a change from this PR. We can make this improvement in a following PR.

2024-03-07 14:14 UTC, aj-rosado approved these changes

2024-03-07 17:48 UTC, audrey-jensen approved these changes
@aj-rosado did the review here. I'm approving just so it's clear that my comments aren't blocking. :)

2024-03-08 00:26 UTC, merged