Pm 5009 migrate billing component
bitwarden/clients pull request #8011
Opened 2024-02-20 04:00 UTC by vinith-kovan

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other
```

## Objective
Migrating billing component css to Tailwind css

## Code changes
billing.component.html

## Screenshots
After Migration
![image](https://github.com/bitwarden/clients/assets/156108204/e2a99c85-7398-4fc2-9d39-c1acc8680d2a)

Before Migration
![image](https://github.com/bitwarden/clients/assets/156108204/db0db61e-8490-4e5b-821c-cc884afec7b8)

2024-02-20 23:18 UTC, willmartian requested changes

2024-02-20 23:18 UTC, willmartian commented on apps/web/src/app/billing/accounts/trial-initiation/billing.component.html
> +      </h2>
Ideally this should be a fieldset legend, that is more semantically appropriate than a heading. 

@vinith-kovan could you revert this change for now?

@bitwarden/team-billing-dev should this heading be part of the `app-payment` component itself?

2024-02-20 23:18 UTC, willmartian commented on apps/web/src/app/billing/accounts/trial-initiation/billing.component.html
> +    <div class="tw-flex tw-gap-x-2">
FYI for anyone else who sees this change, `tw-gap` does the same thing as `tw-space` here. `tw-space` approximates the behavior for older browsers that don't support the flexbox gap property, which doesn't apply to our target browser range.

2024-02-21 05:31 UTC, vinith-kovan commented on apps/web/src/app/billing/accounts/trial-initiation/billing.component.html
> +      </h2>
Sure

2024-02-21 05:32 UTC, vinith-kovan commented on apps/web/src/app/billing/accounts/trial-initiation/billing.component.html
> +              <span *ngIf="selectablePlan.PasswordManager">
Actually, it is not necessary i will revert it to ng-container

2024-02-22 14:22 UTC, amorask-bitwarden commented on apps/web/src/app/billing/accounts/trial-initiation/billing.component.html
> +      </h2>
@willmartian Are you referring to this `<h2>` above?

2024-02-26 22:32 UTC, willmartian approved these changes
LGTM 👍

2024-02-29 13:42 UTC, amorask-bitwarden approved these changes

2024-05-21 12:40 UTC, vinith-kovan commented
@amorask-bitwarden, while resolving conflicts, it seems that billing-component.html got deleted so we don't need this PR.

2024-06-20 14:10 UTC, amorask-bitwarden commented
> @amorask-bitwarden, while resolving conflicts, it seems that billing-component.html got deleted so we don't need this PR.

@vinith-kovan Yeah we can close this, thank you for checking.

2024-06-21 17:56 UTC, cturnbull-bitwarden commented
Closing this PR as it's no longer needed. Thank you for your work on it, @vinith-kovan!

2024-07-15 13:50 UTC, closed without merging