[PM-]Using reactive methods on SendAddEditComponent load
bitwarden/clients pull request #8013
Opened 2024-02-20 10:35 UTC by aj-rosado

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Use the reactive method from SendService instead of the current Promise call

## Code changes

- **libs/send/add-edit.component.ts:** Swapped the existing get method call with the reactive method returning the Send data

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-02-20 16:55 UTC, audrey-jensen reviewed
⛏️ nitpick
💭 thoughts (take them or leave them)
🎨 suggestions

If you have the time to implement the suggestions, I think they'd benefit the overall code quality. The thoughts might require substantial rework, so think of those as more "exploring the idea", and if they make the scope too big then don't do them.

I'm submitting this as a comment b/c the desktop tweak is incoming. Overall, though, this gets my approval.

2024-02-20 16:55 UTC, audrey-jensen commented on libs/angular/src/tools/send/add-edit.component.ts
> +                .decrypt()
🎨 Send decryption can be moved into the pipe, which would avoid relying directly on promise interfaces. They'd be hoisted into the observable.

```javascript
this.sendService.get$(this.sendId)
    .pipe(
        concatMap(async (s) => s ? await s.decrypt() : throw new Error("Failed to load send.")),
        takeUntil(this.destroy$))
    .subscribe({
        next: (s) => {
            this.send = s;
            // etc
        },
        error: (e) => this.logService.error(e.message)
    });
```

2024-02-20 16:55 UTC, audrey-jensen commented on libs/angular/src/tools/send/add-edit.component.ts
> +        this.hasPassword = this.send.password != null && this.send.password.trim() !== "";
⛏️ Looks like there's an indentation issue here. Does it begin on line 234?

💭 This line looks like it should be made part of the reactive pattern. Seems like what you could do is create a `BehaviorSubject<SendView>`, then either wire it to `sendService.get$(id)` or manually `next` it with the new object. Then you'd be able to wire the body on lines 219-223 using the behavior subject instead of wiring to `get$` directly.

```
// send = new BehaviorSubject<SendView>();
send.subscribe({
        next: (s) => {
            this.send = s;
            // etc
        },
        error: (e) => this.logService.error(e.message)
    });

if(edit) {
    this.sendService.get$(this.sendId).subscribe(send);
} else {
   const sendView = new SendView()
   // ...
   send.next(sendView);
}
```

2024-02-21 18:54 UTC, audrey-jensen requested changes
⛏️ nitpick
❓ open-ended questions
👍🏻 kudos!
⚠️ issue
💭 idle thoughts
🤔 thoughts that could benefit from discussion

2024-02-21 18:54 UTC, audrey-jensen commented on libs/angular/src/tools/send/add-edit.component.ts
> +    return firstValueFrom(this.sendService.get$(this.sendId));
⛏️ This should either await or `async` should be removed from line 390.

2024-02-21 18:54 UTC, audrey-jensen commented on libs/angular/src/tools/send/add-edit.component.ts
> +            concatMap((s) => (s ? s.decrypt() : Promise.reject("Failed to load send."))),
👍🏻 Quite like that you were able to remove the async/await here. This is easier to follow than the throw-based version from my last comment.

2024-02-21 18:54 UTC, audrey-jensen commented on libs/angular/src/tools/send/add-edit.component.ts
> +        error: (error: unknown) => {
❓ Do we know that this will always be a string? I'm guessing not, but assuming it's unknowable, then using `+ error` can result in `[object object]` or similar serializations ending up in the error message. I'm not sure what to do about that, but it's worth pointing out given that the type is explicitly `unknown`.

2024-02-23 16:54 UTC, audrey-jensen commented on libs/angular/src/tools/send/add-edit.component.ts
> +        },
⚠️ Hmm... when an error happens this will complete the behavior subject, which, since the `AddEdit` component is reused, could cause sends to stop working entirely. 

Example: https://stackblitz.com/edit/nfymnk?file=index.ts

2024-02-26 11:00 UTC, aj-rosado commented on libs/angular/src/tools/send/add-edit.component.ts
> +        },
Right now the desktop application is not relying on the subscriber to update the view. 
It calls `loadSend` that gets the `firstValueFrom(this.sendService.get$(this.sendId));` so it will work properly when changing sends.

If this changes so that desktop relies only on the subscriber, this should be changed.
Adding this info as a comment to prevent future issues

2024-02-26 14:16 UTC, audrey-jensen submitted a review, later dismissed

2024-03-05 19:50 UTC, audrey-jensen approved these changes

2024-03-08 14:01 UTC, audrey-jensen approved these changes

2024-03-08 16:25 UTC, merged