[PM-5434] Create VaultBrowserStateService and migrate components from. BrowserStateService
bitwarden/clients pull request #8017
Opened 2024-02-20 14:52 UTC by LRNcardozoWDF

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Migrate `browserGroupingComponentState` and `browserVaultItemsComponentState` to the State Provider framework in newly `VaultBrowserStateService`.

## Code changes

- **file.ext:** Description of what was changed and why
- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-02-23 15:26 UTC, willmartian requested changes

2024-02-23 15:26 UTC, willmartian commented on libs/common/tsconfig.json
> +  ],
blocking: is this change intentional?

2024-02-23 15:26 UTC, willmartian commented on apps/browser/tsconfig.json
> +    "src/vault/services/vault-browser-state.service.ts"
blocking: Is this change intentional?

2024-02-23 15:26 UTC, willmartian commented on apps/browser/src/vault/services/vault-browser-state.service.ts
> +  }
The naming pattern seems to be inconsistent here. 

The observable is named `vaultBrowserGroupingsComponent$`

The promise is named `getBrowserGroupingComponentState()`

- "Grouping" is plural in one
- "State" is present in one but not the other

2024-02-23 15:26 UTC, willmartian commented on apps/browser/src/vault/services/abstractions/vault-browser-state.service.abstraction.ts
> +}
Does this service need an abstraction?

2024-02-23 15:26 UTC, willmartian commented on apps/browser/src/vault/services/vault-browser-state.service.ts
> +export class VaultBrowserStateService implements VaultBrowserStateServiceAbstraction {
Zooming out a bit, why does vault need a "browser state service"? In plain language, what is the goal of this service?

Services should often represent a piece of business domain logic. It feels like _our goal_ is to represent some business logic in this service, but it is overshadowed by specific terminology like "Browser", "State", and "Component" being used in our symbol names.

2024-02-23 18:40 UTC, LRNcardozoWDF commented on libs/common/tsconfig.json
> +  ],
No it wasn't, thanks for catching this.

2024-02-23 18:40 UTC, LRNcardozoWDF commented on apps/browser/tsconfig.json
> +    "src/vault/services/vault-browser-state.service.ts"
No it wasn't, thanks for catching this.

2024-02-23 19:39 UTC, LRNcardozoWDF commented on apps/browser/src/vault/services/abstractions/vault-browser-state.service.abstraction.ts
> +}
I thought it would, but ended up not using it anywhere. I will remove it.

2024-03-05 15:12 UTC, willmartian submitted a review, later dismissed
My blocking comments have been resolved.

2024-03-05 17:01 UTC, gbubemismith approved these changes

2024-03-13 17:56 UTC, willmartian submitted a review, later dismissed

2024-03-14 15:01 UTC, gbubemismith approved these changes

2024-04-01 12:44 UTC, gbubemismith approved these changes

2024-04-01 18:31 UTC, willmartian approved these changes

2024-04-02 15:23 UTC, merged