[PM-6383] Migrate clearClipboard account setting to autofill settings service
bitwarden/clients pull request #8022
Opened 2024-02-20 22:25 UTC by jprusik

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-02-21 20:58 UTC, cagonzalezcs submitted a review, later dismissed
Looks good from my side, CodeCov is complaining about some missed lines in terms of coverage, but I'm not keen on blocking this because of that.

If you do need a re-approval to address coverage on those changes, let me know.

2024-02-23 17:50 UTC, cagonzalezcs approved these changes

2024-02-23 18:10 UTC, justindbaur requested changes
Couple minor things.

2024-02-23 18:10 UTC, justindbaur commented on libs/common/src/platform/services/state.service.ts
Should be able to delete [this](https://github.com/bitwarden/clients/blob/dee0b20554694244bceff489dd7c27228f6b32b9/libs/common/src/platform/models/domain/account.ts#L204) now.

2024-02-23 18:10 UTC, justindbaur commented on libs/common/src/state-migrations/migrations/24-move-clear-clipboard-to-autofill-settings-state-provider.spec.ts
> +import { AutofillOverlayVisibility } from "../../../../../apps/browser/src/autofill/utils/autofill-overlay.enum";
You shouldn't import `apps/browser` into `libs/common`, even just for a test. I would just represent these values like the jsonified version of themselves like how they are saved in state.

2024-02-23 18:33 UTC, cagonzalezcs submitted a review, later dismissed

2024-02-23 18:42 UTC, justindbaur approved these changes

2024-02-23 18:52 UTC, merged