[AC-2161] update cipher collections org vault modal
bitwarden/clients pull request #8027
Opened 2024-02-21 15:35 UTC by Jingo88

```
- [ ] Bug fix
- [ X ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

When Org has `Owners and Admins can manage all collections and items` turned on

* Owner can open the `Edit Collections` modal and add/remove collections associated with the cipher

When Org has `Owners and Admins can manage all collections and items` turned off

* Owner can open the `Edit Collections` modal
* Collections they have `readOnly` access to will be on the bottom
* If the cipher does not have any `Can Edit` collections associated with it, the Owner will be blocked from updating that ciphers collections. When trying to save in this instance they will get an error toast

## Code changes

* vault.component - Added a sort for collections before opening the Modal. Update to show all collections instead of only `editableCollections$`. Pass in flexible collections flag to modal
* collections.component.ts (individual)- Do not allow check to complete on readOnly cipher row
* collections.component.ts (org) - use the `canEditAllCiphers` boolean to assess what endpoint to hit
* collections.component.ts (admin-console) - access if org canEditAnyCollection is turned on/off
* collections.component.html - Added disable to the checkbox of the readOnly cipher
* `canEditAllCiphers` - added to loadCipher in org-vault collections component and submit in libs collections component

## Recording

First Recording For Original Flow
https://github.com/bitwarden/clients/assets/8302660/28f6cf86-4bb7-4b5f-8eaf-4a0c169433d5

Second Recording For QA Bugs Found (AC-2283, AC-2279, AC-2280)

https://github.com/bitwarden/clients/assets/8302660/41b0253b-34ef-4e23-b339-f767b4d33376

2024-02-21 19:25 UTC, LRNcardozoWDF submitted a review, later dismissed
LGTM!

2024-02-23 01:03 UTC, shane-melton requested changes
We still have some odd behavior going on here and need to investigate some more before merging this.

2024-02-23 01:03 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +    collections = collections.sort((a, b) => {
issue / question: The `collections` list here is being filtered above to only show non-readonly collections. I think something unexpected is going on if you're able to get a mix of readonly and non-readonly collections to sort here. 

Are you using the v1 flexible collections flag? And/or is the limit admin access to collections/items setting enabled?

2024-03-06 18:11 UTC, shane-melton approved these changes
Looking good, gave it go on my local environment as well and the dialog was behaving as expected in my tests, thank you!

2024-03-07 03:03 UTC, eliykat approved these changes
The `CollectionsComponent` base class is AC Team's only file here, and it doesn't look like we should own it. I assume it's a holdover from when we owned collections. But all its subclasses are all in vault code, and vault now owns collections, so please move this into your code ownership as well.

I am approving in the meantime to unblock you but I am relying on @shane-melton being happy with it.

2024-03-07 22:30 UTC, shane-melton approved these changes

2024-03-08 01:22 UTC, eliykat approved these changes

2024-03-13 22:22 UTC, shane-melton reviewed
I think this is pretty much there -- just two questions to make sure we're on the same page and this is behaving as we both expect.

2024-03-13 22:22 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/collections.component.ts
> +
question: The base component already has a `flexibleCollectionsV1Enabled` property that is set when the component is opened. Can we reuse that without needing to create it again and setting during `loadCipher()`? Or is it not set before `loadCipher()` is called?

2024-03-13 22:22 UTC, shane-melton commented on libs/angular/src/admin-console/components/collections.component.ts
> +          (this.organization?.allowAdminAccessToAllCollectionItems &&
question: I'm not sure we still need these other conditions? 

`canEditAllCiphers()` should be enough to determine if we need to consider `readOnly` collections. If `canEditAllCiphers()` is true, then the `saveCollections()` method above will use the admin endpoint which needs every collection "checked". Otherwise, if `canEditAllCiphers` is false, the method uses `super` method and only needs to supply collections the user has write access to.

2024-03-13 22:52 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/vault.component.ts
>          (c) => !c.readOnly && c.id != Unassigned,
This line should not be filtering collections here and was added by mistake in [AC-1124](https://github.com/bitwarden/clients/pull/7537). Would you mind removing it here to fix the issue when the V1 flag is disabled? See [AC-2281](https://bitwarden.atlassian.net/browse/AC-2281) for some more context.

2024-03-14 23:05 UTC, eliykat approved these changes
Confirming @shane-melton 's review

2024-03-18 16:19 UTC, shane-melton submitted a review, later dismissed

2024-03-19 03:33 UTC, eliykat approved these changes

2024-03-19 18:19 UTC, shane-melton approved these changes

2024-03-19 22:30 UTC, eliykat approved these changes

2024-03-21 15:54 UTC, merged