[PM-6404] Initial Clear Events Code
bitwarden/clients pull request #8029
Opened 2024-02-21 19:26 UTC by justindbaur

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Add a `clearOn` key definition option so users can choose to have their state cleared on certain events. The option is not currently respected but will be in a follow up PR. 

## Code changes

- **apps/browser/src/platform/background/service-factories/*.factory.ts:** Factories for new services
- **apps/web/src/app/platform/web-storage-service.provider.ts:** Web override of storage service provider. This will make it possible to delete the web overrides of all the state providers. 
- **libs/common/spec/fake-state.ts:** Make global state `update` behave like the other fake state `update` methods.
- **libs/common/src/platform/services/storage-service.provider.ts:** Default implementation of the storage service provider.
- **libs/common/src/platform/state/index.ts:** Export the runner only since that is expected to be used by other services.
- **libs/common/src/platform/state/key-definition.ts:** New optional key definition option and it's computed brethren on `KeyDefinition`. 
- **libs/common/src/platform/state/state-event-registrar.service.ts:** A service for registering a key definition for all its clear events. This is meant to be used internally by `SingleUserStateProvider` and `ActiveUserStateProvider`. 
- **libs/common/src/platform/state/state-event-runner.service.ts:** A service for running an event and clearing the state for all registered events. 

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-02-26 22:24 UTC, MGibson1 requested changes

2024-02-26 22:24 UTC, MGibson1 commented on libs/common/src/platform/state/state-event-registrar.service.ts
> +  location: string;
**question**: Any reason to not specify a more precise type here? I assume it's something like future storage locations or name changes, right?

If so, we should handle unknowns a little more carefully -- discussed further in the runner service.

2024-02-26 22:24 UTC, MGibson1 commented on libs/common/src/platform/state/state-event-runner.service.ts
> +      );
Good idea to try/catch this since `get` can throw.

Append the offending value to a `toRemove` list on failure.

2024-02-26 22:24 UTC, MGibson1 commented on libs/common/src/platform/services/storage-service.provider.ts
> +   */
**issue**: Please include `@throws` in your documentation

2024-02-26 22:24 UTC, MGibson1 commented on libs/common/src/platform/state/state-event-runner.service.ts
> +      const ticketStorageKey = userKey.buildKey(userId);
**suggestion**: I'd prefer to extract this into a method that takes a `StateEventInfo`

```typescript
  private storageKeyFor(userId: UserId, ticket: StateEventInfo) {
    const userKey = new UserKeyDefinition<unknown>(
      new StateDefinition(ticket.state, ticket.location as unknown as StorageLocation),
      ticket.key,
      {
        deserializer: (v) => v,
        clearOn: [],
      },
    );
    return userKey.buildKey(userId);
  }
```

or some such

2024-02-27 12:48 UTC, justindbaur commented on libs/common/spec/fake-state.ts
> +  async update<TCombine>(
We had already made `update` not a `jest.fn` for the user states but didn't do this for global. I'll remove `updateMock` from all of them though, they aren't currently used anywhere.

2024-02-27 13:13 UTC, justindbaur commented on libs/common/src/platform/state/state-event-runner.service.ts
> +      );
I think I want that error bubbled up, it shouldn't ever throw if proper values are inputted it, I wouldn't want to silently not delete data that has been requested to be deleted. That would be much less preferable than getting an exception during use of the application.

2024-02-27 13:54 UTC, MGibson1 commented on libs/common/src/platform/state/state-event-runner.service.ts
> +      );
I'm fine with not removing the item, and we can still log on the error, but as written an incorrect value -- due to new or changed names that aren't known to a given version -- will cause processing future tickets to fail.

The try/catch is still important and a single aggregated error is the better way to handle situations like this.

2024-02-27 16:01 UTC, justindbaur commented on apps/web/src/app/platform/web-storage-service.provider.ts
> +        throw new Error(`Unexpected location: ${location}`);
I did this, I have to pass in the web aware location into the first parameter but mostly did this.

2024-02-27 17:16 UTC, justindbaur commented on libs/common/src/platform/state/state-event-runner.service.ts
> +      );
A new version with a new location should be supported through the storage providers and if it's not, that is a developer error, hence my desire for an error so that its likely it gets noticed by the developer. So I did go the route of catching the exceptions and throwing an aggregated error of all failures.

2024-02-27 21:55 UTC, MGibson1 approved these changes
looking great!

2024-02-27 21:58 UTC, merged