[PM-2637] Refactor EnvironmentService
bitwarden/clients pull request #8040
Opened 2024-02-22 09:31 UTC by Hinton

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-02-26 13:06 UTC, Hinton commented on apps/browser/src/platform/services/browser-environment.service.ts
> +    await this.setEnvironment(Region.SelfHosted, {
Technically it's possible to set managed env to EU cloud, we may want some logic to dedupe cloud urls to region?

2024-02-26 13:07 UTC, Hinton commented on apps/cli/src/commands/config.command.ts
> +    await this.environmentService.setEnvironment(Region.SelfHosted, {
I think we want some logic here that figures out if you are using either cloud and uses the region appropriately instead.

2024-02-29 14:59 UTC, Hinton commented on .eslintrc.json
> +        "rxjs-angular/prefer-takeuntil": ["error", { "alias": ["takeUntilDestroyed"] }],
This allows us to use the new `takeUntilDestroyed`.

2024-03-01 14:49 UTC, audrey-jensen commented on libs/angular/src/tools/send/add-edit.component.ts
> +    firstValueFrom(this.environmentService.environment$)
⚠️ As written, this introduces a race condition. This can be addressed by awaiting it in `ngOnInit`.

2024-03-01 15:08 UTC, audrey-jensen requested changes
⚠️ requested changes
🤔 thoughts
👍🏻 kudos!
🎨 suggestions
❓ question (the curious kind, not the veiled request kind.)

2024-03-01 15:08 UTC, audrey-jensen commented on libs/common/src/platform/abstractions/environment.service.ts
> +  getSendUrl: () => string;
🤔 I might include documentation explaining the values these return if the endpoint is not available. Specifically for `Scim`, but also for any other systems this applies to. (e.g. "If there is no SCIM server, this returns `null`" or similar.)

2024-03-01 15:32 UTC, Hinton commented on libs/angular/src/tools/send/add-edit.component.ts
> +      .catch((e) => logService.error("Unable to get environment" + e));
We lose reactivity that way though, but I can await it in `ngOnInit`. Realistically `environment$` will resolve before `ngOnInit` is called.

2024-03-01 15:39 UTC, audrey-jensen commented on libs/angular/src/tools/send/add-edit.component.ts
> +      .catch((e) => logService.error("Unable to get environment" + e));
Neither solution is reactive. The promise returned from `firstValueFrom` can only complete once. If reactivity is your goal, then you need to subscribe to the observable. 

```javascript
this.environmentService.environment$.subscribe({ 
  next(env) {
    this.sendLinkBaseUrl = env.getSendUrl();
  } 
}
```

Recoverable error handling in observables is a whole thing. If the exception is happening within `getSendUrl()` then you can simply add try/catch in the `then` handler. If it happens in `environment$` then you'll need to resubscribe.

2024-03-01 17:39 UTC, Hinton commented on libs/angular/src/tools/send/add-edit.component.ts
> +      .catch((e) => logService.error("Unable to get environment" + e));
🤦, I thought I updated this. Moved the call, I think this is better tackled as part of revamping the add-edit. I don't expect the environment to change within the send page.

2024-03-01 17:59 UTC, audrey-jensen commented on libs/angular/src/tools/send/add-edit.component.ts
> +      .catch((e) => logService.error("Unable to get environment" + e));
Yeah, we're going to port everything to the CL and reactive forms, and I'll figure out all those details as part of that work. 😄

2024-03-04 14:35 UTC, Hinton commented on libs/common/src/platform/abstractions/environment.service.ts
> +  getSendUrl: () => string;
I could add comments, but I don't think they provide any value here,

```ts
/**
 * Get the environment api url.
 */
getApiUrl: () => string;
```
If you can come up with some more descriptive comments I'm all for it. Except key connector they all always return a valid url, and I've updated key connector to make this distinctive by adding `| null` to the return type.

They could, but I generally don't consider them as getters since they include some computational logic which I think aligns with our current practices.

2024-03-04 15:24 UTC, audrey-jensen commented on libs/common/src/platform/abstractions/environment.service.ts
> +  getSendUrl: () => string;
> If you can come up with some more descriptive comments I'm all for it.

I mostly have questions that I'd expect to be answered by these docs.

* How does `getKeyConnector` behave in cloud installs? How does it behave in self-hosted installs if a directory connector isn't deployed?
* How does `getSCIM` behave if I don't have an enterprise subscription?
* How does `getIconsUrl` behave if I'm on a self-hosted environment but haven't deployed the icons server?
* Are there endpoints that fall back to bitwarden's cloud environment if they're not configured in a self-host environment?

The idea being to explain how these methods operate (or should be expected to operate) based on the environment the client is connecting to.

2024-03-04 16:01 UTC, Hinton commented on libs/common/src/platform/abstractions/environment.service.ts
> +  getSendUrl: () => string;
Honestly I'm not well versed in either of those topics. I've marked the key connector as deprecated since it's essentially a hack used by the CLI.

The other concerns are not external concerns in my opinion. Consumers get the urls and should expect them to be correct, what url you actually get is an internal concern of the service. That said we can improve the internal documentation in the service but most of that is very old legacy reasons which boils down to the same behaviour for all of them.

I.e. Direct url ?? base + custom suffix ?? US.

2024-03-04 16:06 UTC, audrey-jensen submitted a review, later dismissed

2024-03-04 19:46 UTC, justindbaur requested changes
Looks really good and huge improvement, just a couple small things.

2024-03-04 19:46 UTC, justindbaur commented on libs/angular/src/auth/components/environment-selector.component.ts
> +  protected AvailableRegions = this.environmentService.availableRegions();
Also `camelCase`

2024-03-04 19:46 UTC, justindbaur commented on libs/angular/src/auth/components/environment-selector.component.ts
> +      takeUntilDestroyed(),
Do we actually need to use `takeUntilDestroyed` if we don't subscribe to it here, won't the `async` pipe unsubscribe for us?

2024-03-07 15:09 UTC, cagonzalezcs reviewed
Autofill files look to be in good condition, provided some nits. 

One thing I"m not seeing here is the removal of `getBgService` within the browser extension's `services.module.ts` file. Would that be possible to incorporate?

2024-03-07 16:01 UTC, r-tome approved these changes

2024-03-07 17:07 UTC, audrey-jensen submitted a review, later dismissed

2024-03-07 17:17 UTC, Jingo88 approved these changes

2024-03-07 17:19 UTC, ike-kottlowski submitted a review, later dismissed
Auth changes look good.

2024-03-07 17:32 UTC, rr-bw submitted a review, later dismissed

2024-03-07 17:59 UTC, Hinton commented on apps/browser/src/autofill/background/notification.background.ts
> +    return env.getWebVaultUrl();
I would say this is undesired. We want to move towards a reactive pattern, which means observables.

There might be an argument for exposing variants of the `environment$` observable like `webVaultUrl$`?

2024-03-07 18:11 UTC, cagonzalezcs commented on apps/browser/src/autofill/background/notification.background.ts
> +    return env.getWebVaultUrl();
I see, well it's your call either way. Not going to block this work for the optimization.

One thing I would like to see before we merge this in is the removal `getBgService("environmentService")` from the `services.module.ts` file for the browser popup. Once that's tackled, I'll provide an approval. Everything else looks solid.

2024-03-08 13:04 UTC, Hinton commented on libs/common/src/platform/services/environment.service.ts
> +});
I defined a separate state for cloud region since it's set by the config service which reacts on the environment state 😢

2024-03-08 13:23 UTC, justindbaur requested changes

2024-03-08 13:23 UTC, justindbaur commented on libs/common/src/platform/services/environment.service.ts
> +      const config = this.getRegionConfig(state);
We have to change all the callsites with converting this to return a promise, why not have this return an observable and make all consumers do the `firstValueFrom`?

2024-03-08 13:23 UTC, justindbaur commented on apps/browser/src/platform/services/browser-environment.service.ts
> +export class BrowserEnvironmentService extends DefaultEnvironmentService {
Since this class is only meant to be used in browser foreground and the default implementation can be used in browser background I think I'd prefer the name `BrowserForegroundEnvironmentService`, granted the `Injectable` does indicate that, I think I'd still like it in the name.

2024-03-11 10:23 UTC, Hinton commented on apps/browser/src/platform/services/browser-environment.service.ts
> +export class BrowserEnvironmentService extends DefaultEnvironmentService {
It's also used in the background page since we need to check the settings on install. I'll remove `@Injectable` to avoid confusion.

2024-03-11 15:59 UTC, justindbaur submitted a review, later dismissed

2024-03-12 10:30 UTC, r-tome submitted a review, later dismissed

2024-03-12 11:05 UTC, Hinton commented
I've sent this off to QA for testing before a final conflict resolve and a round of reviews.

2024-03-12 11:46 UTC, cyprain-okeke approved these changes
Looks Good for billing

2024-03-13 11:32 UTC, MGibson1 commented on libs/common/src/platform/services/environment.service.ts
> +  private activeCloudRegionState: ActiveUserState<CloudRegion>;
**issues**: I don't think this should be active user, this is relevant to whatever _environment_ happens to be active, but that's not necessarily only when a user is active.

2024-03-15 13:15 UTC, Hinton commented on libs/common/src/platform/services/environment.service.ts
> +  private activeCloudRegionState: ActiveUserState<CloudRegion>;
I believe this is resolved now.

2024-03-20 12:45 UTC, cyprain-okeke approved these changes
Looks Good

2024-03-21 11:36 UTC, cyprain-okeke approved these changes

2024-03-21 12:05 UTC, r-tome approved these changes

2024-03-21 12:23 UTC, justindbaur approved these changes

2024-03-21 12:54 UTC, audrey-jensen approved these changes

2024-03-21 13:08 UTC, cagonzalezcs approved these changes

2024-03-21 13:56 UTC, Jingo88 approved these changes

2024-03-21 16:09 UTC, rr-bw approved these changes

2024-03-21 16:09 UTC, merged