billing history component migration
bitwarden/clients pull request #8042
Opened 2024-02-22 11:30 UTC by vinith-kovan

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [X] Other
```

## Objective

Migrate the billing history component to use the Component Library

## Code changes

- billing-history.component.html -  Changed the table to use the Component Library equivalent (bit-table).
- billing-history-view.component.html  - Changed class name to use Tailwind CSS equivalent (bit-tab-nav-bar).

## Screenshots

After Migration
Account billing history
![image](https://github.com/bitwarden/clients/assets/156108204/7817716e-379f-45df-8816-1df9cfdb9fe1)

Org billing history
![image](https://github.com/bitwarden/clients/assets/156108204/3ec376e5-8378-43af-883c-51f772dcc4d8)

Before Migration
Account billing history
![image](https://github.com/bitwarden/clients/assets/156108204/df76df3a-1334-4aa9-a058-79770b888001)

Org billing history
![image](https://github.com/bitwarden/clients/assets/156108204/1c93753a-fd91-48d7-99fe-7f68886b20c0)

2024-02-26 23:37 UTC, willmartian requested changes

2024-02-26 23:37 UTC, willmartian commented on apps/web/src/app/billing/individual/billing-history-view.component.html
>    </h1>
This should be `<h2 bitTypography="h2">`. Most pages should not use `h1`, because the page header already contains one.

2024-02-26 23:37 UTC, willmartian commented on apps/web/src/app/billing/shared/billing-history.component.html
> +<h2 bitTypography="h2" class="tw-mt-3">{{ "invoices" | i18n }}</h2>
Use `<h3 bitTypography="h3">`

2024-02-26 23:37 UTC, willmartian commented on apps/web/src/app/billing/shared/billing-history.component.html
> +<h2 bitTypography="h2" class="tw-mt-16">{{ "transactions" | i18n }}</h2>
Use `<h3 bitTypography="h3">`

2024-02-26 23:37 UTC, willmartian commented on apps/web/src/app/billing/shared/billing-history.component.html
We should use two section CL components instead of bespoke margin:

```html
<bit-section>
  <h3>...</h3>
</bit-section>
<bit-section>
  <h3>...</h3>
</bit-section>
```

2024-02-28 13:15 UTC, willmartian commented on apps/web/src/app/billing/shared/billing-history.component.html
> +      <td bitCell>
Apologies, I was not clear here. 

The entire visual section should be wrapped in the section component, not just the header. 

```html
<bit-section>
  <h3>...</h3>
  <p>...</p>
  <bit-table>...</bit-table>
</bit-section>
```

Same for the next section.

2024-02-29 13:37 UTC, willmartian reviewed
@vinith-kovan could you update the screenshots to reflect the latest changes?

2024-02-29 13:37 UTC, willmartian commented on apps/web/src/app/billing/shared/billing-history.component.html
> +  <h3 bitTypography="h3" class="tw-mt-16">{{ "transactions" | i18n }}</h3>
`class="tw-mt-16"` shouldn't be necessary any more because the section has margin built in.

2024-02-29 13:45 UTC, vinith-kovan commented on apps/web/src/app/billing/shared/billing-history.component.html
> +  <h3 bitTypography="h3" class="tw-mt-16">{{ "transactions" | i18n }}</h3>
Screenshots are already updated

2024-03-01 05:19 UTC, willmartian commented on apps/web/src/app/billing/shared/billing-history.component.html
> +<small class="tw-text-muted">* {{ "chargesStatement" | i18n: "BITWARDEN" }}</small>
Please move this into the section as well.

2024-03-04 04:37 UTC, willmartian approved these changes

2024-04-16 19:39 UTC, merged