[PM-6404] Add `UserKeyDefinition`
bitwarden/clients pull request #8052
Opened 2024-02-22 18:21 UTC by justindbaur

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Add new `UserKeyDefinition` that has all the options of `KeyDefinition` but also an additional `clearOn` option that allows creators to define which events they want their user data cleared on.

This is a backwards compatible change, where we accept overloads of both `KeyDefinition` and `UserKeyDefinition` which a way to create `UserKeyDefinition` from `KeyDefinition`. As time goes on we can encourage the transition to only `UserKeyDefinition` for user state, through deprecation's and eventually we can cut off and remove the overload. 

## Code changes

- New `UserKeyDefinition`
- Overloads

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-02-22 19:19 UTC, MGibson1 requested changes
One copy pasta mistake and some possible minification issues, but this is looking _good_. I'm excited.

2024-02-22 19:19 UTC, MGibson1 commented on libs/common/src/platform/state/user-state.provider.ts
> +  abstract get<T>(keyDefinition: KeyDefinition<T> | UserKeyDefinition<T>): ActiveUserState<T>;
I believe this is redundant

2024-02-22 19:19 UTC, MGibson1 commented on libs/common/src/platform/state/user-key-definition.ts
> +export class UserKeyDefinition<T> {
For now, it might be smart to `implement KeyDefinition<T>` here.

2024-02-22 19:19 UTC, MGibson1 commented on libs/common/src/platform/state/user-key-definition.ts
> +  }
**issue**: It looks like these static methods got copied over without updating their documentation of return types

2024-02-22 19:19 UTC, MGibson1 commented on libs/common/src/platform/state/implementations/default-active-user-state.provider.ts
> +    }
For each of these usages of `instanceof`, this has bitten us in the past during minification despite them claiming it works. I suggest developing a robust type guard for `UserKeyDefinition` instead -- even just

```typescript
const USER_KEY_DEFINITION_MARKER: unique symbol = Symbol("UserKeyDefinition");
export class UserKeyDefinition<T> {
  readonly [USER_KEY_DEFINITION_MARKER] = true;
}
```

You could also define an enum of types and set that, but then you can define
```typescript
function isUserKeyDefinition<T>(keyDefinition: KeyDefinition<T> | UserKeyDefinition<T>): keyDefinition is UserKeyDefinition<T> {
 return keyDefinition[USER_KEY_DEFINITION_MARKER] === true
}
```

2024-02-23 16:23 UTC, justindbaur commented on libs/common/src/platform/state/user-state.provider.ts
> +  abstract get<T>(keyDefinition: KeyDefinition<T> | UserKeyDefinition<T>): ActiveUserState<T>;
Unfortunately it's not, I need this overload for the uses of `getActive` and `getUser` inside of `DefaultStateProvider`.

2024-02-23 16:23 UTC, justindbaur commented on libs/common/src/platform/state/user-key-definition.ts
> +  }
Good catch, updated.

2024-02-26 15:23 UTC, MGibson1 commented on libs/common/src/platform/state/implementations/default-active-user-state.provider.ts
> +    }
good point, it could have been loss of prototype stuff. This was a while ago, and I wasn't able to root cause beyond "avoid instanceof" and a general mistrust of minification guarantees

2024-02-26 15:26 UTC, MGibson1 approved these changes
I think the conversion function should help enough, thanks for looking into the type concern, I appreciate it.

2024-02-26 16:28 UTC, MGibson1 approved these changes

2024-02-26 16:28 UTC, merged