Remove bootstrap and enable tailwind preflight
bitwarden/clients pull request #8071
Opened 2024-02-23 17:07 UTC by Hinton

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2025-07-28 19:38 UTC, danielleflinn commented
@Hinton I just reviewed the Chromatic UI Tests and accepted the changes they seemed trivial and denied a few that need additional changes – see comments in Chromatic. 

It seems like the default text field and area components have lost some of the left margin on the input area. Ideally the input area text would align with the edge of the label, is this something you could look into improving since this PR makes it a bit worse than it is today?

2025-07-29 13:28 UTC, Hinton commented
@danielleflinn I've addressed most items you rejected. I'll take a look at the form inputs next.

2025-07-29 18:41 UTC, vleague2 commented on apps/web/src/scss/vault-filters.scss
> +    // @extend .no-btn;
Probably can delete this selector

2025-07-29 18:47 UTC, vleague2 commented on apps/web/src/scss/vault-filters.scss
> +    // @extend .no-btn;
Same here

2025-07-29 18:49 UTC, vleague2 commented on libs/components/src/tw-theme.css
> +@tailwind utilities;
This is also in preflight which imports this file, do we need it in both?

2025-08-01 11:51 UTC, Hinton commented on libs/components/src/tw-theme.css
> +@tailwind utilities;
Yes, I got errors without them. This file is also imported from non preflight apps.

2025-08-11 13:18 UTC, Hinton commented on libs/components/src/tw-theme-preflight.css
> +  }
@danielleflinn we should identify what color variable we want to use here instead of hard-coding it.

2025-08-11 14:20 UTC, vleague2 commented on libs/components/src/tw-theme.css
> +  * CL-483
@willmartian Maybe we should look at prioritizing CL-483 after this PR is merged?

2025-08-11 15:19 UTC, danielleflinn commented on libs/components/src/tw-theme-preflight.css
> +  }
@Hinton where are these border colors applied in the product interface? 
We use secondary-100 for the majority of borders now though so it likely could be updated to that.

2025-08-11 16:12 UTC, Hinton commented
@vleague2 I added inline to the avatar and removed the web-header change. I can't see any errors that have cropped up with the checkboxes and tables looks fine from my light testing.

2025-08-11 18:44 UTC, Hinton commented on libs/components/src/tw-theme-preflight.css
> +  }
These are Horizontal Rulers https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/hr. We use them in a couple of places like account fingerprint. 
<img width="488" height="210" alt="image" src="https://github.com/user-attachments/assets/d15ed746-f556-4072-beaa-b4ccba8ce28f" />

2025-08-11 18:50 UTC, danielleflinn requested changes
@Hinton I re-reviewed the Chromatic difs and it looks like there are still a few spacing issues. See comments in Chromatic.

2025-08-11 18:51 UTC, danielleflinn commented on libs/components/src/tw-theme-preflight.css
> +  }
Got it; you can update that to `secondary-100 `

2025-08-12 10:16 UTC, Hinton commented
@danielleflinn @vleague2 this should be ready for a final review now. I believe I've addressed all chromatic issues brought up.

2025-08-12 10:20 UTC, Hinton commented on libs/components/src/tw-theme-preflight.css
> +  }
100 is quite hard to see in dark mode.
<img width="494" height="188" alt="image" src="https://github.com/user-attachments/assets/28cbc6ed-a093-413b-a5ed-d21a5b01ac3c" />

2025-08-12 15:41 UTC, JaredSnider-Bitwarden approved these changes
LGTM!

2025-08-12 18:32 UTC, merged