[PM-6199] VaultFilterService keeps decrypted collections in memory after logout
bitwarden/clients pull request #8120
Opened 2024-02-27 20:33 UTC by gbubemismith

## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
We create a ReplaySubject<ColletionView>(1) [in the service](https://github.com/bitwarden/clients/blob/5c6245aaaef6453d3e6ee2e6dff9b5d805baafb9/apps/web/src/app/vault/individual-vault/vault-filter/services/vault-filter.service.ts#L66) that maintains an internal buffer that is not cleared on logout/lock. The subject keeps the decrypted collections in memory after logout which can cause them to briefly be displayed to the next user that logs in.

## Code changes
Fixed this by replacing the replaySubject with `decryptedCollections$` observable from the `collectionService`

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-02-27 23:27 UTC, shane-melton requested changes
Looks good! Just one small nit on a left over FIXME comment we can remove.

2024-02-27 23:27 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault-filter/services/vault-filter.service.spec.ts
>          // eslint-disable-next-line @typescript-eslint/no-floating-promises
nit: We can remove this FIXME comment

2024-02-28 00:08 UTC, gbubemismith commented on apps/web/src/app/vault/individual-vault/vault-filter/services/vault-filter.service.spec.ts
>          // eslint-disable-next-line @typescript-eslint/no-floating-promises
Thanks. I think I missed that.

2024-02-28 00:44 UTC, shane-melton approved these changes

2024-02-29 15:30 UTC, LRNcardozoWDF approved these changes

2024-03-13 18:49 UTC, shane-melton approved these changes

2024-03-21 20:42 UTC, merged