Ps/new i18n for angular
bitwarden/clients pull request #8122
Opened 2024-02-27 21:16 UTC by MGibson1

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Migrates i18n service to state providers and removes the usage of `getBgService` for it.

## Code changes

- **main.background / i18n factory / various i18n service extensions / bw.ts**: update dependencies with global state provider
- **browseri18nService**: This isn't needed since browserSync isn't being used anymore
- **services modules**: use a new i18nservice for browser, this removes a usage of browser session AND an instance of `getBgService`
- **settings.component / init.service / main.ts**: use the i18nService's update methods
- **i18n.main.ts**: This service needs to default to the stored value, then whatever is given by `app.getLocale` rather than the system language. These are likely the same, but the stored system language is really just the fallback language should locale not be set.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-02-28 15:59 UTC, justindbaur requested changes
A few questions.

2024-02-28 15:59 UTC, justindbaur commented on apps/desktop/src/platform/services/i18n.main.service.ts
> +    this.systemLanguage = app.getLocale();
At first glance this doesn't look like equivalent behavior to what was in main.ts, that first grabbed the save locale and if there wasn't one then it fell back to `app.getLocale()` is that taken care of in `super.init()`?

2024-02-28 15:59 UTC, justindbaur commented on libs/common/src/state-migrations/migrations/26-move-preferred-language.spec.ts
> +describe("ProviderKeysMigrator", () => {
copy/paste error.

2024-02-28 22:05 UTC, MGibson1 commented on apps/browser/src/popup/services/services.module.ts
>      },
good point 👍

2024-02-28 22:17 UTC, MGibson1 commented on apps/browser/src/platform/services/i18n.service.ts
> +        // Deprecated
No idea, but it's been deprecated for [5 years](https://github.com/bitwarden/clients/blob/72d0c7d860fbb9accc3a8e9c578e122f05522d07/src/services/i18n.service.ts)...

2024-02-28 22:35 UTC, MGibson1 commented on apps/desktop/src/app/accounts/settings.component.ts
> +      locale: (await firstValueFrom(this.i18nService.locale$)) ?? null,
Looks like I can just remove the coalesce entirely

2024-02-28 22:38 UTC, MGibson1 commented on apps/desktop/src/platform/services/i18n.main.service.ts
> +    this.systemLanguage = app.getLocale();
yeah, the state locale is now internal to the i18n service and is loaded on `init`. It falls back to the `systemLanguage` in the `TranslationService`'s own `init` method.

2024-02-29 02:01 UTC, justindbaur submitted a review, later dismissed

2024-02-29 02:12 UTC, justindbaur commented on apps/browser/src/platform/services/i18n.service.ts
> +        // Deprecated
Yikes... If I had to take a stab in the dark it would be the raw `fetch` rather than going through our own wrapper of it but 🤷

2024-03-04 04:32 UTC, willmartian submitted a review, later dismissed

2024-03-04 21:04 UTC, justindbaur submitted a review, later dismissed

2024-03-04 23:01 UTC, willmartian submitted a review, later dismissed

2024-03-06 15:52 UTC, willmartian submitted a review, later dismissed

2024-03-06 17:22 UTC, justindbaur submitted a review, later dismissed

2024-03-11 17:29 UTC, justindbaur approved these changes

2024-03-11 17:59 UTC, willmartian approved these changes

2024-03-11 17:59 UTC, merged