[AC-2156] Billing State Provider Migration
bitwarden/clients pull request #8133
Opened 2024-02-28 15:00 UTC by cturnbull-bitwarden

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

WIP

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-03-06 05:07 UTC, eliykat approved these changes
AC changes are approved

2024-03-06 18:26 UTC, cturnbull-bitwarden commented
Taking this back to draft as I missed some usages

2024-03-06 19:30 UTC, justindbaur requested changes
Mainly just want to throw out making a few of these components more true observable sooner rather than later. I think in some of the places, the ones where `takeUntil` had to be fully implemented, would actually have fewer overall changes. 

Platform doesn't own any of those components though so this portion of the feedback can be ignored or left up to each teams components and left for a follow up ticket.

2024-03-08 21:13 UTC, cturnbull-bitwarden commented on apps/web/src/app/auth/settings/emergency-access/emergency-access.component.ts
> +      });
I just pushed an update for this! Let me know if you think I missed anything. I didn't make this change everywhere it occurs given that some of them would require more changes in the opposite direction. I'm open to persuasion though so let me know if you think otherwise

2024-03-08 21:13 UTC, cturnbull-bitwarden commented on apps/web/src/app/auth/settings/two-factor-setup.component.ts
> +      });
See the first comment

2024-03-08 21:13 UTC, cturnbull-bitwarden commented on apps/web/src/app/core/guards/has-premium.guard.ts
> +    );
I did go ahead and make this change. Feel free to take a look

2024-03-08 21:14 UTC, cturnbull-bitwarden commented on libs/common/src/vault/services/sync/sync.service.ts
> +    );
Agreed! Good catch. I updated it to have a single setter and added some unit tests to verify that the observables emit a single time

2024-03-08 21:14 UTC, cturnbull-bitwarden commented on libs/common/src/billing/services/account/billing-account-profile-state.service.ts
> +    );
Updated!

2024-03-08 21:14 UTC, cturnbull-bitwarden commented on libs/common/src/state-migrations/migrations/30-move-billing-account-profile-to-state-providers.ts
> +      await helper.set(userId, account);
Updated!

2024-03-11 14:42 UTC, amorask-bitwarden approved these changes
Billing files look good.

2024-03-12 01:18 UTC, eliykat approved these changes

2024-03-12 13:47 UTC, audrey-jensen requested changes
Overall this is looking great. I mostly have suggestions, and the requested change is minor. Great work!

⚠️ requested change
🌱 possible tech debt
🎨 suggestion

2024-03-12 13:47 UTC, audrey-jensen commented on libs/common/src/billing/abstractions/account/billing-account-profile-state.service.abstraction.ts
> +export abstract class BillingAccountProfileStateServiceAbstraction {
🌱 [The naming convention is changing](https://github.com/bitwarden/contributing-docs/blob/f633f2cdd866c8f02801072e170ba9b77f76ec0d/docs/architecture/clients/presentation/angular.md#abstract--default-implementations).

2024-03-12 13:47 UTC, audrey-jensen commented on libs/common/src/billing/abstractions/account/billing-account-profile-state.service.abstraction.ts
> +  canAccessPremium$: Observable<boolean>;
🎨 Adding some documentation to distinguish these parameters from each other would be helpful. A few questions in my mind that aren't answered by the names alone:

* When do these observables update? If I upgrade to a premium subscription while logged in, what happens? Downgrade?
* What happens if I upgrade my personal account to an organization account? Do I lose "Premium Personal" and gain "Premium From Organization"? Do I have both?
* How does `hasPremiumFromOrganization$` account for multiple organizations? Does this follow "any" or "all" semantics? Does it respond in realtime to changes in my organization?

In a general sense, I'd assume these questions also affect `canAccessPremium$`, but it's important to call out whether that's true or not--something like "this emits `true` when `hasPremiumFromOrganization$` or `hasPremiumPersonally$` would emit `true`, and updates when either update."

2024-03-12 13:47 UTC, audrey-jensen commented on libs/angular/src/tools/send/add-edit.component.ts
> +
⚠️ This should be wired using a subscription instead of await, so that the component updates when the observable emits. This uses basically the same code you used in [`tools.component.ts`](https://github.com/bitwarden/clients/blob/4ed8a62e725e2def5b9190c6405fe1ce14f37c62/apps/web/src/app/tools/tools.component.ts#L20-L31)

2024-03-12 14:00 UTC, jprusik submitted a review, later dismissed
LGTM on the autofill side

2024-03-12 19:47 UTC, cturnbull-bitwarden commented on libs/common/src/billing/abstractions/account/billing-account-profile-state.service.abstraction.ts
> +export abstract class BillingAccountProfileStateServiceAbstraction {
Thanks for the heads up! I went ahead and renamed the service classes

2024-03-12 19:48 UTC, cturnbull-bitwarden commented on libs/common/src/billing/abstractions/account/billing-account-profile-state.service.abstraction.ts
> +  canAccessPremium$: Observable<boolean>;
Good callout! I had kept these properties the same from how they were named in the state service, but you bring up an excellent point by saying that they're not super descriptive. I went in and added some jsdocs and renamed the "from org" property. Let me know if you think it's still not clear!

2024-03-12 19:48 UTC, cturnbull-bitwarden commented on libs/angular/src/tools/send/add-edit.component.ts
> +
Updated!

2024-03-13 00:13 UTC, audrey-jensen commented on libs/common/src/billing/abstractions/account/billing-account-profile-state.service.abstraction.ts
> +  canAccessPremium$: Observable<boolean>;
Looks good! :)

2024-03-13 00:14 UTC, audrey-jensen submitted a review, later dismissed

2024-03-13 13:02 UTC, jlf0dev commented
We'll also need to set this on authentication [here](https://github.com/bitwarden/clients/blob/29b5643310570f4f1b03f55acafd59166b08fc00/libs/auth/src/common/login-strategies/login.strategy.ts#L152) (sorry for all the dependency injection this adds, I know its not ideal 😞 )

2024-03-13 13:56 UTC, audrey-jensen submitted a review, later dismissed

2024-03-13 15:50 UTC, justindbaur submitted a review, later dismissed
Looks great, thanks for trying a few of `boolean` to `Observable<boolean>` on the components. There are a few in here not using that but that is perfectly fine with me, now we have a few good examples of how to do it and the rest can be done in smaller refactors as those components are edited for other reasons.

2024-03-13 15:52 UTC, audrey-jensen approved these changes

2024-03-13 15:57 UTC, jprusik submitted a review, later dismissed

2024-03-13 18:34 UTC, audrey-jensen submitted a review, later dismissed

2024-03-13 19:06 UTC, audrey-jensen reviewed
⛏️ Nitpick

2024-03-13 19:06 UTC, audrey-jensen commented on apps/cli/src/tools/send/commands/edit.command.ts
> +    ) {
⛏️ I'd break this out onto another line and use a shorter name for the injected parameter so that prettier doesn't wrap it like this.

```typescript
// line 21
    private accountService: BillingAccountProfileStateService,

// here
let canAccessPremium = firstValueFrom(this.accountService.hasPremiumFromAnySource$);
if(send.type === SendType.File && await canAccessPremium) {
   // ...
}
```

2024-03-13 19:31 UTC, cturnbull-bitwarden commented on apps/cli/src/tools/send/commands/edit.command.ts
> +    ) {
Updated!

2024-03-13 19:40 UTC, audrey-jensen approved these changes

2024-03-13 20:54 UTC, eliykat approved these changes

2024-03-13 21:56 UTC, gbubemismith approved these changes

2024-03-14 12:52 UTC, amorask-bitwarden approved these changes

2024-03-14 12:58 UTC, justindbaur approved these changes

2024-03-14 16:10 UTC, jlf0dev submitted a review, later dismissed
Auth looks good!

2024-03-14 19:15 UTC, audrey-jensen approved these changes

2024-03-14 19:16 UTC, audrey-jensen requested changes
Gotta take back my approval. Your tests are failing. :(

2024-03-15 14:12 UTC, audrey-jensen submitted a review, later dismissed

2024-03-15 19:01 UTC, jprusik submitted a review, later dismissed
LGTM on the autofill side of things!

2024-03-15 19:30 UTC, audrey-jensen approved these changes

2024-03-15 19:40 UTC, jlf0dev approved these changes

2024-03-15 19:43 UTC, gbubemismith approved these changes

2024-03-15 19:43 UTC, amorask-bitwarden approved these changes

2024-03-15 19:43 UTC, jprusik approved these changes

2024-03-15 19:47 UTC, justindbaur approved these changes

2024-03-15 19:48 UTC, justindbaur approved these changes

2024-03-15 19:53 UTC, vincentsalucci approved these changes
Approved on behalf of @eliykat

2024-03-15 19:53 UTC, merged