[PM-6524]Improve import null validations and error messages
bitwarden/clients pull request #8135
Opened 2024-02-28 16:06 UTC by aj-rosado

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

We are having some unexpected erros on the import, in some cases we are trying to access the `id` on undefined objects. This protects a possible cause for that error and adds a more descriptive error message to help track the cause.

## Code changes
- **import.service.ts:** Validating if `targetSelector` is not null on `setImportTarget` and added more descriptive message to help understand where the error occurs

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-02-29 14:41 UTC, audrey-jensen requested changes
⚠️ requested change
🎨 suggestion
📝 notes

2024-02-29 14:41 UTC, audrey-jensen commented on libs/importer/src/services/import.service.ts
> +      if (importResult.folders != null) {
🎨 I wonder whether, instead of the null checks, these loops might be written more cleanly using a null-coalescion and a map.

```javascript
const folderTasks = (importResult.folders ?? [])
  .map(f => this.folderService.encrypt(f));
for(let folder of await Promise.all(folderTasks)) {
  request.folders.push(new FolderWithIdRequest(folder));
}
```

2024-02-29 14:41 UTC, audrey-jensen commented on libs/importer/src/services/import.service.ts
> +          request.folderRelationships.push(new KvpRequest(r[0], r[1])),
🎨 Here's a place where deconstruction and null coalescion ends up helping readability.

```javascript
for(let [key, value] of importResult.folderRelationships ?? []) {
  request.folderRelationships.push(new KvpRequest(key, value));
}
```

2024-02-29 14:41 UTC, audrey-jensen commented on libs/importer/src/services/import.service.ts
> +    try {
📝 If you decide to try out the examples I provided above, then these could be improved using similar techniques.

2024-02-29 14:41 UTC, audrey-jensen commented on libs/importer/src/services/import.service.ts
⚠️ Since this logic is unit tested, the tests should be updated where possible to exercise the new code.

2024-03-06 15:26 UTC, audrey-jensen requested changes
Seems that there's still lines you've modified that aren't covered by tests. I'd like the patch % to be at least 70%. I think you can get there by testing the loops (lines 343-354 and line 381 in `import.service.ts`).

2024-03-06 18:06 UTC, audrey-jensen approved these changes

2024-08-19 17:27 UTC, audreyality approved these changes

2024-08-22 13:48 UTC, audreyality approved these changes
📝 Looks like this is just conflicts with the merge that hoists the userid out of active user state providers.

2024-09-09 08:55 UTC, closed without merging

2024-09-09 08:56 UTC, aj-rosado commented
Closing this PR. Will open a new one in the future only with the added test cases