Migrate provider service to state provider
bitwarden/clients pull request #8173
Opened 2024-03-01 20:32 UTC by addisonbeck

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-03-04 00:26 UTC, eliykat requested changes
Nicely done 👏

2024-03-04 00:26 UTC, eliykat commented on libs/common/src/admin-console/services/provider.service.ts
> +  }
Still references `orgs`.

2024-03-04 16:51 UTC, justindbaur requested changes
Just the tiniest nit and then this is good to go from platform.

2024-03-04 16:51 UTC, justindbaur commented on libs/common/src/state-migrations/migrations/28-move-provider-state-to-state-provider.spec.ts
> +    userEvents: true,
nit:
```suggestion
    useEvents: true,
```

2024-03-04 17:41 UTC, addisonbeck commented on libs/common/src/state-migrations/migrations/28-move-provider-state-to-state-provider.spec.ts
> +    userEvents: true,
Implemented from suggestion on https://github.com/bitwarden/clients/pull/8173/commits/c88324cc0f4bb82828202baa62500ed8544a1a96

2024-03-04 17:46 UTC, addisonbeck commented on libs/common/src/admin-console/services/provider.service.ts
> +  }
Whoops! Changed here: https://github.com/bitwarden/clients/pull/8173/commits/28ae8e8e30c1ebdc5be06c04c94e741671f0cebb

2024-03-04 18:34 UTC, addisonbeck commented on libs/common/src/admin-console/services/provider.service.spec.ts
> +      expect(providers[3]).toEqual(new Provider(mockData[3]));
Done on 
[Compare equality over entire array in a test](https://github.com/bitwarden/clients/pull/8173/commits/7cb5744b7fc27cb25cf7792b7c168658c9cb62ba)

2024-03-04 18:36 UTC, addisonbeck commented on apps/cli/src/bw.ts
> +      this.providerService.save(null, userId as UserId),
I don't understand what you mean here. Does sync run for non active users? The sync seems to only run for a default user, and I was under the assumption that a sync was run on account change and then the active unlocked account was the only one ever synced.

2024-03-04 23:08 UTC, eliykat submitted a review, later dismissed

2024-03-04 23:09 UTC, eliykat commented on apps/cli/src/bw.ts
> +      this.providerService.save(null, userId as UserId),
Hmm I think you're right here, I was just on the wrong track yesterday.

2024-03-05 14:11 UTC, justindbaur approved these changes

2024-03-05 18:26 UTC, justindbaur approved these changes

2024-03-05 19:12 UTC, vincentsalucci approved these changes
Approving merge conflict resolution on behalf of @eliykat

2024-03-05 19:35 UTC, merged