tax info component migration
bitwarden/clients pull request #8199
Opened 2024-03-04 17:52 UTC by vinith-kovan

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [X] Other
```

## Objective

Migrate the tax info component to use the Component Library

## Code changes

- billing-history.component.html - Changed the table to use the Component Library equivalent (bit-table).
- billing-history-view.component.html - Changed class name to use Tailwind CSS equivalent (bit-tab-nav-bar).

## Screenshots

Before migration:
upgrade plan
![image](https://github.com/bitwarden/clients/assets/156108204/c4e8a725-78b3-48a4-a079-49d70655c841)
![image](https://github.com/bitwarden/clients/assets/156108204/fa381001-1ae9-431e-a524-9950ee0663a7)

Create new organization
![image](https://github.com/bitwarden/clients/assets/156108204/c6e80c3d-de38-47ef-8801-47f10d4673e5)

After migration:
upgrade plan
![image](https://github.com/bitwarden/clients/assets/156108204/10c2b968-36ef-477b-a06e-099058621a2f)
![image](https://github.com/bitwarden/clients/assets/156108204/a093c789-2bf9-4469-a582-941a68278a29)

Create new organization
![image](https://github.com/bitwarden/clients/assets/156108204/56b2ecfd-f5d7-45ed-b71b-e90d8a9f4417)

2024-03-07 01:25 UTC, willmartian requested changes
Hey @vinith-kovan,

Rather that replacing the bootstrap `row` and `col-` utilities with their source styles, could you instead use CSS grid? 

- `row` would be `tw-grid tw-grid-cols-12 tw-gap-4`
- `col-3` would be `tw-col-span-3`, etc

This should preserve both the styles and the _semantic_ meaning of the styles. Let me know if you run into any issues with this approach.

2024-03-07 01:25 UTC, willmartian commented on apps/web/src/app/billing/shared/tax-info.component.ts
> +    { name: "-- Select --", value: "", disabled: false },
Nice change moving this into the TS file. 👍 

Makes it a bit easier to filter/manipulate/share this in the future if needed.

2024-03-07 01:25 UTC, willmartian commented on apps/web/src/app/billing/shared/tax-info.component.html
> +    <div class="tw-relative tw-mb-4">
I don't think we need `tw-relative tw-mb-4` anymore.

2024-03-12 00:34 UTC, willmartian approved these changes
Changes LGTM 👍

2024-03-14 15:42 UTC, amorask-bitwarden submitted a review, later dismissed

2024-05-08 17:46 UTC, amorask-bitwarden requested changes
Will re-review after conflicts are resolved.

2024-05-14 11:46 UTC, cyprain-okeke reviewed
Looks good but we have conflicts

2024-06-04 13:33 UTC, amorask-bitwarden submitted a review, later dismissed

2024-06-12 07:08 UTC, cyprain-okeke approved these changes

2024-06-12 07:58 UTC, merged