[PM-5539] Migrate ThemingService
bitwarden/clients pull request #8219
Opened 2024-03-05 21:47 UTC by justindbaur

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Migrate `AbstractThemingService` to use state providers and be a little more reactive. This service has one side effect that can be started with a document that should have theme changes applied to it.

## Code changes

- DI Changes
- Refactor ThemingService to have a single subscription and pass that back to the caller so they could theoretically unsubscribe from it.
- Use `StateProvider` for managing cross context theme updates. 

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-03-06 21:31 UTC, MGibson1 requested changes
This stream manipulation is masterful 👨‍🍳 💋

I did have one major suggestion I'd like to see implemented that will avoid the angular in background issues.

2024-03-06 21:31 UTC, MGibson1 commented on apps/browser/src/background/main.background.ts
> +
**suggestion**: This is needed due to overlay and notification bar services requiring the configured theme, but in reality they only only need the configured state.

This may be a reasonable instance to divorce the concept of a service owning its state directly and allow a third party to manage it -- as I did with the biometrics state service for similar reasons.

2024-03-06 21:31 UTC, MGibson1 commented on libs/angular/src/platform/services/theming/theming.service.ts
Please rename file

2024-03-06 21:31 UTC, MGibson1 commented on libs/angular/src/platform/services/theming/theming.service.ts
> +  static createSystemThemeFromWindow(window: Window): Observable<ThemeType> {
this is awesome! :godmode:

2024-03-06 21:31 UTC, MGibson1 commented on apps/browser/src/popup/services/services.module.ts
> +      useFactory: (stateProvider: StateProvider, platformUtilsService: PlatformUtilsService) => {
any chance you didn't retest this safari limitation and it just works now?

2024-03-06 21:31 UTC, MGibson1 commented on apps/desktop/src/app/services/desktop-theming.service.ts
> +  private static createSystemThemeObservable() {
This one's even better! 🥇

2024-03-06 21:31 UTC, MGibson1 commented on libs/angular/src/platform/services/theming/theming.service.abstraction.ts
> +  monitorThemeChanges: (document: Document) => Subscription;
**nit**: I really feel this name is backwards in usage, it's more like `applyThemeChangesTo`

2024-03-06 21:31 UTC, MGibson1 commented on libs/common/src/platform/state/key-definition.ts
> +import { type Jsonify } from "type-fest";
**question**: what's this change do?

2024-03-06 22:14 UTC, cagonzalezcs commented on apps/browser/src/background/main.background.ts
> +
Removal of this is likely a necessity in Manifest v3, any reference to `@angular/core` throws a runtime error when attempting to run the background service worker.

Along with this consideration, work [has been previously implemented](https://github.com/bitwarden/clients/pull/7770) to remove usage of `window.matchMedia` within the background. There isn't a way to reference the user's system preference within the service worker.

2024-03-07 01:35 UTC, justindbaur commented on apps/web/src/theme.ts
I much prefer the `this` binding behavior of arrow functions. It feels more like C# where it will capture whatever it is at the time of the arrow function creation and avoids the ability for people to accidentally/on purpose rebind the `this` of my function.

2024-03-07 14:50 UTC, justindbaur commented on apps/web/src/theme.ts
> +    }
This had come from the `theme.js` implementation where it guarded against sending `null` into `JSON.parse` but that is totally fine so I've removed it.

2024-03-07 14:55 UTC, justindbaur commented on libs/common/src/platform/state/key-definition.ts
> +import { type Jsonify } from "type-fest";
My attempt to maybe be able to use a `KeyDefinition` in `theme.ts` but trying to keep the final size down, even though I knew this wouldn't help, had to try. 

Since I'm not using KeyDefinition in it I will remove this.

2024-03-07 15:00 UTC, justindbaur commented on apps/browser/src/popup/services/services.module.ts
> +      useFactory: (stateProvider: StateProvider, platformUtilsService: PlatformUtilsService) => {
Yep, same I tried to see if it had gotten better and it hasn't. As Cesar said, we'll probably still be able to reference the background page for a `window` object in Safari's MV3 and if we can't then they will just have to lose the `System` option and we probably hardcode a `of(ThemeType.Light)` to the constructor parameter.

2024-03-07 16:16 UTC, justindbaur commented on apps/browser/src/background/main.background.ts
> +
I did go with having a separate service just for state. The plan was to have a quick follow up to this to move the service out of angular and the way of having it use `throwError` was avoiding having this use `window` directly. But having a `ThemeStateService` also does that along with removing the chance someone might accidentally retrieve the effective theme and getting this error.

2024-03-07 16:17 UTC, justindbaur commented on apps/browser/src/autofill/background/notification.background.ts
> +      theme: await firstValueFrom(this.themingService.configuredTheme$),
Switched to calling a new `ThemeStateService`

2024-03-07 16:17 UTC, justindbaur commented on apps/browser/src/autofill/background/overlay.background.ts
> +      theme: await firstValueFrom(this.themingService.configuredTheme$),
Also switched to calling a new `ThemeStateService`.

2024-03-07 18:00 UTC, cagonzalezcs submitted a review, later dismissed
Awesome job on this dude, gave a couple of nits but approving this work regardless of whether they are considered.

Also, I tested this behavior in mv3 to verify no issues exist. We're good to go on that.

If you need a re-review/approval just let me know.

2024-03-07 18:00 UTC, cagonzalezcs commented on apps/browser/src/background/main.background.ts
> +    const themeStateService = new DefaultThemeStateService(this.globalStateProvider);
Nit - Any reason this is defined as a `cons` declaration rather than as a property of the class?

Not necessarily asking for a change here, just wondering.

2024-03-07 18:00 UTC, cagonzalezcs commented on apps/web/src/theme.ts
Nit - Not gonna knock the decision to use arrow functions here instead of regular function expressions, but you likely aren't receiving any inherent benefit that arrow functions provide here. 

Since the file doesn't contain any significant usage of self-referential closures, arrow functions here don't act any differently than regular functions. You could also reference `getLegacyTheme` below the core logic of `setTheme` if it was a regular function, which would use hoisting to find the method definition in the block scope of the `setTheme` method.

I might give one suggestion, given that file appears to act as as drop-in executable. If you wrap the content of `setTheme` in an IIFE, you're effectively triggering the same behavior without the `setTheme` declaration. 

``` javascript
// Set theme on page load
// This is done outside the Angular app to avoid a flash of unthemed content before it loads
(function () {
  const getLegacyTheme = (): string | null => {
    // MANUAL-STATE-ACCESS: Calling global to get setting before migration
    // has had a chance to run, can be remove in the future.
    // Tracking Issue: https://bitwarden.atlassian.net/browse/PM-6676
    const globalState = window.localStorage.getItem("global");

    const parsedGlobalState = JSON.parse(globalState) as { theme?: string } | null;
    return parsedGlobalState ? parsedGlobalState.theme : null;
  };

  const defaultTheme = "light";
  const htmlEl = document.documentElement;
  let theme = defaultTheme;

  // First try the new state providers location, then the legacy location
  const themeFromState =
    window.localStorage.getItem("global_theming_selection") ?? getLegacyTheme();

  if (themeFromState) {
    if (themeFromState.indexOf("system") > -1) {
      theme = window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
    } else if (themeFromState.indexOf("dark") > -1) {
      theme = "dark";
    }
  }

  if (!htmlEl.classList.contains("theme_" + theme)) {
    // The defaultTheme is also set in the html itself to make sure that some theming is always applied
    htmlEl.classList.remove("theme_" + defaultTheme);
    htmlEl.classList.add("theme_" + theme);
  }
})();
```

2024-03-07 18:00 UTC, cagonzalezcs commented on apps/web/src/theme.ts
The above suggestion isn't something I'd consider a blocker though, just a suggestion.

2024-03-07 18:57 UTC, justindbaur commented on apps/browser/src/background/main.background.ts
> +    const themeStateService = new DefaultThemeStateService(this.globalStateProvider);
In my opinion it being a property on the class is useful only for things that need to be references through `getBgService`, which we shouldn't add to, and for referencing it in `bootstrap` to call an initialization method on it. If your service is just a building block for other things then you can do a `const` and avoid a possible merge conflict and have compile time errors if someone tries to use it before it's been created vs if they reference my property `this.themeStateService` before I've actually created it it will compile fine but give a `TypeError` when the eventually call a method on that service.

2024-03-07 19:00 UTC, justindbaur commented on apps/web/src/theme.ts
This particular usage definitely doesn't have a `this` issue, it's just become my general style. The compilation process does rewrite this pattern as a IIFE but in my opinion the IIFE makes it further from something that could be tested more easily. With this I could convert this to a testable module with a couple lines of code being changed.

2024-03-07 19:23 UTC, cagonzalezcs commented on apps/web/src/theme.ts
Yeah, I don't disagree there. `IIFE`'s can be a pain to test... possible to do, but definitely less convenient.

2024-03-11 21:28 UTC, MGibson1 commented on apps/browser/src/background/main.background.ts
> +    const themeStateService = new DefaultThemeStateService(this.globalStateProvider);
this is good insight and probably something we should advocate for as we remove `getBgService` calls

2024-03-11 21:34 UTC, MGibson1 submitted a review, later dismissed

2024-03-11 21:34 UTC, MGibson1 commented on libs/angular/src/services/jslib-services.module.ts
> +        new AngularThemingService(
**nit**: if you provide the observable as an injection token, you don't need this factory or deps anymore

2024-03-12 16:26 UTC, justindbaur commented on libs/angular/src/services/jslib-services.module.ts
> +        new AngularThemingService(
Since I needed to fix some merge conflicts anyways I decided to do this and was able to delete `DesktopThemingService` altogether.

2024-03-12 17:05 UTC, justindbaur commented
@cagonzalezcs @MGibson1 I had merge conflicts so I decided to implement Matt's nit, while retesting things I actually noticed that only web has the default theme of `ThemeType.Light` and the rest have `ThemeType.System` so I also fixed that issue.

2024-03-12 19:51 UTC, MGibson1 approved these changes

2024-03-13 14:08 UTC, cagonzalezcs approved these changes

2024-03-13 15:22 UTC, MGibson1 approved these changes

2024-03-13 15:25 UTC, merged