Autofill/pm 5744 adjust fido2 page script injection for mv3
bitwarden/clients pull request #8222
Opened 2024-03-06 00:30 UTC by cagonzalezcs

WIP

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-03-14 15:43 UTC, cagonzalezcs commented on apps/browser/src/platform/browser/browser-api.register-content-scripts-polyfill.ts
> +/**
This polyfill facilitates the ability for us to dynamically set and unset static content script declarations, similar to how we set these within `manifest.json`. Firefox has an mv2 API that already allows this within the [browser.contentScripts.register](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contentScripts/register) API. Chrome and Safari do not however, and this polyfill facilitates that behavior. Mv3 does have an API for this feature, which we are conditionally using when available.

I've decided to add this [content scripts register polyfill](https://github.com/fregante/content-scripts-register-polyfill) in our codebase directly rather than through npm. Two benefits come as a result of this:

1. The npm bundle that was being generated by the npm package was causing compilation error within Jest. This was happening due to imports that were happening within the package. Those errors weren't happening when running `npm run build:watch`, but it's possible that these errors might happen with the prod compilation process.
2. I've modified the polyfill to conditionally populate global references to the Chrome extension API. Essentially, we only do that in cases where it is absolutely necessary. For mv2 Firefox or mv3, we will not need to trigger the logic that establishes this polyfill.

2024-04-02 15:50 UTC, cagonzalezcs commented on apps/browser/tsconfig.json
> +    "lib": ["ES2021.String"],
This change allows us to the the `String.replaceAll` method within the dynamic content script registration polyfill without triggering an eslint error.

If we'd like to make changes in regard to that (perhaps avoiding usage of that `String.replaceAll` method), then I'm up for discussing it.

2024-04-02 15:52 UTC, cagonzalezcs commented on libs/common/src/vault/services/fido2/fido2-utils.ts
> +  static fromB64toUrlB64(b64Str: string) {
These additions represent a duplication of the code within the `Utils` class that the Platform Team provides.

The reason why we are doing this is to lighten the size of `page-script.ts`, which goes from loading about ~650kb to about ~50kb. The change is significant enough to facilitate duplicate of this logic in this regard, though I'd definitely like to refactor this in the future.

2024-04-02 16:07 UTC, cagonzalezcs commented on apps/browser/src/manifest.json
> +    "webNavigation"
IMPORTANT: This `webNavigation` permission is new to the extension, and might bring extra scrutiny to our review process. This shouldn't show any new warnings to users however, as the same warning shown to users for usage of this permission is shown for usage of the `tabs` permission.

As far as justification for the permission goes, we are using `webNavigation` to capture all frames loaded within a tab and dynamically inject a content script based on the dynamic registration polyfill's approach to dynamically registering content scripts for the extension.

2024-04-04 09:23 UTC, coroiu requested changes
Big PR but lovely to read with lots of documentation, unit tests, readability improvements, complexity being moved and encapsulated, and more! Great work!

I've added a fair bit of comments, but most of them are just nitpicks and naming convention suggestions. Most of the unit test comments are actually valid in more places that just where I've commented. Sometimes I've mentioned this in the comment, but not always, so if you agree with a comment then please check through the rest of the file to see if the feedback is applicable in other places as well!

Very few actual issues, but I did feel like I needed some additional context to properly review the `fido2.background.ts` port handling (I've put a separate comment for this).

2024-04-04 09:23 UTC, coroiu commented on apps/browser/src/vault/fido2/content/page-script.webauthn-supported.spec.ts
> +      }
🎨 suggestion: use `expect().toThrow()` see similar comment further up

2024-04-04 09:23 UTC, coroiu commented on apps/browser/src/vault/fido2/content/page-script.webauthn-supported.spec.ts
> +    it("falls back to the default browser credentials API if an error occurs", async () => {
⛏️ nit: 
```suggestion
    it("falls back to the default browser credentials API when an error occurs", async () => {
```

2024-04-04 09:23 UTC, coroiu commented on apps/browser/src/vault/fido2/content/page-script.webauthn-supported.spec.ts
> +    it("creates and returns a WebAuthn credential", async () => {
:pick: nit (non-blocking): when? :)

2024-04-04 09:23 UTC, coroiu commented on apps/browser/src/vault/fido2/content/page-script.webauthn-supported.spec.ts
> +    it("should ", async () => {
❓question: what's up with this describe => it structure? Did you forget something? :)

2024-04-04 09:23 UTC, coroiu commented on apps/browser/src/vault/fido2/content/page-script.webauthn-unsupported.spec.ts
> +    });
🎨 suggestion/question: Shouldn't we test the `navigator.credentials.create` return-value somehow? Maybe replace

```
      expect(WebauthnUtils.mapCredentialRegistrationResult).toHaveBeenCalledWith(
        mockCreateCredentialsResult,
      );
```

with 

```
expect(result).toBe(mockCreateCredentialsResult)
```

?

2024-04-04 09:23 UTC, coroiu commented on apps/browser/src/vault/fido2/content/page-script.webauthn-unsupported.spec.ts
> +    it("should ", async () => {
same here :)

2024-04-04 09:23 UTC, coroiu commented on libs/common/src/vault/services/fido2/fido2-utils.ts
> +  static fromB64toUrlB64(b64Str: string) {
❓ question: Do we have tests in the original location that we should also duplicate?

2024-04-04 09:23 UTC, coroiu commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +// import registerContentScript from "content-scripts-register-polyfill/ponyfill.js";
remove?

2024-04-04 09:24 UTC, coroiu commented on apps/browser/src/vault/fido2/background/fido2.background.ts
> +export default class Fido2Background implements Fido2BackgroundInterface {
❓ question: Any particular reason for making this a default export? I don't think we usually do this, but I might be wrong :)

2024-04-04 14:30 UTC, cagonzalezcs commented on apps/browser/src/background/runtime.background.ts
> -      return false;
No, the reason why we were having those weird bugs with responses was because we were passing back promises with the `onMessage` handler. Originally the implementation of the extension was riddled with `async` method handlers, and as a result we were experiencing race conditions anytime a `chrome.runtime.sendMessage` call depended on a `sendResponse` return value.

That said, the only time you should ever return a value from a `chrome.runtime.onMessage` handler is when you are wanting to signal to the message sender that an async response needs to be awaited. That should be done by returning a `true` value after calling the `async sendResponse` method. You should never return anything other than that `true` value in that specific use case.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage

Returning `false` doesn't exactly break the implementation, but it doesn't do anything significant in either regard. Removing it just removes a redundant/unnecessary piece of code.

2024-04-04 14:34 UTC, cagonzalezcs commented on apps/browser/src/platform/browser/browser-api.ts
> +   * scripts within manifest v2.
🤷 

Lol, modified all of the JS Doc descriptions for these to be on a single line.

2024-04-04 15:27 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +      fido2ClientService.isFido2FeatureEnabled = jest.fn().mockResolvedValue(true);
Good call, I also realized that I hadn't wrapped these mocked dependencies in a `MockProxy<T>` typing, so I was getting errors when attempting to implement your suggestion. 

Applied refactors around this suggestion, including removals of `jest.spyOn` calls where they were unnecessary due to the reworked typing.

2024-04-04 15:51 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +  let fido2Background: Fido2Background;
Oh nice, this is new to me. I've never messed around with setting definite assignment assertions.

I've applied these to my tests.

2024-04-04 15:52 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +  });
Done, good call.

2024-04-04 15:55 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +    it("skips injecting the FIDO2 content scripts into tabs that do not have a secure url protocol", async () => {
Adjusted the naming convention.

As for why we are testing it, mainly doing so to test the early return asserting that we do not trigger unexpected injections of script content in an insecure context.

2024-04-04 15:57 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +    it("injects the FIDO2 content scripts that contain a secure url protocol", async () => {
Applied to the implementation

2024-04-04 16:02 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/background/fido2.background.ts
> +    if (typeof previousEnablePasskeysSetting === "undefined") {
So in this instance, your approach could definitely work. Since we're setting a variable before this check, if the value of `this.currentEnablePasskeysSetting` is `undefined` then this check would trigger correctly.

I use `typeof varName === "undefined"` as a general pattern since it's safer than just checking `varName === undefined`. 

Take for instance when we're checking for the presence of the `window` object in the background script service worker. Checking for that value directly throws an uncaught error, but using `typeof window` instead renders the string value `"undefined"` without throwing that error.

I can adjust it in this instance if you'd like, but there isn't really a benefit one way or the other (aside from being a bit less verbose when structured in the way your suggestion is structured).

2024-04-04 16:13 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +    it("skips destroying and re-injecting the content scripts if the enablePasskeys setting is first being read", async () => {
I made some updates to the test to be more obvious regarding what is happening. Also updated the messaging to:

`it("does not destroy and re-inject the content scripts when triggering `handleEnablePasskeysUpdate` with an undefined currentEnablePasskeysSetting property")`

The context for this test is that we are subscribing to updates within the `vaultSettingsService.enablePassks$` observable in order to handle triggering injection/destruction logic of the content scripts. The problem with that is that we need to trigger injection of these scripts on install for all existing tabs, but only when the extension is first installed. 

Since subscribing to the observable triggers the handler, then we need to ensure that we guard against re-injecting the content scripts unnecessarily. Thus if we don't have a previously set value, we know that we want to avoid any logic tied to the observable's state.

2024-04-04 16:15 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +    it("destroys the content scripts but skips re-injecting them if the enablePasskeys setting is set to `false`", async () => {
Done, the wording has been changed to match your suggestion

2024-04-04 16:19 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +    it("registers the page-script-append-mv2.js and content-script.js content scripts for manifest v2 if the enablePasskeys setting is turned on", async () => {
Solid suggestion, done.

2024-04-04 16:21 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +    it("unregisters the FIDO2 page-script.js and content-script.js content scripts for manifest v3 if the enablePasskeys setting is turned off", async () => {
Done, though I like being verbose, I feel the scope of these tests should point to the purpose of `page-script.ts`.... actually, to be honest I'd like to rename `page-script.ts` and `content-script.ts` to be more specific to passkeys in the future, but I definitely want to wait on that for now.

2024-04-04 16:21 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +    it("ignores messages who do not have a handler associated with a command within the message", () => {
Done

2024-04-04 16:25 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +      expect(fido2Background["abortManager"].abort).not.toHaveBeenCalled();
Hm, I could remove this test but this exists simply to verify that we are not acting on messages that do not have a registered handler on the `extensionMessageHandlers`. 

We could check other functions that exist on the handler to be thorough... but I feel that it's a bit unnecessary.... that said, this test itself only checks an exit condition from the handler... so it also is kind of unnecessary, to a degree, lol...

2024-04-04 16:27 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +      const port = createPortSpyMock("nonexistentPort");
Ports are a 1:1 connection between two different contextual sources. 

Port names allow for us to differentiate and guard against acting on port connections that we do not want to handle. For instance, we have ports for the `OverlayBackground` that should not trigger logic within `Fido2Background`. 

This test just verifies that we are not acting on port connections that do not have an expected name identifier.

2024-04-04 16:33 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/background/fido2.background.ts
So these ports aren't actually used to transfer data, though they could be if we wanted to architect that instead of using the `chrome.runtime.onMessage` API. However, that would require refactoring a ton of existing logic within the vault popout and other locations.

The ports here are used mainly to act upon changes in their [lifetime](https://developer.chrome.com/docs/extensions/develop/concepts/messaging#port-lifetime). 

When we inject the `content-script.ts`, we connect to the background using a port to indicate that the content script was initialized. The background then stores that port for future reference so that it can act to "destroy" the logic within `content-script.js` if necessary (eg. when a user turns off the passkeys setting, we want to ensure we dismantle that logic). 

This is done through the `port.onDisconnect` listener that exists when connecting a port. This listener exists on both sides, so it also allows us to dismantle logic on the content script side in the case that the extension is unloaded for some reason. This is what allows us to return the WebAuthn API to it's default state in the browser if the extension is removed (without having to reload the tab, that is).

As far as explaining it goes... sure I could make an update to the deep dive, though technically this should already be a part of those docs. This approach to handling dismantling the content-script and page-script logic was implemented before this refactor.

2024-04-04 16:54 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/content/content-script.spec.ts
> +  it("handles a FIDO2 credential creation request message", async () => {
I can expand regarding the purpose of the test, but we do have fully coverage on this file, including edge cases where handling a request triggers an abort response. 

A reworking of the description might be:

`it('handles a FIDO2 credential creation request message from the window message listener, formats the message and sends the formatted message to the extension background')` 

Would that be more effective?

2024-04-04 17:04 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/content/content-script.spec.ts
> +    }
Done, much less verbose doing that... thank you

2024-04-04 17:08 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/content/content-script.ts
> +    const result = await sendExtensionMessage(command, { data, requestId });
So this import is coming from the `autofill/utils` scope, which is a much smaller file compared to the platform utils.

The size impact is less as a result, though it could be even smaller if we had tree shaking working correctly in our webpack build.

That said, this is a better alternative compared to pulling in the `BrowserApi.sendMessage` static method. That approach pulls in a much larger import to the content script.

If it's a large enough concern, I could duplicate the method in this content script to lighten it more... I'm not concerned though, given that the build size for this file is about 20kb...

2024-04-04 17:10 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/content/page-script-append.mv2.spec.ts
> +  it("appends the `page-script.js` file to the document head", () => {
Added some extra context to this test description

2024-04-04 17:13 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/content/page-script.ts
> +  if (browserNativeWebauthnSupport) {
Done

2024-04-04 17:23 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/content/page-script.ts
> +  const messenger = ((window as any).messenger = Messenger.forDOMCommunication(window));
Honestly no idea, I think you're spot on regarding the reason why it likely exists. 

I've removed it, with no apparent side effects.

2024-04-04 17:31 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/content/page-script.webauthn-supported.spec.ts
> +      }
Hm, honestly struggling with testing this file in either regard. 

I've updated the test to remove the try/catch, but expecting the method to throw doesn't seem to be valid here... not sure where I got the idea to do that. 

There is a follow up ticket to re-visit refactoring and testing `page-script.ts` more thoroughly where I will pick this back up. For now, I'm going to push the modifications I've made even if they're not perfect.

2024-04-04 17:31 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/content/page-script.webauthn-supported.spec.ts
> +    it("falls back to the default browser credentials API if an error occurs", async () => {
Done

2024-04-04 17:32 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/content/page-script.webauthn-supported.spec.ts
> +    it("creates and returns a WebAuthn credential", async () => {
Added some extra context

2024-04-04 17:35 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/content/page-script.webauthn-supported.spec.ts
> +    it("should ", async () => {
Brooo.... it just.... should.... ya know? Don't try boxing it into whatever society wants for it, ya know?

Lol, thanks for the callout. I've updated the description of the test assertion.

2024-04-04 17:40 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/content/page-script.webauthn-unsupported.spec.ts
> +    });
We likely should, these tests are not final however. Testing this was a bit of challenge due to how the script needs to be injected along with the presence of static classes that struggle to properly react to re-injections of the script behavior.... I've got a ticket in our backlog to follow up on these at a later point, but for now I'm keeping these tests as a low priority.

I have a strong feeling that setting up the script to be properly tested would require a larger scale refactor... something I"m not willing to do at the moment.

2024-04-04 17:40 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/content/page-script.webauthn-unsupported.spec.ts
> +    it("should ", async () => {
Updated

2024-04-04 17:46 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +// import registerContentScript from "content-scripts-register-polyfill/ponyfill.js";
Done

2024-04-04 17:52 UTC, cagonzalezcs commented on libs/common/src/vault/services/fido2/fido2-utils.ts
> +  static fromB64toUrlB64(b64Str: string) {
We do have tests for some of these methods in the platform utils. I've pulled those into a new spec file for `fido2-utils.ts`.

2024-04-05 07:32 UTC, coroiu commented on apps/browser/src/vault/fido2/content/page-script.webauthn-supported.spec.ts
> +    it("should ", async () => {
Haha looks like you had fun reading the comments at least 😁

2024-04-08 07:35 UTC, coroiu commented on apps/browser/src/background/runtime.background.ts
> -      return false;
Hmm ok, I didn't really work with fixing that bug so I wasn't 100% sure what caused it. What I do remember is having to introduce a system for selectively returning `true` when we actually wanted to return an answer, and then having an issue with the browser interpreting `async handler(): Promise<void>` as a truthy value. Either way this function should return `undefined` if we remove `return false` so it probably won't cause an issue either way

2024-04-08 07:42 UTC, coroiu commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +    it("skips injecting the FIDO2 content scripts into tabs that do not have a secure url protocol", async () => {
Hmm, I think I'm missing something here. Both this test, and the next define an insecure tab 

```
const insecureTab = mock<chrome.tabs.Tab>({ id: 789, url: "http://example.com" });
```

and according to the test name, they both seem to check that the script is not injected into this tab. Looking at the test code, they both also seem to the test the same thing, but this test seems to be using the spy directly

```
expect(executeTabsSpy).not.toHaveBeenCalled();
```

while the other refers to the spy via `BrowserApi`

```
      expect(BrowserApi.executeScriptInTab).not.toHaveBeenCalledWith(
        insecureTab.id,
        contentScriptDetails,
      );
```

2024-04-08 07:45 UTC, coroiu commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +    it("skips injecting the FIDO2 content scripts into tabs that do not have a secure url protocol", async () => {
Ok I think I get it now, the first test checks that **no scripts whatsoever are executed in any tabs** while the following script explicitly checks for the insecure tab-id. Can we update the test name? Sorry for being so nitpicky with this 🙏 

```
does not inject any content scripts when no tabs have a secure url protocol
```

2024-04-08 07:55 UTC, coroiu commented on apps/browser/src/vault/fido2/background/fido2.background.ts
> +    if (typeof previousEnablePasskeysSetting === "undefined") {
Of course! `undefined` only works when you trying to access it on some object `existingObject.nonExistingProperty`, but you can't refer to undefined variables directly!

But in this case, that variable is explicitly defined just a few rows above

```
    const previousEnablePasskeysSetting = this.currentEnablePasskeysSetting;
```

I think this is a really clever approach, if maybe too clever 😄 I think we should switch to `=== undefined` (or possible the more common `== null`) mostly because of consistency. Otherwise I think this is only going to cause confusion when people read this in the future and might try to find out why this specific row of code looks different from all the other

2024-04-08 13:52 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +    it("skips injecting the FIDO2 content scripts into tabs that do not have a secure url protocol", async () => {
Sure no problem, I've adjusted the name as suggested.

2024-04-08 14:01 UTC, coroiu commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +    it("skips destroying and re-injecting the content scripts if the enablePasskeys setting is first being read", async () => {
> The problem with that is that we need to trigger injection of these scripts on install for all existing tabs, but only when the extension is first installed.

I think I understand what you mean here, in my words: When you first install the extension, passkeys might already be enabled, depending on how the default values look. And if they are enabled, then as soon as we subscribe our first value is going to be `true` and we will incorrectly assume that everything has already been injected. Our logic instead needs to check for what the previous value was and make decisions on how to act on that, i.e.

- `undefined` -> `true`: Extension is starting up.
- `false` -> `true`: The user has previously deactivated passkey support and is now activating it again,

I have two feedback points on this:

1. Any extension reload would trigger this right? And because we are not checking for the actual presence of the page-script on the page, we will always re-inject on extension reload. In some scenarios this is actually better, and is fixing a bug where any updates to the `page-script` would break any existing tabs which would not get their script updated. On the other hand, logout also reloads the extension, but that's fine. How about account switching?

2. I think we can improve the code a bit and get rid of the class-variable (class-property? I can never remember). I'll post it as a comment in `fido2.background.ts`

2024-04-08 14:05 UTC, coroiu commented on apps/browser/src/vault/fido2/background/fido2.background.ts
> +    this.vaultSettingsService.enablePasskeys$.subscribe(this.handleEnablePasskeysUpdate.bind(this));
🎨 suggestion: We might be able to remove `currentEnablePasskeySetting` by using `pairwise`

```suggestion
    this.vaultSettingsService.enablePasskeys$.pipe(
        startWith(undefined),
        pairwise()
    ).subscribe((previous, current) => this.handleEnablePasskeysUpdate(previous, new));
```

where `previous` would take the role of `currentEnablePasskeysSetting`

2024-04-08 14:06 UTC, coroiu commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +    it("unregisters the FIDO2 page-script.js and content-script.js content scripts for manifest v3 if the enablePasskeys setting is turned off", async () => {
It was just that none of the other tests mentioned `FIDO2` but from what I could see they were all testing `FIDO2` related scripts. We could've also added `FIDO2` to all other names :)

2024-04-08 14:09 UTC, coroiu commented on apps/browser/src/vault/fido2/content/content-script.spec.ts
> +  it("handles a FIDO2 credential creation request message", async () => {
Absolutely!

2024-04-09 08:43 UTC, coroiu reviewed
Just a few nitpicks and follow up comments to the previous conversations ☝️ , then we're good to go from my perspective!

2024-04-09 08:43 UTC, coroiu commented on apps/browser/src/vault/fido2/background/fido2.background.ts
We had a quick call about this and talked about how we have one port per tab, and that ports are not transmitted over broadcast calls, but are instead created directly using `chrome.runtime.onConnect`

2024-04-09 08:43 UTC, coroiu commented on libs/common/src/vault/services/fido2/fido2-utils.spec.ts
> +    it("should return an empty string for an empty ArrayBuffer", () => {
⛏️ nitpick:

```suggestion
    it("should return an empty string when given an empty ArrayBuffer", () => {
```

2024-04-09 08:43 UTC, coroiu commented on libs/common/src/vault/services/fido2/fido2-utils.spec.ts
> +    it("should return null for null input", () => {
⛏️ nitpick:
```suggestion
    it("should return null when given null input", () => {
```

2024-04-09 08:43 UTC, coroiu commented on libs/common/src/vault/services/fido2/fido2-utils.spec.ts
> +    it("should return null for null input", () => {
⛏️ nitpick:
```suggestion
    it("should return null when given null input", () => {
```

2024-04-09 22:26 UTC, cagonzalezcs commented on libs/common/src/vault/services/fido2/fido2-utils.spec.ts
> +    it("should return an empty string for an empty ArrayBuffer", () => {
Updated

2024-04-09 22:26 UTC, cagonzalezcs commented on libs/common/src/vault/services/fido2/fido2-utils.spec.ts
> +    it("should return null for null input", () => {
Updated

2024-04-09 22:26 UTC, cagonzalezcs commented on libs/common/src/vault/services/fido2/fido2-utils.spec.ts
> +    it("should return null for null input", () => {
Updated

2024-04-10 07:06 UTC, coroiu commented on apps/browser/src/vault/fido2/background/fido2.background.ts
> +    this.vaultSettingsService.enablePasskeys$.subscribe(this.handleEnablePasskeysUpdate.bind(this));
Glad I could help! 😁

2024-04-10 07:41 UTC, coroiu approved these changes

2024-04-10 07:41 UTC, coroiu commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +    firstValueFrom: jest.fn(firstValueFrom),
💭 thought: I understand that these are "white-box" unit tests, but even so, this seems brittle to me. One of the advantages of unit tests are that they empower developers to change code and have the unit tests guarantee that the behavior they didn't intend to change remains the same. Having tests depend on function calls like this makes it hard to make any type of refactor to the code without breaking the tests, losing some of the advantages of the test. I also think that, in general, it's better to focus tests on behavior and not on implementation detail, because most often we don't care how it is implemented, just as long as it behaves as expect from an external observer.

No action required here from me, I just wanted to share my thoughts

2024-04-10 13:38 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +    firstValueFrom: jest.fn(firstValueFrom),
So I definitely don't mind going back and reworking this. That said, how can I get `firstValueFrom` to function within the test without mocking it? I've always ran into trouble with getting observables to emit within jest tests, which definitely shows how unfamiliar `rxjs` is for me.

2024-04-10 13:47 UTC, coroiu commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +    firstValueFrom: jest.fn(firstValueFrom),
Couldn't we just let `firstValueFrom` do it's thing and instead mock `vaultSettingsService.enablePasskeys$`, then check 

```ts
  describe("isPasskeySettingEnabled", () => {
    it("returns the firstValueFrom the `enablePasskeys$` observable", () => {
      const result = void fido2Background["isPasskeySettingEnabled"]();

      expect(result).toBe(vaultSettingsService.enablePasskeys$.value);
    });
  });
```

2024-04-10 14:23 UTC, coroiu commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +    firstValueFrom: jest.fn(firstValueFrom),
Yeah that's definitely a good way of mocking it! You could also move the definition of the `BehaviorSubject` and store it in a variable so that you have access to the original type, that way you can control what `BehaviorSubject` returns

2024-04-11 15:28 UTC, audrey-jensen submitted a review, later dismissed
Most of my feedback centers the discoverability of platform code. I'd like to see the concern addressed.

👍🏻 kudos!
🤔 concern, but not a blocking one
🎨 suggestion
❓ curiosity
⛏️ nitpick
♻️ tech debt

2024-04-11 15:28 UTC, audrey-jensen commented on apps/browser/src/tools/background/fileless-importer.background.ts
> +        await ScriptInjectorService.inject({
🤔 Seems like this service should be an injected dependency, not statically called. The static call makes it difficult to mock. You'll need to rely on spies, which are more brittle.

2024-04-11 15:28 UTC, audrey-jensen commented on apps/browser/src/tools/background/fileless-importer.background.ts
> +          mv3Details: FilelessImporterInjectedScriptsConfig.LpSuppressImportDownload.mv3,
👍🏻 I like the increased specificity here. It's more clear what data is being moved around.

2024-04-11 15:28 UTC, audrey-jensen commented on apps/browser/src/tools/config/fileless-importer-injected-scripts.ts
> +    mv3: ScriptInjectionConfig["mv3Details"];
🎨 This seems like it would be more clear if `mv2Details` and `mv3Details` had their own types instead of being structurally bound. This is especially true given that `ScriptInjectionConfig` is not a type parameter. It's a statically defined class itself.

2024-04-11 15:28 UTC, audrey-jensen commented on apps/browser/src/platform/services/abstractions/script-injector.service.ts
> +  };
⛏️ Since this type is exported, it should be documented. It is not clear what the formats are for any of the file paths, what can be expected when an optional parameter is not specified, or what data is being stored in the member.

2024-04-11 15:28 UTC, audrey-jensen commented on apps/browser/src/platform/browser/browser-api.ts
> +   */
👍🏻 Yay! Documentation!

2024-04-11 15:28 UTC, audrey-jensen commented on apps/browser/src/platform/services/script-injector.service.spec.ts
> +  jest.spyOn(ScriptInjectorService, "inject");
⛏️ Seems like this spy isn't necessary. `inject` is your system under test.

2024-04-11 15:28 UTC, audrey-jensen commented on apps/browser/src/platform/services/script-injector.service.ts
> +        { world: mv3Details?.world || "ISOLATED" },
❓ Do you mean to look for falsy values, or would the nullish coalescing operator (`??`) be more appropriate?

⛏️ If you do want to look for falsy values (e.g. `""`), then you should add tests for them.

♻️ I wonder what happens if neither file is specified? It might be nice to have a fallback file that simply logs that script injection occurred w/o a file specified. If that should never occur, then a [discriminated union](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#discriminated-unions) may more closely model the semantics you're looking for.

2024-04-11 16:19 UTC, cagonzalezcs commented on apps/browser/src/tools/background/fileless-importer.background.ts
> +        await ScriptInjectorService.inject({
Good call, I approached it as a static method at first because of the BrowserApi's general approach. That said, I think you're right on this and I've reworked the implementation to act as a distinct dependency.

2024-04-11 16:19 UTC, cagonzalezcs commented on apps/browser/src/tools/config/fileless-importer-injected-scripts.ts
> +    mv3: ScriptInjectionConfig["mv3Details"];
Sounds good, I've created a set of typings to describe this more effectively.

2024-04-11 16:21 UTC, cagonzalezcs commented on apps/browser/src/platform/services/abstractions/script-injector.service.ts
> +  };
Hmm... your comment is making me rethink this a bit.... 

I'll get back to this with a better approach. Document it more explicitly should be a problem, but I do feel the typing is a bit ambiguous.

2024-04-11 16:23 UTC, cagonzalezcs commented on apps/browser/src/platform/services/script-injector.service.spec.ts
> +  jest.spyOn(ScriptInjectorService, "inject");
Ah, good call. I think I added it without thinking.

It has been removed.

2024-04-11 16:26 UTC, audrey-jensen submitted a review, later dismissed
Nits. None blocking.

2024-04-11 16:26 UTC, audrey-jensen commented on apps/browser/src/platform/services/abstractions/script-injector.service.ts
> +export type mv3ScriptInjectionDetails = combinedManifestVersionInjectionDetails & {
⛏️ The casing on these is incorrect. (It should use PascalCase.)

2024-04-11 16:26 UTC, audrey-jensen commented on apps/browser/src/platform/services/script-injector.service.ts
> +export class ScriptInjectorService implements ScriptInjectorServiceInterface {
⛏️ Assuming this is integrated with angular, it should follow the [revised naming convention](https://contributing.bitwarden.com/architecture/clients/presentation/angular#abstract--default-implementations).

2024-04-11 16:56 UTC, audrey-jensen commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +    firstValueFrom: jest.fn(firstValueFrom),
One of the things that you have to be careful with when it comes to open box testing is that you end up with over-fitted tests. When you have nondeterministic behavior, that's when doing things like spying on an internal function are valuable. Since most code should be deterministic--a given input always produces a given output--you should be able to rely on that determinism.

For this reason, there are vanishingly few cases where I've found it useful to perform open box testing. Every time I've run into nondeterminism, I've been able to factor it into a different component that makes the output of the SUT deterministic.

This even applies to some fairly complex state provider behaviors. These aren't ready for consumption outside the tools team, but the testing setup may be fairly instructive:
* [RolloverState tests](https://github.com/bitwarden/clients/blob/94abf0464d91bba6b1e8971a506f215489be62a1/libs/common/src/tools/generator/state/rollover-state.spec.ts)
* [SecretState tests](https://github.com/bitwarden/clients/blob/94abf0464d91bba6b1e8971a506f215489be62a1/libs/common/src/tools/generator/state/secret-state.spec.ts)

Both of the above test suites achieve 100% code coverage while only testing the documented behaviors of the SUT. That wasn't the case when I started writing them, however. The way it happened is, roughly:

1. I wrote JsDoc strings.
2. I wrote tests to cover my docs. 
3. I looked at code coverage to see what behaviors I missed and documented them.
4. I wrote more tests.

And in between had a few discussions that pointed out other desirable behaviors, and more or less followed the same loop to make those work.

The examples I wrote above are not perfect by any measure--the tests could probably be more concise, for example--but they are largely self-contained, clear, and helped me identify inconsistencies in the consumer experience.

2024-04-11 21:45 UTC, cagonzalezcs commented on apps/browser/src/platform/services/script-injector.service.ts
> +        { world: mv3Details?.world || "ISOLATED" },
Thank you for the suggestion, yes I think leveraging the nullsih coalescing operator is more appropriate when it comes to the file.

I've also added a guard against attempting to use the script injector service without passing a valid file name. Doing this with the base extension api would throw an error as well, so I decided to do the same with the intent of informing the developer that a file is required to use the ScriptInjector.

2024-04-11 21:46 UTC, cagonzalezcs commented on apps/browser/src/platform/services/abstractions/script-injector.service.ts
> +  };
I documented and reworked the data structure a bit. Essentially, it felt weird to have a separate `combinedManifestVersionDetails` key. I pulled the `file` key into the main `injectDetails` object and added documentation around usage of that value.

Please let me know if this is still unclear.

2024-04-11 21:46 UTC, cagonzalezcs commented on apps/browser/src/platform/services/abstractions/script-injector.service.ts
> +export type mv3ScriptInjectionDetails = combinedManifestVersionInjectionDetails & {
This has been corrected

2024-04-11 21:46 UTC, cagonzalezcs commented on apps/browser/src/platform/services/abstractions/script-injector.service.ts
> +}
Ah thank you for that, I've updated the implementation to use an abstract class as suggested.

2024-04-11 21:47 UTC, cagonzalezcs commented on apps/browser/src/platform/services/script-injector.service.ts
> +export class ScriptInjectorService implements ScriptInjectorServiceInterface {
The naming of the `ScriptInjectorService` has been reworked to `BrowserScriptInjectorService` with the abstract class maintaining the `ScriptInjectorService` name.

Please let me know if this should change.

2024-04-12 11:53 UTC, coroiu reviewed
The new injection service looks great! The new `fido2.background` tests also look nice without private function access. Added some additional comments on how we can improve the tests even more now that we have this abstraction!

2024-04-12 11:53 UTC, coroiu commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +  describe("handleInjectScriptPortOnDisconnect", () => {
⚠️ suggestion: I think we should remove these tests. They test internal implementation (the use of a set containing ports) that is only needed for behavior that is already tested in other places.

2024-04-12 11:53 UTC, coroiu commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +    it("removes the port from the fido2ContentScriptPortsSet", () => {
⚠️ suggestion: replace this with 
```
      it("does not destroy or inject the content script when the port has already disconnected before the enablePasskeys setting is set to `false`", async () => {
        triggerPortOnDisconnectEvent(portMock);
        enablePasskeysMock$.next(false);
        await flushPromises();

        expect(portMock.disconnect).not.toHaveBeenCalled();
        expect(executeTabsSpy).not.toHaveBeenCalled();
      });
```

inside `describe("handleEnablePasskeysUpdate", ...`. This test will instead test the main reason for which we are keeping track of the ports, without relying on internal implemenation logic

2024-04-12 11:53 UTC, coroiu commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +  describe("injectFido2ContentScriptsInAllTabs", () => {
:art: suggestion(non-blocking): these tests could technically be tested without `fido2Background.init()` having been run. Mostly an observation, you don't need to reorganize your tests

2024-04-12 13:29 UTC, audrey-jensen commented on apps/browser/src/platform/services/abstractions/script-injector.service.ts
> +  };
⛏️ JSDoc format lets these values be seen by the editor.

🎨 Since the parameters are all `?`, I've removed "optional" from your descriptions. Also included @coroiu's grammar change and a link to the MDN docs explaining the `runAt` parameter.

```suggestion
    /** Script injected into the document. 
     *  Overridden by `mv2Details` and `mv3Details`. 
     */
    file?: string;
    /** When `true`, the script injects into every frame in the tab. Defaults to `false`. */
    allFrames?: boolean;
    /** Identifies the frame targeted for script injection. Defaults to the top level frame (0). */
    frameId?: number; 
    /** When the script executes. Defaults to "document_start".
     * @see https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts 
     */
    runAt?: "document_start" | "document_end" | "document_idle";
  };
```

2024-04-12 13:29 UTC, audrey-jensen commented on apps/browser/src/platform/services/abstractions/script-injector.service.ts
> +  };
It's clear. I offered some suggested code, but none of it is strictly necessary.

2024-04-12 13:42 UTC, audrey-jensen commented on apps/browser/src/platform/services/browser-script-injector.service.ts
> +    if (!file) {
That actually makes the code incorrect. `!""` is false, and the guard checks that. It also guards against someone passing `file: null`.

2024-04-12 13:42 UTC, audrey-jensen commented on apps/browser/src/platform/services/browser-script-injector.service.spec.ts
All of @coroiu's testing suggestions are worthwhile. I'd also check for edge cases like passing in `""` or `null` in files.

2024-04-12 13:42 UTC, audrey-jensen commented on apps/browser/src/platform/services/abstractions/script-injector.service.ts
> +    frameId?: number; // Optional, defaults to 0, which is the id of the top level frame in a tab
🫏 I like that `frameId`. That's a _nice_ `frameId`.

2024-04-12 13:42 UTC, audrey-jensen commented on apps/browser/src/platform/services/abstractions/script-injector.service.ts
> +export abstract class ScriptInjectorService {
📝 This codecov annotation is a bit silly, but it's easy to eliminate. Simply use `extends` instead of `implements` in the derived type, and add a `super()` to the constructor.

2024-04-12 13:42 UTC, audrey-jensen commented on apps/browser/src/platform/services/script-injector.service.ts
> +        { world: mv3Details?.world || "ISOLATED" },
There's a bunch more discussion on this that I've added some thoughts to. This comment is resolved, either way. :)

2024-04-12 13:50 UTC, coroiu commented on apps/browser/src/platform/services/browser-script-injector.service.ts
> +    if (!file) {
Urgh, the fact that we're not using ts-strict gets me every time (completely missed the `""` case though) 🙃 I always think that being explicit in these cases is better because the next person might make the same mistake I did and not consider those. But I marked this as `non-blocking` so feel free to ignore! 

Otherwise my suggestion would be:

```suggestion
    if (Utils.isNullOrEmpty(file)) {
```

2024-04-12 14:02 UTC, audrey-jensen submitted a review, later dismissed
I'm still all good with this. All of my comments here are just because I enjoy collaborating on a design. Nothing blocking.

🫏 Shrek reference
🎨 suggestion
⛏️ nitpick
📝 note

2024-04-12 14:14 UTC, audrey-jensen commented on apps/browser/src/platform/services/browser-script-injector.service.ts
> +    if (!file) {
> I always think that being explicit in these cases is better 

This is kind of funny to me. I think of `!foo` and `!!foo` as being an explicit truthy or falsy operation. They tell me "Yes, I know what I'm doing here". Then again, I've been working with raw JS so long that my brain has probably started rotting.

2024-04-15 14:58 UTC, cagonzalezcs commented on apps/browser/src/platform/services/abstractions/script-injector.service.ts
> +    allFrames?: boolean; // Optional, defaults to false. If set to true, the script will injection into all frames in the tab
Corrected

2024-04-15 15:06 UTC, cagonzalezcs commented on apps/browser/src/platform/services/abstractions/script-injector.service.ts
> +    frameId?: number; // Optional, defaults to 0, which is the id of the top level frame in a tab
Hmm, I was considering objecting to your suggestion due to how the `InjectionTarget` [options data structure is implemented within the spec.](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting/InjectionTarget#allframes) That's why I went with these as exclusive options. 

However, by the spec's own admission the `all_frames` option will throw an error if a frameId (or frameIds, in the case of the mv3 API) is included alongside a `all_frames` value of `true`.

That said, I'm not sure I like that the `frameId` can accept a string value. I feel like a different name might fit better there... maybe something like `frameContext`? 

```
frameContext: 'all_frames" | number
```

2024-04-15 15:07 UTC, coroiu commented on apps/browser/src/platform/services/abstractions/script-injector.service.ts
> +    frameId?: number; // Optional, defaults to 0, which is the id of the top level frame in a tab
Yeah, either that or just make TS-typing throw an error if you try to set both! Then it'll be much clearar to the developer using this as well :)

2024-04-15 15:15 UTC, audrey-jensen commented on apps/browser/src/platform/services/abstractions/script-injector.service.ts
> +    frameId?: number; // Optional, defaults to 0, which is the id of the top level frame in a tab
🎨 Or just `frame`.

📝 The spec break things down into individual typed values because it requires compatibility with a wide variety of language bindings and user agents. Typescript's type system is more expressive than, say, transpiled C, so where you can you should use it. It's way better for incorrect code to be caught by the compiler than a runtime error.

2024-04-15 15:35 UTC, cagonzalezcs commented on apps/browser/src/platform/services/abstractions/script-injector.service.ts
> +  injectDetails: {
Done

2024-04-15 15:36 UTC, cagonzalezcs commented on apps/browser/src/platform/services/browser-script-injector.service.spec.ts
> +  const mv2Details = { file: mv2SpecificFile };
Done

2024-04-15 15:37 UTC, cagonzalezcs commented on apps/browser/src/platform/services/browser-script-injector.service.spec.ts
> +    describe("injection of single scripts that function in both manifest v2 and v3", () => {
Reworked to fit closer to your suggestin

2024-04-15 15:38 UTC, cagonzalezcs commented on apps/browser/src/platform/services/browser-script-injector.service.spec.ts
> +      it("injects the script in manifest v2", async () => {
Done, and added this to the mv3 description as well

2024-04-15 15:38 UTC, cagonzalezcs commented on apps/browser/src/platform/services/browser-script-injector.service.spec.ts
> +      it("injects the script in manifest v3", async () => {
Done

2024-04-15 15:39 UTC, cagonzalezcs commented on apps/browser/src/platform/services/browser-script-injector.service.spec.ts
> +    it("injects a script that is meant to function within manifest v32 only", async () => {
Done

2024-04-15 16:01 UTC, cagonzalezcs commented on apps/browser/src/platform/services/browser-script-injector.service.spec.ts
Sounds good, I've added a set of tests that validate the edge case concerns listed above.

2024-04-15 16:03 UTC, cagonzalezcs commented on apps/browser/src/platform/services/browser-script-injector.service.ts
> +    if (!file) {
In essence I'm testing here that `file` is a populated string value. If any falsy value such as `'', null, undefined` is encountered, we treat this as an error condition.

I'd like to keep this as structured for now.

2024-04-15 16:26 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +    scriptInjectorService = new BrowserScriptInjectorService();
Done, this required some rework of the tests, but also helped to remove a couple of "manifest-specific" tests that don't really belong in this suite.

2024-04-15 16:26 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +    registeredContentScripsMock = mock<browser.contentScripts.RegisteredContentScript>();
Done

2024-04-15 16:26 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +        });
Yes, as mentioned in a previous comment these have been remove/reworked.

2024-04-15 16:27 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +    describe("given manifest v2", () => {
Done

2024-04-15 16:27 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +  describe("handleInjectScriptPortOnDisconnect", () => {
We lose line coverage if we remove these... is that desired?

2024-04-15 16:34 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +  describe("handleInjectScriptPortOnDisconnect", () => {
So based on your feedback on your next comment, this is still in place. However, I've removed the early exit case test, as your feedback suggests it isn't necessary to test that internal implementation concern.

2024-04-15 16:34 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +    it("removes the port from the fido2ContentScriptPortsSet", () => {
Done, this test has been applied.

2024-04-15 16:37 UTC, cagonzalezcs commented on apps/browser/src/vault/fido2/background/fido2.background.spec.ts
> +  describe("injectFido2ContentScriptsInAllTabs", () => {
Hm, I've scoped down that init call to the test cases that require it.

2024-04-15 16:42 UTC, cagonzalezcs commented on apps/browser/src/platform/services/abstractions/script-injector.service.ts
> +  };
Sounds good, I've applied these and updated the `world` mv3 reference to have a link to documentation in the same manner as your `run_at` suggestion.

2024-04-15 16:50 UTC, cagonzalezcs commented on apps/browser/src/platform/services/abstractions/script-injector.service.ts
> +export abstract class ScriptInjectorService {
Hmmm... this does require me to update the method reference within the abstract `ScriptInjectorService` to be an actual function definition (with an empty block)...

```
export abstract class ScriptInjectorService {
  async inject(config: ScriptInjectionConfig): Promise<void> {}
}
```

Is that preferable? I feel like it's less clean, but I doubt it really has a significant impact one way or another.

2024-04-15 16:54 UTC, cagonzalezcs commented on apps/browser/src/platform/services/abstractions/script-injector.service.ts
> +  mv3Details?: Mv3ScriptInjectionDetails;
Hmm... this isn't exactly how I approached it, but I had to implement a datastructure conversion similar to this due to @coroiu 's suggestion for how `frameId` (or rather `frameContext`, as I've decided to name the prop) is translated to either the `frameId` with a number or `allFrames` with a boolean when actually calling the browser's script injection API.

2024-04-15 16:55 UTC, audrey-jensen commented on apps/browser/src/platform/services/abstractions/script-injector.service.ts
> +export abstract class ScriptInjectorService {
Either that or use the bound function format on your class definition. I completely forgot about that part.

```typescript
class BrowserScriptInjectorService extends ScriptInjectorService {
  inject = async (config: ScriptInjectionConfig) => {
    // implementation
  }
}

2024-04-15 21:04 UTC, cagonzalezcs commented on apps/browser/src/platform/services/abstractions/script-injector.service.ts
> +export abstract class ScriptInjectorService {
Ah I see, definitely need to learn more about how abstract classes work and are structured in JS.

I've gone head with your first recommendation.

2024-04-15 21:17 UTC, cagonzalezcs commented on apps/browser/src/platform/services/abstractions/script-injector.service.ts
> +    frameId?: number; // Optional, defaults to 0, which is the id of the top level frame in a tab
I'm in agreement with the change from `frameContext` to just `frame`. 

I implemented your suggested opaque type... but as you mentioned it ended up feeling noisy to a degree. I was finding myself in a position where I was needing to cast any passed values explicitly... and that felt kind of verbose. 

Is there something I'm missing in how to approaching using that?

2024-04-15 21:28 UTC, audrey-jensen submitted a review, later dismissed

2024-04-15 21:32 UTC, audrey-jensen commented on apps/browser/src/platform/services/abstractions/script-injector.service.ts
> +    frameId?: number; // Optional, defaults to 0, which is the id of the top level frame in a tab
When using opaque types you need to perform the cast, there's no avoiding it. What it buys you is the ability for one interface to emit the opaque value and another to receive it. So, for example, say you had a service that scans a page and gets certain kinds of frames:

type IntegrationFrames = {
   importable: FrameId;
   autofillable: FrameId;
   replaceable: FrameId;
};

Then you could ensure that the frame targets above couldn't be confused with other numbers, such as (say) the number of failed login attempts counter.

2024-04-16 06:45 UTC, coroiu commented on apps/browser/src/platform/services/abstractions/script-injector.service.ts
> +    frameId?: number; // Optional, defaults to 0, which is the id of the top level frame in a tab
From my side this comment was only a question, so I'm good with whatever you both come up with here!

2024-04-16 14:21 UTC, cagonzalezcs commented on apps/browser/src/platform/services/abstractions/script-injector.service.ts
> +    frameId?: number; // Optional, defaults to 0, which is the id of the top level frame in a tab
Hm, given the scope of changes required for the Opaque typing, I'd like to hold off on that suggestion for now.

If we were going to incorporate that kind of element, I'd like to see it incorporated in all expected calls where these elements would be passed. That would expand the scope of this PR even more, which I'd like to avoid.

2024-04-16 19:45 UTC, jprusik approved these changes
Autofill concerns and adjacent LGTM

2024-04-16 20:48 UTC, Jingo88 submitted a review, later dismissed

2024-04-17 07:15 UTC, coroiu submitted a review, later dismissed
🔥

2024-04-17 14:54 UTC, audrey-jensen approved these changes

2024-04-17 14:54 UTC, Jingo88 approved these changes

2024-04-17 15:04 UTC, jprusik approved these changes

2024-04-18 06:15 UTC, coroiu approved these changes

2024-04-18 16:05 UTC, merged

2024-05-14 15:24 UTC, milklineep commented on apps/browser/src/manifest.json
> +    "webNavigation"
Hello! I'm pretty sure this is not the right way to go about this, and I'm sorry. But I just want to let you know that updating the extension to the latest version on Firefox did prompt me to approve a new permission ("Access browser activity during navigation"), which led me on the hunt for any explanation as to why. Thankfully I found this PR and got my curiosity satisfied. Thank you for your commitment to open source!

2024-09-14 14:25 UTC, CC007 commented on apps/browser/src/manifest.json
> +    "webNavigation"
I found this PR in a similar way. I actually postponed updating the plugin until now, because I thought "the plugin works right now without the permission, so I don't feel like updating until I have the time to verify that this permission isn't maliciously used". That verification was now. This seems legit, I think? Not fully sure, because I'm not a browser plugin dev myself.