[PM-5562] Implement Domain Settings state provider
bitwarden/clients pull request #8226
Opened 2024-03-06 17:33 UTC by jprusik

## Type of change

- Tech debt (refactoring, code cleanup, dependency upgrades, etc)

## Objective

- Implement Domain Settings state provider
- migrate `neverDomains` global settings and `equivalentDomains` and `defaultUriMatch` to the domain settings state provider

## Code changes

- Created Domain Settings state service
- Replaced instances of state now handled by the Domain Settings service with their appropriate counterparts
  - In some cases, this allowed the complete removal of the settings service
- Created migration script to upgrade or rollback state storage changes
- Removed account `settings.settings` (from old state storage) since `equivalentDomains` was the last setting being stored there
- replaced the URI match strategy enum with separate constants/types

2024-03-06 17:50 UTC, jprusik commented on libs/common/src/services/settings.service.ts
> -  }
This only clears account `settings.settings` which only has `equivalentDomains` in it now, so it can go away :-D

2024-03-06 17:52 UTC, jprusik commented on libs/common/src/vault/enums/uri-match-type.enum.ts
transplanted to `libs/common/src/models/domain/domain-service.ts`

2024-03-07 16:21 UTC, djsmith85 submitted a review, later dismissed
Approving for tools

2024-03-07 16:27 UTC, audrey-jensen submitted a review, later dismissed
🌱 Possible future improvement
🎨 Suggestion
👍🏻 Kudos!
🤔 Thoughts that might benefit from discussion

2024-03-07 16:27 UTC, audrey-jensen commented on libs/common/src/autofill/services/domain-settings.service.ts
> +  async getUrlEquivalentDomains(url: string): Promise<Set<string>> {
🌱 Seems like this implementation could be reduced if the equivalent domains were to build out a mapping between all domains which was then cached using a derived state provider. Rather than scan the whole list, you'd index into the map.

```typescript
const domain = Utils.getDomain(url);
const domains = this.equivalentDomainsMapping$.pipe(
   map((equivalents) => equivalents.get(domain) ?? new Set();
);

// let the caller decide whether to `firstValueFrom` or stay reactive
return domains;
```

Rough derive implementation for `equivalentDomainsMapping$`:

```typescript
const domains = equivalentDomains.flatMap(
  (eds) => eds.map((ed) => [ed, eds])
);

const domainMap = new Map(domains);

return domainMap;
```

Then again, this may play havoc with serialization.

2024-03-07 16:27 UTC, audrey-jensen commented on libs/common/src/models/domain/domain-service.ts
> +export type UriMatchStrategySetting = (typeof UriMatchStrategy)[keyof typeof UriMatchStrategy];
👍🏻 Love to see the deconstructed enums instead of the compiled ones.

2024-03-07 16:27 UTC, audrey-jensen commented on libs/common/src/models/domain/domain-service.ts
🤔 Could the types used by other modules be documented? It'd be nice to know what the different strategies do, especially the difference between "domain" and "host". It also seems like "Never" is ambiguous--I'd expect it to never match any domain? But then it'd also never match itself, which also seems wrong. At the end of the day, what matters to me is that this is difficult to pick up from context.

2024-03-07 17:02 UTC, cagonzalezcs approved these changes
Awesome work on this! The implementation looks solid, everything I've reviewed looks to be structured cleanly and effectively. 

I also pulled this work down and tested various settings, everything seems to work as expected from my side.

2024-03-07 20:40 UTC, gbubemismith submitted a review, later dismissed

2024-03-07 20:52 UTC, justindbaur requested changes
Thank you so much for this, this is a big improvement.

2024-03-07 20:52 UTC, justindbaur commented on libs/common/src/autofill/services/domain-settings.service.ts
> +  async getUrlEquivalentDomains(url: string): Promise<Set<string>> {
Yeah I want to encourage keeping the output of this an observable. Even the most basic transformation of it to do the exact same logic it holds now but in a `.pipe(map(...))` off of `this.equivalentDomains$`. 

My goal is always to pass any sort of subscription further down the line.

2024-03-07 20:52 UTC, justindbaur commented on libs/common/src/autofill/services/domain-settings.service.ts
> +      this.setNeverDomains(null),
First of all, I don't think you want to clear never domains or default uri match strategy, as far as I saw the only thing previously being cleared was the equivalent domains on logout. As far as I can see in this PR the only place this `clear` method was added was for browsers logout, but luckily for you I come offering some gifts.

We are working on the docs for it but the feature is already able to be used. You can convert `EQUIVALENT_DOMAINS` from being a `KeyDefinition` into a `UserKeyDefinition`, when you do that you'll have an error that you are missing a required property `clearOn`. If you add that property and give it the value `["logout"]` you should actually be able to delete this `clear` method entirely because you never need to call it. The state provider framework will instead delete the equivalent domains for you when the user logs out.

2024-03-07 20:52 UTC, justindbaur commented on libs/common/src/state-migrations/migrations/30-move-domain-settings-to-state-providers.spec.ts
> +          equivalentDomains: ["apple.com", "icloud.com"],
Shouldn't this be?
```suggestion
          equivalentDomains: [["apple.com", "icloud.com"]],
```

2024-03-07 20:52 UTC, justindbaur commented on libs/common/src/state-migrations/migrations/30-move-domain-settings-to-state-providers.ts
> +          key: "neverDomains",
For one, this isn't using the stashed `domainSettingsStateDefinition` but also since each of these key definitions are used twice both in migrate and in rollback I would recommend just stashing these in the own `const`'s too and referencing those instead.

2024-03-07 20:52 UTC, justindbaur commented on libs/common/src/state-migrations/migrations/30-move-domain-settings-to-state-providers.ts
> +      await helper.set<ExpectedGlobalState>("global", globalState);
You can move both these calls into the `if` block so that we only bother deleting and updating global if anything actually needed to be moved off of it.

2024-03-07 20:52 UTC, justindbaur commented on libs/common/src/state-migrations/migrations/30-move-domain-settings-to-state-providers.ts
> +      }
For these I would create a `let updatedAccount = false` and then instead of calling `await helper.set(userId, account)` possibly multiple times you can do `updatedAccount = true` and have a check for that after all possible updates like such:
```typescript
if (updatedAccount) {
  await helper.set(userId, account);
}
```

2024-03-07 20:52 UTC, justindbaur commented on libs/common/src/models/domain/domain-service.ts
> +export type UriMatchStrategySetting = (typeof UriMatchStrategy)[keyof typeof UriMatchStrategy];
Can't agree more, I love these.

2024-03-07 20:52 UTC, justindbaur commented on libs/common/src/autofill/services/domain-settings.service.ts
> +export class DomainSettingsService implements DomainSettingsServiceAbstraction {
In preparation for the update to [ADR 12](https://github.com/bitwarden/contributing-docs/pull/310) I would remove the `Abstraction` suffix from the first type and add the prefix `Default` to the implementation. Now you'll have a shorter name when it is used most often and only the longer name in the fewer places where you have to set it in DI.

2024-03-07 21:11 UTC, audrey-jensen commented on libs/common/src/autofill/services/domain-settings.service.ts
> +  async getUrlEquivalentDomains(url: string): Promise<Set<string>> {
Just to reinforce what Justin said... you don't need to implement my derive idea to keep things in the observable.

```javascript
const domains$ = this.equivalentDomains$.pipe(
   map((equivalentDomains) => {
      const domain = Utils.getDomain(url);
      if (domain == null || equivalentDomains == null) {
         return new Set();
      }

      // `findLast` will stop as soon as the last match happens, which
      // matches the behavior of your `forEach` call.
      const equivalents = equivalentDomains
        .findLast((ed) => ed.includes(domain));

      return equivalents;
   }
);

// let the caller decide whether to `firstValueFrom` or stay reactive
return domains$;
```

🎨 You'll note in the above code that I've removed the length check. You don't need to do that, since `includes` will exit immediately if there's no items in the array.

💭 There's two other array functions that may be of more value to you.

```javascript
// if there's multiple matches, this combines them all.
const equivalents = equivalentDomains
   .filter((ed) => ed.includes(domain))
   .flat();

// `find` will stop as soon as the *first* match happens
const equivalents = equivalentDomains
   .find((ed) => ed.includes(domain));
```

2024-03-07 21:30 UTC, jprusik commented on libs/common/src/autofill/services/domain-settings.service.ts
> +export class DomainSettingsService implements DomainSettingsServiceAbstraction {
okay; will adjust and use that convention for the other services I created

2024-03-07 21:36 UTC, jprusik commented on libs/common/src/state-migrations/migrations/30-move-domain-settings-to-state-providers.ts
> +      }
Yeah, I did that in autofill settings service. Not sure why I didn't copy that here...

Will address 👍

2024-03-07 21:40 UTC, jprusik commented on libs/common/src/state-migrations/migrations/30-move-domain-settings-to-state-providers.spec.ts
> +          equivalentDomains: ["apple.com", "icloud.com"],
yes! 👍

2024-03-11 17:03 UTC, jprusik commented on libs/common/src/state-migrations/migrations/30-move-domain-settings-to-state-providers.ts
> +      await helper.set<ExpectedGlobalState>("global", globalState);
Not addressing this one since the calls are already wrapped in the described block

2024-03-12 13:10 UTC, audrey-jensen approved these changes

2024-03-12 13:27 UTC, cagonzalezcs submitted a review, later dismissed

2024-03-12 18:14 UTC, justindbaur requested changes

2024-03-12 18:36 UTC, justindbaur approved these changes
Thank you!

2024-03-12 18:43 UTC, cagonzalezcs approved these changes

2024-03-12 19:02 UTC, audrey-jensen approved these changes

2024-03-12 19:07 UTC, gbubemismith approved these changes

2024-03-12 19:07 UTC, merged