[PM-5580][PM-5581] Send Browser State Provider
bitwarden/clients pull request #8232
Opened 2024-03-06 19:40 UTC by ttalty

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Move the search text, scroll position, send collection, and send type counts state to the state provider.

## Code changes

- **apps/browser/src/platform/services/abstractions/browser-state.service.ts:** Removing the old state service calls
- - **apps/browser/src/platform/services/browser-state.service.ts:** Removing the old state service calls
- **apps/browser/src/platform/services/browser-state.service.spec.ts:** Removing the old state service tests
- **libs/common/src/platform/state/state-definitions.ts:** State definition added for browser sends
- **apps/browser/src/tools/popup/services/browser-send-state.service.ts:** State provider implementation for the `BrowserComponentState` and `BrowserSendComponentState` for sends
- **apps/browser/src/tools/popup/services/browser-send-state.service.spec.ts:** Tests for `BrowserSendStateService`
- **apps/browser/src/popup/services/services.module.ts:** Adding the creating of the `BrowserSendStateService`
- **apps/browser/src/popup/app.component.ts:** Added the `BrowserSendStateService`  to and set the 2 states to empty
- **apps/browser/src/tools/popup/send/send-groupings.component.ts:** Send groupings to implement the new `BrowserSendStateService`
- **apps/browser/src/tools/popup/send/send-type.component.ts:** Send type to implement the new `BrowserSendStateService`
- 

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-03-07 15:48 UTC, audrey-jensen requested changes
🤔 Concerns that could benefit from discussion
⛏️ Nitpick
⚠️ Requested change
📝 Notes

2024-03-07 15:48 UTC, audrey-jensen commented on apps/browser/src/tools/popup/services/browser-send-state.service.ts
> +export class BrowserSendStateService {
⚠️ This class needs its public/exported members documented.

2024-03-07 15:48 UTC, audrey-jensen commented on apps/browser/src/tools/popup/services/browser-send-state.service.spec.ts
> +      expect(actual).toBeInstanceOf(BrowserSendComponentState);
🤔 Pretty sure this test isn't necessary. It covers the same test scenario as the one on line 58. If you want to be sure an instance is returned, just move this `expect` call into that test.

2024-03-07 15:48 UTC, audrey-jensen commented on apps/browser/src/tools/popup/services/browser-send-state.service.spec.ts
> +    });
⛏️ This test should be in a describe block for the KeyDefinition. The service may call it indirectly through the state service, but it is an independent type.

2024-03-07 15:48 UTC, audrey-jensen commented on apps/browser/src/tools/popup/services/browser-send-state.service.spec.ts
> +      await stateService.setBrowserSendComponentState(state);
⚠️ This test should should call [`awaitAsync()`](https://github.com/bitwarden/clients/blob/0e075259a667907198e3f6d44c4bf7e9c8221bb3/libs/common/spec/utils.ts#L100) after `setBrowserSendComponentState(...)` because the promise returned by `stateService.update` can complete before the state read on line 66 updates.

2024-03-07 15:48 UTC, audrey-jensen commented on apps/browser/src/tools/popup/services/browser-send-state.service.spec.ts
> +  describe("getBrowserSendTypeComponentState", () => {
📝 The notes above also apply to these tests.

2024-03-13 18:48 UTC, ttalty commented on apps/browser/src/tools/popup/services/browser-send-state.service.spec.ts
> +      await stateService.setBrowserSendComponentState(state);
Added `awaitAsync()` to the tests

2024-03-13 18:50 UTC, ttalty commented on apps/browser/src/tools/popup/services/browser-send-state.service.spec.ts
> +    });
Added a new `key-definitions.spec.ts` to run test for the key definitions

2024-03-13 18:51 UTC, ttalty commented on apps/browser/src/tools/popup/services/browser-send-state.service.spec.ts
> +      expect(actual).toBeInstanceOf(BrowserSendComponentState);
Removed

2024-03-13 18:51 UTC, ttalty commented on apps/browser/src/tools/popup/services/browser-send-state.service.ts
> +export class BrowserSendStateService {
Added more detailed document including the public members.

2024-03-13 18:51 UTC, ttalty commented on apps/browser/src/tools/popup/services/browser-send-state.service.ts
> + *  BrowserSendComponentState contains sends and the type count along with scroll position
Elaborated further on active user for sends.

2024-03-13 18:52 UTC, ttalty commented on apps/browser/src/tools/popup/services/browser-send-state.service.ts
> + *  BrowserComponentState contains just scroll position and search text.
Added the docs to the observables and methods.

2024-03-13 18:52 UTC, audrey-jensen approved these changes

2024-03-20 23:25 UTC, willmartian approved these changes
Platform changes LGTM ✅ 

One non-blocking question:

2024-03-20 23:25 UTC, willmartian commented on apps/browser/src/popup/services/services.module.ts
> +    },
Why put this in the providers array instead of marking it as `@Injectable({ providedIn: 'root' })`?

2024-03-22 16:15 UTC, ttalty commented on apps/browser/src/popup/services/services.module.ts
> +    },
Not needed. Same as in jslib. Removed in recent push.

2024-04-03 18:18 UTC, audrey-jensen approved these changes
Marking approved since I'm unsure whether I'm barking up the wrong tree with my nit.

⛏️ nitpick
❓ question

2024-04-03 18:18 UTC, audrey-jensen commented on apps/browser/src/platform/services/abstractions/browser-state.service.ts
> +  addAccount: (account: Account) => Promise<void>;
⛏️ Could these be documented? If they're just implementations of `BaseStateServiceAbstraction` which features the docs, then this can be ignored. It seems like they're net-new though.

2024-04-03 18:18 UTC, audrey-jensen commented on apps/browser/src/popup/services/services.module.ts
> +  // Do not register your dependency here! Add it to the typesafeProviders array using the helper function
❓ Just to confirm, this is precisely what you did on lines 476-480?

2024-04-03 18:55 UTC, ttalty commented on apps/browser/src/popup/services/services.module.ts
> +  // Do not register your dependency here! Add it to the typesafeProviders array using the helper function
Correct. The new logic removes the registering of the dependencies there and adds to the SafeProvider array.

2024-04-03 19:57 UTC, audrey-jensen requested changes
One really minor ⛏️ nit.

2024-04-03 19:57 UTC, audrey-jensen commented on apps/browser/src/platform/services/browser-state.service.ts
> +  implements StateServiceAbstraction
⛏️ `BrowserStateService` should probably be renamed to `DefaultBrowserStateService` to suit the [latest naming guidelines for Angular components](https://contributing.bitwarden.com/architecture/clients/presentation/angular#abstract--default-implementations). That'll also help you avoid aliasing in the `import` statement.

2024-04-03 20:05 UTC, audrey-jensen submitted a review, later dismissed

2024-04-03 21:17 UTC, audrey-jensen approved these changes

2024-04-04 14:35 UTC, willmartian approved these changes

2024-04-04 18:46 UTC, cagonzalezcs approved these changes
Looks through the whole PR, looks solid from my side. In review of the smaller changes made to autofill scoped files, I have no concerns.

2024-04-08 14:30 UTC, merged