[PM 5012] migrate adjust subscription component
bitwarden/clients pull request #8239
Opened 2024-03-07 13:00 UTC by vinith-kovan

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [X] Other
```

## Objective

Migrate the adjust subscription component to use the Component Library

## Code changes
adjust-subscription.component.ts -Updated the form inputs and checkbox to use the equivalent components from the Component Library.
adjust-subscription.component.html - updated the initial state with form builder.

## Screenshots
Before Migration:

![image](https://github.com/bitwarden/clients/assets/156108204/bd9e8afb-9248-4854-817e-32d0b82c2dee)

![image](https://github.com/bitwarden/clients/assets/156108204/7fddf682-22d3-4f1c-adf1-e9ee182b854a)

After Migration:

![image](https://github.com/bitwarden/clients/assets/156108204/8bc2dddb-f994-4807-b4a6-840c0f48d710)

![image](https://github.com/bitwarden/clients/assets/156108204/b787c8bd-1702-4516-bed4-747c314e89e6)

2024-03-25 20:23 UTC, willmartian requested changes

2024-03-25 20:23 UTC, willmartian commented on apps/web/src/app/billing/organizations/adjust-subscription.component.ts
>      try {
This try/catch block is no longer necessary since we are using `bitSubmit`

2024-03-25 20:23 UTC, willmartian commented on apps/web/src/app/billing/organizations/adjust-subscription.component.html
> +          [required]="adjustSubscriptionForm.value.limitSubscription"
Validators should be defined in the template.

2024-04-01 05:22 UTC, vinith-kovan commented on apps/web/src/app/billing/organizations/adjust-subscription.component.html
> +        <input bitInput formControlName="newSeatCount" type="number" min="0" step="1" required />
we noticed that when we remove the min attribute from HTML inputs, users are able to input negative values despite validators being in place. Strangely, upon reviewing the code in the CL library on Storybook, it seems that the min attribute is indeed present in the HTML. I have attached a screenshot. Could you confirm this?
![image](https://github.com/bitwarden/clients/assets/156108204/237d6e7c-95c0-4559-80e4-95e37e52b3a3)

2024-04-04 16:27 UTC, willmartian commented on apps/web/src/app/billing/organizations/adjust-subscription.component.html
> +        <input bitInput formControlName="newSeatCount" type="number" min="0" step="1" required />
Hey @vinith-kovan, I was wrong in my initial comment. You should retain the `min` and `max` attributes. Thanks for double checking!

2024-05-08 17:31 UTC, amorask-bitwarden approved these changes

2024-05-09 15:31 UTC, merged