[PM-5363] PinCryptoService State Providers
bitwarden/clients pull request #8244
Opened 2024-03-07 19:31 UTC by rr-bw

- **move pinKeyEncryptedUserKey**
- **move pinKeyEncryptedUserKeyEphemeral**
- **remove comments**
- **cleanup**

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-04-16 13:07 UTC, jlf0dev reviewed
So far this is looking great! This was definitely a much needed upgrade. I didn't go too deep into your changes since its still in progress, so let me know when you're ready for me to look through it again.

2024-04-16 13:07 UTC, jlf0dev commented on libs/auth/src/common/services/pin/pin.service.implementation.ts
> +  }
We just need to be careful here to make sure that we don't use the negation of this on the lock screen to check if we can ask for pin. There's extra logic in that check since the pin can't be used if MP on Restart is enabled and we haven't logged in with MP yet.

2024-04-16 13:07 UTC, jlf0dev commented on libs/common/src/platform/abstractions/crypto.service.ts
Love all the red here 👏

2024-04-18 15:02 UTC, MGibson1 commented on libs/auth/src/common/abstractions/pin.service.abstraction.ts
> +   * TODO-rr-bw: OR consider moving back to CryptoService within the storeAdditionalKeys() method since it is only used there once
Please resolve I think either is probably fine, but this is similar to the move for master password, right? It should be consistent with what happens there

2024-04-18 15:07 UTC, MGibson1 commented on libs/common/src/platform/services/crypto.service.ts
> +    // }
Please resolve.

I've had trouble with this, too, but setting values to null is fine. Setting them to `undefined` will throw.

2024-04-18 15:12 UTC, MGibson1 commented on libs/auth/src/common/services/pin/pin.service.implementation.ts
> + */
👏

2024-04-18 15:26 UTC, audrey-jensen approved these changes
👍🏻 kudos!
🎨 suggestion
💭 wandering thoughts
❓ curiosity
⛏️ nitpick

2024-04-18 15:26 UTC, audrey-jensen commented on libs/auth/src/common/abstractions/pin.service.abstraction.ts
> +export abstract class PinServiceAbstraction {
❓ This is for PIN-based logins? (As opposed to passwords or biometrics?)

⛏️ If so, that would be great to state here.

🎨 The [naming conventions for abstractions](https://contributing.bitwarden.com/architecture/clients/presentation/angular#abstract--default-implementations) changed. This should be called `PinService` and the implementation should be called `DefaultPinService`.

2024-04-18 15:26 UTC, audrey-jensen commented on libs/auth/src/common/services/pin/pin.service.implementation.ts
> + *                After client reset the master password is required to unlock.
👍🏻 Loving the documentation! It's making it easier to understand what's going on!

2024-04-18 15:26 UTC, audrey-jensen commented on libs/auth/src/common/services/pin/pin.service.implementation.ts
> +});
🎨 If I understand this code, it's being used to implement key rotation? [`BufferedState`](https://github.com/bitwarden/clients/commit/44d59f0d8cea06bac240764aabcb5a747c5bf2de) from the tools code might be a cleaner fit. It'll probably need to be tweaked to more cleanly fit the use-case. If you're interested, let's chat!

2024-04-18 15:26 UTC, audrey-jensen commented on libs/auth/src/common/services/pin/pin.service.implementation.ts
> +      await this.stateService.getKdfConfig({ userId: userId }),
💭 I think I have a place in the generator where I need `getEmail`, and couldn't figure out where to grab it from. I'm guessing these are left in because they're not migrated yet?

2024-04-18 15:26 UTC, audrey-jensen commented on libs/auth/src/common/services/pin/pin.service.implementation.ts
> +export type PinLockType = "DISABLED" | "PERSISTANT" | "TRANSIENT";
⛏️ Looks like there's a typo here. If it's left in for backwards compatibility, just add a comment so that some later editor isn't tempted to fix it the wrong way.

```suggestion
export type PinLockType = "DISABLED" | "PERSISTENT" | "TRANSIENT";
```

2024-04-18 15:26 UTC, audrey-jensen commented on libs/auth/src/common/services/pin/pin.service.implementation.ts
> +    pinKeyEncryptedUserKey ||= await this.getPinKeyEncryptedUserKeyEphemeral();
👍🏻 Such a nice way to avoid lots of repetition and parentheses. 😄

2024-04-18 15:26 UTC, audrey-jensen commented on libs/auth/src/common/services/pin/pin.service.implementation.ts
> +      await this.setPinKeyEncryptedUserKey(pinKeyEncryptedUserKey);
💭 I wonder whether there's ways to lift the comments into the type system by using `Opaque` or `Tagged` from `typefest`.

2024-04-18 15:26 UTC, audrey-jensen commented on libs/auth/src/common/services/pin/pin.service.implementation.ts
> +    await this.stateService.setCryptoMasterKeyBiometric(null);
❓ Is this another place where you're waiting for a different state interface? If it's a matter of not being able to migrate the data until now because it's encrypted, that's actually precisely the use-case `BufferedState` was made to address.

2024-04-18 15:33 UTC, MGibson1 commented on libs/auth/src/common/services/pin/pin.service.implementation.ts
> +      await this.stateService.getEmail({ userId: userId }),
Please use account service for grabbing emails

2024-04-18 15:35 UTC, MGibson1 commented on libs/auth/src/common/services/pin/pin.service.implementation.ts
> +  async storePinKeyEncryptedUserKey(userKey: UserKey, userId?: UserId) {
Please resolve a constant userId at the top of the method. This can be from state provider's activeUserId helper method
```typescript
userId ??= await firstValueFrom(this.stateProvider.activeUserId?)
if (userId == null) {
  throw new Error("No UserId provided an not current active user.");
}
```

2024-04-18 15:38 UTC, MGibson1 commented on libs/auth/src/common/services/pin/pin.service.implementation.ts
> +  async decryptUserKeyWithPin(pin: string): Promise<UserKey | null> {
Same as `storePinKeyEncryptedUserKey`, please use a constant `userId` while resolving the user key

2024-04-18 15:39 UTC, MGibson1 commented on libs/auth/src/common/services/pin/pin.service.implementation.ts
> +    pinKeyEncryptedUserKey ||= await this.getPinKeyEncryptedUserKeyEphemeral();
Same as `storePinKeyEncryptedUserKey,` please use a constant `userId`

2024-04-18 15:41 UTC, MGibson1 commented on libs/auth/src/common/services/pin/pin.service.implementation.ts
> +      // TODO-rr-bw: based on this comment, shouldn't this code be placed outside the if/else block?
seems so, Perhaps check the blame on the commit to discern what the issue was that triggered this?

2024-04-18 15:46 UTC, MGibson1 commented on libs/common/src/state-migrations/migrations/56-move-pin-state-to-providers.ts
> +          await helper.set(userId, account);
**nit**: Can reduce IO by setting these once outside of the if statements and flagging the need to write with a bool
```typescript
let accountUpdated = false;

if (...) {
  ....
  accountUpdated = true;
}

...

if (accountUpdated) {
  // write the updated object
}
```

2024-04-23 17:58 UTC, jlf0dev commented on libs/auth/src/common/services/pin/pin.service.implementation.ts
> +});
Spoke with @audrey-jensen on this and `BufferedState` does sound like a nice fit here (among other places). We most likely won't implement it within this PR but will run it by @rr-bw later to see what he thinks. Thanks @audrey-jensen!

2024-04-23 18:05 UTC, audrey-jensen commented on libs/auth/src/common/services/pin/pin.service.implementation.ts
> +    await this.stateService.setCryptoMasterKeyBiometric(null);
After an out-of-band conversation, it does seem this is the case. It also follows that it won't be addressed as part of this PR.

2024-04-23 22:08 UTC, rr-bw commented on libs/angular/src/auth/components/set-pin.component.ts
> +      await this.pinService.setPinKeyEncryptedUserKey(pinKeyEncryptedUserKey);
I moved much of it [like so](https://github.com/bitwarden/clients/pull/8244/files#diff-1eeb269493fd4e134787f41050fea890aea9ef5fb1d693ccef5fabbe1524bd0bR51-R63). Let me know what you think.

2024-04-23 23:00 UTC, rr-bw commented on libs/auth/src/common/abstractions/pin.service.abstraction.ts
> +export abstract class PinServiceAbstraction {
It's for PIN-based unlocks, set via the settings on Browser and Desktop. Thanks for the heads up on the naming convention changes. I discussed with Auth and we'll keep that in mind going forward, but for this PR I'm going to skip it to limit scope.

2024-04-23 23:10 UTC, rr-bw commented on libs/auth/src/common/services/pin/pin.service.implementation.ts
> +      await this.stateService.getKdfConfig({ userId: userId }),
Matt [said to use the AccountService](https://github.com/bitwarden/clients/pull/8244#discussion_r1570984702) for the email, so I've updated accordingly.
Correct, the [KdfConfigService](https://github.com/bitwarden/clients/pull/8715) is in process and will likely be merged before this, so I'll incorporate those changes.

2024-04-23 23:17 UTC, rr-bw commented on apps/browser/src/popup/settings/settings.component.ts
> +      pin: await this.pinService.isPinSet(),
I'd prefer to keep it as is. To me, `pinIsSet()` reads like a statement that "the pin is in fact set" (though of course it is a boolean). Whereas `isPinSet()` reads like a question that more clearly conveys that it may or it may not be set. If you think otherwise please let me know and I'm happy to change.

2024-04-23 23:18 UTC, rr-bw commented on libs/common/src/platform/services/crypto.service.ts
> +    // }
Discussed with @jlf0dev and resolved.

2024-04-23 23:18 UTC, rr-bw commented on libs/common/src/platform/services/state.service.ts
> +  // MEMORY
Yep! thanks.

2024-04-23 23:19 UTC, rr-bw commented on libs/auth/src/common/services/pin/pin.service.implementation.ts
> +  async storePinKeyEncryptedUserKey(userKey: UserKey, userId?: UserId) {
Thanks, I also updated other methods to require a userId.

2024-04-23 23:20 UTC, rr-bw commented on libs/auth/src/common/services/pin/pin.service.implementation.ts
> +      // TODO-rr-bw: based on this comment, shouldn't this code be placed outside the if/else block?
Resolved

2024-04-23 23:20 UTC, rr-bw commented on libs/common/src/state-migrations/migrations/56-move-pin-state-to-providers.ts
> +          await helper.set(userId, account);
Cool! Thanks.

2024-04-24 15:45 UTC, audrey-jensen commented on libs/auth/src/common/abstractions/pin.service.abstraction.ts
> +export abstract class PinServiceAbstraction {
Cool cool! Please document that it's for PIN-based unlocks in a comment. Once that's complete, this LGTM!

2024-04-29 20:11 UTC, jlf0dev requested changes
Thanks for the hard work on this! Had a bunch of minor things

2024-04-30 19:13 UTC, rr-bw commented on libs/auth/src/common/services/pin/pin.service.implementation.ts
> +   * @returns UserKey
I realize now that I had changed some of the method names in that function to be more clear, such that now this documentation is kind of unnecessary. I removed most of it and just updated the summary.

2024-04-30 23:54 UTC, rr-bw commented on libs/auth/src/common/services/pin/pin.service.implementation.ts
> +      (await firstValueFrom(this.accountService.activeAccount$))?.email,
Do we have a clean way for getting the account email by userId with the account service (couldn't find one). Or are you wanting me to revert to `stateService.getEmail(...)`?

Tagging @MGibson1

2024-05-01 07:28 UTC, rr-bw commented on libs/auth/src/common/services/pin/pin.service.spec.ts
> +        it(`should successfully decrypt and return user key when using a valid PIN`, async () => {
Updated those tests as I noticed I had left `decryptAndMigrateOldPinKeyEncrypterMasterKey()` and `decryptUserKey()` public when they should have been private. So I made those private and adjusted the tests accordingly, making sure to also check for clearing and setting new state as you mentioned.

2024-05-01 07:34 UTC, rr-bw commented
@jlf0dev @MGibson1 This is ready for another review. Most recent updates have been to `pin.service.spec.ts` and to the migration/rollback tests (to incorporate the recently merged [AccountService PR](https://github.com/bitwarden/clients/pull/8893)).

Also, since some of this code is a bit complex, as I worked I marked several places with a comment "TODO-rr-bw: verify". These are places where I'm looking really just looking for a head-nod to make sure what I did was correct. Will remove after confirmation.

2024-05-02 14:11 UTC, jlf0dev commented on libs/auth/src/common/services/pin/pin.service.implementation.ts
> +      (await firstValueFrom(this.accountService.activeAccount$))?.email,
I _think_ it would look something like:
```ts
const email = await firstValueFrom(this.accountService.accounts$.pipe(map((accounts) => accounts[userId].email)));
```

You're right in that its a little clunky. We need a getter on the account service, I just don't think there's been a lot of usage in this way yet.

2024-05-02 18:24 UTC, rr-bw commented on libs/common/src/auth/abstractions/master-password.service.abstraction.ts
> +  ) => Promise<UserKey>;
Great, changes [here](https://github.com/bitwarden/clients/pull/8244/commits/62228b24157028e27dfe95a9e0c2fb7c52d9da2d) and updated `jslib-services.module.ts`. Do the imports for `main.background.ts` and `bw.ts` also need to change? The object there is currently of type `InternalMasterPasswordService`, but I assume we need it that way for other service dependencies?

![Screenshot 2024-05-02 at 11 18 12 AM](https://github.com/bitwarden/clients/assets/102181210/407e8078-391b-4e56-9f85-3cfd5a4054bc)

2024-05-06 14:07 UTC, MGibson1 requested changes
I have a few nits, but we should correct the pin comparison method.

2024-05-06 14:07 UTC, MGibson1 commented on libs/auth/src/common/services/pin/pin.service.implementation.ts
> +  async setProtectedPin(protectedPin: string, userId: UserId): Promise<void> {
Please update protected pin type to represent it's encrypted nature. This probably means parsing the value into an `EncString` as part of the service.

2024-05-06 14:07 UTC, MGibson1 commented on libs/auth/src/common/services/pin/pin.service.implementation.ts
> +    return decryptedPin === pin;
**issue**: This isn't a likely avenue for a timing attack, but in general comparing encrypted data needs to use `CryptoFunctionService.compare` double-hmac verification rather than a method that will early return on failure.

2024-05-07 12:30 UTC, jlf0dev commented on libs/common/src/auth/abstractions/master-password.service.abstraction.ts
> +  ) => Promise<UserKey>;
Exactly, it doesn't need to change since we need it for other types that _do_ use internal. The interface on the PinService will narrow it and give us type safety, even if under the hood its the internal class.

2024-05-07 22:46 UTC, rr-bw commented on libs/common/src/platform/services/crypto.service.spec.ts
> +      );
Good catch. Updated and renamed for clarification.

2024-05-07 22:47 UTC, rr-bw commented on libs/auth/src/common/abstractions/pin.service.abstraction.ts
> + * Used for PIN-based unlocks on Browser and Desktop
Done.

2024-05-07 22:48 UTC, rr-bw commented on libs/auth/src/common/services/pin/pin.service.implementation.ts
> +export const PROTECTED_PIN = new UserKeyDefinition<string>(PIN_DISK, "protectedPin", {
Renamed to `USER_KEY_ENCRYPTED_PIN` and updated type.

2024-05-07 22:48 UTC, rr-bw commented on libs/auth/src/common/services/pin/pin.service.implementation.ts
> +  private async setPinKeyEncryptedUserKey(encString: EncString, userId: UserId): Promise<void> {
Done.

2024-05-07 22:49 UTC, rr-bw commented on libs/auth/src/common/services/pin/pin.service.implementation.ts
> +    encString: EncString,
Done.

2024-05-07 22:49 UTC, rr-bw commented on libs/auth/src/common/services/pin/pin.service.implementation.ts
> +  async setProtectedPin(protectedPin: string, userId: UserId): Promise<void> {
Done. Also renamed methods to `getUserKeyEncryptedPin()`, etc.

2024-05-07 22:50 UTC, rr-bw commented on libs/auth/src/common/services/pin/pin.service.implementation.ts
> +    return decryptedPin === pin;
I ended up using `compareFast()` because I'm comparing two strings. Is that okay?

2024-05-07 23:04 UTC, rr-bw commented
Addressed the latest round of feedback and ready for another review.

Here are a few areas that I'd just like a quick yes/no verification (all related to cryptographic methods):
- [Verify #1](https://github.com/bitwarden/clients/pull/8244/files#diff-6a265e96dd928a674c39cb85302ba6db41048e1c1f0ecfe5359ddb51a0076af2R46-R48): is 32 correct for each of these?
- [Verify #2](https://github.com/bitwarden/clients/pull/8244/files#diff-6a265e96dd928a674c39cb85302ba6db41048e1c1f0ecfe5359ddb51a0076af2R439): Did I mock this correctly?
- [Verify #3](https://github.com/bitwarden/clients/pull/8244/files#diff-6a265e96dd928a674c39cb85302ba6db41048e1c1f0ecfe5359ddb51a0076af2R446): Did I mock this correctly?

@MGibson1 @jlf0dev

2024-05-07 23:06 UTC, rr-bw commented on libs/auth/src/common/services/pin/pin.service.spec.ts
> +      stateService.getEmail.mockResolvedValue(mockUserEmail); // TODO-rr-bw: Fix this (now using accountService)
@jlf0dev How would I mock this email now that we're using AccountService? ([see here](https://github.com/bitwarden/clients/pull/8244/files#diff-5af6f282cff4845f595cfd77884888b3ed790cac99b2c684770dffc9978769eeR306))

2024-05-07 23:11 UTC, rr-bw commented on libs/auth/src/common/abstractions/pin.service.abstraction.ts
> +export abstract class PinServiceAbstraction {
JSDocs added to the top of the abstraction. Since the service can be a bit complex, I gave a very basic overview of how the PIN-flow works. Let me know if you think it's overkill.

2024-05-07 23:16 UTC, rr-bw commented on libs/auth/src/common/services/pin/pin.service.spec.ts
> +  const mockPinKey = new SymmetricCryptoKey(randomBytes(32)) as PinKey; // TODO-rr-bw: verify 32 is correct
Quick verification please. Is 32 correct for each of these?

2024-05-07 23:17 UTC, rr-bw commented on libs/auth/src/common/services/pin/pin.service.spec.ts
> +      cryptoFunctionService.compareFast.calledWith(mockPin, "1234").mockResolvedValue(true); // TODO-rr-bw: verify
Quick verification please. Did I mock this correctly?

2024-05-07 23:17 UTC, rr-bw commented on libs/auth/src/common/services/pin/pin.service.spec.ts
> +      stateService.getEncryptedCryptoSymmetricKey.mockResolvedValue(mockUserKey.keyB64); // TODO-rr-bw: verify .keyB64 is correct
Quick verification please. Did I mock this correctly?

2024-05-08 12:17 UTC, MGibson1 commented on libs/auth/src/common/services/pin/pin.service.spec.ts
> +  const mockPinKey = new SymmetricCryptoKey(randomBytes(32)) as PinKey; // TODO-rr-bw: verify 32 is correct
- user key is 64 bits (32 bits for encryption, 32 bits for mac)
- master password key is 32 bits
- pin key is 32 bits

2024-05-08 12:38 UTC, MGibson1 commented on libs/auth/src/common/services/pin/pin.service.implementation.ts
> +    return decryptedPin === pin;
yep, it's the same method under the hood, it just uses node forge.

2024-05-08 12:44 UTC, MGibson1 commented on libs/auth/src/common/services/pin/pin.service.spec.ts
> +      cryptoFunctionService.compareFast.calledWith(mockPin, "1234").mockResolvedValue(true); // TODO-rr-bw: verify
yes, this does have the caveat that it only sets up the resolved value if the mock is called with values matching those you specified. Otherwise it'll resolve null.

2024-05-08 12:45 UTC, MGibson1 commented on libs/auth/src/common/services/pin/pin.service.spec.ts
> +      stateService.getEncryptedCryptoSymmetricKey.mockResolvedValue(mockUserKey.keyB64); // TODO-rr-bw: verify .keyB64 is correct
yes

2024-05-08 12:51 UTC, MGibson1 approved these changes

2024-05-08 14:22 UTC, audrey-jensen submitted a review, later dismissed

2024-05-08 17:47 UTC, audrey-jensen approved these changes

2024-05-08 18:33 UTC, MGibson1 approved these changes

2024-05-08 18:34 UTC, jlf0dev approved these changes

2024-05-08 18:34 UTC, merged