Block Sending Null to `getUser`
bitwarden/clients pull request #8267
Opened 2024-03-09 02:25 UTC by justindbaur

## Type of change

```
- [x] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

`getUserState$` if called with no user id and called when there is no active user will result in a "You cannot build a user key without a valid UserId". With this change the returned observable will instead just not emit any value until there becomes an active user. This is more preferable than letting an internal error bubble up if people are passing a falsy `userId` into this method while there is no active user they likely have a bug in their code. 

An alternative method to `getUserState$` is also introduced to allow the caller to say that if they don't give a userId and their isn't immediately an active user then we will return a default value that is customizable by them. The inspiration is taken from C# `FirstOrDefault` and `SingleOrDefault` and the behavior takes aim at how someone could have used state service previously. In state service people previously had something like:

```typescript
const account = this.getAccount(optionalUserId);

return account?.settings?.myValue ?? [];
```

In `StateService`, `getAccount` would return null if there was no account and if callers null coalesced down into the value they care about and optionally null coalesced a default value then they would have never known their wasn't a different between the user having a null account object and there being no user to begin with. Now they could call the following code to be equivalent.

```typescript
// Wrap in firstValueFrom if they want a promise
this.stateProvider.getUserStateOrDefault$(myKeyDef, { userId: optionalUserId, defaultValue: [] });
```

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-03-12 14:57 UTC, MGibson1 requested changes
This looks like a reasonable improvement to the behavior, thanks!

2024-03-12 14:57 UTC, MGibson1 commented on libs/common/src/platform/state/implementations/default-state.provider.spec.ts
> +    "getUserState$ & getUserStateOrDefault$",
**nit**: Update your `describe.each` call such that it can be used to generate distinct test names.

This might work
```typescript
describe.each(["getUserState$", [userId]], ["getUserStateOrDefault$", [{userId: userId}]])((methodUnderTest, paramArray) => {
  ...
}
```

Then I think spread should work to call
```typescript
sut["methodUnderTest"](...paramArray)
```

There will probably be some type assurance stuff, though 🐸. If it doesn't work, you can always tack on an unused string in your each or `%#` in the test name

2024-03-12 14:57 UTC, MGibson1 commented on libs/common/src/platform/state/implementations/default-state.provider.spec.ts
It looks like you removed the tests that were validating that the `state$` returned from the get user state helper functions do indeed follow the state of the user.

I think these were important to validate that these helpers do not simply `take(1)` from the retrieved state (except for the new case with default)

2024-03-12 14:57 UTC, MGibson1 commented on libs/common/src/platform/state/state.provider.ts
> +   * @remarks If userId is falsy the observable return will point to the currently active user but will not follow subsequent active user changes,
**issue**: I don't think this is correct. This is true only if the userId is non-nullish. Please also update the remark in `getUserState$` since that behavior has changed

2024-03-12 14:57 UTC, MGibson1 commented on libs/common/src/platform/state/state.provider.ts
> +   * if there is no immediately available active user, then it will fallback to returning a default value in an observable.
```suggestion
   * if there is no immediately available active user, then it will fallback to returning a default value in an observable that immediately completes.
```

2024-03-12 15:59 UTC, justindbaur commented on libs/common/src/platform/state/implementations/default-state.provider.spec.ts
They are still there, I just moved them into the `describe.each` so that to new helper was also tested in the same way.

2024-03-15 00:21 UTC, justindbaur commented on libs/common/src/platform/state/state.provider.ts
> +   * @remarks If userId is falsy the observable return will point to the currently active user but will not follow subsequent active user changes,
I don't think this is totally wrong, if it's falsy it will attempt to point at the currently active user, I added language to clarify that it will "attempt" to and then fallback to the rest. Let me know if you think it's best.

2024-03-15 00:26 UTC, justindbaur commented on libs/common/src/platform/state/implementations/default-state.provider.spec.ts
> +    "getUserState$ & getUserStateOrDefault$",
Doing it with the name of the method and a params array wasn't making typescript happy even with method under test being restricted to `keyof StateProvider`. I kept it as injecting the methodUnderTest as a function but did add the name of the method to the first arg so it prints much better in the test name. Let me know what you think.

2024-03-15 12:47 UTC, MGibson1 approved these changes

2024-03-15 12:47 UTC, MGibson1 commented on libs/common/src/platform/state/implementations/default-state.provider.spec.ts
> +    "getUserState$ & getUserStateOrDefault$",
I thought it might be upset there, this was the fallback I was thinking, too

2024-03-15 13:05 UTC, merged