[PM-5020] Add Storage component migration
bitwarden/clients pull request #8301
Opened 2024-03-12 09:14 UTC by KiruthigaManivannan

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other
```

## Objective
Migrate the Add Storage component to use the component library.

## Code changes

- **adjust-storage.component.html :** Updated Form, Form Inputs, Cards to use the equivalent components from the Component Library. Cards are updated to Dialog component from component library.
-   **adjust-storage.component.ts :** Added FormGroup, Validators to FormControls. Used Dialog service to create a dialog open method. Dialog data interface and dialog result const is created.
-  **user-subscription.component.html :** Removed the adjust storage selector and properties bound to it.
- **user-subscription.component.ts :** Adjust storage dialog is opened during the onclick of AddStorage or RemoveStorage button. Final result of the dialog is captured and loaded again.
- **organization-subscription-cloud.component.html :** Removed the adjust storage selector and properties bound to it.
- **organization-subscription-cloud.component.ts :** Adjust storage dialog is opened during the onclick of AddStorage or RemoveStorage button. Final result of the dialog is captured and loaded again.

## Screenshots

-**Add storage button click** 
Before (card appears):
 
![image](https://github.com/bitwarden/clients/assets/162679756/4e800551-8392-41e5-b35b-cedd2da0151a)

After (cards are converted to dialog):
 
![image](https://github.com/bitwarden/clients/assets/162679756/ae9ebf4c-2311-4263-a1d4-2f0622923205)

-**Enter Value to input** 

Before: (price value changes in hint)

![image](https://github.com/bitwarden/clients/assets/162679756/e2be3b46-ec7f-4f22-9277-45c20a98612a)

 
After: (here also price changes as per storage)
 
![image](https://github.com/bitwarden/clients/assets/162679756/c6d44c0f-1d68-4556-a03b-5e84217bc815)

-**Click submit after entering storage value:**
Before: 
- a toast service opens with a success message
- And it regains the initail look with buttons (Add and Remove)
![image](https://github.com/bitwarden/clients/assets/162679756/6f3882e6-1ffc-475e-970e-adde9722c39b)

 
After: 
 
![image](https://github.com/bitwarden/clients/assets/162679756/2e63ea14-a24a-44ed-bae0-86d7fd0dd8e7)

2024-03-12 11:51 UTC, cyprain-okeke commented on apps/web/src/app/billing/individual/user-subscription.component.html
> -        <app-adjust-storage
Are we removing this completely, what code is replacing it

2024-03-12 14:18 UTC, KiruthigaManivannan commented on apps/web/src/app/billing/individual/user-subscription.component.html
> -        <app-adjust-storage
We are just calling that dialog component in the typescript file. So we removed it from HTML.

2024-03-13 07:03 UTC, KiruthigaManivannan commented on apps/web/src/app/billing/shared/adjust-storage.component.html
@willmartian  In this html, we have <small> tag. Do we have the alternative for this in component library ? . I tried using bit-hint, but when we use that inside this dialog footer , the text size of the hint appears large. So i reverted the change and used <small> tag itself as of now.  Please find the below image if we use bit-hint instead of small inside a dialog footer, 
![image](https://github.com/bitwarden/clients/assets/162679756/3d0a5dbc-40a2-434f-835e-0ac939494748)

2024-03-13 15:50 UTC, willmartian commented on apps/web/src/app/billing/shared/adjust-storage.component.html
@KiruthigaManivannan some of the screenshots in this thread are very low resolution--I'm not sure if GitHub messed them up when uploading. Could you take new screenshots?

@bitwarden/dept-design Should the text be in the footer, or above it?

2024-03-13 16:14 UTC, danielleflinn commented on apps/web/src/app/billing/shared/adjust-storage.component.html
This text should NOT be in the dialog footer. Please move it up into the body of the dialog below the "Total" help text. 

Also, ideally the "Total" help text would utilize the "hint" component and be associated to the input field above–less spacing between the text and the input field than is shown in the current UI is fine.

2024-03-14 00:06 UTC, willmartian requested changes

2024-03-14 07:11 UTC, KiruthigaManivannan commented on apps/web/src/app/billing/shared/adjust-storage.component.html
These changes are done

2024-03-14 07:12 UTC, KiruthigaManivannan commented on apps/web/src/app/billing/individual/user-subscription.component.ts
> +      this.showAdjustStorage = false;
Removed the flag showAdjustStorage

2024-03-14 07:20 UTC, KiruthigaManivannan commented on apps/web/src/app/billing/shared/adjust-storage.component.html
@willmartian Added new screenshots

2024-03-19 02:34 UTC, willmartian requested changes

2024-03-19 02:34 UTC, willmartian commented on apps/web/src/app/billing/individual/user-subscription.component.ts
> +      await this.load();
Don't use `any` unless absolutely necessary

2024-03-19 02:34 UTC, willmartian commented on apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html
>              </button>
Can we update these to use async actions?

`[bitAction]="adjustStorage(true)"`
`[bitAction]="adjustStorage(false)"`

```ts
adjustStorage = (add: boolean) => {
 return async () => { ... }
}
```

2024-03-19 02:34 UTC, willmartian commented on apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts
> +    const result: any = await lastValueFrom(dialogRef.closed);
Don't use `any` unless absolutely necessary

2024-03-19 02:34 UTC, willmartian commented on apps/web/src/app/billing/shared/adjust-storage.component.html
> +      </button>
Buttons within forms should have `bitFormButton` to handle loading/disable states.

2024-03-19 02:34 UTC, willmartian commented on apps/web/src/app/billing/shared/adjust-storage.component.html
> +            required
Are the directive validators (min, max, required) necessary since they are already defined in the `FormGroup`?

2024-03-19 02:34 UTC, willmartian commented on apps/web/src/app/billing/shared/adjust-storage.component.ts
> +  storageGbPrice: any;
Why `any` over `number`?

2024-03-19 22:14 UTC, willmartian requested changes

2024-03-19 22:14 UTC, willmartian commented on apps/web/src/app/billing/shared/adjust-storage.component.html
> +        <bit-form-field class="tw-col-span-2">
- This grid is missing a `gap`
- The original grid had the storage input spanning 6/12 columns. The new grid is 2/3. We should maintain the same ratio. (Keeping everything 12 based is a bit easier for me to review.)

2024-03-19 22:14 UTC, willmartian commented on apps/web/src/app/billing/shared/adjust-storage.component.html
> +      <p>{{ (add ? "storageAddNote" : "storageRemoveNote") | i18n }}</p>
`p` elements should have `bitTypography`

2024-03-19 22:14 UTC, willmartian commented on apps/web/src/app/billing/shared/adjust-storage.component.ts
>      }
Remove this try/catch, `bitSubmit` handles the error/logging for us.

2024-03-19 22:14 UTC, willmartian commented on apps/web/src/app/billing/shared/adjust-storage.component.ts
>    }
`cancel` is not called anywhere. The cancel button should either call it, or we should delete it and pass the desired close value to `bitDialogClose`

2024-03-19 22:14 UTC, willmartian commented on apps/web/src/app/billing/shared/adjust-storage.component.ts
> + * Strongly typed helper to open a StorageDialog
```suggestion
 * Strongly typed helper to open an AdjustStorageDialog
```

2024-03-20 08:52 UTC, KiruthigaManivannan commented on apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html
> +            <button
Earlier when cards were used , there was a flag showAdjustStorage which decides whether the "Add Storage" and "Remove Storage" buttons need to be visible as the card opens. But since we transformed to dialog , I just removed that flag so that even if dialog opens the buttons are visible at the background. Thats why the ngIf is removed

2024-03-20 09:10 UTC, KiruthigaManivannan commented on apps/web/src/app/billing/shared/adjust-storage.component.html
> +        <bit-form-field class="tw-col-span-2">
@willmartian As per your comment i have changed to 12 columns , but the col span i have used is 7. Because in Individual subscription page , the bit-hint of the bit-form-field spans 6 col , but in organization page it exceeds that size and comes to next line as shown below.
![image](https://github.com/bitwarden/clients/assets/162679756/a1c83695-5f0e-4ecd-b669-d2c012635cda)

2024-03-20 18:28 UTC, willmartian commented on apps/web/src/app/billing/shared/adjust-storage.component.html
> +        <bit-form-field class="tw-col-span-2">
Ah, I see. Thank you for the clarification.

2024-03-20 18:52 UTC, willmartian commented on apps/web/src/app/billing/shared/adjust-storage.component.html
> +        <bit-form-field class="tw-col-span-2">
@KiruthigaManivannan could we also move the paragraph above the input, to be consistent with @sukhleenb's [comment here](https://github.com/bitwarden/clients/pull/8321#issuecomment-1997744064)?

2024-03-20 19:00 UTC, willmartian requested changes
Just one more [requested change](https://github.com/bitwarden/clients/pull/8301#discussion_r1532634637) from me, but this is looking good.

2024-03-25 14:23 UTC, amorask-bitwarden approved these changes

2024-04-16 19:40 UTC, merged