[CL-146] Add kitchen sink story
bitwarden/clients pull request #8310
Opened 2024-03-12 18:25 UTC by vleague2

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other
```

## Objective

This PR adds a "kitchen sink" story, which is intended to help us better understand how component changes will look in a more app-like environment.

## TO DO

- [ ] still have ~1/4 of components left to add
- [ ] fix sizing of story
- [ ] add stories to open/display various components for snapshot testing purposes
- [ ] break down into smaller files

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-03-18 18:59 UTC, willmartian reviewed
Nice work!!!

A few things that standout as missing:

- ~Adjacent `bit-section` components with h2 headings.~
- Full `bit-dialog` with content. (There is a simple dialog.)

2024-03-18 18:59 UTC, willmartian commented on libs/components/src/stories/kitchen-sink/kitchen-sink.stories.ts
> +};
The dialog doesn't open for me on Firefox, but opens fine on Chrome/Safari.

2024-03-18 18:59 UTC, willmartian commented on libs/components/src/stories/kitchen-sink/kitchen-sink.stories.ts
> +          <bit-breadcrumb *ngFor="let item of navItems" [icon]="item.icon" [route]="[item.route]">
1. Since we already have other helper components in separate files, I think we should just move this one out too.

2. Let's make this standalone, to match the others components.

2024-03-18 18:59 UTC, willmartian commented on libs/components/src/stories/kitchen-sink/kitchen-sink.stories.ts
> +      <bit-banner bannerType="info"> This content is very important </bit-banner>
At this time, product devs must apply custom css to have banners span the full width of the layout: `-tw-m-6 tw-flex tw-flex-col tw-pb-6`, [jira](https://bitwarden.atlassian.net/browse/CL-205)

Should we also do that here since it is closer to actual usage?

2024-03-18 18:59 UTC, willmartian commented on libs/components/src/stories/kitchen-sink/kitchen-sink.mdx
> +`router-outlet`.
Thoughts on moving this to a bit-callout inside the story component?

2024-03-18 18:59 UTC, willmartian commented on libs/components/src/stories/kitchen-sink/components/kitchen-sink-form.component.ts
> +        ></bit-color-password>
Kinda off topic--should we own this in the first place?

<img width="504" alt="image" src="https://github.com/bitwarden/clients/assets/17113462/e8bc004f-8035-46f6-9dd2-be90f48b252b">

2024-03-18 18:59 UTC, willmartian commented on libs/components/src/stories/kitchen-sink/components/kitchen-sink-form.component.ts
> +        <bit-hint>Required!!!!!</bit-hint>
Let's update this hint to say anything else; we don't want to accidentally encourage devs to use hints to communicate that fields are required when that is handled automatically elsewhere.

2024-03-18 18:59 UTC, willmartian commented on libs/components/src/stories/kitchen-sink/kitchen-sink.stories.ts
> +        TypographyModule,
Perhaps we should make a shared module for the kitchen sink with all of the CL components in it? Then we can import that shared module here and into each helper component.

2024-03-18 18:59 UTC, willmartian commented on libs/components/src/stories/kitchen-sink/kitchen-sink.stories.ts
> +      <div class="tw-text-center tw-mb-6 tw-mt-6">
We don't really use center text styles in-product. Do you think that is a good reason to not use them in this story?

2024-03-18 18:59 UTC, willmartian commented on libs/components/src/stories/kitchen-sink/components/kitchen-sink-toggle-list.component.ts
> +        <bit-toggle value="small"> Mid-sized <span bitBadge variant="info">1</span> </bit-toggle>
Badges aren't rendering 
<img width="504" alt="image" src="https://github.com/bitwarden/clients/assets/17113462/765498a1-53e0-45f5-9bba-cc01ce9ec77c">

2024-03-18 19:03 UTC, willmartian commented on libs/components/src/stories/kitchen-sink/kitchen-sink.stories.ts
> +          <bit-kitchen-sink-form></bit-kitchen-sink-form>
Let's use a few `bit-section`s here to separate the sections instead of custom classes on the `h2` elements.

2024-03-18 19:23 UTC, vleague2 commented on libs/components/src/stories/kitchen-sink/kitchen-sink.stories.ts
> +      <bit-banner bannerType="info"> This content is very important </bit-banner>
If we don't use non-full-width banners, then probably. At that point it would get resolved as part of that ticket.

2024-03-18 19:24 UTC, vleague2 commented on libs/components/src/stories/kitchen-sink/kitchen-sink.mdx
> +`router-outlet`.
Ooh I like that. I kind of want to also leave it on the markdown page as an explanation for what this story actually is. Or we could get rid of the markdown page for this story?

2024-03-18 19:25 UTC, vleague2 commented on libs/components/src/stories/kitchen-sink/components/kitchen-sink-form.component.ts
> +        ></bit-color-password>
As in, should this be a component in the component library or a component in the web app?

2024-03-18 19:26 UTC, willmartian commented on libs/components/src/stories/kitchen-sink/kitchen-sink.mdx
> +`router-outlet`.
We could get rid of the markdown page entirely if you feel the callout communicates the message well enough.

2024-03-18 19:27 UTC, vleague2 commented on libs/components/src/stories/kitchen-sink/kitchen-sink.stories.ts
> +      <div class="tw-text-center tw-mb-6 tw-mt-6">
I don't feel like the layout helpers are necessarily meant to be instructive, but I could see how it might be interpreted as a guideline for composing components together. I can rework the page a bit to make it look less wonky with left-aligned components.

2024-03-18 19:30 UTC, willmartian commented on libs/components/src/stories/kitchen-sink/components/kitchen-sink-form.component.ts
> +        ></bit-color-password>
Should this be in the CL? Or should this belong in another team's library, something like `@bitwarden/tools`?

Or is the fact that it is low-level, dumb, and presentational good enough reason for the CL to own it?

2024-03-18 19:32 UTC, willmartian commented on libs/components/src/stories/kitchen-sink/kitchen-sink.stories.ts
> +      <div class="tw-text-center tw-mb-6 tw-mt-6">
Sounds good. I think that would help it look more Bitwarden-y at a glance.

2024-03-18 19:33 UTC, willmartian commented on libs/components/src/stories/kitchen-sink/kitchen-sink.stories.ts
> +      <bit-banner bannerType="info"> This content is very important </bit-banner>
Yeah, we do not use non-full-width banners.

2024-03-19 13:55 UTC, vleague2 commented on libs/components/src/stories/kitchen-sink/components/kitchen-sink-form.component.ts
> +        ></bit-color-password>
It seems a little bit specific to me compared to the other CL components, and right now it looks like it's only used in the web app in a few places. If that's the extent of its usage then I'm inclined to say it's not very reusable 🤔

2024-03-19 19:43 UTC, willmartian requested changes

2024-03-19 19:43 UTC, willmartian commented on libs/components/src/stories/kitchen-sink/components/kitchen-sink-form.component.ts
> +          toggleVisibility: "Toggle visibility",
Outside of this PR: I think we should deprecate this mock service, and look into using the [preloaded en module](https://github.com/bitwarden/clients/blob/25f89e2a1c3a13733c280240baad8bfb1df9d397/apps/web/src/app/core/tests/preloaded-english-i18n.module.ts#L9). Writing out i18n messages twice is not fun.

2024-03-19 21:06 UTC, vleague2 commented on libs/components/src/stories/kitchen-sink/components/kitchen-sink-form.component.ts
> +          class="tw-w-full"
Hm apparently yes 🤔  The other form fields have full width built in, but this one does not.

2024-03-19 21:07 UTC, vleague2 commented on libs/components/src/stories/kitchen-sink/components/kitchen-sink-form.component.ts
> +          </button>
Hmm since it's not navigational, I usually prefer buttons over links. What do you think?

2024-03-19 21:11 UTC, willmartian commented on libs/components/src/stories/kitchen-sink/components/kitchen-sink-form.component.ts
> +          </button>
`bitLink` is a presentational directive that can attach to either a `button` or `a` element:

`<button bitLink>`
`<a bitLink>`

[docs](https://62a88a6de5b807fa98886113-ypmfvggazn.chromatic.com/?path=/docs/component-library-link--docs)

2024-03-19 21:12 UTC, willmartian commented on libs/components/src/stories/kitchen-sink/components/kitchen-sink-form.component.ts
> +          class="tw-w-full"
Interesting. Could you remove the class for now to capture this discrepancy in the story?

2024-03-20 13:41 UTC, vleague2 commented on libs/components/src/stories/kitchen-sink/components/kitchen-sink-form.component.ts
> +          toggleVisibility: "Toggle visibility",
That feels like a nice dovetail of platform + CL concerns!

2024-03-20 14:42 UTC, vleague2 commented on libs/components/src/stories/kitchen-sink/components/kitchen-sink-form.component.ts
> +          class="tw-w-full"
The stories for the multi select also use this class, in case that matters (it's where I copied it from haha)

2024-03-21 19:21 UTC, willmartian approved these changes
Ship it!

2024-03-22 14:17 UTC, merged