[PM-5273] Migrate state in CipherService
bitwarden/clients pull request #8314
Opened 2024-03-12 23:03 UTC by LRNcardozoWDF

## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-03-13 16:59 UTC, cagonzalezcs submitted a review, later dismissed
Things are looking solid from my side, though the CipherService, FolderService, and CipherStateService classes seem to be missing Jest test coverage in a number of places. It'd be nice to address that, though I won't block the ticket for it.

Let me know if you need any further review on this.

2024-03-14 15:00 UTC, LRNcardozoWDF commented
@cagonzalezcs you're right, thank you for calling my attention to that. Will move this PR to draft while I work on adding those tests.

2024-03-14 17:45 UTC, MGibson1 commented on libs/common/src/vault/services/cipher.service.ts
> +    const decCiphers = await this.decryptCiphers(await this.getAll());
**issue**: This method really doesn't work like it used to. `getDecryptedCipherCache` will _always_ return the latest decrypted ciphers, it isn't really a passive store anymore like it was.

2024-03-14 17:50 UTC, MGibson1 commented on libs/common/src/vault/services/cipher.service.ts
> +    await this.decryptedCiphersState.forceValue(decryptedCipherCache);
If local data is fundamentally part of a cipher view, that needs to be part of your derive dependency by combining the encrypted state and local data as the input to your derive -- then this doesn't need to be done at all! it'll all jsut be recalculated as needed.

2024-03-14 17:57 UTC, MGibson1 commented on libs/common/src/vault/services/cipher.service.ts
>    async upsert(cipher: CipherData | CipherData[]): Promise<any> {
nice, this is kind of an external version of how the update method works, actually.

2024-04-03 23:38 UTC, shane-melton requested changes
Moving in the right direction! A few issues left to resolve in the last commit, please continue to reach out if you run into any other issues.

2024-04-03 23:38 UTC, shane-melton commented on libs/common/src/vault/services/cipher.service.ts
> +    this.addEditCipherInfo$ = this.addEditCipherInfoState.state$.pipe(
kudos: Nice! This will avoid having to re-create the CipherView each time the `addEditCipherInfo` is fetched like it was in the old getter.

2024-04-03 23:38 UTC, shane-melton commented on libs/common/src/vault/services/cipher.service.ts
> +      if (ciphers == null) {
question: Why do we need the null check here? If `ciphers` is null, won't we throw an exception above in the `for` loop?

2024-04-03 23:38 UTC, shane-melton commented on libs/common/src/vault/services/cipher.service.ts
> +    this.addEditCipherInfo$ = this.addEditCipherInfoState.state$.pipe(
suggestion: Looking at this again, can we instead move it to the deserializer in the `ADD_EDIT_CIPHER_INFO_KEY` key definition to ensure we keep the `CipherView` prototype there?

That is primary purpose of the deserializer method in the first place and seems like a good spot for it.

2024-04-03 23:38 UTC, shane-melton commented on libs/common/src/vault/services/key-state/ciphers.state.ts
thought: I think we still have a mismatch of storage locations for each of these pieces of state. Currently the `State` service uses the following for each piece:

1. Encrypted Ciphers: `OnDiskMemory` (`InMemory` for Web)
2. Local Data: `OnDiskLocal`
3. AddEditCipherInfo: `InMemory`

I don't think there is a way we can combine those into only two state definitions and we'll need 3 separate state definitions for the items above. e.g.

1. Encrypted Ciphers: `CIPHERS_DISK` = `disk` and `memory` for Web
2. Local Data:  `CIPHERS_LOCAL` = `disk` and `disk-local` for Web
3. AddEditCipherInfo: `CIPHERS_MEMORY` = `memory`

@MGibson1 @justindbaur Does this sound right to you as well? Or is there another way to reproduce that combination in State providers?

2024-04-04 19:07 UTC, MGibson1 commented on libs/common/src/vault/services/key-state/ciphers.state.ts
You're correct, three unique storage location policies require three unique state definitions

2024-04-08 08:28 UTC, gbubemismith reviewed
Nice job! @LRNcardozoWDF, just added a few suggestions and questions.

2024-04-08 08:28 UTC, gbubemismith commented on libs/common/src/vault/services/key-state/ciphers.state.ts
> +    deserializer: (addEditCipherInfo: AddEditCipherInfo) => {
nitpick: Is it possible to simplify this logic to avoid nested ternary? Something like this.

```suggestion
    deserializer: (addEditCipherInfo: AddEditCipherInfo) => {
      if (!addEditCipherInfo) return null;
            
      // no need for optional chaining since we check for null early enough
      const cipher = addEditCipherInfo.cipher.toJSON ? addEditCipherInfo.cipher : CipherView.fromJSON(addEditCipherInfo.cipher as Jsonify<CipherView>);
      
      return {
        cipher,
        collectionIds: addEditCipherInfo.collectionIds
      };
      }
```
I didn't test this, so please check

2024-04-08 08:28 UTC, gbubemismith commented on libs/common/src/vault/services/key-state/ciphers.state.ts
> +export const DECRYPTED_CIPHERS = KeyDefinition.record<CipherView>(
question: can we use `DeriveDefinition` for the decrypted ciphers?

2024-04-08 08:28 UTC, gbubemismith commented on libs/common/src/state-migrations/migrations/55-move-cipher-service-to-state-provider.spec.ts
> +      helper = mockMigrationHelper(exampleJSON(), 55);
nitpick: Since this is a migration, the version here should be 54.

2024-04-08 08:28 UTC, gbubemismith commented on libs/common/src/platform/state/state-definitions.ts
Can't we avoid `CIPHERS_MEMORY ` by using `DeriveDefinition` for the decrypted ciphers?

2024-04-08 13:37 UTC, MGibson1 commented on libs/common/src/platform/state/state-definitions.ts
We could, but that locks us into re-decrypting the full cipher list on change, which turns out to be too slow. It would be possible to come up with some scheme that allowed identification of updated ciphers, but that would require accurate comparisons that would probably be inefficient.

2024-04-08 14:24 UTC, MGibson1 approved these changes
This is looking good to my eyes right now. I think there's quite a bit of cleanup to schedule to try and limit this services interface, but this looks like a good switch to state providers

2024-04-08 15:42 UTC, audrey-jensen requested changes
⚠️ requested change
🤔 concern, but not necessarily an issue
🎨 suggestion
⛏️ nitpick
📝 note

2024-04-08 15:42 UTC, audrey-jensen commented on libs/common/src/vault/services/cipher.service.ts
> +    let ciphers = await firstValueFrom(this.ciphers$);
⚠️ Unfortunately, this will end up racing `replace` with pending emissions from `ciphers$`. In order to prevent it, you need to perform all of your logic within `this.ciphers$.update(...)`. `update` ensures that its `configureState` and `shouldUpdate` arguments sequence atomic updates.

```javascript
const ciphers = cipher instanceof CipherData ? [cipher] : cipher;
this.ciphers$.update((current) => {
   ciphers.forEach(c => current[c.id as CipherId]);
   return current;
});
```

It gets more complex if you need `async`, but it doesn't seem that's necessary here. Reach out if you want to know more. (I learned this the hard way.)

2024-04-08 15:42 UTC, audrey-jensen commented on libs/common/src/platform/state/state-definitions.ts
Seems like some kind of collection/key aware state provider might be able to sort this out. I'm also interested in this, as password generator history and sends also have this characteristic. I'm hoping to come back to it, maybe as a BEEEP-like thing.

2024-04-11 16:15 UTC, audrey-jensen submitted a review, later dismissed
The requested change I asked for is implemented. There's still a nit (I left it unresolved above), but it's not blocking.

2024-04-11 19:30 UTC, cagonzalezcs approved these changes

2024-04-15 15:47 UTC, MGibson1 approved these changes

2024-04-16 08:38 UTC, gbubemismith submitted a review, later dismissed

2024-04-16 15:40 UTC, audrey-jensen approved these changes

2024-04-16 15:47 UTC, cagonzalezcs approved these changes

2024-04-16 15:56 UTC, MGibson1 approved these changes

2024-04-16 16:37 UTC, merged