[PM-5018] Migrate Add Credit component
bitwarden/clients pull request #8321
Opened 2024-03-13 13:23 UTC by KiruthigaManivannan

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [X] Other
```

## Objective

Migrate the Add Credit component to use the component library.

## Code changes

- **add-credit.component.html:** Updated Form, Form Inputs, Radio Button groups, Cards to use the equivalent components from the Component Library. Cards are updated to Dialog component from component library.
- **add-credit.component.ts:** Added FormGroup, Validators to FormControls. Used Dialog service to create a dialog open method. Dialog data interface and dialog result const is created.
- **payment-method.component.html:** Removed the add-credit selector and properties bound to it.
- **payment-method.component.ts:** Add Credit dialog is opened during the onclick of Add Credit button. Final result of the dialog is captured and loaded again.

## Screenshots
-**On Click of Add Credit Button**
Before:
![image](https://github.com/bitwarden/clients/assets/162679756/ce8c72cf-56ac-4af0-a94f-9f026b4d864e)

After: 
![image](https://github.com/bitwarden/clients/assets/162679756/7e6c2eb9-7f79-4732-b81d-783c9503a9ba)
-**On Click of Submit Button**
Before: 
![image](https://github.com/bitwarden/clients/assets/162679756/39d42875-fe4f-4e6d-a203-11d72e1286b5)

After:
![image](https://github.com/bitwarden/clients/assets/162679756/b9e31414-2079-482d-b6ef-a3537be72d2d)

2024-03-13 23:03 UTC, willmartian requested changes

2024-03-13 23:03 UTC, willmartian commented on apps/web/src/app/billing/shared/payment-method.component.ts
> +      this.showAddCredit = false;
`this.showAddCredit` and `closeAddCredit()` are no longer needed since we are using a dialog now.

2024-03-14 15:36 UTC, sukhleenb commented
This looks great! The design team would like to make two suggestion:
1. Can we move the helper text (Added credit will appear on your account after...) to the top of the dialog in Body 1/regular styling since it applies to both PayPal and Bitcoin
2. I believe the second P in the PayPal radio button should be capitalized

I've attached a design of the suggestion
![Default](https://github.com/bitwarden/clients/assets/95638650/70166235-755c-45c9-ac6e-a3a49a8d7242)

2024-03-15 09:22 UTC, KiruthigaManivannan commented on apps/web/src/app/billing/shared/add-credit.component.ts
> +        throw e;
If we dont add throw e , the toast service messages are not appearing for dialog submit.

2024-03-15 09:22 UTC, KiruthigaManivannan commented on apps/web/src/app/billing/shared/payment-method.component.ts
> +      this.showAddCredit = false;
Removed this.showAddCredit and closeAddCredit()

2024-03-18 23:15 UTC, willmartian requested changes

2024-03-18 23:17 UTC, willmartian commented on apps/web/src/app/billing/shared/add-credit.component.html
> +      </button>
This is still needed @KiruthigaManivannan

2024-03-18 23:30 UTC, willmartian commented on apps/web/src/app/billing/shared/add-credit.component.ts
> +        throw e;
Ah, understood. We can actually remove the `try/catch` entirely.

_Unhandled_ errors in `bitSubmit` or `bitAction` handlers display a toast and call the `LogService` [by default.](https://github.com/bitwarden/clients/blob/28de9439beb87133c8683434df952a0c0be94100/libs/components/src/async-actions/bit-submit.directive.ts#L46-L47)

So this try/catch as written would actually call `LogService.error` twice.

2024-03-19 16:14 UTC, KiruthigaManivannan commented on apps/web/src/app/billing/shared/billing-shared.module.ts
But If I don't add it in module I get errors in using bitwarden library components. Like below
![image](https://github.com/bitwarden/clients/assets/162679756/a33b8d17-4d03-4dea-b4d9-d87a67198dde)

Like above im getting around 17 errors

2024-03-19 21:26 UTC, willmartian requested changes

2024-03-19 21:26 UTC, willmartian commented on apps/web/src/app/billing/shared/add-credit-dialog.component.html
> +      </button>
The `cancel` button should have the `bitFormButton` directive

2024-03-19 21:26 UTC, willmartian commented on apps/web/src/app/billing/shared/add-credit-dialog.component.ts
> +      if (this.formGroup.value.creditAmount == null) {
Use `creditAmount` getter here

2024-03-19 21:26 UTC, willmartian commented on apps/web/src/app/billing/shared/add-credit-dialog.component.ts
> +      if (this.formGroup.value.creditAmount == null) {
Use `creditAmount` getter here

2024-03-19 21:27 UTC, willmartian commented on apps/web/src/app/billing/shared/billing-shared.module.ts
Ah, I misread what was going on here. Thanks for clarifying

2024-03-20 19:55 UTC, willmartian approved these changes
Changes LGTM! Thanks @KiruthigaManivannan

2024-03-21 15:02 UTC, amorask-bitwarden submitted a review, later dismissed

2024-05-08 17:34 UTC, amorask-bitwarden approved these changes

2024-05-13 14:46 UTC, cyprain-okeke commented on apps/web/src/app/billing/shared/payment-method.component.html
> -      *ngIf="!showAddCredit"
Why is this `*ngIf="!showAddCredit"` is removed from the migrated file.

2024-05-16 05:10 UTC, KiruthigaManivannan commented on apps/web/src/app/billing/shared/payment-method.component.html
> -      *ngIf="!showAddCredit"
@cyprain-okeke  Earlier we had card component , so when we click the button , the button should not be shown and card replaces it inorder to do that we had the flag showAddCredit. But now we have changed it to dialog. So on button click dialog appears above the button and the button need not be hidden. So the flag is not required.

2024-05-21 12:47 UTC, cyprain-okeke approved these changes
Thanks for clarifying it. the changes Looks Good

2024-05-21 13:03 UTC, merged