[PM-5269]  Key Connector state migration
bitwarden/clients pull request #8327
Opened 2024-03-13 21:16 UTC by ike-kottlowski

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-03-15 15:47 UTC, jlf0dev requested changes

2024-03-15 15:47 UTC, jlf0dev commented on libs/common/src/auth/services/key-connector.service.ts
> +    await this.stateProvider.setUserState(CONVERT_ACCOUNT_TO_KEY_CONNECTOR, null, userId);
What about clearing the uses key connector? I think the `clearOn` worked has been merged by the way if you'd like to use that. Has been a pretty easy implementation from my experience.

2024-03-15 15:47 UTC, jlf0dev commented
Awesome tests by the way 🎉

2024-03-15 18:05 UTC, ike-kottlowski commented on apps/browser/src/autofill/browser/context-menu-clicked-handler.ts
> +export default CopyToClipboardOptions;
co-pilot "improvements" I missed. Thanks for catching.

2024-03-15 18:42 UTC, jprusik commented on libs/common/src/auth/services/key-connector.service.ts
> +    await this.stateProvider.setUserState(CONVERT_ACCOUNT_TO_KEY_CONNECTOR, null, userId);
Second this - super easy to use as well. We used it for EQUIVALENT_DOMAINS in the Domain Settings service, if that's helpful:

https://github.com/bitwarden/clients/blob/main/libs/common/src/autofill/services/domain-settings.service.ts#L23-L26

2024-03-15 18:48 UTC, jprusik commented on libs/common/src/auth/services/key-connector.service.ts
> +);
If you want to take @jlf0dev 's [suggestion](https://github.com/bitwarden/clients/pull/8327/files#r1526486161):

```suggestion
export const CONVERT_ACCOUNT_TO_KEY_CONNECTOR = new UserKeyDefinition<boolean>(
  KEY_CONNECTOR_DISK,
  "convertAccountToKeyConnector",
  {
    deserializer: (convertAccountToKeyConnector) => convertAccountToKeyConnector,
    clearOn: ["logout"],
  },
);
```

import `UserKeyDefinition` from the same location as `KeyDefinition`

2024-03-15 18:54 UTC, jprusik commented on libs/common/src/state-migrations/migrations/39-move-key-connector-to-state-provider.spec.ts
> +      helper = mockMigrationHelper(rollbackJSON(), 38);
Last I talked with @justindbaur we were doing latest on rollback here:

```suggestion
      helper = mockMigrationHelper(rollbackJSON(), 39);
```

Not blocking, just curious about what convention we use here, if any

2024-03-15 18:54 UTC, jprusik submitted a review, later dismissed
LGTM for autofill concerns

2024-03-15 18:55 UTC, ike-kottlowski commented on libs/common/src/auth/services/key-connector.service.ts
> +);
I was trying to fund usage examples, thanks!

2024-03-15 21:38 UTC, jprusik submitted a review, later dismissed

2024-03-19 16:32 UTC, ike-kottlowski commented on libs/common/src/state-migrations/migrations/39-move-key-connector-to-state-provider.spec.ts
> +      helper = mockMigrationHelper(rollbackJSON(), 38);
Why would we want to rollback to the current? 🤔

2024-03-19 19:34 UTC, jprusik submitted a review, later dismissed

2024-03-19 20:10 UTC, jlf0dev submitted a review, later dismissed

2024-03-23 01:22 UTC, justindbaur requested changes

2024-03-23 01:22 UTC, justindbaur commented on libs/common/src/state-migrations/migrations/49-move-key-connector-to-state-provider.ts
> +    const profileState = await helper.get<ExpectedAccountState>("profile");
You'll want to use the `helper.getAccounts<ExpectedAccountState>();` method. This will give you a list of accounts so that you migrate the data for each user. There are some examples of a similar pattern in migrations #44 & #45.

2024-03-23 01:22 UTC, justindbaur commented on libs/common/src/platform/services/state.service.ts
It should be safe to delete both the properties from this object now.

https://github.com/bitwarden/clients/blob/2a6f21200343daaa9af97b08578cd5b1f9d56252/libs/common/src/platform/models/domain/account.ts#L162-L170

2024-03-23 01:22 UTC, justindbaur commented on libs/common/src/state-migrations/migrations/49-move-key-connector-to-state-provider.spec.ts
> +    },
Our structure of state (that we are migrating from) currently is roughly:
```
{
  authenticatedAccounts: [ "userId1", "userId2" ],
  global: {
    globalValue: ""
  },
  userId1: {
    profile: {}
  },
  userId2: {
    profile: {}
  }
}
```

The `authenticatedAccounts` property is used to look up for other keys that are use values, that's essentially what the `getAccounts` method on `MigrationHelper` will do for you.

2024-03-25 14:17 UTC, jprusik approved these changes

2024-03-26 19:18 UTC, ike-kottlowski reviewed
Updated the Migrator and Migrator Tests per @justindbaur comments.

2024-03-27 13:54 UTC, jprusik approved these changes

2024-03-27 15:41 UTC, justindbaur requested changes
Couple minor things and then this is ready to go, thanks!

2024-03-27 15:41 UTC, justindbaur commented on libs/common/src/auth/services/user-verification/user-verification.service.ts
> +    private keyConnectorService: KeyConnectorServiceAbstraction,
It looks like this was added but wasn't use anywhere or am I missing something?

2024-03-27 15:41 UTC, justindbaur commented on libs/common/src/auth/services/key-connector.service.ts
> +    clearOn: ["logout"],
It looks like just convert account was cleared on logout so I think this one can just be `clearOn: []`.

2024-03-27 16:22 UTC, ike-kottlowski commented on libs/common/src/auth/services/user-verification/user-verification.service.ts
> +    private keyConnectorService: KeyConnectorServiceAbstraction,
Good catch.

2024-03-27 16:27 UTC, ike-kottlowski commented on libs/common/src/auth/services/key-connector.service.ts
> +    clearOn: ["logout"],
Yep, historically in the state service the `clear()` method only cleared the `convertAccountToKeyConnector` state, I'll update it. Thanks for pointing it out.

2024-03-27 16:45 UTC, jprusik submitted a review, later dismissed

2024-03-27 17:30 UTC, jprusik submitted a review, later dismissed

2024-03-28 13:32 UTC, jlf0dev reviewed
Great work! Looks good to me, just need to resolve some of the earlier feedback and I can approve

2024-03-28 13:38 UTC, justindbaur commented on libs/common/src/auth/services/key-connector.service.ts
> +    clearOn: ["logout"],
New information trumps my status quo, totally fine with me. It looks like it's set by `sync` so it makes sense to me that it would work fine with being cleared on logout.

2024-03-28 16:46 UTC, justindbaur approved these changes

2024-03-28 16:48 UTC, jprusik approved these changes

2024-03-28 16:50 UTC, jlf0dev approved these changes

2024-03-28 16:50 UTC, merged