Migrate `autoConfirmFingerPrints` to `StateProvider`
bitwarden/clients pull request #8337
Opened 2024-03-14 22:27 UTC by addisonbeck

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-03-18 13:21 UTC, MGibson1 requested changes
Looks good, just a few variable name nits. The service parameter name is one that could potentially be annoying down the road with repo searches

2024-03-18 18:21 UTC, addisonbeck commented on libs/common/src/admin-console/abstractions/organization-management-preferences/organization-management-preferences.service.ts
> +export class OrganizationManagementPreference<T> {
✅ Implement  as suggested on https://github.com/bitwarden/clients/pull/8337/commits/e6eeb2b7545654630c37c21b5e9199c8c3a94d48

2024-03-18 18:21 UTC, addisonbeck commented on apps/web/src/app/admin-console/organizations/manage/user-confirm.component.ts
> +      await this.organizationManagementPreferenceService.autoConfirmFingerPrints.update(true);
✅ Implemented from suggestion on https://github.com/bitwarden/clients/pull/8337/commits/d426201777eb1967e57d7b9275fcdac2ec7a031e

2024-03-18 18:21 UTC, addisonbeck commented on apps/web/src/app/admin-console/organizations/manage/user-confirm.component.ts
> +    private organizationManagementPreferenceService: OrganizationManagementPreferencesService,
✅ Implemented from suggestion on https://github.com/bitwarden/clients/pull/8337/commits/9480c27c7874417ef985d1fefc652c05a186b2d6

2024-03-18 18:32 UTC, MGibson1 submitted a review, later dismissed

2024-03-19 03:47 UTC, eliykat submitted a review, later dismissed
Cool way of managing disparate pieces of state through a single service 👏

2024-03-19 16:12 UTC, ike-kottlowski submitted a review, later dismissed
Auth changes are good.

2024-03-19 17:40 UTC, ike-kottlowski approved these changes

2024-03-19 21:34 UTC, eliykat approved these changes

2024-03-19 21:37 UTC, MGibson1 approved these changes

2024-03-19 21:37 UTC, merged