Pm 5023 migrate payment component
bitwarden/clients pull request #8345
Opened 2024-03-15 11:10 UTC by vinith-kovan

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [X] Other
```

## Objective

Migrate the payment component to use the Component Library

## Code changes

- payment.component.ts:  Updated the form, inputs and select options to use the equivalent components from the Component Library.
- payment.component.html: Incorporated a nested form group for bank details and passed these details into the createPaymentToken function.

## Screenshots

Before Migration:
Org billing subscription -
![image](https://github.com/bitwarden/clients/assets/156108204/4e79007d-f001-4c36-87a1-85967648c552)
Payment Method -
![image](https://github.com/bitwarden/clients/assets/156108204/17d46944-9e44-4ea0-aa73-906dc9d42970)

After Migration:
Org billing subscription -
![image](https://github.com/bitwarden/clients/assets/156108204/e8c0e989-7645-4308-a7de-d2dca735658a)
![image](https://github.com/bitwarden/clients/assets/156108204/c361b30b-749d-4da0-a0ac-fd8c4603953f)
Payment Method -
![image](https://github.com/bitwarden/clients/assets/156108204/5f81dab7-c2b7-4533-a241-278668f38650)

2024-03-19 00:33 UTC, willmartian requested changes

2024-03-19 00:33 UTC, willmartian commented on apps/web/src/app/billing/shared/payment.component.html
Problem: non-Tailwind classes

- form-control 
- stripe-form-control
- ml-auto
- d-flex

2024-03-19 00:33 UTC, willmartian commented on apps/web/src/app/billing/shared/payment.component.ts
> +    });
Unintended breaking change: Before, the component input `method` would reactively update the input it was bound to. Now, if `method` changes after init, `paymentForm.method` will not reflect it the updated value. I recommend using a setter on `this.method`

2024-03-19 01:29 UTC, willmartian commented on apps/web/src/app/billing/shared/payment.component.html
@bitwarden/team-billing-dev Do you know if it feasible/possible to use the CL with Stripe form fields? It looks like these fields are dynamically created by Stripe elements. 

Should we migrate the references to `.stripe-form-control` to use Tailwind now, or should we hold off and create another ticket to use the CL form inputs proper and let the billing team handle that?

2024-03-20 13:42 UTC, vinith-kovan commented on apps/web/src/app/billing/shared/payment.component.html
> +      <div [ngClass]="trialFlow ? 'tw-col-span-5' : 'tw-col-span-4'">
No

2024-03-20 20:39 UTC, willmartian commented on apps/web/src/app/billing/shared/payment.component.ts
> +    });
[90ea3a1](https://github.com/bitwarden/clients/pull/8345/commits/90ea3a14b649f3726fd7131d475ae963ee05d695) does not fix this issue. 

In main, whenever `@Input() method` is updated, the input's value would also change because of `[(ngModel)]="method"`.

Now, whenever `@Input() method` changes, nothing happens. The form control value is never updated. This is a breaking change.

This can be remedied by making `@Input() method` a setter that updates the underlying form control: https://angular.io/guide/component-interaction#intercept-input-property-changes-with-a-setter

2024-05-08 17:44 UTC, amorask-bitwarden commented on apps/web/src/app/billing/shared/payment.component.html
@willmartian I'm not sure I understand the question. Do you mean is it worth it to try using Tailwind to style the Stripe Elements created by their SDK?

2024-06-03 23:27 UTC, willmartian commented on apps/web/src/app/billing/shared/payment.component.html
I talked with @amorask-bitwarden and we will leave the various Stripe classes (`.stripe-form-control`) in for now and address in a future ticket.

2024-06-06 13:09 UTC, willmartian approved these changes

2024-06-06 13:59 UTC, merged