PM-5263  - TokenService needs to actually use secure storage
bitwarden/clients pull request #8356
Opened 2024-03-15 19:31 UTC by JaredSnider-Bitwarden

## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-03-15 20:34 UTC, justindbaur requested changes

2024-03-15 20:34 UTC, justindbaur commented on apps/desktop/src/main.ts
> +    // Note: secure storage service is not available and should be called in the main background process.
```suggestion
    // Note: secure storage service is not available and should not be called in the main background process.
```

2024-03-15 20:36 UTC, justindbaur approved these changes

2024-03-15 21:05 UTC, merged

2024-03-16 23:46 UTC, BetoMees commented
this was broke the login on desktop (windows)

2024-03-17 00:33 UTC, JaredSnider-Bitwarden commented
> This has broken the login functionality on desktop (Windows).

@BetoMees , what error are you seeing on login so I can confirm the behavior I'm seeing is what you saw?

2024-03-17 02:59 UTC, BetoMees commented
I'm not receiving any error, the token response is working just fine but doesn't login in.
Usually the application initialize without the need to enter the password but now is requesting.
I'm looking ass well and any news I'll comment here

2024-03-17 19:24 UTC, BetoMees commented
Here is the fix #8364