[PM-2870] [PM-2865] Accessibility updates: add labels to buttons & form checkboxes
bitwarden/clients pull request #8358
Opened 2024-03-15 20:28 UTC by merissaacosta

## Type of change

- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

[PM-2870](https://bitwarden.atlassian.net/browse/PM-2870)
[PM-2865](https://bitwarden.atlassian.net/browse/PM-2865)

Fixes two accessibility issues that were found by UofI WCAG.
1. Organization menu in the filter side bar didn't have a label associated with it.
2. Checkbox next to cipher did not have a label.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-03-21 20:57 UTC, shane-melton requested changes
Thanks for fixing these! We do need to i18n them though with the `i18n` pipe and updates to `messages.json` as necessary.

2024-03-26 17:17 UTC, cagonzalezcs commented on apps/web/src/app/vault/individual-vault/vault-filter/components/organization-options.component.html
> +    aria-label="Toggle Organization Menu"
We likely should be translating these `aria-label` string values.

2024-04-02 17:14 UTC, shane-melton submitted a review, later dismissed
Looks good!

2024-04-04 18:53 UTC, cagonzalezcs commented on apps/web/src/app/vault/individual-vault/vault-filter/components/organization-options.component.html
> +        <span id="enrollAccountRecovery">{{ "enrollAccountRecovery" | i18n }}</span>
So this isn't entirely wrong... but you likely don't need to do this...

Screen readers by default SHOULD read text content within a DOM Node.... adding `aria-label` or aria-labelledby` shouldn't be necessary if you're not looking to expand on the inner text of a button (or other DOM element)

You'd want to use an `aria-label` to expand on context... ie. something like...

```
<button type="submit" class="submit-login-form-btn" aria-label="Submit your account details">Submit</button>
```

Keep in mind the triviality of that example, but in general you want to avoid usage of ARIA properties if the inline text is effectively conveying meaning to the screen reader user.

2024-04-04 18:54 UTC, cagonzalezcs commented on apps/web/src/app/vault/individual-vault/vault-filter/components/organization-options.component.html
> +        <span id="enrollAccountRecovery">{{ "enrollAccountRecovery" | i18n }}</span>
Also, when in doubt if something is being read out loud, go ahead and spin up a screen reader such as VoiceOver (Mac) or NVDA (Windows). 

The best way to see if text is being conveyed to users is to test it directly by that kind of software.

2024-04-04 20:03 UTC, merissaacosta commented on apps/web/src/app/vault/individual-vault/vault-filter/components/organization-options.component.html
> +        <span id="enrollAccountRecovery">{{ "enrollAccountRecovery" | i18n }}</span>
@cagonzalezcs thank you! i thought so too, but i remember it not working correctly before I added the new labels in however i just tested again and it's still not reading the labels. going to spend more time testing that out. thanks!

2024-04-08 07:33 UTC, gbubemismith submitted a review, later dismissed

2024-04-09 21:41 UTC, merissaacosta commented on apps/web/src/app/vault/individual-vault/vault-filter/components/organization-options.component.html
> +        <span id="enrollAccountRecovery">{{ "enrollAccountRecovery" | i18n }}</span>
ok youre right! it seems like it was reading the text inside of the button before i added the new aria labels- i probably got confused with the toggle button.  I'm okay with it doing that since the buttons are self explanatory. thanks so much! im taking these out

2024-04-15 19:49 UTC, cagonzalezcs submitted a review, later dismissed

2024-04-15 22:31 UTC, gbubemismith submitted a review, later dismissed

2024-04-19 13:50 UTC, cagonzalezcs approved these changes

2024-04-19 13:54 UTC, Jingo88 approved these changes

2024-04-19 14:09 UTC, merged