[PM-5574] sends state provider
bitwarden/clients pull request #8373
Opened 2024-03-18 16:20 UTC by ttalty

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Implement the state provider for Send data. 

## Code changes

- **libs/angular/src/services/jslib-services.module.ts:** Adding send state provider
- **libs/common/src/platform/state/state-definitions.ts:** New send state definitions for disk and memory
- **libs/common/src/tools/send/services/key-definitions.ts: Key definitions for encrypted/decrypted sends
- **libs/common/src/tools/send/services/key-definitions.spec.ts:** Test cases for the key definitions
- **libs/common/src/tools/send/services/send-state.provider.abstraction.ts:** Abstraction for send state provider
- **libs/common/src/tools/send/services/send-state.provider.ts:** Implementation of the state provider for sends. Methods for getting and setting both encrypted and decrypted sends for the active user
- **libs/common/src/tools/send/services/send.service.ts:** Send service using the new send state provider and using the active account observables from the account service instead of the state service. 
- **libs/common/src/tools/send/services/send.service.spec.ts:** Modifying test cases to use the send state provider
- **libs/common/src/tools/send/services/send-state.provider.spec.ts:** Test cases for the send state provider
- **libs/common/src/platform/abstractions/state.service.ts:** Removing the methods related to sends from the state service
- **libs/common/src/platform/services/state.service.ts:** Removing send methods
- **libs/common/src/platform/models/domain/account.ts:** Removing the sends data used by the send state

2024-03-27 15:17 UTC, justindbaur requested changes

2024-03-27 15:17 UTC, justindbaur commented on libs/common/src/tools/send/services/send.service.ts
> +    this.accountService.activeAccount$
Hopefully the need for subscribing to this can go away using various other features in state providers like `UserKeyDefinition` and `DerivedState`, or could this make use of `SecretState` @audrey-jensen?

2024-03-27 15:17 UTC, justindbaur commented on libs/common/src/tools/send/services/send.service.ts
>    }
This is what can hopefully go away with `UserKeyDefinition`, you could just need to include `clearOn: ["logout", "lock" ]` (or whichever places this clear method is called from) and then it will take care of deleting this data, then you can just delete this method!

2024-03-28 10:59 UTC, aj-rosado commented on libs/common/src/tools/send/services/send-state.provider.ts
> +    this.activeUserDecryptedState = this.stateProvider.getActive(SEND_USER_DECRYPTED);
Shouldn't we be using the `DerivedState` here?
Is this what you mean about not need to use the `activeAccount$` by using `DerivedState$` @justindbaur ?

2024-03-28 16:53 UTC, justindbaur commented on libs/common/src/tools/send/services/send-state.provider.abstraction.ts
> +  getEncryptedSends: () => Promise<{ [id: string]: SendData }>;
Talked with @djsmith85, we can hold off on this, this is optional feedback.

2024-03-29 20:34 UTC, justindbaur approved these changes
This looks wonderful, thanks for the changes!

2024-04-02 09:41 UTC, aj-rosado commented on apps/browser/src/background/service-factories/send-service.factory.ts
> +  StateProviderInitOptions &
I thin this should be `SendStateProviderInitOptions`

2024-04-02 14:11 UTC, justindbaur approved these changes

2024-04-02 14:11 UTC, aj-rosado approved these changes
Changes are looking great!

2024-04-02 16:39 UTC, merged