[PM-6194] Refactor injection of services in browser services module
bitwarden/clients pull request #8380
Opened 2024-03-19 00:04 UTC by gbubemismith

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
While working with the team on the browser architecture changes needed to support MV3, we found that there are a number of services that will not be refactored directly for StateProviders, but still need to have provider definitions updated in apps/browser/src/popup/services/services.module.ts 

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-03-19 14:29 UTC, LRNcardozoWDF approved these changes
LGTM!

2024-03-21 18:31 UTC, MGibson1 requested changes
This all looks good, but I think the search service needs a little bit more work to ensure we're handling the indexes correctly.

2024-03-21 18:31 UTC, MGibson1 commented on apps/browser/src/popup/services/services.module.ts
> +    // The current implementation stores the index in memory using the state provider, another consideration is to reindex the ciphers each time it is needed
I think storing is likely the right move. Hard to imagine that deserializing would be slower than rebuilding.

Please be sure to remove this comment before merge.

2024-03-21 18:31 UTC, MGibson1 commented on libs/common/src/services/search.service.ts
> +export const LUNR_SEARCH_INDEX = new KeyDefinition<SerializedLunrIndex>(
Please convert to a `UserKeyDefinition` and include a `clearOn` for `lock`

2024-03-21 18:31 UTC, MGibson1 commented on libs/common/src/services/search.service.ts
>    private index: lunr.Index = null;
**issue**: This should no longer be needed

2024-03-21 18:31 UTC, MGibson1 commented on libs/common/src/services/search.service.ts
>    private indexing = false;
**issue**: This probably needs to be a synced value. You don't want _any_ of the search services indexing if any of them are.

2024-03-21 18:31 UTC, MGibson1 commented on libs/common/src/services/search.service.ts
>    indexedEntityId?: string = null;
**issue**: This needs to be synced/included along with your user-level index in some way. You are now storing one index per user rather than exactly one per service. This is the way you can track that

2024-04-02 18:33 UTC, audrey-jensen requested changes
⛏️ nitpick (requested change)
👍🏻 kudos!
♻️ acknowledged tech debt (no change needed)

2024-04-02 18:33 UTC, audrey-jensen commented on libs/angular/src/tools/send/send.component.ts
> +  // searchText: string;
⛏️ This commented code should be deleted.

2024-04-02 18:33 UTC, audrey-jensen commented on libs/angular/src/tools/send/send.component.ts
> +  }
👍🏻 This is a pretty clever way to limit the scope of your change in the component.

♻️ In the long run, this needs to be migrated to reactive controls, so that the subjects and subscriptions can be directly wired to one another.

2024-04-02 21:11 UTC, gbubemismith commented on libs/angular/src/tools/send/send.component.ts
> +  }
Thanks. I agree with this as well.

2024-04-03 13:01 UTC, audrey-jensen submitted a review, later dismissed

2024-04-03 13:12 UTC, MGibson1 approved these changes

2024-04-03 13:12 UTC, MGibson1 commented on libs/common/src/services/search.service.ts
> +    deserializer: (obj: Jsonify<SerializedLunrIndex>) => obj,
**nit**: why not actually deserialize here?

2024-04-03 13:24 UTC, LRNcardozoWDF submitted a review, later dismissed

2024-04-03 13:47 UTC, cturnbull-bitwarden submitted a review, later dismissed

2024-04-03 15:12 UTC, gbubemismith commented on libs/common/src/services/search.service.ts
> +    deserializer: (obj: Jsonify<SerializedLunrIndex>) => obj,
I didn't deserialize here cause lunr.js doesn't expose a serialized type (they use object), and I wanted to maintain a known type when storing the search index in state, which led to creating the search index shape SerializedLunrIndex

2024-04-04 03:35 UTC, eliykat requested changes

2024-04-04 03:35 UTC, eliykat commented on apps/web/src/app/admin-console/common/base.people.component.ts
A lot of the boilerplate here is unnecessary - the private property, getter, setter, onDestroy$, etc. I don't think it's the right way to introduce observables into this component. Here's what I recommend:

1. use a `FormControl` for the search input
2. transform the value of that control to get the `isSearching` value:

```ts
isSearching$ = this.searchTextInput.valueChanges.pipe(concatMap(searchText => 
  this.searchService.isSearchable(searchText)));
```

3. similarly, transform the value of `isSearching$` to get `isPaging`:

```ts
isPaging$ = this.isSearching$.pipe(map(val => 
  // isPaging logic goes here
));
```

4. use the async pipe in templates where required to get these values.

That said, I know this isn't your code and isn't your focus (you're just trying to fix search service), so let me know if you'd like to discuss further or if you want AC Team to contribute any code here.

The same pattern would apply in the other components here.

2024-04-04 15:25 UTC, audrey-jensen commented on apps/web/src/app/admin-console/common/base.people.component.ts
Just want to stress that this isn't necessary for sends. It needs to be updated to use CL components, so as much as this isn't fully reactive, that's ok coz we're going to tackle that tech debt later anyway.

2024-04-04 22:26 UTC, eliykat commented on apps/web/src/app/admin-console/common/base.people.component.ts
After sleeping on it, I think we'll take the same approach for AC Team and create our own follow-up ticket for these changes. Thanks!

2024-04-04 22:26 UTC, eliykat submitted a review, later dismissed

2024-04-08 14:23 UTC, LRNcardozoWDF approved these changes

2024-04-08 15:50 UTC, audrey-jensen approved these changes
📝 note

2024-04-08 15:50 UTC, audrey-jensen commented on apps/browser/src/vault/popup/components/action-buttons.component.ts
> +import { TotpService as TotpServiceAbstraction } from "@bitwarden/common/vault/abstractions/totp.service";
📝 There's a [new naming convention for abstractions](https://contributing.bitwarden.com/architecture/clients/presentation/angular#abstract--default-implementations). You need not implement it here, but I just wanted to point it out. 😄

2024-04-08 15:54 UTC, gbubemismith commented on apps/browser/src/vault/popup/components/action-buttons.component.ts
> +import { TotpService as TotpServiceAbstraction } from "@bitwarden/common/vault/abstractions/totp.service";
okay thanks

2024-04-08 18:01 UTC, LRNcardozoWDF approved these changes

2024-04-08 23:29 UTC, eliykat approved these changes

2024-04-09 12:27 UTC, MGibson1 approved these changes
I don't want to block, but in the future please do not alias abstraction (naming convention decisions [documented here](https://contributing.bitwarden.com/architecture/clients/presentation/angular#abstract--default-implementations), but perhaps we need to make this explicit).

The thinking is that since the abstractions are the most commonly reference class, they should be the simplest representation, where concrete implementations are prefixed with `Default`.

2024-04-09 12:37 UTC, cturnbull-bitwarden approved these changes

2024-04-10 13:02 UTC, merged