PM-5019 Migrate Adjust Payment component
bitwarden/clients pull request #8383
Opened 2024-03-19 12:33 UTC by KiruthigaManivannan

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other
```

## Objective

Migrate the Adjust Payment component to use the component library.

## Code changes

- **adjust-payment-dialog.component.html:** Updated Form, Cards to use the equivalent components from the Component Library. Cards are updated to Dialog component from component library.
- **adjust-payment-dialog.component.ts:** Added FormGroup. Used Dialog service to create a dialog open method. Dialog data interface and dialog result const is created.
- **payment-method.component.html:** Removed the app-adjust-payment selector and properties bound to it.
- **payment-method.component.ts:** Adjust payment dialog is opened during the onclick of changePayment button. Final result of the dialog is captured and loaded again

## Screenshots
-**Click on Change Payment Method button**
Before:
![image](https://github.com/bitwarden/clients/assets/162679756/a92726a6-5085-44a2-a00e-0f0b3d9c6e4c)
After:
![image](https://github.com/bitwarden/clients/assets/162679756/66b3b295-0d8c-4f30-8498-64ade5bdbcb0)

-**Select credit card option and fill in details
Before:
![image](https://github.com/bitwarden/clients/assets/162679756/114a7f30-7ff0-431a-bb32-4521f0284422)
![image](https://github.com/bitwarden/clients/assets/162679756/10ccaf26-2171-4378-a1a1-62b1afef3cbd)

After:
![image](https://github.com/bitwarden/clients/assets/162679756/37167b65-3b1a-4c87-b2ac-9a5a5a3071ee)
![image](https://github.com/bitwarden/clients/assets/162679756/47aa485c-7b2d-4939-a4da-5f82b89e518b)

-**Select paypal option and fill in details
Before:
![image](https://github.com/bitwarden/clients/assets/162679756/f56c9e57-1377-49b8-beae-d6a79a88e28b)
After:
![image](https://github.com/bitwarden/clients/assets/162679756/876f80ea-918e-4057-bd94-a8f85297ecc7)

2024-03-19 21:54 UTC, willmartian requested changes

2024-03-19 21:54 UTC, willmartian commented on apps/web/src/app/billing/shared/payment-method.component.html
>    <ng-container *ngIf="!firstLoaded && loading">
These diffs are unrelated to the PR

2024-03-19 21:54 UTC, willmartian commented on apps/web/src/app/billing/shared/adjust-payment-dialog.component.ts
> +    this.dialogRef.close(AdjustPaymentDialogResult.Cancelled);
We never call this method anywhere. Either call it with the cancel button, or pass the close value to `bitDialogClose`

2024-03-19 22:14 UTC, sukhleenb approved these changes

2024-03-20 09:55 UTC, KiruthigaManivannan commented on apps/web/src/app/billing/shared/payment-method.component.html
>    <ng-container *ngIf="!firstLoaded && loading">
Sorry @willmartian For testing purpose i added a line there. Only after I committed the i understood that i need to remove the test code. So After a commit i removed the code thats why it is showing like line is changed.

2024-03-20 19:17 UTC, willmartian commented on apps/web/src/app/billing/shared/payment-method.component.html
>    <ng-container *ngIf="!firstLoaded && loading">
No worries. Could you revert the change?

2024-03-20 19:21 UTC, willmartian requested changes
Looks good! Just one small change still needed here: https://github.com/bitwarden/clients/pull/8383/files#r1532702398

2024-03-25 15:23 UTC, willmartian approved these changes

2024-03-29 18:17 UTC, cturnbull-bitwarden approved these changes

2024-04-16 19:38 UTC, merged