[PM-5571] Migrate enableDDG to state provider framework
bitwarden/clients pull request #8384
Opened 2024-03-19 12:36 UTC by Hinton

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Migrate enableDuckDuckGo to state provider framework.

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-03-19 12:44 UTC, Hinton commented on apps/desktop/src/main/native-messaging.main.ts
> -  async listen() {
This method didn't need to be async, and removing it let us get rid of the eslint warnings when calling.

2024-03-19 21:44 UTC, cagonzalezcs submitted a review, later dismissed
Looks clean and straightforward from my side :)

2024-03-20 13:01 UTC, jprusik requested changes

2024-03-20 13:01 UTC, jprusik commented on apps/desktop/src/autofill/services/desktop-autofill-settings.service.ts
The Duck Duck Go integration doesn't feel like an "autofill setting" to me. Could we make this service "DesktopSettings" (to represent a service whose concern is client-specific settings) instead?

I have no issue with this living as a Autofill team ownership/concern though, if that's desired.

2024-03-20 13:19 UTC, jprusik commented on apps/desktop/src/autofill/services/desktop-autofill-settings.service.ts
Thinking on this more - this probably belongs in a `DesktopIntegrationsService` with `enableBrowserIntegration` and `enableBrowserIntegrationFingerprint`.

2024-03-20 13:22 UTC, jprusik approved these changes
See previous feedback - will follow up offline. Otherwise LGTM

2024-03-20 21:48 UTC, MGibson1 requested changes

2024-03-20 21:48 UTC, MGibson1 commented on apps/desktop/src/app/accounts/settings.component.ts
> -        await this.stateService.getEnableDuckDuckGoBrowserIntegration(),
**issue**: Please remove this and the set methods from state service and the value from global state

2024-03-21 16:49 UTC, jprusik submitted a review, later dismissed

2024-03-21 17:49 UTC, jprusik submitted a review, later dismissed

2024-03-22 12:17 UTC, MGibson1 approved these changes

2024-03-22 16:05 UTC, cagonzalezcs approved these changes

2024-03-22 17:32 UTC, merged