[PM 5007] migrate premium component
bitwarden/clients pull request #8387
Opened 2024-03-19 14:02 UTC by vinith-kovan

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [X] Other
```

## Objective

Migrate the Adjust Premium component to use the component library.

## Code changes

premium-component.html:  Updated the form, inputs, and select options to use the equivalent components from the Component Library.
premium-component.ts: Added from group to capture the form values

## Screenshots
After Migration:

![image](https://github.com/bitwarden/clients/assets/156108204/f3d34d39-bf97-4c97-b959-2056055dc2e9)
![image](https://github.com/bitwarden/clients/assets/156108204/72fb6be9-b0a5-4c51-a9a6-e43b33a68f0f)
![image](https://github.com/bitwarden/clients/assets/156108204/9e5e4b91-b016-41dc-ba9c-fae040c6f70b)

Before Migration:

![image](https://github.com/bitwarden/clients/assets/156108204/90b8956e-7467-4d39-b6bb-44a83ed640e1)
![image](https://github.com/bitwarden/clients/assets/156108204/bac10c81-d81d-4705-a111-7fc38f44438d)

2024-03-19 21:01 UTC, willmartian requested changes

2024-03-19 21:01 UTC, willmartian commented on apps/web/src/app/billing/individual/premium.component.ts
> +  };
Similar to our discussion in [this comment](https://github.com/bitwarden/clients/pull/8321#discussion_r1529454435), we can remove the try catch block because it isn't doing anything.

2024-03-20 21:28 UTC, willmartian requested changes
I'm not sure what is going on here. Is this the intended UI?

<img width="559" alt="image" src="https://github.com/bitwarden/clients/assets/17113462/a7fcfc76-15bb-4877-a808-bbd530aea0a9">

2024-03-25 05:36 UTC, vinith-kovan commented
> I'm not sure what is going on here. Is this the intended UI?
> 
> <img alt="image" width="559" src="https://private-user-images.githubusercontent.com/17113462/314681506-a7fcfc76-15bb-4877-a808-bbd530aea0a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTE4MzcsIm5iZiI6MTcxMTA5MTUzNywicGF0aCI6Ii8xNzExMzQ2Mi8zMTQ2ODE1MDYtYTdmY2ZjNzYtMTViYi00ODc3LWE4MDgtYmJkNTMwYWVhMGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA3MTIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1OGUzNjYxZDk1MjEyMmYxZGJhMjM5ZTcyZTVmNGRiNWQwNjM0ZjUzMTlkZTVkMjI1YTliNmMxZWJlZTkzN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.49Y4qXAoY9QFO7q1Ewy4IE_4UVIvI9WZGaqlSNP-eLY">

After reviewing the available resources, it appears that there isn't a specific Component library explicitly mentioned for file uploads in the documentation. Without a predefined UI mockup, I attempted to design the UI based on my understanding. However, during further exploration, I came across a component named sm-import.html that seemed relevant to handling file uploads. So I have updated the Code as follows in that file.

2024-03-25 18:34 UTC, willmartian requested changes

2024-03-25 18:34 UTC, willmartian commented on apps/web/src/app/billing/individual/premium.component.html
> +      <bit-hint>{{ "licenseFileDesc" | i18n: "bitwarden_premium_license.json" }}</bit-hint>
1. It looks like we are using the wrong label here; it was `"licenseFile"` now it is `"additionalStorageGb"`. 
2. Could you upload a screenshot that captures this change?

2024-03-28 04:26 UTC, vinith-kovan commented on apps/web/src/app/billing/individual/premium.component.html
> +      <bit-hint>{{ "licenseFileDesc" | i18n: "bitwarden_premium_license.json" }}</bit-hint>
It is fixed and also added a screenshot.

2024-05-08 17:30 UTC, amorask-bitwarden approved these changes

2024-05-09 15:16 UTC, merged