[AC-2320] Update canEditAnyCollection logic for Flexible Collections v1
bitwarden/clients pull request #8394
Opened 2024-03-20 01:18 UTC by eliykat

* Return value depends on collection management setting, wrapped behind the v1 feature flag

* Update calling locations

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-03-20 01:58 UTC, eliykat commented on libs/common/src/admin-console/models/domain/organization.ts
>      }
I can see that `org.FlexibleCollections` is checked in some calling locations, but it seems safer to have it here as well.
I also decoupled these methods to make them easier to reason about.

2024-04-01 20:20 UTC, vincentsalucci approved these changes
Reviewed `organization.ts` file only. 👍

2024-04-02 19:04 UTC, shane-melton requested changes
This looks really good, thank you! I did not a few spots where we could be using the `canEditAllCiphers()` helper instead of `canEditAnyCollection()`. You should be able to just swap them out, but if you want to avoid doing that in this PR that should be fine, we'll just have to update them again with the provider work.

Speaking of provider work 
> However, once provider access is restricted, these will diverge (providers can edit all collections but not all items). @shane-melton have you looked into this when restricting provider access? e.g. the bulk-delete component is deleting ciphers, but it checks canEditAnyCollection.

Yep, I've updated the `canEditAllCiphers()` helper in [this PR](https://github.com/bitwarden/clients/pull/8265/commits/c4fc654257d533eb7269b169e76fa59e63bcadc8). But, it does look like I missed a few spots where I need to swap out  the existing references to `canEditAnyCollection` when it comes to dealing with the cipher contents (most of my review comments here highlight those spots).

2024-04-03 04:34 UTC, eliykat commented on apps/web/src/app/vault/individual-vault/bulk-action-dialogs/bulk-delete-dialog/bulk-delete-dialog.component.ts
> +import { ConfigServiceAbstraction } from "@bitwarden/common/platform/abstractions/config/config.service.abstraction";
Great point thank you, I did immediately hit errors here and this pointed me in the right direction.

2024-04-03 04:55 UTC, eliykat commented on apps/web/src/app/vault/individual-vault/bulk-action-dialogs/bulk-delete-dialog/bulk-delete-dialog.component.ts
> +        !this.organization.canEditAnyCollection(flexibleCollectionsV1Enabled)
I had treated this as out of scope, but given that you've reviewed and agree, I've updated the uses you've identified here.

2024-04-03 05:05 UTC, eliykat commented on apps/web/src/app/vault/org-vault/attachments.component.ts
>    }
@shane-melton this might need to be a followup ticket for vault: it seems that only admins could fix old attachments, but now that admins have restricted access, very few users are going to see this message. I would've thought it would only matter that they can edit _this_ cipher, but I haven't looked into it.

2024-04-03 23:45 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/bulk-action-dialogs/bulk-delete-dialog/bulk-delete-dialog.component.ts
> +        !this.organization.canEditAnyCollection(flexibleCollectionsV1Enabled)
Perfect, thank you!

2024-04-03 23:46 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/attachments.component.ts
>    }
Thanks for the heads up! I'll create a ticket to follow up / look into it more closely.

2024-04-03 23:46 UTC, shane-melton approved these changes
This is looking good to me! Thanks for updating all those calls to `canEditAllCiphers()`!

2024-04-04 03:48 UTC, merged