PM-5022 Migrate Payment Method component
bitwarden/clients pull request #8397
Opened 2024-03-20 06:50 UTC by KiruthigaManivannan

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other
```

## Objective

Migrate the Payment Method component to use the component library.

## Code changes

- **payment-method.component.html:** Updated Form. Heading and paragraph tags are updated with its equivalent library components.
- **payment-method.component.ts:**Added FormGroup. Async methods.

## Screenshots

- **Payment method screen for Organization:**
Before:
![image](https://github.com/bitwarden/clients/assets/162679756/3b7e3753-3652-47ee-add2-0b9e0a067a5b)
After:
![image](https://github.com/bitwarden/clients/assets/162679756/2d9fa73b-6b98-44cc-9384-3290fcab806e)

- **Payment method screen for Individual:**
Before:
![image](https://github.com/bitwarden/clients/assets/162679756/20df2634-f398-4df4-9622-b84153888bc7)
After:
![image](https://github.com/bitwarden/clients/assets/162679756/9fa6db82-89c8-48d5-ba55-8734de40264b)

2024-03-20 23:18 UTC, willmartian requested changes

2024-03-20 23:18 UTC, willmartian commented on apps/web/src/app/billing/shared/payment-method.component.html
Many of the CSS changes in this file are Tailwind --> Tailwind. Why were these changes made?

2024-03-22 14:11 UTC, KiruthigaManivannan commented on apps/web/src/app/billing/shared/payment-method.component.html
> -  </div>
@willmartian  Didn't remove the comment intentionally, I just removed the div tag. So unknowingly i removed it. But added it now.

2024-03-22 14:13 UTC, KiruthigaManivannan commented on apps/web/src/app/billing/shared/payment-method.component.html
@willmartian I have reverted some changes , if still you find any issue please  comment in which line i have made mistake.

2024-03-25 18:48 UTC, willmartian requested changes

2024-03-25 18:48 UTC, willmartian commented on apps/web/src/app/billing/shared/payment-method.component.html
> +            <bit-form-field class="tw-w-1/5 tw-h-12">
Why was this change made? 

`tw-mr-2 tw-w-40` --> `tw-w-1/5 tw-h-12`

2024-03-25 18:48 UTC, willmartian commented on apps/web/src/app/billing/shared/payment-method.component.html
>            class="bwi bwi-spinner bwi-spin text-muted"
Problem: non-Tailwind class `text-muted`

2024-03-25 18:48 UTC, willmartian commented on apps/web/src/app/billing/shared/payment-method.component.html
> +            <bit-form-field class="tw-w-1/5 tw-h-12">
Why was this change made? 

`tw-mr-2 tw-w-40` --> `tw-w-1/5 tw-h-12`

2024-03-25 18:48 UTC, willmartian commented on apps/web/src/app/billing/shared/payment-method.component.html
> +              class="tw-w-1/4 tw-h-10 tw-my-6"
Why were these styles added?

2024-03-28 03:54 UTC, KiruthigaManivannan commented on apps/web/src/app/billing/shared/payment-method.component.html
> +              class="tw-w-1/4 tw-h-10 tw-my-6"
@willmartian  If i dont add this class to Verify button , I get the button like below

![Uploading image.png…]()

2024-05-08 17:34 UTC, amorask-bitwarden submitted a review, later dismissed

2024-05-13 14:10 UTC, cyprain-okeke approved these changes

2024-06-04 13:33 UTC, amorask-bitwarden approved these changes

2024-06-10 23:52 UTC, willmartian commented on apps/web/src/app/billing/shared/payment-method.component.html
> +              class="tw-w-1/4 tw-h-10 tw-my-6"
That is happening because flex containers have a default value of `align-items: stretch` [(docs)](https://developer.mozilla.org/en-US/docs/Web/CSS/align-items)

You should be able to be able to remove these classes and place `tw-items-center` on the flex container to achieve the desired look. 

(You can also remove the margin on the other flex siblings, since you are already handling that with `tw-gap-2`.)

2024-06-11 00:00 UTC, willmartian submitted a review, later dismissed
Please see my comment [here.](https://github.com/bitwarden/clients/pull/8397#discussion_r1633988191)

Also, web is failing to build due to errors occurring [here.](https://github.com/bitwarden/clients/pull/8397/files#diff-60ab672ffb5de77de4d267e2951e92420e313906f928ada9bfa077460c197d3bR91-R102) It looks like they were introduced in this merge commit: 1bcb33ed5be54509a89199dab028886d213cfaeb

2024-06-19 14:33 UTC, KiruthigaManivannan commented
@cyprain-okeke Please approve this PR

2024-06-21 15:14 UTC, cyprain-okeke commented on apps/web/src/app/billing/shared/payment-method.component.html
> +        <app-callout
change the app-callout to bit-callout base on this [change](https://github.com/bitwarden/clients/pull/9710#event-13229533536)

2024-06-26 13:25 UTC, cyprain-okeke approved these changes
Looks good

2024-06-26 13:27 UTC, amorask-bitwarden approved these changes

2024-06-26 14:06 UTC, merged