[AC-1121] Collections Add Access filter and badge
bitwarden/clients pull request #8404
Opened 2024-03-20 16:11 UTC by Jingo88

```
- [ ] Bug fix
- [ X ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

- If a collection does not have any members or groups with `Can Manage` access (revoked users do not count) that collection will show an `Add Access` badge. 
- A toggle will appear at the top to filter between `All` and `Add Access` collections
- The user will be able to 

## Code changes

* `vault collection row html` - add badge with ngIf
* `collection admin view` - added methods to return a list of groups and users with can manage access
* `vault component html` - `bit-toggle-group` added for Add Access
* `vault.component org-vault` - When collections$ is being determined we will check for `orgRevokedUsers`, `groupsCanManage`, and `usersCanManage` and apply the badge to the appropriate collection as well as turning on the toggle group if needed

## Screen Recording

https://github.com/bitwarden/clients/assets/8302660/df31b53f-a580-471b-870d-2dae9d736b3f

2024-03-21 19:02 UTC, LRNcardozoWDF submitted a review, later dismissed
LGTM!

2024-04-04 19:15 UTC, cagonzalezcs requested changes

2024-04-04 19:15 UTC, cagonzalezcs commented on apps/browser/src/autofill/overlay/pages/list/autofill-overlay-list.ts
> -
This removal shouldn't be happening as a part of your merge into `main`. These two lines are expected to be present based on a fix merged into `main` earlier this week.

2024-04-04 19:15 UTC, cagonzalezcs commented on apps/browser/src/autofill/overlay/pages/list/autofill-overlay-list.ts
> -
Please review https://github.com/bitwarden/clients/pull/8601 and adjust your changes for these "overlay" related files accordingly.

2024-04-04 19:21 UTC, Jingo88 commented on apps/browser/src/autofill/overlay/pages/list/autofill-overlay-list.ts
> -
yeah sry please ignore this latest comment. I accidently pushed unwanted changes up. reverting now

2024-04-04 19:23 UTC, cagonzalezcs approved these changes

2024-04-04 19:23 UTC, cagonzalezcs commented on apps/browser/src/autofill/overlay/pages/list/autofill-overlay-list.ts
> -
Ah ok, no worries. Reverted my block on the PR :)

2024-04-08 18:23 UTC, LRNcardozoWDF submitted a review, later dismissed

2024-04-15 13:18 UTC, LRNcardozoWDF approved these changes

2024-04-19 13:20 UTC, LRNcardozoWDF submitted a review, later dismissed

2024-04-23 08:25 UTC, LRNcardozoWDF submitted a review, later dismissed

2024-05-01 09:53 UTC, LRNcardozoWDF submitted a review, later dismissed

2024-05-03 14:35 UTC, LRNcardozoWDF approved these changes

2024-05-07 15:02 UTC, merged