[AC-2296] Use SafeProvider in browser services module
bitwarden/clients pull request #8418
Opened 2024-03-21 06:38 UTC by eliykat

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Extend #8206 to the browser services module.

## Code changes

- `services.module.ts` - add safeProvider, with some massaging to make it work. Make sure to review this with whitespace hidden, there should be no substantive changes but someone else should check it.
- `unauth-guard.service.ts` - remove Angular injectable decorator given that it is in the providers array, safeProvider makes this an either/or proposition
- `safe-provider.ts` -
  -  unify the semi-duplicate types (e.g. `useFactoryWithClass`, `useFactoryWithToken`) with a new helper type, `ProviderInstanceType`. This provides a single way to get the underlying instance type of the provider, regardless of whether it uses an injection token, abstract class, or non-abstract class. I think this really cleans up this file and makes the "safe" types much more flexible
  - `useExisting` and `useClass` now support a `SafeInjectionToken` - reflecting how browser's dependencies are configured
- `jslib-services.module.ts` - some minor changes for consistency

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-03-21 12:41 UTC, MGibson1 requested changes

2024-03-21 12:41 UTC, MGibson1 commented on apps/browser/src/auth/popup/services/unauth-guard.service.ts
> -@Injectable()
I think in general `@Injectable` should be the preferred approach. What's more is I can't find any usage of this directly in the angular lib or in the browser code itself. It all seems switched over to `unauthGuardFn`

2024-03-21 12:41 UTC, MGibson1 commented on apps/browser/src/popup/services/services.module.ts
> +    deps: [ConsoleLogService, I18nServiceAbstraction],
Why is this using a concrete object instead of the abstract?

2024-03-21 12:41 UTC, MGibson1 commented on apps/browser/src/popup/services/services.module.ts
> -      provide: SendService,
I don't see a provider for `SendService` anymore

2024-03-21 12:41 UTC, MGibson1 commented on libs/angular/src/platform/utils/safe-provider.ts
nice

2024-03-21 21:53 UTC, eliykat commented on apps/browser/src/auth/popup/services/unauth-guard.service.ts
> -@Injectable()
It's still used throughout `oss-routing.module.ts`. And the problem with this configuration is that it's included in `services.module.ts` to use the browser subclass:

```ts
{
    provide: BaseUnauthGuardService,
    useClass: UnauthGuardService,
}
```

... but it doesn't have a `deps` array because that's handled by the `@Injectable` decorator. We have no way of handling this conditional via the type system - we can't detect whether a class is decorated or not. So it has to be all or nothing.

As you say, it's temporary because it'll be replaced soon.

2024-03-21 21:55 UTC, eliykat commented on apps/browser/src/popup/services/services.module.ts
> +    deps: [ConsoleLogService, I18nServiceAbstraction],
The class, [PopupSearchService](https://github.com/bitwarden/clients/blob/ac/ac-2296/use-safeprovider-in-browser-services-module/apps/browser/src/popup/services/popup-search.service.ts#L8), requires the concrete implementation, not the abstraction. I don't know why _that_ is, but it means we have to be specific here.

2024-03-21 21:56 UTC, eliykat commented on apps/browser/src/popup/services/services.module.ts
> -      provide: SendService,
It's already covered by `jslib-services.module`: https://github.com/bitwarden/clients/blob/ac/ac-2296/use-safeprovider-in-browser-services-module/libs/angular/src/services/jslib-services.module.ts#L553-L556

I think the assumption was that the `useExisting` had to be repeated here to use the `BrowserSendService` but I don't think that's the case.

2024-03-25 12:14 UTC, MGibson1 commented on apps/browser/src/popup/services/services.module.ts
> +    deps: [ConsoleLogService, I18nServiceAbstraction],
No reason, let's update the offending rather than make it available to everyone and risk more.

2024-03-25 22:26 UTC, eliykat commented on apps/browser/src/popup/services/services.module.ts
> +    deps: [ConsoleLogService, I18nServiceAbstraction],
Done - see https://github.com/bitwarden/clients/pull/8418/commits/4b16b192b0e84b4624f300543ba1ab004b71b8c4.

There were also duplicate imports of `LogService` which I've cleaned up.

2024-03-27 16:37 UTC, MGibson1 approved these changes

2024-03-27 22:22 UTC, MGibson1 approved these changes

2024-03-27 22:28 UTC, rr-bw approved these changes

2024-03-27 22:28 UTC, merged