[PM-5014] Download license component migration
bitwarden/clients pull request #8443
Opened 2024-03-22 08:11 UTC by vinith-kovan

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [X] Other
```

## Objective

Migrate the Download License component to use the component library.

## Code changes
download-license.component.html - Updated the form, inputs, and select options to use the equivalent components from the Component Library and migrated card CSS to use `bit-dialog`.
download-license.component.ts - Added the Form group to capture the input values and added the dialog service.
organization-subscription-cloud.component.html - Removed the `app-download-license` component from html.
organization-subscription-cloud.component.ts - Updated the download license function to call the dialog service.

## Screenshots
After Migration:
![image](https://github.com/bitwarden/clients/assets/156108204/d548483e-b23c-4960-8a3e-1d666b8462c8)

Before Migration:
![image](https://github.com/bitwarden/clients/assets/156108204/a9ffb72f-45af-4b97-9152-6add21d95501)

2024-03-25 19:39 UTC, willmartian requested changes

2024-03-25 19:39 UTC, willmartian commented on apps/web/src/app/billing/organizations/download-license.component.html
> +        <div class="tw-col-span-8">
Was the move from 6 to 8 columns intentional?

2024-03-25 19:39 UTC, willmartian commented on apps/web/src/app/billing/organizations/download-license.component.ts
> +    @Inject(DIALOG_DATA) protected params: any,
1. Don't use `any`
2. Could we use "data" instead of "params"?

2024-03-25 19:39 UTC, willmartian commented on apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts
> +    }
This if block is not necessary.

2024-03-25 19:39 UTC, willmartian commented on apps/web/src/app/billing/organizations/download-license.component.ts
>  export class DownloadLicenseComponent {
1. Update the class and file name to reference this is a dialog: `DownloadLicenceDialogComponent`
2. Dialogs don't need selectors.

2024-03-25 19:39 UTC, willmartian commented on apps/web/src/app/billing/organizations/download-license.component.html
> +        [bitDialogClose]="cancel"
`[bitDialogClose]="cancel"` is incorrect usage. This will close the dialog and pass the `this.close` function to `DialogRef.closed$`.

I think you mean to use `bitAction` here, which will run `this.close` and pass `DownloadLicenseDialogResult.Cancelled`.

2024-03-25 19:39 UTC, willmartian commented on apps/web/src/app/billing/organizations/download-license.component.ts
> +      this.licenseForm.get("installationId").value,
Could we use a local variable for `this.licenseForm.value.installationId`?

2024-04-01 06:49 UTC, vinith-kovan commented on apps/web/src/app/billing/organizations/download-license.component.html
> +        <div class="tw-col-span-8">
Yes, the decision to move from 6 to 8 columns was deliberate. We noticed that with the default size dialog component, using 6 columns made the input box appear insufficient to adequately display the installation ID that was entered. Hence, opting for 8 columns provided a better visual representation.

2024-04-01 21:38 UTC, willmartian requested changes
Latest changes are looking good. @vinith-kovan, despite my prior review comment, could you actually revert the file rename? GitHub isn't recognizing that the file is renamed which makes it harder to review. (Sorry for the back and forth!)

2024-04-01 21:38 UTC, willmartian commented on apps/web/src/app/billing/organizations/download-license-dialog.component.html
> +        bitDialogClose
`bitDialogClose` is not necessary since we are manually closing the dialog within the `cancel` handler.

2024-05-08 17:32 UTC, amorask-bitwarden submitted a review, later dismissed

2024-05-30 14:43 UTC, amorask-bitwarden approved these changes

2024-06-05 08:15 UTC, merged