[PM-7004] Verify org delete from emailed link
bitwarden/clients pull request #8445
Opened 2024-03-22 13:37 UTC by kspearrin

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Allow org admins to confirm and verify to delete their org from the emailed link.

## Screenshots

![image](https://github.com/bitwarden/clients/assets/1190944/8978918e-8b60-4224-bc28-3c43def97721)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-03-22 14:21 UTC, willmartian requested changes

2024-03-22 14:21 UTC, willmartian commented on apps/web/src/app/auth/verify-recover-delete-org.component.html
> +            </button>
Use `bitButton` with `bitFormButton` instead of manually hooking into the loading/disabled states. [(docs)](https://components.bitwarden.com/?path=/docs/component-library-async-actions-in-forms-documentation--docs#3-add-directive-to-the-typesubmit-button)

2024-03-22 14:21 UTC, willmartian commented on apps/web/src/app/auth/verify-recover-delete-org.component.ts
> +// eslint-disable-next-line rxjs-angular/prefer-takeuntil
Is disabling this lint rule necessary?

2024-03-22 14:21 UTC, willmartian commented on apps/web/src/app/auth/verify-recover-delete-org.component.ts
> +    // eslint-disable-next-line rxjs-angular/prefer-takeuntil, rxjs/no-async-subscribe
Is disabling this lint rule necessary?

2024-03-22 14:21 UTC, willmartian commented on apps/web/src/app/auth/verify-recover-delete-org.component.ts
> +  }
1. Prefer promises over subscribing to single emission observables:

```ts
const params = await firstValueFrom(this.route.queryParams);
```

2. Fix floating promises with either `await` or `void`

2024-03-22 14:21 UTC, willmartian commented on apps/web/src/app/shared/loose-components.module.ts
> +    VerifyRecoverDeleteOrgComponent,
We should not add additional `declarations` to this module. Instead, create a standalone component and add it to the `imports` array. 

Example of standalone component in this module: https://github.com/bitwarden/clients/blob/28de9439beb87133c8683434df952a0c0be94100/apps/web/src/app/shared/components/account-fingerprint/account-fingerprint.component.ts

[Angular docs](https://angular.io/guide/standalone-components)

2024-03-22 14:29 UTC, kspearrin commented
This all came from copy/paste of the existing recover-delete-account component for user accounts. I guess that is deprecated code. Will have to look into doing things the newer way.

2024-03-22 15:28 UTC, willmartian commented
Ah, gotcha. More than happy to walk through anything with you if needed.

2024-03-22 18:29 UTC, rr-bw requested changes
Nice work so far. Would you mind adding a screen recording of the full flow when you are finished?

2024-03-22 18:29 UTC, rr-bw commented on apps/web/src/app/auth/verify-recover-delete-org.component.html
> +              <span>{{ "deleteAccount" | i18n }}</span>
Should this say "Delete organization" instead of "account"?

Also, the current [DeleteOrganizationDialogComponent](https://github.com/bitwarden/clients/blob/main/apps/web/src/app/admin-console/organizations/settings/components/delete-organization-dialog.component.html) shows a few extra details and warning messages. Will these be included in this implementation?

![Screenshot 2024-03-22 at 11 14 31 AM](https://github.com/bitwarden/clients/assets/102181210/37debfdc-002e-4ee3-b60d-fdc2396b66cb)

2024-03-22 18:29 UTC, rr-bw commented on apps/web/src/app/oss-routing.module.ts
> +        data: { titleId: "deleteAccount" },
"deleteOrganization"

2024-03-22 18:29 UTC, rr-bw commented on apps/web/src/app/auth/verify-recover-delete-org.component.ts
> +        this.i18nService.t("accountDeletedDesc"),
"organizationDeleted"
"organizationDeletedDesc"

2024-03-25 03:52 UTC, eliykat reviewed
I think that AC Team should own this new code, given that organizations are largely an AC concern and don't have much to do with Auth. What are your thoughts @rr-bw @jlf0dev ?

2024-03-25 03:52 UTC, eliykat commented on libs/common/src/abstractions/api.service.ts
> +  ) => Promise<any>;
This should go in the more specific domain api service `organization-api.service`. Although this does assume the answer to the code ownership question.

2024-04-01 18:07 UTC, kspearrin commented on libs/common/src/abstractions/api.service.ts
> +  ) => Promise<any>;
I moved this to organization-api.service, as suggested, however, that service can't be resolved via DI for this component.

```
error_handler.ts:45 ERROR NullInjectorError: R3InjectorError(AppModule)[OrganizationApiService -> OrganizationApiService]: 
  NullInjectorError: No provider for OrganizationApiService!
```

Seems like `OrganizationApiService` is not registered with some mobile, but I am not sure.

2024-04-01 18:29 UTC, willmartian commented on apps/web/src/app/auth/verify-recover-delete-org.component.html
I don't see anything in main using the layout, but you can check out the src for the Storybook samples linked above [here](https://github.com/bitwarden/clients/blob/b3e4ecc568abaf2196ffc60749603acf9bfca4e7/libs/auth/src/angular/anon-layout/anon-layout.stories.ts#L46-L49).

2024-04-03 19:54 UTC, rr-bw commented on apps/web/src/app/auth/verify-recover-delete-org.component.html
@willmartian I apologize for the confusion here as I indicated to you that the AnonLayoutComponent is ready for usage. But now that we are trying to implement the AnonLayoutComponent for the first time, I realize that some additional groundwork needs to be laid before actually using it in Web. That groundwork can be found in [this PR](https://github.com/bitwarden/clients/pull/8585), which is currently open for review.

That said, I think @kspearrin should continue this work **_without_** the AnonLayoutComponent, so as not to block him. Later on we can migrate it just like any other component that will eventually be migrated to use the AnonLayoutComponent.

Tagging for visibility: @trmartin4

2024-04-03 22:33 UTC, eliykat commented on libs/common/src/abstractions/api.service.ts
> +  ) => Promise<any>;
It's because the component is trying to inject the concrete `OrganizationApiService` instead of `OrganizationApiServiceAbstraction`. Change it to the abstraction and it should work.

2024-04-04 14:48 UTC, willmartian commented on apps/web/src/app/auth/verify-recover-delete-org.component.html
No worries at all @rr-bw! Thank you for the clarification.

2024-04-08 20:27 UTC, r-tome requested changes
There's already some great feedback here by @willmartian and @rr-bw.

The changes I'm requesting are:
- feedback from product: update all copy to replace "account" with "organization"
- move the component to be owned by AC

2024-04-08 20:27 UTC, r-tome commented on apps/web/src/app/auth/verify-recover-delete-org.component.ts
> +// eslint-disable-next-line rxjs-angular/prefer-takeuntil
```suggestion
```

2024-04-08 20:27 UTC, r-tome commented on apps/web/src/app/auth/verify-recover-delete-org.component.html
I think the component should be owned by the AC team, so it should be moved to the `admin-console` folder. Is this right @eliykat?

2024-04-08 20:27 UTC, r-tome commented on apps/web/src/app/auth/verify-recover-delete-org.component.html
> +      <p class="lead text-center mb-4">{{ "deleteAccount" | i18n }}</p>
```suggestion
      <p class="lead text-center mb-4">{{ "deleteOrganization" | i18n }}</p>
```

2024-04-08 20:27 UTC, r-tome commented on apps/web/src/app/auth/verify-recover-delete-org.component.html
> +          <app-callout type="warning">{{ "deleteAccountWarning" | i18n }}</app-callout>
```suggestion
          <app-callout type="warning">{{ "deleteOrganizationWarning" | i18n }}</app-callout>
```

2024-04-08 20:27 UTC, r-tome commented on apps/web/src/app/auth/verify-recover-delete-org.component.html
> +          <p>{{ "deleteRecoverConfirmDesc" | i18n }}</p>
Feedback from product: 
>Add the following sentence at the end: User accounts will remain active after deletion but will no longer be associated to this organization.
```suggestion
          <p>{{ "deleteOrganizationConfirmDesc" | i18n }}</p>
          <p>{{ "deletingOrganizationActiveUserAccountsWarning" | i18n }}</p>
```

2024-04-09 01:08 UTC, eliykat commented on apps/web/src/app/auth/verify-recover-delete-org.component.html
Yep!

2024-04-09 22:34 UTC, rr-bw commented
> I think that AC Team should own this new code, given that organizations are largely an AC concern and don't have much to do with Auth. What are your thoughts @rr-bw @jlf0dev ?

@eliykat Sorry for the late response. Yes, we agree (looks like it's already been moved 🙂)

2024-04-11 12:48 UTC, r-tome commented on apps/web/src/app/auth/verify-recover-delete-org.component.html
> +              <span>{{ "deleteAccount" | i18n }}</span>
>Should this say "Delete organization" instead of "account"?

Yes, its been changed!

>Also, the current [DeleteOrganizationDialogComponent](https://github.com/bitwarden/clients/blob/main/apps/web/src/app/admin-console/organizations/settings/components/delete-organization-dialog.component.html) shows a few extra details and warning messages. Will these be included in this implementation?

The second message has been included.

2024-04-18 04:53 UTC, eliykat requested changes

2024-04-18 04:53 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/manage/verify-recover-delete-org.component.ts
> +  selector: "app-verify-recover-delete-org",
The selector can/should be deleted because it is unused.

2024-04-18 04:53 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/manage/verify-recover-delete-org.component.ts
> +  protected formGroup = this.formBuilder.group({});
Empty formGroup?

2024-04-18 04:55 UTC, eliykat commented on libs/common/src/admin-console/abstractions/organization/organization-api.service.abstraction.ts
> +  recoverDeleteToken: (
The name here is not very self-explanatory, I suggest `recoverDelete` or `deleteUsingToken` instead, and/or a jsdoc comment explaining when it's used.

2024-04-18 04:56 UTC, eliykat commented
Also please resolve conflicts :)

2024-04-18 12:33 UTC, r-tome commented on apps/web/src/app/admin-console/organizations/manage/verify-recover-delete-org.component.ts
> +  protected formGroup = this.formBuilder.group({});
I didn't know how to use it properly. I've added the required values for the request (OrgId and Token). Let me know if this is the correct approach.

2024-04-19 00:35 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/manage/verify-recover-delete-org.component.html
> +<form [formGroup]="formGroup" [bitSubmit]="submit">
Continuing our conversation above - I don't think you need the `FormGroup` or `<form>` at all. There are no HTML form controls on this page, only a button. I recommend:

1. Delete the `<form>` element, or change it to a `<div>` if you still need it for structural purposes
2. Delete the `formGroup` property, go back to just storing your token info in private properties
3. Update your button to use the [standalone async action](https://components.bitwarden.com/?path=/docs/component-library-async-actions-standalone-documentation--docs) implementation rather than a form async action

@willmartian can you check me on this, do you agree there's nothing for a "form" to do here?

2024-04-19 19:31 UTC, willmartian commented on apps/web/src/app/admin-console/organizations/manage/verify-recover-delete-org.component.html
> +<form [formGroup]="formGroup" [bitSubmit]="submit">
Yes, that sounds right to me!

2024-04-19 19:44 UTC, willmartian requested changes
Left a few comments! To clarify, is the updated scope to remove the Bootstrap classes in another ticket?

2024-04-19 19:44 UTC, willmartian commented on apps/web/src/app/admin-console/organizations/manage/verify-recover-delete-org.component.ts
> +    }
Handlers passed to `bitAction` (and `bitSubmit`) will automatically call `LogService.error` and show an error toast on error. So the try/catch could be removed, unless the goal is to prevent an error toast from being shown.

2024-04-19 19:44 UTC, willmartian commented on apps/web/src/app/admin-console/organizations/manage/verify-recover-delete-org.component.html
> +            class="btn btn-danger btn-block btn-submit"
These classes are no longer necessary. In general, don't mix non-Tailwind classes with the CL or Tailwind.

2024-04-19 19:44 UTC, willmartian commented on apps/web/src/app/admin-console/organizations/manage/verify-recover-delete-org.component.html
> +            type="submit"
This should be `type="button"` since this is no longer a form.

2024-04-19 19:44 UTC, willmartian commented on apps/web/src/app/admin-console/organizations/manage/verify-recover-delete-org.component.html
> +            [disabled]="loading"
This binding to `disabled` is not necessary; `bitAction` disables the button for us between click and promise resolution.

2024-04-19 19:44 UTC, willmartian commented on apps/web/src/app/admin-console/organizations/manage/verify-recover-delete-org.component.html
> +            <span>{{ "deleteOrganization" | i18n }}</span>
This `span` isn't necessary.

2024-04-19 19:44 UTC, willmartian commented on apps/web/src/app/admin-console/organizations/manage/verify-recover-delete-org.component.html
> +          </a>
Could we update this to also use `bitButton`? It looks out of place right next to a CL button.

2024-04-22 19:56 UTC, r-tome commented on apps/web/src/app/admin-console/organizations/manage/verify-recover-delete-org.component.html
> +            class="btn btn-danger btn-block btn-submit"
I deleted all of them except `btn-danger`, how can I replace that and have the button remain red?

2024-04-22 19:59 UTC, r-tome commented
>To clarify, is the updated scope to remove the Bootstrap classes in another ticket?

I can do that here but I need some assistance. How can I replace the remaining Bootstrap classes?

2024-04-22 20:44 UTC, danielleflinn commented on apps/web/src/app/admin-console/organizations/manage/verify-recover-delete-org.component.html
> +            class="btn btn-danger btn-block btn-submit"
The outlined danger button works for me. I have not seen many use cases yet for the filled danger button (and none for a filled secondary button) so I am ok leaving it out of the CL until we see additional needs.

2024-04-22 20:45 UTC, willmartian commented on apps/web/src/app/admin-console/organizations/manage/verify-recover-delete-org.component.html
> +            class="btn btn-danger btn-block btn-submit"
Sounds good, ty @danielleflinn !

2024-04-23 00:12 UTC, eliykat commented
My understanding of [this thread](https://github.com/bitwarden/clients/pull/8445#discussion_r1535609382) was that we'd leave some Bootstrap classes in because we don't have the card-style layout available in the CL - which is why I didn't mention it in my review. @willmartian can you please clarify what else we can migrate here? It's a small component so it's not a big ask, I just want to clarify what else we can do at this stage.

If it is blocked by CL capabilities, I think we can just account for it with a follow-up Jira ticket.

2024-04-23 00:18 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/manage/verify-recover-delete-org.component.html
> +            [disabled]="loading"
@willmartian This disables the button during initial page load, not while the async action is executing. ngOnInit should be very quick to execute in this particular case, but it seems like a reasonable failsafe.

2024-04-23 12:14 UTC, r-tome commented on apps/web/src/app/admin-console/organizations/manage/verify-recover-delete-org.component.html
> +            class="btn btn-danger btn-block btn-submit"
Thank you both, I've removed the class and set it `buttonType="danger"`

2024-04-23 12:16 UTC, r-tome commented
> My understanding of [this thread](https://github.com/bitwarden/clients/pull/8445#discussion_r1535609382) was that we'd leave some Bootstrap classes in because we don't have the card-style layout available in the CL - which is why I didn't mention it in my review. @willmartian can you please clarify what else we can migrate here and how? I'm not objecting, I just want to clarify what else we can do at this stage.
> 
> If it is blocked by current CL limitations, I think we can just make it a follow-up Jira ticket.
> 
> Aside from this and my [comment above](https://github.com/bitwarden/clients/pull/8445#discussion_r1575491358), this lgtm.

I've added back in the manual loading state. I've also replaced all bootstrap classes with the equivalent tailwind classes (except the card layout).

2024-04-23 13:53 UTC, willmartian commented
> My understanding of [this thread](https://github.com/bitwarden/clients/pull/8445#discussion_r1535609382) was that we'd leave some Bootstrap classes in because we don't have the card-style layout available in the CL - which is why I didn't mention it in my review. @willmartian can you please clarify what else we can migrate here and how? I'm not objecting, I just want to clarify what else we can do at this stage.
>
> If it is blocked by current CL limitations, I think we can just make it a follow-up Jira ticket.

@eliykat  We should either replace the [card classes](https://github.com/bitwarden/clients/pull/8445/files#diff-692e1bd21f96947e72e573163c72297b24670e65312bfde653d9745d2e54b91dR4-R5) with Tailwind in this PR, or create a Jira ticket to use the auth anon layout whenever it is ready ([PR](https://github.com/bitwarden/clients/pull/8585)) and associate it with [BW-11](https://bitwarden.atlassian.net/browse/BW-11). Either is good with me--I just want to make sure this is _captured_ so when I rip bootstrap out nothing breaks here. :)

2024-04-23 13:55 UTC, willmartian commented on apps/web/src/app/admin-console/organizations/manage/verify-recover-delete-org.component.html
> +            [disabled]="loading"
@eliykat  Oof, missed that, thank you for the clarification. Agreed that this is fine to leave it.

2024-04-23 14:51 UTC, r-tome commented
@willmartian I gave it a go at replacing the Bootstrap card classes.

2024-04-23 14:58 UTC, willmartian commented
> @willmartian I gave it a go at replacing the Bootstrap card classes.

LGTM! Thank you @r-tome

2024-04-23 14:58 UTC, willmartian approved these changes

2024-04-24 04:24 UTC, rr-bw approved these changes
Approving because my original requested changes have been addressed. But since this has been moved to Admin Console instead of Auth, I won't do a full review.

2024-05-22 17:00 UTC, merged