PM-5017 Migrate Organization Plans component
bitwarden/clients pull request #8448
Opened 2024-03-22 15:04 UTC by KiruthigaManivannan

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other
```

## Objective

Migrate the Organization Plans component to use the component library.

## Code changes

- **organization-plans.component.html** Changed Radio button groups, checkboxes, Form input fields , buttons and all heading and paragraph tags to its equivalent components in component library.
- **organization-plans.component.ts** Added Form group for file import and removed try/catch in submit click.

## Screenshots
- **Click on Upgrade plan button click:**
Before:
![image](https://github.com/bitwarden/clients/assets/162679756/3cbc91d5-0cc1-41dc-90f2-ca80173fad08)
![image](https://github.com/bitwarden/clients/assets/162679756/0e4ed701-79c0-464f-a6ec-2a68d170e2d5)
![image](https://github.com/bitwarden/clients/assets/162679756/2b1e7232-5e76-4c47-bc39-4cca55509904)

After:
![image](https://github.com/bitwarden/clients/assets/162679756/3e036986-1319-430c-9abe-93950cb92b23)
![image](https://github.com/bitwarden/clients/assets/162679756/2358c60f-3f5e-4e72-a2fb-66a7346ef304)
![image](https://github.com/bitwarden/clients/assets/162679756/5b0b1150-c047-45c0-83df-c42fbc7d8213)
 

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-03-25 20:19 UTC, willmartian requested changes

2024-03-25 20:19 UTC, willmartian commented on apps/web/src/app/billing/organizations/organization-plans.component.html
> +    <h2 bitTypography="h2" class="tw-mt-5">{{ "chooseYourPlan" | i18n }}</h2>
Section titles shouldn't need extra margin/padding

2024-03-25 20:19 UTC, willmartian commented on apps/web/src/app/billing/organizations/organization-plans.component.html
> +    <div *ngFor="let selectableProduct of selectableProducts" class="">
Remove empty attribute `class`

2024-03-25 20:19 UTC, willmartian commented on apps/web/src/app/billing/organizations/organization-plans.component.html
>        >
Is it necessary to have the following hierarchy?

```html
<bit-section>
  <div>
    <bit-section>
      ...
    </bit-section>
    ...
  </div>
</bit-section>
```

Seems like we should just be able to do:

```html
<bit-section>...</bit-section>
<bit-section>...</bit-section>
...
```

2024-03-25 20:19 UTC, willmartian commented on apps/web/src/app/billing/organizations/organization-plans.component.html
> +            <bit-hint bitTypography="body2">{{ "userSeatsHowManyDesc" | i18n }}</bit-hint>
`bitTypography` does not replace the need to add `tw-text-muted`

2024-03-25 20:19 UTC, willmartian commented on apps/web/src/app/billing/organizations/organization-plans.component.html
> +        <h2 bitTypography="h2" class="tw-mt-5">{{ "addons" | i18n }}</h2>
Don't add additional margin/padding to headers

2024-03-25 20:19 UTC, willmartian commented on apps/web/src/app/billing/organizations/organization-plans.component.html
> +          class="tw-grid tw-grid-cols-12"
Missing grid gap

2024-03-25 20:19 UTC, willmartian commented on apps/web/src/app/billing/organizations/organization-plans.component.html
> +            <bit-hint bitTypography="body2"
Don't add custom typography styles to CL components such as `bit-hint`

2024-03-25 20:19 UTC, willmartian commented on apps/web/src/app/billing/organizations/organization-plans.component.html
> +        <div class="tw-grid tw-grid-cols-12">
Missing grid gap

2024-03-25 20:19 UTC, willmartian commented on apps/web/src/app/billing/organizations/organization-plans.component.html
> +          class="tw-grid tw-grid-cols-12"
Missing grid gap

2024-03-25 20:19 UTC, willmartian commented on apps/web/src/app/billing/organizations/organization-plans.component.html
> +            <bit-hint bitTypography="body2">{{
Don't add custom typography styles to CL components such as `bit-hint`

2024-03-25 20:19 UTC, willmartian commented on apps/web/src/app/billing/organizations/organization-plans.component.html
> +        <div *ngFor="let selectablePlan of selectablePlans">
Is this div needed?

2024-03-25 20:19 UTC, willmartian commented on apps/web/src/app/billing/organizations/organization-plans.component.html
> +                    (selectablePlan.isAnnual
Replace inline style (`style="text-decoration: line-through"`) in this block with Tailwind

2024-03-25 20:19 UTC, willmartian commented on apps/web/src/app/billing/organizations/organization-plans.component.html
> +    <h2 bitTypography="h2" class="tw-mb-4">
Use `bit-section` instead of div + margin

2024-05-08 17:33 UTC, amorask-bitwarden approved these changes

2024-05-09 15:41 UTC, merged

2024-05-09 16:19 UTC, amorask-bitwarden commented
@vinith-kovan This branch did not build when you merged it. Can you please ensure the build checks pass before you merge the migration PRs?