Tools/pm 6146/generator history
bitwarden/clients pull request #8497
Opened 2024-03-26 16:42 UTC by audrey-jensen

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

This code is not yet consumed by any client and thus does not need QA.

## Objective

Introduce history service with MV3/State provider support.

## Code changes

Generator history:
- **libs/common/src/tools/generator/abstractions/generator-history.abstraction.ts:** State provider based service for managing password generation history
- **libs/common/src/tools/generator/history/generated-credential.ts:** Data format for credential generation. Distinguishes between types of credentials.
- **libs/common/src/tools/generator/history/index.ts:** module exports
- **libs/common/src/tools/generator/history/local-generator-history.service.ts:** Generator history implementation that keeps the history local to a device. `Local` prefix used for consistency with [architecture guidelines](https://contributing.bitwarden.com/architecture/clients/presentation/angular#abstract--default-implementations) and to distinguish this service from a hypothetical future service that replicates password history.
- **libs/common/src/tools/generator/history/options.ts:** New types consumed by the local history service
- **libs/common/src/tools/generator/key-definitions.ts:** Use secret key definition for history storage. This wasn't available when the original key was created.

State management:
- **libs/common/src/tools/generator/state/classified-format.ts:** Split `ClassifiedFormat` out from `SecretState` since it's now shared with the `SecretKeyDefinition`
- **libs/common/src/tools/generator/state/secret-key-definition.ts:** `SecretKeyDefinition`s now encapsulate key definition derivation. 
- **libs/common/src/tools/generator/state/secret-state.ts:** `SecretState` now uses an rxjs cache instead of a `DerivedState` because the latter is global. The `SecretState` is user-specific, and cannot share the cache.

Moved Jsonification from `DataPacker` to the `SecretClassifier` because the classifier is the only component that has full type information. The data packer still handles stringification:
- **libs/common/src/tools/generator/state/secret-classifier.ts:** The secret classifier must jsonify because a type's `toJSON` implementation might depend on properties deleted or moved by the classifier.
- **libs/common/src/tools/generator/state/data-packer.abstraction.ts**
- **libs/common/src/tools/generator/state/padded-data-packer.ts**
- **libs/common/src/tools/generator/state/user-encryptor.abstraction.ts**
- **libs/common/src/tools/generator/state/user-key-encryptor.ts**

Unit tests:

- **libs/common/src/tools/generator/history/generated-credential.spec.ts** 
- **libs/common/src/tools/generator/history/local-generator-history.service.spec.ts** 
- **libs/common/src/tools/generator/key-definition.spec.ts** 
- **libs/common/src/tools/generator/state/padded-data-packer.spec.ts** 
- **libs/common/src/tools/generator/state/secret-classifier.spec.ts** 
- **libs/common/src/tools/generator/state/secret-key-definition.spec.ts** 
- **libs/common/src/tools/generator/state/secret-state.spec.ts** 
- **libs/common/src/tools/generator/state/user-key-encryptor.spec.ts**

2024-03-26 16:51 UTC, audrey-jensen commented on libs/common/src/tools/generator/state/secret-state.ts
>      userId: UserId,
📝 `from` now consists only of a constructor call, but is left here for backwards compatibility. It will be cleaned up and removed by a future PR.

2024-03-26 17:19 UTC, audrey-jensen commented
@justindbaur - This PR includes the changes to the secret state that we discussed on Friday and today. I've included you as a reviewer in case you want to check it out.

2024-03-28 13:29 UTC, djsmith85 approved these changes
Nice work. 
Clean abstraction of the credential history and how it's tracked/persisted. 

❤️  Thank you for all the thorough tests and docs as it really helps while  reviewing.

Am I correct in assuming this only takes care of the credential history when using the independent generator (not called from within a cipher). 
- Any generator that generates a value will also emit a GeneratedCredential which will then be stored via `local-history-generator.service.track`.
- It will need more work to plug this within the generator attached to a cipher?
  - Converting the emitted GeneratedCredential into a PasswordHistoryView and storing it with the cipher
  - or getting rid of the PasswordHistory models and migrating to use 

The state-related changes also LGTM but, I'll let Justin comment/review. Does not block the merge though.

2024-03-28 14:06 UTC, audrey-jensen commented
> Am I correct in assuming this only takes care of the credential history when using the independent generator (not called from within a cipher).

Yes. I can update the comments to explain that.

> Any generator that generates a value will also emit a GeneratedCredential which will then be stored via local-history-generator.service.track.

I considered updating the generator to emit the `GeneratedCredential` type, but didn't want the scope to grow too large on the PR (At ~20 files, it's already pretty big). I can whip up another PR with that change before jumping into the CL work, but I don't think it's a good idea to pursue it for MV3.

> It will need more work to plug this within the generator attached to a cipher? 

This shouldn't be used with the cipher password history. While it seems like a good candidate for reuse, the ciphers themselves should probably be fully versioned. Consider, for example, that passwords, usernames, passkeys, secret questions, and TOTP codes are all potentially versionable, related credentials stored in a vault item. 

It seems more practical to me that the vault should retain all of this data using an "atomic commit" structure. The user could then see point-in-time credentials. This mechanism could also enable offline sync scenarios. Like git, a version history is easy to replicate and, while hopefully rare, mismatched versions could be easily reconciled.

2024-03-28 14:14 UTC, djsmith85 commented
> Yes. I can update the comments to explain that.
> 
Thank you

> I considered updating the generator to emit the `GeneratedCredential` type, but didn't want the scope to grow too large on the PR (At ~20 files, it's already pretty big). I can whip up another PR with that change before jumping into the CL work, but I don't think it's a good idea to pursue it for MV3.
> 
Yes, also in favour in keeping the work smaller. We can follow up once the MV3 related work wraps up.

> This shouldn't be used with the cipher password history. While it seems like a good candidate for reuse, the ciphers themselves should probably be fully versioned. Consider, for example, that passwords, usernames, passkeys, secret questions, and TOTP codes are all potentially versionable, related credentials stored in a vault item.
> 
> It seems more practical to me that the vault should retain all of this data using an "atomic commit" structure. The user could then see point-in-time credentials. This mechanism could also enable offline sync scenarios. Like git, a version history is easy to replicate and (while hopefully rare) mismatched versions could be easily reconciled.

This would be a really awesome future improvement to version all item fields.

2024-03-28 14:42 UTC, djsmith85 submitted a review, later dismissed

2024-03-28 15:53 UTC, justindbaur requested changes
Just a couple minor copy updates

2024-03-28 15:53 UTC, justindbaur commented on libs/common/src/tools/generator/abstractions/generator-history.abstraction.ts
> +   *  @remarks This field is eventually consistent with `add`, `take`, and `clear` operations.
Comment possibly written before a rename? Probably should be this:
```suggestion
   *  @remarks This field is eventually consistent with `track` and `take` operations.
```

2024-03-28 15:53 UTC, justindbaur commented on libs/common/src/tools/generator/history/generated-credential.spec.ts
> +    it("passes thorugh date parameters", () => {
```suggestion
    it("passes through date parameters", () => {
```

2024-03-28 15:53 UTC, justindbaur commented on libs/common/src/tools/generator/state/classified-format.ts
> +  readonly id: Id | null;
I appreciate doing `| null` in the hopeful one day addition of strict null.

2024-03-28 16:01 UTC, audrey-jensen commented on libs/common/src/tools/generator/abstractions/generator-history.abstraction.ts
> +   *  @remarks This field is eventually consistent with `add`, `take`, and `clear` operations.
Addressed in 70d721a7.

2024-03-28 16:01 UTC, audrey-jensen commented on libs/common/src/tools/generator/history/generated-credential.spec.ts
> +    it("passes thorugh date parameters", () => {
Addressed in 70d721a7.

2024-03-28 16:13 UTC, justindbaur approved these changes

2024-03-28 16:14 UTC, djsmith85 approved these changes

2024-03-28 16:19 UTC, merged