PM-2165 Migrate delete account dialog
bitwarden/clients pull request #8503
Opened 2024-03-27 05:23 UTC by KiruthigaManivannan

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other
```

## Objective

Migrate the Delete account component to use the component library.

## Code changes

- **delete-account.component.html:** Updated modal to its equivalent dialog components of library and buttons also updated.
- **delete-account.component.ts:** Added a static method for dialog open from account component. Updated submit method.
- **account.component.html:** Updated delete account button and added bit action to it.
- **account.component.ts:** Delete account dialog open logic implemented.

## Screenshots
**Delete Account Dialog**
Before:
![image](https://github.com/bitwarden/clients/assets/162679756/fb921862-c813-4559-8414-196034b92582)
After:
![image](https://github.com/bitwarden/clients/assets/162679756/4ca8ddd3-2518-4d68-a14f-8e36870dd26e)

**Screen after account Delete**
Before:
![image](https://github.com/bitwarden/clients/assets/162679756/1ba04b38-cc2e-4e27-96bd-bbe5b28fc9ac)
After:
![image](https://github.com/bitwarden/clients/assets/162679756/11bd69f9-6641-405f-8314-9315ece4351f)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-03-30 14:46 UTC, willmartian requested changes
Looks largely good to me, just a couple change requests:

2024-03-30 14:46 UTC, willmartian commented on apps/web/src/app/auth/settings/account/delete-account.component.ts
>    }
Could you rename this static method to just `open`?

2024-03-30 14:46 UTC, willmartian commented on apps/web/src/app/auth/settings/account/delete-account.component.ts
>  })
1. The selector isn't needed and should be removed
2. Could you update the component name to reference that it is a dialog? `DeleteAccountDialogComponent`

2024-04-09 12:24 UTC, coroiu requested changes

2024-04-09 12:24 UTC, coroiu commented on apps/web/src/app/auth/settings/account/delete-account-dialog.component.html
> +      ></app-user-verification>
❌ issue: `app-user-verification` is deprecated. Use `app-user-verification-form-input` instead.

❌ issue: both of these components currently need the parent component to keep track of `invalidSecret` to be able to properly display an error if the user has entered a wrong secret. 

Here is an example where the new component is used: https://github.com/bitwarden/clients/blob/a4b15bbcf081dca13a057c444660af12cdbbf0b7/libs/auth/src/angular/user-verification/user-verification-dialog.component.html#L41-L47

2024-04-09 12:24 UTC, coroiu commented on apps/web/src/app/auth/settings/account/delete-account-dialog.component.ts
> +  };
🎨 suggestion: should we maybe disable dialog-closing while this request is in progress?

2024-04-12 05:20 UTC, KiruthigaManivannan commented on apps/web/src/app/auth/settings/account/delete-account-dialog.component.html
> +      ></app-user-verification>
@coroiu  Earlier it was mentioned in JIRA that we need to use new User verification dialog component . And I had few queries in using that.  
https://bitwarden.atlassian.net/browse/PM-2165. Todd has given some comments in that. And after going through the analysis document he edited the JIRA description also. 
And also when we had some issues in using new app-user-verification-form-input  in other two factor verify dialog stuff he mentioned the below message in slack.

![image](https://github.com/bitwarden/clients/assets/162679756/67c96706-9b6d-4efa-a5b7-b9db791da2ea)

But for this component can we check once again. ?? Whether to use new app-user-verification -form-input or old one.

2024-04-12 07:27 UTC, coroiu commented on apps/web/src/app/auth/settings/account/delete-account-dialog.component.html
> +      ></app-user-verification>
Oh interesting, I will check and get back to you!

2024-04-12 07:28 UTC, coroiu commented on apps/web/src/app/auth/settings/account/delete-account-dialog.component.html
> +      ></app-user-verification>
Oh interesting! @trmartin4 @jlf0dev @JaredSnider-Bitwarden can you answer this?

2024-05-05 22:01 UTC, trmartin4 commented on apps/web/src/app/auth/settings/account/delete-account-dialog.component.html
> +      ></app-user-verification>
@coroiu I believe we covered this in Slack, but we are actually good with using the new component, and it has been migrated on this PR.  Thank you for pushing for it!

2024-05-13 14:10 UTC, coroiu reviewed
> ❌ issue: both of these components currently need the parent component to keep track of invalidSecret to be able to properly display an error if the user has entered a wrong secret.
> - https://github.com/bitwarden/clients/pull/8503#discussion_r1557540540

Missing `invalidSecret` handling

**Example:**
![Recording 2024-05-13 at 16 07 31](https://github.com/bitwarden/clients/assets/2285588/e1baac41-3af6-4fce-8349-bef0b02ee4c6)

**This PR:**
![Recording 2024-05-13 at 16 09 47](https://github.com/bitwarden/clients/assets/2285588/c4041589-47b8-46f4-9759-5639357b493f)

2024-05-17 05:56 UTC, KiruthigaManivannan commented
https://github.com/bitwarden/clients/pull/8503#pullrequestreview-2052821744  will address this soon @coroiu

2024-05-21 06:46 UTC, KiruthigaManivannan commented
@trmartin4 I have added invalidSecret to form input as per your advise provided in slack. Is this code change fine

2024-05-21 07:35 UTC, coroiu submitted a review, later dismissed
Looking good!

2024-05-22 13:29 UTC, jlf0dev approved these changes

2024-05-24 06:55 UTC, coroiu approved these changes

2024-05-24 06:55 UTC, merged