[AC-1911] Clients: Create components to manage client organization seat allocation
bitwarden/clients pull request #8505
Opened 2024-03-27 08:14 UTC by cyprain-okeke

## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

In the Provider Portal, on the Clients tab, implement components according to the [Figma designs](https://www.figma.com/proto/m8eMk6yeKfOq4AUuyp70ih/Consolidated-Billing?page-id=698%3A10060&type=design&node-id=913-20780&viewport=-4992%2C173%2C0.2&t=fqtmShFWTkcODxja-1&scaling=min-zoom&starting-point-node-id=913%3A20780) that allows the Provider Admin to view and manage the number of seats they’ve allocated to each of their client organizations.

Notes
The 3-dot menu to the right of each client organization opens more options including “Subscription”, which opens the manage-client-subscription.component modal and “Unlink organization”, which should behave the same as the current Provider Portal’s client management

The “Add organization” button will not be included in this story. That piece will be tackled [in this story](https://bitwarden.atlassian.net/browse/AC-1912) after this one has been completed

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-03-27 16:43 UTC, amorask-bitwarden requested changes
Nice start. Got a few points below for you and then we can work through this initial feedback below.

❓ Did you end up getting the feature flag to work? I can't trigger it locally.

✏️  For all net-new files, we should be creating them in a manner where the Billing team owns them so that we don't have to ask other teams for reviews on them arbitrarily. I'd suggest either reorganizing what you have so that it's in a billing folder or updating the CODEOWNERS file.

2024-03-27 16:43 UTC, amorask-bitwarden commented on apps/web/src/locales/en/messages.json
> +    "message": "Add New organization"
"New" should be lowercase here.

2024-03-27 16:43 UTC, amorask-bitwarden commented on apps/web/src/locales/en/messages.json
> +    "message": "Unlink Organization"
"Organization" should be lowercase here.

2024-03-27 16:43 UTC, amorask-bitwarden commented on apps/web/src/locales/en/messages.json
> +    "message": "MANAGE SEATS"
Is this being title cased somewhere? The Figma designs have it as "Manage seats".

2024-03-27 16:43 UTC, amorask-bitwarden commented on apps/web/src/locales/en/messages.json
> +    "message": "Assigned Seats can not be updated . Please contact your organization owner for assistance."
I think you have an extra space after the word "updated".

2024-03-27 16:43 UTC, amorask-bitwarden commented on libs/common/src/abstractions/api.service.ts
> +  ) => Promise<any>;
Please move these two methods to the `billing-api.service` so we have ownership of them.

2024-03-27 16:43 UTC, amorask-bitwarden commented on libs/common/src/services/api.service.ts
> +  async getProviderClientSubscriptions(providerId: string): Promise<ProviderSubscriptionResponse> {
See my note on the abstraction file about moving these to the `billing-api.service`.

2024-03-27 16:43 UTC, amorask-bitwarden commented on libs/common/src/admin-console/models/request/provider/provider-subscription-update.request.ts
> +export class ProviderSubscriptionUpdateRequest {
Please move these to a billing folder so we own it.

2024-03-27 16:43 UTC, amorask-bitwarden commented on libs/common/src/admin-console/models/response/provider/provider-plans.response.ts
> +export class ProviderPlansResponse extends BaseResponse {
Please move this to a billing folder so we own it.

2024-03-27 16:43 UTC, amorask-bitwarden commented on libs/common/src/admin-console/models/response/provider/provider-subscription.response.ts
> +export class ProviderSubscriptionResponse extends BaseResponse {
Please move this to a billing folder so we own it.

2024-03-27 16:43 UTC, amorask-bitwarden commented on bitwarden_license/bit-web/src/app/admin-console/providers/providers-layout.component.html
> +      [route]="(enableConsolidatedBilling$ | async) ? 'manage-client-organizations' : 'clients'"
Did you get this to work? It's not working for me when I run it locally.

2024-03-27 16:43 UTC, amorask-bitwarden commented on bitwarden_license/bit-web/src/app/admin-console/providers/clients/manage-client-organization-subscription.component.ts
> +  async loadData() {
Looks like this is only called once; can probably just go in `ngOnInit`.

2024-03-27 16:43 UTC, amorask-bitwarden commented on bitwarden_license/bit-web/src/app/admin-console/providers/clients/manage-client-organization-subscription.component.ts
> +      this.minimumFloor = this.assignedSeats - seatMinimum;
Is this supposed to represent the remaining open seats? If so, can we rename it as such so it's more clear.

2024-03-27 16:43 UTC, amorask-bitwarden commented on bitwarden_license/bit-web/src/app/admin-console/providers/clients/manage-client-organization-subscription.component.html
> +    <p *ngIf="minimumFloor == 0 && unassignedSeats > 0">
This condition and the one on line 27 are the same condition

2024-03-27 16:43 UTC, amorask-bitwarden commented on bitwarden_license/bit-web/src/app/admin-console/providers/clients/manage-client-organizations.component.ts
> +    this.addableOrganizations = candidateOrgs.filter((o) => allowedOrgsIds.includes(o.id));
Consolidated billing won't support adding existing orgs - this can be removed.

2024-03-27 16:43 UTC, amorask-bitwarden commented on bitwarden_license/bit-web/src/app/admin-console/providers/clients/manage-client-organizations.component.ts
> +    this.showAddExisting = this.addableOrganizations.length !== 0;
So can this.

2024-03-28 07:40 UTC, cyprain-okeke commented on apps/web/src/locales/en/messages.json
> +    "message": "Add New organization"
thanks, resolved

2024-03-28 07:40 UTC, cyprain-okeke commented on apps/web/src/locales/en/messages.json
> +    "message": "Unlink Organization"
thanks, resolved

2024-03-28 07:42 UTC, cyprain-okeke commented on apps/web/src/locales/en/messages.json
> +    "message": "MANAGE SEATS"
The Figma designs have it as it has cased on the dialog page
![dialogPage](https://github.com/bitwarden/clients/assets/108260115/f0c6b820-0694-43fb-927b-061f006baeaf)

2024-03-28 07:43 UTC, cyprain-okeke commented on apps/web/src/locales/en/messages.json
> +    "message": "Assigned Seats can not be updated . Please contact your organization owner for assistance."
thanks, resolved

2024-03-28 09:41 UTC, cyprain-okeke commented on libs/common/src/abstractions/api.service.ts
> +  ) => Promise<any>;
thanks, moved

2024-03-28 09:41 UTC, cyprain-okeke commented on libs/common/src/services/api.service.ts
> +  async getProviderClientSubscriptions(providerId: string): Promise<ProviderSubscriptionResponse> {
thanks, moved

2024-03-28 10:45 UTC, cyprain-okeke commented on libs/common/src/admin-console/models/request/provider/provider-subscription-update.request.ts
> +export class ProviderSubscriptionUpdateRequest {
thanks, moved

2024-03-28 10:53 UTC, cyprain-okeke commented on libs/common/src/admin-console/models/response/provider/provider-plans.response.ts
> +export class ProviderPlansResponse extends BaseResponse {
thanks, moved

2024-03-28 10:53 UTC, cyprain-okeke commented on libs/common/src/admin-console/models/response/provider/provider-subscription.response.ts
> +export class ProviderSubscriptionResponse extends BaseResponse {
thanks, moved

2024-03-28 10:54 UTC, cyprain-okeke commented on bitwarden_license/bit-web/src/app/admin-console/providers/providers-layout.component.html
> +      [route]="(enableConsolidatedBilling$ | async) ? 'manage-client-organizations' : 'clients'"
Yes, is working well now

2024-03-28 10:59 UTC, cyprain-okeke commented on bitwarden_license/bit-web/src/app/admin-console/providers/clients/manage-client-organization-subscription.component.ts
> +  async loadData() {
Yeah, it can be moved to ngOnInit. moved

2024-03-28 12:07 UTC, cyprain-okeke commented on bitwarden_license/bit-web/src/app/admin-console/providers/clients/manage-client-organization-subscription.component.html
> +    <p *ngIf="minimumFloor == 0 && unassignedSeats > 0">
refactored

2024-03-28 12:13 UTC, cyprain-okeke commented on bitwarden_license/bit-web/src/app/admin-console/providers/clients/manage-client-organizations.component.ts
> +    this.addableOrganizations = candidateOrgs.filter((o) => allowedOrgsIds.includes(o.id));
removed

2024-03-28 12:13 UTC, cyprain-okeke commented on bitwarden_license/bit-web/src/app/admin-console/providers/clients/manage-client-organizations.component.ts
> +    this.showAddExisting = this.addableOrganizations.length !== 0;
removed

2024-03-28 12:59 UTC, amorask-bitwarden commented on bitwarden_license/bit-web/src/app/admin-console/providers/providers-layout.component.html
> +      [route]="(enableConsolidatedBilling$ | async) ? 'manage-client-organizations' : 'clients'"
https://github.com/bitwarden/clients/assets/144709477/10c06148-e156-4bfa-b94e-f4ee7a94dfaa

I think something is behaving incorrectly with the feature flag. When I first load the provider portal, it shows the Off state behavior, but then a reload after going to another page shows the On state.

2024-03-28 13:36 UTC, cyprain-okeke commented on bitwarden_license/bit-web/src/app/admin-console/providers/providers-layout.component.html
> +      [route]="(enableConsolidatedBilling$ | async) ? 'manage-client-organizations' : 'clients'"
hmm, I will check, I don't experience this

2024-03-28 16:44 UTC, amorask-bitwarden requested changes
Great work - this is really coming along and looks great on the front-end. I caught one more bug that I left a note for.

Additionally, can you address my comment regarding net-new files? We should either store those files somewhere we own or update the CODEOWNERS for us to own them specifically. AC team won't have context on what to review for these.

Thanks!

2024-03-28 16:44 UTC, amorask-bitwarden commented on bitwarden_license/bit-web/src/app/admin-console/providers/clients/manage-client-organizations.component.ts
> +      assignedSeats: this.assignedSeats,
I don't think this is correct. This appears to be all of the provider's assigned seats across all plans, which results in the following:

![image](https://github.com/bitwarden/clients/assets/144709477/33a9be4a-be0d-4683-a976-51c2eb39beb3)

When I'm managing seats for the organization shown above, they should have 150 seats currently assigned.

2024-03-28 16:53 UTC, amorask-bitwarden commented
Sorry, one more thing. I've scaled both of my client organizations in the example below down below their seat minimum, which means the warning shown in this Figma is not working. In my example, each plan has a seat minimum of 100. The single Teams org has 70 seats and the single Enterprise org has 40 seats. If I manage the subscription for the Teams org, I should see the helper text for 30 unassigned seats.
![image](https://github.com/bitwarden/clients/assets/144709477/be8df15c-afa1-4264-8f65-015edb8c9a9e)

![image](https://github.com/bitwarden/clients/assets/144709477/0b007692-4070-43af-b153-89c3a82ae2d5)

2024-04-02 11:45 UTC, r-tome reviewed
LGTM but I have one business logic question: shouldn't we disable the "Manage seats" option if the selected Organization Plan does not support consolidated billing?

2024-04-02 13:26 UTC, amorask-bitwarden commented
> LGTM but I have one business logic question: shouldn't we disable the "Manage seats" option if the selected Organization Plan does not support consolidated billing?

Hi @r-tome, once Consolidated Billing goes live, a Provider will not be able to link an organization that doesn't use one of the supported plans so theoretically, that case wouldn't be possible.

2024-04-02 13:27 UTC, amorask-bitwarden approved these changes

2024-04-02 14:05 UTC, r-tome approved these changes
Thanks for answering @amorask-bitwarden!
Good work @cyprain-okeke!

2024-04-02 16:04 UTC, merged