PM-2047 Migrated Change Avatar component
bitwarden/clients pull request #8522
Opened 2024-03-28 05:42 UTC by KiruthigaManivannan

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other
```

## Objective

Migrate the Change Avatar component to use the component library.

## Code changes

- **change-avatar.component.html:** Updated the html to bit-dialog component from library
- **change-avatar.component.ts:** Added static method for dialog open
-  **profile.component.ts:** Logic for Change Avatar dialog open is implemented
- **profile.component.html:** Removed ng-template

## Screenshots
**Click Customize button**

Before:
![image](https://github.com/bitwarden/clients/assets/162679756/62004d0c-c483-4c2d-849f-470a64f646ed)

After:
![image](https://github.com/bitwarden/clients/assets/162679756/ac7803b3-4264-41ad-9419-5caa3a2353ab)

2024-03-30 14:31 UTC, willmartian requested changes

2024-03-30 14:31 UTC, willmartian commented on apps/web/src/app/auth/settings/account/change-avatar.component.ts
> +}
Can we update this to be a `Type`? That is more consistent with other usages.

2024-03-30 14:31 UTC, willmartian commented on apps/web/src/app/auth/settings/account/change-avatar.component.ts
> +    private dialogRef: DialogRef,
`DialogRef` should receive `ChangeAvatarDialogResult` as a type parameter for stronger typing

2024-03-30 14:31 UTC, willmartian commented on apps/web/src/app/auth/settings/account/change-avatar.component.ts
> +  static openChangeAvatarDialog(
This static method name can just be `open` since the class name already describes what is being opened.

2024-03-30 14:31 UTC, willmartian commented on apps/web/src/app/auth/settings/account/change-avatar.component.ts
>  export class ChangeAvatarComponent implements OnInit, OnDestroy {
1. Dialogs don't need selectors, could we remove it?
2. Can we update the class name to reference the component is a dialog? `ChangeAvatarDialogComponent`

2024-03-30 14:31 UTC, willmartian commented on apps/web/src/app/auth/settings/account/profile.component.ts
> +    return result;
Since we aren't using this information anywhere, it can be removed.

2024-03-30 14:31 UTC, willmartian commented on apps/web/src/app/auth/settings/account/change-avatar.component.ts
> +}
These don't look like they are ever consumed anywhere. Perhaps we should remove them? cc @JaredSnider-Bitwarden

2024-03-30 14:32 UTC, willmartian commented
@KiruthigaManivannan The lint workflow is failing, could you take a look at that?

2024-05-13 18:36 UTC, jlf0dev commented on apps/web/src/app/auth/settings/account/change-avatar-dailog.component.ts
spellcheck: filename should be "change-avatar-dialog.component.ts"

2024-05-29 04:38 UTC, KiruthigaManivannan commented
@jlf0dev please approve this so that i can merge

2024-05-29 13:07 UTC, jlf0dev commented
Hi @KiruthigaManivannan, please address [this feedback](https://github.com/bitwarden/clients/pull/8522#discussion_r1598889107). The file is still misspelled.

2024-05-29 13:29 UTC, KiruthigaManivannan commented on apps/web/src/app/auth/settings/account/change-avatar-dailog.component.ts
@jlf0dev Done now ..please check

2024-05-29 13:38 UTC, KiruthigaManivannan commented on apps/web/src/app/auth/settings/account/profile.component.ts
> +  formPromise: Promise<any>;
@jlf0dev Done ...removed promise

2024-05-29 15:49 UTC, jlf0dev approved these changes

2024-06-04 15:34 UTC, willmartian approved these changes

2024-06-06 13:53 UTC, merged