Auth/pm-7169/remove-auth-status-from-account-info
bitwarden/clients pull request #8539
Opened 2024-03-28 21:15 UTC by MGibson1

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Adding authentication status to account service has proven to be a mistake. It's better handled as an on-demand check, which is introduced by #8537.

This removes the status from account service entirely, including any current calls to it and set methods.

### Draft Reason
depends on #8537

## Code changes

- ****:

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-04-02 11:54 UTC, coroiu submitted a review, later dismissed
macOS build had failed, re-ran the job and it passed so it was probably nothing :)

2024-04-04 11:37 UTC, coroiu reviewed
Tests failing

2024-04-04 14:10 UTC, jlf0dev submitted a review, later dismissed

2024-04-04 14:43 UTC, audrey-jensen requested changes
⛏️ nitpick

There's one suggested change, which is the only one I'm requesting. I think the nits might be in auth code, not general code, but it was hard to tell. Do whatever make sense for the codeowner.

2024-04-04 14:43 UTC, audrey-jensen commented on apps/browser/src/auth/popup/account-switching/services/account-switcher.service.ts
> +              // ),
⛏️  Is this code that should be deleted or is there a missing FIXME?

2024-04-04 14:48 UTC, MGibson1 commented on apps/browser/src/auth/popup/account-switching/services/account-switcher.service.ts
> +              // ),
😳 that's a big bug, was disable for testing and erroneously pushed. thank you

2024-04-04 14:58 UTC, MGibson1 commented on apps/browser/src/auth/popup/account-switching/services/account-switcher.service.spec.ts
> +    it("only displays accounts that are not logged out", async () => {
I've updated the phrasing and conditions of the first test, but that is the one that covers your case. This is intended to indicate exclusion of logged out users. Of course, a logged out use could be included in the first test, but that feels a bit too much like a kitchen sink test, in that case. I actually feel it already is -- especially with the locked account addition -- but didn't want to go too far in totally rewriting these test cases.

2024-04-04 15:09 UTC, audrey-jensen commented on apps/browser/src/auth/popup/account-switching/services/account-switcher.service.spec.ts
> +    it("only displays accounts that are not logged out", async () => {
Agreed. It was hard to figure out that they were included in the first one b/c it's doing a lot. Thanks!

2024-04-04 15:11 UTC, audrey-jensen approved these changes

2024-04-09 14:30 UTC, MGibson1 commented on apps/browser/src/auth/popup/account-switching/account-switcher.component.ts
> +    );
I had thought that since it is piped through `| async`, it would be called only once, but as you pointed out, change detection runs on the property anyway. Thank you!

2024-04-09 15:46 UTC, coroiu submitted a review, later dismissed

2024-04-09 17:31 UTC, audrey-jensen approved these changes

2024-04-10 07:02 UTC, coroiu submitted a review, later dismissed
<img width="400" src="https://github.com/bitwarden/clients/assets/2285588/610aa9eb-0e60-42d3-92c8-cbc816ad0157"/>

Approving to get stop notifications, just ping me again if my approval gets dismissed during the conflict resolution.

(yes I did spent too much time creating that meme image 🥲)

2024-04-10 07:39 UTC, coroiu commented on apps/browser/src/auth/popup/account-switching/account-switcher.component.ts
> +    );
I didn't consider the testing aspect, but I think there are ways of enabling testing without making this compromise, e.g:

https://github.com/bitwarden/clients/blob/58aa75f35e5f330d876ed5a29cdd6908b32691a2/apps/browser/src/vault/fido2/background/fido2.background.spec.ts#L126

https://github.com/bitwarden/clients/blob/58aa75f35e5f330d876ed5a29cdd6908b32691a2/apps/browser/src/vault/fido2/background/fido2.background.ts#L173

which is from @cagonzalezcs's PR here https://github.com/bitwarden/clients/pull/8222/

2024-04-10 13:57 UTC, audrey-jensen commented on apps/browser/src/auth/popup/account-switching/account-switcher.component.ts
> +    );
We should probably continue this discussion privately.

2024-04-11 14:05 UTC, jlf0dev reviewed
Looks good! What he said about conflicts^

2024-04-11 15:38 UTC, MGibson1 commented
have to close and reopen to bump the enforce pr labels to reevaluate 🙄

2024-04-11 15:43 UTC, audrey-jensen approved these changes

2024-04-11 16:52 UTC, jlf0dev approved these changes

2024-04-12 07:25 UTC, coroiu approved these changes

2024-04-12 07:25 UTC, merged