[AC-2330] Updated Cipher Collections Now Sets Readonly Properly
bitwarden/clients pull request #8549
Opened 2024-03-29 18:51 UTC by Jingo88

```
- [ x ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Previously if a Owner/Admin removed a collection from a cipher, and no longer had `Manage` access to that cipher, when opening the item, it will still show it to be editable

The code changes will check the Ciphers `manage` value and update the `edit` value before saving it to the API and the stateService. 

## Code changes

* `collections component` call new `checkCipherEditValue` method
* `collection service` - new `checkCipherEditValue` method will compare the `cipher.collectionIds` to the `getDecrypted Collections` and will assess the `manage` value for all the ciphers collections. then return the proper edit value for that cipher

## Screen Recording

https://github.com/bitwarden/clients/assets/8302660/1eabae13-c04a-44a7-9724-dda5c0f0fdd5

2024-03-29 19:51 UTC, LRNcardozoWDF approved these changes
LGTM!

2024-04-03 00:52 UTC, eliykat requested changes
I strongly prefer that we rely on the server to manage this logic rather than duplicating it in `clients`. Usually you rely on the server's response to update the local data after a request.

e.g. saveCollectionsWithServer currently looks like this:

```ts
  async saveCollectionsWithServer(cipher: Cipher): Promise<any> {
    const request = new CipherCollectionsRequest(cipher.collectionIds);
    await this.apiService.putCipherCollections(cipher.id, request);
    const data = cipher.toCipherData();
    await this.upsert(data);
  }
```

But if you had the server endpoint return the updated cipher, it could look like this:

```ts
  async saveCollectionsWithServer(cipher: Cipher): Promise<any> {
    const request = new CipherCollectionsRequest(cipher.collectionIds);
    const response = await this.apiService.putCipherCollections(cipher.id, request);
    const data = new CipherData(response);
    await this.upsert(data);
  }
```

And then you're not duplicating authorization logic here, and you're not even adding much logic, just stitching together existing code.

2024-04-08 18:07 UTC, LRNcardozoWDF approved these changes

2024-04-10 23:26 UTC, eliykat approved these changes

2024-04-12 19:41 UTC, merissaacosta approved these changes

2024-04-12 19:41 UTC, merged