AnonLayoutComponent Implementation Groundwork
bitwarden/clients pull request #8585
Opened 2024-04-02 21:18 UTC by rr-bw

- **test implementation**
- **move files**

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-04-03 16:34 UTC, trmartin4 commented
This looks great!  I can't comment on the technical side of the implementation, but I wanted to ask about a slight tweak in the documentation and the PR description.  I'd suggest avoiding referring to the `AnonLayoutComponent` as a "CL component".  It's not technically owned by the CL team, as it's a shared component owned by Auth.  Perhaps instead call it an "Auth-owned library component"?

2024-04-03 17:04 UTC, rr-bw commented
> This looks great! I can't comment on the technical side of the implementation, but I wanted to ask about a slight tweak in the documentation and the PR description. I'd suggest avoiding referring to the `AnonLayoutComponent` as a "CL component". It's not technically owned by the CL team, as it's a shared component owned by Auth. Perhaps instead call it an "Auth-owned library component"?

Great catch @trmartin4. I will update that.

2024-04-05 12:37 UTC, jlf0dev reviewed
This is awesome! Thank you for the details you've included in the documentation, I'm sure that will pay dividends in the future.

2024-04-05 12:37 UTC, jlf0dev commented on libs/auth/src/angular/anon-layout/anon-layout.mdx
> +AnonLayoutComponent.
How does this work for desktop and browser? Will they have wrapper components as well?

2024-04-08 08:26 UTC, Hinton requested changes

2024-04-08 08:26 UTC, Hinton commented on apps/web/src/app/shared/shared.module.ts
> +    AnonLayoutComponent,
I don't think this qualifies to be added here.
```
* This NgModule should contain the most basic shared directives, pipes, and components. They
* should be widely used by other modules to be considered for adding to this module. If in doubt
* do not add to this module.
```

2024-04-08 08:26 UTC, Hinton commented on apps/web/src/app/oss-routing.module.ts
> +  // TODO: remove this example
Comment to ensure this gets removed

2024-04-29 07:53 UTC, rr-bw commented
@Hinton I updated the AnonLayoutWrapperComponent to allow passing down the `pageTitle`, `pageSubtitle`, and `pageIcon` from the router. For the `pageIcon`, unfortunately this meant reintroducing a [switch statement](https://github.com/bitwarden/clients/pull/8585/files#diff-cfa739dce06ebf3fb10c53f830d3c75aa1a3500336e40ef410bd01f5eea8fd04R32-R38) back into the auth AnonLayoutComponent. Let me know if you think there is a better way to handle the icon.

One other question, I noticed that my `tw` classes aren't getting set in development. For example, the classes `tw-gap-9 tw-pt-14 tw-fill-primary-500 tw-mb-8` are all used in the AnonLayoutComponent, but don't actually affect styling until I add them arbitrarily to another Web component like `login.component.html`. Am I doing something wrong with imports?

2024-04-29 11:00 UTC, Hinton commented
@rr-bw I would lift up the switch statement into the wrapper. The wrapper parses the url routes, not the base component.

Did we test if passing in a icon in the routes file would work?

2024-04-29 22:15 UTC, rr-bw commented
@Hinton Thanks, I moved the icon to the router and fixed the tailwind issues.

2024-04-29 23:50 UTC, rr-bw commented
@Hinton @jlf0dev This is ready for a final review. A few comments and one question:
- I've moved the `AnonLayoutWrapperComponent` to `libs` as well so it can be used across clients.
- I've updated storybook docs.
- If you want to see this work in action, I've created [temporary PR](https://github.com/bitwarden/clients/pull/8984) with a `sample-route` that you can build locally to view.
- One question: The `AnonLayoutComponent` is in fact responsive (in storybook), but for it to truly be responsive in Web, we'll have to wait until we deal with the `<meta name="viewport" content="width=1010" />` in `index.html`, correct?

2024-05-02 10:45 UTC, Hinton commented on libs/auth/src/angular/anon-layout/anon-layout-wrapper.component.ts
I consider routable components to be application specific. While you can ensure each application is routed identically it's not something we currently do.

2024-05-02 10:45 UTC, Hinton commented on libs/auth/src/angular/anon-layout/anon-layout-wrapper.component.ts
> +  }
Web specific.

2024-05-03 05:05 UTC, rr-bw commented on libs/auth/src/angular/anon-layout/anon-layout-wrapper.component.ts
Makes sense. I moved it back to web.

2024-05-03 05:07 UTC, rr-bw commented on apps/web/src/app/oss-routing.module.ts
> +  // TODO: remove this example
Removed. However I opened a [temporary draft PR](https://github.com/bitwarden/clients/pull/8984) with this route added in case you want to test visually for yourself. Will close after.

2024-05-06 20:20 UTC, Hinton approved these changes

2024-05-06 20:33 UTC, jlf0dev approved these changes

2024-05-07 01:34 UTC, merged