Auth/pm 7235/remove ever been unlocked and update get auth status
bitwarden/clients pull request #8590
Opened 2024-04-02 22:18 UTC by JaredSnider-Bitwarden

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-04-04 14:35 UTC, jlf0dev reviewed
I like it! Just some questions

2024-04-04 14:35 UTC, jlf0dev commented on libs/common/src/platform/services/user-key-init.service.ts
> +// similar to the TokenService (it would either go to secure storage for the auto user key or memory for the user key)
This is a good idea, but I also think we should wait for state providers to include secure storage. As we've seen with token service, mixing the two adds complexity especially if we're trying to expose it as an observable.

2024-04-04 14:35 UTC, jlf0dev commented on libs/common/src/platform/services/user-key-init.service.ts
> +      .subscribe();
can we add some error handling here? See [this](https://stackoverflow.com/questions/76357688/why-should-errors-of-a-promise-be-always-caught) for more info

2024-04-04 14:35 UTC, jlf0dev commented on apps/web/src/app/core/init.service.ts
> +      this.userKeyInitService.listenForActiveUserChangesToSetUserKey();
Question: What happens with the subscription returned here? Does it just exist for the lifetime of the application?

2024-04-04 15:25 UTC, JaredSnider-Bitwarden commented on libs/common/src/platform/services/user-key-init.service.ts
> +// similar to the TokenService (it would either go to secure storage for the auto user key or memory for the user key)
@justindbaur , @jlf0dev has a good point here. Luckily, this change can be a good stopgap until then!

2024-04-04 17:39 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/core/init.service.ts
> +      this.userKeyInitService.listenForActiveUserChangesToSetUserKey();
Hmm... I tested adding `NgOnDestroy` to all init services, but it never gets hit. Probably just have to leave it as is.

2024-04-04 17:44 UTC, JaredSnider-Bitwarden commented on libs/common/src/platform/services/user-key-init.service.ts
> +      .subscribe();
Good call. Added error handling!

2024-04-04 18:08 UTC, jlf0dev submitted a review, later dismissed

2024-04-10 19:44 UTC, MGibson1 commented on libs/common/src/platform/services/user-key-init.service.ts
> +// after the vault timeout settings svc is transitioned to state provider so that
please avoid these abbreviated words.

```suggestion
// after the vault timeout settings service is transitioned to state provider so that
```

2024-04-10 19:44 UTC, MGibson1 commented on libs/common/src/platform/services/user-key-init.service.ts
> +              // Returning EMPTY to protect obs chain from cancellation in case of error
Please avoid these abbreviations
```suggestion
              // Returning EMPTY to protect observable chain from cancellation in case of error
```

2024-04-10 20:02 UTC, MGibson1 requested changes
The only pattern I'm not 100% on is the `userKeyInitService.listenForActiveUserChangesToSetUserKey`

It would be possible to wire into the switch account logic in desktop + browser to support rather than shoehorning a side effect in this manner @justindbaur, what is your take on this?

2024-04-10 20:02 UTC, MGibson1 commented on libs/common/src/auth/services/auth.service.ts
> +    return hasUserKey ? AuthenticationStatus.Unlocked : AuthenticationStatus.Locked;
**issue**: This doesn't seem quite right to me. My understanding is that this improvement means that the in-memory representation is aggressively set by the `UserKeyInitService` and other `InitService`s. We therefore shouldn't have to check the auto key to determine auth status, correct?

2024-04-10 20:06 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/auth.service.ts
> +    return hasUserKey ? AuthenticationStatus.Unlocked : AuthenticationStatus.Locked;
That's a good point. I've updated the check to simply check memory.

2024-04-10 20:08 UTC, JaredSnider-Bitwarden commented on libs/common/src/platform/services/user-key-init.service.spec.ts
> +
Removed.

2024-04-10 20:35 UTC, jlf0dev commented on libs/common/src/platform/services/crypto.service.ts
> -    let userKey = await firstValueFrom(this.stateProvider.getUserState$(USER_KEY, userId));
We could probably remove the check for auto key storage in this PR, since the crypto service should only care about memory, but moving all references to the biometrics service is a little bit more. We might want to keep this PR slim, but that work will be a nice followup

2024-04-10 20:35 UTC, jlf0dev commented on libs/common/src/platform/services/crypto.service.ts
> -    let userKey = await firstValueFrom(this.stateProvider.getUserState$(USER_KEY, userId));
We should probably remove the auto key check, but transitioning all the checks for the biometrics key is probably too much for this PR. We don't even have that logic in the biometrics service yet.

2024-04-10 22:25 UTC, JaredSnider-Bitwarden commented on libs/common/src/platform/services/crypto.service.ts
> -    let userKey = await firstValueFrom(this.stateProvider.getUserState$(USER_KEY, userId));
Ok, I've updated the `hasUserKey` method to no longer check for the auto user key.

2024-04-11 14:59 UTC, justindbaur commented
> would be possible to wire into the switch account logic in desktop + browser

@MGibson1 @JaredSnider-Bitwarden 

Not against it, I only worry that switch account isn't called for the very initial account so some logic would have to be put somewhere else as well.

In the long term though, I think _a_ side effect is needed to make this work properly, it just wouldn't be _this_ side effect. 

I think we will want a `getUserKey$` method that is able to know where the underlying storage location of the user key is and return it no matter what if it's available. Then we will need a side effect on vault timeout settings changes so that we can `updateStoredLocationIfNeeded` whenever those settings change for a user. That's why I thought this side effect for now is fine. Putting this logic in the switch account logic feels much more shoehorning to me than changing this to react to something. Which is where I think we want to go.

2024-04-11 15:43 UTC, MGibson1 commented
>Not against it, I only worry that switch account isn't called for the very initial account so some logic would have to be put somewhere else as well.

It's already in the `InitService` of each client, which is where the first account would be inited

>I think we will want a getUserKey$ method that is able to know where the underlying storage location of the user key is and return it no matter what if it's available

This is actually the opposite of what I want -- I want to have one valid place to look for a user key for decrypting items. I do think that auto keys are basically the disk storage of the user key, but whether or not we should store is handled by external forces, which complicates things and necessitates an external handler of the disk. That's why I'd like to aggressively set auto keys and separate handling of disk-stored user keys (auto keys) from in-memory user keys to separate services.

2024-04-11 17:40 UTC, justindbaur commented
> It's already in the `InitService`

The change in this PR is, I thought you wanted it in the `switchAccount` logic, like here:

https://github.com/bitwarden/clients/blob/c2b91d2d46c0d31aef46559643063765b575a85a/apps/browser/src/background/main.background.ts#L1121

That's what I am less sure of running on initial account load.

> I want to have one valid place to look for a user key for decrypting items

Totally agree, I do too.

> I do think that auto keys are basically the disk storage of the user key, but whether or not we should store is handled by external forces, which complicates things

Also, completely agree. 

> necessitates an external handler of the disk

I break down slightly here, yes _something_ needs to handle the migration of user key when changes happen to their vault timeout settings, that would be what a `updateStoredLocationIfNeeded` would be, it would be a side effect always subscribed to vault timeout settings changes. It handle both the disk state and the memory state based on the changes it cares about. What service that method exists on doesn't really matter to me all that much. 

> That's why I'd like to aggressively set auto keys and separate handling of disk-stored user keys (auto keys) from in-memory user keys to separate services.

I don't totally get the need for aggressively setting in into memory, I'm not strictly against it but I'd just rather it's "memory" be in a `shareReplay` or something. 

```typescript
class UserKeyService {
  getUserKey$(userId: UserId) {
    return this.sp.getUser(userId, USER_KEY_LOCATATION).combinedState$
      .pipe(switchMap(([userId, location]) => {
        // pipe on disk state if you want your own share replay that has it in memory more often
        return location === "disk"     
          ? this.sp.getUser(userId, USER_KEY_DISK).state$
          : this.sp.getUser(userId, USER_KEY_MEMORY).state$;
      });
      // Maybe distinctUntilChanged since you will change the location without changing the actual value
  }

  // Would be ran inside of a side effect subscription to vault timeout settings with a `pairwise` operator on it most likely.
  async updateStoredLocationIfNeeded(userId: UserId, oldVaultTimeoutSettings: VaultTimeoutSettings, newVaultTimeoutSettings: VaultTimeoutSettings) {
    if (changedToNever()) {
      // get from memory
      // save to disk
      // Update location state
      await this.getUser(userId, USER_KEY_LOCATION).update(() => "disk");
      // clear memory
    } else if (changedFromNever()) {
      // get from disk
      // save to memory
      // Update location state
      // Update location state
      await this.getUser(userId, USER_KEY_LOCATION).update(() => "memory");
      // clear disk
    }
  }
}
```

Whether `getUserKey$` and `updateStoredLocationIfNeeded` are in the same class don't really matter to me. Whether getting the user key from disk vs in memory are also in their own class don't really matter to me either. 

But the main point to me, regarding this current PR is that there should probably be _a_ side effect in play here. I don't think it should on active user changes long term myself but it's the world we live in and moving directly into the `switchAccount` logic feels like the exact place we don't want to go with reactivity.

2024-04-16 20:14 UTC, MGibson1 commented
@justindbaur I agree on all accounts except that we don't currently have a side effect framework. My intent was a temporary solution while we don't have one. I'm definitely on board with everything you're describing.

2024-04-17 02:24 UTC, JaredSnider-Bitwarden commented
> @JaredSnider-Bitwarden Based on the above comment, I do remember that I don't actually plan for side effects to run in browser `InitService` and instead would expect them to be ran in `MainBackground`. Could you try registering the side effect in the `bootstrap` method there and make sure everything works as expected?

@justindbaur, I registered the listener in the `main.background`, and it worked on account switch and app refresh. Should be good to go. Here's a video of the behavior: 

https://github.com/bitwarden/clients/assets/116684653/74321358-2e3e-492d-9729-be5868d758fc

2024-04-18 20:58 UTC, justindbaur approved these changes
Looks great, thanks for even writing tests for our code.

2024-04-19 12:44 UTC, jlf0dev approved these changes

2024-04-19 15:20 UTC, merged