[AC-1586] individual reports filter
bitwarden/clients pull request #8598
Opened 2024-04-03 16:04 UTC by Jingo88

```
- [ ] Bug fix
- [ x ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

* Add header to individual reports for `Name` and `Owner`
* Add toggle filter to individual reports based on Owners
* These will only show in individual and will not impact AC reports
* User can toggle between different owners on all reports
* If user removes all reported items of an owner that owner button will be removed from the toggle

## Code changes

* Added `I18nService` to `cipher report` constructor and all supers
* Added `isAdminConsoleActive` to `cipher report` and all `admin console reports` to ensure filter DOM elements do not load on AC reports
* `cipher report` - Added variables and logic for the filtering by owner and toggling in the reports components
* `reports html` - all the same elements added throughout. these are for the `Name+Owner` header as well as the `toggle group` for filtering by owner
* `reports components` - each report has had logic added to it's reported ciphers list to determine whether we show the filter toggle, and to generate the toggle values dynamically

## Screen Recording of Flow and Screenshot

https://github.com/bitwarden/clients/assets/8302660/3760a7a0-7410-48e2-949a-574e0e3b2286

Screenshot showing no filter if ciphers in reports tab only has one owner

![Screenshot 2024-04-03 at 11 44 32 AM](https://github.com/bitwarden/clients/assets/8302660/ac537709-e320-4118-bb5e-6759815c5634)

2024-04-08 20:34 UTC, addisonbeck approved these changes

2024-04-09 17:50 UTC, aj-rosado requested changes
Great work overall. I would just like move the ciphers mapping into the `CipherReportComponent` to avoid code duplication as it is used by all the components

2024-04-09 17:50 UTC, aj-rosado commented on apps/web/src/app/tools/reports/pages/exposed-passwords-report.component.ts
> +      if (this.filterStatus.length > 2) {
This should be outside the map

2024-04-09 17:50 UTC, aj-rosado commented on apps/web/src/app/tools/reports/pages/inactive-two-factor-report.component.ts
> +      this.ciphers = inactive2faCiphers.map((ciph: any) => {
We are doing this operation in all the reports, this could be moved to the parent component and all the child  components can simply call it to avoid code duplication

2024-04-10 07:26 UTC, Hinton requested changes
Hey, we had a discussion in the #code channel on slack recently about observables, I think this demonstrates some of the dangers and we should refactor this since it may cause significant performance impact and relies on some internal assumptions about rxjs that may not be true.

Feel free to ping me on slack or schedule a time if you want to do some pair programming on this.

2024-04-10 07:26 UTC, Hinton commented on apps/web/src/app/tools/reports/pages/cipher-report.component.ts
> +      });
It looks like you are subscribing to an observable inside a function that gets called from the template.

1. This will be called repetedly causing a lot of subscriptions to the observable which will effect performance.
2. Subscribe can't return values, and it's not adviceable to do an object assignment here since there is no guarantee `orgName = org.name` will run before the function returns. While it looks to be working currently it relies on internal assumptions of the rxjs library.

2024-04-10 07:26 UTC, Hinton commented on apps/web/src/app/tools/reports/pages/cipher-report.component.ts
> +      });
I think you have a few different options here, you can refactor filters to be an observable and data driven, this would look something like this in the template:

```html
<bit-toggle-group
  *ngIf="showFilterToggle && !isAdminConsoleActive"
  [selected]="filterOrgStatus"
  (selectedChange)="filterOrgToggle($event)"
  [attr.aria-label]="'addAccessFilter' | i18n"
  *ngIf="filters as filter$"
>
  <bit-toggle  *ngFor="let filter of filters" [value]="filter.value">
      {{ filter.name }}
  </bit-toggle>
</bit-toggle-group>
```
Unfortunately the filters themselves aren't reactive so this might be a bit clunky.

Another alternative is to subscribe to the organization list in the constructor or ngOnInit and store a variable of `organizations` that are referenced.

2024-04-10 17:29 UTC, Jingo88 commented on apps/web/src/app/tools/reports/pages/inactive-two-factor-report.component.ts
> +      this.ciphers = inactive2faCiphers.map((ciph: any) => {
I've consolidated the code to be in the parent component. Thank you!

2024-04-10 17:31 UTC, Jingo88 commented on apps/web/src/app/tools/reports/pages/cipher-report.component.ts
> +      });
Thanks for the review. I totally missed that template call. I've updated the `organizations$` logic to live in the constructor and populate a new `organizations` variable.

2024-04-11 09:05 UTC, Hinton submitted a review, later dismissed
Observable usage is fixed, I haven't reviewed the rest of the PR.

2024-04-11 12:24 UTC, addisonbeck approved these changes

2024-04-11 15:30 UTC, aj-rosado approved these changes

2024-04-11 15:32 UTC, aj-rosado submitted a review, later dismissed
Thank you for making the changes. LGTM

2024-04-30 19:15 UTC, aj-rosado requested changes

2024-04-30 19:15 UTC, aj-rosado commented on apps/web/src/app/tools/reports/pages/cipher-report.component.ts
> +  getOrgValues(filterId: string | number, type: string) {
believe having this method perform two different operations (return the number of ciphers and the name) makes it more confusing, we should separate this into two different method, would turn the method(s) simpler.
 
This way would not need to perform unnecessary operation (we are always calculating the number of items and getting the name, does not matter if it is not necessary)
And would make the `type` argument unnecessary, making it clearer when calling.

2024-04-30 20:24 UTC, aj-rosado approved these changes
LGTM

2024-04-30 21:29 UTC, addisonbeck approved these changes

2024-05-01 14:39 UTC, merged