Auth/pm 5501/vault timeout settings service state provider migration v2
bitwarden/clients pull request #8604
Opened 2024-04-03 21:07 UTC by JaredSnider-Bitwarden

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-04-17 18:12 UTC, jlf0dev reviewed
Great job! Just had some comments on the service itself but everything else looks good

2024-04-17 20:42 UTC, JaredSnider-Bitwarden commented on libs/common/src/services/vault-timeout/vault-timeout-settings.service.ts
> +            // We want to avoid having a null timeout action always so we set it to the default if it is null
I clarified that the tap is fed by the determine methods in both get methods.

2024-04-17 20:42 UTC, JaredSnider-Bitwarden commented on libs/common/src/services/vault-timeout/vault-timeout-settings.service.ts
> +      if (currentVaultTimeout == null || policyCompliantTimeout < 0) {
Good call! Done!

2024-04-17 20:42 UTC, JaredSnider-Bitwarden commented on libs/common/src/services/vault-timeout/vault-timeout-settings.service.ts
> +    if (maxVaultTimeoutPolicy) {
Good call! Done!

2024-04-17 20:42 UTC, JaredSnider-Bitwarden commented on libs/common/src/services/vault-timeout/vault-timeout-settings.service.ts
> +  ): Promise<void> {
Good call! Done!

2024-04-17 20:42 UTC, JaredSnider-Bitwarden commented on libs/common/src/services/vault-timeout/vault-timeout-settings.service.ts
> +  ): Promise<void> {
Thank you for catching the missing `userId` validation!

2024-04-18 20:59 UTC, jlf0dev approved these changes
👏

2024-04-23 21:49 UTC, JaredSnider-Bitwarden commented
Additional context for reviewers as to why we had to make more changes:  
- @justindbaur discovered that we had client specific default values on account initialization for the vault timeout. I had to rework the vault timeout retrieval to respect the client specific default.  While doing so and while testing the changes, I realized that I needed to rework the default logic for the vault timeout action to ensure the previous default of lock was respected.

2024-04-24 15:24 UTC, cagonzalezcs commented on apps/browser/src/popup/settings/settings.component.ts
> +      // { name: i18nService.t('onSleep'), value: "onSleep" },
Nit - Should this be removed?

2024-04-24 15:24 UTC, cagonzalezcs commented on libs/angular/src/components/settings/vault-timeout-input.component.ts
> +      }
```suggestion
      }
        
      // Exclude all string cases when there's a numeric policy defined
      return false;
```

Nit - you don't really need this `else` branch. The early returns above this statement make it irrelevant

2024-04-24 17:17 UTC, JaredSnider-Bitwarden commented on apps/browser/src/popup/settings/settings.component.ts
> +      // { name: i18nService.t('onSleep'), value: "onSleep" },
Cleaned up the commented out options on browser and desktop!

2024-04-24 23:56 UTC, JaredSnider-Bitwarden commented on apps/browser/src/background/main.background.ts
> +      "onRestart", // default vault timeout
Thank you for showing me the way to handle this! Updated everything to reference the new const!

2024-04-25 14:43 UTC, cagonzalezcs approved these changes

2024-04-30 20:32 UTC, JaredSnider-Bitwarden commented
Further notes for reviewers, we had more work to do because we discovered that the CLI wasn't setting a vault timeout so we had to enable migrations to have access to the client type they were executing on so we could successfully migrate the CLI's undefined vault timeouts to the new `"never"` value. I tested logging in on `main` in the CLI, and swapping over to this branch, and I ensured that the migration was seamless with the user's vault still being unlocked properly.

2024-04-30 20:41 UTC, cagonzalezcs approved these changes
A coupe of small nits, but not blocking for them. Nice work on this.

2024-04-30 20:41 UTC, cagonzalezcs commented on apps/browser/src/background/main.background.ts
> +      VaultTimeoutStringType.OnRestart, // default vault timeout
🎉

2024-04-30 20:41 UTC, cagonzalezcs commented on libs/common/src/types/vault-timeout.type.ts
> +export const VaultTimeoutStringType = {
```suggestion
export const VaultTimeoutType = {
```
Maybe there's some distinct reason we're adding the explicitly state "String" data type here... but wouldn't it normally be extraneous information that is unnecessary to be concerned about?

2024-04-30 20:41 UTC, cagonzalezcs commented on apps/web/src/app/core/core.module.ts
> +      platformUtilsService.isDev() ? VaultTimeoutStringType.Never : 15,
Should this hardcoded `15` value also reference an enum?

2024-04-30 20:50 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/core/core.module.ts
> +      platformUtilsService.isDev() ? VaultTimeoutStringType.Never : 15,
I think you are correct that it and the settings / preferences components across our clients should reference a numeric enum for all the default timeouts that we show to the user. However, that's continuing to expand the scope of the PR into more tech debt than I want to tackle right now. I have created a tech debt ticket for this [PM-7841](https://bitwarden.atlassian.net/browse/PM-7841) for us to tackle later! Thank you for pointing it out!

2024-04-30 22:31 UTC, MGibson1 requested changes
Very small clarity changes requested for now. I'd like to spend some more time on understanding the new vault-timeout service, but this is looking like a _huge_ cleanup of that area. thank you

2024-04-30 22:31 UTC, MGibson1 commented on apps/web/src/app/core/state/account.ts
🥳

2024-04-30 22:31 UTC, MGibson1 commented on libs/auth/src/common/login-strategies/auth-request-login.strategy.spec.ts
> +    const mockVaultTimeout = 1000;
This doesn't cause 1 second delays, does it?

2024-04-30 22:31 UTC, MGibson1 commented on libs/common/src/types/vault-timeout.type.ts
😍

2024-04-30 22:31 UTC, MGibson1 commented on libs/auth/src/common/login-strategies/login.strategy.ts
> +    );
How are these populated with default values on first login?

2024-04-30 22:31 UTC, MGibson1 commented on libs/common/src/state-migrations/migrations/61-migrate-vault-timeout-settings-svc-to-state-provider.ts
> +  // DirectoryConnector = "connector",
I think these commented values are here to indicate they exist, too, but an explanation is warranted.

2024-04-30 22:31 UTC, MGibson1 commented on libs/common/src/state-migrations/migrations/61-migrate-vault-timeout-settings-svc-to-state-provider.ts
> +    // await Promise.all([...accounts.map(({ userId, account }) => migrateAccount(userId, account))]);
Remove commented code and comment below explaining it

2024-05-01 02:31 UTC, JaredSnider-Bitwarden commented on libs/auth/src/common/login-strategies/auth-request-login.strategy.spec.ts
> +    const mockVaultTimeout = 1000;
No, it's just a randomly picked numeric value to be returned for the sake of the tests. Further, the vault timeout value is always in minutes but the test suite runs near instantly.

2024-05-01 02:36 UTC, JaredSnider-Bitwarden commented on libs/auth/src/common/login-strategies/login.strategy.ts
> +    );
Vault timeout is defaulted via the `DEFAULT_VAULT_TIMEOUT` injection token and then applied in the `VaultTimeoutSettingsService`'s `determineVaultTimeout(...)` method when the vault timeout is null from state.

Vault timeout action is defaulted via the `VaultTimeoutSettingsService`'s `determineVaultTimeoutAction(...)` method to `lock` if no policy applies and the state value is null.  It used to be set to lock via the account init and then modified in the previous implementation.

2024-05-01 02:38 UTC, JaredSnider-Bitwarden commented on libs/common/src/state-migrations/migrations/61-migrate-vault-timeout-settings-svc-to-state-provider.ts
> +  // DirectoryConnector = "connector",
Hmm... it's copy pasta from the real client type enum. I've removed them entirely.

2024-05-01 02:39 UTC, JaredSnider-Bitwarden commented on libs/common/src/state-migrations/migrations/61-migrate-vault-timeout-settings-svc-to-state-provider.ts
> +    // await Promise.all([...accounts.map(({ userId, account }) => migrateAccount(userId, account))]);
That was an accidental check in of a change I made to make it easier to debug the migration. Thank you for catching that. I've reverted it back to use `Promise.all`!

2024-05-01 15:15 UTC, cagonzalezcs commented on libs/common/src/types/vault-timeout.type.ts
> +export const VaultTimeoutStringType = {
Hm, I think given the circumstances behind switching from one data type to another, it makes sense to be more explicit here. 

I guess the ideal would be to eventually refactor out the `number` data type, right? Regardless, I think keeping the current structure in place makes sense.

2024-05-01 15:15 UTC, cagonzalezcs submitted a review, later dismissed

2024-05-02 17:47 UTC, jlf0dev approved these changes
Fantastic work, adding the new vault timeout type makes everything so much more readable. I had a couple questions and nits, but nothing blocking 👏

2024-05-02 17:47 UTC, jlf0dev commented on libs/common/src/services/vault-timeout/vault-timeout-settings.service.ts
> +    timeout: VaultTimeout | null,
Question: should this allow `null` still?

2024-05-02 17:47 UTC, jlf0dev commented on libs/common/src/services/vault-timeout/vault-timeout-settings.service.ts
> +  private async setVaultTimeoutAction(userId: UserId, action: VaultTimeoutAction): Promise<void> {
Question: should we check action for `null` here and throw?

2024-05-02 17:47 UTC, jlf0dev commented on libs/common/src/services/vault-timeout/vault-timeout-settings.service.ts
>        }
I know I wrote this, but can you change it to be:
```suggestion
      !!decryptionOptions.hasMasterPassword
```
The else you added below means that we'd return undefined.

2024-05-02 17:47 UTC, jlf0dev commented on libs/common/src/services/vault-timeout/vault-timeout-settings.state.ts
> + */
nit: Can you add a little more on why it needs to persist after logout?

2024-05-02 17:52 UTC, JaredSnider-Bitwarden commented on libs/common/src/services/vault-timeout/vault-timeout-settings.service.ts
> +    timeout: VaultTimeout | null,
Nope! Great catch! Ty!

2024-05-02 18:02 UTC, JaredSnider-Bitwarden commented on libs/common/src/services/vault-timeout/vault-timeout-settings.service.ts
> +  private async setVaultTimeoutAction(userId: UserId, action: VaultTimeoutAction): Promise<void> {
Fixed and tested! Great suggestion!

2024-05-02 18:06 UTC, JaredSnider-Bitwarden commented on libs/common/src/services/vault-timeout/vault-timeout-settings.state.ts
> + */
Done!

2024-05-02 18:19 UTC, JaredSnider-Bitwarden commented on libs/common/src/services/vault-timeout/vault-timeout-settings.service.ts
>        }
Ah, good catch. Done!

2024-05-02 18:24 UTC, jlf0dev approved these changes

2024-05-13 16:27 UTC, MGibson1 approved these changes

2024-05-13 16:38 UTC, jprusik approved these changes

2024-05-13 17:20 UTC, jlf0dev commented on libs/common/src/auth/services/token.service.ts
> +    }
nit:
```suggestion
    // Can't check for falsey b/c 0 is a valid value
    if (vaultTimeout == null) {
      throw new Error("Vault Timeout is required.");
    }
```

2024-05-13 17:20 UTC, jlf0dev commented on libs/common/src/auth/services/token.service.ts
> +    }
suggestion: would be nice to have a nullish check for `vaultTimeoutAction` as well.

2024-05-13 17:20 UTC, jlf0dev commented on libs/common/src/auth/services/token.service.ts
> +    vaultTimeout: VaultTimeout | null,
Question: are all these `VaultTimeout | null` in the service and abstraction accurate? I thought we're not allowing that here anymore

2024-05-13 17:47 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/token.service.ts
> +    }
Fixed

2024-05-13 17:47 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/token.service.ts
> +    }
Fixed

2024-05-13 17:47 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/token.service.ts
> +    vaultTimeout: VaultTimeout | null,
Thank you for catching that. I've removed them all.

2024-05-13 18:42 UTC, jlf0dev approved these changes

2024-05-13 18:58 UTC, MGibson1 approved these changes

2024-05-13 19:01 UTC, jprusik approved these changes

2024-05-13 19:56 UTC, merged