PM-2166 Update Purge vault dialog
bitwarden/clients pull request #8658
Opened 2024-04-10 05:40 UTC by KiruthigaManivannan

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other
```

## Objective

Migrate the Purge Vault component to use the component library.

## Code changes

- **purge-vault.component.html:** bit-dialog library added
- **purge-vault.component.ts:** Dialog open logic implemented
- **auth\settings\account\account.component.html:** Worked on async button click purgeVault
- **auth\settings\account\account.component.ts:** Purge vault dialog open using 
- **admin-console\organizations\settings\account.component.html:**Worked on async button click purgeVault
- **admin-console\organizations\settings\account.component.ts:**Purge vault dialog open using 

## Screenshots

Uploading My account _ Bitwarden Web vault - Google Chrome 2024-04-10 11-07-07.mp4…

2024-05-02 15:04 UTC, r-tome approved these changes
LGTM!

2024-05-15 23:41 UTC, rr-bw requested changes
Looking good from Auth, just fix the [eslint import order errors](https://github.com/bitwarden/clients/actions/runs/8626216551/job/23644065077?pr=8658) on `apps/web/src/app/auth/settings/account/account.component.ts`.

2024-05-16 21:06 UTC, rr-bw approved these changes

2024-05-17 08:40 UTC, r-tome approved these changes

2024-05-21 08:32 UTC, LRNcardozoWDF approved these changes

2024-05-21 13:07 UTC, merged