[AC-1218] Add ability to delete Provider Portals
bitwarden/clients pull request #8685
Opened 2024-04-10 22:52 UTC by cyprain-okeke

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Currently, there is no ability to delete Provider Portals. This functionality should be available from the internal Bitwarden Portal.

On the Provider page, there will be an option to delete the Provider at the bottom of the page. A Provider can only be deleted if no organizations are linked to the Provider.

Deleting from

[Bitwarden portal](https://www.figma.com/proto/m8eMk6yeKfOq4AUuyp70ih/Consolidated-Billing?page-id=698%3A10060&type=design&node-id=1171-18005&viewport=-11087%2C521%2C0.25&t=tpHXkqSav41X2FCa-1&scaling=min-zoom&starting-point-node-id=1399%3A12380&show-proto-sidebar=1&mode=design)

[Provider portal - attempting to delete with clients](https://www.figma.com/proto/m8eMk6yeKfOq4AUuyp70ih/Consolidated-Billing?page-id=698%3A10060&type=design&node-id=1309-18496&viewport=-11087%2C521%2C0.25&t=tpHXkqSav41X2FCa-1&scaling=min-zoom&starting-point-node-id=1309%3A18496&show-proto-sidebar=1&mode=design)

[Provider portal - deleting without clients](https://www.figma.com/proto/m8eMk6yeKfOq4AUuyp70ih/Consolidated-Billing?page-id=698%3A10060&type=design&node-id=1710-15961&viewport=-11087%2C521%2C0.25&t=tpHXkqSav41X2FCa-1&scaling=min-zoom&starting-point-node-id=1710%3A15961&show-proto-sidebar=1&mode=design)

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-04-11 00:46 UTC, trmartin4 commented
🤔 We have ongoing work (https://bitwarden.atlassian.net/browse/PM-1943) to migrate the `verify-recover-delete` component to use Tailwind and new reactive form patterns.  If we add a new component here we will need to migrate it as well or introduce the new component using the new patterns.

2024-04-12 00:26 UTC, ike-kottlowski reviewed
Everything looks good. But should this be owned by AC? I'm not sure it's within the scope of Auth.

I think this is similar to[ this PR](https://github.com/bitwarden/clients/pull/8445#pullrequestreview-1956828876) which has a comment that poses the same question.

2024-04-15 12:23 UTC, justindbaur approved these changes

2024-04-15 15:00 UTC, amorask-bitwarden requested changes
This doesn't look like the correct wording to me. We're deleting the Provider, not the Bitwarden account. Once you complete this action, the account is still active so this is somewhat confusing.

![Screenshot 2024-04-15 at 10 58 10 AM](https://github.com/bitwarden/clients/assets/144709477/f1a37796-aecd-48f4-a1b6-aebff560270e)

2024-04-15 15:18 UTC, cyprain-okeke commented
> This doesn't look like the correct wording to me. We're deleting the Provider, not the Bitwarden account. Once you complete this action, the account is still active so this is somewhat confusing.
> 
> ![Screenshot 2024-04-15 at 10 58 10 AM](https://private-user-images.githubusercontent.com/144709477/322528180-f1a37796-aecd-48f4-a1b6-aebff560270e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxOTM1NzAsIm5iZiI6MTcxMzE5MzI3MCwicGF0aCI6Ii8xNDQ3MDk0NzcvMzIyNTI4MTgwLWYxYTM3Nzk2LWFlY2QtNDhmNC1hMWI2LWFlYmZmNTYwMjcwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQxNTAxMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzI1YzljNmZkMDA2ZGE4MmJjMzNlY2E5ZDExZWUxODNkNjhhMTU4OTRhZDkwMGRiZWExMjI0OTIxMzBlOGQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.e5wOoZcw1nu3N5--e_-tf8v2rQrAms_AMISBTr_ebsc)

2024-04-15 20:43 UTC, justindbaur submitted a review, later dismissed

2024-04-16 11:25 UTC, r-tome requested changes
Looks great, just a couple of things I'd like to see adressed.

2024-04-16 11:25 UTC, r-tome commented on apps/web/src/app/admin-console/providers/verify-recover-delete-provider.component.ts
> +        this.router.navigate(["/"]);
```suggestion
        await this.router.navigate(["/"]);
```
Await this and you don't have to disable the eslint rule

2024-04-16 11:25 UTC, r-tome commented on apps/web/src/app/admin-console/providers/verify-recover-delete-provider.component.ts
> +      this.router.navigate(["/"]);
Same thing here, await the promise

2024-04-16 13:51 UTC, cyprain-okeke commented on apps/web/src/app/admin-console/providers/verify-recover-delete-provider.component.ts
> +        this.router.navigate(["/"]);
resolved

2024-04-16 13:51 UTC, cyprain-okeke commented on apps/web/src/app/admin-console/providers/verify-recover-delete-provider.component.ts
> +      this.router.navigate(["/"]);
resolved

2024-04-16 14:52 UTC, cyprain-okeke commented on libs/common/src/services/api.service.ts
> +  providerRecoverDeleteToken(
this has been move` provider-api.service`

2024-04-16 15:12 UTC, r-tome submitted a review, later dismissed
Nice work! Thanks for the changes!

2024-04-16 15:37 UTC, amorask-bitwarden submitted a review, later dismissed

2024-04-16 17:41 UTC, r-tome approved these changes

2024-04-16 18:57 UTC, justindbaur approved these changes

2024-04-16 19:13 UTC, JaredSnider-Bitwarden reviewed
Nice work on this. I skimmed through it quickly and focused on the use of the `UserVerificationDialogComponent` that we discussed. 2 nits and a small warning.

2024-04-16 19:13 UTC, JaredSnider-Bitwarden commented on apps/web/src/locales/en/messages.json
> +    "placeholders": {
Nit: the translation doesn't have a placeholder in it? Should the translation have this section?

2024-04-16 19:13 UTC, JaredSnider-Bitwarden commented on libs/common/src/admin-console/models/request/provider/provider-verify-delete-recover.request.ts
> +export class ProviderVerifyDeleteRecoverRequest {
Nit: the process and components are all called `RecoverDelete` not `DeleteRecover`. Should they match for clarity?

2024-04-16 19:13 UTC, JaredSnider-Bitwarden commented on bitwarden_license/bit-web/src/app/admin-console/providers/settings/account.component.ts
> +      }
⚠️ this block is not possible unless you are passing `{ ...,  clientSideOnlyVerification: true }` in the `UserVerificationDialogOptions`. So, you can remove it.

2024-04-16 19:16 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/admin-console/providers/verify-recover-delete-provider.component.html
> +              <span>{{ "deleteAccount" | i18n }}</span>
❓ Should this button still say delete account?  Or should it say delete provider?

2024-04-16 20:01 UTC, cyprain-okeke commented on libs/common/src/admin-console/models/request/provider/provider-verify-delete-recover.request.ts
> +export class ProviderVerifyDeleteRecoverRequest {
resolved

2024-04-16 20:04 UTC, cyprain-okeke commented on apps/web/src/locales/en/messages.json
> +    "placeholders": {
removed the placeholders until we are able to get UserVerificationDialogComponent to work with placeholders

2024-04-16 20:09 UTC, cyprain-okeke commented on bitwarden_license/bit-web/src/app/admin-console/providers/settings/account.component.ts
> +      }
I have removed this as suggested although this part of the code was changed during the provider delete implementation.

2024-04-16 20:11 UTC, JaredSnider-Bitwarden approved these changes
💯 !

2024-04-16 20:13 UTC, justindbaur approved these changes

2024-04-17 08:54 UTC, r-tome approved these changes

2024-04-17 11:33 UTC, justindbaur approved these changes

2024-04-17 13:00 UTC, amorask-bitwarden approved these changes

2024-04-17 13:07 UTC, merged