[SM-956] Secret Manager: Integrations Page
bitwarden/clients pull request #8701
Opened 2024-04-11 16:10 UTC by nick-livefront

Draft: I have an open question about which SDKs should be marked as "new" in the ticket.

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Add Integrations page within Secrets manager than links to internal integrations or SDKs available on GitHub.h

## Code changes

- **messages.json**: Added needed copy
- **images/secret-manager/***: Added all language & integration images within a `secrets-manager/` folder
- **integration-card/***: Card component to link to an Integration or SDK
  - I used a pseudo element to cover the entire card as clickable but the link will still only be accessible via keyboard/screen reader rather than the entire card. 
  - The `new` badge is driven by a client side time comparison. This could be done manually or by other means!
- **integration-grid/***: Arranges individual cards into a grid based on the designs
- **integrations/***: Markup & constant data for the Integrations page

## Screenshots

![image](https://github.com/bitwarden/clients/assets/125900171/ed3d4d5c-d214-4801-b582-8b394f251438)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-04-12 20:25 UTC, differsthecat reviewed
This looks really good, thank you @nick-livefront !
I only have a few small feedback items 🙂

2024-04-15 14:33 UTC, nick-livefront commented on apps/web/src/locales/en/messages.json
> +  },
@differsthecat Great point, I was pondering how "Go" was going to be translated or not translated. Hardcoding them makes sense to me!
[cc58db9](https://github.com/bitwarden/clients/pull/8701/commits/cc58db91ebf73ea74824252dc71bef5cfd600f71)

2024-04-17 15:25 UTC, cd-bitwarden requested changes
This looks really great! I just left one suggestion, and I'm waiting to see that the Github dark mode image is added :)

2024-04-17 15:25 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/integrations/integration-grid/integration-grid.component.html
> +      [externalURL]="integration.type === 'sdk'"
Should we store the 'sdk' and other strings relating to integration type into an enum just in case we change this value in the future to be SDK instead of sdk?

2024-04-18 03:28 UTC, nick-livefront commented on bitwarden_license/bit-web/src/app/secrets-manager/integrations/integration-grid/integration-grid.component.html
> +      [externalURL]="integration.type === 'sdk'"
👍 I like the suggestion, it also helps if other integration types are added too

[361c820](https://github.com/bitwarden/clients/pull/8701/commits/361c820e0d26aa7c489b93add0ce472c8eb56cf3)

2024-04-18 03:30 UTC, nick-livefront commented on apps/web/src/images/secrets-manager/integrations/github.svg
I got the dark mode images added. GitHub, GitLab & Java were the only ones that were swapped.

I didn't see any other examples within the codebase to do theme manipulation with JavaScript which kind of surprised me. If there is another pattern to follow that I missed, let me know!

[2fcaa31](https://github.com/bitwarden/clients/pull/8701/commits/2fcaa31384c8e2f00cf3942b5a5904f79b66c02a) & [a057ff5](https://github.com/bitwarden/clients/pull/8701/commits/a057ff5301777b45c6ea3c0c6c50d402a0afb847)

2024-04-18 13:21 UTC, differsthecat commented on apps/web/src/images/secrets-manager/integrations/github.svg
Awesome! 
Yeah, this is the first time we are doing something like this that I am aware of. I looked through our code as well and didn't see anything. I do like your approach!

2024-04-18 13:22 UTC, differsthecat commented
This is good on my end, @nick-livefront I did pull main and resolved the conflicts that were present in the messages.json file 🙂

2024-04-18 13:38 UTC, cd-bitwarden approved these changes
Loogs great! Thank you :)

2024-04-18 14:43 UTC, nick-livefront commented
> This is good on my end, @nick-livefront I did pull main and resolved the conflicts that were present in the messages.json file 🙂

@differsthecat Thank you!

2024-04-18 19:24 UTC, merged