Introduce `MessageSender` & `MessageListener`
bitwarden/clients pull request #8709
Opened 2024-04-11 18:48 UTC by justindbaur

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

The main goal is to establish that if you are using `MessagingService`/`MessageSender` and calling `.send` your message will go to the `MessageListener`/`BroadcasterService` in ANY other context of that particular Bitwarden application. That would be any other popup and the background page/service worker in the browser application and the renderer process and main process of the desktop application. 

`MessagingService` still exists after this PR but only as a re-export and rename of `MessageSender` since `MessageSender.send` contains a roughly equivalent method as the old `MessagingService.send` this resulted in having to change very few call sites. I will make team specific PR's to remove the old name and location once this PR merges. 

## Interesting Changes

### RuntimeBackground

This is the highest concentration of changes that I _didn't_ want to have to make, so please look over it carefully. I moved some messages out of the `processMessage` the criteria for the messages that moved was that they made use of the `chrome.runtime.MessageSender` parameter or the ability to respond to a message. Those messages were moved into a `processMessageWithSender` method that is wired up DIRECTLY to `chrome.runtime.onMessage.addListener`. The rest of the messages are wired up through a `MessageListener`, this will listen to messages both from `chrome.runtime.onMessage` and locally within the background context through a subject (instead of the function attached to `self`). 

### Browser AppComponent

Switched from listening to the `ZonedMessageListenerService` and a function `bitwardenPopupMainMessageListener` on `self` to just `MessageListener`. `MessageListener` in the browser popup is a combined listener that listens to the local subject, which replaces `bitwardenPopupMainMessageListener`, and `ChromeMessageListener`, which replaces `ZonedMessageListenerService`. The `ChromeMessageListener` that is created in the popup is also given the `runInAngular` pipe customization so that all the messages from chrome will run in the `NgZone`.

### Dependency Injection Points

The other important changes are mostly in dependency injection areas.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-04-11 20:24 UTC, cagonzalezcs commented on apps/browser/src/background/runtime.background.ts
> +      void this.processMessageWithSender(msg, sender).catch((err) =>
Is there a reason for why we're setting up two different ways of processing these messages?

2024-04-11 20:24 UTC, cagonzalezcs commented on apps/browser/src/platform/messaging/chrome-message.listener.ts
> +          if (!("webExtSender" in message)) {
What purpose does this property have? The message sender is sent to the chrome.runtime.onMessage handler in an use cases (even within content scripts).

2024-04-11 20:24 UTC, cagonzalezcs commented on apps/browser/src/background/nativeMessaging.background.ts
> +          this.runtimeBackground.processMessage({ command: "unlocked" });
Nit - It might be worth considering avoiding this kind of approach to triggering logic that is meant to also be triggered by a message.

Given that this executes in the same background context as the runtimeBackground class, it makes sense to instead extrapolate the logic used for the "unlocked" command to a separate service or class, and call that in both of these two contexts. 

To be fair, that's definitely a longer way to accomplish the same thing... but I just feel that calling a message handler directly in this manner is a strange.

2024-04-11 20:24 UTC, cagonzalezcs commented on apps/browser/src/background/main.background.ts
> -    })();
🎉

2024-04-11 20:24 UTC, cagonzalezcs commented on apps/browser/src/platform/messaging/chrome-message.listener.ts
> +          message ??= {};
Nice addition, I like it...

One consideration here, a message can of `any` type.... what would we want to do within this service if a message is not a `Record`? Should we even care?

2024-04-11 20:24 UTC, cagonzalezcs commented on apps/browser/src/platform/messaging/chrome-message.listener.ts
> +      fromChromeEvent(chrome.runtime.onMessage).pipe(
How would a `sendResponse` call function in this structure?

2024-04-11 20:24 UTC, cagonzalezcs commented on apps/browser/src/platform/messaging/chrome-message.sender.ts
> +        );
This likely will get chatty based on how messaging functions in the extension... might make sense to set this as a `debug` log instead of a warning.

2024-04-12 00:03 UTC, MGibson1 requested changes
This review is just of the sender/listener pattern for now, I still need to carefully look at the work done on individual messages.

The pattern used for message senders and listeners feels a bit object obsessed and results in [lazy classes](https://refactoring.guru/smells/lazy-class). Feels like this is probably due to aversion to creating method modules to produce observable sources/sinks for messages. We could then utilize a builder pattern on a sole message sender/listener class to register multiple sources/sinks created from (semi-)pure functions. A builder pattern for the message sender has the benefit of not requiring a noop, as well.

2024-04-12 00:03 UTC, MGibson1 commented on apps/browser/src/platform/background/service-factories/messaging-service.factory.ts
> +export {
Same jira ticket to remove?

2024-04-12 14:23 UTC, justindbaur commented on apps/browser/src/platform/messaging/chrome-message.listener.ts
> +      fromChromeEvent(chrome.runtime.onMessage).pipe(
It would not, non of our other clients have a `sendResponse` concept. The thinking is that anyone that requires the `sender` or `sendResponse` parameters should be using the chrome listener directly themselves. The `MessageSender` and `MessageListener` classes are for client agnostic uses of messaging.

2024-04-12 14:36 UTC, justindbaur commented on apps/browser/src/platform/messaging/chrome-message.listener.ts
> +          message ??= {};
Technically yes it can be `any` but in reality it's almost always an object of some sort because most of the entrypoints to sending a message will force a `command` property at the very least. Someone could still directly use the `chrome.runtime.sendMessage` method and pass in whatever but the logic in this `map` should still work fine. We just won't remap it into an object and we won't put the `"webExtSender"` property on it, which should both be perfectly fine outcomes.

2024-04-12 16:22 UTC, justindbaur commented on apps/browser/src/platform/messaging/chrome-message.listener.ts
> +          if (!("webExtSender" in message)) {
This is because the browser app component used to take take unhandled messages and push it through BroadcasterService here:

https://github.com/bitwarden/clients/pull/8709/files#diff-459b2c50ebcb1e13784a630d363fe2d324fcfea1a2ce9bcab7506a6ed29b1e0fL142-L143

`BroadcasterService` is now built using `MessageListener` and `MessageSender` under the hood so there isn't any need to pass the message itself through but it still wants the sender to be available.

2024-04-12 17:38 UTC, justindbaur commented on apps/browser/src/platform/messaging/chrome-message.sender.ts
> +        );
It shouldn't have been any more chatty than the errors we get for unhandled errors that give no context but yeah I can do this better. 

I decided to handle the two most common errors that through here and have a log with the command to the debug channel and then left the completely unknown errors going to the warning channel.

2024-04-12 17:40 UTC, justindbaur commented on libs/common/src/platform/messaging/subject-message.sender.ts
> +    payload: object | T = {},
That's because this is the implementation method of the other two overloads that are going to be generally shown. 

https://github.com/bitwarden/clients/pull/8709/files#diff-d726672f7e47ec2770a0252e480151b858bfe6f812329bc3fa2dcc1305bf0200R18-R41

Those two overloads are what give it the type safety if using a ~`messageDefinition`~ `commandDefinition` and leaves it as the wild west if using a `string`.

2024-04-12 17:42 UTC, justindbaur commented on libs/common/src/platform/messaging/message.listener.ts
> +  constructor(private readonly messages: Observable<Message<object>>) {}
I went with `messagesStream` I'm not sure how having it take a `MessageSender` would even work...

2024-04-15 17:28 UTC, justindbaur commented on libs/common/src/platform/abstractions/messaging.service.ts
> +// team specific PR's will come after.
https://bitwarden.atlassian.net/browse/PM-7479

2024-04-15 17:28 UTC, justindbaur commented on apps/browser/src/platform/background/service-factories/messaging-service.factory.ts
> +export {
https://bitwarden.atlassian.net/browse/PM-7479

2024-04-15 18:49 UTC, justindbaur commented
@MGibson1 Is the lazy classes comment about splitting listening and sending up or just the noop implementation? That just comes from them being separate today and me keeping it that way. I am not against making it one service but I didn't feel the need because generally other services have no need for both functions. Keeping them separate meant I can keep the surface slimmer and the dependencies injected a little lighter. I always try to keep these more "building block" type services light to help make sure everyone can use them. But I will admit, combining them wouldn't keep anyone from being able to use them as it currently stands. If the desire is for them to merge, I can absolutely do it. 

I don't know if I think the builder pattern fits that well into angular DI. I was able to remove the need for the noop implementation in [this commit](https://github.com/bitwarden/clients/pull/8709/commits/781abf396684f126302d266a66530bfeb01d4806) with parts that already existed.

2024-04-16 14:08 UTC, cturnbull-bitwarden approved these changes

2024-04-16 20:12 UTC, cagonzalezcs commented on apps/browser/src/background/nativeMessaging.background.ts
> +          this.runtimeBackground.processMessage({ command: "unlocked" });
Going to resolve this comment with the thought that a refactor of this kind is out of scope for the goal of this ticket. 

Will definitely look into suggesting a resolution for this in the future though.

2024-04-16 20:17 UTC, cagonzalezcs commented on apps/browser/src/platform/messaging/chrome-message.listener.ts
> +      fromChromeEvent(chrome.runtime.onMessage).pipe(
Hmm, I see... 

I know that for now this PR avoids messing with the message listeners established for the OverlayBackground and NotificationBackground classes... but given your approach, I think it would be relatively easy to facilitate a substitution of that established approach for setting up onMessage listeners with the one present in this PR.

That can be a future concern though. Resolving this comment.

2024-04-16 20:19 UTC, cagonzalezcs commented on apps/browser/src/platform/messaging/chrome-message.listener.ts
> +          if (!("webExtSender" in message)) {
Hm I see, ok that makes sense. We need to keep it due to legacy business logic that leverages the prop.

2024-04-16 20:27 UTC, cagonzalezcs commented on apps/browser/src/platform/messaging/chrome-message.sender.ts
> +        ) {
Nit, non-blocking

Might be nice to see this logic extrapolated to a method with a const or enum for the message references.

```
const RuntimeErrorMessage = {
	ReceivingEndDoesNotExist: "Could not establish connection. Receiving end does not exist.",
	PortClosed: "The message port closed before a response was received."
}

function logRuntimeError(command: string, errorMessage: string): void {
	switch(errorMessage) {
		case RuntimeErrorMessage.ReceivingEndDoesNotExist:
			this.logService.debug(`Receiving end didn't exist for command '${command}'`);
			break;
		case RuntimeErrorMessage.PortClosed
			this.logService.debug(`Port was closed for command '${command}'`);
			break;
		default:
			 this.logService.warning(
			 	`Error while sending message with command '${command}': ${chrome.runtime.lastError.message}`
		 	);
	}
}



[...]

if (chrome.runtime.lastError) {
	logRuntimeError(command, chrome.runtime.lastError.message);
}

[...]
```

2024-04-16 20:30 UTC, cagonzalezcs submitted a review, later dismissed
As far as changes go within the extension, this is looking good... I have one concern on the `RuntimeBackground` class with separating the onMessage listener between a function call that uses `sender` and one that does not... not sure why that's needed, but regardless of that nit going to approve for now.

2024-04-18 14:52 UTC, MGibson1 commented
@justindbaur no I like that listening and sending are separated, the lazy class thing is about each given class being expected to do very little, basically just wire up an observable in each case.

I believe DI will work fine since you're already using factories to inject the specific sender/listener. My point is that the default listener (same for sender) class should _be_ a noop class and only when built with listener. These build methods can contain the specific pipe logic for testing reasons if you'd like such that it would be built with

```typescript
...
provide: MessageListener
useFactory: (builder: MessageListernerBuilder) => {
  return builder.listenToSelf().listenToBackground()...
}
...
```
The `MessageListenerBuilder` is probably just a separate interface on the `MessageListener` so he build methods are hidden from those who just need listening

2024-04-18 16:44 UTC, justindbaur commented
@MGibson1 

If I put `MessageListenerBuilder` on `MessageListener` then it would be visible to any users of `MessageListener` because I don't have a version of `MessageListener` with _just_ abstract methods. There didn't seem like a need for it.

What I did here instead was delete the chrome and electron renderer message listener classes in favor of them just exposing a observable factory method. This way you can just grab those and `merge` streams yourself if need be. It allows them to just directly use `MessageListener` themselves and I was able to delete a couple classes and the `combine` method on `MessageListener`. Let me know what you think.

2024-04-18 20:09 UTC, justindbaur commented on apps/browser/src/background/runtime.background.ts
> +      void this.processMessageWithSender(msg, sender).catch((err) =>
Since these particular messages rely on the `chrome.runtime.MessageSender` my thinking is they don't care about "general" messages that could come from the same context, so these messages can be wired up directly to the chrome messaging with safety and can take advantage of the extra goods the chrome messages come with vs the general messages not having.

2024-04-18 20:15 UTC, justindbaur commented on apps/browser/src/platform/messaging/chrome-message.sender.ts
> +        ) {
I went with an object that contains "handlers" for that particular error. Let me know what you think!

2024-04-19 17:01 UTC, MGibson1 submitted a review, later dismissed
I had expected both the listener and sender to get the same composition, just with the sender receiving a list of subjects instead of a merged observable, as the listener gets.

However, I do not think this should block or be implemented now.

2024-04-19 17:29 UTC, MGibson1 approved these changes

2024-04-19 18:47 UTC, cturnbull-bitwarden approved these changes

2024-04-19 19:00 UTC, Jingo88 approved these changes

2024-04-19 19:02 UTC, merged