[PM-5735] Create kdf Service
bitwarden/clients pull request #8715
Opened 2024-04-11 23:21 UTC by ike-kottlowski

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Create a service to fetch new `KdfConfig` object. At the same time remove Kdf References from the `StateService`

## Code changes

Primary code changes are renaming and object accessor adjustments due to combining the `KdfType` into the `KdfConfig` object. 

There are some DI edits to ensure proper injection across clients.

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-04-23 05:29 UTC, ike-kottlowski commented on apps/cli/src/bw.ts
> +  kdfConfigService: KdfConfigService;
Addressed and tested the CLI login successfully.

2024-04-23 05:30 UTC, ike-kottlowski commented on libs/common/src/auth/models/domain/kdf-config.ts
> +export class PBKDF2KdfConfig {
Added some comments.

2024-04-23 12:46 UTC, jlf0dev approved these changes

2024-04-23 15:50 UTC, shane-melton approved these changes
Vault change looks good!

2024-04-23 17:29 UTC, r-tome approved these changes

2024-04-23 19:00 UTC, djsmith85 approved these changes
Changes are looking great and approving for tools!

2024-04-24 10:15 UTC, MGibson1 requested changes

2024-04-24 17:04 UTC, ike-kottlowski commented on libs/common/src/state-migrations/migrations/59-move-kdf-config-to-state-provider.ts
> +
How would I make this more defensive?

2024-04-25 00:22 UTC, MGibson1 commented on libs/common/src/state-migrations/migrations/59-move-kdf-config-to-state-provider.ts
> +
By guarding against null `account` or null `account.profile`

```typescript
      if (account && kdfConfig) {
        account.keys = Object.assign(account.profile ?? {}, {
          kdfIterations = kdfConfig.iterations;
          kdfType = kdfConfig.kdfType;
          kdfMemory = kdfConfig.memory;
          kdfParallelism = kdfConfig.parallelism;
        });
        await helper.set(userId, account);
      }
```

2024-04-25 00:24 UTC, MGibson1 approved these changes

2024-04-25 07:31 UTC, djsmith85 approved these changes

2024-04-25 08:58 UTC, r-tome approved these changes

2024-04-25 13:25 UTC, jlf0dev approved these changes

2024-04-25 18:22 UTC, shane-melton approved these changes

2024-04-25 18:26 UTC, merged