PM -2050 Update Bulk Confirm Dialog
bitwarden/clients pull request #8723
Opened 2024-04-12 15:11 UTC by KiruthigaManivannan

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other
```

## Objective

Update Bulk Confirm Dialog to use the component library.

## Code changes

- **bulk-confirm.component.html:** Modal and Table components are converted to use its equivalent dialog and bit tables in library.
- **bulk-confirm.component.ts:** Open method for dialog service is implemented
- **people.component.ts:** Bulk confirm dialog open logic is implemented

## Screenshots

https://github.com/bitwarden/clients/assets/162679756/a9edae73-9948-4d4a-865b-a9337ca6f71f

2024-05-01 04:07 UTC, eliykat requested changes

2024-05-02 12:41 UTC, KiruthigaManivannan commented on apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-confirm.component.ts
> +  users: BulkUserDetails[];
If we make this getters , we have conflicts in using those property in Providers people component.
![image](https://github.com/bitwarden/clients/assets/162679756/f55163ed-6e11-4f3d-a222-d9761ea1ed49)

2024-05-02 22:27 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-confirm.component.ts
> +  users: BulkUserDetails[];
Ah I see - let's leave it for now then.

2024-05-02 22:28 UTC, eliykat approved these changes

2024-05-21 13:09 UTC, merged