draft of extension layout components
bitwarden/clients pull request #8728
Opened 2024-04-12 20:44 UTC by vleague2

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-04-15 18:19 UTC, willmartian commented on libs/components/src/popup-layout/popup-layout.component.ts
> +        should the icon button with text also become a component? -->
I don't think we gain anything (at this time) by separating these buttons into their own components and passing them in as `ng-content`. We can revisit that when/if this is truly genericized as a design system component, instead of being strictly coupled to the extension itself.

2024-04-15 18:19 UTC, willmartian commented on libs/components/src/popup-layout/popup-layout.component.ts
> +  @Input() title: string;
Using the input name "title" will also set the HTML `title` attribute, which shows a tooltip on hover. If we want to prevent this, we need to either use another name for the input or overwrite the `title` attribute like so:

```
@HostBinding('attr.title') get titleAttr(): null {
  return null;
}
```

2024-04-15 18:19 UTC, willmartian commented on libs/components/src/popup-layout/popup-layout.component.ts
> +
Since the initial implementation of these components will be tightly coupled with specifics of the browser extension, could we move these components into `apps/browser/src/platform/popup`? 

What do you think?

2024-04-15 18:19 UTC, willmartian commented on libs/components/src/popup-layout/popup-layout.component.ts
> +// file location TBD, template files TBD
Separate template files are preferred due to syntax highlighting on GitHub

2024-04-15 18:19 UTC, willmartian commented on libs/components/src/popup-layout/popup-layout.component.ts
> +// in the design (i.e. have a top level header with a sub page footer). TBD on this decision
Not worried about this tbh. Code constraints aren't the only way to ensure that usage conforms to the design system--we also do this during design/code review.

2024-04-15 18:19 UTC, willmartian commented on libs/components/src/popup-layout/popup-layout.component.ts
> +      </div>
Use `<main>`?

2024-04-15 18:21 UTC, willmartian commented on libs/components/src/popup-layout/popup-layout.component.ts
> +      <div class="tw-bg-background-alt tw-p-3 tw-flex-1 tw-overflow-scroll">
Should this horizontal scrollbar be visible? Probably need `tw-overflow-y-scroll` instead

https://github.com/bitwarden/clients/assets/17113462/b6462fdb-1461-4d73-8003-d65336e2f380

2024-04-15 18:27 UTC, vleague2 commented on libs/components/src/popup-layout/popup-layout.component.ts
> +  @Input() variant: "top-level" | "sub-page" | "sub-page-action" = "top-level";
Yeah they do feel different. `footer` being the one that would have the action buttons?

2024-04-15 18:28 UTC, vleague2 commented on libs/components/src/popup-layout/popup-layout.component.ts
> +  @Input() title: string;
Ahhhh okay, noted.

2024-04-15 18:28 UTC, willmartian commented on libs/components/src/popup-layout/popup-layout.component.ts
> +  @Input() variant: "top-level" | "sub-page" | "sub-page-action" = "top-level";
Yeah

2024-04-15 18:29 UTC, vleague2 commented on libs/components/src/popup-layout/popup-layout.component.ts
> +
Yeah I think that makes the most sense. At this point I don't think any of it will be reusable enough to be in the CL.

2024-04-15 18:30 UTC, vleague2 commented on libs/components/src/popup-layout/popup-layout.component.ts
> +// in the design (i.e. have a top level header with a sub page footer). TBD on this decision
Okay cool. I couldn't think of a good solution to that problem so it's even better if we don't have to worry about it.

2024-04-15 18:30 UTC, vleague2 commented on libs/components/src/popup-layout/popup-layout.component.ts
> +      </div>
Gooooood point

2024-04-15 18:30 UTC, vleague2 commented on libs/components/src/popup-layout/popup-layout.component.ts
> +      <div class="tw-bg-background-alt tw-p-3 tw-flex-1 tw-overflow-scroll">
Ahh right, I think browsers show this differently so it looked fine in Chrome. But I'll adjust it

2024-04-15 19:28 UTC, willmartian commented on libs/components/src/popup-layout/popup-layout.component.ts
> +      <div class="tw-bg-background-alt tw-p-3 tw-flex-1 tw-overflow-scroll">
This fixed it for me in FF 🦊 🚀

2024-04-23 15:14 UTC, danielleflinn commented
@vleague2 Just checked storybook for this; it looks amazing 🎉 

For the navigation focus state, what do you think about updating the focus to `focus-visible`? I believe we use that over focus in most of our interactive components.

2024-04-23 19:12 UTC, willmartian commented on apps/browser/src/platform/popup/layout/popup-header.component.ts
> +  @Input() showBackButton: boolean = false;
Could you update this to use boolean attribute coercion? https://material.angular.io/cdk/coercion/overview#example

2024-04-23 19:12 UTC, willmartian commented on apps/browser/src/platform/popup/layout/popup-layout.mdx
> +    page in history.
Could you add these as JSDoc comments in the TS file above each respective input?

2024-04-23 19:12 UTC, willmartian commented on apps/browser/src/platform/popup/layout/popup-layout.mdx
> +```
Marking code blocks with ```html should provide syntax highlighting in MDX

2024-04-23 19:12 UTC, willmartian commented on apps/browser/src/platform/popup/layout/popup-bottom-navigation.component.html
> +        routerLink="/{{ button.page }}"
Code style: don't use string interpolation {{ }} when binding to attributes. 

You property binding syntax instead: 

```html
[attr.title]="button.label"
[routerLink]="button.page"
```

2024-04-23 19:12 UTC, willmartian commented on apps/browser/src/platform/popup/layout/popup-bottom-navigation.component.html
> +        routerLink="/{{ button.page }}"
`/{{ button.page }}` makes me think that "/" should just be part of `button.page`

2024-04-23 19:27 UTC, willmartian commented
Could you update the base branch to `main`?

2024-04-23 19:28 UTC, willmartian commented on apps/browser/src/platform/popup/layout/popup-layout.mdx
> +
Do you know why the view code button isn't showing up below each story? 🤔

2024-04-23 22:11 UTC, willmartian commented on apps/browser/src/platform/popup/layout/popup-header.component.html
> +      </button>
Should the back button be an `bitIconButton`? (for its focus/hover states etc).

cc @danielleflinn

2024-04-24 14:22 UTC, danielleflinn commented on apps/browser/src/platform/popup/layout/popup-header.component.html
> +      </button>
Yes good catch

2024-04-24 14:24 UTC, vleague2 commented on apps/browser/src/platform/popup/layout/popup-bottom-navigation.component.html
> +        ></i>
Oh that's a good point!!

2024-04-24 22:03 UTC, willmartian reviewed
The tabs should not show text decoration on hover:

https://github.com/bitwarden/clients/assets/17113462/8e086082-ccfc-408d-a77b-7be0b1125079

2024-04-25 13:56 UTC, vleague2 commented on apps/browser/src/platform/popup/layout/popup-bottom-navigation.component.html
> +        ></i>
Okay I don't think you can conditionally do an icon class like this, it doesn't seem to render the icon when it's in the `ngClass` 🤔

2024-04-25 14:19 UTC, vleague2 commented on apps/browser/src/platform/popup/layout/popup-header.component.html
> +        aria-label="Back"
@willmartian I am assuming these need to be localized, but I'm not sure how to use the i18n pipe in a standalone component 🤔

2024-04-25 14:26 UTC, willmartian commented on apps/browser/src/platform/popup/layout/popup-header.component.html
> +        aria-label="Back"
You will likely need to bring in whatever shared module the `i18n` pipe is defined in, which sucks but is fine for now. (Note for Platform to make the pipe standalone in a different PR.)

2024-04-25 14:27 UTC, willmartian commented on apps/browser/src/platform/popup/layout/popup-layout.mdx
> +
(This can also happen as a follow up if it isn't a simple solve!)

2024-04-25 15:57 UTC, willmartian requested changes

2024-04-25 15:57 UTC, willmartian commented on apps/browser/src/platform/popup/layout/popup-header.component.ts
> +  _showBackButton = false;
```suggestion
  private _showBackButton = false;
```

2024-04-25 15:57 UTC, willmartian commented on apps/browser/tsconfig.json
> +  "extends": "../../libs/shared/tsconfig",
Do you know what compiler option we were missing? I think it was maybe `allowSyntheticDefaultImports`.

 Could we just add it instead of extending the shared config (at this time)? Extending brings changes to `dist` and `pretty` which I believe are unrelated to the goal of making Storybook work in `apps/browser`

2024-04-25 17:50 UTC, vleague2 commented on apps/browser/tsconfig.json
> +  "extends": "../../libs/shared/tsconfig",
Yep that seems to work

2024-04-25 18:19 UTC, willmartian submitted a review, later dismissed
LGTM! Let's change the base to `main`

2024-04-25 20:40 UTC, willmartian approved these changes

2024-04-25 21:07 UTC, danielleflinn approved these changes

2024-04-26 13:35 UTC, merged