[PM-7304] Add static error message when import fails
bitwarden/clients pull request #8743
Opened 2024-04-15 10:23 UTC by aj-rosado

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

No message was sent when the import failed due to unassigned collections. Added a static error message as the error object that was used to display error information, does not contain the expected error message.

## Code changes

- **import.command.ts:** Displaying static import error message as error is not returning any data.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-04-16 11:38 UTC, djsmith85 requested changes
We should look into why the error.message isn't present, as it seems to work on all other clients. I'd prefer that over a generic message. 

I have a suspicion that this is due to a missing entry in the CLI en locale (`importUnassignedItemsError`). With the import.service being shared with all clients, we have to ensure that all locale files have the keys being used.

@aj-rosado: Could you please look into this and if any keys are missing or we are using non-translatable strings, please add them to the en-locale files.

2024-04-16 12:49 UTC, aj-rosado commented
> We should look into why the error.message isn't present, as it seems to work on all other clients. I'd prefer that over a generic message.
> 
> I have a suspicion that this is due to a missing entry in the CLI en locale (`importUnassignedItemsError`). With the import.service being shared with all clients, we have to ensure that all locale files have the keys being used.
> 
> @aj-rosado: Could you please look into this and if any keys are missing or we are using non-translatable strings, please add them to the en-locale files.

That was a very correct guess thanks. I was a little misled as we only do the error handling like this here and thought there was another issue.

2024-04-16 14:59 UTC, djsmith85 approved these changes

2024-04-16 19:07 UTC, djsmith85 approved these changes

2024-04-17 15:17 UTC, djsmith85 approved these changes

2024-04-17 15:19 UTC, merged