[AC-2405] migrate SCIM component
bitwarden/clients pull request #8781
Opened 2024-04-17 11:04 UTC by vinith-kovan

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [X] Other
```

## Objective

Migrate the scim component to use the component library.

## Code changes

scim.component.html -  Updated the bootstrap css to use the equivalent components from the Component Library.
scim.component.ts - Update the normal functions to es6 function.

## Screenshots

https://github.com/bitwarden/clients/assets/156108204/22a6a2e8-5d12-47ab-bbdc-9dc53ecf6a58

2024-04-22 06:28 UTC, eliykat requested changes

2024-04-22 06:28 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/organizations/manage/scim.component.html
>        ></button>
Using the non-standard `button.loading` property is also deprecated - it was part of the `appApiAction` pattern to disable the button while the promise is executing.

The async actions CL directives should handle this for you - see in particular the [standalone form buttons](https://components.bitwarden.com/?path=/docs/component-library-async-actions-in-forms-documentation--docs#usage-standalone-form-buttons). 

Suggested changes:

1. delete this `[disabled]` binding
2. add the `bitFormButton` directive

You can also delete the wrapping `ng-container` because it was only here to attach the `appApiAction` directive to.

2024-04-22 06:28 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/organizations/manage/scim.component.html
>        [appA11yTitle]="'copyScimKey' | i18n"
@willmartian is the `appA11yTitle` directive still in use? Is it OK to combine with other CL button directives, or is it duplicative here?

2024-04-23 15:00 UTC, willmartian commented on bitwarden_license/bit-web/src/app/admin-console/organizations/manage/scim.component.html
>        [appA11yTitle]="'copyScimKey' | i18n"
It is still in use and okay to use with CL directives 👍

2024-05-01 03:24 UTC, eliykat requested changes
Looks good, just a few minor changes around cleaning up the `formPromise` pattern.

2024-05-01 03:24 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/organizations/manage/scim.component.ts
> +    let rotatePromise: Promise<ApiKeyResponse> = this.organizationApiService.rotateApiKey(
I agree that we don't need the class property anymore, but it doesn't even need to be a local variable. You can just `await` this call directly.

2024-05-01 03:24 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/organizations/manage/scim.component.ts
> +    rotatePromise = null;
And delete this line given that we're not assigning the promise to a variable.

2024-05-01 03:24 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/organizations/manage/scim.component.ts
> +    let formPromise: Promise<OrganizationConnectionResponse<ScimConfigApi>>;
Same here, although in this case we need to declare `let response: OrganizationConnectionResponse<ScimConfigApi>;` here instead, which is assigned inside the `if` block.

2024-05-01 03:24 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/organizations/manage/scim.component.ts
> +    const response = (await formPromise) as OrganizationConnectionResponse<ScimConfigApi>;
The type cast here looks unnecessary.

2024-05-15 21:53 UTC, eliykat approved these changes
Great work thank you!

2024-05-22 12:34 UTC, merged