[PM-7562] Add DuckDuckGo back to State Service
bitwarden/clients pull request #8791
Opened 2024-04-17 17:54 UTC by differsthecat

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Add the previous enable DDG setting back so that users on previous versions of DuckDuckGo can use the integration.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-04-17 18:47 UTC, MGibson1 requested changes
If I understand the situation correctly, we just need to ensure the value is stored to the same location for DDG to read. We don't need to use it as a source of data for _ourselves_, correct?

In that case, we should only add the `set` method back and maintain the state provider location for our own value until DDG can update.

2024-04-17 18:47 UTC, MGibson1 commented on apps/desktop/src/app/accounts/settings.component.ts
> +      enableDuckDuckGoBrowserIntegration:
I think we'll want to choose one of these for the read source and just make sure we write to both

2024-04-17 21:12 UTC, differsthecat commented on apps/desktop/src/app/accounts/settings.component.ts
> +      enableDuckDuckGoBrowserIntegration:
Makes total sense, we don't need to read it, DDG does so no need for the getter

2024-04-17 22:02 UTC, differsthecat commented on apps/desktop/src/app/accounts/settings.component.ts
> +      enableDuckDuckGoBrowserIntegration:
Fixed!

2024-04-18 13:36 UTC, MGibson1 approved these changes

2024-04-19 13:45 UTC, merged