Auth/PM-6689 - Migrate Security Stamp to Token Service and State Provider
bitwarden/clients pull request #8792
Opened 2024-04-17 18:27 UTC by JaredSnider-Bitwarden

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-04-17 21:18 UTC, jlf0dev approved these changes
🚀

2024-04-19 11:15 UTC, justindbaur requested changes
You shouldn't need a migration for data stored in memory. Everything else looks great though.

2024-04-19 17:23 UTC, JaredSnider-Bitwarden commented
> You shouldn't need a migration for data stored in memory. Everything else looks great though.

@justindbaur , thank you for catching that! I've been doing so many migrations that it was second nature. I've removed the unnecessary migration!

2024-04-19 17:31 UTC, justindbaur approved these changes

2024-04-19 20:08 UTC, Jingo88 approved these changes

2024-04-19 20:12 UTC, jlf0dev approved these changes

2024-04-19 20:44 UTC, merged