[DEVOPS-1919] - Slack messages contain the incorrect git commit sha
bitwarden/clients pull request #8813
Opened 2024-04-18 17:24 UTC by mimartin12

## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [X] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
https://bitwarden.atlassian.net/jira/software/c/projects/DEVOPS/boards/127?quickFilter=244&selectedIssue=DEVOPS-1919
Accurately show the commit SHA that will be used, linked from the artifact deployed. This leverages the new feature here in https://github.com/bitwarden/gh-actions/pull/276

## Code changes

- **.github/workflows/deploy-web.yml:**
  - Removed the `get-branch-or-tag-sha:` job, this is replaced by the functionality in https://github.com/bitwarden/gh-actions/pull/276
  - Moved `notify` job to run after the artifact check job.
  - Added a step in the artifact job to set the build commit of the artifact, depending on which job is ran.

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-04-18 17:32 UTC, vgrassia requested changes

2024-04-18 17:32 UTC, vgrassia commented on .github/workflows/deploy-web.yml
> +          workflow: build-web.yml
```suggestion
          workflow: build-web.yml
```

2024-04-18 17:35 UTC, vgrassia approved these changes

2024-04-18 22:44 UTC, mimartin12 commented
@vgrassia There is another step I need to account for, the one where this workflow triggers a build if no artifact is found. I have converted to a draft in the meantime. Stay tuned.

2024-04-19 15:31 UTC, urbinaalex17 approved these changes
LGTM!

2024-04-19 19:39 UTC, merged