Ac/ac 2302/move device approve deny into a service
bitwarden/clients pull request #8818
Opened 2024-04-18 19:44 UTC by r-tome

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-04-18 22:57 UTC, eliykat requested changes
Looking good so far!

2024-04-18 22:57 UTC, eliykat commented on bitwarden_license/bit-common/src/admin-console/services/auth-requests/organization-auth-request.service.ts
> +import { OrganizationAuthRequestApiService } from "bitwarden_license/bit-common/src/admin-console/services/auth-requests";
Broken import:

```suggestion
import { OrganizationAuthRequestApiService } from "./organization-auth-request-api.service";
```

2024-04-18 22:57 UTC, eliykat commented on bitwarden_license/bit-common/src/admin-console/services/auth-requests/organization-auth-request.service.ts
> +@Injectable()
`bit-common` is going to be used in Angular and non-Angular clients (the CLI), so it can't import Angular code such as `@Injectable()`. You'll need to remove this decorator and then manually configure its dependencies in the ngModule. (See `jslib-services.module.ts` for examples, or I have a [draft writeup here](https://dependency-injection.contributing-docs.pages.dev/architecture/clients/dependency-injection#angular-modules).)

2024-04-18 22:57 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/organizations/core/core-organization.module.ts
> +  providers: [OrganizationAuthRequestApiService, OrganizationAuthRequestService],
I think these could probably be moved to `OrganizationsModule` where `DeviceApprovalsComponent` is declared, because that's the only component that uses them.

2024-04-18 22:57 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/organizations/manage/device-approvals/device-approvals.component.ts
>        const details = await this.organizationUserService.getOrganizationUserResetPasswordDetails(
I think this could also be moved into the service. That way, the component (or CLI command) only have to pass in the `PendingAuthRequestView` they want to approve.

2024-04-30 03:50 UTC, eliykat requested changes
I have reviewed from a high level structure perspective, but I'll ask @addisonbeck to do a more in-depth review as the other dev working on device approvals.

2024-04-30 03:50 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/organizations/organizations.module.ts
> +  providers: [
Can you please implement the same pattern as `JslibServicesModule` where the `providers` are declared in their own variable of with the type of `SafeProvider[]`. It helps ensure that others will continue to use safeProvider when they make changes later.

2024-04-30 03:50 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/organizations/organizations.module.ts
> +    }),
You shouldn't need to register `ApiService` again, it should be registered by the time this module is loaded. (The bit-web `AppModule` imports `JslibServicesModule` which registers it.)

2024-04-30 03:50 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/organizations/manage/device-approvals/device-approvals.component.ts
> +import { OrganizationAuthRequestService } from "../../../../../../../bit-common/src/admin-console/services/auth-requests/organization-auth-request.service";
Please define a path mapping for `@bitwarden/bit-common`:
* add the path mapping to `tsconfig.json` and `tsconfig.eslint.json` in the root of the repository
* look at the rules in `.eslintrc.json` for existing mappings. They prevent using the `@bitwarden` mappings from inside the same folder (imports from inside the same folder must be relative). Add a similar rule for this new mapping

2024-04-30 03:50 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/organizations/organizations.module.ts
More generally - I think you could make `DeviceApprovalsComponent` standalone and register your new services there. This Organizations module is relatively high level, it's loading these services even if the user isn't clicking through to the device approvals component.

2024-04-30 03:50 UTC, eliykat commented on bitwarden_license/bit-common/src/admin-console/services/auth-requests/admin-auth-request-update.request.ts
The `bit-common/src/admin-console/services/auth-requests` contains more than just the service - it also has request/response models etc. I suggest removing the `service` folder so that it's organized primarily by feature and not by class type: `bit-common/src/admin-console/auth-requests`.

2024-05-02 21:06 UTC, addisonbeck reviewed
Checks are failing, but generally this seems good to me. Just a couple of small comments, in addition to the unresolved marks from Thomas.

2024-05-02 21:06 UTC, addisonbeck commented on bitwarden_license/bit-common/src/admin-console/auth-requests/index.ts
> +export * from "./organization-auth-request-api.service";
Do you need this? The service exports itself currently.

2024-05-03 01:30 UTC, eliykat reviewed
A few explanatory comments on what I changed in the course of fixing the build problems.

2024-05-03 01:30 UTC, eliykat commented on bitwarden_license/bit-common/jest.config.js
> +  testEnvironment: "jsdom",
`jest-preset-angular` sets up the test environment for Angular clients. It's not required here because it's a non-Angular library.

Instead we should use `ts-jest`, the more general Jest setup for Typescript environments, and jsdom for the [testEnvironment](https://jestjs.io/docs/configuration#testenvironment-string). This all mirrors the `libs/common` setup, which is more similar to this library than `bit-web`.

2024-05-03 01:30 UTC, eliykat commented on bitwarden_license/bit-common/tsconfig.json
> +  }
This shouldn't be necessary because we're using `extends` to include the shared config. And yet, it does fix the problem. Looking at other tsconfig files, it seems fairly common that it's repeated in full around the place.

2024-05-03 01:30 UTC, eliykat commented on bitwarden_license/bit-common/tsconfig.spec.json
> -  "files": ["../../libs/common/test.setup.ts"]
If you look at this file, it mostly bootstraps some environment stuff for crypto, which shouldn't be needed here.

2024-05-03 01:55 UTC, eliykat commented on apps/web/tsconfig.json
> -      "@bitwarden/bit-common/*": ["../../bitwarden_license/bit-common/src/*"]
`apps/web` is OSS code. It should never import BL code, otherwise it's no longer OSS. Instead, BL code imports OSS code.

2024-05-03 03:37 UTC, eliykat commented
I had to spend a bit more time on this, here's the summary.

In https://github.com/bitwarden/clients/pull/8818/commits/5e66416c13dff18d61d09a2431cec4609140b1c1 I removed the `@bitwarden/bit-common` path mapping from `apps/web`, because the web vault is OSS code. It should never import BL code, otherwise it's no longer purely OSS. Instead, BL code is our entrypoint, and it imports OSS code. (You can see this because `npm run build:bit` [points to a webpack file in the `bit-web` directory](https://github.com/bitwarden/clients/blob/main/apps/web/package.json#L6).) ((When you start updating the CLI, it will need a similar configuration.))

However, `npm run build:bit` was still using the `tsconfig.json` in the `apps/web` directory, because that's where the command was being run from. So removing that mapping broke the `bit` build.

The [Angular Webpack Plugin](https://www.npmjs.com/package/@ngtools/webpack) does provide an option to specify the location of tsconfig, but it looks like at some stage it changed name: the docs call it [`tsconfig`](https://www.npmjs.com/package/@ngtools/webpack) whereas our configuration uses [`tsConfigPath`](https://github.com/bitwarden/clients/blob/main/bitwarden_license/bit-web/webpack.config.js#L7), so that wasn't actually working as intended.

Once I fixed _that_ to use the `bit-web` tsconfig, the build broke because that tsconfig isn't fully set up. I had to copy across the configuration from `apps/web/tsconfig.json` and update relative paths, and then for good measure, remove the BL entrypoint from `apps/web/tsconfig.json`. (One annoying thing here is that the tsconfig `extends` option isn't very robust; as soon as you set a top-level configuration option in the child tsconfig, it'll blast over the parent tsconfig, so lots of copy/paste is required here.)

On the plus side, this is now working how it should 😁

2024-05-03 09:51 UTC, r-tome commented on bitwarden_license/bit-web/src/app/admin-console/organizations/organizations.module.ts
> +    }),
If I remove it then it fails to inject `ApiService`
`NullInjectorError: R3InjectorError(Standalone[OrganizationLayoutComponent])[OrganizationAuthRequestService -> OrganizationAuthRequestService -> OrganizationAuthRequestApiService -> ApiService -> ApiService]: 
  NullInjectorError: No provider for ApiService!`

2024-05-03 11:15 UTC, r-tome commented on bitwarden_license/bit-web/src/app/admin-console/organizations/organizations.module.ts
I've done that, let me know if its missing anything

2024-05-03 11:16 UTC, r-tome commented on bitwarden_license/bit-common/src/admin-console/auth-requests/index.ts
> +export * from "./organization-auth-request-api.service";
Apparently not, I've removed it. It was added whilst troubleshooting the broken paths

2024-05-06 03:21 UTC, eliykat requested changes
Standalone component looks good, just a few items.

2024-05-06 03:21 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/organizations/manage/device-approvals/device-approvals.component.ts
> +  imports: [SharedModule, OrganizationsRoutingModule, NoItemsModule, LooseComponentsModule],
You should check whether these imports are actually required, i.e. does this component depend on them? In this case, you can drop `OrganizationsRoutingModule`. The others look OK.

2024-05-06 03:21 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/organizations/manage/device-approvals/device-approvals.component.ts
> +  }),
This will create another instance of `ApiService` (as well as duplicating its DI configuration), which we don't want. You can delete this provider definition and add `JslibServicesModule` to the `imports` array instead, to use the existing definition.

2024-05-06 03:21 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/organizations/manage/device-approvals/device-approvals.component.ts
> +    deps: [ApiService],
This needs to refer to the ApiService abstraction (`"@bitwarden/common/abstractions/api.service"`), not the concrete implementation (`"@bitwarden/common/services/api.service"`). Similar to how you inject interfaces in C#, not implementations. It's the abstraction/interface that's been registered with the DI framework.

2024-05-06 03:26 UTC, eliykat requested changes

2024-05-06 03:26 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/organizations/organizations.module.ts
> +import { CoreOrganizationModule } from "@bitwarden/web-vault/app/admin-console/organizations/core";
I don't think there's any need to swap the old CoreOrganizationModule for this one. They're totally separate modules. If you got rid of the old one, no need to add this one unless it's actually used by something here.

2024-05-06 03:26 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/organizations/organizations.module.ts
Now that `DeviceApprovalsComponent` is standalone, you should also review the `imports` array here, because it's possible that an import was only used by `DeviceApprovalsComponent` and doesn't need to still be here.

The one I can spot is `NoItemsModule`, it's used to render the empty state of the device approvals list, and doesn't seem to be used by any other component in this module. So it can be removed. This is the process of unbundling ngModules and why standalone components are useful for more precisely defining dependencies within the app.

2024-05-06 03:26 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/organizations/organizations.module.ts
> +    }),
See my latest review, this is because you're supplying the implementation rather than the abstraction.

2024-05-07 12:52 UTC, r-tome commented on bitwarden_license/bit-web/src/app/admin-console/organizations/manage/device-approvals/device-approvals.component.ts
> +  }),
If I remove this and add `JslibServicesModule` then the `ApiService` for this module uses the public api instead of my local dev address. Is this because `JslibServicesModule` is configured to use `DefaultEnvironmentService`?

2024-05-07 13:20 UTC, r-tome commented on bitwarden_license/bit-web/src/app/admin-console/organizations/organizations.module.ts
Nicely spotted! Looks like that is the only one not required.

2024-05-08 04:34 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/organizations/manage/device-approvals/device-approvals.component.ts
> +  }),
I tested it and it works for me! I pushed a commit just to make sure we're talking about the same set of changes. If it's still not working for you - what public address is it reaching out to?

2024-05-08 04:38 UTC, eliykat reviewed
All commits reviewed, should be good to go once we get this EnvironmentService stuff figured out.

2024-05-10 05:23 UTC, eliykat submitted a review, later dismissed
LGTM, although as I've also pushed code a final check from @addisonbeck would be appreciated.

2024-05-10 05:23 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/organizations/manage/device-approvals/device-approvals.component.ts
> +  }),
Honestly not sure why that would've made a difference, but I clarified with Will that we don't need to import JslibServicesModule anyway. Let's leave it how it is.

2024-05-12 22:52 UTC, eliykat approved these changes

2024-05-14 12:00 UTC, addisonbeck submitted a review, later dismissed

2024-05-19 23:19 UTC, eliykat approved these changes

2024-05-20 10:18 UTC, merged