Simplify `LocalBackedSessionStorage`
bitwarden/clients pull request #8852
Opened 2024-04-21 15:26 UTC by MGibson1

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other - performance improvements
```

## Objective

My testing has shown that the current implementation of `localBackedSessionStore` creates problems as the total amount of stored data increases. Every value retrieved suffers from the presence of all other data due to the single blob nature.

In the extreme, signing in with an account with thousands of vault items (~50MB worth) significantly impacts a second vault with only 5, which should still be perfectly snappy. The solution to this coupling is, of course, to decouple. We _could_ do this by assigning namespaces by global/userId, but my testing suggests that it is not necessary to bundle even to that extent. It's sufficient to group the large, enumerable lists of items (ciphers, collections, folders, sends, etc) into one key-value-pair each. We do lose some time with encryption/decryption by treating multiple values instead of exactly one, but the IO saved _definitely_ makes up for this. On a human perspective, it also makes sense to me when I'm loading a huge vault that things take longer, but I'm less willing to put up with long load times for a small vault that happens to be signed in at the same time as a large one.

The last big change here is the introduction of a `Lazy` class that loads a value from a supplied factory exactly once. This is to allow me to remove the complexity of key management from `LocalBackedSessionStorage` and allow that to be handled by application initialization. This is how I expect all of the future key-protected-storage will work.

## Code changes

- **main.background**: Two big changes here
  - extract key generation into a lazy predicate. This uses a storage.session-stored key if one is found and generates + stores one if not. The first run of the service worker (that calls this lazy predicate) will create a key and all subsequent ones will just read it from disk. This is also true of the fake background in the popup.
  - reuses state providers' memory storage in mv3. There is no partitioning anymore since all data is stored independently. We could probably just use the state-providers version for the normal `memoryStorageService` entirely, but out of an abundance of caution for JSON serialization norms, we haven't totally moved over, yet.
- **local-backed-session-storage.service**: This is obviously the meat of the change. It removes key management and stores values indipendently to disk store.
  - This work includes a full rewrite of the test cases due to those test heavily presuming a single stored session (and key management)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-04-21 23:23 UTC, justindbaur requested changes
Looks good, just a few nits and thoughts on the inner workings of `Lazy`.

2024-04-21 23:23 UTC, justindbaur commented on apps/browser/src/platform/services/local-backed-session-storage.service.ts
> +      if (port.name !== `${portName(chrome.storage.session)}`) {
Don't need to wrap this in ` anymore.

2024-04-21 23:23 UTC, justindbaur commented on apps/browser/src/platform/services/local-backed-session-storage.service.ts
> +      return this.remove(key);
I get that this is allowed in JavaScript but I hate it, you're technically returning a `Promise<Promise<void>>`, which it will unwrap just fine, but it's stupid in my opinion. So I would rather keep the `await`.

2024-04-21 23:23 UTC, justindbaur commented on libs/common/src/platform/misc/lazy.spec.ts
> +  describe("getValue", () => {
Method renamed after describe created?

2024-04-22 00:20 UTC, MGibson1 commented on libs/common/src/platform/misc/lazy.ts
In the async case, yes. You want to store the promise because you want to guarantee that the factory is called only once and that the value stored is the result of the factory. That's exactly what a stored promise does. If we instead stored a bool, there's a chance of either returning `_value` before it's actually been set or calling the factory before the first has finished.

I can see what you mean about forcing an await on a sync factory, but that's going to happen no matter what because the `get` method is async. `Promise.resolve` resolves immediately, it's just at the end of the execution queue, same as awaiting the `get`.

Now if you're objecting to having a sync factory handler at all, I can get behind that. I actually added it during testing just because I didn't want to have the extra `async` keyword in my test. I also thought there's some utility in a sync `Lazy` value, but that can easily be a separate class. That's probably more appropriate for js, anyway.

2024-04-22 00:26 UTC, MGibson1 commented on libs/common/src/platform/misc/lazy.spec.ts
> +  describe("getValue", () => {
thank you, fixed in https://github.com/bitwarden/clients/pull/8852/commits/bc2f897bdac2c387c38aa5aaeaa0eb7a3dd28854

2024-04-22 00:27 UTC, MGibson1 commented on apps/browser/src/platform/services/local-backed-session-storage.service.ts
> +      return this.remove(key);
I totally agree, this was a miss by me, thank you. Fixed in https://github.com/bitwarden/clients/pull/8852/commits/bc2f897bdac2c387c38aa5aaeaa0eb7a3dd28854

2024-04-22 00:27 UTC, MGibson1 commented on apps/browser/src/platform/services/local-backed-session-storage.service.ts
> +      if (port.name !== `${portName(chrome.storage.session)}`) {
Fixed in https://github.com/bitwarden/clients/pull/8852/commits/af6f0f4793e1cdde2c3d1351eeac53432ac6f6e5

2024-04-22 00:30 UTC, justindbaur commented on libs/common/src/platform/misc/lazy.ts
In the async case you would still be storing the promise, you'd be storing it in `_value` and their creation factory would still only be called once. 

```typescript
class Lazy<T> {
  private _isCreated = false;
  private _value: T = undefined;

  constructor(private readonly valueFactory: () => T) {
  }

  get(): T {
    if (!this._isCreated) {
       this._value = this.valueFactory();
       this._isCreated = true;
    }

    return this._value;
  }
}
```

Now when someone makes a factory like this:
```
new Lazy(async () => await Promise.resolve(1));
```

it will have the type `Lazy<Promise<number>>`

now when you try to get your value you will call `await myLazy.get();` the same way you do now. But if you create your lazy like `new Lazy(() => 1)` you have `Lazy<number>` and can get your value without awaiting. This is essentially how C#'s Lazy works, there is no special async lazy. You just make your value be a `Task<T>`.

2024-04-22 13:08 UTC, MGibson1 commented on libs/common/src/platform/misc/lazy.ts
wow, you're right. I can't believe I didn't think of that, but I guess that's what happens when you get stuck on a certain solution.

Thanks for pointing this out, I've updated to your suggestion and added the sync tests back.

2024-04-22 13:18 UTC, cagonzalezcs commented on apps/browser/src/platform/services/local-backed-session-storage.service.ts
> +    // console.log("Sending message to port", port, data);
Leftover console log?

2024-04-22 13:18 UTC, cagonzalezcs commented on apps/browser/src/platform/services/local-backed-session-storage.service.ts
> -      return this.cachedSession;
Is it no longer necessary to try to avoid decryption of the session as a result of the smaller encrypted values?

2024-04-22 13:23 UTC, MGibson1 commented on apps/browser/src/platform/services/local-backed-session-storage.service.ts
> -      return this.cachedSession;
we're no longer storing values as a single session value at all, so if the cache lacks the precise key we're looking for, we don't know the value and need to fetch it.

2024-04-22 13:24 UTC, MGibson1 commented on apps/browser/src/platform/services/local-backed-session-storage.service.ts
> +    // console.log("Sending message to port", port, data);
removed in https://github.com/bitwarden/clients/pull/8852/commits/43c82d1d91d72b32d0cbe4ba099a9f34197ba506

2024-04-22 13:27 UTC, cagonzalezcs submitted a review, later dismissed

2024-04-22 13:27 UTC, justindbaur commented on libs/common/src/platform/misc/lazy.ts
> +   * @returns Promise resolving the result of the factory
```suggestion
   * @returns The value produced by your factory.
```

2024-04-22 13:27 UTC, justindbaur commented on libs/common/src/platform/misc/lazy.ts
Another thing we could steal from C#'s Lazy would be to add a way to create one with an already resolved value, you would be able to take advantage of it in one of the tests but this is definitely a nit. 

```typescript
static factory<T>(factory: () => T) {
  return new Lazy<T>(factory: factory, isCreated: false, value: undefined);
}

static value<T>(value: T) {
  return new Lazy<T>(factory: undefined, isCreated: true, value: value);
}
```

Then you just make the constructor take in all the properties and make it private.

2024-04-22 13:49 UTC, MGibson1 commented
I'd prefer to worry about expanding the interface as we actually use the helper. We really haven't had too many situations that need. It's kind of a way to avoid `init` methods, which is great, but honestly we've been doing well leaning into rxjs, which I prefer to this.

2024-04-22 13:57 UTC, MGibson1 commented on libs/common/src/platform/misc/lazy.ts
I'd prefer to prove out the usage of this helper before investing too much into it. This really is a means to avoid `init` methods, which I like, but we've been really successful investing in rxjs to do that thus far and I think that's a better way to do it for the moment.

2024-04-22 13:58 UTC, MGibson1 commented on libs/common/src/platform/misc/lazy.ts
I suppose that means that the better way to do this would be to use a global state provider saved to session (now that we have it).

2024-04-22 14:01 UTC, cagonzalezcs approved these changes

2024-04-22 14:06 UTC, justindbaur approved these changes

2024-04-22 14:14 UTC, merged