[AC-2411] migrate account component
bitwarden/clients pull request #8854
Opened 2024-04-22 08:45 UTC by vinith-kovan

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [X] Other
```

## Objective

Migrate the account component to use the component library.

## Code changes

bitwarden_license\bit-web\src\app\admin-console\providers\settings\account.component.html - Updated the bootstrap css to use the equivalent components from the Component Library.
bitwarden_license\bit-web\src\app\admin-console\providers\settings\account.component.ts - Formgroup added and refactored the submit method.

## Screenshots

https://github.com/bitwarden/clients/assets/156108204/b381a77b-c341-4aef-910b-332dff15bd70

2024-05-08 16:09 UTC, r-tome submitted a review, later dismissed

2024-05-24 09:54 UTC, r-tome commented
Hi @vinith-kovan, please resolve the merge conflict. Otherwise it looks good

2024-05-30 08:53 UTC, r-tome submitted a review, later dismissed
Please resolve the merge conflicts

2024-06-14 02:52 UTC, eliykat requested changes
@r-tome is on leave so I've reviewed this - I agree that it looks good, I just spotted a few things in the logic that we should fix up.

2024-06-14 02:52 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/providers/settings/account.component.ts
>        this.providerId = params.providerId;
Please add `.pipe(takeUntil(this.destroy$))` to the route subscription above, and remove the `eslint-disable-next-line` comment.

2024-06-14 02:52 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/providers/settings/account.component.ts
> +  ngOnDestroy() {
Please add `implements onDestroy` to the class definition.

2024-06-14 02:52 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/providers/settings/account.component.ts
> +    });
This is how the old binding worked, but we don't need it now that you've converted this to use a FromGroup. Please:

1. remove this block so that we're not overwriting `this.provider` until the form is actually saved
2. make `submit()` read from FormGroup values instead
3. no other changes required I think - anywhere we display the provider name should use the saved value emitted by `providerApiService`, not the potentially dirty form values

2024-06-14 02:57 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/providers/settings/account.component.ts
> +      return this.syncService.fullSync(true);
Please use `await` rather than `then` callbacks.

2024-06-17 20:20 UTC, eliykat requested changes

2024-06-17 20:20 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/providers/settings/account.component.ts
>      this.loading = false;
This line has to be inside the `try` block above so that it's only executed after the page has loaded.

2024-06-17 20:20 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/providers/settings/account.component.ts
> +    request.billingEmail = this.formGroup.get("providerBillingEmail").value;
Please use the type safe way of accessing values. e.g. `this.formGroup.value.providerName`

2024-06-17 20:20 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/providers/settings/account.component.ts
> +    this.provider = await this.providerApiService.getProvider(this.providerId);
Please move this one line up so that the success toast is only shown after the method is complete.

2024-06-17 20:20 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/providers/settings/account.component.ts
> +export class AccountComponent implements OnDestroy {
I didn't spot there's also an `ngOnInit` here:

```suggestion
export class AccountComponent implements OnDestroy, OnInit {
```

2024-06-18 11:02 UTC, vinith-kovan commented on bitwarden_license/bit-web/src/app/admin-console/providers/settings/account.component.ts
>      this.loading = false;
we can move it to finally so even if an error throws, loading will set to false.

2024-06-18 21:29 UTC, eliykat approved these changes
Thanks!

2024-06-25 20:02 UTC, eliykat commented
@vinith-kovan I didn't realise that Rui's stale review was blocking you. You should be OK to merge now, thank you.

2024-06-26 17:46 UTC, merged