[AC-2484] Fix bug where Custom Users with "Delete any collection" permission incorrectly see "Can Edit" permission for Unassigned Collection
bitwarden/clients pull request #8858
Opened 2024-04-22 14:49 UTC by r-tome

## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-04-23 00:04 UTC, eliykat requested changes

2024-04-23 00:04 UTC, eliykat commented on apps/web/src/app/vault/components/vault-items/vault-collection-row.component.ts
> +    ) {
The ternary `if` statement nested in the regular `if` makes this difficult to understand. Besides that, I don't really understand the logic here, e.g. why it depends on all these variables.

Backing up a little, it seems like we need some logic to determine whether a user can edit unassigned items. Looking around, we already have `organization.canEditUnassignedCiphers`. So this method could read something like:

```ts
if (this.collection.id == Unassigned) {
  return this.organization.canEditUnassignedCiphers
    ? "canEdit"
    : "noAccess";
}

// deal with regular collections here
```

I'm not actually familiar with who can edit unassigned ciphers, so I'd probably defer to @shane-melton as to whether that org method is up-to-date (taking into account flags etc).

2024-04-23 11:31 UTC, shane-melton commented on apps/web/src/app/vault/components/vault-items/vault-collection-row.component.ts
> +    ) {
`organization.canEditUnassignedCiphers` should be up-to-date and applicable here. Only admins/owners and custom users with EditAnyCollection have access to edit unassigned and that hasn't changed with V1. So your suggestion above should work as expected.

Note: Providers are also handled by that method via the `isAdmin` check, and will be updated with the provider restriction work.

2024-04-25 09:31 UTC, shane-melton requested changes
Just wanted to echo Thomas' [request here](https://github.com/bitwarden/clients/pull/8858#discussion_r1575483145) and then I think this is good to go.

2024-04-25 11:35 UTC, r-tome commented on apps/web/src/app/vault/components/vault-items/vault-collection-row.component.ts
> +    ) {
I tried using `organization.canEditUnassignedCiphers` but then, custom users with `DeleteAnyCollection` enabled would read "Can edit" for the Unassigned collection and after clicking no items would appear. Is this the correct behavior?

2024-04-25 11:50 UTC, r-tome commented on apps/web/src/app/vault/components/vault-items/vault-collection-row.component.ts
> +    ) {
I was using `this.organization.canEditUnassignedCiphers` without `()` at the end so it would always be true 😅. I've pushed the requested change, thank you both for your input.

2024-04-25 13:02 UTC, shane-melton approved these changes

2024-04-25 22:34 UTC, eliykat approved these changes
Much nicer!

2024-05-11 13:54 UTC, merged