[PM-7627]
bitwarden/clients pull request #8863
Opened 2024-04-22 18:17 UTC by jprusik

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-04-25 16:04 UTC, cagonzalezcs submitted a review, later dismissed

2024-04-25 21:03 UTC, jprusik commented on apps/browser/src/manifest.v3.json
> +  "host_permissions": ["https://*/*", "http://*/*"],
After testing with @cagonzalezcs , `"*://*/*"` doesn't appear to work as expected, hence the two separate entries here

2024-04-25 21:13 UTC, justindbaur submitted a review, later dismissed

2024-04-25 21:44 UTC, cagonzalezcs approved these changes

2024-04-25 21:46 UTC, cagonzalezcs requested changes

2024-04-25 21:46 UTC, cagonzalezcs commented on apps/browser/src/manifest.v3.json
> +  "host_permissions": ["https://*/*", "http://*/*"],
@jprusik 

We likely should also include `"file:///*"` within this array of items. We seem to be referencing that url pattern in some of the content scripts above.

2024-04-25 21:58 UTC, cagonzalezcs submitted a review, later dismissed

2024-04-26 12:10 UTC, djsmith85 submitted a review, later dismissed
Approving for tools

2024-04-26 13:43 UTC, MGibson1 requested changes
This breaks #8831 (PM-7616, totp scanning in browser) again. If we really can't have `<all_urls>`, we need to investigate the `activeTab` permission. I'll take a look at whether active tab would suffice, but is there some solution that allows us to maintain all url host permissions?

2024-04-26 13:50 UTC, MGibson1 commented
First pass looks like adding `activeTab` to the `permissions` array will fix totp scanning.

2024-04-29 15:38 UTC, jprusik commented
Apologies for the rebase - added @MGibson1 's [suggestion](https://github.com/bitwarden/clients/pull/8863#issuecomment-2079438103) in [d4bbcd1](https://github.com/bitwarden/clients/pull/8863/commits/d4bbcd17818df9118af262df3b75e01dd9c697d6)

2024-04-29 16:49 UTC, djsmith85 submitted a review, later dismissed

2024-04-29 19:54 UTC, justindbaur submitted a review, later dismissed

2024-04-29 21:36 UTC, cagonzalezcs approved these changes

2024-04-29 21:36 UTC, cagonzalezcs commented on apps/browser/src/platform/services/browser-script-injector.service.ts
> +          if (this.platformUtilsService.isDev()) {
```suggestion
        if (
        this.platformUtilsService.isDev() &&
          message ===
          "Cannot access contents of the page. Extension manifest must request permission to access the respective host."
        ) {
```

Nit - This nested `if` statement can be eliminated

2024-04-30 14:17 UTC, jprusik commented on apps/browser/src/platform/services/browser-script-injector.service.ts
> +          if (this.platformUtilsService.isDev()) {
Ah, this is meant to still throw other errors:
cc017eb473ae4861225294843353460b04d96802

2024-04-30 15:30 UTC, jprusik commented on apps/browser/src/platform/services/browser-script-injector.service.ts
> +        // @TODO remove when the bugged behaviour is resolved
[relevant](https://stackoverflow.com/a/74319499):

> chrome.scripting seems to throw this error for tabs that existed prior to installing the extension.
> ...
> Scripting works as expected for any newly created tab, regardless of if the user has clicked the extension.
> I've found a workaround is to call `chrome.tabs.reload(tabId)` on those preexisting tabs, and then `chrome.scripting` will work as expected...

I'm not sure we want to incur the cost of reloading all tabs on extension install (especially since we refresh injections regularly), but something to think about...

2024-04-30 16:00 UTC, cagonzalezcs approved these changes

2024-04-30 16:00 UTC, cagonzalezcs commented on apps/browser/src/platform/services/browser-script-injector.service.ts
> +        // @TODO remove when the bugged behaviour is resolved
Reloading all tabs is a "nuclear option" approach to solving this kind of issue. We definitely would want to find a different approach for resolving this kind of issue.

2024-05-01 08:41 UTC, djsmith85 approved these changes

2024-05-01 14:23 UTC, justindbaur approved these changes

2024-05-01 14:56 UTC, Jingo88 approved these changes

2024-05-02 15:18 UTC, MGibson1 approved these changes

2024-05-02 15:19 UTC, merged