[PM-7662] Suppress welcome window on install when extension is in dev mode
bitwarden/clients pull request #8864
Opened 2024-04-22 18:19 UTC by jprusik

## Type of change

```
- Other
```

## Objective

Don't show the welcome window every time the extension is reinstalled when debugging

2024-04-26 13:26 UTC, MGibson1 requested changes
Sorry for the bad communication, but this isn't what I meant. the section o the code I linked define compile time flags that are never true in prod environments, but are configurable in dev environments.

I want to be able to easily turn this back on should we need to test

2024-05-01 15:24 UTC, jprusik commented on apps/browser/config/base.json
> -  "dev_flags": {},
This and the update in desktop base config are presumptive given no apparent consumption of this casing pattern.

![Screenshot 2024-05-01 at 11 21 03 AM](https://github.com/bitwarden/clients/assets/1556494/5a47f200-dcaf-4769-bea6-651b3871710f)

2024-05-02 15:29 UTC, MGibson1 approved these changes
nice, thank you!

2024-05-02 15:29 UTC, MGibson1 commented on apps/browser/config/base.json
> -  "dev_flags": {},
yep, should be camel case, thank you

2024-05-06 19:25 UTC, merged