AC-2402 Migrate sponsoring org row component
bitwarden/clients pull request #8894
Opened 2024-04-24 07:51 UTC by KiruthigaManivannan

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other
```

## Objective

Migrate the Sponsoring Org Row component to use the component library.

## Code changes

- **sponsoring-org-row.component.html:** Table row cells are migrated , Menu component added to one of the cell.
- **sponsoring-org-row.component.ts:** Removed form promise.

## Screenshots

https://github.com/bitwarden/clients/assets/162679756/9c8e9d52-f819-49e7-a09c-152a61b1267a

2024-04-24 15:03 UTC, r-tome requested changes
Good start, I've left some feedback in the comments

2024-04-24 17:26 UTC, willmartian commented on apps/web/src/app/admin-console/settings/sponsoring-org-row.component.html
> +  <button
Some of these differences are okay--that is just what the components look like. 

However, cc @bitwarden/dept-design 
1. the button should be positioned at the _end_ of the row
2. Should this icon be updated from cog to vertical ellipsis? 
3. I think this icon button should be `buttonType="main"`
4. I'm not sure why the extra classes defined on this button are necessary

2024-04-24 17:35 UTC, danielleflinn commented on apps/web/src/app/admin-console/settings/sponsoring-org-row.component.html
> +  <button
1. Yes
2. Yes
3. Yes
4. Agreed

2024-04-24 17:37 UTC, danielleflinn commented on apps/web/src/app/admin-console/settings/sponsoring-org-row.component.html
> +  <button
It would also be good to add an "Options" label to that column's table header

2024-04-24 17:44 UTC, willmartian commented on apps/web/src/app/admin-console/settings/sponsoring-org-row.component.ts
>    statusClass: "text-success" | "text-danger" = "text-success";
These classes also need to be migrated to Tailwind.

2024-05-02 10:42 UTC, KiruthigaManivannan commented on apps/web/src/app/admin-console/settings/sponsoring-org-row.component.html
> +  <button
All the above changes are done except for "Options" label to be added in header. This can only be done in parent component.

2024-05-02 14:52 UTC, r-tome approved these changes
Looks good to me!

2024-05-21 13:26 UTC, merged