[AC-217] Migrate to Banner Component
bitwarden/clients pull request #8899
Opened 2024-04-24 14:26 UTC by nick-livefront

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Migrate Minimum Browser, Low KDF, Email Verification, & Premium cards to the component library banner. 

## Code changes

- **vault-banners.component.ts**
  - Contains the UI for each of the banners
- **vault-banners.service.ts**
  - Consolidated all logic for when a individual banner should be shown & handling when they're dismissed
  - All of the logic was pre-existing in `vault.component.ts`
- **state-definitions.ts**
  - Added keys for localStorage & sessionStorage integrations for the banners. 
- **vault.component.ts**
   - Removed all logic for showing/hiding banners (migrated to `vault-banners.service.ts`)
   - Removed classes for displaying a shortened grid when the old cards were visible.
- **verify-email.component.ts** 
  - Refactor `VerifyEmailComponent` to use the component library banner rather than a card UI.
- **low-kdf.component.ts**
  - Removed this component as it was only UI and easy to implement within the `VaultBannersComponent`
## Screenshots

<img width="1655" alt="Screenshot 2024-04-24 at 9 25 59 AM" src="https://github.com/bitwarden/clients/assets/125900171/76a85690-4ed9-435b-b78b-5594de750f5d">

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-04-25 10:00 UTC, shane-melton requested changes
This is looking great! The tests and new vault banner service are very much appreciated! 

I mostly had a couple suggestions regarding the usage of `bitBanner` and the style overrides. Otherwise, just a few other comments/questions here and there.

2024-04-25 14:29 UTC, gbubemismith reviewed
Thanks for working on this, @nick-livefront; @shane-melton raised some valid points; other than that, this is looking good

2024-04-25 15:47 UTC, nick-livefront commented on apps/web/src/app/shared/loose-components.module.ts
Good question, maybe there's some more refactoring I can do alongside of this to achieve that. I'm seeing errors without `BannerModule` defined in `LooseComponentsModule`, I believe because the `VerifyEmailComponent` is also defined there. 

The `VaultBannersComponent` is the only usage of `VerifyEmailComponent` that I can see, I could relocated the component itself closer to the usage. Any cons you can think of to doing so?

2024-04-25 15:50 UTC, nick-livefront commented on apps/web/src/app/vault/individual-vault/vault.component.ts
Thanks! It did feel good to strip out some isolated logic 😄

2024-04-25 16:01 UTC, nick-livefront commented on libs/common/src/platform/state/state-definitions.ts
> +export const BANNERS_DISMISSED_DISK = new StateDefinition("bannersDismissed", "disk");
Yes, I think `DiskLocal` could be used to handle both sets of logic for dismissing the banners. I choose to use the two separate implementations because it aligned directly with the requirements of the banners. 
- The dismissal of the premium banner is stored in `localStorage` as the reprompt is based on a date rather than the users session.
- Dismissal of Verify Email, Low KDF, and Outdate Browser banners should only persist through the users session, which felt natural for `sessionStorage`. 

Do you think there is an added benefit to using `DiskLocal`/`localStorage` for handling all of the logic?

2024-04-25 19:52 UTC, nick-livefront commented on apps/web/src/app/vault/individual-vault/vault.component.html
> +  <div class="col-9">
Great callout, I replaced with the equivalent tailwind styles
[ae7af20](https://github.com/bitwarden/clients/pull/8899/commits/ae7af202c2c313906be6d15135c888a918d37399)

2024-04-25 19:54 UTC, nick-livefront commented on apps/web/src/app/vault/individual-vault/vault-banners/services/vault-banners.service.ts
> +  async shouldShowPremiumBanner(): Promise<boolean> {
Changing to an observable definitely felt like a code improvement. I pondered if each of the APIs should be an observable rather than a method but I had mixed feelings when I started to implement that. If you think that's worth pursuing I can revist!

[93463d4](https://github.com/bitwarden/clients/pull/8899/commits/93463d47e5c55735f34cf07ffa89ebd52d5e922b)

2024-04-25 19:55 UTC, nick-livefront commented on apps/web/src/app/auth/settings/verify-email.component.html
> +    class="!tw-text-contrast !tw-font-bold tw-bg-warning-600 tw-border-0 hover:!tw-underline focus-visible:tw-ring focus-visible:tw-ring-offset-2 focus-visible:tw-ring-primary-700 focus-visible:tw-z-
Thanks for the link! I updated all of the banner styles to use the `bitLink` directive.

[5bc5649](https://github.com/bitwarden/clients/pull/8899/commits/5bc56492978a1a624185e64e246890153ba5c43a)

2024-04-29 17:35 UTC, shane-melton commented on apps/web/src/app/shared/loose-components.module.ts
Ah, yeah, the `VeryifyEmailComponent` is likely the culprit for that. I don't think we necessarily want to move it as its owned by Auth. But, I could see us making it a [standalone component](https://angular.io/guide/standalone-components) and removing it from the `LooseComponentsModule` (and the `BannerModule` as well). @bitwarden/team-auth-dev How do you all feel about that?

If not that, I think it makes sense to just include/export the `BannersModule` in the `SharedModule` and remove the explicit imports in the other modules.

2024-05-01 16:40 UTC, jlf0dev commented on apps/web/src/app/shared/loose-components.module.ts
I think moving that to a standalone component is a great idea! I'm not sure how much scope creep that would add to this though, is that doable? Or should we go with @shane-melton's other option and plan for that at a future date?

2024-05-01 17:18 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault-banners/services/vault-banners.service.ts
> +    return combineLatest([
suggestion: This looks great as an observable! One small concern is we're rebuilding a new observable for every caller of `shouldShowPremiumBanner()`. 

Perhaps we should just make a `shouldShowPremiumBanner$` public observable property on the service and build it in the constructor once. The `UserDecryptionOptionsService` has a pretty good example of this practice [here](https://github.com/bitwarden/clients/blob/main/libs/auth/src/common/services/user-decryption-options/user-decryption-options.service.ts)

2024-05-01 17:18 UTC, shane-melton commented on libs/common/src/platform/state/state-definitions.ts
> +export const BANNERS_DISMISSED_DISK = new StateDefinition("bannersDismissed", "disk");
Ah, forgot that the Verify Email, Low Kdf, and Outdated browser banners should only persist for the session. In that case it makes sense to have the separate definitions. 

The only thing that seems confusing to me still is calling it `DISK` when its only stored for the session (on Web anyways). But, that's not related to this PR and I think we can leave what you have as is.

2024-05-01 17:19 UTC, shane-melton reviewed
One last comment/suggestion for the premium observable. Otherwise, I think this is looking really good!

2024-05-01 20:34 UTC, nick-livefront commented on apps/web/src/app/shared/loose-components.module.ts
It didn't feel like too much of a scope creep! Added [4d94466](https://github.com/bitwarden/clients/pull/8899/commits/4d94466d9be3091d063b1bad9de6fcbc574f3e74)

Let me know if I missed anything related to the migration 🚀

2024-05-01 20:35 UTC, nick-livefront commented on apps/web/src/app/vault/individual-vault/vault-banners/services/vault-banners.service.ts
> +    return combineLatest([
Thanks for example, swapped over to passing through observable straight through!

[90ad77a](https://github.com/bitwarden/clients/pull/8899/commits/90ad77a89b8e77ba1b28567d3f12e1b54a00822b)

2024-05-01 22:27 UTC, shane-melton approved these changes
Looks great, nice work!

2024-05-02 19:06 UTC, gbubemismith approved these changes

2024-05-07 13:42 UTC, nick-livefront commented
@justindbaur @ike-kottlowski When you have some time, would you be able to review this PR?

2024-05-07 14:26 UTC, justindbaur submitted a review, later dismissed

2024-05-09 15:27 UTC, jlf0dev approved these changes

2024-05-14 16:00 UTC, justindbaur requested changes
One recommendation for the syncCompleted$ observable.

2024-05-14 16:00 UTC, justindbaur commented on apps/web/src/app/vault/individual-vault/vault-banners/services/vault-banners.service.ts
> +      map(([canAccessPremium, dismissedState]) => {
```suggestion
    this.shouldShowPremiumBanner$ = combineLatest([
      this.billingAccountProfileStateService.hasPremiumFromAnySource$,
      this.premiumBannerState.state$,
    ]).pipe(
      skipUntil(() => this.syncCompleted$),
      map(([canAccessPremium, dismissedState]) => {
```

Even though `combineLatest` does work it will keep subscribed to `syncCompleted$` until it's resulting observable is unsubscribed from. With it in `skipUntil` it will unsubscribe once it got the "notification". Eventually I will add a `lastSync$` method on sync service which will be a stream of those last sync dates and you could `filter` out the `null`. I think using `skipUntil` now would make that a smaller refactor and be a little more efficient when that happens.

2024-05-14 19:27 UTC, nick-livefront commented on apps/web/src/app/vault/individual-vault/vault-banners/services/vault-banners.service.ts
> +      map(([canAccessPremium, dismissedState]) => {
@justindbaur Thanks for pointing this out, I spent probably to much time trying to work in `skipUntil` but based on the logic flow I don't think it works in this use case. 

`skipUntil` will skip the emissions from `combineLatest` until `this.syncCompleted$` emits. For this use case, `combineLatest` will usually emit before `this.syncCompleted$` and doesn't reemit again unless something were to change. I tried using `skipUntil` in combination with a couple other operators but I couldn't get the previous value from the `combineLatest` after `skipUntil` passes. Let me know if I missed something obvious here!

I ended up using a `ReplaySubject` & `take(1)` to replay the `combineLatest`. Let me know what you think! [9f43b01](https://github.com/bitwarden/clients/pull/8899/commits/9f43b0166a3961a4471d7f03caa73c1b19253486)

2024-05-16 22:01 UTC, justindbaur commented on apps/web/src/app/vault/individual-vault/vault-banners/services/vault-banners.service.ts
> +      map(([canAccessPremium, dismissedState]) => {
@nick-livefront Thanks for giving it a try, I definitely led you astray with `skipUntil`, for whatever reason I thought it would avoid subscribing to the source observable until it emitted, then it would subscribe and the `combineLatest` would go and get it's values for the first time. None of the documentation or examples back me up on that so who knows where I got that. 

What you came up with is quite good, I think you could `mergeMap(() = premiumSource$)` directly and not need the intermediary `ReplaySubject`. But this will have the difference where those values will first get subscribed to when the sync has completed vs already going for a value and having it cached and ready to go when the sync completes. Those values should be grabbed pretty quickly though.

2024-05-16 23:40 UTC, nick-livefront commented on apps/web/src/app/vault/individual-vault/vault-banners/services/vault-banners.service.ts
> +      map(([canAccessPremium, dismissedState]) => {
For sure, to me it felt like it _should_ be a common scenario enough that it would be available with some operator. 

Anyways, one less operator the better! [fc1c4ca](https://github.com/bitwarden/clients/pull/8899/commits/fc1c4ca8f4ea28c38f40214a797d94642f69ef18)

2024-05-17 00:12 UTC, shane-melton approved these changes

2024-05-17 01:04 UTC, justindbaur commented on apps/web/src/app/vault/individual-vault/vault-banners/services/vault-banners.service.ts
> +      map(([canAccessPremium, dismissedState]) => {
Yeah same, I really thought there was going to be something built in, but the `take(1), mergeMap(...)` gives the exact pattern I was hoping for. If you're at all interested [this](https://stackblitz.com/edit/typescript-spgadh?file=index.ts) is where I played around to make sure it subscribes and unsubscribes to everything in the order I was expecting. The `docClick$` is the sync completed essentially and the `timer` and `interval` are the two states that will emit at least once but not ever again necessarily. It looks perfect, thanks for doing this!

2024-05-17 01:04 UTC, justindbaur approved these changes

2024-05-20 14:12 UTC, nick-livefront commented
@jlf0dev When you have some time, could you give this one another review?

2024-05-20 15:29 UTC, jlf0dev approved these changes

2024-05-20 21:06 UTC, merged