Auth/pm 7392/token service add secure storage fallback
bitwarden/clients pull request #8913
Opened 2024-04-25 00:39 UTC by JaredSnider-Bitwarden

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-05-07 12:16 UTC, MGibson1 requested changes
I see what you're doing trying to alert and logout from these locations, but they are so deep in the stack that you cannot rely on the methods you're using.

If we must log out here rather than when attempting to use the token (which occurs only in api service and vault timeout service), you need to pass in a logout callback like api service already does.

Similarly, you could do the same to display a toast, but the platformUtilService dependence won't work either.

2024-05-07 14:45 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/token.service.ts
> +          // Remove this call to remove the access token from memory after 3 releases.
Ok, the link has been removed. Ah, my bad regarding the release timeframe. I was still in the mindset of monthly releases when I wrote those. TIL about the due date field. Appreciate the information!

2024-05-07 14:51 UTC, JaredSnider-Bitwarden commented on libs/common/src/platform/models/domain/enc-string.spec.ts
> +  describe("isSerializedEncString", () => {
Ah, I missed that. Sorry about that. I've moved the new tests to the existing describe.

2024-05-07 15:43 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/token.service.spec.ts
Updated all tests to adhere to convention.

2024-05-07 17:57 UTC, JaredSnider-Bitwarden commented on libs/common/src/services/api.service.ts
> +    // Log the error so it isn't lost. The error throw below is lost.
In the scenario that I tested in (calling `ApiService.refreshIdentityToken()` directly), the error was lost completely. Here's a video of my testing which made me want to add logging and a toast for the user. 

https://github.com/bitwarden/clients/assets/116684653/3dc874c0-a39f-41ce-a92e-92cdbec98e12

2024-05-07 18:28 UTC, JaredSnider-Bitwarden commented on apps/desktop/src/main.ts
> +      this.messagingService,
I don't fully understand what you are getting at here. The `StateService` is still needed in `main.ts`. Thus, we still need to have the `TokenService` definition until the `StateService` can be removed.

2024-05-07 18:35 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/enums/logout-reason.enum.ts
> +  REFRESH_TOKEN_SECURE_STORAGE_RETRIEVAL_FAILED = "logoutReasonRefreshTokenSecureStorageRetrievalFailure",
Swapped the enum for a string union type.

2024-05-07 18:40 UTC, JaredSnider-Bitwarden commented on apps/cli/src/bw.ts
> +      this.messagingService,
That seems fine. The CLI currently returns false for `platformSupportsSecureStorage` so it will never hit any scenario where we need to log the user out.

2024-05-07 20:01 UTC, JaredSnider-Bitwarden commented on libs/common/src/services/api.service.ts
> +    );
Notes for reviewers:  I worked with @MGibson1 and @justindbaur synchronously to implement a new callback based approach to remove the `MessengingService` from the `ApiService`.

2024-05-09 21:16 UTC, JaredSnider-Bitwarden commented on apps/cli/src/bw.ts
> +      this.messagingService,
Per our sync meeting, we've removed the use of the `messagingService`.

2024-05-09 21:17 UTC, JaredSnider-Bitwarden commented on apps/desktop/src/app/app.component.ts
> +      await new Promise((resolve) => setTimeout(resolve, 5000));
Per our discussion and a discussion with @willmartian , we've migrated to using simple dialogs that the user must acknowledge to proceed w/ the process reload. This ensures they understand why they are being logged out.

2024-05-09 21:17 UTC, JaredSnider-Bitwarden commented on apps/desktop/src/app/app.component.ts
> +      await new Promise((resolve) => setTimeout(resolve, 5000));
Video (note: we changed the dialog type to danger after this was recorded):

https://github.com/bitwarden/clients/assets/116684653/9623e4e5-89e6-4d23-b9d3-4015f69db8da

2024-05-09 21:18 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/token.service.ts
Per discussion, I moved towards using the `logoutCallback` which I refactored to support the new `LogoutReason` type.

2024-05-09 21:22 UTC, JaredSnider-Bitwarden commented
Notes for reviewers about the latest changes:
- The `ApiService` now uses a new `refreshAccessTokenErrorCallback` to ensure that any error in refreshing an access token is not swallowed silently like was before. 
- The `TokenService` now uses the `logoutCallback` for triggering the logout 
- I refactored the existing `logoutCallback` from accepting a single `expired` boolean to accept the new `LogoutReason` custom type so we have the option of handling error scenarios differently in each client's `app.component`

2024-05-13 16:46 UTC, MGibson1 submitted a review, later dismissed
Thanks for all these changes! looks much better 👍

2024-05-13 16:46 UTC, MGibson1 commented on apps/browser/src/background/main.background.ts
> +      },
**nit**: Extract to method

2024-05-13 16:46 UTC, MGibson1 commented on apps/cli/src/bw.ts
> +      },
**nit**: better as a named callback like `logoutCallback`, doesn't have to be a class property. It's just nice to have a name.

2024-05-13 17:03 UTC, jlf0dev submitted a review, later dismissed
Fantastic work! Nothing blocking here, just some nits and questions

2024-05-13 17:49 UTC, JaredSnider-Bitwarden commented on apps/desktop/src/app/app.component.ts
> +        if (this.activeSimpleDialog) {
We cannot return early in any of the calls to logout because then the process reload will occur and the user cannot see the original simple dialog. We must await the initial dialog's close event for all calls to the logout method.

2024-05-13 18:09 UTC, JaredSnider-Bitwarden commented on apps/browser/src/background/main.background.ts
> +      },
Good call!

2024-05-13 18:12 UTC, justindbaur commented on apps/browser/src/popup/app.component.ts
> +                await this.displayLogoutReason(msg.logoutReason);
Almost certainly no good reason, just needing to be able to tap logic into the pre logout and post logout phase. But there isn't a need to do that with tons of messaging long term IMO.

2024-05-13 18:13 UTC, JaredSnider-Bitwarden commented on apps/cli/src/bw.ts
> +      },
Fixed!

2024-05-13 18:20 UTC, JaredSnider-Bitwarden commented on libs/angular/src/services/jslib-services.module.ts
> +          messagingService.send("logout", { logoutReason: logoutReason, userId: userId }),
We discussed and we can fix this in separate PR.

2024-05-13 18:21 UTC, JaredSnider-Bitwarden commented on apps/browser/src/popup/app.component.ts
> +                await this.displayLogoutReason(msg.logoutReason);
Interesting. I'll make a note to investigate why it is necessary.

2024-05-13 18:52 UTC, jlf0dev approved these changes

2024-05-13 19:21 UTC, jprusik approved these changes
Approved for Autofill concerns, and scanned otherwise; LGTM

2024-05-13 20:09 UTC, willmartian approved these changes
Approving for CL 🚀

2024-05-13 20:17 UTC, shane-melton submitted a review, later dismissed

2024-05-16 13:35 UTC, jprusik approved these changes
re-approving and [re-run BIT](https://github.com/bitwarden/browser-interactions-testing/actions/runs/9113218740) 👍

2024-05-21 14:11 UTC, jprusik approved these changes

2024-05-28 16:30 UTC, jprusik approved these changes

2024-06-03 14:22 UTC, jprusik submitted a review, later dismissed

2024-06-03 14:26 UTC, shane-melton approved these changes
Vault change looks good!

2024-06-03 15:08 UTC, shane-melton approved these changes

2024-06-03 15:09 UTC, jprusik approved these changes

2024-06-03 16:27 UTC, MGibson1 approved these changes

2024-06-03 16:34 UTC, willmartian approved these changes

2024-06-03 16:36 UTC, merged