[SM-1192] displaying full project name in tooltip and allowing more of project name in bit badge/project column
bitwarden/clients pull request #8917
Opened 2024-04-25 14:59 UTC by cd-bitwarden

Allowing max width adjustment on bit badge and not truncating the tooltip 

## Type of change

```
- [ x ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Allowing max width adjustment on bit badge and not truncating the tooltip so the user can see more of the project name easily when viewing the secrets list.

## Code changes

Updated the bit badge directive file to allow customizing the max width, removing truncation pipe from the project name on the secrets list.

- **file.ext:** Description of what was changed and why

## Screenshots
Updated UI
![image](https://github.com/bitwarden/clients/assets/106776772/bb282480-eaae-4fb4-bae2-c4f8c2b3641f)
## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-04-26 20:21 UTC, Thomas-Avery approved these changes
Looks good from the SM perspective. 

Let's make sure the component library team is good with the proposed change.

2024-05-01 15:17 UTC, Thomas-Avery approved these changes

2024-05-10 03:35 UTC, willmartian requested changes
Hey @cd-bitwarden! Looks good, tiny change request:

2024-05-10 03:35 UTC, willmartian commented on libs/components/src/badge/badge.directive.ts
> +  @Input() maxWidth = "tw-max-w-40";
Could you update the type to be more restrictive? And the name to convey that we expect a Tailwind class instead of a raw value. 

```ts
  @Input() maxWidthClass: `tw-max-w-${string}` = "tw-max-w-40";
```

2024-05-16 19:49 UTC, cd-bitwarden commented on libs/components/src/badge/badge.directive.ts
> +  @Input() maxWidth = "tw-max-w-40";
@willmartian done 😄 thank you for the great suggestion!

2024-05-16 19:51 UTC, willmartian approved these changes
LGTM, thank you!

2024-05-16 19:58 UTC, cd-bitwarden commented
@Thomas-Avery can you please review the newest changes when you have time, Will had me make 1 small change 😄

2024-05-16 22:02 UTC, Thomas-Avery approved these changes
LGTM

2024-06-04 14:58 UTC, merged