[PM-2056] update two factor duo dialog
bitwarden/clients pull request #8976
Opened 2024-04-29 17:36 UTC by vinith-kovan

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [X] Other
```

## Objective

Update Two Factor duo component to use the component library.

## Code changes

two-factor-duo.component.html - Updated the bootstrap CSS to use the equivalent components from the Component Library.
two-factor-duo.component.ts - Updated the dialog service from modal.
two-factor-setup.component.ts - Updated the duo switch case to call the two-factor duo dialog service.

## Screenshots

https://github.com/bitwarden/clients/assets/156108204/ab1ec4e1-cba4-4d9a-9046-2e9975d691f2

2024-05-09 13:24 UTC, jlf0dev requested changes

2024-05-09 13:24 UTC, jlf0dev commented on apps/web/src/app/auth/settings/two-factor-duo.component.ts
> +    return super.disable(this.formPromise);
if we don't have any extra logic here, I don't think we need the extra method.

2024-05-09 13:24 UTC, jlf0dev commented on apps/web/src/app/auth/settings/two-factor-duo.component.html
> +        <img class="tw-float-right ml-3 mfaType2" alt="Duo logo" />
`ml-3` should be `tw-ml-3`

2024-05-09 13:24 UTC, jlf0dev commented on apps/web/src/app/auth/settings/two-factor-duo.component.ts
> +    return super.disable(this.formPromise);
Do we need the `formPromise` anymore? If its not being used we can remove it.

2024-05-09 13:24 UTC, jlf0dev commented on apps/web/src/app/auth/settings/two-factor-base.component.ts
>    protected async disable(promise: Promise<unknown>) {
I know this may not make sense to do in this PR, but can you remove the passed in `promise` from the base component? We don't need it anymore since the `bitSubmit` will handle the loading state.

2024-05-16 17:54 UTC, vincentsalucci commented on apps/web/src/app/admin-console/organizations/settings/two-factor-setup.component.ts
> +        if (response !== null) {
Any reason in particular why we need this `null` check? From what I can see, the `this.enabled` boolean is set when the duo component is _initialized_ and when a response is _received_ from the API. Regardless, a value will always be sent back when the dialog is closed.

2024-05-20 10:50 UTC, vinith-kovan commented on apps/web/src/app/auth/settings/two-factor-duo.component.ts
> +    return super.disable(this.formPromise);
We are not able to call super inside an arrow function that's why we have created this method to call.

2024-05-20 11:02 UTC, vinith-kovan commented on apps/web/src/app/auth/settings/two-factor-base.component.ts
>    protected async disable(promise: Promise<unknown>) {
If we remove this promise from this method then we have to adjust all the two-factor methods, Is that okay?

2024-06-20 09:17 UTC, vinith-kovan commented on apps/web/src/app/admin-console/organizations/settings/two-factor-setup.component.ts
> +        if (response !== null) {
Yes, you're right we don't need this `null` check here. I'll remove it.

2024-06-26 13:03 UTC, jlf0dev approved these changes

2024-06-26 16:02 UTC, vincentsalucci approved these changes

2024-06-26 17:55 UTC, merged