[AC- 2493] Restore and Delete Unassigned Items
bitwarden/clients pull request #8983
Opened 2024-04-29 23:01 UTC by Jingo88

```
- [ X ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Allow Owners and Admins to restore and delete unassigned items. Flows checked are

- soft delete single
- soft delete bulk
- perm delete single
- perm delete bulk
	- all same collection
	- different collection (unassigned + assigned)
- restore single item
- restore bulk item
	- all same collection
	- different collection (unassigned + assigned)

## Code changes

- `bulk delete dialog- now takes an extra optional array of unassigned items
- `vault component org` - add logic for unassigned items to delete and restore methods
- `cipher service` - updated `restorewithmanyserver` method. `asAdmin` was not in use

2024-04-30 16:30 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/bulk-action-dialogs/bulk-delete-dialog/bulk-delete-dialog.component.ts
> +  private async deleteCiphersAdmin(ciphers: string[]): Promise<any> {
nit (non-blocking): We can use the `CipherId` type instead of `string`.

2024-04-30 16:31 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/bulk-action-dialogs/bulk-delete-dialog/bulk-delete-dialog.component.ts
> +  unassignedCiphers: string[];
nit (non-blocking): We should be able to use `CipherId` instead of `string` here.

2024-04-30 16:39 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +      const isUnassigned = c.collectionIds.length === 0;
question: What do you think about putting a `getter` or helper method on the `CipherView` that does this length check instead of having to repeat it everywhere? Something like:

```ts
get isUnassigned(): boolean {
   return this.organizationId != null && (this.collectionIds == null || this.collectionIds.length === 0);
}
```

2024-04-30 16:40 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +    const editAccessCiphers: string[] = [];
nit (non-blocking): `CipherId` instead of `string`.

2024-04-30 16:42 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +    const orgId = ciphers[0]?.organizationId;
question: Any particular reason were indexing into the `ciphers` array to get the organization id instead of using `this.organization`? I don't think these will ever be different since we're in the org vault in this component.

2024-04-30 16:43 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +    const unassignedCiphers: string[] = [];
nit (non-blocking): `CipherId` instead of `string`

2024-04-30 16:44 UTC, shane-melton commented on libs/common/src/vault/abstractions/cipher.service.ts
> +  restoreManyWithServer: (ids: string[], orgId?: string) => Promise<void>;
nit (non-blocking): Since we're modifying this signature already, can we also use the `CipherId` and `OrganizationId` types as well?

2024-04-30 16:47 UTC, shane-melton commented on libs/common/src/vault/abstractions/cipher.service.ts
> +  restoreManyWithServer: (ids: string[], orgId?: string) => Promise<void>;
suggestion: Can we add some docs to help clarify when the `orgId` should be provided since we're combining it with the `asAdmin` flag? e.g. It should be provided when attempting to restore ciphers as an administrator.

2024-04-30 17:55 UTC, Jingo88 commented
Unable to update those nits. It will require us to update `CipherView` to have the id set to `CipherId`. this is a larger change. I created a tech debt ticket to address it. https://bitwarden.atlassian.net/browse/PM-7834

2024-04-30 22:31 UTC, shane-melton approved these changes
Looks good, thanks for making those changes!

2024-05-03 16:22 UTC, shane-melton submitted a review, later dismissed

2024-05-07 07:56 UTC, LRNcardozoWDF submitted a review, later dismissed

2024-05-07 20:02 UTC, shane-melton requested changes
One small tweak to use some existing permission logic and then I think we're good to go!

2024-05-07 20:02 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/bulk-action-dialogs/bulk-delete-dialog/bulk-delete-dialog.component.ts
> +      (this.organization.isAdmin || this.organization.permissions.editAnyCollection)
suggestion: I think we should use the existing `this.organization.canEditUnassignedCiphers()` as it will also take providers into consideration.

2024-05-07 20:37 UTC, shane-melton submitted a review, later dismissed
Looks good, thanks!

2024-05-13 23:06 UTC, shane-melton approved these changes

2024-05-15 20:51 UTC, shane-melton requested changes
Thanks for catching those missing custom permission checks for restoring ciphers! However, it think you added the checks in a few other places we don't need and will cause some issues.

2024-05-15 20:51 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +      !this.organization.permissions.deleteAnyCollection &&
issue: `organization.permissions.deleteAnyCollection` does not give users the ability to delete ciphers.

2024-05-15 20:51 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +      !this.organization.permissions.deleteAnyCollection &&
suggestion: While `organization.permissions.deleteAnyCollection` isn't causing an issue, we should not need to add it because its already handled within `colleciton.canDelete()` after digging through it a bit in the `CollectionAdminView`.

Which brings up a related point, we should update the signature of this method to be `collection: CollectionAdminView` to make this more clear. The org vault uses `CollectionAdminViews` for its collections (see `protected collections` at the top of the class) so we should use that type when possible.

2024-05-15 20:51 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +      !this.organization.permissions.deleteAnyCollection &&
issue: Users with delete any collection should not be able to delete any cipher. The custom permission check is being taken care of above `canDeleteCollections` above via the `c.canDelete()` method.

2024-05-15 20:51 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +      !this.organization.permissions.editAnyCollection &&
suggestion: This is also already considered in the `c.canEdit` below and can be removed.

2024-05-16 14:13 UTC, Jingo88 commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +      !this.organization.permissions.deleteAnyCollection &&
I believe they have to be `CollectionView` because of the `VaultItemEvent` that's shared between both vaults

2024-05-16 14:19 UTC, Jingo88 commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +      !this.organization.permissions.deleteAnyCollection &&
hmm `(!canDeleteCiphers || !canDeleteCollections)` is going to pass and show the error message for the Custom User. We can add the `this.organization.canEditAllCiphers` here for the custom user logic.

2024-05-16 14:35 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +      !this.organization.permissions.deleteAnyCollection &&
Ah, I see what you mean 🤔 

I think we should still be able to use `CollectionAdminView` and cast the `VaultItemEvent` item(s) to `CollectionAdminView` since that is what the `VaultItems` component is being given anyways.

2024-05-16 14:37 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +      !this.organization.permissions.deleteAnyCollection &&
Oh, good point, we'll need the `this.organization.canEditAllCiphers` call in the `canDeleteCiphers` assignment above instead of the `this.organization.allowAdminAccessToAllCollectionItems`

2024-05-17 15:25 UTC, shane-melton requested changes
One last thing and then I think we're good to go!

2024-05-17 15:25 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +      !this.organization.canEditAllCiphers(
suggestion: We should move this condition into `canDeleteCiphers` above in place of the `allowAdminAccessToAllCollectionItems` check. And then remove it from the `if`. There is a chance a user will have access to requested ciphers, but not the requested collections and this case would not be handled appropriately as currently written.

```ts
const canDeleteCiphers =
      ciphers == null ||
      this.organization.canEditAllCiphers(
        this.flexibleCollectionsV1Enabled,
        this.restrictProviderAccessEnabled,
      ) ||	
      ciphers.every((c) => c.edit);	
```

2024-05-17 16:08 UTC, Jingo88 commented on apps/web/src/app/vault/org-vault/vault.component.ts
> +      !this.organization.canEditAllCiphers(
ah good call.

2024-05-17 16:39 UTC, shane-melton requested changes

2024-05-17 16:39 UTC, shane-melton commented on apps/web/src/app/vault/org-vault/vault.component.ts
>        this.organization.allowAdminAccessToAllCollectionItems ||
We need to remove `this.organization.allowAdminAccessToAllCollectionItems` as its already considered in `canEditAllCiphers` and doesn't actually check if the user is an admin/owner itself.

2024-05-17 17:34 UTC, shane-melton approved these changes
Thank you!!

2024-05-21 16:32 UTC, merged