PM-7843 Two Factor Verification is Empty on Organization duo 2fa
bitwarden/clients pull request #9008
Opened 2024-05-02 07:23 UTC by KiruthigaManivannan

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

 Two factor verification should be done on Organization Duo 2FA

## Code changes

- **src\app\admin-console\organizations\settings\two-factor-setup.component.ts:** Two Factor verification dialog open on manage button click. Logic added in switch case.

## Screenshots

https://github.com/bitwarden/clients/assets/162679756/59d344ee-c6e3-4a03-b44a-45e4b79923ab

2024-05-02 21:20 UTC, addisonbeck approved these changes

2024-05-02 21:23 UTC, addisonbeck requested changes

2024-05-02 21:23 UTC, addisonbeck commented on apps/web/src/app/admin-console/organizations/settings/two-factor-setup.component.ts
> +          this.updateStatus(enabled, TwoFactorProviderType.Duo);
This shouldn't be changed, right? We're dealing with the `OrganizationDuo` 2FA type.

2024-05-03 00:02 UTC, trmartin4 commented on apps/web/src/app/admin-console/organizations/settings/two-factor-setup.component.ts
> +          this.updateStatus(enabled, TwoFactorProviderType.Duo);
Correct.  This is still the `OrganizationDuo` type we should be dealing with.  @KiruthigaManivannan this should remain the same.

2024-05-03 05:16 UTC, KiruthigaManivannan commented on apps/web/src/app/admin-console/organizations/settings/two-factor-setup.component.ts
> +          this.updateStatus(enabled, TwoFactorProviderType.Duo);
@trmartin4 Yes changed the code.

2024-05-03 16:33 UTC, addisonbeck approved these changes

2024-05-05 18:54 UTC, merged