PM- 2059 Update Two factor webauthn dialog
bitwarden/clients pull request #9009
Opened 2024-05-02 08:13 UTC by KiruthigaManivannan

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other
```

## Objective

Update Two factor webauthn dialog component to use the component library

## Code changes

- **two-factor-webauthn.component.html:** Converted modal to dialog compoenents
- **two-factor-webauthn.component.ts:** Added dialog open method. Data passed to dialog is typed.
- **two-factor-setup.component.ts:** Added Web authn dialog logic and passing the result of two factor verify dialog in the switch statement of mange method call.

## Screenshots

https://github.com/bitwarden/clients/assets/162679756/28f189ff-d39f-4e52-aa8f-e157ba9e09bb

2024-05-02 08:16 UTC, KiruthigaManivannan commented
@rr-bw When I click the read key button , it is not opening the windows authentication using PIN like in QA vault. That may be due to that im running using local host. Because I get the following err ..
![image](https://github.com/bitwarden/clients/assets/162679756/f5e9d7d9-c195-4b4a-98b2-52914ef345ae)

This error is due to the rp value in publicKeyCredentials passed to navigator. So I think this will work in qa vault

2024-05-22 15:59 UTC, KiruthigaManivannan commented
> > When I click "Save" I get the following error, are you able to track this down? Everything works fine on `main`. Let me know if you need help debugging.
> > ![Screenshot 2024-05-17 at 11 42 33 AM](https://private-user-images.githubusercontent.com/102181210/331700583-7974960a-b569-4f72-a370-4ad395116c62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNDUwOTgsIm5iZiI6MTcxNjI0NDc5OCwicGF0aCI6Ii8xMDIxODEyMTAvMzMxNzAwNTgzLTc5NzQ5NjBhLWI1NjktNGY3Mi1hMzcwLTRhZDM5NTExNmM2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQyMjM5NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZmZmYjc4YzM3ZjgzMWY5YjdjYTdkMDY2MTc2NmYxNTEyOWM3OTVmOGE1YjJmZDJiZTkwNTY0ZDY4MmVlY2E4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IoV8iwB5RyIx5uSqBlpt8S6Hxp7xURZAq6Tkkzg0x60)
> 
> @rr-bw Actually the issue is when we give name in the name input field , it should read key. Since we already have issue in reading key in local host , webAuthnResponse is null. And actual workflow is if webAuthnResponse is null Save button should be disabled. It should not be enabled and user is unable to click. But here even if the webAuthnResponse is null save is getting enabled. Yes please help me in debugging.

@rr-bw Please advise on the above

2024-05-23 08:45 UTC, rr-bw requested changes
It won't let me comment on the specific line, but line 39 of the html file needs updated to `tw-text-muted`.

2024-05-23 08:45 UTC, rr-bw commented on apps/web/src/app/auth/settings/two-factor-setup.component.ts
> +        webAuthnComp.componentInstance.onChangeStatus.subscribe((enabled: any) => {
Should this be `enabled: boolean`?

2024-05-23 08:45 UTC, rr-bw commented on apps/web/src/app/auth/settings/two-factor-setup.component.ts
> +          this.updateStatus(enabled, TwoFactorProviderType.Authenticator);
`TwoFactorProviderType.WebAuthn`, not Authenticator.

2024-05-23 08:45 UTC, rr-bw commented on apps/web/src/app/auth/settings/two-factor-webauthn.component.ts
>    name: string;
Do will still need `name`? Where do we access this property?

2024-05-23 08:45 UTC, rr-bw commented on apps/web/src/app/auth/settings/two-factor-webauthn.component.ts
> +    private dialogRef: DialogRef,
Is `private dialogRef: DialogRef` injection needed? I don't see where we are reading it.

2024-05-23 08:45 UTC, rr-bw commented on apps/web/src/app/auth/settings/two-factor-webauthn.component.html
> +      <img class="tw-float-right tw-ml-5 mfaType7" alt="FIDO2 WebAuthn logo'" />
Could you remove the trailing single quote `'` in the string?

2024-05-23 08:45 UTC, rr-bw commented on apps/web/src/app/auth/settings/two-factor-webauthn.component.html
> +          </p>
Go with `<span>`s here instead of paragraphs. Our paragraphs add some extra margin on the bottom which spreads them out. The original spacing looks like this:

![Screenshot 2024-05-23 at 1 32 02 AM](https://github.com/bitwarden/clients/assets/102181210/91c9a3a5-0802-4ec4-9c7a-0f8ba1e0b966)

2024-05-23 08:45 UTC, rr-bw commented on apps/web/src/app/auth/settings/two-factor-webauthn.component.html
> +      <div class="tw-flex tw-flex-row">
I think `tw-flex-row` is unnecessary because it is the default.

2024-05-23 08:45 UTC, rr-bw commented on apps/web/src/app/auth/settings/two-factor-webauthn.component.html
> +        bitFornButton
Typo: `bitFormButton`

2024-05-23 08:45 UTC, rr-bw commented on apps/web/src/app/auth/settings/two-factor-webauthn.component.html
> +        #disableBtn
I don't think we are using this `#disableBtn` templateRef anymore.

2024-05-23 09:03 UTC, rr-bw commented
> > When I click "Save" I get the following error, are you able to track this down? Everything works fine on `main`. Let me know if you need help debugging.
> > ![Screenshot 2024-05-17 at 11 42 33 AM](https://private-user-images.githubusercontent.com/102181210/331700583-7974960a-b569-4f72-a370-4ad395116c62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNDUwOTgsIm5iZiI6MTcxNjI0NDc5OCwicGF0aCI6Ii8xMDIxODEyMTAvMzMxNzAwNTgzLTc5NzQ5NjBhLWI1NjktNGY3Mi1hMzcwLTRhZDM5NTExNmM2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQyMjM5NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZmZmYjc4YzM3ZjgzMWY5YjdjYTdkMDY2MTc2NmYxNTEyOWM3OTVmOGE1YjJmZDJiZTkwNTY0ZDY4MmVlY2E4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IoV8iwB5RyIx5uSqBlpt8S6Hxp7xURZAq6Tkkzg0x60)
> 
> @rr-bw Actually the issue is when we give name in the name input field , it should read key. Since we already have issue in reading key in local host , webAuthnResponse is null. And actual workflow is if webAuthnResponse is null Save button should be disabled. It should not be enabled and user is unable to click. But here even if the webAuthnResponse is null save is getting enabled. Yes please help me in debugging.

@jlf0dev or @JaredSnider-Bitwarden Would either of you have capacity to help in debugging this? I can't seem to track down the issue. The "save" button is somehow getting enabled when you simply start typing in the name field. It's supposed to remain disabled [as long as `webAuthnResponse` is null](https://github.com/bitwarden/clients/pull/9009/files#diff-ba20b4cbe8dfdd63aff476dc09c485d94773c08dc4610b86a9072993d6de97bfR98). It's almost like form status changes are overriding our `[disabled]="!webAuthnResponse"` on the "save" button. One odd thing I noticed is that if I remove `bitFormButton` from the "save" button, it will in fact remain disabled until you Read Key. (But we still then have the problem where clicking "save" gives an error).

2024-05-23 12:26 UTC, KiruthigaManivannan commented on apps/web/src/app/auth/settings/two-factor-webauthn.component.ts
>    name: string;
@rr-bw  Yes this is used in setup component , to immediately send enabled status to set up component , the enabled tick mark should appear before we close the dialog . so we are using this event emitter.

2024-06-05 17:04 UTC, rr-bw commented
@KiruthigaManivannan Reading the key should now work, and the "save" button will also remain disabled until the appropriate time. Could you now fix the remaining issues when clicking "deactivate all keys". The dialog should close and the green check mark next to "FIDO WebAuthn" should get removed. See `main` for the correct flow.

2024-06-10 09:37 UTC, KiruthigaManivannan commented
> > @KiruthigaManivannan Reading the key should now work, and the "save" button will also remain disabled until the appropriate time. Could you now fix the remaining issues when clicking "deactivate all keys". The dialog should close, a toast should appear, and the green check mark next to "FIDO2 WebAuthn" should get removed. Here is a video of the correct deactivate flow on `main`:
> > deactivate.mov
> 
> @willmartian As you said , save button is working as expected now. But clicking on read key button does not do anything.
> 
> ![image](https://private-user-images.githubusercontent.com/162679756/337328283-97cea05e-4f3e-474e-b1e0-5c0cbe79ed56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMTI1MjYsIm5iZiI6MTcxODAxMjIyNiwicGF0aCI6Ii8xNjI2Nzk3NTYvMzM3MzI4MjgzLTk3Y2VhMDVlLTRmM2UtNDc0ZS1iMWUwLTVjMGNiZTc5ZWQ1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQwOTM3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ODExYjM0OTQxZDA0Zjg2MWVjMDEzNWU0NDE1NWNiNTUwNDRiYmZkZGVhOGFlZDc0NzQxMWQ4ODMxZmU0MjJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6jgOkFHw16cRglxRbB0r3vQGgsGxNxVQ35D1Pz8UEs4)
> 
> This occurs not only in this branch , but also in main while running in localhost

@willmartian Any advise on this? Please help on this.

2024-06-11 15:55 UTC, willmartian reviewed
> clicking on read key button does not do anything.

I am unable to repro this on my side. This also seems more likely to be related to auth code vs CL code--any ideas @rr-bw ?

2024-06-11 15:55 UTC, willmartian commented on apps/web/src/app/auth/settings/two-factor-setup.component.ts
> +        webAuthnComp.componentInstance.onChangeStatus.subscribe((enabled: boolean) => {
This seems off. There is not another instance in the codebase where we use `.componentInstance`. 

If we want to communicate from dialog --> calling component, the more canonical way of doing that is by a `DialogRef.close(someValue)` or `[bitDialogClose]="someValue"` from within the component. That would also solve the issue of the dialog not closing correctly when all keys are removed.

2024-06-11 16:58 UTC, rr-bw commented
> clicking on read key button does not do anything.

I am also unable to reproduce. It's working fine on both `main` and on this branch.

**Main**

https://github.com/bitwarden/clients/assets/102181210/9e82706a-25ad-4c34-99e2-40524358a8da

**This Branch**

https://github.com/bitwarden/clients/assets/102181210/7c42f64f-fd8e-40f7-bc2e-13f3c17e778b

2024-06-11 16:59 UTC, rr-bw commented on apps/web/src/app/auth/settings/two-factor-webauthn.component.html
> +        bitButton
Add `tw-mr-2` to this button for more spacing between the help text when it shows.

2024-06-11 17:54 UTC, rr-bw commented
@KiruthigaManivannan I spoke with Todd about this. After you address Will's comment we're thinking we can merge to `main` and have QA flush out any issues with read key. For now it seems there must be something unique about your environment.

2024-06-13 18:30 UTC, rr-bw submitted a review, later dismissed

2024-06-20 19:25 UTC, rr-bw approved these changes

2024-06-25 15:03 UTC, merged