PM- 2060 Update Two Factor Yubikey dialog
bitwarden/clients pull request #9010
Opened 2024-05-02 09:33 UTC by KiruthigaManivannan

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other
```

## Objective

Update Two Factor Yubikey dialog component to use the component library.

## Code changes

- **two-factor-yubikey.component.html:** Converted modal to dialog compoenents
- **two-factor-yubikey.component.ts:** Added dialog open method. Data passed to dialog is typed.
- **two-factor-setup.component.ts:** Added Yubikey dialog logic and passing the result of two factor verify dialog in the switch statement of mange method call.

## Screenshots

https://github.com/bitwarden/clients/assets/162679756/f9af930e-b221-46f4-8679-78f453e87e58

2024-05-22 18:53 UTC, ike-kottlowski requested changes

2024-05-23 16:27 UTC, ike-kottlowski requested changes
There is an issue when viewing existing YubiKeys.

![image](https://github.com/bitwarden/clients/assets/137194738/de8f94ea-a719-4cdb-99e9-a42d319dda02)

2024-05-24 09:08 UTC, KiruthigaManivannan commented
> There is an issue when viewing existing YubiKeys.
> 
> ![image](https://private-user-images.githubusercontent.com/137194738/333267936-de8f94ea-a719-4cdb-99e9-a42d319dda02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MjY5ODUsIm5iZiI6MTcxNjUyNjY4NSwicGF0aCI6Ii8xMzcxOTQ3MzgvMzMzMjY3OTM2LWRlOGY5NGVhLWE3MTktNGNkYi05OWU5LWE0MmQzMTlkZGEwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQwNDU4MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjdmMmQ1NjhlZTZkYzVjN2MwMTJlOWIwNzI5OGMyZjA3ZDc1MjVhNWI0MGZmNGFmMmMxMWRkYmI1NjAxNWI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NaNCn5djDCEJcrxpTj5PZyxktP896AWS6XmQm4hR0x0)

@ike-kottlowski  I tried fixing this. But I get the UI look like below only
![image](https://github.com/bitwarden/clients/assets/162679756/cd7cfc46-4668-4680-9afe-8906108c1c01)

Here when i click remove button , the value of keys get updated in formGroup , but input field is not appearing. I tried debugging but i couldnt fix. Any advise on this.

2024-05-24 15:36 UTC, willmartian commented
> I tried debugging but i couldnt fix. Any advise on this.

Hey @KiruthigaManivannan, could you post a recording that more clearly shows what the error is? (I am having a hard time following.) Are you getting any unexpected errors in the console?

2024-05-28 00:28 UTC, KiruthigaManivannan commented
> > I tried debugging but i couldnt fix. Any advise on this.
> 
> Hey @KiruthigaManivannan, could you post a recording that more clearly shows what the error is? (I am having a hard time following.) Are you getting any unexpected errors in the console?



@willmartian  Please find the video below.

https://github.com/bitwarden/clients/assets/162679756/60e8d072-f1d0-493a-ae89-8d0539b9ce3a

In the above video , if i click remove button for existing key and click save. You can notice the validation errors saying A key is required , it means if i click remove button, key value becomes null but the input field dont appear. 2nd case if i dont click remove button , the value is not made null and if now i click save button it shows key is invalid. which means key is present and it is invalid. this is fine actually if i give right key it would have submitted. So on clicking remove button , input field should appear correspondingly . thats the issue

2024-06-10 09:38 UTC, KiruthigaManivannan commented
> > > I tried debugging but i couldnt fix. Any advise on this.
> > 
> > 
> > Hey @KiruthigaManivannan, could you post a recording that more clearly shows what the error is? (I am having a hard time following.) Are you getting any unexpected errors in the console?
> 
> @willmartian Please find the video below.
> 
>  Yubikey_.Bitwarden.Web.vault.-.Google.Chrome.2024-05-28.05-51-32.mp4 
> In the above video , if i click remove button for existing key and click save. You can notice the validation errors saying A key is required , it means if i click remove button, key value becomes null but the input field dont appear. 2nd case if i dont click remove button , the value is not made null and if now i click save button it shows key is invalid. which means key is present and it is invalid. this is fine actually if i give right key it would have submitted. So on clicking remove button , input field should appear correspondingly . thats the issue

@willmartian  I have attached the video. Please advise me on the above issue

2024-06-11 22:41 UTC, willmartian requested changes

2024-06-11 22:41 UTC, willmartian commented on apps/web/src/app/auth/settings/two-factor-yubikey.component.ts
> +    });
I'm not sure this helper function adds much value.

2024-06-11 22:41 UTC, willmartian commented on apps/web/src/app/auth/settings/two-factor-yubikey.component.ts
> +  private submitForm(request: UpdateTwoFactorYubioOtpRequest) {
It is confusing to have both a `submit` and `submitForm` method. Could we combine them?

2024-06-11 22:41 UTC, willmartian commented on apps/web/src/app/auth/settings/two-factor-yubikey.component.ts
>        const response = await this.formPromise;
Error toasts are not being displayed to the user because errors within `super.enable` are swallowed by a try/catch. Is this the existing behavior?

2024-06-11 22:41 UTC, willmartian commented on apps/web/src/app/auth/settings/two-factor-yubikey.component.html
> +        #disableBtn
I don't believe `#disableBtn` is needed anymore

2024-06-11 22:41 UTC, willmartian commented on apps/web/src/app/auth/settings/two-factor-yubikey.component.html
> +          <div formGroupName="{{ i }}">
Don't use interpolation for HTML attributes: `[formGroupName]="i"`

2024-06-11 22:41 UTC, willmartian commented on apps/web/src/app/auth/settings/two-factor-setup.component.ts
> +        yubiComp.componentInstance.onChangeStatus.subscribe((enabled: boolean) => {
See my comment [here](https://github.com/bitwarden/clients/pull/9009#discussion_r1635097263)

2024-06-11 22:41 UTC, willmartian commented on apps/web/src/app/auth/settings/two-factor-yubikey.component.ts
> +  formGroup: FormGroup<{ keys: FormArray<FormControl<any>>; nfc: FormControl<any> }>;
Is there a strong reason to use `any` here?

2024-06-11 22:41 UTC, willmartian commented on apps/web/src/app/auth/settings/two-factor-yubikey.component.ts
> +    this.auth(data);
Is the intention to run this when the dialog opens? If so, it should happen in `ngOnInit`

2024-06-11 23:09 UTC, willmartian commented
> > > > I tried debugging but i couldnt fix. Any advise on this.
> > > 
> > > 
> > > Hey @KiruthigaManivannan, could you post a recording that more clearly shows what the error is? (I am having a hard time following.) Are you getting any unexpected errors in the console?
> > 
> > 
> > @willmartian Please find the video below.
> > Yubikey_.Bitwarden.Web.vault.-.Google.Chrome.2024-05-28.05-51-32.mp4
> > In the above video , if i click remove button for existing key and click save. You can notice the validation errors saying A key is required , it means if i click remove button, key value becomes null but the input field dont appear. 2nd case if i dont click remove button , the value is not made null and if now i click save button it shows key is invalid. which means key is present and it is invalid. this is fine actually if i give right key it would have submitted. So on clicking remove button , input field should appear correspondingly . thats the issue
> 
> @willmartian I have attached the video. Please advise me on the above issue

I am looking into this and will get back to you.

2024-06-12 11:37 UTC, KiruthigaManivannan commented on apps/web/src/app/auth/settings/two-factor-yubikey.component.ts
> +  private submitForm(request: UpdateTwoFactorYubioOtpRequest) {
@willmartian If I try to call any super method inside arrow function (async) , i get this below message
![image](https://github.com/bitwarden/clients/assets/162679756/12140081-aa3d-4146-a290-f7b9c1a8c7af)

Thats why Itried like this.

2024-06-12 12:02 UTC, KiruthigaManivannan commented on apps/web/src/app/auth/settings/two-factor-yubikey.component.ts
>        const response = await this.formPromise;
@willmartian  Yes it is swallowed by try catch , so we need to make change in base enable. can we throw error in super enable.
![image](https://github.com/bitwarden/clients/assets/162679756/c5644967-fe82-442b-8aef-140640be2c72)

This above change can be done in base component. I have changed this as of now.

2024-06-12 18:41 UTC, willmartian commented on apps/web/src/app/auth/settings/two-factor-yubikey.component.ts
> +  private submitForm(request: UpdateTwoFactorYubioOtpRequest) {
Ah, gotcha. Thanks for the clarification.

2024-06-12 18:43 UTC, willmartian commented on apps/web/src/app/auth/settings/two-factor-yubikey.component.ts
>        const response = await this.formPromise;
cc @bitwarden/team-auth-dev is this fine?

2024-06-12 21:12 UTC, willmartian commented on apps/web/src/app/auth/settings/two-factor-yubikey.component.ts
> +  formGroup: FormGroup<{ keys: FormArray<FormControl<any>>; nfc: FormControl<any> }>;
```ts
I think we want to use `Key` rather than `Key[]`:

protected formGroup: FormGroup<{ 
    keys: FormArray<FormControl<Key>>; 
    nfc: FormControl<boolean> 
}>;
```

```ts
this.formGroup = this.formBuilder.group({
      keys: this.formBuilder.array<Key>([]),
      nfc: this.formBuilder.control(this.nfc),
});
```

2024-06-12 21:17 UTC, willmartian commented on apps/web/src/app/auth/settings/two-factor-setup.component.ts
> +        yubiComp.componentInstance.onChangeStatus.subscribe((enabled: boolean) => {
I am suggesting we remove all references to the output and instead pass the value back via `this.dialogRef.close(this.enabled)` or similar.

2024-06-12 21:36 UTC, willmartian commented
> So on clicking remove button , input field should appear correspondingly . thats the issue

@KiruthigaManivannan The current `remove` function is updating the value object within a control, but not updating the control itself, which is bound to the template. We can fix this by updating `remove` to something like:
```ts
remove(control: FormControl<Key>) {
    control.setValue({
      existingKey: null,
      key: null,
    })
  }
```

And by passing in the full control in the template:

```
(click)="remove(k)"
```

Gonna tag team this back to @bitwarden/team-auth-dev for further reviews. (Thanks!)

2024-06-17 07:33 UTC, KiruthigaManivannan commented on apps/web/src/app/auth/settings/two-factor-yubikey.component.ts
>        const response = await this.formPromise;
@bitwarden/team-auth-dev any updates on this

2024-06-19 15:32 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/settings/two-factor-yubikey.component.ts
>        const response = await this.formPromise;
@KiruthigaManivannan, ensuring the user can see errors is good with me!

2024-06-20 07:51 UTC, KiruthigaManivannan commented
https://github.com/bitwarden/clients/pull/9010#discussion_r1635547833 this issue is fixed now by adding throw e in base component's enable and disable methods. Once this PR gets merged along with other 2FA components , toast error appears for all 2FA types

2024-06-26 13:57 UTC, KiruthigaManivannan commented
@ike-kottlowski  Can you please check and approve , so that i can merge the PR

2024-06-26 14:25 UTC, ike-kottlowski commented
> @ike-kottlowski Can you please check and approve , so that i can merge the PR

@KiruthigaManivannan, I am working on a fix currently for viewing existing YubiKeys I will have a commit today. I will approve once I am finished with the changes I am making.

2024-06-28 14:38 UTC, KiruthigaManivannan commented
> > @ike-kottlowski Can you please check and approve , so that i can merge the PR
> 
> @KiruthigaManivannan, I am working on a fix currently for viewing existing YubiKeys I will have a commit today. I will approve once I am finished with the changes I am making.

@ike-kottlowski  can you please check and approve this.

2024-07-01 22:22 UTC, ike-kottlowski commented
Made updates to the component. 

https://github.com/bitwarden/clients/assets/137194738/1b2a6f73-d6e6-4022-ae71-59c1ff4e46f6

2024-07-02 13:43 UTC, jlf0dev requested changes

2024-07-02 14:58 UTC, JaredSnider-Bitwarden requested changes

2024-07-02 14:58 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/settings/two-factor-setup.component.ts
>            this.updateStatus(enabled, TwoFactorProviderType.Yubikey);
We really should update the `TwoFactorYubiKeyComponent` to use the cdk close API so we can just use `await firstValueFrom(dialogRef.closed)`.

2024-07-09 21:29 UTC, ike-kottlowski commented on apps/web/src/app/auth/settings/two-factor-setup.component.ts
>            this.updateStatus(enabled, TwoFactorProviderType.Yubikey);
We spoke about how this is a bigger lift and outside the scope of this task. Using the `dialogRef.closed` observable doesn't account for all paths that can be taken to close the dialog.

2024-07-09 21:30 UTC, ike-kottlowski commented on apps/web/src/app/auth/settings/two-factor-yubikey.component.ts
>      return super.enable(async () => {
Removed the reference to `super.enable`.

2024-07-10 14:49 UTC, JaredSnider-Bitwarden approved these changes
Nice work getting this across the finish line!

2024-07-10 14:54 UTC, jlf0dev approved these changes

2024-07-10 15:34 UTC, ike-kottlowski approved these changes

2024-07-10 17:56 UTC, merged