testing icon sizes
bitwarden/clients pull request #9021
Opened 2024-05-02 16:51 UTC by vleague2

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-05-22 19:15 UTC, danielleflinn submitted a review, later dismissed
For an initial commit this looks good. 

In Figma I have the chip text-size as` body2`. We might want to update that now since it doesn't rely on any new styles. But I'll leave that up to you @willmartian if you'd prefer to tackle it in the follow up one. 

We should address the following in a followup PR:

- chip focus state
- chip styles for hover, pressed, and focused states
- keyboard navigation and SR announcements
- style updates that will happen as part of updates to the` bit-menu`

2024-05-22 20:10 UTC, willmartian commented
Thanks @danielleflinn! I went ahead and added a focus ring and updated the font size to use `body2`. Will finalize the other items in a separate ticket.

2024-05-22 21:47 UTC, danielleflinn commented
@willmartian I just noticed in the menu the list focus is only on the top of the item, but in the `bit-menu` story we have it on both the top and bottom. Is this expected? Will it be addressed in the follow up PR? 
<img width="240" alt="Screenshot 2024-05-22 at 2 44 25 PM" src="https://github.com/bitwarden/clients/assets/43477473/f9ccf91d-740c-40b6-85f3-db68e2678f48">

2024-05-23 13:48 UTC, vleague2 reviewed
Ty for such beautiful work ✨ Here are a couple of questions!

2024-05-23 13:48 UTC, vleague2 commented on libs/components/src/chip-select/chip-select.component.html
> +        [title]="
Do we need the title, since the button already has visible/accessible text?

2024-05-23 13:48 UTC, vleague2 commented on libs/components/src/chip-select/chip-select.component.ts
> +      children: this.options,
Should we be making a copy of the passed-in `options` so that we aren't modifying it directly? (Or is that part of the Angular magic)

2024-05-23 13:48 UTC, vleague2 commented on libs/components/src/chip-select/chip-select.component.html
> +      {{ option.label }}
In Storybook, the text size of the options looks bigger than the chip label -- is that intentional?

2024-05-23 13:48 UTC, vleague2 commented on libs/components/src/chip-select/chip-select.component.html
> +    class="tw-bg-transparent hover:tw-bg-transparent tw-outline-none tw-rounded-full tw-p-1 tw-my-1 tw-mr-1 tw-text-[inherit] tw-border-solid tw-border tw-border-text-muted hover:tw-border-text-contr
The focus ring is kind of oblong?

<img width="548" alt="Screenshot 2024-05-23 at 9 42 11 AM" src="https://github.com/bitwarden/clients/assets/32983157/2d43cc98-3e5c-442e-8e3c-98516495d81e">

2024-05-23 13:48 UTC, vleague2 commented on libs/components/src/select/option.component.ts
> +  @Input({ transform: booleanAttribute })
TIL about this transform 🌈

2024-05-23 16:18 UTC, willmartian commented on libs/components/src/chip-select/chip-select.component.html
> +        [title]="
I did this in case there is text overflow + truncation. That way users can still hover for a tooltip to see the full text.

2024-05-23 16:29 UTC, willmartian commented on libs/components/src/chip-select/chip-select.component.html
> +      {{ option.label }}
Nope, per Figma: `This menu’s list items should be set to the same font size as the chip’s label.` 

Fixed in [2977cd5](https://github.com/bitwarden/clients/pull/9021/commits/2977cd5d65948c104015bc19ed09d9e2d60d0556)

2024-05-23 16:29 UTC, willmartian commented on libs/components/src/select/option.component.ts
> +  @Input({ transform: booleanAttribute })
Yup, it is new and great!

2024-05-23 16:38 UTC, willmartian commented on libs/components/src/chip-select/chip-select.component.ts
> +      children: this.options,
Since the folders object could potentially be pretty big, a deep clone is kinda inefficient. The only property we are overriding is a property that we explicitly mark as `@internal`, so I think it is fine.

I do think that we need to update this to be reactive. As written, if `options` changes we would not update the root tree or mark the parents again. Commit on the way.

2024-05-23 16:41 UTC, willmartian commented on libs/components/src/chip-select/chip-select.component.html
> +    class="tw-bg-transparent hover:tw-bg-transparent tw-outline-none tw-rounded-full tw-p-1 tw-my-1 tw-mr-1 tw-text-[inherit] tw-border-solid tw-border tw-border-text-muted hover:tw-border-text-contr
Huh, I am not seeing that in FF, but I am on Chrome. Will solve that in the follow up PR for CL-291.

2024-05-23 17:13 UTC, vleague2 commented on libs/components/src/chip-select/chip-select.component.html
> +    class="tw-bg-transparent hover:tw-bg-transparent tw-outline-none tw-rounded-full tw-p-1 tw-my-1 tw-mr-1 tw-text-[inherit] tw-border-solid tw-border tw-border-text-muted hover:tw-border-text-contr
That screenshot is from Chrome 😭

2024-05-23 17:14 UTC, willmartian commented on libs/components/src/chip-select/chip-select.component.ts
> +      children: this.options,
^ fixed in [14edafb](https://github.com/bitwarden/clients/pull/9021/commits/14edafbd13bd31964ab0e38a82a30bf2c0a886b8)

2024-05-23 17:33 UTC, willmartian commented
> I just noticed in the menu the list focus is only on the top of the item, but in the `bit-menu` story we have it on both the top and bottom. Is this expected? Will it be addressed in the follow up PR?

@danielleflinn I believe this is a style bug with the menu component itself. I would like to care of that when we update menu styles in [CL-237](https://bitwarden.atlassian.net/browse/CL-237) if that is cool? The focus rings in the menu component are also not up to spec on main.

2024-05-23 19:42 UTC, willmartian commented on libs/components/src/chip-select/chip-select.component.ts
> +      children: this.options,
(As you pointed out offline) We were actually getting an error in Storybook (and crashing) from cyclic references in the tree.

![image](https://github.com/bitwarden/clients/assets/17113462/d1606a7b-90e2-4799-97af-cfd894431e8f)

Storybook serializes options that are passed to it, and cyclic objects aren't serializable. Options to fix:
- disable whatever Storybook feature was serializing the data and continue on like nothing is wrong.
  - but what if devs need to serialize the tree, perhaps to store it in state? Since we are modifying _their_ object, this could lead to unexpected errors in the future.
- make a deep copy of the options passed to us (as you note in this thread) and manipulate it instead. However, that would require that the passed options tree _must be_ serializable, which seems like a lame limitation to impose just to make Storybook not error. 
- refactor the tree structure to not be cyclic

The last option made the most sense to me; fixed in [05beb78](https://github.com/bitwarden/clients/pull/9021/commits/05beb78c1d560062397b5d72d222f2d35b6d06c6)

2024-05-23 19:47 UTC, vleague2 commented on libs/components/src/chip-select/chip-select.component.html
> -        *ngIf="renderedOptions._parent"
This removal is because the folder can have items in it at the top level?

2024-05-23 19:49 UTC, willmartian commented on libs/components/src/chip-select/chip-select.component.html
> -        *ngIf="renderedOptions._parent"
It was redundant, a parent `ng-container` is already doing the same check.

2024-05-23 19:52 UTC, vleague2 reviewed
✅  This is me symbolically approving the PR because I can't actually approve it since I own it

2024-05-23 19:53 UTC, willmartian approved these changes
Wow, amazing work

2024-05-23 19:56 UTC, willmartian requested changes
Oh actually, it looks like the menu changes here introduces a regression in the product switcher. Gonna fix this real quick.

![image](https://github.com/bitwarden/clients/assets/17113462/4aab3ae9-d784-4607-aa96-64fc4b7c7353)

2024-05-23 20:28 UTC, vleague2 reviewed
✅ Width changes look good

2024-05-23 20:30 UTC, willmartian approved these changes

2024-05-23 20:30 UTC, merged