[AC-2086] Update CanDelete with v1 flag logic
bitwarden/clients pull request #9100
Opened 2024-05-09 15:50 UTC by vincentsalucci

## Type of change

- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

> Apply v1 flag logic to the `CanDelete` functionality

## Code changes

### Views
- **collection-admin.view.ts** Removed override. With `FC` being applied to all organizations, the logic between a user/admin to delete a collection has aligned.
- **collection.view.ts** Consolidated `canDelete` logic.

### Domain
- **libs/common/src/admin-console/models/domain/organization.ts**: Updated the `canDeleteAnyCollection` to accept the v1 flag status as a parameter. Updated the `canViewAllCollections` method to only check for the custom permission as the final part of the conditional.

### References
- Updated all references to use already available v1 flag data.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-05-09 15:54 UTC, vincentsalucci commented on libs/common/src/admin-console/models/domain/organization.ts
> +      this.isAdmin || this.permissions.editAnyCollection || this.permissions.deleteAnyCollection
@shane-melton @eliykat : Instead of calling the `canDeleteAnyCollection` method for the final check in the conditional, I've replaced it with a sole check on the custom permission. This maintains existing functionality (there is already an `isAdmin` check at the forefront of the `ORs`. Is this sufficient?

2024-05-09 15:55 UTC, vincentsalucci commented on apps/web/src/app/vault/core/views/collection-admin.view.ts
> -  override canDelete(org: Organization): boolean {
@shane-melton @eliykat : I've removed this override as the logic is now identical after removing the `org.FlexibleCollections` check (a nudge to your future clean-up effort). I don't believe this causes any issues, but wanted to double check!

2024-05-09 15:57 UTC, vincentsalucci commented on apps/web/src/app/vault/individual-vault/bulk-action-dialogs/bulk-delete-dialog/bulk-delete-dialog.component.ts
> +    const flexibleCollectionsV1Enabled = await firstValueFrom(this.flexibleCollectionsV1Enabled$);
@shane-melton : This follows a similar pattern found within this component. Are we okay with this approach?

2024-05-09 15:59 UTC, shane-melton commented on libs/common/src/admin-console/models/domain/organization.ts
> +    }
question: Shouldn't we still return some value here in case both of these branches fail?

2024-05-09 15:59 UTC, shane-melton commented on libs/common/src/admin-console/models/domain/organization.ts
> +    if (!flexibleCollectionsV1Enabled || this.allowAdminAccessToAllCollectionItems) {
issue: I don't think this properly accounts for Providers? They will likely need their own branch because they're not affected by the `allowAdminAccessToAllCollectionItems` setting.

2024-05-10 05:36 UTC, eliykat requested changes
LGTM, I agree with both of @shane-melton's requested changes, but nothing else to add.

2024-05-10 05:36 UTC, eliykat commented on libs/common/src/admin-console/models/domain/organization.ts
> +      this.isAdmin || this.permissions.editAnyCollection || this.permissions.deleteAnyCollection
I agree with you, I think this is sufficient and is probably what the logic is targeting anyway (i.e. custom users with the delete permission).

2024-05-10 05:36 UTC, eliykat commented on apps/web/src/app/vault/core/views/collection-admin.view.ts
> -  override canDelete(org: Organization): boolean {
Agree, it was only the pre-FC logic that diverged and required the override.

(I will reintroduce this in a later PR but you don't need to worry about that here, it's fine to delete.)

2024-05-10 18:03 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/bulk-action-dialogs/bulk-delete-dialog/bulk-delete-dialog.component.ts
> +    const flexibleCollectionsV1Enabled = await firstValueFrom(this.flexibleCollectionsV1Enabled$);
Yep, this works!

2024-05-10 18:04 UTC, shane-melton approved these changes
Looks good to go!

2024-05-12 22:50 UTC, eliykat approved these changes

2024-05-13 15:05 UTC, gbubemismith approved these changes

2024-05-13 16:27 UTC, willmartian requested changes

2024-05-13 16:27 UTC, willmartian commented on apps/web/src/app/vault/components/vault-items/vault-items.component.ts
> +    return collection.canDelete(organization, this.flexibleCollectionsV1Enabled);
This change is causing a visual regression in Storybook. We likely need to update this mock: https://github.com/bitwarden/clients/blob/3ddf05306e23bb1e9980825c7adf1632d776d572/apps/web/src/app/vault/components/vault-items/vault-items.stories.ts#L96-L99

2024-05-13 16:37 UTC, willmartian commented on apps/web/src/app/vault/components/vault-items/vault-items.component.ts
> +    return collection.canDelete(organization, this.flexibleCollectionsV1Enabled);
The error might actually be because of a different change (don't let my above suggestion be a red herring). I see this error when viewing the vault items story: 

```
ERROR TypeError: can't access property "deleteAnyCollection", this.permissions is undefined
    canDeleteAnyCollection
```

https://62a88a6de5b807fa98886113-hpjxqmclgx.chromatic.com/?path=/story/web-vault-items--organization-top-level-collection

2024-05-13 17:07 UTC, willmartian commented on apps/web/src/app/vault/components/vault-items/vault-items.component.ts
> +    return collection.canDelete(organization, this.flexibleCollectionsV1Enabled);
Okay, that error looks like it is happening because when we [construct the mock orgs](https://github.com/bitwarden/clients/blob/3ddf05306e23bb1e9980825c7adf1632d776d572/apps/web/src/app/vault/components/vault-items/vault-items.stories.ts#L316-L321) for the story, we are not passing giving `Organization.permissions` a value. The simple fix is to add that to the mock, but this seems indicative of a larger type error going on here, because the compiler *should* be yelling at us:

Why is `permissions` not required when constructing an Organization?

---

This is another example of why we need to enable `strictNullChecks`, cc @justindbaur

2024-05-13 18:26 UTC, shane-melton approved these changes

2024-05-13 21:04 UTC, eliykat approved these changes

2024-05-13 21:13 UTC, merged