[AC-2570] Existing providers see new CB experience on Admin Console org Billing Subscription page
bitwarden/clients pull request #9108
Opened 2024-05-09 20:54 UTC by cyprain-okeke

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Existing (pre consolidated billing/created flag off) Provider admins and service users see the new CB page when navigating to the Admin Console client org billing page implemented in [AC-2265](https://bitwarden.atlassian.net/jira/software/c/projects/BW/boards/101?selectedIssue=AC-2265) 

Previously, provider admins and service users saw the Manage Billing Subscription page for client organizations. Now, they will be unable to manage the subscription.

 

Steps to reproduce:

Log in with a provider admin or service user for a Provider Org created with enable-consolidated-billing = false

Navigate to the Provider Portal

Select a client org from the list

Go to the Billing > Subscription page

Expected Result - provider admins and service users are able to view plan details and make updates to the client orgs subscription

Actual Result - Provider admins and service users are met with the new ‘Manage billing from the Provider Portal’ imagery

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-05-10 20:20 UTC, cturnbull-bitwarden commented on apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts
> +      const provider = await this.providerApiService.getProvider(this.userOrg.providerId);
This throws an error if the user isn't a provider user, which is the case for the client users. See https://github.com/bitwarden/clients/pull/9137

2024-05-13 14:49 UTC, amorask-bitwarden requested changes

2024-05-13 14:49 UTC, amorask-bitwarden commented on apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts
> +      const provider = await this.providerApiService.getProvider(this.userOrg.providerId);
Providers are loaded as part of the [`sync`](https://github.com/bitwarden/clients/blob/869fa29da6f586826437816d53164f160893447d/libs/common/src/vault/services/sync/sync.service.ts#L347) process and can be retrieved through the [`ProviderService`](https://github.com/bitwarden/clients/blob/0b02d2ee1c2a5ec33e3ec3c85f5298d6e4101d11/libs/common/src/admin-console/services/provider.service.ts#L41-L47) so I don't think this requires another API call. Additionally, that response model that's part of the sync process already includes the Provider Status from previous work.

2024-05-13 15:03 UTC, cyprain-okeke commented on apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts
> +      const provider = await this.providerApiService.getProvider(this.userOrg.providerId);
I remove the ProviderService sync call because this loaded base on the profiled information of the login user. The ProviderService call was removed and status property was aded to the providerApiService.getProvider response.

2024-05-13 15:09 UTC, amorask-bitwarden commented on apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts
> +      const provider = await this.providerApiService.getProvider(this.userOrg.providerId);
Sorry I might be missing something. Isn't the information gathered as part of the sync process specifically for the logged in user as well? I think the sync call [retrieves provider information](https://github.com/bitwarden/server/blob/974d23efdd00fc54de52954c34c43e42e2a51e8a/src/Api/Vault/Controllers/SyncController.cs#L76-L80) for the logged-in user and stores it in state. So my understanding is the information you could get from the User State would be the same as having to make another API call.

2024-05-13 15:38 UTC, amorask-bitwarden submitted a review, later dismissed

2024-05-13 16:15 UTC, vincentsalucci commented on apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts
> +      const provider = await this.providerApiService.getProvider(this.userOrg.providerId);
Was there resolution here? Nothing has changed, but the PR has been accepted.

2024-05-13 16:40 UTC, amorask-bitwarden commented on apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts
> +      const provider = await this.providerApiService.getProvider(this.userOrg.providerId);
@vincentsalucci We discussed it and I ultimately accepted using the API cuz there's one field left on the provider user response (Provider Type) from sync that we'd have to add to wire it up. If AC prefers this, we can do that though.

2024-05-13 16:53 UTC, amorask-bitwarden approved these changes

2024-05-13 19:10 UTC, vincentsalucci commented on apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts
> +      const provider = await this.providerApiService.getProvider(this.userOrg.providerId);
Given that this happens within the subscription view in the admin context, following the existing pattern of hitting an API instead of relying solely on sync data is fine, I believe.

2024-05-13 19:10 UTC, vincentsalucci approved these changes

2024-05-13 20:51 UTC, cturnbull-bitwarden approved these changes

2024-05-13 21:00 UTC, merged