Ps/pm-7926/next-up-is-locked
bitwarden/clients pull request #9115
Opened 2024-05-10 00:48 UTC by MGibson1

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

This eneded up being a bit of a hodge-podge of fixing issues around logging our and nextup user determination.

1. Browser now switches accounts first (including no account)
  - the switch account method redirects when necessary
2. Split app logout responsibilities to showing a toast and navigating home. Home is handled by switch and toast by logout. This is why we can always send `"doneLoggingOut"`
3. Chrome, Vivaldi, and Opera all reseed storage on logout. I'm doing the archaeology needed to determine why this is, but until then it was causing some serious problems with our `update$` stream. These reseed events were picked up as `remove` and `save` events that caused numerous race conditions on logout with components and services still using `firstValueFrom`. Ignoring events that don't match the signature of our storage services -- and therefore are special cases not due to the state provider framework -- resolves all the races I was seeing around logout.
4. Activity is set on account switch, which results in correctly determining the next up user even when the activity heartbeat has not yet thumped
5. Cipher Service has been updated to support user data clearing by userId. Individual updates still assume active user, but the interface used by logout / lock now supports passing in a userId so we can perform these actions appropriately on non-active users.

## Code changes

- **account-switcher.component**: Navigation now occurs in background + app component through messaging, it is inappropriate to trigger navigation manually here because we lack context on next up users.
- **main.background**:
  - await changes
  - popup-only (and therefore null in popup) service handling in lock/logout methods
  - early switch and improved switch navigation routing
  - support displaying expired toast on switch, not just logout to unauth
- **abstract-chrome-storage-api**: ignore updates that don't look like storage service-mediated storage changes.
- **app.component**: handle routing for no next up user
- **account service**: trigger activity update on switch
- **cipher service**: handle non active data clear

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-05-10 16:11 UTC, cagonzalezcs commented on apps/browser/src/platform/services/abstractions/abstract-chrome-storage-api.service.ts
> +        // reseeding storage and we should ignore the changes.
Hm, are these changes just swallowed and ignored entirely?

Is there any change that a set of legitimate changes could occur simultaneously? Would we miss updating local storage correctly in that case?

2024-05-10 16:11 UTC, cagonzalezcs commented on apps/browser/src/background/main.background.ts
> +        void this.notificationsService.updateConnection(false);
Your notes state that we should no longer be triggering lock/logout/account switch behavior within the popupOnly context... I'm not seeing anything here that might guard against that, is that the case or am I missing something?

2024-05-10 17:00 UTC, MGibson1 commented on apps/browser/src/platform/services/abstractions/abstract-chrome-storage-api.service.ts
> +        // reseeding storage and we should ignore the changes.
Any changes to storage that are done through our storage framework and not directly accessing the storage apis will not be swallowed by this.

I toyed around with creating a property that could be synced and indicate that the service should ignore updates while it is true, but that causes concurrency issues.

The only other idea I have is to write/remove a special value and any changeset involving that value would be ignored by this update stream. I kind of like that better now that I say it.

2024-05-10 17:03 UTC, MGibson1 commented on apps/browser/src/background/main.background.ts
> +        void this.notificationsService.updateConnection(false);
Do you mean in this file or _right_ here? This specific section is just getting rid of a `FIXME`.

I also didn't mean to imply that there is no direct call to lock or logout from a popup, just that if there is, unintialized services are through optional chaining operators.

2024-05-10 17:09 UTC, cagonzalezcs commented on apps/browser/src/background/main.background.ts
> +        void this.notificationsService.updateConnection(false);
I see, ok that makes sense.

2024-05-10 17:10 UTC, cagonzalezcs commented on apps/browser/src/platform/services/abstractions/abstract-chrome-storage-api.service.ts
> +        // reseeding storage and we should ignore the changes.
Maybe worth exploring in a future refactor.

2024-05-10 17:10 UTC, cagonzalezcs submitted a review, later dismissed

2024-05-10 17:31 UTC, Jingo88 submitted a review, later dismissed

2024-05-10 17:37 UTC, MGibson1 commented on apps/browser/src/platform/services/abstractions/abstract-chrome-storage-api.service.ts
> +        // reseeding storage and we should ignore the changes.
looks like that does work. I don't think I like it more, though. It means that we catch non-storage service compliant changes, but it also means that if there are any more weird updates like reseed, we need to identify them manually. So the question is: Do we think these kind of out-of-band updates should be generally honored or ignored? My instinct is ignored.

2024-05-10 18:32 UTC, jlf0dev approved these changes
We need tests _really_ badly for this process. I would be scared to touch any of this code.

2024-05-13 13:57 UTC, MGibson1 commented on apps/browser/src/background/main.background.ts
> +        void this.notificationsService.updateConnection(false);
reverted

2024-05-13 17:48 UTC, cagonzalezcs approved these changes

2024-05-13 20:50 UTC, justindbaur requested changes
One tiny thing.

2024-05-13 20:50 UTC, justindbaur commented on libs/angular/src/services/jslib-services.module.ts
> +      AuthService,
This needs to have the `Abstraction` suffix.

```suggestion
      AuthServiceAbstraction,
```

2024-05-13 21:04 UTC, Jingo88 submitted a review, later dismissed

2024-05-13 21:17 UTC, jlf0dev submitted a review, later dismissed

2024-05-14 12:09 UTC, MGibson1 commented on libs/angular/src/services/jslib-services.module.ts
> +      AuthService,
good catch, thank you

2024-05-14 17:55 UTC, justindbaur approved these changes

2024-05-14 18:01 UTC, jprusik approved these changes
Smoke tested and LGTM

2024-05-14 18:04 UTC, Jingo88 approved these changes

2024-05-14 18:14 UTC, jlf0dev approved these changes

2024-05-14 20:27 UTC, merged