include check-run in workflows where secrets are used
bitwarden/clients pull request #9135
Opened 2024-05-10 16:54 UTC by bwdil

## Type of change

GitHub workflows

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

As part of our organization-wide effort to secure bw code repos, a change to include `check-run` in workflows where `secrets` are used is required.

## Code changes

Incremental change to existing workflows

2024-05-10 17:45 UTC, withinfocus requested changes
This PR wouldn't be necessary as-is; when you look at all the other workflows in this repo it might be. I would like to see one PR for the entire repo, as is relevant.

2024-05-10 17:45 UTC, withinfocus commented on .github/workflows/build-cli.yml
> +  pull_request_target:
❌ You have to replace the above `pull_request_target` with this.

2024-05-10 17:45 UTC, withinfocus commented on .github/workflows/build-cli.yml
> +      - check-run
❌ This is expanding the work surface but touches on something Oscar was bringing up -- needing secrets, and when. You'll see below that the secret reference is only relevant when on non-PR builds, so this check isn't even necessary.

2024-05-10 18:13 UTC, bwdil commented on .github/workflows/build-cli.yml
> +      - check-run
ok, in that case we don't need `check-run` for this one.

2024-05-31 12:22 UTC, withinfocus requested changes

2024-05-31 12:22 UTC, withinfocus commented on .github/workflows/test.yml
> +    needs: check-run
🎨 Let's also assert some token permissions here.

```suggestion
    needs: check-run
    permissions:
      contents: read
      pull-requests: write
```

2024-06-07 21:20 UTC, bwdil commented on .github/workflows/test.yml
> +    needs: check-run
@withinfocus leaving a reference to [assigning-permissions-to-jobs](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs) 

`contents: read` permits an action to list the commits
`pull-requests: write` permits an action to add a label to a pull request

2024-06-10 14:29 UTC, withinfocus approved these changes

2024-06-10 15:53 UTC, vgrassia approved these changes

2024-06-10 15:54 UTC, merged