[PM-4961]anon-layout login component migrated
bitwarden/clients pull request #9167
Opened 2024-05-14 08:21 UTC by vinith-kovan

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [X] Other
```

## Objective

Migrate the login component to use the component library.

## Code changes

- login.component.html: Added form group and bit form fields
- login.component.ts: Added new form group , converted submit to arrow function
- oss-routing.module.ts: Added Routing for Anon layout wrapper component.

## Screenshots

https://github.com/bitwarden/clients/assets/156108204/d293d75b-3b0c-4c42-b590-395fdc672d14

2024-05-22 23:23 UTC, ike-kottlowski requested changes

2024-05-22 23:23 UTC, ike-kottlowski commented on apps/web/src/app/oss-routing.module.ts
> +          pageTitle: "loginOrCreateNewAccount",
Can this be changed to the `login` key from `messages.json`

2024-05-27 07:27 UTC, vinith-kovan commented on apps/web/src/app/auth/login/login.component.html
> +  <div class="tw-w-96">
Actually we don't need any of these bcz Anon-layout itself has all these class so I'm removing it.

2024-05-28 08:48 UTC, vinith-kovan commented on apps/web/src/app/auth/login/login.component.html
> +  <div class="tw-w-96">
![image](https://github.com/bitwarden/clients/assets/156108204/6fb254cc-18c3-464c-94db-f36a8f307b4c)

Hi @ike-kottlowski based on this [comment](https://github.com/bitwarden/clients/pull/9170#discussion_r1610769080), I have removed the tw-w-96 from the html as advised in the comment, but the UI look clumsy can you please take a look and guide me, Thank you!.

![image](https://github.com/bitwarden/clients/assets/156108204/16e68676-4d06-4c1d-8275-d23c32e49415)
tw-w-96 added one

2024-05-28 18:30 UTC, ike-kottlowski commented on apps/web/src/app/auth/login/login.component.html
> +  <div class="tw-w-96">
Just curious as to the reasoning I think using the `tw-w-96` to meet the visual requirement is acceptable. 

You can change it to `tw-w-96`

cc: @willmartian

2024-05-30 17:59 UTC, rr-bw commented on apps/web/src/app/auth/login/login.component.html
> +  <div class="tw-w-96">
@vinith-kovan My apologies, I should have been more clear in [this comment](https://github.com/bitwarden/clients/pull/9170#discussion_r1610769080) you referred to. The reason that component could remove the `tw-w-96` is because that component had enough internal content that it would automatically stretch to the full width of the anon layout (`tw-max-w-md`), making a width class unecessary. But this login component doesn't have enough internal content to make it stretch, so Ike's suggestion is correct to go with `tw-w-96` here. Thanks @ike-kottlowski .

2024-05-30 18:23 UTC, rr-bw commented
@vinith-kovan Thanks for your patience as we worked out some issues with AnonLayout. The latest updates are now in `main`, which allows you to add the Environment Selector to this login page. To do so:
1. Grab latest from `main`
2. Update the import in `oss-routing.module.ts` to:
```typescript
import { AnonLayoutWrapperComponent } from "@bitwarden/auth/angular";
```
3. Update the route to:
```typescript
  {
    path: "",
    component: AnonLayoutWrapperComponent,
    children: [
      {
        path: "login",
        canActivate: [unauthGuardFn()],
        children: [
          {
            path: "",
            component: LoginComponent,
          },
          {
            path: "",
            component: EnvironmentSelectorComponent,
            outlet: "environment-selector",
          },
        ],
        data: {
          pageTitle: "logIn",
        },
      },
    ],
  },
```

cc: @ike-kottlowski

2024-06-11 23:43 UTC, ike-kottlowski submitted a review, later dismissed

2024-06-12 00:47 UTC, ike-kottlowski approved these changes

2024-06-12 13:29 UTC, merged