PM-4951 Migrate Recover Two Factor Component
bitwarden/clients pull request #9170
Opened 2024-05-14 11:07 UTC by KiruthigaManivannan

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other
```

## Objective
Migrate the Recover Two Factor Component to use the component library.

## Code changes

- **recover-two-factor.component.html:** Added form group and bit form fields
- **recover-two-factor.component.ts:** Added new form group , converted submit to arrow function
- **oss-routing.module.ts:**  Added Routing for Anon layout wrapper component.

## Screenshots

https://github.com/bitwarden/clients/assets/162679756/0fd53ab2-c03f-49ed-8982-167faf20df80

2024-05-15 02:07 UTC, rr-bw requested changes
Thanks! Just a few minor requests.

2024-05-15 02:07 UTC, rr-bw commented on apps/web/src/app/oss-routing.module.ts
> +  },
Also bring over the `titleId` and the Unauth Guard as `canActivate: [unauthGuardFn()]`

2024-05-15 02:07 UTC, rr-bw commented on apps/web/src/app/auth/recover-two-factor.component.html
> +  <div class="tw-w-[400px]">
You can just go with `tw-w-96` here.

2024-05-15 02:07 UTC, rr-bw commented on apps/web/src/app/auth/recover-two-factor.component.ts
> -      this.logService.error(e);
What happened to logging the error?

2024-05-15 09:54 UTC, KiruthigaManivannan commented on apps/web/src/app/auth/recover-two-factor.component.ts
> -      this.logService.error(e);
@rr-bw  Since we are using bitSubmit it will already handle this logging error. During our Earlier PRs are we were asked to remove try catch block for bitSubmit.

2024-05-22 22:53 UTC, rr-bw commented on apps/web/src/app/auth/recover-two-factor.component.ts
> -      this.logService.error(e);
Cool! Thanks for the context.

2024-05-22 23:04 UTC, rr-bw requested changes
Thanks, just a few more minor updates and this is good to go.

2024-05-22 23:04 UTC, rr-bw commented on apps/web/src/app/auth/recover-two-factor.component.html
> +  <div class="tw-w-96">
I know I previously had you change this to `tw-w-96`, but we recently made a few modifications to AnonLayout. The AnonLayout now wraps this section with a `tw-max-w-md`.

This means that once you grab the latest changes from `main`, you can remove this `tw-w-96` class entirely.

2024-05-22 23:04 UTC, rr-bw commented on apps/web/src/app/oss-routing.module.ts
> +import { AnonLayoutWrapperComponent } from "./auth/anon-layout-wrapper.component";
Once you grab the latest from `main`, this should change to:

```typescript
import { AnonLayoutWrapperComponent } from "@bitwarden/auth/angular"
```

2024-05-22 23:04 UTC, rr-bw commented on apps/web/src/app/oss-routing.module.ts
> +        canActivate: [UnauthGuard],
Use `unauthGuardFn()`

2024-06-03 16:34 UTC, rr-bw requested changes
For this page:

1. Grab latest from `main`
2. Update the import in `oss-routing.module.ts` to:
```typescript
import { AnonLayoutWrapperComponent } from "@bitwarden/auth/angular";
```
3. Update the route to:
```typescript
   {
    path: "",
    component: AnonLayoutWrapperComponent,
    children: [
      {
        path: "recover-2fa",
        canActivate: [unauthGuardFn()],
        children: [
          {
            path: "",
            component: RecoverTwoFactorComponent,
          },
          {
            path: "",
            component: EnvironmentSelectorComponent,
            outlet: "environment-selector",
          },
        ],
        data: {
          pageTitle: "recoverAccountTwoStep",
          titleId: "recoverAccountTwoStep",
        },
      },
    ],
  },
```
You will need to import the web Environment Selector:

```typescript
import { EnvironmentSelectorComponent } from "./components/environment-selector/environment-selector.component";
```

2024-06-05 17:36 UTC, rr-bw approved these changes

2024-06-05 17:52 UTC, merged