PM-4960 Migrate Verify Recover Delete Component
bitwarden/clients pull request #9171
Opened 2024-05-14 12:42 UTC by KiruthigaManivannan

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other
```

## Objective

Migrate the Verify Recover Delete Component to use the component library.

## Code changes

- **verify-recover-delete.component.html:** Added form group and bit form fields
- **verify-recover-delete.component.ts:** Added new form group , converted submit to arrow function
- **oss-routing.module.ts:** Added Routing for Anon layout wrapper component.

## Screenshots

https://github.com/bitwarden/clients/assets/162679756/d8c52767-5dbf-420b-845b-a99d800d6edb

https://github.com/bitwarden/clients/assets/162679756/d8c52767-5dbf-420b-845b-a99d800d6edb

https://github.com/bitwarden/clients/assets/162679756/d8c52767-5dbf-420b-845b-a99d800d6edb

2024-05-22 20:21 UTC, ike-kottlowski approved these changes
functional tests were good.

2024-05-22 21:58 UTC, rr-bw commented on apps/web/src/app/oss-routing.module.ts
> +          pageTitle: "deleteAccount",
@KiruthigaManivannan When you get the latest from `main` and resolve the merge conflict in oss-routing.module.ts, could you also carry over the `titleId`?

```typescript
data: {
  pageTitle: "deleteAccount",
  titleId: "deleteAccount",
}
```

You do _not_ need to add `satisfies AnonLayoutWrapperData` to the object. Auth team can do that later as we are still working on the type safety and don't want to block this PR.

2024-05-22 22:46 UTC, ike-kottlowski requested changes

2024-05-22 22:46 UTC, ike-kottlowski commented on apps/web/src/app/oss-routing.module.ts
> +        canActivate: [UnauthGuard],
Is it possible to change this to the `UnauthGuardFn()`?

2024-05-29 16:27 UTC, ike-kottlowski submitted a review, later dismissed
Looks good.

2024-06-11 23:02 UTC, ike-kottlowski approved these changes

2024-06-12 19:40 UTC, ike-kottlowski approved these changes

2024-06-19 15:18 UTC, merged