PM-1938 Migrate Accept Emergency Component
bitwarden/clients pull request #9177
Opened 2024-05-14 15:34 UTC by KiruthigaManivannan

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other
```

## Objective

Migrate the Accept Emergency Component to use the component library.

## Code changes

- **accept-emergency.component.html:** Added buttons from library
- **oss-routing.module.ts:** Added Routing for Anon layout wrapper component.

## Screenshots

https://github.com/bitwarden/clients/assets/162679756/1b7b3e10-1e40-4067-acb5-c4bc5d171a91

2024-05-30 22:04 UTC, JaredSnider-Bitwarden requested changes

2024-05-30 22:04 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/emergency-access/accept/accept-emergency.component.html
Please restore the loading functionality to this component. 
In your recorded video, the user is left on an empty component after logging in after accepting the invite. 
![image](https://github.com/bitwarden/clients/assets/116684653/36c1cac3-81b9-45bb-b6da-533802a8c227)

2024-05-30 22:04 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/oss-routing.module.ts
> +  },
We have just pushed up the new changes to the anon-layout component which allow for the proper env selector to be configured: https://components.bitwarden.com/?path=/docs/auth-anon-layout--docs#environment-selector. That will need to be configured as well to show the server selector.

2024-06-03 11:53 UTC, KiruthigaManivannan commented on apps/web/src/app/auth/emergency-access/accept/accept-emergency.component.html
@JaredSnider-Bitwarden  Please find the below video and let me know if any thing needs to be changed.


https://github.com/bitwarden/clients/assets/162679756/2c8a269f-3a81-4805-b466-9ea0a07790cb

2024-06-03 21:17 UTC, JaredSnider-Bitwarden submitted a review, later dismissed
Thank you for incorporating the feedback! Looks good to me!

2024-06-04 16:20 UTC, JaredSnider-Bitwarden approved these changes

2024-06-04 16:38 UTC, JaredSnider-Bitwarden submitted a review, later dismissed

2024-06-05 20:00 UTC, JaredSnider-Bitwarden approved these changes

2024-06-06 13:15 UTC, merged