[PM-6823] Vault Header Refresh
bitwarden/clients pull request #9197
Opened 2024-05-15 18:34 UTC by nick-livefront

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Implement `popup-page` & `popup-header` for the VaultV2Component. 

## Code changes

- **vault-v2.component:**
  - Implement `popup-header` to match designs with the current components available.
  - The "New" button doesn't match the current figma design as a new button is in the works. 
- **pop-out.component:**
  - Add `Input` to allow for a different UI that is used in the V2 Header. 

## Screenshots

![Screen Recording 2024-05-15 at 1 20 45 PM](https://github.com/bitwarden/clients/assets/125900171/6f4bed6a-6b26-43b0-9bb5-7cc7875d3ab5)

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-05-15 19:15 UTC, willmartian requested changes

2024-05-15 19:15 UTC, willmartian commented on apps/browser/src/vault/popup/components/vault/vault-v2.component.html
> +      </button>
If this button is simply calling `router.navigate`, we should instead use an anchor element `<a bitButton [routerLink]="...">`

2024-05-15 19:15 UTC, willmartian commented on apps/browser/src/platform/popup/components/pop-out.component.html
Let me know if I am wrong in my assumptions here:
- We should not use an input because we don't want to support both styles indefinitely; the existing style is deprecated and is being replaced
- If we want to *temporarily* support both variants for release/rollback purposes, we should instead use a feature flag. (This is my change request.) It also more clearly marks this as something that needs to be removed in the future--when the flag itself is removed we will get a compiler error. 
- The other option is to make this change in the style update [feature branch](https://github.com/bitwarden/clients/pull/8696). But having it in main might be less confusing and this work is already extant so no need to backtrack.

2024-05-15 19:15 UTC, willmartian commented on apps/browser/src/platform/popup/components/pop-out.component.ts
> +import { IconButtonModule } from "../../../../../../libs/components/src/icon-button";
Please update to `"@bitwarden/components";`

Todo for @bitwarden/team-component-library : deep imports should error.

2024-05-16 15:59 UTC, nick-livefront commented on apps/browser/src/platform/popup/components/pop-out.component.ts
> +import { IconButtonModule } from "../../../../../../libs/components/src/icon-button";
👍 [57ef668](https://github.com/bitwarden/clients/pull/9197/commits/57ef668e6134414159a530c2acc1be9672a8710d)

2024-05-16 16:00 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault/vault-v2.component.html
> +      </button>
Good idea, I got caught up in looking at the current implementation and went after that. `a` makes more sense here: [7844232](https://github.com/bitwarden/clients/pull/9197/commits/784423283f3320b856fd7af3deba459cb68e31bf)

2024-05-16 16:00 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault/vault-v2.component.ts
> +    });
Eliminated as a part of: [7844232](https://github.com/bitwarden/clients/pull/9197/commits/784423283f3320b856fd7af3deba459cb68e31bf)

2024-05-16 16:03 UTC, nick-livefront commented on apps/browser/src/platform/popup/components/pop-out.component.html
Great call out! From all of the designs that I can see this will be fully replaced. So it falls in your feature flag suggestion, which I utilized the existing `ExtensionRefresh` feature flag. Huge improvement 💯 

[957a244](https://github.com/bitwarden/clients/pull/9197/commits/957a2445c867f8eecc44b7f381ebb3b48ce32ee7)

2024-05-16 18:03 UTC, shane-melton requested changes
One small issue with the `VaultFilterService`, otherwise this looks great! Nice work!

2024-05-16 18:03 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault/vault-v2.component.ts
issue: We're not expecting to use the `VaultFilterService` in new vault tab so we should leave the `selectedOrgId` undefined for now and mark it with a comment to be flushed out during the filter section implementation in PM-6826.

2024-05-16 18:35 UTC, willmartian requested changes

2024-05-16 18:35 UTC, willmartian commented on apps/browser/src/vault/popup/components/vault/vault-v2.component.html
> +        class="tw-no-underline"
Oh, could you actually remove this? It is no longer necessary after https://github.com/bitwarden/clients/pull/9219

2024-05-16 18:55 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault/vault-v2.component.ts
Thanks for the context! I added a comment to the markup & within [PM-6826](https://bitwarden.atlassian.net/browse/PM-6826?focusedCommentId=58293)

2024-05-16 18:55 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault/vault-v2.component.html
> +        class="tw-no-underline"
[351af96](https://github.com/bitwarden/clients/pull/9197/commits/351af96133105c9141d98b47608c53844cb2a93b)

2024-05-16 19:04 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault/vault-v2.component.ts
Thanks!

2024-05-16 19:04 UTC, shane-melton approved these changes
Looks good to go!

2024-05-16 19:28 UTC, willmartian approved these changes

2024-05-16 19:30 UTC, merged