[PM-4956] two factor component migration
bitwarden/clients pull request #9204
Opened 2024-05-16 04:52 UTC by vinith-kovan

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other
```

## Objective
Migrate the Two Factor Component to use the component library.

## Code changes

- **two-factor.component.html:** Added form group and bit form fields
- **two-factor.component.ts:** Added new form group, converted submit to arrow function
- **oss-routing.module.ts:**  Added Routing for Anon layout wrapper component.

## Screenshots

https://github.com/bitwarden/clients/assets/156108204/9c2806ac-05d8-42db-9e5f-fd60e61d3dd0

2024-05-17 17:51 UTC, jlf0dev requested changes
Since this is a very complex part of our code, please add some videos of successfully completing different 2fa methods and switching between them.

2024-05-17 17:51 UTC, jlf0dev commented on apps/web/src/app/auth/two-factor.component.html
>    [appApiAction]="formPromise"
We can remove the `appApiAction` since the `bitSubmit` handles the loading state.

2024-05-17 17:51 UTC, jlf0dev commented on apps/web/src/app/auth/two-factor.component.html
> +            [appApiAction]="emailPromise"
This should use the `bitAction` directive instead of the `appApiAction`

2024-05-22 13:25 UTC, jlf0dev commented
> Since this is a very complex part of our code, please add some videos of successfully completing different 2fa methods and switching between them.

Hi @vinith-kovan, any chance we can get a video showing off some of the other functionality? If you're not sure how to do that please let me know. Thanks!

2024-05-24 08:00 UTC, vinith-kovan commented
@jlf0dev I have added a video of two-factor authenticator, please take a look.

2024-05-24 15:49 UTC, danielleflinn commented
I'm not seeing the page title that we [discussed in slack](https://bitwarden.slack.com/archives/C06A09D5MU5/p1715697297259859?thread_ts=1715640810.426179&cid=C06A09D5MU5) in the screen recording. Please add "Verify your Identity" to the 2FA page.

2024-05-28 10:12 UTC, vinith-kovan commented
Hi @danielleflinn "Verify your Identity" has been added.

![image](https://github.com/bitwarden/clients/assets/156108204/1097d913-7d5f-4cdc-aeee-da0becdb9f69)

2024-05-29 15:55 UTC, jlf0dev commented on apps/web/src/app/auth/two-factor.component.html
> +      <a biLink href="#" appStopClick (click)="anotherMethod()">{{
Is `bilink` here supposed to be `bitlink`?

2024-05-29 15:55 UTC, jlf0dev commented on apps/web/src/app/auth/two-factor.component.html
> +    ></i>
Please remove this spinner, I'm not sure how much value its adding here

2024-05-29 16:11 UTC, jlf0dev commented on apps/web/src/app/auth/two-factor.component.ts
> +  });
I'm getting some strange behavior with the default `updateOn` behavior, as you can see in this video. 

https://github.com/bitwarden/clients/assets/24985544/87a264ef-2490-42cf-9aa6-54a0e84a5053


Can you please change this to update on submit as so:
```js
  formGroup = this.formBuilder.group({
    token: [
      "",
      {
        validators: [Validators.required],
        updateOn: "submit",
      },
    ],
    remember: [false],
  });
```

2024-06-03 16:46 UTC, danielleflinn submitted a review, later dismissed

2024-06-10 13:35 UTC, jlf0dev approved these changes

2024-06-10 14:47 UTC, danielleflinn submitted a review, later dismissed

2024-06-10 22:43 UTC, jlf0dev approved these changes

2024-06-11 17:55 UTC, merged