[AC-2559] - BUG - Refactor members search observable chains
bitwarden/clients pull request #9230
Opened 2024-05-17 02:39 UTC by vincentsalucci

## Type of change

- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

> Searching for members within an organization is broken. Refactor the observable chains to reduce boilerplate and restore the search functionality.

## Code changes

### apps/web/src/app/admin-console/common/base.people.component.ts
- Removed getter/setter/behavior subject for `searchText` tracking
- Added a `FormControl` for search text manipulation and information binding
- Added two observable chains that will pass along the search text / state to its subscribers
- Moved `isPaging` into one of the above mentioned observables

### apps/web/src/app/admin-console/organizations/members/people.component.html
- Updated `searchText` references to take either the control or the read-only value
- Replaced `isPaging` method calls with the new observable, retrieving data via the async pipe

### apps/web/src/app/admin-console/organizations/members/people.component.ts
- Set initial value if query param `search` text is available

### bitwarden_license/bit-web/src/app/admin-console/providers/manage/people.component.html
- Updated `searchText` references to take either the control or the read-only value
- Replaced `isPaging` method calls with the new observable, retrieving data via the async pipe

### bitwarden_license/bit-web/src/app/admin-console/providers/manage/people.component.ts
- Set initial value if query param `search` text is available

## Screenshots
https://github.com/bitwarden/clients/assets/26154748/516eb21b-a04b-4ea2-bc55-1d854dbd0d7f

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-05-19 22:54 UTC, eliykat requested changes

2024-05-19 22:54 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/members/people.component.html
> +    [(ngModel)]="searchControl"
I'm not sure why two-way binding is used here (the `[(` syntax) but I don't think it's necessary. The `SearchComponent` just implements `ControlValueAccessor` and doesn't seem to be doing anything unusual. Can you try replacing the `NgModel` binding with `FormControl` (like a normal reactive form) and then verify it still works?

2024-05-19 22:54 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/members/people.component.html
> +    [(ngModel)]="searchControl"
Same applies for all other uses of `bit-search` in this PR.

2024-05-19 22:54 UTC, eliykat commented on apps/web/src/app/admin-console/common/base.people.component.ts
> +  ngOnInit(): void {}
`ngOnInit` is no longer required and can be deleted.

2024-05-19 22:54 UTC, eliykat commented on apps/web/src/app/admin-console/common/base.people.component.ts
> +        this.resetPaging();
`resetPaging()` doesn't actually need to be async, once you remove `async` from its declaration then this `FIXME` and `eslint-disable` comment can be removed.

2024-05-19 22:54 UTC, eliykat commented on apps/web/src/app/admin-console/common/base.people.component.ts
> +        this.resetPaging();
There are also other calling locations in this component with similar FIXMEs that can be removed.

2024-05-19 22:54 UTC, eliykat commented on apps/web/src/app/admin-console/common/base.people.component.ts
> +    }),
I'm concerned here we have 3 other variables that affect this callback, but because it's now an observable, it's only going to be recalculated when `isSearching` emits.

Thinking aloud here, those other variables are:

* `this.users` - part of this logic is that the component is paging when `this.users.length` exceeds the pre-set page size. `this.users.length` can change independent of `isSearching$`, so I think this needs to be an observable that can be combined with` isSearching$`.
* `this.didScroll` - the logic here seems to be, "if you scrolled down enough to get the next page of results, and then you search, reset the paging". I _think_ that's still OK, because it's not actually triggered by a change in `didScroll` - it's more like a record of what the user's already done. So I think we can leave that.
* `this.pageSize` - this is a constant which will never change, so it's fine

I'm not super familiar with this paging logic (really it should be replaced by infinite scroll) but this seems like a potential gotcha that I want to make sure we think about.

2024-05-19 22:56 UTC, eliykat commented on apps/web/src/app/admin-console/common/base.people.component.ts
>    protected destroy$ = new Subject<void>();
`destroy$` was only added with these breaking changes, you should be able to delete it along with `onDestroy`.

2024-05-22 14:50 UTC, vincentsalucci commented on apps/web/src/app/admin-console/common/base.people.component.ts
>    protected destroy$ = new Subject<void>();
This is still used in one of the inheriting classes. I moved it out of the base class for now to reduce scope. I think making any further changes there is out of scope for this PR.

2024-05-22 14:51 UTC, vincentsalucci commented on apps/web/src/app/admin-console/common/base.people.component.ts
> +  ngOnInit(): void {}
Removed.

2024-05-22 14:51 UTC, vincentsalucci commented on apps/web/src/app/admin-console/organizations/members/people.component.html
> +    [(ngModel)]="searchControl"
Updated and working as expected

2024-05-22 22:57 UTC, eliykat commented on apps/web/src/app/admin-console/common/base.people.component.ts
>    protected destroy$ = new Subject<void>();
Agreed!

2024-05-23 03:35 UTC, eliykat commented on apps/web/src/app/admin-console/common/base.people.component.ts
> +    }),
Thanks for syncing on this! Where we landed was that this is fine for now, and I've created AC-2673 to remove the old paging logic.

2024-05-23 03:35 UTC, eliykat approved these changes

2024-05-23 14:05 UTC, merged