[PM-6789] add legacy user key state
bitwarden/clients pull request #9274
Opened 2024-05-20 18:18 UTC by jlf0dev

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

When we migrated private keys to state providers, we didn't account for legacy user keys. Without being able to decrypt the private key using the legacy key (master key) we couldn't migrate the legacy users. This adds a `activeUserKeyWithLegacySupport$` observable to pass in the derived state so it can correctly decrypt the private key.
## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-05-20 18:21 UTC, jlf0dev commented
@MGibson1 I know we discussed moving out all the legacy code from the crypto service, but that ended up being quite the overhaul. Considering this should be the final step before removing all the legacy code, I wanted to throw this up as an option.

2024-05-20 20:31 UTC, ike-kottlowski approved these changes, later dismissed
Auth changes are good.

2024-05-21 17:08 UTC, MGibson1 requested changes

2024-05-21 17:08 UTC, MGibson1 commented on libs/common/src/platform/services/crypto.service.ts
> +        }
**issue**: please use master password service directly rather than this, which causes a weird cycle on `activeUserKey$`.

I would just switch map a few times from user id -> master key -> async is legacy user with a function that returns the master key again

2024-05-22 13:02 UTC, jlf0dev commented on libs/common/src/platform/services/crypto.service.ts
> +        }
Fixed!

2024-05-22 17:35 UTC, ike-kottlowski approved these changes

2024-05-23 18:46 UTC, MGibson1 approved these changes

2024-05-23 18:48 UTC, MGibson1 requested changes

2024-05-23 18:48 UTC, MGibson1 commented on libs/common/src/platform/services/crypto.service.ts
> +        }
Why not just call validate -- you have all the data

What is returned if neither pass?

2024-05-23 18:56 UTC, justindbaur commented
Heads up, I am working on some changes right now that are actually going to get rid of `activeUserKey$` in favor of a method that requires a user id. If the main goal of this is that the encrypted private key needs to allow for the user of the master key for legacy reasons I can take care of that in my changes. I would need an answer to [Matt's question](https://github.com/bitwarden/clients/pull/9274#discussion_r1612163865) before finishing it though.

2024-05-23 21:26 UTC, jlf0dev commented on libs/common/src/platform/services/crypto.service.ts
> +        }
1. Good point, sure why not.
2. We could return `userKey` (really whatever the state provider should give us if there was no `userKey`). The `userKey` nullish check should happen before we check for legacy users. So we're not doing extra computation on every request.

2024-05-23 21:27 UTC, jlf0dev commented
@justindbaur That'd be awesome, can you add me on that PR? I can close this in favor of that one.

2024-05-28 01:19 UTC, jlf0dev commented
Closing in favor of #9364

2024-05-28 01:19 UTC, closed without merging