PM-4950 Migrate Hint Component
bitwarden/clients pull request #9303
Opened 2024-05-22 06:30 UTC by KiruthigaManivannan

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other
```

## Objective

Migrate the Hint component to use the component library.

## Code changes
- **hint.component.html:** Added form group and bit form fields
- **hint.component.ts:** Added new form group , converted submit to arrow function
- **oss-routing.module.ts:** Added Routing for Anon layout wrapper component.
## Screenshots

https://github.com/bitwarden/clients/assets/162679756/55f67e5b-5164-4ddd-87a1-d0f7240ba0b6

2024-05-29 21:23 UTC, JaredSnider-Bitwarden reviewed
This is looking really good! Just two small ideas / tweaks listed 👇

2024-05-29 21:23 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/hint.component.ts
> +    await this.submitSuper();
Nit pick: you probably could just call `await super.submit();` here without worrying about creating a function to execute the one line?

2024-05-29 21:23 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/hint.component.ts
> +    this.formGroup.get("email").setValue(this.email);
Idea:  it could be worth creating a get accessor for the local form email form control since you access it twice in this component. 
```Typescript
  get formEmail(): FormControl {
    return this.formGroup.get("email") as FormControl;
  }
  ```

2024-05-29 22:07 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/oss-routing.module.ts
> +  },
@KiruthigaManivannan , we  just pushed up the new changes to the anon-layout component which allow for the proper env selector to be configured: https://components.bitwarden.com/?path=/docs/auth-anon-layout--docs#environment-selector. That will need to be configured as well.

2024-06-03 10:17 UTC, KiruthigaManivannan commented on apps/web/src/app/auth/hint.component.ts
> +    await this.submitSuper();
@JaredSnider-Bitwarden If I call super.submit directly inside submit which is an async arrow function . I get the below error.
![image](https://github.com/bitwarden/clients/assets/162679756/5097cfaa-2f93-46ca-9c56-fa600a6fc0db)

Thats why I added the separate submitSuper method. Should i need to change ?Please advise

2024-06-03 21:55 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/hint.component.ts
> +    await this.submitSuper();
Ah, good point. I'm sorry that I missed that! I added a comment explaining that.

2024-06-03 21:55 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/hint.component.ts
> +    this.formGroup.get("email").setValue(this.email);
I tweaked the implementation to match this recommendation and re-tested.

2024-06-03 21:56 UTC, JaredSnider-Bitwarden submitted a review, later dismissed

2024-06-04 08:34 UTC, Hinton requested changes
We have a leaking subscription here, that should be fixed before merge. The other 3 comments are more open ended.

2024-06-04 08:34 UTC, Hinton commented on apps/web/src/app/auth/hint.component.ts
> +  // Wrapper method to call super.submit() since arrow functions cannot use super directly
This isn't directly related to arrow functions but rather because `submit` is a property. Properties are assigned per type and generally don't have access to the prototype.

2024-06-04 08:34 UTC, Hinton commented on apps/web/src/app/auth/hint.component.ts
> +  private destroy$ = new Subject<void>();
**blocker**: This subject never destroyed, which means it will leak memory! We need to either implement `OnDestroy` or use [`takeUntilDestroyed`](https://v17.angular.io/api/core/rxjs-interop/takeUntilDestroyed)

2024-06-04 08:34 UTC, Hinton commented on apps/web/src/app/auth/hint.component.ts
> +    });
**question**: Is this needed? `this.email` is already set on the submit handler.

2024-06-04 08:34 UTC, Hinton commented on apps/web/src/app/auth/hint.component.ts
> +  }
**issue**: Please use the typed interface for `FormGroups`. This will cause a compile error should `email` not exist in the `formGroup` any longer.

```suggestion
  get emailFormControl() {
    return this.formGroup.controls.email;
  }
```

2024-06-04 15:38 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/hint.component.ts
> +    });
It was not needed. I've removed it.

2024-06-04 15:38 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/hint.component.ts
> +  private destroy$ = new Subject<void>();
The [removal](https://github.com/bitwarden/clients/pull/9303#discussion_r1626237643) of the valueChanges resulted in no longer needing this.

2024-06-04 15:38 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/hint.component.ts
> +  // Wrapper method to call super.submit() since arrow functions cannot use super directly
I've updated the comment. Thank you for helping make it more accurate!

2024-06-04 15:39 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/hint.component.ts
> +  }
Ah, TIL that Angular 14 introduced type safety with the controls approach. Thank you!

2024-06-04 15:44 UTC, JaredSnider-Bitwarden commented
I've retested to ensure this is good to go.

2024-06-04 17:18 UTC, Hinton approved these changes
My concerns are addressed.

2024-06-10 20:13 UTC, JaredSnider-Bitwarden submitted a review, later dismissed

2024-06-18 21:12 UTC, JaredSnider-Bitwarden submitted a review, later dismissed

2024-06-19 15:23 UTC, JaredSnider-Bitwarden approved these changes

2024-06-19 15:42 UTC, merged