SM-1213 Add Bitwarden Secrets Manager tip to CLI help
bitwarden/clients pull request #9307
Opened 2024-05-22 14:15 UTC by mzieniukbw

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [X] Other
```

## Objective

To increase awareness to our user base we want to add a small tip to the help output of the bw CLI.

## Code changes

`bw` and `bw --help` now displays the `Tip: Managing and retrieving secrets for dev environments is easier with Bitwarden Secrets Manager. Learn more under https://bitwarden.com/products/secrets-manager/` text in yellow color in between the _Usage_ and _Options_.

## Screenshots

2024-05-22 17:06 UTC, coltonhurst submitted a review, later dismissed

2024-05-22 17:12 UTC, coltonhurst requested changes
@mzieniukbw the changes look good to me, but can you update your branch with the changes on `main`? The failing CI was fixed by Matt's [PR](https://github.com/bitwarden/clients/pull/9308) already.

2024-05-23 14:21 UTC, coltonhurst approved these changes

2024-05-23 19:03 UTC, MGibson1 reviewed
This doesn't feel like a description to me.

We capture calls to `--help` and display custom messaging that includes examples. I think it would better fit at the top of that.

2024-06-03 18:37 UTC, MGibson1 approved these changes

2024-06-03 19:27 UTC, coltonhurst approved these changes

2024-06-06 07:40 UTC, merged