[AC-2504] Add new members access report card
bitwarden/clients pull request #9335
Opened 2024-05-23 13:43 UTC by aj-rosado

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Add new member access report card with a new guard validating if org is enterprise.

## Code changes

- **is-enterprise-org.guard.ts:** Guard that validates if the org has enterprise access, otherwise shows a dialog asking the user to upgrade to enterprise.
- **organization-reporting-routing.module.ts:** Added new route to member access report page.
- **organizations/reporting/reports-home.component.ts:** Adding the member access report entry to the `reportsArray` when the feature flag is active
- **reports.ts**: Added new member access report
- **report-variant.ts**: Added new variant `RequiresEnterprise`

## Screenshots

### **Light Layout:**

**Enterprise**
<img width="400" alt="enterprise reports light layout" src="https://github.com/bitwarden/clients/assets/109146700/3c8c36fa-7c23-493a-8cca-b31259f79a16">

**Family/Teams**
<img width="400" alt="family/teams reports light layout" src="https://github.com/bitwarden/clients/assets/109146700/30083e2e-4ff7-4d06-9bf0-8df66821ad1b">

**Free**
<img width="400" alt="free reports light layout" src="https://github.com/bitwarden/clients/assets/109146700/472f43e8-ecf7-42b4-81d7-dd2fb0d9e2aa">

**Upgrade Dialog**
<img width="332" alt="upgrade dialog member access light layout" src="https://github.com/bitwarden/clients/assets/109146700/8d63f39d-33c6-4ea0-8649-3c20d6036760">

### **Dark Layout:**
**Enterprise**
<img width="400" alt="enterprise reports light layout"  src="https://github.com/bitwarden/clients/assets/109146700/5d195e35-fd9e-4e58-92ad-1c2bfea62f2a">

**Family/Teams**
<img width="400" alt="family/teams reports dark layout"  src="https://github.com/bitwarden/clients/assets/109146700/01085d07-2c03-439d-90b3-0339b0fbcb7a">

**Free**
<img width="400" alt="free reports dark layout" src="https://github.com/bitwarden/clients/assets/109146700/39335140-a176-44dd-8ade-8e93ac4e4001">

**Upgrade Dialog**
<img width="331" alt="upgrade dialog member access dark layout"  src="https://github.com/bitwarden/clients/assets/109146700/52795b47-6c81-4442-a8f3-a0d3aaa2c9c9">

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-05-24 12:44 UTC, djsmith85 requested changes

2024-05-24 12:44 UTC, djsmith85 commented on apps/web/src/app/admin-console/organizations/guards/is-enterprise-org.guard.ts
> +    }
I'd probably remove this check, as the guard itself could be used by others, regardless of this feature flag. You are also only showing the card if the flag is enabled, so no need to check it again.

2024-05-24 12:44 UTC, djsmith85 commented on apps/web/src/app/admin-console/organizations/reporting/reports-home.component.ts
> +  private memberAccessReport: boolean;
This should be renamed to make it clear that it's a flag showing if the report is accesible/visible

Suggestion: `isMemberAccessReportEnabled`or `memberAccessReportEnabled` if you don't want to prefix with is/can/has

2024-05-24 12:44 UTC, djsmith85 commented on apps/web/src/locales/en/messages.json
> +
Please remove empty line

2024-05-27 11:14 UTC, aj-rosado commented on apps/web/src/app/admin-console/organizations/guards/is-enterprise-org.guard.ts
> +    }
I added this to protect against navigating directly to the url, despite not displaying the card would still be possible to navigate directly through the endpoint

2024-05-27 11:15 UTC, aj-rosado commented on apps/web/src/app/admin-console/organizations/reporting/organization-reporting-routing.module.ts
> +          {
Will remove and add it later with the `MemberAccessComponent`

2024-05-28 20:54 UTC, djsmith85 submitted a review, later dismissed

2024-05-31 17:58 UTC, vincentsalucci commented on apps/web/src/app/admin-console/organizations/guards/is-enterprise-org.guard.ts
> +    if (!isMemberAccessReportEnabled) {
🎨 Let's make sure this conditional is removed during the feature flag clean-up.

2024-05-31 17:58 UTC, vincentsalucci approved these changes

2024-06-18 09:53 UTC, djsmith85 approved these changes

2024-06-18 10:37 UTC, djsmith85 approved these changes

2024-06-18 20:26 UTC, eliykat approved these changes

2024-06-18 21:13 UTC, merged