[PM-6824] Browser V2 Search
bitwarden/clients pull request #9343
Opened 2024-05-23 17:58 UTC by Jingo88

```
- [ ] Bug fix
- [ X ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Incorporate the search functionality to the new Browser `vault-v2` component

## Code changes

* Create component for `vault-v2-search`. This will be presentational using `bit-search` and emitting the text value
* `vault-v2` component will get the value emitted and pass it to the `applyFilter` method in the `vault-popup-item.service`
* `vault-popup-items.service` will have a new `_filteredCipherList$` that will be filtered with the `searchService.searchCiphers` and pass those values down to the other cipher lists `favorites` `autofill` and `remaining`. 
* `_filteredCipherList$` will also be used by the `noFilterResults$` Observable so we can determine when the `no results page` will show in vault
* spec file updated for new service and new cipher list

## Screenshots

NO RESULTS
![PM-6824-no-results](https://github.com/bitwarden/clients/assets/8302660/59c3ef07-2d2b-48d7-b58d-693e47480ba1)

MULTIPLE RESULTS
![PM-6824-multi-results](https://github.com/bitwarden/clients/assets/8302660/2aeedbf9-d54f-4984-a40b-01ba782e40d3)

SINGLE RESULTS
![PM-6824-single-result](https://github.com/bitwarden/clients/assets/8302660/1b9551b7-c43b-4cb0-b6d7-a4da61f3b2f6)

2024-05-23 18:22 UTC, shane-melton requested changes
This is looking great, nice work! I see one small blocking issue and then had a few other suggestions.

2024-05-23 18:22 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/vault-search/vault-v2-search.component.ts
> +    this.searchText = t;
nit (non-blocking): I don't think we need `this.searchText = t` because its already set due to the `[(ngModel)]` directive in the template.

Also, you could technically put the `searchTextChanged.emit($event)` in the template, avoiding the need for the method entirely.

2024-05-23 18:22 UTC, shane-melton commented on apps/browser/src/vault/popup/services/vault-popup-items.service.spec.ts
suggestion: Would you mind adding some tests to keep the coverage of this service up? Specifically around the `hasFilterApplied$` and `noFilteredResults$` observables and maybe the `applyFilter()` method.

2024-05-23 18:22 UTC, shane-melton commented on apps/browser/src/vault/popup/services/vault-popup-items.service.ts
> +  private _filteredCipherList$ = combineLatest([this._cipherList$, this.searchText$]).pipe(
suggestion: We probably want to add some type of `debounce` to the `searchText$` observable here to avoid repeatedly spamming the search logic while the user is typing. 

We do something similar in the vault here: https://github.com/bitwarden/clients/blob/db3d66dae1ca610f70109034426c4bf33f29ab20/apps/web/src/app/vault/individual-vault/vault.component.ts#L232-L234

2024-05-23 18:22 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault/vault-v2.component.html
> +  <app-vault-v2-search (searchTextChanged)="handleSearchTextChange($event)"> </app-vault-v2-search>
issue: We should move this down to line ~27 with the TODO, so that the search/filters are hidden when the Vault is empty to match the Figma.

2024-05-23 18:22 UTC, shane-melton commented on apps/browser/src/vault/popup/services/vault-popup-items.service.ts
> +  private _filteredCipherList$ = combineLatest([this._cipherList$, this.searchText$]).pipe(
Or maybe we should do this within the new search component?

2024-05-24 18:15 UTC, Jingo88 commented on apps/browser/src/vault/popup/services/vault-popup-items.service.ts
> +  private _filteredCipherList$ = combineLatest([this._cipherList$, this.searchText$]).pipe(
yeah good point. I've implemented it in the search component. I think it fits better there.

2024-05-25 00:27 UTC, willmartian commented on apps/browser/src/vault/popup/components/vault-v2/vault-search/vault-v2-search.component.html
> +</div>
Would it make sense to build in debouncing into `bit-search`? Something like

`<bit-search [debounce]="SearchTextDebounceInterval" ...>`

2024-05-25 00:29 UTC, willmartian commented on apps/browser/src/vault/popup/components/vault-v2/vault-search/vault-v2-search.component.html
> +</div>
Or maybe even a generic directive that debounces `ngModelChange` anywhere it is used? 🤔 

(Assuming that is feasible)

2024-05-28 15:28 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/vault-search/vault-v2-search.component.html
> +</div>
@willmartian That sounds like a great idea to me!

2024-05-28 16:03 UTC, willmartian commented on apps/browser/src/vault/popup/components/vault-v2/vault-search/vault-v2-search.component.html
> +</div>
Created a ticket here: https://bitwarden.atlassian.net/browse/CL-299

If y'all are interested in utilizing such a feature sooner than later, feel free to implement it in this ticket! Otherwise I can mark PM-6824 as related and make a note to remove the debounce implemented here later since it would be redundant.

2024-05-28 17:12 UTC, Jingo88 commented on apps/browser/src/vault/popup/components/vault-v2/vault-search/vault-v2-search.component.html
> +</div>
I'm okay with sending this to QA as is so we can keep the ball rolling on the V2 work, and I'll keep a look out to remove the debounce implementations later.

2024-05-28 17:12 UTC, willmartian commented on apps/browser/src/vault/popup/components/vault-v2/vault-search/vault-v2-search.component.html
> +</div>
Sounds great! 🫡

2024-05-28 17:28 UTC, shane-melton approved these changes
Thanks for adding those tests and debounce! I did see one possible small nit/improvement, but I don't think it should be blocking from moving this forward.

2024-05-28 17:28 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/vault-search/vault-v2-search.component.ts
> +      .pipe(debounceTime(SearchTextDebounceInterval), takeUntil(this.destroy$))
nit (non-blocking): We can use the [new `takeUntilDestroyed` operator](https://angular.dev/api/core/rxjs-interop/takeUntilDestroyed) provided by Angular so we can avoid the `destroy$` subject.

2024-05-28 17:55 UTC, shane-melton approved these changes

2024-05-28 21:08 UTC, merged