[PM-8210] Reintroduce Foreground & Background Derived State
bitwarden/clients pull request #9344
Opened 2024-05-23 18:12 UTC by justindbaur

## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Fix a race condition in the retrieval of decrypted ciphers while they are being updated. Inlined derived state didn't respect the `forceValue` method much at all. The thinking was it doesn't have it's own cache so there isn't a security reason to force a value. But `CipherService` is using it to block emissions during an update so I broke this. Adding it back because the original bug that caused us to remove it seems to have gotten fixed in another way. But I will have QA do full automation to make sure. 

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

2024-05-23 20:04 UTC, MGibson1 requested changes
small but hopefully meaningful changes

2024-05-23 20:04 UTC, MGibson1 commented on apps/browser/src/platform/state/background-derived-state.ts
> +    this.sendMessage(
```suggestion
    await this.sendMessage(
```

2024-05-25 16:37 UTC, justindbaur commented on apps/browser/src/platform/state/foreground-derived-state.ts
> +    private pipeCustomizer: OperatorFunction<unknown, TTo>,
Good call, this is definitely not supposed to make any changes to the data.

2024-05-25 16:38 UTC, justindbaur commented on apps/browser/src/platform/state/background-derived-state.ts
> +    this.sendMessage(
Was going to do this but `sendMessage` didn't actually need to be async and therefore `sendResponse` didn't need to be either so I removed that instead.

2024-05-28 21:16 UTC, Jingo88 approved these changes

2024-10-21 17:45 UTC, closed without merging