[PM-6826] Vault filter refresh
bitwarden/clients pull request #9365
Opened 2024-05-24 22:21 UTC by nick-livefront

## 🎟️ Tracking

[PM-6826](https://bitwarden.atlassian.net/browse/PM-6826)

## 📔 Objective

- Add the ability to filter ciphers within the Extension Vault
  - Behind `ExtensionRefresh` feature flag
- Available filters: `Vault`, `Collection`, `Folder`, & `Type`

### Open Thoughts

- I'm pondering if there are some efficiency gains to be had but I wanted to get this PR up. I'll see if there are some other approaches I could take with the observables here. Though I'm open to ideas!
- I needed to alter the `ChipSelectComponent` in order for the integration to work here. I'll leave individual comments as to _why_.
- This will have conflicts with @Jingo88's https://github.com/bitwarden/clients/pull/9343, I'll keep an eye out on changes there for any conflicts/implementation changes!

## 📸 Screenshots

|General Functionality|Deactivated Org|
|---------------------|----------------|
|<img src="https://github.com/bitwarden/clients/assets/125900171/a512b6ce-e694-41fe-8ec6-1ad6f04145bd" width="376" />|<img width="376" alt="Screenshot 2024-05-24 at 3 41 28 PM" src="https://github.com/bitwarden/clients/assets/125900171/c6281203-fc73-4232-8e1b-ccef2acbd4ee">|

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-05-24 22:27 UTC, nick-livefront commented on libs/components/src/chip-select/chip-select.component.ts
> +    if (tree.value !== null && tree.value === value) {
Reason for change: 

When my initial value was null and that the `tree` value was also null, it would return the `tree` resulting in `this.selectedOption` being set to a truthy value. 
So the empty state is shown as selected:
<img width="383" alt="Screenshot 2024-05-24 at 5 26 07 PM" src="https://github.com/bitwarden/clients/assets/125900171/eece81fa-d34a-4fc3-b1bc-75e6b9a3b1a2">

2024-05-24 22:30 UTC, nick-livefront commented on libs/components/src/chip-select/chip-select.component.ts
> +    this.notifyOnChange(option?.value ?? null);
The optional chaining here is calling `notifyOnChange` with `undefined` rather than `null`, which resulted in logic issues when `null` is used for empty states.

The inverse could be argued, when `undefined` is used for an empty state. In my opinion `null` is a more natural use case for these scenarios but I'm open to the discussion!

2024-05-28 13:18 UTC, nick-livefront commented
I'm moving this to a draft, I realized that if selecting one filter negates another one the filter is still being applied. I have to rework how I'm handling the filters. 

I'm still open to feedback in the meantime!

2024-05-28 18:36 UTC, shane-melton requested changes
This is looking great! I know its still in Draft but I added a few comments on what you have so far!

2024-05-28 18:36 UTC, shane-melton commented on apps/browser/src/vault/popup/services/vault-popup-list-filters.service.ts
> +    this.vaultSettingsService.showCardsCurrentTab$,
issue: These `show*CurrentTab$` settings are meant to only apply to the autofill list section and determine if Cards/Identities should show up there in addition to Logins.

Otherwise, I believe we should always show all cipher types in the filter chip regardless of the settings.

2024-05-28 18:36 UTC, shane-melton commented on apps/browser/src/vault/popup/services/vault-popup-list-filters.service.ts
> +              } else if (org.planProductType === 1) {
nit (non-blocking): Can we use the `ProductType` enum here instead of `1`?

2024-05-28 18:36 UTC, shane-melton commented on apps/browser/src/vault/popup/services/vault-popup-list-filters.service.ts
> +        if (orgs.length) {
nit (non-blocking): Smallest of nits/suggestion, but we could invert this `if` to reduce the nesting here a bit.

2024-05-28 18:36 UTC, shane-melton commented on apps/browser/src/vault/popup/services/vault-popup-list-filters.service.ts
> +  cipherTypes$: Observable<ChipSelectOption<string | CipherType>[]> = combineLatest([
question: Why do we have `string | CipherType[]` here for the `ChipSelectOption`?

2024-05-28 18:36 UTC, shane-melton commented on apps/browser/src/vault/popup/services/vault-popup-list-filters.service.ts
> +      const allCollections = await this.collectionService.getAllDecrypted();
suggestion: We can use the `collectionService.decryptedCollections$` observable instead of `getAllDecrypted()`

2024-05-28 18:36 UTC, shane-melton commented on apps/browser/src/vault/popup/services/vault-popup-list-filters.service.spec.ts
kudos: As always, thanks for the tests!

2024-05-28 18:36 UTC, shane-melton commented on apps/browser/src/vault/popup/services/vault-popup-items.service.ts
> +    this.vaultPopupListFiltersService.filters$,
thought: Random idea, not necessarily better, but what if we had a `filterFunction$` observable on the filter service and subscribe to that. 

I think it might help avoid some of the awkwardness around subscribing to a service value and then passing it back into said service. What do you think?

2024-05-29 16:04 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault-v2/vault-list-filters/vault-list-filters.component.ts
> +    this.filterForm.valueChanges.pipe(takeUntil(this.destroy$)).subscribe((formValue) => {
Noted for next time, I nixed this change based on moving the filterForm into the service 🚀

2024-05-29 16:05 UTC, nick-livefront commented on apps/browser/src/vault/popup/services/vault-popup-list-filters.service.ts
> +    this.vaultSettingsService.showCardsCurrentTab$,
Removed! [7d0e096](https://github.com/bitwarden/clients/pull/9365/commits/7d0e0967f53553ec3936060ac02909f1c169560a)

2024-05-29 16:05 UTC, nick-livefront commented on apps/browser/src/vault/popup/services/vault-popup-list-filters.service.ts
> +              } else if (org.planProductType === 1) {
[53e4e4b](https://github.com/bitwarden/clients/pull/9365/commits/53e4e4baa468a4cfe9e61bbd5be6d5aaebdb2f77)

2024-05-29 16:06 UTC, nick-livefront commented on apps/browser/src/vault/popup/services/vault-popup-list-filters.service.ts
> +  cipherTypes$: Observable<ChipSelectOption<string | CipherType>[]> = combineLatest([
I'm not sure why I had to add that but I remember jumping hoops for typescript. But this was eliminated by making the list of ciphers constant

2024-05-29 16:08 UTC, nick-livefront commented on apps/browser/src/vault/popup/services/vault-popup-items.service.ts
> +    this.vaultPopupListFiltersService.filters$,
This might be one of my favorite changes because I don't like it and like it. It feels kind of odd to me that the service would have an observable function but the actual implementation is exactly what we need so I'm all for it! 

The overall structure is an improvement, I like it. Let's roll. [acf4d97](https://github.com/bitwarden/clients/pull/9365/commits/acf4d9791776269fd5c6603d51a612fc3e1cdaf7)

2024-05-29 16:11 UTC, nick-livefront commented
@shane-melton I was running into an error when I added `FormBuilder` to the filter service tests. The internet lead me to adding `"jest-preset-angular/setup-jest"` to the `test.setup.ts` file. This caused some other, unrelated tests to break. I fixed them here: [820d6ab](https://github.com/bitwarden/clients/pull/9365/commits/820d6ab0e0d3710bbeefa4e7070f8c04b7feeb87) but I also pulled them into a separate PR #9412 just so they're called out separately.

2024-05-30 18:12 UTC, shane-melton reviewed
Looking great! Just a few more thoughts/questions.

2024-05-30 18:12 UTC, shane-melton commented on apps/browser/src/vault/popup/services/vault-popup-list-filters.service.ts
> +      const noFolder = folders.find((f) => f.id === null);
♻️ This no folder == null Id thing seems kind of annoying to work around, especially since its already added by the service. It's forcing us to iterate the `folders` array 2 more times here when we should just be able to append it to the end. 

The team should probably look into cleaning this up in the future; but for now this should be fine.

2024-05-30 18:12 UTC, shane-melton commented on apps/browser/src/vault/popup/services/vault-popup-list-filters.service.ts
> +  filterForm = this.formBuilder.group<PopupListFilter>(INITIAL_FILTERS);
💭 I'm kind of torn on adding the actual `FormGroup` to the service. On the one hand, it does avoid the need for a separate `updateFilters` method on the service and having to manually keep another `FormGroup` in sync; so I definitely see its value. But, it also feels unfortunate that we now have this dependency on Angular in this service AND we have to subscribe to `valueChanges` in the constructor.

2024-05-30 18:12 UTC, shane-melton commented on apps/browser/src/vault/popup/services/vault-popup-list-filters.service.ts
> +  filterForm = this.formBuilder.group<PopupListFilter>(INITIAL_FILTERS);
❓ Do we need to be concerned with reseting this `formGroup` since its living in a service that might outlive the new Vault tab and have stale values?

2024-05-30 18:12 UTC, shane-melton commented on apps/browser/src/vault/popup/services/vault-popup-list-filters.service.ts
> +      .valueChanges.subscribe(this.validateOrganizationChange.bind(this));
❓ I'm not entirely certain on the lifetime of this service, but maybe we should have a `takeUntilDestroyed()` operator here?

2024-05-30 18:12 UTC, shane-melton commented on apps/browser/src/vault/popup/services/vault-popup-list-filters.service.ts
> +  filterFunction$: Observable<(ciphers: CipherView[]) => CipherView[]> = this.filters$.pipe(
👍 I really like how this turned out actually! Fully embracing the [first class citizenship](https://en.wikipedia.org/wiki/First-class_function) of functions in JS haha

2024-05-30 18:12 UTC, shane-melton commented on apps/browser/src/vault/popup/services/vault-popup-items.service.ts
> +    this.vaultPopupListFiltersService.filters$,
Awesome, thanks for trying it out!

2024-05-30 21:03 UTC, nick-livefront commented on apps/browser/src/vault/popup/services/vault-popup-list-filters.service.ts
> +      return folders.filter((f) => orgCiphers.some((oc) => oc.folderId === f.id) || f.id === null);
I don't believe so! Removed [c3af6b1](https://github.com/bitwarden/clients/pull/9365/commits/c3af6b18179bcb5e1ad248fb91f1fca30993138b)

2024-05-30 21:12 UTC, nick-livefront commented on apps/browser/src/vault/popup/services/vault-popup-list-filters.service.ts
> +  filterForm = this.formBuilder.group<PopupListFilter>(INITIAL_FILTERS);
I can see both sides, what pushed me to move it to the service was creating a single data model that would drive the logic & the UI. When I had the `filterForm` in the component, I was writing more logic to keep the `filterForm` in sync with the `filter$` observable. 

> Do we need to be concerned with reseting this formGroup since its living in a service that might outlive the new Vault tab and have stale values?

I think that's an easy add, I added a reset to the form when the filter component is destroyed. [505e811](https://github.com/bitwarden/clients/pull/9365/commits/505e811e007f535f7f6ef53d2bb2bdbadcbcf4c5)

2024-05-30 21:12 UTC, nick-livefront commented on apps/browser/src/vault/popup/services/vault-popup-list-filters.service.ts
> +      .valueChanges.subscribe(this.validateOrganizationChange.bind(this));
👍 [51db8dc](https://github.com/bitwarden/clients/pull/9365/commits/51db8dc114c33b96e68cacc219ac32377936ae5f)

2024-05-31 17:30 UTC, shane-melton reviewed
One last small question, but I think we're pretty much there!

2024-05-31 20:24 UTC, nick-livefront commented on apps/browser/src/vault/popup/services/vault-popup-list-filters.service.ts
>        .get("organization")
👍 [f04bf5c](https://github.com/bitwarden/clients/pull/9365/commits/f04bf5ccba668db22cba88d37a1dfc300e83519e)

2024-05-31 20:27 UTC, nick-livefront commented on apps/browser/src/vault/popup/services/vault-popup-list-filters.service.ts
> +    destroyRef: DestroyRef,
Good call out, yes it does use `inject` under the hood. I was struggling to get the unit tests to run without passing the `destroyRef` manually.

Turns out that is just because the test wasn't running within the `TestBed`. Using the `new VaultPopupListFilterService(..)` syntax was the culprit. Switched `TestBed.inject(VaultPopupListFilterService)` and all is well.

[4d02197](https://github.com/bitwarden/clients/pull/9365/commits/4d0219706bb2eddcbd54a03c617512e55450acff)

2024-05-31 20:34 UTC, shane-melton approved these changes

2024-05-31 20:42 UTC, nick-livefront commented
@willmartian When you have the time could you give this a review? I made some changes here to the `ChipSelect` component.

2024-06-02 21:42 UTC, willmartian approved these changes
CL changes LGTM, thanks @nick-livefront!

2024-06-03 14:20 UTC, merged