[AC-1679] Approve all pending device authorizations
bitwarden/clients pull request #9407
Opened 2024-05-28 23:41 UTC by vincentsalucci

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-05-28 23:41 UTC, vincentsalucci commented on bitwarden_license/bit-cli/src/admin-console/device-approval/approve-all.command.ts
> +      if (pendingApprovals.length == 0) {
@eliykat I thought about returning a success here if there weren't any pending approvals: might be nicer on the automation folks. Thoughts?

2024-05-28 23:42 UTC, vincentsalucci commented on bitwarden_license/bit-cli/src/admin-console/device-approval/device-approval.program.ts
> +          (this.serviceContainer as ServiceContainer).organizationAuthRequestService,
@eliykat This seemed to be the only way I could get the service container to recognize the newly added services. Are you seeing this behavior as well?

2024-05-29 04:15 UTC, eliykat commented on bitwarden_license/bit-cli/src/admin-console/device-approval/device-approval.program.ts
> +  constructor(serviceContainer: ServiceContainer) {
You're passing in `ServiceContainer` as an argument, but not defining it as a property. Because the base class defines `this.ServiceContainer` using the OSS `ServiceContainer`, that's what the class is using throughout. You need to override the base class definition:

```suggestion
  constructor(protected serviceContainer: ServiceContainer) {
```

2024-05-29 04:15 UTC, eliykat commented on bitwarden_license/bit-cli/src/admin-console/device-approval/device-approval.program.ts
> +          (this.serviceContainer as ServiceContainer).organizationAuthRequestService,
See my other comment!

2024-05-29 06:53 UTC, eliykat requested changes
Only a few minor comments, looks good! However some manual testing will also tell us if there are any other changes needed.

2024-05-29 06:53 UTC, eliykat commented on bitwarden_license/bit-cli/src/admin-console/device-approval/approve-all.command.ts
> +        "Unauthorized Access: you do not have permission to approve pending authorization requests.",
Needs i18n. Also "Unauthorized Access:" is unnecessary in my opinion, I don't think we'd use that wording in an error toast for example.

2024-05-29 06:53 UTC, eliykat commented on bitwarden_license/bit-cli/src/admin-console/device-approval/approve-all.command.ts
> +      if (pendingApprovals.length == 0) {
I agree, I wouldn't consider this case to be an error. There's no work to do, but nothing's gone wrong.

I do wonder what we should return from this command though. e.g. the number of auth requests approved, or a list of the auth requests approved, so the user has feedback about what they've done? That would also handle this situation, because it would clearly communicate that nothing went wrong but also nothing was approved.

Please ask Priya so she can check with integration what would be useful.

2024-05-29 15:01 UTC, vincentsalucci commented on bitwarden_license/bit-cli/src/admin-console/device-approval/device-approval.program.ts
> +  constructor(serviceContainer: ServiceContainer) {
Ah. That makes sense. Thank you!

2024-05-29 16:02 UTC, vincentsalucci commented on bitwarden_license/bit-cli/src/admin-console/device-approval/approve-all.command.ts
> +        "Unauthorized Access: you do not have permission to approve pending authorization requests.",
Surprisingly we don't use i18n within the cli except for shared services that contain messages within them. However, I'm definitely not opposed to it. It'll feel cleaner in case we expand in the future.

2024-05-29 19:44 UTC, vincentsalucci commented on bitwarden_license/bit-cli/src/admin-console/device-approval/approve-all.command.ts
> +      if (pendingApprovals.length == 0) {
Checking on this!

2024-05-31 05:21 UTC, eliykat commented on bitwarden_license/bit-cli/src/admin-console/device-approval/approve-all.command.ts
> +        "Unauthorized Access: you do not have permission to approve pending authorization requests.",
I forgot we didn't have i18n in the CLI. I'd actually prefer not to introduce the pattern, the long-fabled effort to rewrite the CLI is gaining steam, so I don't think it'll be around long enough to be fully i18n'd.

2024-05-31 20:32 UTC, vincentsalucci commented on bitwarden_license/bit-cli/src/admin-console/device-approval/approve-all.command.ts
> +        "Unauthorized Access: you do not have permission to approve pending authorization requests.",
Reverted my i18n changes.

2024-05-31 20:34 UTC, vincentsalucci commented on bitwarden_license/bit-cli/src/admin-console/device-approval/approve-all.command.ts
> +      if (pendingApprovals.length == 0) {
Leaving as-is for now. Can make any requested updates once QA/Product/Integration try the command.

2024-06-02 22:11 UTC, eliykat approved these changes
Nice work, and good spot on the command names, you're right they should be kebab case.

2024-06-03 00:52 UTC, merged