[AC-2286] [Defect] - CLI: User creating a collection through the CLI does not have access to the collection
bitwarden/clients pull request #9409
Opened 2024-05-29 14:52 UTC by r-tome

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-05-30 05:21 UTC, eliykat requested changes

2024-05-30 05:21 UTC, eliykat commented on apps/cli/src/vault/create.command.ts
> +      const currentOrgUserId = users.data.find((u) => u.userId === organization?.userId)?.id;
I don't think we should have to GET all organizationUsers for the organization just to get the current user's orgUserId. I was thinking we could include this in sync data, e.g. `Organization.organizationUserId`. That would also be useful in the `group-add-edit.component.ts` where I had to write similarly awkward filtering logic.

The only other alternative I can think of is to create a new endpoint where you can get by UserId + OrgId, but I'm not sure how you'd structure that in a nice RESTful way.

2024-05-30 05:21 UTC, eliykat commented on apps/cli/src/admin-console/models/request/organization-collection.request.ts
> +  users: SelectionReadOnly[];
You've added this to the CLI request model, but it's not actually used in the command. Adding this here would allow the user to specify collection-user assignments in their CLI command (which is nice additional functionality), but you then ignore it in favour of the default assignment.

I suggest that you keep this here, and use any value supplied by the user, but fall back to the default assignment if no value is provided.

2024-05-30 05:21 UTC, eliykat commented on apps/cli/src/vault/create.command.ts
> +      request.users = [new SelectionReadOnlyRequest(currentOrgUserId, false, false, true)];
To follow on from my previous comment, this would be more like

```
      request.users = req.users ?? [new SelectionReadOnlyRequest(currentOrgUserId, false, false, true)];
```

2024-05-30 05:21 UTC, eliykat commented on apps/cli/src/admin-console/models/request/organization-collection.request.ts
> +  users: SelectionReadOnly[];
Also, please check what other commands this model is used by. Do any other commands need updating to feed this new property through?

2024-05-30 13:40 UTC, r-tome commented on apps/cli/src/vault/create.command.ts
> +      const currentOrgUserId = users.data.find((u) => u.userId === organization?.userId)?.id;
I've included it in the sync data here https://github.com/bitwarden/server/pull/4142

2024-05-31 01:48 UTC, eliykat submitted a review, later dismissed

2024-06-06 20:47 UTC, gbubemismith submitted a review, later dismissed
Vault changes look good 👍

2024-06-07 19:07 UTC, vincentsalucci commented
@gbubemismith Had to fix a failing deserialization test. No other changes have been made 👍

2024-06-07 19:07 UTC, vincentsalucci approved these changes
Approving on behalf of @eliykat

2024-06-07 19:07 UTC, gbubemismith approved these changes

2024-06-07 19:14 UTC, merged