[AC-2509] add member access component
bitwarden/clients pull request #9411
Opened 2024-05-29 15:29 UTC by aj-rosado

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/AC-2509
## 📔 Objective
This focus on the visual components and layouts and not on the service layer of the Member Access Report page.

Add the MemberAccessReportComponent on the `bitwarden_license`, it is using static data for now.
Also added navigation to the component on the `organization-reporting-routing`
Created `member-access-report.service.ts` that has a temporary method to return static data

## 📸 Screenshots
### Light Theme
<img width="1920" alt="image" src="https://github.com/bitwarden/clients/assets/109146700/d3c25951-e7b2-4cf9-a0bb-3d192be1f08c">

### Dark Theme
<img width="962" alt="image" src="https://github.com/bitwarden/clients/assets/109146700/a30ae196-3e73-4f2d-8215-2872b00e36f0">

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-24 13:41 UTC, djsmith85 requested changes
Report looks good just some small items

:thought_balloon: Maybe if we made the member-access-report standalone, it would simplfy and centralize the routing and guarding as we wouldn't need a specific reports-reporting.module for import.

2024-06-24 13:41 UTC, djsmith85 commented on bitwarden_license/bit-web/src/app/tools/reports/member-access-report/member-access-report.component.html
> +  <app-header>
❓  Does this need to be wrapped within an ng-container?

Other report pages are structured as:

```
<app-header></app-header>

<bit-container>
 table content here...
</bit-container>
```

2024-06-24 20:07 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/reporting/organization-reporting-routing.module.ts
> +                "../../../../../../../bitwarden_license/bit-web/src/app/tools/reports/reports.module"
To expand slightly, see [OrganizationRoutingModule](https://github.com/bitwarden/clients/blob/main/apps/web/src/app/admin-console/organizations/organization-routing.module.ts#L1) (OSS) and [OrganizationsRoutingModule](https://github.com/bitwarden/clients/blob/main/bitwarden_license/bit-web/src/app/admin-console/organizations/organizations-routing.module.ts#L1) (BL). They're both standard routing modules, but it shows how you can declare a separate routing module in the Bitwarden-licensed code and have it "overlap" with your standard routing module (i.e. even though their paths partially overlap, Angular still resolves them in order).

Also note the [order that they are registered in](https://github.com/bitwarden/clients/blob/main/bitwarden_license/bit-web/src/app/app.module.ts#L41), which might be a gotcha.

2024-06-26 14:13 UTC, aj-rosado commented on bitwarden_license/bit-web/src/app/tools/reports/reports-routing.module.ts
> +    canActivate: [IsEnterpriseOrgGuard],
Created a new task under this epic to follow this work

2024-06-26 14:13 UTC, aj-rosado commented on bitwarden_license/bit-web/src/app/tools/reports/member-access-report/member-access-report.component.html
> +  <app-header>
not necessary, removed

2024-06-26 14:17 UTC, aj-rosado commented on apps/web/src/app/admin-console/organizations/reporting/organization-reporting-routing.module.ts
> +                "../../../../../../../bitwarden_license/bit-web/src/app/tools/reports/reports.module"
Thank you for the guidance!

I have followed @djsmith85 suggestion and removed the `reporting-route` and `module` on the `bitwarden-license` as the `member-access-report` is a standalone component and added it to the existing `organizations-routing.module`.

Removing all the imports from BL on the OSS

2024-06-26 14:21 UTC, djsmith85 approved these changes

2024-06-26 22:56 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/organizations/organizations-routing.module.ts
> +        canActivate: [AuthGuard],
I think you probably want an `OrganizationPermissionsGuard` on this, probably referencing `org.canAccessReports`.

2024-06-26 23:02 UTC, eliykat requested changes

2024-06-26 23:02 UTC, eliykat commented on bitwarden_license/bit-web/src/app/tools/reports/member-access-report/member-access-report.component.ts
> +      takeUntil(this.destroy$),
This isn't doing anything - piping just returns a new observable, it's neither assigned anywhere nor subscribed to anywhere.

In general with the boilerplate search logic, it seems like you're following what's in other components, but (at least in AC's components), this is out of date and/or broken. A much simpler pattern can be seen in [new-base.people.component.ts](https://github.com/bitwarden/clients/blob/main/apps/web/src/app/admin-console/common/new-base.people.component.ts#L137-L140):

```ts
// connect the search input to a FormControl
protected searchControl = new FormControl("", { nonNullable: true });

constructor() {
    // Connect the search input to the table dataSource filter input
    this.searchControl.valueChanges
      .pipe(debounceTime(200), takeUntilDestroyed())
      .subscribe((v) => (this.dataSource.filter = v));
  }
```

2024-06-26 23:02 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/organizations/organizations-routing.module.ts
> +        children: [
Also, does this need to be feature flagged? It looks like a WIP.

2024-06-27 10:48 UTC, aj-rosado commented on bitwarden_license/bit-web/src/app/admin-console/organizations/organizations-routing.module.ts
> +        children: [
The feature flag is on the `IsEnterpriseGuard` as it was added just for this.

2024-07-01 02:57 UTC, eliykat commented on bitwarden_license/bit-web/src/app/admin-console/organizations/organizations-routing.module.ts
> +        children: [
Sure - for next time, we have `FeatureFlagGuard` so you don't have to re-implement this functionality yourself.

2024-07-01 04:23 UTC, eliykat requested changes
The main request here is re: `canAccessReports`, the other comments are non-blocking but just stuff I noticed.

2024-07-01 04:23 UTC, eliykat commented on libs/common/src/admin-console/abstractions/organization/organization.service.abstraction.ts
> +}
I don't think there's any benefit to defining this new function when you can just access `org.canAccessReports` directly. The other functions here like `canAccessOrgAdmin` aggregate multiple permissions, but this doesn't.

So in the routing module:

```ts
data: { organizationPermissions: org => org.canAccessReports }
```

2024-07-02 00:54 UTC, eliykat submitted a review, later dismissed

2024-07-02 09:31 UTC, djsmith85 approved these changes

2024-07-02 19:54 UTC, eliykat requested changes
We just updated the `OrganizationPermissionsGuard` to use functional route guards: https://github.com/bitwarden/clients/pull/9631

This has been merged, which is probably causing your conflict. It also means you need to update your use of the route guard. It is now a function that takes the callback as a parameter, e.g. `OrganizationPermissionsGuard(org => org.canAccessReports)`. You no longer use the `data` property.

Sorry for the bad timing!

2024-07-03 12:02 UTC, djsmith85 approved these changes

2024-07-03 20:11 UTC, eliykat approved these changes
Thanks @aj-rosado !

2024-07-09 17:36 UTC, merged