[SM-1292] Add secret view dialog
bitwarden/clients pull request #9445
Opened 2024-05-30 19:40 UTC by Thomas-Avery

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/SM-1292

## 📔 Objective

The objective of this PR is to add a secret view dialog for a read-only view of a secret.

## 📸 Screenshots

### Before
![image](https://github.com/bitwarden/clients/assets/43214426/54620549-e5b2-4b14-a255-fc699f3c9404)

### After

![image](https://github.com/bitwarden/clients/assets/43214426/3299f180-6641-4818-868c-ed3e51ac6bfc)

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-01 20:00 UTC, coltonhurst requested changes
One real comment, other than that it looks great. Thanks!

2024-06-01 20:00 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-view-dialog.component.html
> +    [title]="'viewSecret' | i18n | uppercase"
Any reason we are making this uppercase? I believe Create and Edit for secrets (+ edit for projects) aren't this way, unless that's going to be changed?

2024-06-01 20:00 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.ts
> +  protected editSecret(secret: SecretListView) {
I was trying to think if there was a better name for this to convey the full scope of what could happen, but I can't think of anything at the moment. I thought about `clickSecret` but that's not descriptive either. 🤦‍♂️ So all good, just was mentioning I thought about it.

2024-06-03 15:08 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-view-dialog.component.html
> +    [title]="'viewSecret' | i18n | uppercase"
It is what the design calls for. Currently, all of those mentioned are upper case in our design documents. 

Would you like me to update the create and edit in this PR?

2024-06-03 15:23 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.ts
> +  protected editSecret(secret: SecretListView) {
At one point I had `handleSecretInteraction` but it seemed too wordy, so I went with this.

Open to suggestions. Since this isn't a public method, we only have to convey things internal to this component's context.

2024-06-03 19:33 UTC, coltonhurst commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.ts
> +  protected editSecret(secret: SecretListView) {
No worries, feel free to leave as is, thank you 👍

2024-06-03 19:42 UTC, coltonhurst submitted a review, later dismissed

2024-06-04 19:19 UTC, coltonhurst approved these changes

2024-06-07 15:32 UTC, merged