Autofill/pm 8510 implement collect page details observable
bitwarden/clients pull request #9452
Opened 2024-05-31 06:36 UTC by cagonzalezcs

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-05-31 13:40 UTC, jprusik submitted a review, later dismissed

2024-05-31 16:11 UTC, shane-melton requested changes
This looks awesome! Thanks again for putting it together! 

I do see one potential issue in the current-tab component and had a question regarding some retry logic that was removed.

2024-05-31 16:11 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault/current-tab.component.ts
> +    this.autofillService
⚠️ I believe we'll need to keep track of this subscription so we can unsubscribe/resubscribe to a new tab every time this `load()` method is called. Otherwise, we'll end up with multiple subscriptions to potentially different tabs all trying to update `this.pageDetails`.

2024-05-31 16:11 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault/current-tab.component.ts
> -    this.initPageDetailsTimeout = window.setTimeout(() => {
❓ I believe we have this timeout to re-send the `BrowserApi.tabSendMessage` in case we manage to send the message too early before the tab is ready. I'm not 100% sure if we still need this, but it does look like a change in behavior now that we're only attempting to send the tab message a single time without any retry with this PR.

2024-05-31 16:11 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault/current-tab.component.ts
> +    this.autofillService
Oh, you already do something similar in the View component -- we should be able to reuse that pattern here.

2024-05-31 16:25 UTC, cagonzalezcs commented on apps/browser/src/vault/popup/components/vault/current-tab.component.ts
> +    this.autofillService
Good call, added this pattern to the current tab component as well.

2024-05-31 16:31 UTC, cagonzalezcs commented on apps/browser/src/vault/popup/components/vault/current-tab.component.ts
> -    this.initPageDetailsTimeout = window.setTimeout(() => {
So the reason why this was originally implemented we not because the tab might not be ready to send details, but rather because the broadcasterService might not be initialized by the time the `collectPageDetailsResponse` was to the current tab component. 

Due to how the current tab component is initialized, you pretty much will always have your current tab loaded before triggering the page details collection. The only way this seems to different is within the Firefox sidebar (which doesn't seem to update on window or tab change, as the view component does).

In either regard, because the current tab component initializes when opening the popup, the only way that this might run into an issue is if the tab is taking a very very long time to load. In which case, you'd have the same issue with this older method, as you collect an empty set of page details... 

Definitely give it a shot locally and let me know if some kind of issue persists though, but this new approach makes this "pulsed methodology" for collection of page details obsolete.

2024-05-31 16:32 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault/current-tab.component.ts
> -    this.initPageDetailsTimeout = window.setTimeout(() => {
Ah, I misunderstood the original purpose of that timeout, thanks for the clarification!

2024-05-31 16:38 UTC, shane-melton approved these changes

2024-06-06 20:43 UTC, jprusik commented
LGTM and BIT run passed:
https://github.com/bitwarden/browser-interactions-testing/actions/runs/9405418593

2024-06-06 20:43 UTC, jprusik submitted a review, later dismissed

2024-06-07 13:35 UTC, jprusik approved these changes

2024-06-07 19:41 UTC, shane-melton approved these changes

2024-06-11 20:00 UTC, merged