[PM-8520] [Beeep] Rust Fido2/CTAP2 2FA for Mac/Linux Desktop
bitwarden/clients pull request #9456
Opened 2024-05-31 13:50 UTC by quexten

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-8520

Replaces:
https://github.com/bitwarden/clients/pull/6375

## 📔 Objective

Implement fido2 2FA (not prf yet) 2fa sign in for Desktop using USB Fido2 authenthicators (Yubikey, etc). For now all implementations use `webauthn-rs`, but for windows/mac we can switch to native bindings later on, that do not require UI support. This is switched out at compile-time.

### Points for discussion

In this Beeep, I also wanted to somewhat explore the Rust-typescript interaction. Webauthn-authenticators-rs calls some functions that we can implement, such as on pin-requirement, on touch-requirement, device missing, and so on.

Here, the idea is to pass in thread safe callback functions. These can be called from within the rust code. An (unexplored) alternative would be having an ipc implementation available from within rust that hooks into the messagingservice/ipc of the typescript code in general, since this might be useful in other, future, native rust code. But this seems out of scope for this PR.

## 📸 Screenshots

https://github.com/bitwarden/clients/assets/11866552/ed3c7609-90d7-468c-a9a9-62d7d09bbfb1

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-02 01:16 UTC, wrinkledeth commented
Wow, so will we have a Mac desktop app soon?

2024-06-02 08:48 UTC, quexten commented
@wrinkledeth what do you mean? The mac desktop app has been available for years?

2024-06-03 06:24 UTC, brunescio commented
I guess they mean will we have FIDO2 support on the Mac app? That's what I would like to know, anyway.

2024-06-03 09:06 UTC, quexten commented
Yes, that's what the PR implements.

2024-06-07 10:02 UTC, quexten commented
@dani-garcia @coroiu Added both of you to the reviers because I feel especially the rust code could use some input from experienced rust users, since this is the first time using callbacks in the desktop_native rust code. I also want to make sure that the interface of the webauthn function makes sense, to the extend that we can later implement mac/windows native webauthn/passkey client bindings instead of using webauthn-authenticators-rs, to give us plaform ui support and other transports (caBLE/QR).

2024-06-10 10:03 UTC, Hinton requested changes
Marking a request for changes to ensure this isn't accidentally merged since it would most likely break any linux distro but the most recent ones, due to missmatch of glibc. There are a few other concerns and codeowners needs to be handled.

2024-06-10 10:10 UTC, quexten commented on apps/desktop/desktop_native/Cargo.toml
> +openssl-src = "300.3.1"
Sadly, webauthn-rs does not have a pure rust backend at the moment ( https://github.com/kanidm/webauthn-rs/issues/423 ), one alternative could be to compile against just libfido2, but I'm not sure this would be easier to cross-compile. Otherwise I'm happy to make this feature entirely compile-time toggleable, and we only ship it where it's not a pain to cross-compile.

2024-06-10 10:15 UTC, quexten commented on apps/desktop/src/platform/preload.ts
I will note that the plan is to drop this on mac os as soon as native bindings are written for it, and then we will also not need openssl on mac. On Linux we don't have an alternative in the foreseeable future. So again, I would propose to make this compile-time toggleable, and we ship it where possible.

2024-06-10 12:47 UTC, quexten commented on .github/workflows/build-desktop.yml
> +    runs-on: ubuntu-24.04
**question:** The comment focuses on snap specifically, and also mentions that this is until ubuntu-24.04 releases (which is now the case). I did not look too deeply into which distro has which glibc, but if we want to ensure no issues, we could also again use a compile time flag, that enables this on the packages where we know the glibc version (snap with core24, flatpak), until we know that most distros support the glibc version we compiled against.

By the way, do we have a minimum supported version/age for distros that we need to support?

2024-06-10 15:35 UTC, Hinton commented on .github/workflows/build-desktop.yml
> +    runs-on: ubuntu-24.04
We have a native node-argon dependency which needs to be built on ubuntu-20.04 for maximum compatibility since it's not using musl as a target, and will be linked to the glibc version.

2024-06-11 11:56 UTC, coroiu commented on apps/desktop/src/platform/preload.ts
@quexten How would you feel about trying to get something standardized in the Linux community instead?

2024-06-11 12:54 UTC, coroiu requested changes
This is not a full review, but wanted to bring up some initial issues and questions, the most important one being CTAP1 support

2024-06-11 12:54 UTC, coroiu commented on apps/desktop/desktop_native/Cargo.toml
> +webauthn-rs = "0.5.0"
question: These are using the MPL 2.0 license which seems to be ok? I haven't worked with this license before

2024-06-11 12:54 UTC, coroiu commented on apps/desktop/desktop_native/src/passkeyclient/ctap2.rs
> +    }
question: Do we expect any of these to be called? What happens if they are called? Will the user get any feedback/error messages?

2024-06-11 12:54 UTC, coroiu commented on apps/desktop/desktop_native/Cargo.toml
> +webauthn-authenticator-rs = { version = "0.5.0", features = ["usb"] }
regression/issue?: according to https://docs.rs/webauthn-authenticator-rs/0.5.0/webauthn_authenticator_rs/#fido--ctap-version-support `webauthn_authenticator_rs` does not support CTAP1 (i.e. older U2F keys), which I think that we still support, meaning that this would lock out U2F users. Is this correct/intentional?

2024-06-11 18:39 UTC, jlf0dev commented on apps/desktop/desktop_native/Cargo.toml
> +webauthn-authenticator-rs = { version = "0.5.0", features = ["usb"] }
Do we still support older U2F keys? [This code](https://github.com/bitwarden/server/blob/59fa6935b48c9947e09e9a5cb944ae2b1924533c/src/Core/Entities/User.cs#L144) has always made me think we dropped support.

2024-06-12 07:07 UTC, coroiu commented on apps/desktop/desktop_native/Cargo.toml
> +webauthn-authenticator-rs = { version = "0.5.0", features = ["usb"] }
I think we dropped support for U2F and migrated to WebAuthn for the API. But WebAuthn itself has backwards compatibility with U2F keys, which I think we still support:

https://github.com/bitwarden/server/blob/576b78d739cea27479167ca376d404651546ad13/src/Core/Auth/Identity/WebAuthnTokenProvider.cs#L57

2024-07-05 11:51 UTC, regismesquita commented
Hi all, Any idea if we would have security key support for desktop mac on the foreseeable future? It has been a long time since the PR #6375 and I am not sure of what is the current bitwarden expectation on supporting this.

I am getting errors from running old builds that I have manually added support for this feature and I kinda need to update , so I am unsure if I should try adding the feature again on a newer build or if it is close to being released.

2024-07-08 07:50 UTC, coroiu commented
@regismesquita I think you can expect it fairly soon (@quexten know the timeline better than me). Unrelated work on the passkey-provider side is also doing work that can be used to speed up native FIDO2 integration on macOS, so we are making progress on multiple fronts :)

2024-08-21 10:23 UTC, closed without merging

2024-08-21 10:23 UTC, quexten commented
Most likely taking another look from scratch here. Closing for now.