Autofill/pm 8518 autofill scripts do not inject into sub frames on install
bitwarden/clients pull request #9459
Opened 2024-05-31 15:21 UTC by cagonzalezcs

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-8518

## 📔 Objective

An issue exists where the content scripts that facilitate autofill behavior are not injected into subframes of an existing website when the extension is first installed. This work introduces a methodology for querying subframes of a tab to allow for injection of content scripts into those existing pages.

This work splits from the larger set of changes present in https://github.com/bitwarden/clients/pull/8431  with the hope that this presents as a smaller set of changes for the Platform team to review.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-05-31 15:23 UTC, cagonzalezcs commented on apps/browser/src/platform/browser/browser-api.ts
> +        resolve(response);
Note: This will be used in https://github.com/bitwarden/clients/pull/8431 to ensure we can get a response back the tab that we sent a message to.

No calls within the codebase currently anticipate this response, so this doesn't affect behavior in any significant manner at the moment.

2024-05-31 21:03 UTC, justindbaur requested changes

2024-05-31 21:03 UTC, justindbaur commented on apps/browser/src/platform/browser/browser-api.ts
> +    return new Promise<any>((resolve) => {
Can we avoid the `any` by adding a second, optional, generic like `TResult = unknown`?

2024-05-31 21:15 UTC, cagonzalezcs commented on apps/browser/src/platform/browser/browser-api.ts
> +    return new Promise<any>((resolve) => {
Good call, I've updated this with a generic as suggested.

2024-05-31 21:17 UTC, justindbaur approved these changes

2024-06-03 13:37 UTC, jprusik commented
BIT run:
https://github.com/bitwarden/browser-interactions-testing/actions/runs/9351222159

2024-06-03 13:43 UTC, jprusik commented on apps/browser/src/manifest.v3.json
> +    "webNavigation"
Is this new permission going to prompt/notify users?

2024-06-03 13:52 UTC, jprusik approved these changes
One question on permissions, but otherwise LGTM

2024-06-03 13:54 UTC, cagonzalezcs commented on apps/browser/src/manifest.v3.json
> +    "webNavigation"
Yes it will, though we already use this permission for mv2.

2024-06-03 13:55 UTC, cagonzalezcs commented on apps/browser/src/manifest.v3.json
> +    "webNavigation"
https://developer.chrome.com/docs/extensions/reference/permissions-list

2024-06-06 17:37 UTC, jprusik commented on apps/browser/src/manifest.v3.json
> +    "webNavigation"
so is the expected UX:

- they might get a prompt if they installed MV3 before upgrading to the release version including these changes
- they won't get a prompt if they update from MV2 to the release version that includes this

2024-06-07 13:51 UTC, cagonzalezcs commented on apps/browser/src/manifest.v3.json
> +    "webNavigation"
That should be the case.

2024-06-11 20:50 UTC, merged