Fix tde offboarding
bitwarden/clients pull request #9480
Opened 2024-06-03 09:48 UTC by quexten

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-5963
https://github.com/bitwarden/server/pull/4144

## 📔 Objective

Fix the TDE offboarding flow to not mess up encryption keys.

## 📸 Screenshots
![image](https://github.com/bitwarden/clients/assets/11866552/a1c4f7fd-b522-4352-9356-aa5984430eb4)

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-03 12:18 UTC, jlf0dev commented on libs/common/src/services/api.service.ts
> +  }
Do you think it makes sense to put this in `DevicesApiService`? I know its more TDE related than devices, but I think the `DeviceTrustService` should be responsible for building the request and calling the api service.

Also:
```suggestion
  putUpdateTdeOffboardingPassword(request: UpdateTdeOffboardingPasswordRequest): Promise<void> {
    return this.send("PUT", "/accounts/update-tde-offboarding-password", request, true, false);
  }
```

2024-06-03 12:18 UTC, jlf0dev commented on libs/auth/src/common/models/domain/user-decryption-options.ts
> +  /** True if tde is disabled but user has not set a master password. yet */
```suggestion
  /** True if tde is disabled but user has not set a master password yet. */
```

2024-06-03 12:18 UTC, jlf0dev commented on libs/angular/src/auth/components/sso.component.ts
> +    }
If both `isTdeOffboarding` and `hasManageResetPasswordPermission` are both true, I think the tde offboarding should take priority right? If so we might want to move this above the previous if.

2024-06-03 15:26 UTC, quexten commented on libs/angular/src/auth/components/sso.component.ts
> +    }
Agreed, implemented in [409d9d5](https://github.com/bitwarden/clients/pull/9480/commits/409d9d554e34eaa89690bab60d3f8fd9a70f5bca)

2024-06-03 17:36 UTC, MGibson1 approved these changes
Are there related mobile changes for this?

I also agree that it would be better to avoid expanding the API class, but not going to push for it. If it fits in your devices api service, great. If not, this is probably the right place for now.

2024-06-03 19:04 UTC, micahblut commented
For the message, can we say something more comprehensible to the user.
"Your organization has updated your decryption options. Please set a master password to access your vault."

2024-06-04 11:04 UTC, quexten commented on libs/common/src/services/api.service.ts
> +  }
`DeviceTrustService` feels more like it's about managing devices, and their trust, themselves (and looking into it, it only is concerned with that) rather than being about functionality around the TDE feature. Maybe a refactor into "TrustedDeviceEncryptionFeatureService" or something along the lines would make sense. I'll keep it in apiservice for now.

2024-06-04 12:53 UTC, quexten commented
> Are there related mobile changes for this?

Good catch, tracking in https://bitwarden.atlassian.net/browse/PM-8564

2024-06-11 14:29 UTC, jlf0dev requested changes
got some tests failing :(

2024-06-11 16:12 UTC, quexten commented
> got some tests failing :(

Apologies, I'll make a note to let the tests complete and verify them before re-requesting a review. Should be fixed now.

2024-06-11 18:00 UTC, jlf0dev approved these changes
No worries it happens, thats why we have the CI builds 👍

2024-07-23 10:28 UTC, quexten commented
Upon the second round, this came back good to go from QA, just needed to resolve merge conflicts.

2024-07-23 11:11 UTC, quexten commented
Not sure why the completely unrelated setTimeout test fails (even on multiple runs), because it's 1.) unrelated and 2.) does not fail locally. I assume it's something with the github runner the build gets assigned to.

2024-07-23 11:39 UTC, quexten commented
Seems to have passed after re-running another time.

2024-07-24 15:42 UTC, jlf0dev approved these changes

2024-08-01 23:48 UTC, MGibson1 approved these changes

2024-08-01 23:48 UTC, merged