[AC-1452] Restrict access to 'Organization Info' and 'Two-Step Login' settings pages with a permission check
bitwarden/clients pull request #9483
Opened 2024-06-03 12:09 UTC by r-tome

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/AC-1452

## 📔 Objective

Even though the menu items were hidden, Admins and Custom users could still access the 'Organization Info' and 'Two-Step Login' settings pages by manually entering the URL in the browser. This is fixed by checking the necessary permissions on the route guard.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-03 14:42 UTC, addisonbeck approved these changes

2024-06-14 03:59 UTC, eliykat commented
@addisonbeck this will conflict with your PR #9631, how do you want to handle it? Maybe merge yours first, then if you don't mind updating this to match, I can approve it?

2024-06-14 16:26 UTC, addisonbeck requested changes
Pending updates

2024-07-03 16:45 UTC, addisonbeck approved these changes

2024-07-03 16:45 UTC, merged