[AC-2721][Defect] Apply Subscription Status Updates in Provider Subscription details
bitwarden/clients pull request #9484
Opened 2024-06-03 12:43 UTC by cyprain-okeke

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/AC-2721
## 📔 Objective

This  change is to ensure we are able to display the right banner on the provider-subscription page base of the status of the subscription.

## 📸 Screenshots

<img width="1728" alt="Screenshot 2024-06-03 at 12 57 02" src="https://github.com/bitwarden/clients/assets/108260115/64934dfc-d2e6-4bae-aa23-0c8bf5011fe3">
<img width="1728" alt="Screenshot 2024-06-03 at 13 43 00" src="https://github.com/bitwarden/clients/assets/108260115/4723c9ad-1a7f-473c-a2f3-474bbdadc11f">

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-03 13:51 UTC, addisonbeck submitted a review, later dismissed

2024-06-03 17:51 UTC, amorask-bitwarden requested changes
I think we're missing the option that manages when the subscription is "past_due". It's shown in the other `subscription-status.component.ts` file [here](https://github.com/bitwarden/clients/blob/main/apps/web/src/app/billing/organizations/subscription-status.component.ts#L93-L127), but it will require you to add the Suspension Date to the provider subscription response.

You see how to calculate the Suspension Date if you follow the Get Subscription endpoint's controller.

2024-06-05 19:40 UTC, amorask-bitwarden approved these changes

2024-06-06 14:52 UTC, addisonbeck approved these changes

2024-06-06 14:53 UTC, merged