Remove approve device logins and enable it by default
bitwarden/clients pull request #9495
Opened 2024-06-04 12:05 UTC by quexten

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-4139

## 📔 Objective

Remove login-with-device setting and enable it by default.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-06 17:24 UTC, rr-bw requested changes
Looks good. I think you can also remove the following in Desktop `messages.json`:

```json
"approveLoginRequestDesc": {
    "message": "Use this device to approve login requests made from other devices."
  },
```

2024-06-07 10:33 UTC, quexten commented
Good catch, removed the unused i18n string.

2024-06-10 13:14 UTC, rr-bw approved these changes

2024-06-11 17:59 UTC, shane-melton approved these changes
Vault change looks good!

2024-06-13 18:05 UTC, merged