[PM-6789] finish key rotation distribution and fix legacy user
bitwarden/clients pull request #9498
Opened 2024-06-04 14:55 UTC by jlf0dev

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-6789
## 📔 Objective

Fixes legacy user migration by using the legacy key for private key re-encryption.

I took the chance to finish distributing key rotation logic to each domain using an interface.
## 📸 Screenshots

https://github.com/bitwarden/clients/assets/24985544/48c0d98f-4625-4de5-8f6e-7f634f2568ea

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-07 07:36 UTC, coroiu approved these changes
Platform changes look good, haven't reviewed the other files

2024-06-10 13:39 UTC, Jingo88 submitted a review, later dismissed

2024-06-10 17:46 UTC, JaredSnider-Bitwarden reviewed
Really nice changes! 2 questions below 👇

2024-06-10 17:46 UTC, JaredSnider-Bitwarden commented on libs/common/src/platform/services/crypto.service.ts
> +    return this.cipherDecryptionKeys$(userId, true).pipe(map((keys) => keys?.orgKeys));
Question: what are the implications of changing all `orgKeys$` retrievals to have legacy support?

2024-06-10 17:46 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/key-rotation/user-key-rotation.service.ts
> +    // TODO: Add device trust rotation support to the user key rotation endpoint
Do we have a tech debt item to track this?

2024-06-11 12:57 UTC, jlf0dev commented on libs/common/src/platform/services/crypto.service.ts
> +    return this.cipherDecryptionKeys$(userId, true).pipe(map((keys) => keys?.orgKeys));
We've actually had legacy support for `orgKey` operations this whole time, albeit [built into the model itself](https://github.com/bitwarden/clients/blob/f059d136b22749821a0d9263719ed35a1cdbca49/libs/common/src/vault/services/cipher.service.ts#L1158). If we don't add legacy support here then legacy user migration will break since they don't have a user key to decrypt org key with.

2024-06-11 17:55 UTC, jlf0dev commented on apps/web/src/app/auth/key-rotation/user-key-rotation.service.ts
> +    // TODO: Add device trust rotation support to the user key rotation endpoint
yep, added!

2024-06-11 17:57 UTC, JaredSnider-Bitwarden approved these changes
Excellent work!

2024-06-11 20:40 UTC, Jingo88 approved these changes

2024-06-11 21:04 UTC, audrey-jensen approved these changes
No blockers, and the tools integration is pretty straightforward.

2024-06-11 21:04 UTC, audrey-jensen commented on libs/common/src/platform/abstractions/crypto.service.ts
> +   */
⛏️ Present tense is preferable to future tense.
🎨 Ideally, observables should state when they emit/complete.

2024-06-12 16:01 UTC, jlf0dev commented on libs/auth/src/common/abstractions/user-key-rotation-data-provider.abstraction.ts
> +   */
thanks - updated!

2024-06-12 16:01 UTC, jlf0dev commented on libs/auth/src/common/abstractions/user-key-rotation-data-provider.abstraction.ts
> +export interface UserKeyRotationDataProviderAbstraction<
yep, fixed and renamed!

2024-06-12 16:01 UTC, jlf0dev commented on libs/auth/src/common/abstractions/user-key-rotation-data-provider.abstraction.ts
> +  T extends { id: string } | { organizationId: string },
Nice suggestion, went with #1

2024-06-12 16:07 UTC, audrey-jensen submitted a review, later dismissed

2024-06-12 17:49 UTC, JaredSnider-Bitwarden approved these changes

2024-06-12 20:48 UTC, vincentsalucci reviewed
Reviewed AC owned files 👍

2024-06-13 07:41 UTC, coroiu commented on libs/common/src/platform/abstractions/crypto.service.ts
> +   */
The helper just gets its lifetime from `stateProvider.getUser` so you should be able to just refer to the state provider documentation

2024-06-13 07:41 UTC, coroiu commented on libs/common/src/platform/abstractions/crypto.service.ts
> +   */
@justindbaur tagging you here since you wrote the helper

2024-06-13 07:42 UTC, coroiu approved these changes

2024-06-13 13:58 UTC, vincentsalucci approved these changes

2024-06-13 14:30 UTC, Jingo88 submitted a review, later dismissed

2024-06-13 15:40 UTC, audrey-jensen commented on libs/common/src/platform/abstractions/crypto.service.ts
> +   */
I mean from an application perspective. The folks consuming the services shouldn't have to trace back through a state provider to figure out what calls `update`.

2024-06-14 06:32 UTC, coroiu commented on libs/common/src/platform/abstractions/crypto.service.ts
> +   */
Yeah, my comment was for @jlf0dev, as in: you don't need to refer to platform to write this comment, the state provider documentation should be enough :) And the comment could in turn also refer to the state provider docs for information about when this will emit/complete (otherwise we'll be duplicating those docs everywhere)

Ideally the platform team should've already documented  🤷‍♂️

2024-06-18 16:00 UTC, JaredSnider-Bitwarden approved these changes

2024-06-18 17:47 UTC, Jingo88 approved these changes

2024-06-18 18:12 UTC, audrey-jensen approved these changes

2024-06-18 18:27 UTC, audrey-jensen requested changes
Sorry, just noticed a problem on the RC PR that also applies to this one.

2024-06-18 18:27 UTC, audrey-jensen commented on libs/common/src/tools/send/services/send.service.spec.ts
> +    it("throws if the original user key is null", async () => {
⚠️ The return value of `getRotatedData` is no longer tested. Please restore that test.

2024-06-18 18:34 UTC, jlf0dev commented on libs/common/src/tools/send/services/send.service.spec.ts
> +    it("throws if the original user key is null", async () => {
Please see bf0a7f6a2c0732ab8c96acd516beaeea8ba0ef5f, if this is sufficient I can cherry pick it over

2024-06-18 18:37 UTC, audrey-jensen submitted a review, later dismissed

2024-06-18 18:37 UTC, audrey-jensen commented on libs/common/src/tools/send/services/send.service.spec.ts
>        sendService.replace(null);
```suggestion
      async sendService.replace(null);
```

2024-06-18 18:42 UTC, jlf0dev commented on libs/common/src/tools/send/services/send.service.spec.ts
>        sendService.replace(null);
Updated!

2024-06-18 18:42 UTC, audrey-jensen approved these changes

2024-06-18 18:43 UTC, audrey-jensen commented on libs/common/src/tools/send/services/send.service.spec.ts
> +    it("throws if the original user key is null", async () => {
That works! You don't need to pull the `async` bit into this PR. :)

2024-06-18 20:02 UTC, addisonbeck approved these changes

2024-06-19 07:05 UTC, coroiu approved these changes

2024-06-19 18:38 UTC, JaredSnider-Bitwarden approved these changes

2024-06-20 15:36 UTC, Jingo88 approved these changes

2024-06-20 15:36 UTC, merged