Creating a landing page for SM, where user can request access from ad…
bitwarden/clients pull request #9504
Opened 2024-06-04 18:39 UTC by cd-bitwarden

…mins

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/SM-1211

## 📔 Objective

Create a landing page for Secrets Manager inside of Password Manager's sidebar, redirect to a request access page if the user logged in isn't the admin, redirect to create org if they aren't a part of any org, and redirect to the subscription page in admin console if they are the org admin.

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-07 17:12 UTC, rr-bw approved these changes
Approved for Auth

2024-06-07 17:28 UTC, rr-bw commented on apps/web/src/app/layouts/product-switcher/navigation-switcher/navigation-switcher.component.html
> +  ></section>
I'm not sure what's happening here. Looks like an empty section?

2024-06-11 13:58 UTC, willmartian reviewed
Rather than adding the landing page components to `apps/web/src/app/shared/components/`, what do you think about creating `apps/web/src/app/secrets-manager/`, and then adding SM as the code owner of that folder?

2024-06-11 17:15 UTC, cd-bitwarden commented on apps/web/src/app/layouts/product-switcher/navigation-switcher/navigation-switcher.component.html
> +  ></section>
The purpose is to have a solid line above the list of products :) however, this made me notice that it shouldn't be set to *ngIf="true" it should only be visible if there are products in the list. Thank you!

2024-06-14 20:00 UTC, Thomas-Avery requested changes

2024-06-17 15:25 UTC, mzieniukbw requested changes

2024-06-17 15:25 UTC, mzieniukbw commented on apps/web/src/locales/en/messages.json
> +  "selectAnOrganization": {
does not seem to be used anywhere

2024-06-17 15:25 UTC, mzieniukbw commented on apps/web/src/locales/en/messages.json
> +  "developmentDevOpsAndITTeamsChooseBWSecret": {
does not seem to be used anywhere

2024-06-17 15:25 UTC, mzieniukbw commented on apps/web/src/locales/en/messages.json
> +    "message" :"Access request for secrets manager email sent to admins."
formatting
```suggestion
    "message": "Access request for secrets manager email sent to admins."
```

2024-06-17 15:25 UTC, mzieniukbw commented on apps/web/src/locales/en/messages.json
> +  ,
formatting of the closing bracket and comma (from 4691 line until here)
```suggestion
  },
```

2024-06-17 15:25 UTC, mzieniukbw commented on apps/web/src/locales/en/messages.json
> +    "message": "Protect secrets with end-to-end encryption. No more hard coding secrets or sharing through env. files."
shouldn't this be `through .env files` instead ? (the dot in front of the env)

2024-06-17 15:25 UTC, mzieniukbw commented on apps/web/src/locales/en/messages.json
> +    "message": "securely store and manage secrets in one location to prevent secret sprawl across your organization."
Uppercase `Securely` ?

2024-06-17 15:25 UTC, mzieniukbw commented on apps/web/src/locales/en/messages.json
> +    "message": "Development, DevOps, and IT teams choose Bitwarden Secrets Manager to securely manage and deploy their infrastructure and machine secrets."
That's the first time i see the term `machine secret`, maybe this was supposed to be just `secrets` ?

2024-06-17 15:41 UTC, cd-bitwarden commented on apps/web/src/locales/en/messages.json
> +    "message": "Development, DevOps, and IT teams choose Bitwarden Secrets Manager to securely manage and deploy their infrastructure and machine secrets."
This is what I was told to write :)

2024-06-17 15:43 UTC, cd-bitwarden commented on apps/web/src/locales/en/messages.json
> +    "message": "securely store and manage secrets in one location to prevent secret sprawl across your organization."
thank you

2024-06-17 15:44 UTC, cd-bitwarden commented on apps/web/src/locales/en/messages.json
> +    "message": "Protect secrets with end-to-end encryption. No more hard coding secrets or sharing through env. files."
The design I was given said env. files, ill look more into this

2024-06-17 15:46 UTC, cd-bitwarden commented on apps/web/src/locales/en/messages.json
> +  ,
thanks!

2024-06-17 15:59 UTC, cd-bitwarden commented on apps/web/src/app/secrets-manager/secrets-manager-landing/sm-landing.component.html
> +      deploy their infrastructure and machine secrets.
yes! :)

2024-06-17 16:01 UTC, cd-bitwarden commented on apps/web/src/app/secrets-manager/secrets-manager-landing/sm-landing.component.ts
> +  organizationId: any;
youre right !

2024-06-17 16:02 UTC, cd-bitwarden commented on apps/web/src/locales/en/messages.json
> +  "developmentDevOpsAndITTeamsChooseBWSecret": {
its used now thanks

2024-06-17 16:17 UTC, cd-bitwarden commented on apps/web/src/app/secrets-manager/secrets-manager-landing/request-sm-access.component.ts
> +  submit = async () => {
I copied the structure of this page from elsewhere, where it used submit = async () =>, I did update it to use async submit() instead like you suggested because it's more readable :)

2024-06-17 16:22 UTC, cd-bitwarden commented on apps/web/src/app/secrets-manager/secrets-manager-landing/sm-landing.component.html
> +    </button>
Great idea!! I didn't think of that 😄 thank you.

2024-06-17 16:33 UTC, Thomas-Avery commented on apps/web/src/app/secrets-manager/secrets-manager-landing/request-sm-access.component.ts
> +  submit = async () => {
This is how we should write async action in forms utilizing the `bitSubmit` directive. 

Documentation here https://components.bitwarden.com/?path=/docs/component-library-async-actions-in-forms-documentation--docs

2024-06-17 17:18 UTC, cd-bitwarden commented on apps/web/src/app/secrets-manager/secrets-manager-landing/sm-landing.component.ts
> +        const organizationId = orgsUserIsAdminOf[0]?.id;
you're right, its not

2024-06-17 17:20 UTC, cd-bitwarden commented on apps/web/src/app/secrets-manager/secrets-manager-landing/sm-landing.component.ts
> +        await this.router.navigate([`/organizations/${organizationId}/billing/subscription`]);
Thank you!

2024-06-17 17:44 UTC, cd-bitwarden commented on apps/web/src/app/secrets-manager/secrets-manager-landing/request-sm-access.component.html
> +      <div class="tw-col-span-9">
This is to that it matches what the marketing team wants this page to look like, let me know if I misunderstand, we don't want it to take up the entire page🤔

2024-06-17 18:03 UTC, cd-bitwarden commented on apps/web/src/locales/en/messages.json
> +  "selectAnOrganization": {
you're right, thank you

2024-06-17 18:21 UTC, cd-bitwarden commented on apps/web/src/images/sm.webp
webp has better compression rates and smaller file sizes compared to JPEG and PNG, however if we want to be consistent I can convert it to a different file type 🤔 I have seen other files use this type as well for example u2fkey-mobile.webp and u2fkey.webp

2024-06-17 18:53 UTC, cd-bitwarden commented on apps/web/src/app/layouts/product-switcher/navigation-switcher/navigation-switcher.component.html
> +      *ngIf="moreProductsInternal != null"
we don't want to show it in the case where it's an empty array, fixing this now 😸

2024-06-17 20:41 UTC, cd-bitwarden commented on apps/web/src/app/layouts/product-switcher/navigation-switcher/navigation-switcher.component.html
> +    *ngIf="moreProducts$ != null || moreProductsInternal$ != null"
I've fixed this issue, thank you for noticing this!

2024-06-17 20:48 UTC, cd-bitwarden commented on apps/web/src/app/layouts/product-switcher/shared/product-switcher.service.ts
> +          marketingRoute: "/sm-landing",
Just to be sure I'm not missing a case, is this the Secrets Manager you are clicking in the top right? The link? :) 
![image](https://github.com/bitwarden/clients/assets/106776772/d60e20cd-8343-40f2-893e-f79e3ef07f22)

2024-06-17 21:24 UTC, Thomas-Avery commented on apps/web/src/app/layouts/product-switcher/shared/product-switcher.service.ts
> +          marketingRoute: "/sm-landing",
@cd-bitwarden Yes that is correct!

2024-06-18 05:07 UTC, mzieniukbw commented on apps/web/src/app/secrets-manager/secrets-manager-landing/request-sm-access.component.html
> +          <button type="button" bitButton buttonType="secondary" [routerLink]="'/landing'">
```suggestion
          <button type="button" bitButton buttonType="secondary" [routerLink]="'/sm-landing'">
```

2024-06-18 05:26 UTC, mzieniukbw requested changes

2024-06-18 05:26 UTC, mzieniukbw commented on apps/web/src/app/secrets-manager/secrets-manager-landing/request-sm-access.component.ts
> +    });
this is not needed anymore ? (since it's already done at the very beginning of the class)

2024-06-18 05:26 UTC, mzieniukbw commented on apps/web/src/app/secrets-manager/secrets-manager-landing/request-sm-access.component.ts
> +    this.organizations = (await this.organizationService.getAll()).filter((e) => e.enabled);
i just noticed, but the `getAll` is deprecated, is there any way around this ?

2024-06-18 05:26 UTC, mzieniukbw commented on apps/web/src/app/secrets-manager/secrets-manager-landing/request-sm-access.component.ts
> +    if (this.organizations == null || this.organizations.length < 1) {
```suggestion
    if (this.organizations === null || this.organizations.length < 1) {
```

2024-06-18 05:26 UTC, mzieniukbw commented on apps/web/src/app/secrets-manager/secrets-manager-landing/request-sm-access.component.ts
> +    request.OrganizationId = formValue.selectedOrganization.id;
```suggestion
    request.OrganizationId = formValue.selectedOrganization.id as Guid;
```

2024-06-18 05:26 UTC, mzieniukbw commented on apps/web/src/app/secrets-manager/secrets-manager-landing/request-sm-access.component.ts
> +    request.EmailContent = formValue.requestAccessEmailContents;
since `requestAccessEmailContents` does not have any validation, user can just delete the email content message from textarea. In such case, will this come up as empty string or null/undefined ?

2024-06-18 05:26 UTC, mzieniukbw commented on libs/common/tsconfig.json
> +    "../../apps/web/src/app/secrets-manager/models/Requests/request-sm-access.request.ts"
typo ? We probably want to revert this.

2024-06-18 14:35 UTC, cd-bitwarden commented on apps/web/src/app/secrets-manager/secrets-manager-landing/request-sm-access.component.ts
> +    request.EmailContent = formValue.requestAccessEmailContents;
I've added the required Validator, that should solve any issues :)

2024-06-18 14:37 UTC, cd-bitwarden commented on apps/web/src/app/secrets-manager/secrets-manager-landing/request-sm-access.component.ts
> +    this.organizations = (await this.organizationService.getAll()).filter((e) => e.enabled);
I saw it deprecated one moment, then I checked it again and it didnt' say deprecated, I'm not sure what's going on here!

2024-06-18 20:38 UTC, mzieniukbw submitted a review, later dismissed
LGTM

2024-06-18 21:24 UTC, Thomas-Avery commented on apps/web/src/images/sm.webp
I'm good with keeping it like this. Thank you!

2024-06-19 21:11 UTC, cd-bitwarden commented on apps/web/src/locales/en/messages.json
> +    "message": "Development, DevOps, and IT teams choose Bitwarden Secrets Manager to securely manage and deploy their infrastructure and machine secrets."
@mzieniukbw I verified with Marketing and they say the machine secret is what they want 😄

2024-06-20 17:56 UTC, vleague2 requested changes

2024-06-20 17:56 UTC, vleague2 commented on apps/web/src/app/layouts/product-switcher/navigation-switcher/navigation-switcher.component.html
> +      <ng-container *ngFor="let more of moreProducts">
Maybe we can leave a comment in each of these files to explain why we are duplicating the anchor tag (for rendering either an external `href` link or an internal `routerLink` link)

2024-06-26 14:15 UTC, cd-bitwarden commented on apps/web/src/app/layouts/product-switcher/product-switcher-content.component.ts
> +  isInternalMarketingRoute(marketingRoute: any) {
You're so right! I had added the external: true/false I just forgot that it meant to remove the isInternalMarketingRoute :)

2024-06-26 17:23 UTC, rr-bw commented
@cd-bitwarden looks like Auth has been removed from the scope, so I've removed myself from review. Let me know if anything changes.

2024-06-26 21:55 UTC, willmartian submitted a review, later dismissed
Looks good to me! Thanks for iterating 🚀

2024-06-27 11:12 UTC, mzieniukbw requested changes

2024-06-27 11:12 UTC, mzieniukbw commented on apps/web/src/app/layouts/product-switcher/product-switcher-content.component.html
> +          *ngIf="!product.marketingRoute.external"
I think the comments are the other way around, since this angular condition is internal.

2024-06-27 11:12 UTC, mzieniukbw commented on apps/web/src/app/layouts/product-switcher/product-switcher-content.component.html
> +          *ngIf="product.marketingRoute.external"
I think the comments are the other way around, since this angular condition is external.

2024-06-27 11:14 UTC, mzieniukbw commented on apps/web/src/app/layouts/product-switcher/shared/product-switcher.service.ts
> +            external: false,
this one look external.

2024-06-27 14:21 UTC, cd-bitwarden commented on apps/web/src/app/layouts/product-switcher/shared/product-switcher.service.ts
> +            external: false,
you're right! Thank you :)

2024-06-27 15:50 UTC, vleague2 submitted a review, later dismissed
🎉

2024-06-27 16:08 UTC, Thomas-Avery approved these changes
Looks good, one optional change from me.

2024-06-27 16:08 UTC, Thomas-Avery commented on apps/web/src/app/secrets-manager/secrets-manager-landing/sm-landing-api.service.ts
> +  }
```suggestion
  async requestSMAccessFromAdmins(request: RequestSMAccessRequest): Promise<void> {
    await this.apiService.send("POST", "/request-access/request-sm-access", request, true, false);
  }
```
Doesn't look like we expect this to return anything.

2024-06-27 16:51 UTC, cd-bitwarden commented on apps/web/src/app/secrets-manager/secrets-manager-landing/sm-landing-api.service.ts
> +  }
@Thomas-Avery even though it's optional, I made this change because it would be weird and confusing for someone in the future if they saw this and thought it would be returning something 😆

2024-06-27 16:53 UTC, mzieniukbw approved these changes
LGTM

2024-06-27 17:08 UTC, willmartian approved these changes

2024-06-27 17:36 UTC, vleague2 approved these changes

2024-06-27 17:45 UTC, Thomas-Avery approved these changes

2024-07-02 19:42 UTC, cd-bitwarden commented
@mzieniukbw @vleague2 @Thomas-Avery could I please have your review on these two tiny changes requested by the QA team: 

Changing a value in the messages file,
and ordering the organizations by org name in the org drop down :)

2024-07-03 05:34 UTC, mzieniukbw submitted a review, later dismissed

2024-07-03 12:48 UTC, vleague2 approved these changes

2024-07-03 15:17 UTC, Thomas-Avery submitted a review, later dismissed

2024-07-16 21:09 UTC, cd-bitwarden commented
Hey @Thomas-Avery and @vleague2 there is a new scenario I had to code for this SM-Landing page. Scenario: where the logged in person is an Admin (they do not have permission to go to the billing page), so they need to go to the request access page instead. If the logged in user is an Admin and the org does have SM enabled then we show them different content, explaining to them how to enable SM for a member. 
![image](https://github.com/user-attachments/assets/e1b5db6a-34b7-497a-9ad3-15092dc165c8)

Could I please get your review on this? 😄

2024-07-17 09:37 UTC, mzieniukbw commented on apps/web/src/app/secrets-manager/secrets-manager-landing/sm-landing.component.ts
> +      this.handleEnabledOrganizations(organizations);
This is misleading, since the `organizations` contains disabled organizations too

2024-07-17 10:09 UTC, mzieniukbw requested changes

2024-07-17 10:09 UTC, mzieniukbw commented on apps/web/src/app/secrets-manager/secrets-manager-landing/sm-landing.component.ts
> +    const adminPlusNeedsInstructionsToEnableSM = enabledOrgs.filter(
Since we only care about first, use`find `

2024-07-17 10:09 UTC, mzieniukbw commented on apps/web/src/app/secrets-manager/secrets-manager-landing/sm-landing.component.ts
> +  private ShowHowToEnableSMForMembers(orgId: string) {
method names should start lowercase

2024-07-17 13:45 UTC, vleague2 commented on apps/web/src/app/secrets-manager/secrets-manager-landing/sm-landing.component.html
> +    <a bitLink linkType="primary" [href]="this.learnMoreUrl" target="_blank" class="tw-m-5">
Not a blocker, but you shouldn't need to use `this` in front of property names in template files. It should work with just the property (example `[href]="learnMoreUrl"`)

2024-07-17 13:46 UTC, cd-bitwarden commented on apps/web/src/app/secrets-manager/secrets-manager-landing/sm-landing.component.html
> +    <a bitLink linkType="primary" [href]="this.learnMoreUrl" target="_blank" class="tw-m-5">
thank you for explaining :)

2024-07-17 13:48 UTC, cd-bitwarden commented on apps/web/src/app/secrets-manager/secrets-manager-landing/sm-landing.component.ts
> +    const adminPlusNeedsInstructionsToEnableSM = enabledOrgs.filter(
Great suggestion :)

2024-07-17 15:50 UTC, vleague2 approved these changes

2024-07-17 15:56 UTC, mzieniukbw approved these changes
LGTM

2024-07-17 19:47 UTC, Thomas-Avery approved these changes
LGTM

2024-07-25 15:03 UTC, merged