[PM-8553] browser v2 search bar defects
bitwarden/clients pull request #9506
Opened 2024-06-04 20:04 UTC by Jingo88

## 🎟️ Tracking

[PM-8553](https://bitwarden.atlassian.net/browse/PM-8553)
[PM-8554](https://bitwarden.atlassian.net/browse/PM-8554)
[PM-8555](https://bitwarden.atlassian.net/browse/PM-8555)

## 📔 Objective

1. Make sure the search term remains after a user makes a search, clicks into an item, and then closes the item
2. Update the `No Results` screen with the svg from the figma
3. Remove the scrolling of the `No Results` screen

## 📸 Screen Recording

https://github.com/bitwarden/clients/assets/8302660/b9b1557f-33ef-4fcb-bf4c-faf52ed93399

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-04 20:21 UTC, shane-melton requested changes
Looking pretty good! We just need to make sure the icon respects the different dark/light themes.

2024-06-04 20:21 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault/vault-v2.component.html
> +      class="tw-flex tw-flex-col tw-justify-center tw-h-auto tw-pt-12"
🎨 Can we do the same for the other full screen "empty" states while we're at it?

2024-06-04 20:21 UTC, shane-melton commented on libs/components/src/icon/icons/no-results.ts
> +<path d="M8.8545 86.7919L56.9901 86.7919C60.2321 86.7919 62.8603 84.1637 62.8603 80.9217L62.8603 32.2678C62.8603 30.7472 62.2702 29.2859 61.2143 28.1916L47.5536 14.0345C46.4473 12.8881 44.9225 12.240
⚠️ We need to use `tw-fill-*` or `tw-stroke-*` classes for the stroke and fill colors instead of the attributes with hex values. Otherwise, the icons will not respect dark/light themes.

2024-06-04 20:21 UTC, shane-melton commented on apps/browser/src/vault/popup/services/vault-popup-items.service.ts
>    private searchText$ = new BehaviorSubject<string>("");
⛏️ Can we update `searchText$` to `_searchText$` to follow the `private` field naming convention in this file.

2024-06-04 20:24 UTC, vleague2 submitted a review, later dismissed
Component library changes look good!

2024-06-04 20:24 UTC, vleague2 commented on libs/components/src/icon/icons/no-results.ts
> +<path d="M8.8545 86.7919L56.9901 86.7919C60.2321 86.7919 62.8603 84.1637 62.8603 80.9217L62.8603 32.2678C62.8603 30.7472 62.2702 29.2859 61.2143 28.1916L47.5536 14.0345C46.4473 12.8881 44.9225 12.240
⛏️ Not blocking, but consider indenting the html for (a little bit better) readability

2024-06-04 22:00 UTC, shane-melton approved these changes
Looks great, thanks!

2024-06-05 13:53 UTC, vleague2 approved these changes

2024-06-05 14:06 UTC, merged