Vault/pm 7625
bitwarden/clients pull request #9507
Opened 2024-06-04 21:04 UTC by gbubemismith

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-10 21:45 UTC, shane-melton reviewed
This looks great, nice work @gbubemismith! Really glad you were able to get it working without the need for server changes 🎆 

Most of my comments are just clarifying questions and a few minor suggestions, nothing major. 

Otherwise, the only potential outstanding change would be extracting this collection assignment component into something re-usable in browser. Happy to chat more about how we could go about that if you still think its something we should do!

2024-06-10 21:45 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/bulk-action-dialogs/bulk-move-dialog/bulk-move-dialog.component.html
💭 I'm sure this is probably fine, but wanted to note that these changes are not behind a feature flag.

2024-06-10 21:45 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +          this.showBulkMove = filter.type !== "trash";
❓ 💭 This change isn't behind the feature flag. (Also not entirely sure why it changed)

2024-06-10 21:45 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +    if (activeOrgId === "MyVault" || (!activeOrgId && !orgId)) {
❓ 💭 Do we need to build the list of available collections here as well? I believe they're going to be immediately re-calculated in the dialog using the `getCollectionsForOrganization()` helper.

2024-06-10 21:45 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +
🎨 I think the `orgId` / `activeOrgId` stuff could be combined to be a bit simpler:

```ts
const orgId: OrganizationId = this.activeFilter.organizationId || this.ciphers.find((c) => c.organizationId !== null)?.organizationId;
```

2024-06-10 21:45 UTC, shane-melton commented on apps/web/src/app/vault/components/bulk-collection-assignment-dialog/bulk-collection-assignment-dialog.component.ts
> +    this.editableItems = org.canEditAllCiphers(v1FCEnabled, restrictProviderAccess)
❓ With your improvements to the bulk menu options to only show the "Assign to collections" dialog when editable items are selected, do we still need to filter them here again? I don't think there will ever be the case where you can open this dialog with readonly ciphers. (I could be missing a scenario, and if so, please ignore!)

2024-06-10 21:45 UTC, shane-melton commented on apps/web/src/app/vault/components/bulk-collection-assignment-dialog/bulk-collection-assignment-dialog.component.ts
💭 With the idea to re-use this dialog in the browser for managing a single cipher's collection assignment, I think we would need to consider the path of un-assigning a **single** cipher from a collection(s). The current bulk implementation only allows un-assigning the "active collection", but when editing a **single** cipher, we would need to allow them to un-assign multiple collections to have the same functionality as the current cipher collections dialog. 

We'd need to check if a single cipher is being modified, and if so, load all of its assigned collections and present them as "selected". Then when submitting, we'd need to use the `cipherService.saveCollectionsWithServer()` method instead of `bulkUpdateCollectionsWithServer()`.

It does add some complexity, but I think its feasible. What do you think?

2024-06-10 21:45 UTC, shane-melton commented on apps/web/src/app/vault/components/bulk-collection-assignment-dialog/bulk-collection-assignment-dialog.component.html
💭 If we do make this re-usable with browser, we'd need to extract the dialog content into its own component in the `libs` folder so it can be re-used.

2024-06-11 13:59 UTC, gbubemismith commented on apps/web/src/app/vault/components/vault-items/vault-cipher-row.component.html
> +    <button
Yes we should

2024-06-11 21:08 UTC, gbubemismith commented on apps/web/src/app/vault/components/vault-items/vault-items.component.ts
> +      return hasPersonalItems;
I don't think it's possible to select a personal item and a collection; I think a collection can only be shown when an org filter is selected, and personal items won't exist there

2024-06-11 21:44 UTC, gbubemismith commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +          this.showBulkMove = filter.type !== "trash";
Today, the `Add to folder` bulk action is only shown on `my vault` and `all vault`, and after discussing with product, they couldn't tell why this restriction exists but okayed removing the restriction. 

It probably makes sense to put it behind the feature flag.

2024-06-12 15:27 UTC, gbubemismith commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +    if (activeOrgId === "MyVault" || (!activeOrgId && !orgId)) {
Yeah, that's true. Thanks

2024-06-12 15:41 UTC, gbubemismith commented on apps/web/src/app/vault/components/bulk-collection-assignment-dialog/bulk-collection-assignment-dialog.component.ts
> +    this.editableItems = org.canEditAllCiphers(v1FCEnabled, restrictProviderAccess)
I left this because the improvement only to show `Assign to collections` when editable items are selected has not been applied to the org vault; this PR only takes care of the end-user vault

2024-06-19 16:21 UTC, gbubemismith commented on apps/web/src/app/vault/components/vault-items/vault-items.component.ts
> +    );
Fixed here ef073fffa8d5f607041f1129c3e2ade6303ca110

2024-06-19 16:21 UTC, gbubemismith commented on apps/web/src/app/vault/individual-vault/bulk-action-dialogs/bulk-move-dialog/bulk-move-dialog.component.html
Fixed here efae5ceda32a8fec7fdfb7200dcad74c1db0e229

2024-06-19 16:33 UTC, gbubemismith commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +    if (activeOrgId === "MyVault" || (!activeOrgId && !orgId)) {
Fixed here ef073fffa8d5f607041f1129c3e2ade6303ca110

2024-06-19 16:33 UTC, gbubemismith commented on apps/web/src/app/vault/individual-vault/vault.component.ts
> +
Fixed here ef073fffa8d5f607041f1129c3e2ade6303ca110

2024-06-24 23:53 UTC, shane-melton requested changes
Great work on this! I think its going in a good direction and will be very helpful to have this logic consolidated into a shared component.

I have a few comments/suggestions that I think could make things a bit simpler and a few other clarifying questions.

2024-06-24 23:53 UTC, shane-melton commented on libs/vault/src/components/assign-collections.component.ts
> +    this.editableItemCountChange.emit(this.editableItemCount);
❓ 💭 Hmm, I'm not sure we want to make the editable item count something we need to emit for consumers. Ideally, the consumer of this component will know which items are editable on their own.

With that said, I know you said the the org vault is not filtering out editable ciphers so we must do so here. But I think it would make sense to avoid relying on it for other consumers and eventually the org vault would also only send "editable" ciphers to the component.

2024-06-24 23:53 UTC, shane-melton commented on libs/vault/src/components/assign-collections.component.ts
> +    // If no ciphers are editable, close the dialog
⛏️ (non-blocking) We're not necessarily in a "dialog" at this scope.

2024-06-24 23:53 UTC, shane-melton commented on libs/vault/src/components/assign-collections.component.ts
> +    if (this.editableItemCount == 0) {
🎨 I think it would make more sense to move this check earlier in the initialization process (likely towards the top of `ngOnInit()`) If we don't have any editable items, then there's nothing to do regardless of the organization.

2024-06-24 23:53 UTC, shane-melton commented on libs/vault/src/components/assign-collections.component.ts
> +      this.platformUtilsService.showToast(
🎨 We should use the `ToastService` instead for showing the toast.

2024-06-24 23:53 UTC, shane-melton commented on libs/vault/src/components/assign-collections.component.html
> +        <bit-select bitInput formControlName="selectedOrg">
⚠️ We can't use the `bitInput` on a `bit-select`

2024-06-24 23:53 UTC, shane-melton commented on libs/vault/src/components/assign-collections.component.ts
> +    const sharedCollectionIds = this.params.ciphers
❓ This only applies when we're editing a single cipher, correct? Or is this trying to replace the `activeCollectionId` param and support removing multiple collections for a group?

2024-06-24 23:53 UTC, shane-melton commented on libs/vault/src/components/assign-collections.component.ts
> +    this.platformUtilsService.showToast(
🎨 We should use `ToastService` instead

2024-06-24 23:53 UTC, shane-melton commented on libs/vault/src/components/assign-collections.component.ts
> +    const sharedCollectionIds = this.params.ciphers
When I edit multiple items that belong to the same two collections, I see both collections appear as selected initially, but nothing seems to happen upon removing the non `activeCollectionId`. I don't think we want this `sharedCollectionIds` logic when editing doing a bulk action on more than one item.

2024-06-24 23:53 UTC, shane-melton commented on apps/web/src/app/vault/individual-vault/bulk-action-dialogs/bulk-move-dialog/bulk-move-dialog.component.html
> +        <bit-select bitInput formControlName="folderId">
⚠️ We don't want the `bitInput` on the `bit-select`

2024-06-25 16:34 UTC, gbubemismith commented on libs/vault/src/components/assign-collections.component.ts
> +          setTimeout(() => {
just `setTimeout`, changeDetetorRef.markForCheck() is a leftover from a test. Thanks for pointing that out

2024-06-25 17:40 UTC, gbubemismith commented on apps/web/src/locales/en/messages.json
I think it makes sense to add the shared keys to the other clients' `messages.json` files once we implement the assign collections for those clients.

2024-06-26 19:33 UTC, shane-melton commented on libs/vault/src/components/assign-collections.component.ts
> +    this.editableItemCountChange.emit(this.editableItemCount);
@gbubemismith Can we add a reference to a tech debt ticket in the comments to come and clean this up?

2024-06-26 19:39 UTC, shane-melton approved these changes
Amazing work on this @gbubemismith! This turned out very nice and I am excited we'll be able to reuse this across multiple clients and we've centralized the complex logic around collection assignment 🚀 🥳 🍾

2024-06-26 20:00 UTC, shane-melton approved these changes

2024-07-11 21:39 UTC, shane-melton approved these changes

2024-07-11 21:39 UTC, merged

2024-07-12 10:30 UTC, djsmith85 commented on apps/web/src/locales/en/messages.json
> +    "message": "Only organization members with access to these collections will be able to see the items."
@gbubemismith @shane-melton Please don't change the meaning of existing messages without changing the key. These changes will not be reflected in existing translations and translators are also not notified about the change. I only notice this while reviewing the Crowdin Sync PRs. To fix this I'm going to need to manually delete all existing translations for this key. 

Same goes for https://github.com/bitwarden/clients/pull/9507/files#diff-2869bc75c8ac9b9302d87d5514c88395a23ab153dd473f14f4a3e78703bfa843R1063

2024-07-12 15:15 UTC, shane-melton commented on apps/web/src/locales/en/messages.json
> +    "message": "Only organization members with access to these collections will be able to see the items."
Ah, apologies for missing that, thank you for catching it!