[PM-4370] Implement PRF key rotation
bitwarden/clients pull request #9517
Opened 2024-06-05 12:40 UTC by quexten

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-4370

## 📔 Objective

Implement PRF key rotation.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-05 20:57 UTC, jlf0dev requested changes
Super excited to see this coming together! Please reach out if my comments weren't clear, there's a little bit of history here I forgot to share on the ticket.

2024-06-05 20:57 UTC, jlf0dev commented on apps/web/src/app/auth/key-rotation/user-key-rotation.service.ts
> +  private async rotateWebAuthnKeys(
Can we move this to the `WebauthnLoginAdminService`? I've been moving these to their respective domains. Checkout #9498 for examples.

2024-06-05 20:57 UTC, jlf0dev commented on apps/web/src/app/auth/key-rotation/user-key-rotation.service.ts
> +    return rotatedKeys;
We have a `RotateableKeySet` that we've been building for this exact purpose actually. We don't have the method to rotate them in the service yet, but its basically this same logic. Can you integrate that model? We'd like to share it between webauthn and device trust so all you have to do is call `rotateableKeySetService.rotate` for this kind of thing.

2024-06-06 07:55 UTC, quexten commented on apps/web/src/app/auth/key-rotation/user-key-rotation.service.ts
> +    return rotatedKeys;
I saw these (and meant to ask about them, but forgot), but since tde rotation also did not use them I had planned to leave them for a future refactor. But taking this PR as an opportunity to use them makes sense.

2024-06-06 09:50 UTC, quexten commented on apps/web/src/app/auth/key-rotation/user-key-rotation.service.ts
> +    return rotatedKeys;
:question: : Rotateable keys, depending on context, do not require the encrypted private key. When unlocking, we obviously need it. When just rotating, I'd rather avoid sending out the encrypted private key. RotabeableKeySet does expect the private key though. Are there any concerns with makeing it optional?

2024-06-06 10:27 UTC, quexten commented on apps/web/src/app/auth/key-rotation/user-key-rotation.service.ts
> +    return rotatedKeys;
Implemented in cd6d900, let me know if that matches the expectations.

2024-06-06 11:09 UTC, quexten commented on apps/web/src/app/auth/key-rotation/user-key-rotation.service.ts
> +  private async rotateWebAuthnKeys(
Done

2024-06-07 18:43 UTC, jlf0dev commented on apps/web/src/app/auth/core/services/rotateable-key-set.service.ts
> +  }
This is looking great! Can you add some error handling? We should probably throw if any of the parameters are nullish, and also if any of the operations return nullish values.

We also probably need a test or two for this.

2024-06-07 18:43 UTC, jlf0dev commented on apps/web/src/app/auth/core/services/webauthn-login/webauthn-login-admin.service.ts
> +  ): Promise<WebauthnRotateCredentialRequest[]> {
Some error handling and documentation here would be nice as well.

2024-06-10 22:50 UTC, jlf0dev approved these changes
Awesome work!

2024-06-17 18:47 UTC, merged