[AC-2647] Remove Flexible Collections MVP code
bitwarden/clients pull request #9518
Opened 2024-06-05 15:12 UTC by vincentsalucci

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/AC-2647

## 📔 Objective

> Remove dead code in the clients regarding the Flexible Collections MVP. This includes the following:
* Update `organization.ts`
* Update AccessSelectorComponent and models
* Update CollectionView and CollectionAdminView
* Remove misc references in components
* Delete AccessAll from request/response models

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-06 04:03 UTC, eliykat requested changes
I've reviewed commit-by-commit as recommended, mostly looks good, just a few items/questions to make sure we get it all.

2024-06-06 04:03 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/shared/components/access-selector/access-selector.models.ts
> +    readonly: false,
I think you can just remove the `readonly` assignment here altogether. It's an optional property.

2024-06-06 04:03 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/shared/components/access-selector/access-selector.models.ts
> +    readonly: false,
Same here

2024-06-06 04:03 UTC, eliykat commented on apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.ts
> +    readonly: false,
And here. Although in this case, do we still need `readonlyPermission` in the next line? Will it ever be displayed?

2024-06-06 04:03 UTC, eliykat commented on apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.ts
> +    readonly: false,
And here, and same question re: `readonlyPermission`.

2024-06-07 14:32 UTC, audrey-jensen approved these changes

2024-06-07 15:30 UTC, vincentsalucci commented on apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.ts
> +    readonly: false,
Yes! That property is used to display the assigned permission when the dialog is in a `disabled` (aka view only) state.

2024-06-07 15:30 UTC, vincentsalucci commented on apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.ts
> +    readonly: false,
Same answer!

2024-06-07 15:48 UTC, vincentsalucci commented on libs/common/src/admin-console/models/domain/organization.ts
>      }
Updated!

2024-06-07 18:02 UTC, vincentsalucci commented on apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.html
> -              <bit-hint>{{ "managerDesc" | i18n }}</bit-hint>
Updated!

2024-06-07 18:12 UTC, vincentsalucci commented on apps/web/src/app/admin-console/organizations/shared/components/access-selector/access-selector.models.ts
> +    readonly: false,
Removed

2024-06-07 18:12 UTC, vincentsalucci commented on apps/web/src/app/admin-console/organizations/shared/components/access-selector/access-selector.models.ts
> +    readonly: false,
Removed

2024-06-09 21:54 UTC, eliykat approved these changes
LGTM! I note that the deprecated custom permissions are still in `permissions.api.ts` but they're covered by a separate ticket, AC-1722, so I don't think we need to remove them here.

2024-06-10 12:11 UTC, audrey-jensen approved these changes

2024-06-10 15:43 UTC, LRNcardozoWDF approved these changes

2024-06-10 15:47 UTC, shane-melton approved these changes

2024-06-10 16:59 UTC, merged