[CL-237] Update menu styles for extension refresh
bitwarden/clients pull request #9525
Opened 2024-06-05 21:33 UTC by vleague2

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-06 16:20 UTC, danielleflinn requested changes
It looks like the padding in Figma is slightly different than what we have here. Can we update these? 
- .375rem top + bottom padding, menu item
- .75rem left + right padding, menu item
- .25rem top + bottom padding, menu container

Also looks like the border color was updated to secondary-600 back when we renamed things and in Figma we are still using the 500 variant for interactive borders...this might be something we want to address in a different PR.

2024-06-06 18:09 UTC, danielleflinn requested changes
Updated padding and border looks great!

I found one more odd behavior with the keyboard navigation. When navigating the menu with arrow keys you have to select the down arrow 2 times to get the focus past the disabled item. This felt unexpected to me, so if possible it would nice if we could just skip the disabled item as if it were not present in the UI. Is that possible

2024-06-06 18:32 UTC, willmartian approved these changes

2024-06-06 21:13 UTC, danielleflinn approved these changes

2024-06-07 13:53 UTC, willmartian approved these changes

2024-06-07 14:25 UTC, merged