[SM-654] Individual secret permissions
bitwarden/clients pull request #9527
Opened 2024-06-06 01:41 UTC by Thomas-Avery

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/SM-654

## 📔 Objective

The purpose of this PR is to add the ability to manage directly assigning permissions to a secret.

server PR https://github.com/bitwarden/server/pull/4160

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-12 11:51 UTC, differsthecat reviewed
This looks good, I only have one comment on tests, but I'll leave this for someone else on @bitwarden/team-secrets-manager-dev to give the final review and approval 😉

2024-06-12 11:51 UTC, differsthecat commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/secret.service.ts
It appears we don't have tests for this service. We probably want to add those sooner rather than later.

2024-06-12 20:47 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/secret.service.ts
Added tests to changed files here https://github.com/bitwarden/clients/pull/9527/commits/b9857e90c2028803461435089772d0b9ad58be44

2024-06-12 21:14 UTC, cd-bitwarden requested changes
Just two quick things I thought of 😄

2024-06-12 21:14 UTC, cd-bitwarden commented on apps/web/src/locales/en/messages.json
> +    "message": "Grant groups or people access to this secret. Permissions set for people will override permissions set by  groups."
I believe that there is an extra space in "by  groups." 🔎

2024-06-12 21:14 UTC, cd-bitwarden commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/access-policies/access-policy-selector/access-policy-selector.service.ts
> +    if (organization.isOwner || organization.isAdmin) {
Can we combine line 46 with this, so that it's if (organization.isOwner || organization.isAdmin || !this.userHasReadWriteAccess(current))?

2024-06-12 21:29 UTC, Thomas-Avery commented on apps/web/src/locales/en/messages.json
> +    "message": "Grant groups or people access to this secret. Permissions set for people will override permissions set by  groups."
Great catch! Fixed in https://github.com/bitwarden/clients/pull/9527/commits/ecd623a29760fed6b5f8be531fb68a8ad1bb2c8a

2024-06-12 21:29 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/access-policies/access-policy-selector/access-policy-selector.service.ts
> +    if (organization.isOwner || organization.isAdmin) {
Sounds good. Updated in https://github.com/bitwarden/clients/pull/9527/commits/d5511dbde59711d84b05488c1c94c444b8b4aa8e

2024-06-13 14:33 UTC, cd-bitwarden approved these changes
LGTM! 🎉

2024-06-14 07:30 UTC, mzieniukbw commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/access-policies/access-policy-selector/access-policy-selector.service.ts
> +        s.permission == ApPermissionEnum.CanReadWrite &&
⛏️ triple equality operator

2024-06-14 07:30 UTC, mzieniukbw commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/access-policies/access-policy-selector/access-policy-selector.service.ts
> +    if (groupReadWritePolicies.length > 0 || userReadWritePolicy != null) {
⛏️ triple equality operator

2024-06-14 07:33 UTC, mzieniukbw approved these changes
LGTM, with some minor comments

2024-06-14 15:59 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/secret.service.ts
> +    if (secretAccessPoliciesView) {
Updated in https://github.com/bitwarden/clients/pull/9527/commits/15a16742819c673d1c5bdc6c4ba0ec84c079665d

2024-06-14 15:59 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.ts
> +    }
Updated here for clarity https://github.com/bitwarden/clients/pull/9527/commits/1834add7d0923a6372f9053949215d978504d333

2024-06-14 16:00 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.ts
> +        currentUserInGroup: m.type == ApItemEnum.Group ? m.currentUserInGroup : null,
Updated here https://github.com/bitwarden/clients/pull/9527/commits/1834add7d0923a6372f9053949215d978504d333

2024-06-14 16:00 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.ts
> +    if (this.data.projectId == null || this.data.projectId == "") {
Updated here https://github.com/bitwarden/clients/pull/9527/commits/1834add7d0923a6372f9053949215d978504d333

2024-06-14 16:00 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.ts
> +      if (this.projects.find((p) => p.id === currentProject.id) == undefined) {
Updated here https://github.com/bitwarden/clients/pull/9527/commits/1834add7d0923a6372f9053949215d978504d333

2024-06-14 16:00 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/access-policies/access-policy-selector/access-policy-selector.service.ts
> +        s.permission == ApPermissionEnum.CanReadWrite &&
Updated here https://github.com/bitwarden/clients/pull/9527/commits/1834add7d0923a6372f9053949215d978504d333

2024-06-14 16:00 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/secret.service.spec.ts
> +describe("SecretService", () => {
Agreed, but it is out of scope.

2024-06-14 16:00 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/shared/access-policies/access-policy-selector/access-policy-selector.service.ts
> +    if (groupReadWritePolicies.length > 0 || userReadWritePolicy != null) {
Updated here https://github.com/bitwarden/clients/pull/9527/commits/1834add7d0923a6372f9053949215d978504d333

2024-06-14 16:01 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.ts
>      } else if (this.data.operation == OperationType.Add) {
Updated here https://github.com/bitwarden/clients/pull/9527/commits/1834add7d0923a6372f9053949215d978504d333

2024-06-14 17:01 UTC, mzieniukbw approved these changes

2024-06-16 07:45 UTC, mzieniukbw approved these changes

2024-06-20 17:20 UTC, coltonhurst approved these changes
Only one question, still approved though!

2024-06-20 17:20 UTC, coltonhurst commented on apps/web/src/locales/en/messages.json
> +    "message": "This action will remove your access to this secret."
Is it worth being consistent on punctuation across these? (If we should end the message with periods or not?)

2024-06-20 17:38 UTC, Thomas-Avery commented on apps/web/src/locales/en/messages.json
> +    "message": "This action will remove your access to this secret."
I double-checked and these match designs. 

The empty messages appear in the table and match our other empty table messages for access policies.

The other is a title for a dialog which shouldn't have the period.

2024-06-20 17:43 UTC, merged