[PM-7102] Create Add/Edit container for Item v2 work
bitwarden/clients pull request #9541
Opened 2024-06-06 20:47 UTC by Jingo88

## 🎟️ Tracking

[PM-7102](https://bitwarden.atlassian.net/browse/PM-7102)

## 📔 Objective

Create a new AddEditV2Component that will be able to navigate to from the +New button or the item itself. The new component should also differentiate between having a "New" vs "View" page, and the four different types of ciphers "Login", "Card", "Identity", "Note"

## 📸 Screen Recording

https://github.com/bitwarden/clients/assets/8302660/e50510ac-6f88-4cd1-8134-b380621b157a

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-06 21:49 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.ts
> +    return this.route.queryParams.pipe(first()).subscribe((params) => {
⚠️ We should have the `takeUntilDestroyed()` and remove the eslint statement.

2024-06-06 21:49 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.ts
> +    const headerOne = isNew ? this.i18nService.t("new") : this.i18nService.t("view");
⚠️ I believe this should be "new" or "edit" (not "view").

2024-06-06 21:49 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.ts
> +    return `${headerOne} ${headerTwo}`;
⚠️ 💭 I don't think this fully supports languages that might have a different noun/verb order. We'll likely want to make a new templated messages for view/edit that accept a translated type argument. Then we can do something like:

```ts
return this.i18nService.t("viewItemGeneric", this.i18nService.t("note"));
```

Where `viewItemGeneric` has a message value of `"View $ITEMTYPE$"` that way translators can re-arrange as necessary. 

Though, this is still likely not perfect as I believe some languages might use a different conjugation of "View" depending on the item type. 🤔

2024-06-06 21:49 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault/vault-v2.component.html
> +        <button type="button" bitMenuItem (click)="newItemNavigate(cipherType.Login)">
🎨 Since we're performing navigation these should be `<a>` tags to be semantically correct instead of `button`.

2024-06-06 21:49 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault/vault-v2.component.html
> +          <i class="bwi bwi-globe" slot="start"></i>
⚠️ These icons should have `aria-hidden="true"` since there are text labels already.

2024-06-06 21:49 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault/vault-v2.component.ts
>      void this.router.navigate(["/add-cipher"], {});
❓ I don't think we should need this anymore if we have `newItemNavigate()` below.

2024-06-06 21:49 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault/vault-v2.component.ts
>      void this.router.navigate(["/add-cipher"], {});
Oh, we'll need to re-create the dropdown button for the empty vault state that also used this `addCipher()` method. It might be worthwhile to make the new item dropdown this its own component.

2024-06-06 21:49 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault/vault-v2.component.html
> -      <!-- TODO PM-6826: add selectedVault query param -->
💭 We should either keep this TODO somewhere or go ahead and pass the selected vault in the query params now that they're available.

2024-06-06 21:49 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.ts
> +  subscribeToParams(): Subscription {
👍 I like how you've broken this up into its own method!

2024-06-06 21:49 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.ts
> +    return this.route.queryParams.pipe(first()).subscribe((params) => {
❓ Why are we returning the subscription?

2024-06-06 21:50 UTC, shane-melton requested changes
Whoops, forgot to select the review type last time

2024-06-07 16:54 UTC, Jingo88 commented on apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.ts
> +    return this.route.queryParams.pipe(first()).subscribe((params) => {
cool cool. i figured having first would be easier than doing another import but I'm okay either way. updated.

2024-06-07 16:54 UTC, Jingo88 commented on apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.ts
> +    return `${headerOne} ${headerTwo}`;
ah forgot about translation keys here. updated

2024-06-07 16:54 UTC, Jingo88 commented on apps/browser/src/vault/popup/components/vault/vault-v2.component.ts
>      void this.router.navigate(["/add-cipher"], {});
gotcha. moved to it's own component now.

2024-06-07 16:55 UTC, Jingo88 commented on apps/browser/src/vault/popup/components/vault/vault-v2.component.html
> -      <!-- TODO PM-6826: add selectedVault query param -->
Keeping this TODO not in the new component

2024-06-07 16:55 UTC, Jingo88 commented on apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.ts
> +    return this.route.queryParams.pipe(first()).subscribe((params) => {
ah just a habit for the type return. updated

2024-06-10 15:54 UTC, shane-melton requested changes
Looking good! We just need to use the new dropdown component in the empty vault state and then I think we're ready for merge!

2024-06-10 15:54 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault/vault-v2.component.html
🎨 We should use the new `<app-new-item-dropdown>` component in the `<bit-no-items>` empty state below too (~line 18). That should also let us remove the `addCipher()` method from the `vault-v2`.

2024-06-10 15:54 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/new-item-dropdown/new-item-dropdown-v2.component.html
👍 Looks great!

2024-06-10 17:52 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault/vault-v2.component.html
> -      <button slot="button" type="button" bitButton buttonType="primary" (click)="addCipher()">
❓ Can we put the new dropdown in the `bit-no-items` component and use the `slot="button"`? That way we keep the layout provided by `bit-no-items` and don't need our own tailwind classes. Something like:

`<app-new-item-dropdown slot="button"></...>`

2024-06-10 18:20 UTC, shane-melton approved these changes
Awesome, looks great!

2024-06-10 18:23 UTC, merged