[PM-8381] Assign collections
bitwarden/clients pull request #9542
Opened 2024-06-06 22:03 UTC by nick-livefront

## 🎟️ Tracking

[PM-8381](https://bitwarden.atlassian.net/browse/PM-8381)

## 📔 Objective

The first portion of PM-8381:
- Add "Assign Collections" screen for moving a cipher into an organization and assigned to at least one collection
- This should mimic the logic of the `ShareComponent`
- The select & multi-select that are shown in the designs do not appear to be available yet. 

### Open Questions/Thoughts
- The path for the `Assign Collections` Component isn't behind the feature flag. Nothing links to it from _outside_ the feature flag but still is a risk. Should I add logic to reroute if the flag isn't enabled?
- I really wanted to break the form and submission logic into a separate component for organization but I was getting render errors by trying to keep the `submit` button in sync with the form from a child component.
- Part two will include logic to allow for reassigning collections if a cipher is already assigned to an Organization
  - For now I hid the "Assign Collections" link if a cipher is already assigned to an org 

## 📸 Screenshots

![Screen Recording 2024-06-06 at 5 00 24 PM](https://github.com/bitwarden/clients/assets/125900171/1ed76818-3c03-42e9-926b-3be2e5c132a8)

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-06 22:33 UTC, shane-melton requested changes
Looking good! A few small issues and we should adjust the form logic to use the newer [CL `bitSubmit` directive.](https://components.bitwarden.com/?path=/docs/component-library-async-actions-in-forms-documentation--docs)

2024-06-06 22:33 UTC, shane-melton commented on apps/browser/src/popup/app-routing.module.ts
> +    data: { state: "assign-collections" },
🎨 We have a `canAccessFeature` guard we can use here to prevent anyone from unintentionally accessing this route.

2024-06-06 22:33 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/assign-collections/assign-collections.component.html
> +      1 item will be permanently transferred to the selected organization. You will no longer own
⚠️ Looks like we missed this for i18n.

2024-06-06 22:33 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/assign-collections/assign-collections.component.ts
> +      .subscribe(async ([{ cipherId }, collections]) => {
🎨 We should really avoid using `async` subscribe. I think we could just pipe the `route.queryParams` above. Something like:

```ts
combineLatest([
  route.queryParams.pipe(switchMap(({cipherId}) => this.cipherService.get(cipherId))),
  this.collectionService.decryptedCollections$
]).pipe(...).subscribe( ([cipher, collections]) => {
...
```

2024-06-06 22:33 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/assign-collections/assign-collections.component.ts
> +    const cipherView = await cipherDomain.decrypt(
❓ Might be missing something, but can we re-use `this.cipher` here instead of getting the domain and decrypting it again?

2024-06-06 22:33 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/assign-collections/assign-collections.component.html
> +    <button bitButton buttonType="secondary" (click)="navigateBack()" type="button">
⛏️ This should be a `<a>` since its navigation related.

2024-06-06 22:33 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/assign-collections/assign-collections.component.html
> +      [appApiAction]="formPromise"
⚠️ We should avoid `appApiAction` and instead use the `bitSubmit` directive from the CL. [Docs can be found here](https://components.bitwarden.com/?path=/docs/component-library-async-actions-in-forms-documentation--docs).

This might require adjust the wrapping of the parent `<form>` tag so it includes the popup footer which has the submit button.

2024-06-06 22:33 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/assign-collections/assign-collections.component.html
> +      bitButton
⚠️ After migrating to `bitSubmit` for the form, you should be able to use `bitFormButton` here instead (and remove all the `disabled` and `form` attributes as they're already handled by `bitFormButton`.

2024-06-10 20:58 UTC, nick-livefront commented on apps/browser/src/popup/app-routing.module.ts
> +    data: { state: "assign-collections" },
💥 [ea863c8](https://github.com/bitwarden/clients/pull/9542/commits/ea863c845dc16da3bf5a07c1abd5a87b27d72dc2)

2024-06-10 20:58 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault-v2/assign-collections/assign-collections.component.html
> +      1 item will be permanently transferred to the selected organization. You will no longer own
😬 [b3074e4](https://github.com/bitwarden/clients/pull/9542/commits/b3074e4fbba975403efb4e4f4e62d57554381ec6)

2024-06-10 20:59 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault-v2/assign-collections/assign-collections.component.ts
> +      .subscribe(async ([{ cipherId }, collections]) => {
Good call, it does tidy up the logic too. [d06c82d](https://github.com/bitwarden/clients/pull/9542/commits/d06c82d3d6b74a01701a5a39c8155cde96c8d5fc)

2024-06-10 21:00 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault-v2/assign-collections/assign-collections.component.ts
> +    const cipherView = await cipherDomain.decrypt(
I don't think you're missing anything, I think I got caught up in reverse engineering some existing components between the Share/AssignCollection components and didn't make the connection that this could be simplified.

[08a01db](https://github.com/bitwarden/clients/pull/9542/commits/08a01db7eb4f062a5897a5c6efb474480a28df13)

2024-06-10 21:00 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault-v2/assign-collections/assign-collections.component.html
> +    <button bitButton buttonType="secondary" (click)="navigateBack()" type="button">
👍 [3514693](https://github.com/bitwarden/clients/pull/9542/commits/35146930d6bf8a70c1fb678ead7b84c63d599750)

2024-06-10 21:00 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault-v2/assign-collections/assign-collections.component.html
> +      [appApiAction]="formPromise"
I had to wrap the entire page in the `form` but that's a small price for the added functionality and up to date with the codebase!

[27aa256](https://github.com/bitwarden/clients/pull/9542/commits/27aa2565c06b773172e02671366c1502a530e081)

2024-06-10 21:02 UTC, nick-livefront commented
@shane-melton I updated per your comments here just to keep my todo items in check. No need to review until we get an answer from design about combining mine and @gbubemismith's work

2024-06-11 20:45 UTC, Jingo88 approved these changes

2024-06-11 20:46 UTC, Jingo88 commented
Ah just saw the last comment haha.

2024-06-20 19:54 UTC, nick-livefront commented
@shane-melton @Jingo88 I'm going to close this PR and branch off of @gbubemismith's PR: https://github.com/bitwarden/clients/pull/9507/files

2024-06-20 19:54 UTC, closed without merging