Restructure the `org-redirect` guard to be Angular 17+ compliant
bitwarden/clients pull request #9552
Opened 2024-06-07 21:05 UTC by addisonbeck

## 🎟️ Tracking

[
](https://bitwarden.atlassian.net/browse/AC-2756)

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-09 21:29 UTC, eliykat submitted a review, later dismissed
Great work, I like the tests particularly 🎉

2024-06-09 21:29 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/guards/org-redirect.guard.ts
> +export function organizationRedirectGuard(): CanActivateFn {
🎨 (non-blocking): Now that this is a function, you could replace the non-type safe `route.data` property with an explicitly typed parameter:

```ts
export function organizationRedirectGuard(autoRedirectCallback: org => string): CanActivateFn {
```

which I think makes full use of the new "all guards are just functions' design.

2024-06-11 19:23 UTC, addisonbeck commented on apps/web/src/app/admin-console/organizations/guards/org-redirect.guard.ts
> +export function organizationRedirectGuard(): CanActivateFn {
Good idea. Implemented as suggested on https://github.com/bitwarden/clients/pull/9552/commits/42f77e10322241ff3bb1b1fc916ee76f9142f041

2024-06-11 22:08 UTC, eliykat requested changes

2024-06-11 22:08 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/settings/organization-settings-routing.module.ts
>          },
Missed this one

2024-06-13 18:36 UTC, addisonbeck commented on apps/web/src/app/admin-console/organizations/settings/organization-settings-routing.module.ts
>          },
Thank you. Added on https://github.com/bitwarden/clients/pull/9552/commits/df39b9c983e958c45380b92848bb51336c5890aa

2024-06-14 02:17 UTC, eliykat submitted a review, later dismissed

2024-06-25 22:19 UTC, eliykat approved these changes

2024-07-01 15:54 UTC, merged