[AC-1102]Automatic Sync is visible for self hosted Families Orgs
bitwarden/clients pull request #9565
Opened 2024-06-10 15:23 UTC by cyprain-okeke

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/AC-1102
## 📔 Objective

modify the UI for self-host and remove Automatic Sync and Manual upload radio button
## 📸 Screenshots

<img width="1728" alt="Screenshot 2024-06-06 at 16 06 28" src="https://github.com/bitwarden/clients/assets/108260115/8be749c3-9b30-411c-bebd-26086f44892d">
<img width="1728" alt="Screenshot 2024-06-06 at 16 07 14" src="https://github.com/bitwarden/clients/assets/108260115/8906d9e6-9c92-4ae1-a7d9-80c4dad502ad">

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-10 15:42 UTC, amorask-bitwarden reviewed
Just one question regarding the update to the BCL.

2024-06-10 15:42 UTC, amorask-bitwarden commented on libs/components/src/form-field/form-field.component.ts
> +  @Input() showRequired: boolean | undefined = true;
❓ Sorry I'm a bit confused as to the purpose of the `showRequired` property on the `form-field.component`. Is this being added because you want a field to be required but not show the "required" label? If so, can we handle that logic on submission rather than updating the base component library?

2024-06-10 16:29 UTC, cyprain-okeke commented on libs/components/src/form-field/form-field.component.ts
> +  @Input() showRequired: boolean | undefined = true;
We don't want to show bit-label for licenseFile comment if the organisation is family but because is marked required , when you use *ngif, the to hide the label, the `required` is still been displayed. Which is why it was added to mark it as `not required`

2024-06-10 17:04 UTC, amorask-bitwarden commented on libs/components/src/form-field/form-field.component.ts
> +  @Input() showRequired: boolean | undefined = true;
In the case you're talking about, is it possible to just make the entire form field not required and then just handle validation on submission? Updating the BCL component for this one circumstance seems like a sizable change and I'm not sure it's only limited to the .ts and .html files. For instance, would Storybook changes be required for this as well? Maybe @bitwarden/team-component-library can provide some guidance since they're tagged reviewers.

2024-06-12 14:27 UTC, audrey-jensen requested changes
Just a nit or two.

2024-06-12 14:27 UTC, audrey-jensen commented on apps/web/src/locales/en_GB/messages.json
> +    "message": "Your license file will be named something like $FILE_NAME$",
⛏️ Licence is the correct spelling. The license file is the grant, not the action of granting. The US uses "license" for the noun, while the UK uses "licence". ([source](https://www.grammarly.com/blog/licence-license/))

```suggestion
    "message": "Your licence file will be named something like $FILE_NAME$",
```

2024-06-12 14:27 UTC, audrey-jensen commented on apps/web/src/locales/en_IN/messages.json
> +    "message": "Your license file will be named something like $FILE_NAME$",
🤔 I'm not as certain about how India's spelling works, but I assume that as a former colony of Britain, that they use the British spelling.

```suggestion
    "message": "Your licence file will be named something like $FILE_NAME$",
```

2024-06-12 14:37 UTC, cyprain-okeke commented on apps/web/src/locales/en_GB/messages.json
> +    "message": "Your license file will be named something like $FILE_NAME$",
I will get the product team to review this because they wanted it changed

2024-06-12 15:35 UTC, audrey-jensen submitted a review, later dismissed
Approving so that this can be merged w/ the nits overruled.

2024-06-17 15:59 UTC, amorask-bitwarden submitted a review, later dismissed

2024-06-17 18:40 UTC, amorask-bitwarden approved these changes

2024-06-17 18:57 UTC, audrey-jensen submitted a review, later dismissed

2024-06-18 12:51 UTC, amorask-bitwarden submitted a review, later dismissed

2024-06-18 12:55 UTC, audrey-jensen approved these changes

2024-07-02 17:02 UTC, audreyality approved these changes

2024-07-09 19:55 UTC, audreyality submitted a review, later dismissed

2024-07-09 21:15 UTC, audreyality submitted a review, later dismissed

2024-07-10 21:45 UTC, audreyality approved these changes

2024-07-11 13:06 UTC, amorask-bitwarden approved these changes

2024-07-11 17:05 UTC, merged