[PM-8772] move ranges to static properties on class
bitwarden/clients pull request #9567
Opened 2024-06-10 16:45 UTC by jlf0dev

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-8772
## 📔 Objective

Moves kdf ranges to be static properties on the class to prevent circular dependency issues.

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-10 16:53 UTC, LRNcardozoWDF approved these changes

2024-06-10 17:17 UTC, ike-kottlowski requested changes
⛏️ : Tightening up the naming for the `KdfConfig`

2024-06-10 17:17 UTC, ike-kottlowski commented on libs/common/src/auth/models/domain/kdf-config.ts
Spoke with @MGibson1 and he pointed out the Constant's names are redundant. So
`PBKDF2KdfConfig.PBKDF2_ITERATIONS` to `PBKDF2KdfConfig.ITERATIONS`, `Argon2KdfConfig.ARGON2_MEMORY` to `Argon2KdfConfig.MEMORY`, etc.

2024-06-10 18:36 UTC, ike-kottlowski approved these changes

2024-06-12 12:58 UTC, LRNcardozoWDF approved these changes

2024-06-17 14:53 UTC, justindbaur approved these changes

2024-06-19 15:52 UTC, djsmith85 approved these changes

2024-06-25 12:21 UTC, merged