[PM-1802] Update 2fa provider icons and description
bitwarden/clients pull request #9568
Opened 2024-06-10 16:47 UTC by quexten

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-20 21:38 UTC, rr-bw requested changes
Looks great so far. A couple of minor comments and copy changes below. As for splitting the SVGs into separate files, I think that's a good idea. You could try following the pattern [here](https://github.com/bitwarden/clients/blob/main/apps/web/src/app/auth/login/login-via-webauthn/login-via-webauthn.component.ts#L12) and [here](https://github.com/bitwarden/clients/blob/main/libs/angular/src/auth/icons/create-passkey.icon.ts) using `svgIcon`.

2024-06-20 21:38 UTC, rr-bw commented on libs/angular/src/auth/components/two-factor-icon.component.ts
> +  selector: "bw-two-factor-icon",
Why `bw-` prefix? I think we'd just go with `auth-` here.

2024-06-21 08:14 UTC, djsmith85 requested changes

2024-06-21 08:14 UTC, djsmith85 commented on apps/browser/src/_locales/en/messages.json
> +    "description": "'Bitwarden Authenticator' is a product name and should not be translated."
To let our translation community over at CrowdIn know, that the source string has changed, we also need to provide a new key. Please rename all keys where you have changed the message content/meaning.

Once this is merged, any translator gets a notification about a new text to translate.

My comment applies to **all** messages.json files

2024-06-21 14:50 UTC, quexten commented on libs/angular/src/auth/components/two-factor-icon.component.ts
> +  selector: "bw-two-factor-icon",
Makes sense! Updated in 3ed56bc761.

2024-06-21 14:51 UTC, quexten commented on apps/web/src/app/auth/settings/two-factor-authenticator.component.html
> +            >2FAS Authenticator</a
Updated in 9321068

2024-06-21 14:51 UTC, quexten commented on apps/web/src/app/auth/settings/two-factor-authenticator.component.html
> +            >Aegis Authenticator</a
Updated in 9321068

2024-06-21 14:58 UTC, quexten commented on apps/web/src/locales/en/messages.json
> +    "message": "Use your device's biometrics or a FIDO2 security key."
Updated in d79c345. Nice catch!

2024-06-21 15:01 UTC, quexten commented on apps/browser/src/_locales/en/messages.json
> +    "description": "'Bitwarden Authenticator' is a product name and should not be translated."
To clarify, do I just rename the key in the English messages.json or do I do this for all languages?

2024-06-21 15:11 UTC, quexten commented on apps/browser/src/_locales/en/messages.json
> +    "description": "'Bitwarden Authenticator' is a product name and should not be translated."
Also is there a general pattern to prefer when simply updating the text to a different phrasing? Does adding a "V2" suffix to each key suffice?

2024-06-21 15:13 UTC, quexten commented on apps/browser/src/_locales/en/messages.json
> +    "description": "'Bitwarden Authenticator' is a product name and should not be translated."
The V2 suffix is what I went with for now in a4ec25d , but I'm happy to change it if there is a preferable pattern.

2024-06-21 15:29 UTC, djsmith85 commented on apps/browser/src/_locales/en/messages.json
> +    "description": "'Bitwarden Authenticator' is a product name and should not be translated."
Only the keys in the en/messages.json need to change. Those are then used as source for all translations. 
Regarding naming, there are no guidelines. Usually an update in copy also introduces a different meaning which the key can be renamed to.

2024-06-21 15:31 UTC, djsmith85 requested changes

2024-06-21 15:31 UTC, djsmith85 commented on apps/web/src/locales/en/messages.json
> +  "twoStepAuthenticatorEnterCode V2": {
Need to remove the space from the key, but other than that all changes are looking good.

Leaving it up to the Auth team to finish the review

2024-06-21 15:53 UTC, quexten commented on apps/web/src/locales/en/messages.json
> +  "twoStepAuthenticatorEnterCode V2": {
Messed this up in find&replace. Nice catch!

2024-06-21 15:54 UTC, quexten commented on apps/browser/src/_locales/en/messages.json
> +    "description": "'Bitwarden Authenticator' is a product name and should not be translated."
Great! In this case most it's mostly the phrasing that changes, so keeping the V2 suffix.

2024-06-21 15:54 UTC, quexten commented
@rr-bw Moved out the svg icons to separate files as per the example you linked.

2024-06-24 10:47 UTC, djsmith85 submitted a review, later dismissed
@quexten Thank you for addressing my translation-related concerns!

2024-06-24 16:27 UTC, rr-bw approved these changes

2024-06-27 08:16 UTC, quexten commented
@rr-bw Seems resolving merge conflicts dismissed the approving review.

2024-06-27 17:14 UTC, rr-bw approved these changes

2024-06-27 17:14 UTC, merged