[CL-250] Update badge styles for extension refresh
bitwarden/clients pull request #9572
Opened 2024-06-10 20:03 UTC by vleague2

## 🎟️ Tracking

[CL-250](https://bitwarden.atlassian.net/browse/CL-250)

## 📔 Objective

This PR updates the styles of the `badge` component according to the new designs for the extension refresh. This also involved adding some more text color options in the tailwind config. 

## 📸 Screenshots

Check the Storybook Publish action and the `badge` stories.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-10 20:27 UTC, danielleflinn requested changes
Amazing! Can we up the font-weight to 500 to match Figma? 

Then, I realized since we have the Figma branch merged now we can update the "Design" add on links as we go if you and @willmartian think that will be easier than doing it after the fact. You could use the same link as in the jira description if you decide you want to add that now

2024-06-10 21:41 UTC, danielleflinn approved these changes

2024-06-11 13:32 UTC, willmartian commented on libs/components/src/badge/badge.stories.ts
> +  render: (args) => ({
For clarity, could you add labels to each row?

```
Default: ...
Hover: ...
Focus visible: ...
etc
```

2024-06-11 14:34 UTC, willmartian approved these changes

2024-06-11 15:05 UTC, merged