[PM-4348] Migrate AuthGuards to functions
bitwarden/clients pull request #9595
Opened 2024-06-12 12:26 UTC by quexten

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-4348

## 📔 Objective

We need to update the old router guards to use the new funcitonal-style guards since the class based guards are deprecated and may be removed in Angular 17.

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-13 15:56 UTC, Hinton commented on libs/angular/src/services/jslib-services.module.ts
> +  }),
**issue:** I don't believe you need any glue code for Angular DI when using the functional route guards. The `AUTH_GUARD` and `UNAUTH_GUARD` injection tokens seems unused.

2024-06-13 15:57 UTC, audrey-jensen submitted a review, later dismissed
Just an optional nit.

2024-06-15 19:17 UTC, addisonbeck submitted a review, later dismissed

2024-06-17 11:08 UTC, quexten commented on libs/angular/src/services/jslib-services.module.ts
> +  }),
Nice catch! Fixed in [f9a8b34](https://github.com/bitwarden/clients/pull/9595/commits/f9a8b343a63885f6e062370f9a93561a3c8b8c26)

2024-06-17 21:12 UTC, Thomas-Avery requested changes

2024-06-17 21:12 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/guards/sm.guard.ts
> +  const authGuard = inject(authGuardFn);
Manually changing the url to `/#/sm` to get this code to execute produces a console error and doesn't take us to Secrets Manager.

```
Error: Uncaught (in promise): NullInjectorError: NullInjectorError: No provider for authGuard!
NullInjectorError: NullInjectorError: No provider for authGuard!
```

2024-06-21 14:42 UTC, quexten commented on bitwarden_license/bit-web/src/app/secrets-manager/guards/sm.guard.ts
> +  const authGuard = inject(authGuardFn);
Fixed in [a7e4113](https://github.com/bitwarden/clients/pull/9595/commits/a7e4113aebe189f7923bb8461a81b96aed2b5d05) by moving the auth related logic out of the sm guard completely, and adding it as an additional guard in the sm routing module. Nice catch!

2024-06-21 15:51 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/guards/sm.guard.ts
> +  const authGuard = inject(authGuardFn);
```
canActivate: [authGuard, canActivateSM],
```

@quexten Is there any execution ordering with this, or is it just whatever `CanActivateFn` returns a boolean or `UrlTree` first between the two?

I read the docs here https://angular.dev/api/router/CanActivateFn?tab=description, but it's unclear to me.

2024-06-21 16:07 UTC, quexten commented on bitwarden_license/bit-web/src/app/secrets-manager/guards/sm.guard.ts
> +  const authGuard = inject(authGuardFn);
Hmm, reading this it is also unclear to me, need to dig deeper on this.

2024-06-21 16:30 UTC, quexten commented on bitwarden_license/bit-web/src/app/secrets-manager/guards/sm.guard.ts
> +  const authGuard = inject(authGuardFn);
From a bit of poking at it: The async guards get executed concurrently (async), but the order of evaluation of the results is: If any is false, then the result is false. If none are false, then we check if any is a UrlTree, in order of the auth guards.

Even when forcing the authGuard to be exceptionally slow using a 1 second promise, the redirection happens directly to /lock in case the vault is locked.

2024-06-21 16:33 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/guards/sm.guard.ts
> +  const authGuard = inject(authGuardFn);
Could that be because the routes `canActivateSM` return require the `authGuard` as well?

2024-06-21 16:36 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/guards/sm.guard.ts
> +  const authGuard = inject(authGuardFn);
If it works like described.

"If none are false, then we check if any is a UrlTree, in order of the auth guards."

Then that works for me. Thank you for the clarification!

2024-06-25 15:01 UTC, JaredSnider-Bitwarden reviewed
This is looking really good!  A few extra test suggestions below 👇

2024-06-25 15:01 UTC, JaredSnider-Bitwarden commented on libs/angular/src/auth/guards/unauth.guard.spec.ts
Really nice work on this test suite as well! 

Do you think we should add a small test for the overrides functionality?

2024-06-26 10:51 UTC, quexten commented on libs/angular/src/auth/guards/auth.guard.spec.ts
Added tests for this!

2024-06-26 11:00 UTC, quexten commented on libs/angular/src/auth/guards/unauth.guard.spec.ts
Added tests for this too!

2024-06-26 14:19 UTC, JaredSnider-Bitwarden approved these changes
Very nice work!

2024-06-26 15:47 UTC, Thomas-Avery approved these changes

2024-07-01 14:07 UTC, audreyality submitted a review, later dismissed

2024-07-01 16:32 UTC, addisonbeck approved these changes

2024-07-10 14:06 UTC, audreyality submitted a review, later dismissed

2024-07-10 15:19 UTC, JaredSnider-Bitwarden submitted a review, later dismissed

2024-07-10 15:25 UTC, Thomas-Avery submitted a review, later dismissed

2024-07-16 11:36 UTC, quexten commented
Resolved merge conflicts again.

2024-07-16 14:41 UTC, JaredSnider-Bitwarden submitted a review, later dismissed

2024-07-16 21:01 UTC, Thomas-Avery approved these changes

2024-07-18 15:20 UTC, audreyality submitted a review, later dismissed

2024-07-18 19:30 UTC, addisonbeck submitted a review, later dismissed

2024-07-19 11:35 UTC, quexten commented
Resolved merge conflicts again.

2024-07-19 12:10 UTC, audreyality approved these changes

2024-07-19 14:19 UTC, JaredSnider-Bitwarden submitted a review, later dismissed

2024-07-23 13:40 UTC, audreyality approved these changes
📝 The promise test is a bit flappy and is safe to ignore. The fix is pending in #10215.

2024-07-23 14:01 UTC, JaredSnider-Bitwarden approved these changes

2024-07-23 17:22 UTC, Thomas-Avery approved these changes

2024-07-25 09:54 UTC, quexten commented
Fixed merge conflicts once more.

2024-07-25 14:45 UTC, JaredSnider-Bitwarden approved these changes

2024-07-25 15:17 UTC, audreyality approved these changes

2024-07-25 16:54 UTC, Thomas-Avery approved these changes

2024-07-25 21:00 UTC, addisonbeck approved these changes

2024-07-25 21:00 UTC, merged