[PM-6826] Pass along the filtered vault in new item dropdown
bitwarden/clients pull request #9604
Opened 2024-06-12 16:08 UTC by nick-livefront

## 🎟️ Tracking

[PM-6826](https://bitwarden.atlassian.net/browse/PM-6826)

## 📔 Objective

When a user is filtering by an organization and selects a new item, pass along the `id` of the organization to the add/edit component.

- I believe this is the only location. It was the only TODO 😄 
- The existing logic doesn't appear to filter out `MyVault` if it is selected but I don't believe that would be needed by the Add/Edit component because it would be the same scenario as if an organization wasn't selected all. Is that accuate?

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-12 16:32 UTC, shane-melton reviewed
This looks great and straightforward! 

With that said, how would you feel passing the `vaultId` in as an `@Input()` so we don't add the popup filter service as a dependency to this component? It would allow us to move this dropdown component to our `Vault Lib` eventually so we can re-use it in other clients in the future.

2024-06-12 16:56 UTC, nick-livefront commented
> With that said, how would you feel passing the `vaultId` in as an `@Input()` so we don't add the popup filter service as a dependency to this component? It would allow us to move this dropdown component to our `Vault Lib` eventually so we can re-use it in other clients in the future.

@shane-melton Thank you for the context, and no issue from me! 🥳 
[6224a27](https://github.com/bitwarden/clients/pull/9604/commits/6224a2719bc2ac18426cc460b544f8a003025199)

2024-06-12 16:57 UTC, gbubemismith commented on apps/browser/src/vault/popup/components/vault-v2/new-item-dropdown/new-item-dropdown-v2.component.ts
>    ngOnDestroy(): void {}
I think we can remove ngOnDestroy since we use takeUntilDestroyed

2024-06-12 17:22 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault-v2/new-item-dropdown/new-item-dropdown-v2.component.ts
>    ngOnDestroy(): void {}
👍 They're unused in a couple components, I assume from the CLI boilerplate. It's a little unrelated to my change here but worth it to remove them, in my opinion! 

[0692029](https://github.com/bitwarden/clients/pull/9604/commits/0692029606c712f0ceb9d68ff7e4309de76d58a2)

2024-06-12 17:59 UTC, shane-melton requested changes

2024-06-12 17:59 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault/vault-v2.component.html
⛏️  Can we also add the `[selectedVaultId]` to the `app-new-item-dropdown` in the empty vault section (~line 18).

2024-06-12 19:06 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault/vault-v2.component.html
Happy to add it! I left it out in this case because the filters aren't visible the instance where the empty vault shows and therefore the selected org would always be `null/undefined` with how the filters are configured.

Is that a bug itself?

2024-06-12 19:46 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault/vault-v2.component.html
Easy add regardless: [e9efe9b](https://github.com/bitwarden/clients/pull/9604/commits/e9efe9bd5a6dffc1459a00ea1a4e03ece8b2ece1)

2024-06-17 14:36 UTC, Jingo88 approved these changes

2024-06-24 17:38 UTC, shane-melton commented
@nick-livefront I mistakenly forgot about your PR (sorry!) and ended up implementing this again with support for folders/collections as part of #9758. Unless you're opposed I think it we can close this in favor of #9758 as it supports the other filters as well. What do you think?

2024-06-24 17:51 UTC, nick-livefront commented
@shane-melton I'm not opposed, moving forward with https://github.com/bitwarden/clients/pull/9758 will be more integrated into the logic flow anyways!

2024-06-24 17:51 UTC, closed without merging