[SM-1305] Add Kubernetes and Rust to the integrations page
bitwarden/clients pull request #9611
Opened 2024-06-12 18:44 UTC by differsthecat

## 📔 Objective

Add Kubernetes and Rust to the integrations page

## 📸 Screenshots
<img width="989" alt="Screenshot 2024-06-12 at 8 07 54 AM" src="https://github.com/bitwarden/clients/assets/8926729/a861cacd-45cf-4b02-b223-9e8dc23d8db3">
<img width="950" alt="Screenshot 2024-06-12 at 8 07 08 AM" src="https://github.com/bitwarden/clients/assets/8926729/bc9438fc-ecfa-40b4-be16-7b1a0a8f45f4">

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-12 19:31 UTC, Thomas-Avery requested changes
Looks good, one minor thing.

2024-06-12 19:31 UTC, Thomas-Avery commented on bitwarden_license/bit-web/src/app/secrets-manager/integrations/integrations.component.ts
We should add these new values to the tests in `bitwarden_license/bit-web/src/app/secrets-manager/integrations/integrations.component.spec.ts`. 

It is weird to me the current tests pass the `toEqual` must just check if the array of expected values is in the current array?

2024-06-12 23:56 UTC, differsthecat commented on bitwarden_license/bit-web/src/app/secrets-manager/integrations/integrations.component.ts
Fixed; I am seeing weird behavior with the tests, though that may be related to the weirdness you are seeing.
When running all locally, they all pass. When running just the tests for the integrations page, they fail as you would expect.

2024-06-13 19:08 UTC, Thomas-Avery approved these changes

2024-06-14 20:54 UTC, merged