[PM-5085] Create InputPasswordComponent
bitwarden/clients pull request #9630
Opened 2024-06-13 17:58 UTC by rr-bw

- **setup for InputPasswordComponent and basic story**
- **add all input fields**
- **add translated error messages**
- **update validation**
- **add password-callout**
- **update hint text**
- **use PolicyService in component**
- **setup SetPasswordComponent**
- **remove div**
- **add default button text**
- **add mocks for InputPassword storybook**
- **simplify ngOnInit**
- **change param and use PolicyApiService**
- **check for breaches and validate against policy**
- **user toastService**
- **use useValue for mocks**
- **hash before emitting**
- **validation cleanup and use PreloadedEnglishI18nModule**
- **add ngOnDestroy**
- **create validateFormInputsDoNotMatch fn**
- **update validateFormInputsComparison and add deprecation jsdocs**
- **rename validator fn**
- **fix bugs in validation fn**
- **cleanup and re-introduce services/logic**
- **toggle password inputs together**
- **update hint help text**
- **remove SetPassword test**

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-15 20:07 UTC, JaredSnider-Bitwarden requested changes
I've got some partial feedback from testing using this initially below!  The layout and form validation is working perfectly so far in all my tested scenarios. It's shaping up nicely!

2024-06-15 20:07 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/input-password/input-password.component.ts
> +    };
⚠️ after looking a bit more at the logic for the existing register component, I cannot make a user key without the masterKey, so this will have to return the master key and the master key hash. 

@jlf0dev, do you have any concerns with emitting the master key to the parent component?

2024-06-17 20:26 UTC, JaredSnider-Bitwarden requested changes
This is looking great! One tiny tweak and we are good to go!

2024-06-17 20:26 UTC, JaredSnider-Bitwarden commented on libs/auth/src/angular/input-password/input-password.stories.ts
> +      imports: [BrowserAnimationsModule],
⚠️ : There is a warning in the console which indicates that you should leverage `importProvidersFrom(BrowserAnimationsModule),` in the applicationConfig providers array instead of importing the `BrowserAnimationsModule` directly. 
<img width="1669" alt="image" src="https://github.com/bitwarden/clients/assets/116684653/7c65ed3c-fa9d-43fd-9150-1fe8645fc492">

2024-06-17 21:09 UTC, rr-bw commented on libs/auth/src/angular/input-password/input-password.stories.ts
> +      imports: [BrowserAnimationsModule],
Fixed [here](https://github.com/bitwarden/clients/pull/9630/commits/ea494acb5a83990b20db327d20dac6cf17786cbe#diff-c070cdea87f0ad10bcacf25fcde41b23700a742b0812f191a21aec89f742d371).

I also added a way to update the minimum password length help text for orgs that have a custom req (like we do on the RegisterForm component).

![Screenshot 2024-06-17 at 2 08 09 PM](https://github.com/bitwarden/clients/assets/102181210/4238d7eb-f811-4f24-bae4-3fb81e96d259)

2024-06-17 21:14 UTC, JaredSnider-Bitwarden approved these changes
Excellent work! 🚀

2024-06-17 21:56 UTC, merged