Restructure the `org-permissions` guard to be Angular 17+ compliant
bitwarden/clients pull request #9631
Opened 2024-06-13 18:18 UTC by addisonbeck

# Restructure the `org-permissions` guard to be Angular 17+ compliant

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/AC-2758

## 📔 Objective

In the web vault: in order to support Angular versions 17 and higher we must
restructure the way organization landing page URL redirects are written and
configured.

Currently most URL guards in the Bitwarden Angular clients are written as
router guard classes. The base `CanActivate` / `CanDeactivate` classes have
been deprecated by the Angular team and are subject to removal. See [the](https://angular.io/guide/deprecations#router-class-and-injectiontoken-guards-and-resolvers)
[Angular deprecation notice](https://angular.io/guide/deprecations#router-class-and-injectiontoken-guards-and-resolvers) for details.

At the time of writing, platform team has already completed this work for
their guards [here](https://bitwarden.atlassian.net/browse/PM-4349). Any guard declarations are swapped from exporting a
class to exporting a function, and the function is added to CanActivate
arrays in routers the same way the classes already are. There are some other
guards that are already function based scattered throughout the codebase that
can also be used as examples for style, like [auth team's lock guard](https://github.com/bitwarden/clients/blob/1aaa88a64d4d48aa75868980eb4c280b672057c3/libs/angular/src/auth/guards/lock.guard.ts).

This PR achieves this goal for the `org-permissions` guard.

This change should result in no functional changes to the system. It is
purely a code restructure to comply with a deprecation in Angular.

This ticket applies to urls that are:
1. Subroutes of `<https://THE_WEB_VAULT/organizations/{id}/>`
1. `<https://THE_WEB_VAULT/sm/settings/import>`
1. `<https://THE_WEB_VAULT/sm/settings/export>`

> ℹ️ There are many subroutes of organizations/{id}, too many to list at
> once and test individually. If specific examples are needed for testing
> please reach out to development.

For URLs that are subject to this guard the following rules apply:
1. If the organizationId route parameter is not set or is not valid for the
user then the user is redirected to /
1. There is a special case to support linkable ciphers. If the user fails the
permission check, meaning they can not access the admin console, but a cipher
id is found in the route parameters the user is redirected to /vault
with the item id passed along.
1. If the required permissions are found navigation proceeds as normal. If the
required permissions are not found the user should be redirected to
/organizations/{id} or / depending on whether or not they have access to
the admin console at all.

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-14 02:28 UTC, eliykat requested changes
Great job with these @addisonbeck 👏

2024-06-14 02:28 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/guards/org-permissions.guard.ts
> +      platformUtilsService.showToast("error", null, i18nService.t("organizationIsDisabled"));
While we're here, please replace this with the newer `ToastService` from the CL.

2024-06-14 02:28 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/guards/org-permissions.guard.ts
> +      platformUtilsService.showToast("error", null, i18nService.t("accessDenied"));
And here

2024-06-14 02:28 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/reporting/organization-reporting-routing.module.ts
> +        canActivate: [organizationPermissionsGuard((org: Organization) => org.canAccessEventLogs)],
nit: explicit typing of `Organization` is probably unnecessary here now that the function parameter is typed. (And in other locations - doesn't really matter though, your call.)

2024-06-14 02:28 UTC, eliykat commented on apps/web/src/app/admin-console/organizations/guards/org-permissions.guard.spec.ts
> -    organizationPermissionsGuard = new OrganizationPermissionsGuard(
Above this, line ~45: old reference to `data.organizationPermissions`.

2024-06-15 19:21 UTC, addisonbeck commented on apps/web/src/app/admin-console/organizations/guards/org-permissions.guard.ts
> +      platformUtilsService.showToast("error", null, i18nService.t("organizationIsDisabled"));
Implemented as suggested on https://github.com/bitwarden/clients/pull/9631/commits/30a200b6c8d581b15a4f7df524c51ccf28e85c8c

2024-06-15 19:21 UTC, addisonbeck commented on apps/web/src/app/admin-console/organizations/guards/org-permissions.guard.ts
> +      platformUtilsService.showToast("error", null, i18nService.t("accessDenied"));
Implemented as suggested on https://github.com/bitwarden/clients/pull/9631/commits/30a200b6c8d581b15a4f7df524c51ccf28e85c8c

2024-06-15 19:22 UTC, addisonbeck commented on apps/web/src/app/admin-console/organizations/reporting/organization-reporting-routing.module.ts
> +        canActivate: [organizationPermissionsGuard((org: Organization) => org.canAccessEventLogs)],
No complaints from me, I agree this level of verbosity is not really needed. Implemented as suggested on https://github.com/bitwarden/clients/pull/9631/commits/8d98a93bf758e1d8415ef10d3febfb35c80bdd4f

2024-06-15 19:22 UTC, addisonbeck commented on apps/web/src/app/admin-console/organizations/guards/org-permissions.guard.spec.ts
> -    organizationPermissionsGuard = new OrganizationPermissionsGuard(
Removed on https://github.com/bitwarden/clients/pull/9631/commits/caa1b7aad302a7f8667d2c68959393b916df7b22

2024-06-16 22:04 UTC, eliykat approved these changes

2024-06-17 21:46 UTC, Thomas-Avery approved these changes
SM changes LGTM

2024-06-21 14:43 UTC, amorask-bitwarden submitted a review, later dismissed

2024-06-24 20:01 UTC, shane-melton approved these changes
Vault change looks good!

2024-06-25 20:58 UTC, djsmith85 commented
@addisonbeck Conflict was created by merging https://github.com/bitwarden/clients/pull/9741:

`apps/web/src/app/admin-console/organizations/tools/vault-export/org-vault-export-routing.module.ts` has been deleted and the "export"-route has been moved into `apps/web/src/app/admin-console/organizations/settings/organization-settings-routing.module.ts`

2024-06-26 22:22 UTC, eliykat approved these changes

2024-07-01 21:49 UTC, addisonbeck commented
@eliykat @shane-melton @amorask-bitwarden @Thomas-Avery Hey folks! This passed QA and I'm ready to get it merged, if you wouldn't mind giving it another stamp. Nothing changed during QA besides keeping the branch up to date with `main`. Thank you!

2024-07-02 14:03 UTC, cturnbull-bitwarden approved these changes

2024-07-02 14:53 UTC, merged