[PM-8805] migrate cli to generator libraries
bitwarden/clients pull request #9637
Opened 2024-06-13 20:56 UTC by audrey-jensen

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-8805

## 📔 Objective

Replace dependencies on `@bitwarden/common/tools/generator` with `@bitwarden/generator-core` and `@bitwarden/generator-extensions` so that the common code can be deleted.

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-13 22:26 UTC, JaredSnider-Bitwarden submitted a review, later dismissed
Auth file change looks good!

2024-06-17 11:27 UTC, djsmith85 requested changes
Nice work! Only one minor thing and this is good to go

2024-06-17 11:27 UTC, djsmith85 commented on apps/cli/src/tools/generate.command.ts
> +import { StateService } from "@bitwarden/common/src/platform/abstractions/state.service";
:x: This import shouldn't change

2024-06-17 13:39 UTC, audrey-jensen commented on apps/cli/src/tools/generate.command.ts
> +import { StateService } from "@bitwarden/common/src/platform/abstractions/state.service";
The `StateService` import?

2024-06-20 18:15 UTC, audrey-jensen commented on apps/cli/src/tools/generate.command.ts
> +import { StateService } from "@bitwarden/common/src/platform/abstractions/state.service";
Resolved in 04dafeccc.

2024-06-20 20:17 UTC, djsmith85 approved these changes

2024-06-24 21:08 UTC, closed without merging