[PM-8868] only deserialize org invite if not nullish
bitwarden/clients pull request #9644
Opened 2024-06-14 12:14 UTC by jlf0dev

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-8868
## 📔 Objective

I forgot to add a `null` check before deserializing org invites from state, meaning that the deserializer simply returned `{}` when the observable emitted a `null` state. 

This was problematic because `{}` isn't caught by our regular `null` checks and the application thought there was a stored org invite...when there wasn't.

I also took the opportunity to clean up some types on our key definitions and do the same null check for the device key (`SymmetricCryptoKey.fromJson` should return `null` but I figured it didn't hurt to be explicit since we don't own that code).
## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-14 16:29 UTC, ike-kottlowski approved these changes

2024-06-17 23:04 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/organization-invite/accept-organization.service.ts
> +    deserializer: (invite) => (invite ? OrganizationInvite.fromJSON(invite) : null),
@jlf0dev 
Question: why not update the OrganizationInvite method to simply return null if the JSON is null?

```TypeScript
static fromJSON(json: Jsonify<OrganizationInvite>) {
    if (json == null) {
      return null;
    }

    return Object.assign(new OrganizationInvite(), json);
  }
```

I saw this approach used elsewhere in code.

2024-06-17 23:04 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/organization-invite/accept-organization.service.ts
> +    deserializer: (invite) => (invite ? OrganizationInvite.fromJSON(invite) : null),
I also tested it and confirmed it fixed the issue

2024-06-25 12:30 UTC, jlf0dev commented on apps/web/src/app/auth/organization-invite/accept-organization.service.ts
> +    deserializer: (invite) => (invite ? OrganizationInvite.fromJSON(invite) : null),
Good idea, I left the above code just in case. I feel like I always forget that these deserializers will emit `null` and don't want others to make the same mistake.

2024-06-25 14:23 UTC, JaredSnider-Bitwarden requested changes
Nice work on cleaning up these types. Just a few small things I saw below!

2024-06-25 14:23 UTC, JaredSnider-Bitwarden commented on libs/auth/src/common/services/login-strategies/login-strategy.state.ts
⚠️ : I confirmed with platform that technically state provider returns null if a value has not been set - not undefined.

2024-06-25 14:23 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/auth/organization-invite/organization-invite.ts
nitpick but since you modified the return type elsewhere figured I would mention:  Should we add returns to the modified methods and add `OrganizationInvite | null`?

2024-06-25 14:23 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/device-trust.service.implementation.ts
> +    deserializer: (shouldTrustDevice) => shouldTrustDevice ?? false,
⚠️ : this will break the existing logic in the `setRememberDeviceDefaultValue()` method in the `BaseLoginDecryptionOptionsComponent` which uses null to properly initialize the product required default value of true when it is not set.

2024-06-25 18:46 UTC, jlf0dev commented on libs/auth/src/common/services/login-strategies/login-strategy.state.ts
fixed!

2024-06-25 18:46 UTC, jlf0dev commented on apps/web/src/app/auth/organization-invite/organization-invite.ts
fixed!

2024-06-25 18:47 UTC, jlf0dev commented on libs/common/src/auth/services/device-trust.service.implementation.ts
> +    deserializer: (shouldTrustDevice) => shouldTrustDevice ?? false,
Really glad you caught this, I should know better than to assume making these kind of changes are ok. I've reverted this and my key connector additions.

2024-06-25 18:48 UTC, JaredSnider-Bitwarden commented on libs/common/src/auth/services/device-trust.service.implementation.ts
> +    deserializer: (shouldTrustDevice) => shouldTrustDevice ?? false,
All good! Glad I spotted it! I attempted to vet the key connector change, and it looked harmless enough but I agree w/ the decision to revert those just in case!

2024-06-25 18:49 UTC, JaredSnider-Bitwarden approved these changes
Ship it 🚀 🌔 !

2024-06-25 19:00 UTC, merged