migrate desktop to generator libraries
bitwarden/clients pull request #9662
Opened 2024-06-14 18:39 UTC by audrey-jensen

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-8807

## 📔 Objective

Replace dependencies on `@bitwarden/common/tools/generator` with `@bitwarden/generator-core` and `@bitwarden/generator-extensions` so that the common code can be deleted.

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-14 18:41 UTC, ike-kottlowski submitted a review, later dismissed

2024-06-17 11:51 UTC, djsmith85 approved these changes

2024-06-17 11:52 UTC, djsmith85 requested changes
All reviewed changes are looking good, just seen that one test is failing

2024-06-18 08:13 UTC, djsmith85 submitted a review, later dismissed
Changes are looking good, just one small conflict likely introduced by https://github.com/bitwarden/clients/pull/9690

2024-06-18 08:13 UTC, djsmith85 commented on apps/desktop/src/app/tools/generator.component.spec.ts
> +          useValue: mock<typeof PasswordGenerationServiceAbstraction>(),
❓ Do we still need typeof here as it's now directly imported?

2024-06-20 18:13 UTC, audrey-jensen commented on apps/desktop/src/app/tools/generator.component.spec.ts
> +          useValue: mock<typeof PasswordGenerationServiceAbstraction>(),
Resovled in b5e317ab.

2024-06-20 20:19 UTC, djsmith85 approved these changes

2024-06-21 15:41 UTC, ike-kottlowski approved these changes

2024-06-24 21:08 UTC, closed without merging