Auth/pm 6789/rc version legacy migration fix
bitwarden/clients pull request #9714
Opened 2024-06-18 16:35 UTC by jlf0dev

Copied from #9498, we unfortunately had key rotation changes that were merged immediately after `rc` was cut. This is a blocker for our release, so I have created a branch off the original work and rebased it on `rc`, without the new key rotation changes.

Everything should be the exact same as #9498, before commit 20b5edca6dfe7a20729b9f782b52805f02777d9a. Which means everything was previously pre-approved (even though I may not be able to prove it 😞).

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-6789
## 📔 Objective

Fixes legacy user migration by using the legacy key for private key re-encryption.

I took the chance to finish distributing key rotation logic to each domain using an interface.
## 📸 Screenshots

https://github.com/bitwarden/clients/assets/24985544/48c0d98f-4625-4de5-8f6e-7f634f2568ea

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-18 18:24 UTC, audrey-jensen requested changes
Sorry, just noticed a problem on the RC PR that also applies to this one.

2024-06-18 18:24 UTC, audrey-jensen commented on libs/common/src/tools/send/services/send.service.spec.ts
> +    it("throws if the original user key is null", async () => {
⚠️ The return value of `getRotatedData` is no longer tested. Please restore that test.

2024-06-18 18:25 UTC, audrey-jensen requested changes

2024-06-18 18:25 UTC, audrey-jensen commented on libs/common/src/tools/send/services/send.service.spec.ts
> +    it("throws if the original user key is null", async () => {
⚠️ The return value of `getRotatedData` is no longer tested. Please restore that test.

2024-06-18 18:40 UTC, jlf0dev commented on libs/common/src/tools/send/services/send.service.spec.ts
> +    it("throws if the original user key is null", async () => {
Please see b36e5ca225d6e00db20ae4a49f32ce38b970c282

2024-06-18 18:44 UTC, audrey-jensen commented on libs/common/src/tools/send/services/send.service.spec.ts
> +    it("throws if the original user key is null", async () => {
Perfect!

2024-06-18 18:45 UTC, audrey-jensen approved these changes

2024-06-18 19:43 UTC, JaredSnider-Bitwarden approved these changes

2024-06-18 20:02 UTC, addisonbeck approved these changes

2024-06-19 07:05 UTC, coroiu approved these changes

2024-06-20 13:15 UTC, Jingo88 approved these changes

2024-06-20 13:16 UTC, merged