[PM-7161] browser v2 view container
bitwarden/clients pull request #9723
Opened 2024-06-18 21:01 UTC by Jingo88

## 🎟️ Tracking

[PM-7161](https://bitwarden.atlassian.net/browse/PM-7161)

## 📔 Objective

Create a dynamic container for an item's view. Including the reusable components

- Dynamic header for item types
- Added a `slot=end` to the platform popup footer
- Word wrapping for long values
- Copy function for copy icon + Copy toasts
- Dynamic show/hide function and icon in case user has multiple hidden values in Custom Fields
- Download function for attachments + download spinner + Error toasts for downloads not working
- Password history link if more than one password change
- Edit button leads to edit container
- Delete icon hides if user does not have edit access 

Notes: 
- Animations for this container will get their own ticket
- Screen Reader functionality for this container will get it's own ticket
- Password history container will get it's own ticket - linked to the new component being created here [PM-8277](https://bitwarden.atlassian.net/browse/PM-8277)

## 📸 Screenshots

![PM-7161-details-note](https://github.com/bitwarden/clients/assets/8302660/7e518a8f-b608-4c29-9eec-c1fd703c5cc7)

![PM-7161-custom-fields](https://github.com/bitwarden/clients/assets/8302660/db327c54-c112-4c37-a867-4bd88bd5f6d5)

![PM-7161-attachments-history](https://github.com/bitwarden/clients/assets/8302660/02dfd8d5-2e15-45b5-9001-17d2f65913e7)

## Screen Recording

https://github.com/bitwarden/clients/assets/8302660/6345cb01-78c3-4749-a107-eb0f6e26c267

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-18 22:02 UTC, shane-melton requested changes
I think the separation of sections into their own components is looking great! Nice work!

We do need to make sure we're using the CL components wherever possible however so the new styles are applied with the CL team's style feature branch work. We should also avoid adding to the `scss` styles if possible.

2024-06-19 18:14 UTC, nick-livefront requested changes
I tried not to overlap @shane-melton's feedback, I apologize if I did. 

As I'm working through the `attachments` work I wonder if we can create a single download-attachments component to handle all of the logic there. Maybe I'll think about that as a refactor. No need to hold this work up for that.

2024-06-19 18:14 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault-v2/view/custom-fields/custom-fields-v2.component.html
> +          <i (click)="copy(field.value)" class="bwi bwi-clone bwi-fw"></i>
❌ Another instance of `bitIconButton`? Maybe there is another way of implementing it with the `i` that I'm not aware of!

2024-06-19 18:14 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault-v2/view/custom-fields/custom-fields-v2.component.ts
> +  hiddenFields: any = {};
❓ Is this really `any`? The answer could be yes! The use of `any` just flags in my mind.

2024-06-19 18:14 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault-v2/view/custom-fields/custom-fields-v2.component.ts
> +        if (field.type === 1) {
:art: The `FieldType` enum can be used here

```suggestion
        if (field.type === FieldType.Hidden) {
```

2024-06-19 18:14 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault-v2/view/custom-fields/custom-fields-v2.component.ts
> +    if (linkedId === 101) {
🎨 The `LinkedIdType` enum in tandem of `LoginLinkedId` enum can replace the hardcoded values

```suggestion
  getLinkedType(linkedId: LinkedIdType) {
    if (linkedId === LoginLinkedId.Username) {
      return this.i18nService.t("username");
    }

    if (linkedId === LoginLinkedId.Password) {
```

2024-06-24 22:29 UTC, Jingo88 commented on apps/browser/src/vault/popup/components/vault-v2/view/additional-information/additional-information-v2.component.html
> +      <input type="text" [value]="notes" readonly aria-readonly="true" />
hm would a <p> tag work better here? Looks like I'll need to add several tailwind classes and attrs to remove the border and other things of the textarea

2024-06-26 17:56 UTC, shane-melton requested changes
I think this is pretty close now! Thanks for making all the changes! Just one small issue with the `popup-*` layout components being used within the shared cipher view component. Otherwise, some minor suggestions to use the `bit-section` and `bit-section-header` CL components.

Also, hopefully we can get/create some type of `bit-display-field` CL component to reduce some of the style repetition at some point in the future.

2024-06-26 17:56 UTC, shane-melton commented on libs/angular/src/directives/copy-click.directive.ts
> +  @Input("appCopyToastMessage") toastMessage?: string;
👍 Nice add!

2024-06-26 17:56 UTC, shane-melton commented on libs/vault/src/cipher-view/additional-information/additional-information.component.html
> +    <label class="tw-text-xs tw-text-muted tw-select-none">
🎨 We might want to look at adding some type of `bit-display-field` component to the CL to be used here so we don't have to repeat this pattern everywhere with explicit tailwind classes. We can iron that out more with @willmartian.

2024-06-26 17:56 UTC, shane-melton commented on libs/vault/src/cipher-view/attachments/attachments-v2.component.html
> +<div class="tw-mb-6">
🎨 We can use the `bit-section` along with the `bit-section-header` and it will automatically apply the correct padding/margins. ([docs here](https://components.bitwarden.com/?path=/docs/component-library-section--docs#section-header-padding))

2024-06-26 17:56 UTC, shane-melton commented on libs/vault/src/cipher-view/cipher-view.component.html
⚠️ We can't have the `popup-page` and `popup-header` within this component as it will eventually be used outside of the Browser extension context. This component should contain the list of sub-sections and we should have a separate wrapper component in the Browser project that has the `popup-page` layout details.

2024-06-26 17:56 UTC, shane-melton commented on libs/vault/src/cipher-view/custom-fields/custom-fields-v2.component.html
> +<div class="tw-mb-6">
🎨 We can use `bit-section` and `bit-section-header` here as well.

2024-06-26 17:56 UTC, shane-melton commented on libs/vault/src/cipher-view/custom-fields/custom-fields-v2.component.html
> +      [class.tw-mb-4]="!last"
🎨 We should be able to simplify this a bit with this syntax:
```suggestion
      [class]="{'tw-boder-0 tw-border-b tw-border-solid tw-pb-2 tw-mb-4': !last}"
```

2024-06-26 17:56 UTC, shane-melton commented on libs/vault/src/cipher-view/custom-fields/custom-fields-v2.component.html
> +            [appCopyToastMessage]="'copySuccessful' | i18n"
💭 Maybe we can make the toast message and variant inputs default to these values and have a boolean option to show the toast or not. Would hopefully avoid a lot of this repetition.

2024-06-26 17:56 UTC, shane-melton commented on libs/vault/src/cipher-view/item-details/item-details-v2.component.html
> +<div class="tw-mb-6">
🎨 We can use `bit-section` and `bit-section-header`

2024-06-26 17:56 UTC, shane-melton commented on libs/vault/src/cipher-view/item-history/item-history-v2.component.html
> +<div class="tw-mb-6">
🎨 `bit-section` and `bit-section-header`

2024-06-26 21:26 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/view-v2/view-v2.component.ts
> +    // FIXME: Verify that this floating promise is intentional. If it is, add an explanatory comment and ensure there is proper error handling.
⛏️ We can either `await` or `void` this navigation to get ride of this FIXME.

2024-06-26 21:26 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/view-v2/view-v2.component.ts
> +    this.route.queryParams.pipe(takeUntilDestroyed()).subscribe(async (params) => {
🎨 We can avoid the `async` subscribe warning by using a `switchMap` to call `getCipherData` and have that return the cipher which we can then assign in the non-async subscribe. (we could also move the call to `setHeader() into the subscribe block as well)

2024-06-26 21:26 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/view-v2/view-v2.component.ts
> +  deleteCipher() {}
⚠️ Not sure if we have another ticket to implement the `deleteCipher` logic, but wanted to call out that its missing currently.

2024-06-26 21:26 UTC, shane-melton commented on libs/angular/src/directives/copy-click.directive.ts
> +  @Input("appCopyShowSuccessToast") showToast?: boolean;
⛏️  Using `coerceBooleanProperty` would allow us to avoid explicitly setting the value to `true`
```ts
  @Input({transform: coerceBooleanProperty}) showToast?: boolean;
```

```html
<button [appCopyClick]="'some-value'" showToast></button>
```

2024-06-26 22:19 UTC, Jingo88 commented on apps/browser/src/vault/popup/components/vault-v2/view-v2/view-v2.component.ts
> +  deleteCipher() {}
oh I was planning to add that later. but I can add it now.

2024-06-26 23:19 UTC, shane-melton commented on libs/vault/src/cipher-view/custom-fields/custom-fields-v2.component.html
> +    <h5 class="tw-pl-2 tw-font-bold tw-text-headers tw-mb-2">{{ "customFields" | i18n }}</h5>
❓ Could we use `bitTypography="h5"` or do we need the custom classes here?

2024-07-08 21:14 UTC, shane-melton reviewed
This is looking great! Just a few last remaining comments/questions!

2024-07-08 21:14 UTC, shane-melton commented on libs/vault/src/services/password-reprompt.service.ts
> +    if (cipher.reprompt === CipherRepromptType.None || passwordReprompted) {
🎨  I don't think we need to pass in `passwordReprompted` here since we simply just return early when its true and  do no other checks / logic with it. We can just have the caller `OR` the result of `promptPasswordCheck()` with `passwordReprompted` instead of doing it inside the method.

2024-07-08 21:14 UTC, shane-melton commented on libs/vault/src/services/password-reprompt.service.ts
> +  async promptPasswordCheck(cipher: CipherView, passwordReprompted: boolean) {
💭 I see you're trying to reduce the need to check the `CipherRempromptType` every time we need to call `showPasswordPrompt` which I really like 👍 . I'm just slightly concerned this name doesn't really clarify the difference between `showPasswordPrompt` vs `promptPasswordCheck`.

2024-07-08 21:14 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/view-v2/view-v2.component.html
> +      (click)="delete()"
⛏️ We would get some spinner animations for free by using `[bitAction]` instead of a `(click)` handler.

2024-07-08 21:52 UTC, danielleflinn commented on libs/vault/src/cipher-view/attachments/attachments-v2.component.html
> +    <h6 bitTypography="h6">{{ "attachments" | i18n }}</h6>
That's correct; we want this to be semantically `<h2>` styled with the `bit-typography="h6"`.

2024-07-09 18:34 UTC, shane-melton approved these changes
Great work on this! 

I do think we'll have some clean up work to do once the `bit-display-field` is available, but I think we're okay to merge this as-is for now.

2024-07-09 19:49 UTC, nick-livefront approved these changes

2024-07-09 21:39 UTC, willmartian approved these changes
LGTM! Thanks

2024-07-10 04:11 UTC, merged