[PM-7897] Attachments Part 2
bitwarden/clients pull request #9755
Opened 2024-06-20 19:20 UTC by nick-livefront

Stacked on top of https://github.com/bitwarden/clients/pull/9715

## 🎟️ Tracking

[PM-7897](https://bitwarden.atlassian.net/browse/PM-7897)

## 📔 Objective

Following up on https://github.com/bitwarden/clients/pull/9715 and closing out the ticket
- Navigate the user back to the edit screen after uploading an attachment
- Allow for downloading an attachment
- Allow for deleting an attachment
- Link to the "edit cipher" screen
  - This can get refactored into its own location when the edit container is built out.
  - Links to the premium page if the user doesn't have access to attachments
  - Show error message for attachments that are assigned to a free organization.
    - This works in the current extension but I can't figure out how 🙃 I left a question in the code.

## 📸 Screenshots

|Download/Delete|Premium Redirect|~~Free Org Error~~ Old, see https://github.com/bitwarden/clients/pull/9755#discussion_r1648966969|
|-|-|-|
| <video src="https://github.com/bitwarden/clients/assets/125900171/302959ab-f706-4616-868a-ce7fd6bc690b" />|<video src="https://github.com/bitwarden/clients/assets/125900171/1ccb4255-bb70-44e9-b583-1bfdfbe5826d" />|<video src="https://github.com/bitwarden/clients/assets/125900171/e04dd6e1-3e02-448a-8ff8-6163a20bf918" />|

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

[PM-7897]: https://bitwarden.atlassian.net/browse/PM-7897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-06-21 13:27 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/cipher-attachments.component.ts
> +      if (e.message === "This organization cannot use attachments.") {
This doesn't feel like the right path, but it works. 

The current extension throws this error and shows the toast but I for the life of me couldn't find out where in the codebase that logic was. It appears that the message is coming from the API message because I can't find it in the translations anywhere. Any advice?

2024-06-25 22:53 UTC, shane-melton requested changes
This also looks great! There is one issue with navigation history that we'll want to get fixed. Otherwise, I just had a few suggestions that I think could make better use of our existing CL components and async actions.

2024-06-25 22:53 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/cipher-attachments.component.html
> +    <bit-card class="tw-flex tw-justify-between tw-mb-2">
🎨 I missed this in my Part 1 review, but we could use [`bit-item` component ](https://components.bitwarden.com/?path=/docs/component-library-item--docs) here instead and would likely avoid the need for as many explicit tailwind classes.

2024-06-25 22:53 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/download-attachment/download-attachment.component.html
> +  [loading]="downloading"
🎨 We can use the standalone `[bitAction]` instead to avoid having to track the loading state ourselves. It also already handles preventing duplicate submissions/clicks when something is inflight.

2024-06-25 22:53 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/download-attachment/download-attachment.component.html
> +  [title]="'downloadAttachmentName' | i18n: attachment.fileName"
⛏️ `appA11yTitle` should already take care of setting the `title` attribute for us.

2024-06-25 22:53 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/delete-attachment/delete-attachment.component.html
🎨 Same as the download button, we can use `[bitAction]` instead and `[appA11yTitle]` should take care of `title` for us automatically.

2024-06-25 22:53 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/cipher-attachments.component.ts
> +      if (e.message === "This organization cannot use attachments.") {
Yeah, this is a hard coded error message returned by the server if the organization does not have attachment storage configured (typically the case for Free Organizations, but I don't know if we can guarantee that is always the case).

I wonder if it would be better to simply replace the upload form section with a warning/message stating that free orgs (or at least the cipher's organization) are not allowed to upload attachments instead. It avoids the user going through the trouble of finding a file and sending it to the server and then getting denied.

@danielleflinn How would you feel about this?

2024-06-25 22:53 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/attachments/attachments-v2.component.ts
> +    this.router.navigate(["/edit-cipher"], {
⚠️ We'll need to be careful here with the browser's location history here. Because we navigated to the attachment page and completed the action, we'll want to remove it from the history so the back button on the edit page goes back to the view page instead of the attachment page again.

2024-06-25 22:53 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/attachments/attachments-v2.component.ts
> +    this.router.navigate(["/edit-cipher"], {
⛏️ We can use `void this.router.navigate(...)` to stop eslint from complaining instead of disabling it with a comment.

2024-06-25 22:53 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.ts
> +      const isNew = params.isNew?.toLowerCase() === "true";
📝  This is going to conflict with changes coming in #9758 where a `mode` is being introduced.

2024-06-26 14:22 UTC, danielleflinn commented on apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/cipher-attachments.component.ts
> +      if (e.message === "This organization cannot use attachments.") {
I'd had this alternative design for this flow: https://www.figma.com/design/gbRu9aGoIZFdmcc6WKis4k/Add%2FEdit-item?node-id=764-42529&t=bygX3b0DKBTmF4AX-4

But I'd left it out to reduce scope, would that be something we'd want to implement now?

2024-06-26 17:12 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/cipher-attachments.component.ts
> +      if (e.message === "This organization cannot use attachments.") {
@shane-melton @danielleflinn As an in-between I can show the error toast with the current text from the API rather than replacing it?

2024-06-26 17:21 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/cipher-attachments.component.html
> +    <bit-card class="tw-flex tw-justify-between tw-mb-2">
🙇 Thank you for pointing that out! [8925fbd](https://github.com/bitwarden/clients/pull/9755/commits/8925fbd5764422f08a31b82f01d0a30be34cabe9)

2024-06-26 17:21 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/download-attachment/download-attachment.component.html
> +  [loading]="downloading"
🚀 [b279db9](https://github.com/bitwarden/clients/pull/9755/commits/b279db9c9e7e2afc7852ca4677d5d02a7404d969)

2024-06-26 17:22 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/download-attachment/download-attachment.component.html
> +  [title]="'downloadAttachmentName' | i18n: attachment.fileName"
:rocket: [57539ab](https://github.com/bitwarden/clients/pull/9755/commits/57539ab98d7a28c0afeca5fce6d7f9e9b7e1ddf0)

2024-06-26 17:22 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/delete-attachment/delete-attachment.component.html
Fixed in [b279db9](https://github.com/bitwarden/clients/pull/9755/commits/b279db9c9e7e2afc7852ca4677d5d02a7404d969) & [57539ab](https://github.com/bitwarden/clients/pull/9755/commits/57539ab98d7a28c0afeca5fce6d7f9e9b7e1ddf0)

2024-06-26 17:22 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault-v2/attachments/attachments-v2.component.ts
> +    this.router.navigate(["/edit-cipher"], {
Good callout, I fixed avoided this issue by using `replaceUrl` which seems to do the trick based on my testing! [f41f2de](https://github.com/bitwarden/clients/pull/9755/commits/f41f2ded32d4cbc2af4f2538b66cb622aeb69df9)

2024-06-26 17:39 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/cipher-attachments.component.ts
> +      if (e.message === "This organization cannot use attachments.") {
@danielleflinn I was thinking that instead of showing the new "Free organizations"  text, I could use the current implementation and the toast would read: "This organizaiton"

But I could also put logic before they user gets the attachments screen as you suggested! (I like that better)
Would that conflict with the "Premium" state [here](https://www.figma.com/design/gbRu9aGoIZFdmcc6WKis4k/Add%2FEdit-item?node-id=760-37026&t=u241K52aazwi08nE-4)? Correct me if I'm misunderstanding some product level details here!

2024-06-26 17:59 UTC, danielleflinn commented on apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/cipher-attachments.component.ts
> +      if (e.message === "This organization cannot use attachments.") {
Ok yeah I like the simplicity of moving the error up vs. changing the text / revamping the full ui. Let's do that if it is possible. 

It shouldn't conflict with the Premium state (our product level details are a bit complex though, I'll do my best to explain the possible scenarios here). The Premium state is only showed on items owned by a Free **Users**, and this error should only be shown on items that are owned by a Free **Organizations**.

Basically we would need something like the following logic when the user selects the "Attachements" link:

- Is item owned by a free user (is Premium badge present)?
- Yes, ->  show upgrade prompt
- No,  ->  is item owned by **free** organization?
  - Yes, ->  show error toast and don't navigate user to the attachments page
- Else ->  navigate user to the Attachments page 
(Item is either owned by user who has an individual Premium subscription, or a Premium subscription paid for by an organization, OR item is owned by a PAID organization. All 3 of these scenarios includes access to Attachments)

Let me know if you run into any issues with the proposed new solution and we can look at adjusting again.

2024-06-26 18:15 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/cipher-attachments.component.ts
> +      if (e.message === "This organization cannot use attachments.") {
Thanks @danielleflinn for laying that out! It helps a ton 🙇

2024-06-26 18:23 UTC, shane-melton approved these changes
Awesome work! Just two last minute optional comments/suggestions, but I think this looks good to go as is too.

2024-06-26 18:23 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/cipher-attachments.component.html
> +    <bit-item>
💭 Not sure if its needed here, but there is a `bit-item-group` component. Not 100% sure what it would get us though 🤔 ([docs](https://components.bitwarden.com/?path=/docs/component-library-item--docs#item-groups))

2024-06-26 18:23 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/attachments/open-attachments/open-attachments.component.html
🎨 💭 This is likely fine, but I think we could also use the `bit-item` here as well as its just a card under the hood and has slots for the "end" and supports having a full width button as `bit-item-content`. ([docs](https://components.bitwarden.com/?path=/docs/component-library-item--docs#primary-content))

2024-06-26 18:43 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/cipher-attachments.component.html
> +    <bit-item>
I think we'd be losing something sadly. Accessibility wise, a screen reader user would lose the context that it's a list & how many items are within it upon entering the element. 

I think it's a good idea to stick with `ul` & `li` here.

2024-06-26 19:06 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/cipher-attachments.component.ts
> +      if (e.message === "This organization cannot use attachments.") {
@shane-melton @danielleflinn 

Double checking, this is the expected experience?

https://github.com/bitwarden/clients/assets/125900171/70e2164b-ae31-4fdb-add4-bbb5b2172c63

2024-06-26 20:52 UTC, danielleflinn commented on apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/cipher-attachments.component.ts
> +      if (e.message === "This organization cannot use attachments.") {
Looks great! Thanks Nick

2024-06-26 21:03 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault-v2/attachments/open-attachments/open-attachments.component.html
🥳 Consistency! [22d6601](https://github.com/bitwarden/clients/pull/9755/commits/22d66012e8bb6c9843b827a42912fe632e34121e)

2024-06-26 21:42 UTC, danielleflinn approved these changes

2024-06-26 21:44 UTC, shane-melton approved these changes
Looks great!

2024-06-26 21:44 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/cipher-attachments.component.ts
> -      if (e.message === "This organization cannot use attachments.") {
🎉

2024-06-26 21:45 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/cipher-attachments.component.html
> +    <bit-item>
Totally fair point!

2024-06-26 21:51 UTC, merged