PM-4661: Add passkey.username as item.username
bitwarden/clients pull request #9756
Opened 2024-06-20 19:26 UTC by abergs

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-20 20:45 UTC, gbubemismith approved these changes
LGTM! Thanks for working on this @abergs

2024-06-20 20:54 UTC, justindbaur reviewed
Couple questions.

2024-06-20 20:54 UTC, justindbaur commented on libs/common/src/platform/services/fido2/fido2-authenticator.service.ts
> +        userName: params.userEntity.name,
Is there any chance that `name` is `null` but `displayName` isn't so we'd want to do something like `params.userEntity.name ?? params.userEntity.displayName`?

2024-06-20 20:54 UTC, justindbaur commented on apps/browser/src/vault/popup/components/vault/add-edit.component.ts
> +      }
Could this be added in the below if block and guarded to only respect it if `this.cipher.login.username` is null or empty like the other ones? If the user has something saved it should always take precedence right? (I get that this param is brand new and only used for a brand new cipher but gotta defend against the future)

2024-06-21 06:15 UTC, abergs commented on libs/common/src/platform/services/fido2/fido2-authenticator.service.ts
> +        userName: params.userEntity.name,
Nope, name is required, but display name is not.

2024-06-24 10:25 UTC, LRNcardozoWDF submitted a review, later dismissed
LGTM!

2024-06-24 10:27 UTC, abergs commented on libs/common/src/platform/services/fido2/fido2-authenticator.service.ts
> +        userName: params.userEntity.name,
right @coroiu?

2024-06-24 10:28 UTC, abergs commented on apps/browser/src/vault/popup/components/vault/add-edit.component.ts
> +      }
Was there any reason to resolving this @merissaacosta?

2024-06-24 10:41 UTC, abergs commented
@kendratodd Perhaps you could help me test this unless it lands well into existing QA processes?

2024-06-24 18:21 UTC, kendratodd commented
@abergs, I'm always happy to take a look, though I do believe this can be covered by existing QA processes for the Vault team (the JIRA just needs to be updated to reflect the current status).

2024-06-25 08:43 UTC, coroiu commented on libs/common/src/platform/services/fido2/fido2-authenticator.service.ts
> +        userName: params.userEntity.name,
Correct.

Technically both are `required`, but the spec allows setting the `displayName` to an empty string ([spec](https://www.w3.org/TR/webauthn-3/#dictionary-user-credential-params)), which is not allowed for `name` ([spec](https://www.w3.org/TR/webauthn-3/#dictionary-pkcredentialentity))

2024-06-25 08:44 UTC, coroiu commented on apps/browser/src/vault/popup/components/fido2/fido2.component.ts
>        // PM-4577 - https://github.com/bitwarden/clients/pull/8746
@gbubemismith should this comment be removed?

2024-06-25 08:48 UTC, coroiu commented on apps/browser/src/vault/popup/components/vault/add-edit.component.ts
> +      }
Unresolving, I agree that this should be addressed, we really shouldn't be overwriting usernames. I'm even hesitant to assign it even it was empty, since in some edge cases sites might not have a username

2024-06-25 08:50 UTC, coroiu requested changes
Tests failing and needs fix for comment from @justindbaur

2024-06-25 10:04 UTC, abergs commented on apps/browser/src/vault/popup/components/vault/add-edit.component.ts
> +
@coroiu @justindbaur as per the feedback, is this ok?

2024-06-25 11:09 UTC, coroiu commented on apps/browser/src/vault/popup/components/vault/add-edit.component.ts
> +
You can also use `Utils.isNullOrWhitespace` or `Utils.isNullOrEmpty` if you want

Yes but I assume it would be assigned since the `Fido2Credential` is saved inside of the login?

2024-06-25 13:21 UTC, abergs commented on apps/browser/src/vault/popup/components/vault/add-edit.component.ts
> +
@coroiu So this would be Ok to approve?

2024-06-25 14:07 UTC, coroiu commented on apps/browser/src/vault/popup/components/vault/add-edit.component.ts
> +
I think so yes, but vault has the in-depth knowledge and needs to approve the changes :)

2024-06-25 14:14 UTC, gbubemismith commented on apps/browser/src/vault/popup/components/fido2/fido2.component.ts
>        // PM-4577 - https://github.com/bitwarden/clients/pull/8746
@coroiu, the comment is still needed. We just reverted from using user verification

2024-06-25 14:31 UTC, coroiu commented on apps/browser/src/vault/popup/components/vault/add-edit.component.ts
> +
I think so yes, but ultimately vault has the in-depth knowledge

2024-06-25 16:27 UTC, gbubemismith commented on apps/browser/src/vault/popup/components/vault/add-edit.component.ts
> +
@abergs this looks fine

2024-06-25 19:07 UTC, justindbaur requested changes

2024-06-25 19:07 UTC, justindbaur commented on apps/browser/src/vault/popup/components/vault/add-edit.component.ts
> +          (this.cipher.login.username === null || this.cipher.login.username === "")
```suggestion
          (this.cipher.login.username == null || this.cipher.login.username === "")
```

Kind of a nit but also kind of not because JavaScript is a great language lol.

2024-06-25 22:06 UTC, justindbaur approved these changes

2024-06-26 07:11 UTC, coroiu reviewed
Tests still failing

2024-06-26 08:54 UTC, abergs commented
Let's see if I managed to fix the tests and actually run them now ...

<img width="515" alt="image" src="https://github.com/bitwarden/clients/assets/357283/7acc92e3-53b5-4487-af2b-7850cf6ac57d">

2024-06-26 11:46 UTC, coroiu submitted a review, later dismissed

2024-06-27 12:59 UTC, gbubemismith approved these changes

2024-06-27 22:24 UTC, gbubemismith approved these changes

2024-06-28 11:30 UTC, coroiu approved these changes

2024-06-29 22:48 UTC, merged