[PM-7330] Create SetPasswordComponent (email verification)
bitwarden/clients pull request #9810
Opened 2024-06-24 19:30 UTC by rr-bw

- **setup SetPassword component**
- **accept query params**
- **add InputPasswordComponent to template**
- **add route**
- **add dynamic translation with org name**
- **feature flag route**
- **setup onInit**
- **add set password logic**
- **move to libs**
- **remove comments**

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-07-07 22:34 UTC, jlf0dev requested changes
Looking good! Left some changes I'd like to see before approving, but excited about this one.

2024-07-07 22:34 UTC, jlf0dev commented on libs/auth/src/angular/set-password-jit/set-password-jit.component.ts
> +          await this.policyApiService.getMasterPasswordPolicyOptsForOrgUser(autoEnrollStatus.id);
I think the auto enroll logic should belong in the service. I would pass the orgId to the service if present and resolve the auto enroll based on the existence.

2024-07-07 22:34 UTC, jlf0dev commented on libs/auth/src/angular/set-password-jit/default-set-password-jit.service.ts
> +  }
Even though I like the fact that this doesn't overcomplicate things, the service shouldn't be aware that there is client specific logic needed to be run. This also requires the caller to know to call this after the `setPassword`.

Instead, we should override the `setPassword` method in each client specific service, call the original method through `super`. Then add the client specific logic after.

2024-07-07 22:34 UTC, jlf0dev commented on libs/auth/src/angular/set-password-jit/set-password-jit.component.ts
> +    }
do we need to set `this.submitting = false` here?

2024-07-07 22:34 UTC, jlf0dev commented on libs/auth/src/angular/set-password-jit/set-password-jit.service.abstraction.ts
> +   */
`InputPasswordComponent` shouldn't be referenced from the service, it couples them too much for my liking. Please provide `@param` definitions and `@throws` as well.

2024-07-07 22:34 UTC, jlf0dev commented on libs/auth/src/angular/set-password-jit/set-password-jit.service.abstraction.ts
> +    passwordInputResult: PasswordInputResult,
I'd rather have a model created specifically for this service than reusing the `PasswordInputResult` here. Just to decouple things.

2024-07-07 22:34 UTC, jlf0dev commented on libs/auth/src/angular/set-password-jit/default-set-password-jit.service.ts
> +  ): Promise<void> {
I'd like to see some error handling in this service. We need to check input parameters for nullish values, as well as the result of external services we call while assembling request (within reason of course).

2024-07-07 22:38 UTC, jlf0dev commented
I also just noticed that the success toasts weren't showing in the videos, are those from the previous iteration of this PR?

Also going to tag @danielleflinn to see if she'd like to do a design review on this one, the MP policy requirements on the browser look a little...tight.

2024-07-10 00:11 UTC, rr-bw commented
> I also just noticed that the success toasts weren't showing in the videos, are those from the previous iteration of this PR?

Yes, those were previous videos. Here's an updated one.

https://github.com/bitwarden/clients/assets/102181210/f91d4187-924b-48e5-8a60-925418d7b843

2024-07-10 00:13 UTC, rr-bw commented
> I do agree that both the browser and desktop MP policy callouts look a bit off though. Is there a way we can fix the spacing between the leftmost edge of the bullets and the text?

@danielleflinn Here are updated screenshots for Desktop and Browser:

<img width="443" alt="desktop-list" src="https://github.com/bitwarden/clients/assets/102181210/31b46895-3f17-4bf3-a9f1-d26fc7162c76">

![browser-list](https://github.com/bitwarden/clients/assets/102181210/4471c1f6-23eb-4927-a1b8-c07fb58f6016)

2024-07-10 00:17 UTC, danielleflinn commented
@rr-bw looks great! Thank you

2024-07-11 15:39 UTC, jlf0dev commented on libs/auth/src/angular/set-password-jit/default-set-password-jit.service.ts
> +  masterPasswordPolicyOptions: MasterPasswordPolicyOptions;
I think i've steered you wrong here.

I missed that the orgId is retrieved from the autoEnroll response. I want to avoid having properties on the service, so I think we should move this back to the component. Sorry for the back and forth, this one is fully on me.

The real fix here is adding something to the server that can get us the orgId. Taking shortcuts like that always end up biting us later down the line.

2024-07-11 15:39 UTC, jlf0dev commented on libs/auth/src/angular/set-password-jit/default-set-password-jit.service.ts
> +    const keysRequest = new KeysRequest(newKeyPair[0], newKeyPair[1].encryptedString);
nit: this could probably be its own method

2024-07-11 19:35 UTC, rr-bw commented
@jlf0dev I addressed the recent feedback and also updated the PR description with a new screencast for each client. I am having one issue with Browser. As you can see in the video, setting the password works fine, but I cannot get the account to sync with the org and get access to the org. Here is the error I get:

![Screenshot 2024-07-03 at 11 38 35 AM](https://github.com/bitwarden/clients/assets/102181210/64e75ca2-07fd-40b5-a1eb-3574e0082796)

Am I potentially doing something wrong with service injection? I also tried adding the following to `main.background.ts`, but that did not help.

![Screenshot 2024-07-03 at 12 33 56 PM](https://github.com/bitwarden/clients/assets/102181210/c25e0521-37fe-4abc-8642-5334da1e6371)

2024-07-11 22:18 UTC, danielleflinn commented
@rr-bw I just noticed a few inconsistencies [with Figma](https://www.figma.com/design/81uGWWdQVAQfKDiR4qltoq/Email-Verification-%5BCreate-account%5D?node-id=2055-64010&t=IG5IIvVUNJEbh9G8-4). Are we able to make the title of this page "Join organization" (once we can support[ dynamic text](https://bitwarden.atlassian.net/browse/PM-9603) in the Anon layout title we can update this to "Join [Org name]" to match Figma), and can we change the CTA to "Create account"?

Also, I know in Figma we have the "Finishing joining org..." text in the content area; but what do you think about moving this to the Anon layout subtitle? 

If we are using this UI for another flow other than the Join organization we can probably keep the text the same, but if it is just for the Join Org flow, lets customize it a bit for the user.

2024-07-11 22:41 UTC, rr-bw commented
> I am having one issue with Browser. As you can see in the video, setting the password works fine, but I cannot get the account to sync with the org and get access to the org.

Issue fixed in a conversation with @jlf0dev

2024-07-12 19:06 UTC, rr-bw commented
> Are we able to make the title of this page "Join organization" (once we can support[ dynamic text](https://bitwarden.atlassian.net/browse/PM-9603) in the Anon layout title we can update this to "Join [Org name]" to match Figma), and can we change the CTA to "Create account"?
>
> Also, I know in Figma we have the "Finishing joining org..." text in the content area; but what do you think about moving this to the Anon layout subtitle?

@danielleflinn For sure, here's an updated screenshot:

![Screenshot 2024-07-12 at 11 59 51 AM](https://github.com/user-attachments/assets/2b58bdaf-82b0-4180-9628-41c11a1e0290)

2024-07-12 19:47 UTC, danielleflinn commented
@rr-bw Thank you this looks great! I'll make sure things are updated in Figma accordingly for QA

2024-07-18 13:23 UTC, jlf0dev submitted a review, later dismissed
Looks good! I had a couple thoughts but nothing blocking.

2024-07-18 13:23 UTC, jlf0dev commented on libs/auth/src/angular/set-password-jit/default-set-password-jit.service.ts
> +  async setPassword(credentials: SetPasswordCredentials): Promise<void> {
Another thought, it might be nice here to check the user decryption options and/or master key before doing anything to make sure that the user doesn't already have a password. Just as a nice sanity check.

2024-07-22 14:19 UTC, justindbaur approved these changes

2024-07-24 13:45 UTC, jlf0dev approved these changes

2024-07-24 14:40 UTC, justindbaur approved these changes

2024-07-25 14:42 UTC, merged