[PM-9170] combine library migrations
bitwarden/clients pull request #9812
Opened 2024-06-24 21:07 UTC by audreyality

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-9170

## 📔 Objective

Combines the following PRs to avoid DI failures due to misalignment between angular libraries and consuming apps:

* #9669
* #9666
* #9662
* #9638
* #9637

**Note:** All of the above PRs have already been reviewed. This PR just smashes them all together on the latest code from `main`, fixes the resulting conflicts, and reverts the factory rename in the CLI.

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-24 21:08 UTC, audrey-jensen commented
♻️ Sometimes I need to learn things the hard way.

2024-06-25 08:07 UTC, djsmith85 requested changes
Unfortunate that you had to bunch all changes into one PR again. Luckily the majority of changes are just changing imports.

Reviewed all changed files and besides two small things for future package-management, this looks good!

2024-06-25 08:07 UTC, djsmith85 commented on libs/tools/generator/extensions/src/index.ts
> +export { UsernameGenerationServiceAbstraction } from "./legacy-username";
This file needs to be deleted, as we now have individual packages for all extensions which provide their exports

2024-06-25 08:07 UTC, djsmith85 commented on libs/tools/generator/extensions/legacy/package.json
> +    "@bitwarden/generator-core": "file:../../core",
This change also needs to be done on the `history/package.json` and `navigation/package.json`

2024-06-25 14:50 UTC, jprusik submitted a review, later dismissed
LGTM for Autofill concerns

BIT run:
https://github.com/bitwarden/browser-interactions-testing/actions/runs/9663985511

2024-06-25 20:36 UTC, audrey-jensen commented on libs/tools/generator/extensions/src/index.ts
> +export { UsernameGenerationServiceAbstraction } from "./legacy-username";
Hmm. I did delete it, but the 🐱 came back, the very next merge...

2024-06-25 20:40 UTC, audrey-jensen commented on libs/tools/generator/extensions/legacy/package.json
> +    "@bitwarden/generator-core": "file:../../core",
Addressed in [6e91216](https://github.com/bitwarden/clients/pull/9812/commits/6e912161bd441ff3db5583efbf39cd4127bf4e18).

2024-06-25 20:46 UTC, djsmith85 approved these changes

2024-06-26 12:53 UTC, addisonbeck approved these changes

2024-06-26 14:13 UTC, jprusik approved these changes

2024-06-26 14:20 UTC, gbubemismith approved these changes

2024-06-26 14:55 UTC, audreyality commented
📝 Merged `main` to fix the macOS build errors.

2024-06-26 16:39 UTC, rr-bw approved these changes

2024-06-27 16:16 UTC, merged