[PM-8602-8603] Sticky search & filters
bitwarden/clients pull request #9846
Opened 2024-06-26 18:27 UTC by nick-livefront

## 🎟️ Tracking

[PM-8602](https://bitwarden.atlassian.net/browse/PM-8602)
[PM-8603](https://bitwarden.atlassian.net/browse/PM-8603)

## 📔 Objective

- Add `slot` to the popup page to allow for content to be shown above the scrollable area
  - A "bottom border" is shown only on scroll
  - Adds an example in storybook
- Implement this for the Search & Filters in the browser extension refresh

## 📸 Screenshots

|Storybook|Browser Extension|
|-|-|
|<video src="https://github.com/bitwarden/clients/assets/125900171/64ee30fb-d8da-4755-a768-f1ecccb072f0" />|<video src="https://github.com/bitwarden/clients/assets/125900171/41c56acc-068b-4238-8bf0-5981fd0b2887" />|

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-26 18:47 UTC, danielleflinn submitted a review, later dismissed

2024-07-02 18:09 UTC, nick-livefront commented
@willmartian @vleague2 When you have time, could you give this one a review?

2024-07-02 20:00 UTC, willmartian reviewed
1. I am seeing a double scrollbar in Storybook: 

![image](https://github.com/bitwarden/clients/assets/17113462/3b7f9ef8-bedb-46a2-99d6-b48a75ba2df1)

2. Is it intentional for the padding of the sticky area to be smaller than the rest of the main content? cc @bitwarden/dept-design 

![Screenshot 2024-07-02 at 3 55 44 PM](https://github.com/bitwarden/clients/assets/17113462/6c4f2112-cda5-4eb3-a5fd-03213a3c3922)

3. I wonder if it makes sense to add the slot to `popup-header` instead, since it is already sticky. What do you think?

2024-07-02 20:00 UTC, willmartian commented on apps/browser/src/platform/popup/layout/popup-layout.stories.ts
> +      <mock-search slot="above-scroll-area"></mock-search>
I am a nit picker when it comes to names: what do you think about "sticky-top"?

2024-07-02 21:15 UTC, danielleflinn commented
@willmartian 
1. I wasn't seeing the double scrollbar in Chromatic until I turned on my Mac's "Always show scrollbar" setting. 
2. Not intentional, the padding should be the same on the sticky search/filter area as the rest of the content.

2024-07-02 21:55 UTC, nick-livefront commented
> 1. I am seeing a double scrollbar in Storybook:

I also was not seeing this because of my mac settings 😅 I had to move some styles and elements around but I got there [3f7973a](https://github.com/bitwarden/clients/pull/9846/commits/3f7973a40e5309fbf27c136b6153de9ab8fda636)

> 2. Is it intentional for the padding of the sticky area to be smaller than the rest of the main content? cc @bitwarden/dept-design

Fixed! [911fb3c](https://github.com/bitwarden/clients/pull/9846/commits/911fb3c076e3b947e70c9b2910c98530b959d22a)

> 3. I wonder if it makes sense to add the slot to `popup-header` instead, since it is already sticky. What do you think? ("No" is an okay answer!)

I would lean towards no because they semantically are different and it would add extra logic to the header component that I feel is unrelated. I'm not super passionate on that stance though so I can go another route! I did have to sadly move the non scrollable content out of the `main` [3f7973a](https://github.com/bitwarden/clients/pull/9846/commits/3f7973a40e5309fbf27c136b6153de9ab8fda636) so scrolling would work how I wanted. So maybe that is more of an argument it should go in the header.

2024-07-03 12:57 UTC, vleague2 requested changes
Could you also update the popup layout mdx documentation for Storybook to document the new slot and its usage?

2024-07-03 12:57 UTC, vleague2 commented on apps/browser/src/platform/popup/layout/popup-page.component.html
> +<div #nonScrollable>
I think technically for accessibility, all content is supposed to be contained within a landmark. So maybe a `main` can wrap all of this and the existing `main` could just become a div so that the styles are all retained in the correct places.

2024-07-16 15:53 UTC, nick-livefront commented on apps/browser/src/platform/popup/layout/popup-page.component.html
> +<div #nonScrollable>
Great idea, it took some styling tweaks! [4b3e31a](https://github.com/bitwarden/clients/pull/9846/commits/4b3e31a6ec7f6bf8cca4fbb71411386b7369d2da)

2024-07-17 14:00 UTC, vleague2 approved these changes
The slot documentation and the part you added to the existing stories is good with me! Thanks!

2024-07-23 17:40 UTC, shane-melton approved these changes
Vault changes look good!

2024-07-24 02:07 UTC, merged