[PM-8381] Assign collections
bitwarden/clients pull request #9854
Opened 2024-06-27 14:38 UTC by nick-livefront

Stacked on top of @gbubemismith's https://github.com/bitwarden/clients/pull/9507 and the same PR as #9757 but with a clean git history 😓 

## 🎟️ Tracking

[PM-8381](https://bitwarden.atlassian.net/browse/PM-8381)

## 📔 Objective

- Add "Assign Collections" screen
- Moving a cipher into an organization and assigned to at least one collection
- Reassigning collections within an organization
- The select & multi-select that are shown in the designs do not appear to be available yet. 

## 📸 Screenshots

|Move cipher to org|reassign collections|
|-|-|
| <video src="https://github.com/bitwarden/clients/assets/125900171/899dd0ae-812a-4f94-965c-f5531c7c3fce" />|<video src="https://github.com/bitwarden/clients/assets/125900171/0eafe48a-1ebf-48f6-8693-ecb84ac44b1f" />|

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

[PM-8381]: https://bitwarden.atlassian.net/browse/PM-8381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-06-27 22:26 UTC, Jingo88 submitted a review, later dismissed

2024-07-01 18:19 UTC, shane-melton requested changes
This looks great and I really like how straightforward it became due to the re-use of the shared assign component. Only 2 minor nits and one potential suggestion/thought if you feel its appropriate here and want to give it a go.

2024-07-01 18:19 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/assign-collections/assign-collections.component.ts
> +      takeUntilDestroyed(),
⛏️ We don't technically need this `takeUntilDestroyed()` since we never subscribe to it directly.

2024-07-01 18:19 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/assign-collections/assign-collections.component.ts
> +      switchMap(({ cipherId }) => this.cipherService.get(cipherId)),
🌱  We should really have a method on the `cipherService` to get a decrypted cipher instead of having to go through this process every time. Ideally we'd use the existing `cipherView$` and its cache if possible as well.

2024-07-01 18:23 UTC, shane-melton commented on apps/browser/src/vault/popup/components/vault-v2/assign-collections/assign-collections.component.ts
> +      switchMap(({ cipherId }) => this.cipherService.get(cipherId)),
Created a tech debt ticket for now: [PM-9420](https://bitwarden.atlassian.net/browse/PM-9420)

2024-07-01 18:53 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault-v2/assign-collections/assign-collections.component.ts
> +      takeUntilDestroyed(),
👍 [4cff1b2](https://github.com/bitwarden/clients/pull/9854/commits/4cff1b28aff7dba4a85e1fdd48d96cf601ca3721)

2024-07-01 18:53 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault-v2/assign-collections/assign-collections.component.html
> +      bitFormButton
👍 [2e4280e](https://github.com/bitwarden/clients/pull/9854/commits/2e4280e8c82a3aeeaee1559f4ab550dc2ed18d74)

2024-07-01 18:54 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault-v2/assign-collections/assign-collections.component.html
> +      (formDisabled)="disabled = $event"
I think that's worth it! Because it would refactor @gbubemismith's work and mine I'll open a separate PR so it can be reviewed individually.

2024-07-01 18:57 UTC, shane-melton submitted a review, later dismissed
This looks good to go! I'd suggest holding off merging until @gbubemismith's parent PR is merged as its currently undergoing QA. (unless you feel differently @gbubemismith)

2024-07-01 19:27 UTC, nick-livefront commented
> This looks good to go! I'd suggest holding off merging until @gbubemismith's parent PR is merged as its currently undergoing QA. (unless you feel differently @gbubemismith)

I'll wait to merge in until after @gbubemismith's work is merged that way we don't have a single huge PR.

2024-07-01 19:34 UTC, nick-livefront commented on apps/browser/src/vault/popup/components/vault-v2/assign-collections/assign-collections.component.html
> +      (formDisabled)="disabled = $event"
PR: https://github.com/bitwarden/clients/pull/9899

2024-07-12 21:36 UTC, gbubemismith commented
@nick-livefront I merged mine to the main; this should be good once the merge conflicts are addressed.

2024-07-16 14:04 UTC, nick-livefront commented
@Jingo88 @shane-melton Rebased on top of `main` after @gbubemismith's merge

2024-07-17 18:31 UTC, Jingo88 approved these changes

2024-07-18 13:53 UTC, merged