Update the README to mention the discrepancy with homebrew
bitwarden/clients pull request #9856
Opened 2024-06-27 15:31 UTC by addisonbeck

## 🎟️ Tracking

## 📔 Objective

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-27 19:44 UTC, joseph-flinn approved these changes

2024-06-27 20:00 UTC, patrick-bitwarden requested changes

2024-06-27 20:00 UTC, patrick-bitwarden commented on apps/cli/README.md
> +  > Homebrew pulls the CLI's GPL build, and is missing some enterprise-grade features.
Let's change this to "Homebrew pulls the CLI's GPL build and does not include device approval commands for Enterprise SSO customers." 
This way we can be transparent about what's not included. Down the road, if we have additional CLI features that are licensed under the bitwarden license, we can explore a central location with the differences that we link to from here, so that we're not having to maintain the list in multiple places and so on.

2024-06-27 20:04 UTC, addisonbeck commented on apps/cli/README.md
> +  > Homebrew pulls the CLI's GPL build, and is missing some enterprise-grade features.
Update as written on https://github.com/bitwarden/clients/pull/9856/commits/de5cb9de636dc725aba1a8869759c26261cf1993

Screenshot:

<img width="1030" alt="Screenshot 2024-06-27 at 4 03 32 PM" src="https://github.com/bitwarden/clients/assets/15897251/167e8a83-7f79-4b8e-b476-940bb53e6d61">

2024-06-28 12:58 UTC, patrick-bitwarden approved these changes

2024-06-28 14:59 UTC, merged