[PM-9317] fix duo subscriptions and org vs individual duo setup
bitwarden/clients pull request #9859
Opened 2024-06-27 20:16 UTC by jlf0dev

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-9317
## 📔 Objective

We weren't sending the organization id or the correct two factor type to the dialog when configuring Organization Duo. This fixes that and adds some better handling of the dialog callbacks.
## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-07-01 14:52 UTC, JaredSnider-Bitwarden requested changes

2024-07-01 14:52 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/admin-console/organizations/settings/two-factor-setup.component.ts
> +          .pipe(first(), takeUntil(this.destroy$))
❓ why have a `takeUntil` when there is a `first`?  [First](https://rxjs.dev/api/operators/first) will complete after the first emission.

2024-07-01 14:52 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/admin-console/organizations/settings/two-factor-setup.component.ts
> +          .pipe(first(), takeUntil(this.destroy$))
There are several other places where this comment applies as well.

2024-07-01 15:52 UTC, JaredSnider-Bitwarden commented on apps/web/src/app/admin-console/organizations/settings/two-factor-setup.component.ts
> +          .pipe(first(), takeUntil(this.destroy$))
Nvm. Per Jake: " if the dialog is closed and component left the subscription will be kept alive. Basically, if there’s no emission I wanted it to still be destroyed with the component"

2024-07-01 18:55 UTC, JaredSnider-Bitwarden approved these changes

2024-07-02 01:15 UTC, eliykat approved these changes
I think it would be preferable for the 2FA dialogs to call `dialogRef.close` with a result so that the `TwoFactorSetupComponent` can just `await lastValueFrom(dialogRef.closed)`. That way you don't have to define your own `EventEmitter` and manage your subscription etc. However that is non-blocking feedback.

2024-07-02 14:44 UTC, merged