[PM-8525] Edit Card
bitwarden/clients pull request #9901
Opened 2024-07-01 21:47 UTC by nick-livefront

Stacked on top of @shane-melton's https://github.com/bitwarden/clients/pull/9758 to integrate with `CipherFormConfigService`

## 🎟️ Tracking

[PM-8525](https://bitwarden.atlassian.net/browse/PM-8525)

## 📔 Objective

Add Card Details section for editing a card cipher
- Slight changes from the current implementation:
  - Expiration year is now a numerical input to limit the input to numerical values
  - The year input doesn't take up as much vertical space as the month select. I manually applied a height here because the `bitInput` seems to override all classes applied to it's host element.

## 📸 Screenshots

|Edit Card|
|-|
|<video src="https://github.com/bitwarden/clients/assets/125900171/f6595f05-5466-4b9f-a84e-dda935741b47" />|

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-07-01 22:51 UTC, shane-melton requested changes
Nice work! I think this came together really nicely with the cipher form abstraction.

I see one issue with regards to `partial-edit` mode we'll need to address. Otherwise, just a few other comments/questions.

2024-07-01 22:51 UTC, shane-melton commented on libs/vault/src/cipher-form/components/card-details-section/card-details-section.component.html
> +        <!-- `ngStyle` to force the number input to be the same height as the expiration month select. -->
❓ 💭 Should we be setting a fixed height for the `bit-select` and/or `bitInput` at the CL level so that they always match? It seems odd that they would have a different height, but I'm guessing it's never come up before since we don't normally have two inputs like this inline together. @willmartian Any other thoughts or ideas to address this?

Regardless, I'm not 100% certain the `ngStyle` will work in production as I somewhat recall running into CSP issues when trying to set styles explicitly using the `style` attribute.

2024-07-01 22:51 UTC, shane-melton commented on libs/vault/src/cipher-form/components/card-details-section/card-details-section.component.ts
> +  @ViewChild("yearInput") yearInput: ElementRef<HTMLInputElement>;
❓ This looks unused, do we need it?

2024-07-01 22:51 UTC, shane-melton commented on libs/vault/src/cipher-form/components/card-details-section/card-details-section.component.ts
⚠️ We need a means of disabling all of these child form controls with the cipher form is in `partial-edit` mode. That mode only allows the folder and favorite status to be modified in the item details section. All other sections should be disabled. (You can enter this state by trying to edit that is in a View only collection)

Some possible options could be to add an `@Input() disabled` property or pass in the `config` object and check the `mode` in `ngOnInit()`.

2024-07-01 22:51 UTC, shane-melton commented on libs/vault/src/cipher-form/components/card-details-section/card-details-section.component.ts
> +type CardDetailsForm = {
❓ 💭 I'm not opposed to keeping this type, but I'm also not certain we're gaining anything by having it. It is only used by the `formBuilder` below and it doesn't inherit any `CardView` properties. To me, it feels like we're just writing out the shape of the form in two places that have to be kept in sync.

2024-07-02 02:50 UTC, nick-livefront commented on libs/vault/src/cipher-form/components/card-details-section/card-details-section.component.html
> +        <!-- `ngStyle` to force the number input to be the same height as the expiration month select. -->
💯 I agree, it feels odd. I was using `line-height` at first because it would be more universal across zoom/font sizes. But the value to match it was `1.602` or something very specific which felt unintuitive. 

Brainstorming..
- Would we still run into CSP issue if we use JS to set the style attribute of the element?
- I could check with Danielle about moving these to their own line for now. I assume they'll be replaced by new CL components to match designs eventually.
- We could alter the `bitInput` to allow for classes. If I'm misinterpreting how this works, please correct me!

2024-07-02 03:03 UTC, nick-livefront commented on libs/vault/src/cipher-form/components/card-details-section/card-details-section.component.ts
> +type CardDetailsForm = {
> I'm also not certain we're gaining anything by having it

With all of my default values are `null` the form infers the type of each control as `unknown` which causes the need to narrow variables further down in the chain to it's proper type. That is what caused me to separate out the type. I could initialize the form controls to empty string but that feels like "a value" versus "no value" discussion. Would that break any logic by passing empty strings for empty fields? 

![Screen Shot 2024-07-01 at 21 58 42 PM](https://github.com/bitwarden/clients/assets/125900171/9f74145f-a315-479d-ba8f-7c623d7be495)


> it doesn't inherit any CardView properties

I agree with you here, I created an invisible dependency. I'll add references to the `CardView` type. But if we decide to go a different way in the first  thread ☝️ I'll remove it! [b94f155](https://github.com/bitwarden/clients/pull/9901/commits/b94f1552a65e39088c736716cb61cea8c094b6ed)

2024-07-02 03:04 UTC, nick-livefront commented on libs/vault/src/cipher-form/components/card-details-section/card-details-section.component.ts
> +  @ViewChild("yearInput") yearInput: ElementRef<HTMLInputElement>;
We do not! That was leftover from a previous iteration. Removed: [257af49](https://github.com/bitwarden/clients/pull/9901/commits/257af49c4325e132b6b1e7f73cdc1653138593ad)

2024-07-02 03:25 UTC, nick-livefront commented on libs/vault/src/cipher-form/components/card-details-section/card-details-section.component.ts
🙈 I asked about this specifically and forgot about it. [566105b](https://github.com/bitwarden/clients/pull/9901/commits/566105b9ff6f2fe035b3d5423cb59b51664dd6ec)

Would the `view` mode be applicable as well?

2024-07-02 17:26 UTC, shane-melton commented on libs/vault/src/cipher-form/components/card-details-section/card-details-section.component.ts
The cipher form does not have a `view` mode so we should be good to go! The view portion will be its own component that Jason is working on in #9723.

2024-07-02 17:59 UTC, shane-melton commented on libs/vault/src/cipher-form/components/card-details-section/card-details-section.component.ts
> +type CardDetailsForm = {
Ah, I see 🤔 

What would you think about putting `null as string` in the form builder to get the proper type?

As for doing the `CardView["number"]` type referencing, I don't see a problem with it. I was originally trying to refer to the form fields possibly not having same property names as `CardView` which could cause a problem when you do `Object.assign(this.cardView, {...<FormValues>...})` below when patching. 

But, you're already building an anonymous object with the correct `CardView` properties when assigning, so I don't think we need the from group to have the exact same names necessarily. (e.g. `expYear` differs from `expirationYear` already)

2024-07-02 18:04 UTC, shane-melton commented on libs/vault/src/cipher-form/components/card-details-section/card-details-section.component.html
> +        <!-- `ngStyle` to force the number input to be the same height as the expiration month select. -->
Oh, I had not considered that the new CL components may correct this for us, so perhaps we don't need to do anything custom here or change the layout at this time. 

@willmartian and/or @vleague2 I'm curious what you of think about this?

2024-07-02 20:21 UTC, willmartian commented on libs/vault/src/cipher-form/components/card-details-section/card-details-section.component.html
> +        <!-- `ngStyle` to force the number input to be the same height as the expiration month select. -->
This is a bug. They should have the same height by default. I created [this issue](https://bitwarden.atlassian.net/browse/CL-323) to track that and linked PM-8525 as related.

2024-07-02 20:41 UTC, shane-melton commented on libs/vault/src/cipher-form/components/card-details-section/card-details-section.component.html
> +        <!-- `ngStyle` to force the number input to be the same height as the expiration month select. -->
Thanks Will!

2024-07-02 21:56 UTC, nick-livefront commented on libs/vault/src/cipher-form/components/card-details-section/card-details-section.component.html
> +        <!-- `ngStyle` to force the number input to be the same height as the expiration month select. -->
@shane-melton @willmartian Ditto! Thanks, Will!

With that bug filed I'm going to remove this hardcoded height

2024-07-02 22:42 UTC, nick-livefront commented on libs/vault/src/cipher-form/components/card-details-section/card-details-section.component.ts
> +type CardDetailsForm = {
I don't mind the `as string`, I included a note in the JSDoc above it to explain why. [95152e6](https://github.com/bitwarden/clients/pull/9901/commits/95152e6a51fdaefaa6e937aed150a1069235ffa8)

2024-07-02 22:42 UTC, nick-livefront commented on libs/vault/src/cipher-form/components/card-details-section/card-details-section.component.html
> +        <!-- `ngStyle` to force the number input to be the same height as the expiration month select. -->
Removed [5bd213c](https://github.com/bitwarden/clients/pull/9901/commits/5bd213ccbfd01d98ceb22fdb00bacb231c762103)

2024-07-02 22:42 UTC, nick-livefront commented
@shane-melton I rebased on top of main after your merge of https://github.com/bitwarden/clients/pull/9758

2024-07-02 22:56 UTC, shane-melton approved these changes
Looks great and ready to go! Nice work!

2024-07-03 01:31 UTC, merged