Add tests for undefined state values
bitwarden/clients pull request #9910
Opened 2024-07-02 13:51 UTC by coroiu

## 🎟️ Tracking

## 📔 Objective

This PR improves `FakeStorageService` to better emulate `ElectronStorageService` which throws error when saving undefined values in the state.

As a result migrations have been updated to avoid this behavior.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-07-02 15:24 UTC, justindbaur requested changes

2024-07-02 15:28 UTC, coroiu commented on libs/common/src/platform/state/implementations/default-single-user-state.ts
> +    }
Yeah I'm definitely not sure on the approach here, that's why I wanted to create a separate ticket for this PR since it might involve some more work and discussions. 

I've also been thinking if we should instead convert `set(key, undefined)` calls in the `ElectronStorageService` to `remove(key)`

2024-07-02 18:06 UTC, justindbaur commented on libs/common/src/platform/state/implementations/default-single-user-state.ts
> +    }
There is precedence in doing exactly that actually.

https://github.com/bitwarden/clients/blob/9294a4c47e52d7d5d55260ecf9a0e4101acabafa/apps/browser/src/platform/services/abstractions/abstract-chrome-storage-api.service.ts#L86-L89

I would have no problem with doing the same exact think in `ElectronStorageService`.

2024-07-03 08:18 UTC, coroiu commented on libs/common/src/platform/state/implementations/default-single-user-state.ts
> +    }
Awesome, I'll update the PR with this fix then!

2024-07-03 12:15 UTC, justindbaur approved these changes
Looks fantastic, thank you!

2024-07-03 14:06 UTC, merged