[PM-5165][PM-8645] Migrate password strength component
bitwarden/clients pull request #9912
Opened 2024-07-02 14:48 UTC by djsmith85

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-5165
https://bitwarden.atlassian.net/browse/PM-8645
## 📔 Objective

Create a new password-strength component using the ProgressComponent from the Component library.

The existing component was kept to not break visual styles on non-CL-pages. A follow-up to this is to replace all existing usages with the new component.

## 📸 Screenshots

### Before
![image](https://github.com/bitwarden/clients/assets/2670567/2c72b253-c182-401a-bde2-0cd127f1e7de)
![image](https://github.com/bitwarden/clients/assets/2670567/486e2d87-c297-480f-a66b-d224eb0b9b6d)

### After
![image](https://github.com/bitwarden/clients/assets/2670567/0f89f9ec-49ec-4237-94c5-6bc95e2ec397)
![image](https://github.com/bitwarden/clients/assets/2670567/ab030609-aae6-496c-93be-b32fbb5bc7e5)

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-07-03 14:39 UTC, audreyality requested changes
⚠️ - requested change.

All other comments are optional.

2024-07-03 14:39 UTC, audreyality commented on libs/angular/src/tools/password-strength/password-strength-v2.component.ts
⚠️ Since this file is net-new, it should be unit-tested.

2024-07-03 14:39 UTC, audreyality commented on libs/angular/src/tools/password-strength/password-strength-v2.component.ts
> +    const masterPassword = password;
⛏️  This variable can be eliminated

2024-07-03 14:39 UTC, audreyality commented on libs/angular/src/tools/password-strength/password-strength-v2.component.ts
> +    this.passwordScoreColor.emit({ color: color, text: text });
🤔 This emission appears unnecessary. What is its purpose?

2024-07-03 14:39 UTC, audreyality commented on libs/angular/src/tools/password-strength/password-strength-v2.component.ts
> +  color: string;
⛏️ Seems like the type of this value should be `BackgroundTypes`.

2024-07-03 14:39 UTC, audreyality commented on libs/angular/src/tools/password-strength/password-strength-v2.component.ts
> +  @Output() passwordScoreColor = new EventEmitter<PasswordColorText>();
⛏️ Inputs and outputs should be documented.

2024-07-09 13:11 UTC, djsmith85 commented on libs/angular/src/tools/password-strength/password-strength-v2.component.ts
> +  @Output() passwordScoreColor = new EventEmitter<PasswordColorText>();
Addressed with 1829b2a1cd84e84914cdd01aad78371344832045

2024-07-09 13:12 UTC, djsmith85 commented on libs/angular/src/tools/password-strength/password-strength-v2.component.ts
> +    const masterPassword = password;
Addressed with 2f375c52a4fe12422f6653f4409da8ed28c1ce7b

2024-07-09 13:12 UTC, djsmith85 commented on libs/angular/src/tools/password-strength/password-strength-v2.component.ts
> +  color: string;
Addressed with 74043bc24743edc13985cc008a57124d66a4523d

2024-07-09 13:13 UTC, djsmith85 commented on libs/angular/src/tools/password-strength/password-strength-v2.component.ts
It's a copy of the original component, just using the bit-progress from CL instead. 
I agree though that this should have unit tests: Added with c40c38d12d7bd2b8235b9b5b24e4514eda8b25ac

2024-07-09 13:20 UTC, djsmith85 commented on libs/angular/src/tools/password-strength/password-strength-v2.component.ts
> +    this.passwordScoreColor.emit({ color: color, text: text });
The emission is also part of the original component and is used for example with the [register component](https://github.com/bitwarden/clients/blob/1cb063689fd9cfc187bfd5df2b1e19c78ab23a40/apps/browser/src/auth/popup/register.component.html#L26-L31)
Displaying the strength text and color might be redundant but just aiming to keep existing functionality. Might get removed after say the extension-refresh.
Removed `setPasswordScoreText` and renamed the emitter to `passwordScoreTextWithColor`

2024-07-09 13:44 UTC, audreyality commented on libs/angular/src/tools/password-strength/password-strength-v2.component.ts
> +  color: string;
👍🏻 Typing the timeout value at the same time.

2024-07-09 13:45 UTC, audreyality approved these changes

2024-07-10 14:59 UTC, merged